### ISSUE TITLE
Feature request - Add prices in BTC/LTC per item in invoice 

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#100]
- If possible show prices of individual items in btc in the invoice on the server (this is useful when we have to issue a refund for 1/5 items, we can see the amount of btc paid on that date without having to manually calculate it).

**Comment by NicolasDorier** [comment]
but you have a link in the invoice page to the order, just clicking on it should bring you the full details of your order right?

**Comment by bitcoinshirt** [comment]
@NicolasDorier Are you referring to the link to the order inside Woo? If so it does not show price per item in Bitcoin, only in USD. 
![screenshot from 2018-04-03 12-09-11](https://user-images.githubusercontent.com/36959754/38243457-19f1e184-3727-11e8-9bc8-7c1de88818d0.png)

For us it would be useful to have price per item not only total invoice price. Would be useful for refunds.

**Comment by NicolasDorier** [comment]
if there is two payment method, bitcoin and litecoin, which one to show? all of them?

**Comment by bitcoinshirt** [comment]
Well is it possible to differentiate if it's paid with btc show btc if it's shown with ltc show ltc?
For example, if we have a refund request for the item 15 days ago, I can go to the invoice and see how much for each of the item(s) customer paid and manually refund them the same amount they paid. Right now we're doing it manually, but it would be way better to have price per item in crypto.

**Comment by bitcoinshirt** [comment]
If there's a way to show price per item in cryptocurrency in which customer paid (backend invoice) besides in fiat which is already implemented on the frontend it would be  great.

**Comment by bitcoinshirt** [comment]
I'm closing this issue now for two reasons:

1. There hasn't been much activity about it.
2. It's slightly related to  #140 

It's too bad, for me personally, this would make refunds for particular items much easier. 
Imagine having an invoice with:
- 1x Apple 25$
- 2x Orange 50$
- 1x Candy 25$
- TOTAL 100$ - 0.02 BTC

Customer paid in Bitcoin and want's a refund for 1x candy. Unfortunately, I don't have a record how much 1 candy is in BTC to refund right away, as the invoice doesn't show this info, so I have to find price in fiat for 1 candy, see the rate at that day, and calculate the amount to refund to my customer.
