### ISSUE TITLE
Paying Expired Lightning Invoices

### ISSUE THREAD

**Issue by jackeveritt** [btcpayserver/btcpayserver#1002]
**Describe the problem/bug**
In the Eclair wallet (version 0.4.8, android), it is possible to pay an invoice when it expires.  

If you pay an expired invoice, the payment completes on the LND node and shows as settled.  However, BTCPayServer shows the invoice as expired, but the 'Due' column still shows that the payment hasn't been received.  

The completed payment is also missing from the CSV download.

**Your environment**
Version of BTCPay Server: v1.0.3.127
Deployment method: LunaNode

**To Reproduce**
1. Open a lightning invoice created via BTCPayServer in Eclair wallet
2. Tap on the amount field to show the keyboard. This will keep that app in focus and stop the interface refreshing. 
3. Wait for the invoice to expire and pay it
4. After paying view the BTCPayServer Invoices and view the Ride the Lightning invoices.  You see the descrepency. 

See attachments. The expirey was set to 2 minutes, the payment was completed 3 minutes after creation.

**Expected behavior**
I expect that BTCPayServer 'Due' column in the invoices should be 0 because the invoice was paid.  I also expect although the CSV invoices export file to contain the invoice.

**Actual behavior**
The invoice still apears as Due and doesnt appear in the CSV.

![BTCPayServer](https://user-images.githubusercontent.com/1027263/64008381-ecd66e00-cb0d-11e9-8ded-f331fb6190e4.png)
![Payment Pending RTL](https://user-images.githubusercontent.com/1027263/64008385-eea03180-cb0d-11e9-9c45-a17662d2a4da.png)
![Payment Settled After Expiry RTL](https://user-images.githubusercontent.com/1027263/64008390-f069f500-cb0d-11e9-9524-d875ccf12b1e.png)

**Comment by NicolasDorier** [comment]
@jackeveritt why would LND accept a payment after the payment has been done? May it be a bug in LND?

**Comment by jackeveritt** [comment]
There are two causes;
1. LND accepts payments after expiration
2. Eclair wallet allows paying after expiration

BTCPayServer doesn't monitor unpaid invoices indefinately.  This causes these issues;
1. If the customer pays after expiry, the merchant will not see the payment in BTCPayServer (however, it does show on Ride The Lightning connected to LND)
2. If the merchant uses the accounting tools in BTCPayServer, payments made after expiry will not be included.
3. If the merchant allows 3rd parties to use their BTCPayServer, they my need offer support for this issue.

The Bolt 11 spec states:

> A payer:
>     after the timestamp plus expiry has passed:
>         SHOULD NOT attempt a payment.
> A payee:
>     after the timestamp plus expiry has passed:
>         SHOULD NOT accept a payment.

(Source: https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md#payer--payee-requirements)

Alex Bosworth from Lightning Labs explained this to me as:

> Although "SHOULD NOT" is in capitals, it doesn't mean "Must Not". 
> LND will still accept the invoice even if it’s marked expired, and in any case it’s not safe for wallets to assume the expiry date means the invoice won’t settle.

He pointed out that an invoice might be paid just before expiry but received after the expirey date. Payments are not instantaneous.

Alex suggested rejecting payments from expired invoices is a feature being discussed.  

He suggestted the 'hodl' invoices give more control on payments.
More info: https://github.com/lightningnetwork/lnd/pull/2022

So I have not reported this as a bug to LND, as it seems it's working as intended.  It's just not well communicated that its not safe to rely expiry to assume the invoice will never be paid.

In regards to Eclair, I do not believe being able to pay an expired invoice was their intention and I have reported it as a bug to them.

**Comment by jackeveritt** [comment]
A potential solution is to use a HODL invoice.  These appear the same to the payer, but the payee can cancel:

> Settling or canceling
> 
> Once the htlc has been accepted in lnd, it is held there until either a cancel or settle rpc is received. Both can be issued through lncli:
> lncli cancelinvoice <hash>
> or
> lncli settleinvoice <preimage>

source: https://github.com/lightningnetwork/lnd/pull/2022

When BTCPayServer stops monitoring an invoice, it could cancel it.

**Comment by Kukks** [comment]
> A potential solution is to use a HODL invoice. These appear the same to the payer, but the payee can cancel:
> 
> > Settling or canceling
> > Once the htlc has been accepted in lnd, it is held there until either a cancel or settle rpc is received. Both can be issued through lncli:
> > lncli cancelinvoice 
> > or
> > lncli settleinvoice
> 
> source: [lightningnetwork/lnd#2022](https://github.com/lightningnetwork/lnd/pull/2022)
> 
> When BTCPayServer stops monitoring an invoice, BTCPayServer could send a cancel command.
> Whilst watching the invoice, it can execute a settle command if invoice was paid before expiry.
> 
> Here is some example code:
> Note: Requires lnd built with invoicesrpc
> 
> Creating a hodl invoice:
> https://github.com/alexbosworth/ln-service/blob/master/invoices/create_hodl_invoice.js#L89
> 
> Cancelling:
> https://github.com/alexbosworth/ln-service/blob/master/invoices/cancel_hodl_invoice.js
> 
> Settling
> https://github.com/alexbosworth/ln-service/blob/master/invoices/settle_hodl_invoice.js

We don't want to have to care for specific implementation features, there should be no difference in BTCPay if they are using LND, Eclair, Clightning, ptarmigan, etc

**Comment by NicolasDorier** [comment]
A solution is to fix it on our fork. I don't want to waste time on it though.
Maybe somebody can open an issue on LND so they fix it?

**Comment by jackeveritt** [comment]
> > A potential solution is to use a HODL invoice. These appear the same to the payer, but the payee can cancel:
> > > Settling or canceling
> > > Once the htlc has been accepted in lnd, it is held there until either a cancel or settle rpc is received. Both can be issued through lncli:
> > > lncli cancelinvoice
> > > or
> > > lncli settleinvoice
> > 
> > 
> > source: [lightningnetwork/lnd#2022](https://github.com/lightningnetwork/lnd/pull/2022)
> > When BTCPayServer stops monitoring an invoice, BTCPayServer could send a cancel command.
> > Whilst watching the invoice, it can execute a settle command if invoice was paid before expiry.
> > Here is some example code:
> > Note: Requires lnd built with invoicesrpc
> > Creating a hodl invoice:
> > https://github.com/alexbosworth/ln-service/blob/master/invoices/create_hodl_invoice.js#L89
> > Cancelling:
> > https://github.com/alexbosworth/ln-service/blob/master/invoices/cancel_hodl_invoice.js
> > Settling
> > https://github.com/alexbosworth/ln-service/blob/master/invoices/settle_hodl_invoice.js
> 
> We don't want to have to care for specific implementation features, there should be no difference in BTCPay if they are using LND, Eclair, Clightning, ptarmigan, etc

If someone sends me an invoice from those implementations, I can pay it after expiry to check that if they also allow the payment.

**Comment by pavlenex** [comment]
@jackeveritt I use c-lightning on [my donation page,](https://pavlenex.com/) so you can create invoices there and test it.

**Comment by NicolasDorier** [comment]
@jackeveritt have you open an issue on eclair wallet so people don't pay expired invoices as well?

**Comment by jackeveritt** [comment]
@NicolasDorier ACINQ/eclair-mobile#209

**Comment by jackeveritt** [comment]
@pavlenex thanks for the link.  I did one normal payment of 1043 sats to confirm the routing was ok. I tried 1243 and 1252 for expired invoices, I believe C-Lightning rejected expired payments.

Error "incorrect payment amount or unknown payment hash" 
Type "RemoteFailure"

**Comment by NicolasDorier** [comment]
I posted on an LND issue.

**Comment by pavlenex** [comment]
Closing this one as it seems to be addressed in LND repo.
