### ISSUE TITLE
[Crowdfund app] Show raised amount tooltip only if content in the tooltip is different from what's below it

### ISSUE THREAD

**Issue by bolatovumar** [btcpayserver/btcpayserver#1003]
**Describe the problem/bug**
As mentioned [here](https://github.com/btcpayserver/btcpayserver/issues/926#issuecomment-524235018) we should show the raised amount tooltip only if the content in the tooltip is different from what you see right below it.

![63580381-5cdc7580-c59d-11e9-861d-4a5a03679e09](https://user-images.githubusercontent.com/1934678/64057784-2a5ee980-cb56-11e9-944c-86d03a13a091.png)

So, what you see above is 3 BTC raised and 3 BTC again in the tooltip. This shouldn't happen. The tooltip should only show up if the tooltip content has something additional to show.

**Your environment**
* Version of BTCPay Server: v1.0.3.127

**To Reproduce**
1. Create a crowdfunding app
2. Raise some on-chain BTC 
3. Hover over the raised amount
4. See how the tooltip is exactly the same content as what's below it

**Expected behavior**
Don't show the tooltip if it doesn't provide any additional information

**Actual behavior**
Shows the tooltip even if the info in it is exactly the same as what's below it

**Comment by radWorx** [comment]
@bolatovumar , what would the tooltip tip if its not giving a tip about the content?
Unintended, riddle...

Perhaps that tooltip is not necessary at all?

**Comment by bolatovumar** [comment]
@radWorx as far as I remember it, the crowdfund app can specify the raise amount in any supported crypto or fiat. People can contribute in any supported crypto, both on-chain and with LN. The raised amount shows the total amount raised while the tooltip shows what the total amount is made up of (for example, 1 BTC, 0.25 BTC through lightning, 2 LTC and 3 DOGE).
