### ISSUE TITLE
Removing a description from the PoS item adds `null`/ `undefined` text

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1008]
**Describe the problem/bug**
When you're editing PoS item on the front-end, click on the `edit` button and remove description from the description field of the item. Save. It adds `null` text which is not saved, but if you're changing a price next time, for example, you save, then the `null` is saved and display.

**Your environment** 
* Version of BTCPay Server: v1.0.3.127
* Deployment method: Docker

**To Reproduce**
1. Go to PoS App
2. Click on `Edit` button
3. Remove description from the item description field
4. See the `null` being added but not yet saved.
5. When you save changes for the second time, it of course displays `null`

**Expected behavior**
When item description is removed, it should not display anything in txt format.

**Actual behavior**
Null text is added when you remove the description.

**Screenshots/Links**
![Screen Shot 2019-09-03 at 22 27 24](https://user-images.githubusercontent.com/36959754/64207077-2a375480-ce9c-11e9-81bc-2699c13c07be.png)

![2019-09-03_22-45-10](https://user-images.githubusercontent.com/36959754/64207375-cb260f80-ce9c-11e9-8cf7-96bd93bfd40a.gif)

**Additional context**
Nothing critical, but the UX annoyance, especially if you're saving items constantly and previewing them.

**Comment by bolatovumar** [comment]
I can take a look.
