### ISSUE TITLE
Ubuntu installation tutorial

### ISSUE THREAD

**Issue by andres-pinilla** [btcpayserver/btcpayserver#101]
Hi, I installed BTCPay in Azure but it has not been possible to install it from 0 on an internal server with Ubuntu 16-04. Could you do a tutorial for your installation with Ubuntu ?.

Thank you.

Andres.

**Comment by NicolasDorier** [comment]
With or without docker?

**Comment by andres-pinilla** [comment]
Hi Nicolas, without docker.

**Comment by NicolasDorier** [comment]
have you checked https://www.youtube.com/watch?v=liOUTqBUi_g ? it is on windows but this is not different from ubuntu. Except, I made `build.sh` and `run.sh` for building and running nbxplorer and btcpay.

**Comment by andres-pinilla** [comment]
@NicolasDorier Hi Nicolas. I was already able to install BTCPay under docker using Ubuntu. Could you tell me the command to update to the latest version using git pull ?. Thank you very much.

**Comment by lepipele** [comment]
@andres-pinilla https://github.com/btcpayserver/btcpayserver-azure#how-to-update-btcpay

@NicolasDorier it seems we should definitely increase visibility of this... it's like 5th time I've seen people asking it ;)

**Comment by andres-pinilla** [comment]
Hi @lepipele, thanks for your response. The command had already seen it. My installation of BTCPay was in Ubuntu with Docker and when I execute that command nothing happens. Command not found appears.

**Comment by andres-pinilla** [comment]
@NicolasDorier @lepipele Please see this image: [https://imgur.com/a/01GzX](url)

**Comment by andres-pinilla** [comment]
<img width="286" alt="captura de pantalla 2018-04-04 a la s 7 00 02 p m" src="https://user-images.githubusercontent.com/29980213/38340746-97234a08-383a-11e8-897f-da53437d4709.png">
