### ISSUE TITLE
Checkout Page doesn't allow changing to Lightning

### ISSUE THREAD

**Issue by sicksubroutine** [btcpayserver/btcpayserver#1012]
**Describe the problem/bug**
If Bitcoin on chain is the default for the checkout page, you are not able to change to Lightning when on the checkout page. If you have Lightning on as default for the checkout page, you are able to change to Bitcoin but are not able to change back to Lightning.

**Your environment**
* Version of BTCPay Server: v1.0.3.128
* Deployment method: LunaNode
* Other relevant environment details:

**Logs (if applicable)**
Basic logs can be found in Server Settings > Logs.

**To Reproduce**
1. Go to http://crowdfund.lightningjunkies.net/
2. Click on Contribute, select any amount and click continue.
3. Try to change to Bitcoin and then back to Lightning.
4. It oddly changes the screen and gets stuck on accepting Bitcoin.

**Expected behavior**
I should be able to change between Bitcoin and Lightning without anything significant happening. Some obvious bugs are cropping up.

**Actual behavior**
If Bitcoin is the default for the checkout page, I or someone paying me cannot change the option to pay with Lightning.
If Lightning is the default for the checkout page, if you change the option to Bitcoin and try to change it back, things get bugged out, with the option for Lightning/Bitcoin simply disappearing.

**Screenshots/Links**
![bugged out checkoutpage](https://btcpay.sicksubroutine.com/LocalStorage/1bfacef2-6560-46d6-aea8-32e045bb5756-bugged-checkout.jpg)

**Additional context**

**Comment by NicolasDorier** [comment]
@Kukks your refactoring of the page introduced the bug

**Comment by NicolasDorier** [comment]
It happens when you swittch several time.

**Comment by NicolasDorier** [comment]
Probably unrelated, but I have `TypeError: this.fetchData is not a function` popping in my logs.

**Comment by NicolasDorier** [comment]
on the

```
   setTimeout(function(){
                        if (socket === null || socket.readyState !== 1) {
                            this.fetchData();
                        }
                        watcher();
                    }, 2000);
```

**Comment by britttttk** [comment]
I was having some problems with the timer too.

**Comment by NicolasDorier** [comment]
I can fix the timer one sec

**Comment by britttttk** [comment]
> If Bitcoin on chain is the default for the checkout page, you are not able to change to Lightning when on the checkout page
I also can't switch to LN even one time

**Comment by NicolasDorier** [comment]
I just fixed the `fetchData`. Trying to find the issue for lightning.

**Comment by NicolasDorier** [comment]
I guess it begs for selenium tests for the checkout!

**Comment by britttttk** [comment]
ahh was just thinking the same

**Comment by NicolasDorier** [comment]
Got it, making a new version

**Comment by britttttk** [comment]
It still happens on v.129 for me

**Comment by sicksubroutine** [comment]
Same issue remains with newest update.

**Comment by NicolasDorier** [comment]
wtf wtf one sec

**Comment by britttttk** [comment]
it works if you add on the invoice domain ~/BTC_LightningLike

**Comment by NicolasDorier** [comment]
@sicksubroutine are you sure? I can't repro. Can you try in incognito mode to be sure it is not some cache trickery?

**Comment by NicolasDorier** [comment]
@britttttk does it works for you this page: https://mainnet.demo.btcpayserver.org/i/Nq7g3A4WSQfvEY68jhMugG

**Comment by britttttk** [comment]
yes it works there

**Comment by NicolasDorier** [comment]
@britttttk can you share an invoice on your site?

**Comment by britttttk** [comment]
btcps0.com

**Comment by NicolasDorier** [comment]
can you create an invoice?

**Comment by britttttk** [comment]
works only if I do it like this https://btcps0.com/i/KXVh7LXGPyJ9ro5LD96iqb/BTC_LightningLike

**Comment by NicolasDorier** [comment]
@Kukks from now no change on checkout page until at least @pavlenex and @britttttk can test it and that we have a selenium test. This is critical part of btcpayserver and the last refactoring made at least 4 different bugs. :(

**Comment by britttttk** [comment]
I think also i'm using the root directory for my app and your mainnet is not right

**Comment by NicolasDorier** [comment]
@britttttk I am removing the feature that give issues.

**Comment by NicolasDorier** [comment]
So I removed the sats denomination for lightning payments.

**Comment by NicolasDorier** [comment]
@britttttk can you try 1.0.3.130 ?

**Comment by britttttk** [comment]
ok it works @NicolasDorier
