### ISSUE TITLE
Amount Placeholder cuts off the "amount" text when 4 items per row

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1016]
**Describe the problem/bug**
The custom amount text in the placeholder="Amount" gets cut off when there are 4 items in a row.

**Your environment**
* Version of BTCPay Server: 
* Deployment method: Docker

**To Reproduce**
1. Create a PoS app
2. Have an item with a custom amount
3. Have more than 4 items in the app
4. See the cut off amount field.

[Live preview available here](https://mainnet.demo.btcpayserver.org/apps/87kj5yKay8mB4UUZcJhZH5TqDKMD3CznjwLjiu1oYZXe/pos)

**Expected behavior**
The text should be visible or removed as it looks confusing this way. Or maybe add blinking `|` 
or any other symbol that indicates people can type in the amount, that's a better solution than the text imo.

**Actual behavior**
The `Amount` text does not fit and is cut off.

**Screenshots/Links**
![2019-09-05_15-20-42](https://user-images.githubusercontent.com/36959754/64345506-c83c3380-cff0-11e9-84b3-d5bdf23d3d72.png)

**Comment by bolatovumar** [comment]
![Screen Shot 2019-09-05 at 7 27 15 PM](https://user-images.githubusercontent.com/1934678/64396722-680ab900-d013-11e9-835c-c55120009ce1.png)

Doesn't really seem to be an issue on a Mac in Chrome/Opera.

**Comment by bolatovumar** [comment]
Also not an issue on Win 10 Chrome/Opera.

![Capture](https://user-images.githubusercontent.com/1934678/64396773-97212a80-d013-11e9-8d33-8c9a19114c04.PNG)

**Comment by pavlenex** [comment]
@bolatovumar you need to have 4 items, and the custom amount needs to be 4th in a row.
I can see it cut off on a 13" Mac on Firefox. https://mainnet.demo.btcpayserver.org/apps/87kj5yKay8mB4UUZcJhZH5TqDKMD3CznjwLjiu1oYZXe/pos

**Comment by bolatovumar** [comment]
@pavlenex I'm looking at the exact same link on a 13" Mac in Chrome/Opera and no issue. Could it be a Firefox-specific issue?

**Comment by bolatovumar** [comment]
Doesn't seem to be an issue in Firefox 69 on Win 10 either.

![Capture](https://user-images.githubusercontent.com/1934678/64440907-b6ef3780-d081-11e9-8ac3-39edd97536c2.PNG)

**Comment by pavlenex** [comment]
Does not seem to be browser-related, more screen-size related.

Safari
![Screen Shot 2019-09-07 at 12 07 46](https://user-images.githubusercontent.com/36959754/64473529-41aa6200-d168-11e9-90ca-6fb48c46b021.png)

Chrome
![Screen Shot 2019-09-07 at 12 08 05](https://user-images.githubusercontent.com/36959754/64473536-466f1600-d168-11e9-8c2e-ec21346f87c1.png)

**Comment by bolatovumar** [comment]
@pavlenex seems to be browser-related to me. It looks fine on all major browsers except for Firefox on my 13" Mac Air.

This is how it looks like in Firefox:
![Screen Shot 2019-09-08 at 11 54 15 AM](https://user-images.githubusercontent.com/1934678/64493007-a2e93880-d22f-11e9-94e7-5389b061d08e.png)

**Comment by pavlenex** [comment]
Okay, in that case I'm closing this one, until more people complain, seems like it only bothers me as a Firefox user.
