### ISSUE TITLE
Jumpy transition when refreshing wallet transaction page when there are labels

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1017]
**Describe the problem/bug**
If you assign a label(s) to your transactions and refresh or just visit the page, the transition will be awkward and the screen will "jump" (see gif at the bottom).

While it's a minor UX annoyance, it can look pretty awkward on slower servers (that take a bit more to load)

This is possibly introduced with .128
**Your environment**
* Version of BTCPay Server: v1.0.3.130
* Deployment method: Docker
* Other relevant environment details: Tested on Chrome and Firefox

**To Reproduce**
1. Assign a label to a transaction (one or more).
2. Visit wallet and you'll notice jumping
3. Refresh to see again

**Screenshots/Links**
![2019-09-05_19-20-44-1](https://user-images.githubusercontent.com/36959754/64364626-98eaee00-d013-11e9-8ad1-9ca0bf56e4b5.gif)

**Comment by bolatovumar** [comment]
A small related issue: if you have more than one label they butt up agains each other without any space in-between. It would be nice to have some space between each label.

![Screen Shot 2019-09-05 at 6 36 12 PM](https://user-images.githubusercontent.com/1934678/64394674-1a3e8280-d00c-11e9-97a1-9a1f28f1575b.png)

**Comment by bolatovumar** [comment]
Also would be nice to be able to remove a label by clicking some sort of "x" icon in the label.

**Comment by pavlenex** [comment]
@bolatovumar That was quick. Both of your suggestions are good ideas. I agree. Will test the jumpy transition in a few hours and comment on the PR.

**Comment by bolatovumar** [comment]
@pavlenex I will probably open two separate issues for the two suggestions.
