### ISSUE TITLE
Link to a custom logo not working

### ISSUE THREAD

**Issue by brunoaduarte** [btcpayserver/btcpayserver#102]
I've tried to set a custom logo for a store using the image url "https://www.google.com/logos/doodles/2018/dr-maya-angelous-90th-birthday-5544539824586752.3-s.png"

But i get the error

> Checkout experience
> The Link to a custom logo field is not a valid fully-qualified http, https, or ftp URL.

**Comment by andres-pinilla** [comment]
+1

**Comment by andres-pinilla** [comment]
<img width="565" alt="captura de pantalla 2018-04-04 a la s 7 15 09 p m" src="https://user-images.githubusercontent.com/29980213/38341114-935ff766-383c-11e8-957b-3ec41ffe9396.png">
<img width="584" alt="captura de pantalla 2018-04-04 a la s 7 15 18 p m" src="https://user-images.githubusercontent.com/29980213/38341115-93766582-383c-11e8-87db-38767b5097fc.png">

**Comment by andres-pinilla** [comment]
<img width="546" alt="captura de pantalla 2018-04-04 a la s 7 16 50 p m" src="https://user-images.githubusercontent.com/29980213/38341172-c17d74c0-383c-11e8-87eb-2fb837d962fa.png">

**Comment by NicolasDorier** [comment]
ha this is strange. Maybe you inserted a space before? worked for @astupidmoose .
Can you give me the URL?

**Comment by NicolasDorier** [comment]
I could reproduce. Looking to it.

**Comment by NicolasDorier** [comment]
Ok found the bug,  @astupidmoose it is a wonder why it worked for you... and for me in my tests before.
Anyway, in 10 min, 1.0.1.73 will realease and fix this bug. 6270a626fbc59713a85370a5fb93202b1fd797c4

**Comment by NicolasDorier** [comment]
The new version is online now, `btcpay-update.sh` if you are on azure.
