### ISSUE TITLE
Create stores via REST API

### ISSUE THREAD

**Issue by netpoe** [btcpayserver/btcpayserver#1022]
**Is your feature request related to a problem? Please describe.**

I'm familiar with the Bitpay API docs. I was able to create invoices as described in the [Custom Integration docs](https://docs.btcpayserver.org/integrations/customintegration). The problem is that I would like to create a store for each one of the users registered on my app. Basically, have access to all of the BTCPayServer web deployment features via a REST API. 

**Describe the solution you'd like**

The solution I'm creating is basically a mobile app with almost the same features as the BTCPAyServer web deployment, (perhaps the maintainers can suggest something else), so I need some API endpoints that allow me to:

- User downloads the app (a custom mobile bitcoin wallet application)
- The user creates wallets, export their private keys, etc. via the bitcore mnemonic sdk. (The app won't store the user's keys.)
- The app creates a store in my btcpayserver deployment via the API I'm requesting
- The app associates the _derivation scheme_ to the store of any wallet the user selects as default via the API I'm requesting
- The user can now accept payments through the app by creating invoices with the existing API
- Each user should have a unique store, so the invoices are associated only to the user's store
- The app will allow the users to add invoice products, currencies, etc. and display the QR code in the app with a new BTC address each time (very similar to the current web modal)

Specifically, this would look something like this: 

```
// POST Create Store
axios({
  url: `https://${MY_BTCPAYSERVER_CUSTOM_DEPLOYMENT_URL}/stores/create`,
  method: "POST",
  headers: {
    Authorization: `Bearer ${BTCPAYSERVER_DEPLOYMENT_API_KEY}`,
  },
  data: {
    name: "A user's store name",
  }
}).then(res => {
  // expected response
  const {storeID} = res.data;
  // link storeID somewhere in the user's datamodel
});
```

**Describe alternatives you've considered**

Currently I'm considering doing all of the above by myself, but BTCPayServer already solves this very well. I've googled for a while looking for documentation about this. I found the [node-js implementation](https://github.com/btcpayserver/node-btcpay) but it does not include these features I'm describing.

Thanks for the effort put into BTCPayServer

**Comment by Kukks** [comment]
We already have these planned but no eta. It also requires my openid pull requests to be merged first

**Comment by pavlenex** [comment]
Closing this one as the feature is planned for the new API in #1320
