### ISSUE TITLE
Could this work for a multi address transaction?

### ISSUE THREAD

**Issue by desLT** [btcpayserver/btcpayserver#1027]
I need in my solution to use this server as a service between clients and stores...
The main idea is to split the transaction cost in two, one % for the store and one for me to provide the service, so this would need to generate a new addres for my wallet and a new address for the store wallet

So I was wondering if there exist a way to do this? maybe

- from the settings?
- plugin that append my address to the transaction?

where could I start?

**Comment by pavlenex** [comment]
This is not possible out of the box. That said, you should look into [BTC Transmuter ](https://github.com/btcpayserver/btcTransmuter)+ btcpay. It's still in the alpha phase and not that well documented yet. @Kukks may be able to tell you if it's currently possible or not to achieve that in combination with Transmuter.

Please in future, open an issue only if you have a technical issue or for filing a bug report or a feature request.

General questions can quicker be answered on our Mattermost Community chat - chat.btcpayserver.org.

Related #204

**Comment by desLT** [comment]
Yeah it seams that Transmuter Extensions could work, but being alpha it's a limitation... let me talk with my fellow c# developer, see if we could help

Thank you for your answer and sorry for the new issue, I thought this could be a new feature for the btcPayserver, or in the worst case something to add to docs... my bad :)

**Comment by pavlenex** [comment]
It's in very early alpha phase. We do have a #btc-transmuter channel on our chat so feel free to join and ask questions if you have troubles to make it work.
