### ISSUE TITLE
Pay button image looks blurry on iPhone

### ISSUE THREAD

**Issue by bolatovumar** [btcpayserver/btcpayserver#1030]
See how the "Pay with BTCPAY" button text looks blurry in comparison to other elements on the page. To resolve this the underlying image needs to be re-exported in 2x the original size (in pixels).

![IMG_0015](https://user-images.githubusercontent.com/1934678/64719015-43cc3380-d47c-11e9-91c4-b174a5d562ac.jpeg)

**Comment by astupidmoose** [comment]
Easy solution: buy android phone :P

**Comment by bolatovumar** [comment]
@astupidmoose it also looks blurry on high-res Android phones or any retina-like screen for that matter.

**Comment by bolatovumar** [comment]
![Screenshot_20190911-112601](https://user-images.githubusercontent.com/1934678/64724369-3bc5c100-d487-11e9-82d4-f3f65c28dedf.png)

See Android screenshot above. Same issue.

**Comment by NicolasDorier** [comment]
@bolatovumar ah this stuff should be in SVG.

**Comment by NicolasDorier** [comment]
hey @rockstardev how did you create this button image?

**Comment by bolatovumar** [comment]
@NicolasDorier definitely agree about the SVG part. Whoever has the original design files should be able to export it as an SVG very easily.

**Comment by bolatovumar** [comment]
I was just wondering what BitPay does for their buttons and they do use SVG lol.

![Screen Shot 2019-09-15 at 7 09 33 PM](https://user-images.githubusercontent.com/1934678/64931302-8ed3a700-d7ec-11e9-9d85-ea41b681ae37.png)
