### ISSUE TITLE
[Repo] Add Security Policy to the repository

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1031]
**Is your feature request related to a problem? Please describe.**
When a security researcher wants to report a potential vulnerability, we do not offer clear steps on how to proceed.

**Describe the solution you'd like**
[Add Security Policy](https://help.github.com/en/articles/adding-a-security-policy-to-your-repository) which will provide information about vulnerabilities, how to report them, how we address them, list of vulnerable versions and a set of instructions for researchers that will enable faster communication with maintainers.

**Comment by Eskyee** [comment]
Creating a default community health file for the BTCPay project,
Security Policy is what Github spoke about today Pav & bk
we need to add a SECURITY.md file to our repository's root 

I agree here.


which will provide information about vulnerabilities, how to report them, how we address them, list of vulnerable versions and a set of instructions for researchers that will enable faster communication with maintainers. 
as said above!! I repeat.. here [https://www.youtube.com/watch?v=ekHXeRUldE0](url)

**Comment by pavlenex** [comment]
To provide some real-world examples.
[Security.md file in Bitcoin Core](https://github.com/bitcoin/bitcoin/blob/master/SECURITY.md) is a good example.
The direct benefit is that a security researcher can now be easily directed to appropriate page when reporting a vulnerability.
