### ISSUE TITLE
Show a "Suggested" Satoshis per byte on Bitcoin invoice

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#1036]
I'd like to propose displaying text with the suggested Satoshis per byte from the full nodes fee calculations on invoices. This fee should correlate with the "next block" fee. My understanding is that this value is already currently accessible and being used in the internal wallet calculations. 

Example: "We suggest adding a payment fee of at least 6 satoshis per byte".

Showing the customer what the suggested fee is for their transaction should serve 2 purposes:
1. Customer will know if their wallet is garbage and overcharging them. Example, Copay wallet will say "Send a fee of 140 sats/byte", but maybe only 10 sats/byte is needed for next block confirmation. 

2. Customers will be told what is expected for a fee to process their order the quickest possible way. This ensures that customers are not sending 1 sat/byte by default but getting mad when the payment doesn't confirm for 6 hours.

**Comment by bolatovumar** [comment]
So, if the suggested fee were to be displayed below the payment amount, that would be good?

![Capture](https://user-images.githubusercontent.com/1934678/64925311-67a4b780-d7a3-11e9-8043-383f58d85a00.PNG)

Below where it says 1 BTC = $13,533.89 (CAD).

**Comment by astupidmoose** [comment]
It could work as simply "Suggested Fee" but that might be too obscure and many people might not understand that. 

I know real estate is an issue, but I think it would be best as a text block below "open in wallet" since this is an actionable item. 

"We suggest adding a payment fee of at least 6 satoshis per byte for faster processing" or something similar. Open to suggestions though.

**Comment by bolatovumar** [comment]
> I know real estate is an issue, but I think it would be best as a text block below "open in wallet" since this is an actionable item.

> "We suggest adding a payment fee of at least 6 satoshis per byte for faster processing" or something similar. Open to suggestions though.

This sounds reasonable.

**Comment by bolatovumar** [comment]
So, does this get an ACK from peeps? Should effort be put towards it? I can potentially look into implementing this if there is consensus that this would be useful.

**Comment by Kukks** [comment]
I think we should decide on the UI of this first. It  needs to be optional
from the store checkout settings too.
Have to keep in mind that the recommended fee from core is not always
accurate too.

**Comment by astupidmoose** [comment]
This was my original idea: 

![image](https://user-images.githubusercontent.com/3916318/65806345-fa4b3c00-e13d-11e9-84e9-e69786c647e0.png)

It does require extending the invoice a little on the bottom. Agreed, it should probably be an optional setting, but I feel it really is a plus from a customer experience / merchant experience and avoids under/over payments on fees. 

My understanding is Core is pretty good at fees in the latest few iterations. Is it still off?

**Comment by bolatovumar** [comment]
I know LND is pretty good at estimating fees so I would guess Core is not much worse. LND definitely seems better than most fee estimation services.

I definitely agree this has to be optional.

@astupidmoose in your design I feel like the suggested fee would need to be made more prominent. Something like "Suggested fee: 6 satoshis per byte" would allow someone to see the suggested fee at  first glance. I guess this line can be made configurable so each merchant picks the text that shows up and BTCPay inserts the estimated number in there.

**Comment by bolatovumar** [comment]
@astupidmoose I ran `estimatesmartfee` on my 0.17.1 node to see what fee estimation is like and it's seems to be on part with https://bitcoinfees.earn.com which is often used.

Estimate is 18282 satoshis per 1 kilobyte (so, 18 sats per byte) for 1 block confirmation:
![Capture](https://user-images.githubusercontent.com/1934678/65837938-00622980-e2b2-11e9-94bd-941895120ff5.PNG)

Earn dot com had the same estimate when I checked.

**Comment by pavlenex** [comment]
Added in #1076
