### ISSUE TITLE
Lightning Payment Requests Missing "Description"

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#104]
Looks like the Description field of the lightning invoices is blank. This is not anything displayed on BTCpay, but rather part of the information passed in the payment request. 

The description should likely include the StoreName and OrderID or InvoiceID if OrderID is not present.

**Comment by astupidmoose** [comment]
![alx8nis](https://user-images.githubusercontent.com/3916318/38393853-13595bfc-38e1-11e8-94a2-a263f449d4b2.jpg)

**Comment by NicolasDorier** [comment]
will be soon in v1.0.1.75
