### ISSUE TITLE
Crowdfund button does not work

### ISSUE THREAD

**Issue by openoms** [btcpayserver/btcpayserver#1040]
Crowdfund button does not bring up the invoice.

**Your environment**
* Version of BTCPay Server: latest
* Deployment method: manual deployment to RaspiBlitz
* Other relevant environment details: RPi4 4GB

**Logs (if applicable)**
Logs are not set: 
 Error: File Logging Option not specified. You need to set debuglog and optionally debugloglevel in the configuration or through runtime arguments 

**To Reproduce**
New store - new crowdfund app
See here:
https://pay.diynodes.com/apps/rFc3yRFQdmTjUqygPsr95f4AcnQ/crowdfund

**Comment by Kukks** [comment]
Ok, just double checked: it's a deployment issue with the raspbiblitz nginx configuration. websockets are not correctly configured

**Comment by openoms** [comment]
Thanks for looking into it this fast. Let me know if there is anything I can do on my side.

**Comment by openoms** [comment]
Ok, will compare my settings to the manual deployment guide.
What is interesting that the problem does not affect the Point os Sale App:
https://pay.diynodes.com/apps/zsXnNnXsYAiZtwUSHtsev5LcWnD/pos

**Comment by Kukks** [comment]
Yeah the point of sale is a more traditional app while the crowdfund does a lot of communication with the backend.

**Comment by openoms** [comment]
Thank you for your comment in https://gist.github.com/normandmickey/3f10fc077d15345fb469034e3697d0d0#gistcomment-3031500

My instance is fixed:
https://pay.diynodes.com/apps/rFc3yRFQdmTjUqygPsr95f4AcnQ/crowdfund
