### ISSUE TITLE
Cannot pull GBP data from BitcoinAverage/Kraken

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#1043]
**Describe the problem/bug**
When trying to get a rate pairing for Kraken's BTC_GBP pairing an error is served.

![image](https://user-images.githubusercontent.com/3916318/65364035-0b3b0100-dbc4-11e9-8335-ad280d410283.png)

**Your environment**
* Version of BTCPay Server: v1.0.3.130
* Deployment method: Docker

**To Reproduce**

**Expected behavior**
Expect a BTC_GBP pairing

**Actual behaviour**
Error!

**Additional context**
The rate is available in the BitcoinAverage API here: 
https://apiv2.bitcoinaverage.com/exchanges/ticker/kraken

I'm not sure if this is the source of BTCPay's rates, but the rate pairing does exist. I asked in chat for comfirmation and user kryptkhex also verified the issue.

**Comment by NicolasDorier** [comment]
Fix by https://github.com/btcpayserver/btcpayserver/commit/2e0abdbd06eec6d01f2befb72532aa923578c617

**Comment by bolatovumar** [comment]
Oh, gosh, just as I debugged this and was about to push a fix, @NicolasDorier storms in and fixes it.

**Comment by NicolasDorier** [comment]
I needed to do this one to repay Mike for all the beers he offered when I was in honey badger. :p
