### ISSUE TITLE
Redundant invoice state change notifications

### ISSUE THREAD

**Issue by conscott** [btcpayserver/btcpayserver#1050]
**Describe the problem/bug**
I receive more than one callback/email notification on invoice state changes that occur _after_ the `new` state notification. This can cause annoyances like receiving multiple emails for the same state change. 

**Your environment**
BTCPayServer manual build/deploy off master @ 27f20386dfd32a61e22f59a9f62bb9cf99357fbf on Ubuntu 18.04 server

**Reproduce Problem**
1. Make PoS App with a Callback Notification Url set. 
2. Make an invoice 
3. Only one 'invoice new' notification is sent to the callback url
4. Manually mark invoice to invalid
5. Two 'invalid notifications' are sent to the callback url 

I would expect to only ever receive one notification per state change. Curios why it doesn't happen for the `new` state, but does for other states. 

**Screenshots/Links**
![multiple_notification](https://user-images.githubusercontent.com/14220652/65435932-323e4080-de19-11e9-9ab7-9ac0076fc280.png)

Any ideas here?

**Comment by pavlenex** [comment]
Seems related #785 #968

**Comment by conscott** [comment]
Indeed, ill close this one and follow #968
