### ISSUE TITLE
Wrong address and due amount on "paid summary" of invoice page.

### ISSUE THREAD

**Issue by reablaz** [btcpayserver/btcpayserver#1056]
I had and invoice in my Invoices page, which one was marked as paidPartial. To check details i opened invoice:

![image](https://user-images.githubusercontent.com/3844596/65787221-1c09ea80-e161-11e9-9cc6-5da3dc03a7db.png)

Well, first of all i have two BTC addresses in invoice page. As Pavlenex mentioned, this is because partialpaid status (on partial paid new addr is generated). So that's not the issue. That is fine.
But as you can see on status page, the addr 34idTd8JmCq8WnntpiGAn5isf1yMLgNZmQ is mentioned as used address in "paid summary", while in fact, the only address which was used is 3EuCWPZkX2YWQs55H9ySpSQi64LAMzmboY
Also, as you can see from tx details, the amount paid is 0.01000000 BTC, while invoice created for 0.01000099 BTC (99 more sats than paid). But in the summary view it shows due 199 sats. So the wrong address is entioned, as well as amount is not precise.

https://chain.so/address/BTC/3EuCWPZkX2YWQs55H9ySpSQi64LAMzmboY
https://chain.so/address/BTC/34idTd8JmCq8WnntpiGAn5isf1yMLgNZmQ

* Version of BTCPay Server:  v1.0.3.132
* Deployment method: BTCPayJungle
* Other relevant environment details: conversion enabled using changelly

**To Reproduce**
1. Create invoice
2. Pay it in partial
3. Wait until invoice is expired
4. Open invoice detailed view in INVOCES page

**Expected behavior**
It should show that 3EuCWPZkX2YWQs55H9ySpSQi64LAMzmboY was used to pay invoice and the due amount is 99 sats (100 sats less then it shows to me)

**Actual behavior**
It seems that btcpay uses first invoice bitcoin address, not actual one. I have no idea, why the amount does not match as well.

**Comment by Eskyee** [comment]
Any idea about this Nicolas ??

**Comment by pavlenex** [comment]
I was able to replicate this with `master` in dev-env.

1. Create an invoice to `0.01000099`
2. Pay `0.01000000` to the shown address, for example `bcrt1qnmef3eespfhhrwp8m7hznkylqsv04g7j444sv2`
3. In the UI, I see this

![paid](https://user-images.githubusercontent.com/36959754/65790974-08f71a80-e161-11e9-8ef5-b857b0da050c.PNG)

The UI here is bad, because it can lead to conclusion that second address `....4akp` in the underpaid invoice` is actually paid.

**Comment by reablaz** [comment]
The issue with additional 100 sats was because i had set the option to add network fee if multiple payments done. i dont get why such low fee was calculated. but anyway that's not the issue!

**Comment by Eskyee** [comment]
Cheers Pav !!

**Comment by bolatovumar** [comment]
@pavlenex isn't `0.01000099 - 0.01000000` equal to 99 sats so what it shows as due (`0.00010099`) is inccorect? Where did the additional `10000` sats come from? Fee? Shouldn't that be shown in the UI somehow?

**Comment by pavlenex** [comment]
@bolatovumar That extra comes from the [network fee](https://docs.btcpayserver.org/faq-and-common-issues/faq-stores#add-network-fee-to-invoice-vary-with-mining-fees) which is a form of a protection mechanism applied after the first payment to protect merchants from various dust attacks. It's optional and can be disabled in Store Settings.

As for showing it in the UI, that is actually a good idea I think. I will have to double check if we show that in the invoice export, I think we do.

**Comment by Eskyee** [comment]
has this been solved @pavlenex we can close if so !!

**Comment by pavlenex** [comment]
No, it hasn't been solved yet.

**Comment by NicolasDorier** [comment]
I think that this is confusing indeed.

What about just removing the address and renaming "paid summary" to "current status"?

![image](https://user-images.githubusercontent.com/3020646/72503845-02132580-3880-11ea-9cc2-153721ccb782.png)

**Comment by NicolasDorier** [comment]
Marking for closing if there is no more input on the PR for 7 days.
