### ISSUE TITLE
I cant get invoice data as described in APPS page

### ISSUE THREAD

**Issue by reablaz** [btcpayserver/btcpayserver#1059]
On the APPS page there are instructions on how to handle callbacks:

![image](https://user-images.githubusercontent.com/3844596/65824596-7e074480-e274-11e9-86d1-184898d2d243.png)

What i do is create an invoice using html form (you can do the same at https://bit.ly/2nydDMt ), then, using generated invoice ID i try to fetch invoice data:

[test@localhost ~]$ curl -X GET https://btcpayjungle.com/invoices/CzjCebcQdCS3kSMUzGYFAP --header "Content-Type: application/json" 
**Status Code: 401; Unauthorized** 

is it feature or it is bug?

I dont know is there any reason to do authorization do get that invoice data. First, the invoice ID is already kinda token to make a request. Secondly, if we want go _secure way_, we could give some basic invoice data (which is publicly available from https://server.com/i/{ivoiceID} page) even for unauthorized user, because anyway all this data is available from invoice web-UI page.

**Comment by NicolasDorier** [comment]
@reablaz so yes there is a reason: The callback url that you don't want to be public.
Actually this was public before and remove it.

If you want simply query it, you can just use the API key in Store/Access Token.

**Comment by reablaz** [comment]
@NicolasDorier API KEY was exactly the option i need. Than this isssue is minor and need just small update of instructions.

**Comment by reablaz** [comment]
https://github.com/btcpayserver/btcpayserver/pull/1061
