### ISSUE TITLE
Add BTCPay custom theme

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#106]
The new https://github.com/btcpayserver/btcpayserver/pull/105 broke some stuff:

Ideally it should be a "bootstrap theme" that the host or merchant can switch to his own.
But the first, default, should be same theming as BTCpay now.

Button and table header:

![image](https://user-images.githubusercontent.com/3020646/38450698-898f14ec-3a5d-11e8-81f8-15cfcfdab94c.png)

Against

![image](https://user-images.githubusercontent.com/3020646/38450702-a3317796-3a5d-11e8-9b0d-6bf7e6953ab3.png)

Pills

![image](https://user-images.githubusercontent.com/3020646/38450712-bced0736-3a5d-11e8-84cc-1d4a27bd4d94.png)

Against

![image](https://user-images.githubusercontent.com/3020646/38450713-c38cf6c8-3a5d-11e8-8e26-b2673e9e9f85.png)

The PoS (just bootstrap broken links)

![image](https://user-images.githubusercontent.com/3020646/38450719-d13d6898-3a5d-11e8-992d-4c3b1e721c54.png)

Then links

![image](https://user-images.githubusercontent.com/3020646/38450720-e03006bc-3a5d-11e8-8052-ad5ea0d16db1.png)

Against

![image](https://user-images.githubusercontent.com/3020646/38450724-ecd62d2e-3a5d-11e8-8245-fb90a9dadd02.png)

Blue button

![image](https://user-images.githubusercontent.com/3020646/38450743-159c02e2-3a5e-11e8-937a-a6766c23cf05.png)

Against

![image](https://user-images.githubusercontent.com/3020646/38450746-2308843c-3a5e-11e8-8b20-bcb7dc5a7fa8.png)

The font

![image](https://user-images.githubusercontent.com/3020646/38450753-347db0b6-3a5e-11e8-9664-6b16ba1fa473.png)

Against

![image](https://user-images.githubusercontent.com/3020646/38450756-40cb6a98-3a5e-11e8-8700-3f465beb00b3.png)

Ping @lepipele

**Comment by lepipele** [comment]
Yeah, these are all BASE changes in Bootstrap4 from beta to release version we are migrating to. Like, button style has changed, default font size isincreased. It's easy to see when comparing side by side:

https://getbootstrap.com/docs/3.3/components/#btn-dropdowns
https://getbootstrap.com/docs/4.0/components/buttons/

I'll PM you to discuss best approach... but yeah... it's like create whole custom theme if we want to preserve exactly the same look.
