### ISSUE TITLE
Logs listing on front-end by date

### ISSUE THREAD

**Issue by MyNameIsOka** [btcpayserver/btcpayserver#1062]
Hi community,

I recently set up a BTC server on AWS and the log in the front-end is showing up without a problem. 
However, I would like to have logs of the last couple of days and I can't figure out how to do that.

Version of BTCPay Server: 1.0.3.133
Deployed via the Docker guide.
Running on Ubuntu 18.04 on AWS

I can't really show any logs s the only thing is that each day the previous day's logs are automatically deleted.

If you need any additional info, please let me know.
Thanks a lot.
    - Oka

**Comment by pavlenex** [comment]
Have you tried [getting the logs this way?](https://docs.btcpayserver.org/support-and-community/troubleshooting#2-1-btcpay-logs)

**Comment by MyNameIsOka** [comment]
Thank you for your response.
Yes, querying the logs directly via Docker is possible and I see the logs after one day, as well.
But I would like to have them day by day at the front-end.

**Comment by pavlenex** [comment]
I believe our issue reports would  be way better if we added logs of not only btcpayserver but also nbx and other important stuff and maybe keep them for like 1 week.

I've noticed that it's way better to troubleshoot the issue with less tech-savvy users if they can provide logs on the front end.

I did not want to open a new issue since this one is pretty similar.

@NicolasDorier @Kukks thoughts?

**Comment by britttttk** [comment]
Concept ACK, for log page changes/improvements. It would be nice to have UI access to more logs, for much faster troubleshooting of issues. Also there is quite a bit of room on the logs page to display logs differently.

**Comment by pavlenex** [comment]
This is how we currently display logs, just a single date, always, no pagination whatsoever. Would be good to also include logs of other relevant containers (nbx, Ligtning etc)

![Screenshot 2020-01-07 at 14 13 59](https://user-images.githubusercontent.com/36959754/71897862-0fc9fc00-3158-11ea-9d3f-2243a5fc412a.png)

Some discussion on pagination by @rockstardev in #1238 related to #1236

**Comment by NicolasDorier** [comment]
So we hard code the logs, this is our config

```
.WriteTo.File(debugLogFile, rollingInterval: RollingInterval.Day, fileSizeLimitBytes: MAX_DEBUG_LOG_FILE_SIZE, rollOnFileSizeLimit: true, retainedFileCountLimit: 1)
```

We can maybe keep a bit more.

**Comment by NicolasDorier** [comment]
So basically, a new file is created if:

* One day is passed
* The file exceed 2MB

And we retain only 1 of such file.

**Comment by pavlenex** [comment]
Besides BTCPay logs, I'd separate them into containers rather than dates. We should keep logs for one day or 2MB as you mentionered. Some containers that are very important and often we need info is: let's encrypt, LND, nbx, etc

**Comment by NicolasDorier** [comment]
@pavlenex I want to open separate issue for the logs of other containers.

**Comment by bolatovumar** [comment]
@NicolasDorier would it make sense to allow people to configure for how long they want to keep the logs around? A user could specify they want to keep the logs for the past seven days or something like that. The default option would be what we have hard-coded now.

**Comment by NicolasDorier** [comment]
@bolatovumar I think it makes sense, but probably difficult to refactor to do it right.
Serilog is configured at launch time, I don't think it can be changed while running.

**Comment by pavlenex** [comment]
Unfortunately after discussing with Kukks, it seems that due to different deploylement methods and the way in which docker container works, this is either hardly possible or requires an incredible amounts of hacks. I think our docs troubleshoting guide explains it decently enough.
