### ISSUE TITLE
Feature Request: Merge BTC and Lightning Addresses into a Single QR

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#1064]
According to my understanding of the article below, lightning allows for a fallback BTC address to be included in the lightning generated QR code. 

https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md#tagged-fields

TravelbyBit builds this QR into their lightning QR, which allows wallets to scan either a BTC address or lightning address in a single display option. 

https://twitter.com/VNumeris/status/1095826765111451648?s=19

I think it would be a cool way to merge the BTC and Lightning options into 1 qr code. 

Downside would be possible confusion to customers who are used to clicking between the two. 

Putting this here for discussion.

**Comment by pavlenex** [comment]
How would you handle the `copy` part of the invoice?
It may end up being very confusing if you try to distinguish it all in one UI.
* `Copy LN`
* `Copy on-chain`
How would a noob know a difference?

**Comment by astupidmoose** [comment]
Agreed, it might be confusing and needs more thought. Unfortunately a precedent has been set that they are different. Copy would be kind of messy based on its current layout. I need to think about this more. 

However that being said, I think ALL lightning invoices should have a built in BTC QR. I think this is a brilliant feature and eliminates the need to differentiate. From a UX design, I think it's great to have the wallet decide the BTC or lightning flow and have both displayed at once server side. 

:)

**Comment by bolatovumar** [comment]
@astupidmoose I agree about having on-chain backup addresses for lightning invoices. I believe Zap wallet does this by default already (or will allow this in a future version).

**Comment by pavlenex** [comment]
Ok, so instead of merging all into one, your proposal is to have a fallback on LN QR code, is that correct? I think that's a good compromise since it won't invade the current workflow but still provides value.

Do you guys know if this will cause any compatibility issues among Lightning Network wallets? I assume it won't but would be good to think about that as well.

**Comment by astupidmoose** [comment]
Yea, that might be a good idea. 

Incase someone doesn't really understand lightning, then clicks that option and tries to pay they still get an useable QR. 

I wouldn't think it would mess any lightning wallets up as it's built into the standard. But that doesn't really mean anything lol. 

The backup BTC address should also be the BTC address in the BTC tab.

**Comment by bitbug42** [comment]
I really like that idea, would greatly simplify the QR-scanning flow.

A good way to do it IMO would be to use a BIP21 URL like this:
`bitcoin:ONCHAIN_ADDRESS?amount=AMOUNT&lightning=BOLT11_INVOICE`

I don't know about other wallets but for example Eclair Mobile is already able to recognize that type of encoding.

Non-Lightning wallets would still be able to recognize the on-chain address, and Lightning wallets would understand both options right away, all in one QR.

**Comment by Eskyee** [comment]
is it possible to have a test branch with this feature for us to test out the user experience ..
Feature Request: Merge BTC and Lightning Addresses into a Single QR branch.. simplify the check out is great for newbies, coming to BTCPay, less clicks the  better!!

**Comment by Kukks** [comment]
Curious on how this will be made without forcing the payment methods to be forced to de-isolate from each other.

**Comment by Kixunil** [comment]
@Kukks guessing by that question, the current architecture is that each payment method is a separate module that generates the payment string in isolation and then the string is presented to the user. Am I correct?

**Comment by Kukks** [comment]
Correct

**Comment by Kixunil** [comment]
So I see, why it's hard. Maybe a way to solve it would be to return a dynamic object that supports optionally merging with other objects. Then merge what's possible and present merged objects to the user.

Pseudo code:

```
// this is for avoiding iterator invalidation
objects_to_remove = Set();
iterator = objects.iter();
// this is strictly O(n^2), but we have very small n
for object in iterator {
    // ignore removed objects
    if objects_to_remove.contains(object) {
        continue;
    }
    // basically continue iterating from the next object
    // we assume try_merge is commutative (BIP21 + BOLT11 == BOLT11 + BIP21)
    for other in iterator.clone().skip(1) {
        if objects_to_remove.contains(object) {
            continue;
        }
        // returns true if the payment methods were merged, object then contains both methods
        if object.try_merge(other) {
            objects_to_remove.insert(other);
        }
    }
}
// remove all objects that were merged into other objects, so that only merged or single objects remain
for object in objects_to_remove {
    objects.remove(object);
}
```

This would solve "BTC+LN+maybe Payjoin+maybe something more in the future" as well as shitcoins (if anyone bothers with them). I even heard a strange idea to have shitcoins as a fallback to BTC. While I don't think it's a productive idea, my proposal happens to be useful for that case as well.

**Comment by Kixunil** [comment]
@mariodian that's what I was suggesting essentially, just a generic implementation. I guess there's a general preference to avoid special casing. Although, maybe special casing just LNP/BP is fine. It's just one relevant case. Shitcoins usually don't care about LN.

**Comment by rockstardev** [comment]
> Curious on how this will be made without forcing the payment methods to be forced to de-isolate from each other.

Used your magical `IPaymentMethodHandler.PreparePaymentModel` method in `BitcoinLikePaymentHandler` class.
