### ISSUE TITLE
Dynamic DNS auto-renewal

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#1067]
**Is your feature request related to a problem? Please describe.**
The most used Dynamic dns system is NoIp. They provide a "free" service but the catch is that you need to remember to confirm your subscription every month. 

**Describe the solution you'd like**
Add an auto-nrenewal script if noip is configured. Most of the work has been already done here: https://github.com/loblab/noip-renew

**Comment by NicolasDorier** [comment]
what do you mean? We already have this feature in `Server Settings/Dynamic DNS`

**Comment by Kukks** [comment]
Yes but if you use noip(or any of its domains), you will need to go to their UI and physically confirm to extend the service else they curt you off. Alternatively, you pay to not need to do it. 

The linked repo does the confirmation under the covers through an e2e-ish  style

**Comment by NicolasDorier** [comment]
The solution of `noip-renew` relies on selenium this is not good.
