### ISSUE TITLE
Bitcoin testnet checkout page 

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver#1069]
when using the btcpay bitcoin testnet, is it possible to let all noob users and myself, Know!! 
in checkout window and Bitcoin logo, That they are using bitcoin testnet coins, if possible ?

just a idea!!  since I`m playing much more with testnet bitcoin, lightning with btcpay server

cheers

**Comment by Eskyee** [comment]
@rockstardev when you a free moment, can you guide me thru this process ;) 
cheers rockstar, maybe at the next happy coding remote session !!

**Comment by bolatovumar** [comment]
@NicolasDorier @pavlenex do you see value in this feature? I'm thinking since you already see a testnet/regtest badge on the landing page this might not be worth it? Also, testnet addresses are different from mainnet addresses so you can't really mix them up.

![Capture](https://user-images.githubusercontent.com/1934678/67442159-95f09080-f5b4-11e9-860e-39b7f01fd601.PNG)

I'm open to working on this if people see value in it.

**Comment by NicolasDorier** [comment]
I am quite neutral about it.

**Comment by pavlenex** [comment]
Don't have a strong ACK or NACK for it neither, considering that user can change the icon on the invoice in Checkout Experience fairly easily, I don't think it brings any major value.

**Comment by Kukks** [comment]
You'd need to
* add a variant of `CryptoImagePath` to the BTCPayNetwork for testnet/regtest( or make it a `Dictionary<NetworkType, string>`)
* Modify implementations of `IPaymentMethodHandler.GetCryptoImage` to switch images based on network

So it is only a few mins of work if you want to do it. Neutral about it too

**Comment by NicolasDorier** [comment]
@Kukks no, you can just inject the `BTCPayNetworkProvider` and do if/else on the network type to show different badges.

This is not related to payments, this is related to a server wide setting.

**Comment by Kukks** [comment]
Ah, when I talked with @Eskyee he said he wanted to change the bitcoin icon to something more testnety on the checkout for this

**Comment by NicolasDorier** [comment]
If that's the case, then there is no need to modify any implementation. You just have to do a `if/else` where you affect the `CryptoImagePath` to put another image. This is 1 line of code.

**Comment by Kukks** [comment]
Yeah, but he needs to specify where the image is, per network per network type :P

**Comment by bolatovumar** [comment]
@Eskyee could you clarify about what you want here? Is it as @Kukks says? Just have a different Bitcoin logo if you are not on mainnet during the checkout process?

**Comment by esky33kubernetes** [comment]
As I wrote above, and what kukks says!! 
Bitcoin Testnet On the Checkout !! 
To help differentiate !! Between Main Net! Testnet 
I know their is a t in the address!! And testnet logo on site!! But nothing on checkout!! ??  🤔☝️  Since I’m using Testnet a lot more!! I like visual clues !!

**Comment by esky33kubernetes** [comment]
I would of done this in a rockstar 😎online session!! Just been busy at moment 🤓

**Comment by Eskyee** [comment]
closing this , as looking forwards to a live share with rockstar, just adding the word TestNet on the checkout, B logo is good enough,
