### ISSUE TITLE
PayServer:  BTC: NBXplorer error `Connection refused`

### ISSUE THREAD

**Issue by iamnotagentleman** [btcpayserver/btcpayserver#1074]
Hello ı'm runing run.sh after build.sh processed  but I'm stuck on this error from BTCPayServer

* Version of BTCPay Server: lastest
* Deployment method: with build.sh on Ubuntu 18.04 Server
* Other relevant environment details: built on aws

fail: PayServer:      BTC: NBXplorer error `Connection refused`

**Comment by blockchainsolutionshi** [comment]
How did you solve this?

**Comment by francoisharris** [comment]
Please can you post the fix?

**Comment by LouisWayne** [comment]
Did you fix the issue?
