### ISSUE TITLE
Latest commit missing class HeadersOverrideMiddleware 

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver#1080]
**Describe the problem/bug**
I cant build the latest commit 5025e0dd4ddd6d5ab459cbe3c6aa947bb882b5f1

<img width="1440" alt="Screenshot 2019-10-09 at 20 05 59" src="https://user-images.githubusercontent.com/30862925/66512417-cc1c1380-ead0-11e9-9b7f-2cd52da5dead.png">

to reproduce try building the solution

**Comment by rockstardev** [comment]
I can also reproduce it on my end @NicolasDorier

**Comment by NicolasDorier** [comment]
sorry! just fixed
