### ISSUE TITLE
Support bitcoin output descriptors

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#1082]
The best way to describe what and why is the beautiful link
https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md

**Comment by jacobburrell** [comment]
Is this supported?

**Comment by Kukks** [comment]
A subset is, yes

**Comment by jacobburrell** [comment]
Is there a way to [connect an existing wallet](https://docs.btcpayserver.org/ConnectWallet/#import-wallet-file) such as [Muun](https://muun.com/) using its output descriptors?

If it's implemented but not in docs, can we add the info to docs?

If it's not quite yet implemented, is it on the roadmap?

**Comment by Kukks** [comment]
I highly advise against this. Connecting a lightning wallets onchain wallet
to btcpay without some kind of state sync will cause address reuse and gap
limit issues where funds do not show on both wallets

**Comment by Lovegina71** [comment]
Thank you I need help I'm new to all this

**Comment by jacobburrell** [comment]
Admittedly that example has those issues.

In general for on chain only wallets using output descriptors but no gap limit issue, is there a means to use output descriptors instead of a xpub for instance?

**Comment by Kukks** [comment]
Yes, feel free to try it. (We convert it to our own internal format but the result is the same)
