### ISSUE TITLE
broken url link popup connecting-btcpay-store-to-your-wallet

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver#1087]
<img width="849" alt="Screenshot 2019-10-13 at 03 07 55" src="https://user-images.githubusercontent.com/30862925/66709994-639a9400-ed67-11e9-8796-3f74a6397dd0.png">

this URL popup only happens "when the user forgets to add wallet to store" 
so needs to be updated from this old broken url link

<img width="823" alt="Screenshot 2019-10-13 at 03 31 19" src="https://user-images.githubusercontent.com/30862925/66710124-081dd580-ed6a-11e9-8e4d-f7c625fd1c18.png">

https://docs.btcpayserver.org/btcpay-basics/gettingstarted#connecting-btcpay-store-to-your-wallet 

I think this should link here, please check @pavlenex cheers

https://docs.btcpayserver.org/faq-and-common-issues/faq-wallet#how-to-connect-my-wallet-to-btcpay-server

**Comment by britttttk** [comment]
@Eskyee the link was fixed already in [this commit](https://github.com/btcpayserver/btcpayserver/commit/1c2c3ede80d18d75be9e7105a0bd16c32893c1b4#diff-cf427292b2f76704cc7a734a60602dde). I guess it will be in the next version?

**Comment by Eskyee** [comment]
ok sorry, as only just found this break, cheers bk

**Comment by britttttk** [comment]
I'm also waiting for this fix :( @Eskyee

**Comment by Eskyee** [comment]
jaja it will drop soon I guess 👍 @britttttk
