### ISSUE TITLE
Display Woo on website root ?? internal fragments ie Woo 

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver#1088]
is it possible to connect the internal WooCommerce or LibrePatron 
to the policy section!! Display app on website root...
Map specific domains to specific apps ????

I know our Woo fragment, LibrePatron is not a internal app, but as a internal fragment it could be Kool to have this choice if possible 
just a idea

**Comment by pavlenex** [comment]
Displaying on a root of btcpay is a bad practice, you can already configure woocommerce host that does what you're referring to, provided that you launch [woo on top of btcpay](https://docs.btcpayserver.org/integrations/woocommerce#deploying-woocommerce-from-btcpay-server):

`export WOOCOMMERCE_HOST="yourstoredomain.com"`

@Kukks I think we need to clean up this section for apps on root, really unnecessary.

**Comment by Kukks** [comment]
> Displaying on a root of btcpay is a bad practice, you can already configure woocommerce host that does what you're referring to, provided that you launch [woo on top of btcpay](https://docs.btcpayserver.org/integrations/woocommerce#deploying-woocommerce-from-btcpay-server):
> 
> `export WOOCOMMERCE_HOST="yourstoredomain.com"`
> 
> @Kukks I think we need to clean up this section for apps on root, really unnecessary.

Not sure what you mean, we ve had actual use cases for this feature?

**Comment by pavlenex** [comment]
If someone sets it on the root, the UX gets clunky as they need to log in by applying /login to the link manually, I don't think it makes sense to have root on domain anymore.

**Comment by Kukks** [comment]
> If someone sets it on the root, the UX gets clunky as they need to log in by applying /login to the link manually, I don't think it makes sense to have root on domain anymore.

NACK from my end, I think it is useful and should stay. Maybe just needs some small docs to describe the pitfalls you mentioned

**Comment by Eskyee** [comment]
Yes I want to keep mapping apps to root , this is still a good idea I like, 
but yes it can be hard for a noob figuring out how to login back again, this should have a read me notice,  for sure !! As for woo that’s kool was just a idea

**Comment by Eskyee** [comment]
im happy now to close this, Issue, as I like what we have, please highlight to noobs,  more they can run a internal woo commerce, and could save on hosting fee like this.

as Kukks""  say I think it is useful and should stay. Maybe just needs some small docs to describe the pitfalls you mentioned!!  
I agree ..
