### ISSUE TITLE
Show checkboxes inline instead of a separate line from label

### ISSUE THREAD

**Issue by bolatovumar** [btcpayserver/btcpayserver#1089]
Currently checkboxes are on a separate line from their label:
![Screen Shot 2019-10-10 at 6 23 29 PM](https://user-images.githubusercontent.com/1934678/66719859-d462a000-eda9-11e9-9f09-b70d6596f9ff.png)
![Screen Shot 2019-10-10 at 6 23 59 PM](https://user-images.githubusercontent.com/1934678/66719860-d62c6380-eda9-11e9-9633-0fe5a1cbe38b.png)

I suggest having them on the same line like so:
![Screen Shot 2019-10-13 at 11 07 50 AM](https://user-images.githubusercontent.com/1934678/66719867-007e2100-edaa-11e9-877b-fab0f81bd3b3.png)

This way they take up less space and it looks nicer imo.

I will implement this if ACKed.

**Comment by pavlenex** [comment]
Yeah, definitely a better experience.
ACK.

**Comment by bolatovumar** [comment]
Closing the issue as my PR was merged.
