### ISSUE TITLE
Use "lightning:" instead of "LIGHTNING:"

### ISSUE THREAD

**Issue by Iffabled** [btcpayserver/btcpayserver#1091]
**Is your feature request related to a problem? Please describe.**
Currently, Lightning invoices URIs use the `LIGHTNING:` scheme, which most apps don't handle.

**Describe the solution you'd like**
`lightning:` should be used instead.

**Comment by Kukks** [comment]
i think this is because we are recommended to use uppercase for the QR code and use the same string for both

**Comment by Iffabled** [comment]
> i think this is because we are recommended to use uppercase for the QR code and use the same string for both

Most services use lower case, and BTCPay itself uses lower case for on-chain payments.

**Comment by NicolasDorier** [comment]
BTCPay use upper case for bech32. 
I was not aware that app scheme was case sensitive, can you tell use of an app does not work?

**Comment by Iffabled** [comment]
https://play.google.com/store/apps/details?id=com.lightning.walletapp

**Comment by NicolasDorier** [comment]
@Iffabled I think it makes sense, will do.
