### ISSUE TITLE
Theme settings broken

### ISSUE THREAD

**Issue by radWorx** [btcpayserver/btcpayserver#1097]
**Describe the problem/bug**
When applying custom bootstrap, layout and css break; don't match expected output. 
**Your environment**
* Version of BTCPay Server: v1.0.3.135
* Deployment method: local regtest

**To Reproduce**
1. Go to 'Server Settings'
2. Click on 'Theme'
3. Click on 'Build your own theme' or 'pick one already made' 
Or GoTo: https://docs.btcpayserver.org/development/theme#bootstrap-themes for instructions
4. Paste Custom Bootstrap or CreativeStart URI in respective theme settings textbox.
5. Click 'Save'

**Expected behavior**
Theme should change as expected.

**Actual behavior**
Theme changes but layout and css are off.
![ThemeBad](https://user-images.githubusercontent.com/27673545/67448986-af123500-f5e6-11e9-9f30-30c880336bcc.PNG)

**Screenshots/Links**
If applicable, add screenshots or links to help explain your problem.

**Comment by bolatovumar** [comment]
@radWorx not all themes are guaranteed to work. This needs to be considered on a theme-to-theme basis.

**Comment by Eskyee** [comment]
Custom bootstrap CSS file work for me, but I find the problem here, with CreativeStartCssUri 
Creative Start theme is used on top of Bootstrap.. breaks the layout, with the BTCPay default @bolatovumar @radWorx

**Comment by Eskyee** [comment]
https://uxplanet.org/how-to-customize-bootstrap-b8078a011203

**Comment by pavlenex** [comment]
This seems like external theme issue as @bolatovumar mentioned, not sure what we can do about it @radWorx , any ideas? I don't think we can do much on our end.

**Comment by radWorx** [comment]
@pavlenex, I believe the work @dennisreimann is doing will help this.

**Comment by dennisreimann** [comment]
I think @bolatovumar is right, it depends on the theme that is used and whether or nor is compatible with the markup BTCPayServer provides. 

The new theming approach fixes this! ™

Users will be able to do overrides based on CSS custom properties (-> variables for colors, fonts, etc.) instead of having to provide a full blown CSS file that overwrites selectors.

**Comment by pavlenex** [comment]
Ok, so obviosly this is a broader issue of the UI, so I'll go ahead and close this one, we'll continue to brainstorm in the UI/UX channel on Mattermost, and open a new issue once we're ready to discuss changes on GitHub.
