### ISSUE TITLE
The button to return to the store when the invoice expires has no link

### ISSUE THREAD

**Issue by andres-pinilla** [btcpayserver/btcpayserver#110]
I am using BTCPay with the WooCommerce Plugin. When an invoice expires by time, the button to return to the store has no link.

**Comment by NicolasDorier** [comment]
This is not related to woocommerce, this is a BTCPay bug. You are using latest version right?

**Comment by andres-pinilla** [comment]
Yes @NicolasDorier. v1.0.1.79

**Comment by NicolasDorier** [comment]
pinging @lepipele  I'll take a look as well.

**Comment by lepipele** [comment]
Fixed in this PR: https://github.com/btcpayserver/btcpayserver/pull/117
