### ISSUE TITLE
Feature Request: Adding Attachments to Payment Requests

### ISSUE THREAD

**Issue by readmor** [btcpayserver/btcpayserver#1100]
This is not a problem but could be a beneficial addition to some users. I think it would be nice to be able to add attachments to payment requests. With the attachments you can simply add invoices when the payment requests need to be more official.

**Comment by pavlenex** [comment]
I've had a chat with @readmor about this, and we came to a conclusion that current visual editor is already enough to fulfill his use-case as it's possible to highly  customize it, hence I'm closing the issue with his approval.
