### ISSUE TITLE
Email not working Gmail

### ISSUE THREAD

**Issue by 59023g** [btcpayserver/btcpayserver#1105]
Environment:
- v1.0.3.135 Docker
- VPS
- Server: smtp.gmail.com
- Port: 587

Input login, password, hit save. Then 'Send test email'.

Response:
```Error: The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.5.1 Authentication Required. Learn more at```

`Less Secure Apps` enabled in Google. No 2FA. Said I "Recognize activity" in Google. And reviewed this doc: https://support.google.com/mail/answer/185833?hl=en. No luck 

Looked around, couldn't find any information.

**Comment by pavlenex** [comment]
Could gmail  doing something on their end, but it was working for me before I updated.

 I get this

` Error: Syntax error, command unrecognized. The server response was: `

**Comment by britttttk** [comment]
Actually now it does work for me on both previous v133 & current v135. 

There is a note for less secure apps in gmail `To keep your account secure, Google will automatically turn this setting OFF if it’s not being used.` and I believe it turned it off automatically for me because after enabling less secure apps to access again, now it works. 

@pavlenex can you check if you're maybe that feature is getting turned off?

**Comment by Kukks** [comment]
I recommend anyone to use a more reliable SMTP server for their business needs. Mailgun allows you to use theirs for free(you need to put in your credit card but they never charge you unless you use their paid plans) against your domain.

**Comment by pavlenex** [comment]
@britttttk can confirm that you have to allow access to less secure app for this to work. I used port 587. We should update the docs [here](https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#how-to-configure-smtp-settings-in-btcpay) for gmal specifically and add perhaps another smtp setup such as mailgun as Kukks suggested, but I assume whoever uses mailgin would know how to set up smtp, maybe just mention it. 

I think we can close this one and open a new issue in docs.

**Comment by robertclarkson** [comment]
For anyone else trying to use Gmail as the email server you need to create an "app password" for the gmail account you want to use as Google now require app passwords when using 3rd party services to send email on behalf.
