### ISSUE TITLE
Registering multiple U2F devices breaks all but most recent

### ISSUE THREAD

**Issue by jlopp** [btcpayserver/btcpayserver#1109]
**Describe the problem/bug**
If you register multiple U2F devices for 2FA and then try to log in, only the last device that was registered will actually authenticate.

**Your environment**
* Version of BTCPay Server:  v1.0.3.135
* Deployment method: docker
* Other relevant environment details: Ubuntu 18.04.1 LTS

**To Reproduce**
1. Go to /Manage/U2FAuthentication
2. Click on 'Add New Device'
3. Register a U2F device
4. Click on 'Add New Device'
5. Register a second U2F device
6. Log Out
7. Log In
8. Try to authenticate with the first U2F device you registered

**Expected behavior**
Log in should succeed

**Actual behavior**
Login fails with a timeout error

**Comment by pavlenex** [comment]
Thanks for reporting this. I've been noticing inconsistency with U2F on my end, but was never able to figure out what's going on.

I've replicated the steps and indeed it's a bug.

The only thing is see in the logs is this:

```
U2f exception:Wrong challenge signed in clientData 
```
