### ISSUE TITLE
Make recommended fee confirmation target configurable

### ISSUE THREAD

**Issue by bolatovumar** [btcpayserver/btcpayserver#1110]
**Is your feature request related to a problem? Please describe.**
Now that we have an option to show recommended fee on checkout invoice, it would be nice to allow merchants to set the confirmation target they want. It is currently hardcoded at 20 blocks.

**Describe the solution you'd like**
Add an option to set confirmation target in blocks on the checkout experience page.

**Describe alternatives you've considered**
Hardcode some other value instead of 20. Probably not a good idea as there was a rationale for setting it to 20 blocks.

**Additional context**
This issue was brought to my attention by @astupidmoose. He is using this feature on CoinCards and would like the transaction to clear as quickly as possible.

**Comment by astupidmoose** [comment]
Yea, 20 blocks do not work for customers who are looking for fast transactions. 

It would be best to either make this configurable or use a 1 block time. My understanding is 20 blocks is hardcoded for wallet users as most people can wait for money going to an exchange, but for a customer-facing section of btcpay it should be conveying the urgency

**Comment by pavlenex** [comment]
Added in #1127
