### ISSUE TITLE
Pay Button Preview too low on page

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#1111]
**Is your feature request related to a problem? Please describe.**
No, but I think payment button higher on the page so the user does not have to scroll to the bottom of the page to preview their button selection(s) would be better for UX. Sometimes checking boxes like `Use a simple input style` I'm not even sure what changed because you don't see it change. 

**Describe the solution you'd like**
Move button preview above optional Payment Notifications / Advanced fields.

**Additional context**
Keep code at the bottom of page

**Comment by bolatovumar** [comment]
This makes sense. I'm thinking something like this would be nice?

![Screen Shot 2019-11-02 at 8 53 08 PM](https://user-images.githubusercontent.com/1934678/68080172-d7eab500-fdb2-11e9-8ec8-4435667e1cdf.png)

**Comment by pavlenex** [comment]
Done in #1116 🚀
