### ISSUE TITLE
different smtp server for each store?

### ISSUE THREAD

**Issue by chovy** [btcpayserver/btcpayserver#1114]
Is it possible to use a different smtp server setup for each store? I have several stores on different domains and would like each email to look like it was sent from that domain.

**Comment by Kukks** [comment]
Yes, check the email settings on the store page

**Comment by Kukks** [comment]
![image](https://user-images.githubusercontent.com/1818366/68081484-f41c3f80-fe0e-11e9-84c4-1550511a8087.png)
