### ISSUE TITLE
Instant Fiat conversion with exchanges

### ISSUE THREAD

**Issue by andres-pinilla** [btcpayserver/btcpayserver#112]
Hi,

I would like the possibility that the payment can be sent  immediately to an address of an exchange that sells it immediately to avoid volatility.

Thanks,

Andrés

**Comment by NicolasDorier** [comment]
It might be a good idea. Although might not be realistic when fees get high. Thanks for the idea though, will think about it.

**Comment by andres-pinilla** [comment]
Thanks for your answer. I hope you think about it and that you can implement it.

**Comment by NicolasDorier** [comment]
I was thinking about periodic dump. But having a payment forwarder is better UX.

**Comment by NicolasDorier** [comment]
If you want to accelerate the thing, please discuss about the ideal UX here.

**Comment by NicolasDorier** [comment]
Copying from slack

```
@everyone I am starting to think about how to provide exchange integration ton BTCPayServer such that merchant can sell immetiately their bitcoin/shitcoin.  One thing I can't beat Bitpay with is that the merchant will be subject to volatility until the exchnge confirm the deposit.  (worth noting that once exchanges integrate lightning it will be instant)

Anyway, for merchant ready to take a 10 minutes risk, Bitpay still have merchants who does not really mind paying high fees to them. Other than that BTCPay will be a complete solution and cheaper to use instead of Bitpay.

This issue has been open https://github.com/btcpayserver/btcpayserver/issues/112 . I am starting to think about the concept of "Payment Forwarders" in BTCPay. Basically forwarding payments upon receipt to an address, a derivation scheme or deposit address of your exchange.

I think adding the concept of "Exchange Bot" on top of this, whose role will be to place orders on behalf of the merchant once the deposit get confirmed by the exchange.

I would need more idea on how to do a clean UX to achieve this. As well as providing to the merchant a good visibility to follow where his money is moving.
```

**Comment by NicolasDorier** [comment]
other things to think about: If fees get high, then merchant will want to batch payment forward together. 
So a way to control how much they are willing to pay in miner fee as % of the payment is needed.

**Comment by JeremyRand** [comment]
I'd like to donate some BTC earmarked for developing this feature.  Would such an earmarked donation be accepted?  If so, what's the preferred procedure for making an earmarked donation?

**Comment by ndaxio** [comment]
why not use merchant exchange wallet directly on the exchange? That will open up the option for exchange to provide the merchant with an option to immediately liquidate coins that arrive at his account? and if the end user has an account on the exchange that it will become an instant transfer internally saving the merchant a ton of blockchain fees? Just a thought

**Comment by rockstardev** [comment]
@ndaxio we needed to start with solution that doesn't depend on third parties - your keys, you Bitcoin.

From there we can add support for those wanting fiat... and we wanted to go down the route that would work for most of existing exchanges and their APIs. 

We didn't have "pay to exchange wallet" because no exchange wanted to support this. If your exchange is willing to support this, we can definitely talk details - join our Slack (http://slack.btcpayserver.org/), direct message me and we can go from there.

**Comment by shivaenigma** [comment]
Hi,
Blockonomics has announced a payment forwarder compatible with BTCPay. Feel free to [try it out](https://blog.blockonomics.co/a-bitcoin-payment-forwarding-service-for-hd-wallets-13d86c947fec)

Also, here are the [instructions](https://blockonomics.freshdesk.com/support/solutions/articles/33000234755-payment-forwarding-using-xpub-with-merchant-service) for xpub configuration with BTCPay

**Comment by Kukks** [comment]
We're progressing on a standalone self-hostable version so that you don't need to funnel all your crypto to a third party's xpub. :)

**Comment by shivaenigma** [comment]
> We're progressing on a standalone self-hostable version so that you don't need to funnel all your crypto to a third party's xpub. :)

Thanks good to know this. For a self-hosted version there is a risk on keeping private keys on an online server with open http/other ports, which may a bit difficult to secure for all merchants.

Which is why we have designed this service, which is completely firewalled and securely managed by us. We will be provide fund guarantees in the future. 

Of course, merchants who can manage self hosted service... there cannot be a more privacy friendly solution.

**Comment by andres-pinilla** [comment]
Hi @NicolasDorier and @Kukks, any update about this?

**Comment by NicolasDorier** [comment]
I know @rockstardev is cooking something

**Comment by Kukks** [comment]
Anyone interested in progress on this can go to https://chat.btcpayserver.org/btcpayserver/channels/fiat to follow and provide feedback

Here's the latest update at least: 
```
heya @all, got a test version up at https://transmuter.fiat.kukks.org right now. It is still very alpha but you can experiment and let me know how you feel about it 

If you want to deploy to your own, I have a fork of the docker repo @ 
`https://github.com/kukks/btcpayserver-docker` with branch `transmuter`
Everything is the same in terms of config, you just have the following extra:
* Add `opt-add-btctransmuter` to the `BTCPAYGEN_ADDITIONAL_FRAGMENTS` options
* `BTCTRANSMUTER_HOST` set to domain for fiat service app
*  `BTCTRANSMUTER_CRYPTOS` set to the cryptos you set up on btcpay, separated by a comma( e.g: `BTC,LTC`)
```

**Comment by rockstardev** [comment]
OK, we are handling this in separate repository (https://github.com/Kukks/btcTransmuter-vnext) + discussing it further in our MatterMost (https://chat.btcpayserver.org/).

Whoever is willing to test (or is already testing) is welcome to join us there <3
