### ISSUE TITLE
Invoice stuck in new state hours after creation

### ISSUE THREAD

**Issue by michnovka** [btcpayserver/btcpayserver#1123]
I cretaed an invoice via API. It was counting down the 15min window when I took down the server for few mins. When I powered it back on, the invoice should already have been expired, but it is still stuck as "new". 

![Screenshot_2019-11-05 BTCPay Server](https://user-images.githubusercontent.com/16553087/68242611-24cbc700-0011-11ea-9c83-822de8d03976.png)

When I click on checkout, details, it shows modal which says it is expired.

![Screenshot_2019-11-05 BTCPay Server(1)](https://user-images.githubusercontent.com/16553087/68242668-40cf6880-0011-11ea-842f-7cbc4402e6b4.png)

Now obviously this is because some hooks were not run at specific times as server was powered down. But how do I fix this? I want this invoice to be expired, not new for all eternity.

Thanks!

EDIT: I did find the option to mark invoice invalid, but I am keeping the issue open as I think invoice should be marked as expired even tho it expires during downtime of a server.

**Comment by pavlenex** [comment]
This is something @britttttk experienced, but we were unable to replicate.
When opening a technical issue, it's always useful if you don't ignore the issue template 😄 
So can you provide us with a bit more information:

**Your environment**
* Version of BTCPay Server:
* Deployment method:  
* Anything weird in the logs

**Comment by britttttk** [comment]
Close **all** your browsers. Then logout & log back in.

For me, the issue was fixed once I closed all my browsers. I did also update (restart server) during the time when I was having the issue so maybe it's related as you said. I'll try to replicate the issue again later today.

**Comment by michnovka** [comment]
I use 1.0.3.136 on lunanode deployed VPS. For some reasons my logs at /Server/Logs are totally empty, do I have to enable this somewhere?

I am quite certain it happens due to being powered off when the invoice is about to expire. I reproduced this once more, doing exactly this:

1. create new invoice with API
2. power down server
3. wait till invoice should expire (15 mins in my case)
4. power on server
5. check invoices - the latest one will be stuck in "new" state

Thanks!

**Comment by michnovka** [comment]
> Close **all** your browsers. Then logout & log back in.

@britttttk This does not solve the issue.

**Comment by britttttk** [comment]
Awesome thanks for replicating :) My logs were empty as well in the UI. 

You can always check more logs [like this](https://docs.btcpayserver.org/support-and-community/troubleshooting#2-1-btcpay-logs).

**Comment by NicolasDorier** [comment]
@michnovka can you provide the link to this invoice?

**Comment by pavlenex** [comment]
Hey @michnovka does the issue still occur? If so , can you provide more information Nicolas asked, please?

**Comment by michnovka** [comment]
Sorry, I was away for some time. I cannot give URL to the server for security reasons in this public thread, however if somebody contacts me over PM, I can disclose more. I did not reboot the server since last time it happened, but I was able to reproduce it reliably with the instructions I gave above at the time I was testing it. I did not update btcserver tho, still using  1.0.3.136. Was there some related fix in any of the updates? Thanks

**Comment by pavlenex** [comment]
Has anyone been able to replicate this? @britttttk ?

**Comment by britttttk** [comment]
@pavlenex I have not seen this issue for some time now. I have not yet tried reproducing the error with:
>create new invoice with API

**Comment by bolatovumar** [comment]
I had this issue once before and restarting my server fixed it.

**Comment by NicolasDorier** [comment]
Should we close this?

**Comment by michnovka** [comment]
I tried to reproduce this few times with latest version and its not reproducible for me anymore. I am closing the issue.
