### ISSUE TITLE
Theme CSS URL not translated to .onion version for TOR hidden service

### ISSUE THREAD

**Issue by michnovka** [btcpayserver/btcpayserver#1124]
**Describe the problem/bug**
When I open invoice on over .onion domain, the assigned CSS theme is loaded over regular domain. If I use local file storage and URL like https://btcpay.domain.com/LocalStorage/3d775b47-b338-45ac-a469-1b8dff5511a2-btcpay_theme.css I would expect this to be translated automatically to 
http://naokdinbuebuebduebduebduebduebduebduebduedb.onion/LocalStorage/3d775b47-b338-45ac-a469-1b8dff5511a2-btcpay_theme.css

**Your environment**
* Version of BTCPay Server: 1.0.3.136
* Deployment method: lunanode

**Expected behavior**
All CSS files loaded from the same server's local storage should be translated to .onion domain when .onion domain is accessed

**Actual behavior**
Since I have to pass ABSOLUTE URL in settings, the regular https non-onion URL for CSS file is used

**Comment by NicolasDorier** [comment]
The right way to fix this is to allow relative url in settings. Will do.
