### ISSUE TITLE
Wrong USD rate for sats on invoice

### ISSUE THREAD

**Issue by bolatovumar** [btcpayserver/btcpayserver#1128]
**Describe the problem/bug**
If you check the "Display lightning payment amounts in Satoshis" checkbox in "Checkout experience" tab and then switch to lightning payment on an invoice you see exchange rate which says something like "1 Sats = $9,307.54" which is obviously incorrect (at least for now).

**Your environment**
* Version of BTCPay Server: v1.0.3.136

**Expected behavior**
Either show the actual value of a sat (something like $ 0.0093 USD) or show "1 BTC = $9,307.54".

**Actual behavior**
Shows price of 1 BTC for 1 Sat

**Screenshots/Links**
![Screen Shot 2019-11-06 at 7 10 06 PM](https://user-images.githubusercontent.com/1934678/68357978-f19a3e00-00cb-11ea-9a6f-d711136654e8.png)

**Comment by NicolasDorier** [comment]
Ping @Kukks
