### ISSUE TITLE
Extra information in create store error message

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#1130]
**Describe the problem/bug**
Extra text in the warning, you need to create a store first (Payment Requests)

**Your environment**
* Version of BTCPay Server:  v1.0.3.137
* Deployment method: regtest

**To Reproduce**
1. No xpub
2. Go to: Payment Request > Create Payment Request

**Expected behavior**
Should only show "Error: you need to create at least one store."

**Actual behavior**
Shows extra information "{"Message":null,"Html":"Error: You need to create at least one store. <a href='/stores/create'>Create store</a>","Severity":1,"AllowDismiss":true,"SeverityCSS":"danger"}"

![image](https://user-images.githubusercontent.com/39231115/68372668-8e75cf00-00fe-11ea-8fe1-e0339603c3a7.png)

**Comment by NicolasDorier** [comment]
ah it is still not officially released. Will fix before the real rrelease thanks.
