### ISSUE TITLE
Redirect when adding user manually

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1138]
**Describe the problem/bug**
With our new register/login page re-design, user gets the impression that the new login page is a home page. Ok, when user goes to Server Settings > Users > Add new user he's redirected to a newly designed home page which disrupts the UX way too much. 

I suggest that we handle addition of a new user similarly to how we do it in Store Settings, internally without re-directing people.

1. Go to Server Settings > Users
2. Click on `Add new user`
3. See the disruption.

This is up for discussion, not sure how you feel about this, don't want to hurt any feelings with my language, so let's kindly discuss it.

**Comment by pavlenex** [comment]
Ok, this may not be a bug as @britttttk clarified, but really terrible UX.

**Comment by britttttk** [comment]
@pavlenex can you describe why you think it is terrible UX, so we can improve it? 
It was redirected to that link before as well.

**Comment by pavlenex** [comment]
As I said on Mattermost, it disrupts the UX way too much and looks weird, user gets a feeling that  he's logged out.

**Comment by bolatovumar** [comment]
Agree with @pavlenex here. This probably won't be a big deal for experienced users but would probably be pretty jarring for a new user.

**Comment by NicolasDorier** [comment]
I think it is quite easy to solve actually:

1. Set `ViewData["LayoutPage"]` to `_Layout.cshmtl`.
2. In Register, if  `ViewData["LayoutPage"]` is not empty, then use that instead of the `WelcomeLayout`.

**Comment by bolatovumar** [comment]
@NicolasDorier wouldn't you have to check if there is a return url to make sure you don't accidentally use the regular layout when you mean to use the welcome layout (see my PR).

@pavlenex what do you think about this solution?

**Comment by pavlenex** [comment]
Closing this as it's been fixed in #1139
