### ISSUE TITLE
BitPay Node.JS Client error interacting with BTCPayServer "no-bitid"

### ISSUE THREAD

**Issue by FreedomLabsIO** [btcpayserver/btcpayserver#114]
I've successfully paired the Bitpay Node.JS client with my local instance of BTCPayServer, but when i try to invoke the api i'm getting this weird "no-bitid" error.

```
root@ubuntu:/home/ubuntu/node_modules/bitpay/lib# bitpay pair
Do you have a pairing code?
no

Okay, we can get a pairing code, please choose a facade:
  1) Point of Sale
  2) Merchant
  : 1

 Your token information:

 Client ID:     Tf71..................................ZYR3
 Pairing Code:  zEXgMr5
 Label:         node-bitpay-client-ubuntu
 Facade:        pos


 Your pairing code will be available until: Wed Apr 11 2018 20:17:57 GMT-0300 (-03)


 Pair this client with another organization by giving an administrator this pairing code:
 zEXgMr5

 Pair this client with your organization:
 https://0.0.0.0:23000/api-access-request?pairingCode=zEXgMr5
```

Then i access the link on the browser and get the message "Pairing is successful", the token is now activated.

But when i try to invoke any methods i only get errors

```
root@ubuntu:/home/ubuntu/node_modules/bitpay/lib# bitpay whoami
Enter Key Password:
Error: { error: 'no-bitid' }
root@ubuntu:/home/ubuntu/node_modules/bitpay/lib# bitpay request -T pos -R invoices
Enter Key Password:
Error: { error: 'no-bitid' }
root@ubuntu:/home/ubuntu/node_modules/bitpay/lib# bitpay request -T pos -X post -R invoices -P '{"price": 15, "currency": "USD"}'
Enter Key Password:
Error: { error: 'no-bitid' }
```

I've commented the lines that check the type of the model of "controller.User.Identity" on "Extensions.cs"
(just to help debugging)
```
public static BitIdentity GetBitIdentity(this Controller controller, bool throws = true) {
//    if (!(controller.User.Identity is BitIdentity))
//        return throws ? throw new UnauthorizedAccessException("no-bitid") : (BitIdentity)null;
    return (BitIdentity)controller.User.Identity;
}
```
Now this error is thrown at server console

```
crit: PayServer:      Unhandled exception in BTCPayMiddleware
System.InvalidCastException: Unable to cast object of type 'System.Security.Claims.ClaimsIdentity' to type 'BTCPayServer.Authentication.BitIdentity'.
   at BTCPayServer.Extensions.GetBitIdentity(Controller controller, Boolean throws) in /home/ubuntu/btcpay/btcpayserver/BTCPayServer/Extensions.cs:line 117
```

**Comment by brunoaduarte** [comment]
I've commented the lines that check the type of the model on "Extensions.cs"

```
        public static BitIdentity GetBitIdentity(this Controller controller, bool throws = true)
        {
        //    if (!(controller.User.Identity is BitIdentity))
       //        return throws ? throw new UnauthorizedAccessException("no-bitid") : (BitIdentity)null;
            return (BitIdentity)controller.User.Identity;
        }
```
Now this error is thrown at server console

```
crit: PayServer:      Unhandled exception in BTCPayMiddleware
System.InvalidCastException: Unable to cast object of type 'System.Security.Claims.ClaimsIdentity' to type 'BTCPayServer.Authentication.BitIdentity'.
   at BTCPayServer.Extensions.GetBitIdentity(Controller controller, Boolean throws) in /home/ubuntu/btcpay/btcpayserver/BTCPayServer/Extensions.cs:line 117
```

**Comment by NicolasDorier** [comment]
Uncomment those lines. This error only mean you are not signing your request as you should do with Bitpay.

You need to pair a private key of your client with the server via a process Bitpay call "pairing".
There is two way of doing it: server side pairing and client side pairing. Check this for python

https://support.bitpay.com/hc/en-us/articles/115003001203-How-do-I-configure-and-use-the-BitPay-Python-Library-

The process for nodejs should be same

**Comment by NicolasDorier** [comment]
The issue is probably here `https://0.0.0.0:23000/api-access-request?pairingCode=zEXgMr5` . 

It should be https://127.0.0.1:23000/api-access-request?pairingCode=zEXgMr5

**Comment by NicolasDorier** [comment]
So the issue is the following: Your client is signing a request thinking your instance URI is "https://0.0.0.0:23000/"... but your btcpay server think its address is "http://127.0.0.1:23000/".

If you want your btcpay instance to use the same address as your bitpay client you can use `--externalurl http://127.0.0.1:23000/` and use the same url for your client!

**Comment by brunoaduarte** [comment]
@NicolasDorier , i'm not sure that the addressing is the problem here...

In fact my addressing was a little messed cause i was using a Ubuntu VM (Virtual Box) with NAT, so i had to forward ports between the internal and external address, now i've cleaned this mess by switching to "Adapter bridge", so now my Ubuntu VM is on the same ip range of my Windows machine.

- Windows IP: 192.168.15.54
- Ubuntu IP: 192.168.15.55

On Ubuntu, i run BTCPayServer and bind it to the 192.168.15.55 adapter (now i'm using port 80 to make things easier)
Ps: i'm also using the flag you suggested  `--externalurl http://192.168.15.55:80/`

```
root@ubuntu:/home/ubuntu/btcpay/btcpayserver# ./run.sh -b 192.168.15.55 -p 80 --externalurl http://192.168.15.55:80/
info: Configuration:  Data Directory: /root/.btcpayserver/Main
info: Configuration:  Configuration File: /root/.btcpayserver/Main/settings.config
info: Configuration:  Root Path: /
info: Configuration:  SQLite DB used (Data Source=/root/.btcpayserver/Main/sqllite.db)
info: Hangfire.BackgroundJobServer: Starting Hangfire Server
info: Hangfire.BackgroundJobServer: Using job storage: 'Hangfire.MemoryStorage.MemoryStorage'
info: Hangfire.BackgroundJobServer: Using the following options for Hangfire Server:
info: Hangfire.BackgroundJobServer:     Worker count: 10
info: Hangfire.BackgroundJobServer:     Listening queues: 'default'
info: Hangfire.BackgroundJobServer:     Shutdown timeout: 00:00:15
info: Hangfire.BackgroundJobServer:     Schedule polling interval: 00:00:15
info: Configuration:  BTC: Explorer url is http://127.0.0.1:9735/
info: Configuration:  BTC: Cookie file is /root/.nbxplorer/Main/.cookie
warn: Configuration:  BTC: Using cookie auth against NBXplorer, but /root/.nbxplorer/Main/.cookie is not found
info: PayServer:      Starting listening NBXplorer (BTC)
info: PayServer:      Start watching invoices
info: Configuration:  Listening on http://192.168.15.55:80
info: Events:         NBXplorer BTC: NotConnected => Ready
info: PayServer:      BTC: Checking if any pending invoice got paid while offline...
info: PayServer:      BTC: 0 payments happened while offline
info: PayServer:      Connected to WebSocket of NBXplorer (BTC)
```
Then i create a server initiated pairing code 

![image](https://user-images.githubusercontent.com/5354345/38698198-a07fc7f8-3e6a-11e8-97f9-4418cfbda305.png)


BitPay client is properly pointed to the BTCPayServer API

```
root@ubuntu:/home/ubuntu# bitpay config -p
{ apiHost: '192.168.15.55', apiPort: '80', forceSSL: 'false' }
```

Then i try to pair the "Server initiated pairing code" and it succeeds

```
root@ubuntu:/home/ubuntu# bitpay pair -c sZyVYbs

 Client successfully paired with `pos` facade capabilities.
```
But problem persists
```
root@ubuntu:/home/ubuntu# bitpay whoami
Enter Key Password:
Error: { error: 'no-bitid' }
```

**Comment by NicolasDorier** [comment]
Can you print what the node client is signing when sending the request?

**Comment by NicolasDorier** [comment]
Ah I think it is caused by the `nonce=` part. Can you try something like createINvoice ?

**Comment by NicolasDorier** [comment]
Your code seems different than https://github.com/bitpay/node-bitpay-client/blob/master/lib/rest-client.js

But anyway I think the bug is that BTCPay does not replicate GET requests signatures the right way. I am looking into it now. 
CreateInvoice should work.

**Comment by brunoaduarte** [comment]
You're right, it seems my code is older than the one in GitHub repository.
I've got mine from npm `https://www.npmjs.com/package/bitpay`

Now i'm running the most recent one from GitHub

But even if i execute

`node bitpay.js request -T pos -X post -R invoices -P '{"price": 10, "currency": "USD"}'`

The same problem occurs

`Error: { error: 'no-bitid' }`

![image](https://user-images.githubusercontent.com/5354345/38714108-1183cfb8-3eab-11e8-8ca4-0792448d6d3e.png)

**Comment by NicolasDorier** [comment]
can you show me same screenshot for the invoices call ?

**Comment by brunoaduarte** [comment]
That's the screenshot for the create invoice request
`node bitpay.js request -T pos -X post -R invoices -P '{"price": 10, "currency": "USD"}'`

**Comment by NicolasDorier** [comment]
it is possible it is calling the tokens method first.

**Comment by NicolasDorier** [comment]
Here: https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Hosting/BTCpayMiddleware.cs#L69

Can you add 

`Logs.PayServer.LogInformation($"key ({key.ToHex()}), sig ({sig}), url ({url}), body ({body})");`

And tell me what it gives you

**Comment by NicolasDorier** [comment]
Also verify that the pubkey used is well registered into stores/user tokens

**Comment by brunoaduarte** [comment]
You mean the Stores/Access Tokens, right ? Yes, it's there...

Here's the Log output
`info: PayServer:      key (038f8c9855c1a64a50528b7ede7a6b47b538454049d950b2ddb9960dde59a28937), sig (3045022100f784029f9cd3660c32cc46ec9f8637dc676988e78fe0cf337ebc4b8d531da9b5022076ed2fbad088ecd4db745dc5b02f8ad1b32d9da2c2cce567bcae521712c40cb2), url (http://192.168.15.55/tokens), body ()`

Seems the port number is missing on the signing url `http://192.168.15.55/tokens`.
The client is signing as `http://192.168.15.55:80/tokens`.

**Comment by brunoaduarte** [comment]
Awesome, thanks !
```
root@ubuntu:/home/ubuntu/btcpay/node-bitpay-client/bin# node bitpay.js request -T pos -R invoices
Enter Key Password:
[ { url: 'http://192.168.15.55/invoice?id=9Ke3YXUHh4YBY8rGsoD1cd',
    posData: null,
    status: 'expired',
    btcPrice: '0.00123962',
    btcDue: '0.00124063',
    cryptoInfo:
     [ { cryptoCode: 'BTC',
         paymentType: 'BTCLike',
         rate: 8066.959534759423,
         exRates: { USD: 8066.959534759422 },
         paid: '0.00000000',
         price: '0.00123962',
         due: '0.00124063',
...............
```
