### ISSUE TITLE
Get Invoices gives everytime an 403 error with bitpay schema forbidden

### ISSUE THREAD

**Issue by didiandalucia** [btcpayserver/btcpayserver#1140]
As the documentation link to bitpay they syntax for make an invoice get request is:

https://<mybtc-server>/invoices/<invoice-id>/?token=<my-token>

So I can make it via the btcpay-phpclient - scripts or via curl or via direct http - request, I get everytime an error 403 and the error logged in the btcserver as: 

info: BTCPayServer.Security.Bitpay.BitpayAuthenticationHandler: AuthenticationScheme: Bitpay was forbidden.
info: BTCPayServer.Security.Bitpay.BitpayAuthenticationHandler: AuthenticationScheme: Bitpay was forbidden.

With the same token I can create a test invoice without problems, but I cant request the invoice status!

**Comment by NicolasDorier** [comment]
show me the code

**Comment by didiandalucia** [comment]
The Code you find in the 2nd line of my issue message:

`https://<btcpayserver>/invoices/<invoiceno>/?token=<my security token>`

and its the same thing, when I test via curl or php - about php I have open equal a issue in the port of phpclient - here the php code:

`<?php
/**
 * Copyright (c) 2014-2017 BitPay
 *
 * getInvoice
 *
 * Requirements:
 *   - Account on https://test.bitpay.com
 *   - Baisic PHP Knowledge
 *   - Private and Public keys from 001.php
 *   - Token value obtained from 002.php
 *   - Invoice created
 */
require __DIR__ . '/../../../../../vendor/autoload.php';
// Now fetch the invoice from BitPay
$client = new \BTCPayServer\Client\Client();
$adapter = new \BTCPayServer\Client\Adapter\CurlAdapter();
$client->setUri('https://<our btcpayserver>:443');
$client->setAdapter($adapter);
$token = new \BTCPayServer\Token();
$token->setToken('<our secret token>'); // UPDATE THIS VALUE
$client->setToken($token);
/**
 * This is where we will fetch the invoice object
 */
$invoice = $client->getInvoice("Py3soohUrGKzRKQPUXk94V"); // last invoice id
$request = $client->getRequest();
$response = $client->getResponse();
echo (string)$request . PHP_EOL . PHP_EOL . PHP_EOL;
echo (string)$response . PHP_EOL . PHP_EOL;
print_r($invoice);
?>`

**Comment by NicolasDorier** [comment]
I need you show me YOUR code, completely so I can reproduce.

**Comment by didiandalucia** [comment]
Thats 1 of the codes (3 days ago), they produce the same. Only on our server ist the actual token and the uri correct set!

Equal with filled informations, the request must function correct from the browser? Is that correct or not?

`https://<btcpayserver>/invoices/<invoiceno>/?token=<my security token>`

I cant send you my token here, otherwise you can connect to our server with all functions?!

**Comment by pavlenex** [comment]
It's been quite a while ,has this issue been resolved?

**Comment by cd2357** [comment]
FYI: Got the exact same error, turned out the issue was I was trying to lookup the invoice from an unpaired client (i.e. which had no token). After pairing, it worked.

Pretty obvious in retrospect, but perhaps this hint helps others who are new to the API.
