### ISSUE TITLE
Displaying sats in a more user-friendly way (spacing)

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1146]
As discussed in #1143 sats should be displayed with spacing on an invoice page. Like `10 000`instead of `10000`

![Screen Shot 2019-11-10 at 2 42 01 PM](https://user-images.githubusercontent.com/1934678/68552135-7d5fe300-03c8-11ea-85bd-c14883aafe05.png)

**Comment by bolatovumar** [comment]
@pavlenex why limit the display to just spaces? As far as I'm aware .NET makes it easy to have culture-specific formatting for numbers.

**Comment by pavlenex** [comment]
I like spacing because it is an easy solution that's pleasant to the eye, no other reason.
