### ISSUE TITLE
1 Sat = USD in invoice rates when using satoshi

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1147]
**Is your feature request related to a problem? Please describe.**
[As described here by @NicolasDorier ](https://github.com/btcpayserver/btcpayserver/pull/1143#issuecomment-552414223)using 1 sat = USD would be better looking and future-proof.
![sats](https://user-images.githubusercontent.com/36959754/68650174-9a112d80-0524-11ea-8da6-c4cbc3c55753.png)

**Describe the solution you'd like**
Display the rate for 1 satoshi if people are displaying sats on the invoice.

**Comment by knocte** [comment]
IMO it should say "Exchange rate" not "Tea shop", on the left, and then have two lines:

```
1 bitcoin = $9,066.62 (USD)
1 sat = 0.0000906662 (USD)
```

**Comment by knocte** [comment]
Or even better, showing the sats amount in USD (rounding to only two decimals for the latter):

```
1 bitcoin (100,000,000 sats) = $9,066.62 (USD)
11030 sats ~= 1.00 (USD)
```
