### ISSUE TITLE
New Login page lets me log in via port 80

### ISSUE THREAD

**Issue by 21isenough** [btcpayserver/btcpayserver#1149]
I just noticed that the new login page lets me login via an unsecured connection. 

I can access and login via port 80 and only after the login, it displays the "Your access to BTCPay Server is over an unsecured network..." message. Even though the message displays, I'm logged in and have access to all functions.

**Comment by pavlenex** [comment]
@NicolasDorier I remember that we did not allow https registration for people, unless they run on `.local`. 

I noticed one user on Mattermost posted this 

![Screenshot 2019-11-14 at 17 04 16](https://user-images.githubusercontent.com/36959754/68875776-aacbca00-0703-11ea-84c4-c9b3b646a671.png)

His issue was related to [SSL expiration](https://github.com/btcpayserver/btcpayserver-doc/issues/351) `export BTCPAY_ADDITIONAL_HOSTS="raspberrypi.local,btcpay.local, 192.1.1.1"` where `192.1.1.1` was the IP Let's Encrypt was unable to issue certificate for.

After excluding the IP, his instance got up and running without issues on https and http was no longer accessible.

What confused me was the ability to register on https without any warring, so posting this for further investigation as it's beyond my knowledge.
