### ISSUE TITLE
Server settings: Logs !! information blank & missing on GUI on BTCPay Version .137

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver#1157]
**Describe the problem/bug**
Server settings: Logs: Logs are showing blank in BTCPay Version .137 
Server settings: Logs worked in all versions before this update! .135 etc etc

![Screenshot 2019-11-14 at 09 18 25](https://user-images.githubusercontent.com/30862925/68843811-a5995b80-06c0-11ea-98cc-a7cca14ce613.png)

old working version before the .137 update

![Screenshot 2019-11-14 at 09 19 35](https://user-images.githubusercontent.com/30862925/68843878-bfd33980-06c0-11ea-8312-f5c14f5c4db0.png)

same blank Server settings: Missing Logs problem on different deployments!!

**Comment by NicolasDorier** [comment]
I indeed touched something there not long ago... will check

**Comment by Eskyee** [comment]
I think missing <a href="/server/logs/btcpayblaaaablaaaa.log">btcpayblaaaablaaaa.log</a>

something like this ??

**Comment by Eskyee** [comment]
<img width="1143" alt="Screenshot 2019-11-14 at 09 40 37" src="https://user-images.githubusercontent.com/30862925/68845138-dbd7da80-06c2-11ea-8e79-ac92454fd5d9.png">

**Comment by Eskyee** [comment]
<img width="1143" alt="Screenshot 2019-11-14 at 09 45 54" src="https://user-images.githubusercontent.com/30862925/68845774-d4fd9780-06c3-11ea-806e-3d93d469970c.png">
