### ISSUE TITLE
Fixing some CSS bugs

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#1159]
**Describe the problem/bug**

With the latest styling change from @dennisreimann and @rockstardev there is a few style to fix.

1. We lost the left border of the current menu
2. The title of the page should be aligned to the left
3. There is no "hover" effect when passing the mouse on the line of the row.
4. The font size for the lines in the row is bigger than what was before.

Before

![image](https://user-images.githubusercontent.com/3020646/68915979-7a3d6c00-07a7-11ea-98fc-811b80d674c9.png)

After

![image](https://user-images.githubusercontent.com/3020646/68916014-9d681b80-07a7-11ea-9417-aaadeed00c3d.png)

**Comment by rockstardev** [comment]
I think header should remain centered to be consistent with rest of the website. If needed we can address this later.

I've addressed all the other issues in my commit. When @dennisreimann is online he can take a look at exact styling of `td` (font-size & padding) when it comes to new design vs old design.

![Design after fixes](https://user-images.githubusercontent.com/5191402/68917706-1a0be300-0731-11ea-9c83-888f3479fc63.png)

**Comment by NicolasDorier** [comment]
awesome thanks!
