### ISSUE TITLE
Error 500 in stores setup

### ISSUE THREAD

**Issue by andres-pinilla** [btcpayserver/btcpayserver#116]
Hello,

I just updated to version v1.0.1.80.

When I try to access to configure stores, I get a 500 error.

**Comment by Eskyee** [comment]
hello, I can confirm v1.0.1.80 is working,
no problems with configuring stores, and everything is working fine, 
I quite sure the error is on your side andres-pinilla

**Comment by NicolasDorier** [comment]
wow, can you see the logs ?

**Comment by Eskyee** [comment]
@NicolasDorier 
No, I tested as a user, then admin,

**Comment by andres-pinilla** [comment]
@NicolasDorier Hello, could you tell me what logs should I check?

**Comment by Eskyee** [comment]
@NicolasDorier I used docker logs, and sent u

**Comment by NicolasDorier** [comment]
Problem identified will push new version in around 20-30 min

**Comment by NicolasDorier** [comment]
New version out @andres-pinilla please update! Sorry for the inconvenience.
