### ISSUE TITLE
Improve Pin entering UI (hover) - BTCPay Vault

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1179]
A nit, but would be nice to have a hover effect when inputting pin, just so that people are aware something is going on, since the pin input field is tiny.

![pin](https://user-images.githubusercontent.com/36959754/69229137-28209000-0b85-11ea-93d7-c80970422123.gif)

**Comment by NicolasDorier** [comment]
Closing, there is now a "feel in gray" animation.
