### ISSUE TITLE
More descriptive error page when attempting a payment while node is syncing.

### ISSUE THREAD

**Issue by ddustin** [btcpayserver/btcpayserver#1180]
**Is your feature request related to a problem? Please describe.**
When setting up for the first time an eager user may attempt a payment before the node has synced. Currently in this situation HTTP code 500 is returned and a log message describing the problem happens.

**Describe the solution you'd like**
It would be great if a page loaded showing the either 1) that the node hasn't synced yet, or 2) whatever the latest log messages were. Or perhaps both!

Probably should only show it if logged in, so maybe another page saying "an error occurred" with a login button if they're not logged in.

**Describe alternatives you've considered**
Just a simple page saying "an error occurred, check logs" would probably go a long way and be fairly easy to implement.

**Provide examples**
Many ways to skin it depending on how ambitious your feeling. The simplest would just be a white page, black text that says "an error occurred, check logs."

**Additional context**
Nope! That's it.

**Comment by ddustin** [comment]
This happened in response to a POST to https://buy.koinkeep.com/api/v1/invoices using the HTML provided under Store -> Pay Button

**Comment by ddustin** [comment]
This happened in response to a POST to /api/v1/invoices from HTML generated from Store -> Pay Button

**Comment by NicolasDorier** [comment]
would you have the stacktrace of the ugly error appearing?
