### ISSUE TITLE
Add pasphrase option for Trezor Model T

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1185]
Currently we don't have an option for passphrase  for Trezor T, only for Trezor One.
It should have the same UI, but for some reason it does not.
![passphrase](https://user-images.githubusercontent.com/36959754/69340992-fb45a900-0c68-11ea-8437-ae0aa66bb3f4.PNG)

To replicate, enable passphrase protection on Trezor T, try to import into store derivation settings, nothing happens.

**Comment by pavlenex** [comment]
@NicolasDorier 
Ok, so on Trezor T (because it's touch-screen) you have an option to enter passphrase on:
- device
- host
Of course, it is way safer to do it on device itself, but in case you want to do it on a host, btcpay just ignores it and exports xpub.

The JS error in console is this
```
XML Parsing Error: syntax error
Location: http://localhost:65092/hwi-bridge/v1
Line Number 1, Column 1:
```

**Comment by pavlenex** [comment]
Well, this is not fixed. As there's no option for user to input passphrase on Trezor T.

**Comment by NicolasDorier** [comment]
@pavlenex does your Trezor T has passphrase enabled?

**Comment by pavlenex** [comment]
Yes it does.
1. Enable passphrase on Trezor T
2. Import xpub
3. BTCPay prompts for passphrase on the host (device does not even show if you want to enter the passphrase on device or a host)

**Comment by pavlenex** [comment]
With latest commit and latest firmware it's different.

1. Connect to Trezor T
2. You see the passphrase field on BTCPay, you click continue 
3. On Trezor T you now see option to enter passpharse on host or on device

The steps should be reversed:
1. Connect Trezor T
2. On Trezor T choose if you want passphrase on host or on device
3. If you select host, then btcpay shows passphrase input

**Comment by pavlenex** [comment]
Tested in dev env with [2e0db1](https://github.com/btcpayserver/btcpayserver/commit/2e0db1a4304aeb5c9367fc8a711d11154f717255) My comment above is still valid, the order is reversed for some reason.

**Comment by NicolasDorier** [comment]
`On Trezor T you now see option to enter passpharse on host or on device` you mean that Trezor T is prompting you this?

**Comment by pavlenex** [comment]
@NicolasDorier correct, check this
![serveimage](https://user-images.githubusercontent.com/36959754/69492267-a8eecd00-0ea0-11ea-8332-30ea734a54af.jpg)

**Comment by pavlenex** [comment]
Added & tested in [de2e222](https://github.com/btcpayserver/btcpayserver/commit/de2e222ae5bfe56a9229f1868854bd01705f57ac).
