### ISSUE TITLE
LND Seed Backup - NOT WORKING

### ISSUE THREAD

**Issue by whiteyhat** [btcpayserver/btcpayserver#1188]
## Problem

After following this guide step by step https://blog.btcpayserver.org/btcpay-lnd-migration the service for LND Seed Backup is still the same.

## Screenshots
<img width="646" alt="Captura de pantalla 2019-11-22 a las 12 31 12" src="https://user-images.githubusercontent.com/31220861/69437656-03bee200-0d44-11ea-845f-2507ac8d78ee.png">

## Context
I made sure:
- I closed all my channels
- I wiped/recreate the volume for LND

**Comment by rockstardev** [comment]
No, the likely problem is that volume doesn't get deleted because it's referenced by some other container.

@whiteyhat needs to paste terminal output that he gets when running `./recreate_bitcoin_lnd.sh` so that we confirm that's what's going on.

**Comment by whiteyhat** [comment]
@rockstardev It seems there was an issue during the first `./recreate_bitcoin_lnd.sh` maybe it was my connection to the server.

 I did it again and it is working great
