### ISSUE TITLE
RETURN URL IS BROKEN

### ISSUE THREAD

**Issue by whiteyhat** [btcpayserver/btcpayserver#1189]
## Problem 
When trying to log in with a specified `return_url` it does not:
- Log in
- Return to the specified `URL`

**Comment by bolatovumar** [comment]
@whiteyhat could you elaborate with reproduction steps?

**Comment by pavlenex** [comment]
This is very annoying bug, that is mostly visible when you update btcpay server and stay on that page, refresh it then your login credentials don't work. Also if you ever try to visit a an url from your browser that's bookmarked, and try to login to that page it won't work.

To replicate:
1. Create an account on mainnet.demo.btcpayserver.org/
2. Log out
3. Visit https://mainnet.demo.btcpayserver.org/Account/Login?ReturnUrl=%2Finvoices
4. Try to log in
5. You won't be able to log in

**Comment by bolatovumar** [comment]
Tried repro-ing this issue with @rockstardev in our session today and it seems to be fixed.

@whiteyhat in you example you are `return_url` parameter when you should be using `ReturnUrl`.  This seems to be the root problem in your example.

**Comment by klokit-co** [comment]
Same issue seen here
Logging in from : /Account/Login?ReturnUrl=%2Fserver%2Fusers
(probably last viewed page that has timed out)
Replicated by logging in from home page, logging out, going to above url and trying to log in.
Login unsuccessful, returns to above url, no error message displayed.
Environment: hosted on lunanode (Ubuntu 16.04 64-bit (template))
 v1.0.3.137

**Comment by bolatovumar** [comment]
Ok, not sure what's going on in your case @klokit-co. I checkout out BTCPay `v1.0.3.137` and logged in through `/Account/Login?ReturnUrl=%2Fserver%2Fusers`. I was able to log in successfully and I landed on `/server/users` page as expected.
