### ISSUE TITLE
Need translation for "transaction count"

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#119]
New translation string:

* [x] English @lepipele
* [x] Icelandic @Saevar2000
* [x] Spanish
* [x] Japanese @junderw
* [x] Dutch @LinoxBE
* [x] German @mutedstorm
* [x] French @NicolasDorier
* [x] Czech @pajasevi
* [x] Portuguese @rsandrade

This commit https://github.com/btcpayserver/btcpayserver/pull/117 added tranlsation string here https://github.com/btcpayserver/btcpayserver/pull/117/files#diff-e2137de459fded7a1252477aad4afe40R51 by @lepipele 

Meant to fix this part of the checkout page https://github.com/btcpayserver/btcpayserver/issues/111

**Comment by lepipele** [comment]
For German, can we call on someone to look through them and then add these two also? I've done initial pass using Google Translate. I've tweeted today about this... if you can retweet or do another call for German speaking crowd - it would be very helpful:

https://twitter.com/codeoverwhelmin/status/985181844462297090

**Comment by NicolasDorier** [comment]
thanks! :D

**Comment by junderw** [comment]
https://help.github.com/articles/creating-a-commit-with-multiple-authors/

btw you can co-author with me: ;-)

1. Author is usually auto-set by your git client.
2. Co-author is just literally an addition to the commit comment. (Two empty lines, then on the third line write:)

```
normal commit message


Co-authored-by: githubUserName <Email@Domai.tld>
```

You can get my email from my other commits using `git log --author=junderw`

**Comment by NicolasDorier** [comment]
Sorry, I did not know. Will do next time, I prefer not amending an already pushed commit so people don't have to do a `git push --force`.

**Comment by junderw** [comment]
ahh it's ok. Just so you know in the future.

**Comment by NicolasDorier** [comment]
will settle that with beers.

**Comment by NicolasDorier** [comment]
Only Icelandic by @Saevar2000 is missing yay! :)

**Comment by lepipele** [comment]
@Saevar2000 you alive man? Please give us translation for those two so we can close issue.

**Comment by NicolasDorier** [comment]
Yay he just did!
