### ISSUE TITLE
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid"

### ISSUE THREAD

**Issue by hakonamatata** [btcpayserver/btcpayserver#1191]
Hi

BTCPay works, invoices comes in and everything seems to work fine, but when I ssh into my machine and try: 
` bitcoin-lncli.sh getinfo`

I get this error:

`bitcoin-lncli.sh getinfo`
`[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid"`

I also wanted to ask if there was any way to do back ups? Maybe just run a cron job that export all channel info every hour and upload it to an ftp server, or something like that.

**Comment by NicolasDorier** [comment]
Can you cross post this error on LND? seems like an LND bug.
There is no way from BTCPay to do periodic backup, you might check RTL.
For the periodic backup, there is nothing done in BTCPay speicifcally for this.

**Comment by hakonamatata** [comment]
> Can you cross post this error on LND

https://github.com/lightningnetwork/lnd/issues/3780

**Comment by hakonamatata** [comment]
After updating BTCPay server, it worked again.
