### ISSUE TITLE
Set BTCPayServer REGTEST to TESTNET

### ISSUE THREAD

**Issue by sean208208** [btcpayserver/btcpayserver#1194]
**Describe the problem/bug**
I refer to this video to setting up BTCPayServer development environment on Linux.
[https://www.youtube.com/watch?v=j486T_Rk-yw&t=](url)

And I want to set REGTEST to TESTNET.

Dose anyone can teach me how to do it?

Thanks 

**My environment**
* Version of BTCPay Server: v1.0.3.143 
* Version of Dotnet: 2.1.802 
* Version of Docker: 18.09.7, build 2d0083d 
* Deployment method: Visual Studio Code 1.40.1

**Comment by NicolasDorier** [comment]
Why do you want Testnet? Testnet is useless for a developer environment.

**Comment by sean208208** [comment]
> Why do you want Testnet? Testnet is useless for a developer environment.

I want to import my wallet for test btcpay flowchart

**Comment by pavlenex** [comment]
You can easily [test payments from regtest itself.](https://github.com/btcpayserver/btcpayserver/tree/master/BTCPayServer.Tests#how-to-manually-test-payments)

Just enter any xpubkey (you can get it [here](https://iancoleman.io/bip39/) for example).

For testnet, afaik, you'd need to deploy a server and use `NBITCOIN_NETWORK="testnet"` as an [environment variable](https://github.com/btcpayserver/btcpayserver-docker#environment-variables).

IMO regtest is way better for development testing.

**Comment by sean208208** [comment]
@pavlenex Thanks for your information, I will try by myself.
