### ISSUE TITLE
Altering access to BTCPay server (access for pay)

### ISSUE THREAD

**Issue by maurocolella** [btcpayserver/btcpayserver#12]
Hello,

I have setup BTCPay server on a Linux instance.

We are interesting in altering the registration flow, in order to enable registration for a fee somehow.

Is this a possibility currently? We would prefer not to fork for this; I'd be happy to contribute some work to help put together an implementation.

**Comment by NicolasDorier** [comment]
Concept ACK. This is a feature I wanted to add, but my first priority now is Lightning Network.
Do you plan on working on it ? if so, come on the slack, there is a #dev channel, I can quickly respond to questions there to help you implement.

**Comment by lepipele** [comment]
@maurocolella you still interested in helping making this happen?

**Comment by maurocolella** [comment]
I am sorry gents, the project has taken a different direction for the time being.

**Comment by lepipele** [comment]
OK, thanks for letting us know @maurocolella ... and update us if that changes, we'll be around.

**Comment by maurocolella** [comment]
Will do. Without revealing too much, management on this project is looking to expand. 

We are currently looking for staff with a background in cryptoanalysis or finance to help.

**Comment by lepipele** [comment]
@maurocolella good luck on that... my experience is that it's pretty hard to find good people to work on crypto related projects. The good ones are already employed... and with those who could be good teammates you often need to "sell idea of crypto" (they listen to mainstream media and think that Bitcoin is used exclusively by bad people).

For my experience: if you have funding try searching http://meetup.com for local crypto meetups and look for people there... 
If you really, really like someone's work - ping him here on GitHub. That can work great sometimes.

**Comment by maurocolella** [comment]
Thank you so much for the advice.
