### ISSUE TITLE
Can btcpayserver run on android phone?

### ISSUE THREAD

**Issue by sean208208** [btcpayserver/btcpayserver#1204]
Does someone run btcpayserver with fullnode and NBXplorer on android phone?

I want to try btcpayserver run on my phone

Anyone can give some article or hint for me?

Thanks

**Comment by Kukks** [comment]
No, no one has done it as far as I know and it is not trivial to pull off.

**Comment by sean208208** [comment]
Hi @Kukks ,
Thank you for your reply,

That is possible use phone to link local btcpayserver and pay?

**Comment by Kukks** [comment]
BtcPay runs as a web application. Just open it in the phone browser.

**Comment by pavlenex** [comment]
Closing this one as the question seems to be answered.
