### ISSUE TITLE
[Vault] UX -  Signing the transaction... (add confirm the transaction on device)

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1207]
**Describe the problem/bug**
When using Vault, `Signing the transaction...` is not a good enough indicator, because users can just wait and nothing happens.

Instead I propose we use something like "Confirm the transaction on your device" or whatever is more technically correct. That tells users what exactly they need to do. 

After the transaction is confirmed, I suggest we then add `Signing the transaction, please wait...` as the next step, with some sort of **animated** loading icon (we have that for U2F when adding a new device).

![Screenshot 2019-12-02 at 22 18 13](https://user-images.githubusercontent.com/36959754/69996104-a8fe6500-1551-11ea-9eb4-5768b5b315b4.png)

The reason I think loading indicator  is needed, is because on some devices (especially Ledger S in my tests, signing can take up to 20-30 seconds) so we must indicate that users should wait.

**Your environment**
* Version of BTCPay Server:  v1.0.3.144
* Deployment method:  Docker
* Other relevant environment details: Vault 0.0.9, MacOS

**Screenshots/Links**
#### Current
![Screenshot 2019-12-02 at 21 36 17](https://user-images.githubusercontent.com/36959754/69995564-9f283200-1550-11ea-8955-ebdac7f1ba22.png)
#### Proposed
![Screenshot 2019-12-02 at 22 19 49](https://user-images.githubusercontent.com/36959754/69996204-df3be480-1551-11ea-978e-8692d0a532b5.png)

**Comment by NicolasDorier** [comment]
I can't know when the user confirmed on the device. But at least I can show better message
