### ISSUE TITLE
Edit Name in User Settings

### ISSUE THREAD

**Issue by conscott** [btcpayserver/btcpayserver#1216]
In server settings, there are two columns: User and Email

![name](https://user-images.githubusercontent.com/14220652/70229119-7de06500-174d-11ea-99fd-b02fcd2b3198.png)

However the name portion isn't editable and always matches email, which at least makes it redundant. 

**Proposal**
Have `Name`  field in "Create account" page _and/or_ have it as an option when clicking `Edit`

**Alternative**
Simply remove the `Name` column, as it always matches email and is redundant.

**Comment by bolatovumar** [comment]
I just took a look through the code and I can't find `UserName` property being used anywhere. It seems completely redundant to me. Was there a reason it was added in the first place? If not, should it be removed from the modal then? Or just from the view?

**Comment by Kukks** [comment]
We could remove it from the UI. Technically, We can't remove it from the
system as it's part of the asp.net Identity system though

**Comment by Eskyee** [comment]
for third party hosts, it helps having User and Email the same, as for admin purpose, helps keeps house keeping simple

**Comment by bitcoinbrisbane** [comment]
> I just took a look through the code and I can't find `UserName` property being used anywhere. It seems completely redundant to me. Was there a reason it was added in the first place? If not, should it be removed from the modal then? Or just from the view?

Its probably the .net auth framework.  It puts an email and username by default.

**Comment by bolatovumar** [comment]
@bitcoinbrisbane yeah, Kukks clarified this above

**Comment by Kukks** [comment]
fixed in #1268
