### ISSUE TITLE
How do I turn off LND autopilot?

### ISSUE THREAD

**Issue by hakonamatata** [btcpayserver/btcpayserver#1223]
Hi

I am trying to migrate BTCPay server to a server using a wallet seed, but in order to do so I first have to close all channels. 

Easy enough, except since autopilot it on, as soon as I have closed all channels. New ones are created automatically. 

I tried changing the lnd.conf file, but as soon as I do: 

`docker restart btcpayserver_lnd_bitcoin`

The lnd.conf file is updated with autopilot on again.

**Comment by pavlenex** [comment]
It's an [environment variabl](https://github.com/btcpayserver/btcpayserver-docker#generated-docker-compose-)e, just comment it out `opt-lnd-autopilot`

**Comment by hakonamatata** [comment]
> 
> 
> It's an [additional fragment ](https://github.com/btcpayserver/btcpayserver-docker#generated-docker-compose-), just comment out `opt-lnd-autopilot` from `BTCPAYGEN_ADDITIONAL_FRAGMENTS`
> 
> For, example if your additional fragment have
> 
> ```
> export BTCPAYGEN_ADDITIONAL_FRAGMENTS"opt-save-storage;opt-lnd-autopilot"
> ```
> 
> You should:
> 
> ```
> export BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-save-storage"
> . btcpay-setup.sh -i
> ```
> 
> Make sure you don't comment out other additional fragments if you're using them, especially if you're using pruning.

Thanks that helps, only that caused a new problem. I ran your command: 

`export BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-save-storage"`

This sets up a pruned bitcoin node, that was not my intention, when I removed this option again I got this:

```
2019-12-12T17:21:15Z Checking all blk files are present...
: You need to rebuild the database using -reindex to go back to unpruned mode.  This will redownload the entire blockchain.
Please restart with -reindex or -reindex-chainstate to recover.
2019-12-12T17:21:15Z LoadBlockIndexDB(): Block files have previously been pruned
2019-12-12T17:21:15Z : You need to rebuild the database using -reindex to go back to unpruned mode.  This will redownload the entire blockchain.
Please restart with -reindex or -reindex-chainstate to recover.
2019-12-12T17:21:15Z Aborted block database rebuild. Exiting.
2019-12-12T17:21:15Z Shutdown: In progress...
2019-12-12T17:21:15Z scheduler thread interrupt
2019-12-12T17:21:15Z Shutdown: done
```

How can I -reindex ?

**Comment by hakonamatata** [comment]
never mind, got it indexing

```
btcpay-down.sh
# Delete 'blocks' and 'chainstate' folders
rm -rf /var/lib/docker/volumes/generated_bitcoin_datadir/_data/blocks
rm -rf /var/lib/docker/volumes/generated_bitcoin_datadir/_data/chainstate
btcpay-up.sh
```

**Comment by pavlenex** [comment]
@hakonamatata Glad you solved it, I'll then go ahead and close this issue, if it persists, let us know and we'll re-open it.
