### ISSUE TITLE
MySQL support broken in recent versions

### ISSUE THREAD

**Issue by ketominer** [btcpayserver/btcpayserver#1224]
**Describe the problem/bug**
A migration fails because of incorrect types used for Id columns

**Your environment**
btcpayserver.dll v1.0.3.146 (may affect earlier too)

**Logs (if applicable)**
MySql.Data.MySqlClient.MySqlException (0x80004005): BLOB/TEXT column 'Id' used in key specification without a key length ---> MySql.Data.MySqlClient.MySqlException (0x80004005): BLOB/TEXT column 'Id' used in key specification without a key length

**Possible solutions**
Solution 1 (best): Use varchar with a fixed length for the Id column (will be much faster)
Solution 2 (workaround): Add the length to be used in key when creating the key

**Comment by ketominer** [comment]
Additional info:
BLOB/TEXT column 'Id' used in key specification without a key length : CREATE TABLE `OpenIddictApplications` (
    `ClientId` varchar(100) NOT NULL,
    `ClientSecret` longtext NULL,
    `ConcurrencyToken` varchar(50) NULL,
    `ConsentType` longtext NULL,
    `DisplayName` longtext NULL,
    `Id` longtext NOT NULL,
    `Permissions` longtext NULL,
    `PostLogoutRedirectUris` longtext NULL,
    `Properties` longtext NULL,
    `RedirectUris` longtext NULL,
    `Type` varchar(25) NOT NULL,
    `ApplicationUserId` longtext NULL,
    CONSTRAINT `PK_OpenIddictApplications` PRIMARY KEY (`Id`),
    CONSTRAINT `FK_OpenIddictApplications_AspNetUsers_ApplicationUserId` FOREIGN KEY (`ApplicationUserId`) REFERENCES `AspNetUsers` (`Id`) ON DELETE RESTRICT
)

longtext is 16 MBs!!! Not very useful for an Id... consider replacing most (all?) longtext with appropriate types (varchar(xx))

**Comment by NicolasDorier** [comment]
fuck this is openid... something we don't even use.

**Comment by NicolasDorier** [comment]
@ketominer can you give me the line that crash? I plan to remove openid until they fix everything.

**Comment by NicolasDorier** [comment]
@ketominer do you know when did it last work? do you have special commits?

**Comment by NicolasDorier** [comment]
might be related. https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/936

**Comment by PinpointTownes** [comment]
@ketominer I opened to track future improvements in OpenIddict to assign max lengths to columns like `DisplayName` or `ConsentType`  (https://github.com/openiddict/openiddict-core/issues/868), but the fact the primary key columns (`Id`) are declared as `longtext` is super weird, and not the intended behavior.

I'll work with @NicolasDorier to determine what's causing that.

**Comment by NicolasDorier** [comment]
It may be that the old migrations are somehow conflicting with the new...

I wonder if I can just cleanup all the migration classes and replace it by a text file script.

**Comment by NicolasDorier** [comment]
When I run `dotnet ef script` I get this:

```
CREATE TABLE "OpenIddictApplications" (
    "ClientId" TEXT NOT NULL,
    "ClientSecret" TEXT NULL,
    "ConcurrencyToken" TEXT NULL,
    "ConsentType" TEXT NULL,
    "DisplayName" TEXT NULL,
    "Id" TEXT NOT NULL CONSTRAINT "PK_OpenIddictApplications" PRIMARY KEY,
    "Permissions" TEXT NULL,
    "PostLogoutRedirectUris" TEXT NULL,
    "Properties" TEXT NULL,
    "RedirectUris" TEXT NULL,
    "Type" TEXT NOT NULL,
    "ApplicationUserId" TEXT NULL,
    CONSTRAINT "FK_OpenIddictApplications_AspNetUsers_ApplicationUserId" FOREIGN KEY ("ApplicationUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);
```

**Comment by NicolasDorier** [comment]
ah maybe this is not for mysql...

**Comment by NicolasDorier** [comment]
@ketominer I am trying to find out what the fuck remove the lenght... can you tell me the last version of btcpayserver which worked?

**Comment by ketominer** [comment]
I don't know which one is the last that worked, we keep v1.0.3.102 for now because no time to test every version between v1.0.3.102 and v1.0.3.146 :)

**Comment by NicolasDorier** [comment]
@ketominer so the guy maintaining the MySql plugin we use has been very helpful.

In a nutshell, what we did to support several db has been quite fragile and flawed.
I can fix this, but I need to think a bit on how to refactor the mess.

**Comment by NicolasDorier** [comment]
So basically I need to maintain a different set of scripts only for MySql

Discussion here

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/936#issuecomment-568353924

This will make adding any table quite difficult and error prone.
We need MySQL to be integrated in CI if you want to prevent breakage in the future, I won't work on doing it though. Meanwhile I will try to fix your issues without testing and crossing fingers.
