### ISSUE TITLE
Invalid bitcoin address error

### ISSUE THREAD

**Issue by beetlevw** [btcpayserver/btcpayserver#1227]
I am testing and have tried different ways of store wallets.
Electrum Standard Segwit
Electrum Standard Legacy

I am able to get it to process a transaction with and andriod device and with and electrum wallet on the sender side. Also a bitcoin developed wallet.

However when attempting from an Iphone with various wallets (Bitcoin, etc.) the bitcoin address is always invalid.

Any thoughts?

Or suggestions.

Looks like a hardware wallet is best?

Thank you.

**Comment by bolatovumar** [comment]
@beetlevw what do you mean by "address is always invalid"? You are trying to pay an invoice but your wallet can't pay to the address generated by BTCPay?

**Comment by pavlenex** [comment]
I believe the issue here is that @beetlevw is using SegWit (addresses starting with bc1) and not all wallets are compatible with it, if you want compatibility as a merchant, you should use p2sh (addressees starting with 3).

## From our documentation 

> IMPORTANT NOTE: If you're a merchant, instead of SegWit (Bech32), it's recommended to use SegWit wrapped (P2SH) format. [This guide](https://www.youtube.com/watch?v=-1DBJWwA2Cw) explains how to create P2SH wallet in Electrum that's more suited for merchants, due to compatibility with legacy wallets customers use.

**Comment by beetlevw** [comment]
Morning, wallet was the issue.

Thank you!!!
