### ISSUE TITLE
BitcoinAverage removed the "Free" tier plan

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#1230]
A large number of merchants are currently relying on the free tier of the BitcoinAverage plan, however as they announced today, [https://bitcoinaverage.com/blog/pricing-changes](https://bitcoinaverage.com/blog/pricing-changes), they have ended support for this and will be requiring merchants to pay after 7 days. 

This will cause huge issues, potentially shutting down stores.

**Comment by bolatovumar** [comment]
Yeah, I got an e-mail from them as well. Looks like this will be a major issue if nothing is done.

**Comment by thehapax** [comment]
Why can't we just make our own price feed by pulling data from major exchanges through their APIs and consolidating, or even better allow an option to select which group of feeds they'd like? Just thinking of FOSS options here.

**Comment by NicolasDorier** [comment]
@thehapax we are already pulling the data from major exchanges when we can.

However because we need exchange rate before the invoice is created, it means that we continuously get rate every min for like 10 different exchanges. 
This does not scale.

@astupidmoose I will make a PR which remove them as the default provider. However I can't support all they did and would advise to pay them if you have to rely on them. (it depends on which exchange you chose)

**Comment by Kukks** [comment]
I will add an alternative, free option similar to what coin average did
when I have the time. There are plenty of free options available and paying
200 a month for this api is stupid.

**Comment by NicolasDorier** [comment]
200 a month?

**Comment by Kukks** [comment]
https://apiv2.bitcoinaverage.com/#websocket-api-v3

**Comment by bolatovumar** [comment]
@Kukks @NicolasDorier they have plans from $12 to $599 a month: https://bitcoinaverage.com/#plans

**Comment by astupidmoose** [comment]
In order to use exchange specific APIs (v2 or v3) you need to use the $200 per month plan. 

We've already moved to an exchange specific connection that's built in to btcpay

**Comment by NicolasDorier** [comment]
We don't use websockets.

**Comment by NicolasDorier** [comment]
Please for those begging for support for their favorite exchange, a very important thing is if you can give us also the link to their API.

**Comment by cryptofuture** [comment]
Why not just to use rates from [coingecko](https://www.coingecko.com/en/api) by default?

**Comment by NicolasDorier** [comment]
Coingecko offer unified API for querying different exchanges? If yes, then we can switch to this for next release for exchange feed.

**Comment by cryptofuture** [comment]
> Coingecko offer unified API for querying different exchanges? If yes, then we can switch to this for next release for exchange feed.

I think, yes at least `curl -X GET "https://api.coingecko.com/api/v3/coins/bitcoin" -H  "accept: application/json"` response also includes price data from multiple exchanges

**Comment by NicolasDorier** [comment]
Thanks, I will take a look.

**Comment by thehapax** [comment]
> Coingecko offer unified API for querying different exchanges? If yes, then we can switch to this for next release for exchange feed.

There is also ccxt and nomics API as other options to Coingecko 
https://github.com/ccxt/ccxt
https://p.nomics.com/cryptocurrency-bitcoin-api

both are free for just bitcoin price feed usage

**Comment by pavlenex** [comment]
CoinGecko now replaces BitcoinAverage by default, added in #1264. If you face issues with broken stores, you just have to update your btcpay.
