### ISSUE TITLE
Minor errors as reported by JetBrains Rider

### ISSUE THREAD

**Issue by bolatovumar** [btcpayserver/btcpayserver#1235]
After seeing @Kukks praise JetBrains Rider endlessly I decided to try it and it reported a few potential issues. I'm just gonna add them here in case any of these are actually issues and not just the IDE making things up.

![Screen Shot 2019-12-25 at 9 54 40 PM](https://user-images.githubusercontent.com/1934678/71460817-3eac9f00-2762-11ea-8191-d2bcac86cede.png)

Error is `<BTCPayServer>\Controllers\ManageController.2FA.cs:6647 Cannot resolve view 'GenerateRecoveryCodesWarning'`.

This one is weird because this method doesn't seem to be used anywhere outside of itself and there is no corresponding view. Not sure what's going on here.

---

![Screen Shot 2019-12-25 at 9 55 19 PM](https://user-images.githubusercontent.com/1934678/71460989-f93ca180-2762-11ea-9e3f-2ac94ce3717a.png)

Error is: `  <BTCPayServer>\Controllers\ManageController.cs:5079 Cannot resolve view 'SendVerificationEmail'`.

This one is weird because this is a POST method but it tries to return a view which doesn't exist if model state is not valid.

---

![Screen Shot 2019-12-25 at 9 55 32 PM](https://user-images.githubusercontent.com/1934678/71461025-3012b780-2763-11ea-8d87-2597ec840276.png)

Error is: `  <BTCPayServer>\Views\Invoice\ListInvoices.cshtml:20248 Block statements must be enclosed in "{" and "}".  You cannot use single-statement control-flow statements in CSHTML pages.`.

This one is pretty simple but I'm not sure if it's actually a problem or the IDE just making things up. Won't hurt to add the curly braces anyway.

---

![Screen Shot 2019-12-25 at 9 55 46 PM](https://user-images.githubusercontent.com/1934678/71461098-72d48f80-2763-11ea-8ada-ff4ea8428e95.png)

Error is: `<BTCPayServer>\Views\Server\CreateTemporaryFileUrl.cshtml:1089 Cannot choose method from method group. Did you intend to invoke the method?`.

Again, not sure if this is actually an issue but it does look weird. Wrapping the statement in curly braces does "fix" the issue and Rider becomes happy.

---

![Screen Shot 2019-12-25 at 9 56 32 PM](https://user-images.githubusercontent.com/1934678/71461160-b0d1b380-2763-11ea-9864-9bd10982478a.png)

This one is same as above.

---

![Screen Shot 2019-12-25 at 9 57 24 PM](https://user-images.githubusercontent.com/1934678/71461166-b7f8c180-2763-11ea-8dd4-39c76941de26.png)

Errors are: `  <BTCPayServer>\Views\Server\_Nav.cshtml:121 Cannot resolve action 'Users'` and `  <BTCPayServer>\Views\Server\_Nav.cshtml:851 Cannot resolve action 'Logs'`.

This one makes sense since `Users` and `Logs` actions don't actually exist, they are called something else. Renaming the actions "fixes" this issue.

---

Thoughts about these @NicolasDorier @Kukks?

**Comment by NicolasDorier** [comment]
Quite cool, will check around but some of the errors seems genuine bug.

**Comment by NicolasDorier** [comment]
@bolatovumar I wonder if it is possible to get the linters that Rider is using as part of the CI so we can catch this in the future.

**Comment by bolatovumar** [comment]
@NicolasDorier I think Rider is using its custom analysis engine to analyze the code. It takes quite a while to analyze the entire solution once you open it for the first time. Looks like it's available as a command line tool as well: https://www.jetbrains.com/help/resharper/InspectCode.html

**Comment by bolatovumar** [comment]
@NicolasDorier ok, I tried the command line tool locally and it gives the same output as what you see in the IDE. It does take quite a bit of time to run though.

Command that I used was: `.\InspectCode.exe <path to btcpayserver.sln> --dotnetcoresdk=2.1.602 -o=<path to output file> --severity=ERROR --exclude="**/*.js;**/*.css"`.

This command will only output ERROR severity issues (by default it gives much more) and excludes all *.js and *.css files.

**Comment by pavlenex** [comment]
Closing this one since it will be consolidated into #1235 as earlier agreed with @bolatovumar.
