### ISSUE TITLE
End of year code clean-up

### ISSUE THREAD

**Issue by bolatovumar** [btcpayserver/btcpayserver#1239]
After running the JetBrains code inspection tool it pointed out a bunch of code issues which are not errors but could be cleaned up. Stuff like unnecessary type parameters, unused variables, redundant `using` directives, etc...

It would be nice to clean these things up as end of year activity and start the year off with fresh clean code. Any PR that I make to clean things up would go against this issue.

**Comment by NicolasDorier** [comment]
I wonder if it is possible to include checks as part of CI

**Comment by bolatovumar** [comment]
@NicolasDorier yes, but I wouldn't want these warnings to break the build. They are not errors but just suggestions about dead code and stuff like that. It's probably nice to run the check locally every once in a while and fix up at least some of the issues it brings up.

**Comment by NicolasDorier** [comment]
will you reopen another PR for that?

**Comment by bolatovumar** [comment]
@NicolasDorier i'm meaning to but haven't gotten around to it yet.

**Comment by rockstardev** [comment]
I can do this automatically with CodeMaid. Want me to take over @bolatovumar ?

**Comment by bolatovumar** [comment]
@rockstardev I could do this automatically as well (I actually did it locally to test out). The resulting changeset is so huge that I would not want to submit it. I wanted to go over things manually and clean-up the easy bits which are easy to review first. Feel free to submit something though.

**Comment by rockstardev** [comment]
OK, I have experience with this type of work - will break it down in stages and invite you to review PRs @bolatovumar. 

However we do need @NicolasDorier and @Kukks to finish their PRs first. Because if I start going wild with my tooling - merging pending PRs will be extreme pain with all the changes across complete codebase.

**Comment by bolatovumar** [comment]
sounds good @rockstardev

**Comment by pavlenex** [comment]
On top of above mentioned, just FYI, #1235 is consolidated into this one.

**Comment by bolatovumar** [comment]
Probably won't have time to work on this so closing for now.
