### ISSUE TITLE
Remove "Invoice IPN Notification" from app page

### ISSUE THREAD

**Issue by escapedcat** [btcpayserver/btcpayserver#1241]
> Ok, since we have 4 ACKs for removing this feature, it would be good to close this issue and open a request in the main repository for removing this option from both apps.

[After the comments on another issue](https://github.com/btcpayserver/btcpayserver-doc/issues/401#issuecomment-569124157) people decided this confusing feature should be removed. Therefor these two issue are being closed:

- https://github.com/btcpayserver/btcpayserver/issues/1222
- https://github.com/btcpayserver/btcpayserver-doc/issues/401

**Comment by nleeburch** [comment]
What is an ACK?

**Comment by britttttk** [comment]
Hey @nleeburch check [this issue](https://github.com/bitcoin/bitcoin/issues/6100) explaining ACK :)

**Comment by escapedcat** [comment]
I would give this a try if nobody else is interested :P

**Comment by pavlenex** [comment]
Feel free to tackle it @escapedcat.

**Comment by escapedcat** [comment]
The pay button settings list IPN notifications as well:
![image](https://user-images.githubusercontent.com/1016218/72603574-8ebdf200-3919-11ea-89be-4c0dcbe19e5b.png)

Should these be removed as well?

**Comment by pavlenex** [comment]
@Kukks what do you think about ^ ?

**Comment by Kukks** [comment]
yeah just the email one

**Comment by escapedcat** [comment]
@Kukks sorry, I don't think that answers my question.

> I think I can remove all entries of NotificationEmailWarning and NotificationEmail 

This means all "Sending IPN via Email"-options will be remvoed. For "Pos" and "Pay button".

Could you clarify? Thanks

**Comment by pavlenex** [comment]
Removed in #1337
