### ISSUE TITLE
Does it require a full node?

### ISSUE THREAD

**Issue by naddika** [btcpayserver/btcpayserver#1243]
Does btcpayserver require a full node running on the same machine?

**Comment by bolatovumar** [comment]
@naddika BTCPay comes shipped with a full node and runs it and syncs the blockchain for you.

**Comment by bitcoinbrisbane** [comment]
Btcpayserver talks to https://github.com/dgarage/NBXplorer via port 24444, which in turn talks to btc core via port 8333.

**Comment by pavlenex** [comment]
As guys already mentioned, BTCPay Server already comes with a built in full node. You can read [more on the architecture here ](https://github.com/btcpayserver/btcpayserver-doc/blob/master/Architecture.md)and [how it works here](https://docs.btcpayserver.org/#how-it-works).

**Comment by naddika** [comment]
the size of the full BTC node is 250 Gb. That is, btcpayserver weighs 250+ Gb, right?

**Comment by pavlenex** [comment]
You can [prune](https://meet.jit.si/BTCPayServerTeamRoomHangout) your node.

**Comment by naddika** [comment]
I see. Does running prune node require downloading 250+ Gb **all at once, first**? Or does prunning happen **on the fly**?

**Comment by pavlenex** [comment]
@naddika It happens "on the fly" ✈️ 😄
