### ISSUE TITLE
Not getting confirmation emails

### ISSUE THREAD

**Issue by chovy** [btcpayserver/btcpayserver#1250]
I'm not getting confirmation emails after making a payment request and sending emails.

**Comment by Kukks** [comment]
BTCPay doesn't send out emails for payments

**Comment by pavlenex** [comment]
As Kukks mentioned, BTCPay does not send emails. SMTP settings, for now are only used for reset password.

If you want to extend email sending, try [BTCPay Transmuter, ](https://github.com/btcpayserver/btcTransmuter)there's a whole [#btc-transmuter](https://chat.btcpayserver.org/btcpayserver/channels/btc-transmuter) channel on our [Mattermost](chat.btcpayserver.org/) where you can ask questions and read through convo where some people describe how they set it up.
