### ISSUE TITLE
How do I import wallet file for Monero?

### ISSUE THREAD

**Issue by chovy** [btcpayserver/btcpayserver#1252]
Which files do I upload to btcpayserver?

**Comment by NicolasDorier** [comment]
I don't know. Check monero documentation. All files are in `/var/lib/docker/volumes`

**Comment by Kukks** [comment]
https://web.getmonero.org/resources/user-guides/view_only.html

**Comment by Kukks** [comment]
You just upload the generated view only wallet files from the monero node wallet and enter the password if set.
