### ISSUE TITLE
Send $1700 by link updated to b.account.us

### ISSUE THREAD

**Issue by coin750** [btcpayserver/btcpayserver#1260]

**Comment by pavlenex** [comment]
Spam.

**Comment by coin750** [comment]
{
 "nodeId": "03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134",
 "channelId": "1dcb7d392058b47d6d6561548e82486d901d34f2c35b836a46039f4dc7eebd96",
 "state": "NORMAL",
 "data": {
  "$type": "fr.acinq.eclair.channel.DATA_NORMAL",
  "commitments": {
   "channelVersion": "00000000000000000000000000000000",
   "localParams": {
    "nodeId": "03fc839a859a6052b86cc923b0682e13eca9dc357c3da039c86020633673e68227",
    "channelKeyPath": "m/1455068406'/1623553958'/52044225/952024846",
    "dustLimitSatoshis": "546",
    "maxHtlcValueInFlightMsat": "5000000000",
    "channelReserveSatoshis": "167772",
    "htlcMinimumMsat": "1",
    "toSelfDelay": 2016,
    "maxAcceptedHtlcs": 30,
    "isFunder": true,
    "defaultFinalScriptPubKey": "a9147c84d8655753d5e133932fcdd50fece3ca7d128187",
    "globalFeatures": "",
    "localFeatures": "808a"
   },
   "remoteParams": {
    "nodeId": "03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134",
    "dustLimitSatoshis": "546",
    "maxHtlcValueInFlightMsat": "20000000000",
    "channelReserveSatoshis": "167772",
    "htlcMinimumMsat": "1",
    "toSelfDelay": 720,
    "maxAcceptedHtlcs": 30,
    "fundingPubKey": "0378e5392a9759094b44549019a44ae47818902295145004afa290407548d2a7d4",
    "revocationBasepoint": "028829a06f9784254b88904c70d62ff22632fe9bea48ca4e26f72a72f5fe2e2fb9",
    "paymentBasepoint": "03ce53854a72596e3c0d7fa7783334e203cf7be4fc7f98476a38d33f260a411ee7",
    "delayedPaymentBasepoint": "0340854407642244237a24888f8a2005ce71144352f1c507afc4ba9d3d241882ae",
    "htlcBasepoint": "0394b3db73ccf55e7247a13e7d69f0b6350d53126303d574c6947d0f559ae8d84a",
    "globalFeatures": "0200",
    "localFeatures": "088a"
   },
   "channelFlags": 0,
   "localCommit": {
    "index": "2",
    "spec": {
     "htlcs": [
      
     ],
     "feeratePerKw": "750",
     "toLocalMsat": "16777200000",
     "toRemoteMsat": "0"
    },
    "publishableTxs": {
     "commitTx": {
      "$type": "fr.acinq.eclair.transactions.Transactions.CommitTx",
      "input": {
       "outPoint": "1dcb7d392058b47d6d6561548e82486d901d34f2c35b836a46039f4dc7eebd96:0",
       "txOut": {
        "amount": {
         "$type": "fr.acinq.bitcoin.Satoshi",
         "amount": "16777200"
        },
        "publicKeyScript": "0020d9bc5910785d1bb7a6079368238f3ecf7addeb164975ab2dc21e6efa06d47b6a"
       },
       "redeemScript": "522102b484f9e733c05e393eaec6bcb50911b5273b0e2da1f1415e9551e0501c280f48210378e5392a9759094b44549019a44ae47818902295145004afa290407548d2a7d452ae"
      },
      "tx": "020000000001011dcb7d392058b47d6d6561548e82486d901d34f2c35b836a46039f4dc7eebd960000000000d3c9ff8001d1fdff0000000000220020f66bf294ff8f562930e34a844ac608ddbec0dfdc4426be749d1c19eef4ebce300400473044022018eeab7e954867cedbbc04f773914abc5d7e8a2db91901af8c7b3cb8e32022e9022033b2bbd9ff2be40a41b3e2382df80342d4bf8c3f16763f57b12941b24c701ce40147304402201666f82a2dbf76158acc50b838bbae9fe251973337855531a19c8fed3d6f5a69022015da3e17cde825798d299bf78a4233e3be1d31aa9b274ab3998f2812c4a306150147522102b484f9e733c05e393eaec6bcb50911b5273b0e2da1f1415e9551e0501c280f48210378e5392a9759094b44549019a44ae47818902295145004afa290407548d2a7d452ae11b46f20"
     },
     "htlcTxsAndSigs": [
      
     ]
    }
   },
   "remoteCommit": {
    "index": "2",
    "spec": {
     "htlcs": [
      
     ],
     "feeratePerKw": "750",
     "toLocalMsat": "0",
     "toRemoteMsat": "16777200000"
    },
    "txid": "1bd3b36a56ed403963ba7e89cc4f7ad07857922420e4e3aee848596abc148a44",
    "remotePerCommitmentPoint": "0207235d8e3d06ca54fde6637fa39235053e2410b793aae394119493555366bf99"
   },
   "localChanges": {
    "proposed": [
     
    ],
    "signed": [
     
    ],
    "acked": [
     
    ]
   },
   "remoteChanges": {
    "proposed": [
     
    ],
    "acked": [
     
    ],
    "signed": [
     
    ]
   },
   "localNextHtlcId": "0",
   "remoteNextHtlcId": "0",
   "originChannels": [
    
   ],
   "remoteNextCommitInfo": [
    1,
    "03f1c93e63a3bdb41cc86a7d7a4c8f3ae791e13cad93315a529da781ae0e158850"
   ],
   "commitInput": {
    "outPoint": "1dcb7d392058b47d6d6561548e82486d901d34f2c35b836a46039f4dc7eebd96:0",
    "txOut": {
     "amount": {
      "$type": "fr.acinq.bitcoin.Satoshi",
      "amount": "16777200"
     },
     "publicKeyScript": "0020d9bc5910785d1bb7a6079368238f3ecf7addeb164975ab2dc21e6efa06d47b6a"
    },
    "redeemScript": "522102b484f9e733c05e393eaec6bcb50911b5273b0e2da1f1415e9551e0501c280f48210378e5392a9759094b44549019a44ae47818902295145004afa290407548d2a7d452ae"
   },
   "remotePerCommitmentSecrets": {
    "knownHashes": [
     [
      "-1",
      "19cb306e14799ba399d865459150534d641d1f80d4e0c8b7aec4c4572d8aa5a7"
     ]
    ],
    "lastIndex": [
     "281474976710654"
    ]
   },
   "channelId": "1dcb7d392058b47d6d6561548e82486d901d34f2c35b836a46039f4dc7eebd96"
  },
  "shortChannelId": "1638222x15x0",
  "buried": true,
  "channelAnnouncement": [
   
  ],
  "channelUpdate": {
   "$type": "fr.acinq.eclair.wire.ChannelUpdate",
   "signature": "a4e6c23ff8dc5626c0247419b32902ce321bb04843650c21bc67e28fa7d6a93b395a81a77b197daf4d6852e20f5d68b38cf0cb78ed97714800509f27a641e61f",
   "chainHash": "43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000",
   "shortChannelId": "1638222x15x0",
   "timestamp": "1578045819",
   "messageFlags": 1,
   "channelFlags": 1,
   "cltvExpiryDelta": 144,
   "htlcMinimumMsat": "1",
   "feeBaseMsat": "1000",
   "feeProportionalMillionths": "100",
   "htlcMaximumMsat": [
    "16777200000"
   ]
  },
  "localShutdown": [
   
  ],
  "remoteShutdown": [
   
  ]
 }
}
