### ISSUE TITLE
Access Denied to edit Email Service for a store

### ISSUE THREAD

**Issue by mondoir** [btcpayserver/btcpayserver#1271]
**Describe the problem/bug**
Trying to modify Email service for any individual store gives access denied. I am logged in with Admin and on the latest release.

**Your environment**
* Version of BTCPay Server: Latest Release
* Deployment method: LunaNode
* Other relevant environment details:

**Logs (if applicable)**
Basic logs can be found in Server Settings > Logs.

**To Reproduce**
1. Go to Stores
2. Click on Modify Email Service
3. See error

**Expected behavior**
Being able to modify email server setting

**Actual behavior**
Access denied

**Screenshots/Links**
<img width="362" alt="Screenshot 2020-01-14 at 08 06 30" src="https://user-images.githubusercontent.com/56967158/72325322-c8d28e00-36a4-11ea-9cbf-f52362681699.png">

**Additional context**

**Comment by Kukks** [comment]
I think this is another 3.1 bug @NicolasDorier

**Comment by mondoir** [comment]
Same authentication problem occurs when trying to add label.comment on transactions in Wallet.

**Comment by Kukks** [comment]
fixed in #1274
