### ISSUE TITLE
Need to default to coin gecko rates provides for a previously created store

### ISSUE THREAD

**Issue by cryptofuture** [btcpayserver/btcpayserver#1278]
In case there no any api key for bitcoinaverage in the server settings, all previously  created stores should default to coin gecko provider. As there no easy option to switch those from coinaverage recursively

**Comment by Kukks** [comment]
+1. Are you completely against this @nicolasdorier?

**Comment by cryptofuture** [comment]
@Kukks Maybe there is a better solution, but there should be a way to reset those in non manual manner. 
As I couldn't imagine how to do it for another people without login details and every person has multiple stores, beside sql-fu, and which is would be complicated in that case. In my example there are more than 100 stores.

**Comment by NicolasDorier** [comment]
@Kukks it depends. If the user never set the preferred exchange, I think this is fair.
But I am not sure we can know that.

**Comment by Kukks** [comment]
I think we can by looking in the preferredexchange set value. By default it should be null until it is saved?

**Comment by Kukks** [comment]
Maybe even just do a check:
* if bitcoinaverage settings are NOT set
* and store is setto bitcoinaverage
THEN
* set to coingecko and set a flag `bitcoinaverage post monetization migration` to true

**Comment by NicolasDorier** [comment]
I think this is the current behavior.

**Comment by NicolasDorier** [comment]
I mean, if the store never set the rate provider, I think he is automatically on coingecko now.

**Comment by cryptofuture** [comment]
> I mean, if the store never set the rate provider, I think he is automatically on coingecko now.
Only for a new stores, old ones are still trying to use bitcoinaverage

**Comment by NicolasDorier** [comment]
Working on it #1286

**Comment by NicolasDorier** [comment]
Fixed on v1.0.3.152 that I release in 30min
