### ISSUE TITLE
How to use Liquid Bitcoin support?

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#1282]
### How to use Liquid Bitcoin support in BTCPay?
Enable it as if it was any other coin by following the [official docs](https://docs.btcpayserver.org/faq-and-common-issues/faq-altcoin#how-to-add-an-altcoin-to-an-existing-btcpay-deployment)

Enabling LBTC also implicitly enables any Liquid assets that have been configured in BTCPay such as Liquid Tether (USDt).

We also prune the Liquid node to ~5GB in order to not break existing installs that wanted to support Liquid on a tightly constrained server( such as the ones from the LunaNode installer)

### Wallet Configuration

BTCPay supports Liquid's confidential transactions. In order to make use of this though, you'll need to use the "Generate Wallet" feature as there are no other wallets that support our way of deriving blinding keys and would not be able to track incoming funds. 

The Generate Wallet feature allows you to generate or provide a mnemonic seed to the store, and it will generate the xpub for the store to use. Furthermore, it allows you to import your keys to the bitcoin/liquid node so that you can spend any incoming funds from the node's wallet itself `via cli commands such as sendtoaddress OR a remote bitcoin node app such as FullyNoded`.

![image](https://user-images.githubusercontent.com/1818366/72499449-2fd17d80-3832-11ea-960e-d05a3cc87510.png)

 It's important to check the `Is hot wallet ` & `Import keys to RPC` options. Also note that while BTCPay supports Liquid's Blech32 segwit confidential addresses, Green wallet still does not. It is recommended to use "Segwit wrapped" p2sh addresses.
![image](https://user-images.githubusercontent.com/1818366/72499502-58597780-3832-11ea-8f0a-6653243bd6ae.png)

Make sure you save the seed key after generating.
![image](https://user-images.githubusercontent.com/1818366/72499656-b8e8b480-3832-11ea-8fbc-a5a762e2b46b.png)

### Skipping Confidential transactions.
You may skip the confidential transactions feature and use the traditional xpub input method. Just add `-[unblinded]` at the end
`xpub6DHf9nVQP6mc5FgKD4E3UuxPubv7Gf19BUMemRR73o5BRiTsgexiDmMsVv3DDeH251UdJFkUYAkneiwg5RKHn8wa3Azpkx2eVHmFLY3ErmF-[p2sh]-[unblinded]`

NOTE: If you generated a wallet using the Generate wallet feature, and then added `-[unblinded] ` afterwards, the keys will not be imported to the node.

### Configuring Assets
Liquid assets show up as if they are their own coin in BTCPay and are configured as such. I would recommend just using the same seed/xpub on liquid bitcoin & each liquid asset.

### I'd like to add my own Liquid asset
It should be relatively simple. If you don't know how to code, just contract me at kukks.org :)

**Comment by NicolasDorier** [comment]
@Kukks 

> Make sure you save the seed key after generating.

The user then need to click on "Confirm".

Also, I would prefer you tell: "WARNING IT IS NOT POSSIBLE TO RESTORE SO BE CAREFUL"

**Comment by NicolasDorier** [comment]
Because right now, there is simply no process to restore from seed with liquid. ScanUTXOSet is not supported.

**Comment by pavlenex** [comment]
Would be good to add this to docs FAQ-Altcoin?

**Comment by Kukks** [comment]
I wanted to keep the altcoins faq generic and then linked to this from the docs

**Comment by NicolasDorier** [comment]
@Kukks I think we can put that in doc

**Comment by nharmon9** [comment]
Is it impossible to spend Liquid using NBXplorer without saving the private keys and an rpc call to a liquid node?

**Comment by Kukks** [comment]
> Is it impossible to spend Liquid using NBXplorer without saving the private keys and an rpc call to a liquid node?

Yes.

**Comment by nharmon9** [comment]
What if you save the private key locally?

**Comment by nharmon9** [comment]
Or derive it from the extended key and keypath?

**Comment by whiteyhat** [comment]
Hi @Kukks 👋 

I followed the guide, but `L-BTC` does not seem to synchronise at all. It is been over 24 hours and it keeps the same

![Captura de pantalla 2020-04-01 a las 16 47 48](https://user-images.githubusercontent.com/31220861/78151146-8cf3cd00-7438-11ea-868d-7553348ac315.png)

**Comment by Kukks** [comment]
> 
> 
> Hi @Kukks 👋
> 
> I followed the guide, but `L-BTC` does not seem to synchronise at all. It is been over 24 hours and it keeps the same
> 
> ![Captura de pantalla 2020-04-01 a las 16 47 48](https://user-images.githubusercontent.com/31220861/78151146-8cf3cd00-7438-11ea-868d-7553348ac315.png)

Do you have space for it?

**Comment by whiteyhat** [comment]
I do not think so 🤔 

 Maybe because I did the one-click deployment through Lunanode, now I have to set-up a different volume to the instance. Do you have a related issue that explains how to do it?

**Comment by Kukks** [comment]
> 
> 
> I do not think so 🤔
> 
> Maybe because I did the one-click deployment through Lunanode, now I have to set-up a different volume to the instance. Do you have a related issue that explains how to do it?
> 
> Also, the volume must have a name declaration? eg: `<MY_BTCPAY_HOSTNAME>-lbtc`?

No, I never used LunaNode so no clue what needs to be done there.

**Comment by whiteyhat** [comment]
Any recommended specs for the storage from the `L-BTC` altcoin?

**Comment by Kukks** [comment]
The one click deployment is only meant to handle the creation of the server (and volumes) as you initially set up. AFAIK, if you sat up the server with more coin options, the volumes grow with it. 

I think we set LBTC hardcoded to 5GB pruning (please check) + whatever else is used for the utxo set 
So I would aim for an extra 10GB to be safe ( on top of the pruning size)

**Comment by whiteyhat** [comment]
I solved the issue!

Steps to solve it:
1. creating by creating a volume manually from Lunanode
2. Mount the volume (https://www.lunanode.com/features/volumes) to `/var/lib/docker/volumes/generated_elements_datadir/_data`
3. Restart btpcay: `./btcpay_restart.sh

**Comment by whiteyhat** [comment]
Hey 👋 

@Kukks @NicolasDorier The `L-BTC` sidechain does not sync any blocks... Steps I did:

1. I clean the instance by using `./btcpay_clean.sh` 
2. I updated the instance `./btcpay_update.sh` 
3. Next, I restarted the instance `./btcpay_restart.sh`

Now, it seems to not even syn any block at all
![Captura de pantalla 2020-04-02 a las 12 46 52](https://user-images.githubusercontent.com/31220861/78241029-11e5f180-74e0-11ea-88fe-beb12c7e3d96.png)

**Comment by Dinglebarry9** [comment]
Hey @Kukks I have been experiencing a strange issue with Liquid where invoices for Liquid Assets with the `[unblinded]` flag fail to update when BTCPay receives a new transaction event from NBXplorer. Though, when the connection to NBX is severed and BTCPay reconnects (when I shut down either NBX or BTCPay) and it checks if pending invoice got paid while offline the invoice gets updated with the payment happening. This is not a problem with the pegged asset (blinded or unblinded Derivation Strategy) nor Liquid assets sent to a`DerivationScheme` without the `[unblinded]` flag.

**Comment by IT4Crypto** [comment]
> 
> 
> Hey 👋
> 
> @Kukks @NicolasDorier The `L-BTC` sidechain does not sync any blocks... Steps I did:
> 
>     1. I clean the instance by using `./btcpay_clean.sh`
> 
>     2. I updated the instance `./btcpay_update.sh`
> 
>     3. Next, I restarted the instance `./btcpay_restart.sh`
> 
> 
> Now, it seems to not even syn any block at all
>![Captura de pantalla 2020-04-02 a las 12 46 52](https://user-images.githubusercontent.com/31220861/78241029-11e5f180-74e0-11ea-88fe-beb12c7e3d96.png)

I had the same issue with a Lunanode one-click-deploy, and I find a solution that worked for me after trying some stuff:

Following the BTCPayServer guide https://docs.btcpayserver.org/FAQ/FAQ-Synchronization/#btcpay-server-takes-forever-to-synchronize I check it out, and my RAM was around 90% and SWAP file around 50%. However, after reading additional documentation, and find out that the liquid node needs a bigger swap file to do the initial sync.

Enable a big swap file (repeat this procedure when you need it).
swapoff -a
touch /swapfile
dd if=/dev/zero of=/swapfile bs=1M count=4096
mkswap /swapfile
swapon /swapfile
               
How did I know that? I went to my favorite website related to liquid network https://liquid.beer/pub and read about the recommended parameters for the node they propose.

I hope it helps.

**Comment by tiero** [comment]
Is it possible to use Liquid with a hardware wallet or provider an xpub for each specific store?

**Comment by IT4Crypto** [comment]
> Is it possible to use Liquid with a hardware wallet or provider an Xpub for each specific store?

Unfortunately, I did not find any Liquid wallet that works with XPUBs, being BTCPay Server is the only one so far.
Mobile wallets don't show that feature, and Elements (desktop) is a fork of Bitcoin Core which doesn't work that way.

I am getting my JADE very soon, so I can try and tell you how it goes. But afaik is only compatible with Green which doesn't have that feature.
Maybe it is possible to use a Liquid Version of Electrum (currently, it doesn't exist, I think) and plug the Hardware wallet there.

**Comment by tiero** [comment]
Jade can show the xpub, using the GDK library (not sure it exists on plain hwi) https://gdk.readthedocs.io/en/release_0.0.48/gdk-hw/#hardware-get-xpubs-action


PS: For hot/light wallets, I can push the inclusion of xpub import/export in [Marina Wallet](https://github.com/vulpemventures/marina/) (with slip77 master blinding key for confidential transactions)

**Comment by IT4Crypto** [comment]
> Jade can show the xpub, using the GDK library (not sure it exists on plain hwi) https://gdk.readthedocs.io/en/release_0.0.48/gdk-hw/#hardware-get-xpubs-action
> 
> PS: For hot/light wallets, I can push the inclusion of xpub import/export in [Marina Wallet](https://github.com/vulpemventures/marina/) (with slip77 master blinding key for confidential transactions)

Excellent to know that! I cannot wait to receive it then :D

Marina Wallet is the only one I did not try (and the iPhone ones). Thanks for this valuable piece of information! :D

**Comment by IT4Crypto** [comment]
> Jade can show the xpub, using the GDK library (not sure it exists on plain hwi) https://gdk.readthedocs.io/en/release_0.0.48/gdk-hw/#hardware-get-xpubs-action
> 
> PS: For hot/light wallets, I can push the inclusion of xpub import/export in [Marina Wallet](https://github.com/vulpemventures/marina/) (with slip77 master blinding key for confidential transactions)

by the way, jade is multisig so extracting the XPUB out of it will not give you the operative XPUB that conforms with green but only one of the co-sign xpub if I am not wrong. As I said I will try it soon and document it.

**Comment by tiero** [comment]
You can also use it single sig now, it should work i think

**Comment by ProTechEx** [comment]
@Kukks where can I found more detailed informations about sending Liquid ?  
  
And basically it would be also amzing if also a sending part available on the BTCPay Server Web GUI.

**Comment by ProTechEx** [comment]
**I try as it is here described:**  
 

![](https://user-images.githubusercontent.com/5677301/206934437-0fc41158-df9c-40dc-ba2b-e1edfb0bbfa5.png)

  
  
**but I get this error:**

![](https://user-images.githubusercontent.com/5677301/206934403-1e20dafb-aa00-44f1-968e-a6f332f20bd2.png)

**What i am doing wrong?**

**Comment by donnyxray** [comment]
Recent versions of btcpay look a little different and I have the generated xpub show up in a read-only field. How/where can I add the ```-[unblinded]``` flag to it?

**Comment by Besthuvelraju** [comment]
Bitcoin and Amazon

**Comment by Besthuvelraju** [comment]
Amazon bounse Google
