### ISSUE TITLE
Missing documentation for invoice status "confirmed"

### ISSUE THREAD

**Issue by AusPrinzip** [btcpayserver/btcpayserver#1288]
As per official [documentation](https://docs.btcpayserver.org/features/invoices) in features/invoices section, a description of invoice status "confirmed" is missing.

**Environment**
* Version of BTCPay Server: latest as per 17.01.2020
* Deployment method: Automatic deployment (recommended)

**To Reproduce**
1. Create an invoice client sided
2. Pay 
3. Monitor invoice status, within minutes will change from "new" to "confirmed"

**Expected behavior**
A clear description of "confirmed" status meaning.

**Actual behavior**
No mention of "confirmed" status in official documentation.

**Comment by britttttk** [comment]
https://docs.btcpayserver.org/faq-and-common-issues/faq-stores#consider-the-invoice-confirmed-when-the-payment-transaction

**Comment by bolatovumar** [comment]
@britttttk I think what @AusPrinzip means is that there is not confirmed status description in the table in this section: https://docs.btcpayserver.org/features/invoices#invoice-statuses

**Comment by britttttk** [comment]
@bolatovumar @AusPrinzip Thanks for clarifying! I'm not used to seeing this status because of LN txs :) Added, let me know if you think it's clear or could be better.

**Comment by pavlenex** [comment]
Added in [#415](https://github.com/btcpayserver/btcpayserver-doc/pull/415)
