### ISSUE TITLE
[UX] Warning system for stores

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#1290]
## Problem

When a user create a new store, there is a number of steps he need to do to be operational such as:

* Setting up at least one payment method
* Setting up the rate provider (so not everyone ends up depending on CoinGecko by default, and so they get the relevant rate of their location)
* TODO... (more idea?)

Right now we don't notify him of such actions.

## Proposed solution

I propose that the Stores page would show a ⚠️ logo in case the store is not fully configured. If the user over it, he will see the remaining actions to do.

I am unsure this is the best solution.
Maybe we could add a wider "notification system" and use to notify users "Warning: Your store is still relying on the default rate provider".

I am opening this PR to open the discussion.

**Comment by bolatovumar** [comment]
This was an issue for me as well when I first created a store. It's not immediately obvious what needs to be done to complete the set-up. I think there should be at least a warning at the top of the page is something still needs to be configured. This is a no-brainer for me.

In addition there could be a wizard type of store creating process where the user has to specify all options for a new store in steps. This way you can't miss any of the required steps. This will help novice users but experienced users may not like it as much as it would feel slower than just creating a store in one click.

**Comment by NicolasDorier** [comment]
@bolatovumar this make sense actually this may be part of https://github.com/btcpayserver/btcpayserver/issues/1263

I want to scrap completely the current Add derivation scheme process to make it more newbie friendly.

**Comment by pavlenex** [comment]
1. User creates a store and is welcomed with this
![Screenshot 2020-01-22 at 11 13 46](https://user-images.githubusercontent.com/36959754/72885502-5c8d0580-3d08-11ea-9444-737c9b3765e0.png)
It is not intuitive what has to be done next unless docs are read.
2. Next, the user should connect a wallet by adding xpubkey in derivation scheme. This is at the bottom of the page, we have to show somehow a warring with a link at least to derivation scheme, at least in that dialog.
3. We've talked about simplifying derivation scheme setup, but I don't think it's the goal of this issue, that one should be done in [#1290](https://github.com/btcpayserver/btcpayserver/issues/1290)

I've seen notifications being mentioned, we have an issue for that #775 would probably be cool to have that at some point.

I am unsure about the rate source, I'd leave that at the end, it adds just another step for the user, we have to figure that one differently imo not by pushing it towards user, especially not during first time setup.

**Comment by pavlenex** [comment]
@NicolasDorier @rockstardev If we can tie this into #775 #1542 it can solve an issue where users would not end up configuring the store settings (especially forgetting to add derivation scheme). 

- Save but not add derivation scheme
- Remind them to set up rates (defaults are set) but would help with decentralizing rate providers in case of a failure as Nicolas mentioned.

However besides an UI notification, I believe we can add a store warring as well.

**Comment by Bosch-0** [comment]
Quick concept of something that could be done. Let me know what you guys think, happy to explore this further

![image](https://user-images.githubusercontent.com/55287964/89440927-f38a4e00-d77e-11ea-84ef-e6b27fbeee8d.png)

**Comment by Eskyee** [comment]
Nice idea, for newbies getting started.. but not sure of the placement.

**Comment by pavlenex** [comment]
For this particular issue I was thinking we utalize simple things we fan easily implement. The idea by @Bosch-0 is more suitable imo in dashboard #1711 

Here is what I suggest:

1. Currently, user creates a store ` Store successfully created ` is the message.

![Screenshot 2020-08-05 at 21 33 37](https://user-images.githubusercontent.com/36959754/89456236-d8f6ab80-d763-11ea-9a95-b60b89b81666.png)


Instead we can provide a yellow message indicating incompleteness ` Store successfully created, but wallet not set up. Set up a wallet now"

2. We utilize notification feature. So when user creates an account, he gets these notifications:
- Welcome to BTCPay Server to begin, create your store.
- Store successfully created, but wallet not set up. Set up a wallet now.

So a combination of notification features and simple store message.

These small things should be easy to implement and would give us time to get user feedback so that we can properly decide how to implement setup wizard or something that @Bosch-0 suggested in the dashboard in the future.

I am not sure about the rate provider. It works. Perhaps we can add a reminder after a while "You appear to be using a default rate provider..." But I don't really think we need to bother people with rate providers those out of the box work well. If they don't we can add a notification/warring.

What do you guys think?

**Comment by Eskyee** [comment]
I agree with pav

**Comment by NicolasDorier** [comment]
I think that @Bosch-0 idea instead of the current "Store successfully created" would work quite nicely.

The problem with notification is that we can't remove a notification automatically when the action has been done.
If you get one notification for each step, that's spamming 5 notifications.

**Comment by Bosch-0** [comment]
Here is another lower fidelity design of another concept we could explore.

![image](https://user-images.githubusercontent.com/55287964/89495670-53b6d980-d7eb-11ea-9247-5991367fe84d.png)

I'll play around with some notification designs later today

**Comment by NicolasDorier** [comment]
It does not have to be sequential, he can setup the rate before the payment method.

**Comment by pavlenex** [comment]
@NicolasDorier I was aiming for low-effort high-impact type of idea. If you want to completely re-structure this, then I suggest we pause this and decide on the setup wizard. Also before we even consider implementing this, we need to improve derivation scheme workflow.

**Comment by dennisreimann** [comment]
I'm not sure if completely restructuring it is necessary or even a good idea. If wee'd go with a wizard approach, then we'd also need a quick way to access the individual parts for the maintenance case (like what we have currently).

I like the idea of having something on top of the "Manage Store" pages (like the bar @Bosch-0 proposed), as long as the necessary setup isn't completed. As this isn't sequential we should find a better way to convey the missing steps, but in general I like the idea and position.

**Comment by pavlenex** [comment]
I think we need to step back and try to determine what problem we're trying to solve with this particular issue.

This issue states:

> When a user create a new store, there is a number of steps he need to do to be operational such as:
Right now we don't notify him of such actions.

So our issue is > User creates store and does not know what to do next, which is wallet setup, so let's focus on how we can make that more obvious. Our goal is bring user to the wallet setup page. Wallet setup workflow is not ideal but we'll get there eventually. The wallet setup workflow is not the topic of this issue so let's disregard it.

### Re-positioning Derivation scheme section and renaming it

It  seems to me that can solve this with quick fix, by pushing derivation scheme above the fold. 
Currently this is how you access derivation scheme. 

![28034DFC-FD54-4184-B42E-CD5329D06070](https://user-images.githubusercontent.com/36959754/89548932-fc733200-d807-11ea-801f-870780be55b8.GIF)

Derivation scheme is highly technical that 90% of people don't understand. On the other hand they do understand "Wallet Setup".

I suggest we push the section above the fold and re-name it to wallet setup.

![Capture2](https://user-images.githubusercontent.com/36959754/89549543-bbc7e880-d808-11ea-84ca-9cbaa24c8e93.jpg)


### Wallet Setup call to action
Upon moving and renaming the wallet setup section, we'd have to figure out a proper way to indicate that wallet is not set up and create a clear CTA, which is something  I am sure @Bosch-0 and @dstrukt can solve with their magic.

![image](https://user-images.githubusercontent.com/36959754/89549651-def29800-d808-11ea-82df-37dc6bacf3c7.png)

Now when store is created I still think it's a good idea to put a warring that wallet setup is required.

![Capture2](https://user-images.githubusercontent.com/36959754/89550380-d9e21880-d809-11ea-9537-1de7c42b0eff.jpg)


I think these fixed are quite easy to implement and do not present a huge refactoring risk and will not require is to rip apart exiting videos and documentation. Dennis made a good point that the individual setup should still be easy if we ever decide to go wizard way.

These are just my idea, happy to hear if there are other approaches.

**Comment by pavlenex** [comment]
Been thinking about this and most of these elements in store are unusable unless you have a wallet, so here's another rough idea that strips everything from the store until a wallet is set up. When wallet setup complete show all additional options.

This method has disadvantages (for people who want to use LN only) so perhaps we can add "Show more" button on the initial setup that would reveal the elements.

![Capture](https://user-images.githubusercontent.com/36959754/90120763-6d13d480-dd5b-11ea-9772-e297b14f0aed.PNG)

**Comment by dstrukt** [comment]
I agree with @pavlenex's approach here.

Which I see you've started to utilize some of the "flow" mock I've been tinkering on - liking where it's going!

I also support clearly delineating sections a bit more explicitly via the left menu as well + restricting access until certain actions have been completed, allows us flexibility with low effort, and allows us to leverage a wizard at a later time.

Still thinking on this as well, but trying to wrap up push/pull payment stuff in the meantime, will circle back.

**Comment by Bosch-0** [comment]
Here is a more stylized alert which gives the user some more info. Also included 'danger' and 'success' alerts in this format in the [figma style guide ](https://www.figma.com/file/C7Xyq0FlxgFW8vaBr8ht1z/BTCPAY?node-id=1628%3A4)

![image](https://user-images.githubusercontent.com/55287964/90399624-d41fe900-e0cd-11ea-9423-f13ed445e293.png)

**Comment by pavlenex** [comment]
From that example, personally I like breadcrumbs, I think they help navigation. The warring itself really does not give any context, I think what we proposed in earlier is way clearer CTA. In this new mockup we still force user to scroll to "derivation scheme" part which in itself is just pain.

**Comment by pavlenex** [comment]
Posting this after some discussion we had.

The consensus for this issue is as following. In this issue we will focus on making the "derivation scheme part" more visible and human-readable so to say.

1. Rename `Derivation Scheme` to `Wallet Setup`
2. Rename `Modify` to `Setup a wallet` or `Setup` 
3. Push Derivation Scheme box above the fold after the `General` and  before the`Payment`
4. Add a message when store is created to remind about wallet creation.

This issue will then build on #1703 because we want to have store + wallet setup together, but we still want to give options for people who manually want to set stuff up.

The only image I currently was able to find is a mockup from @dstrukt I'm hoping it can be adjusted to what have we agreed on.

![Screenshot 2020-10-05 at 11 11 28](https://user-images.githubusercontent.com/36959754/95351955-0675e780-08c2-11eb-860f-c873f039fa76.png)

**Comment by dstrukt** [comment]
Yeah, there's still a good bit to do, these were just explorations, but will provide some new mocks soon to discuss.

**Comment by dstrukt** [comment]
My thoughts on this, posted in:

https://github.com/btcpayserver/btcpayserver/issues/1959#issuecomment-705988667

**Comment by pavlenex** [comment]
#1959 #1990
