### ISSUE TITLE
Add a field for a second redirect URL for failed/non-payment

### ISSUE THREAD

**Issue by Hotstryker** [btcpayserver/btcpayserver#1291]
**Describe the problem/bug**
I have the Store Website URL programmed, and then use the redirect URL on the Pay button settings to send the customer to the successful payment webpage to opt-in to a paid account.

However, if the invoice expires and you click on the Return to "store" button that shows up, it takes the customer to the redirect/successful payment page and not to the Store Website URL.

**Your environment**

* Version of BTCPay Server:  v1.0.3.150
* Deployment method: Docker

**To Reproduce**
1. Go to 'https://clicktofreedom.com/paypage/wm25.html'
2. Click on 'Bitcoin Buy Now button'
3. Allow invoice to expire without payment
4. Click on "Return to Store"

**Expected behavior**
Expect customer to be sent to URL as defined in "Store Website" settings

**Actual behavior**
Customer is sent to redirect URL defined in Pay Button settings for successful payment.

This is critical as it allows a customer to get to the paid account page just by allowing the invoice to expire and never having paid

**Comment by bolatovumar** [comment]
This sounds reasonable to me. I would expect the "Return to Store" button to actually return you to the store. My only concern would be that existing merchants may already rely on this non-ideal behavior and it could be a breaking change for them.

**Comment by Hotstryker** [comment]
That's kinda what I was thinking this morning.  On the Pay Button Settings page inside BTCPay, a field could be added for a second redirect URL for failed/non-payment.  If populated, then the return to store button would go to that URL, but if left empty, then current behavior would stay the same.  That way it shouldn't break any ones current setup if they've done some type of custom workaround.

**Comment by bolatovumar** [comment]
@NicolasDorier @Kukks does the above suggestion of adding a separate redirect url for failed payments make sense or are there reasons why that's not a good idea? If we confirm that it's something we want, I can go ahead and implement it.

**Comment by NicolasDorier** [comment]
Actually there is easier.
An undocumented feature is that we allow "PlaceHolders" in the redirectURI such as `{OrderId}` or `{InvoiceId}`. This could be modified to also pass `{Status}`

```
        private Uri FillPlaceholdersUri(string v)
        {
            var uriStr = (v ?? string.Empty).Replace("{OrderId}", OrderId ?? "", StringComparison.OrdinalIgnoreCase)
                                     .Replace("{InvoiceId}", Id ?? "", StringComparison.OrdinalIgnoreCase);
            if (Uri.TryCreate(uriStr, UriKind.Absolute, out var uri) && (uri.Scheme == "http" || uri.Scheme == "https"))
                return uri;
            return null;
        }
```

**Comment by bolatovumar** [comment]
@NicolasDorier so if a status like "failed=true" is passed in to the provided redirect URL then it would be up to the app that this url points to do something different like showing "payment failed" status?

**Comment by Kukks** [comment]
> 
> 
> @NicolasDorier so if a status like "failed=true" is passed in to the provided redirect URL then it would be up to the app that this url points to do something different like showing "payment failed" status?

Yeah pretty much. Though I would still argue that the app should query the invoice via API to make sure the status is correct( anyone can manipulate the url to get a success page)

**Comment by NicolasDorier** [comment]
Yes. In anycase, the redirect should not be what is used to process logic. It should be IPN + Getting the invoice.

**Comment by bolatovumar** [comment]
@Kukks the problem currently is that everyone always gets to the success page even if the payment fails. Are you saying that whatever app exists on the redirect URL shouldn't assume that the payment has succeeded and query the API for that invoice id and check if it succeeded or failed and decide what to do based on that?

**Comment by Kukks** [comment]
> 
> 
> @Kukks the problem currently is that everyone always gets to the success page even if the payment fails. Are you saying that whatever app exists on the redirect URL shouldn't assume that the payment has succeeded and query the API for that invoice id and check if it succeeded or failed and decide what to do based on that?

Exactly. the redirect page should not blindly trust that it was accessed in a truthful matter. 

A simplified example:
* user wants to buy a digital product from Store A
* Store A creates invoice with redirectURL to store.com/success
* User pays invoice and goes to  store.com/success
* success page displays the download link
* User a shares success link online
* Everyone now has access directly from your site

**Comment by bolatovumar** [comment]
@Hotstryker does the above help your case? Can you query the API first on your redirect page to direct the user to the right page?

**Comment by NicolasDorier** [comment]
ping @Hotstryker

**Comment by Hotstryker** [comment]
Hi guys, sorry for the late reply.  I've not had much time to work on this, as it involves a level of programming outside of my expertise.  I suppose if I can find proper PHP programmer, this would work, and is sounding like my only choice.

**Comment by Hotstryker** [comment]
Hi guys, sorry for the late reply.  I've not had much time to work on this, as it involves a level of programming outside of my expertise.  I suppose if I can find proper PHP programmer, this would work, and is sounding like my only choice.

However, from a user standpoint, (keeping in mind that myself and my clients are mostly marketers, not web developers or programers) it seems to me that BTCPayserver is already doing most of this.  Is it not using NBxplorer to check if invoice is paid, then at the point of the invoice expiring it determines either succuss or expired?  I belive it is in the Checkout-Body.cshtml that I saw where it decides that and thus displays the expired invoice notice with the "return to store" button.

Now understanding that people who run more complex e-comm sites already have a work around in place, is why the suggestion for the dual url option.  For those of us who are simply using a "Pay Button" with the code embedded on a page as in my example site above, is it really a major programming change to  where the 

`<div class="bp-view" id="paid" v-bind:class="{ 'active': `invoicePaid}">` 

section take them to a success url (in my case an opt-in page) and the 

`<div class="bp-view expired" id="expired" v-bind:class="{ 'active': invoiceUnpayable}">` 

section takes them back to a fail page, which in my case would be the original pay page where they could setup another invoice?

Hopefully I've communicated clearly as programing is not a strong point of mine.  I know just enough to be dangerous.  LOL.  Also, if the API work is the best/only option, can any of you refer me to a developer who would work for a solution for me for very cheap if not free?  Once I have something that works, I could then impliment if for my clients.  Thanks.

**Comment by pavlenex** [comment]
How do we want to proceed with this issue?

**Comment by bolatovumar** [comment]
Seems like we can close it?

**Comment by Kukks** [comment]
> Seems like we can close it?

Yes, {Status} is available to be used in the redirect URL now so you can have a page that is "success" vs "failure" based on it.
