### ISSUE TITLE
Invoice are lacking important details

### ISSUE THREAD

**Issue by Transisto** [btcpayserver/btcpayserver#1292]
The current invoice format is missing many potentially useful details.

If a customer doesn't bookmark the invoice and imputing an email are not required there is no way to reliably retrieve an invoiceID if there is any problems.

The receiving bitcoin address disappear when it's paid, (could be useful to verify confirmations status.

There is no Bitcoin TXID when a transaction is pending.

There is no way to monitor confirmation status from the invoice page. (most services do not do any action unless there at least one confirmation. The delay between PAID and ACTUALLY PAID, can be way too long if fee set is too low, it's setting expectation too high but create frustration.

**Comment by NicolasDorier** [comment]
Can you comment under this one https://github.com/btcpayserver/btcpayserver/issues/1256 and describe what are the fields you would like to see?

This should be part of the same goal.
