### ISSUE TITLE
Clear Expired/Void Invoice

### ISSUE THREAD

**Issue by mondoir** [btcpayserver/btcpayserver#1296]
During the tests there are a lot of generated invoices which are marked invalid or simply are expired.
It would be a good option to be able to delete/purge invoices by type or date.
It would also save a lot of space on db and screen.

**Comment by bolatovumar** [comment]
You can already use filtering functionality to filter-out invalid/expired invoices.

I guess being able to delete invalid/expired invoices could be useful but I'm wondering if there are reasons why this might not be a good idea. Thoughts @pavlenex?

**Comment by britttttk** [comment]
https://github.com/btcpayserver/btcpayserver-doc/blob/master/FAQ/FAQ-Stores.md#can-i-delete-invoices-from-btcpay

**Comment by pavlenex** [comment]
As Brit linked, there are many reasons why we don't allow this, it can hurt more than it can help. Therefore I'll close this issue.
