### ISSUE TITLE
Add/Remove BTCPay Users

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#13]
Need the ability to add/remove users without having them register. 

Also, possibly "lock down" server, not allowing anyone to attempt to register. Good for single organizations. 

When adding user, perhaps grant them permissions to certain stores. Again, good for when multiple users from a single organization need access

**Comment by NicolasDorier** [comment]
The lock down of registration is on v1.0.0.36 (server settings)

**Comment by NicolasDorier** [comment]
Removing user has been implemented in v1.0.0.37

**Comment by lepipele** [comment]
Nicolas note: We still need to implement add user in order to close this issue

**Comment by lepipele** [comment]
Continuing on #44
