### ISSUE TITLE
Maintenance feature lost access to SSH 

### ISSUE THREAD

**Issue by mondoir** [btcpayserver/btcpayserver#1311]
**Describe the problem/bug**
After updating to v1.0.3.155, the Maintenance page displays the following warning while all buttons are disabled on this page.

<img width="881" alt="Screenshot 2020-01-29 at 07 34 24" src="https://user-images.githubusercontent.com/56967158/73336558-0c62f580-426a-11ea-9abc-6a03dd5483d9.png">

**Your environment**
* Version of BTCPay Server: v1.0.3.155
* Deployment method: Docker/LunaNode

**To Reproduce**
I just updated the code from within Maintenance page, after which this warning came.

**Additional context**
Based on suggestions on Telegram group, I've done the following commands without any luck:

export BTCPAY_ENABLE_SSH=true
. ./btcpay-setup.sh -i

I've also followed docs in here without any luck.
https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#btcpay_sshkeyfile-is-not-set-when-running-the-docker-install-or-unable-to-update-through-server-settings-maintenance

**Comment by pavlenex** [comment]
@NicolasDorier Any idea what can be the problem here? I assuming this was a very old version being updated that causes such break.

**Comment by NicolasDorier** [comment]
@mondoir thanks for the feedback. Sorry for the delay, been traveling these days.
I checked on my version, I don't have any issue so I don't think this is caused by the update.

Can you tell us your config when you do `. ./btcpay-setup.sh -i`?

**Comment by mondoir** [comment]
@NicolasDorier 
here it is:

WARNING: BTCPAY_HOST_SSHKEYFILE is now deprecated, use instead BTCPAY_ENABLE_SSH=true and run again '. btcpay-setup.sh -i'

-------SETUP-----------
Parameters passed:
BTCPAY_PROTOCOL:https
BTCPAY_HOST:**********
BTCPAY_ADDITIONAL_HOSTS:
REVERSEPROXY_HTTP_PORT:80
REVERSEPROXY_HTTPS_PORT:443
REVERSEPROXY_DEFAULT_HOST:none
LIBREPATRON_HOST:
WOOCOMMERCE_HOST:
BTCTRANSMUTER_HOST:
BTCPAY_ENABLE_SSH:true
BTCPAY_HOST_SSHKEYFILE:/root/.ssh/id_rsa_btcpay
LETSENCRYPT_EMAIL:**********
NBITCOIN_NETWORK:mainnet
LIGHTNING_ALIAS:
BTCPAYGEN_CRYPTO1:btc
BTCPAYGEN_CRYPTO2:
BTCPAYGEN_CRYPTO3:
BTCPAYGEN_CRYPTO4:
BTCPAYGEN_CRYPTO5:
BTCPAYGEN_CRYPTO6:
BTCPAYGEN_CRYPTO7:
BTCPAYGEN_CRYPTO8:
BTCPAYGEN_CRYPTO9:
BTCPAYGEN_REVERSEPROXY:nginx
BTCPAYGEN_LIGHTNING:lnd
BTCPAYGEN_ADDITIONAL_FRAGMENTS:opt-save-storage-s
BTCPAYGEN_EXCLUDE_FRAGMENTS:
BTCPAY_IMAGE:
ACME_CA_URI:production
TOR_RELAY_NICKNAME: 
TOR_RELAY_EMAIL: 
----------------------
Additional exported variables:
BTCPAY_DOCKER_COMPOSE=/root/btcpayserver-docker/Generated/docker-compose.generated.yml
BTCPAY_BASE_DIRECTORY=/root
BTCPAY_ENV_FILE=/root/.env
BTCPAYGEN_OLD_PREGEN=false
BTCPAY_SSHKEYFILE=/datadir/host_id_rsa
BTCPAY_SSHAUTHORIZEDKEYS=/datadir/host_authorized_keys
BTCPAY_HOST_SSHAUTHORIZEDKEYS:/root/.ssh/authorized_keys
BTCPAY_SSHTRUSTEDFINGERPRINTS:
BTCPAY_CRYPTOS:btc
BTCPAY_ANNOUNCEABLE_HOST:**********

**Comment by mondoir** [comment]
Update:

I just updated to the latest version and its working fine now. the warning is gone.
