### ISSUE TITLE
Docker deployment: Nginx requires further configuration

### ISSUE THREAD

**Issue by gitman23** [btcpayserver/btcpayserver#1315]
**Problem/bug**
Docker deployment of BTCPay worked without errors. 

When I go now in a web browser to http://mydomain.com I get this message:
_"Welcome to nginx! If you see this page, the nginx web server is successfully installed and working. Further configuration is required. For online documentation and support please refer to nginx.org. Commercial support is available at nginx.com. Thank you for using nginx."_

When I go to  https://mydomain.com no content is found "unable to connect"

When I enter in shell "certbot certificates" I get:
"Saving debug log to /var/log/letsencrypt/letsencrypt.log
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
No certs found."

**Environment**
* Version of BTCPay Server: 190001
* Deployment method: Docker deployment
* Other relevant environment details: Ubuntu 18.04

**Expected behavior**
Expectet to see the [BTC account registration screen](https://blobscdn.gitbook.com/v0/b/gitbook-28427.appspot.com/o/assets%2F-LOnsHXOleEK7mXmj8eY%2F-LuTPD2hT1JsxNhqSCyF%2F-LtnKh4RTvbYWzoP9lJa%2Fbtcpay-registration-page.jpg?generation=1574615707949688&alt=media) when going to mydomain.com

**Actual behavior**
No website found or nginx message, see above. 

**Additional context**
I didn't create a subdomain for BTCPay because on this server nothing else is running.
I stopped Apache on this server because I think it doesn't harmonize with nginx. Not sure if I ned to de-install Apache...
Not sure if I need to wait longer to see something on https or if my nginx isn't setup properly.

Thanks a lot in advance from a first time user!

**Comment by Kukks** [comment]
It seems to me like there is another nginx instance running on the server instead of the one from btcpay's containers.

**Comment by gitman23** [comment]
No other nginx. I de-installed Apache and restarted the server. Now it's showing on the http and on the onion side the expected behavior but on the https page I get an Error 500. I fear it's not because the Let's encrypt needs time, otherwise it would me allow to make an exception  but showing the same content as on the http? How can I find the root cause of the https Error 500?

Thank you!

**Comment by gitman23** [comment]
Solved the 500 by opening the ports 80 and 443 with ufw command and afterwards restart of btcpay.
Now working as expected on both https and onion version :)
