### ISSUE TITLE
Import from ColdCard (AirGap) - No dialog prompt

### ISSUE THREAD

**Issue by mechawrench** [btcpayserver/btcpayserver#1326]
**Describe the problem/bug**
Import from ColdCard (AirGap) for wallet does not present a dialog prompt to import the wallet file.  This has worked in the past but now does not seem to work.  As a result I am unable to import ColdCard through a wallet file import.

**Your environment**
* Version of BTCPay Server: v1.0.3.156
* Deployment method: LunaNode automated deployment
* Other relevant environment details:  Attempted on Safari, Brave, Chrome all without any Adblockers.  Also tried on 3rd party service BTCPayJungle with same results.

**Logs (if applicable)**
N/A

**To Reproduce**
1. Go to Derivation Scheme on a store, click modify
2. Click on "Import from ColdCard (AirGap)"
3. See that no prompt is present and as a result it isn't possible to import the ColdCard wallet

**Expected behavior**
In the past a dialog prompt would present that allowed for import from ColdCard file.

**Actual behavior**
No dialog shows, doesn't seem to do anything.

**Screenshots/Links**
N/A

**Additional context**
N/A

**Comment by Kukks** [comment]
Sorry about that, fixed and should make it in next release
