### ISSUE TITLE
RTL QR Code Error: code length overflow

### ISSUE THREAD

**Issue by jimbojw** [btcpayserver/btcpayserver#1332]
**Describe the problem/bug**

RTL service is not producing a QR Code to connect. 

**Your environment**
* Version of BTCPay Server: v1.0.3.156
* Deployment method: LunaNode

**To Reproduce**
1. Go to 'Services'
1. Under 'Crypto services', find 'Ride the Lightning server', click on 'See information'
1. Click 'Show confidential QR Code'

**Expected behavior**
Expect to see the QR Code.

**Actual behavior**
Where the QR Code should be, there is a tiny white box.
In the developer console, is the following error, attributed to qrcode.js:

```
Error: code length overflow. (1604>1056)
```

**Comment by jimbojw** [comment]
Any idea how I can approach this? Is there a workaround? I was hoping to use Zeus with my `lnd` instance, but I don’t know of another way to get the info to Zeus.

**Comment by pavlenex** [comment]
I believe that even Zeus tells you where to get the information in their UI.
You need Server Settings > Services >  LND (REST server), what you were trying to do would just open RTL on your phone, nothing to do with connecting to an external wallet.
