### ISSUE TITLE
Add Ability to revoke "Legacy Api Keys"

### ISSUE THREAD

**Issue by mjlamb** [btcpayserver/btcpayserver#1333]
In the [Access Token] screen it would be a good feature to be able to revoke "Legacy API Keys"

There is the ability to revoke Access Tokens, this is to be able to revoke Legacy Api Keys, it seems a security issue to have old keys still active.

**Comment by NicolasDorier** [comment]
@mjlamb normally you can regenerate a new API Key which revoke the previous one.

**Comment by mjlamb** [comment]
@NicolasDorier True, but you cannot completely remove in that case, which just seems a little strange.
