### ISSUE TITLE
Impossible to use bitcoin-cli.sh (and to synch)

### ISSUE THREAD

**Issue by Feyynt** [btcpayserver/btcpayserver#1334]
**Describe the problem/bug**

Hello! I'm continuing to have problems during synchronization (i'm at 25%):

1. Bitcoin core stopped to sync without errors in the logs
2. btcpay-down.sh
3. btcpay-up.sh (here it had porblems in starting the container "btcpayserver_bitcoind", btcpay removed it and created a new one with some numbers at the beginning (like 023455_btcpayserver_bitcoind)
4. It was impossible to use Bitcoin Core commands (with bitcoin-cli.sh), returning the error: the container btcpayserver_bitcoind doesn't exist
5. I renamed the container from 023455_btcpayserver_bitcoind to btcpayserver_bitcoind
6. now trying to use bitcoin-cli.sh it return the error: "cannot exec in a stopped state: unknown"

Of course I tried to start and restart the container and btcpayserver, but nothing changed

**Your environment**
* updated 13/02/2020
* Docker 

**Expected behavior**
Node continuing to sync

**Actual behavior**
Not possible to sync bitcoind, it doesn't restart to download blocks

**Comment by NicolasDorier** [comment]
1. Do not rename the container name
2. Update docker-compose there was one version (I think 1.23.x) which had such behavior, this was reverted.

**Comment by Feyynt** [comment]
Great, solved! It started again to sync! Thank you very much
