### ISSUE TITLE
c# BitPay NBitpayClient.Invoice() Expiration not set

### ISSUE THREAD

**Issue by mjlamb** [btcpayserver/btcpayserver#1336]
When using the NBitpayClient.Invoice() class and setting the .ExpirationTime property.
This does not set the expiration time of the individual invoice and inherits the store default setting.

**Expected behavior**
When setting the ExpirationTime property this should set against the individual invoice in BtcPayServer..

**Actual behavior**
When set it uses the Store setting and the Expiration property is ignored.

**Comment by NicolasDorier** [comment]
This is strange, does the invoice in the checkout has the proper expiration time?

**Comment by mjlamb** [comment]
The invoice default to using the store expiration tine which is 15mins in my case, so yes the invoice has this as the correct expiration time. Kukks commented on this in the telgram and said was a problem with the Api not setting it or using it. So he seems to no the problem.

**Comment by NicolasDorier** [comment]
@mjlamb so I checked on my own btcpay instance via PostMan if the API was correct, and it is.
Maybe a problem in the lib? @Kukks ?

**Comment by mjlamb** [comment]
Can you send me the postman example to try here also?

**Comment by mjlamb** [comment]
I guessing I'm meaning the lib is the problem. Yes the NBitPay Client lib c# nuget.

**Comment by mjlamb** [comment]
I should post this here then ah! https://github.com/MetacoSA/NBitpayClient

**Comment by NicolasDorier** [comment]
```json
{
	"info": {
		"name": "BTCPay Server",
		"_postman_id": "b9b210df-05c5-a577-d8ed-1759aaca29a6",
		"description": "",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "https://mainnet.demo.btcpayserver.org/invoices",
			"request": {
				"method": "POST",
				"header": [
					{
						"key": "X-Forwarded-Proto",
						"value": "http",
						"disabled": true
					},
					{
						"key": "Content-Type",
						"value": "application/json"
					},
					{
						"key": "Authorization",
						"value": "Basic R01MVnI3dkJIWm5EWVdwb2hMMHBrVWQ3cm92bzE3SEgwV0VkV292a0VwYg=="
					}
				],
				"body": {
					"mode": "raw",
					"raw": "{\n\t\n}"
				},
				"url": {
					"raw": "https://mainnet.demo.btcpayserver.org/invoices",
					"protocol": "https",
					"host": [
						"mainnet",
						"demo",
						"btcpayserver",
						"org"
					],
					"path": [
						"invoices"
					]
				},
				"description": "Create an invoice"
			},
			"response": []
		}
	]
}
```

**Comment by pavlenex** [comment]
@mjlamb were you able to solve this issue? If so please close it.

**Comment by ravcodebase** [comment]
No not resolved, but is a NBitpayClient.Invoice() problem with setting expiration time not being honored.

**Comment by mjlamb** [comment]
No not resolved, but is a NBitpayClient.Invoice() problem with setting expiration time not being honored.

**Comment by NicolasDorier** [comment]
I understand now. You want to set the expiration in code. I can fix that.

**Comment by mjlamb** [comment]
You rock, that right I'm trying to set the TimeSpan from the NBitPayCLient but it is ignored. Let me know when fixed I'll test. It the least I can do!

**Comment by NicolasDorier** [comment]
@mjlamb wait, this is not a TimeSpan, this is a DateTime right?

**Comment by mjlamb** [comment]
The NBitPayClient ExpirationTime is DateTimeOffset. 
![image](https://user-images.githubusercontent.com/2274034/75228819-a2f8e700-5815-11ea-8c00-728e3f27cb1d.png)

**Comment by mjlamb** [comment]
Tested and not working, I set the NBitpayClient Api via...

invRequest.ExpirationTime = new DateTimeOffset(DateTime.Now.AddMinutes(30));

Expected outcome to have inovice expire @ 8:38:20pm

But the invoice was set to the default 5min expiry still. 


![image](https://user-images.githubusercontent.com/2274034/76061625-ccb9c700-5fe8-11ea-8fbf-33e2049c1fc7.png)

**Comment by NicolasDorier** [comment]
It was a problem on the library, pushed 1.0.0.38 which should fix your issue.

**Comment by mjlamb** [comment]
Hi @NicolasDorier Just pulled that new package and tested it.
Its working but I'd just point out a thing I noticed,

Created date 3/10/2020 9:39:40 PM
Expiry Date 3/10/2020 9:41:37 PM

Although I set a test to expire in 2mins it was not quite 2mins from the Created date, there is 3 second diff in there, so I wonder if you have based of DateTime.Now() maybe the offsite should be off the CreationDate. So should be 9:41:40 PM

Thanks for the fix BTW.

**Comment by mjlamb** [comment]
All good, this is working as expected. Thanks

**Comment by NicolasDorier** [comment]
@mjlamb I take the exact time you are passing.
Created date is set at the time we enter in the `CreateInvoiceCore` function, so it mean it took 3 sec for your http request to reach this point.

**Comment by NicolasDorier** [comment]
Or more probably there is a clock difference between the server and your client.
