### ISSUE TITLE
FATAL ERROR: After invoice is paid it forces to iframe btcpay store

### ISSUE THREAD

**Issue by whiteyhat** [btcpayserver/btcpayserver#1338]
**Describe the problem/bug**
Using the client library to pop up check-out modals causes fatal errors `<script src ="https://btcpay/modal/btcpay.js"></script>`

**Your environment** 
* Version of BTCPay Server: ` v1.0.3.144` 
* Deployment method: `Lunanode on-click deployment`

**To Reproduce**
1. Implement the btcpay client library
2. Paste the following code for a test:
```
const invoiceCreation = {
                /"price": asset.price,
                "buyerEmail": email,
                "currency": "USD",
                "orderId": asset.name + "-" + asset.uuid,
                "itemDesc": "Buying " + asset.name + " at play.lightnite.io",
                "notificationUrl": "http://f6e539e1.ngrok.io/api/v1/asset/purchase/" + asset.uuid,
                "notificationEmail": "carlos@satoshis.games"
            };
```

> As you can see, I do not specify any value `redirectUrl` because I do not want the window location to change since that is the purpose of check-out modals

3. Pay the invoice

**Expected behavior**
When the invoice is paid the modal, the client library should not force to redirect to the login page of my btcpay instance.

**Actual behavior**
When the invoice is paid the modal, the client library should force to redirect to the login page of my btcpay instance.

**Screenshots/Links**
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/31220861/74591078-13815600-5015-11ea-8006-14192d3ded7c.gif)

**Comment by whiteyhat** [comment]
On the gif, the console log  after the invoice is paid is the following:

```
Refused to display 'https://buy.lightnite.io/Account/Login' in a frame because it set 'X-Frame-Options' to 'deny'.
```

**Comment by pavlenex** [comment]
@Kukks Any ideas?

**Comment by Kukks** [comment]
Writing an e2e test to try and replicate.

**Comment by Kukks** [comment]
I wrote a test and could not recreate your issue
https://github.com/btcpayserver/btcpayserver/pull/1342

How are you calling the btcpay modal library?

**Comment by whiteyhat** [comment]
I am importing the library using this: https://docs.btcpayserver.org/integrations/customintegration

**Comment by Kukks** [comment]
I was referring to the modal.js usage

**Comment by whiteyhat** [comment]
Sorry!  I missed the following function `window.btcpay.onModalWillLeave(yourCallbackFunction);` to kill the iframe. All solved
