### ISSUE TITLE
UI/UX issue: should not show QR code or "Awaiting Payment" until after "Continue" button is clicked

### ISSUE THREAD

**Issue by taoeffect** [btcpayserver/btcpayserver#1339]
**Describe the problem/bug**

This UI is extremely confusing (to me, and others I suspect):

<img width="388" alt="Screen Shot 2020-02-16 at 1 40 16 PM" src="https://user-images.githubusercontent.com/138706/74613788-5fd89e80-50c6-11ea-87e3-b029d5b1f7e8.png">

A countdown appears saying "Awaiting Payment", yet no QR code or address is visible.

**Expected behavior**

The countdown and "Awaiting Payment" message should appear only **after** the QR code / address are shown. In this case, if the email address is required, then only after it is entered and the Continue button is pressed.

**Actual behavior**

The UI gives me (the user) the impression that the entire payment system is completely broken.

**Screenshots/Links**

See above.

**Comment by pavlenex** [comment]
First of all, the email requesting is an optional feature, disabled by default, which means only a certain type of users who want to collect email will use it.

Second, Invoice is created at that time, so in my opinion the timer is useful here since it creates a sense of urgency.

Could we maybe improve the text, if so, what could be added instead? We haven't received many complaints like this and I'm just trying to figure out what can be done here, the e-mail feature was even enabled by default for year and a half.

I'm not against removing the timer, but just trying to understand if it is beneficial to do it.

**Comment by taoeffect** [comment]
Is it worth it? Yes, I'm pretty certain you are losing quite a large number of users who don't even bother to open an issue for this. They see this screen, scratch their head, and go away thinking Bitcoin doesn't make sense without saying a word.

Don't show a countdown timer, don't generate any sort of invoice thing, until you are telling the user how they can pay it.

If you tell them that you're waiting for them to pay, without explaining how how they can pay, all that accomplishes is frustration. I can't tell you have many times I've encountered  this issue and just didn't bother buying the product / donating the $. I am speaking from experience. I could have opened this issue a year ago, but didn't. Only now did I decide to finally do it because I saw something I really wanted to contribute to.

**Comment by Kukks** [comment]
> 
> 
> Is it worth it? Yes, I'm pretty certain you are losing quite a large number of users who don't even bother to open an issue for this. They see this screen, scratch their head, and go away thinking Bitcoin doesn't make sense without saying a word.
> 
> Don't show a countdown timer, don't generate any sort of invoice thing, until you are telling the user how they can pay it.
> 
> If you tell them that you're waiting for them to pay, without explaining how how they can pay, all that accomplishes is frustration. I can't tell you have many times I've encountered this issue and just didn't bother buying the product / donating the $ thinking the server was broken or my ad blocker was blocking something. I am speaking from experience. I could have opened this issue a year ago, but didn't. Only now did I decide to finally do it because I saw something I really wanted to contribute to, _and_ someone explained to me what I had to do to get the payment information. And I'm supposedly a Bitcoin expert.

`Don't show a countdown timer, don't generate any sort of invoice thing, until you are telling the user how they can pay it.`
This is how BTCPay works. If you provide the email while creating the invoice or turn off the email requirement, the user is not prompted to enter the email. The timer only starts on invoice creation.

**Comment by taoeffect** [comment]
> This is how BTCPay works. If you provide the email while creating the invoice 

The screenshot above shows the timer has started, the text "Awaiting payment" is visible, and no email has been provided. Nor is there any indication that an email is required in order to send payment.

**Comment by pavlenex** [comment]
> Hire yourselves a UX expert.

This is FOSS. Our "UX experts" are our users, which imo are the only "experts we need". 

Your feedback is appreciated and will be taken into consideration.

**Comment by pavlenex** [comment]
I'm not quite sure if the text should be the same (we have it translated already so it may not be worth changing it at this point).

![74613788-5fd89e80-50c6-11ea-87e3-b029d5b1f7e8](https://user-images.githubusercontent.com/36959754/75169027-22a88800-5728-11ea-9205-f0c3ad964578.png)

**Comment by bolatovumar** [comment]
I think @taoeffect is right here in that this could be confusing to some users as it does look like the payment is being awaited yet there is no way to pay and you only see the e-mail input field.

I think what @pavlenex has above is better as now the only thing the user sees is the input field so it doesn't look like you are supposed to pay right at that moment. However, I think it might also be useful to add a short line below the existing text to let the user know that once the user provides the e-mail, they can will be taken to the payment screen.

**Comment by pavlenex** [comment]
@bolatovumar Agreed. Let's brainstorm on the text though. Any text change means all translations have to be updated, so it's best we think this through and use the opportunity to see if current text makes sense. It should be concise, universal and easy to translate.

**Comment by bolatovumar** [comment]
@pavlenex are these strings editable by the merchants? I feel like some merchants would probably like to be able to change them.

**Comment by pavlenex** [comment]
@bolatovumar They aren't.
The idea was to allow that in #863 but perhaps it's a good idea to allow people to add their own text (besides standard one) since 863 itself feels like a huge feature that will take a lot of time to be built in. Merchants being able to leave custom instructions really makes ton of sense.

I believe that once the user selects `Requires a refund email` in Store > Checkout experience we can show a custom text field.

**Comment by bolatovumar** [comment]
@pavlenex the problem with having the text customizable through the UI like that is that it you are limited to having this text in only one language now.

**Comment by pavlenex** [comment]
@bolatovumar Yes, but one can easily type custom text  in Spanish in there if needed and we can have the default translated, is that what you mean?

**Comment by bolatovumar** [comment]
@pavlenex i assume once you enter some text into that field then this text gets used and you can't have it be in some other language. I wanted to add this type of field with text to allow merchants to specify some text about the fee users should pay but @NicolasDorier suggested I don't have this field in the UI as it would make the text not translatable.

**Comment by pavlenex** [comment]
@NicolasDorier I don't understand. If I am from Spain and I set my invoice default language to Spanish, I'd add custom text  in obviously Spanish myself and would need no translations for it. If you don't type anything in the custom text field = default which is already translated.

I think a custom text field would be really needed and would solve plenty of UX issues for buyers and merchants who don't use CMS with BTCPay Server.

**Comment by NicolasDorier** [comment]
@pavlenex it should be more than a "custom text field". Potentially any string present in there should be translatable.

The best way is that in Checkout Experience we have a link: "Set translations". This would just show 1 textbox per line in the `en.json` file. Allowing the user to override his own strings.

**Comment by pavlenex** [comment]
A default string can be translated, but once user starts writing over it, they'll write in their own language a custom text anyway, so we can't translate these and there's no need to.

Default custom field text string: Bla bla bla
I start editing text in Spanish : Ola Ola Ola
My customers need Ola Ola Ola they don't care about bla bla bla translation

Perhaps I am lost in translation, but I see no reason to have a translation for this field, as it would allow people to add custom checkout instructions, which are individual for each merchant.

**Comment by pavlenex** [comment]
Thinking about this @NicolasDorier I think you're right. It may not be used, but it will look messy. The approach you outlined is probably the best course of action, though it will cause a mess and cutter in the UI most likely.

**Comment by Kukks** [comment]
It would need to be an override file so `en.custom.json` else they would be
replaced in the next update

**Comment by pavlenex** [comment]
This is now better handled in optional checkout v2 #4157 #4137 , test it out and let us know.
