### ISSUE TITLE
Bitcoin average issue

### ISSUE THREAD

**Issue by michnovka** [btcpayserver/btcpayserver#1347]
I am getting misleading error over API invoice creation since yesterday:

 ```
[error] => Warning: No wallet has been linked to your BTCPay Store. See the following link for more information on how to connect your store and wallet. (https://docs.btcpayserver.org/getting-started/connectwallet)
2/22/20 8:18:52 AM: Creation of invoice starting
2/22/20 8:18:52 AM: BTC_USD: The rating rule is (coinaverage(BTC_USD)) * (0.97, 1.03)
2/22/20 8:18:52 AM: BTC_USD: The evaluated rating rule is (ERR_RATE_UNAVAILABLE(coinaverage, BTC_USD)) * (0.97, 1.03)
2/22/20 8:18:52 AM: BTC_USD: Rate rule error (RateUnavailable)
2/22/20 8:18:52 AM: BTC_USD: Exception reaching exchange coinaverage (Unauthorized access to the API, premium plan needed)
```

The error saying that No wallet has been linked is misleading. The error has been narrowed down to coinaverage issues. When I use binance, I get the same error, just with binance(BTC_USD) function. Before I figured this out, I created new store and new wallet, the issue was the same. I had to switch to bittrex for my server to work.

I even have paid bitcoincoinaverage plan, and while it shows correct increased quota (meaning I use correct API key and secret), for some reason this error I get always when calling create invoice API.

Running btcpay server 1.0.3.136 on lunanode

**Comment by pavlenex** [comment]
That error message is terrible. I really want us to improve it.

Try updating your btcpay.

**Comment by michnovka** [comment]
As this was related to a super ancient version of BTCPay, I am closing the issue. If I find the same misleading error in an up-to-date version, I will open a new one
