### ISSUE TITLE
btcpay-update.sh problem

### ISSUE THREAD

**Issue by darkban** [btcpayserver/btcpayserver#1348]
have a problem when start update whit command btcpay-update.sh i received this error

```
error: Your local changes to the following files would be overwritten by merge:
        groestlcoin-lightning-cli.sh
Please, commit your changes or stash them before you can merge.
Aborting
```

how to fix?

**Comment by pavlenex** [comment]
@darkban Try this, it worked for people who experienced the issue.

```
sudo su -
cd  btcpayserver-docker
git reset --hard origin/master
btcpay-update.sh
```
@NicolasDorier can we investigate a bit closer why this issue happens? Several people reported that this file breaks from them and this is terrible situation that alt file can break entire update for people even though they don't have it activated as environment variable. We had 5-6 people reporting this issue.

**Comment by NicolasDorier** [comment]
Yes, it is a terrible situation, I have no idea what provoke it, I need to get access to a machine that can reproduce that. I don't understand.

**Comment by pavlenex** [comment]
I'll keep an eye if people continue to report this and ask someone to investigate a bit deeper or provide an access so we can fix it.

@darkban have you applied the fix? If not can you maybe help us find the root of the problem?

**Comment by pavlenex** [comment]
There have been no more reports from people about this issue, so I'll close it for now.

If someone is facing an issue, let us know and we will re-open it.
