### ISSUE TITLE
Feature Request: Differenciate on-chain and off-chain payment method for expired invoices

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#137]
So far it's possible to differentiate on chain and off-chain paid and completed payments.
However there is no way to differentiate them for expired or cancelled invoices.

LN is still new and sometimes people need help, our use case from this feature would be the ability to tell the difference between the on-chain and off-chain (LN) expired invoice and send an email to the customer manually with some tips on how to troubleshoot the issue.

In future it the differentiation should be in form of custom fields so that automatic emails, reports and events can be triggered. But for now, let's start small and do the a change in invoices for the expired/cancelled ones if possible.

**Comment by NicolasDorier** [comment]
the thing is that all invoices have on-chain and off-chain payment methods. We have no way of knowing which the user wanted to use.

**Comment by bitcoinshirt** [comment]
Closing this after plenty of discussion on Slack. It's not possible.
