### ISSUE TITLE
Call GetMempoolEntry on RBF unconfirmed txs on next block event/ periodically

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#1371]

**Comment by NicolasDorier** [comment]
please can you tell more about why you need this?

**Comment by Kukks** [comment]
* `Store A` with `DerivationScheme A` creates an invoice for `0.1BTC` payable to `Address A`
* `User A` creates `Transaction A`, signalling RBF and spending `UTXO1` to `Address A`   and sending change to his change `Address B`. `User A` signs and broadcasts `Transaction A`.
* `Store A` detected payment, adds it to `invoice A` as `Accounted` and marks invoice as paid.
* `User A` creates `Transaction B`, signalling RBF and spending all of `UTXO1` to `Address B` , with a higher fee than `Transaction A`.  `User A` signs and broadcasts `Transaction B`.
* `Store A` does not ever find out about `Transaction B` because it does not have any outputs to `DerivationScheme A`/ `Address A`.
* `Invoice A` is still marked as `Paid` and the payment is still marked as `Accounted` even though `Transaction A` has been removed from the mempool. Calling `getmempoolentry TransactionA` results in it not being found.
* NBX still returns the Transaction when calling `v1/deriv/{deriv}/transactions` and it is not in the `Replaced list`.  Calling `v1/deriv/{deriv}/ttransactions{Transaction A}` also returns the transaction as if everything is still valid.
* Even after blocks have passed, the transaction stays in the same status, never being marked as replaced.

**Comment by Kukks** [comment]
3 scenarios where this matters:
* stores using 0 conf( why on earth is this even available) as their confirmed  status
* physical shops showing the checkout, ( #1330 and then extending it to show danger red  color if it has been replaced with the `getmempoolentry` rpc check call)
* payjoin #1321 , where I have to monitor for malicious users trying to spy on utxos by broadcasting a payjoin and then double spending their own inputs to cancel the payment. While I can't add enough protection, I  need to realize the tx has been replaced to put the exposed utxos in a prioritized bag

**Comment by NicolasDorier** [comment]
This is not a problem as the invoice will never pass to the Confirmed state.
The transactions normally get periodically rebroadcasted so NBX should eventually remove from the transaction list of the store. (even if BTCPayServre still show the tx in invoice details)

**Comment by NicolasDorier** [comment]
* stores using 0 conf( why on earth is this even available) as their confirmed status

We can't go from Confirmed to Paid status. If this is a problem for stores, they should use 1 conf.

**Comment by NicolasDorier** [comment]
>  I have to monitor for malicious users trying to spy on utxos by broadcasting a payjoin and then double spending their own inputs to cancel the payment. 

I need to read your code, but this should not be needed, it can use the same logic as how we do currently.

**Comment by Kukks** [comment]
> 
> 
> > I have to monitor for malicious users trying to spy on utxos by broadcasting a payjoin and then double spending their own inputs to cancel the payment.
> 
> I need to read your code, but this should not be needed, it can use the same logic as how we do currently.

In terms of validating the payment, it is no issue. This is for spam protection so that I put the compromised utxo in the queue for next payjoin to use and get rid of it.

**Comment by Kukks** [comment]
> 
> 
> This is not a problem as the invoice will never pass to the Confirmed state.
> The transactions normally get periodically rebroadcasted so NBX should eventually remove from the transaction list of the store. (even if BTCPayServre still show the tx in invoice details)

What's the criteria for it to rebroadcast? Is it a timer?

**Comment by pavlenex** [comment]
#1382
