### ISSUE TITLE
UX Improvement: Wallet Transaction Label function only allows 20-byte labels and "Transactions" page "balance" is not balance

### ISSUE THREAD

**Issue by maltokyo** [btcpayserver/btcpayserver#1373]
Labels are 20 bytes only, and comments are longer.  But 20 bytes is not really usable. 

 What about just have one field, for "label" that is longer and just display the first 20 bytes in transaction list, and show all when it is clicked..  Not sure why we need two fields for this.

**Comment by maltokyo** [comment]
> It does show the balance, have you re-scanned your wallet? If you'd had transactions prior to BTCPay xpub inport, those won't be fetched unless you `utxoscan` in Wallet > Re-scan
This page: https://my.btcpay.com/wallets shows balance, you are right.  But then click on the "manage" action at the right for one of the wallets.  In the next screen, there is also a balance column.  It does not show balance, but only transaction value.  Does it make sense?

**Comment by pavlenex** [comment]
I see, you're right. What would you prefer here instead of the `Balance` what would be more correct wording? Perhaps `Amount`?

I still don't understand 100% what you [meant](https://github.com/btcpayserver/btcpayserver/issues/1373#issuecomment-593105959) with

> Maybe an entry field in the middle of the screen to enter text would be better?

**Comment by maltokyo** [comment]
I guess another column is needed, one should be "Transaction Amount" and the last column should remain "Balance".  The current field for "balance" should be the amount of the transaction, and in balance field, it should have the current balance after that transaction in the same row took place. 

Regarding the label and comment entry fields, I will come back on this with some screenshots.

**Comment by Kukks** [comment]
No longer limited to 20 chars after #1499
