### ISSUE TITLE
concerned about Derivation Scheme change

### ISSUE THREAD

**Issue by ChrizVR** [btcpayserver/btcpayserver#1374]
I develop a BTC Terminal for a company and I am concerned about the Derivation Scheme.
I paired and generated a client with nodeJS as a backend. It all worked fine, but when i modify my Derivation Scheme on the Store settings, I can still create Invoices and connect with the same client. Is this the normal behavior? Because isn't it a security issue? when a bad guy can get access to the settings and change the Derivation Scheme I will never know and all the future payments will go in the bad guys wallet and I will not notice it. I was assuming when the Derivation Scheme is changed i loose connection and have to generate a pairing code again.

Maybe we can get a solution to get an email notification at least when the Derivation Scheme changed. I am really concerned and this issue holds me back to continue developing. It may take a month for the company to notice the change, that the BTC are not reaching the companies wallet and then its to late.

Yes there are no private keys in the BTC Pay Server, but when someone malicious change the Scheme they have the private key for the future payments.

**Comment by Kukks** [comment]
Pasting what I replied on Telegram:

> You pair with a store, which consists of its own identifier, and has a bunch of other data.  Changing the derivation does not change the identifier so of course nothing is or should be expected to happen

> Of course, maybe this could be part of some enhanced security scheme. I've heard it before to create more awareness around changing wallet configurations. 
> 
> Maybe:
> * a lock file on the machine that if present does not allow you to edit any wallet. 
> * reauthorization on the wallet edit page and other sensitive page.
> * an event log of actions that occurred on the server along with an email alert to notify you of anything serious
> 
> Have to be realistic here though in that, they have to gain access to your account to modify the wallet, and if they can do that, they can probably toggle alerts off, and probably have a way to authorize and edit the wallet config in the store. If you're not an admin of the server, it's also frivolous to add all this security as the admin can just disable all your 2fa and gain access of your store at any moment with a few commands. 
> 
> I'm open to ideas but please create an issue on our github so we track and discuss openly and in an organized fashion

**Comment by Kukks** [comment]
Also, if you are worried about attackers gaining access to your account, enable U2F/ 2FA and use your own server.

**Comment by ChrizVR** [comment]
thank you. Activated the 2FA today and it runs on my own build server.
Its connected to the internet, maybe i am to paranoid :-)

**Comment by pavlenex** [comment]
I think an email notification can be a decent protection mechanism against front-end attacks by workers. But it would be better if we could limit their access via certain roles #442 a combo of both can be good. May be a good idea to add in #775 

But against over the internet, it adds false sense of security imo. 

For now you can set up an external wallet that pings you when payment is made so when it does not ping you and you have orders, you'll know something is not good. Obviously this doesn't scale for large businesses but for small shop it can be decent until we figure it out. In the future external btcpay app could be able to do this and warn you.

**Comment by pavlenex** [comment]
Closing this as it can be suggested in #1320 as the feature of the upcoming API and it can't really be done properly until we close #1263
