### ISSUE TITLE
Wallet disappear after BTCPAY Upgrade

### ISSUE THREAD

**Issue by lbar83** [btcpayserver/btcpayserver#1377]
Dear,

after that we have upgraded BTCPAY at the latest version, on one of the stores configured suddently the client could not connect to the BTCPAY server for this reason:

`Warning: No wallet has been linked to your BTCPay Store. See the following link for more information on how to connect your store and wallet. (https://docs.btcpayserver.org/getting-started/connectwallet) 3/9/2020 10:20:21 AM: Creation of invoice starting 3/9/2020 10:20:21 AM: BTC_EUR: The rating rule is abcc(BTC_EUR) 3/9/2020 10:20:21 AM: BTC_EUR: The evaluated rating rule is ERR_RATE_UNAVAILABLE(abcc, BTC_EUR) 3/9/2020 10:20:21 AM: BTC_EUR: Rate rule error (RateUnavailable) "`

this is weird due that the xpub is still present on the store on btcpay. And nothing is changed.
Moreover, we have created a new store on btcpay, with exactly the same data of the one that does not work. The new store works great.

Any ideas?

**Comment by pavlenex** [comment]
What's your BTCPay version?

**Comment by NicolasDorier** [comment]
I may check in the code, but maybe the error message is not good.

As you can see, the error below show that the invoice could not be created because `abcc` is not a valid exchange.

**Comment by pavlenex** [comment]
Yes @NicolasDorier we really must improve this error message it's really confusing.

**Comment by NicolasDorier** [comment]
My guess is that when @lbar83 updated, he was using an exchange supported by bitcoin average, but not anymore. As such, the update broke his stores, and the message mislead him.

@lbar83  The fix is just to find a different rate provider in the rate's settings of your store.
