### ISSUE TITLE
Acctept BTC in retail store

### ISSUE THREAD

**Issue by PayBitcoin** [btcpayserver/btcpayserver#138]
I want to accept BTC in my store (Example, Costumer comes in my store, buys a sandwich and want to pay with BTC without typing his email)
1. Costumer choise sandwich and a coke
2. I create new invoice for him and click checkout
3. Costumer scan QR code and send paymend in BTC

**Comment by NicolasDorier** [comment]
this is already possible

**Comment by NicolasDorier** [comment]
closing this

https://twitter.com/BtcpayServer/status/989496101672665088

https://twitter.com/BtcpayServer/status/989405539913248768
