### ISSUE TITLE
RTL update to v0.6.7

### ISSUE THREAD

**Issue by alevchuk** [btcpayserver/btcpayserver#1380]
**Describe the solution you'd like**

Update to the latest release of RTL https://github.com/Ride-The-Lightning/RTL/releases

**Additional context**

I'm looking for the major update of RTL, in particular "Sign messages with your pubkey and verify message-signature pair (LND)."

**Comment by alevchuk** [comment]
version is configured here https://github.com/btcpayserver/btcpayserver-docker/blob/310b0a388232984425718075bf0e19ece7157ca1/docker-compose-generator/docker-fragments/bitcoin-lnd.yml#L42

**Comment by pavlenex** [comment]
We're now on[ v0.6.8](https://twitter.com/BtcpayServer/status/1237605825796952064).
