### ISSUE TITLE
No updates details in UI 

### ISSUE THREAD

**Issue by Transisto** [btcpayserver/btcpayserver#1385]
There's currently no way to see anything that's being done when clicking Update.
beside:
![image](https://user-images.githubusercontent.com/388716/76493900-1a2f9d00-640a-11ea-98b7-93633485a3e2.png)

_The server **might** restart soon if an update is available..._ 

Current and updates version should be visible.

Log file doesn't say much either, of whether it's been successfully updated or not.

```
2020-03-12 07:49:41.910 +00:00 [INF] Running SSH command: . /etc/profile.d/btcpay-env.sh && nohup btcpay-update.sh > /dev/null 2>&1 & disown
2020-03-12 07:49:42.562 +00:00 [INF] SSH command executed with exit status 0. Output: 
2020-03-12 07:53:40.390 +00:00 [INF] BTC: New block
```

**Comment by pavlenex** [comment]
There is an indicator once you click on update.
![Screenshot 2020-03-12 at 10 28 00](https://user-images.githubusercontent.com/36959754/76506980-4ff57580-644c-11ea-948c-425b98e4e417.png)

**Comment by bolatovumar** [comment]
@pavlenex I think what @Transisto means is that they would like to see something like 

>Your version: 1.x.x
>Update version: 1.x.y

**Comment by pavlenex** [comment]
Closing this due to similarities with #1420
