### ISSUE TITLE
Rescan does not update wallet balance

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#1391]
**Describe the problem/bug**
Did a rescan, found txs, balance was still 0 but transactions show in the list

**Comment by NicolasDorier** [comment]
wtf? never happened to me.

**Comment by NicolasDorier** [comment]
Did the rescan was done on a clean wallet? Or there was some transactions already before rescan?

**Comment by pavlenex** [comment]
@Kukks can you reliably replicate this? Can you give us more info on what happened here, I'm unable to replicate.

**Comment by pavlenex** [comment]
ping @Kukks

**Comment by Kukks** [comment]
cant replicate again, will count this one as a freak accident
