### ISSUE TITLE
Pay with BTCPay button can have payment amount changed using inspect element

### ISSUE THREAD

**Issue by MiLeung** [btcpayserver/btcpayserver#1392]
**Describe the problem/bug**
Users can modify the html of the button to change how much they pay

**Your environment**
Just the embedded BTCPay button in HTML

example: https://www.youtube.com/watch?v=VrQBkPkfIk8

A work around is to explicitly set the value of the price input to the actual amount?

**Comment by Kukks** [comment]
Pay buttons are not a full solution for doing e-commerce, and this issue is not solve able if you only rely on that html.

You can look into using the Pos app which can help with making sure the amounts are set correctly.

**Comment by MiLeung** [comment]
That's fair  I guess, but I thought the BTCPay button was supposed to be an equivalent to the Coinbase Commerce button.

**Comment by Kukks** [comment]
If you use the POS app in BTCPay, you can create payment buttons that work that way, though you'll have to craft the html yourself

**Comment by Kukks** [comment]
Let me try whip up some something, will get back to you soon

**Comment by MiLeung** [comment]
I was actually looking for a payment button where the price is dynamic. I like how Coinbase Commerce allows you to create a charge with a specified price with their api, and then you can just take the chargeId from the response and drop it inside their CC button (also available as a React component).

**Comment by MiLeung** [comment]
Is it possible to create  a new invoice programmatically?

**Comment by Kukks** [comment]
Yes, you can either use the endpoint that the pay button uses to create an
invoice or else use our api which is bitpay compatible.

**Comment by MiLeung** [comment]
Right thanks, I'll try that

**Comment by MiLeung** [comment]
If I [create an invoice](https://bitpay.com/api/#rest-api-resources-invoices-create-an-invoice) and get the `orderId `, is it possible to put that orderId in the Pay Button HTML and omit the `<input type="hidden" name="price" value="..." />`  line? Would the button then fetch the `orderId`s price?

**Comment by Kukks** [comment]
No, that's now how it works.

With #1395, you'll be able to do what you want by doing:
* Create POS app with items with set price
* Generate Pay button pointing to the app and item 

You can essentially already do this, just that the button generator is helpful to non-devs.

For example:
```
<form method="POST" action="https://YOURBTCPAY.com/apps/YOUR_APP_ID/pos">
  <input type="hidden" name="email" value="customer@example.com" />
  <input type="hidden" name="orderId" value="CustomOrderId" />
  <input type="hidden" name="notificationUrl" value="https://example.com/callbacks" />
  <input type="hidden" name="redirectUrl" value="https://example.com/thanksyou" />
  <button type="submit" name="choiceKey" value="YOUR ITEM">Buy now</button>
</form>
```
