### ISSUE TITLE
Add Store field on Invoices Screen / Invoices on Stores Screen

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#14]
On the invoices screen, it will show all invoices generated. This will cause issue for users who have multiple stores running on one BTCPay instance. It is hard to tell without going into the invoice, which one came from which store. Two possible solutions:

1. Add a "Store Field" to the invoices screen. This will allow the user to know which store generated which invoice. 

2. On the Stores page, add a link to each store which shows only the invoices for that store.

**Comment by NicolasDorier** [comment]
I think the best is to use filters like suggested on https://github.com/btcpayserver/btcpayserver/issues/8 where one can add a store by adding `store:STORE_ID` inside the search textbox.

**Comment by NicolasDorier** [comment]
Done in v1.0.0.35 via storeid filter
