### ISSUE TITLE
Feature request:  add btc/ltc amount in /invoices next to the fiat amount.

### ISSUE THREAD

**Issue by forkyboy** [btcpayserver/btcpayserver#140]
title is self explanatory it can be really usefull
Feature request:  add btc/ltc amount in /invoices next to the fiat amount.

**Comment by NicolasDorier** [comment]
if there is 10 supported currencies, how should it looks?

**Comment by forkyboy** [comment]
In this case : 
- maybe just show the amount and curencies used to actually pay the invoice.

ie:
 125$/X LTC

**Comment by NicolasDorier** [comment]
An invoice can be paid in several currencies. (multiple payments)

**Comment by pavlenex** [comment]
This has been a ghost issue without a reply, so closing it now.
