### ISSUE TITLE
Errors in dev env on MacOS in launchSettings.json

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1406]
**Describe the problem/bug**
When a dev enviroment is set up on MacOS, there is an issue with `launchSettings.json`.

When you build a project, it will automatically alter your `launchSettings.json` and then it's considered as a change in the PR

**Your environment** 
* Version of BTCPay Server: Dev env
* Deployment method: Docker, v3.1.102 SDK, GitHub Desktop

**To Reproduce**
1. Build a project on Mac.
2. See that it changes parameters in `launchSettings.json` that never happens on Windows.

**Expected behavior**
Project should build without any changes.

**Actual behavior**
Building project changes file parameters.

**Screenshots/Links**
![Screenshot 2020-03-22 at 18 00 04](https://user-images.githubusercontent.com/36959754/77255348-fc163800-6c66-11ea-8e1d-bbc05a03ec76.png)

![Screenshot 2020-03-22 at 18 08 22](https://user-images.githubusercontent.com/36959754/77255484-261c2a00-6c68-11ea-8334-227595d54303.png)

**Additional context**
Affected files from the screenshot above:

```
@ -50,4 +50,7 @@
    <ProjectReference Include="..\BTCPayServer\BTCPayServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Properties\launchSettings.json" />
  </ItemGroup>
</Project>
```
```
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'Docker-Regtest' ">
    <StartAction>Project</StartAction>
    <EnvironmentVariables>
      <Variable name="BTCPAY_NETWORK" value="regtest" />
      <Variable name="BTCPAY_LAUNCHSETTINGS" value="true" />
      <Variable name="BTCPAY_BUNDLEJSCSS" value="false" />
      <Variable name="BTCPAY_LTCEXPLORERURL" value="http://127.0.0.1:32838/" />
      <Variable name="BTCPAY_BTCLIGHTNING" value="type=clightning;server=tcp://127.0.0.1:30993" />
      <Variable name="BTCPAY_BTCEXTERNALLNDGRPC" value="type=lnd-grpc;server=https://lnd:lnd@127.0.0.1:53280/;allowinsecure=true" />
      <Variable name="BTCPAY_BTCEXTERNALLNDREST" value="type=lnd-rest;server=https://lnd:lnd@127.0.0.1:53280/lnd-rest/btc/;allowinsecure=true;macaroonfilepath=D:\admin.macaroon" />
      <Variable name="BTCPAY_BTCEXTERNALLNDSEEDBACKUP" value="../BTCPayServer.Tests/TestData/LndSeedBackup/walletunlock.json" />
      <Variable name="BTCPAY_BTCEXPLORERURL" value="http://127.0.0.1:32838/" />
      <Variable name="BTCPAY_ALLOW-ADMIN-REGISTRATION" value="true" />
      <Variable name="BTCPAY_DISABLE-REGISTRATION" value="false" />
      <Variable name="ASPNETCORE_ENVIRONMENT" value="Development" />
      <Variable name="BTCPAY_CHAINS" value="btc,ltc" />
      <Variable name="BTCPAY_POSTGRES" value="User ID=postgres;Host=127.0.0.1;Port=39372;Database=btcpayserver" />
      <Variable name="BTCPAY_DEBUGLOG" value="debug.log" />
      <Variable name="BTCPAY_TORRCFILE" value="../BTCPayServer.Tests/TestData/Tor/torrc" />
    </EnvironmentVariables>
    <ApplicationURL>http://127.0.0.1:14142/</ApplicationURL>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'Docker-Regtest-https' ">
    <StartAction>Project</StartAction>
    <EnvironmentVariables>
      <Variable name="BTCPAY_NETWORK" value="regtest" />
      <Variable name="BTCPAY_LAUNCHSETTINGS" value="true" />
      <Variable name="BTCPAY_PORT" value="14142" />
      <Variable name="BTCPAY_HttpsUseDefaultCertificate" value="true" />
      <Variable name="BTCPAY_BUNDLEJSCSS" value="false" />
      <Variable name="BTCPAY_LTCEXPLORERURL" value="http://127.0.0.1:32838/" />
      <Variable name="BTCPAY_LBTCEXPLORERURL" value="http://127.0.0.1:32838/" />
      <Variable name="BTCPAY_BTCLIGHTNING" value="type=clightning;server=tcp://127.0.0.1:30993" />
      <Variable name="BTCPAY_BTCEXTERNALLNDGRPC" value="type=lnd-grpc;server=https://lnd:lnd@127.0.0.1:53280/;allowinsecure=true" />
      <Variable name="BTCPAY_BTCEXTERNALLNDREST" value="type=lnd-rest;server=https://lnd:lnd@127.0.0.1:53280/lnd-rest/btc/;allowinsecure=true" />
      <Variable name="BTCPAY_BTCEXTERNALLNDSEEDBACKUP" value="../BTCPayServer.Tests/TestData/LndSeedBackup/walletunlock.json" />
      <Variable name="BTCPAY_BTCEXTERNALSPARK" value="server=/spark/btc/;cookiefile=fake" />
      <Variable name="BTCPAY_BTCEXTERNALCHARGE" value="server=https://127.0.0.1:53280/mycharge/btc/;cookiefilepath=fake" />
      <Variable name="BTCPAY_EXTERNALCONFIGURATOR" value="passwordfile=testpwd;server=/configurator" />
      <Variable name="BTCPAY_BTCEXPLORERURL" value="http://127.0.0.1:32838/" />
      <Variable name="BTCPAY_ALLOW-ADMIN-REGISTRATION" value="true" />
      <Variable name="BTCPAY_DISABLE-REGISTRATION" value="false" />
      <Variable name="ASPNETCORE_ENVIRONMENT" value="Development" />
      <Variable name="BTCPAY_CHAINS" value="btc,ltc,lbtc" />
      <Variable name="BTCPAY_POSTGRES" value="User ID=postgres;Host=127.0.0.1;Port=39372;Database=btcpayserver" />
      <Variable name="BTCPAY_EXTERNALSERVICES" value="totoservice:totolink;" />
      <Variable name="BTCPAY_SSHCONNECTION" value="root@127.0.0.1:21622" />
      <Variable name="BTCPAY_SSHPASSWORD" value="opD3i2282D" />
      <Variable name="BTCPAY_DEBUGLOG" value="debug.log" />
      <Variable name="BTCPAY_TORRCFILE" value="../BTCPayServer.Tests/TestData/Tor/torrc" />
    </EnvironmentVariables>
    <ApplicationURL>https://localhost:14142/</ApplicationURL>
  </PropertyGroup>
```

I have no clue what happens here, I know @Eskyee reported this issue months ago and tried to troubleshoot it with @rockstardev but with no success, so leaving it here as a notice. It does not affect a workflow besides being annoying thing you always have to discard. Probably has to do something with the host.

**Comment by Eskyee** [comment]
Lol 😂 thank you Pav, Thought I was going mad, had this problem like three months, nightmare on a Mac 💻 told Rockstar Kukks and Nicolas about this Bug , you will also find a double Json file sometimes in vs !! BTCPay/ Property’s folder !! This has been a pain in my side lol 😝 launchSettings.json  good luck 😉 this dup does not happen in Visual Studio Code... Just VS  I must of been the only person to see this !! Bug, I made a issue on this , already before

**Comment by Eskyee** [comment]
That’s why I got bored !! Lol no one could solve it !! 👀 it started when kukks worked on Monero, that’s when I found this error in json around that time pav

**Comment by Eskyee** [comment]
😂🦠

**Comment by Eskyee** [comment]
Also the sdk got updated from Microsoft!! I’m sure it’s there bug

**Comment by pavlenex** [comment]
Related #1042

**Comment by Eskyee** [comment]
![A4C27E18-5371-46BD-A7B9-14543269A4EA](https://user-images.githubusercontent.com/30862925/77255828-36c9a180-6c62-11ea-87dc-f55137e4028b.jpeg). Don’t happen in VS Code, but can still create the config json bug

**Comment by Eskyee** [comment]
That’s is a btcpayserver github showing that bug

**Comment by Eskyee** [comment]
Level up Pav 📡

**Comment by Eskyee** [comment]
Check also the btcpayserver.csproj. Sometimes that showed a bug, I’m sure

**Comment by Eskyee** [comment]
![33B732D0-07B1-46BD-A7F4-B09B883396C2](https://user-images.githubusercontent.com/30862925/77256013-6cbb5580-6c63-11ea-8c3d-bed5fc1f733a.jpeg). This bundleconfig.json is also a bug !! On a Mac !! btcpayserver  github build

**Comment by Eskyee** [comment]
Shows 3 copy’s !!

**Comment by Eskyee** [comment]
Visual studio 2019 latest version

**Comment by Eskyee** [comment]
Lol 😆 I lived with this for 6 months... wow

**Comment by rockstardev** [comment]
This is known issue with Visual Studio on Mac... we can't really do much other than allow your Mac installation to overwrite everything it wants to overwrite and then we test that our other IDEs won't do any automatic changes.

Link that describes issue: https://developercommunity.visualstudio.com/content/problem/833426/launchsettingsjson-is-always-overwritten.html

**Comment by Eskyee** [comment]
I`m using Visual studio code, and these problems above, don't exist, 
only Visual Studio giving these bugs on a Mac, thanks Rockstar!!

**Comment by pavlenex** [comment]
Closing this after trying out Rider, it's a bug in Visual Studio as @rockstardev told, pretty much nothing we can do about it on our end.

**Comment by Eskyee** [comment]
so. I'm testing the.  fix/json-indent branch 
Modifying launchSettings.json to follow 2 space indent convention #1731

I find problems in my IDE, still !! Rockstar 
so I just deleted my BTCPay folder, and recloned BTCPay Server again fresh
tested the new fix/json-indent branch ..
problems in my fresh VS IDE, 
let me think, why this is happening, this is a clean fresh Mac.
and I will keep trying, 

I see my hidden files as well to check .vs folder etc etc
need some one. else with a Mac to try and reproduce our old bug.



<img width="1440" alt="Screenshot 2020-07-11 at 23 27 05" src="https://user-images.githubusercontent.com/30862925/87235031-6b0ecc80-c3cf-11ea-897f-b30e2764b749.png">

![Screenshot 2020-07-11 at 23 29 22](https://user-images.githubusercontent.com/30862925/87235033-6c3ff980-c3cf-11ea-9f52-3dcfbafcdff6.png)

![Screenshot 2020-07-11 at 23 29 34](https://user-images.githubusercontent.com/30862925/87235034-6cd89000-c3cf-11ea-979c-69b6b5de4c60.png)

<img width="924" alt="Screenshot 2020-07-11 at 23 30 56" src="https://user-images.githubusercontent.com/30862925/87235112-41a27080-c3d0-11ea-9332-d6f6561e9886.png">
<img width="1219" alt="Screenshot 2020-07-11 at 23 31 41" src="https://user-images.githubusercontent.com/30862925/87235114-42d39d80-c3d0-11ea-9126-597fbe73f69e.png">
<img width="924" alt="Screenshot 2020-07-11 at 23 31 50" src="https://user-images.githubusercontent.com/30862925/87235115-4404ca80-c3d0-11ea-8419-317e0e7ec39e.png">
<img width="1219" alt="Screenshot 2020-07-11 at 23 32 04" src="https://user-images.githubusercontent.com/30862925/87235116-449d6100-c3d0-11ea-9d0d-e5148b2dc424.png">
<img width="682" alt="Screenshot 2020-07-11 at 23 34 02" src="https://user-images.githubusercontent.com/30862925/87235117-45ce8e00-c3d0-11ea-82a9-c0f4d5632bcd.png">

**Comment by Eskyee** [comment]
@rockstardev  There things you can put in your .csproj file like <DockerDebuggeeArguments> that can affect how Docker starts up your container.

You can also add things like environmentVariables in launchSettings.json for the Docker configuration and those will get passed to the application but won't be global environment variables you can inspect in the running container.

The Dockerfile that gets generated has a bunch of named intermediate containers but it turns out you only need the one named base for the VS debugging to work.

There have been other issues (eg #62, #160) that have touched on some of this, but... it'd be nice if there was documentation covering the options available in launchSettings.json, .csproj files, and so on. It's really hard to figure this stuff out and ends up being a manual trek through .props and .targets files, decompilers on the libraries installed with VS, and slogging through issues and forums.
