### ISSUE TITLE
Errors in dev env on MacOS in bundleconfig.json bug

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver#1407]
**showing duplicates in visual studio**
left this here as a reminder !!.

bug only shows up in visual studio for Mac

this don't happen in visual code.

as describe in #1406 Mac bug

I have done a fresh format on my MacBook , to double check these bugs are not only in my machine!! , as Pav has reproduced.

![](https://user-images.githubusercontent.com/30862925/77256013-6cbb5580-6c63-11ea-8c3d-bed5fc1f733a.jpeg)

**Comment by pavlenex** [comment]
Thanks for the info,I'll close this one since it's closely tied to #1406 and those are now linked and cross-referenced.
