### ISSUE TITLE
Same OrderID has different invoiceID causing the same order to be duplicated

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1413]
Reporting this on behalf of the user. 

**Describe the problem/bug**
User reported their customer paid an invoice in WooCommerce, but the invoice did not mark as paid. Instead it was expired. After a bit of investigation, we've noticed that there's a duplicate `OrderID` in their BTCPay Serve Invoices, with two separate InvoideID's. I have no idea how this is possible but I've seen this one before.  I assume it has something to do with LND being down, causing 500, then things went downhill.

I don't think there's an easy way to troubleshoot.

**Your environment**
* Version of BTCPay Server:
* Deployment method: 
* Other relevant environment details:

**Logs (if applicable)**

### Expired Invoice Event Log
```
3/24/2020 1:45:30 PM | Creation of invoice starting
-- | --
3/24/2020 1:45:35 PM | BTC_USD: The rating rule is coinaverage(BTC_USD)
3/24/2020 1:45:35 PM | BTC_USD: The evaluated rating rule is 6724.868
3/24/2020 1:45:51 PM | BTC (Off-Chain): Payment method details creation took 15 seconds
3/24/2020 1:45:51 PM | BTC: Payment method unavailable (The lightning node did not reply in a timely manner)
3/24/2020 1:45:52 PM | BTC (On-Chain): Payment method details creation took 16 seconds
3/24/2020 1:45:55 PM | Saving invoice took 3 seconds
3/24/2020 1:45:56 PM | Invoice LeyVD2N8r9DGpCBG1Augz5 new event: invoice_created (1001)
3/24/2020 1:46:44 PM | IPN (1001 invoice_created) sent for invoice LeyVD2N8r9DGpCBG1Augz5
3/24/2020 2:00:30 PM | Invoice status is expired
3/24/2020 2:00:30 PM | Invoice LeyVD2N8r9DGpCBG1Augz5 new event: invoice_expired (1004)
3/24/2020 2:00:31 PM | Error while sending IPN (1004 invoice_expired): Unexpected return code: 500
3/24/2020 2:00:32 PM | Error while sending IPN (1004 invoice_expired): Unexpected return code: 500
3/24/2020 2:10:33 PM | Error while sending IPN (1004 invoice_expired): Unexpected return code: 500
3/24/2020 2:10:34 PM | Error while sending IPN (1004 invoice_expired): Unexpected return code: 500
3/24/2020 2:20:35 PM | Error while sending IPN (1004 invoice_expired): Unexpected return code: 500
3/24/2020 2:20:36 PM | Error while sending IPN (1004 invoice_expired): Unexpected return code: 500
3/24/2020 2:30:36 PM | Error while sending IPN (1004 invoice_expired): Unexpected return code: 500
3/24/2020 2:30:37 PM | Error while sending IPN (1004 invoice_expired): Unexpected return code: 500
```

### Paid Invoice Event Logs
```

Date | Message
-- | --
3/24/2020 1:47:09 PM | Creation of invoice starting
3/24/2020 1:47:09 PM | BTC_USD: The rating rule is coinaverage(BTC_USD)
3/24/2020 1:47:09 PM | BTC_USD: The evaluated rating rule is 6723.656
3/24/2020 1:47:13 PM | BTC (On-Chain): Payment method details creation took 3 seconds
3/24/2020 1:47:13 PM | BTC (Off-Chain): Payment method details creation took 4 seconds
3/24/2020 1:47:14 PM | Saving invoice took 466 milliseconds
3/24/2020 1:47:14 PM | Invoice 8MHr2LoRrBP7P3G3T87d5n new event: invoice_created (1001)
3/24/2020 1:47:17 PM | IPN (1001 invoice_created) sent for invoice 8MHr2LoRrBP7P3G3T87d5n
3/24/2020 1:48:08 PM | Invoice 8MHr2LoRrBP7P3G3T87d5n new event: invoice_receivedPayment (1002)
3/24/2020 1:48:08 PM | Invoice status is paid
3/24/2020 1:48:08 PM | Invoice 8MHr2LoRrBP7P3G3T87d5n new event: invoice_paidInFull (1003)
3/24/2020 1:48:15 PM | IPN (1002 invoice_receivedPayment) sent for invoice 8MHr2LoRrBP7P3G3T87d5n
3/24/2020 1:48:16 PM | IPN (1003 invoice_paidInFull) sent for invoice 8MHr2LoRrBP7P3G3T87d5n
3/24/2020 1:48:17 PM | IPN (1003 invoice_paidInFull) sent for invoice 8MHr2LoRrBP7P3G3T87d5n
3/24/2020 2:11:30 PM | Invoice status is confirmed
3/24/2020 2:11:30 PM | Invoice 8MHr2LoRrBP7P3G3T87d5n new event: invoice_confirmed (1005)
3/24/2020 2:11:33 PM | IPN (1005 invoice_confirmed) sent for invoice 8MHr2LoRrBP7P3G3T87d5n
3/24/2020 2:11:34 PM | IPN (1005 invoice_confirmed) sent for invoice 8MHr2LoRrBP7P3G3T87d5n
3/24/2020 3:20:26 PM | Invoice status is complete
3/24/2020 3:20:26 PM | Invoice 8MHr2LoRrBP7P3G3T87d5n new event: invoice_completed (1006)
3/24/2020 3:20:27 PM | Invoice 8MHr2LoRrBP7P3G3T87d5n is not monitored anymore.
3/24/2020 3:20:30 PM | IPN (1006 invoice_completed) sent for invoice 8MHr2LoRrBP7P3G3T87d5n
3/24/2020 3:20:32 PM | IPN (1006 invoice_completed) sent for invoice 8MHr2LoRrBP7P3G3T87d5n
```

Customer reported this:
> On my end I just saw one invoice, and things seemed to go fine when I paid it."

For merchant:
> in Woo the status still shows at "pending payment". The bitcoin payment went through an hour ago.

This issue is **Not** related to Woo Order statuses or any Woo issue. WooCommerce was confused because we duped the order in BTCPay itself and reacted normally.

**Screenshots/Links**
<img width="697" alt="Screen Shot 2020-03-24 at 3 36 50 PM" src="https://user-images.githubusercontent.com/36959754/77485686-0fbfcb00-6e2e-11ea-9003-1ac736262f4c.png">

**Additional context**
I saw this dupe OrderID issue a few times. I was never able to troubleshoot it properly, so leaving it here in case someone can figure it out. It's nasty bug in a way, because a merchant is unaware of a paid order, unless customer contacts or he double-checks.

I tried replicating the issue with a merchant , no luck, we've looked through NBX and other logs, noting odd there.

**Comment by Kukks** [comment]
`3/24/2020 1:45:35 PM | BTC_USD: The rating rule is coinaverage(BTC_USD)`
what? Coin average was removed from btcpay months ago

**Comment by NicolasDorier** [comment]
Also, this is on purpose. There is nothing to prevent an orderId to be unique.

**Comment by pavlenex** [comment]
@NicolasDorier  Well this comes from our woo-plugin no reason why it should behave like that. Perhaps this should be moved to woo-repo then?

**Comment by NicolasDorier** [comment]
No, there is a reason for that as well. It happen if you do one order, click pay, then the invoice expires, and you reclick on pay

**Comment by pavlenex** [comment]
I don't think that's possible really in WooCommerce. It should create a new orderid, anyway, reported this on behalf of the user, I'll close until someone else reports it, though it happened a few times to me and was really weird(long time ago though)

**Comment by pavlenex** [comment]
@astupidmouse had a good observation on why this happens in woocommerce, leaving it in case someone faces the same issue in the future.

> Thats a woocommerce issue, customer is likely pressing back button and redoing order
