### ISSUE TITLE
Cannot clone a payment request

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#1414]
Clicking on Clone on the payment request is giving error 404. Only in the edit view.

**Comment by pavlenex** [comment]
For clarity, it happens when you create a payment request, click save and try to clone it from that same page, does not happen on Payment Request page for me.
![Screenshot 2020-03-25 at 16 30 02](https://user-images.githubusercontent.com/36959754/77554178-05e1aa80-6eb6-11ea-804c-46bd7c0f6082.png)
