### ISSUE TITLE
Documentation or help adding Monero to a store

### ISSUE THREAD

**Issue by thestick613** [btcpayserver/btcpayserver#1419]
I would like to add monero to my btcpayserver instance. I already have a monerod instance with rpc access, but i don't know what to do next.

> ./run.sh --help

 doesn't show any monero support. I've looked over #1044, and it seems i can only run it via a docker image.

**Comment by Kukks** [comment]
You'll need to port over the settings from https://github.com/btcpayserver/btcpayserver-docker/blob/master/docker-compose-generator/docker-fragments/monero.yml  
It should be too hard. If you're not technical enough to do this, I'd advise you against doing a manual install in general.

We don't handle documenting non bitcoin specific settings( unless they are almost identical).

**Comment by thestick613** [comment]
Found this after a while: https://docs.btcpayserver.org/FAQ/FAQ-Altcoin/
