### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by AryanJ-NYC** [btcpayserver/btcpayserver#1421]
**Is your feature request related to a problem? Please describe.**
I cannot find documentation on the BTCPay server store/invoice/etc. API.

Are there docs for the BTCPay server API? For example, I understand we make a POST request to /api/v1/invoices to make a new invoice...but I can't seem to find documentation on the API for that endpoint.

These are the only docs I can find: https://docs.btcpayserver.org/

And they aren't very technical about the endpoints available on BTCPay server

**Describe the solution you'd like**
A link to the API documentation on the general documentation site.

**Comment by Kukks** [comment]
Replied on telegram but here it is again:

That endpoint is not documented because we try to discourage its use as an
api( since there is no auth protection on it) . You should use the bitpay
compatible api we have instead for creating invoices if possible until we
roll out the new api.

That said, if you look at the pay button generator page, there is some
documentation there for it.

The new api being built has docs available at `/docs`  of your install

**Comment by pavlenex** [comment]
As Kukks said 

> The new api being built has docs available at `/docs`  of your install

The legacy BitPay compatible API is the same as https://bitpay.com/api, therefore closing this.

**Comment by AryanJ-NYC** [comment]
Hey @pavlenex. Thanks for the response.

In The BitPay API, there is no concept of stores. How then do we go about creating an invoice associated with a specific store?

**Comment by pavlenex** [comment]
Check this out https://docs.btcpayserver.org/integrations/customintegration

**Comment by Kukks** [comment]
When you pair a bitpay client with btcpay, you have to choose the store.

**Comment by AryanJ-NYC** [comment]
I ended up using https://github.com/btcpayserver/node-btcpay. Worked like a charm.

**Comment by softyengineer** [comment]
> I ended up using https://github.com/btcpayserver/node-btcpay. Worked like a charm.

Tried this but when running " BTCPAY_URL=https://mydomain.com/ BTCPAY_KEY=... BTCPAY_PAIRCODE=... node -e "const btcpay' .... " (with the leading space in front) I get the error:
.../elliptic/lib/elliptic/curve/short.js:415
  return this.x.fromRed();
                ^

TypeError: Cannot read property 'fromRed' of null
...

I've tried rebuilding the node_modules folder, putting the code into a file and running it. It doesn't matter my values of BTCPAY_URL or BTCPAY_PAIRCODE either so maybe a more general problem.
