### ISSUE TITLE
Allow custom invoice data to be passed to the /api/v1/invoices endpoint

### ISSUE THREAD

**Issue by AryanJ-NYC** [btcpayserver/btcpayserver#1422]
**Is your feature request related to a problem? Please describe.**
As a user, I should be able to add the buyer name, buyer email, item description, etc. to invoices added via the /api/v1/invoices endpoint

**Describe the solution you'd like**
I should be able to pass buyer information in the form of `buyer[name]` (or `BuyerName`, like in [InvoiceController.UI.cs](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Controllers/InvoiceController.UI.cs#L545)) `buyer[email]` (or `BuyerEmail`), etc. to the /api/v1/invoices endpoint.

The fields in  [InvoiceController.API.cs](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Controllers/InvoiceController.API.cs#L30) are a good example of fields that can extend the `/api/v1/invoices` endpoint.

**Comment by NicolasDorier** [comment]
There is no /api/v1/invoices right now

**Comment by AryanJ-NYC** [comment]
Isn't that endpoint exactly what the PayButton hits?

**Comment by Kukks** [comment]
https://github.com/btcpayserver/btcpayserver/issues/1421
