### ISSUE TITLE
Cannot remove stores

### ISSUE THREAD

**Issue by bitcoinbrisbane** [btcpayserver/btcpayserver#1424]
**Describe the problem/bug**
Store not being removed after click the remove link on `/stores`.

**Your environment**
Ubuntu 18

**To Reproduce**

1. Navigate to stores
2. Click the RHS Remove Action
3. Confirm the Delete
4. When returned to the store list, the store still appears.  Refreshing the page still shows the store.

**Expected behavior**
Store should be removed

**Actual behavior**
Store remains

** Other **
Should the word "Remove" be changed to "Delete" to match the confirm box?  Or vis versa.

**Comment by bitcoinbrisbane** [comment]
I did a 
- git pull
- ./build.sh
- ./run.sh

And they seem to have gone

**Comment by bitcoinbrisbane** [comment]
Still having the same issue actually.

**Comment by Kukks** [comment]
If you are running on sqlite, there is a limitation which does not allow you to remove stores.

Sqlite is highly discouraged for btcpay, we don't even use it for our development environment

**Comment by bitcoinbrisbane** [comment]
Ok, I’ve been looking for a reason to role out postgres
