### ISSUE TITLE
Login page coloring re-design

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1428]
After our invoice re-design, we're re-designing a login page which was re-designed recently. This means we're only doing a minor coloring changes to make design consistent with the invoice and other upcoming stuff, such as directory and website.

There are some tweaks that we can do with the suggested design, so the screenshot is by no means finally proposed version, just a direction for coloring. 

Figma files available [here](https://www.figma.com/file/C7Xyq0FlxgFW8vaBr8ht1z/BTCPAY?node-id=205%3A372), design guidelines available [here](https://www.figma.com/file/C7Xyq0FlxgFW8vaBr8ht1z/BTCPAY?node-id=0%3A1).

I would also change this intro text that we have, since it's, well annoying. I'd put what we have on the website for now. 

`BTCPay Server is a self-hosted, open-source cryptocurrency payment processor. It's secure, private, censorship-resistant and free. `

![Screenshot 2020-03-31 at 17 18 50](https://user-images.githubusercontent.com/36959754/78043502-b565c380-7373-11ea-9bd0-2e90b7acb900.png)

**Comment by rockstardev** [comment]
:+1:

**Comment by pavlenex** [comment]
This has been done as a part of #1447
