### ISSUE TITLE
Default theme coloring re-design

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1429]
After redesign of the invoice re-design and login page (#1428) it would be good if we can make colors consistent in our default theme, without doing anything fancy but color changes, to avoid breaking changes for users using default theme.

We can either leave classic theme as a legacy and keep new one as default, that's something that we should discuss.

Unfortunately, we do not have mockups available for it yet, but it should be done like @dennisreimann did for the #1137 Casa theme. 

Design guidelines are available [here](https://www.figma.com/file/C7Xyq0FlxgFW8vaBr8ht1z/BTCPAY?node-id=0%3A1), and should be consistent with what we have [here](https://www.figma.com/file/C7Xyq0FlxgFW8vaBr8ht1z/BTCPAY?node-id=25%3A0). 

If time allows of course a dark theme on top would be great, if not we can do that in the future.

**Comment by dennisreimann** [comment]
Here's what I've come up with so far, oriented on the color scheme defined in the Figma docs.

The light/dark theme depends on the system setting, defining the [CSS `prefers-color-scheme` media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), which is [supported by modern browsers](https://caniuse.com/#feat=prefers-color-scheme). Older browsers fall back to light as the default. I like this approach as I find it to be elegant and orienting on the users general preferences, but it'd also be possible to split the two themes and let the user choose explicitely.

Feedback welcome – I'll tweak things accordingly.

## Light

<img width="1243" alt="light-login" src="https://user-images.githubusercontent.com/886/78179693-ecb29e00-7461-11ea-88eb-8cdc48935763.png">

<img width="1271" alt="light-themes" src="https://user-images.githubusercontent.com/886/78179702-ef14f800-7461-11ea-908d-b76882542552.png">

<img width="1213" alt="light-home" src="https://user-images.githubusercontent.com/886/78179710-f20fe880-7461-11ea-8060-0816571b4cd7.png">


## Dark

<img width="1262" alt="dark-login" src="https://user-images.githubusercontent.com/886/78179727-fb00ba00-7461-11ea-926a-ec19503fd797.png">

<img width="1263" alt="dark-themes" src="https://user-images.githubusercontent.com/886/78179734-fe944100-7461-11ea-9ef6-6d89e0a37966.png">

<img width="1259" alt="dark-home" src="https://user-images.githubusercontent.com/886/78179748-02c05e80-7462-11ea-8e36-a0f1806584c2.png">

**Comment by pavlenex** [comment]
@dennisreimann some quick feedback from me:
- Login pages look great on both 
- Color on the light theme seem off compared to what we had on Figma, for example the header & sidebar (server settings) color is off
- Main page of the light theme - colors are not consitent with desing guidelines 
- Main page of the dark theme - looks like a black and white photo, not really consistent with what we have on main website demo
