### ISSUE TITLE
Apostrophe in store name not displayed correctly when invoice expires

### ISSUE THREAD

**Issue by oparex** [btcpayserver/btcpayserver#1438]
**Describe the problem/bug**
The apostrophe sign (which is part of store name) is shown as html code &#39; in invoice expired screen.

**Your environment**
* Version of BTCPay Server: v1.0.3.164
* Deployment method: manual

**To Reproduce**
1. Create a store with an apostrophe in the name ("someone's store")
2. Create a POS for the store
3. Go to POS, add something to the cart, go to payment
4. Let the invoice expire

**Expected behavior**
Expect a new screen with invoice expired text with the full store name in several places.

**Actual behavior**
New screen that notifies the user of expired invoice appears with text that shows the apostrophe in store name as html code &#39;

**Additional context**
The store name is displayed correctly in pay invoice screen (the screen before invoice expired screen)

<img width="547" alt="invoiceexpiredbtcpay" src="https://user-images.githubusercontent.com/3031967/78543482-ff79f980-77f8-11ea-849f-8555161f39ac.png">

**Comment by NicolasDorier** [comment]
Your version is not v1.0.3.164, this new checkout is not released yet, you are on the master branch.

**Comment by NicolasDorier** [comment]
ping @Kukks , I guess this is a vue issue.

**Comment by Kukks** [comment]
Yeah it was a small thing, fixed now
