### ISSUE TITLE
Mnemonic seed not visible when generating a hot wallet

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1456]
**Describe the problem/bug**

**EDIT: This happens on every theme not just dark theme as I originally reported.**

When someone uses dark theme and tries to generate a hot wallet, the mnemonic is not that visible and it's hard for user to even notice there's a seed there, which can be quite dangerous.

**To Reproduce**
1. Go to Store > Derivation Scheme > Modify
2. Click on `Import from` ...`new/existing seed`
3. Enable hot wallet 
4. Generate a wallet.
5. See error

**Expected behavior**
User should clearly see, possibly emphasized in danger color his seed and should be aware that they need to back it up.

**Actual behavior**\
The seed is barely visible

**Screenshots/Links**
![seed](https://user-images.githubusercontent.com/36959754/79071679-4ece9700-7cdd-11ea-88fc-96e94efcc995.PNG)

![mnemonic](https://user-images.githubusercontent.com/36959754/79071641-20e95280-7cdd-11ea-8cb0-d6f575614874.PNG)

Happens on light theme as well

![light](https://user-images.githubusercontent.com/36959754/79072635-652b2180-7ce2-11ea-857e-f5928ad7d946.PNG)

**Comment by bolatovumar** [comment]
I will take a look now.
