### ISSUE TITLE
Mobile menu icon is not shown on light theme

### ISSUE THREAD

**Issue by bolatovumar** [btcpayserver/btcpayserver#1458]
**Describe the problem/bug**
Mobile menu icon is not shown on light theme. Also, notice how the onion icon is shifted weirdly to the right.

**Your environment**
* Version of BTCPay Server: v1.0.3.164 

**Screenshots/Links**
![Screen Shot 2020-04-12 at 10 45 24 AM](https://user-images.githubusercontent.com/1934678/79076768-8cb5c600-7cb1-11ea-9578-971e06046147.png)

**Comment by Kukks** [comment]
fixed by #1466
