### ISSUE TITLE
Can't read code elements in the new theme

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#1463]
@dennisreimann can we maybe add a background like to code elements?
![image](https://user-images.githubusercontent.com/3020646/79092741-ca3b5180-7d8c-11ea-92b0-8f294f7c277e.png)

Because right now here is how it looks like

![image](https://user-images.githubusercontent.com/3020646/79092717-b132a080-7d8c-11ea-8e3d-175b14c7e1fb.png)

**Comment by dennisreimann** [comment]
Umar fixed it with #1457 😀

**Comment by pavlenex** [comment]
@NicolasDorier Is the issue related specifically to the hot wallet or you'd like it for other stuff as well? If for hot-wallet only, then this is a duplicate of #1456

**Comment by NicolasDorier** [comment]
dups https://github.com/btcpayserver/btcpayserver/issues/1456
