### ISSUE TITLE
Make it obvious that Payjoin is enabled

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1476]
**Describe the problem/bug**
We've noticed that people are confused and don't know if they enabled p2ep. We should somehow make it clear through the UI that it's enabled and working. Possibly this can be done when user enables ticks `Enable Payjoin/P2EP` we can give `Payjoin/P2EP successfully enabled` when users saves the store settings. Related to #1474

**Comment by Eskyee** [comment]
I had the same problem

**Comment by pavlenex** [comment]
Haven't noticed any complaints afterwards, so closing this one until more people face the problem. I assume that #1474 also helped.
