### ISSUE TITLE
Show fiat value on Checkout page

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#148]
https://twitter.com/riggsfinn/status/990922094853611521

**Comment by rockstardev** [comment]
Here is first iteration - looking forward to crew's feedback:

![invoice with fiat 1 btc](https://user-images.githubusercontent.com/5191402/39851004-0fd52e0c-53da-11e8-8ab3-c92da95ad641.png)

![invoice with fiat 2 ltc](https://user-images.githubusercontent.com/5191402/39851005-0fe2f0fa-53da-11e8-893a-5e55031a87cf.png)

Like to commit: https://github.com/rockstardev/btcpayserver/commit/be1128a886aaf8ff102a7ca83e1151dbe56fa485

**Comment by NicolasDorier** [comment]
let's commit this!

**Comment by NicolasDorier** [comment]
For reference, before this change:

![image](https://user-images.githubusercontent.com/3020646/39909350-639c2bea-552d-11e8-9137-25af399f285a.png)

**Comment by rockstardev** [comment]
And here is how it looks when its in item details: 

![fiat](https://user-images.githubusercontent.com/5191402/39909816-0b715332-54ba-11e8-9393-9cbb4d040db5.png)

I'm also curious what would be best term in item details... Fiat Total is basically - "Order Amount + Network Fee in Fiat"... but that one would be mouthful ;).

Looking forward to comments

**Comment by hubiktomas** [comment]
I think that the original version where there was total amount and fiat total under it with all the details in the lower part was better.

**Comment by hubiktomas** [comment]
Also can there be more than 1 transaction? Is it necessary to include "1 transaction x " in the Network Cost?

**Comment by NicolasDorier** [comment]
yes there can be more transaction. If you pay an invoice with 2 transactoin you need to pay two time the network cost.

**Comment by hubiktomas** [comment]
So if I pay lower than required amount while having this option to include network cost in the total enabled, the total will be increased after this first payment?

**Comment by Eskyee** [comment]
good job, rockstardev I like it, 
total amount and fiat total under it with all the details in the lower part looks nice. I agree

**Comment by NicolasDorier** [comment]
@hubiktomas yes

**Comment by hubiktomas** [comment]
Ok, then I think that the original proposal with total amount and fiat total under it with all the details in the lower part was the best one. Thanks for clarification.

**Comment by astupidmoose** [comment]
I prefer this:
https://github.com/btcpayserver/btcpayserver/issues/148#issuecomment-388272777

We typically refund in BTC if needed, not the Fiat amount so it's not important to have the fiat listed on the invoice.

**Comment by hubiktomas** [comment]
@astupidmoose I think that the amount in fiat is important just for cross check with the original order for the customer. I would say that more important than exchange rate.

**Comment by rockstardev** [comment]
@hubiktomas the core problem for me is that fiat value would need to show:

invoice amount + network fee

I think most merchants want is to show fiat value as they enter it when creating invoice. I've been thinking about showing just invoice amount instead of rate. But that is then not "correct".

I'm thinking to maybe close this by doing "Order Amount in Fiat" and display price from Invoice instead of what is shown on https://github.com/btcpayserver/btcpayserver/issues/148#issuecomment-388272777 as "Fiat Total".

Doing this would likely satisfy both everyone involved.

**Comment by astupidmoose** [comment]
I guess this comes down to preferences set. 

To us, we deal in BTC. We refund in BTC at the amount of BTC you paid. FIAT is really only used for calculations of comparison, so it's not important to us. My customers care more about the current exchange rate. 

We also do not charge the network fee, this again this is not an issue for us.

**Comment by hubiktomas** [comment]
Actually we probably should not call it Order Amount in Fiat as the source currency could be crypto as well. So something like Order Amount in Original Currency? This one is probably too long.

**Comment by NicolasDorier** [comment]
Another approach possible:

`In 1 BTC = XXX (USD)`, makes BTC and USD clickable link. When clicked it will show all the prices in the selected currency.

Advantage of it: No cluster in the payments details, and no new label to translate.

**Comment by rockstardev** [comment]
Hey everyone - thanks for all the input - I think final solution wouldn't be nearly as good as I see it now without all the feedback. I'm closing the issue to move discussion toward PR - am posting final images along with commits there so that we can finally move toward closing this ;)

Link -> #170
