### ISSUE TITLE
[Feature Request] Option to include private route hints in the invoice

### ISSUE THREAD

**Issue by openoms** [btcpayserver/btcpayserver#1480]
**Describe the problem/bug**
When BTCpay Server generates and invoice for a node with private channels, there are no route hints added so the payment cannot be routed.

**Your environment**
* Version of BTCPay Server: 1.0.4.0
* Deployment method: manual deployment on a RaspiBlitz
* Other relevant environment details: RaspiBlitz 1.4 with LND 0.9.0

**Logs (if applicable)**
Test invoicegenerated by BTCpay  (redacted) :
```
lncli decodepayreq lnbcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
{
    "destination": "xxxxxxxxxxxxxxxxxxxxxxxx",
    "payment_hash": "xxxxxxxxxxxxxxxxxxxx",
    "num_satoshis": "13844",
    "timestamp": "xxxxxxxxxx",
    "expiry": "899",
    "description": "Paid to test (Order ID: )",
    "description_hash": "",
    "fallback_addr": "",
    "cltv_expiry": "40",
    "route_hints": [
    ],
    "payment_addr": "xxxxxxxxxxxxxxxxxx",
    "num_msat": "13844000",
    "features": {
        "9": {
            "name": "tlv-onion",
            "is_required": false,
            "is_known": true
        },
        "15": {
            "name": "payment-addr",
            "is_required": false,
            "is_known": true
        },
        "17": {
            "name": "multi-path-payments",
            "is_required": false,
            "is_known": true
        }
    }
}
```

Invoice created in the command line with `lncli addinvoice 1` (redacted):
```
$ lncli decodepayreq xxxxxxxxxxxxxxxxxxxxxxxxxxx
{
    "destination": "xxxxxxxxxxxxxx",
    "payment_hash": "xxxxxxxxxxxxxx",
    "num_satoshis": "1",
    "timestamp": "xxxxxxxxxx",
    "expiry": "3600",
    "description": "",
    "description_hash": "",
    "fallback_addr": "",
    "cltv_expiry": "40",
    "route_hints": [
        {
            "hop_hints": [
                {
                    "node_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    "chan_id": "xxxxxxxxxxxx",
                    "fee_base_msat": 1000,
                    "fee_proportional_millionths": 1,
                    "cltv_expiry_delta": 40
                }
            ]
        }
    ],
    "payment_addr": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "num_msat": "1000",
    "features": {
        "9": {
            "name": "tlv-onion",
            "is_required": false,
            "is_known": true
        },
        "15": {
            "name": "payment-addr",
            "is_required": false,
            "is_known": true
        },
        "17": {
            "name": "multi-path-payments",
            "is_required": false,
            "is_known": true
        }
    }
}

```

**To Reproduce**
Generate invoice on a node with private channels only .

**Expected behavior**
Being able to pay.

**Actual behavior**
Failed to send payment: unable to find path to the destination.

**Screenshots/Links**
REST API format of route hints: 
https://api.lightning.community/rest/index.html#routehint

**Additional context**
It is a good privacy feature to run a lightning node with private channels only. In that case the pubkey and channels are only advertised to the payer and not publicly.

**Comment by Kukks** [comment]
How do we need to generate it differently?

**Comment by openoms** [comment]
> How do we need to generate it differently?

Need to allow / add route hints for private channels.
lncli does it automatically, not sure if it would be opt-in with REST.

Here is the relevant link form the lnd API: https://api.lightning.community/rest/index.html#routehint

**Comment by Kukks** [comment]
I don't think this needs to be done on the invoice generation level, more of a node config?

**Comment by openoms** [comment]
> I don't think this needs to be done on the invoice generation level, more of a node config?

`lncli addinvoice` has the `--private`  option to do this which seems to be on by default.
https://api.lightning.community/?shell#addinvoice

This is what should be used in REST:
https://api.lightning.community/rest/index.html?shell#v1-invoices
with the `"private":<boolean>` set to `true`

**Comment by openoms** [comment]
This might be some help too: https://github.com/lightningnetwork/lnd/issues/3971
I am not sure if the `route hints` would need to be looked up from `listchannels`. Just looks too complicated when all there is is one private channel.

**Comment by NicolasDorier** [comment]
The API is one thing, the second part of the story is: what ux to propose to the user to configure that. Which textbox in which page.

**Comment by openoms** [comment]
I could imagine a checkbox saying:
- [ ] Add hop hints for private channels to the lightning invoice

added to the  `Manage store: Checkout experience` page
where there are similar settings are set already
![image](https://user-images.githubusercontent.com/43343391/80351680-a981fa00-886a-11ea-8c72-3a1fec2b9f0c.png)

**Comment by NicolasDorier** [comment]
IMHO this is a shortcoming in the API of lnd. (maybe same in other implementation)

When a user pay an invoice he does not think about "Route hint", neither the API should.  So this should be a configuration matter rather than a parameter in the send api call.

**Comment by NicolasDorier** [comment]
"Add hop hints for private channels to the lightning invoice" and where are those private channels set up?

**Comment by openoms** [comment]
@NicolasDorier just to make this clear the private channels are the channels of the node creating the invoice (connected to the BTCPayServer in this case)
If it has only private channels a payer from more than a direct channel away would not know how to reach this node.

Therefore the hop hints need to be included in the invoice so the payer knows where to pay (pubkey) and how to get there (hop hints).

**Comment by pavlenex** [comment]
Isn't this something that's better added in the UI of external apps for LN in BTCPay such as RTL or Thunderbolt?

**Comment by openoms** [comment]
It is completely understandable if fixing this is not a priority, but it means that in case of private channel(s) only the invoices created by BTCPayServer are not usable.
They can be only paid by the peers with a direct (in this case private) channels.
Does attempting to generate an invoice without channels lead to an error? This case should show similar or need to include the hop hints.

**Comment by NicolasDorier** [comment]
> added to the Manage store: Checkout experience page
where there are similar settings are set already

This step in the UX is not enough. There is some stuff btcpay need to know on top of this. So please details how they should be input by the user.

**Comment by openoms** [comment]
I think it is a staightforward question that the user either wants to expose the private channels in the in the invoice or not.

What other info BTCpayserver would need?

**Comment by bolatovumar** [comment]
This is what Zap wallet shows when you are creating a Lightning invoice. Notice the "Include routing hints" toggle. There is also a tooltip element that explains why you would want to enable it.

![Capture](https://user-images.githubusercontent.com/1934678/81507564-240f3880-92b3-11ea-9a3c-8f3e732bac1f.PNG)

**Comment by NicolasDorier** [comment]
Is there any reason to not turn that on?

**Comment by NicolasDorier** [comment]
> What other info BTCpayserver would need?

Configuring what are the routing hints.

**Comment by bolatovumar** [comment]
@NicolasDorier I think there might be an issue that if you always include routing hints, intermediate nodes might learn about your private channels. I'm not 100% sure about this though.

**Comment by openoms** [comment]
@NicolasDorier the routing hints are provided by lnd if the "private":<boolean> is set to true.

@bolatovumar exactly the routing hints are exposing the private channels in the invoice and with that the funding UTXO.

Typically one would not want the private channels to be exposed by default if those are not the only ones, but only been opened for rebalancing with a routing node in a private way.
If the node has private channel(s) only the only way to accept a payment from a non-directly connected node is to include the route hints in the invoice.

The point of running with private channels only would be mainly if the node does not want to be involved in routing payments in order to:
  *  avoid losing incoming capacity on cheap channels
  *  avoid the cost of rebalancing
  * stop the potential surveillance of payment amounts, node relationships and wormhole attack. (These are active attacks on LN described in this presentation and paper for example: https://www.youtube.com/watch?v=8lUTbfO94mM&feature=youtu.be)

**Comment by rockstardev** [comment]
I'm on this.
