### ISSUE TITLE
Crowdfund App button missing , plus contribute comes up with a blank.

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver#1481]
**Describe the problem/bug**

crowdfunding app
BTCPay latest version v1.0.4.1

since updating last night to v1.0.4.1 I can see that the app button is missing at bottom of screen
and when you try too contribute, no checkout window, just comes up blank

it seem like the latest btcpay update has broken things. I will digg about to see what else has broken since this update from v1.0.4.0.

not sure how this past the testing phase.

<img width="1457" alt="Screenshot 2020-04-19 at 06 24 45" src="https://user-images.githubusercontent.com/30862925/79680336-9043d280-8206-11ea-886f-5c3f212d2c66.png">

**Comment by Eskyee** [comment]
<img width="1440" alt="Screenshot 2020-04-19 at 06 18 07" src="https://user-images.githubusercontent.com/30862925/79680504-4a880980-8208-11ea-8eb6-25307c699747.png">


as you can see its missing.

**Comment by britttttk** [comment]
@Eskyee 
> I can see that the app button is missing

Do you mean the "View App" button is missing?

**Comment by Eskyee** [comment]
Yes missing

**Comment by Eskyee** [comment]
Can you see it here ??  Since the latest update has broken things, and view app button is missing

**Comment by Eskyee** [comment]
<img width="1329" alt="Screenshot 2020-04-19 at 06 45 46" src="https://user-images.githubusercontent.com/30862925/79680616-78ba1900-8209-11ea-82ce-399073fc6388.png">

App View missing here as well.

**Comment by Eskyee** [comment]
I will now digg about to see what else has changed since last update.

**Comment by britttttk** [comment]
@Eskyee view app button is hidden when there are missing required properties. After you save the *required fields you can see the view app button.

**Comment by britttttk** [comment]
![image](https://user-images.githubusercontent.com/39231115/79681077-1bf03b80-81d4-11ea-83d4-409f0704a290.png)

**Comment by Eskyee** [comment]
ok thanks to bk I solved this problem
