### ISSUE TITLE
scrolling around the website via mobile, it seems a bit shaky, with strange actions

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver#1482]
**Describe the problem/bug**

I have noticed this morning browsing the BTCPay website via iPhone Max S 
seems a bit shaky, with strange actions doesn't feel smooth,
 im not sure why this is happening. but it doesn't feel nice scrolling now.

**Your environment**

Version of BTCPay Server: 1.0.4.1
Deployment method: docker

**Comment by Eskyee** [comment]
browsing the BTCPay website via MacBook Air does the same thing, shaky and not nice.
scoll to the middle and watch the page move.. ??? strange action

**Comment by pavlenex** [comment]
You need to make issue more clear. What website? On your server? Also for such issues it's best to record a video or provide more info, "feels shaky" is not something we can troubleshoot.

**Comment by Eskyee** [comment]
sorry for not being clear,  BTCPay Jungle and also in my dev environment. the scrolling action aint smooth at all.

**Comment by Eskyee** [comment]
I will check on another mobile device ;) to see if I can reproduce

**Comment by Eskyee** [comment]
I can reproduce the same problem on a SE iPhone , which use safari , 
i will try in another browser to see if this is a safari bug

**Comment by Eskyee** [comment]
when scrolling up and down, it just flicks the page, doesn't look or feel nice.

**Comment by pavlenex** [comment]
I've created account on btcpayjungle and tested on iPhone 8 Safari and don't see the issue you're mentioning, I still don't understand what you mean quite honestly.

**Comment by Eskyee** [comment]
Read up about this please Pav, I am not imagining yet, scrolling don’t feel that smooth.. https://css-tricks.com/almanac/properties/s/scroll-behavior/

**Comment by Eskyee** [comment]
Push the screen up and down, and then you see it flick . I will try make a video later. Showing this

**Comment by Eskyee** [comment]
Ok just tested it, and yes it’s seems smooth again... I will keep a eye on this next few days, if I can’t reproduce, I will close this issue!! Cheers for trying.. pav

**Comment by Eskyee** [comment]
thinking I had this problem on iPhone, was a low batt thing, as I can't reproduce any more this stickiness with the scrolling.
