### ISSUE TITLE
Dark Theme Contrast Issue - Payment Requests

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#1488]
**Describe the problem/bug**
The default theme used in payment requests is hard to read when using overall Dark Theme mode.

**Your environment**
* Version of BTCPay Server: BTCPayServer v1.0.4.1
* Deployment method: Debug Regtest

**To Reproduce**
1. Create Payment Request (looks ok)
2. Click Pay now (can't see the invoice and transaction info text very well)
3. Payments completed are also hard to read (see photo below)

**Expected behavior**
There is more contrast on the payment text in payment requests when using Dark Theme.

**Actual behavior**
Text is very hard to read. 

**Screenshots/Links**
![image](https://user-images.githubusercontent.com/39231115/79699451-f2272b00-824c-11ea-8f6e-a78ae797a503.png)

**Additional context**
No payment request functionality issues, just viewing payment/transaction text.

**Comment by NicolasDorier** [comment]
ping @dennisreimann
