### ISSUE TITLE
L-CAD icon is not loading

### ISSUE THREAD

**Issue by dpet** [btcpayserver/btcpayserver#1491]
**Describe the problem/bug**

L-CAD icon is not loading.

https://github.com/btcpayserver/btcpayserver/blob/841cf61c92f7322db657e13378d989cc021ab019/BTCPayServer.Common/Altcoins/Liquid/BTCPayNetworkProvider.LiquidAssets.cs#L71

Asset icon filename is LCAD.png

CryptoImagePath = "imlegacy/lcad.png",
should be
CryptoImagePath = "imlegacy/LCAD.png",

**Your environment**
* Version of BTCPay Server:
* Deployment method: docker

:)

**Comment by pavlenex** [comment]
ping @FrancisPouliot ^
