### ISSUE TITLE
Users that are not admin cannot create seed/hot wallet for Payjoin

### ISSUE THREAD

**Issue by bitcoinheiro** [btcpayserver/btcpayserver#1494]
**Describe the problem/bug**
Users that are not admin cannot create seed/hot wallet for Payjoin

**Your environment**
* Version of BTCPay Server: 1.0.4.0
* Deployment method: VPS (but also the kukks site: https://payjoin.kukks.org/)
* Other relevant environment details:

**Logs (if applicable)**
Not applicable

**Setup Parameters**
NA

**To Reproduce**
1. Go to 'Modify BTC Derivation Scheme'
2. Click on 'Import from...'
3. Scroll down to '...a new existing seed'
4. Create wallet with passphrase, segwit, wallet 0, check HOT WALLET and click Generate
5. See error:
This page isn’t working
payjoin.kukks.org is currently unable to handle this request.
HTTP ERROR 500

**Expected behavior**
Expected to have a hot wallet generated. Reproduced the same above with out personal server pay.bitcoinheiros.com and had same result.

**Actual behavior**
HTTP ERROR 500

**Screenshots/Links**
NA

**Additional context**
NA

**Comment by NicolasDorier** [comment]
ping @Kukks

**Comment by pavlenex** [comment]
You need to specifically grant a permission in Server Settings for that, that said, what we need to do here is provide a better message when the option is disabled in Server Settings.

![Screenshot 2020-04-22 at 13 17 12](https://user-images.githubusercontent.com/36959754/79975832-e2515600-849b-11ea-9ac1-6a45b4c4ac0e.png)

**Comment by Kukks** [comment]
I just tried on the demo site (payjoin.kukks.org) with a brand new user and it worked. Can you try again?

**Comment by Kukks** [comment]
Did you provide your own seed or did you let it generate one?

**Comment by bitcoinheiro** [comment]
Have it generate one

**Comment by NicolasDorier** [comment]
mmmh it should not have given a HTTP error 500.

**Comment by Kukks** [comment]
made it show a status message instead now
