### ISSUE TITLE
Invoices default view

### ISSUE THREAD

**Issue by 2ge** [btcpayserver/btcpayserver#1498]
It would be nice to have setting when one can change default view of list of invoices. For example show all invoices except expired ones (I don't care about those ones).

**Comment by NicolasDorier** [comment]
maybe a default filter in user's settings.

**Comment by Kukks** [comment]
At one point we had it save the last search in the browser cache I think.

**Comment by NicolasDorier** [comment]
mmh I think @rockstardev did it actually.

**Comment by Eskyee** [comment]
![154D12E3-B081-4E81-8510-85AD7499C04C](https://user-images.githubusercontent.com/30862925/80242026-90a3f980-865c-11ea-9e13-037ea34fe85e.jpeg) yes rockstar sorted it

**Comment by pavlenex** [comment]
I do not remember us ever caching the default filter view. I agree it can be a useful thing.

**Comment by rockstardev** [comment]
I definitely remember doing this to preserve grid data between navigation to invoice detail. What I think is missing is setting link  on top... when you click on Invoices link it can take you to the last Invoices list you were looking.

**Comment by pavlenex** [comment]
Should be fixed with #1734 try it out once new release is out and let us know if that's what you wanted, if not we can re-visit this issue. For now I consider it fixed.
