### ISSUE TITLE
Invoices tab incorrectly marks payjoin to p2sh-p2wpkh as non-payjoin

### ISSUE THREAD

**Issue by junderw** [btcpayserver/btcpayserver#1500]
**Describe the problem/bug**
When performing payjoin with p2wpkh, Invoices tab marks it correctly. With p2sh-p2wpkh it says it is paidOver with the amount of my payjoin utxo. (See image below, each wallet started with 1 UTXO of 0.1337 BTC size and it shows payment for 0.1337 + the actual invoice value)

**Your environment**
* Version of BTCPay Server: Github commit 7adaa14

**To Reproduce**
1. Create invoice with store that has p2sh-p2wpkh hot wallet, at least one utxo, and payjoin enabled.
2. Perform payjoin to pay the invoice.
3. Open invoice tab
4. See it was paidOver and it was marked as paying utxo value extra.

**Expected behavior**
It should be marked as payjoin and not paidOver. (see p2wpkh example in image below)

**Actual behavior**
It is marked paidOver  (see p2sh-p2wpkh example in image below)

**Screenshots/Links**
![範囲を選択_001](https://user-images.githubusercontent.com/11246316/80277159-18a30580-8728-11ea-814f-745fd7837d5d.png)

**Comment by pavlenex** [comment]
Haven't tried it yet but I don't agree that an invoice should be marked as `payjoin` normally it should just be `complete`.

**Comment by Kukks** [comment]
> 
> 
> Haven't tried it yet but I don't agree that an invoice should be marked as `payjoin` normally it should just be `complete`.

that's the status, not the invoice payment item

**Comment by Kukks** [comment]
Looking into it

**Comment by pavlenex** [comment]
Ok, I misunderstood the issue, was thinking it was about the statuses.

**Comment by junderw** [comment]
https://github.com/btcpayserver/btcpayserver/blob/92c58eea7feb12bb037cbfa82c93c071d7559eb6/BTCPayServer/Payments/PayJoin/PayJoinEndpointController.cs#L451-L464

Found the problem, but the fix is difficult... @NicolasDorier help please?

`CoinjoinTransactionHash = newPsbt.GetGlobalTransaction().GetHash(),`

This is the problem.

1. PSBT global transactions (as per BIP174) must have all scriptSigs as null.
2. P2SH requires redeemScript to be in the scriptSig, and therefore it will affect the TX hash.
3. This CoinjoinTransactionHash is not correct

Unless GetGlobalTransaction() tries to add in info from the Psbt Input (redeemScript, finalScriptSig, finalWitnessScript etc.) to populate the transaction.

**Comment by Kukks** [comment]
@NicolasDorier  here is an example of the different hash results
```
//in payjoin controller endpoint
newTx.GetHash() = 5f41d2e6fbfc5217ea68bae17c072702beffba4fd69ff9e9fba0f406c37cf69d
newPsbt.GetGlobalTransaction().GetHash() =e90a07038ba5ac57c42d44ccee6c33ede5d66a2afc7832e2941656dcb9d77d72
//in payjoin client after signed and finalized
proposedPayjoin.GetGlobalTransaction().GetHash() =e90a07038ba5ac57c42d44ccee6c33ede5d66a2afc7832e2941656dcb9d77d72

proposedPayjoin.ExtractTransaction().GetHash() = ea44922d1dd55c76a4536dedfc4a45f4ae68017de2aafb5c9d9bd762721ebd69

```

**Comment by junderw** [comment]
@Kukks could you also print out the raw hex of the transaction for each of those?

**Comment by Kukks** [comment]
```
newTx.GetHash() = 2454043d8aad8b1bb32c0bdb8189f0aece1c33c389d98c071ee105d9c9a7996c
newTx.ToHex()
01000000000102253d67d0d5858102d944e03fe88a2acf18975e595d85b4ad3b79c4777608e6e60000000000ffffffff253d67d0d5858102d944e03fe88a2acf18975e595d85b4ad3b79c4777608e6e601000000171600142a1a6d6aa857fe796c9f933712f17bba2b838e16fdffffff0251519b000000000017a91487d79397f90fba6c392085d8eead65a1b229fa6b87fa0b04000000000017a914ece15a35038bb62e96e5066eff98dcc9cf97906687024730440220698f4b7edd2052f5db008cf8c0bcf0c941ca855f88dd5e84c362fd94e96d05c202207ddcc57d36aa7fc562c0359dde06a081fdf276c4f9d35d4136007ee2b98aab7d01210342158159b2bdd2a34e31950c6f542aa0f3e0bf8a073a94106a3edce142fb1ded0000000000

newPsbt.GetGlobalTransaction().GetHash() = 262e3866385f9080b7d8c26d927cbbbd113d080480d72663d4b0ad186d152881
newPsbt.GetGlobalTransaction().ToHex() 
0100000002253d67d0d5858102d944e03fe88a2acf18975e595d85b4ad3b79c4777608e6e60000000000ffffffff253d67d0d5858102d944e03fe88a2acf18975e595d85b4ad3b79c4777608e6e60100000000fdffffff0251519b000000000017a91487d79397f90fba6c392085d8eead65a1b229fa6b87fa0b04000000000017a914ece15a35038bb62e96e5066eff98dcc9cf9790668700000000
```

**Comment by junderw** [comment]
newTx has redeemScript for # 1 but not # 0

newPsbt.GetGlobalTransaction() has no redeemScript for anything

The actual txid of the finalized and fully valid tx can be gained by adding the redeemScript to input # 0 of newTx

**Comment by junderw** [comment]
Which is available in the finalScriptSig of the PSBT that was sent to us from the client.

**Comment by junderw** [comment]
`newTx.Inputs.Add(selectedUTXO.Outpoint);` this doesn't add the redeemScript in the ScriptSig, does it?

If not, that's the culprit. @Kukks 

We can add the redeemScript and then use newTx.GetHash() instead of newPsbt.GetGlobalTransaction().GetHash() for CoinjoinTransactionHash

**Comment by junderw** [comment]
#1501 is the PR to fix this.
