### ISSUE TITLE
Adding more then 1 monero view wallet

### ISSUE THREAD

**Issue by mstyp** [btcpayserver/btcpayserver#1505]
I setup a btcpay server with monero and everything worked fine, but then i wanted to add another store for a friend who runs a different buisness, and I cant figure out how to add a view wallet for him. 

He has his own personal monero and btc wallets, and he was able to add his own electrum wallet to the server, but he did not see the option to add monero that I could when i setup my store, and when I added him as an admin he saw that for his store he was getting my monero, he added me to his store I could see that only admins could add/configure monero wallets, and the monero wallet his store uses seems to be using the monero wallet from my store.

Is it possible to add seperate monero wallets for each store?

**Comment by mstyp** [comment]
we could hypothetically setup a shared monero wallet and use different accounts, but at least from what i can see tinkering with the monero gui wallet we would both still have access to each others funds.

**Comment by Kukks** [comment]
You can only use 1 monero wallet per BTCPay instance. This is a limitation on how the monero-wallet-rpc works. As you said, the only solution is using separate accounts on the same wallet but that's as far as you can go.
