### ISSUE TITLE
Store Settings UI: Show begining and end of Derivation scheme

### ISSUE THREAD

**Issue by junderw** [btcpayserver/btcpayserver#1506]
**Describe the solution you'd like**
Currently, the Derivation scheme is formatted as "xpubxxxxxx..." whereas I would like it to be "xpubxxxxxx...xxxx-[p2sh]" with the ... in the middle. Since the Derivation scheme format places most of the meaning at the beginning and end of the scheme.

**Provide examples**
If applicable provide examples, wireframes, sketches or images to better explain your idea.
![範囲を選択_001](https://user-images.githubusercontent.com/11246316/80293929-f8625d80-879e-11ea-9fe5-bdc5f9217f34.png)

**Comment by junderw** [comment]
I do realize you can view by clicking modify and click the input and scroll all the way to the right.

Super super low priority for lazy people. (me)

**Comment by Kukks** [comment]
Ack, will do once I'm out of bed :) maybe a tooltip with the full string
works well enough?

**Comment by junderw** [comment]
it's better than 2 clicks and a scroll.

But a mouseover is more effort than just being able to glance at it.

the full string isn't really needed, the characters in the middle are not important for an "at-a-glance" UI entity.

**Comment by junderw** [comment]
Looking into it, the css is adding ellipsis dynamically for the size of the screen, maybe instead of the derivationScheme it should just say the bottom with word wrap.

"2-of-3 Multisig Legacy Keep Order"
"Standard"
"P2SH Wrapped"
"Legacy"

**Comment by junderw** [comment]
Again, low priority, but yeah.
