### ISSUE TITLE
Improve invoice paid visibility of on a dark invoice

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1508]
**Describe the problem/bug**
The gray text on the darkmode invoice is not that visible, but is important message that should be clear to the customers on the checkout.

**Your environment**
* Version of BTCPay Server:  v1.0.4.1
* Deployment method: Dev Env, Regtest

**To Reproduce**

Choose dark mode invoice and pay it.

**Expected behavior**
I believe it's better visible when the text is white and it does not make the design any different.

**Screenshots/Links**
![paid](https://user-images.githubusercontent.com/36959754/80302932-51d18900-87ad-11ea-8d0f-4423dd99755a.PNG)

**Suggested Solution**
```
.success-message {
    color: rgba(255, 255, 255, 0.9);
```
![white](https://user-images.githubusercontent.com/36959754/80302974-93623400-87ad-11ea-9b96-b5aa09d120ee.PNG)

**Comment by NicolasDorier** [comment]
ping @dennisreimann
