### ISSUE TITLE
docker-customer-lightning-cli.ps1 pay doesn't work

### ISSUE THREAD

**Issue by Dolu89** [btcpayserver/btcpayserver#1509]
**Describe the problem/bug**
When I try to launch `.\docker-customer-lightning-cli.ps1 pay lnb...` I get this error message `lightning-cli: Connecting to 'lightning-rpc': No such file or directory`

**Your environment**
* Version of BTCPay Server: v1.0.4.1
* Deployment method: Local dev regtest
* Other relevant environment details: LN node is launched. Test connection works in store settings

**Logs (if applicable)**
No log

**Setup Parameters**
/

**To Reproduce**
1. Go into a store settings
2. Click on Modify on BTC from Lightning nodes (Experimental)
3. Click on "You can use the internal lightning node by clicking here" to select internal node and save.
4. Create an invoice and get bolt11 request
5. Launch `.\docker-customer-lightning-cli.ps1 pay ln...`
6. See error

**Expected behavior**
Payment works

**Actual behavior**
lightning-cli: Connecting to 'lightning-rpc': No such file or directory

**Screenshots/Links**
/

**Additional context**
/

**Comment by NicolasDorier** [comment]
Tried to fix by connecting with

```
root@85495c88b361:/# lightning-cli --conf=/root/.lightning/config --lightning-dir=/root/.lightning --rpc-file=/root/.lightning/lightning-rpc  help
lightning-cli: Connecting to '/root/.lightning/lightning-rpc': Connection refused
```

But it seems that it does not work... :( did clightning broke something on regtest?

**Comment by Eskyee** [comment]
I see the command not found: lightning-cli
