### ISSUE TITLE
Brazilian Portuguese Localization issue - Checkout experience

### ISSUE THREAD

**Issue by bitcoinheiro** [btcpayserver/btcpayserver#1526]
**Describe the problem/bug**
One of the translated strings is breaking the design. I believe this specific string should have the char limit set to 44 chars with spaces to avoid bug in all languages.
Fixed the string to fit in Transifex - please update

**To Reproduce**
1. Create invoice (in pt_BR version)
2. Click on 'Conversion`
3. See error

**Expected behavior**
Clean design

**Actual behavior**
Broken design

**Screenshots/Links**
![btc_design-break](https://user-images.githubusercontent.com/50273260/80585984-e42b9400-8a1c-11ea-891d-ec78f040cee2.png)

**Additional context**
Added fix to translation and comment here:
https://www.transifex.com/btcpayserver/btcpayserver/translate/#pt_BR/enjson/156624077

I've also reviewed all the translations and made other minor changes/improvements to the checkout experience strings.

**Comment by NicolasDorier** [comment]
will update translations for next release. That said pinging @dennisreimann , I think it would be nice to properly handle the overflow of the box
