### ISSUE TITLE
Wrong amount calculation for POS in BTC

### ISSUE THREAD

**Issue by hubiktomas** [btcpayserver/btcpayserver#153]
When I creat a POS App with prices in BTC and then try to generate an invoice, it looks like BTC/LTC FX rate is 1:1.

BTC Selected:
![image](https://user-images.githubusercontent.com/3431342/39562707-7a158aa0-4ead-11e8-80d6-f99dc4410c18.png)

LTC Selected:
![image](https://user-images.githubusercontent.com/3431342/39562712-86bb3cbe-4ead-11e8-8801-bf2052257db3.png)

**Comment by NicolasDorier** [comment]
Ah interesting, will take a look! Definitively a bug.
I never tried to use "BTC" as the currency for creating the invoice (it is expecting fiat currency)

**Comment by hubiktomas** [comment]
I am using BitcoinAverage.com service. It looks like there is not a quote for BTC-LTC pair.

**Comment by NicolasDorier** [comment]
I did lot's of change to the rating system which will be deployed for the next version. Will check out if the bug is still present.

**Comment by NicolasDorier** [comment]
So now you can configure the BTC_LTC rate via the new rate scripting feature

![image](https://user-images.githubusercontent.com/3020646/39631325-d436c73e-4fec-11e8-995d-9adb44ba6361.png)

Failing to do this will result in LTC being disabled for the invoice and the following events in the invoice logs

![image](https://user-images.githubusercontent.com/3020646/39631376-ef278e98-4fec-11e8-939b-b0dbda45576a.png)
