### ISSUE TITLE
Invoice API returns HTTP 200 for creation failure

### ISSUE THREAD

**Issue by jlopp** [btcpayserver/btcpayserver#1532]
**Describe the problem/bug**
I have a script that creates invoices by making a POST request to my btcpayserver at /api/v1/invoices

I noticed that no invoices had been created in a long time, but didn't see errors in any logs.

Upon digging into the responses from btcpayserver the problem appears to be that the error is only returned in the HTML, not as a part of the HTTP response.

The root cause of the problem was a failed exchange rate provider. Perhaps consider using multiple fallback exchange rate APIs to eliminate this as a single point of failure?

**Your environment**
* Version of BTCPay Server: v1.0.4.2
* Deployment method: Docker
* Other relevant environment details: Ubuntu

**Logs (if applicable)**
No server log entries generated.

**Setup Parameters**
Nothing noteworthy

**To Reproduce**
1. Set store's exchange rate provider to NDAX
2. Make a POST request to create an invoice
3. Note that the server returns a 200 OK response

**Expected behavior**
An HTTP error code response; perhaps a 500?

**Actual behavior**
Server returns an HTTP 200 OK and an HTML response to my POST request that includes:

```
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>Pay Button request failed</h2>
                Please fix following errors:
                <ul>
                        <li>4/30/2020 7:16:33 PM: Creation of invoice starting&#xA;4/30/2020 7:16:33 PM: BTC_USD: The rating rule is ndax(BTC_USD)&#xA;4/30/2020 7:16:33 PM: BTC_USD: The evaluated rating rule is ERR_RATE_UNAVAILABLE(ndax, BTC_USD)&#xA;4/30/2020 7:16:33 PM: BTC_USD: Rate rule error (RateUnavailable)&#xA;</li>
                </ul>
            </div>
        </div>
    </div>
</section>
```

**Comment by NicolasDorier** [comment]
@jlopp as the error tells you, the exchange rate is set to "ndax" but they broke their API so we needed to stop support for them.

**Comment by NicolasDorier** [comment]
For the fallback, this is difficult.

The problem is that merchant, most of the time, prefer no deal rather than bad exchange rate.

**Comment by NicolasDorier** [comment]
Will check, the error code should definitely be different though.

**Comment by NicolasDorier** [comment]
@jlopp I just checked. The `/api/v1/invoices` route is actually for the pay button. As such it replies with HTML, and HTML does not send back HTTP error for incorrect input.

This is not meant to be used as part of an API. (counter intuitively)

You should use our Bitpay's API route to create invoices if you don't use the pay button.

**Comment by jlopp** [comment]
Gotcha; I guess I reverse engineered the payment button API so that I didn't need to use a full bitid library. I do think that eliminating exchange rate sources as single points of failure would be a big help since I've seen them cause stores to fail on several occasions.

**Comment by NicolasDorier** [comment]
@jlopp you can use the invoice endpoint without BitId by using the "Legacy API Key" in the Token section of your store.
We call it Legacy because that's how bitpay call it, but we won't remove it.
