### ISSUE TITLE
Payment request, edit window page, space under footer. 

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver#1536]
**Describe the problem/bug**
their seems like there is space under footer, which will create a flicker on Mac safari and on iOS iPhone when reach bottom of scrolling 

I also added pic to show the error and space under footer.

latest btcpay production build

<img width="1255" alt="Screenshot 2020-05-02 at 15 21 07" src="https://user-images.githubusercontent.com/30862925/80866793-9c10a980-8c88-11ea-80b8-d9b5da07e856.png">

**Comment by dennisreimann** [comment]
I can take a look at that :)

**Comment by pavlenex** [comment]
Can't replicate this in v1.0.4.4.

**Comment by pavlenex** [comment]
Actually replicated, so the problem occurs when you hit the bottom of the page in safari and may need to try a few times before you see the flicker, not a big deal imo ,but if someone knows how to fix would be good.

**Comment by Eskyee** [comment]
I think this has to do with the css stylesheets,
footer ?? fixed or absolute defined ??  

main-bundle.min.css
payment-request-admin-bundle.min.css

 "Any parent of footer div which does not have position defined makes it footer position:fixed of no consequence" 

<img width="291" alt="Screenshot 2020-05-08 at 05 09 27" src="https://user-images.githubusercontent.com/30862925/81369397-34c08280-90ea-11ea-8b9d-c3ae74c192ad.png">


https://medium.com/@sDeveloper/position-a-fixed-footer-in-ios-app-safari-browser-1c7721c65487

@dennisreimann

**Comment by Eskyee** [comment]
also this came up while researching bug
https://stackoverflow.com/questions/37933047/when-i-have-to-use-section-scripts
@dennisreimann

**Comment by Eskyee** [comment]
Replicated, so the problem occurs when you hit the bottom of the page in safari and may need to try a few times before you see the flicker, not a big deal imo @pavlenex 
yes I agree , but its very ugly bug and annoying !!  attention to detail sir.

I have tried to find a fix solution for @dennisreimann ;)

**Comment by Eskyee** [comment]
I also found the same whitespace footer bug in Home.cshtml @dennisreimann 
maybe if @rockstardev can look into this. if have a free moment.

**Comment by Eskyee** [comment]
![IMG_2799](https://user-images.githubusercontent.com/30862925/81370389-efea1b00-90ec-11ea-9aee-b0c43641af93.jpg)

**Comment by dennisreimann** [comment]
I can reeproducee this, but only during scrolling. Safari has this rubber band effect, which allows the scrolling to go beyond the page size (revealing the body background color), but it snaps back and should not stay at the overshot position. This can be reproduced on every website, not just ours.

For me it always snaps back and I haven't found a way to reproduce it so that e.g. the footer permanently has this space under it.

**Comment by pavlenex** [comment]
@dennisreimann go full screen mode, scroll to the bottom you'll see 1-sec flicker. I could only repro this in full screen. It does not stay back but there's just that flicker that I believe Esky finds annoying.

**Comment by Eskyee** [comment]
@dennisreimann 
Safari has this rubber band effect , yes you are correct.
but these two pages above... has a much bigger rubber band effect, than the other pages, 
and feels bit untidy, sorry for moaning at small details.

**Comment by Eskyee** [comment]
the footer doesn't permanently stay with space under it. 
it springs back like you said rubber band effect, but  has more space to drag than the other pages.
other pages look tidy with, rubber band effect.. its  a strange bug.. this one

I also checked in tor browser,  and see a white space under footer.

<img width="1440" alt="Screenshot 2020-05-08 at 10 10 30" src="https://user-images.githubusercontent.com/30862925/81391016-53d40a00-9114-11ea-9ac5-aa8673de86bf.png">

<img width="1440" alt="Screenshot 2020-05-08 at 10 10 51" src="https://user-images.githubusercontent.com/30862925/81391031-5afb1800-9114-11ea-90c9-48602b03452b.png">

as u can see here.

**Comment by Eskyee** [comment]
this might be a safari bug, in apple with the rubber band effect, I can't work it  out @dennisreimann

**Comment by Eskyee** [comment]
<img width="1440" alt="Screenshot 2020-05-08 at 10 15 38" src="https://user-images.githubusercontent.com/30862925/81391386-e5437c00-9114-11ea-94d1-db96bcd26b1f.png">

in my tor browser, their is white space under all page sections in the footer, so I can't seem to track this bug down ??

**Comment by Eskyee** [comment]
https://stackoverflow.com/questions/8150191/disable-elastic-scrolling-in-safari @dennisreimann

**Comment by Eskyee** [comment]
https://blog.christoffer.online/2015-06-10-six-things-i-learnt-about-ios-rubberband-overflow-scrolling/ @dennisreimann

**Comment by Eskyee** [comment]
https://www.smashingmagazine.com/2018/08/scroll-bouncing-websites/

**Comment by Eskyee** [comment]
can we try this when you have free time @dennisreimann 
Conclusion ??
If you don’t want your fixed headers or footers to bounce around on your web pages, you can now use the overscroll-behavior CSS property.

**Comment by Kukks** [comment]
Pleaaaaase use the edit button if you are posting so many comments in succession. I get an email for each one
![image](https://user-images.githubusercontent.com/1818366/81394014-90f2c900-9121-11ea-8894-6ef0820c4a9f.png)

**Comment by Eskyee** [comment]
whoops, sorry, I use edit button, next time..

**Comment by dennisreimann** [comment]
I'm afraid we won't be able to solve this without potentially introducing side effects in other browsers. The correct way to solve this would be to use the [`overscroll-behavior`](https://caniuse.com/#feat=css-overscroll-behavior) property, but Safari doesn't support it yet.

**Comment by pavlenex** [comment]
**Similar** issue happens on Firefox on Windows 10, but when editing a page.  v1.0.4.4
![57662E17-0897-4CF1-9C43-362CFE47E415](https://user-images.githubusercontent.com/36959754/82159312-8f49a380-988d-11ea-9ef1-a1ade9196769.GIF)

**Console**
![144v](https://user-images.githubusercontent.com/36959754/82159290-7fca5a80-988d-11ea-8cf2-d711cc29ebe5.PNG)

**Comment by bolatovumar** [comment]
I observed it on my Mac Air as well at some point.

**Comment by Eskyee** [comment]
It makes the site.. untidy with this. flaw

**Comment by pavlenex** [comment]
I posted [this ](https://github.com/btcpayserver/btcpayserver/issues/1536#issuecomment-629855846)here because it's similar issue. 
Make sure you're on the Point of Sale creation page and just scroll till the bottom, the footer disappears. Replicated in both dark (haven't tried the light theme yet).
I'm sure this can be replicated easier, though it's probably unrelated issue to the one in this issue.

**Comment by bolatovumar** [comment]
@pavlenex yeah, I'm trying it exactly as you describe it and can't repro it. I remember being able to repro it before though. I tried both Chrome and Safari.

**Comment by pavlenex** [comment]
@bolatovumar  I experienced this on Firefox, where as the issue Esky reported I was able to repro on Safari.

**Comment by dennisreimann** [comment]
Still cannot reproduce the initial error in Firefox, but noticed that the POS editing page behaves a bit weird and jumps when scrolling to the bottom. There is a kind of bump near to the bottom when scrolling up and down, where it seems to skip a bit. This seems to be somewhat related to the rich text editor, because if I remove it this effect is gone. Also expanding the text field sometimes alleviates this.

**Comment by Eskyee** [comment]
This is now scrolling smooth. Bug now fixed
