### ISSUE TITLE
Notification system

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#1542]
## Goal

Haing a notification system twitter and facebook like to notify users of several events such as:

* New version of btcpayserver available
* New payment received
* New pending refunds

## Technical design

Say a notification is for a store. A controller would call `notifcations.Broadcast(storeId, notification)` then the notifications instance would be responsible to fetch all the current users of that storeId and save a notification for them.

Table would be
```json
{
    "Created": "1234-56-78",
    "NoticeForUserId": "GUID",
    "Blob": {
    },
    "NoticeType": "",
    "Archived": false
}
```

This mean that if a notification target 2000 users, there will be 2000 dups of notification inserted.

We could avoid duplication by creating a table mapping user to notifications instead of embedding NoticeForUserId. 

I think we should not really care about that, BTCPay Server is not meant to be facebook level.
Also, such table would still require 2000 insert to map the users to the notification (say via a `UserNotification` table)

For the notifcation type, some example:
```json
{
    "Created": "1234-56-78",
    "NoticeForUserId": "GUID",
    "Blob": {
        "version": "1.0.5.0"
    },
    "NoticeType": "NewVersion",
    "Archived": false
}
```
```json
{
    "Created": "1234-56-78",
    "NoticeForUserId": "GUID",
    "Blob": {
        "invoiceId": "abc",
        "paymentType": "BTC",
        "amount": "10000",
    },
    "NoticeType": "NewPayment",
    "Archived": false
}
```
The renderer is responsible to create a `BodyText` and the `ActionLink` advantage are:

* We can later add localization easily
* This is API friendly (events can be consumed via greenfield) (@woutersamaey  [wants it](https://github.com/btcpayserver/btcpayserver/issues/775#issuecomment-523324249))
* This is extensible we can easily make new type as we want

All of that without making db migrations.

## Alternatives

Rockstardev does not like blobs, but he failed to convince me blob are evil. 
Before that we spoke about having `BodyText` and `ActionLink` in the column, or on blobs

on blobs => Under the presented design this can still be implemented without DB migration change if we really need it (though I am not sure we will)

On columns => I think this is not really flexible, and invite lot's of DB headache like collation, magic max length column size etc... Any new feature like localization or adding an imagePath will require more and more columns.

## Complaints

@rockstardev does not like byte blobs. But there is no other solution that would require us to add new type of notification without the need of making migrations with all the overhead it incurs (two PR can't update schema at same time, several EF gotcha, slower startup)

I am not against having `VARCHAR(max)` blobs so you can use some GUI to query the DB, but how to do that accross the three database we support is not clear.

I personally prefer byte array to decrease reliance on EF and database specific magic on string handling. (collation is also another magic part)

![image](https://user-images.githubusercontent.com/3020646/80924906-e730d680-8dc6-11ea-81ee-f7b30960eef5.png)

**Comment by pavlenex** [comment]
related #775

**Comment by pavlenex** [comment]
One thing that has to be taken into consideration for the future is also having notification **preferences**. Server admin hosting an instance may have a different preference from a merchant using a store. Store user may only want to be notified about `partiallypaid` or `invalid` invoices because that are the ones that require a reaction. Something to take into consideration while drifting how this can be achieved technically.

**Comment by NicolasDorier** [comment]
Example of notification design we would like 

![image](https://user-images.githubusercontent.com/3020646/80950804-88547700-8e31-11ea-9ef6-32633bae862b.png)

**Comment by Kukks** [comment]
Regarding schema, I agree with @rockstardev  about byte[] column being unfortunate, but having it a string would not work as we also zip and compress it so it's never readable by the db engine anyways.  Columns for each type wont work though as we need a renderer as @NicolasDorier  said since some of the data is dynamic and requires computation upon fetch. 


"I'm better with code than with words though." - Satoshi 
```csharp
    public class NotificationData
    {
        public string Id { get; set; }
        public byte[] Blob { get; set; } //or string, whicever works for you 
        public string Type { get; set; }
        public DateTimeOffset Timestamp { get; set; }
        public bool Seen { get; set; }
        public string ApplicationUserId { get; set; }
    }


    public interface INotificationEvent
    {
        Task<IEnumerable<NotificationData>> GenerateNotifications(IServiceProvider serviceProvider);
    }

    public class NotificationGenerator : EventHostedServiceBase
    {
        private readonly IServiceProvider _serviceProvider;

        public NotificationGenerator(EventAggregator eventAggregator, IServiceProvider serviceProvider) : base(
            eventAggregator)
        {
            _serviceProvider = serviceProvider;
        }

        protected override void SubscribeToEvents()
        {
            Subscribe<INotificationEvent>();
            base.SubscribeToEvents();
        }

        protected override async Task ProcessEvent(object evt, CancellationToken cancellationToken)
        {
            if (evt is INotificationEvent notificationEvent)
            {
                await notificationEvent.GenerateNotifications(_serviceProvider);
                // db.add
            }
        }
    }

    public interface INotificationRenderer
    {
        bool CanRender(NotificationData notificationData);
        (string partialName, object Model) GetRenderInfo(NotificationData notificationData);
    }

    public class PaymentNotification : INotificationEvent, INotificationRenderer
    {
        public class PaymentNotificationData()
        {
            public string StoreId { get; set; }
            public string InvoiceId { get; set; }
            public string PaymentId { get; set; }
        }

        public const string NotificationType = nameof(PaymentNotification);

        public PaymentNotificationData Data { get; set; }

        public async Task<IEnumerable<NotificationData>> GenerateNotifications(IServiceProvider serviceProvider)
        {
            return (await serviceProvider.GetService<StoreRepository>().GetStoreUsers(Data.StoreId)).Select(user =>
                new NotificationData() {ApplicationUserId = user.Id, Type = NotificationType});
        }

        public bool CanRender(NotificationData notificationData)
        {
            return notificationData.Type == NotificationType;
        }

        public (string partialName, object Model) GetRenderInfo(NotificationData notificationData)
        {
            var data = (PaymentNotificationData)null; //convert notificationData.Blob
            return ("Notifications/Payment", data);
        }
    }

```
