### ISSUE TITLE
Bad Gateway (nginx)

### ISSUE THREAD

**Issue by Uter1007** [btcpayserver/btcpayserver#1543]
**Describe the problem/bug**
Since the newest upgrade we received a higher load of 502 Bad Gateway errors in our API Logs. 
We are also facing a spike of user traffic at he moment where a lot of expired invoices have been created , so I am not quite sure what this cause is, but in total the application felt slower in the last couple of days (already updated my azure vm as well via ssh and restarted the server). 

**Your environment**
Azure hosted with Standard D2 v3 Size. BTCPayServer v1.0.4.2

**Logs (if applicable)**
The only errors that I found in the logs => 
2020-05-04 05:16:16.666 +00:00 [WRN] Error while contacting exchange kraken: The operation was canceled.

**To Reproduce**
It is not reproduceable sadly. Sometime btcpay performs like in the past very stable but since the update it felt unstable for me. 

If I can provide more log files, please instruct me which one I should add. 

Cheers,
Christoph

**Comment by Uter1007** [comment]
e.g.: A click on wallets takes > 30 seconds to open + the 3 wallets that I got showing only -- BTC after several refreshes some values are added

**Comment by Uter1007** [comment]
Also search is not finding all correct infos -> e.g.: when I am searching via Email address I found only a subset of invoices of a customer.

**Comment by NicolasDorier** [comment]
I advise you against using Azure. I had similar problem, paying a 60 USD per month machine on azure.

This was beaten by another VPS with 8 USD per month. And the VPS perf was beaten by a raspberry PI.  (yeah I know that's strange)

Can you take a look to `docker stats` to find what is taking lots of CPU?

**Comment by NicolasDorier** [comment]
For example, on my own instance LND:

`2a763cd684dc        btcpayserver_lnd_bitcoin            84.32%              219.2MiB / 1.953GiB   10.96%   `

**Comment by Eskyee** [comment]
I agree with @NicolasDorier  azure is over priced, & not recommend.

I`m also using Azure hosted with Standard D2 v2 Size. BTCPayServer v1.0.4.2
and since the update of btcpay server v1.0.4.2 released, I have seen improvements in my VM 
nothing I have noticed has slowed down my VM. with this release.
this is a month graph view of my stats.

<img width="1140" alt="Screenshot 2020-05-04 at 09 56 54" src="https://user-images.githubusercontent.com/30862925/80951692-40613000-8df0-11ea-9f59-2b39fd5b4dfc.png">

**Comment by Uter1007** [comment]
CONTAINER ID        NAME                                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
6054568c5523        btcpayserver_bitcoind               2.38%               361.8MiB / 7.749GiB   4.56%               155MB / 241MB       74.4GB / 4.16GB     14
7642da7083d8        tor-gen                             0.12%               8.562MiB / 7.749GiB   0.11%               9.66kB / 192B       14.3GB / 4.1kB      12
168809dfa85b        tor                                 0.14%               26.53MiB / 7.749GiB   0.33%               70.6MB / 72.6MB     14.8GB / 18.1MB     1
9cbbef2f0627        letsencrypt-nginx-proxy-companion   0.10%               14.2MiB / 7.749GiB    0.18%               9.65kB / 0B         20.3GB / 0B         14
d8890a928cec        nginx-gen                           0.08%               8.742MiB / 7.749GiB   0.11%               9.65kB / 0B         14.4GB / 143kB      12
b12d6189fc8c        generated_btcpayserver_1            0.74%               132.8MiB / 7.749GiB   1.67%               1.39MB / 60.4kB     83.6MB / 4.1kB      18
fad1db1c9da0        generated_nbxplorer_1               0.95%               258.4MiB / 7.749GiB   3.26%               186MB / 24.4MB      43.3GB / 457MB      24
284e58da1005        nginx                               0.00%               4.367MiB / 7.749GiB   0.06%               16.4MB / 21MB       2.76GB / 0B         2
00c00e44478d        generated_postgres_1                198.12%             60.94MiB / 7.749GiB   0.77%               209MB / 118GB       1.49TB / 31.4MB     16

**Comment by Uter1007** [comment]
I have also found some transactions that have been the correct timestamp by blockchain.info blockexplorer but where not rightfully set from expired to paid.

**Comment by Uter1007** [comment]
![image](https://user-images.githubusercontent.com/3653245/80952294-bddd6e00-8df9-11ea-868c-5bc3a91ca7bf.png)

**Comment by Uter1007** [comment]
I will now try to migrate to managed disks maybe this will increase performance.

**Comment by Eskyee** [comment]
managed disks is not your problem here.

**Comment by Uter1007** [comment]
yeah it was maybe I really bad idea - since 30 minutes the disks are still updating and the node is not syncing 
=>
NBXplorer headers height: 0
The node is starting...

but at least the website is snappy fast again.

**Comment by Eskyee** [comment]
Good news, if that’s it. You can close this issue.

**Comment by Uter1007** [comment]
it ended a total disaster thx to azure - sync does not work anymore, meanwhile I am trying lunanode to host a new instance. If azure is really so a pain in the a**, maybe a disclamer in the installation setup guide could help others.

**Comment by Eskyee** [comment]
Sorry to hear this!! 
yes adding a warning ⚠️ to deploy Azure is a good idea.  Nicolas has always recommend against using Azure due to costs and a needing a high learning experience. To deploy azure.. 

I have found Lunanode to be more easier & have a great service and offer great value.

**Comment by Eskyee** [comment]
You can try restarting your vm . Hardware,
Also trying btcpay-restart.sh via ssh
And btcpay-update.sh 
Node should start syncing!!

**Comment by NicolasDorier** [comment]
@Uter1007 managed disk is worse because of IO latency, the bitcoin node can't sync well.

**Comment by NicolasDorier** [comment]
the docker status you shared with us does not show anything concerning btcpay which take your CPU.

I also got a case where Azure had a fucking process trashing my machine for some reason, did not tried to investigate other processes on your machine?

**Comment by Uter1007** [comment]
no clue :( there was nothing suspicious via "top" (postgress took the most cpu and memory). I just dumped my azure vm now, will ride now with lunanode.Sync is still in progress (50%). So with some luck everything will be back to normal tomorrow. thx for the assistance.
