### ISSUE TITLE
Notification was sent only once

### ISSUE THREAD

**Issue by Marfusios** [btcpayserver/btcpayserver#1546]
Hello, 

I'm testing a notification feature on the invoice. 
Here is my configuration: 

![image](https://user-images.githubusercontent.com/3494837/80977968-be8bf980-8e25-11ea-9d8b-8d98145b6098.png)

As you can see, I've provided a notification URL to the webhook testing site, so it records every callback from BTCPay Server. 
https://webhook.site/#!/03b96bf0-dbd3-4da0-b3d1-54aa5e7f794c/6a302d75-870e-4aab-bfee-1207c89d0398/1

![image](https://user-images.githubusercontent.com/3494837/80978116-eb401100-8e25-11ea-882c-a5d54660bfef.png)

Invoice log: 
![image](https://user-images.githubusercontent.com/3494837/80978733-bb453d80-8e26-11ea-8a41-98c420f6879f.png)

Is it intended that notification is sent only once for `confirmed` state but not for `complete` (or any other)? 
It would be really convenient to get a notification when something happened with the invoice, to avoid constant polling. 

I'm implementing C# client for BTCPay Server (https://github.com/Marfusios/btcpayserver-client) and would like to make usage as straightforward as possible.

**Comment by Kukks** [comment]
You need to set `FullNotifications` and `ExtendedNotifications` to true when creating the invoice.

**Comment by Marfusios** [comment]
@Kukks thank you for the quick response. 
That seems to work. Is there any documentation for these features? Or current API is fully compatible with BitPay and we should examine their documentation (https://bitpay.com/api/#rest-api-resources-invoices-create-an-invoice)? 

One more small question. 
When getting an invoice data via API `/invoices/{invoiceId}` I have to also provide token `?token={token}`. 
BTCPay Server sends `token` when an invoice is created. 
Is it the correct approach to store `invoiceId` along with `token` somewhere (in local db) for later use? Will it work forever?

**Comment by Kukks** [comment]
> 
> 
> @Kukks thank you for the quick response.
> That seems to work. Is there any documentation for these features? Or current API is fully compatible with BitPay and we should examine their documentation (https://bitpay.com/api/#rest-api-resources-invoices-create-an-invoice)?
> 
> One more small question.
> When getting an invoice data via API `/invoices/{invoiceId}` I have to also provide token `?token={token}`.
> BTCPay Server sends `token` when an invoice is created.
> Is it the correct approach to store `invoiceId` along with `token` somewhere (in local db) for later use? Will it work forever?

That's correct about docs. 

We have an official client at https://github.com/MetacoSA/NBitpayClient

**Comment by Kukks** [comment]
On an unrelated, we wanted to use that nuget name for when we wanted to publish the client ourselves :(

**Comment by Marfusios** [comment]
@Kukks thanks for the info. 
Contact me in the future, when you will be ready. 
We can move that git repo under BTCPay Server organization also I can help you with implementation.

**Comment by pavlenex** [comment]
According to comments the issue has been resolved. Closing it.
