### ISSUE TITLE
Archive invoices

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1551]
People have been requesting the ability to delete invoices. We've been very restrictive about that since permanently deleting an invoice is very bad idea due to sometimes overlooked important information being lost. 

So we should introduce the concept of archived invoice and payment request

@NicolasDorier should user be able to view archived invoices somewhere?

**Comment by NicolasDorier** [comment]
@pavlenex we can add a filter `includearchived:true`

**Comment by rockstardev** [comment]
Yeah, all you need there is `Archived` field in database table. Or in Blob if @NicolasDorier prefers it that way ;)

**Comment by Kukks** [comment]
This one deserves a column so that we can do sql queries on before fetching everything

**Comment by pavlenex** [comment]
I am going to split this issue into multiple smaller ones per Kukks' request 🎉
