### ISSUE TITLE
Credentials autofill in generate wallet

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#1553]
**Describe the problem/bug**
When I generate a wallet from new/existing seed, the browser autofills my login credentials in the seed and passphrase fields. This only happens if you have saved credentials in the browser. It happens for me in chrome and firefox.

**Your environment**
* Version of BTCPay Server: v1.0.4.4
* Deployment method: LunaNode

**To Reproduce**
1. Go to: Stores > Settings 
2. Click on: Modify (derivation scheme)
3. Drop down to: New/Existing seed

**Expected behavior**
Should have empty fields

**Actual behavior**
My login is auto filled in seed and passphrase fields.

**Screenshots/Links**
![image](https://user-images.githubusercontent.com/39231115/81263540-116bd980-8ffd-11ea-8fbe-6bded5ea5a9f.png)

**Additional context**
I guess it's just annoying. Not really a big deal if there isn't a fix.

**Comment by pavlenex** [comment]
This is quite an annoyance for me as well. I remember we had a community member reporting they were unable to generate a wallet because they thought they need to add credentials there and were sure they were correct.

@Kukks is there a way we can fix this?
