### ISSUE TITLE
Payjoin HWW signing is broken

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#1557]
https://github.com/bitcoin-core/HWI/issues/328
and https://github.com/zkSNACKs/WalletWasabi/pull/3626

**Comment by pavlenex** [comment]
@Kukks What's the status on this one, some issues which were related got closed. It appears it's been solved on HWI level?

**Comment by Kukks** [comment]
Needs to get released on HWI and then Vault needs a release

**Comment by NicolasDorier** [comment]
did released new version of the vault btw

**Comment by Kukks** [comment]
will test and close once confirmed
