### ISSUE TITLE
Install on Dokku 

### ISSUE THREAD

**Issue by raminious** [btcpayserver/btcpayserver#1562]
really not sure this is a feature request but pretty sure this is not a bug. 
feel free to close the issue if it's irrelevant.

I'm trying to install btcpayserver on a machine that runnings Dokku.   
I spent a lot of hours and eventually could install that with 
`https://github.com/btcpayserver/btcpayserver/blob/master/amd64.Dockerfile` 
through the following commands:
```
docker pull btcpayserver/btcpayserver:1.0.4.4   
dokku apps:create btcserver
docker tag btcpayserver/btcpayserver:1.0.4.4 dokku/btcserver:1.0.4.4
dokku tags:deploy btcserver 1.0.4.4
```  

I could get the app up and running. 
I have a question and appreciate if someone answers to that:

how can I customize the setup, for example, I want to configure the image with `LTC` and `opt-save-storage-xs`?

**Comment by Kukks** [comment]
This will not work. You are only deploying one piece of the puzzle: you also need bitcoind (and litecoind in your case), NBXplorer, Postgres, nginx, etc
