### ISSUE TITLE
Fine-tune archival feature

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#1563]
Archival has been merged for both invoices and payment requests. They currently have no limits in terms of what can be archived. 
Should we:
* When archiving payment requests, archive its invoices?
* only allow expired or invalid(marked) invoices to be archived?
* Unarchive invoices when we detect a payment has been made to them?
* include amount of archived invoices to crowdfund and payment request counts?

**Comment by pavlenex** [comment]
I think yes for the first three points, but can you explain the forth one, what kind of counts?

**Comment by Kukks** [comment]
> 
> 
> I think yes for the first three points, but can you explain the forth one, what kind of counts?

Do we include the amounts paid to invoices that were archived on crowdfund? Code-wise, we want archival equivalent  to deleting, but this has severe consequences to those that wanted to "spring clean" when they have a long term crowdfund campaign where the amount just disappears then.

**Comment by pavlenex** [comment]
@Kukks  I guess people interested in spring cleaning won't clear paid ones, this mostly refers to expired. Sounds a bit like an edge-case if they have a crowdfund and notice it's not matching, they can unarchive those invoices they messed up?

**Comment by NicolasDorier** [comment]
>  When archiving payment requests, archive its invoices?

I think no.

> only allow expired or invalid(marked) invoices to be archived?

no.

> Unarchive invoices when we detect a payment has been made to them?

no.

> include amount of archived invoices to crowdfund and payment request counts?

yes

**Comment by pavlenex** [comment]
@NicolasDorier @Kukks so what do we do with this issue?

**Comment by Kukks** [comment]
> @NicolasDorier @Kukks so what do we do with this issue?

I will go through all points and verify that they are as above and then will close

**Comment by Kukks** [comment]
Seems like it's all good.
