### ISSUE TITLE
Add WebAuthn support

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#1564]
**Is your feature request related to a problem? Please describe.**
We should support WebAuthN as an alternative to U2F or TOTP as multi-factor. It enables you to use security keys on NFC, Bluetooth, USB and even the device's fingerprint or pin code! This will allow us to allow users to be able to be prompted to re-authenticate when changing sensitive information if wanted. 

**Describe the solution you'd like**
A WebAuthn implementat

**Describe alternatives you've considered**
We currently have support for U2F, TOTP two factor auth.

**Provide examples**
https://webauthn.io/
Try on desktop and phones with various settings, even with different settings. On windows for example, it asks you for the windows user pin if set!

**Additional context**
https://caniuse.com/#search=webauthn

**Comment by bolatovumar** [comment]
This is really cool! I tried the demo and it asked me to tap my Yubikey when registering. Once I tapped my Yubikey I had an account and could log in by tapping the Yubikey again.

**Comment by pavlenex** [comment]
concept ACK, would this break existing U2F registered keys? We should be careful not to lock people down, but sounds like a way better method compared to U2F.

**Comment by Kukks** [comment]
I think I would add it alongside U2F/2FA to not break existing users' security

**Comment by dennisreimann** [comment]
Researched this a bit, leaving some breadcrumbs here:

- [Migrating from U2F](https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/Migrating_from_U2F.html)
- [ASP.NET server-side lib](https://github.com/abergs/fido2-net-lib)
- [JavaScript client-side lib](https://github.com/wallix/webauthn)
