### ISSUE TITLE
Apps - Sort by name (Store-Name-Apptype)

### ISSUE THREAD

**Issue by Silverhaze19** [btcpayserver/btcpayserver#1568]
In the /apps page, add the possibility to sort apps by :

- Store name
- App name
- App type

by adding a 🔽 before or after : Store - App name - App type 

I think you can also do it on the /stores page with the Name & Website menus.

Thank you.

**Comment by bolatovumar** [comment]
Looks like this can be easily done with this jQuery plug-in: https://datatables.net. I will try it and report back.

**Comment by Kukks** [comment]
We should try and do this as we do invoices, in the backend, for future API
purposes

**Comment by bolatovumar** [comment]
@Kukks yeah, that's why I wanted to clarify if we want to maintain the sort order between page reloads and browsers. 

One disadvantage of doing it on the back-end is that you have to wait for a page reload (or an API Ajax call) before you see the sorted results which is not ideal.

**Comment by Kukks** [comment]
If you have paging while also sorting, the results need to be retrieved from the backend either way as the data in another page maybe become relevant for page one.
