### ISSUE TITLE
Refactor BTCPayNetworkProvider

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#1572]
We have a lot of places where we create new instances of this type. We should have a central instance, where we register networks to just it.

**Comment by NicolasDorier** [comment]
I think only in the currency parser.
I wished we cut this dependency as this is the only reason the Rates project reference common.

**Comment by pavlenex** [comment]
Is this issue still relevant @Kukks @NicolasDorier ?

**Comment by pavlenex** [comment]
ping @Kukks @NicolasDorier
