### ISSUE TITLE
I cannot transfer LTC using Ledger

### ISSUE THREAD

**Issue by lvtz** [btcpayserver/btcpayserver#1577]
**Describe the problem/bug**
When I want to transfer LTC from Ledger, I can't do it. Ledger Nano S is being detected, I have to accept the request for the public key and confirm the payment details (address, sum and fees). When I do this, I get a message like on the screen (Windows) or I don't see any message on macOS. Finally, Ledger Nano S freezes, only unplug and reconnect allow me to use it again.

**Your environment**
* Version of BTCPay Server: BTCPayServer v1.0.4.4
* Deployment method: LunaNode
* Other relevant environment details: -
* Windows, macOS

**Expected behavior**
I should see the final screen where there I will able to broadcast my transaction.

**Actual behavior**
Screen with error: TransportError: Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE

**Screenshots/Links**

Could not complete login.
Please try again and remember to make another transaction.

![image](https://user-images.githubusercontent.com/18595528/82218768-aaafbf80-991c-11ea-9362-efe269b280b9.png)

When press 'Anuluj' => Cancel

![image](https://user-images.githubusercontent.com/18595528/82219020-04b08500-991d-11ea-84b1-4d5456d159cf.png)

**Additional context**
I have recently updated the Firmware as well as the Ledger Live application.

The issue also occurred in the previous version of BTCPay Server.

**Comment by pavlenex** [comment]
Make sure Ledger Live is closed when you're doing it and that you have no other U2F devices plugged in, such as Yubikey, etc.

**Comment by lvtz** [comment]
I have no other U2F devices, and Ledger Live is always disabled while I trying to make the transfer. I'm always doing same procedure for both BTC and LTC transfers. I do not know how long this problem concerns me, because long ago no buyers chose LTC, but some time ago it worked OK.

**Comment by Kukks** [comment]
The Ledger U2F method for using a Ledger device with BTCPay is deprecated and won't be receiving any updates or fixes unless it is trivial (or someone else does it for us). BTCPay Vault is the official, new way but there has been no attempts from the community to support alts through it and as such is BTC only. 

As @pavlenex said, try making sure you use only one U2F active device. I've also seen that you usually need to do the confirmation quite fast when signing a transaction

**Comment by Kukks** [comment]
For alts, I just suggest you generate a new wallet( you can use the generate wallet feature inBTCPay), store the seed in a password manager(or other secure place) and use it to sign transactions as needed.

**Comment by pavlenex** [comment]
> 
> 
> I have no other U2F devices, and Ledger Live is always disabled while I trying to make the transfer. I'm always doing same procedure for both BTC and LTC transfers. I do not know how long this problem concerns me, because long ago no buyers chose LTC, but some time ago it worked OK.

You do have a LTC app opened? You tried plugging ledger in out and re-checking? If you can please provide console logs from browser if there's something strange and also look into logs of btcpayserver to see if it gives any error.

**Comment by lvtz** [comment]
@pavlenex - I don't have any other LTC apps, and Ledger Live is turned off. I checked it on several computers (Windows 10 and macOS), as well as different browsers.

Always the same result - after confirming the transfer on Ledger device, I've received the failure message. In the case of macOS, I still see the message in the yellow box "Please validate the transaction on your ledger". In both systems, the Ledger device stuck on 'Application is ready'.

I add a screenshot from the Network and Console tab.

![ledger-ltc-issue](https://user-images.githubusercontent.com/18595528/82239262-cb860e00-9938-11ea-8592-69e96bb2eefd.png)

**Comment by pavlenex** [comment]
> I don't have any other LTC apps, and Ledger Live is turned off.

I was referring to having an opened LTC app on your ledger device, which is required in order to sign.

**Comment by lvtz** [comment]
> > I don't have any other LTC apps, and Ledger Live is turned off.
> 
> I was referring to having an opened LTC app on your ledger device, which is required in order to sign.

Yes, of course, if you talk about it, then of course I know that the app must be open on the device. Without this, I would not see a request for a public key or transfer information that I need to approve.

**Comment by pavlenex** [comment]
1. Look into [btcpay logs](https://docs.btcpayserver.org/Troubleshooting/#_2-1-btcpay-logs)
2. Try to sign fast by clicking those buttons., sometimes that worked. 

Without an actual error from logs it's hard to say what's going on.

Alternatively as Kukks suggested, try signing with a seed itself bypassing the ledger integration or recover the wallet in Electrum or whatever wallet LTC uses.

**Comment by NicolasDorier** [comment]
May help https://www.reddit.com/r/ledgerwallet/comments/c5uy96/ledger_failed_to_sign_u2f_device_ineligible/

**Comment by lvtz** [comment]
@NicolasDorier - I've disabled Windows Defender, and same issue.
@pavlenex - Any idea which gap limit should I set, to get my transactions and funds available into Ledger Live?

I also see nothing in the logs.

**Comment by pavlenex** [comment]
@lvtz Gap limit depends on you and how customers interact with your checkout. I'd say try with 100, 200, 500 to see if you can see all the funds. 500 should be more than enough.

**Comment by lvtz** [comment]
Unfortunately, but none of the indicated "gap" limits proved to be helpful. I do not know, it's strange, it always looks like (long) synchronization has been completed, but I do not see the last LTC payment in my account. The last customer paid with LTC in January and this payment appeared, but the last one transaction from May, unfortunately, did not.

I didn't make any changes to the settings. I have only updated the Ledger firmware to the latest version. I don't know if it was the cause or something else. Strange that this transaction is not visible in Ledger Live.

It is also puzzling that LTC has an "xpub" address in the BTCPayServer settings, and in Ledger Live logs this address starts with "Ltub".

BTCPayServer:
![image](https://user-images.githubusercontent.com/18595528/82595202-7bf84a00-9ba5-11ea-89ec-1a1049696ddf.png)

Ledger Live:
![image](https://user-images.githubusercontent.com/18595528/82595251-929ea100-9ba5-11ea-84db-f9f50d39a2c5.png)

When I connected Ledger and generated a list of addresses to check inside BTCPayServer if LTC connection is valid, I found an address on the list that matches the one I generated in Ledger Live.

Maybe BTCPayServer tries to use an "xpub" address when trying to transfer, where Ledger requires "Ltub". Or, the funds landed on the address generated for "xpub", and Ledger displays only those "Ltub". I don't know anymore, it's a total mystery to me.

**Comment by pavlenex** [comment]
> Unfortunately, but none of the indicated "gap" limits proved to be helpful. 

Since these transactions are months apart, you can try going higher. I'd contact Ledger and ask what's the maximum gap limit they allow.

> Maybe BTCPayServer tries to use an "xpub" address when trying to transfer, where Ledger requires "Ltub". Or, the funds landed on the address generated for "xpub", and Ledger displays only those "Ltub". 

We auto-convert it all to an xpub, so that's normal.

If these don't work, then the only solution is to sign the transaction with a private key. As long as you see the transaction in BTCPay wallet, it's there and can be spent.

**Wallet > `Sign with hd private key or mnemonic`**

**Comment by pavlenex** [comment]
FYI, Ledger integration has been removed for altcoins in [3be2ef5](https://github.com/btcpayserver/btcpayserver/pull/1599)

Closing this since it no longer appears to be relevant due to removal. You should still be able to get your funds out the way explained above. Let us know if you can't figure it out.

**Comment by lvtz** [comment]
God, I don't know if I'm so stupid or just this withdrawal method has not been tested by anyone before.

I used the offline tool called 'BIP39 Mnemonic Code Converter', which based on my seed was generated LTC account details for the appropriate 'AccountKeyPath'. While the 'xpub' key is the same as in the BTCPayServer settings, the private key that is in the pair no longer matches (getting an error when want to send transfer). 

Well, unless BTCPayServer requires me to enter my 'BIP32 Root Key' there, but this is not acceptable to me. I will not enter the 'xprv' primary private key here, which is associated with all Ledger accounts. Please tell me it's not what I think. The only thing that may not agree is that I have not entered 'MasterFingerprint' anywhere, which may be important to generate a private key. If this is it, then please advise on how to do it correctly.

Thank you for your willingness to help and understanding.

![LNIJHK BG](https://user-images.githubusercontent.com/18595528/82803373-b18c8400-9e80-11ea-8a45-761bf7a983ea.png)
![hlnV* OD](https://user-images.githubusercontent.com/18595528/82803383-b5b8a180-9e80-11ea-8c59-c0244729bbd9.png)

**Comment by NicolasDorier** [comment]
@lvtz if you are copy and pasting the xpriv from say "m/49'/1'/1'", then you need to put "m" in your wallet settings.

**Comment by NicolasDorier** [comment]
Another way you can get back your funds is by using Electrum for Litecoin with the hardware integration (if there is). You just need to increase the gap limit.

**Comment by lvtz** [comment]
> if you are copy and pasting the xpriv from say "m/49'/1'/1'", then you need to put "m" in your wallet settings.

@NicolasDorier - Wow... Finally it works! I've used xprv that was in pair with xpub, next I cleared MasterFingerprint and set AccountKeyPath m/. Finally transfer was processed without any issue. Thank you for your help!

![image](https://user-images.githubusercontent.com/18595528/82824821-5079a600-9eaa-11ea-8c18-44806ef9df7d.png)
