### ISSUE TITLE
Can't use Pay Button with Raspiblitz v1.5

### ISSUE THREAD

**Issue by Arno-GitHub** [btcpayserver/btcpayserver#1584]
**Describe the problem/bug**
When copying html code for pay button it can't be used.
The button has a link (form action) to the tor address of my lightning node. When the button is clicked the non-tor browser can't connect to my lightning node.

**Your environment**
* Version of BTCPay Server: v1.0.4.2
* Deployment method: Raspiblitz v1.5
* Other relevant environment details:
With Raspiblitz when selecting BTCPay server Tor is mandatory.

**To Reproduce**
1. Install Raspiblitz v1.5
2. Select BTCPay server at Services
3. Create store
4. Go to 'Pay Button'
5. Copy html code to a webpage
6. Click button (in a non tor browser)

**Expected behavior**
html code which can connect to my lightning node to show an invoice.
or
a message the Pay Button can't be used if lightning node is behind Tor.
I don't know if it is possible at all.

**Actual behavior**
Browser can't open .union address of my lightning node.
Tor browser can't find my test website in my lan (I use tor browser only to connect to the BTC Pay server).
Browser (FF) can connect to test website in my lan.

**Comment by NicolasDorier** [comment]
Do you have configured a clearnet domain for your btcpay instance?

**Comment by Arno-GitHub** [comment]
No I don't have a domain.

If I want to change the domain name there is a red message: Maintenance feature requires access to SSH properly configured in BTCPayServer configuration.
On https://docs.btcpayserver.org/ChangeDomain I see an SSH settings option but this setting is not on my instance so I can't change domainname.

Can I set SSH access in a different way (I know how to do it on OS level).
Raspbian has already ssh access but with different user. Even BTCPay server user on raspiblitz (btcpay) is different from the user in BTCPay server (user@hostname).

**Comment by Kukks** [comment]
The ssh feature only works if btcpay has the ssh settings configured
correctly. Please take a look at the docker setup and configure based on
that.

Using only tor will not allow you to use btcpay or the configured lightning
node through a normal browser.

**Comment by Arno-GitHub** [comment]
> Using only tor will not allow you to use btcpay or the configured lightning node through a normal browser.

There is no possibility for me to go for another solution. Only a Raspberry Pi for now.
Thanks anyway.

**Comment by pavlenex** [comment]
Closing this since it appears to have been solved.
