### ISSUE TITLE
BtcpayServer v1.0.4.4 build failure because of unreferenced package System.IO.Pipelines

### ISSUE THREAD

**Issue by MrEightFive** [btcpayserver/btcpayserver#1588]
**Describe the problem/bug**
Manual upgrade of the BtcpayServer fails on `./build.sh` invocation :
`error CS0234: The type or namespace name 'Pipelines' does not exist in the namespace 'System.IO' (are you missing an assembly reference?)`

**Your environment**
* Version of BTCPay Server: v1.0.4.4
* Deployment method: manual
* dotNet:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.300/

Host (useful for support):
  Version: 3.1.4
  Commit:  0090613580

.NET Core SDKs installed:
  3.1.300 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Logs (if applicable)**
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  BTCPayServer.Client -> /srv/btcpayserver/BTCPayServer.Client/bin/Release/netstandard2.1/BTCPayServer.Client.dll
  BTCPayServer.Common -> /srv/btcpayserver/BTCPayServer.Common/bin/Release/netcoreapp3.1/BTCPayServer.Common.dll
  BTCPayServer.Data -> /srv/btcpayserver/BTCPayServer.Data/bin/Release/netcoreapp3.1/BTCPayServer.Data.dll
  BTCPayServer.Rating -> /srv/btcpayserver/BTCPayServer.Rating/bin/Release/netcoreapp3.1/BTCPayServer.Rating.dll
  
  Bundler: Begin processing bundleconfig.json
        Bundled wwwroot/bundles/wallet-send-bundle.min.js
  Bundler: Done processing bundleconfig.json
HostedServices/Socks5HttpProxyServer.cs(3,17): error CS0234: The type or namespace name 'Pipelines' does not exist in the namespace 'System.IO' (are you missing an assembly reference?) [/srv/btcpayserver/BTCPayServer/BTCPayServer.csproj]                                                                                                                         
HostedServices/Socks5HttpProxyServer.cs(151,90): error CS0246: The type or namespace name 'PipeReader' could not be found (are you missing a using directive or an assembly reference?) [/srv/btcpayserver/BTCPayServer/BTCPayServer.csproj]                                                                                                                          
HostedServices/Socks5HttpProxyServer.cs(318,64): error CS0246: The type or namespace name 'PipeWriter' could not be found (are you missing a using directive or an assembly reference?) [/srv/btcpayserver/BTCPayServer/BTCPayServer.csproj]                                                                                                                          

Build FAILED.

HostedServices/Socks5HttpProxyServer.cs(3,17): error CS0234: The type or namespace name 'Pipelines' does not exist in the namespace 'System.IO' (are you missing an assembly reference?) [/srv/btcpayserver/BTCPayServer/BTCPayServer.csproj]                                                                                                                         
HostedServices/Socks5HttpProxyServer.cs(151,90): error CS0246: The type or namespace name 'PipeReader' could not be found (are you missing a using directive or an assembly reference?) [/srv/btcpayserver/BTCPayServer/BTCPayServer.csproj]                                                                                                                          
HostedServices/Socks5HttpProxyServer.cs(318,64): error CS0246: The type or namespace name 'PipeWriter' could not be found (are you missing a using directive or an assembly reference?) [/srv/btcpayserver/BTCPayServer/BTCPayServer.csproj]                                                                                                                          
    0 Warning(s)
    3 Error(s)

**To Reproduce**
1. pushd /srv/btcpayserver
2. git checkout -f v1.0.4.4
3. ./build.sh

**Expected behavior**
Build is successful

**Actual behavior**
Error building, but build is successful after:
`dotnet add BTCPayServer/BTCPayServer.csproj package System.IO.Pipelines --version 4.7.2`

**Screenshots/Links**
none

**Additional context**
I guess BTCPayServer/BTCPayServer.csproj is missing
`<PackageReference Include="System.IO.Pipelines" Version="4.7.2" />`

**Comment by janoside** [comment]
Seeing this on ubuntu 18.04.4 also (still dotnet 3.1.300). Fix proposed by @MrEightFive worked for me.

**Comment by pavlenex** [comment]
[f2bb24f](https://github.com/btcpayserver/btcpayserver/commit/f2bb24f6ab6d402af8214c67f84e08116eb650e7)
