### ISSUE TITLE
Support for 2of3 MultiSig LTC Wallets

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#159]
I'm not sure if this is a bug or a usage issue. But I can't seem to manage to get the Derivation Scheme right for my 2of3 p2sh Multi Signature LTC Wallet created with Electrum-LTC. No matter what combination I try I allways get different addresses then on my wallet software (even with disabling cashaddr format).

Could you provide an example of how to configure such a setup? I've got 3 master public keys and tried:

2-of-xpub1-xpub2-xpub3-[legacy] and -[p2sh]

Same with 3-of ... non seemed to work.

Grateful for any input on this. :-)

**Comment by NicolasDorier** [comment]
use `2-of-xpub1-xpub2` without any tag, then on the second screen, where they ask you to confirm the addresses, fill the textbox below with the first address of your wallet. It will try to find the derivation scheme.

**Comment by petzsch** [comment]
I just noticed that I was using Electron Cash (BCH wallet) the whole time. That kind of explains my problem ^^
Thanks anyway for the valuable information. Perhaps a general information how the XofY wallets should be enterd would be helpful.

I will test again with Electrum-LTC, but i'm pretty shure it was just a layer 8 problem :-)
