### ISSUE TITLE
Sending btc

### ISSUE THREAD

**Issue by jonathan-daniel** [btcpayserver/btcpayserver#1593]
is it possible to send btc through the API? To handle cases like refunds etc.

**Comment by pavlenex** [comment]
Not possible yet, though it's being worked on, specifically in #1320 and #890 
For questions like this I recommend you join us on chat.btcpayserver.org insead of opening the issues. Feel free to join convo on the related issues.

**Comment by jonathan-daniel** [comment]
Thanks, but is it really not possible to withdraw funds to a specific address through the API? It seems like such a basic feature
