### ISSUE TITLE
Public link to share the greenfield api docs part of CI

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#1594]
It would be nice if we had a public link to share the API.

Maybe later we can do a github page with the latest swagger and just integrate the update to the Circle CI when we tag a new version.

Also it will be indexable by search engines!

(following https://github.com/btcpayserver/btcpayserver/pull/1567)

**Comment by pavlenex** [comment]
This would be useful as part of docs.btcpayserver.org as well.

**Comment by dennisreimann** [comment]
Is this the same as #1613?

**Comment by NicolasDorier** [comment]
ugh... I have bad memory sorry
