### ISSUE TITLE
Currency does not show during checkout screen

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#16]
Checkout is not shown, only currency. This could cause issues with users thinking they are paying in one currency when another is being used. 

Currency Code should be added to checkout flow.

**Comment by astupidmoose** [comment]
![image](https://user-images.githubusercontent.com/3916318/33518484-7e6b2072-d74a-11e7-9437-d8c49f1cfe33.png)

**Comment by NicolasDorier** [comment]
What would you show instead of currency ? USD 10,854.91 ?

**Comment by astupidmoose** [comment]
There is no currency indicated right now is there? 

Usually you should see 1 BTC = $10,854.91 USD or 1 BTC = $14049 CAD

Maybe only an issue when currencies use the same symbol, such as dollars.

**Comment by NicolasDorier** [comment]
Will be fixed by 43635071d99dd7c1e15f6f585bf8bee9b023547c
