### ISSUE TITLE
Feature request: Add support for Monero

### ISSUE THREAD

**Issue by hubiktomas** [btcpayserver/btcpayserver#160]
Support for Monero including self hosted full node would be great.

**Comment by NicolasDorier** [comment]
This is not easy as Monero has completely different design than Bitcoin.
All shitcoin support depends on NBXplorer and NBitcoin which highly depend on the UTXO model.

I don't have time to learn about Monero to do this, but if someone feels motivated to do, I can guide.

**Comment by wallopthecat** [comment]
Closed by https://github.com/btcpayserver/btcpayserver/commit/d66b111121c9b6eebdde90e8ce8ace7044df1546 and subsequent fixes
