### ISSUE TITLE
selling Digital Products using BTC pay server

### ISSUE THREAD

**Issue by Nimo503** [btcpayserver/btcpayserver#1601]
I sell Digital Products and audiobooks and I need a feature with BTC pay server 

feature just like URL redirection we get in PayPal buy buttons. After the customer makes successfull payment and the transaction is complete, how can I redirect customer to a new webpage url instead of just the "invoice has been paid, view invoice or return to merchant website button"?
Or 
At least there must be a customizable button for example- "click here to access your audiobooks”

This is especially helpful for merchants that sell Digital downloadable products/softwares/ebooks/audiobooks

**Comment by Kukks** [comment]
There is already an option when creating the invoice to have a specific url for after the invoice is done. There's also another option to redirect to the option automatically. 

```
 public string RedirectURL { get; set; }
 public bool? RedirectAutomatically { get; set; }
```

`RedirectURL ` can have templates in them that change based on the invoice. For example
`http://gozo.com/{OrderId}/{InvoiceId}`

**Comment by pavlenex** [comment]
Closing this since it's appears to have been solved.
