### ISSUE TITLE
The internal Lightning connection string address is checked for HTTPS instead of the one entered via web UI

### ISSUE THREAD

**Issue by Kixunil** [btcpayserver/btcpayserver#1603]
**Describe the problem/bug**
Instead of checking the actual connection string, the check whether an address is localhost or onion checks against the `btc.lightning` setting from config file

**Your environment**
* Version of BTCPay Server: 1.0.4.2
* Deployment method: [Cryptoanarchy Debian Repository](https://https://github.com/Kixunil/cryptoanarchy-deb-repo-builder)
* Other relevant environment details: N/A

**Logs (if applicable)**
N/A

**To Reproduce**
1. Configure BTCPayServer without `btc.lightning` key in the config file
2. Go to Add Lightning node page
3. Add the connection string to that field using http and pointing to localhost or 127.0.0.1
4. *See BTCPay complaining about HTTP*
5. Add `btc.lightning` with the same string to btcpay config
6. Restart the service
7. Add the same string again
8. *Observe that the string is accepted*
9. Change the connection string to a non-local address
10. **See the connection string being accepted despite being dangerous**

**Expected behavior**
The setting of `btc.lightning` doesn't affect detection of HTTP. In particular:

* When `btc.lightning` is missing or is different from the specified string, the error message doesn't show for loclahost and onion addresses
* **When `btc.lightning` contains `https`, but the entered string does not, the user gets the error**

**Actual behavior**
The condition checks the internal node instead of the entered connection string.

**Screenshots/Links**
I believe screenshot is not needed here, will add if required.

**Additional context**
* [Probably offending line](https://github.com/btcpayserver/btcpayserver/blob/3425f84507ada2f527f7e735da6270e0b7eb86a0/BTCPayServer/Controllers/StoresController.LightningLike.cs#L94)
* This supersedes #1600

**Comment by bolatovumar** [comment]
I'm not sure if this issue even applies anymore? The error referenced in this issue doesn't even exist anymore.

**Comment by Kixunil** [comment]
Good point, I just tested it with recent version and it now works fine. I guess the refactorings fixed it. :tada:
