### ISSUE TITLE
About the internal lightning wallet of the btcpayserver

### ISSUE THREAD

**Issue by makarid** [btcpayserver/btcpayserver#1606]
Hello, i would like to ask you about the internal lightning wallet of the btcpayserver. Does the server creates a lightning wallet for every store or every store shares the same lightning wallet? I am sorry if the question is off topic. Thank you!

**Comment by pavlenex** [comment]
All store share a the same LN wallet. The use-case where we allow stores to share LN node is not mean for multi-users. This has been mentioned in our FAQ. 

Please in the future, for general questions use chat.btcpayserver.org, we use GitHub for bug reports, feature requests and technical issues.

**Comment by makarid** [comment]
Thank you!
