### ISSUE TITLE
[Feature] Ability for the payjoin receiver to setup which coin to use in priority by label

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#1607]
Currently, coin selected by the payjoin receiver for are more or less random. I think we can significantly improve this situation.

# Use case

If you use wasabi wallet for mixing `0.15 BTC`, you will get `0.1 BTC` which is unlinkable to the input and `0.5 BTC` which is linkable.

Now imagine, that we add an auto labelling feature which flag `0.1 BTC` as Coinjoin, Wasabi Mixing and `0.5 BTC` as "Wasabi Change".

If the payjoin receiver can prioritize "Wasabi Change"  outputs to be used in payjoin, this would severely undermine one of the heuristic used to de-anonymise wasabi wallet users.

Ping @lontivero @nopara73

**Comment by nopara73** [comment]
While I agree the 1 anonset small coins should participate in CoinJoins for usability reasons, however this can backfire as in this way the receiver exposes its pre-mixed wallet cluster to the sender, so there's a privacy argument against it :/

**Comment by NicolasDorier** [comment]
Closing this as anyway there is no more change problem in wasabi
