### ISSUE TITLE
[Discussion] Updates in the Greenfield API

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#1617]
We need to take a decision over how to do updates in BTCPayServer, and then keep consistency.

Should a `POST` update the whole structure or only specified field.

Imagine I want to update store with id `123` to `my awesome store`.

Should make POST handle partial update like:
POST/PUT or PATCH /store/123
```json
{
  "name": "my awesome store"
}
```

Or should POST update the whole thing, where you need to first
GET /store/123
```json
{
   "name" : "old name",
   "payjoinEnabled": true,
   "defaultCurrency": "USD"
}
```

Then update the whole thing
POST /store/123
```json
{
   "name" : "Awesome store",
   "payjoinEnabled": true,
   "defaultCurrency": "USD"
}
```
If some fields are not initialized, the server assume that it is set to a default value and update the field.

I am rejecting the following alternative:

* Make both POST and PUT. This would double the amount of work for us, while not providing something that still can't be done already whichever what solution we chose.
* Using JSON PATCH. This is completely untyped, difficult to use, and not really spread anyway.

I checked how for example did slack API, and [they seem to support POST with partial updates](https://api.slack.com/methods/users.profile.set).

[Twitter](https://developer.twitter.com/en/docs/accounts-and-users/manage-account-settings/api-reference/post-account-update_profile) is also doing POST with partial update, but instead pass all by query string.

I think that from API perspective it makes sense to support partial update for POST.

Two API that need to be fixed if we decided to go that route:
* Update payment requests
* Update store

**Comment by NicolasDorier** [comment]
About updating the whole object: If a btcpayserver is updated but not the greenfield library in use, then the user will end up updating field he is not meaning to.

**Comment by NicolasDorier** [comment]
Another point about partial updates:

You can do full update with partial update, but not the reverse.

**Comment by Kukks** [comment]
Full updates. Doing partial updates Is a nightmare on both client and server. If you create a UI updating the model, you have to write ugly diff functiona and partial model building and then either lose your static type model or end up with a model with all properties anyway

**Comment by NicolasDorier** [comment]
Can you give more details about what you call nightmare?

On the client part this is definitely better, you want to change name?

PATCH
```json
{
 "name": "new name"
}
```

On the server this is just an additional null check.

**Comment by britttttk** [comment]
Personally I hate to deal with partial updates. Doesn't the client always already know the whole object anyways? Also is there no property that will ever be assigned back to null, just like the issue with PATCH?

**Comment by Kukks** [comment]
> 
> 
> Can you give more details about what you call nightmare?
> 
> On the client part this is definitely better, you want to change name?
> 
> PATCH
> 
> ```json
> {
>  "name": "new name"
> }
> ```
> 
> This is easily scriptable via curl.
> 
> On the server this is just an additional null check.

Let's look at this example:
```
    public class ModelA
    {
        public string Id { get; set; }
        public int? PropertyA { get; set; }
        public int PropertyB { get; set; }
    }
```

I call `/api/models/{id}` and get 
```json
{
  "id": "",
  "propertyA": 1,
  "propertyB": 3
}
```

I want to update `PropertyB` and set it to `2`. With the proposed PATCH call in https://github.com/btcpayserver/btcpayserver/issues/1617#issuecomment-636282156 , the payload would be 
```json
{
  "propertyB" : 2
}
```

If your Controller action has `PartialUpdate(string id, [FromBody] ModelA payload)`, `ModelA.PropertyA` will be set to null as it was not found in the model, and the controller will accept it.

This means that for nullable types, you would need to wrap them in a specific data type for partial update models.  Something like
```
    public class PropUpdate<T>
    { 
        public T NewValue { get; set; }
        public bool Updated { get; set; }
    }
```

We would need to do a separate model for only updates then:
```
    public class UpdateModelA
    {
        public string Id { get; set; }
        public PropUpdate<int?> PropertyA { get; set; }
        public int PropertyB { get; set; }
    }
```

And to stay sane, we should be consistent and apply to all update-able properties then
```
    public class UpdateModelA
    {
        public string Id { get; set; }
        public PropUpdate<int?> PropertyA { get; set; }
        public  PropUpdate<int> PropertyB { get; set; }
    }
```

Now that the server is sorted out, we go back to the client.

The client can no longer just send 

```json
{
  "propertyB" : 2
}
```

and needs to do 

```json
{
  "propertyB" : { newValue: 2, updated: true }
}
```

If the client was for example building a UI, they would fetch `ModelA`, display it, let user modify and submit. 
The client now needs to 
* cache the original model retrieved
* retrieve a fresh model from the server after submission
and then perform a diff to see which properties were updated. 

You can say "screw this" and just set all properties to be updated and send them all but at this point, why even have partial updates then?

An alternative solution would be that the controller action for updates ditches the static type and goes for generics, but this is not nice unless you are working with dynamic models with dynamic properties. This means the signature would be something like `PartialUpdate(string id, [FromBody] Dictionary<string, JToken> payload)`

**Comment by shesek** [comment]
> will be set to null as it was not found in the model, and the controller will accept it.

Couldn't the JSON parser tell you the difference between a field explicitly set to `null` versus a one that was not set at all, like JavaScript differentiates `null` from `undefined`?

If I understand correctly, this appears to resolve all the complexity you mentioned.

> You can say "screw this" and just set all properties to be updated and send them all but at this point, why even have partial updates then?

If you already have all the fields available on the client side, then I think its perfectly reasonable to issue a `PATCH` with all of them without checking which fields were changed, which is effectively the same as doing a full update.

**Comment by Kukks** [comment]
> 
> 
> > will be set to null as it was not found in the model, and the controller will accept it.
> 
> Couldn't the JSON parser tell you the difference between a field explicitly set to `null` versus one that was not set at all, like JavaScript differentiates `null` from `undefined`, or how Rust's serde differentiates a `None` from a `Some(Value::Null`)?
> 
> If I understand correctly, this appears to resolve all of the complexitiex you mentioned.
> 
> > You can say "screw this" and just set all properties to be updated and send them all but at this point, why even have partial updates then?
> 
> If you already have all the fields available on the client side, then I think its perfectly reasonable to issue a `PATCH` with all of them without checking which fields were changed, which is effectively the same as doing a full update.

You would still need to create the custom model or switch to a `Dictionary` on the server and then you map from the json body manually (instead of using the standard, recommended ways of ASP.NET Core).

**Comment by NicolasDorier** [comment]
@Kukks if I understand, you nightmare is only in the case where `null` and `not defined` are different concept. But do you have such example? For me a field set to null or undefined should be considered the same.

**Comment by Kukks** [comment]
> 
> 
> @Kukks if I understand, you nightmare is only in the case where `null` and `not defined` are different concept. But do you have such example? For me a field set to null or undefined should be considered the same.

Not one that I can think of right now, but I am 101% certain we will have that issue at one point and then force us to refactor the simplistic approach later on.

This is a VERY common issue with partial update apis, and everyone has their own take on how to handle it, which is why I prefer the much simpler full update way.

https://stackoverflow.com/questions/22160403/how-to-distinguish-between-null-value-and-value-not-provided-in-json-net

https://stackoverflow.com/questions/29024284/is-there-a-way-in-json-net-serialization-to-distinguish-between-null-because-no

**Comment by Kukks** [comment]
> 
> 
> For me a field set to null or undefined should be considered the same.

You can't: Undefined means don't update. Null means update it to null. C# nullable types don't have that distinction so you need a wrapper class like `PropUpdate<T>` or `Optional<T>`. Then you offload that added model complexity to either the server or the client. 

If you do it on the client, they have to deal with annoying json nesting that is different from the original model.
If you do it on the server, you need to create and register a JsonConverter to distinguish null and undefined and set `PropUpdate<T>` or `Optional<T>` correctly

**Comment by kmenashe** [comment]
IMHO, Handling property related update logic (if any at all) is more cleaner with  partial update

**Comment by Kukks** [comment]
> 
> 
> IMHO, Handling property related update logic (if any at all) is more cleaner with partial update

Can you elaborate?

**Comment by RooSoft** [comment]
According to REST guidelines, POST is usually used for resource creation. In most cases, its url shouldn't contain an ID and a new one should be returned.

To modify the whole resource, PUT should be used with the ID in the URL.

Lastly, PATCH is meant for partial updates, but in practice it is a mess. This is especially true when the resource contains arrays. In those cases, I tend to recommend sub-resources.

If you can't do with whole object modifications, it may mean that the resource should be split in smaller ones. In my experience, parting with partial modifications enables cleaner code on both back-end and client code.

**Comment by RooSoft** [comment]
> @Kukks if I understand, you nightmare is only in the case where `null` and `not defined` are different concept. But do you have such example? For me a field set to null or undefined should be considered the same.

Null means the client explicitely means nothing goes in that field. Undefined is an omission. It is harder to represent undefined in statically typed languages, which explains why programmers thend to consider them all the same.

**Comment by kmenashe** [comment]
> > IMHO, Handling property related update logic (if any at all) is more cleaner with partial update
> 
> Can you elaborate?

Just takking from my experience I had recently...say you have a property update that triggers some post update actions. If you have full input object, you need to figure out what property was change and act upon. Partial specifies the relevant properties so no need to identify them.
In addition, some times you don't have the entire object on the client, and partial will still allow you to update. Hope I am making sense here.

**Comment by Kukks** [comment]
If you're triggering some action based on a specific property change, you
still need to validate that the value changed in comparison to the old
value, so there is nothing gained in that regard.

I think it's much more likely that you would have the whole object on the
client, and if not, you can easily retrieve it before you update.

**Comment by NicolasDorier** [comment]
I think the partial update won, and I can understand some downside of it now.
Let's just use PUT instead of POST for update and continue what we do now, and later, if partial update needed, add a PATCH.
