### ISSUE TITLE
Allow localhost in store website

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#162]
![image](https://user-images.githubusercontent.com/1818366/39830220-09ebc4b0-53c1-11e8-9838-5d6127a1afea.png)

![image](https://user-images.githubusercontent.com/1818366/39830249-194ac366-53c1-11e8-9d34-b1329588ecfa.png)

Right?

**Comment by NicolasDorier** [comment]
wtf

**Comment by rockstardev** [comment]
It is definitely lolz: https://stackoverflow.com/questions/45707293/url-validation-attribute-marks-localhost-as-invalid-url

**Comment by NicolasDorier** [comment]
well we should just copy that.

**Comment by NicolasDorier** [comment]
Should work in latest version 2.1 though see https://github.com/JonHanna/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/UrlAttribute.cs they changed it.

**Comment by NicolasDorier** [comment]
No it does not work...
why in the hell ? https://github.com/dotnet/corefx/blob/release/2.1/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/UrlAttribute.cs

**Comment by NicolasDorier** [comment]
I tried to reference latest of https://www.nuget.org/packages/System.ComponentModel.Annotations/ ... no luck :/
