### ISSUE TITLE
Supporters logos /supporters page and restructuring the login page

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1624]
**Is your feature request related to a problem? Please describe.**
On the `Account/Login` we need to show logos of the higher-tier [supporters ](https://github.com/btcpayserver/btcpayserver-doc#supporters)and add some sort of `more` or `+` indicator that will lead people to supporters page where they are sorted by their tier level.
**Describe the solution you'd like**

- [ ] Remove LunaNode Logo from the `Account/Login`
- [ ] Remove Wallet of Satoshi Logo from the `Account/Login`
- [ ] Add `more` icon or something that will indicate that there are more supporters on a separate page
- [ ] Create `/supporters` page that will have some concise intro text and show all supporters with a link to https://btcpayserver.org/donate/

**Comment by Kukks** [comment]
For supporters page, i like the feel of this design

![image](https://user-images.githubusercontent.com/1818366/83517631-7d950c80-a4d9-11ea-8f58-8c76b8551247.png)
