### ISSUE TITLE
Add XMR.to Support to Conversions Tab or as "Monero"

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#163]
Monero is supported on Shapeshift, so this likely is not a big issue but some customers have indicated for some reason they like using XMR.to service more. 

XMR.to looks to have an API: https://xmrto-api.readthedocs.io/en/latest/

Since this is a service for "Shifting" only XMR to BTC, this would likely not work on stores who use only LTC or other coins. There might be other challenges as well. 

Putting this here for feedback and thoughts. 

Also putting the open issue for adding XMR support for reference: 
https://github.com/btcpayserver/btcpayserver/issues/160

**Comment by NicolasDorier** [comment]
I think it could work by adding one button below shapeshift.io if BTC is selected.

**Comment by NicolasDorier** [comment]
by using this service, how soon the payment is forwarded in BTC?

**Comment by astupidmoose** [comment]
> by using this service, how soon the payment is forwarded in BTC?

As per their website:
Note that a message might inform you that "Orders up to X BTC will be sent out instantly." This means that if you choose an amount smaller or equal to the amount X BTC shown, it will be processed instantly without even a confirmation. Larger orders require a confirmation (2 minutes on average).


I have no experience with Monero, so I would not be the best to answer or test. :P
