### ISSUE TITLE
SegWit inputs in PSBT must provide full UTXO

### ISSUE THREAD

**Issue by matejcik** [btcpayserver/btcpayserver#1631]
A security issue* in the design of BIP-143 allows an attacker to lie about segwit input amounts and get the user to pay an unexpectedly high transaction fee. The problem affects all HWW vendors.

For Trezor, we are fixing this by requiring the full UTXO for all types of inputs, so we can validate that the input amount is correct.

To facilitate that, we need BTCPay to provide full UTXOs for all input types.
This goes against the recommendation in BIP-174, saying that `NON_WITNESS_UTXO` should not be provided for SegWit inputs. Nevertheless, the resulting PSBT is still valid AFAICT.

Without this modification, it will be impossible to sign SegWit transactions on Trezor firmwares starting with 1.9.1 and 2.3.1. Also, an issue in HWI must be fixed first: https://github.com/bitcoin-core/HWI/issues/338

*) Details in our blogpost: https://blog.trezor.io/details-of-firmware-updates-for-trezor-one-version-1-9-1-and-trezor-model-t-version-2-3-1-1eba8f60f2dd

**Comment by Kukks** [comment]
So you're saying we need to include the full previous transaction for every input we want signed, even if it's segwit?

**Comment by matejcik** [comment]
that is correct

**Comment by NicolasDorier** [comment]
We can't support it, as we don't have the previous transaction in the case of restore.

**Comment by NicolasDorier** [comment]
Let me rephrase it: If all hardware wallet drop support for non_witness_utxo we have no choice but to remove hardware wallet support  in BTCPayServer and only support hotwallet.

This sucks, but we simply can't expect our users to maintain the full transaction index.

**Comment by NicolasDorier** [comment]
https://twitter.com/BtcpayServer/status/1268544252247715849?s=20

**Comment by NicolasDorier** [comment]
closing this as we can't fix it.

**Comment by prusnak** [comment]
Other option is to integrate Trezor via Trezor Connect

**Comment by Kukks** [comment]
If this firmware update forces users to use the "fix", users on BTCPay will have their funds locked. So I really, REALLY hope there is a way to turn off this breaking change new requirement. The vulnerability is a big edge case in a very unlikely event.

We do not use Trezor Connect for integration as it is a trusted third party.

**Comment by NicolasDorier** [comment]
No, they don't. We have direct hardware wallet support, most of our users use this.

**Comment by NicolasDorier** [comment]
I think this is unlikely this fix get implemented anywhere. The finalization steps of PSBT in libraries (and in bitcoin core) usually trim the non witness UTXO if it detect segwit.

I don't intend to change to change it in NBitcoin at this point. And even if I did, BTCPay Server could still not support it due to the lack of previous transactions, and the fact we don't want to rely on external services to fetch this data.

**Comment by NicolasDorier** [comment]
Tried to search in core code, did not found specific on that, so I am probably wrong on Core.

Found this in NBitcoin, I don't remember which test specifically it is referring to.
```csharp
		/// <summary>
		/// Check if this satisfies criteria for witness. if it does, delete non_witness_utxo
		/// This is useful for following reasons.
		/// 1. It will make a data smaller which is an obviously good thing.
		/// 2. Future HW Wallet may not support non segwit tx and thus won't recognize non_witness_utxo
		/// 3. To pass test in BIP174
		/// </summary>
                public void TrySlimUTXO()
```

For bitcoin core, any program depending on `utxoupdatepsbt` will not function with this new requirement.

**Comment by prusnak** [comment]
Thanks!

**Comment by AvivMilner** [comment]
Pardon my likely stupid question - could I simply move to a different hardware wallet (like Ledger) and restore that into Electrum? No signing problems, same derivation path. Would this work?

**Comment by Kukks** [comment]
> 
> 
> Pardon my likely stupid question - could I simply move to a different hardware wallet (like Ledger) and restore that into Electrum? No signing problems, same derivation path. Would this work?
> 
> Also, any solution that break privacy of my funds is off the table.

Yes, just restore the same seed from Trezor into Ledger and verify the addresses are the same.
Don't use Electrum if you want privacy. This is why we have a wallet built into BTCPay directly.

**Comment by AvivMilner** [comment]
@Kukks I should have clarified that I run my own EPS. There are no other privacy concerns correct? Should I be using the btcpayserver to move my funds?

**Comment by Kukks** [comment]
You might as well, it's one less surface you expose your funds and wallet data to.

**Comment by AvivMilner** [comment]
But when Wasabi in btcpay? Keep everything in one place.

**Comment by Kukks** [comment]
> But when Wasabi in btcpay? Keep everything in one place.
> 
> Thank you for your answers.

An issue for another day that I'm already looking into.

**Comment by AvivMilner** [comment]
Nothing but respect. Thank you!

**Comment by NicolasDorier** [comment]
@AvivMilner that said, I don't know Ledger stance on it. I don't think they will fix it as it breaks lot's of thing, but I may be wrong.

This is a difficult decision for hardware wallets.
