### ISSUE TITLE
If I leave AccountKeyPath blank and use my xPub from Blockchain to generate addresses what AccountKeyPath does it default to?

### ISSUE THREAD

**Issue by shishohf** [btcpayserver/btcpayserver#1632]
I have pretty much lost access to $2700 sitting and I can't remove them because although I have the mnemonic I left the AccountKeyPath blank and now I can't figure out what was used to generate the addresses in the first place.

I'm getting BIP84 addresses starting with bc1 which are bech32.

A AccountKeyPath of "m/0" would have been ideal but I don't think it's correct... When I leave the field blank and add the xPub to the store the 10 addresses shown from index 0-9 are completely different suggesting it's not the standard m/84'/0'/0'

I need serious help guys.

This xPub was generated from a wallet on Blockchain and I have my mnemonic so I should be able to get my private key for the wallets...

**Comment by Kukks** [comment]
When entering the xpub in the wallet config, there is a detection tool where you can put in one of your original addresses and btcpay will try to detect the format and keypath for you.

If the addresses match the ones you received on, but your balance is wrong, try the Rescan wallet feature (read the docs).

If the balance is there, you can spend using the btcpay wallet by signing with your seed directly.

Honestly not sure what you mean, you need to be more clear for us to help you better but it does not sound that this is btcpay related?

**Comment by shishohf** [comment]
I rescanned and it found 16 UTXO's. The balance is there but I can't send out. The format and keypath is not automatically detected, it's literally just left blank.

**Comment by shishohf** [comment]
The error is that my key path is incorrect.

**Comment by shishohf** [comment]
![Screenshot from 2020-06-03 12-07-25](https://user-images.githubusercontent.com/58644279/83660555-f99f5b00-a592-11ea-8c33-2ad79aae6839.png)

This is the error I get when trying to send out using my seed.

**Comment by shishohf** [comment]
Key path was blank from the get go. What would it have defaulted to generate valid addresses?

**Comment by britttttk** [comment]
@shishohf please provide more details about your situation.

1. How did you create the wallet? (generated from a wallet on Blockchain.com? be specific)
2. How did you create the wallet in btcpay? Import from existing seed & account 0, correct?
3. "$2700 sitting" sent to an address generated by your blockchain wallet or btcpay? 
4. "generated from a wallet on Blockchain and I have my mnemonic" Are you able to access your funds using your wallet generating software, it seems you have the seed words?

**Comment by britttttk** [comment]
Issue resolution can be found in the mattermost chat, related to legacy address vs. segwit.

**Comment by pavlenex** [comment]
[So solution provided on Mattermost](https://chat.btcpayserver.org/btcpayserver/pl/nnayh1gy1trbfbynbqoqzmnodw) (you must be a registered user on our chat in order to preview it).
