### ISSUE TITLE
  Lightning node does not respond in a timely manner

### ISSUE THREAD

**Issue by fstetter** [btcpayserver/btcpayserver#1635]
From time to time when i try to generate an invoice on my BTCPayServer (Point of Sale app). I get an error which says, the "Lightning node does not respond in a timely manner" (Screenshot). This only occurs sometimes, but when it does, it happens several times in a row until it works properly again.

![Screenshot 2020-06-05 at 13 55 06](https://user-images.githubusercontent.com/16136112/83878973-3d35c880-a73d-11ea-8d36-3163bbde9dea.png)

BTCPayServer is running on a Raspberry Pi 3b 
The Lightning Node is running on the same Pi

Any idea on how to fix this? Is this a known problem? I couldnt find any threads discussing similar behaviour.

**Comment by Kukks** [comment]
The Raspberry Pi 3b is a very under-powered device. The lightning node is probably crashing and restarting which explains your bursts of unavailability.

**Comment by fstetter** [comment]
I upgraded to a Pi 4 (4GB). Now its working fine. Thanks for the advice!
