### ISSUE TITLE
Feature request: Add possibility to allow/disable payment in store settings

### ISSUE THREAD

**Issue by hubiktomas** [btcpayserver/btcpayserver#164]
It would be great to have a possibility to enable or disable payment methods in the store settings while preserving derivation schemes and lightning nodes settings.

**Comment by Kukks** [comment]
Would also be great to extend this to an invoice level

**Comment by hubiktomas** [comment]
Extending this on an invoice level would be great. It could allow more UI options - such as selecting payment method before going to BTCPay.

**Comment by NicolasDorier** [comment]
If store and invoice settings are in conflict, who whin?

**Comment by hubiktomas** [comment]
I think that store settings should be some defaults with possibility to override it through invoice API.

**Comment by NicolasDorier** [comment]
It have been done by @Kukks  on https://github.com/btcpayserver/btcpayserver/pull/235
