### ISSUE TITLE
Make Vault Page a more informative and add retry

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1642]
**Is your feature request related to a problem? Please describe.**
The vault page which appears once you sign with a hardware wallet needs more information that will provide a brief info on what's btcpay server vault and have a retry button since very often in case of an error user is unaware that they have to refresh the page to try again.

**Describe the solution you'd like**

- [ ] Add retry button in case of an error?
- [ ] Add a bit more information on the vault (1 sentence with a link to vault page in our docs)

**Additional context**
![Capture](https://user-images.githubusercontent.com/36959754/84008443-2f1cbd80-a972-11ea-80e5-a5554f141a81.PNG)

**Comment by Carlos-MCV** [comment]
A retry button would be great!
