### ISSUE TITLE
Show recovery seed in a better way when creating a new wallet

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1645]
**Is your feature request related to a problem? Please describe.**
Currently, when you create a new wallet, recovery seed is shown on top of the Store Settings page, which can easily be disregarded. I've noticed that due to wallet incompatibilities, more users are now using `create a wallet`, that said we should make sure to educate them properly on the risks and create an UI that will make it clear that backup is crucial and that unless a hot wallet is used their seed is wiped out.

![Capture](https://user-images.githubusercontent.com/36959754/84124185-2643ee80-aa3b-11ea-8475-ca24bc505062.PNG)

**Describe the solution you'd like**
Create a separate page which will show first of all a short message like we have in [docs](https://docs.btcpayserver.org/CreateWallet/)

```WARNING
Securely back up your seed by writing it down and keep it in a safe place. Do not photograph it or store it in a digital format. When creating a wallet, the recovery seed will be shown only once and wiped from the server. If you loose your recovery seed, you'll lose the access to all of your funds.
```

**Provide examples**
![Seed](https://user-images.githubusercontent.com/36959754/84123840-ae75c400-aa3a-11ea-9e75-954e782c2230.png)

**Additional context**
I'd like to open this issue for a discussion. Perhaps we should consider having a seed confirm page to make sure users have properly backed up their mnemonic but also warn them about passphrases.

The separate page idea is because of the the changes in #1055 we plan to do eventually.
Opening this one for the future.

**Comment by Eskyee** [comment]
Perhaps we should consider having a seed confirm page to make sure users have properly backed up their mnemonic but also warn them about passphrases.

Yes I agree @pavlenex 
Very important for noobs to understand this seed confirm point. as they could lose their money in the future, if they forgotten.  
mnemonic, passphrases.

**Comment by dennisreimann** [comment]
I agree with @Eskyee and think having a separate page as proposed above is the way to go. This way we'd focus the users attention on the matter and would also have the attention and space to provide some more information around the topic (plus link to further information in the docs).

**Comment by pavlenex** [comment]
I agree with having a separate page for this one. Actually it seems this relates to #1703. 
It'll be quite a challenge to get this one right, but it's been pointed out to me that [user-experience Monero wallet has](https://www.figma.com/file/DplJ2DDQfIKiuRvolHX2hN/Monero-GUI?node-id=15%3A778) in regards to recovery seed backup is quite satisfactory, so we can definitely try to replicate similar process. 

Backing up a recovery seed will become an important step as I assume more and more people will go with `create a wallet` option rather than importing it from incompatible wallet and then facing common UX issues.

To go back to the point, here are some mockups that are quite solid UX, but I'd also leave space for designers and UX people here to suggest what's best course of action.

![showseed](https://user-images.githubusercontent.com/36959754/86372472-7d2b9500-bc82-11ea-978e-d02ffe14943f.PNG)

What I like about the example above is how it explains what's going on and why it's important. Just an idea.

**Comment by dstrukt** [comment]
Working on a couple of different things, but I want to start getting some screens up to discuss...

Also realizing I need to update our figma typography defaults and add a bit more subtly to our color palette for updated screens - will communicate to @dennisreimann 

<img width="1107" alt="Screen Shot 2020-07-04 at 10 14 11 PM" src="https://user-images.githubusercontent.com/6250771/86526074-148c1600-be44-11ea-968d-bb499af5f28c.png">

**Comment by Eskyee** [comment]
Nice & simple.. good job 👏

**Comment by pavlenex** [comment]
@dstrukt Great job on that one. I agree we have to update the fonts, really digging this font.

About the mockup ,one thing @GBKS told me, which is that headline `Write down your recovery phrase` gives clear CTA from start instead of `"Back up..."` Minor note , we only show 12 word mnemonic, not 24 😄 Looking forward to more mockups, especially on the "seed confirmation" front, this is great and clean starting point imo.

**Comment by bolatovumar** [comment]
Tested it locally and things look good. Good job @dennisreimann!

**Comment by dennisreimann** [comment]
I just pushed the pixels, this has been a great effort of everyone involved 😀👍

**Comment by dstrukt** [comment]
Indeed.

Enjoying the process!

**Comment by dennisreimann** [comment]
Merged, done, boom 🎉
