### ISSUE TITLE
EventAggregator.Subscribe<T>() doesn't handle events raised for child classes

### ISSUE THREAD

**Issue by rockstardev** [btcpayserver/btcpayserver#1657]
When you call `EventAggregator.Subscribe<NotificationEventBase>()` you would expect that events from all classes derived from `NotificationEventBase` are handled.

In practice, it doesn't work this way - you need to subscribe to each child class specifically in order for events to be raised.

**Comment by rockstardev** [comment]
@NicolasDorier @Kukks are we opting out not to do this?

**Comment by pavlenex** [comment]
Ping @NicolasDorier @Kukks what do we do with this one?
