### ISSUE TITLE
IPN (/invoices/ID?token= endpoint) not working

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#166]
With the merchant fascade it should be possible to query invoices with the API as done by the IPNlogger.php Script from the PHP API toolkit.

However I seem to alway get an empty response from the toolkit. Having tried the same request with Postman and setting Accept and Content-Type Headers to application/json I still get an html response.

Here is the output from my apache/php error log:
https://pastebin.com/fCtdRDgY

Is this API call not implemented or am I doing something wrong trying to get a json response for my invoice?

**Comment by NicolasDorier** [comment]
this API call is implemented and used by https://github.com/btcpayserver/php-bitpay-client

**Comment by petzsch** [comment]
I am using the official BitPay Toolkit (only changed the LiveNet URL to my server). Invoice creation works fine, but the IPNlogger seems to get invalid data for his GET request. Trying to put some more debug output into IPNlogger.

What stands out to me is the size of the response the nginx log reports:
pay.petzsch.eu 188.68.38.31 - - [11/May/2018:03:49:10 +0000] "GET /invoices/MwcFaC2UL7dKUU3p4KD5Bs HTTP/1.1" 200 12190 "-" "BitPay PHP-Client/2.2.20 (PHP 7.1.8)"

That doesn't look like a slim json response to me, more like a fat html one.

I'll update here once I found out how to dump the GET Response with the IPNlogger.

**Comment by petzsch** [comment]
Dumping $client->getResponse I get exactly what I suspected. Fat HTML Response: https://pastebin.com/uYFzF4fc

Any help with this is appreciated.

**Comment by NicolasDorier** [comment]
you need to add `Content-Type: application/json`

**Comment by petzsch** [comment]
Public and Private Keys are not added in the [IPNlogger](https://github.com/bitpay/php-bitpay-client/blob/master/examples/tutorial/IPNlogger.php), even when doing so there is no signature beeing sent in the GET request.

According to https://bitpay.com/api#resource-Invoices the endpoint (GET/invoices/:invoiceId) is "PUBLIC". I assume that no signature/auth information is required to query it.

Can you reproduce my problem on your end?

As an intermediate solution I'm considering to just go with the POST data I get from the IPN call and to protect the IPN endpoint via .htaccess (Allow/Deny). But not beeing able to query invoices is definitly a bug.

**Comment by NicolasDorier** [comment]
Do not go with the callback data. It is not authenticated.

I did not know the `invoices/id` call is public, I should fix this to make it public. (will be done for next version!)

If you set the private key to the bitpayClient it should pass. Can you try ?

**Comment by petzsch** [comment]
As I said I tried adding private and public key to the Client prior to making the request. The result is the Client->GetRequest() output I posted above.

Here is my modified IPNlogger: https://pastebin.com/ep3upJKw

**Comment by NicolasDorier** [comment]
I will release a new version in like an hour to make the method public. Should work with the credentials though.

**Comment by petzsch** [comment]
No hurry from my side. I am waiting for another issue I raised with my domain registrar and their payment integration api.

When I'm done integrating BTCPay Server with ResellerClub, I'll donate you some LTC for a beer or a coffee. Just message me an address to send it to. :-)

:heart: this project.

**Comment by NicolasDorier** [comment]
You can donate via BTCPay of course: https://main2-btc-ltc.forkbitpay.ninja/apps/Hoddr1KdzJcBf9MbhfXHziL1nnrtw7uMFWkZqL9Uhuyj/pos

**Comment by NicolasDorier** [comment]
ok, you can try again, now it should work in https://twitter.com/BtcpayServer/status/994952812193763333

**Comment by petzsch** [comment]
works. thx.

**Comment by NicolasDorier** [comment]
should we care? I don't see anything wrong continuing to provide it without auth.

**Comment by petzsch** [comment]
Could be a security/privacy thing. I don't know why bitpay implemented it the way they did.

I'm fine with closing the issue, since no one objected the current solution that we have.
Other than maybe putting an robots.txt in place to forbid access to the /invoices/* endpoint. :-)

**Comment by NicolasDorier** [comment]
I think closing this as the invoices are not enumerable without authentication. 
A `robot.txt` at the root of btcpay seems reasonable, but should be treated as separate issue.
