### ISSUE TITLE
"Back to the app list" opens new tab.

### ISSUE THREAD

**Issue by Zaxounette** [btcpayserver/btcpayserver#1661]
**Describe the problem/bug**
The 'Back to the app list' button opens a new browser tab which seens

**Your environment**
* Version of BTCPay Server: _v1.0.4.2_
* Deployment method: _Lunanode_
* Tested Browsers: _Chrome_ and _Firefox_.

**To Reproduce**
1. Go to `Apps`, 
2. Select the `Settings` of an already existing app
3. Scroll down to the very bottom
4. Click on `Back to the app list`
5. Get a new opened browser tab.

**Actual behavior**
When the `Back to app list` button is clicked, it opens a new tab.

**Expected behavior**
Two behaviors could be expected:
- If it's really a bug, I expect it to just send me back to the app list in the **same browser tab**, instead of opening a new one.

- If it was intentionally coded that way as to not loose any unsaved changes in the app settings, I would instead expect a popup or an error message of some sorts indicating that any unsaved changes will be lost.
And then it sends me back to the app list **in the same tab**.

**Screenshots/Links**
![Screenshot_54](https://user-images.githubusercontent.com/51208677/84542488-d8104300-acf9-11ea-8c69-93ca8eac4f09.png)

**Comment by britttttk** [comment]
I agree with @Zaxounette comments on expected behavior. I can also confirm it does open new tabs.
