### ISSUE TITLE
How to get store name from in Callback Notification Url?

### ISSUE THREAD

**Issue by ezhevak** [btcpayserver/btcpayserver#1668]
**Is it possible to get the name of the store in Callback Notification Url?**

**Comment by Kukks** [comment]
You can't, https://bitpay.com/docs/invoice-callbacks

Please don't use the notification callback as a trustful action. Anybody can fake one and send it to you to scam you.

**Comment by ezhevak** [comment]
Please tell me what can I use?
I want to receive information about the amount BTC and the name of the store?

**Comment by Kukks** [comment]
You should connect using the Bitpay compatible invoice API to see paymnt data related to an invoice, ( look for `cryptoInfo` object when you `get` invoice). https://docs.btcpayserver.org/CustomIntegration/

I cannot help you more than that.

The store name is not part of the invoice, but you should have the storeId when connecting with the bitpay api.
