### ISSUE TITLE
Coinswitch problem

### ISSUE THREAD

**Issue by 2ge** [btcpayserver/btcpayserver#1675]
Hi

I want to receive 10 USD, which is around 0.00121104 BTC, I integrated coinswitch...The problem is sometimes, for some currencies (ETH for example but there are much more) I am getting error:
```
Cardano: Sorry, you can not pay using altcoins as the payable amount is above 0.0028 ADA
Ethereum: Something went wrong. Please try again later
```

and so on. I checked developer console and it seems, they are not accepting the small amount of money, response is:

```
code: "min_limit_breached"
data: null
msg: "destination_coin_amount must be more than 0.001998"
success: false
```

so probably no fix, I am posting it for somebody who could have similar issue, so no need to debug...

**Comment by Kukks** [comment]
Yup, nothing we can do.
