### ISSUE TITLE
Allow Placeholders in redirectURL (i.e.: invoice-id, payment status, etc.)

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#169]
At the moment the redirectURL is presented after succesfull and expired invoices.
While not complying with the specification of the BitPay API documentation (only present on success), we could use it as a universal payment completion URL if we had placeholders in there.

Especially useful would be `invoice-id` and ´payment-status´ as placeholders to put anywhere in the redirectURL.

Extending the redirectURL with `{placeholders}` would not break API compatibility to BitPay, but yet would allow the payment completion page to respond to succesfull or unsucesful payments.

For reference, this has been discussed on [here](https://github.com/btcpayserver/btcpayserver/issues/165).

**Comment by petzsch** [comment]
second thought: maybe allowing payment status would be an invitation to manipulation. We should probably not offer that, better force devs to query the invoice via api to get the status.

**Comment by conando2000** [comment]
I can only second this request - my use case currently is using only direct links and the POS app plus my own little custom IPN to handle software licenses, no "real" shopping system is used which is working fine and so far I love it. However one big miss for me currently is that in this scenario I have now way of making a connection from the "thank you" / RedirectURL page to the particular order/invoice.

All thats needed for this to work for me is an option to somehow append the invoice ID to the redirect URL. Either with a placeholder like Markus mentioned (something like https://domain.com/checkout/thankyou?id={invoice_id}) or just with an on/off option to decide if the invoice ID is simply appended to the redirect URL (then I would put https://domain.com/checkout/thankyou?id= as redirectURL and enable that particular option)
Wouldn't break any backwards compatibility or anything and be a big plus for the POS app at least!

**Comment by Kukks** [comment]
There is a way to solve this:
When you create the invoice, set the orderId to a unique identifier of your choice. Then you can doc the redirecturl to `https://domain.com/checkout/thankyou?id=orderid` and you should be good to go without any changes from btcpay

**Comment by conando2000** [comment]
@Kukks Yes that would be possible if I would use some kind of checkout process etc. but like I said I'm mainly using the POS "app" only - with its integrated card. It handles everything and there is no way for me to "intervene" imho and add anything custom like this. It would be possible if I could change any invoice attributes from the IPN via REST API or similar but I didn't see any possibility of that either, so imho (optionally) adding the invoice ID to redirect URL would be the easiest and cleanest way of solving this.

**Comment by NicolasDorier** [comment]
Working on it
