### ISSUE TITLE
Onion-Location HTTP header wrong redirect

### ISSUE THREAD

**Issue by RiccardoMasutti** [btcpayserver/btcpayserver#1693]
**Describe the problem/bug**
https://github.com/btcpayserver/btcpayserver/pull/1634 enables the Onion-location HTTP Header. The problem is that right now it redirects subdomains mapped to apps to the .onion homepage of BTCPay.

**Your environment**
* Version of BTCPay Server:  v1.0.5.0 

**To Reproduce**
1. Add Domain to app mapping (Server > Policies)
2. Go to [dona.bitcoinsicurezzaprivacy.it](https://dona.bitcoinsicurezzaprivacy.it/) with Tor Browser
3. Enable the redirect to the .onion service
4. Check redirect

**Comment by dennisreimann** [comment]
Thanks for reporting, will fix this.

**Comment by NicolasDorier** [comment]
@dennisreimann  I am on it.

**Comment by NicolasDorier** [comment]
fixed in 1.0.5.2

**Comment by dennisreimann** [comment]
This morning @NicolasDorier also officially obsoleted me. Thanks. 😉
