### ISSUE TITLE
Protect the view sending /view seed with a user password or multi-factor authentication

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1697]
**Is your feature request related to a problem? Please describe.**
Opening this issue for a discussion. Is it useful to have a way of encrypting a hot wallet with a password?
Use-case: User uses a hot wallet feature and holds small amount because it's convenient to spend frequently from it via web browser.

I think that for certain use-case it's a good security practice, but I'm unsure if it gives a false sense of security, since in theory a keylogger could easily break it. However better encrypted than not?

My main concern is that most users who use a hot wallet feature are using it for Liquid/Payjoin, a very small portion of users would probably use a hot wallet for the sake of convenience of spending?

**Describe the solution you'd like**
When a hot wallet is selected, show password field (I wouldn't mix it with passphrase) and ask if user would like to encrypt it. We have to explain that when a wallet is encrypted, it manually needs to be decrypted every time before spending and that Liquid/Payjoin won't work if this option is enabled.

**Describe alternatives you've considered**
Not having a wallet encrypted.

**Provide examples**
I currently won't provide wrieframes, as this is opened for discussion for now.

**Comment by Eskyee** [comment]
Interesting 🧐 Pav, I agree with your point of view.. needs brain storming and future proof. For sure!

**Comment by pavlenex** [comment]
I've talked to @Kukks about this issue.

Here's what we came up with that may be possible.

A way to password protect to use the `sending /view seed`, either via user password or via 2FA/MFA. Kukks explained to me that encryption isn't possible this way as for encryption a key is needed, which now seems obvious but wasn't to me at that time.

**Comment by Kukks** [comment]
> I've talked to @Kukks about this issue.
> 
> Here's what we came up with that may be possible.
> 
> A way to password protect to use the `sending /view seed`, either via user password or via 2FA/MFA. Kukks explained to me that encryption isn't possible this way as for encryption a key is needed, which now seems obvious but wasn't to me at that time.

Let's wait for #1564

**Comment by bolatovumar** [comment]
Do we still want to do this? @pavlenex @Kukks 

Were we thinking that going to the "View seed" or "Send" pages would require a full re-login (possibly with 2FA enabled)?

**Comment by pavlenex** [comment]
Yes, I guess we should call this "restraining certain actions with 2FA". @Kukks may be able to post more on how and what we may want to secure with it.

**Comment by Kukks** [comment]
Yeah, still want to but we need to refactor things to make this fit in somehow. We need to:
* create an MFAService (aggregated 2fa and fido2)
* Have POST models for UI actions implement a specific interface (`IRequiresMFA`, which has props for providing 2FA code or FIDO2 response)
* Have some middleware that check post requests  and if it has a model that implements `IRequiresMFA`
* If it does, verify MFA details and proceed if valid, Forbidden if not

**Comment by pavlenex** [comment]
I'll close this one, there hasn't been much interest in it.
