### ISSUE TITLE
Crowdfund app doesn't count old invoices

### ISSUE THREAD

**Issue by RiccardoMasutti** [btcpayserver/btcpayserver#1698]
**Describe the problem/bug**
If you click `Count all invoices created on the store as part of the crowdfunding goal` under `Crowdfund` app, it doesn't count old invoices.
It counts only invoices created after enabling the option.

**Your environment**
* Version of BTCPay Server: v1.0.5.2

**To Reproduce**
1. Create a Crowdfund app
2. Send some sats to another app (eg. donation page)
3. Open settings of the Crowdfund app
4. Enable `Count all invoices created on the store as part of the crowdfunding goal`

**Expected behavior**
It should count old invoices,

**Comment by pavlenex** [comment]
Replicated, thanks for reporting.

**Comment by RiccardoMasutti** [comment]
With a lightning invoice paid from another app, it's updating only `Contributors` (while `Raised` stands still).
