### ISSUE TITLE
Lightning Publisher Application (Paywall)

### ISSUE THREAD

**Issue by 0xjacobb** [btcpayserver/btcpayserver#1705]
**Is your feature request related to a problem? Please describe.**
I would like to see a simple BTCPay application where I can set up paywalls to monetize blog articles or website content.

**Describe the solution you'd like**
**Describe alternatives you've considered**
There is this working code (https://github.com/ElementsProject/wordpress-lightning-publisher), which also works with WordPress in principle. But the installation is too complex for beginners and only available for c-lightning.

**Provide examples**
Here is an example (sorry I only have a German website which I know): https://coincharge.io/bezahlschranke-paywall-fur-wordpress-mit-lightning-zahlung/

**Additional context**
![btcpay_paywall](https://user-images.githubusercontent.com/32514554/86009634-bc57ad00-ba1a-11ea-8226-efa8c7fd0544.jpg)

**Comment by onleines** [comment]
The article is also available in english https://coincharge.io/en/portfolio/payment-per-newspaper-article-with-bitcoin-lightning/

**Comment by Kukks** [comment]
This kind of feature requires backend code so it is not straightforward to make a one-size-fits-all paywall. It's very simple code though:
* Create a pay button with a specific itemCode 
* User clicks, creates invoice, pays
* User goes back to your site, inputs paid invoice Id/Order Id (can be an automatic redirect)
* Your BACKEND (not frontend/javascript code, not secure and can be bypassed)  queries BTCPay and checks that the invoice is paid and displays content if yes

**Comment by pavlenex** [comment]
I made a video a while ago on how to set this up, https://www.youtube.com/watch?v=ZbM3jcxau0o you actually may want to post suggestions for improvements at [Lightning Publisher Repo ](https://github.com/ElementsProject/wordpress-lightning-publisher)their repo, for technical reasons Kukks outlined, this one won't be easy at all.

**Comment by dennisreimann** [comment]
If LSAT emerges as a standard it would be a nice addition to build an Aperture like functionality in. 😀

**Comment by 0xjacobb** [comment]
> I made a video a while ago on how to set this up, https://www.youtube.com/watch?v=ZbM3jcxau0o you actually may want to post suggestions for improvements at [Lightning Publisher Repo ](https://github.com/ElementsProject/wordpress-lightning-publisher)their repo, for technical reasons Kukks outlined, this one won't be easy at all.

Thanks @pavlenex , I've missed that

**Comment by onleines** [comment]
The video was inspiration for me to rebuild a corresponding page. A great solution.
Unfortunately with the disadvantage that it only runs under clightning and has its own checkout process.   

It would be great if there would be a solution from BTCPay that would support both Lightning instances and maybe further developments like LSAT.

Also the BTCPay Checkout Process. 

But maybe it would be a Wordpress application based on BTCPay with Lightning (LND & Clightning).

There are a few comparable solutions with other crypto currencies. Satoshipay for example based on Stellar https://wordpress.org/plugins/satoshipay/#description

There you can charge not only texts but also video, audio, pictures and downloads within Wordpress.
![satoshipay](https://user-images.githubusercontent.com/22472943/86231153-6148c600-bb92-11ea-948f-27b3906f4b15.png)

There are already a few issues here that go in a similar direction:
https://github.com/btcpayserver/btcpayserver/issues/300
https://github.com/btcpayserver/btcpayserver/issues/1173

Maybe it's more a further development of the existing Wordpress plugin?

**Comment by pavlenex** [comment]
Personally I don't think BTCPay should try to solve issues like this. There's an existing solution that can further be improved and modified, so I recommend you guys post this there. Happy to leave this issue opened for discussion and if someone wants to create such solution in the future, but chances of that happening on btcpay's end are very slim imo.

**Comment by Eskyee** [comment]
https://github.com/ElementsProject/wordpress-lightning-publisher & WooCommerce 
@pavlenex I use this wordpress-lightning-publisher very regularly, for audio & video over the years, works solid every time. with **c-charge & lightning**,  takes time to figure out & customise the css, very geeky, I love it ;) jaja

**Comment by pavlenex** [comment]
Closing this as there's a plugin already that allows this. Happy to re-open if there are more requests, but for now this is not our priority. 
Perhaps @shesek would like to enable LND in LN publisher.
