### ISSUE TITLE
Multiple selection and batch action of invoices on the invoice page

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1709]
**Is your feature request related to a problem? Please describe.**
In 1.0.5.0 we've added a way to select multiple notifications on the notifications page and perform a batch action. I think that this can be handy thing to add for invoices as well.

**Describe the solution you'd like**

- Add a way to select multiple invoices 
- Add a way to perform a batch action
- Add archived invoices as an action

**Provide examples**
![invoices](https://user-images.githubusercontent.com/36959754/86288042-8ddbfc80-bbe9-11ea-8c8e-8fd33622fee7.PNG)

**Additional context**
Personally I couldn't remember any actions besides `archive` that would be useful for this, perhaps a `refund` but at this point it's probably too complex and I'd let refunds get a bit more feedback from users first.

**Comment by NicolasDorier** [comment]
I did it for payouts. Easy enough in Javascript.

![image](https://user-images.githubusercontent.com/3020646/86314833-9ec95400-bc63-11ea-96c2-2c3d79dd922b.png)

**Comment by bolatovumar** [comment]
I can take a look into doing this.

**Comment by Kukks** [comment]
Take a look at the notifications list, there is no JavaScript required or
else it falls back gracefully.

**Comment by pavlenex** [comment]
@Kukks While we're at it, would be cool to have `select all` otherwise batch is not that useful if user has to click on the notifications to get them selected. New issue?

**Comment by bolatovumar** [comment]
> @Kukks While we're at it, would be cool to have `select all` otherwise batch is not that useful if user has to click on the notifications to get them selected. New issue?

How about I make it the same as what @NicolasDorier did in the Payouts screen (the screenshot he posted above)?

@pavlenex do you think we should just add a single "Archive" button OR an "Actions" dropdown with just a single "Archive" action for now OR merge the "Export" dropdown into the "Actions" dropdown so we have three buttons in it.

![Screen Shot 2020-07-14 at 7 14 55 PM](https://user-images.githubusercontent.com/1934678/87495647-bced6780-c606-11ea-8670-f3b58ee81582.png)

**Comment by pavlenex** [comment]
@bolatovumar Late to the party since this already got merged. I'll open a new issue for notifications.

**Comment by bolatovumar** [comment]
@pavlenex emperor @NicolasDorier says YOLO and clicks merge. Feel free to open any issue relating to this for updates/improvements. I will try to look into them as I have time.
