### ISSUE TITLE
Confirm E-Mail Link is broken

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#171]
According to @rockstardev there is an issue with rendgering in .NET Core 2.1 that breaks the Confirm email page.

Here is his proposed fix: https://forkbitpay.slack.com/archives/C6PSCRFAM/p1526064331000702

The exception that I got:
https://pastebin.com/EaiV29fa

**Comment by rockstardev** [comment]
Yeah, I'm not 100% that it has to do with .NET Core 2.1 - but it is definitely this line of code: https://github.com/btcpayserver/btcpayserver/blob/26db946392927c3387cd9d263717f6fbf41bf054/BTCPayServer/Views/Account/ConfirmEmail.cshtml#L10

**Comment by NicolasDorier** [comment]
released 1.0.2.17 to fix it
