### ISSUE TITLE
Login page re-design

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1710]
**Is your feature request related to a problem? Please describe.**
I know we've recently re-designed our login page, but I think we can still do a better job on making sure it is consistent with our [design guidelines ](design.btcpayserver.org/).

**Describe the solution you'd like**
The login page on BTCPay Server is the front page user sees before logging in. It appears even before user creates an account. The goal of this page is to:

- Have a clear CTA (user needs to create an account / log in to access BTCPay)
- Welcome user and explain concisely what BTCPay Server is
- Show prominent supporters of the BTCPay Server Foundation and link for the rest
- If Tor is enabled, we'd like to show .onion access link (currently the way we show it may not be clear enough for regular folks at all, luckily if user already accesses btcpay over Tor [we'll notify them via Tor Browser](https://pbs.twimg.com/media/Ebj7QWNVcAAziAD?format=png&name=medium))

Problems with current login page:
- If user does not have an account, `create account` is not that prominently displayed (I've seen users asking questions about this one)
- Tor .onion url may seem confusing for those unfamiliar with it
- forgot password page does not look consistent with login page
- Page looks all over the place, it  could use some consistency and cleanup (imo)

**Current login page design**
![login1](https://user-images.githubusercontent.com/36959754/86332497-e4c5ee00-bc4a-11ea-82b2-3fb06b2b7714.PNG)
![login2](https://user-images.githubusercontent.com/36959754/86332740-379fa580-bc4b-11ea-8b89-a0c86076431f.PNG)
![forgot your password](https://user-images.githubusercontent.com/36959754/86332765-3e2e1d00-bc4b-11ea-93e8-35d5c2e1b19e.PNG)

**Provide examples**
There are mockups of different [iterations of the login page on Figma. ](https://www.figma.com/file/C7Xyq0FlxgFW8vaBr8ht1z/BTCPAY)

![login](https://user-images.githubusercontent.com/36959754/86332060-3c178e80-bc4a-11ea-87c1-d3cc73fa8c07.PNG)
![login2](https://user-images.githubusercontent.com/36959754/86332063-3d48bb80-bc4a-11ea-8b95-f31ce01fe8b6.PNG)

Another thing, is that login page is available for several themes, while we don't need design for several themes, it's good to keep that in mind.

![casa](https://user-images.githubusercontent.com/36959754/86332894-6fa6e880-bc4b-11ea-870a-db105a0cc354.PNG)
![classic](https://user-images.githubusercontent.com/36959754/86332900-703f7f00-bc4b-11ea-9488-ce1e4a060d62.PNG)
![dark](https://user-images.githubusercontent.com/36959754/86332903-7170ac00-bc4b-11ea-9aa6-432fd414c7fc.PNG)

**Additional context**
Designer interested in tackling this should create mockups on Figma so that devs can easier implement it. Examples above are just for the reference purposes, feel free to be creative and provide your own solutions. I am particularly interested in how we can show that .onion url in a more clear way to those who need it, yet avoid confusing those who don't need it.

One thing you shouldn't forget is that front page should provide a certain sense of accomplishment. Lots of people like that celebratory moment when they deploy their BTCPay Server. It would be really good to have it all above the fold, so that supporters are visible as well.

**Comment by Eskyee** [comment]
I kind of like the front page we have, and think their are much more important things to be done, around BTCPay Server.  Just my opinion. @pavlenex

**Comment by dennisreimann** [comment]
I think the main thing we can do to provide more clarity is using a one column layout as shown in the first mockup screen. This would also help making it more consistent with the forgot password page  

>  If user does not have an account, create account is not that prominently displayed 

By display the content in one column and maybe making the register option a secondary button this could be solved already. 

> Tor .onion url may seem confusing for those unfamiliar with it

With the recent addition of the Tor Location header I think we can streamline this: If Tor is enabled for the instance leet's just display the onion (wrapped with a link) and hide the address (or reveal it on click on the onion). Those who care would open the page in Tor anyways and this way wee could prevent confusing people who don't know what this is about.

> Page looks all over the place, it could use some consistency and cleanup (imo)

I'd move the supporters to the bottom – or if possible maybe just put them on the homepage. I don't know about the details that were agreed upon, but from a users perspective this looks like ad space.

**Comment by pavlenex** [comment]
I'm with you Dennis regarding Tor. Location headers are great. 
The entire page needs to fit in above the fold. Supporters need to be visible above the fold on destkop at least. Logos need to stay there, in a way it is an ad space.

**Comment by dstrukt** [comment]
I'm excited to see these as actual issues, not just my work sitting in Figma!

1. Tend to agree the supporters need to stay above the fold, but the single column is a lot cleaner. I'm sure there's a compromise to find.
2. Have some ideas to make Tor better, agree with Dennis' suggestions.

I'll revisit this screen in Figma this week.

I'm currently writing up feedback for a lot of stuff in terms of implementation, but been busy.

**Comment by dstrukt** [comment]
<img width="1074" alt="Screen Shot 2020-07-04 at 11 48 50 PM" src="https://user-images.githubusercontent.com/6250771/86527177-48216d00-be51-11ea-991b-95f4a76b27b6.png">
<img width="1373" alt="Screen Shot 2020-07-04 at 11 49 47 PM" src="https://user-images.githubusercontent.com/6250771/86527194-7141fd80-be51-11ea-8ef4-924285085020.png">

Also explored some options.. i couldn't resist even though there's a lot more to do.

The supports would be limited a row of five, but each would cycle through subtly, will provide an animation as well.

**Comment by dstrukt** [comment]
Still experimenting, and will invert them when I feel more strongly about one direction.

**Comment by pavlenex** [comment]
@dstrukt I like the direction in which we're going with these. @dennisreimann had a very similar idea, and it also fits in with what I though would be the best, so glad we're on on a same(similar) page on that one.
If you take a look at #1712 you can see Dennis' progress there. What I like in this mockups is `Open in Tor Browser` which is a great and clear CTA unlike the onion icon we had. Still, if you look into Dennis' PR you'll see that we can even consider ditching that one. Dennis  created a button for `Sign up` and `Log in` which I think is clearer than a link, so maybe you want to consider that.

Only thing that I feel is missing is names of supporters and their links. I know this ruins the cleanness of the page, but most of our supporters aren't brands you can recognize just by looking at a logo imo.

As far as the layout goes, I'm leaning towards centered layout, `Demo Signup Alternate`

**Comment by bolatovumar** [comment]
Agree with @pavlenex about the missing links and text for the sponsor logos. Also, I would imagine sponsors would want their logos showing up above the fold rather than below the sign-up form (but I'm not 100% sure).

**Comment by dennisreimann** [comment]
Incorporated the feedback in my PR and posted [some new screenshots](https://github.com/btcpayserver/btcpayserver/pull/1712#issuecomment-657750646). If it fits the direction we want to go towards, let's work out the details in #1712.

**Comment by pavlenex** [comment]
#1752
