### ISSUE TITLE
incorrect responce using API greenfield v1

### ISSUE THREAD

**Issue by ezhevak** [btcpayserver/btcpayserver#1714]
**Hello i tried to get app or store information by invoice Id.**

First of all using postman i tried to get store information by Store Id (example https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Stores_GetStores)

https://xxxxxxxx.lndyn.com/api/v1/stores/FgBNhPgNEdHW7564J3HgMyzDxSdhP4D5d1X19Mr

In response a get not all information, only two parameters.

{
    "id": "FgBNhPgNEdHW7564J3HgMyzDxSdhP4D5d1X19Mr",
    "name": "Main Store"
}

In example response must contain
[
{
"name": "string",
"website": "string",
"invoiceExpiration": 900,
"monitoringExpiration": 3600,
"speedPolicy": "HighSpeed",
"lightningDescriptionTemplate": "string",
"paymentTolerance": 0,
"anyoneCanCreateInvoice": false,
"showRecommendedFee": true,
"recommendedFeeBlockTarget": 1,
"defaultLang": "en",
"lightningAmountInSatoshi": false,
"customLogo": "string",
"customCSS": "string",
"htmlTitle": "string",
"redirectAutomatically": false,
"requiresRefundEmail": false,
"networkFeeMode": "MultiplePaymentsOnly",
"payJoinEnabled": false,
"lightningPrivateRouteHints": false,
"id": "string"
}
]

Please provide me example to get store or app information using Invoice Id.

**Comment by Kukks** [comment]
You are not on the latest version.

**Comment by ezhevak** [comment]
Tell me, is it possible to do the following?
I want to get information about Application or Shop using Invoice Id?
Maybe you have some examples?

**Comment by Kukks** [comment]
We don't support that yet.

**Comment by ezhevak** [comment]
You don’t support “API greenfield v1”?

**Comment by elvece** [comment]
also curious if the greenfield API v1 docs are up to date? I am not able to access my store's payment-requests based on these [docs](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/PaymentRequests_GetPaymentRequests).

**Comment by pavlenex** [comment]
@ezhevak What is documented on https://docs.btcpayserver.org/API/Greenfield/v1/ is supported, but as mentioned make sure you're running the latest version of btcpayserver. Also whatever is not documented is not supported yet.

**Comment by ezhevak** [comment]
Hello @KukksPlease tell me what should I use in order to use the data in the Callback Notification Url to get data on the app or store
Thanks in advance.

**Comment by Kukks** [comment]
> 
> 
> Hello @Kukks Please tell me what i should to use. I want to use event and data from "Callback Notification Url" and i need to get Application Name or Shop Name from BTCPay Server.
> 
> Thanks in advance.

The invoice api you are using is not part of GreenField APi and is only meant to be used with the payment button (officially). We do not recommend you use that and instead use the Bitpay compatible API.

You cannot get the store or application name from the callback event (IPN) and actually, you should only use the invoice id or order id from it and fetch the data via the Invoice API as anyone can fake a call to your public notification url and attempt to scam you.

We are planning a new invoice api to go with GreenField which streamlines all this.
