### ISSUE TITLE
Re-design Payment Request page and Pull payment page

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1719]
**Is your feature request related to a problem? Please describe.**
This issue is about re-designing payment request and pull payments page to look a bit more user-friendly and consistent with our design guidelines. These pages in current form aren't bad, but it would be cool if we can enhance them even further. Layout redesign is also acceptable course of action, not just aesthetics.

### Payment Request

In BTCPay Server, there are a few ways ways to request a payment. One is traditionally by to manually create an invoice. Second is to use one of the apps we have like Point of Sale or Crowdfunding. Payment requests is yet another way to request a payment, but with a difference that it always provides a current rate to avoid volatility problems. 

Think of it as a payment link, where a freelancer can send to a person who hired them and get paid in BTC. Payer can then click on that link, generate an invoice at current rate and pay. 

You can learn more about payment requests if you read [docs ](https://docs.btcpayserver.org/PaymentRequests/)or better yet [watch a video](https://youtu.be/j6CvwDPvfzQ).

![paymentrequest](https://user-images.githubusercontent.com/36959754/86791069-6feb1d80-c069-11ea-96ee-3119ab683d23.PNG)

### Pull Payment

Pull payment is the opposite concept of payment requests in a way. It's made for the receiver to provide information for the payment (amount + address) so that merchant can claim a payout to them (refund).

![PULLPAYMENT](https://user-images.githubusercontent.com/36959754/86791087-77122b80-c069-11ea-9442-e0735e4d4a76.PNG)

You can learn more about pull payments requests if you read [docs ](https://docs.btcpayserver.org/PullPayments/).

**Describe the solution you'd like**

1. Discuss the layout and if we can improve it
2. Create a mockup in figma
3. Based on mockup developers will be able to improve the pages

**Additional context**
Unfortunately the naming of these two concept is confusing probably. Furthermore the UX for the Pull Payments is still new and we're trying to perfect it. If anybody has ideas on how to improve the workflow please open up another issue, for this issue in particular it would be good to focus on a smaller chunk - design of the pages themselves where people could pay or provide info to get paid.

**Comment by dstrukt** [comment]
Few suggestions moving forward for making UX/UI tickets for more complex views (even though this is relatively simple)

1. If it's possible to do a screen capture of the interaction (via QuickTime on Mac, etc..) to capture more than a static mock. I know it's a slight bit more work, but I think it will help push discussion further :)
2. Additionally, if a screen capture isn't possible, a simple flow could also potentially suffice.

I have quite a few ideas for this, but I'm trying to stay focused on the dashboard at the moment, and will circle around to this when I get the chance.

**Comment by dstrukt** [comment]
Still experimenting with a few iterations, but came to a stopping point tonight, so I thought I'd share the progress.

I've asked some questions directly to @pavlenex to clarify functionality, etc.. so a few more changes will be made regardless.

Any feedback is welcome.

![Exploration](https://user-images.githubusercontent.com/6250771/88253153-be054100-cc65-11ea-9c98-d8f9961b8c8e.jpg)

**Comment by pavlenex** [comment]
I like the suggested layout for Payment requests. Looks certainly cleaner. Don't have any concrete feedback since it's WIP still it seems. Perhaps we should discuss adding additional CTA "Pay invoice" at the bottom of the screen, center, for those who scroll but miss the CTA in top right, but this is not something essential and just an idea.

>  experimenting a bit more with the due / paid / remaining view. I think it could be simplified a bit more

I agree with this one.

**Comment by dstrukt** [comment]
Has anyone ever requested a "share" button or "copy link" feature?

I suppose it's very easy to just copy the URL to send to someone -- curious.

**Comment by NicolasDorier** [comment]
@dstrukt wow I love the redesign! I can't wait. Nobody requested that as far as I know, but I think it should be very useful.

**Comment by pavlenex** [comment]
I like the copy/share button idea.
@dstrukt Since CTA is important, I'm thinking if it would be worthwhile to explore the idea of a sticky header so that pay is always in the field of view and same goes for claiming with pull payments, just another idea, really digging these designs.

**Comment by dstrukt** [comment]
@NicolasDorier Thanks, glad you like where it's going!

@pajasevi I love that idea! Can explore it via Figma's prototyping and post a quick animation (for whoever builds it out) as we wrap up this ticket.

**Comment by dstrukt** [comment]
Haven't changed much, just wanted to show an animated mock with a fixed header.

![PaymentRequest_1](https://user-images.githubusercontent.com/6250771/89049083-90736400-d305-11ea-8ea5-cda5357da49e.gif)

Feedback welcome!

**Comment by Eskyee** [comment]
Awesome.

**Comment by dennisreimann** [comment]
Is this ready to be worked on or are there still things that need refining?

**Comment by dstrukt** [comment]
It's ready to be worked on! 

There's one last issue I wanted to make sure I ironed out on the mobile view to be sure both will degrade well.

@dennisreimann I'll share the designs with you via MM (if you're going to take up the task), and we can iron out any remaining concerns, then I'll share what we settle on here.
