### ISSUE TITLE
Confirmation E-Mail on expired invoice missing + make notification emails customizable

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#172]
I've just tested email notifications with my freshly confirmed email address and don't seem to get one for an expired invoice.

As I understand the `fullNotifications` flag (which is set by the php toolkit by default) such emails should be sent. Not sure how BitPay handles email notifications for expired invoices. I guess it keeps the noise rate down to not send them.

Open to disscussion on that one. :-)

However if notification emails get sent (i.e. for payed/confirmed invoices - haven't tested yet) they should be customizable by the server admin.

**Comment by NicolasDorier** [comment]
No email will be sent. I plan to make more flexible option to decide what to do when an invoice state change through ifft integration later on.

**Comment by pavlenex** [comment]
e-mail customization can be done via [btc-transmuter](https://github.com/btcpayserver/btcTransmuter), so closing this one.
