### ISSUE TITLE
Let people choose custom currency

### ISSUE THREAD

**Issue by RiccardoMasutti** [btcpayserver/btcpayserver#1722]
It would be fantastic to allow people to manually choose the currency (in addition to the amount, which is already possible).

This is very useful especially for crowdfund apps and donation pages

**Comment by britttttk** [comment]
@RiccardoMasutti just want to mention a temp solution for now, you can use the item description to link to another store with a different currency.

**Comment by pavlenex** [comment]
@RiccardoMasutti  Which specific part of BTCPay are you referring to? This is already possible in invoice. 
It seems to me it's about the payment button or? Please don't ignore issue template when opening a feature request.

**Comment by RiccardoMasutti** [comment]
> @RiccardoMasutti Which specific part of BTCPay are you referring to? This is already possible in invoice.
> It seems to me it's about the payment button or? Please don't ignore issue template when opening a feature request.

Yes, I'm talking about pay buttons, like the ones in the crowdfund/pos app

**Comment by pavlenex** [comment]
Ok, please update your original post by following the issue template and providing examples of what in particular you'd like so it's clear to whoever is interested in tackling this.

**Comment by pavlenex** [comment]
Closing this for now so we can focus on other issues until more context is provided.
