### ISSUE TITLE
Pull Payments style consistency

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#1726]
**Describe the solution you'd like**
Make pull payments page more similar to the other `create` pages.
These are my suggestions: 

1. Left align the create pull payment button
2. Remove large text copy and replace with a tool tip to http://docs.btcpayserver.org/PullPayments
2a. Tool tip is normally on the right side of the create button
3. Reduce `Start` column width
3a. Remove extra space after DateTime and before `Name` column
4. Make the `View | Payouts | Archive` more similar to the other list view pages 
4a. I propose `View - Payouts - Archive`

Photo example of Apps list view and Pull Payments list view for comparison below. 
![image](https://user-images.githubusercontent.com/39231115/87008590-39a0c180-c181-11ea-871b-96399e81e3a3.png)

![list-view-layout](https://user-images.githubusercontent.com/39231115/87008603-3efe0c00-c181-11ea-8739-708b948abcbe.PNG)

**Comment by britttttk** [comment]
Also as a small nit, the max characters for pull payment name will overflow into second row for any theme besides classic.
![image](https://user-images.githubusercontent.com/39231115/87010439-cc426000-c183-11ea-9f64-a0664bee81fd.png)

**Comment by bolatovumar** [comment]
Addressing these issues in #1733.

**Comment by pavlenex** [comment]
#1733
