### ISSUE TITLE
Fix gap limit issues

### ISSUE THREAD

**Issue by Giszmo** [btcpayserver/btcpayserver#1728]
**Is your feature request related to a problem? Please describe.**
As [documented here](https://docs.btcpayserver.org/FAQ/FAQ-Wallet/#missing-payments-in-my-software-or-hardware-wallet), BTCPayServer does not play well with many light wallets and suggests to expose the seed to other software and potentially other hardware to resolve the issue.

**Describe the solution you'd like**
Please provide an option, maybe even default, that introduces a tiny bit of address reuse for the sake of trust in not having lost donations. Please resort to address reuse if the 20 address gap limit is soon to be exceeded and long expired invoices are available.

**Describe alternatives you've considered**
Please show address indices and addresses the user would have to send funds to, to help his wallet find the funds. The transaction list only shows txids but not address index or full list of addresses.

**Comment by Kukks** [comment]
There are no lost donations, only wallet software that cannot see them.
Reusing address causing many dangerous side effects, such as having 2
customers being able to lay claim that a payment was made to their own
individual invoice or allows for a malicious user to spam invoices and
expose previous payment data to them.

I think we can start displaying indexes, and also a tool to generate the
specific private key if you input a seed.

**Comment by Giszmo** [comment]
I understand your concerns and see how my solution 1 won't be the default ever but funds received to a non-standard address are lost to the user and need to be addressed somehow. As laid out in the documentation, wallet software usually follows the standard with a gap limit of 20 and while you claim that funds are not lost if you send beyond that, what if you send $1 to an address 120000 beyond that? It will cost more checking all the balances than that $1.

Does btcpayserver have any gap limit at all? I see good reason not to have one.
I bet this issue is something many people fall for and constantly comes up especially given [this issue](https://github.com/btcpayserver/btcpayserver/issues/924) which needlessly produces more gap for invoices that get paid. May I propose yet another solution?

BTCPayServer should send dust to addresses to make sure gaps can be bridged by standard BIP44 wallets. Should gaps build, show the user a red warning and assist him in filling gaps, ideally by bridging them with dust. The user might have to put a small amount into the btcpay hot wallet for that.

**Comment by pavlenex** [comment]
@Giszmo That's been considered, but to do this, a hot wallet needs to be enabled. To use a hot wallet, you need to generate a wallet inside BTCPay so it defeats a whole purpose, since gap limit is only the issue with external wallets.

**Comment by Giszmo** [comment]
I understand that but there is a difference between trusting the hot wallet with those hundreds of bitcoins I receive every day and trusting it with $12 for occasional gap closures.

**Comment by Giszmo** [comment]
The main thing is that while I might be able to work around this, my first assumption was that the btcpayserver was hacked and somebody swapped out the xpub. And I'm maintaining a big wallet with gap limit 20 myself, so how do you think the usual user who never heard of gap limit before feels at that point. Tell him there is a problem when there is a problem. A big red warning and a way out of it. Going off BIP44 standard derivation addresses is a problem for most users.

**Comment by pavlenex** [comment]
> trusting it with $12

It's not about funds it's about UX, this is bad UX that most people won't know or understand. There's no need to complicate things if people are using our internal wallet. We only recommend wallets with configurable gap limit in our documentation anyway.

**Comment by Giszmo** [comment]
> Ok, please suggest where specifically, when and how would you show this warring in the UI.

I would put a red exclamation mark next to every balance that comes to be exceeding the bip44 gap limit, linking the information mentioned above if an assistant to fill the gaps is not going to happen.
Users should be able to permanently dismiss this, if they use wallets with gigantic gap limit.

(And yes, gap limit is a terrible thing but I haven't heard of how it could be avoided short of re-using addresses or maintaining a list of indices or addresses like bitcoind in the old days.)

**Comment by Kukks** [comment]
I'll do a PR to start displaying address indexes and we can discuss that.
The easiest fix is to use the recommended documented wallets or to use the
internal wallet.

You don't need to store your seed in BTCPay and can just input it when
signing a transaction. Even better, create a separate wallet for btcpay and
use our third party plugin to forward the funds periodically to your own
wallet.

We won't do address reuse as it requires a bunch of dangerous changes with
dangerous assumptions.

**Comment by pavlenex** [comment]
Concrete discussion continuing in #1806
