### ISSUE TITLE
Improve the look of the "Pull payments" table

### ISSUE THREAD

**Issue by bolatovumar** [btcpayserver/btcpayserver#1732]
**Is your feature request related to a problem? Please describe.**

Pull payments table looks awkward

![Screen Shot 2020-07-11 at 8 54 12 PM](https://user-images.githubusercontent.com/1934678/87238594-5c1d1f80-c3b9-11ea-8265-8739d6de2fbb.png)

**Describe the solution you'd like**

Make it looks less awkward

**Describe alternatives you've considered**

Do nothing and enjoy life.

**Comment by dstrukt** [comment]
I can easily format this to look good, but was curious to know the context, as I'm trying to build a consistent components for all tables, etc..assuming it makes the most sense to have this displayed as a table still.

**Comment by dstrukt** [comment]
As for the table format,

Name > Start (could use a better label) / Created / Created At > Refunded > Actions

With the first three aligned left, and the actions far aligned right.

Do we need any additional information added to the table?

**Comment by pavlenex** [comment]
@dstrukt It's okay to mock it up, but #1719 is priority for pull payment design, so perhaps start there if you have the time, we can easily clean up the interface later.

**Comment by bolatovumar** [comment]
@dstrukt see this for the PR: https://github.com/btcpayserver/btcpayserver/pull/1733#issue-447847623
