### ISSUE TITLE
Zap lightning invoice works but btcpayserver invoice gives no payment route error

### ISSUE THREAD

**Issue by chippsmith** [btcpayserver/btcpayserver#1739]
I set up a Btcpayserver using the one click Lunanode option a few days ago.  I set up zap iOS wallet to manage the lightning node.  I set up four channels and spent some sats to get some inbound liquidity.  I created an invoice using Zap and was able to pay it using strike.  However, when I try to pay a lightning invoice created by the Btcpayserver using strike I keep getting no payment route found error.  I have tried multiple times for multiple amounts smaller than my total inbound liquidity and each time I am able to pay the invoice created by Zap but not the invoice created by Btcpayserver.  

Any help in troubleshooting would be greatly appreciated.

**Comment by pavlenex** [comment]
We use Github only for bug reports and feature requests. For general support like this, pleas ask on chat.btcpyserver.org Most likely you need incoming capacity from another node try lnbig.com

**Comment by chippsmith** [comment]
thanks
