### ISSUE TITLE
Select all notifications

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1743]
**Is your feature request related to a problem? Please describe.**
Currently we don't have a way to select all notifications like we have for payouts or invoices.

**Describe the solution you'd like**
Add select all button to the notification page so that user can select all notifications on that page and perform a batch action.

**Provide examples**
Example 1 https://github.com/btcpayserver/btcpayserver/issues/1709#issuecomment-652767312
Example 2 https://github.com/btcpayserver/btcpayserver/issues/1709#issuecomment-658505731

#1709

**Comment by bolatovumar** [comment]
I was going to take a look into this but can't figure out how I can trigger a notification. I tried creating an invoice and paying it, created a payment request and paid id, created an invoice and underpaid it but nothing shows up in notifications. How do I trigger a notification?
