### ISSUE TITLE
Invoice Opening UX 

### ISSUE THREAD

**Issue by alexli1111** [btcpayserver/btcpayserver#1744]
Opening an invoice requires clicking on the little i inside the purple circle

- Previously clicking anywhere on the yellow invoice would open a new tab with all the transaction details
<img width="833" alt="Screen Shot 2020-07-15 at 9 34 14 AM" src="https://user-images.githubusercontent.com/68347343/87580928-07192c00-c68d-11ea-8507-aae054c0c847.png">

**Comment by pavlenex** [comment]
I propose:

- [ ] We remove the `i` 
- [ ] Clicking on label should open the invoice
- [ ] Click on the `X should remove the label, currently it doesn't

There's no need to filter labels by clicking on a label as there's already good filtering option in the header imo. @NicolasDorier do you agree with this one. I remember we had a discussion where you said it's important to have `i`?

**Comment by bolatovumar** [comment]
>  Click on the `X should remove the label, currently it doesn't

This just feels like a bug

> Clicking on label should open the invoice

It's not entirely obvious that clicking on the label would open the details though. Maybe an explicit details link like in the "Invoices" section would make it obvious? I know there is not any space to place this link rn, but we could shorten the transaction id (while keeping it clickable ofc) to fit the "Details" link.

![Screen Shot 2020-07-15 at 8 08 14 PM](https://user-images.githubusercontent.com/1934678/87621986-f1305900-c6d6-11ea-98e8-906efb0d11d0.png)

Something like this maybe:

![Screen Shot 2020-07-15 at 8 18 11 PM](https://user-images.githubusercontent.com/1934678/87622653-6e100280-c6d8-11ea-8546-1355dc5e42f9.png)

Or like this:

![Screen Shot 2020-07-15 at 8 18 43 PM](https://user-images.githubusercontent.com/1934678/87622666-75cfa700-c6d8-11ea-9d6b-49f1058d7808.png)

Alternatively you could make entire row clickable (ares which are not clickable rn) to open invoice details. It could work well or could be awkward, I would have to try it.

**Comment by bolatovumar** [comment]
> > Click on the `X should remove the label, currently it doesn't
> 
> This just feels like a bug

Actually, just tried adding a label in my local dev by adding a label to a random transaction and then clicking the "x" icon and it  removed the label.  It seems like the "Invoice" label is special for some reason?

**Comment by pavlenex** [comment]
I guess it's hardcoded for `invoice` and actually that makes sense. Unsure if it should be allowed to be removed though or f we should remove `x`. @NicolasDorier may know why this has been implemented in this way.

**Comment by pavlenex** [comment]
@bolatovumar I think what we can do here is show hover on `i` and just add an invoice link in `invoice` label text. I can no longer replicate the "unable to remove label".

**Comment by bolatovumar** [comment]
@pavlenex 

> I think what we can do here is show hover on `i`

![Screen Shot 2020-08-04 at 6 59 28 PM](https://user-images.githubusercontent.com/1934678/89363333-c2c5ee00-d684-11ea-9305-6ee76fe87ca4.png)

Like this? (this already exists)

> and just add an invoice link in invoice label text

This would change the current behavior and would make this "invoice" label the only one that behaves this way. This could be confusing.

> I can no longer replicate the "unable to remove label".

I'm the latests master branch and can't remove the label by clicking the "x" icon.

**Comment by NicolasDorier** [comment]
```
 We remove the i
Clicking on label should open the invoice
Click on the `X should remove the label, currently it doesn't
```
Clicking on the label should not open the invoice. Clicking on all other labels are filtering the table. Why invoice would be acting differently?

The X should remove the label, probably a bug.

**Comment by pavlenex** [comment]
> Clicking on the label should not open the invoice. Clicking on all other labels are filtering the table. Why invoice would be acting differently?

Because people don't know that `i` open's invoice directly, that's what why this issue was opened. I recommend we use `i` for the tooltip and invoice text for opening invoice. I don't see benefit in filtering by clicking on label as there are label filters on top of the page.

**Comment by NicolasDorier** [comment]
maybe the `i` is not the right symbol. Maybe an arrow is better.

**Comment by mariodian** [comment]
I don't think a label should have any other function apart from labeling something. However, a "button" could be added to it to enhance it functionality. Something like this:

![label](https://user-images.githubusercontent.com/3636406/92453960-84c36900-f1f2-11ea-8eae-5ae13332ffe1.png)

**Comment by bolatovumar** [comment]
Adjusted the styling to be more like the above:

**Before:**
![Screen Shot 2020-09-13 at 5 27 00 PM](https://user-images.githubusercontent.com/1934678/93032700-c6378800-f5e7-11ea-88e8-c87cb95f6359.png)

**After:**
![Screen Shot 2020-09-13 at 5 21 05 PM](https://user-images.githubusercontent.com/1934678/93032706-cb94d280-f5e7-11ea-9c5a-860e1362032f.png)
