### ISSUE TITLE
Add option for expanded line item default and / or more visible USD price

### ISSUE THREAD

**Issue by svpn** [btcpayserver/btcpayserver#1756]
At checkout the USD price being paid is NOT shown by default.  This can make customers feel uncomfortable.

Currently the only way for the buyer to see the price is by manually expanding the line items by clicking an icon that is barely noticeable and not an obvious function when it is noticed.

Please add an option to allow the line items section to be expanded by default, and / or an option to show the USD price more visibly in the top part of the final checkout page on the left side underneath the description.

**Comment by pavlenex** [comment]
Less is more imo when it comes to checkout. By implementing this people may be tricked into entering the fiat amount in some of the wallets which will cause the invoice to be under or overpaid. I don't think it brings any actual benefit and not many people mentioned this. I personally don't think this is good idea.

**Comment by svpn** [comment]
How can it be a bad idea if it's optional?

In my experience it's absolutely not a bad idea, in fact if you want to increase payment abandonment then just go ahead and don't show people how much they're paying.

There's isn't a mainstream shopping cart or payment system in the world that doesn't show dollar value on the final page.

You do want this to become mainstream right?

**Comment by britttttk** [comment]
Ok I'm going to share an image of what I think we are talking about here for anyone else who wants to share ideas. 
![image](https://user-images.githubusercontent.com/39231115/88001711-02ee7380-cabe-11ea-80f6-4b4725861461.png)

**Comment by britttttk** [comment]
I think @svpn is suggesting a store settings option for non-collapsed invoices. Which seems fair for fiat users... I do think that type of user is looking for the fiat amount. If the collapse isn't too hard to make optional I would say it's an ok idea. 

I guess the bigger issue for me is how to convey this choice in the Store Settings. There are many options already. As @pavlenex  mentioned about simple, it's not just the invoice but also in the settings area which should be going towards simpler imo... 

So in a way I think it might be a marginal improvement if the user can instead just un-collapse it... Although there have been a few discussions before about discoverability of that drop down, as well as the currency toggle. Maybe there is a compromise there..

**Comment by svpn** [comment]
> I think @svpn is suggesting a store settings option for non-collapsed invoices. Which seems fair for fiat users... I do think that type of user is looking for the fiat amount. If the collapse isn't too hard to make optional I would say it's an ok idea.
> 
> I guess the bigger issue for me is how to convey this choice in the Store Settings. There are many options already. As @pavlenex mentioned about simple, it's not just the invoice but also in the settings area which should be going towards simpler imo...
> 
> So in a way I think it might be a marginal improvement if the user can instead just un-collapse it... Although there have been a few discussions before about discoverability of that drop down, as well as the currency toggle. Maybe there is a compromise there..

This is correct, and I'm thinking about it from the perspective of new people that may not be fully familiar / comfortable with Bitcoin ecosystem.  In my case I currently help 1M+ people / month and I want to start converting as many as I can to making payment in Bitcoin.  Many have likely never used i to make a payment, and will be confused when seeing just the value of 1 BTC and absence of the amount they'll be paying in fiat.

**Comment by pavlenex** [comment]
People add stuff to cart, they already know the fiat value. This solution won't bring btcpay mainstream nor btcpay needs to be a mainstream. Exactly suggestions like this, kept polluting the UI. It's optional so let's add it. I am confident this will bring more problems than benefits because people will make that error of adding fiat price. Some wallets also show fiat equivalent, if plenty of people need this I am okay on adding it as an option, as I said I personally think it's bad UX that will lead to underpaid invoices.

**Comment by Kukks** [comment]
I *think*you can customize the css on your store checkout to not have it collapsed at all times which would achieve your goal. 

You can also build your own checkout UI easily if you wanted to.

**Comment by Kukks** [comment]
Just tried, add this to a css file and set your store to use it. It works well enough to start but you can customize it more obviously.

```css
line-items{
  display: block !important;
}
.buyerTotalLine .fa.fa-angle-double-down, 
.buyerTotalLine .fa.fa-angle-double-down:hover, 
.buyerTotalLine .fa.fa-angle-double-up,
.buyerTotalLine .fa.fa-angle-double-up:hover {
  display:  none !important;
}
.buyerTotalLine {
   cursor: default !important;;
}

```

**Comment by svpn** [comment]
> Just tried, add this to a css file and set your store to use it. It works well enough to start but you can customize it more obviously.
> 
> ```css
> line-items{
>   display: block !important;
> }
> .buyerTotalLine .fa.fa-angle-double-down, 
> .buyerTotalLine .fa.fa-angle-double-down:hover, 
> .buyerTotalLine .fa.fa-angle-double-up,
> .buyerTotalLine .fa.fa-angle-double-up:hover {
>   display:  none !important;
> }
> .buyerTotalLine {
>    cursor: default !important;;
> }
> ```

This works great, thanks Kukks.
