### ISSUE TITLE
Can I use it for a online selling platform? 

### ISSUE THREAD

**Issue by SH4LT1S** [btcpayserver/btcpayserver#1757]
Is it possible to use it as middleman for online selling platform? For example people post something online to sell, buys pays me, I take fee and then send BTC to seller? Can it do it automatically? 

Also whats the difference between BTCPay Server and BitcartCC?

**Comment by pavlenex** [comment]
Please do not use github for general questions, we use Github for feature requests and bug reports. Post your question on our chat to get answer from other community members. chat.btcpayserver.org
