### ISSUE TITLE
Add docker compose visual studio project

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#176]
Visual studio 2017 & Visual Studio for mac support docker and allow you to create a native docker-compose visual studio project. We should give it a shot.

**Comment by NicolasDorier** [comment]
Relevant https://www.reddit.com/r/dotnet/comments/8ibvup/manually_configuring_aspnet_core_docker_debugging/

**Comment by Kukks** [comment]
Yeah, we can do it after if we have more than one service running that needs to be debugged
