### ISSUE TITLE
Add padding between "Delete this store" and "Save" buttons

### ISSUE THREAD

**Issue by msafi** [btcpayserver/btcpayserver#1770]
On the store general settings page, the "Delete this store" and "Save" buttons need to have some spacing between them.

This is what the UI looks like for me

![image](https://user-images.githubusercontent.com/4027731/88431622-9621f480-cdaf-11ea-9d7b-ddd5505284f4.png)

**Comment by Eskyee** [comment]
Nicely spotted 🍻 @dennisreimann

**Comment by dennisreimann** [comment]
Will fix it if @bolatovumar isn't faster than I am 😉

**Comment by bolatovumar** [comment]
@dennisreimann Lol I noticed this issue as well earlier but was too lazy to make a PR for this. Will do it now I guess since there is an issue opened for it.

**Comment by dennisreimann** [comment]
Yeah, go for it! 🐛🔫🤘
