### ISSUE TITLE
Pagination in wallets -> manage -> transactions

### ISSUE THREAD

**Issue by simonlucalandi** [btcpayserver/btcpayserver#1771]
**Is your feature request related to a problem? Please describe.**
Let's consider a merchant that sells several orders per day. After some months, he can have generated thousands of transactions.
The page wallets->manage ->transactions is loading all of them, slowing down the browser, that becomes unresponsive.

**Describe the solution you'd like**
I suggest to add a pagination for the transactions list, similar to what we have in the "invoices" page.

**Describe alternatives you've considered**
An alternative can be and "infinite scroll", and load the transactions when the user scroll down the page.

**Provide examples**
Something like this in the bottom of the "transactions" page:

![image](https://user-images.githubusercontent.com/2782202/88434683-fb520600-ce00-11ea-8cf6-c38e42e8c96d.png)

**Comment by NicolasDorier** [comment]
@simonlucalandi last week I made a release of NBXplorer which increase performance of transaction listing and balance listing by a factor of 10x. Can you try?

@bolatovumar did paging, which is cool, but under the hood NBXplorer still get all the transactions which is maybe why things are slow.

Also, for big wallets you can go to your wallet settings / Other actions / Prune wallet. This will remove transactions from your history which does not influence the UTXO, speeding things up considerably.
