### ISSUE TITLE
"Clear All"/"Mark All Seen" button for notifications or disable notifications option

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#1777]
There is no way, at least that I can see, to mark all notifications read en masse. 

I think there should be an easy "Mark All Seen" below the "See All" link when you click the notifications. Or possibly a checkbox above all individual check boxes on the notifications screen with a "Mark All Seen" button at the bottom. 

Ultimately, the notifications don't really help high volume merchants as theres too much to see, so if a simple way of disabling it existed, I would probably use that. 

![Capture](https://user-images.githubusercontent.com/3916318/88565206-21d29580-cfe9-11ea-9221-642bbca08fc4.PNG)

**Comment by pavlenex** [comment]
@astupidmoose Can you try on latest master, I think this is a duplicate since it's added on  #1751. Not really sure it's useful on see all, since you can bulk select on the notification page anyway.

**Comment by astupidmoose** [comment]
Ok, I didn't know this was added. I'll wait for next release to try :)

**Comment by pavlenex** [comment]
You can test it on dev env if you want already quite easily. I'll close this one then, since I'm sure that's what you meant.

**Comment by NicolasDorier** [comment]
I thought we already released this feature

**Comment by astupidmoose** [comment]
> I thought we already released this feature

I'm running BTCPayServer v1.0.5.3, this is latest "stable" release isn't it?

**Comment by NicolasDorier** [comment]
ah so we did not released it
