### ISSUE TITLE
Removed unblinded option for liquid?

### ISSUE THREAD

**Issue by Dinglebarry9** [btcpayserver/btcpayserver#1778]
BTCPay no longer recognizes the `[unblinded]` flag when I paste in an elements derivation scheme. Was this removed?

**Comment by NicolasDorier** [comment]
ping @Kukks it should not have been removed. Maybe something broke it?

**Comment by Kukks** [comment]
I just tried and it worked. Can you confirm that the format was `xpub...-[unblinded]`?

**Comment by Dinglebarry9** [comment]
`tpub...-[unblinded]` but yes. It was generated as such:

```
Dictionary<string, bool> additionalOptions = new Dictionary<string, bool>();
additionalOptions.Add("unblinded", true);

DerivationStrategyOptions derivationStrategyOptions = new DerivationStrategyOptions()
{
         ScriptPubKeyType = scriptPubKeyType,
         AdditionalOptions = new ReadOnlyDictionary<string, bool>(additionalOptions),
};

UserDerivationStrategy = new DerivationStrategyFactory(network).CreateDirectDerivationStrategy(extPubKey, derivationStrategyOptions);
```
It works fine with the console application and a Xamarin forms app

**Comment by Dinglebarry9** [comment]
After sticking a MITM into NBXplorer and building a local nuget NBXplorer.Client it works. Thanks @Kukks
