### ISSUE TITLE
Do not multiply rate if the invoice currency = payment currency

### ISSUE THREAD

**Issue by hubiktomas** [btcpayserver/btcpayserver#178]
Right now if I use "Multiply the rate by ..." option in the Rates section, the rate is multiplied even if the order currency is equal to selected payment currency, which is wrong behavior I believe as there is no conversion.

**Comment by hubiktomas** [comment]
Any update on this issue?

**Comment by NicolasDorier** [comment]
Thanks for brinding it back. I don't think it is wrong. You can see `Multiply the rate by` as a way to apply a discount or premium on paying via Bitcoin.

**Comment by hubiktomas** [comment]
Ok, but when you pass amount in BTC (i.e. 0.1 BTC) to the gateway, then it looks really strange when you see 0.09 BTC instead of 0.1 BTC. I thought that this setting was there to cover possible losses during conversion to altcoins. Even is you like to give a discount, you usually pass fiat to the BTCPay and this is all right ar the currencies differ. I was basically referring to point when you pass BTC or LTC to the gateway and the gateway then displays different amount. But anyway - it is probably not an high priority issue as I can just not use this feature and use rate scripting instead (great feature btw). :)

**Comment by hubiktomas** [comment]
Oh that is true - my approach would not work as you showed. Adding a checkbox would do the trick.

**Comment by hubiktomas** [comment]
Cool, thanks :)
