### ISSUE TITLE
question about addresss test-net

### ISSUE THREAD

**Issue by Ambraham1544** [btcpayserver/btcpayserver#1786]
Hello
I tested the btc payserver.
good.
However, when the address is retrieved from the blockchain
It says test-net.
Is there a way to change this?

**Comment by pavlenex** [comment]
Hello, please for general questions use our community chat chat.btcpayserver.org on Mattermost.
We use GitHub to keep track of feature request and bug reports.
To answer your question, you probably need switch your server from testnet to mainnet.

```
export NBITCOIN_NETWORK="mainnet"
. btcpay-setup.sh -i
```
