### ISSUE TITLE
Minor UI/UX Improvement: Stores -> My Stores 

### ISSUE THREAD

**Issue by Bosch-0** [btcpayserver/btcpayserver#1787]
A small suggestion I'd make to the BTCPay Server home screen (once you sign in). I've always found that simply having 'Stores' is a little ambiguous. A few questions popped into my mind when I first signed into BTCPay - Who's stores? What kind of stores? Are these stores to buy features for BTCPay or something else? Are they my stores? What is a store anyways? (this last question is something I am keen to explore further based on issue #1703) 

I've included a screenshot of the before and after for the top nav menu below as well as minor text changes to the stores page below that.

![BTCPay My Stores](https://user-images.githubusercontent.com/55287964/88896196-15b23680-d27c-11ea-89c0-20834dcce19b.png)

I omitted the 'create' wording from the body text as the button below this already communicates this option. Secondly I simplified the body text from 'Create and manage store settings.' to Manage your stores people which communicates the same thing in simpler English and aligns with the change from Stores to My Stores 

![My Store page](https://user-images.githubusercontent.com/55287964/88897416-cc62e680-d27d-11ea-8501-d70affe72351.png)

**Comment by pavlenex** [comment]
Arguably then we could same the same for Apps. Is this the apps store or is that not confusing? Then it would be too much to #personalizeeverything (my store my apps my wallet)😃

**Comment by Eskyee** [comment]
I prefer what we have, than adding my

**Comment by Bosch-0** [comment]
Good point! Though arguably stores is the most important page and should not have any ambiguity

**Comment by pavlenex** [comment]
It's good argument IMO (that's why we added Welcome to _your_ btcpayserver) on the homepage, I'm just unsure if by adding it, it'll make other menu items more confusing, but it would certainly require quite a bit of documentation changes, hence I'd like to get more feedback before proceeding with it 😸

**Comment by Bosch-0** [comment]
Once/if the dashboard from #1711 gets implemented I think that would also clear up the ambiguity as the landing page currently has little personalization so it leaves the user wondering if this is their stores/apps/wallets etc. This is what lead to my initial confusion.
