### ISSUE TITLE
Remove Confirmed state in UI 

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#1789]
In #1760 , we were discussing removing the Completed state for the new API. If we do this, we will need to retain it for the BitPay API.

So my questions are:
* Should we remove Confirmed or Completed?  We currently have some features such as marking an invoice as complete
* How do we communicate to existing users who use the Bitpay API support and see a different state on the BTCPay UI to the one received through the API?
* Should we make the BitPay API just report that a payment is completed once it is confirmed by the store settings and remove the "IsCompleted" added logic?

**Comment by pavlenex** [comment]
It's really a big change, I'm not sure if it's worth it, but in all honesty those two states are quite confusing for the user. I am with removing completed, but we'd need to change the label to green in invoices as that's the biggest indicator people use to ship items.

I think this will be a big mental and possibility compatibility challenge for people.

**Comment by pavlenex** [comment]
Since we've added different states in the API, I've been thinking and `settled` makes very little sense. We should use `Paid` in the UI. I think there won't be confusions with legacy naming as long as we can present it in green labels and perhaps add a hover explanation for the states. 

Settled isn't really used (I've look through quite a bit of API's that others use, and it's always `paid`. Settled will be hard to understand when we do localization as well. 

Received a payment, unconfirmed - `processing`
Payment confirmed - `paid`

**Comment by Kukks** [comment]
We can't rename the `state` from `settled` now since it's been released to production and would be a breaking change in the API.

**Comment by pavlenex** [comment]
I don't think many people are using the API yet, and it makes sense, as this is a long-term consequence where we're fucking things up, so breaking change is imo OK.

**Comment by Kukks** [comment]
> I don't think many people are using the API yet, and it makes sense, as this is a long-term consequence where we're fucking things up, so breaking change is imo OK.

It's been half a year since we released this and is definitely used. A breaking change like this will cause any integration to break as soon as the update occurs with no warning. If we change this, we have to release a v2 endpoint for the Invoice API as per [GreenField Development Docs](https://github.com/btcpayserver/btcpayserver/blob/master/docs/greenfield-development.md#scenario-1-changing-a-property-type-on-the-model)

**Comment by Kukks** [comment]
> > I don't think many people are using the API yet, and it makes sense, as this is a long-term consequence where we're fucking things up, so breaking change is imo OK.
> 
> It's been half a year since we released this and is definitely used. A breaking change like this will cause any integration to break as soon as the update occurs with no warning. If we change this, we have to release a v2 endpoint for the Invoice API as per [GreenField Development Docs](https://github.com/btcpayserver/btcpayserver/blob/master/docs/greenfield-development.md#scenario-1-changing-a-property-type-on-the-model)

Maybe we can find a way to add an Alias so that `Settled = Paid` and not do  a breaking change but I'm not sure it's possible.

**Comment by pavlenex** [comment]
Ok, but are we on the same page that `Settled` is not intuitive and that `Paid` makes more sense? I guess we first have to see if we all agree on that one to proceed with implementation. 

We can probably keep this until we have more things ready for the v2.

**Comment by Kukks** [comment]
> Ok, but are we on the same page that `Settled` is not intuitive and that `Paid` makes more sense? I guess we first have to see if we all agree on that one to proceed with implementation.
> 
> We can probably keep this until we have more things ready for the v2.
> 
> I remember that many people were confused about `Paid` and `Complete` thinking `Paid` is `Complete` until we added the color distinction, so coloring goes a long way to visually communicate things as well.

Honestly I prefer "Completed" :P

**Comment by pavlenex** [comment]
I must say I'd rather have `Completed` than `Settled`, but I still think `Paid` sounds way more reasonable to people who'll be using this on the front end. I've been looking into other payment processors API's and most of them call this state `Paid`, but I understand it's now hard to go back, it's a bit unfortunate since imo we'll introduce just another way to confuse people instead of finally solving that state mess.

**Comment by NicolasDorier** [comment]
Our additional states are
```
        None,
        PaidLate,
        PaidPartial,
        Marked,
        Invalid,
        PaidOver
```

**Comment by pavlenex** [comment]
@NicolasDorier  `None` is `Expired` or?

**Comment by NicolasDorier** [comment]
None just mean no additional state

**Comment by NicolasDorier** [comment]
Expired is not an additional state, this is a normal state

**Comment by satwo** [comment]
I'll take this one @pavlenex.
