### ISSUE TITLE
Access "services" whilst IBD is still syncing

### ISSUE THREAD

**Issue by Fonta1n3** [btcpayserver/btcpayserver#1795]
It would be cool if I could still access the `btcrpc` hidden service QR code so that I can connect Fully Noded while the node is still syncing. It is a great way to keep an eye on the sync status remotely. Much of the nodes functionality works fine even during IBD, obviously you will not see transactions but other then that :)

**Comment by NicolasDorier** [comment]
it is strange. It should be the case already.

**Comment by NicolasDorier** [comment]
What happen right now before it is synched? It does not appear at all in the Services list?

**Comment by Fonta1n3** [comment]
> What happen right now before it is synched? It does not appear at all in the Services list?

Everything appears, but I was not able to load any of the QR codes, always get the "synching alert". I was using Tor Browser 9.5.3

Now that sync is complete all is working.
