### ISSUE TITLE
Bug in Update Crowdfund page, it seems to jitter during scrolling , tested with browser - chrome & safari 

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver#1796]
in the middle of page  during scrolling you noticed shake or jitter.
latest btcpay update & build.
I have added screen capture to show reproduction. posted video to development at Mattermost, @dennisreimann

**Comment by dennisreimann** [comment]
See my [comment here](https://github.com/btcpayserver/btcpayserver/issues/1536#issuecomment-630828987) – this is related to the rich text editor. I upgraded it in #1798 – can you verify it works?

**Comment by Eskyee** [comment]
> See my [comment here](https://github.com/btcpayserver/btcpayserver/issues/1536#issuecomment-630828987) – this is related to the rich text editor. I upgraded it in #1798 – can you verify it works?

Just tested #1798 yes bug fixed, scroll is now smooth.
cheers
