### ISSUE TITLE
API returns wrong amountPaid empty string instead of 0

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#180]
On invoice creation the original BitPay API returns `0` as empty value for `amountPaid` BtcPayServer returns an empty string `""` instead. Using PHP client library.

This is causing some existing database storage of the invoice fail when switching from BitPay to BtcPayServer.

Would be great if this can be confirmed and fixed* so that we do not need to change upstream library or fix the value before saving. 

\* I'm not familar with C# but if you can give me some hints where this needs to be fixed I will try to get dev setup and give a PR a try.

**Comment by ndeet** [comment]
I debugged it a bit further. My initial guess was wrong. The problem is that BtcPayServer does not return that attribute `paidAmount` at all (because it is empty anyway?) but the offical API always returns `paidAmount: 0`

Together with this new code (function `fillInvoiceData()` the attribute gets set to a empty string:
https://github.com/bitpay/php-bitpay-client/blob/master/src/Bitpay/Client/Client.php#L134

The above mentioned code of official api is not present in your fork of the php client here: 
https://github.com/btcpayserver/php-bitpay-client/blob/master/src/Bitpay/Client/Client.php

Is there any reason this has diverged? I guess BitPay won't accept/merge any PR from your fork :D Will your fork become incompatible with BitPay API or do you stell seek 100% API compability?

**Comment by rockstardev** [comment]
> Will your fork become incompatible with BitPay API or do you stell seek 100% API compability?

Every day I wake up, I remember my wet dreams of 100% Bitpay API _compability_. Every time Bitpay devs diverge from consensus or make changes I cry a little bit. My sorrow was incomprehensible this morning when you pointed me to discovery of changed invoice structure: https://github.com/bitpay/php-bitpay-client/commit/83e2e0e67830d6a9a66fa348de3c029488aa65ac#diff-93bc5e1f94b92088977c4f4470867ba7

@NicolasDorier check if this change will do the trick: https://github.com/rockstardev/btcpayserver/commit/440a62708f3a8e26f45089f5d99f179cf4fc4a90#diff-65f6d5b1b23e4bd190204b659a5bd061R341

**Comment by rockstardev** [comment]
EDIT: Nah, that previous commit likely won't work because core issue is likely how JSON is spit out. Try this new one that targets `DefaultValueHandling`: https://github.com/rockstardev/btcpayserver/commit/e8b6b6f78568c3359fa4cf283061abd7c0ef25ff#diff-d781b11dfa8813818b0c58f42afbf58bR234

**Comment by NicolasDorier** [comment]
Will review tomorrow, we need to do our best to make migration easy. Yes the code might diverge.
I will need to update the php lib.

**Comment by NicolasDorier** [comment]
ok so should we fix this actually?  The thing is that `amountPaid` field in Bitpay makes sense because 1 invoice is always in one specific crypto currency. This is not the case in BTCPay.

`amountPaid` is a crypto value, and we can't properly decide which one to use if the customer paid half btc half ltc.

**Comment by rockstardev** [comment]
I think all @ndeet wants is to have that field initialized when creating invoice so that his database `null` check doesn't throw error. I think that last commit I've sent would do the trick - he can replicate that change and then run test on his instance. 

From there he definitely needs to update logic for handling - I think what we use with `CryptoInfo` is similar to what BitPay now has with `PaymentTotals`.

@ndeet let us know if this works - and thanks for reporting this.

**Comment by Kukks** [comment]
@ndeet  We discussed this briefly @ #168 
No idea how we should be setting this as when partial multi crypto payments are involved we will end up giving out bad data since the new format does not support it well at all. 

`amountPaid` should probably be the total paid in all cryptos converted with the exchange rate to what is set to `transactionCurrency`. Question is, what do  we set it to, the first payment? a store configuration? Meh..

**Comment by NicolasDorier** [comment]
I am unsure as well about the good way of handling this.

@ndeet is it a big deal for you do not rely on those fields?

**Comment by ndeet** [comment]
@NicolasDorier just to be sure we are on the same page. The scope of this issue is only the JSON response after initially creating a new invoice, which diverges from bitpay API by not including `amountPaid` at all. Which seems to be fixed here without major impact?
https://github.com/rockstardev/btcpayserver/commit/e8b6b6f78568c3359fa4cf283061abd7c0ef25ff#diff-d781b11dfa8813818b0c58f42afbf58bR234

The related problem of multiple coin payments discussed above should be separate issue, imo.

Why I would prefer it fixed on btcpayserver:
I build a btcpayserver payment plugin for Drupal Commerce 2.x and there is an existing bitpay module (which uses official PHP library) I can build on top. I have these options now:
1. Hope you fix JSON output to stay with bitpay API
2. Propose patch to bitpay module I'm building on top off. My concern is that they do not accept patch because the official API works
3. Ditch the dependency to that module and start from scratch

I'm fine with each option but it would be really helpful to get a clear answer if btcpayserver want's / can be assumed API compatible with official bitpay API making it a drop in replacement or not (at least for this major versions releases). If yes, I would prefer option 1., if not, happy to do option 3.

**Comment by NicolasDorier** [comment]
That is fair point, will merge the patch.
That said I am surprised it is the only issue you have with drupal plugin. They allow you to customize bitpay server url?

**Comment by NicolasDorier** [comment]
I was expecting you forked their plugin and needed some adaptation. At least for the server url.

**Comment by ndeet** [comment]
Awesome thanks!

Will let you know if anything else breaks further down the road 😆

Regarding custom URL, I asked maintainers if they would accept PR for that and they agreed. They also pointed me to `Customnet.php` which allows exactly that. My guess is this is because of bitpay insight or sth like that.
https://github.com/bitpay/php-bitpay-client/blob/master/src/Bitpay/Network/Customnet.php

**Comment by NicolasDorier** [comment]
wow very cool! so we don't need to maintain our own lib.

**Comment by NicolasDorier** [comment]
1.0.2.22 should be available in like 20-30 min.

**Comment by NicolasDorier** [comment]
Closing this issue 1.0.2.22 is out, can you try? Reopen this issue if it does not fix the problem.

**Comment by ndeet** [comment]
@NicolasDorier Thank you! Updated my docker node to 1.0.2.22, works like a charm now. 💯
