### ISSUE TITLE
Unblinded Liquid Assets not triggering invoice event

### ISSUE THREAD

**Issue by Dinglebarry9** [btcpayserver/btcpayserver#1807]
I have been experiencing a strange issue with Liquid where invoices for Liquid Assets with the [unblinded] flag fail to update when BTCPay receives a new transaction event from NBXplorer. Though, when the connection to NBX is severed and BTCPay reconnects (when I shut down either NBX or BTCPay) and it checks if pending invoice got paid while offline the invoice gets updated with the payment happening. This is not a problem with the pegged asset (blinded or unblinded Derivation Strategy) nor Liquid assets sent to aDerivationScheme without the [unblinded] flag.

**Comment by NicolasDorier** [comment]
ping @Kukks

**Comment by Dinglebarry9** [comment]
In `NBXplorerListener` the `FindPaymentViaPolling` method works in finding payments to Liquid Assets with the `[unblinded]` flag. Not ideal but to help figuring out why this is happening, adding another `await FindPaymentViaPolling(wallet, network)` after `_Aggregator.Publish(new NewOnChainTransactionEvent())`.

Further, in Manage Wallets under transactions it shows the transaction with the value (the New Transaction Event is triggered) but is not tied to an invoice (no InvoiceEvent is triggered). Any idea why?

**Comment by Kukks** [comment]
I attempted to test this and couldn't replicate.
Could you provide additional details on the wallet configured and how you configured it?

**Comment by Dinglebarry9** [comment]
Sure, I am not generating a wallet I am just tracking a derivation scheme  

```
Mnemonic mnemo = new Mnemonic("...");

ExtKey masterKey = mnemo.DeriveExtKey("");

ExtPubKey masterPubKey = masterKey.Neuter();
            
Dictionary<string, bool> additionalOptions = new Dictionary<string, bool>();
            additionalOptions.Add("unblinded", true);

DerivationStrategyOptions derivationStrategyOptions = new DerivationStrategyOptions()
{
    ScriptPubKeyType = ScriptPubKeyType.Legacy,
    AdditionalOptions = new ReadOnlyDictionary<string, bool>(additionalOptions),
};
DerivationStrategyBase userDerivationStrategy = new DerivationStrategyFactory(network).CreateDirectDerivationStrategy(masterPubKey, derivationStrategyOptions);
```

**Comment by pavlenex** [comment]
@Dinglebarry9 has this been resolved? Been a while, so I am double-checking if you're still having issues.

**Comment by Dinglebarry9** [comment]
Hey @pavlenex, great work yall do, I had previously add a call to `FindPaymentViaPolling()` in the `NewTransactionEvent` switch case in the `Listen()` method of the `NBXplorerListener` class. This provided a hacky workaround. I just tried removing the call with the most up to date release and it seems to work fine for both the pegged asset and issued assets.

**Comment by pavlenex** [comment]
Thanks for the update @Dinglebarry9 in that case, I'll go ahead and close this one, but if you do face any similar problems in the future, let us know so we can re-open it.
