### ISSUE TITLE
Clicking on the status in the invoice list should add a filter

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#1809]
If clicking on the state of invoices in the list, it should filter by it.
I think it should filter only on the main state (for example clicking on `complete (marked)` would filter every invoice `complete`)

![image](https://user-images.githubusercontent.com/3020646/89374121-6f57ac80-d725-11ea-9b28-88f658fc6129.png)

**Comment by pavlenex** [comment]
You can already filter via drop down for all states? I think if we add this people would expect it for all states, but then it's not possible to have it since there are drop down actions for some states (complete marked) etc.

**Comment by bolatovumar** [comment]
Also, for some labels like "paid" and "complete" you get a dropdown on click. If we change this behavior to filter instead then this functionality will either be lost or will need to be done in some other way.

![Screen Shot 2020-08-06 at 8 38 58 PM](https://user-images.githubusercontent.com/1934678/89606465-e32cae80-d824-11ea-8038-5291de970c49.png)

**Comment by dstrukt** [comment]
Going to try to catalog all of these various states and the surround UX in the coming weeks so we can standardize / better document some of the expected behavior.
