### ISSUE TITLE
Proposal for UX improvement of Lightning setup page

### ISSUE THREAD

**Issue by Kixunil** [btcpayserver/btcpayserver#1811]
**Is your feature request related to a problem? Please describe.**
I'd like to see BTCPayServer as user-friendly as possible. Looking at the Lightning setup page, there's a text field to enter the (scary looking) connections string and only at the bottom there's a small link to get the internal configuration. A huge part of the page is taken by describing how to enter the connection string, which most users won't even need to read.

Further, only one internal LN implementation is supported, which makes it harder to configure for users who would like to experiment with different LN nodes.

**Describe the solution you'd like**
* Change the layout to use a drop down (similar to off-lightning wallet), which could select from various internal implementations and have "Custom" option which would show the text field and the help *under* the text field.
* Allow entering the connection string in the configuration **file** more than once
* Add a new `label` parameter to the connection string, this label will be shown in the UI
* Use labels in Docker deployment ("Internal LND node", "Internal Eclair node", "Internal c-lightning node")

**Describe alternatives you've considered**
* Keep scaring off users
* Fork the project and implement this feature

**Provide examples**
I'm not a graphics designer but I hope I described it sufficiently above. If you have hard time imagining the above, I will try to provide example later.

**Comment by Kukks** [comment]
`Keep scaring off users` 🤣

**Comment by NicolasDorier** [comment]
`Allow entering the connection string in the configuration more than once`
If an invoice is created, which connection string should btcpayserver pick.

**Comment by NicolasDorier** [comment]
`Fork the project and implement this feature`

And one more dotnet dev? Fuck yes!

**Comment by Kixunil** [comment]
> If an invoice is created, which connection string should btcpayserver pick.

The one set in the store settings. I guess I was imprecise in my wording, it should have been "Allow entering the connection string in the configuration **file** more than once" so that the UI would show all of them.

> And one more dotnet dev? Fuck yes!

Well, I might do the PR at some point, however I'm not very familiar with C# (used it a loong time ago) and it's not my top priority right now, so I guess you might be able to do it sooner, if you have the time and find the idea useful. I guess I won't be able to work on it at least for a few months.

**Comment by dennisreimann** [comment]
I think the suggestions are reasonable and I could take on the UI side if someone else takes care of the Docker part :)

**Comment by dennisreimann** [comment]
Just a note: There's a [check on the Lightning setup page](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Views/Stores/AddLightningNode.cshtml#L108) that prevents the "Use the internal lightning node" option from being shown. We received feedback that it seems broken if it's just not there and we should display a hint why this isn't available.

**Comment by Kixunil** [comment]
I wouldn't call it "broken", but I agree with having a helpful message in case there are no nodes configured.

**Comment by pavlenex** [comment]
Firing up the LN node should be as easy as our new #2164 there's way too much stuff going on, let's await for https://github.com/btcpayserver/btcpayserver/pull/2314 and then we can thinker around the UI.
Wizard type of UI:

0. Disclaimer
1. How do you want to start using Lightning Network:
- Deploy a node
- Connect a node (which can have all the messy stuff for advanced users)
2. (In the future) Get inbound capacity 
3. Successfully deployed (some warnings about backup, channels and keeping funds safu)

**Comment by Kixunil** [comment]
@pavlenex do you propose that BTCPayServer will execute some privileged command to deploy LN node when choosing "Deploy a node"? It doesn't feel right to me but also see some value in hinting the user what to do.
It'd also destroy various non-docker deployments if docker-specific code was added there.

I also don't feel like a big disclaimer should be on its own page. LN is quite stable these days and while some disclaimer may be appropriate, it doesn't feel right to act as if it was a nuclear bomb.

I propose instead a simple page with short disclaimer and a ling with more details. Then a dropdown menu:

* Internal Node 1
* Internal Node 2
* ...
* Internal Node n
* Add a new node
* Custom node

(`Internal Node $i` are not actually numbered items but labels as specified in config *file* - e.g. `Internal LND node`, `Internal Eclair node`...)

Clicking "Add a new node" would point to an administrator-supplied URL from the config. If you still want to execute privileged commands in Docker, just set the URL to some internal BTCPay URL which will handle the rest. If you want to avoid executing privileged commands, point it to LN node documentation.

"Get inbound capacity" sounds also useful but it feels like adding yet another feature to BTCPay which may require privileged access to LN node, depending on the implementation. Allowing to at least override it may be a good idea.

Note that I've already head several complains that BTCPay has everything but a kitchen sink in it so maybe making it possible to have less stuff would improve the reputation of BTCPay.

**Comment by pavlenex** [comment]
> @pavlenex do you propose that BTCPayServer will execute some privileged command to deploy LN node when choosing "Deploy a node"? 

BTCPay already deploys an internal node I was just brainstorming how it can be communicated through the UI. 99% of users most likely use internal BTCPay node. Drop-down should be used when there are more options, in this case we have two.

I am not sure why you're mentioning privileged commands, I was not referring to that at all.

> Clicking "Add a new node" would point to an administrator-supplied URL from the config. If you still want to execute privileged commands in Docker, just set the URL to some internal BTCPay URL which will handle the rest. If you want to avoid executing privileged commands, point it to LN node documentation.

This is too complicated for regular merchant.

> Note that I've already head several complains that BTCPay has everything but a kitchen sink in it so maybe making it possible to have less stuff would improve the reputation of BTCPay.

This is on a [roadmap](https://github.com/orgs/btcpayserver/projects/9) with new plugin system.

**Comment by Kixunil** [comment]
> BTCPay already deploys an internal node

Yes, using a script at docker level or by other means in case of other BTCPay vendors - e.g. as an additional package.

> 99% of users most likely use internal BTCPay node.

Exactly, the reason for this issue.

> Drop-down should be used when there are more options, in this case we have two.

Yeah, I suggested that BTCPay could support more internal nodes. If it won't then just two buttons is enough.

> I am not sure why you're mentioning privileged commands

My understanding of the wording "Deploy a node" was that you want BTCPay to perform the deployment logic that is currently handled by the script. If it's not what you mean then I suggest renaming it to "Use internal node" to avoid confusing others the same way I was confused.

> This is too complicated for regular merchant.

Sorry, I should've written "vendor" instead of "administrator". The value would be hard-coded in configuration scripts by all vendors. Merchant only sees the result: a link that allows him to deploy a node.

> This is on a roadmap with new plugin system.

Awesome!

**Comment by dennisreimann** [comment]
Explored this a bit, here's a mockup of something that would work imho.  /cc @dstrukt 

We could expand this with additional radio options for multiple internal nodes in the future … 

## Internal Node

![internal](https://user-images.githubusercontent.com/886/110098659-b92e7100-7da0-11eb-9085-1fa211a034a8.png)

## Custom Node

![custom](https://user-images.githubusercontent.com/886/110098682-be8bbb80-7da0-11eb-879a-1c18fc9bf046.png)

**Comment by Kixunil** [comment]
This looks awesome, thanks a lot!

One more thing would be great, if the internal node is not configured, there could be something like this:

> No internal node detected. You can read the documentation of how to setup internal node.

Where "documentation of how to setup internal node" is a link to vendor-provided documentation. BTCPayServer-docker would hard-code it to https://docs.btcpayserver.org/LightningNetwork/

**Comment by dstrukt** [comment]
@dennisreimann Looking good - liking the updates! I think it's becoming a lot clearer + some of the bootstrap UI changes will help as well.

Working a bit this weekend to get all the things we discussed done, will take a pass at this.
