### ISSUE TITLE
UX/UI - Visual bug in crowdfund creation page

### ISSUE THREAD

**Issue by Zaxounette** [btcpayserver/btcpayserver#1816]
**Describe the problem/bug**
A visual bug is present in the crowdfund creation screen.

**Your environment**
* Version of BTCPay Server: v1.0.5.4
* Deployment method: Lunanode
* Browser: Chrome, latest build.

**Setup Parameters**
NA

**To Reproduce**
1. Go to 'Apps'
2. Click on 'Create new app (Crowdfund)'
3. Scroll down to 'Reset goal every'
4. See the ticker and the drop-down icons that are intertwined

**Expected behavior**
Only keep the dropdown icon, as it makes sense to have it since multiple choices are offered.
Delete the validating ticker since it's usefulness is questionable ?

**Actual behavior**
Ticker and the drop-down icons are intertwined

**Screenshots/Links**
![Screenshot_82](https://user-images.githubusercontent.com/51208677/89452917-b6ae5f00-d75e-11ea-8bd2-a5b6bd67329f.png)
![Screenshot_83](https://user-images.githubusercontent.com/51208677/89453518-b06cb280-d75f-11ea-9b79-9fee43a5f845.png)

**Additional info**

This is visible in Chrome, latest build.
Checked the BTCPay Server themes, just in case: It's visible in both Default, Classic and Casa themes.

**Comment by Eskyee** [comment]
Spotted on my fresh install.. bug confirmed
