### ISSUE TITLE
number of notifications in top bar is not updated after deleting the notifications from UI

### ISSUE THREAD

**Issue by simonlucalandi** [btcpayserver/btcpayserver#1820]
**Describe the problem/bug**
After deleting the "notifications", the "bell" icon on the right of the top bar still shows that we have notifications to read.

Steps to reproduce:
 - click on the "bell" icon on the top right (https://btcpay.cryptorefills.com/Notifications/Index)
 - select "500" to show 500 notifications per page
 - select all the notifications and "delete" them (without marking as "read")
 - the top bar shown a wrong number

![image](https://user-images.githubusercontent.com/2782202/89542603-2cb6d280-d800-11ea-97cf-4a8c595a4581.png)

**Your environment**
* Version of BTCPay Server: 1.0.5.4
* Deployment method: Docker

**To Reproduce**
1. click on the "bell" icon on the top right (https://btcpay.cryptorefills.com/Notifications/Index)
2. select "500" to show 500 notifications per page
3. select all the notifications and "delete" them
4. the top bar shown a wrong number

**Expected behavior**
The "bell" icon should show no notifications to read.

**Actual behavior**
The "bell" icon still show notifications to read.

**Comment by astupidmoose** [comment]
This is actually a different cause... The bottom "Page Size" selector is wrong in what it brings up. 

For example, If you select 500, as you did, there is only 250 results presented. So what is happening is that you are expecting to clear 500 but only 250 are being cleared.

**Comment by bolatovumar** [comment]
@astupidmoose just looking at the code now and it doesn't look like the pagination is wrong.

@simonlucalandi does the notification number by the bell icon go down when you "delete" notifications? Or does it just stay the same?

**Comment by astupidmoose** [comment]
> @astupidmoose just looking at the code now and it doesn't look like the pagination is wrong.

When I navigate to /Notifications/Index?skip=0&count=50 I get the following: 
![image](https://user-images.githubusercontent.com/3916318/89606458-db6d0a00-d824-11ea-9663-d3e0736b7251.png)

I always get exactly half of the results the pagination has been asked to provide. 
![image](https://user-images.githubusercontent.com/3916318/89606503-fe97b980-d824-11ea-914a-33e0edc8beae.png)

**Comment by bolatovumar** [comment]
@astupidmoose ok, weird. I'm trying to repro it but it's not easy as I don't have any notifications and I'm trying to trigger some now somehow.

**Comment by simonlucalandi** [comment]
> 
> 
> @astupidmoose just looking at the code now and it doesn't look like the pagination is wrong.
> 
> @simonlucalandi does the notification number by the bell icon go down when you "delete" notifications? Or does it just stay the same?

The numbers goes down, but of a wrong amount.

**Comment by bolatovumar** [comment]
> > @astupidmoose just looking at the code now and it doesn't look like the pagination is wrong.
> > @simonlucalandi does the notification number by the bell icon go down when you "delete" notifications? Or does it just stay the same?
> 
> The numbers goes down, but of a wrong amount.

Ok, that's consistent with what @astupidmoose is saying then. I will attempt to repro the issue.

**Comment by bolatovumar** [comment]
Still can't repro. What does your URL look like @astupidmoose? Like this: `/Notifications/Index?skip=0&count=50`?

Also, I don't have that many notifications and I'm wondering if this happens if you have many notifications only.

**Comment by astupidmoose** [comment]
Yea,

Notifications/Index?skip=0&count=50

This shows 25 results in events.
