### ISSUE TITLE
Page alignment and zoom bugs

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#1823]
**Describe the problem/bug**
Table isn't aligned in on the invoices page

**Your environment**
* Version of BTCPay Server: v1.0.5.4
* Deployment method: Debug
* Other relevant environment details: Firefox and chrome

**To Reproduce**
1. View invoices page

**Expected behavior**
Search, create and table should be aligned (similar to the other pages like payment requests). 

**Actual behavior**
Search and Create buttons are centered a bit.

**Screenshots/Links**
![image](https://user-images.githubusercontent.com/39231115/89606147-859c6000-d82c-11ea-932c-db4e309345d4.png)

**Additional context**
Another related issue is that on the Payment requests page, the table and search become misaligned if the page zoom is not 100%. Invoices page does not have this issue on page zoom changes. 

![image](https://user-images.githubusercontent.com/39231115/89606418-23902a80-d82d-11ea-8472-67dba2ba459e.png)

**Comment by dennisreimann** [comment]
See #1815 :)

**Comment by pavlenex** [comment]
@britttttk Did #1815 resolve the issues?

**Comment by britttttk** [comment]
@pavlenex yes the latest master has both issues above fixed. Thanks @dennisreimann! I believe the payment request comment is a duplicate of issue #1862

**Comment by dennisreimann** [comment]
Yes, I guess we can close #1862 too and reopen it in case Mike still has this after upgrading the next time.
