### ISSUE TITLE
Creation Invoice

### ISSUE THREAD

**Issue by jessemarco** [btcpayserver/btcpayserver#1832]
https://xpayserver.com/invoices/create

I want to create invoice and I get error:

"Error: 8/9/2020 7:40:45 PM: Creation of invoice starting 8/9/2020 7:40:45 PM: USDT20_ETH: The rating rule is bitfinex(UST_BTC) * (1 / kraken(ETH_BTC)) 8/9/2020 7:40:45 PM: USDT20_ETH: The evaluated rating rule is (0.0000859549596011689874505759, 0.0000859623484913607839766182) * (1 / (0.03345, 0.03346)) 8/9/2020 7:40:45 PM: ETH_ETH: The rating rule is 1.0 8/9/2020 7:40:45 PM: ETH_ETH: The evaluated rating rule is 1.0 8/9/2020 7:40:45 PM: USDT20 (On-Chain): Payment method details creation took 3 milliseconds 8/9/2020 7:40:45 PM: USDT20: Payment method unavailable (could not generate address) 8/9/2020 7:40:45 PM: ETH (On-Chain): Payment method "

Can you help?

**Comment by pavlenex** [comment]
@jessemarco xpayserver is a third party host, that's using fork of btcpayserver (for now). Please in future get in touch with them directly for support.

ping @xpayserver
