### ISSUE TITLE
Default to Alphabetic Ordering of Stores List

### ISSUE THREAD

**Issue by memiamap** [btcpayserver/btcpayserver#1837]
**Is your feature request related to a problem? Please describe.**
It's not related to an existing problem.

**Describe the solution you'd like**
I'd like to see the list of Stores on the `stores` pages ordered alphabetically.

**Describe alternatives you've considered**
There are two alternatives that I can think of:

1. Keep it as is, which appears to be ordered by creation date (although this is not shown as a column in the list).
2. Provide a facility to choose the ordering (i.e. alphabetically, by creation date, by current balance, by most recent transaction, etc.).

**Provide examples**
See the screenshot showing the current ordering.  Note that this is not alphabetically ordered, and stores with identical names but numeric postfixes are in a non-logical order (i.e. 01, 03, 02 and 07, 09, 08).

![Stores Ordering](https://user-images.githubusercontent.com/38524655/89883952-c398db80-dbc0-11ea-804f-92bbee2be431.png)

**Additional context**
Nothing further to add although I see that there is a default ordering that is not alphabetic on most other tables\lists on the site.

**Comment by NicolasDorier** [comment]
I think @bolatovumar added some sorting in some table around, and this might be one of those. Though I am unsure if that's save in preferences.
