### ISSUE TITLE
CSV Files are no longer formatting properly

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#1844]
When downloading a CSV of the invoices, the data no longer contains line breaks for each new line and the quotations (") around each piece of data are now missing. This causes programs such as excel, google docs, and even notepad to assume all data is one row. 

My report from June worked well, so this break is recent, I am assuming it was this change:
https://github.com/btcpayserver/btcpayserver/commit/26112a1ed6e666bd38b77196e69e58662a716546

**Comment by NicolasDorier** [comment]
on it.

**Comment by NicolasDorier** [comment]
Will make a small release soon to fix this.

**Comment by NicolasDorier** [comment]
> the quotations (") around each piece of data are now missing

This is normal. It is sometimes not needed (csv is complicated...)
