### ISSUE TITLE
LND connection string needs admin macaroon

### ISSUE THREAD

**Issue by fiksn** [btcpayserver/btcpayserver#1845]
**Describe the bug**
Perhaps this is not a bug and just needs some clarification. I want to use external LND.
When I supply connection string btcpayserver says `Error while connecting to the API (The HTTP status code of the response was not expected (500).)`. If I change the connection string to use admin.macaroon everything works.

**To Reproduce**
1. Go to Stores / Settings / Lightning nodes (Experimental) 
2. Try adding url like `type=lnd-rest;server=https://...:8080/;macaroonfilepath=../invoice.macaroon;certthumbprint=...`
3. Press Test Connection

**Expected behavior**
My assumption was that invoice.macaroon would be enough.

**Your BTCPay Environment (please complete the following information):**
v1.0.5.4 and LND 0.10.3-beta on remote machine with TCP port 8080 open

**Comment by NicolasDorier** [comment]
@fiksn we use `GetInfo` which is not allowed for the invoice macaroon.
We need GetInfo because we should check whether the lightning node is fully sync before creating an invoice, as well as for fetching the node URI to display in the QR Code.

**Comment by fiksn** [comment]
Thanks for explanation.

If anyone else stumbles upon this. I did `lncli bakemacaroon address:read address:write info:read invoices:read invoices:write onchain:read` now  and use the generated macaroon as `macaroon=` (instead of `macaroonfilepath=`).

But I suppose you could also use `--save_to` option of `bakemacaroon` and the reference the (local) file.

**Comment by dennisreimann** [comment]
Maybe we should add the essence of the last two comments into an FAQ item of the docs. Great info here 👍
