### ISSUE TITLE
Extend API: feerate

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#1846]
**Is your feature request related to a problem? Please describe.**
As described on [Mattermost](https://chat.btcpayserver.org/btcpayserver/pl/xxs5hyt7zbypfgn3ndnx5oes6w) - I'm trying to enrich the checkout page with some fee information.

Like: "if you pay with On-Chain funds (from a segwith wallet): your transaction costs could on average be: X.YZ €"
or: "If you pay with On-Chain funds (from a legacy wallet): your transaction costs would be on average: ...
or: "If you use lightning expect to pay somewhere around 0-3% (depending on your routing and proximity to our node)"

**Describe the solution you'd like**
I would need an /api/feerate endpoint. Which expects a store_id to send me back the current feerate per vB for the way my store is configured (i.e. estimates based on next block or next X blocks, etc.) - preferably without AUTH/public facade and as json output so I can include it in my frontend html/javascript.

**Describe alternatives you've considered**
I have checked the Greenfield and Legacy API docs and couldn't find any information related to feerate. If there is such a feature, please feel free to close this request.

**Comment by NicolasDorier** [comment]
id you tried `https://mainnet.demo.btcpayserver.org/api/rates?storeId=<storeid>`

**Comment by NicolasDorier** [comment]
Ah forget about it this is only for exchange rates.

**Comment by Kukks** [comment]
We can probably do this for the next version under 
GET api/v1/stores/{storeId}/payment-emthods/onchain/{cryptoCode}/wallet/feerate 
OR include it in 
GET `api/v1/stores/{storeId}/payment-emthods/onchain/{cryptoCode}/wallet `
