### ISSUE TITLE
Show multiple addresses

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#185]
Is it possible to show  the equivalent nonsegwit, segwit and bech32 addresses under an invoice checkout screen? In an ideal world, we's just use the newer format but some outdated clients and exchanges validate falsely against it and do we have to allow legacy formats too. Any suggestions?

**Comment by Kukks** [comment]
@NicolasDorier  Perhaps we can make a derivation strategy that can handle tracking multiple addresses per  derivation?

**Comment by NicolasDorier** [comment]
meh this is pain in the ass. Lot's of refactoring when only a P2SH-P2WSH would be supported everywhere.

**Comment by Kukks** [comment]
Killing this for now
