### ISSUE TITLE
Cannot use Internal Lightning Node from a Greenfield authenticated user, even if "btcpay.server.canuseinternallightningnode" permission is present

### ISSUE THREAD

**Issue by gradientskier** [btcpayserver/btcpayserver#1855]
**Describe the bug**
Cannot use Internal Lightning Node from a Greenfield authenticated user, even if "btcpay.server.canuseinternallightningnode" permission is present

**To Reproduce**
1. Create a Greenfield API Key with btcpay.server.canuseinternallightningnod
2. Try to use the Greenfield method GetInfo

**Expected behavior**
I should get the info from the internal lightning node

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version v1.0.5.2

By debugging, I think the problem is in the following line of code: https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Controllers/GreenField/LightningNodeApiController.cs#L291

That should be modified into something like this
`
            return (_btcPayServerEnvironment.IsDevelopping || User.IsInRole(Roles.ServerAdmin) ||
                    (_cssThemeManager.AllowLightningInternalNodeForAll && !doingAdminThings) ||
                    User.HasClaim(GreenFieldConstants.ClaimTypes.Permission, Policies.CanUseInternalLightningNode));
`

What do you think?

**Comment by Kukks** [comment]
> **Describe the bug**
> Cannot use Internal Lightning Node from a Greenfield authenticated user, even if "btcpay.server.canuseinternallightningnode" permission is present
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Create a Greenfield API Key with btcpay.server.canuseinternallightningnod
> 2. Try to use the Greenfield method GetInfo
> 
> **Expected behavior**
> I should get the info from the internal lightning node
> 
> **Your BTCPay Environment (please complete the following information):**
> 
> * BTCPay Server Version v1.0.5.2
> 
> By debugging, I think the problem is in the following line of code: https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Controllers/GreenField/LightningNodeApiController.cs#L291
> 
> That should be modified into something like this
> `return (_btcPayServerEnvironment.IsDevelopping || User.IsInRole(Roles.ServerAdmin) || (_cssThemeManager.AllowLightningInternalNodeForAll && !doingAdminThings) || User.HasClaim(GreenFieldConstants.ClaimTypes.Permission, Policies.CanUseInternalLightningNode));`
> 
> What do you think?

As a non-admin, the only things you are able to do(with canuseinternallightningnode permission)  is:
* get a lightning invoice
* create a lightning invoice

`GetInfo` might expose data that the server admin does not want to share with others, such as a tor/ip address or if the ln node is fully synced yet. @NicolasDorier  what do you think? Should we relax it for GetInfo?
