### ISSUE TITLE
Changelly integration broken

### ISSUE THREAD

**Issue by Transisto** [btcpayserver/btcpayserver#1858]
When the changelly popup show up, No currency or amount seems like they were passed to it.

**Comment by Kukks** [comment]
I won't be fixing this most likely. I think we should schedule it for removal if no one intends to fix it within a reasonable time frame. 

There is still Coinswitch support for now but the idea is that once that breaks it will receive the same fate.

**Comment by astupidmoose** [comment]
I'm pretty sure coinswitch is dead too tbh. We disabled it long ago.

![image](https://user-images.githubusercontent.com/3916318/90817401-9e078280-e2e2-11ea-8742-604522e80d56.png)

Can't pay anything above $1? lol

**Comment by pavlenex** [comment]
I second Kukk's suggestion that both of these third-party services should be removed if they're not fixed in the reasonable time-frame. We shouldn't build in TTP in the software in the future, even if optional IMO.

**Comment by Transisto** [comment]
Has whoever build the integration aware it's broken? 
I contacted changelly in case they'd want to contribute.

**Comment by astupidmoose** [comment]
> Has whoever build the integration aware it's broken?
> I contacted changelly in case they'd want to contribute.

I think @Kukks actually wrote the first iterations of these integrations. I think if changelly wanted to throw a dev on it that would be best.

**Comment by NicolasDorier** [comment]
@Transisto I think that @Kukks integrated it. But I think he fixed several time breaking changes and is tired of it.

**Comment by NicolasDorier** [comment]
tweeted https://twitter.com/BtcpayServer/status/1298175682803974144

will ask on the mattermost as well. Nobody seems crying.

**Comment by BitcoinMitchell** [comment]
> I'm pretty sure coinswitch is dead too tbh. We disabled it long ago.
> 
> ![image](https://user-images.githubusercontent.com/3916318/90817401-9e078280-e2e2-11ea-8742-604522e80d56.png)
> 
> Can't pay anything above $1? lol

CoinSwitch seems to work fine for me. Please do not remove the integration. It was probably a temporary issue on their side.

![image](https://user-images.githubusercontent.com/27309467/92658204-75c5df00-f2f6-11ea-8416-bd0d0a6addfd.png)

**Comment by BitcoinMitchell** [comment]
> I'm pretty sure coinswitch is dead too tbh. We disabled it long ago.
> 
> ![image](https://user-images.githubusercontent.com/3916318/90817401-9e078280-e2e2-11ea-8742-604522e80d56.png)
> 
> Can't pay anything above $1? lol

CoinSwitch seems to work fine for me. Please do not remove the integration. It was probably a temporary issue on their side.

![image](https://user-images.githubusercontent.com/27309467/92658255-88d8af00-f2f6-11ea-80f3-106120cd5655.png)
