### ISSUE TITLE
Payment Requests not spanning whole page

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#1862]
When navigating to the payment requests page, the list of requests is confined to the left hand side of the page. See attached. Expecting it to span the whole page. 

![tempsnip](https://user-images.githubusercontent.com/3916318/90971431-09a94580-e4c5-11ea-88fa-13e3dcd7b333.png)

**Comment by pavlenex** [comment]
ping @astupidmoose can you check if this is fixed?

**Comment by astupidmoose** [comment]
Was there a release? 

I don't have a dev instance running so can only check against releases

**Comment by dennisreimann** [comment]
@astupidmoose Not yet, those changes happened after v1.0.5.5

**Comment by pavlenex** [comment]
I'll close this one so we clear out the backlog. If after the new release this still happens, let's re-open it.
