### ISSUE TITLE
Bootstrap 5 migration

### ISSUE THREAD

**Issue by dennisreimann** [btcpayserver/btcpayserver#1866]
This issue serves to plan and discuss the migration to [Bootstrap 5](https://v5.getbootstrap.com/), which is in alpha currently. We use Bootstrap across our products and had to make [adjustments to the current version in the design system](https://design.btcpayserver.org/resources/css/). The v5 will be a big step forward, allowing us to hopefully drop the fork approach.

@dstrukt and @Bosch-0 are making great progress with the [design specifications and mockups on Figma](https://www.figma.com/file/C7Xyq0FlxgFW8vaBr8ht1z/BTCPAY). These have a cleaner look/more reduced style and involve some larger changes. We should hold those off until Bootstrap 5 is released, because it will most likely make our lives easier approaching this bigger UI redesign.

The plan I'd propose would be to

1) Update to v5 once it's at least in RC stage ([Migration docs](https://v5.getbootstrap.com/docs/5.0/migration/))
2) Make the adaptions to v5 to fit the new style on Figma – see the [Bootstrap kitchensink page in the design system](https://design.btcpayserver.org/views/bootstrap/)
3) Integrate the new css files in BTCPay Server
4) Make necessary adaptions across the products 

The main reason for this issue is to ensure everyone is on the same page and we can point towards it for clarifications in other current issues – basically as an explainer why we are holding off larger changes and discuss the migration there.

**Comment by dstrukt** [comment]
Update: I've been overhauling the entire design system on the Figma and building out every single page so we can quickly iterate on future updates, etc.. this work should be done in the coming weeks. 

Implementation, edge cases, and micro-interactions will likely take a considerable bulk of time as well, so I'm almost thinking we'll have to make these changes in chunks as well.

**Comment by NicolasDorier** [comment]
I don't understand why waiting for Bootstrap 5 before doing changes.

If we wait for Bootstrap 5, it means we will spend time porting stuff that will ultimately be replaced by @dstrukt 's design.

**Comment by dennisreimann** [comment]
@NicolasDorier the idea is to do the migration + customizations and then the changes instead of customizing the current bootstrap version, doing the changes and then migrating and potentially having to do the customizations again. 

[CSS Variables](https://v5.getbootstrap.com/docs/5.0/customize/css-variables/) become a first-class concept in Bootstrap 5 – this has been something I monkeypatched into our current version (4.5) and my hope is it'll be easier to maintain and customize the components afterwards. I can take a closer look again, but my gut feeling is that there'd be potential for doing stuff twice.

**Comment by dennisreimann** [comment]
Reading the [migration guide](https://v5.getbootstrap.com/docs/5.0/migration/)/changelog for Bootstrap v5 and love to see this:

> JavaScript
> Dropped jQuery dependency and rewrote plugins to be in regular JavaScript.

Reading up on the state of CSS custom properties I also saw that their usage might not go as far as I initially expected. [Described our use case](https://github.com/twbs/bootstrap/issues/26596#issuecomment-706088248) in detail to hopefully extend their support for the variables.

**Comment by dennisreimann** [comment]
Update: The first Bootstrap v5 beta is live andit looks like they won't ship CSS custom properties to the extend I've hoped for. We'll continue with the current approach then …

**Comment by dennisreimann** [comment]
Spent the last week working on this and the automation of converting the bootstrap.css to our customized version is mostly done. Progress can be tracked here: btcpayserver/btcpayserver-design#2

**Comment by dstrukt** [comment]
Pushing some additions on a branch tonight @dennisreimann 

Wanted to make some notes for us:

- Consolidate white/black as primitives, separate from Light/Dark

- Consolidate dark & light into 000/50,100,200 .. 900, OR 100,200 .. 900, 950, OR something better, that will include 10 total colors (saw we generate in 100 increments, but might need to adjust that..?)

- Deprecate "secondary" and consolidate completely into Light / Dark

Added dark, but will be adding more colors and will be adjusting some of the existing ones as well.

**Comment by dennisreimann** [comment]
🎉  Bootstrap v5 just got merged in the design repo, also available on the [design system website](https://design.btcpayserver.org/) now.
⏭  Next up: I'll open a PR that integrates the update in the app so that @dstrukt and I can polish and finalize the migration.

**Comment by 9mido** [comment]
Just here to say that bootstrap 5 stable just got released

**Comment by dennisreimann** [comment]
@9mido Thanks for the pointer, I just upgraded the PR #2490 to the final Bootstrap v5.
