### ISSUE TITLE
BTCPay Server Plugins

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#1869]
**Is your feature request related to a problem? Please describe.**
It is increasingly difficult to develop new features for BTCPay Server. I either anger the minimalists because of potential feature bloat, or I anger reviewers because of massive code footprint changes due to tight coupling. There needs to be a way for development to scale without a bottleneck around pleasing both parties. 

**Describe the solution you'd like**
BTCPay Server codebase should be refactored to provide a `BTCPayServer.Base` Nuget package which exposes events, services, contracts. 
Individual features (or a set of features) should be separated (decoupled) from the original codebase and use the `BTCPayServer.Base` too hook into BTCPay Server. Some can be embedded by default into an official BTCPay release, but can be toggled on/off on startup but others should live as separate packages (zip file with DLLs and web resources) that can be added to BTCPay Server by server owners. 

Some examples of current features that could be decoupled and extracted into plugins (that are shipped with official release):
* Payjoin
* BitPay API Compatibility
* Crowdfund app
* POS app
* Lightning
* Changelly/Coinswitch
* Altcoins
* Payment Requests
* Pull Payments

Some examples of new features that can be built as plugins:
* Fiat exchange system
* Email Receipts
* Dedicated centralized e-commerce integrations (shopify)
* Easy setup wizards
* Recurring payment requests
* New apps (marketplace, escrow services, atomic swaps, btctransmuter),
* New payment methods (such as my old Manual payment method PR)
* Dashboard 
* Dashboard individual widgets

**Sketch/Image/Wireframe/Mockup**
BTC Transmuter has a plugin system and all its modules can be added/removed by restarting the application if wanted.  It uses https://github.com/natemcmaster/DotNetCorePlugins but there are minimal dependencies on that library and can be easily removed)

**Describe alternatives you've considered**
* GreenField API but this is a very restricted approach in that it's only good for external integration
* Independent applications to handle the extra functionality such as BTC Transmuter. While this works, it has plenty of downsides:
  * Duplicated code - A lot of functionality had to be duplicated such as wallet management, payment detection, theming, UI etc. This is a huge headache and takes a lot of time not just to code but to test.
  * Limited - Up till now, users were forced to re-register, set up the wallet again, set up email again, etc. GreenField will partially fix this, but it still is an inferior UX, especially if you own both projects that try to bridge to each other, which are also deployed and live alongside each other.
  * Wasteful - We have to start a separate docker container with a bunch of background services doing the exact same thing in BTCPay Server.

**Additional context**
We have a great codebase with great features and performance. I think it is realistic to aim long-term to be the Wordpress (albeit with restraint) of Bitcoin

**Comment by Eskyee** [comment]
having a bare bones BTCPayServer.Base build sounds like a great idea kukks, plus the idea of standard plugins (that are shipped with official release)
 
then expanding BTCPay with other plugins, that the user wants or needs.. this idea reminds me of VST plugins or AU audio units plugin standards, for music software, this was a huge feature in music software back in the day, this helped to set new higher standards for the end producers, plus made the plugin code developers enjoyed their work much more.  end result" Music software became much more popular and easier to use. ie. Logic Pro, Cubase, Pro Tools

We have a great codebase with great features and performance. I think it is realistic to aim long-term to be the Wordpress (albeit with restraint) of Bitcoin .. I agree 100% with kukks here

**Comment by alexk111** [comment]
Agree. That's a great idea to decouple the core of BTCPay Server from the rest things which bloat UI with no real value in many usage scenarios.

By analogy with Wordpress which become an admin panel for posts & plugins, BTCPay Server will be an absolute winner if it turns into an admin panel for invoices & plugins.

**Comment by Kukks** [comment]
> Agree. That's a great idea to decouple the core of BTCPay Server from the rest things which bloat UI with no real value in many usage scenarios.
> 
> By analogy with Wordpress which become an admin panel for posts & plugins, BTCPay Server will be an absolute winner if it turns into an admin panel for invoices & plugins.

You should check out #1981 it contains a full demo of BTCPay +plugins!

**Comment by Kukks** [comment]
Continued in #2006
