### ISSUE TITLE
Add ability to generate a partial refund

### ISSUE THREAD

**Issue by zachherbert** [btcpayserver/btcpayserver#1874]
**Is your feature request related to a problem? Please describe.**
When issuing refunds, we sometimes do not seek to refund the entire transaction. We'd like to instead specify a precise BTC or USD amount to refund. Currently, we manually create a new pull payment in order to accomplish this.

**Describe the solution you'd like**
We'd like to have the ability to specify a custom refund amount after clicking the "issue refund" button on the order details page.

**Sketch/Image/Wireframe/Mockup**
 It could look something like this. Would be cool if there was a way to enter the exact amount of BTC or USD; maybe a text entry field could appear below if selected.

<img width="400" alt="CleanShot 2020-08-28 at 11 54 27@2x" src="https://user-images.githubusercontent.com/14018740/91587791-3f1abc80-e925-11ea-801c-e8d2675a0022.png">

**Describe alternatives you've considered**
The only alternative I could think of is to manually create the pull payment, which we currently do.

**Comment by Kukks** [comment]
I think the main issue here is the amount to refund specification part after you select that option though the description you specified is the simplest and a good starting point. Let me give it a go
