### ISSUE TITLE
Checkout URL incompatible with .onion

### ISSUE THREAD

**Issue by Ruinous101** [btcpayserver/btcpayserver#1881]
Having issue with .onion address for website. 
User loads a cart in tor browser and proceeds to checkout then our btcpayserver is selected. 
URL loads with invoice?id=
User selects the .onion redirect and 404 error is produced. 
When manually pulling the invoice up from the server side it uses a URL with /i/ in place of above. 
Copying this into tor brower and selecting .onion correctly displays the invoice.

**Comment by Ruinous101** [comment]
https://btcpay.minefarmbuy.com/invoice?id=4DN7mQDDRKRF9PQE7EV2aP 

vs.

https://btcpay.minefarmbuy.com/i/4DN7mQDDRKRF9PQE7EV2aP

**Comment by Kukks** [comment]
I see the onion header is not set correctly: `http://juz3qfqadb6pi5qpbajmbi3rplybzvvwvu7eutea7ic5gh5yaav6gaid.onion/invoice`

**Comment by Kukks** [comment]
Please use the issue template next time. You did not provide enough info for me to debug and work with this way.
