### ISSUE TITLE
Address showing as invalid

### ISSUE THREAD

**Issue by Panzercore16** [btcpayserver/btcpayserver#1885]
I try to send momey through btc pay but it says the address is invalid. I tried using two bitcoin methods

First one was though Bitcoin.com and it said invalid address

Second one was xcoins and it said address didn’t exist or was invalid.

Heres the link. https://btcpay.co.ua/invoice?id=P5fERkpJRKPzhF8iTD2mUv 
Serveral attempts have bee made with no success

 I tried everything including copy and paste the address, using different devices and internet. Using different browsers but nothing works. Any help would be appreciated 

Thank you

**Comment by Panzercore16** [comment]
![D627ED3F-784F-4602-A626-3C3AC85773D9](https://user-images.githubusercontent.com/70765814/92255994-79e29e80-eea9-11ea-927d-5909021cd62a.png)
![A524482A-7445-4810-987C-14FE192EB426](https://user-images.githubusercontent.com/70765814/92256035-8961e780-eea9-11ea-99c0-9c9442dbbbc0.png)

**Comment by Panzercore16** [comment]
![FFFCF266-088D-4453-B1E4-F941583CCD9A](https://user-images.githubusercontent.com/70765814/92256175-c4fcb180-eea9-11ea-9a6b-c101e09b0c8a.png)

**Comment by pavlenex** [comment]
See this https://docs.btcpayserver.org/FAQ/FAQ-General/#what-if-i-have-a-problem-paying-an-invoice
