### ISSUE TITLE
Wording/UX Fix: Word "Balance" should be "Transaction Amount" on wallet's list transactions page

### ISSUE THREAD

**Issue by maltokyo** [btcpayserver/btcpayserver#1887]
**Describe the bug**
On the wallet transaction list page, one of the columns is called `"Balance"`.  It should be called `"Transaction Amount"`

https://github.com/btcpayserver/btcpayserver/blob/eb0dee07d83db70d3f153fb7a6c2c12212e386ca/BTCPayServer/Views/Wallets/WalletTransactions.cshtml

**To Reproduce**
1. Go to Wallets in top bar
2. Click on "Manage" of one wallet
3. See image below, that column that says Balance is actually the transaction amount.

![image](https://user-images.githubusercontent.com/1388507/92313245-e785ec00-efc9-11ea-8651-a8008e6ca0bc.png)

I tried to fix myself, but somehow it said I had to make a branch, but I could only make a fork.  Can someone teach me how to "branch" it?

**Comment by Zaxounette** [comment]
Hi @maltokyo !

You can follow this doc for your branch issue: https://docs.btcpayserver.org/Contribute/ContributeWrite/WriteSoftware/

On the string change, it's a nice find, gratz.

Zax.

**Comment by maltokyo** [comment]
Thanks @Zaxounette !  Done!

**Comment by maltokyo** [comment]
Closing as https://github.com/btcpayserver/btcpayserver/pull/1888 will fix this

**Comment by Zaxounette** [comment]
@maltokyo FYI, a tip for your next issue and pull request, when signaling in a PR `Closes #ISSUE-NUMBER` like you did in #1888 the PR will automatically close that issue, so you don't need to manually close it.

**Comment by maltokyo** [comment]
Ah, that's cool, TIL.  Thanks again for your help and for teaching me.
