### ISSUE TITLE
can't 'export as psbt'

### ISSUE THREAD

**Issue by caixiao-1123** [btcpayserver/btcpayserver#1893]
**Describe the bug**

**To Reproduce**
![image](https://user-images.githubusercontent.com/37337093/92559271-d297aa00-f2a2-11ea-9d42-73791af121db.png)

1. buid a transaction
2. click 'review'
3. click'export as psbt',cant download psbt file and return back
![image](https://user-images.githubusercontent.com/37337093/92559520-55206980-f2a3-11ea-8d05-0deba5ec35e4.png)

**Comment by Kukks** [comment]
Not sure what the issue is: 
https://i.imgur.com/gUx4ae9.gif

**Comment by caixiao-1123** [comment]
I thought click 'export as psbt' will download the psbt file，but the page return back
