### ISSUE TITLE
Allow connecting to existing "private" Lightning nodes (unannounced public IP)

### ISSUE THREAD

**Issue by nitramiz** [btcpayserver/btcpayserver#1897]
**Is your feature request related to a problem? Please describe.**
It'd be great to be able to connect to an existing, private Lightning node. In this case, via Charge on the local subnet (i.e. no need for HTTPS, using `allowinsecure=true`).  I understand the need for BTCPay to promote connecting to the node in order to fund channels and pay for invoices, but the store using this BTCPayServer instance has a mechanism to recommend connections to its existing peers with already-funded channels. That way the Lightning node doesn't get all connections directly to it while dispersing funds in the network.  

When you enter the connection string in the UI (e.g. `type=charge;server=http://localhost:8080/;api-token=asdf1234;allowinsecure=true`) and you enable Lightning, the connection "succeeds". But if you click "Test Connection", BTCPay doesn't receive the node's public info from Charge, so it returns `No lightning node public address has been configured`. The same error message can be seen in an invoice's Events log (`BTC: Payment method unavailable (No lightning node public address has been configured`). 

The connection from the BTCPay container to the Charge API works because `/info` returns the node's info.

Currently, the only solution is to make the Lightning node public, which is undesirable.

**Comment by nitramiz** [comment]
@Kukks let's continue the conversation here. What do you have in mind if I wanted to keep the node's public IP unannounced?

**Comment by nitramiz** [comment]
ping @Kukks

**Comment by NicolasDorier** [comment]
I think we fixed it for next release

**Comment by NicolasDorier** [comment]
I can't pinpoint the commit, but I believe we did something recently to solve this problem. Can you test with new release (we release thursday)

**Comment by nitramiz** [comment]
Cool! Will let you know.

**Comment by rockstardev** [comment]
@nitramiz was your problem solved?

**Comment by nitramiz** [comment]
@rockstardev I deployed that release (latest around Sep 30) and the problem wasn't fixed - I couldn't keep the node "private" and had to make it announce its public IP. It works well. But if it the Lightning node info can be kept private, that'd be preferable.

**Comment by pavlenex** [comment]
@nitramiz is this still an ongoing issue?

**Comment by Kukks** [comment]
Yes, there are a few limitations hard coded into BTCPay afair

**Comment by pavlenex** [comment]
Do we want to address this issue @Kukks @rockstardev @NicolasDorier or should we close it?

**Comment by Kukks** [comment]
We should address this especially since checkout v2 doesn't even show the
node info anymore

**Comment by dennisreimann** [comment]
I already fixed this in #4263.
