### ISSUE TITLE
Add Header and Footer to Store App.

### ISSUE THREAD

**Issue by regedittap** [btcpayserver/btcpayserver#1899]
**Is your feature request related to a problem? Please describe.**
There's no option to add footer and header to the store app.

**Describe the solution you'd like**
Add field to add/edit header and footer in the store app settings

**Sketch/Image/Wireframe/Mockup**
![image](https://user-images.githubusercontent.com/8253590/92679464-1221cd00-f35b-11ea-87d3-0b3e8f69b29f.png)

**Comment by pavlenex** [comment]
So you're referring to adding the header/footer script fields in the point of sale app? What would be the use-case for this?
