### ISSUE TITLE
Non-exact BTC payments issue

### ISSUE THREAD

**Issue by Arkaroo** [btcpayserver/btcpayserver#19]
Looks like it's not possible to request bitcoin payments in exact amounts.

Using container: nicolasdorier/btcpayserver:1.0.0.49

Repro steps:
1. Click "Create a new invoice" from the admin panel (e.g. http://localhost:49392/invoices)
2. Set currency to "BTC", set Amount to 1
3. Click "Create"
4. Click "checkout" on the resulting invoice
5. Observe that the amount charged is 1.00010000BTC, approx $1.50USD more than it should be

Expected outcome:
An invoice for exactly 1BTC

Actual outcome:
An invoice for slightly more than 1 BTC

Let me know if you need more info. Cool system by the way, I'm hoping to have it in production in a side-project I'm working on in a few months time :smile:

**Comment by astupidmoose** [comment]
Do you have the "Network Fee" setting turned on in your store settings? 

This will add a .00010000BTC Charge for every expected payment, and I believe its turned on by default.

**Comment by Arkaroo** [comment]
Ah, I did. In that case, I don't understand what the network fee setting is supposed to be doing. It's not setting a transaction fee, that still has to be set by the payee in their wallet, so what's it for?

But that's a separate, far less important issue. I can confirm that when the network fee checkbox under  http://localhost:49392/stores/{$store_id} is unchecked, the issue goes away.

**Comment by astupidmoose** [comment]
> I don't understand what the network fee setting is supposed to be doing.

The network fee is being set to be able to cover some of the cost of sweeping the UTXO's from payments: https://support.bitpay.com/hc/en-us/articles/115002990803-Why-Am-I-Being-Charged-an-Additional-Network-Cost-on-My-BitPay-Invoice-

:)

**Comment by NicolasDorier** [comment]
@Arkaroo imagine that the user send you a payment of 40 USD in one transaction. Because it creates an UTXO, as a merchant, when you will want to spend this UTXO (for example for sending the money to your exchange), you will have to pay around 120 bytes of fees. By default, those fees are passed to the customer, this represent the network fees.

If a user pay the invoice by sending 4 different bitcoin transactions, you will have 4 UTXO, so the fees network fees would be increased by 4 times.
Note that Signature aggregation (also called schnorr sig) would solve this problem, but this is not in bitcoin yet...

You can choose to disable this in your store settings if you don't want it.

Reopen if

**Comment by NicolasDorier** [comment]
Reopening for now, this is a UX problem, the checkout page show the details of the network fees if you click on "1 BTC = XXX USD" header of the checkout page.

**Comment by NicolasDorier** [comment]
@Arkaroo here is a screenshot and where you have to click to see those details

![untitled](https://user-images.githubusercontent.com/3020646/34458296-d9d71034-ee0f-11e7-82c1-f551b4f31124.png)

**Comment by lepipele** [comment]
I've looked at this and you basically can click either on Store name (My Store) or Amount to expand. In other areas of that row cursor is standard arrow and no clicking is possible.

My proposition for making this more intuitive for people like @Arkaroo is:

1. Cursor becomes pointer on that whole row and click anywhere will expand extra data.
2. If that is not enough we can add visual indicator that expansion is possible... either always visible or on hover. Here is proposal of how it would look:

![proposal](https://user-images.githubusercontent.com/5191402/34459537-25108d1c-edb8-11e7-8ed7-518a50b2d938.jpg)

@NicolasDorier let me know if this is direction in which we'll go.

**Comment by NicolasDorier** [comment]
Yeah I think this is just perfect!

**Comment by NicolasDorier** [comment]
Solved by #23

**Comment by astupidmoose** [comment]
Arrows seem to be in a weird spot on v1.0.0.53. You do see the expected functionality when clicking the btc amount , but not the arrows. 

![image](https://user-images.githubusercontent.com/3916318/34653357-9782d098-f39f-11e7-8adb-9f3523d337a2.png)

**Comment by lepipele** [comment]
@astupidmoose I see you posted this: 

> Arrows seem to be in a weird spot on v1.0.0.53. You do see the expected functionality when clicking the btc amount , but not the arrows.
> 
> [image](https://user-images.githubusercontent.com/3916318/34653357-9782d098-f39f-11e7-8adb-9f3523d337a2.png)

It's seems to be deleted since. Was this problem with refreshing page? Like your browser had old CSS and then when you refereshed arrow was properly located?

**Comment by astupidmoose** [comment]
@lepipele 

Yes, it was weird at first however seems to went away and is now in its proper location so im assuming it was a cached issue.

**Comment by lepipele** [comment]
@astupidmoose OK, I'll talk with @NicolasDorier about me doing some kind of bundling with versioning.

That way we can both speed up serving of JS/CSS files plus have clients automatically refresh files when there are changes to JS/CSS without relying on customer doing CTRL+F5.

Thanks for reporting this!
