### ISSUE TITLE
Mark all notifications for update

### ISSUE THREAD

**Issue by Globalebill** [btcpayserver/btcpayserver#1903]
@rockstardev 

At present the check boxes on /Notifications/Index can only be clicked one at a time and on a single page only for bulk updates

It would be beneficial to have
1) a check all on page
2) mark all unread as read on all pages

Thanks

**Comment by Kukks** [comment]
IIRC, we have already done the first part.

**Comment by pavlenex** [comment]
@Globalebill 
Hi, can you please not ignore the [issue template](https://github.com/btcpayserver/btcpayserver/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) when submitting a report, those are there for a reason, so we don't have to go back and forth until we determine the issue.

That said, what's the version you're using, this has been added in 1.0.5.4
![notifications-1-1024x237](https://user-images.githubusercontent.com/36959754/92988609-63ea6480-f4cd-11ea-9fee-e8d53398f2ed.png)

**Comment by Globalebill** [comment]
hi upgraded to v1.0.5.5 and the check box for select all on one page is working good

2nd suggestion is a mark all as read, as it is very time consuming to do a page at a time

![image](https://user-images.githubusercontent.com/63942253/92997028-40113800-f53a-11ea-82b1-2cd9a2e78303.png)

**Comment by Globalebill** [comment]
as a note, selecting 500 page size, then using the check all on page check box, defaults back to 250

**Comment by Globalebill** [comment]
![image](https://user-images.githubusercontent.com/63942253/92997074-94b4b300-f53a-11ea-8234-8d8f225626e5.png)

**Comment by Globalebill** [comment]
ooops

**Comment by Globalebill** [comment]
also a bug, when you select 250 items to bulk "mark as seen" the notification bell total does not decrease

**Comment by Kukks** [comment]
> also a bug, when you select 250 items to bulk "mark as seen" the notification bell total does not decrease

already fixed for the next release.
