### ISSUE TITLE
The previous scan stopped with an error: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by mariodian** [btcpayserver/btcpayserver#1911]
**Describe the bug**
When rescanning a wallet in the "Manage wallet: Rescan" administration, I get the following error after a while:

`The previous scan stopped with an error: Object reference not set to an instance of an object.`

The master public key added to btcpay is "zpub", addresses are native segwit, and the wallet was created in Electrum, has a positive balance and all the incoming txs are from outside of btcpay. 

**Your BTCPay Environment (please complete the following information):**
- commit 0545f6b
- Deployment Method: Manual

**Logs (if applicable)**
Can't seem to force my manual setup to log anything other than `Info`. 

![Screen Shot 2020-09-15 at 3 29 36 PM](https://user-images.githubusercontent.com/3636406/93185285-cb274380-f76f-11ea-9b7a-3eb8c3232e89.png)

**Comment by bolatovumar** [comment]
This error gets set here:
![Screen Shot 2020-09-19 at 7 47 01 PM](https://user-images.githubusercontent.com/1934678/93693167-eb793a00-fab0-11ea-8143-1c6f9d46e07c.png)

The actual error comes from NBXplorer though, not from BTCPay internals (https://github.com/dgarage/NBXplorer).

**Comment by pavlenex** [comment]
@mariodian Do you still have problems with this, any further information on how to try to replicate this?  Since it's manual I guess it'll be hard.

**Comment by mariodian** [comment]
I no longer have the issue. Either it has been fix somehow or there was some problem with my nodes that were resolved. I guess it can be closed.
