### ISSUE TITLE
Can’t register 

### ISSUE THREAD

**Issue by htreamin** [btcpayserver/btcpayserver#1918]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version [available in the right bottom corner of footer] 
- Deployment Method: [e.g. Docker, Manual, Third-Party-hoist]

**Logs (if applicable)**
Basic logs can be found in Server Settings > Logs. More logs https://docs.btcpayserver.org/Troubleshooting/#2-looking-through-the-logs

**Setup Parameters**
If you're reporting a deployment issue run `. btcpay-setup.sh -i` and paste your the parameters by obscuring private information.

**Additional context**

**Comment by htreamin** [comment]
Hi I can’t register to see the remaining amount what I got

**Comment by pavlenex** [comment]
Closing due to inavtivity, if you're still having issue, let us know. Make sure to check how to reset [admin password in docs ](https://btcpay.coingaming.io/Account/ForgotPassword)
