### ISSUE TITLE
Open Lightning payment channel as option

### ISSUE THREAD

**Issue by charlespax** [btcpayserver/btcpayserver#192]
Use case: Alice is ordering a t-shirt online from example.com for 2.65 mBTC. She has Bitcoin, but does not have any funds on the Lightning Network. During checkout she is presented with the option to convert her payment to a Lightning Network channel for an additional small fee of 0.05 mBTC. She agrees and her total is now 2.70 mBTC. After her transaction is complete there is an open Lightning Network channel between Alice and example.com with 2.67 mBTC on the example.com side and 0.00 mBTC on Alice's side. Example.com has an additional 0.02 mBTC on their side as a fee and the remaining 0.03 mBTC is spent for the on-chain transaction fee.

Additionally, on checkout there could be an option for Alice to add additional funds to the channel. For example, if Alice added an additional 1.0 mBTC to the transaction the balance would be 2.67 mBTC for example.com and 1.0 mBTC for Alice.

Benefits:
* Receive Lightning Network funds - Not that Alice has a Lightning Network channel open she will be able to receive a Lightning payment from another individual, employer, exchange, etc..
* Refunds - If example.com wants to issue a refund to Alice, it can be done via Lightning rather than an additional on-chain transaction.
* Using sunk cost - An on-chain payment requires *x* bytes of data and opening a Lightning Network channel requires *y* bytes. Since this transaction would have happened on-chain anyway, there is a sunk cost of *x*. In principle, the additional cost *= y - x*. This is better than making a transaction for the sole purpose of creating a channel.
* Merchants have an incentive to become well-connected nodes and keep funds on the Lightning Network because they can charge an additional fee.

**Comment by Technifocal** [comment]
>Example.com has an additional 0.02 mBTC on their side as a fee

I'm confused what this "fee" you're talking about is. Why wouldn't I, as Alice, just run:

`lncli openchannel --node_key ${pubkey} --connect ${ip}:${port} --local_amt 100000`

Now I've got 100k Satoshis in the channel, and let's say I pay 50k of them on the transaction to the merchant:

`lncli payinvoice ${btcpayserverinvoice}`

Now we've both got 50k and I didn't have to pay any "fees".

>Additionally, on checkout there could be an option for Alice to add additional funds to the channel.

Is there something in the Lightning spec for this? My understanding is that the amount allocated to the channel is however much the client (or user operating the client) deems should be allocated to the channel. Especially if/when AMP comes out one may not even have any direct connections with merchants due to the ability to route large payments through multiple small ones.

**Comment by charlespax** [comment]
> I'm confused what this "fee" you're talking about is. Why wouldn't I, as Alice, just run:
> `lncli openchannel --node_key ${pubkey} --connect ${ip}:${port} --local_amt 100000`

In this example I am assuming Alice is not an expert and lacks the deep knowledge necessary to accomplish that at the command line. For you and I that might be a normal thing to do, but for most other people it is not.

The fee is there to incentivize the merchant to keep their funds in a Lightning channel or to cover the cost of eventually broadcasting a closing transaction on-chain. The merchant has the option to set the fee to whatever they like, including zero.

>> Additionally, on checkout there could be an option for Alice to add additional funds to the channel.

> Is there something in the Lightning spec for this?

I do not know if there is anything in the spec specifically for this. In this example the merchant is constructing a payment request/invoice or Alice to pay. Alice is provided with the option for that transaction to include adding funds to her side of a payment channel.

**Comment by Technifocal** [comment]
>In this example I am assuming Alice is not an expert and lacks the deep knowledge necessary to accomplish that at the command line. For you and I that might be a normal thing to do, but for most other people it is not.

My understanding is that this will be handled by lightning clients, automatically. Either through utilisation of systems such as autopilot (with lnd) or via the UI. I see no legitimate reason to have merchants perform this action.

>The fee is there to incentivize the merchant to keep their funds in a Lightning channel or to cover the cost of eventually broadcasting a closing transaction on-chain. The merchant has the option to set the fee to whatever they like, including zero.

Lightning payments are designed to be kept open. Utilising systems such as AMP (if/when it becomes available) means that keeping tiny channels open with obscure routing still makes legitimate sense.

>I do not know if there is anything in the spec specifically for this. In this example the merchant is constructing a payment request/invoice or Alice to pay. Alice is provided with the option for that transaction to include adding funds to her side of a payment channel.

How would this work then, on a technical level? Unless you're suggesting Alice over pays the merchant who then issues an immediate refund, I don't see this working. If you are suggesting that then I personally feel that this is:

1. a horrendous idea in terms of being trustless.
2. something that the lightning client Alice utilises should have provided in a trustless manor (I.E. What I described [here](https://github.com/btcpayserver/btcpayserver/issues/192#issuecomment-392313909)).

I feel this is a much better suggestion for lightning clients, not merchant solutions.

**Comment by charlespax** [comment]
Take a look at https://dev.lightning.community/overview/

> 2. Initiating Channel Opening. The OpenChannel method begins the channel opening process with a connected peer. Lightning assumes that this is led by a single party. The opening party can specify a local amount, representing the funds they would like to commit to the channel, and a “push” amount, the amount of money that they would like to give to the other side as part of an initial commitment state. One could imagine that instead of sending a standard Bitcoin transaction to pay a merchant, they could instead open a channel with the push amount representing the amount they want to pay, and optionally add some funds of their own, so that both parties can benefit from having a channel available for payments in the future.

**Comment by Technifocal** [comment]
Two issues I see with that:

1. I (personally) see no method of identifying a user who pays through that method
2. This is a channel-opening option, and as the buyer (I.E. Alice) will be opening the channel, this should be in her client, not the merchant software
3. How would you recommend performing this action? Currently BOLT11 only covers encoding transactions to nodes you can route to, but if you cannot route to them, you'll need to open a channel and provide an IP address/port if you cannot find them on the network. There's no defined URI for this, other than a standard `${PUBKEY}@${IP}:${PORT}`, and even that lacks an amount to push.

**Comment by NicolasDorier** [comment]
Paying from customer by pushing the money in a channel is currently flawed. BOLT11 assume that you pay same price for an invoice on chain versus off chain. This is not true, because On-Chain must include the cost of sweeping UTXO.
I started working on a different spec for making that better but nobody will implement it at first.

But what you were trying to do is to pay on-chain and also ask the merchant to create a channel to you if I understand.
I think we should not try to do this during checkout, but maybe as a "BTCPay App" where someone can just pays a merchant to open a channel, standalone.

**Comment by bitcoinshirt** [comment]
I believe the OP is referring to what Bitrefill did. Here's [a good article on exact use-case](https://medium.com/@bitrefill/would-you-like-a-lightning-channel-with-that-48be63a4eef3) which may be easier to understand.

**Comment by charlespax** [comment]
Yes! This is exactly what I'm thinking.

> There are even more technically elegant ways of doing this that would require upgrades to the Lightning protocol

I'd love to know more about the upgrades they're talking about.

I've commented on that article and linked back to this issue.

**Comment by bitcoinshirt** [comment]
I talked with guys from Bitrefill a while ago about them potentially helping us figure this. I was unaware there's an issue. If you want I can try email them and see if they have time to help (though it's holiday season for merchants, so we may better figure it out ourselves)

**Comment by charlespax** [comment]
Reaching out would be nice. I think it would be a good Idea to document any related resources on this github issue, so it is available to any interested developer (I'm not a dev). And to make any other interested parties aware of this github issue.

- Relevant contact at Bitrefill
- Relevant contact at Bitcoin Lightning wallet
- chat discussion threads
- code resources
- specifications

(On a related note, [Lightning Specivication 1.1 proposals](https://github.com/lightningnetwork/lightning-rfc/wiki/Lightning-Specification-1.1-Proposal-States) are out. I scanned it, but did not find anything related to this issue.)

**Comment by pavlenex** [comment]
Unfortunately it seems that this idea never took off. I talked very briefly with someone from Bitrefil and it seems the approach is quite inactive. I'll go ahead and close this one, due to inactivity.
