### ISSUE TITLE
Bug: Inventory in PoS is reset on manipulation via the UI

### ISSUE THREAD

**Issue by mariodian** [btcpayserver/btcpayserver#1921]
The following was reported on Mattermost

> Hi there! I am having issues in my POS store in that the inventory won't update. When I save the settings it reverts the changes to having nothing. Is this a known issue?

I see the bug, I'll fix it.

**Comment by HeadyWook** [comment]
I am still having issues with this. How can i get the inventory section on edit item working? I only have one of each item for sale but in default view as cart, multiple of the same item can be added. Also, after entering 1 as inventory and save, when i go back the inventory section is blank.
