### ISSUE TITLE
Add Bitpay invoice translator/deobfuscator link

### ISSUE THREAD

**Issue by Zaxounette** [btcpayserver/btcpayserver#1923]
**Enhancement request:** Add Bitpay invoice translator to UI/UX

It appears there is no link or mention of the bitpay translator/deobfuscator ( www.YOURBTCPAYINSTANCE.com/translate) in the UI/UX anywhere.
As briefly stated [here](https://github.com/btcpayserver/btcpayserver-doc/pull/725) in the comments it could be a good idea to add it somewhere.

Place it could be mentioned:
* `Server Settings` > `Services` > `Other External Services`

Open for discussion.

**Comment by NicolasDorier** [comment]
Server settings is only accessible to admin, so that's not what we want.
There is several of such context free tooling I want to add (for example a transaction broadcaster).

Ping @dstrukt . I really wished we had somewhere to put those kind of tools.

**Comment by dstrukt** [comment]
Thanks for tagging.

Will keep this is mind as I'm building out the remaining screens!

**Comment by pavlenex** [comment]
Translator is great example of what should be a plugin.

**Comment by Zaxounette** [comment]
> Translator is great example of what should be a plugin.

It is indeed a good idea !

**Comment by Zaxounette** [comment]
#2130 being merged and translator being confirmed obsolete (lol) from what I understand, should this be closed ?

@pavlenex @NicolasDorier

**Comment by pavlenex** [comment]
Yup, closing.

**Comment by Zaxounette** [comment]
> Should be removed from docs as well if we have it, not 100% certain we do.

I'll look into that, boss ! <3
