### ISSUE TITLE
nbxplorer stuck at CoreSynching

### ISSUE THREAD

**Issue by MarcosMe** [btcpayserver/btcpayserver#1926]
**Describe the bug**
My docker btcpayserver is stuck on nbxplorer:
info: Events:         BTC: Node state changed: NotStarted => CoreSynching

btcpayserver_bitcoind is already in the latest block, as confirmed in logs. 
This is hosted in a raspi3 but working before.

**To Reproduce**
1. run ./btcpay-up.sh

**Expected behavior**
Run normally the nbxplorer, and btcpayserver as before.

**Screenshots**
![image](https://user-images.githubusercontent.com/28023775/94170596-2c45ca00-fe88-11ea-85c2-59877e8f2c26.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: 1.0.5.5 (nbxplorer 2.1.42)
- Deployment Method: Docker in raspi3
 - Browser: Firefox

**Logs (if applicable)**
root@raspi3:~# docker logs --tail 10 btcpayserver_bitcoind
2020-09-24T16:01:46Z ERROR: AcceptBlockHeader: block 0000000000000000000d9461e2573e9e9923862a2f457f4596286d6e536741ca is marked invalid
2020-09-24T16:01:54Z socket send error Broken pipe (32)
2020-09-24T16:01:55Z New outbound peer connected: version: 70015, blocks=649792, peer=3413 (full-relay)
2020-09-24T16:01:55Z New outbound peer connected: version: 70015, blocks=649792, peer=3414 (full-relay)
2020-09-24T16:01:59Z ERROR: AcceptBlockHeader: block 0000000000000000000d9461e2573e9e9923862a2f457f4596286d6e536741ca is marked invalid
2020-09-24T16:02:01Z New outbound peer connected: version: 70015, blocks=649791, peer=3415 (full-relay)
2020-09-24T16:02:02Z ERROR: AcceptBlockHeader: block 0000000000000000000d9461e2573e9e9923862a2f457f4596286d6e536741ca is marked invalid
2020-09-24T16:02:05Z New outbound peer connected: version: 70015, blocks=649792, peer=3416 (full-relay)
2020-09-24T16:02:07Z New outbound peer connected: version: 70015, blocks=649792, peer=3418 (full-relay)
2020-09-24T16:02:25Z New outbound peer connected: version: 70015, blocks=649792, peer=3419 (full-relay)
root@raspi3:~# docker logs --tail 10 generated_nbxplorer_1
info: Configuration:  BTC: Transient error 'Verifying blocks...', retrying soon...
info: Configuration:  BTC: Transient error 'Verifying blocks...', retrying soon...
info: Configuration:  BTC: Transient error 'Verifying blocks...', retrying soon...
info: Configuration:  BTC: Transient error 'Verifying blocks...', retrying soon...
info: Configuration:  BTC: Transient error 'Verifying blocks...', retrying soon...
info: Configuration:  BTC: Transient error 'Verifying blocks...', retrying soon...
info: Configuration:  BTC: RPC connection successful
info: Configuration:  BTC: Full node version detected: 190001
info: Configuration:  BTC: Node banlist loaded
info: Events:         BTC: Node state changed: NotStarted => CoreSynching

**Additional context**
It is stuck here for a long time, it was working before for quite some time (more than six months) I've already restart btcpay, update it, clean it, added swap memory, but it is still stuck.
It is not a production server, it is just a side project of mine, nonetheless it can help others if having the same problem.

**Comment by NicolasDorier** [comment]
That's strange, as NBXPlorer is using Bitcoin Core API to know the progress. Can you update your instance? I moved to Bitcoin Core 0.20.1.

**Comment by MarcosMe** [comment]
Hello Nicolas,
Thank you for the feedback. It is really strange since it was working for so long, even with some updates.

I've updated to Bitcoin Core 0.20.1 but still same behavior (I've confirmed bitcoind log is showing the latest block):
root@raspi3:# docker logs --tail 10 generated_nbxplorer_1
info: Configuration:  BTC: Transient error 'Verifying blocks...', retrying soon...
info: Configuration:  BTC: Transient error 'Verifying blocks...', retrying soon...
info: Configuration:  BTC: Transient error 'Verifying blocks...', retrying soon...
info: Configuration:  BTC: Transient error 'Verifying blocks...', retrying soon...
info: Configuration:  BTC: Transient error 'Verifying blocks...', retrying soon...
info: Configuration:  BTC: Transient error 'Loading P2P addresses...', retrying soon...
info: Configuration:  BTC: RPC connection successful
info: Configuration:  BTC: Full node version detected: 200100
info: Configuration:  BTC: Node banlist loaded
info: Events:         BTC: Node state changed: NotStarted => CoreSynching

And the web display still shows the same block number (although the percentage moved to 90% instead of 89%).

Do you have any other WA, or should I just change HW?

Thanks

**Comment by MarcosMe** [comment]
One more log, not sure if relevant:
root@raspi3:/home/admin/BTCPayServer/btcpayserver-docker# docker logs --tail 10 btcpayserver_lnd_bitcoin
LND_CHAIN=btc
LND_ENVIRONMENT=mainnet
Added bitcoin.active and bitcoin.mainnet to config file /data/lnd.conf
Waiting /root/.nbxplorer/btc_fully_synched to be created...

And on /root/ there is no .nbxplorer folder...

**Comment by pavlenex** [comment]
@MarcosMe did you resolve this? You're using non-recommended hardware and what now is quite outdated version, please let us know if you're still having issues.

**Comment by MarcosMe** [comment]
Hello @pavlenex 
Unfortunately I still didn't sort this out, I tried to update to latest version but still same behavior. nbxplorer still stuck in CoreSynching state...
Most likely I will move it to a raspberry pi 4. Is there a way to copy my store to the new HW?

**Comment by pavlenex** [comment]
There's no documented way to copy a store to a new HW at this moment. I'll go ahead and close this issue then, please do let us know if you face similar issues on RPI 4, which is the go-to for hardware in a box setups. RPI3 is simply not powerful enough and causes problems like this.
