### ISSUE TITLE
Support Invoice parameters in the Payment Request API

### ISSUE THREAD

**Issue by gkrizek** [btcpayserver/btcpayserver#1928]
**Is your feature request related to a problem? Please describe.**

Yes, I want to use the [CreatePaymentRequest](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/PaymentRequests_CreatePaymentRequest) API to create a Payment Request for the user. However, a Payment Request automatically create invoices for me from the Request's page. I have no way to customize these Invoices that are auto-generated. Things like `notificationUrl` aren't able to be set. I rely on Webhooks to handle a confirmed payment so in order to use Payment Requests I need to be able to set the notificationUrl.

**Describe the solution you'd like**

When creating a Payment Request, we should be able to set the Invoice parameters used when doing auto-generation from the Requests page. 

**Sketch/Image/Wireframe/Mockup**

Something like an `invoice` object on the request's payload like:

```
{
  "amount": "string",
  "title": "string",
  "currency": "string",
  "email": "user@example.com",
  "description": "string",
  "expiryDate": "2020-09-27T15:07:04Z",
  "embeddedCSS": "string",
  "customCSSLink": "http://example.com",
  "allowCustomPaymentAmounts": true,
  "invoice": {
    "notificationUrl": "https://webhook.after.checkout.com/goeshere",
    ...
  }
}
```

**Describe alternatives you've considered**

Webhooks don't seem to be well defined so I'm not sure the best alternative. Worst case I'll have to do something like polling all invoices. 😬 

**Additional context**

Perhaps maybe an even better solution is to allow a global webhook to be set per Store?

**Comment by Kukks** [comment]
Hi @gkrizek We have had webhooks on a GreenField API level implemented for some versions now which should cover your issue now. We'll probably add more events such as specific ones to  a payment request but the invoice vents should suffice for your needs.
