### ISSUE TITLE
Allow to set feerate suggestion as position from tip. (Mempool)

### ISSUE THREAD

**Issue by Transisto** [btcpayserver/btcpayserver#1932]
![image](https://user-images.githubusercontent.com/388716/94890616-baecb500-044d-11eb-8f2a-6c8c67e5f9cb.png)

For example, Electrum offer this option:
![image](https://user-images.githubusercontent.com/388716/94890707-043d0480-044e-11eb-810d-c6f6e45e5ffe.png)

We find that this option is more reliable when aiming for next block confirmation.

**Comment by NicolasDorier** [comment]
We use https://bitcoin-rpc.github.io/en/doc/0.16.0/rpc/util/estimatesmartfee/ so we sadly don't have much flexibility.
