### ISSUE TITLE
Add captcha/recaptcha in Server Setting Policies to prevent spam sign-ups

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1933]
**Is your feature request related to a problem? Please describe.**
A couple of users and bigger third-party host instances reported bot signups on their servers. 
Since most hosts use SMTP to send verification email, this leads to server not being able to send mass messages due to mail server restrictions (usually) and in some case can lead to suspension of the email account by the provider.

**Describe the solution you'd like**
Add an optional[ Re-captcha](https://www.google.com/recaptcha/about/) or similar alternative in Server Settings > Policies to prevent spam signups.

**Comment by NicolasDorier** [comment]
I think to prevent this the easiest is to let them configure a custom question with a static answer that they can change anytime they have spam.

Spammers in general don't have time to keep up with unpredictable changes.

**Comment by pavlenex** [comment]
Yes I was thinking of suggesting that as well, would be less intrusive privacy-wise though it would have to be a good question. In past, questions worked to prevent spam signups on the forums I used to run. It was a while ago but I assume it's still effective.

**Comment by Eskyee** [comment]
Would be great to brainstorm this spam problem.. Hashcash is a proof-of-work system used to limit email spam and denial-of-service attacks, and more recently has become known for its use in bitcoin (and other cryptocurrencies) as part of the mining algorithm.... we need the future now..  I don't like captcha that much.. but I hate spam even more!!

**Comment by NicolasDorier** [comment]
no fancy tech is better than unpredictable change initiated by a human.

**Comment by Kukks** [comment]
Need to see how this plays in with the users greenfield api

**Comment by mariodian** [comment]
> I think to prevent this the easiest is to let them configure a custom question with a static answer that they can change anytime they have spam.

Depending on what the source of the answer is, any AI should be able to figure this out rather easily. 

I think captcha is a bulletproof idea. However, is there a good enough open source captcha that compares to google's recaptcha?

**Comment by bolatovumar** [comment]
I googled around and it doesn't look like there is much in terms of OSS Captcha solutions. Sounds like the static answer solution proposed by @NicolasDorier might be a good privacy-preserving solution.

Also, see this thread discussing alternatives to Google's reCaptcha:
https://news.ycombinator.com/item?id=20058697

**Comment by mariodian** [comment]
How about using [hashcash](https://hashcash.io/) or some other form of proof-of-work "captcha"? Those are generally opensource.

**Comment by Eskyee** [comment]
I love the hash cash idea... it's strange after all these years.. bots & spam still affect us...

**Comment by Kukks** [comment]
> > I think to prevent this the easiest is to let them configure a custom question with a static answer that they can change anytime they have spam.
> 
> Depending on what the source of the answer is, any AI should be able to figure this out rather easily.
> 
> I think captcha is a bulletproof idea. However, is there a good enough open source captcha that compares to google's recaptcha?

we need a captcha compatible with a REST api  as they can just spam at a greater magnitude through it anyway

**Comment by bolatovumar** [comment]
> How about using [hashcash](https://hashcash.io/) or some other form of proof-of-work "captcha"? Those are generally opensource.

It looks like it's a centralized service? You have to hit their API to check the work (https://github.com/hashcash/jquery.hashcash.io)

**Comment by Eskyee** [comment]
😂 we should get Adam Back on this..     how can we squash spammers & bots 🤖     This is now 2020 😄 the bots are still here

**Comment by mariodian** [comment]
> we need a captcha compatible with a REST api as they can just spam at a greater magnitude through it anyway

Shouldn't it be an authenticated endpoint (with the exception of the very first sign up), anyway?

**Comment by Kukks** [comment]
> > we need a captcha compatible with a REST api as they can just spam at a greater magnitude through it anyway
> 
> Shouldn't it be an authenticated endpoint (with the exception of the very first sign up), anyway?

It is authenticated, but only if the server policy states that user registration is disabled( and thus requires you to be an admin)

**Comment by pavlenex** [comment]
Closing this in favor of #1958 if after v.1.0.6.3 there are reports, we can look into adding this as a another step. For now, our investigation showed that third-party hosts were most likely spammed through the API abuse.
