### ISSUE TITLE
Invoice Summary Doesn't Show Addresses

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#1936]
When you go into an invoice, the BTC address that was expected no longer shows in the invoice summary. 

As a merchant, this is often needed to provide manually to a customer, perhaps after expiry. 

Example:
- Customer places order but doesnt pay
- Customer claims they paid
- Merchant cannot search wallet address as he doesn't know what address was to be paid. 

I think we should add the addresses that are generated back to the invoice summary.

**Comment by NicolasDorier** [comment]
Seems there is already?

![image](https://user-images.githubusercontent.com/3020646/95042478-f8369880-0714-11eb-9566-8baa253a6fc8.png)

**Comment by NicolasDorier** [comment]
Related to https://github.com/btcpayserver/btcpayserver/issues/1541

**Comment by astupidmoose** [comment]
> Seems there is already?
> 
> ![image](https://user-images.githubusercontent.com/3020646/95042478-f8369880-0714-11eb-9566-8baa253a6fc8.png)

This only shows the paid addresses. For a merchant, I need to see all possible addresses from the invoice so I can investigate issues. It seems #1541 is indeed a duplicate. I will close this, and comment there.
