### ISSUE TITLE
Remove lenghty texy from the Pay button H2

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1940]
**Describe the bug**
The pay button heading is a bit too long and doesn't look nice.
I suggest we just leave `Pay Button`

**To Reproduce**
1. Go to Store Settings > Pay Button.'
2. See the lengthy title

**Screenshots**
![Screenshot 2020-10-05 at 18 31 41](https://user-images.githubusercontent.com/36959754/95106858-62f9cb00-0739-11eb-932b-5cac633a39fc.png)

**Your BTCPay Environment (please complete the following information):** `BTCPayServer v1.0.5.6`
- BTCPay Server Version [available in the right bottom corner of footer] 
- Deployment Method: [e.g. Docker, Manual, Third-Party-hoist] Docker

**Additional context**
Add any other context about the problem here. If people think the text is important I'd move it to the next paragraph.

Tip If anybody wants to fix it you can start here `BTCPayServer/Views/Stores/PayButtonEnable.cshtml:`

**Comment by sgracia13** [comment]
Think I could hop on this one?

**Comment by pavlenex** [comment]
@sgracia13 Sure thing, it's all yours 😃
