### ISSUE TITLE
New update notifications released... when clicked,  give a broken URL 

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver#1942]
https://github.com/btcpayserver/btcpayserver/releases/tag/vv1.0.5.6

<img width="279" alt="Screenshot 2020-10-05 at 19 48 51" src="https://user-images.githubusercontent.com/30862925/95119971-be7d8600-0744-11eb-9845-84caf9a669e7.png">

**Comment by pavlenex** [comment]
Yes, noticed this today as well. Good catch. 
Also @Eskyee are you on v1.0.5.6 already and are notified that there's a new version?

Ping @rockstardev

**Comment by Eskyee** [comment]
> Yes, noticed this today as well. Good catch.
> Also @Eskyee are you on v1.0.5.6 already and are notified that there's a new version?
> 
> Ping @rockstardev

yes.. my hack0 is v1.0.5.6 already ... you are correct @pavlenex

**Comment by Kukks** [comment]
fixed with #1944
