### ISSUE TITLE
Allow users to select block explorers from a list or specify their own URL

### ISSUE THREAD

**Issue by wiz** [btcpayserver/btcpayserver#1953]
It would be nice to have a list of popular block explorers to choose from, as well as a user provided custom field, instead of simply hard-coding blockstream.info

Here is the list that Bisq uses: https://github.com/bisq-network/bisq/blob/master/core/src/main/java/bisq/core/user/Preferences.java#L81

**Comment by bolatovumar** [comment]
I wonder where this selection would go. I'm not sure if there is a specific section we could stick this into.

**Comment by Kukks** [comment]
If anything, server settings. Would need an array for each network
