### ISSUE TITLE
Add invoice like print-view for the payment-request

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1957]
**Is your feature request related to a problem? Please describe.**
Once the user pays (or gets paid) a payment request, he may need to print it out and keep for the reference in a more of a formal invoice format.

While for the web, users don't care about the format, for documentation/paperwork it would be nice if our print-view is a bit of more suited for that use-case.

**Describe the solution you'd like**
- Create an invoice-like print-view for payment requests that would show all the relevant data an invoice would usually have
- Some optional fields in the payment request UI might be needed for this?

Builds on aftet #1930 is merged.

**Comment by bolatovumar** [comment]
Looks like payment requests already have this? Or is this specific to pull payments?

![Screen Shot 2020-10-11 at 2 15 12 PM](https://user-images.githubusercontent.com/1934678/95690435-a2f2ff00-0bcc-11eb-8d63-b96027225d51.png)

**Comment by dennisreimann** [comment]
@bolatovumar We redesigned thge payment request and pull payments with #1967. Though they already have a basic print version, this issue is focused on providing a print version that looks like an actual invoice, so that one can use it in ones business accounting/bookkeeping.
