### ISSUE TITLE
Policy for a server admin to limit the accounts per API call 

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1958]
**Is your feature request related to a problem? Please describe.**
This issue builds on #1933 and proposes that certain cases of spam go through the API.

The proposal is to add a Server Setting > Policy which would put a limit on the amount of accounts that can be created per API call.

**Additional context**
In a way I believe both #1933 and this issue can be good protection from a different kind of spam.

@rockstardev @Kukks may be able to expand on the technicalities here. I just opened an issue so we don't forget about it.

**Comment by mariodian** [comment]
Shouldn't the call be authenticated instead (if the admin already exists)? Any arbitrary limits on API calls could easily be circumvented, imo.

**Comment by Kukks** [comment]
> Shouldn't the call be authenticated instead (if the admin already exists)? Any arbitrary limits on API calls could easily be

The aim of the API is to provide a way to rebuild the entire UI if desired. Requiting the call to be authenticated makes this impossible
