### ISSUE TITLE
Invoice labels on the invoice page don't show accurate state for PaidLate and PaidPartial

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1960]
**Describe the bug**
IIt's been reported by @astupidmoose t seems in v.1.0.5.6 we introduced a very bad UI bug that would show `Expired` if the invoice is `PaidLate` or `PaidParial`which can lead to all sorts of troubles.

**To Reproduce**
1. Create an invoice
2. Pay it late ot pay partially
3. Go to invoices, it's marked as expired.

**Screenshots**
![Image Pasted at 2020-10-7 11-37](https://user-images.githubusercontent.com/36959754/95378130-c4f63400-08e3-11eb-946a-1770eae3809d.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version [available in the right bottom corner of footer] v.1.0.5.6
- Deployment Method: [e.g. Docker, Manual, Third-Party-hoist]

**Comment by pavlenex** [comment]
Possibly introduced in #1916

**Comment by Kukks** [comment]
> Possibly introduced in #1916

Nothing to do with it

**Comment by Kukks** [comment]
Seems to be from # <https://github.com/btcpayserver/btcpayserver/pull/1815>
1815
