### ISSUE TITLE
Instant Payment Notification (POST)

### ISSUE THREAD

**Issue by adrastee** [btcpayserver/btcpayserver#1971]
**Is your feature request related to a problem? Please describe.**
No payment notification via HTTP POST request

**Describe the solution you'd like**
Payment notification via HTTP POST request, that includes details of the payment (like Paypal or Stripe etc).

**Describe alternatives you've considered**
Email notification exsits, but it's not parse-able by a server-side langage like PHP. HTTP POST in json notification would be easily parse-able.

Thanks!

**Comment by NicolasDorier** [comment]
You can now use our webhook API.

https://docs.btcpayserver.org/API/Greenfield/v1/#tag/Webhooks/paths/~1api~1v1~1stores~1{storeId}~1webhooks/post
