### ISSUE TITLE
Disable notifications for a store or user

### ISSUE THREAD

**Issue by Rheopyrin** [btcpayserver/btcpayserver#1974]
**Is your feature request related to a problem? Please describe.**
The particular store has about 200 active users (admins and guests). With a large number of new invoices a very large number of notifications are sent. Which, in turn, leads to the fact that the amount of data in the database increases (users do not delete notifications). Also increases the load on the web sockets.

**Describe the solution you'd like**
Introduce the ability to enable/disable notifications for a specific store or a specific user.

**Describe alternatives you've considered**
Add a filter for notifications of invoice events for a specific store or a specific user.

**Comment by pavlenex** [comment]
@Rheopyrin We wanted to add user-preference for notifications in the future, is this what you're asking. Or you want to have this on an admin level and disable notifications entirely for users of the instance. I assume we can have both.

**Comment by Rheopyrin** [comment]
@pavlenex Disabling notification on instance level will reduce the number of open websockets. Perhaps this option will not satisfy everyone. 
I think we need to add filter on the store level to configure notifications for all attached users and user-preference to enable/disable notifications on the user level.

**Comment by brainharrington** [comment]
Is this for email notifications or for the bell icon notifications? Totally agree the ability to customize the notifications would be great

**Comment by pavlenex** [comment]
@brainharrington This issue is for 🔔 notifications. :)
