### ISSUE TITLE
GreenField API: Remaining Invoice work

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#1975]
We have released an incomplete invoice API a few versions ago. 
Notable missing features include:
* a notification system to be alerted on a status change and payment
* an endpoint to fetch existing payments #1901
* an endpoint to fetch payment method details ( current address, payment link, etc) #1901
* an endpoint to set the user email to an existing invoice (if it has not yet been set) similar to how the Checkout UI does it. #1902

**Comment by pavlenex** [comment]
@Kukks I assume we're done with this one?

**Comment by Kukks** [comment]
We have one item left: 
* Update existing invoice metadata

**Comment by NicolasDorier** [comment]
@Kukks I thiink we could add one item: Update Checkout options.
