### ISSUE TITLE
Invoices that are paid late should have a status of "expired(paidLate)"

### ISSUE THREAD

**Issue by jstrnbrg** [btcpayserver/btcpayserver#1976]
**Describe the bug**
In the dashboard, if an invoice was paid late it has a status of "expired(paidLate)".
However when accessing the same invoice via the API, the status field only contains "expired".

It would be great if the status field could also indicate if the invoice was paid late as that would allow us to mark the order as paid in our webshop. 
Without this, we currently have to check the BTCPay dashboard regularly in order to check if there is a "paidLate" invoice.

Webshop: https://shiftcrypto.shop/

**Expected behavior**
I would expect the status field to contain the same value as shown in the dashboard, i.e. expired(paidLate)

**Comment by Kukks** [comment]
Please check the property additionalStatus or exceptionStatus, it is
already available.

**Comment by jstrnbrg** [comment]
Oh awesome "exceptionStatus" is what I was looking for! Thank you :)

Will close issue.
