### ISSUE TITLE
Improve reset password email 

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#1978]
**Is your feature request related to a problem? Please describe.**
Reset password email is very basic copy and looks almost like a phishing email. Users are not able to change this copy (afaik). I think we should try to enhance the copy for users and make it more apparent it is an email from a BTCPay Server.

Currently all it says: 
Please reset your password by clicking here: **link** 

**Describe the solution you'd like**
Now that there is the invite new users link which will send the "reset password" email to this user, I think we should make some copy changes to this email to make it more general and apply to both cases:

- user is resetting password
- user is creating password for the first time

**Additional context**
Possibly something like this: using the word *update* instead of *reset*

Subject: Update Password

A request has been made for you to update the password for your BTCPay Server account. Please click here to update your password. 

Open to any ideas...

**Comment by brainharrington** [comment]
Allowing users to customize the email would be awesome. What I'm already doing manually is basically writing:

Hi <Name>,

Just set up your account for you on BTC Pay Server. Go ahead and click the link below to finish setting up your password.

**Comment by Eskyee** [comment]
Subject: Update Password

A request has been made for you to update the password for your BTCPay Server account. Please click here to update your password.

a better improvement for emails needed, so it doesn't look  like spam, 
I agree with @britttttk 100%

**Comment by bolatovumar** [comment]
> Now that there is the invite new users link which will send the "reset password" email to this user, I think we should make some copy changes to this email to make it more general and apply to both cases:

I wonder if it would make sense to send a different e-mail for when a user is invited vs when a user explicitly requests a password reset. I haven't really looked into this issue so not sure how feasible this solution is.

**Comment by PresidentNick** [comment]
@bolatovumar https://github.com/btcpayserver/btcpayserver/blob/83dd80ae8660115d2db81d90973ce92e5df537f5/BTCPayServer/Extensions/EmailSenderExtensions.cs

Currently, it just builds the email string based on if it's setting or resetting

**Comment by saliehendricks** [comment]
Happy to take a look at this.

Had a quick look at the code. It is fairly trivial to update the copy as per @britttttk's suggestion. 

My change will look something like:

Subject:
Body:
```
A request has been made for you to update the password for your BTCPay Server account. Please click <a href='{link}'>here</a> to update your password. 

Alternatively copy and paste this URL into your browser: 
{link}
```
I think editable email copy sounds cool but it is something that should be tackled as a more wholistic issue. The approach should be discussed amongst the more seasoned devs first.

**Comment by pavlenex** [comment]
#2211

**Comment by Kukks** [comment]
Related #2229
