### ISSUE TITLE
504 Gateway Timeout testing mail settings

### ISSUE THREAD

**Issue by johnwmg** [btcpayserver/btcpayserver#198]
I have btcpayserver installed (using one of the supplied .sh script) at Amazon AWS on a t2.large EC2 instance w/ 600GB storage, using Postfix as my MTA. After sync I have not been able to send email in Email Settings test. I've tried it directly from the instance, and via Amazon SES, and via gmail as an authorized app. I've also tried it w/ other MTAs. 

I just spent an hour with Amazon SES support. All my Postfix settings are correct, and I can send mails via SES using sendmail from my SSH console logged into the EC2 instance without any issues. 

But, when the docker container running btcpayserver tries to send mail using the mail Test - it times out... 

I ran a traceroute from within the container - tracing to my SES endpoint, using 
 docker-compose exec btcpayserver sh 
and it stops at the 1st hop. 

ANY ideas would be appreciated -- but it is definitely something specific to trying to send email from the container in a ubuntu context -- where the MTA is outside of the container -- that is Not working.

**Comment by NicolasDorier** [comment]
* Do you really need emails? Because it does very little for now.
* Are you running latest version? I fixed a bug not long time ago in this area

What settings are you using?

**Comment by johnwmg** [comment]
Nicolas,

Thank you for reply. 

The /Generated/...yml file says image: nicolasdorier/btcpayserver:1.0.2.28
If the update was made after that version I will get fresh copy.

Is there documentation that explains how the email is used by the system? 
I assumed it was for sending receipts to customers – but perhaps that is to be done by the merchant site after IPN?

Regards (and thank you very much for making this system available),
John Wm Gotts

**Comment by NicolasDorier** [comment]
No it does not send receipt to customers.

It is only used when you require a valid email for new users to register to your BTCPay Server.

Receipt should be done at ecommerce level. (or via BTCPay when I'll find time to have proper integration with mailchimp)

**Comment by johnwmg** [comment]
That makes perfect sense.

I was just confused because the setup option was present, but did not say how it was used.

I very much appreciate this new understanding, because I’ve spent many hours trying to make the Test Mail function, and had concluded that without it the system might be incomplete.

Regards,
John

**Comment by NicolasDorier** [comment]
Drop on the slack (http://slack.forkbitpay.ninja/).
I should probably remove this feature as it is now quite useless and you are not the first one who lost time on it.
