### ISSUE TITLE
Create postgres database by default

### ISSUE THREAD

**Issue by openoms** [btcpayserver/btcpayserver#1996]
A new BTCPay Server instance creates with SQlite, then warns about it:
```
warn: Configuration:  SQLite is not widely tested and should be considered experimental, we advise you to use postgres instead.
```
Discussed with @Kukks:
https://chat.btcpayserver.org/btcpayserver/pl/cskt6jesstddtj7kpre47ecfby

**Describe the solution you'd like**
Use postgres database by default when starting a new instance

**Describe alternatives you've considered**
Simply uncommenting the:
```
#postgres=User ID=root;Password=myPassword;Host=localhost;Port=5432;Database=myDataBase;
```
in the settings.config results to BTCPayServer stalling 
```
info: Configuration:  Postgres DB used (User ID=root;Password=myPassword;Host=localhost;Port=5432;Database=myDataBase;)
```
Would need more detailed instructions to use this option.

**Additional context**
Using the RaspiBlitz manual deployment script: https://github.com/rootzoll/raspiblitz/blob/v1.6/home.admin/config.scripts/bonus.btcpayserver.sh

**Comment by Kukks** [comment]
fixed in #1987 

We cannot really  create the postgres like we did with sqlite as you need postgres running as a service, configured and ready to be connected. We do create the database once we connect to the postgres server though.

**Comment by openoms** [comment]
ok, so that adds a dependency.
Unfortunately it does not seem to be available for 32bit ARM (like the current Raspeberry OS is): https://www.postgresql.org/download/linux/debian/
We are in the process of testing for 64bit so might be an option then: https://github.com/rootzoll/raspiblitz/issues/1199

**Comment by Kukks** [comment]
Hmm, I think we build a arm32 docker image with postgres. Maybe you can see
how that's being built? (btcpayserver/dockerfile-deps)

**Comment by Kukks** [comment]
@openoms  We use https://github.com/docker-library/postgres/tree/master/9.6 which seems to run on our arm32 docker image

**Comment by openoms** [comment]
Ok, thanks for the links. Will look into it although the main point of the manual deployment style script is to not need docker. The RaspiBlitz also planned to migrate over to the 64bit Raspberry OS so the next major release might solve this problem too.
