### ISSUE TITLE
Automatic app label gives 404

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1997]
**Describe the bug**
When you click on an `i` tooltip for the automatic labels added in #1916 for the `app` it gives 404, because the URL goes to 
apps/xyz instead apps/xyz/pos for example, so app type is not included which leads to 404.

**To Reproduce**
1. Receive a payment through the pos app
2. Go to Wallets and click on the `i` for the app
4. See 404 page

**Expected behavior**
It should open a link from the app.

**Screenshots**
![image](https://user-images.githubusercontent.com/36959754/96374872-c6dab580-1175-11eb-9515-4391c144d8d6.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version [available in the right bottom corner of footer]  1.0.5.8
- Deployment Method: [e.g. Docker, Manual, Third-Party-hoist]: Docker

**Logs (if applicable)**
Basic logs can be found in Server Settings > Logs. More logs https://docs.btcpayserver.org/Troubleshooting/#2-looking-through-the-logs

**Additional context**
I'm not sure what's expected behavior here. The `x` (remove the label) doesn't work (if the expected behavior is to not remove this then we shouldn't have the `x`.

**Comment by Kukks** [comment]
Actually the url is correct, I added a way for it to resolve the app type
after you hit that url so the bug must be in that part

**Comment by pavlenex** [comment]
@Kukks Have you tested it?
![Capture](https://user-images.githubusercontent.com/36959754/96415583-19a48380-11ef-11eb-8b87-7908390d6b43.PNG)
It gives a 404 for me on 1.0.5.8?

**Comment by pavlenex** [comment]
I also noticed that you can't assign an automatically created label to a TX, there's no reason why I shouldn't be able to do this manually.

![9DE365D6-7571-49F6-8E2A-00ABE5F879F6](https://user-images.githubusercontent.com/36959754/96480702-e1c32d80-123a-11eb-90f4-7d672ab9039a.GIF)

**Comment by Kukks** [comment]
They are special labels, with special specific data attached to them. You
should be able to create plain ones though

**Comment by pavlenex** [comment]
Yeah I can make plain ones, but I was wondering why are they displayed then if they can't be assigned to a TX?
If the goal is not to allow these type of labels to be assigned except for automatically, then we should perhaps hide it, I guess.

**Comment by Kukks** [comment]
Because they're plain text. User can write whatever they want in reality

**Comment by pavlenex** [comment]
Ok, but I can't add another `app` label nor assign the existing one is what I'm trying to say. And if they're displayed there I'd expect they can be assigned. Not a big deal, but just trying to figure out the reasoning it got implemented that way.
