### ISSUE TITLE
Input fiat value form appears only after you populate the amount input

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1998]
**Describe the bug**
When you're trying to send from an internal wallet, in order for `input-group-text fiat-value-edit-input` to appear, you first need to add a numeric value in the amount field.

This user-workflow is a bit weird and we can't assume that user would expect that.

**To Reproduce**
1. Go to Wallet > Send
2. See Amount field (no fiat input)
3. Enter a a numeric value in the amount
4. Fiat form populates
5. Delete randomly added number
6. Input again the value you want to send.

**Expected behavior**
The fiat field should be visible, and if I may suggest it should be somehow clearer that it can be populated.

**Screenshots**

![BC775589-3F15-42D2-AA46-F4381D140E17](https://user-images.githubusercontent.com/36959754/96385511-b6860300-1194-11eb-8997-9cb7d3f88ef8.GIF)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version [available in the right bottom corner of footer] : v1.0.5.8
- Deployment Method: [e.g. Docker, Manual, Third-Party-hoist] Docker
 - Browser [e.g. chrome, safari] Firefox

**Comment by hibroseph** [comment]
Mind if I take this one on?

**Comment by pavlenex** [comment]
Sure @hibroseph feel free to! 🚀

**Comment by dennisreimann** [comment]
For consistency, let's also have it with a white background – I think that'd make it clear, that one can input values there too.
I'd also say we should start off with both field set to 0 and in general not hide the fiat one.

**Comment by hibroseph** [comment]
👍 That's the route I was going.

**Comment by pavlenex** [comment]
@hibroseph any progress on this one or should someone else take-over?

**Comment by hibroseph** [comment]
Yeah I did, I forgot to commit it.

**Comment by pavlenex** [comment]
Closing this one as it's no longer reproducible in v1.0.6.2
