### ISSUE TITLE
Store > Manage your account: Manage your API Keys permissions cannot enable all roles

### ISSUE THREAD

**Issue by oiiahchai** [btcpayserver/btcpayserver#2002]
**Describe the bug**
As store owner, Manage your account: Manage your API Keys, only btcpay.store.canviewinvoices and btcpay.store.cancreateinvoice able to enable, all other cannot enable. I try with system admin apikey with all roles enable i can use this apikey to create pull payment, with store user apikey is respond 403, I can able to create pull payment with Basic HTTP authentication but not apikey.

As system admin I can enable all.

**To Reproduce**
1. Go to 'Manage your account: Manage your API Keys'
2. Click on 'select all roles'
3. only view and create invoice able to enable.

**Expected behavior**

**Screenshots**
https://ibb.co/VJMGXH9
https://ibb.co/FH2tZ0V

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version [v1.0.5.8] 
- Deployment Method: [docker]

**Comment by Kukks** [comment]
There is no `select all roles` option anywhere on that page. I tried to repduce but it worked fine. 
Account->Api Keys -> Generate new key -> tick every checkbox -> save

**Comment by oiiahchai** [comment]
Hello, Thank you for reply.
With system admin, yes I cam create api key with selected permissions.
But with other non-admin user like store owner, only view and create invoice permissions able to create.
Please try with store user.
Thanks

**Comment by NicolasDorier** [comment]
fixed in 1.0.6.3
