### ISSUE TITLE
Add a warning when Unconfirmed (0-comf) is selected as an option in the Store Settings

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2003]
**Is your feature request related to a problem? Please describe.**
It's an increasing trend in the wallets (like [Electrum ](https://github.com/spesmilo/electrum/pull/6641)and [Bluewallet](https://bluewallet.io/features/)) to add a `Cancel` button. Their reasoning for it is different, but on merchant end, it provides a big problem when the UX to double-spend a transaction gets easier.

On our end, we do handle the 0-confirmations properly, but in this issue I'd like to propose that we add a little warring, just as a bit of education on why a merchant may NOT want to do this. 

I suggest we add a little yellowish `warning` when somebody selects this, just so we're sure they understood the implications.

**Describe the solution you'd like**
Add a yellow warning box when user selects `Unconfirmed`. `Choosing to accept an unconfirmed invoice can lead to double-spending and is strongly discouraged.`

**Sketch/Image/Wireframe/Mockup**
![Capture](https://user-images.githubusercontent.com/36959754/96615504-a0498580-1301-11eb-9055-4c6a45349468.PNG)

**Comment by pavlenex** [comment]
Something a bit related in #1330

**Comment by shivaenigma** [comment]
My two cents - Even if merchant has enabled zero confirmation, btcpayserver shouldn't accept RBF transaction to mark the payment paid. It is highly risky in current scenario. Feel free to ignore this if already implemented

**Comment by Kukks** [comment]
> My two cents - Even if merchant has enabled zero confirmation, btcpayserver shouldn't accept RBF transaction to mark the payment paid. It is highly risky in current scenario. Feel free to ignore this if already implemented

Already handled
```
public bool PaymentConfirmed(PaymentEntity entity, SpeedPolicy speedPolicy)
        {
            if (speedPolicy == SpeedPolicy.HighSpeed)
            {
                return ConfirmationCount >= 1 || !RBF;
            }
            else if (speedPolicy == SpeedPolicy.MediumSpeed)
            {
                return ConfirmationCount >= 1;
            }
            else if (speedPolicy == SpeedPolicy.LowMediumSpeed)
            {
                return ConfirmationCount >= 2;
            }
            else if (speedPolicy == SpeedPolicy.LowSpeed)
            {
                return ConfirmationCount >= 6;
            }
            return false;
        }
```
