### ISSUE TITLE
Allow transioning invoices into the "completed" state without going through "invalid"

### ISSUE THREAD

**Issue by shesek** [btcpayserver/btcpayserver#2019]
Currently, you have to mark the invoice as "invalid" first, and only then the option to mark it as "completed" is made available. It would be nice if it was possible to change into "completed" directly.

**Comment by NicolasDorier** [comment]
right now our code is 

```csharp
        public bool CanMarkComplete()
        {
            return (Status == InvoiceStatus.Paid) ||
#pragma warning disable CA1305 // Specify IFormatProvider
                   ((Status == InvoiceStatus.New || Status == InvoiceStatus.Expired) && ExceptionStatus == InvoiceExceptionStatus.PaidPartial) ||
                   ((Status == InvoiceStatus.New || Status == InvoiceStatus.Expired) && ExceptionStatus == InvoiceExceptionStatus.PaidLate) ||
                   (Status != InvoiceStatus.Complete && ExceptionStatus == InvoiceExceptionStatus.Marked) ||
                   (Status == InvoiceStatus.Invalid);
#pragma warning restore CA1305 // Specify IFormatProvider
        }
```
Note than in the future we think getting rid of the complete state, merchants should only care about "confirmed" state.
So I fear that not having a transition to "confirmed" will make problem later.

**Comment by Kukks** [comment]
> right now our code is
> 
> ```cs
>         public bool CanMarkComplete()
>         {
>             return (Status == InvoiceStatus.Paid) ||
> #pragma warning disable CA1305 // Specify IFormatProvider
>                    ((Status == InvoiceStatus.New || Status == InvoiceStatus.Expired) && ExceptionStatus == InvoiceExceptionStatus.PaidPartial) ||
>                    ((Status == InvoiceStatus.New || Status == InvoiceStatus.Expired) && ExceptionStatus == InvoiceExceptionStatus.PaidLate) ||
>                    (Status != InvoiceStatus.Complete && ExceptionStatus == InvoiceExceptionStatus.Marked) ||
>                    (Status == InvoiceStatus.Invalid);
> #pragma warning restore CA1305 // Specify IFormatProvider
>         }
> ```
> 
> Note than in the future we think getting rid of the complete state, merchants should only care about "confirmed" state.
> So I fear that not having a transition to "confirmed" will make problem later.
> 
> @shesek can I ask you why you want to pass directly from New to Complete?
> I started thinking about an API which would allow you to account some payments externally via an API call, so you could accept payment out btcpayserver but still able to have the btcpay invoice paid. This is maybe more what you need.

I often do it myself (new to complete), if you have an app that you want to trigger a successful contribution, you would do this (inventory management, external contributions, etc)

In terms of the state modifications, I would prefer keeping complete instead of confirmed as it fits as a more generic term (confirmed does not make sense when using LN).

**Comment by shesek** [comment]
> @shesek can I ask you why you want to pass directly from New to Complete?

My use case is similar to what @Kukks described, I wanted to update the crowdfunding app total raised amount to account for an off-btcpay donation (using the "Count all invoices created on the store as part of the crowdfunding goal" option).

It was a one-off manual thing, so the API would've been relevant in this case.
