### ISSUE TITLE
Not https on Azure deployment

### ISSUE THREAD

**Issue by tohchi** [btcpayserver/btcpayserver#202]
Sorry for a very fundamental question. I just deployed BTCpay Server using Azure. The URL to the server shows https but I cannot connect using it. When I change it to http, it works.

I would like to make the server securied should I worry about http or https? If so, how can I enable https?

Thanks!

**Comment by NicolasDorier** [comment]
hey, sometimes the HTTPS link take 20 min to set (I don't know why).

Anyway, setup your custom domain before doing anything. This will work.

**Comment by NicolasDorier** [comment]
You can also do `systemctl restart btcpayserver`. For some reason the test certificate sometimes does not set correctly, restarting the service seems to work.

**Comment by NicolasDorier** [comment]
Less barbaric: `docker restart letsencrypt-nginx-proxy-companion` will work fine.

**Comment by tohchi** [comment]
Thanks so much. I am able to use https now. I am working on getting my domain name per your instruction!
