### ISSUE TITLE
PostgreSQL connections spike

### ISSUE THREAD

**Issue by Rheopyrin** [btcpayserver/btcpayserver#2022]
**Describe the bug**
In production we have a large invoices flow. Every ~10-30 minutes the number of connections to the database increases dramatically (from ~10 to maximum of connection pool size).

I suppose the problem is that [there](https://github.com/btcpayserver/btcpayserver/blob/2083954aa5a29b009ad10abf0872938c81ee62b4/BTCPayServer/Payments/Bitcoin/NBXplorerListener.cs#L141) is no limit on the number of parallel threads. With a large number of pending invoices, the application will open a large number of database connections. 
At the moment when too many connections to the database are open, other operations with invoices take too long or fall with a HTTP timeout. It is critical for our payments flow.

In my opinion, using System.Linq.ParallelEnumerable or Microsoft.TPL.DataFlow will limit the number of parallel threads and database connections.

**To Reproduce**
Generate a large number of rows in database table "PendingInvoices".

**Expected behavior**
BtcPay server does not take unlimited number of connections.

**Screenshots**
![image](https://user-images.githubusercontent.com/9480458/97344100-fcc41c00-1890-11eb-9773-edea3c596c00.png)

**Your BTCPay Environment (please complete the following information):**
Deployment method: Docker
Browser: all browsers
Bitcoin Network: mainnet
NBXplorer version: v2.1.36
BtcPay server version: v1.0.5.7
Database engine: PostgreSQL v11.8
Database hosting: AWS RDS
Pending invoices count: 3162
Connection pool size: 255

**SQL Query that runs in each connection**
`SELECT i."Id", i."Archived", i."Blob", i."Created", i."CurrentRefundId", i."CustomerEmail", i."ExceptionStatus", i."ItemCode", i."OrderId", i."Status", i."StoreDataId", p."Id", p."Accounted", p."Blob", p."InvoiceDataId"
FROM "Invoices" AS i
LEFT JOIN "Payments" AS p ON i."Id" = p."InvoiceDataId"
WHERE i."Id" = $1
ORDER BY i."Id", p."Id"`

**Comment by Kukks** [comment]
This is a very interesting issue, as up to now we have not had any direct complaints in terms of scalability around BTCPay (excluding NBXplorer as nicolas refactored it and performs much better now).

**Comment by Rheopyrin** [comment]
@Kukks Unlimited threads - it is bad in any case. 
I think the next problem will be loading a lot of records from "PendingInvoices" table into the memory ;)

**Comment by NicolasDorier** [comment]
@Rheopyrin this is not unlimited threads, this is using the .net thread pool which is limited already. So I doubt your solution will change anything, but let's give a try.

**Comment by Rheopyrin** [comment]
@NicolasDorier My solution did not help. All connections from connection pool are used. 
Do you now another places where there are massive calls of `GetInvoice()`?

**Comment by NicolasDorier** [comment]
@Rheopyrin I am wondering why there is 3000 invoices in pending in the first place. 800 invoices per day is not huge, and the invoices should not be tracked after a day or so...

**Comment by NicolasDorier** [comment]
@Rheopyrin do you build by yourself or use the docker deployment? Because if you build by yourself I have a temporary workaround for you.

The problem is because we do some polling. But this polling is actually useless in normal situation so we can just disable it.

**Comment by Rheopyrin** [comment]
@NicolasDorier I use docker images from docker.io. Where is this polling?

**Comment by Rheopyrin** [comment]
> @Rheopyrin I am wondering why there is 3000 invoices in pending in the first place. 800 invoices per day is not huge, and the invoices should not be tracked after a day or so...

In `PendingInvoices` table I've found invoices that were created a week ago...

**Comment by NicolasDorier** [comment]
@Rheopyrin what is the "Monitoring" setup of your store?

![image](https://user-images.githubusercontent.com/3020646/97444483-8d712980-196f-11eb-96f0-1a882c6b24e3.png)

**Comment by NicolasDorier** [comment]
ah and expiration time as well?

**Comment by NicolasDorier** [comment]
Ping @rockstardev I think the logic of the `ExtendInvoiceMonitor` is wrong which result in invoices always being monitored.

**Comment by NicolasDorier** [comment]
@Rheopyrin the logic is the following:

If an invoice expires, or is confirmed, it is still monitored actively (polled) for the amount of minutes configured.
If the invoice is paid but did not received enough confirmations yet, we extend monitoring of 1H.

**Comment by NicolasDorier** [comment]
I think I will try to change the request to make 1 request instead of 3000.

**Comment by Rheopyrin** [comment]
@NicolasDorier Expiration time is 15 min and monitoring time is one week. 
Invoices that are stuck in this table have `expired` or `expired(paidPartial)` (related payment with confirmations exists) status.

**Comment by NicolasDorier** [comment]
@Rheopyrin ah so the problem is the monitoring time of one week, put it down to 1 day.
The problem will clear out. But anyway, I need to optimize to not make as much request.
I will make a fix tomorrow, but meanwhile put the monitoring time down.

**Comment by NicolasDorier** [comment]
I will make a small release just for you so you can give it a try by pulling the docker file

**Comment by Rheopyrin** [comment]
@NicolasDorier Which tag has a new image?

**Comment by NicolasDorier** [comment]
@Rheopyrin give me 30min, running tests

**Comment by NicolasDorier** [comment]
@Rheopyrin can you pull again the same image/tag (1.0.5.9) I did not do a new release, just rebuilt in place.
My fix should properly fix your issue.

**Comment by Rheopyrin** [comment]
@NicolasDorier Thanks a lot for updated image. Now I'll try to deploy new image but only on pre-prod environment.

**Comment by NicolasDorier** [comment]
Ok let me know. I will go to bed now, if that fix the issue, please close this issue.

Given your graph, it seems that you are right about the problem, because such problem seems to happen periodically, around once every block. If so, this should completely solve the problem.

I think other people never had issues because they run postges and btcpay on the same server, thus there is no latency issues which could cause lot's of connections to open at once.

**Comment by Rheopyrin** [comment]
@NicolasDorier I was wrong. The first solution works too. But it is not optimal.
![image](https://user-images.githubusercontent.com/9480458/97466498-d7481880-194b-11eb-8653-a32937ca5170.png)

Your fix works as well. I've generated ~500 invoices and application doesn't use all connections from the pool.
![image](https://user-images.githubusercontent.com/9480458/97467054-79680080-194c-11eb-8301-887f10ffb0a1.png)

Unfortunately we need to keep in mind that a large number of rows in `PendingInvoices` table will lead to performance problems.

Thank you for fixes.

**Comment by Kukks** [comment]
@Rheopyrin Can you join our chat at chat.btcpayserver.org? We have some more usability and scalability questions for you if you don't mind. :)

**Comment by pavlenex** [comment]
@Rheopyrin would anybody from the company be interested to hop on a call with us to discuss the technical and non-technical issues that you guys had or are having. This type of information is very valuable for us, and would really like to know how we can make the software scalable for the business of that size.

**Comment by Rheopyrin** [comment]
@Kukks Thank you for invitation. I've joined to the chat.

**Comment by Rheopyrin** [comment]
@pavlenex I'll ask our customer support team to provide actual feedback.

**Comment by NicolasDorier** [comment]
@Rheopyrin glad it is fixed. If you can tell us what are the requests in this peak, I can try to batch that as well so it stay completely flat.

**Comment by NicolasDorier** [comment]
@Rheopyrin please also decrease the monitoring time, 1 or 2 days is enough.

**Comment by Rheopyrin** [comment]
> @Rheopyrin glad it is fixed. If you can tell us what are the requests in this peak, I can try to batch that as well so it stay completely flat.

@NicolasDorier I'll enable Performance Insights and collect queries.

**Comment by Rheopyrin** [comment]
@NicolasDorier There were updates of invoice status. I've created 500 invoices simultaneously for testing.

**SQL query:**
`INSERT INTO "InvoiceEvents" ("InvoiceDataId", "UniqueId", "Message", "Severity", "Timestamp")
VALUES ($1, $2, $3, $4, $5)`

On production environment spikes are gone but I continue to monitor the number of connections.

**Comment by Kukks** [comment]
> @NicolasDorier There were updates of invoice status. I've created 500 invoices simultaneously for testing.
> 
> **SQL query:**
> `INSERT INTO "InvoiceEvents" ("InvoiceDataId", "UniqueId", "Message", "Severity", "Timestamp") VALUES ($1, $2, $3, $4, $5)`
> 
> On production environment spikes are gone but I continue to monitor the number of connections.

These are less important, we can create a batching tool to schedule a mass insert every x interval

**Comment by NicolasDorier** [comment]
@Kukks but I don't see how there can be a mass insert of logs...
