### ISSUE TITLE
 1.0.5.9 update  This page isn’t working redirected you too many times.

### ISSUE THREAD

**Issue by regedittap** [btcpayserver/btcpayserver#2026]
This happened after the 1.0.5.9 update

![image](https://user-images.githubusercontent.com/8253590/97459183-76820580-1976-11eb-9aeb-016602bcf33d.png)

**Comment by pavlenex** [comment]
Please do not use issue without filling out the issue template. For non-bug related support please go to chat.btcpayserver.org

**Comment by NicolasDorier** [comment]
I doubt this is related to the update. Can you clear the cookies?

**Comment by regedittap** [comment]
Solved. It was due to cloudflare SSL certificate. Changed to full and it's fixed
