### ISSUE TITLE
Unable to use Prestashop plugin

### ISSUE THREAD

**Issue by Nisaba** [btcpayserver/btcpayserver#2032]
Hi all,

It's probably the wrong place to post this issue and sorry for that.

But these issues don't have feedback :
https://github.com/btcpayserver/prestashop-plugin/issues/19
https://github.com/btcpayserver/prestashop-plugin/issues/23

So, I would like to draw your attention to this problem, since the Prestashop plug in is a important part of the BTCPay ecosystem...

Thank you

**Comment by pavlenex** [comment]
Yes, this is wrong repository, you've already posted the issues there 😃 
@BitcoinMitchell is working on a new release and needs help testing so maybe you can help him, get in touch via chat.btcpayserver.org.
