### ISSUE TITLE
Flyp.me integration

### ISSUE THREAD

**Issue by devnuvo** [btcpayserver/btcpayserver#2034]
**Is your feature request related to a problem? Please describe.**

Present integration with Coinswitch and Changelly requires KYC registraion with these exchanges. Flyp.me is an account less exchange.

**Describe the solution you'd like**

Request to add Flyp.me integration for privacy, until atomic swap implementation.

Flyp.me API: https://flyp.me/en/api/

https://flyp.me/en/#/

**Comment by pavlenex** [comment]
We're actually considering removing all types of integrations like this. Once #2006 is fully ready someone can make this as a separate plugin, but certainly won't be included in the core of the software.
