### ISSUE TITLE
Eclair test connection fails 

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#2036]
**Describe the bug**
Test lightning connection in store when using eclair gives the ui error: 
Error while connecting to the API (Name or service not known). 

**To Reproduce**
1. Go to Store settings
2. Click on Modify Lightning
3. Click Use the internal lightning node of this BTCPay Server instance by clicking here.
4. Click submit & test connection
5. See `Error while connecting to the API (Name or service not known).`

**Expected behavior**
Test connection succeeds.

**Screenshots**

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: v1.0.5.9
- Deployment Method: Configurator deploy to DigitalOcean

**Logs (if applicable)**
eclair container is running but it's log is a long list of this same log:
```
/bin/sh: 1: -Xmx256m: not found
/bin/sh: 1: -Xmx256m: not found
/bin/sh: 1: -Xmx256m: not found
/bin/sh: 1: -Xmx256m: not found
```

**Setup Parameters**
```
-------SETUP-----------
Parameters passed:
BTCPAY_PROTOCOL:https
BTCPAY_HOST:mysite.com
BTCPAY_ADDITIONAL_HOSTS:
REVERSEPROXY_HTTP_PORT:80
REVERSEPROXY_HTTPS_PORT:443
REVERSEPROXY_DEFAULT_HOST:none
LIBREPATRON_HOST:
WOOCOMMERCE_HOST:
BTCTRANSMUTER_HOST:
BTCPAY_ENABLE_SSH:true
BTCPAY_HOST_SSHKEYFILE:
LETSENCRYPT_EMAIL:
NBITCOIN_NETWORK:mainnet
LIGHTNING_ALIAS:
BTCPAYGEN_CRYPTO1:btc
BTCPAYGEN_CRYPTO2:
BTCPAYGEN_CRYPTO3:
BTCPAYGEN_CRYPTO4:
BTCPAYGEN_CRYPTO5:
BTCPAYGEN_CRYPTO6:
BTCPAYGEN_CRYPTO7:
BTCPAYGEN_CRYPTO8:
BTCPAYGEN_CRYPTO9:
BTCPAYGEN_REVERSEPROXY:nginx
BTCPAYGEN_LIGHTNING:eclair
BTCPAYGEN_ADDITIONAL_FRAGMENTS:opt-txindex
BTCPAYGEN_EXCLUDE_FRAGMENTS:
BTCPAY_IMAGE:
ACME_CA_URI:production
TOR_RELAY_NICKNAME:
TOR_RELAY_EMAIL:
PIHOLE_SERVERIP:
----------------------
Additional exported variables:
BTCPAY_DOCKER_COMPOSE=/root/btcpayserver-docker/Generated/docker-compose.generated.yml
BTCPAY_BASE_DIRECTORY=/root
BTCPAY_ENV_FILE=/root/.env
BTCPAYGEN_OLD_PREGEN=false
BTCPAY_SSHKEYFILE=/datadir/host_id_rsa
BTCPAY_SSHAUTHORIZEDKEYS=/datadir/host_authorized_keys
BTCPAY_HOST_SSHAUTHORIZEDKEYS:/root/.ssh/authorized_keys
BTCPAY_SSHTRUSTEDFINGERPRINTS:
BTCPAY_CRYPTOS:btc
BTCPAY_ANNOUNCEABLE_HOST:mysite.com
----------------------
```

**Additional context**
Setup with configurator using [these commands](https://docs.btcpayserver.org/Configurator/#export-manual-configuration)
![image](https://user-images.githubusercontent.com/39231115/97796428-864c5480-1bd7-11eb-9cc0-b5dae821d39c.png)

**Comment by NicolasDorier** [comment]
Fixed by https://github.com/btcpayserver/btcpayserver-docker/commit/f02e4bbd39d201a55dc037f7f49b72b69f3cae9b#diff-bb8e76f029bd7d5419dcd77ae44c9f3265ab62672f457500aa9dd778908cdeeb
