### ISSUE TITLE
Bad translation in checkout screen

### ISSUE THREAD

**Issue by constcast-glitch** [btcpayserver/btcpayserver#2037]
**Describe the bug**
The language option for Norwegian in the checkout screen reads Engelsk.

**To Reproduce**
1. Go to checkout.
2. Click on the language selection drop down.
3. Scroll down and select Engelsk.
4. Note that the language changes to Norwegian.

**Expected behavior**
The option for Norwegian should be Norsk or at least not Engelsk. I'm not Norwegian so not 100% sure.

**Screenshots**
![bild](https://user-images.githubusercontent.com/60033096/97801139-e9230780-1c3a-11eb-99f4-74d26033c51f.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: BTCPayServer v1.0.4.4
- Deployment Method: myNode
- Browser: Firefox

**Comment by britttttk** [comment]
@constcast-glitch thanks for opening an issue to point this out! I have made this change in Transifex. It should appear in the interface in the next update. 

In the future, translation updates can be made in the [BTCPay Transifex](https://docs.btcpayserver.org/Contribute/ContributeTranslate/#requirements). If you find other translation issues, please register an account there to help us make improvements. :)

Note: I have added reference context to this string in Transifex to help translators understand it. As you can see, it was not clear previously.
