### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by mrmstevenson** [btcpayserver/btcpayserver#2039]
**Describe the bug**
Installation is not working on Google VM 

**To Reproduce**
I ran this video exactly 
https://www.youtube.com/watch?v=ltKUzFaer2g&feature=youtu.be

When i browse to the domain I get 
NGINX error - 503 Service Temporarily Unavailable

**Comment by pavlenex** [comment]
Please ask support-related questions on chat.btcpayserver.org we use GitHub only for bug reporting. Check logs of your let's encrypt. There are a bunch of possible solutions on our chat when using a search function and in our docs.
