### ISSUE TITLE
get an error message when trying to buy

### ISSUE THREAD

**Issue by jfds-me** [btcpayserver/btcpayserver#2040]
Hi, i got this message error like this, anyone can help to fix this error? i'm use lunanode server 2gb rame 1core cpu 

11/2/2020 8:47:44 PM:Info Creation of invoice starting
11/2/2020 8:47:44 PM:Info BTC_USD: The rating rule is (bitcoin_com(BTC_USD)) * (0.01, 1.99)
11/2/2020 8:47:44 PM:Info BTC_USD: The evaluated rating rule is (13650.49) * (0.01, 1.99)
11/2/2020 8:47:44 PM:Info BTC (On-Chain): Payment method details creation took 2 milliseconds
11/2/2020 8:47:44 PM:Error BTC: Payment method unavailable (Full node not available)

Thankyou

**Comment by pavlenex** [comment]
Please ask support-related questions on chat.btcpayserver.org we use GitHub only for bug reporting. Your node probably needs to sync first.
