### ISSUE TITLE
"redirect URL" field

### ISSUE THREAD

**Issue by 634-5789** [btcpayserver/btcpayserver#2047]
**Is your feature request related to a problem? Please describe.**
The "redirect URL" is mentioned in stores and apps but can't be set within the btcpayserver web interface.

**Describe the solution you'd like**
There should be a field where the redirect URL can be set to redirect the buyer to a different site than back to the POS store.

**Sketch/Image/Wireframe/Mockup**

**Describe alternatives you've considered**

**Comment by Kukks** [comment]
Please use the issue template.

**Comment by mariodian** [comment]
This feature is available since around 6 weeks ago #1924

**Comment by dennisreimann** [comment]
It's available in the PoS app settings with yesterdays v1.0.6.0 release 👍

![redirect](https://user-images.githubusercontent.com/886/100341557-faaec380-2fdc-11eb-9ed7-3715ff5bf121.png)

**Comment by britttttk** [comment]
@634-5789 please see the issue above which documents redirects in BTCPay.
