### ISSUE TITLE
Notification URL / responses

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#205]
For the invoices you can provide the common Redirect Url but also a Notification Url. The latter is used for updates on payment status (partial payment? expired?; at least thats what I assume).

Sidenote: This way you can also get the payment notification if the user pays but does not hit the redirect url after successful payment or something else breaks on that route.

Logging the response form BTCPay a few interesting things show:

### 1) notification response: orderId vs posData
- the notification response (from BTCPay) does *not* include the `orderId` but `posData` field. Because Order Id missing you can't easily load it but you may need some more complicated logic to load your internal order by the BTCPay invoice ID (which is most likely not that straight forward)

Response:
```
{
  "id": "NBBMjdueu3hrd9bDCmbDH2",
  "url": null,
  "posData": "32",
  "status": "complete",
  "btcPrice": null,
  "price": 0.58,
  "currency": "USD",
  "invoiceTime": 1529272228000,
  "expirationTime": 1529273128000,
  "currentTime": 1529272277186,
  "btcPaid": null,
  "btcDue": null,
  "rate": 0.0,
  "exceptionStatus": false,
  "buyerFields": {
    "buyerEmail": "xxxx",
    "transactionCurrency": null,
    "paymentSubtotals": @ "BTC_LightningLike": 8930,
    "paymentTotals": @ "BTC_LightningLike": 8930,
    "amountPaid": "0.00000000",
    "exchangeRates": @ "BTC": {
      "USD": 0.0
    }
  }
}
```

- in the BTCPay UI you have the order ID shown but *not* the `posData`
![image](https://user-images.githubusercontent.com/1136761/41512636-b37e1480-728c-11e8-8448-fbc9d4453d34.png)

To make this more consistent and assuming that BTCPay already returns the same notification data as the original BitPay API I would suggest to:
- show "posData" also in UI
- BitPay docs suggest that you may also use structured data like JSON in this field too, see
https://bitpay.com/docs/create-invoice

### 2) Notification responses verbose
Makes sense that the server notifies on every status change but this does not look right to me. On payment I get 6 times the same response with payment completed. 
Seems the server keeps sending notification those last payments (not sure if intended or not?) The actual last payment was around 23:30 but now 00:20 server still sends old completed payment notifications, each 3 times:
![image](https://user-images.githubusercontent.com/1136761/41512732-ebbde7a6-728e-11e8-9a88-0e1365536ade.png)

**Comment by NicolasDorier** [comment]
Hey, OK for showing PoS Data in the page.

For callbacks: I prefer not adding the orderId. The reason is that those notifications can be faked by an attacker if he knows the callbackUri. It is best to consider the callback entirely compromised. The attacker knows the callbackUri, because knows the invoice id and querying the invoice by id is not protected by a token for compatibility reason.

The right way to do is to query the invoice on your BTCPayServer by fetching with the invoice id.

For the duplicates, the only reason there can have duplicate is because you don't return HTTP 200.
Can you check your invoice page and see what are the events?

**Comment by ndeet** [comment]
> So query the invoice (you have the invoice id), then fetch the orderId.
Yes, thank you, after looking at it again I did it this way as I was already verifying the invoice + payment status anyway.
Still showing also "posData" in Backend UI may not harm if it is used for a POS system at some point.

ad 2) notification response verbose:
You were right I had an exception after logging the response so the callback was not returning 200 OK and most of the verbosity is gone. 
Minor but still a bit strange is that the notification seems to get fired 3 times in a row (always same response):
![image](https://user-images.githubusercontent.com/1136761/41560347-16feee0c-7347-11e8-8a06-8d4e33fa8aa1.png)

**Comment by ndeet** [comment]
Ok, debugged it a bit more:
The diff between all 3 responses is only the timestamps of `currentTime`

The event log shows that IPN notification is sent after each state change of the invoice:
![image](https://user-images.githubusercontent.com/1136761/41585882-95857804-73ab-11e8-8ce8-91f3ff02ac93.png)

Because of LN payment these are instantly changed and therefore all notifications seemingly triggered at the same time.
The only thing that seems to be wrong is that the `status` should not be "complete" each notification but go through: "paid" -> "confirmed" -> "complete" also for LN payments. Or only send one notification for LN, but I guess it would be more consistent and desired to have all 3 notification state changes for consistency.

**Comment by NicolasDorier** [comment]
Normally the three events also have different status. If not the case, this is a bug.

Yes, for LN the three are sent. Because we don't want to break code which does not know about lightning network we send all events.

**Comment by ndeet** [comment]
Ok, seems the status is always completed on LN. See also the Event log above. **"Invoice status is complete"** seems to be fired before any notifications (assuming events listing is sorted ASC).

my logs: 
`cat log.1 log.2 log.3`
```
@"id":"QwqUzF1ggxa5Lu7yFteZix","url":null,"posData":"34","status":"complete","btcPrice":null,"price":0.29,"currency":"USD","invoiceTime":1529353867000,"expirationTime":1529354767000,"currentTime":1529353884706,"btcPaid":null,"btcDue":null,"rate":0.0,"exceptionStatus":false,"buyerFields":{"buyerEmail":"btc@example.com","transactionCurrency":null,"paymentSubtotals":@"BTC_LightningLike":4318,"paymentTotals":@"BTC_LightningLike":4318,"amountPaid":"0.00000000","exchangeRates":@"BTC":{"USD":0.0}}
@"id":"QwqUzF1ggxa5Lu7yFteZix","url":null,"posData":"34","status":"complete","btcPrice":null,"price":0.29,"currency":"USD","invoiceTime":1529353867000,"expirationTime":1529354767000,"currentTime":1529353884751,"btcPaid":null,"btcDue":null,"rate":0.0,"exceptionStatus":false,"buyerFields":{"buyerEmail":"btc@example.com","transactionCurrency":null,"paymentSubtotals":@"BTC_LightningLike":4318,"paymentTotals":@"BTC_LightningLike":4318,"amountPaid":"0.00000000","exchangeRates":@"BTC":{"USD":0.0}}
@"id":"QwqUzF1ggxa5Lu7yFteZix","url":null,"posData":"34","status":"complete","btcPrice":null,"price":0.29,"currency":"USD","invoiceTime":1529353867000,"expirationTime":1529354767000,"currentTime":1529353884770,"btcPaid":null,"btcDue":null,"rate":0.0,"exceptionStatus":false,"buyerFields":{"buyerEmail":"btc@example.com","transactionCurrency":null,"paymentSubtotals":@"BTC_LightningLike":4318,"paymentTotals":@"BTC_LightningLike":4318,"amountPaid":"0.00000000","exchangeRates":@"BTC":{"USD":0.0}}
```
when you do `git diff --color-words=. log.1 log.2` and `git diff --color-words=. log.1 log.3` you will see only timestamps changed.

**Comment by NicolasDorier** [comment]
indeed. I will need to fix this.

**Comment by ndeet** [comment]
Cool, thank you. 

I just did a normal BTC payment and compared the notification. There the payment status is as expected "paid" for the first notification, followed by "confirmed" after first confirmation. (without waiting I guess after 6 confs it will be "complete"). 👍 

Another small difference/nitpick: the BTC payment provides the `url` of invoice, the LN payment does not.

**Comment by NicolasDorier** [comment]
So for URL is is actually expected

```
            // We keep backward compatibility with bitpay by passing BTC info to the notification
            // we don't pass other info, as it is a bad idea to use IPN data for logic processing (can be faked)
            var btcCryptoInfo = dto.CryptoInfo.FirstOrDefault(c => c.GetpaymentMethodId() == new PaymentMethodId("BTC", Payments.PaymentTypes.BTCLike));
            if (btcCryptoInfo != null)
            {
#pragma warning disable CS0618
                notification.Rate = dto.Rate;
                notification.Url = dto.Url;
                notification.BTCDue = dto.BTCDue;
                notification.BTCPaid = dto.BTCPaid;
                notification.BTCPrice = dto.BTCPrice;
#pragma warning restore CS0618
            }
```

My comments in the code helped me remember why. :p

**Comment by ndeet** [comment]
Agree, as the callback data can't be trusted, only invoice id needs to be returned as we fetch everything in the subsequent request by querying the invoice data.

**Comment by gs63875** [comment]
I did some normal BTC payment. Everything is going fine but got posData always null and Nothing adding to buyer information can anybody have any idea. I'm using form button method.
{  
   "id":"JjX6orxDy7QvtQ9cw8wTCi3XX",
   "url":"https://btcpay123550.lndyn.com/invoice?id=JjX6orDy7QvtQ9cw8wTCi3",
   "posData":null,
   "status":"expired",
   "btcPrice":"0.00000354",
   "price":1.0,
   "currency":"USD",
   "invoiceTime":1543598469000,
   "expirationTime":1543598649000,
   "currentTime":1543598649068,
   "btcPaid":"0.00000000",
   "btcDue":"0.00003254",
   "rate":282794.863934514,
   "exceptionStatus":false,
   "buyerFields":null,
   "transactionCurrency":null,
   "paymentSubtotals":{  
      "BTC":354
   },
   "paymentTotals":{  
      "BTC":3254
   },
   "amountPaid":"0.00000000",
   "exchangeRates":{  
      "BTC":{  
         "USD":0.0
      }
   }
}

**Comment by danielalexiuc** [comment]
> Agree, as the callback data can't be trusted, only invoice id needs to be returned as we fetch everything in the subsequent request by querying the invoice data.

Let's not throw out the baby with the bathwater here. Adequate trust for some can be acheived simply using SSL on the callback url and a secret parameter.

**Comment by NicolasDorier** [comment]
@danielalexiuc no you can't. The callback is public information because the invoice page is not protected (not not break against Bitpay model)

**Comment by danielalexiuc** [comment]
@NicolasDorier I see. Is there anything at all on the invoice that is not public?

**Comment by danielalexiuc** [comment]
@NicolasDorier Nice! I'm not doing this, but there are other services that work this way. I think it's a good idea to keep it private just in case.

**Comment by danielalexiuc** [comment]
@NicolasDorier Can you link to the PR?

**Comment by NicolasDorier** [comment]
1477630c78dc4dcced40db3ea38c80fa50630b6a

**Comment by Kukks** [comment]
@NicolasDorier  @ndeet 

Can this be closed now?  POS Data is displayed on invoice page now and can handle complex json structures too.

**Comment by Kukks** [comment]
There was also a fix for IPNs being buggy a few days ago
