### ISSUE TITLE
Bitcoin RPC remote connection not working, only from bitcoin-cli

### ISSUE THREAD

**Issue by Tragic** [btcpayserver/btcpayserver#2056]
I'm unable to connect to my bitcoin rpc(hosted on a docker at digitalocean) from my localhost or a webhosting.

I've tried changing my config file to accept any connection, i've opened my port using sudo afw but still no luck. I get server connection refused as an error. My config log(details removed)

I am able to perform commands from cli like getnetworkinfo. I've set my server up using BTCPay

When i look at my debug.log i notice that its using loading a diferent config file. from /home/bitcoin/.bitcoin/bitcoin.conf (I am not able to locate this file at all) while mine is located at /var/lib/docker/volumes/generated_bitcoin_datadir/_data

```mainnet=1
[main]
walletdir=/walletdata/mainnet
server=1
daemon=1
rpcallowip=0.0.0.0/0
rpcbind=0.0.0.0

printtoconsole=1
port=39388
maxmempool=500

rpcuser=user
rpcpassword=user
# We need to use rpcauth because we also need cookieauth. rpcpassword disabled cookie file auth.
# Be careful if you copy the line below from the docker-compose.yml! A dollar sign is escaped.
rpcauth=
prune=25000
zmqpubrawblock=tcp://0.0.0.0:28332
zmqpubrawtx=tcp://0.0.0.0:28333
zmqpubhashblock=tcp://0.0.0.0:28334

onion=tor:9050
# rpcuser=
# rpcpassword=
# We need to use rpcauth because we also need cookieauth. rpcpassword disabled cookie file auth.
# Be careful if you copy the line below from the docker-compose.yml! A dollar sign is escaped.
rpcauth=```

**Comment by Kukks** [comment]
Don't post the same issue on multiple repos, it is rude and unhelpfu.
