### ISSUE TITLE
No-JS in crowdfund is not fully functional

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#2061]
**Describe the bug**
@Kukks there are multiple issues in this bug report. I fixed the issue wit the root path being ignored but I haven't done anything for the crowdfund app not working properly with JS disabled. I wasn't sure what the expected behavior is (see my above comment). 
_Originally posted by @bolatovumar in https://github.com/btcpayserver/btcpayserver/issues/2057#issuecomment-723655281_

**To Reproduce**
* Create crowdfund app, disable JS, view it

**Expected behavior**
Crowdfunding should appear active when JS is disabled.

**Your BTCPay Environment (please complete the following information):**
Latest.

**Comment by bolatovumar** [comment]
Looks like this issue was fixed in this PR but wasn't linked there: https://github.com/btcpayserver/btcpayserver/pull/2062

We can close this issue now @pavlenex.

**Comment by bolatovumar** [comment]
I also manually tested it and it works as expected with JS disabled.

**Comment by Kukks** [comment]
Ah great, thanks!
