### ISSUE TITLE
Typo: Your nodes are synching...

### ISSUE THREAD

**Issue by topitsky** [btcpayserver/btcpayserver#207]

**Comment by NicolasDorier** [comment]
where is the typo?

**Comment by topitsky** [comment]
When you first boot up the docker image it says that nodes are *synching*,
while I believe it should be that the nodes are *syncing*

**Comment by NicolasDorier** [comment]
There seem to have a spelling war going on about it http://thelousylinguist.blogspot.com/2010/09/syncing-vs-synching.html

**Comment by NicolasDorier** [comment]
`are synchronizing` should be better maybe.

**Comment by topitsky** [comment]
It just caught my eye. Using the full word here might be more professional looking.

**Comment by NicolasDorier** [comment]
#273cf1adc9d3003ae636669036a5ab683f98b832
