### ISSUE TITLE
Lazily Activate Payment Feature Button goes to 404

### ISSUE THREAD

**Issue by ChrisRxyz** [btcpayserver/btcpayserver#2073]
**Disclaimer**
This is actually from the xpayserver (@xpayserver https://github.com/xpayserver/btcpayserver) fork that created the Ethereum support, which has partly been merged into this repo. This may still be relevant if there are future commits, including this merged into this repo. Also I cant open an Issue on the other repo. If you think this doesnt fit here, please move or mark it, thx.

**Describe the bug**
There is a feature to speed up creation of invoices by lazily loading the payment methods - having the user click an "activate payment method" button before the payment details appear.  
See also: https://github.com/xpayserver/btcpayserver/commit/042e2d2ce013413f1d73f2fde57c76657ca06157
This can be switched on in the store checkout settings. But the url for the POST request seems to be generated incorrectly and also even when the setting is switched off, the ETH and USDT payments show the "activate payment method" button still.
This bug is also present for BTC or LTC payments!

Actual ajax call is sent to something like:
https://btcpay.myserver.org/invoice/BTCLike/activate
or
https://btcpay.myserver.org/invoice/ETH_EthereumLike/activate

=> This results in 404 not found

I think the actual url should be:
https://btcpay.myserver.org/i/{invoiceID}/ETH_EthereumLike/activate
for example:
https://btcpay.myserver.org/i/2dxCPX2szZp5JvnMXX9bWq/ETH_EthereumLike/activate

**To Reproduce**
- Switch to the xpayserver latest version (https://github.com/xpayserver/btcpayserver)
- Enable eth and set it up 
- go to a store in BTCPay server
- check the option "Only enable the payment method after user explicitly activates it" 
- create a payment request and go to "pay"
- click the button "activate payment method"

**Expected behavior**
The payment methods should be activated and show a QR Code 

**Screenshots**
![activate_pay](https://user-images.githubusercontent.com/17290590/99881124-ff0f6100-2c17-11eb-86a5-321d03a420fe.JPG)
![eth1](https://user-images.githubusercontent.com/17290590/99881126-06cf0580-2c18-11eb-84dd-cc9bd267e6fc.JPG)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: BTCPayServer v1.0.5.9 (altcoins)
- Deployment Method: Docker, self-hosted
- Browser: any

**Additional context**

**Comment by pavlenex** [comment]
Does not seem related to this repo. You can try contacting xpayserver through our mattermost.
