### ISSUE TITLE
Shopify Integration, Skips "Review and Pay" page. 

### ISSUE THREAD

**Issue by dylanleclair19** [btcpayserver/btcpayserver#2074]
The Bug: 
When using certain browsers or operating softwares, (everything but Safari on MacOS), during the checkout process using the "Bitcoin with BTCPay Server" option,  after selecting "pay now", the "Pay and Review" stage is completely skipped, no BTCPay Server button is ever shown, and it skips directly to the "Order is Confirmed" page. 

This bug does not seem to occur when using Safari with my MacBook, but every other browser on my laptop, and all browsers on my phone seem to encounter this problem. 

**To Reproduce**
1. Go to www.leclairssugartreefarm.com, view products, add any of the offerings to your cart and click checkout. 
2. Fill out the shipping info (use a Test Test as name and add random address info) and click "Continue to payment"
3. Select "Bitcoin with BTCPay Server" and click "Complete Order".
4. You are redirected to the order confirmation page, displaying "Thank you _____!". The BTCPay Sever invoice button is never displayed. 

**Expected behavior**
1. Go to www.leclairssugartreefarm.com, view products, add any of the offerings to your cart and click checkout. 
2. Fill out the shipping info (use a Test Test as name and add random address info) and click "Continue to payment"
3. Select "Bitcoin with BTCPay Server" and click "Complete Order".
4. You are redirected to the "Review and Pay" page, where the green "Pay with BTCPAY" button is present. Select the button to generate an invoice. Pay the invoice. 
5. Once paid, you are redirected to the order confirmation page, displaying "Thank you _____!". 
fin.

**Screenshots**

Screenshots of path with the bug: 
Checkout: 
<img width="1149" alt="Screen Shot 2020-11-21 at 4 07 00 PM" src="https://user-images.githubusercontent.com/64622239/99887649-ff0d6200-2c13-11eb-8a22-3086b2fcffff.png">

Information: 
<img width="972" alt="image" src="https://user-images.githubusercontent.com/64622239/99887698-6d522480-2c14-11eb-82f5-79e3c6795dfd.png">

Shipping: 
<img width="970" alt="image" src="https://user-images.githubusercontent.com/64622239/99887705-7b07aa00-2c14-11eb-96a3-4c45abc527a0.png">

Payment: 
<img width="974" alt="image" src="https://user-images.githubusercontent.com/64622239/99887712-8fe43d80-2c14-11eb-9a58-4d91a917dc65.png">

*where the issue occurs as it skips directly over "Review and Pay"* 

Order Confirmation: 
![image](https://user-images.githubusercontent.com/64622239/99887732-c9b54400-2c14-11eb-9930-d1892d5186fe.png)

**Screenshots of the correct path: Same steps, except between the payment and order confirmation steps: 

Review and Pay: 
<img width="899" alt="image" src="https://user-images.githubusercontent.com/64622239/99887751-fff2c380-2c14-11eb-905e-4a551436b243.png">
 

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: BTCPayServer v1.0.5.9
- Deployment Method: MyNode BTC
- Browser: Issue arises with every browser except Safari on MacOS 

**Logs (if applicable)**

**Setup Parameters**
If you're reporting a deployment issue run `. btcpay-setup.sh -i` and paste the setup parameters here with your private information removed or obscured.

**Additional context**

**Comment by bolatovumar** [comment]
I can repro the issue. Tried in Safari as well but it just got stuck after I filled out order details and got to the confirmation screen.

I don't know how Shopify integration works so not sure what's going wrong here. Could be some misconfiguration on your end.

**Comment by dylanleclair19** [comment]
Tomorrow I can rerun through the integration. Maybe it is something on my
end, although I am fairly confident I followed the guide to a tee.

**Comment by pavlenex** [comment]
```
GET https://mynode.local:49393/stores/2KQ5tYHfBc1YiVGyAYv25mdy5dLtHSJp9ScgNjZG1RZQ/integrations/shopify/shopify.js net::ERR_NAME_NOT_RESOLVED
```
You can't use Mynode outside of your local environment as far as I know. Try paring with a third-party host or our [demo ](mainnet.demo.btcpayserver.org/)server to make sure that's the issue.
