### ISSUE TITLE
Feature Request: Direct Wallet Integration with TREZOR

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#208]
We have direct wallet integration with Ledger, however, it would also be nice to have Trezor support. This opens the cold storage features to even more merchants who do not have/trust ledger vs trezor. 

I believe trezor should already support this through bridge, but I am not sure. 

Putting this here for future consideration. :)

**Comment by bitcoinshirt** [comment]
I second this suggestion, would really love to see this implemented. 
Perhaps we can ping Trezor guys to help with implementation?

**Comment by ca98am79** [comment]
I agree, but in the meantime it is possible to manually add Trezor XPUB Derivation Scheme to receive payments directly to your Trezor wallet

**Comment by astupidmoose** [comment]
Yes, possible to add the Xpub already, but this is more so for using the "wallet" feature built into btcpay as the ledger does. 

The issue with Trezor and Ledger is the GAP LIMIT is not customizable, and often funds are hidden. The wallet helps with this issue by showing all funds. Electrum also helps with this as an alternative solution, however some alt coins built into BTCpay do not have electrum variations (such as doge) and can could issues. 

Built in Wallet helps this, although it might be a pain to maintain wallets for every altcoin which is added to hardware wallets.

**Comment by pavlenex** [comment]
Related #[1152](https://github.com/btcpayserver/btcpayserver/pull/1152)

**Comment by pavlenex** [comment]
This is possible since the BTCPay Vault has been released.
