### ISSUE TITLE
Payment request description is cut off

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#2084]
**Describe the bug**
Payment request description doesn't show properly when it's a long description. 

**To Reproduce**
1. Create payment request
2. Give it a long description, such as a sentence or paragraph.
3. Click save & view

**Expected behavior**
Text should not be hidden.

**Screenshots**
![image](https://user-images.githubusercontent.com/39231115/100418668-68400b80-3040-11eb-89b8-a69632d3d516.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: v1.0.6.0
- Deployment Method: LunaNode
- Browser: chrome

**Comment by britttttk** [comment]
Also the "Invoice Summary" and "Settled" header text will overlap when the payment request has a scroll, from a long description or several payments 

![image](https://user-images.githubusercontent.com/39231115/100419506-e6e97880-3041-11eb-8fc9-7890106111af.png)

**Comment by dennisreimann** [comment]
I'll take care of this.

**Comment by dennisreimann** [comment]
@britttttk can you test the PR I made?
