### ISSUE TITLE
U2F on Mobile

### ISSUE THREAD

**Issue by jon4hz** [btcpayserver/btcpayserver#2085]
When logging in with a smartphone I did not get any further than the 2FA request. I have added a U2F USB stick but this was not requested on the smartphone. 

**To Reproduce**
1. Add U2F Key
2. Try to log in with a smartphone

**Expected behavior**
Nothing happens and you wont be able to log in.

- BTCPay Server Version:  v1.0.6.0 (altcoins)
- Deployment Method: [e.g. Docker, Manual, Third-Party-host]
- Browser: Android 10 Firefox 83.1.0

**Comment by Kukks** [comment]
Most likely, U2F is not supported on Firefox Android.

**Comment by dennisreimann** [comment]
I can verify it doesn't work on the iPhone in Safari either. Will take a look.

**Comment by jon4hz** [comment]
I suppose @Kukks is right. Never noticed it but for example u2f on github didn't work either.

**Comment by dennisreimann** [comment]
Definitely depends on the OS/browser, but I'm pretty sure it worked for me once.

**Comment by pavlenex** [comment]
@dennisreimann did we resolve his issue with #2086?

**Comment by dennisreimann** [comment]
As far as I see, this is a lack of browser support. In that case, the PR we merged should report the lack of support and male the user aware. That wasn't the case before. 

But to offer those features to a wider range of users, the WebAuthn issue we discussed needs to be addressed.

**Comment by pavlenex** [comment]
Since we have #1564 already opened, I'll proceed with closing this one, thanks for clarifying.
