### ISSUE TITLE
Invoice modal fails in Tor Browser

### ISSUE THREAD

**Issue by elvece** [btcpayserver/btcpayserver#2089]
When loading an invoice after Shopify checkout, the invoice modal briefly appears and then the browser fails with an "Unable to connect" to the `.onion` BTC Pay Server address. I think this is because of a `GET` request attempting to load the `.onion` url over HTTPS. 

From the screenshots, you can see that the `onion-location` response header returns the proper url, and that the failing request which causes the connection failure has a leading `https`. 

<img width="1676" alt="Screen Shot 2020-11-30 at 5 40 20 PM" src="https://user-images.githubusercontent.com/12953208/100683178-0845af80-3335-11eb-9200-fcef732ad508.png">
<img width="1680" alt="Screen Shot 2020-11-30 at 5 48 47 PM" src="https://user-images.githubusercontent.com/12953208/100683190-0bd93680-3335-11eb-87b1-c2237608e3d0.png">

Other Details:
`whitelist_onions` is `True` in `about:config`
This exclusively happens in the Tor Browser and seems to work fine in a Brave Tor window.

Environment:
- BTCPay Server Version: v1.0.6.0
- Deployment Method: Docker/Manual
- Browser: Tor Browser

**Comment by dennisreimann** [comment]
I've tried to look at this, but lack the knowledge to investigate further. @Kukks did you find something?

**Comment by Kukks** [comment]
Will give it a go

**Comment by pavlenex** [comment]
@Kukks Any progress on this one?

**Comment by Kukks** [comment]
> @Kukks Any progress on this one?

Not yet

**Comment by NicolasDorier** [comment]
Do you think it is a bug of the Tor Browser? because the onion-location is correct. Why would they try to query it with https

**Comment by NicolasDorier** [comment]
@elvece we will make a new release this week, this should fix it.
