### ISSUE TITLE
Feature Request: Vertcoin Support

### ISSUE THREAD

**Issue by corbimos** [btcpayserver/btcpayserver#209]
I know everyone is very busy and a BIG thanks to all who take the time to work on this project!

Could we get Vertcoin support in the future? I know it is very similar to litecoin and even the doge as far as it being a btc fork. From what i understand, it should be somewhat easier to implement. I would love to move away from a 3rd party to accept VTC at my store. 

Thanks again!

**Comment by NicolasDorier** [comment]
There is lot's of work involved to make it happens. They need to integrate to NBitcoin.Altcoins, NBXplorer and finally BTCPayServer. Maintainers behind this project should ping me on slack if they have questions about it, but they can take example on the other coins.

**Comment by rockstardev** [comment]
Seems you are in luck @corbimos, somebody just brought up that Vertcoin integration would be a good idea and they are looking for input from community: https://twitter.com/vertbase/status/1042213518974574592

**Comment by Kukks** [comment]
@pavlenex  time to close?
