### ISSUE TITLE
Automatic tx labels "remove" icon

### ISSUE THREAD

**Issue by bolatovumar** [btcpayserver/btcpayserver#2090]
**Describe the bug**

Transactions labels which are automatically assigned such as "invoice" or "payment-request" still have the "x" icon next to them even though they are not actually removable. I don't believe they are supposed to be removable (correct me if I'm wrong) as they are automatically assign and allow the user to filter through different kinds of transactions easily.

![Screen Shot 2020-11-30 at 8 24 59 PM](https://user-images.githubusercontent.com/1934678/100697289-75b00b00-334a-11eb-90ba-4565be80802b.png)

These automatic labels have custom colors and configuration:

![Screen Shot 2020-11-30 at 8 25 42 PM](https://user-images.githubusercontent.com/1934678/100697303-7d6faf80-334a-11eb-8148-89837f00e3be.png)

**To Reproduce**
1. Generate an invoice
2. Pay an invoice
3. Notice you have a new transaction in your wallet
4. Notice it has an "invoice" label
5. Notice it has an "x" icon next to it but clicking it does nothing

**Expected behavior**

I assume the "x" icon should not show up for any of these automatically-assigned transaction labels?

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: v1.0.5.9

**Comment by NicolasDorier** [comment]
They should be removable. Strange it does not work.

**Comment by bolatovumar** [comment]
> They should be removable. Strange it does not work.

Is it actually desirable for them to be removable? Since they are automatically added they are always correct and represent what type of transaction it is.

**Comment by Kukks** [comment]
> > They should be removable. Strange it does not work.
> 
> Is it actually desirable for them to be removable? Since they are automatically added they are always correct and represent what type of transaction it is.

Yeah, the user should be able to remove whatever label they want.

**Comment by Kukks** [comment]
I just tried to replicate locally and it seemed to work just fine, I tried specifically with an invoice label.

**Comment by bolatovumar** [comment]
@Kukks you are running BTCPay locally and can delete the "invoice" label? It doesn't work for me. Every time I try it, I get this exception in the debug console:

![Screen Shot 2020-12-03 at 6 49 47 PM](https://user-images.githubusercontent.com/1934678/101115526-60c8b700-3598-11eb-8fca-6ebc546ffc12.png)

I wonder if this has to do with me being on Mac.

**Comment by Kukks** [comment]
> @Kukks you are running BTCPay locally and can delete the "invoice" label? It doesn't work for me. Every time I try it, I get this exception in the debug console:
> 
> ![Screen Shot 2020-12-03 at 6 49 47 PM](https://user-images.githubusercontent.com/1934678/101115526-60c8b700-3598-11eb-8fca-6ebc546ffc12.png)
> 
> I wonder if this has to do with me being on Mac.

Yeah that looks like a Mac issue that we be seen before. What IDE are you using?

**Comment by pavlenex** [comment]
I'm unable to remove an automatic invoice label as well on a in-production server.
![1E37961C-F4D0-4670-998E-A7256D8251BA](https://user-images.githubusercontent.com/36959754/101139235-8940c780-3611-11eb-94ab-c46a806b0c5f.GIF)

**Comment by bolatovumar** [comment]
> > @Kukks you are running BTCPay locally and can delete the "invoice" label? It doesn't work for me. Every time I try it, I get this exception in the debug console:
> > ![Screen Shot 2020-12-03 at 6 49 47 PM](https://user-images.githubusercontent.com/1934678/101115526-60c8b700-3598-11eb-8fca-6ebc546ffc12.png)
> > I wonder if this has to do with me being on Mac.
> 
> Yeah that looks like a Mac issue that we be seen before. What IDE are you using?

VSCode

**Comment by NicolasDorier** [comment]
could reproduce on public servers... strange will take a look today

**Comment by NicolasDorier** [comment]
Digged around, the issue is caused by `\r\n` versus `\n`.

What we search to delete has `\r\n`, but what we actually store is `\n`. Trying to find where this problem comes from.

**Comment by NicolasDorier** [comment]
So the bug come from MVC which silently add `\r` on strings submitted in a POST

**Comment by NicolasDorier** [comment]
Digging deeper, it seems that it is the browser which insert `\r\n` when it POST!

**Comment by NicolasDorier** [comment]
Digging deeper: This is part of the HTML spec

https://www.w3.org/MarkUp/html-spec/html-spec_8.html#SEC8.2.1


> The form field names and values are escaped: space characters are replaced by `+', and then reserved characters are escaped as per [URL]; that is, non-alphanumeric characters are replaced by `%HH', a percent sign and two hexadecimal digits representing the ASCII code of the character. Line breaks, as in multi-line text field values, are represented as CR LF pairs, i.e. `%0D%0A'. 

Which mean that if we have a field's value with `\n`, when the user POST it, it will be converted to `\r\n`. Ping @Kukks this is a big gotcha here.
