### ISSUE TITLE
Manually set invoices in BTCpay to Paid/Completed

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#21]
Sometimes an invoice expires and the customer has paid it after the fact (Exchanges) but the merchant would like to process the invoice anyways. 

In order to have consistent records, we will need a way to manually change the invoice status to paid/completed. 

Perhaps also setting these allows the cart to continue monitoring for confirmations?

**Comment by NicolasDorier** [comment]
This seems doable. I will need to check whether it breaks some logic though.

**Comment by bitcoinshirt** [comment]
With #9 being added, this feature becomes a must. 
To make our reports more accurate, we need a way to change payment status.
For example, if an invoice is invalid and I want to honor it regardless, I want to be able that to reflect in my export.

**Comment by NicolasDorier** [comment]
should notifications be sent?

**Comment by bitcoinshirt** [comment]
Yes, that would be great if possible.

**Comment by NicolasDorier** [comment]
Done in b5c9a030527dfee2753bb46bb4f876a48dcaf3d0 , this allow the merchant to set Invalid or Complete state manually. The ExceptionStatus will be set to "marked".
