### ISSUE TITLE
Some people experience issues with notificationURL and IPN

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#2102]
Since v1.0.6.0

![image](https://user-images.githubusercontent.com/3020646/101122567-231a6b80-3636-11eb-9ed8-f76355076d7f.png)

**Comment by NicolasDorier** [comment]
![image](https://user-images.githubusercontent.com/3020646/101122643-4fce8300-3636-11eb-96bf-c6d546f9ef1e.png)

**Comment by NicolasDorier** [comment]
I need more inputs, as I can't reproduce it.
Does the invoice show notificationURL in the invoice details?

**Comment by freeride554** [comment]
> I need more inputs, as I can't reproduce it.
> Does the invoice show notificationURL in the invoice details?

No, the invoice details have now all an empty notificationURL. No code has been changed.

**Comment by Kukks** [comment]
![image](https://user-images.githubusercontent.com/1818366/101259582-f2b3f980-3729-11eb-85b0-bc1f5e4f3aea.png)

**Comment by pavlenex** [comment]
It seems this one was resolved then as we have no more complains?

**Comment by Kukks** [comment]
Yeah, seems like it was just user error.
