### ISSUE TITLE
API key creation problem

### ISSUE THREAD

**Issue by maximkozlov** [btcpayserver/btcpayserver#2107]
Problem was found on https://mainnet.demo.btcpayserver.org/
Version 1.0.6.1

1. Go to 'Profile' -> 'API Keys'
2. Click 'Generate new key' button
3. Tick all checkboxes to add all possible permissions
4. Click 'Generate API Key' button

Expected:
API Key was created with all set permissions

Actual:
API Key was created with the following permissions:
 - btcpay.store.canviewinvoices
 - btcpay.store.cancreateinvoice
 - btcpay.store.webhooks.canmodifywebhooks

Screenshots
![image](https://user-images.githubusercontent.com/4731435/101241961-a35ed080-370b-11eb-8b27-8a84df1d0e47.png)
![image](https://user-images.githubusercontent.com/4731435/101241965-a954b180-370b-11eb-9dbb-23f5b1f72faf.png)

Additional:
It can't be reproduced in 1.0.6.0 but It can be reproduced in 1.0.5.9.

**Comment by oiiahchai** [comment]
Hello. Similar problem reported #2002. Only admin user can create all permissions. Store owner can create view/create invoice. 

I solve it with create script greenfield api POST
/api/v1/api-keys to create selected permissions. Is not convenient.

**Comment by NicolasDorier** [comment]
thank you, looking at it.

**Comment by NicolasDorier** [comment]
Could reproduce in regtest

**Comment by NicolasDorier** [comment]
Will release this week the fix in new version.

**Comment by NicolasDorier** [comment]
released fix in 1.0.6.3
