### ISSUE TITLE
Feature Request: Add CSS customization to Pull Payments (& concurrently Refunds)

### ISSUE THREAD

**Issue by Zaxounette** [btcpayserver/btcpayserver#2108]
**Is your feature request related to a problem? Please describe.**
Currently, it's possible to customize the public view of `Payment Requests` using either pre-made bootstrap files, or inserting custom CSS code to be rendered on the `Payment Request` page.

**Describe the solution you'd like**
Such customization is currently missing from the `Pull Payment` feature.
Additionally, It could be nice to also have it included while issuing a `Refund` as well, not only a direct Pull Payment creation.

**Additional context**
 CSS Customization in the `Payment Request` feature currently missing in `Pull Payments` (Screenshot pulled from the Documentation):
![100981726-7792ed80-3547-11eb-8407-0054382f80ca](https://user-images.githubusercontent.com/51208677/101246792-c42c2380-3715-11eb-8c3e-a9894076dbd1.png)

This feature request follows a discussion with @dennisreimann earlier this week.

**Comment by bolatovumar** [comment]
@dennisreimann are you looking into this or should I try looking into it?

**Comment by dennisreimann** [comment]
@bolatovumar go ahead :)

**Comment by pavlenex** [comment]
Added in #2113
