### ISSUE TITLE
Crowdfund Pay Button and Manual Reset

### ISSUE THREAD

**Issue by Dinglebarry9** [btcpayserver/btcpayserver#2112]
When navigating to a Pay Button for a Crowdfund App the response is the InvoiceID and not a Checkout like with a POS App.
Also is there a way to manually reset contributors and total raised?

**Comment by Kukks** [comment]
Please use the issue template next time.

**Comment by Kukks** [comment]
> Also is there a way to manually reset contributors and total raised?

No, create a new crowdfund app for that
