### ISSUE TITLE
Remove conversion tab for the LN

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#212]
Is there a usecase for the conversion tab, when the LN payment is selected?

Is it here because of the submarine swaps in future?

If not, can we remove it as it appears to mislead that users can convert other currencies to Bitcoin and pay merchant.

![screen shot 2018-07-03 at 13 04 33](https://user-images.githubusercontent.com/36959754/42216405-011dfc50-7ec2-11e8-848f-3267fd8dc3e2.png)

**Comment by rockstardev** [comment]
It UI problem - if you start hiding and showing Conversion tab you would have Scan & Copy "dancing"  left and right on currency switch.

I would leave it as is for now - could be useful for submarine swaps in future as you mention.
