### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by HeadyWook** [btcpayserver/btcpayserver#2126]
**Describe the bug**
Inventory not working. Users can add multiple of same item in cart view even after setting inventory for that item to 1 (or any number). Users are able to generate invoice with incorrect inventory. No warning message is given that they selected more than the given inventory amount. Also, after saving inventory as 1 (or given number), upon returning to that item for editing, inventory displays as blank.

**To Reproduce**
1.  In apps, under settings, set default view to 'cart'.
2. Edit item inventory to 1 or desired amount and save changes. Also, save settings for app at bottom of page.
3. View app in new tab and select item. Continue selecting and user will be able to add more than set inventory. Select confirm and pay and an invoice is generated with no warning that there was only X number of inventory available.
4. Go back to app settings and select 'edit' on item for which inventory was set and you will see the inventory field is blank.

**Expected behavior**
It should be expected that the user is only able to select the item up to the inventory limit or a message displayed that there is only X number of that given item. Also, the user should not be able to generate an invoice when selecting more than the set inventory.

**Screenshots**
N/A

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: v1.0.5.3
- Deployment Method: BTCPay Jungle
- Browser: Mozilla and Tor

**Logs (if applicable)**
N/A

**Setup Parameters**
N/A

**Additional context**
N/A

**Comment by pavlenex** [comment]
I cannot replicate this _entirely_ on v1.0.6.2.

- When the items in cart are added and paid for the inventory decreases normally.
- When the inventory is 0, the message `Sold Out is displayed on the cart view.
- However, when item is `sold out` it can still be added to the cart, but cannot proceed to the checkout.


> Expected behavior
It should be expected that the user is only able to select the item up to the inventory limit or a message displayed that there is only X number of that given item. Also, the user should not be able to generate an invoice when selecting more than the set inventory.

All of this is already happening. I think what you mean is that inventory doesn't change when item is added to the cart. We change it only when item is paid, which in my opinion is expected and normal behavior. https://streamable.com/fgqjlh

To conclude:
What we can do:
- What we can solve here is if the inventory is `0` don't allow item to be added to cart.
- Don't allow item to be added to the cart if items in cart > inventory.
- Display an error message if user edits the inventory manually and that's > inventory set.

Ping @bolatovumar this seems like something that may be interesting to you to figure out, I just briefly touch on the issue, but could be something that requires more digging.

**Comment by Kukks** [comment]
Please try and update from 1.0.5.3 to the latest and see if your issues are resolved. There was a bug fix in the last release regarded to properly saving the inventory when editing a pos app.

**Comment by Eskyee** [comment]
Hosted site now updated 
Deployment Method: BTCPay Jungle v1.0.6.2.

**Comment by pavlenex** [comment]
@HeadyWook Can you try again?

**Comment by HeadyWook** [comment]
It works now that the hosted site is v1.0.6.3! Thank you!
