### ISSUE TITLE
Add Autocomplete signing 

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#213]
The idea from Build on Bitcoin talk from the audience [4h37m3s](https://youtu.be/XORDEX-RrAI?t=4h37m3s)
The basic suggestion was to allow hardware wallet to sign and auto-complete transactions.
Leaving it here as a reminder.

**Comment by NicolasDorier** [comment]
it concerns only transactions which are provably giving you money. This can only be the case once some passive income feature are developped. (like coinjoin market provider)
