### ISSUE TITLE
Redesign of the notification's dropdown

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#2131]
Follow up from https://github.com/btcpayserver/btcpayserver/pull/2101

I decided to merge @bolatovumar PR as it is a needed feature in the short term.
That said, I agree that the design is less than ideal and should be improved.

FROM @dstrukt

----------------
In my true fashion, I'm presenting a few options :)

My personal favorite is Option B, the right (with more padding), all based on the 4px base (4, 8, 16, 24, etc...).

I realize this would be a bit more work, but this notification overlay was an area I wanted to address, so I thought I'd go ahead and share something a bit more ambitious with this addition, it's all cosmetic, but if it's out of scope, I understand.

Option A, extending the current version with a similar pattern.

Option C, a modified version with everything on the bottom, which I suppose I could make an option D using the current text + date with everything on the bottom, but I'm not particularly a fan of this direction, so I didn't

As for the "eye" icon, I'm ambivalent, I could take it or leave it, with the addition of (potential) future icons however, it's cleaner not to have it, but for the current state .. shrug.

As usual, open to any and all feedback!

![image](https://user-images.githubusercontent.com/3020646/101975958-20e28d80-3c84-11eb-91bc-92e0504e326f.png)
--------------

**Comment by dstrukt** [comment]
Add the resolution of where we landed as well, top right and bottom right (for multi-line), we decided to remove the "eye" icon, so disregard, but for the sake of comparison, I left.

+ Figma link:
https://www.figma.com/file/C7Xyq0FlxgFW8vaBr8ht1z/BTCPAY?node-id=2561%3A2310

<img width="1440" alt="Notifications0 2" src="https://user-images.githubusercontent.com/6250771/102000202-da982900-3c99-11eb-9d69-a9ca16b426a4.png">

**Comment by bolatovumar** [comment]
Starting on this.

**Comment by pavlenex** [comment]
#2167
