### ISSUE TITLE
Payment Request: "Pay Invoice" button doesn't generate invoice

### ISSUE THREAD

**Issue by ArbenKarb** [btcpayserver/btcpayserver#2147]
**Describe the bug**
"Pay Invoice" button from payment request doesn't generate invoice

**To Reproduce the bug**
1. Create Payment request
2. Specify payment request details
3. save
4. view
5. hit "Pay Invoice" button

**Expected behavior**
Should generate invoice with QR code as it does when clicking "pay" on the payment request page:
![image](https://user-images.githubusercontent.com/31412198/102410553-ffb9ce00-3ff0-11eb-9bea-9e89b06d6168.png)
![image](https://user-images.githubusercontent.com/31412198/102410773-50c9c200-3ff1-11eb-944c-f56b2f4035b6.png)

**Your BTCPay Environment (please complete the following information):**
- Btcpayserver v1.0.6.2
- self hosted (mynode on raspi)

**Comment by pavlenex** [comment]
Are you able to create invoice manually without payment request?
Cannot replicate in 1.0.6.3. Since this is not official setup, you should try looking through the logs, perhaps Mynode is blocking it.

**Comment by ArbenKarb** [comment]
Yes, I am even able to create invoices from the payment request setup page here:
![image](https://user-images.githubusercontent.com/31412198/102412042-3b559780-3ff3-11eb-91ce-c8d04ab622cd.png)

Unable to do so out of the actual payment request

**Comment by pavlenex** [comment]
Check console logs in your browser that may tell you the issue or share a link to the payment request. Perhaps modal is being blocked in some way.

**Comment by ArbenKarb** [comment]
Tried both firefox and chrome (including mobile) 

![image](https://user-images.githubusercontent.com/31412198/102413329-0b0ef880-3ff5-11eb-80c8-5ddee0032494.png)

seems there might be an issue with the network /dns config

**Comment by ArbenKarb** [comment]
This is what I get when I try to open the link as per console log:

![image](https://user-images.githubusercontent.com/31412198/102417995-2bdb4c00-3ffd-11eb-8245-af08a676f527.png)

**Comment by pavlenex** [comment]
No idea, make sure your mynode is not hosted locally and that it's available outside of your local network. As I said they use custom setups that we aren't familiar with so best to contact their team and check.

**Comment by pavlenex** [comment]
Closing since it's being troubleshooted in appropriate repository. Feel free to let us know once solution is found there.

**Comment by cercatrova21** [comment]
Any ideas what the problem was on this issue? I have the same right bow with my btcpayserver. (Also hosted on a raspiblitz)

**Comment by pavlenex** [comment]
@cercatrova21 probably your node is down or you need to configure a wallet. Try manually creating an invoice inside btcpay server.

**Comment by cercatrova21** [comment]
> @cercatrova21 probably your node is down or you need to configure a wallet. Try manually creating an invoice inside btcpay server.

My node is up, and manually creating an invoice works perfect. Only creating the invoice with the pay button doesn't work. Also with the crowdfunding App: same issue. When I click contribute, nothing happens

**Comment by pavlenex** [comment]
Come to chat.btcpayserver.org so we can troubleshoot.
