### ISSUE TITLE
Problem when manually importing BIP32 derivation path

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2149]
**Describe the bug**
When user imports externally generated xpub it's impossible to find a match.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to 'Electrum`, create legacy wallet, copy xpubkey.
2. Add xpubkey to btcpay
4. See address match - fail
5. Try to find a match by adding it into a hint field - fail

When you try with zpub the problem doesn't happen. 

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: 1.0.6.3 and 1.0.6.2   
- Deployment Method:     Docker   
- Browser:       Firefox 

**Logs (if applicable)**
Nothing much besides this which isn't weird in nbx
```
info: Events:         BTC: New block 000000000000000000078b5f45cda077c8b1e3d32415af997b4026657a2473d2 (661406)
info: Events:         BTC: xpub6CQirZ...UJDvSHMCdgFaeeosZXU1 matching unconfirmed transaction cd7554...7fa72a (0/70)
info: Events:         BTC: New block 00000000000000000000554e4db347ead7e88066d80c2e4c919c805835934f2c (661407)
info: Events:         BTC: New block 00000000000000000008521e70152dafbfc5994d2096f628c1965c343534e14b (661408)
info: Events:         BTC: xpub6CQirZ...UJDvSHMCdgFaeeosZXU1 matching confirmed transaction cd7554...7fa72a (0/70)
```

**Setup Parameters**

**Additional context**

**Comment by pavlenex** [comment]
Doesn't work for me, please try with Electrum of Ian Coleman site, you're using hot wallet feature and it's not the same it seems.

**Comment by Kukks** [comment]
> Ian Coleman

BIP32 is the HD address definition (how to create infinite addresses from one key)
BIP39 is the seed phrase definition ( how to create one key from a set of words)
BIP 44 defines legacy address derivation paths using BIP32
BIP 49 defines P2SH derivation paths using BIP32
BIP 84 defines segwit derivation paths using BIP32

I need to dig into Electrum a bit and see what they do

**Comment by pavlenex** [comment]
@Kukks Ugh I was typing this at 1AM all worried, will dig in deep in a moment, but one thing is certain electrum doesn't work, neither do a few more wallets reported on Mattermost.

**Comment by Kukks** [comment]
> @Kukks Ugh I was typing this at 1AM all worried, will dig in deep in a moment, but one thing is certain electrum doesn't work, neither do a few more wallets reported on Mattermost.
> 
> ` BIP 44 defines legacy address derivation paths using BIP32` is what I meant.

I just did some tests with Electrum:
```
segwit
electrum generated seed(NOT BIP39) = alert myself endorse cat peace wash erosion ritual veteran plastic blouse drastic
electrum xpub = zpub6mnYnWH73TQ7UzUmpG43MeZyxP44mqsSuyndGbeuitRRE5KZikYykwLhMFLhGCw6GECFFSKeUWk5eEyfcrJ897rSaH876E7Qx9ggXmR9y8x
btcpay covnersion from electrum xpub = xpub6882BAwGk6K9nQ6Y9YUnwUNycSmAtbtT5kkBhos8xsff7sh7DSDrWp2RJqRXGPdFSwxdkV8XZC2ysfkYBTU6YeVEqbjFvQUSQhZPkgmpzmV
btcpay 1st address = bc1qtrt0slxzdxn483a5l8n5m22hltgxq9cfudj35f
electrum 1st address = bc1qtrt0slxzdxn483a5l8n5m22hltgxq9cfudj35f

```
```

legacy
electrum generated seed(NOT BIP39) = old merge cactus husband alien fossil busy length brush curtain lamp sunset
electrum xpub = xpub661MyMwAqRbcFyk9X83wZwroHgxPiwDPA7SVVVGEbQ3RSWMQaRNsreow3BUpbq7qjMLtTzhyqdcMZj3ezwsJSzoUSjZVYyLez6ZXKjFgYpJ
btcpay xpub = xpub6882BAwGk6K9nQ6Y9YUnwUNycSmAtbtT5kkBhos8xsff7sh7DSDrWp2RJqRXGPdFSwxdkV8XZC2ysfkYBTU6YeVEqbjFvQUSQhZPkgmpzmV-[legacy]
when left without -[legacy], it generated segwit addresses but used hint address and put in st address from electrum (12UhLngN8ziZJy7xGLaL6bAdbH1zTf4xnX) and it was successful.
btcpay 1st address = 12UhLngN8ziZJy7xGLaL6bAdbH1zTf4xnX
electrum 1st address = 12UhLngN8ziZJy7xGLaL6bAdbH1zTf4xnX
```

**Comment by pavlenex** [comment]
Apparently I am drama queen at 1AM 😕 

Explained the issue [here](https://chat.btcpayserver.org/btcpayserver/pl/csj3unu7q7npf8tw7pi3a9zqzy) it was wallet UI that was confusing.
