### ISSUE TITLE
BTCPayServer v1.0.2.39 broke the Lightning Network node

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#215]
Latest version  BTCPayServer v1.0.2.39 definitely broke our lightning network node for some weird reason

This happened when we **tried to update already updated version** more than once.

The following error appears in our terminal when we try to update it 

`  found orphan containers (btcpayserver_clightning_bitcoin) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.`

In Store Settings, LN connection test provides this error 

` Error: Error while connecting to the API (Address not available /etc/clightning_bitcoin/lightning-rpc)`

It looks like the node crashed/removed itself
I followed the regular btcpay update protocol, nothing more, but the thing is I tried to update already up to date version. I'm running on Azure.

**Comment by NicolasDorier** [comment]
We fixed it with
```
docker stop $(docker ps -q -f name=btcpayserver_clightning*)
docker rm $(docker ps -q -a -f name=btcpayserver_clightning*)
btcpay-update.sh
```
