### ISSUE TITLE
Classic theme header not showing on initial login

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#2155]
**Describe the bug**
On initial login page load, when classic theme is enabled the header does not show properly.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Choose classic theme
2. Log out
3. Log in
4. Cant see header

**Expected behavior**
Header shows on initial page load.

**Screenshots**
![image](https://user-images.githubusercontent.com/39231115/102708309-490f5500-425f-11eb-8129-5707f9ebfe24.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: v1.0.6.4   
- Deployment Method: LunaNode       
- Browser: Chrome                 

**Additional context**
Clicking in the header area will load a new page with the header showing.

**Comment by dennisreimann** [comment]
Looks like the font color doesn't apply there. Will fix this.

**Comment by pavlenex** [comment]
Replicated.


Slightly related, but it seems there's no longer much distinction or none between header and body in terms of colours in the light theme?. 

![Screenshot from 2020-12-20 14-46-38](https://user-images.githubusercontent.com/36959754/102714929-50237b00-42d2-11eb-81c4-b416acfdb41d.png)

![Screenshot from 2020-12-20 14-47-00](https://user-images.githubusercontent.com/36959754/102714937-587bb600-42d2-11eb-967b-3a01ef0d51e4.png)
