### ISSUE TITLE
Update invoice endpoint fails to update metadata field

### ISSUE THREAD

**Issue by elvece** [btcpayserver/btcpayserver#2195]
**Bug**:
PUT to [update an invoice](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Invoices_UpdateInvoice) does not update the metadata field with the http request body. The original data in metadata is persisted. 

Response is a 200. 
Content-type is application/json
Example body:

`{
    "metadata":  {
        "POSData": 12
    }
}`

**Expected Behavior**:
PUT request to update an invoice should properly update the metadata field, with either POSData populated, but ideally any arbitrary object field. 

**Server Details**:
- BTCPay Server Version: v1.0.6.5
- Deployment Method: Docker
- Browser: Postman

**Comment by saliehendricks** [comment]
Hi @elvece 

I just tested with my fresh dev instance and updated the invoice without issue. I get a 200 response with the invoice returned and metadata object updated.

Perhaps try with an API with higher privileges? I am using an admin Auth key.

S

**Comment by elvece** [comment]
Hi @saliehendricks - the returned data in the 200 response does show the metadata as "updated", but the value in the UI is unchanged. I will try with a more privileged API to gather more information, but I do not think this should be necessary since I would like to use the restricted API permission (`btcpay.store.canmodifystoresettings`) with my implementation.

**Comment by saliehendricks** [comment]
Hi @elvece , I see what you mean now. After the PUT, I do a GET and the Metadata is different. Will do some digging.

**Comment by pavlenex** [comment]
Fixed in #2197
