### ISSUE TITLE
Stuck on "The node is starting..." after updating to Bitcoin 0.21.0

### ISSUE THREAD

**Issue by BTCBellyButton** [btcpayserver/btcpayserver#2201]
**Describe the bug**
After updating my node to Bitcoin Core 0.21.0 BTCPayServer stopped working.
It's stuck on "The node is starting..."
But the node is fully synced and it has been working perfectly for months...
After rolling back to 0.20.1 it works again.

**To Reproduce the bug**
Steps to reproduce the reported bug:
Install Bitcoin Core 0.21.0
Reboot 

**Screenshots**

![image](https://user-images.githubusercontent.com/68573637/104791797-9ea52780-5761-11eb-9c2c-9c11b0f51ebf.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.0.6.4
- Deployment Method:        Manual
- Browser:                  Firefox

**Comment by NicolasDorier** [comment]
You need NBX `>=2.1.47`

**Comment by BTCBellyButton** [comment]
Thank you, Thank you!
