### ISSUE TITLE
Manage wallet > Settings > Account key > Scan QR is switching and it's unclear what it does

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2206]
**Describe the bug**
In `Manage wallet > Settings > Account key` > `Scan QR ` there's a little icon and once clicked it shows 2 QR codes switching between them quickly.
1. The quick switching makes it hard to scan
2. It is not really clear if you need to scan 1 or 2
3. It is not clear what this option actually does

**To Reproduce the bug**
Steps to reproduce the reported bug:

Make sure you have a wallet created.

1. Go to `Manage wallet > Settings > Account key`
2. Click on QR icon
3. See error

**Expected behaviour**
First of all it should be clear what this does, it's unclear. Second it probably shouldn't be next to the header.
Second, I am not sure how this is supposed to work but auto-switching does not seem like a desired behaviour.

**Screenshots**

https://user-images.githubusercontent.com/36959754/104845306-f57f3e00-58d4-11eb-83ac-7a57e1938a7b.mp4

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:   1.0.6.6 and 1.0.6.7 
- Deployment Method:  Docker      
- Browser:  Firefox

**Comment by Kukks** [comment]
The switching is intended, it is an animated qr code format. Blue wallet
can read it for example

**Comment by pavlenex** [comment]
Yes then this needs to be explicitly said. We shouldn't keep on adding feature available in Bluewallet only, without making it clear that it's only available there.

In that case it's a UX issue on how this should be communicated better.

@Kukks Can you explain to us what is this supposed to be useful for?

**Comment by Kukks** [comment]
> Yes then this needs to be explicitly said. We shouldn't keep on adding feature available in Bluewallet only, without making it clear that it's only available there.
> 
> In that case it's a UX issue on how this should be communicated better.
> 
> @Kukks Can you explain the use-case for this one, so we can properly tackle it UX-wise then? I assume it probably has to do something with importing in Blue, but I'm curious if other wallets support this.

I think cobo also supports it. We cannot list every wallet that supports it as that's unsustainable since it requires a release to update

**Comment by Kukks** [comment]
> Yes then this needs to be explicitly said. We shouldn't keep on adding feature available in Bluewallet only, without making it clear that it's only available there.
> 
> In that case it's a UX issue on how this should be communicated better.
> 
> @Kukks Can you explain the use-case for this one, so we can properly tackle it UX-wise then? I assume it probably has to do something with importing in Blue, but I'm curious if other wallets support this.

The use case is to import the watch only wallet to your app or multisig setup

**Comment by pavlenex** [comment]
> We cannot list every wallet that supports it

If it's widely adopted we shouldn't however for a feature available only in Cobo and Blue we have to specify. I assume that very little portion of users uses those two wallets anyway, so we need to tell people how to interact with these specific features. This has already been mentioned in QR Wallet import which again works only with these two wallets.

**Comment by bolatovumar** [comment]
Yeah, probably makes sense to mention which wallets support this feature even if it means this list will have to be updated periodically if new wallets start supporting the same feature. There could be a blurb saying: "If you use wallet X or wallet Y you can setup your account key by scanning this QR code" even before the user clicks on it. Otherwise you might click on it and be disappointed to find out it doesn't work with your wallet.

**Comment by dennisreimann** [comment]
Let's proceed here once #2164 is merged :)

**Comment by dennisreimann** [comment]
Let's wait for #2508 now. 😬

**Comment by CoderBoogs** [comment]
Has anyone tested the liquid Tether QR code on blockstream? I recently made a purchase there and the QR code was invalid I had to copy and paste the destination address.

**Comment by Zaxounette** [comment]
> Has anyone tested the liquid Tether QR code on blockstream? I recently made a purchase there and the QR code was invalid I had to copy and paste the destination address.

Don't pollute issues with questions that have nothing to do with it.

Report the issue to blockstream.

**Comment by pavlenex** [comment]
> Let's proceed here once #2164 is merged :)

@dennisreimann any idea how do we want to proceed here?

**Comment by dennisreimann** [comment]
Yes, we discussed multiple UX improvements for the wallet in the last UI pair programming session which I'll come up with proposals for. We can then iterate on those – will keep you posted.
