### ISSUE TITLE
Google marked my btc pay site as "This site is unsafe" with a huge red warning page when you click pay

### ISSUE THREAD

**Issue by hakonamatata** [btcpayserver/btcpayserver#2217]
I have not made any changes to my btc pay server lately, but suddenly google says this: 

According to Google

This site is unsafe

The site https://btcpay.xxxxxxxxxxx.com/apps/xxxxxxxxxxxxxxxxx/pos contains harmful content, including pages that:

Try to trick visitors into sharing personal info or downloading software

![image](https://user-images.githubusercontent.com/4003969/105637353-6abab800-5e6d-11eb-8e1a-0d2e819af160.png)

Not sure what is going on, but this essentially killed all payments overnight.

**Comment by pavlenex** [comment]
Duplicate #2139
