### ISSUE TITLE
Custom price display bug

### ISSUE THREAD

**Issue by HeadyWook** [btcpayserver/btcpayserver#2247]
**Describe the bug**
The 'custom price' does not stay on 'no' after changes have been saved. This is regarding 'products' of a 'store' in the 'apps' tab. The bug is also visible in the 'toggle raw editor' template area.

**To Reproduce the bug**
In apps>store settings>edit product>custom price>no>save changes>save settings

Now the products custom price option has been saved and the store has been saved.

Scroll down to and select  'toggle raw editor' to start. The given products 'custom' variable is 'true' (aka yes). Go back to the given product through the edit button and the 'custom price' option is set to 'yes'.

**Expected behavior**

After setting the custom price to 'no' and saving the changes, it should remain on 'no' for both the toggle raw editor 'custom' variable (aka false) and the 'custom price' option within the edit product tab.

**Screenshots**

N/A

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: v1.0.6.5
- Deployment Method: btcpay jungle
- Browser: Tor and Firefox

**Logs (if applicable)**
N/A

**Setup Parameters**
N/A

**Additional context**
This does not actually affect a customers ability to set a custom price. If the user has set it to 'no' then it will behave that way but not display it correctly. This casts doubt in users' minds as to whether or not a costumer can or can't set a custom price.

**Comment by Zaxounette** [comment]
Hi HeadyWook, 

Thanks for the input ! 

Issue reproduced on `v1.0.6.7` also.

**Comment by bolatovumar** [comment]
Looking into this.
