### ISSUE TITLE
Coingecko store rates return errors in some cases

### ISSUE THREAD

**Issue by Zaxounette** [btcpayserver/btcpayserver#2263]
**Describe the bug**

In `Store > Rates > Coingecko Integration`, when `advanced rate rule scripting` is activated, some selectable strings return errors.

**Screenshots**
For example, `ccx`:

![chrome_0zlpPV0dyV](https://user-images.githubusercontent.com/51208677/107163658-19511380-69ab-11eb-99f4-cd023d7de34f.png)

Or `cryptonit`:

![chrome_rwqkhj2rSb](https://user-images.githubusercontent.com/51208677/107164134-e78d7c00-69ad-11eb-9317-68a3cd419506.png)

**Your BTCPay Environment:**
- BTCPay Server Version:    v1.0.6.7
- Deployment Method: Lunanode
- Browser: Chrome + Firefox

**Additionnal info:**
Full list seems to be nested here:
https://github.com/btcpayserver/btcpayserver/blob/9daa424afd8ee0ab06f56b08f01e277b046c55d0/BTCPayServer.Rating/Providers/CoinGeckoRateProvider.cs#L16

If this issue can be resolved just be manually deleting exchanges that produce errors, I can do it, but I expect there is an automatic retrieval of some sorts ?

**On a secondary note:** 
I feel like these clickable links should be set to `target="_blank"`

**Comment by Kukks** [comment]
This can be fixed by bumping the ExchangeSharp library most likely.

**Comment by NicolasDorier** [comment]
Fixed by #de4cd55
