### ISSUE TITLE
Recommended fee is covered in invoice window (language, CSS)

### ISSUE THREAD

**Issue by d2ro** [btcpayserver/btcpayserver#2264]
Hi, first of all: thanks for your great work!

Depending on the language, part of the invoice window is hidden by HTML widgets.

Steps to reproduce the reported bug:
1. Create an invoice
2. Open the "pay" window
3. Go to the "copy" tab
4. Select a language where the text takes one more line (e.g. German)

![invoice1](https://user-images.githubusercontent.com/78594032/107202886-00704e80-69fb-11eb-9d8c-14a37989609a.png)
![invoice2](https://user-images.githubusercontent.com/78594032/107202888-0108e500-69fb-11eb-8fff-bbe428d91182.png)

- BTCPay Server Version: BTCPayServer v1.0.6.8 (altcoins)
- Deployment Method: Docker
- Browser: reproduced with both Chromium and Firefox

**Comment by Zaxounette** [comment]
Hi @d2ro !

Thanks for the issue.
Nice catch ! 

I'm unable to reproduce since I don't actually have the recommended fees appear, for some reason, despite the option checked.

**Comment by d2ro** [comment]
Thanks for your reply! There is another very similar observation: When selecting Monero (XMR), the payment link is overlaid. (Same server, same browsers.) Maybe you can reproduce that?

![invoice3](https://user-images.githubusercontent.com/78594032/107211859-67473500-6a06-11eb-8c95-c490a14c9067.png)

**Comment by Zaxounette** [comment]
> Maybe you can reproduce that?

I only use the default Bitcoin-only build.
