### ISSUE TITLE
[OpenAPI Documentation] Define storeId path parameter for "Get store on-chain payment methods"

### ISSUE THREAD

**Issue by AryanJ-NYC** [btcpayserver/btcpayserver#2268]
**Describe the bug**
I've recently created a [node client for BTCPayServer](https://github.com/AryanJ-NYC/btcpay-greenfield-node-client) which is generated from the docs' [swagger.json](https://docs.btcpayserver.org/API/Greenfield/v1/swagger.json).

For the most part, everything worked well BESIDES "Get store on-chain payment methods" as it's missing the definition for the `storeId` path parameter.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreOnChainPaymentMethods_GetOnChainPaymentMethods
2. Note that the `storeId` path parameter definition is missing

**Expected behavior**
The `storeId` path parameter should be present, as in ["Get store on-chain payment method"](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreOnChainPaymentMethods_GetOnChainPaymentMethod)

**Screenshots**
![Screen Shot 2021-02-09 at 1 27 09 AM](https://user-images.githubusercontent.com/8263430/107324450-18d17f00-6a76-11eb-940e-659e2a073a6b.png)

**Comment by Kukks** [comment]
fixes in #ebc46eb7d20212b618513461e01d24f6562a26a7

**Comment by AryanJ-NYC** [comment]
Hey @Kukks! Realizing this is closed here but I still don't see the `storeId` definition in https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreOnChainPaymentMethods_GetOnChainPaymentMethods.

I'm _guessing_ it's just a matter of mashing some publish docs button that exists somewhere but haven't a clue.
