### ISSUE TITLE
Erratic timestamp ordering in File Storage System view.

### ISSUE THREAD

**Issue by Zaxounette** [btcpayserver/btcpayserver#2273]
**Describe the bug**
At first, when adding new files to the internal storage system, the timestamps are ordered from oldest to newest.

But as you add for files to the system, the timestamps start to make no sense in terms of order. 

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Enable the file system
2. Add a bunch of files to your local file system
3. See the timestamps start to become erratic

**Expected behavior**

The default visual order of the files should be `old to new`, or `new to old`.

**Screenshots**
![chrome_zX7h6efTmy](https://user-images.githubusercontent.com/51208677/107632288-952ab480-6c66-11eb-8887-b4db3723c0a6.png)

As seen in screenshot, timestamps are inconsistent.
This seems to have no relation to alphabetical order either.
This seems to have an impact on files uploaded on the same day only.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: v1.0.6.8
- Deployment Method: Lunanode
- Browser:  Chrome & Firefox

**Comment by pavlenex** [comment]
Maybe you deleted some files in between which affects sorting?
Looks okay on my end.

![Screenshot from 2021-02-11 12-51-00](https://user-images.githubusercontent.com/36959754/107633371-2f3f2c80-6c68-11eb-84a0-246034b7edd1.png)

**Comment by Zaxounette** [comment]
I deleted a lot of files yes.

But that should not affect ordering.

13:23 to 10:59 to 19:18 and 19:25 then back to 11:48. 
Even considering deleted files, that is erratic ordering IMHO.

**Comment by pavlenex** [comment]
Let's keep it for now, maybe @britttttk or @bolatovumar can try to repro.

**Comment by Kukks** [comment]
SHould probably convert that list to use the same list/paging system as all the new lists

**Comment by bolatovumar** [comment]
@Zaxounette I don't see any logic that would order the files by the timestamp.

![Screen Shot 2021-02-21 at 1 42 03 PM](https://user-images.githubusercontent.com/1934678/108639748-f7e03500-744a-11eb-829b-dc4f4b2a3623.png)

We just grab the files belonging to the user and display them in whichever order they come back. I'm not sure if they __should__ be ordered by the timestamp when displaying to the user?

cc @pavlenex @Kukks

**Comment by Zaxounette** [comment]
I don't know how it happened exactly, but that day I uploaded at least 30 files. A number of them being the same that was just updated. 
So I would upload the updated file and directly delete the now "old" version in the list.

For half the day, the list was top-to-bottom, ordered by timestamp by default, no action needed.
But at one point the order became erratic for the Time part of the timestamp, on top of the fact that the date part of the timestamp was now bottom-to-top.

I don't really know if it **should** be ordered by timestamp, but it could be just a default, and on top you have the clickable table titles to re-order, like what you have implemented before in multiple lists.

**Comment by bolatovumar** [comment]
@Zaxounette yeah, the current code doesn't guarantee that things will be ordered by the timestamp as far as I can tell so things can show up out of order. If we wanted to I could make it so that the items are ordered by the timestamped when being shown to the user if that's the behavior we want. I guess we could also have a sortable table so the user can view things from latest to oldest and vice-versa.

**Comment by pavlenex** [comment]
I think adding by timestamp would be a good starting point, but sortable table is even better idea as well, concept ack from my end.

**Comment by britttttk** [comment]
@Zaxounette my list is also in consecutive order so I can't reproduce.
