### ISSUE TITLE
Blockchain Wallet not recognising QR Code or Bitcoin Address

### ISSUE THREAD

**Issue by davidjhume** [btcpayserver/btcpayserver#2278]
**Describe the bug**
We have setup BTCPay server to accept payments in BTC for our service, however, when testing with Blockchain Wallet, we receive a message saying "This is not a Bitcoin QR Code".  We have also tried it with Bitcoin Wallet app and that was able to read the QR code fine.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Generate BTCPay invoice
2. Open Blockchain Wallet app and scan QR code from BTCPay Invoice screen
3. See error

**Expected behavior**
We would expect the Wallet app to show the invoice amount and offer the option to pay.

**Screenshots**

![Screenshot_20210211-195625_Blockchain](https://user-images.githubusercontent.com/21981774/107677909-a5f11f80-6c92-11eb-8c96-4291017bcc93.jpg)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.0.5.5
- Deployment Method:        Third-Party-host
- Browser:            Chrome

**Logs (if applicable)**

**Setup Parameters**

**Additional context**

**Comment by pavlenex** [comment]
Hey, check this out https://docs.btcpayserver.org/FAQ/FAQ-General/#what-if-i-have-a-problem-paying-an-invoice. 
For further questions use discussions or our chat.btcpayserver.org since this isn't a bug.
