### ISSUE TITLE
[Greenfield API] Webhook Validation requires abnormal request body serialization

### ISSUE THREAD

**Issue by AryanJ-NYC** [btcpayserver/btcpayserver#2300]
**Describe the bug**
When validating a Greenfield API webhook, a developer assumes that serializing the request body with no indentation is needed. However, the Greenfield API forces developers to serialize the request body with indentation (notice the [webhookEvent uses "Formatting.Indented" when being serialized in the btcpayserver code](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/HostedServices/WebhookNotificationManager.cs#L309)).

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Try to validate a Greenfield API webhook by serializing the request body with no indentation
2. Note that the hashes are not equal
3. Then try to validate a Greenfield API webhook by serializing the request body with 2 spaces of indentation
4. Great success!
(Indentation shouldn't be assumed here)

**Expected behavior**
The developer does not need to add indentation when serializing the request body

**Code (warning, incoming Node)**
👇 does not work
```typescript
async (req: NextApiRequest, res: NextApiResponse) => {
  const btcPaySig = req.headers['btcpay-sig'];
  if (typeof btcPaySig !== 'string') {
    throw new Error('btcPaySig not string');
  }
  const checksum = Buffer.from(btcPaySig, 'utf-8');

  const body = JSON.stringify(req.body);
  const hmac = crypto.createHmac(
    'sha256',
    Buffer.from(process.env.SETTLED_INVOICE_WEBHOOK_SECRET)
  );
  const bodySignature = `sha256=${hmac.update(Buffer.from(body)).digest('hex')}`;
  const digest = Buffer.from(bodySignature);
  if (checksum.length !== digest.length || !crypto.timingSafeEqual(digest, checksum)) {
    throw new Error('cannot verify request hmac');
  }
};
```

👇 works, note the ONLY difference is how the request body is stringified
```typescript
async (req: NextApiRequest, res: NextApiResponse) => {
  const btcPaySig = req.headers['btcpay-sig'];
  if (typeof btcPaySig !== 'string') {
    throw new Error('btcPaySig not string');
  }
  const checksum = Buffer.from(btcPaySig, 'utf-8');

  const body = JSON.stringify(req.body, null, 2);
  const hmac = crypto.createHmac(
    'sha256',
    Buffer.from(process.env.SETTLED_INVOICE_WEBHOOK_SECRET)
  );
  const bodySignature = `sha256=${hmac.update(Buffer.from(body)).digest('hex')}`;
  const digest = Buffer.from(bodySignature);
  if (checksum.length !== digest.length || !crypto.timingSafeEqual(digest, checksum)) {
    throw new Error('cannot verify request hmac');
  }
};
```

Video explainer: https://www.loom.com/share/33baff4f4f3641f7b707813134a43b83

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    BTCPayServer v1.0.6.8
- Deployment Method:        Docker

**Comment by Kukks** [comment]
ping @NicolasDorier Should we witch behavior? I think it is wrong to have it indented but this is kind of a breaking change?

**Comment by bolatovumar** [comment]
Yeah, this would be a breaking change if it was modified. I guess we could support both? Try to parse it the old way first and if it fails parse it the new way?

**Comment by Kukks** [comment]
> Yeah, this would be a breaking change if it was modified. I guess we could support both? Try to parse it the old way first and if it fails parse it the new way?

We can't as the verification is done on userland code not ours. We would need to introduce a new BTCPay-SIG2 header.

**Comment by Kukks** [comment]
I looked at this again and it is actually an issue with your implementation. 
You should not be parsing the body, stringifying and then verifying.

 Instead you should take the raw body string instead (you seem to have some API library that simplifies things by auto parsing the body, hopefully it still gives you the option to grab the raw body).

**Comment by AryanJ-NYC** [comment]
@Kukks Good call. I bet the framework I'm using is parsing the body automagically. Thanks!
