### ISSUE TITLE
Btcpayserver on kubernetes - strange behavior

### ISSUE THREAD

**Issue by grstein** [btcpayserver/btcpayserver#2303]
**Describe the bug**

I'm trying to port the docker-compose.yaml to kubernetes manifests. When I start the btcpayserver image in K8s, I only see:
`info: Configuration:  Data Directory: /datadir`
And then the POD dies.

**To Reproduce the bug**

Steps to reproduce the reported bug:
1. Get the [btcpayserver.yaml](https://github.com/btcpayserver/btcpayserver/files/6013195/btcpayserver.yaml.txt)
2. Execute kubectl apply -f btcpayserver.yaml -n btcpayserver
3. See the stdout

**Expected behavior**

The log shoud continue like:
`info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: Configuration:  Network: Mainnet
etc...`

**BTCPay Environment:**

- BTCPay Server Version:   btcpayserver/btcpayserver:1.0.6.8
- Deployment Method:        Kubernetes
- Browser:                  NA

**Additional context**

I can run this image in Docker directly and see the normal behaviour. I have confirmed that this docker image runs as Root so this isn't a permission problem on the /datadir directory.

Is there any command, switch or environment variable that produces a more verbose output to help this troubleshoot? This is my first dotnet deployment :)

Thanks

**Comment by grstein** [comment]
Nevermind, there was a typo in the env: BTCPAY_NETWORK. I put **mainet** instead of **mainnet**. I plan deploy in plain kubernet manifests and than write a Helm Chart, I think this will help a lot. Get in touch if you're interested.

**Comment by gabrielseibel1** [comment]
Hi, @grstein did you e ver get to port successfuly to k8s manifests? Would you be willing to share it?

**Comment by grstein** [comment]
Of course, it is a very preliminary version that I did a year ago. Unfortunately, I don't had time to finish. I hope it helps and fell free to discuss some decisions that I took.

https://github.com/grstein/k8s-BTCPay
