### ISSUE TITLE
'Customize text in button' text displaced from center

### ISSUE THREAD

**Issue by 917huB** [btcpayserver/btcpayserver#2311]
When using the "customize test in button" option the HTML output does not match what is shown in the BTCpay dashboard.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to Store > Pay Button
2. Enable customize test in button
3. Change text to custom string, or leave as it, it doesn't matter.  
4. Verify example on right is correct
5. Copy code to web site and verify positioning of custom text is vertically displaced

**Expected behavior**
Text should be centered as is shown in the BTCpay dashboard

**Screenshots**
How it should look
<img width="707" alt="expectedOutput" src="https://user-images.githubusercontent.com/22522964/108903117-ca71c380-75d1-11eb-8503-397ad625296a.png">

and how it looks in Chrome / Safari
<img width="287" alt="actualOutput" src="https://user-images.githubusercontent.com/22522964/108903112-c9409680-75d1-11eb-8e6c-dd115e45d0d3.png">

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.0.6.8
- Deployment Method:        Docker
- Browser:                  witness in Chrome, Safari

Code produced

```
<style type="text/css"> .btcpay-form { display: inline-flex; align-items: center; justify-content: center; } .btcpay-form--inline { flex-direction: row; } .btcpay-form--block { flex-direction: column; } .btcpay-form--inline .submit { margin-left: 15px; } .btcpay-form--block select { margin-bottom: 10px; } .btcpay-form .btcpay-custom-container{ text-align: center; }.btcpay-custom { display: flex; align-items: center; justify-content: center; } .btcpay-form .plus-minus { cursor:pointer; font-size:25px; line-height: 25px; background: #DFE0E1; height: 30px; width: 45px; border:none; border-radius: 60px; margin: auto 5px; display: inline-flex; justify-content: center; } .btcpay-form select { -moz-appearance: none; -webkit-appearance: none; appearance: none; color: currentColor; background: transparent; border:1px solid transparent; display: block; padding: 1px; margin-left: auto; margin-right: auto; font-size: 11px; cursor: pointer; } .btcpay-form select:hover { border-color: #ccc; } #btcpay-input-price { -moz-appearance: none; -webkit-appearance: none; border: none; box-shadow: none; text-align: center; font-size: 25px; margin: auto; border-radius: 5px; line-height: 35px; background: #fff; } #btcpay-input-price::-webkit-outer-spin-button, #btcpay-input-price::-webkit-inner-spin-button { -webkit-appearance: none; margin: 0; } </style>
<form method="POST"  action="https://btcpay.xxxx.org/api/v1/invoices" class="btcpay-form btcpay-form--inline">
  <input type="hidden" name="storeId" value="xxx" />
  <input type="hidden" name="price" value="100" />
  <input type="hidden" name="currency" value="USD" />
<button type="submit" class="submit" name="submit" style="min-width:146px; min-height:40px; border-radius: 4px;border-style: none;background-color: #0f3b21;" alt="Pay with BtcPay, Self-Hosted Bitcoin Payment Processor"><span style="color:#fff">My Pay with</span>
<img src="https://btcpay.xxx.org/img/logo.svg" style="height:40px;display:inline-block;padding: 5% 0 5% 5px;">
</button></form>
```

**Comment by Kukks** [comment]
Your website is most likely overriding the pay button styles with its own css

**Comment by 917huB** [comment]
I verified (as best I can, I'm not a web developer) that that isn't the case. 
I pasted the generated code into [w3schools html test framework](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_intro) and got the same result...

<img width="967" alt="Tryit Editor v3 6 2021-02-23 13-18-59" src="https://user-images.githubusercontent.com/22522964/108909740-c5b10d80-75d9-11eb-8c46-f5800df16a0a.png">

**Comment by bolatovumar** [comment]
I looked into this and looks like this is indeed an issue if the site you embed the button on does not have a Bootstrap CSS file. This button is implicitly relying on styles from the Bootstrap CSS file and if it's not there the text will not be aligned correctly. I will make a PR with the fix.
