### ISSUE TITLE
LocalStorage URLs don't contain root path

### ISSUE THREAD

**Issue by Kixunil** [btcpayserver/btcpayserver#2315]
**Describe the bug**
After uploading a file into local storage in server settings a URL is shown which points to `/LocalStorage/...` instead of `/root_paht/LocalStorage/...` and is thus broken. Manually prepending root path fixes the URL which then returns the appropriate file.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Setup BTCPayserver with non-empty root path, e.g. `/btcpay`
2. In Server settings -> Files upload any file
3. See the generated Direct URL contains `/LocalStorage/...` instead of `/btcpay/LocalStorage/...`
4. Click indirect URL - it will redirect to Direct URL which is broken
5. Fix the URL by prepending `/btcpay` to path - the request will succeed

**Expected behavior**

Direct URL contains `/btcpay` or whatever root path was set
Indirect URL redirects to URL containing the root path

**Screenshots**

![btcpay-bug](https://user-images.githubusercontent.com/1178779/109295132-84656b80-782e-11eb-816b-c4cea1aab117.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:   1.0.6.7
- Deployment Method:        Debian package
- Browser:                  Firefox

**Logs (if applicable)**

I don't think they are needed

**Setup Parameters**

```
network=mainnet
rootPath=/btcpay
```

The rest should be irrelevant

**Additional context**

Same issue seems to be present in version 1.0.6.4

Cc @MaxHillebrand

**Comment by MaxHillebrand** [comment]
I can reproduce the issue, and can confirm that manually adding `/btcpay/` to the URL fixes it.

Thanks @Kixunil for opening the issue!

**Comment by bolatovumar** [comment]
I can repro this bug as well. Looking into it.
