### ISSUE TITLE
About the BUG of Altcoins IPN

### ISSUE THREAD

**Issue by Beanv587** [btcpayserver/btcpayserver#2317]
**Describe the bug**
I received the IPN after I paid the payment, but I found that the value of amountPaid is 0.00000000,
transactionCurrency is null.I want to verify the paid amount in the database

**Screenshots**
![20210227102320](https://user-images.githubusercontent.com/30143806/109372946-2ea0ca00-78e7-11eb-9396-2b30411ea436.png)

**Comment by Beanv587** [comment]
BTCPayServer Version: 1.0.6.8

**Comment by pavlenex** [comment]
@Beanv587 is this still an issue for you?

**Comment by Beanv587** [comment]
@pavlenex 
No, I have solved it. When receiving the IPN notification, go to check the status of the order.Thank you!
