### ISSUE TITLE
Store Wallet Freeze when transaction "canceled" on Nano S

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#232]
In Store > Wallet when you confirm a transaction in BTCPay Wallet, but cancel it on the Nano S, there's no way to edit and confirm again, as "confirm button can't be pressed".

You have to “refresh” and in some cases when refreshed it’s bugged (  "Are you running the ledger app with version equals or above 1.2.4?“)
and I have to disconnect the Nano S.

**Comment by bitcoinshirt** [comment]
Actually, after further testing, I was not able to replicate the issue, so it's not a bug, closing this.

**Comment by NicolasDorier** [comment]
Strange things happen if you have ledger app other than btcpay open at same time on your PC

**Comment by bitcoinshirt** [comment]
I think I might have had Electrum opened, but I was not able to replicate the issue, will keep following.
