### ISSUE TITLE
Error message "You cannot login over an insecure connection. Please use HTTPS or Tor." misleading

### ISSUE THREAD

**Issue by Spixmaster** [btcpayserver/btcpayserver#2322]
**Describe the bug**
When calling btcpayserver from the web I get the notification "You cannot login over an insecure connection. Please use HTTPS or Tor." although an SSL certificate is installed. Even the browser says that an SSL certificate is installed.

**To reproduce the bug**
Steps to reproduce the reported bug:
1. Install this package https://aur.archlinux.org/packages/btcpayserver-git/ which I made.
2. Follow these installation instructions: https://aur.archlinux.org/cgit/aur.git/tree/README.md?h=btcpayserver-git
3. Run nbxplorer and btcpayserver in tmux.
4. Call the website.

**Screenshots**
The error:
![screenshot-20210301-110141](https://user-images.githubusercontent.com/46067952/109481888-a143ae00-7a7d-11eb-8b2a-7e0ed5c49955.png)

The valid certificate:
![screenshot-20210301-111145](https://user-images.githubusercontent.com/46067952/109483494-9853dc00-7a7f-11eb-851f-d0dfec726a1d.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: 1.0.6.7
- Deployment Method: Manual, AUR package
- Browser: Brave

**Settings file for btcpayserver**
I tried giving the setting "httpscertificatefilepath" all possible certificates in /etc/letsencrypt/live/"subomain.domain.me" but this does not solve the problem. In that case btcpayserver threw exceptions with log message `fail: Configuration:  The https certificate file could not be found at privkey.pem.`.
```
### Global settings ###
#network=mainnet

### Server settings ###
#port=23000
#bind=127.0.0.1
#httpscertificatefilepath=devtest.pfx
#httpscertificatefilepassword=toto

### Database ###
#postgres=User ID=root;Password=myPassword;Host=localhost;Port=5432;Database=myDataBase;
#mysql=User ID=root;Password=myPassword;Host=localhost;Port=3306;Database=myDataBase;
sqlitefile=sqlite.db

### NBXplorer settings ###
#BTC.explorer.url=http://127.0.0.1:24444/
#BTC.explorer.cookiefile=/home/user/.nbxplorer/Main/.cookie
#BTC.lightning=/root/.lightning/lightning-rpc
#BTC.lightning=https://apitoken:API_TOKEN_SECRET@charge.example.com/
```

**Comment by Spixmaster** [comment]
I finally found the error. The cause were missing HTTP headers. **In this case, the error message "You cannot login over an insecure connection. Please use HTTPS or Tor." is false and misleading!** It should be changed changed to indicate that solely expected headers are missing.

The following settings work.
```
http
{
    # Variables
    map $scheme $proxy_x_forwarded_ssl
    {
        default off;
        https on;
    }
    
    map $http_upgrade $proxy_connection
    {
        default upgrade;
        "" close;
    }
    
    server
    {
        listen          443 ssl;
        server_name     subdomain.domain.me;
        
        # SSL
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
        ssl_certificate_key /etc/letsencrypt/live/subdomain.domain.me/privkey.pem;
        ssl_certificate /etc/letsencrypt/live/subdomain.domain.me/fullchain.pem;
        
        location /
        {
            # Proxy
            proxy_pass          http://localhost:8080;
            proxy_http_version  1.1;
            proxy_set_header    Host $host;
            proxy_set_header    Upgrade $http_upgrade;
            proxy_set_header    Connection $proxy_connection;
            proxy_set_header    X-Forwarded-For $remote_addr;
            proxy_set_header    X-Forwarded-Proto $scheme;
            proxy_set_header    X-Forwarded-Ssl $proxy_x_forwarded_ssl;
            proxy_set_header    X-Forwarded-Port $server_port;
        }
    }
}
```

**Comment by Kukks** [comment]
Thanks for posting the solution! The error is meant for end users not
system admins so. I fear such an advanced message may intimidate new users.
Maybe we can post a more precise info on the server logs

**Comment by pavlenex** [comment]
Should we then re-name this issue and clarify that it's related to logs improvement?

**Comment by Spixmaster** [comment]
@pavlenex It can either be a log improvment or the message itself on the website can be changed. I am fine if you decide to that it should be a log improvement and thus want to change the title or label.

**Comment by rockstardev** [comment]
@sagecoder are you running into any trouble with resolving this issue?

**Comment by NicolasDorier** [comment]
The relevant code is here:

https://github.com/btcpayserver/btcpayserver/blob/bbe1442c284f32a133aafb548756b403a144013e/BTCPayServer/Services/BTCPayServerEnvironment.cs#L65

Knowing `httpContext.HttpContext.Request.Scheme` can be modified by the reverse proxy by setting `X-Forwarded-Ssl` true.

**Comment by kenaitian** [comment]
I have no clue what I should understand about the explanation above, especially the part about the code snippet although I get the same error when I first deploy BTCPayServer.

**Comment by NicolasDorier** [comment]
Closing this.
I don't want to put tech information in this error message.
People having this problem will likely find this post here. We are documenting SSL offloading on

https://docs.btcpayserver.org/FAQ/Deployment/#can-i-use-an-existing-nginx-server-as-a-reverse-proxy-with-ssl-termination
