### ISSUE TITLE
U2F Support on Safari not working (though it's supported)

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2354]
**Describe the bug**
When trying to do U2F on Safari, Version 14.0.3 (16610.4.3.1.7) you get `U2F Not supported message`
However, recently Safari added the support for U2F.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Use Safari browser (Version 14.0.3, iOS
2. Make sure to have U2F enabled
4. `U2F not supported`
**Expected behavior**

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:  1.0.7.0   
- Deployment Method:    Docker    
- Browser:         Safari 14.0.3         

**Logs (if applicable)**

**Setup Parameters**

**Additional context**

**Comment by Kukks** [comment]
U2F will be obsoleted in the next major version once #1564  is done. All existing u2f devices will be supported through it too

**Comment by pavlenex** [comment]
Awesome. Right, just wanted to open in case someone experiences the same issue. Makes sense to close it as it's already cross-refferenced.
