### ISSUE TITLE
[Question] Where to look at for paid invoices from outside btcpayserver (but inside the same machine).

### ISSUE THREAD

**Issue by nagualcode** [btcpayserver/btcpayserver#236]
Hello, I would like to setup a script inside the same machine I am running BTCpayserver, to interact with my personal account at Bitstamp.
Goal is to watch BTCpayserver for succesfull invoices and then order a market sell of the exact same amount of bitcoin at the exchange.
No Bitcoin transfer from BTCpayserver's wallet... I will leave btc ready to sell sitting at Bitstamp. 
Is there some output / log ? Where should I look at?

**Comment by NicolasDorier** [comment]
@nagualcode not without hacking. I advise you add a Websocket API route at store level to receive such events.

**Comment by rockstardev** [comment]
Yeah, famous fiat integration... we'll get to this eventually.
