### ISSUE TITLE
Multiple paragraphs in description breaks items in POS app

### ISSUE THREAD

**Issue by Sakrecoer** [btcpayserver/btcpayserver#2365]
**Describe the bug**
When editing or adding an item to the POS app, if the description has more than 1 paragraph, it breaks the database layout. Effectively breaking the item and creating an item per paragraph with corrupted values.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to "Apps"
2. Click on `Settings` of a "Point of Sale"
3. Add or edit an item
4. Add or edit the description of the item with a text that has 3 paragraphs.
5. Click `Save Settings`

**Expected behavior**
The description of edited item has 3 paragraphs

**Actual Behavior**

2 new items with broken values appear.

**screenshot**
![image](https://user-images.githubusercontent.com/3484593/111133209-8cd1dc00-857a-11eb-8010-7551293f4d58.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    v1.0.6.2
- Deployment Method:  https://mynodebtc.com/
- Browser: Firefox

**Comment by pavlenex** [comment]
Thanks for reporting, I was able to reproduce this on 1.0.7.0.
