### ISSUE TITLE
Switch App Item Template to JSON

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#2369]
> I think without proper YAML parsing we are setting us up for problems with edge cases here. For instance if the string contains `"`, it'll also break – a description like this will result in an invalid template:
> 
> ```
> This is "THE BEST TEA EVAR" someone said.
> 
> I tend to agree. 
> ```
> 
> With a YAML parser we could use [multiline YAML](https://yaml-multiline.info/) and get rid of the other hacks as well. Otherwise we need to at least patch this by escaping the quotes `\"` … not optimal.

If anything, we should get rid of the YAML parser and switch over to JSON. YAML is a superset of JSON anyway so it shouldn't be that hard. We're also already hiding the raw editor now so any benefits of yml readability has gone a long time ago.

_Originally posted by @Kukks in https://github.com/btcpayserver/btcpayserver/issues/2366#issuecomment-799479118_

**Comment by bolatovumar** [comment]
I agree in principle but if there are users who like to edit things in YAML directly then they might disagree and it's more user-friendly to n00bs.

Also, I wonder if there are any backwards-compatibility considerations here?

**Comment by Kukks** [comment]
> I agree in principle but if there are users who like to edit things in YAML directly then they might disagree and it's more user-friendly to n00bs.
> 
> Also, I wonder if there are any backwards-compatibility considerations here?

Noobs have the UI editor, I doubt YAML can beat that UX in any way :P

No considerations, we'll just do a migration task on startup converting all the yml to json (technically, we can even support both because a compliant yaml parser is able to parse json json too since yml is a superset of json)

**Comment by NicolasDorier** [comment]
This parser probably support json as well
