### ISSUE TITLE
Add unified file storage solution

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#239]
Add in a way to store files within the system

@NicolasDorier  suggested to store them in the db directly but I'm a bit wary of that due to issues that could come with it (more details here: https://softwareengineering.stackexchange.com/questions/150669/is-it-a-bad-practice-to-store-large-files-10-mb-in-a-database)

I propose we use something like this: https://github.com/geeklearningio/gl-dotnet-storage

**Comment by NicolasDorier** [comment]
But we don't need large files. That said, we could probably use external cloud storage provider because the Azure deployment already have a Storage Account! :)
