### ISSUE TITLE
Search bar barely functional

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#24]
Search only works with the following:

> storeid:id for filtering a specific store
> status:(expired|invalid|complete|confirmed|paid|new) for filtering a specific status

All other fields within the invoices are not searchable, including invoice ID. 

Example: Searching Invoice ID returns 0 results - 

Before Searching:
![image](https://user-images.githubusercontent.com/3916318/34552188-e121b8a4-f0d4-11e7-9d52-001185a9b1c9.png)

After Search Attempt
![image](https://user-images.githubusercontent.com/3916318/34552205-f558eed2-f0d4-11e7-9909-03efc032db5c.png)

**Comment by NicolasDorier** [comment]
wow this is weird. I will check it.

**Comment by NicolasDorier** [comment]
I just tried on https://btcpay-server-testnet.azurewebsites.net/ and searching by invoice id worked. Trying to replicate your bug...

**Comment by NicolasDorier** [comment]
Ok so it seems it works for some invoice but not other... will find out.

**Comment by robert-dietrich** [comment]
What was the solution here? I'm having problems trying to search OrderIds that I know exist. Nothing shows up in the results.

**Comment by NicolasDorier** [comment]
It should work. Have you tried `orderid:yourorderid` ?

**Comment by astupidmoose** [comment]
Yea, I'm able to search order ids right now without issue. I simply search for example '73000' and it finds our order Id. 

Are you seeing any invoices on the invoice tab? What version of btcpay are you running?

**Comment by robert-dietrich** [comment]
I'm not seeing any invoices on the invoice tab. And when I try to create an invoice it says: "Error: You need to create at least one store before creating a transaction" -- which is strange because it will still say that even after I've been made owner on this account.

It's v1.0.3.28

**Comment by astupidmoose** [comment]
You need to create a store and add a derivation scheme. I suggest starting here: 

https://docs.btcpayserver.org/btcpay-basics/gettingstarted

**Comment by robert-dietrich** [comment]
But we already have a store... Have been using it for months. I had my creds deleted and recreated recently and this issue began. I think I was able to search for one orderId that came back expired before about a dozen of them came back with nothing, and half of them were ones I know had completed payments. It's as if it's not linking me to the store I should be linked to.

**Comment by NicolasDorier** [comment]
@robert-dietrich BTCpay has only knowledge of the OrderId of woocommerce for orders that have been settled in crypto through BTCPay. It can't search on woocommerce.

**Comment by astupidmoose** [comment]
I suggest you come to the chat and discuss as more people might be able to help you out. 

Chat.btcpayserver.org
