### ISSUE TITLE
I think we Need a Default Lightning BTC crypto currency on checkout, if possible.

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver#240]
I  have noticed Pay with 

LTC lightning payment seem to come up first on the check out window!
Is their a way for BTC Lightning to always be the default,
On a BTCPay Server BTC LTC C-Lightning instance. Maybe the same for LND,

thanks

**Comment by NicolasDorier** [comment]
yep, let me know. I will close this if that solve the issue.

**Comment by NicolasDorier** [comment]
I can't replicate, can you check in your store settings / checkout experience if BTC is selected?

**Comment by Eskyee** [comment]
<img width="736" alt="screenshot 2018-08-07 at 15 31 09" src="https://user-images.githubusercontent.com/30862925/43782368-1e51433a-9a57-11e8-82f3-2245c760d6d2.png"> yes I have BTC set as default .

**Comment by NicolasDorier** [comment]
Can you select LTC, save and reselect BTC and save?

**Comment by Eskyee** [comment]
I have noticed it only happens when it goes to lightning only payment and no BTC ... when its less than a dollar
<img width="736" alt="screenshot 2018-08-07 at 15 37 14" src="https://user-images.githubusercontent.com/30862925/43782714-dd3c6e8c-9a57-11e8-91f8-fbe923b936e0.png">

**Comment by Eskyee** [comment]
I sent a pos app link so you can see for your self the error with the default BTC Lightning payment window .. hope that helps to find the bug  https://btcpayjungle.com/apps/CcXXBRt9Stk2kbcfFdn1p5Y6PVFqZaH2gKuywRXUjRpP/pos

**Comment by Eskyee** [comment]
test the jungle dirt first...

**Comment by Eskyee** [comment]
then test the green tea .. you will see what happens, as this is over a dollar..

**Comment by NicolasDorier** [comment]
Fixed it, I release new version soon.

**Comment by NicolasDorier** [comment]
1.0.2.87

**Comment by Eskyee** [comment]
thanks Nicolas
