### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR 

### ISSUE THREAD

**Issue by hulst88** [btcpayserver/btcpayserver#2400]
**Describe the bug**
My BTC server is an instance on Lunanode and installed just like the documentation tells you to.
But somehow since couple months a small percentage customers get SSL errors like ERR_SSL_PROTOCOL_ERROR

This is very annoying because customers can't see the checkout page.
When I browse to my server SSL is fine and valid. I checked with customers if this is browser or device related but it's not.
They tested with Chrome/Safari/Firefox and on apple devices/windows devices and android devices. 1 was able to see the checkout after activating VPN.

To be clear this happens with a few customers but it is regular. And they were able to pay in the past. 
How to resolve this issue. Hired 2 ssl experts and they did not find the issue.

https://btcpay990721.lndyn.com/

**To Reproduce the bug**
Not able to reproduce.. it's not based on actions

**Expected behavior**
Should show checkout page

**Screenshots**

![image](https://user-images.githubusercontent.com/39407562/112622417-4e1a0c80-8e2b-11eb-9233-53082093b933.png)
![image](https://user-images.githubusercontent.com/39407562/112625314-072e1600-8e2f-11eb-95e8-9dabc0f9f687.png)
![image](https://user-images.githubusercontent.com/39407562/112625344-10b77e00-8e2f-11eb-84f3-98b9f134904c.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    Latest but is happening with at least 6 version back
- Deployment Method:        Lunanode install
- Browser:                  Chrome/Safari/Firefox and different devices

**Logs (if applicable)**
No

**Setup Parameters**

**Additional context**

**Comment by Zaxounette** [comment]
Hi ! 
For us to be able to help you swiftly, please edit your issue using the template that you discarded. It's there for a reason.

**Comment by hulst88** [comment]
> Hi !
> For us to be able to help you swiftly, please edit your issue using the template that you discarded. It's there for a reason.

Changed format using template

**Comment by pavlenex** [comment]
I don't see how we can help you with this if it's not possible to replicate it. I'll have to close this issue as it's not a reproducible bug report, if you manage to find a way to reproduce it let us know and we can address it, meanwhile you can try consulting the community at chat.btcpayserver.org to see if someone had a similar issue.

**Comment by hulst88** [comment]
Problem is that they could not help in the chat and told me to open an issue.
This happens quite a lot and I am probably not the only one. My server is always last version and install is on Lunanode .. they could not find any issue also.

If this occurs to me it could be with others as well. I have a very close customer relation so I get word from my customers that it's happening but I can imagine thousands would just leave a webshop and not order. A potential big problem for webshop owners using btcpay server.

Closing topic is not a solution to recover the problem. Maybe help investigating bug would be helpful.

**Comment by pavlenex** [comment]
We cannot help you investigate this bug unless we have a way to reproduce it.

**Comment by hulst88** [comment]
I understand it is difficult to find if you cannot reproduce. Any suggestions on tests I can run. Because for me I keep testing and keep getting good SSL. But somehow a couple customers send me these screenshot. SO something is wrong.

**Comment by pavlenex** [comment]
You can try digging through https://docs.btcpayserver.org/Troubleshooting/#2-looking-through-the-logs the logs of Let's Encrypt container. `docker logs letsencrypt-nginx-proxy-companion`. Then post on chat.btcpayserver.org.
