### ISSUE TITLE
Invoice QR code is invalid in multiple wallets

### ISSUE THREAD

**Issue by Kogelet** [btcpayserver/btcpayserver#2402]
I have scanned the QR code of a LTC invoice with 2 different wallet apps (Ledger Live and Binance). Both saying that the address is invalid. If I copy the address manually everything is fine.

I think the issue is that the address in QR code is in uppercase instead of lowercase. 

Please see the attached screen shots with errors. 
![WhatsApp Image 2021-03-27 at 21 31 21](https://user-images.githubusercontent.com/11589611/112734091-f3c09f00-8f43-11eb-9b53-8ce29845e42e.jpeg)
![WhatsApp Image 2021-03-27 at 21 31 01](https://user-images.githubusercontent.com/11589611/112734092-f4593580-8f43-11eb-8d53-1f8a3094ef7c.jpeg)

**Comment by astupidmoose** [comment]
It's likely related to the changes made for btc to be all uppercase bech32 addresses

https://github.com/btcpayserver/btcpayserver/issues/2110 

An easy fix, if it's your store, might be to not use LTC segwit and go back to segwit compatible.

**Comment by Kogelet** [comment]
@astupidmoose Yes, the store is mine. Do you mean to use LTC segwit instead of LTC native segwit? It doesn't change anything. I have tried both type of wallets. 

I have actually noticed that other shops removed LTC from BTCPayServer. For example, @aantonop removed LTC from own shop. 

Can this issue be fixed? LTC is a nice alternative when BTC fees are so high.

**Comment by astupidmoose** [comment]
I have LTC non-native segwit and it has both lower and upper case characters and we have received recent payments with it. 

I would assume that should still be working. 

Native Segwit may have been "broken" by the changes I mentioned but it's only a guess. The solution was to get the wallets to support a standard, which they seem to have done with BTC but maybe didn't fix with LTC? 

I would try non-native segwit, or even a legacy address if it's needed. LTC is so fast the address type really doesn't matter.

**Comment by pavlenex** [comment]
Hey @Kogelet, this isn't really a bug. The wallet, or in this case exchanges you're using do not follow the BIP, so they're deviating. In this case, I recommend that you ping them or the LTC community for a fix. 

We've done extensive outreach and testing for BTC in #2110 , since that's what we support, altcoins are out of scope for the developers, and it's up to the community to maintain them. I recommend you post this to the LTC repo.

I'll close this issue as it's not something we can "fix".
