### ISSUE TITLE
Not so much a technical issue but I paid an invoice which timed out?

### ISSUE THREAD

**Issue by btcisthefuture** [btcpayserver/btcpayserver#2403]
Hey everyone, 

Quick question. I was using a site to purchase something. Used btcpay server QR code. sent over transaction. maybe it didn't confirm in time or it was off because my wallet didn't send right amount. Is there a usual response time for btcpayserver to respond about a refund??? I see it confirmed on blockchain later to the address that was given on the QR code/invoice.

I have transaction ID and order number. Just dont want to lose any coin lol. Thanks and sorry if this was not the place to ask this. I did not see anyway to contact btcpayserver support directly to solve this.

**Comment by britttttk** [comment]
You need to contact the merchant @btcisthefuture https://docs.btcpayserver.org/FAQ/FAQ-General/#what-if-i-have-a-problem-with-a-paid-invoice this is an open source project and have nothing to do with refunding any payments.

**Comment by btcisthefuture** [comment]
> You need to contact the merchant @btcisthefuture https://docs.btcpayserver.org/FAQ/FAQ-General/#what-if-i-have-a-problem-with-a-paid-invoice this is an open source project and have nothing to do with refunding any payments.



Thank you. Completely different setup than bitpay. Thank you for confirming this.
