### ISSUE TITLE
[PayJoin] Add onion to BIP21 uri if onion store is visited

### ISSUE THREAD

**Issue by MaxHillebrand** [btcpayserver/btcpayserver#2411]
**Describe the bug**
If a store has PayJoin activated, and is also available at a onion server, then the BIP21 URI of the invoice still uses the clearnet domain in the `pj` field. I think the expected behavior would be to add the onion link into the BIP21 URI. As the user reached BTCPay through Tor browser, the default should be that the user stays within the Tor network, and does not use clearnet to negotiate the PayJoin.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to m33g5t4itjerxhf2vuyrxahstcuhshfxzl2qy5mcuhti3m5erzh5y2yd.onion, the onion address of https://payjoin.test.kukks.org/
2. Click on an Item
3. Go to the `Copy` view of the invoice
4. See that BIP21 URI has the clearnet domain.

**Expected behavior**

If user reaches BTCPay through Tor, it should show the onion link in the BIP21 URI

**Screenshots**

![screenshot_20210331_140422](https://user-images.githubusercontent.com/30683012/113141457-04199800-922a-11eb-9654-8c9cfd5c380f.png)

**Additional context**

This might not be unexpected, as maybe the rational is that most wallets who do support BIP21 URI, do not support Tor and reaching an onion server.

**Comment by Kukks** [comment]
ACK, this is more of a bug than a feature request

**Comment by Kukks** [comment]
I have not been able to replicate in my environments.. Everytime I visit btcpay on an hidden service, the URL in the bip21 reflects it

**Comment by Kukks** [comment]
Perhaps it could be an issue with a forwarded header somewhere.

**Comment by MaxHillebrand** [comment]
This was a bug in https://github.com/Kixunil/cryptoanarchy-deb-repo-builder/, @kixunil fixed it and it's working properly now. 

sorry for opening in the wrong repo :)
