### ISSUE TITLE
App on root not displaying

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#2414]
**Describe the bug**
Apps on root not displaying properly after update

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to Settings
2. Select app to display on root domain
3. Visit root domain and see Login page

**Expected behavior**

Root domain should display my selected app.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: v1.0.7.1   
- Deployment Method: docker, lunanode       
- Browser: chrome                 

**Additional context**

Using my own domain and not using a subdomain.

**Comment by bolatovumar** [comment]
Also happens on my BTCPay instance after update to `v1.0.7.1`. I worked around it by explicitly pointing the domain to the app but this should be fixed. I can take a look into this.

**Comment by NicolasDorier** [comment]
wtf it works on my server?

**Comment by bolatovumar** [comment]
I upgraded my BTCPay instance to v1.0.7.2 and root app shows up correctly now.
