### ISSUE TITLE
Can't check out 1.0.7.2...why?

### ISSUE THREAD

**Issue by ProofOfKeags** [btcpayserver/btcpayserver#2417]
It seems like the most recent release can't be checked out for some reason, despite there being a commit hash and tag for it.

**Comment by dennisreimann** [comment]
The commit e9264e2c2f0e6ac7f0675d97e404748fc0cc9a59 associated with the commit isn't part of the repo. @NicolasDorier did you amend to the original commit afterwards? We should update the tag and associate it with the correct commit.

**Comment by ProofOfKeags** [comment]
Is there a chance you can give me the correct commit that *should* be at that tag so that we can get the Embassy package release out and fix the security vulns? The best guess I have is this: 64db865e1ec7441ba7c211877d55ea3617fa974f

**Comment by dennisreimann** [comment]
Yeah, I'd have guessed so too, because that changelog commit has been targeted before and I think Nicolas amended to it after creating the tag.

**Comment by decentralizedb** [comment]
How we can update to this version?, If I try to check out I had an error (Spanish: error: ruta especificada 'tags/v1.0.7.2' no concordó con ningún archivo(s) conocido por git)

How I can solve it? Thanks!

**Comment by NicolasDorier** [comment]
The tag is part of the repo https://github.com/btcpayserver/btcpayserver/tree/v1.0.7.2

**Comment by NicolasDorier** [comment]
This is not on the master branch because I only wanted 2 commits.
