### ISSUE TITLE
Transaction fees feature

### ISSUE THREAD

**Issue by coinsr** [btcpayserver/btcpayserver#242]
Is it possible to charge a processing fee to stores

**Comment by NicolasDorier** [comment]
You mean, as a host, to charge a processing fee on each transaction? No it is not possible. Also because such fee would be very small the transaction cost onchain might surpass it.

**Comment by al-ec** [comment]
This would be a great feature to help offset server costs, encouraging more implementations of BTCPay servers.

**Comment by NicolasDorier** [comment]
Another solution is a subscription based, where you ask money once a month to the user.

**Comment by Kukks** [comment]
This was discussed a few days ago on Slack. It's not really possible without somehow having the funds transferred to a btcpayserver managed bitcoin address to take a chunk of the cost. Payments currently go straight to the store owner's wallets.

**Comment by NicolasDorier** [comment]
@Kukks it is. It would be custodial accounts. Like when you pre pay on Gandi.NET for example.

**Comment by al-ec** [comment]
https://github.com/coinfee/coinfee

Here's a very defunct library, written in python, that accomplishes exactly this.

**Comment by rockstardev** [comment]
There hasn't been activity on this issue - and from what I know noone from team will be working on this, so I'm closing it for now.

If someone wants to take this upon themselves to implement - ping me and I can reopen for discussion on how this would be implemented and then tracking PRs.

**Comment by KAISDev** [comment]
Hi,

What do you think to make charging the balance in an account of merchant and add minimum balance 20 $ for example, and when add this balance fees of every transactions will deducted from this balance ... And when the balance is 0 will diable this merchant to Force him to charge his balance.

Regards,

**Comment by rockstardev** [comment]
@KAISDev I see you've opened separate issue #2109 so I expect conversation to continue there.
