### ISSUE TITLE
[Greenfield API] Endpoint /misc/lang not working as intended

### ISSUE THREAD

**Issue by jon4hz** [btcpayserver/btcpayserver#2437]
**Describe the bug**
It seems that the API endpoint `$URL/misc/lang` is only accessible by using the browser based authorization. Neither the basicAuth nor token header seems to provide a valid authorization for that endpoint.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Access `$URL/misc/lang` over the browser
2. Call `$URL/misc/lang` using curl

**Expected behavior**

A valid json response as described [here](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/langCodes).

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    v1.0.7.2
- Deployment Method:        Docker
- Browser:                  Firefox

**Comment by bolatovumar** [comment]
@jon4hz Not sure if there is a reason for this but if not I made a PR to address this.

**Comment by NicolasDorier** [comment]
that's indeed surprising
