### ISSUE TITLE
[Greenfield API]: Invoices_GetInvoicePaymentMethods returns invalid fee

### ISSUE THREAD

**Issue by zumoris** [btcpayserver/btcpayserver#2443]
**Describe the bug**
Greenfield API [GetInvoicePaymentMethods](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Invoices_ArchiveInvoice) always returns invalid fee:
- `networkFee` is always `0`
- `payments[i].fee` is  always `0.0` 

**Expected behavior**
- `networkFee` _may_ be recommended network fee by the moment of time when the invoice was created, in **sat/byte**
- `payments[i].fee` should be particular transaction fee, in **sat/byte**

**Method response example**
```[
    {
        "destination": "dist1",
        "paymentLink": "bitcoin:invoice_1?amount=0.00",
        "rate": "44902.518",
        "paymentMethodPaid": "0.00007105",
        "totalPaid": "0.00007105",
        "due": "0",
        "amount": "0",
        "networkFee": "0",
        "payments": [
            {
                "id": "id1-0",
                "receivedDate": 11111111,
                "value": "0.00007105",
                "fee": "0.0",
                "status": "Processing",
                "destination": "dist1"
            }
        ],
        "paymentMethod": "BTC"
    }
]
```

**Comments**
Issue was investigated and confirmed by `@jon4h` in BTC Server Telegram group.

**BTCPay Environment:**
- BTCPay Server Version:    **v1.0.7.1**
- Deployment Method:        **Docker**
- Browser:                             **Chrome**

**Comment by bolatovumar** [comment]
I can't really replicate this locally as fees on regtest seem to always be zero but the bug is somewhere in this method (or in data that this method relies on): https://github.com/btcpayserver/btcpayserver/blob/e1df1c255a41eed8394a92a7f6155de7d0a07164/BTCPayServer/Services/Invoices/InvoiceEntity.cs#L903

Looks like this code was last touched by @NicolasDorier three years ago and by @Kukks a year. Perhaps one of them can weigh in.

**Comment by Kukks** [comment]
This is not the recommended fee, but the fee that is added to an invoice based on the store preference: https://docs.btcpayserver.org/FAQ/FAQ-Stores/#add-network-fee-to-invoice-vary-with-mining-fees
