### ISSUE TITLE
Fail2Ban not installed, big security issue!

### ISSUE THREAD

**Issue by hakonamatata** [btcpayserver/btcpayserver#245]
Hi

I just wanted to add that when SSH is publicly accessible, especially when the bitcoin and lightning node is exposed. SSH access should be properly protected. 

by simply running: 
`sudo apt-get install fail2ban`

A service that IP ban computers for 10 minutes that attempt too many failed login attempts is automatically set up. 

After setting this up myself my log showed: 

` tail -f /var/log/fail2ban.log`

```
2018-08-08 09:05:13,556 fail2ban.filter         [31984]: INFO    [sshd] Found 121.18.238.123 - 2018-08-08 09:05:13
2018-08-08 09:05:16,261 fail2ban.filter         [31984]: INFO    [sshd] Found 121.18.238.123 - 2018-08-08 09:05:15
2018-08-08 09:05:26,252 fail2ban.filter         [31984]: INFO    [sshd] Found 121.18.238.123 - 2018-08-08 09:05:25
2018-08-08 09:05:28,957 fail2ban.filter         [31984]: INFO    [sshd] Found 121.18.238.123 - 2018-08-08 09:05:28
2018-08-08 09:05:39,332 fail2ban.filter         [31984]: INFO    [sshd] Found 121.18.238.123 - 2018-08-08 09:05:31
2018-08-08 09:05:39,826 fail2ban.actions        [31984]: NOTICE  [sshd] Ban 121.18.238.123
```

As you can see an Chinese IP address has been attempting to log in every couple of seconds for god knows how long. As soon as I installed Fail2Ban this IP was banned from access.

**Comment by harding** [comment]
If your server is protected by a secure passphrase (or, even better, has password access disabled and logins only using a private key), fail2ban and similar tools don't add any security.  However, the cryptographic setup for an SSH session (which happens before a passphrase is provided) is computationally expensive for both sides of the connection, so I've seen low-power computers (e.g. RPi version 1) CPUs overwhelmed by just by attempted passphrase brute forcing.

Fail2ban is a good and easy solution to this, although you do want to keep the ban time small in my experience---I've locked myself out of several systems before by, e.g., entering the wrong password several times in a row by accident.  Another solution is requiring logins in sshd_config only using private keys (obviously after setting that up first), as I believe that will reject passphrase attempts before the expensive cryptographic setup starts.

**Comment by NicolasDorier** [comment]
> If your server is protected by a secure passphrase

The SSH password created on Azure deployment of BTCPay has very basic strongness check provided by Azure, however I fear it is not enough. Private keys would be perfect, but I can't expect my users to be fluent with linux.

> I've locked myself out of several systems before by, e.g., entering the wrong password several times in a row by accident.

I am a bit worried by that as well, @hakonamatata, if you can provide me a simple script that I can add to the Azure deploy which does this, I will definitively add it.

I think that Fail2Ban might be a good idea for now, just to make sure that even if the password is not very secure, there is less chance for it to be bruteforced.

Long term, I need to find a way to generate the password. (@harding  submitted idea on mastodon)
My only issue is that I don't know how I can convey this information back to the user...

I will think about this. Actually this might make the entire UX easier while making it also more secure.

**Comment by hubiktomas** [comment]
> I've locked myself out of several systems before by, e.g., entering the wrong password several times in a row by accident.

It can be at least partially mitigated by combination of SSH jail + Recidive jail. SSH jail can have shorter timeouts and Recidive will catch notorious brutforcers for longer time.

Also we can integrate 2FA for SSH as well to increase security. There is a Google Authenticator package for Ubuntu. However I am not sure how to integrate it in the install process so that user can actually pair it with his phone.

**Comment by NicolasDorier** [comment]
I can't expect the users of BTCPay to know how to enter a command line, so I need to script everything at setup.

**Comment by bitcoinshirt** [comment]
@NicolasDorier What about adding U2F verification via Ledger/Trezor/Yubikey?

**Comment by NicolasDorier** [comment]
This is for SSH access, not site access.

**Comment by bitcoinshirt** [comment]
I was under impression that SSH is possible with [Yubikey](https://developers.yubico.com/PGP/SSH_authentication/), [Trezor](https://doc.satoshilabs.com/trezor-apps/sshagent.html), [Ledger](https://thoughts.t37.net/a-step-by-step-guide-to-securing-your-ssh-keys-with-the-ledger-nano-s-92e58c64a005).

**Comment by NicolasDorier** [comment]
Ah indeed I think I saw that somewhere.

**Comment by NicolasDorier** [comment]
Fixed with https://mastodon.social/@BTCPayServer/100541625451629987

**Comment by NicolasDorier** [comment]
Decided to drop user/pwd completely. Better UX, less fields.
