### ISSUE TITLE
Fee estimate looks incorrect

### ISSUE THREAD

**Issue by prayank23** [btcpayserver/btcpayserver#2452]
![Screenshot_20210411-014613__01](https://user-images.githubusercontent.com/13405205/114283590-200e0c80-9a68-11eb-96a0-2a551b3a9dac.jpg)

I was trying to donate someone and the page uses Btcpayserver. I was surprised to see recommended fee rate as 95 sat/vByte whereas other websites like https://mempool.space or https://btc.bitaps.com are showing way less and looking at the mempool I think 10 sat/vByte should have been displayed on this donation page.

How does this estimate work in btcpayserver, which part of the code exactly is responsible to calculate and show the fee rate?

**Comment by Zaxounette** [comment]
Hi ! 

The recommended fee is based on Core and can be customized in the `store settings > checkout experience` on the merchant's side for a targeted block.

Also next time, don't discard the template that is shown before you post, it's there for a reason. It tells you that issues are for confirmed bug reports. If unsure it's a bug, just ask in the [chat](https://chat.btcpayserver.org/) or open a [discussion](https://github.com/btcpayserver/btcpayserver/discussions).

**Comment by Kukks** [comment]
Based on Core, and also based on block conf preference of merchant (which it asks Core to estimate on).
