### ISSUE TITLE
Setup Derivation Scheme with my Trezoor xpub key no funds have moved to my wallet

### ISSUE THREAD

**Issue by corbimos** [btcpayserver/btcpayserver#247]
I setup the Derivation Scheme with my trezor xpub and tested out a transaction. It all worked fine and i could see my addresses tied to my trezor. 

Now that i've accepted orders, none of the funds, except the original test is showing up in my trezor. 

Please let me know if anyone has had similar issues. '

Thanks!

**Comment by NicolasDorier** [comment]
probably because of the Gap limit issue. The solution is to use Electrum with Trezor and follow this https://github.com/btcpayserver/btcpayserver-doc/blob/master/Xadrez.md#electrum . You'll then be able to get your money back.

**Comment by corbimos** [comment]
Also, trying to look at the addresses and the 'Check ExtPubKey' button is no longer there

**Comment by corbimos** [comment]
Thanks!! @NicolasDorier

**Comment by NicolasDorier** [comment]
If you saw the first payment the problem is surely the gap limit.

**Comment by corbimos** [comment]
I just located all the funds. You really are the greatest!! Thanks for everything you do @NicolasDorier

**Comment by NicolasDorier** [comment]
nice!
