### ISSUE TITLE
Add QR code encoding server address

### ISSUE THREAD

**Issue by haarts** [btcpayserver/btcpayserver#248]
I'm working on creating a PoS app for BTCPay. There's going to be one shop with many points of sale. Each install of the PoS app must be configured to point to the correct BTCPay server. That means entering a domain. 
The only option now is typing that out, this is error prone. 

I think it would be beneficial to provide a QR code for the user encoding the server address.
The page displaying the QR code should be served by BTCPay on a unauthenticated path or subdomain. For example `https://test2-btc-ltc.forkbitpay.ninja/domain` or `https://test2-btc-ltc.forkbitpay.ninja/setup`. Or even on the home page.

**Comment by pavlenex** [comment]
There's a discussion regarding this on Mattermost, Bluewallet has similar idea, so I'd recommend you join [#Blue-wallet](https://chat.btcpayserver.org/btcpayserver/channels/bluewallet-btcpay) channel. Closing this one due to inactivity.
