### ISSUE TITLE
Trouble importing new wallet via multiple QR codes

### ISSUE THREAD

**Issue by zachherbert** [btcpayserver/btcpayserver#2499]
**Describe the bug**
We are testing our Passport hardware wallet with BTCPay. Passport uses Blockchain Commons' UR1.0 or UR2.0 standards for splitting data into multiple QR codes. By default, we send data via the UR standard, even if the data can fit in a single QR code.

We are passing the wallet XPUB details in the Cobo format. Example below: 

`{"ExtPubKey": "zpub6qv65WZ1ws7StYEitaaXjk7qFai1VtSuGm9FuY7QZ8ZWt2ZbsbBXnSeW6Cz7BHjzPftAAx9anvcSprkvRCbAP33yMymM1WijmgV9cPRCgu6", "MasterFingerprint": "317184B6", "AccountKeyPath": "84'/0'/0'", "FirmwareVersion": "0.9.73"}`

If we pass this via a QR code that is not encoded in UR format, BTCPay is able to instantly read it. For example, BTCPay can read the below QR: 

<img width="203" alt="CleanShot 2021-05-02 at 21 04 33@2x" src="https://user-images.githubusercontent.com/14018740/116833966-0a34c880-ab8a-11eb-88fb-52554b12c3ff.png">

It correctly outputs:

<img width="635" alt="CleanShot 2021-05-02 at 21 15 59@2x" src="https://user-images.githubusercontent.com/14018740/116834358-b0cd9900-ab8b-11eb-96a4-82b292d7e82b.png">

However, if we pass the data via UR1.0 to BTCPay, BTCPay is unable to parse it. QR below:

<img width="203" alt="CleanShot 2021-05-02 at 21 07 26@2x" src="https://user-images.githubusercontent.com/14018740/116834052-6b5c9c00-ab8a-11eb-9da2-74583457c91a.png">

When scanning this QR code, this is what BTCPay displays:

<img width="666" alt="CleanShot 2021-05-02 at 21 07 48@2x" src="https://user-images.githubusercontent.com/14018740/116834181-ecb42e80-ab8a-11eb-9dd2-7a379e67d1ef.png">

Notably, BTCPay is able to scan multiple QR codes formatted in UR1.0 and display the same output as above. But it cannot parse this data and extract the XPUB.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to Wallet Setup under store settings
2. Connect Existing Wallet -> Scan wallet QR code
3. Try scanning both QR codes above. It's the same data, but the second is formatted with UR1.0. They should display the same output, but they don't! 

**Expected behavior**

We would expect BTCPay to properly parse the UR1.0 formatted QR code. Is this a problem on BTCPay's end, or are we sending it in an incorrect data format?

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    v1.0.7.1
- Deployment Method:        Docker
- Browser:                  Chrome

**Comment by pavlenex** [comment]
ping @Kukks
