### ISSUE TITLE
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

### ISSUE THREAD

**Issue by pretyflaco** [btcpayserver/btcpayserver#2502]
**Describe the bug**
I get an error when trying to access lnd via cli: 
`[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"`

**To Reproduce the bug**
`root@btcpay:~/btcpayserver-docker# ./bitcoin-lncli.sh getinfo`

**Expected behavior**
show node info

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    BTCPayServer v1.1.0.0
- Deployment Method:        LunaNode
- Browser:             

**Additional context**

https://github.com/lightningnetwork/lnd/issues/5264
https://github.com/lightningnetwork/lnd/issues/5264#issuecomment-831608294 

how can I check to see if default RPC listening port has been modified in the config and what RTL and Joule are using for the port + cert ?

**Comment by pavlenex** [comment]
@rockstardev do you perhaps know what's going on?

**Comment by Eskyee** [comment]
I see this @rockstardev after checking my logs !!

nrpclisten=lnd_bitcoin:10009
shouldn't this be ??
nrpclisten=127.0.0.1:10009


LND_EXTRA_ARGS=restlisten=lnd_bitcoin:8080\nrpclisten=127.0.0.1:10008\nrpclisten=lnd_bitcoin:10009\nbitcoin.node=bitcoind\nbitcoind.rpchost=bitcoind:43782\nbitcoind.rpcuser=lnd\nbitcoind.rpcpass=afixedpasswordbecauselndsuckswithcookiefile\nbitcoind.zmqpubrawblock=tcp://bitcoind:28332\nbitcoind.zmqpubrawtx=tcp://bitcoind:28333\nadminmacaroonpath=/data/admin.macaroon\ninvoicemacaroonpath=/data/invoice.macaroon\nreadonlymacaroonpath=/data/readonly.macaroon\ntlsextradomain=lnd_bitcoin\nno-rest-tls=1\nprotocol.wumbo-channels=1\n\ntor.active=1\ntor.socks=tor:9050\n",

**Comment by Eskyee** [comment]
I can also see with docker inspect!! 

maybe 10009 hasn't Exposed Port for the LND docker container ??

"Hostname": "56726ec0ed92",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {},
                "8081/tcp": {},
                "9735/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "LND_CHAIN=btc",
                "LND_EXTERNALIP=",
                "LND_PORT=9735",
                "LND_ALIAS=noname",
                "LND_ENVIRONMENT=mainnet",
                "LND_READY_FILE=/root/.nbxplorer/btc_fully_synched",
                "LND_REST_LISTEN_HOST=http://lnd_bitcoin:8080",
                "LND_HOST_FOR_LOOP=lnd_bitcoin:10009",

**Comment by astupidmoose** [comment]
I'm getting the same errors in command line. 

./bitcoin-lncli.sh walletbalance
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

**Comment by rockstardev** [comment]
Just add rcpserver to it `./bitcoin-lncli.sh --rpcserver lnd_bitcoin:10009 getinfo`

I'll open PR to make adding rpcserver not required.

**Comment by AryanJ-NYC** [comment]
> Just add rcpserver to it `./bitcoin-lncli.sh --rpcserver lnd_bitcoin:10009 getinfo`

Can confirm this workaround works for me.

**Comment by rockstardev** [comment]
Will be resolved once PR I've opened is merged. In the meantime you can one liner from PR on your instances and script will work again.

**Comment by Eskyee** [comment]
bitcoin-lncli.sh --rpcserver lnd_bitcoin:10009 getinfo
can confirm workaround works for me!
cheers

**Comment by maltokyo** [comment]
confirm this closed the issue, thank you @rockstardev !

**Comment by pretyflaco** [comment]
Updating to  v1.1.2.0 solved the issue.
