### ISSUE TITLE
ay Button BTC "Min Amount" and "Step" values cannot be lower than 1

### ISSUE THREAD

**Issue by vikingsarehere** [btcpayserver/btcpayserver#2503]
Hello Guys,

As discussed on https://chat.btcpayserver.org, I have encountered an issue today.

I am trying to setup a BTCpay Pay Button using a BTC currency.

The problem is that the system does not want to accept any "Min Amount" or "Step" values of lower than "1" which for BTC currency is quite high.

I attach a screenshot.

Many people are confused with the satoshi value so this would not be an ideal denomination.

I hope that someone can find a solution and advise back. Thanks

**Comment by vikingsarehere** [comment]
![Screen1](https://user-images.githubusercontent.com/82751603/116994850-f2705800-ace1-11eb-82d1-47f6184848f6.jpg)
Here is a screen of the issue

**Comment by Kukks** [comment]
yeah this is a bug, thanks for reporting

**Comment by NicolasDorier** [comment]
I guess you can work around by changing the generated html code directly
