### ISSUE TITLE
Improve the UI of signing (sign with)

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2508]
It's been proposed recently that we should have a better signing UI than clicking on the `sign with` button which currently provides unclear options. 
![Screenshot 2021-05-06 at 11 14 44](https://user-images.githubusercontent.com/36959754/117273942-df35c780-ae5c-11eb-9176-19096e853df3.png)

Perhaps a `Sign` button opens up a new page/view similar to what we have in the wallet setup.

![Screenshot 2021-05-06 at 11 18 09](https://user-images.githubusercontent.com/36959754/117273918-d80eb980-ae5c-11eb-8237-c5f370527499.png)

Opening this up for concrete suggestions.

**Comment by dennisreimann** [comment]
Started working on this. Here's a preview screenshot we can use to discuss and prepare a few things:

- Wording of the titles and descriptions
- Do we want to recomment/discourage use of specific options?
- An additional icon for PSBT would be good. @dstrukt 

![signing](https://user-images.githubusercontent.com/886/120476207-99f8ad00-c3aa-11eb-9465-245facc5d634.png)
