### ISSUE TITLE
Ability to Custom Sort currencies in the invoice screen

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#251]
Not sure how this would look, but it looks like coins are currently sorted by name. 

Would be nice to be able to sort with a custom priority system. This would allow your "favourite" shitcoins to be listed before even shittier shitcoins. :)

**Comment by NicolasDorier** [comment]
I think I understand which shitcoin you are talking about.
Any idea on the UX for this @rockstardev ? Maybe just textboxes with a priority number in "Checkout experience"?

**Comment by rockstardev** [comment]
In database you'll likely need another field (number) assigned to "PaymentMethod"... then you sort by that. As fallback for those that don't have number assigned you sort by name. Right now I sort by name and then insert Bitcoin/Bitcoin via Lightning as first payment options if they exist: https://github.com/btcpayserver/btcpayserver/blob/65916755b6745c8c2d3ddbc3833eaa56f8ba3eb2/BTCPayServer/Controllers/InvoiceController.UI.cs#L298

For UX I would likely use some component like: https://www.telerik.com/kendo-vue-ui/components/listbox/drag-and-drop/

Kendo is not open source so we can't use that, but I remember seeing similar components... we don't also need to stick with VueJs, but rather see some jQuery component that does the same thing.

**Comment by pavlenex** [comment]
Discussed this one with Mike, considering the fact we now have a drop down and that users can choose default currency, there's no really need for this one.

If in future anyone wants this feature, feel free to comment and we'll re-open.
