### ISSUE TITLE
Pull payment payout still on awaiting payment list after payout sent.

### ISSUE THREAD

**Issue by oiiahchai** [btcpayserver/btcpayserver#2513]
**Describe the bug**
Pull payment payout still list at "Awaiting payment" list after sent out the payout.
**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to 'greenfield api create pull payment, login backend > manage payout >  select all > action >  send selected payout'
2. after sent payout it still show on awaiting payment list.

**Expected behavior**

**Screenshots**
https://ibb.co/vqG389L
https://ibb.co/Wy64Jtj
https://ibb.co/hYVrjDt

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:  BTCPayServer v1.1.0.0
- Deployment Method:        Docker
- Browser:   Chrome

**Logs (if applicable)**

**Setup Parameters**

**Additional context**

**Comment by oiiahchai** [comment]
View detail pull payment show Already claimed, pull payment list status awaiting.
https://ibb.co/wNXs086
https://ibb.co/WFkvHQJ

**Comment by Kukks** [comment]
Are you sure you sent the transaction? Are you sure you sent the transaction AFTER you approved the payout?

**Comment by Kukks** [comment]
I have tried many possibilities and not been able to recreate this issue.
