### ISSUE TITLE
Cannot change currency

### ISSUE THREAD

**Issue by lbphp** [btcpayserver/btcpayserver#2516]
Hello,
when i change the currency, e.g. from BTC to DASH, the currency dropdown still shows BTC.
Example invoice https://btcpay.cryptokix.com/invoice/status?invoiceId=GeuQknMJVYJxSZASZgVpTB&paymentMethodId=DASH&_=1620487339566
( Probably expired now. )

When i selected DASH, this status update request has been made
https://btcpay.cryptokix.com/invoice/status?invoiceId=GeuQknMJVYJxSZASZgVpTB&paymentMethodId=DASH&_=1620487339566
Showing this output
`
{"uiSettings":{"extensionPartial":"Bitcoin/BitcoinLikeMethodCheckout","checkoutBodyVueComponentName":"BitcoinLikeMethodCheckout","checkoutHeaderVueComponentName":"BitcoinLikeMethodCheckoutHeader","noScriptPartialName":"Bitcoin/BitcoinLikeMethodCheckoutNoScript"},"customCSSLink":null,"customLogoLink":null,"htmlTitle":"BTCPay Invoice","defaultLang":"en","availableCryptos":[{"paymentMethodId":"BTC","cryptoImage":"/imlegacy/bitcoin.svg","link":"/i/GeuQknMJVYJxSZASZgVpTB/BTC","paymentMethodName":"Bitcoin","isLightning":false,"cryptoCode":"BTC"},{"paymentMethodId":"DASH","cryptoImage":"/imlegacy/dash.png","link":"/i/GeuQknMJVYJxSZASZgVpTB/DASH","paymentMethodName":"Dash","isLightning":false,"cryptoCode":"DASH"},{"paymentMethodId":"LTC","cryptoImage":"/imlegacy/litecoin.svg","link":"/i/GeuQknMJVYJxSZASZgVpTB/LTC","paymentMethodName":"Litecoin","isLightning":false,"cryptoCode":"LTC"}],"isModal":false,"cryptoCode":"BTC","invoiceId":"GeuQknMJVYJxSZASZgVpTB","btcAddress":"bc1q55jstjrd6dlhuu2cyx7v380c4ff8h65u7ksuem","btcDue":"0.28542680","customerEmail":"stealthepixels@cryptokix.com","requiresRefundEmail":false,"showRecommendedFee":true,"feeRate":87.16,"expirationSeconds":779,"status":"new","merchantRefLink":"https://btcpay.cryptokix.com/invoice","maxTimeSeconds":900,"storeName":"CryptoKix","itemDesc":null,"timeLeft":"12:59","rate":"$58,652.52 (USD)","orderAmount":"0.28542680","orderAmountFiat":"$16,741.00 (USD)","invoiceBitcoinUrl":"bitcoin:bc1q55jstjrd6dlhuu2cyx7v380c4ff8h65u7ksuem?amount=0.2854268","invoiceBitcoinUrlQR":"bitcoin:BC1Q55JSTJRD6DLHUU2CYX7V380C4FF8H65U7KSUEM?amount=0.2854268","txCount":1,"btcPaid":"0.00000000","storeEmail":null,"orderId":"1216","networkFee":0.0,"isMultiCurrency":false,"maxTimeMinutes":15,"paymentType":null,"paymentMethodId":"BTC","paymentMethodName":"Bitcoin","cryptoImage":"/imlegacy/bitcoin.svg","storeId":"8US5rraqHGQuRaWkU2hYRWApw4SVhh8MA8zaFqpjbQ5k","peerInfo":null,"rootPath":"/","redirectAutomatically":false,"activated":true,"invoiceCurrency":"USD"}`

I also noticed that the wss requests fail, maybe it's because of Cloudflare blocking them ( i have my domain on cloudflare).
Example wss://btcpay.cryptokix.com/invoice/status/ws?invoiceId=GeuQknMJVYJxSZASZgVpTB
returns ERR_DISALLOWED_URL_SCHEME when navigating on it.
Is it possible to force BTCPay to use https instead of websocket for these requests?

I see this in the error console:
```
invoice?id=GeuQknMJVYJxSZASZgVpTB&paymentMethod=LTC:514 WebSocket connection to 'wss://btcpay.cryptokix.com/invoice/status/ws?invoiceId=GeuQknMJVYJxSZASZgVpTB' failed: 
listenIn @ invoice?id=GeuQknMJVYJxSZASZgVpTB&paymentMethod=LTC:514
i @ checkout-bundle.min.js?v=PQqOnpS2rGYvvf9P9OmVn7nx0iRPF43GJ5tRwo4wGu8:27
mounted @ invoice?id=GeuQknMJVYJxSZASZgVpTB&paymentMethod=LTC:435
d @ checkout-bundle.min.js?v=PQqOnpS2rGYvvf9P9OmVn7nx0iRPF43GJ5tRwo4wGu8:27
(anonymous) @ checkout-bundle.min.js?v=PQqOnpS2rGYvvf9P9OmVn7nx0iRPF43GJ5tRwo4wGu8:27
r.$mount @ checkout-bundle.min.js?v=PQqOnpS2rGYvvf9P9OmVn7nx0iRPF43GJ5tRwo4wGu8:27
r.$mount @ checkout-bundle.min.js?v=PQqOnpS2rGYvvf9P9OmVn7nx0iRPF43GJ5tRwo4wGu8:27
n._init @ checkout-bundle.min.js?v=PQqOnpS2rGYvvf9P9OmVn7nx0iRPF43GJ5tRwo4wGu8:27
r @ checkout-bundle.min.js?v=PQqOnpS2rGYvvf9P9OmVn7nx0iRPF43GJ5tRwo4wGu8:27
(anonymous) @ invoice?id=GeuQknMJVYJxSZASZgVpTB&paymentMethod=LTC:396
invoice?id=GeuQknMJVYJxSZASZgVpTB&paymentMethod=LTC:519 Error while connecting to websocket for invoice notifications (callback)
```

**Comment by lbphp** [comment]
Is there a way fo force the default coin in the dropdown via a GET parameter to the invoice page?
So that i may work-around the problem by presenting a coin selection at checkout page, and when the user clicks on "Proceed to BTCPAY" , i will redirect the user to` https://<btcpayserver host>/invoice?id=<invoiceId>&coinParameter=DASH`

**Comment by Kukks** [comment]
* Cloudflare is known to interfere with BTCPay deployments
* only a refresh of the invoice page would update it if websockets are not working, I think.  Will look into a possible failover

**Comment by lbphp** [comment]
Another way of solving this.
I may run multiple instances of BTCPayserver, each one being a manual deployment copied each into a different directory, and having enabled only one coin.
And i duplicate/fork also the wordpress plugin, so i have one plugin per coin, paired with a different BTCPayserver instance.
Would it work?
