### ISSUE TITLE
My Shopify Integration doesn't work as advertised

### ISSUE THREAD

**Issue by Giszmo** [btcpayserver/btcpayserver#2533]
**Describe the bug**

After pasting the Shopify "example url" I get a confirmatory "Shopify integration successfully updated":

![Screenshot from 2021-05-18 19-46-24](https://user-images.githubusercontent.com/96378/118761334-3a46c180-b842-11eb-9347-a33317b20414.png)

but when selecting again the "Integrations", it remains "Disabled":

![Screenshot from 2021-05-18 19-46-38](https://user-images.githubusercontent.com/96378/118761411-577b9000-b842-11eb-8087-6bde43287caa.png)

**Expected behavior**

Something resempling "step 7" in [the tutorial](https://docs.btcpayserver.org/Shopify/#setting-up-btcpay-server-with-shopify).

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.1.1.0
- Deployment Method:        Docker I guess
- Browser:                  FF88.0.1

**Logs (if applicable)**

Old logs disappeard. Just tried again to link Shopify and the logs remain unchanged with only "New block" messages and one "Remove pending invoice"

**Additional context**

I noticed that Shopify had one additional step that was not mentioned in the tutorial where I had to promise not to mess with the checkout process with my custom plugin. That made me think they might dislike BtcPayServer now?

**Comment by Kukks** [comment]
Thank you for the report! Confirmed and fixed in a pull request for next
release

**Comment by pavlenex** [comment]
Fixed in #2530

**Comment by NicolasDorier** [comment]
released the new version 1.1.2
