### ISSUE TITLE
Can't import C-Lightning output descriptor

### ISSUE THREAD

**Issue by hosiawak** [btcpayserver/btcpayserver#2538]
**Describe the bug**
The xpub import screen is rejecting my descriptor exported from C-Lightning using their `lightning-hsmtool dumponchaindescriptors hsm_secret`

**To Reproduce the bug**
Steps to reproduce:
1. Export your C-Lightning descriptor
2. Try to import it into BTCPayserver wallet
3. See "Invalid wallet format" error

**Expected behavior**
Ability to import any output descriptor.

**Screenshots**

![btcpayserver_import](https://user-images.githubusercontent.com/4709/119112022-f14e6300-ba23-11eb-91f7-36215fa5ea6e.jpg)

**Comment by Kukks** [comment]
We only allow a subset of descriptors for now, specifically ones that follow normal path derivations
The `/0/0/*` is abnormal.  BIP84 specifies `0/*`

**Comment by hosiawak** [comment]
Thanks for the clarification @Kukks.

There's software that uses non standard (eg. non BIP-44/84 etc.) derivation paths here and there. I was hoping descriptors would solve the wallet interoperability. I guess you could fairly easily fallback to bitcoind `deriveaddresses` and support descriptors fully but I have no idea how disruptive that will be to your codebase.

Feel free to close it if it's not on the roadmap.

**Comment by Kukks** [comment]
We don't use bitcoind to derive and track addresses and instead do it manually by connecting via p2p to bitcoind and parsing the blocks. This happens in NBXplorer
