### ISSUE TITLE
[UI] Fixing display when the invoice is loading on Checkout

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#255]
Hey @rockstardev , any idea how to fix that?

![image](https://user-images.githubusercontent.com/3020646/44618792-f2c0c000-a8b7-11e8-9148-0bc61a7d1f8a.png)

**Comment by rockstardev** [comment]
Yeah, bundling is easiest way, but I'll make it work even without bundling - sending you PR once it's done

**Comment by rockstardev** [comment]
Hey @NicolasDorier I'm having trouble reproducing locally - can you send me link to some environment where I can reproduce it.

**Comment by NicolasDorier** [comment]
Create an invoice here https://main2-btc-ltc.forkbitpay.ninja/apps/Hoddr1KdzJcBf9MbhfXHziL1nnrtw7uMFWkZqL9Uhuyj/pos

When you refresh the page by removing the cache you see it.

**Comment by rockstardev** [comment]
Tried reproducing, but for me it's working without showing these VueJs params during loading.

**Comment by NicolasDorier** [comment]
even when doing CTRL+F5 on the invoice page of an invoice? strange.
