### ISSUE TITLE
how does a admin uninstall or disable the Plugins ?? Shopify, CoinSwitch, or CustomLiquidAssetplugin.

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver#2556]
<img width="1280" alt="Screenshot 2021-06-03 at 01 20 04" src="https://user-images.githubusercontent.com/30862925/120567839-8b41e280-c40a-11eb-9a60-486c83cd339e.png">

also I can not remove the CustomLiquidAsset after a install and after updating broke the plugin. been testing liquid, and this is the only problem find. as I mentioned before.
plus the restart does not remove the plugin for me. So Im sure this is a bug. not be able to remove the plugins.

btcpay version v1.1.0 to v1.1.2

Some plugins were disabled due to fatal errors. They may be incompatible with this version of BTCPay Server. 

<img width="843" alt="Screenshot 2021-06-03 at 01 34 53" src="https://user-images.githubusercontent.com/30862925/120568514-ecb68100-c40b-11eb-977a-ee96a025b151.png">

**Comment by pavlenex** [comment]
You cannot remove system plugins @Eskyee. They haven't been decoupled entirely yet.

**Comment by pavlenex** [comment]
Ping @Kukks are these `fatal errors` something we can take a look at or is this out of scope atm and we shall close this issue until we fully decouple things like we're attempting to do in #2563?

**Comment by Kukks** [comment]
> Ping @Kukks are these `fatal errors` something we can take a look at or is this out of scope atm and we shall close this issue until we fully decouple things like we're attempting to do in #2563?

It's because he installed an experimental plugin (liquid plugin) that supported an older version of btcpay. He has to uninstall the plugin + restart btcpay.

This fatal error has nothing to do with the system plugins. I'm working on decoupling stuff from system plugins as we speak
