### ISSUE TITLE
Question regarding lightning wallet seed, config and backup

### ISSUE THREAD

**Issue by hakonamatata** [btcpayserver/btcpayserver#256]
Hi

Great work on the btc pay server. Has been working very well. I just a have couple of questions before turning to the mainnet. 

This might be stupid questions, but I can't see any information about how the lightning node is set up. How is the wallet generated? What is the backup seed? How can I change the lnd.conf ?

What I would like to do is set up a new lightning wallet, get the new seed, make a backup of the seed words and maybe change settings in lnd.conf. How can I do that? and if I run an update later, will this be reset?

PS. information about this might be good to have in the BTCPay Server Documentation

**Comment by NicolasDorier** [comment]
I don't know sorry. The only thing I would advise is to not keep too much money on your LN node.

**Comment by slack333** [comment]
> Check https://github.com/btcpayserver/btcpayserver-docker to understand how it works under the hood.
> 
> Sadly, I don't support backup of seed because I just start the wallet with noencrypt. (Though you can do it)
> 
> You can change `lnd.conf` by using the concept of `custom docker fragment` and following what `opt-lnd-autopilot` does.

Hi @NicolasDorier, sorry for my next stupid question, how can I do that? I need to setup my tls.cert + macaroon (stuff) too and I don't know how to do it with docker.

I will be grateful if you or someone could help me with this. Also in this share link https://github.com/btcpayserver/btcpayserver-docker doesn't say to much about lightning.

**Comment by NicolasDorier** [comment]
@slack333 with docker you don't need to setup anything. Check https://www.youtube.com/watch?v=CWhTOunTb2Q

**Comment by bitcoinshirt** [comment]
I think we can close the issue now.
We've added [document](https://docs.btcpayserver.org/development/lightningnetwork) clarifying the risks of using Lightning Network and also a new feature suggested in  #346.
