### ISSUE TITLE
Notification after sending a test email appears twice on the page. The test email is sent only once.

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver#2565]
**Describe the bug**
When I go to a store > Email settings and send a test email. The notification "Email sent to xxx, please, verify you received it" appears twice. Only 1 email is sent, so it's a frontend issue.

**To Reproduce the bug**
1. Go to 'stores'
2. Go to SMTP email settings
3. Make sure you have a working SMTP config in place.
4. Send a test email
5. The green notification appears twice, but only 1 email is sent.

**Expected behavior**
You get 1 green notification on success. Not double.

**Comment by woutersamaey** [comment]
@dennisreimann this is the issue we discussed on Mattermost.

**Comment by dennisreimann** [comment]
This is already fixed on master ([reference](https://github.com/btcpayserver/btcpayserver/commit/ed7031981b7e14d2d75bc2d031b9a9b7050c1e48#diff-888a287ff32ebd635bebdd14c74118b0851ffa590ef0715ef13b5d60b221c0fcL3)), just not released in v1.1.2 yet. Will be fixed with the next update.
