### ISSUE TITLE
Exporting invoices to CSV or JSON provides empty results when invoices that aren't complete are selected

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver#2579]
**Describe the bug**
Exporting invoices to CSV or JSON doesn't work. Empty results.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to "Invoices" in the backoffice
2. Select some invoices or all, doesn't matter
3. Click Export
4. Choose "CSV" or "JSON"
5. You get an empty CSV or an empty JSON

**Expected behavior**
The invoice data should be there for the items I selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/71019/122526234-5c3a8c00-d01a-11eb-80ce-0d5e2991dc85.png)

![image](https://user-images.githubusercontent.com/71019/122526344-796f5a80-d01a-11eb-8137-b66ab8874798.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:   1.1.2.0
- Deployment Method:  Docker
- Browser:   Chrome latest

**Comment by bolatovumar** [comment]
Seems to be working fine for me both for JSON and CSV in `v1.1.2.0` in prod deployment.

**Comment by woutersamaey** [comment]
That's very strange.

The only think I can add is that I run BTCPay behind an Nginx load balancer and use SSL offloading, but this has never been an issue.

**Comment by bolatovumar** [comment]
@woutersamaey just tried this again and noticed that only those invoices which have status "complete" will show up in the export (not sure if this is intentional, probably yes?). If you don't have any "complete" invoices yet you will get an empty result set when exporting.

**Comment by woutersamaey** [comment]
Ok so it seams by design then. 
If this is the case, I'd propose we change this and add a link or button to "Select all complete".
It could even be a dropdown with all states, so you can select any status you need. 
That way, you can easily select the completed invoices first, then export without thinking about the status. 

If you guys agree, I can do it with some simple jQuery code or maybe even vanilla JS is that's preferred.

**Comment by bolatovumar** [comment]
@woutersamaey I think it will export just the "complete" status invoices no matter what you selected.

**Comment by woutersamaey** [comment]
Yes. That's why I suggest maybe we should change this behavior or at least make it more idiot proof

**Comment by Kukks** [comment]
> Yes. That's why I suggest maybe we should change this behavior or at least make it more idiot proof

I agree, it should focus on the current filter in the UI.

**Comment by pavlenex** [comment]
Concept ACK. When a user manually selects an invoice we should obey that selection, because we cannot know or assume why they may need invoices that aren't complete.

**Comment by pavlenex** [comment]
@rustywave you can take on this one if you want :) https://github.com/btcpayserver/btcpayserver/issues/2579

**Comment by HamroRamro** [comment]
Submitted a PR for this @pavlenex @Kukks - https://github.com/btcpayserver/btcpayserver/pull/4060

**Comment by pavlenex** [comment]
Done in #4060 🎉

**Comment by acapanther** [comment]
Guys or Gals I remember investing this and have screen shots from last year when I did this

**Comment by acapanther** [comment]
It was stolen from my cash app account
