### ISSUE TITLE
Greenfield doc issue: 6 Event Names do not match the 6 values of the `type` field

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver#2580]
**Describe the bug**
Just realized some confusing shit in the Docs. The event names do NOT match the type field.

There are 6 events and 6 `type` values.

Payment Received = InvoiceReceivedPayment
InvoicePaidInFull = Invoice processing???
Invoice settled = InvoiceConfirmed ???
The other 3 are self-explanatory

**Screenshots**
![image](https://user-images.githubusercontent.com/71019/122609386-3050f200-d07e-11eb-9062-e57289c6245d.png)

Can't we name the events like the `type` value to avoid confusion?

This actually cost me quite some time :(

**Comment by woutersamaey** [comment]
@Kukks @NicolasDorier,
Would you mind if I rename the events in the Greenfield docs to better reflect the event 'type' field? It's only documentation and not code, so it wouldn't do any harm, right?

Might even improve the description as well while I'm at it.

**Comment by Kukks** [comment]
I'm not sure what you mean. The docs need to reflect the api as accurately
as possible to allow for automated client generated. Maybe you can add some
additional descriptions instead?

**Comment by woutersamaey** [comment]
I mean that the labels on the left hand side of the screenshot should match the 'type' of the event. 

Can we rename "Invoice Processing" to "Invoice Paid in Full"?

It's just a label in the docs after all right?

**Comment by bolatovumar** [comment]
Makes sense to me. The only thing that stands out is that we always use plain English titles for the description on the left side and using something like `InvoiceReceivedPayment` would break away from that.

**Comment by pavlenex** [comment]
Well, the thing here is... we're using different names for invoice statuses in the greenfield which don't match the current UI. So we cannot really rename these, as they will reflect the UI at some point. Unfortunately, but I don't really see the other way around. Related to #1789

**Comment by woutersamaey** [comment]
I've changed the labels and descriptions in #2598

**Comment by NicolasDorier** [comment]
The name is `InvoiceSettled`, this won't change for two reasons:

1. This is a breaking change to change it back to `InvoiceConfirmed`
2. In the greenfield API there is no distinction between confirmed and completed (unlike the bitpay one). This is why I changed the name.

**Comment by woutersamaey** [comment]
@NicolasDorier I don't understand. The name is just a label in the docs, right? It's the field `type` that defines the event.
Currently the value of `type` is `InvoiceConfirmed`, not `InvoiceSettled`, like I showed in the screenshot. So I'm not changing anything back in #2598 ?
Can you please take another look or help me understand?

**Comment by NicolasDorier** [comment]
@woutersamaey the documentation is wrong the type name is `InvoiceSettled`, the code is using InvoiceSettled as well. You mean the type of the actual event is Confirmed??

**Comment by woutersamaey** [comment]
@NicolasDorier I checked and you're right. The doc is wrong.
The actual event data looks fine, like this:
```
{
  "manuallyMarked": true,
  "deliveryId": "GfnzAVyw63ehZRv6LQwpPw",
  "webhookId": "2z7MjXYzxHbEyE4aNELPJX",
  "originalDeliveryId": "GfnzAVyw63ehZRv6LQwpPw",
  "isRedelivery": false,
  "type": "InvoiceSettled",
  "timestamp": 1624544309,
  "storeId": "Hf9GvFK2dHJehm9J8A6kYfbc1ruc5jEZBKEr9r7jsrLo",
  "invoiceId": "CwYGeS9qUgiDx6hvTusNXL"
}
```

I tried to fix the doc, but it looks like it is autogenerated somehow? How can the doc be wrong then? Unless someone needs to run the generation process again manually?

The doc fragment looks like this
```
        "Invoice settled": {
            "post": {
                "summary": "Invoice settled",
                "description": "An invoice has been settled",
                "parameters": [
                    {
                        "in": "header",
                        "name": "BTCPay-Sig",
                        "required": true,
                        "description": "The HMAC of the body's byte with the secret's of the webhook. `sha256=HMAC256(UTF8(webhook's secret), body)`",
                        "schema": {
                            "type": "string",
                            "example": "sha256=b438519edde5c8144a4f9bcec51a9d346eca6506887c2ceeae1c0092884a97b9"
                        }
                    }
                ],
                "tags": [
                    "Webhooks"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/WebhookInvoiceSettledEvent"
                            }
                        }
                    }
                }
            }
        }
```
The issue should be with `"#/components/schemas/WebhookInvoiceSettledEvent"` then?

In any case, we should fix the doc.
