### ISSUE TITLE
[Visual bug] Invoice actions overlap invoice search help text when expanded

### ISSUE THREAD

**Issue by bolatovumar** [btcpayserver/btcpayserver#2582]
**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to "Invoices" tab
2. Make sure you have at least one invoice
3. Click on the icon button on the left side of the search box
4. Notice help section appears
5. Notice that the bottom of the help section overlaps the "Actions" and "Export" buttons

**Expected behavior**

Invoice help text shouldn't go over any other elements.

**Screenshots**

![Screen Shot 2021-06-19 at 9 03 00 PM](https://user-images.githubusercontent.com/1934678/122661842-62785780-d143-11eb-83a6-1b013d7c1a4f.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: 1.1.2.0

**Comment by dennisreimann** [comment]
Thanks for spotting this. Will review the PR tomorrow!
