### ISSUE TITLE
Expired Invoice Can be Paid Later

### ISSUE THREAD

**Issue by ridetothefuture** [btcpayserver/btcpayserver#2587]
I want to use BTCPayServer in one of my projects and but I have one problem with it. The problem is if someone copies the address from the invoice and the invoice expired. The user can use the copied address and pay it later after expiry. I don't want to like this. If the invoice is expired I don't want it to be paid.

Thanks

**Comment by NicolasDorier** [comment]
In bitcoin, you can't prevent somebody to pay you.

If the user pay you after expiry, the invoice will because `invalid`. At which case, you should see directly with him about what to do.

**Comment by ridetothefuture** [comment]
@NicolasDorier I'm not getting you well. What do you mean by an **invalid invoice**?

**Comment by bolatovumar** [comment]
@ridetothefuture this means if you go to your BTCPay instance `/invoices?searchTerm=status%3Ainvalid` section you will see the invoices in "invalid" state which are the ones which were paid after they expired OR the ones you marked as invalid explicitly OR for some other reason which I'm not remembering.

**Comment by ridetothefuture** [comment]
@bolatovumar thats not marked as invalid. BTCPayServer is marking as latePaid or partialPaid

**Comment by pavlenex** [comment]
As mentioned, you can't really prevent anybody from paying, however, the invoice can be marked as `paid late` and you can manually mark it as invalid if you choose to do so and refund your customer.
