### ISSUE TITLE
Greenfield API: Cannot set an invoice status to `Complete`. Should it be `Settled` instead? Documentation error.

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver#2597]
**Describe the bug**
The Greenfield API tells me that I can set an invoice to `Complete`, using the call "Mark Invoice Status".
However, it appears there is no status `Complete` in the C# code. There is `Settled` though. No `Complete`.

The error I get is
```
Error converting value "Complete" to type 'BTCPayServer.Client.Models.InvoiceStatus'. 
```

See docs: https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Invoices_MarkInvoiceStatus

It appears the docs are wrong and `Complete` should instead be `Settled` ?
Setting an invoice as `Invalid` works though, so I believe this is likely a documentation issue.

**Comment by woutersamaey** [comment]
Using the status `Settled` works, so it' a doc issue.

**Comment by pavlenex** [comment]
Have we confirmed this is a doc issue, if it is let's fix it?
