### ISSUE TITLE
Please correct your false marketing.

### ISSUE THREAD

**Issue by vmenond** [btcpayserver/btcpayserver#2609]
Allow me to share some background to explain exactly why the false marketing of BTCPayServer is dangerous to our community.

I am from India, a country where most of the population is under-educated. For a country like India to adopt Bitcoin, education is the prerequisite. Now, when it comes to legal tender and money, India understands a single `unit` of account, like Gold. This makes the process of initiation onto Bitcoin easier. 

Now, we have been looking for solutions to provide vendors - from cafes, restaurant, chaiwalas and paan walas in India. Your marketing led us to you. And then the moment we tried the software all these shitcoins emerged at the root! 

A few problems here:

1. You lied in calling it BTCPayServer; where it should be ShitcoinPayServer
2. Vendors will now be confused and ask about these shitcoins and want shitcoin support too.
3. The educated among us, whose duty it is to pave the way for Bitcoin as legal tender and raise the standard of living, will also think it is okay to equate shitcoins to Bitcoin in the payments environment (this is possibly a bigger issue because educated people blindly follow this project by virtue of appeal to authority)

Shitcoining in India is a problem and this project is worsening it. It is making our work on Bitcoin more difficult.

This is bad for our community. Please either change your name OR stop supporting shitcoins as a payment processor with BTC leading its name. Anyway, these shitcoins do not stand a chance to compete with Bitcoin as legal tender. Put more work into supporting lightning and real BTC.

This project seems to have casually become the evil it set out to fight.

You can correct this and we hope you do!

**Comment by Kukks** [comment]
You've clearly not attempted to use btcpay. We only develop and work on bitcoin related features, but we allow other communities to merge their altcoin support upstream is they do the work. We do not provide support or a place on the roadmap for anything other than bitcoin features.

Further to that, you can deploy btcpay in bitcoin only mode (and is the default if you do not explicitly attempt to add shitcoins) where not even any of the non bitcoin code makes it to the deployed application.

So get off your fucking high horse. This is free open source self hosted software under an MIT license that lets you do literally anything you want with it. If there are communities that want to add support for their shitcoin which doesn't complicate our architecture, they're free to do so as they also end up providing optimisations and new features and bug fixes along the way (as has been the case with dozens and dozens of contributions over the past few years).

**Comment by Zaxounette** [comment]
Hey @vmenond !

First of all, it would have been appreciated that you don't open an **issue**, but stick to a **discussion** since issues are for bug reports, as **stated in the obnoxious pre-formattted message that you deleted and discarded** before you started typing your message.

As for your actual message content here is, briefly, how the BTCPayServer project works:
* The BTCPayServer foundation develops and supports only Bitcoin (and associated L2, ie Lightning Network)
* All Altcoin integrations are supported & maintained by their respective communities

This lead us a few months ago to separate the project into two different builds.
Upon deployment, you now have the choice between the default Bitcoin-only build, and an Altcoin supporting build.
If you deploy the Bitcoin-only build, you will not see or interact with the Altcoin code in any manner.

**Comment by vmenond** [comment]
Man, really? Youre gna give me these excuses. I know all this. I have tried it. 

If you dont get it, i will not waste any more time.

**Comment by vmenond** [comment]
Its called BTCPayServer. Why not push the shitcoining to an entirely separate project. Do you guys not see the importance in that?

And no need to get abusive @Kukks , chill. I suppose you deep down hate youself for being involved in a sneaky shitcoining project; whatever it is, you, as a custodian of this project ought to be more civil.

**Comment by Kukks** [comment]
> Its called BTCPayServer. Why not push the shitcoining to an entirely separate project. Do you guys not see the importance in that?
> 
> And no need to get abusive @Kukks , chill. I suppose you deep down hate youself for being involved in a sneaky shitcoining project; whatever it is, you, as a custodian of this project ought to be more civil.

**Comment by vmenond** [comment]
I didn't come here to fight. So I will close this issue. I have stated my peace. I hope you guys do the right thing.

**Comment by Kukks** [comment]
> I didn't come here to fight. So I will close this issue. I have stated my peace. I hope you guys do the right thing.

You clearly did come here with the intention to aggravate and instigate with passive aggressive comments. I gave you our reasoning and you shrugged them off as "excuses" and called the project "evil". If you can't see the benefit and value of this project beyond some opt in insignificant features (that we do not market, encourage and support), that's on you.

**Comment by vmenond** [comment]
Okay man, Im frustrated and doing my best at being civil. This is a serious problem to me and as project leaders you guys must be able to handle this better.

**Comment by vmenond** [comment]
Your 'reasoning' is already in the README - I get it, but its just an excuse - to be okay with shitcoining. Thats what i was getting at. Im not just here to rant man, i tried your software and i was let down.

**Comment by Kukks** [comment]
> Your 'reasoning' is already in the README - I get it, but its just an excuse - to be okay with shitcoining. Thats what i was getting at. Im not just here to rant man, i tried your software and i was let down.

The only way you were let down by shitcoins by testing it is if you actively installed shitcoins on your instance..

**Comment by vmenond** [comment]
The setup asks you to chose which shitcoins you want to activate...

**Comment by Eskyee** [comment]
I understand the feeling, shitcoins in BTCPay have put me off too, truth be told.. keepin it honest to bitcoin should of been our long term goal. 
I don't understand how we ever mixed a bitcoin project with a Shitcoin project.
my opinion is known to my team. And is my own opinion... also many people don't understand. Bitcoin let alone Shitcoin.. Esky rant over

**Comment by vmenond** [comment]
Look man, this is besides the point. I get that you have separated shitcoins from bitcoin and what not - thats the bare minimum you had to do. If you dont see the misleading nature of a project called BTCPayServer that supports shitcoins, there is not much more for me to say. From where I stand, this is doing harm because people look up to this project, and when it supports shitcoins casually, they think these are legitimate alternatives for legal tender and makes the entire process of what Bitcoin started more difficult and it makes it more difficult for the few of us who are keeping it Bitcoin-only.

**Comment by vmenond** [comment]
@Eskyee Thank you man!

**Comment by britttttk** [comment]
Fork the project. This conversation sounds familiar! @vmenond

**Comment by vmenond** [comment]
@britttttk thats too much work, why not present reason and engage in discussions and improve what exists? There are other projects out there like cyphernode and umbrel that are keeping it real to Bitcoin and could use support. That's where I have redirected my efforts. 

The people behind this project are intelligent and influential. At the very least this is important feedback for them.

**Comment by vmenond** [comment]
You are delaying the Bitcoin Standard.

**Comment by vmenond** [comment]
@NicolasDorier please consider this.

**Comment by pavlenex** [comment]
Ok, you said what you had, thanks for your feedback, please don't use issues for discussing something. We use issues to keep a track of bugs/to-do. You're free to continue this discussion in `discussions` or on our chat. 

You can read more about our bitcoin-only build here https://blog.btcpayserver.org/btcpay-server-1-0-5-4/
And in our documentation.
