### ISSUE TITLE
No Seed after LND initialization

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#261]
I have had a problem where I could not recover my LND wallet, because I didn't have the seed that was used when creating the LND instance.

We should make sure that the user gets this displayed to be able to make a paper backup from it.

The current implementation is a very high security risk. See https://github.com/lightningnetwork/lnd/issues/1819 @Roasbeef called this "very dangerous"

**Comment by NicolasDorier** [comment]
I agree. Though if I change now, it will break existing deployment so I am in a bad position here.

**Comment by NicolasDorier** [comment]
What will happen if I remove `--noencrypt` for existing deployment?

**Comment by petzsch** [comment]
Encrypting the wallet is one thing. Giving users access to the wallet seed another. :-)

On 0.5-rc1 It's waiting for the lncli to unlock the wallet. :-)

**Comment by NicolasDorier** [comment]
This go hand in hand. I don't have the seed because I use `--noencrypt`

**Comment by petzsch** [comment]
We should probably advice users when upgrading from 0.4.2-beta1 to 0.5-rc1 to close all their channels and sweep their onchain wallets so that a clean wallet can be generated encrypted and with seed for the user.

I know it adds pain to the update process, but keeping users without seeds is the real problem.

**Comment by NicolasDorier** [comment]
LND gives me no way to get a seed if I do not use `--noencrypt`

**Comment by petzsch** [comment]
I see, I thought it would always display the seed when the create gRPC method is called.

**Comment by NicolasDorier** [comment]
Sadly, you don't call `create` when you use `noencrypt`

**Comment by petzsch** [comment]
When the wallet is encrypted, the user would need to unlock the wallet every time the VM is restarted. Storing the decryption key in btcpay wouldn't be a good idea I guess.

I guess we should discuss this in a broader circle?

I'm currently on the standpoint that I won't use LND as long as I don't have the seed.

**Comment by NicolasDorier** [comment]
also, what happen if I call `create` after the node is used?
For clightning you have the same issue btw.

**Comment by NicolasDorier** [comment]
I think storing decryption key in btcpay is what should be done. BTCPay need access to LND funds so there is no work around.

**Comment by petzsch** [comment]
> The create command is used to initialize an lnd wallet from scratch for
> 	the very first time. This is interactive command with one required
> 	argument (the password), and one optional argument (the mnemonic
> 	passphrase).  
> 	The first argument (the password) is required and MUST be greater than
> 	8 characters. This will be used to encrypt the wallet within lnd. This
> 	MUST be remembered as it will be required to fully start up the daemon.
> 	The second argument is an optional 24-word mnemonic derived from BIP
> 	39. If provided, then the internal wallet will use the seed derived
> 	from this mnemonic to generate all keys.
> 	This command returns a 24-word seed in the scenario that NO mnemonic
> 	was provided by the user. This should be written down as it can be used
> 	to potentially recover all on-chain funds, and most off-chain funds as
> 	well.

I assume it overwrites the existing wallet though I'm not sure.

**Comment by NicolasDorier** [comment]
ok so there is no migration path possible as is.

**Comment by mrfelton** [comment]
One option could be integrating a service like Vault into the stack (https://www.vaultproject.io/) which could be used to store the seed and password securely and provide a mechanism to securely retrieve the secrets on a short lived lease when the containers start up in order to automatically unlock the wallets

**Comment by NicolasDorier** [comment]
Closing this for now.

* The seed give a false sense of security, as it does not allow you to get back the money in your channel
* This is only supported by LND
* There is no easy way to migrate existing user to such new system
* LND does not support access to the seed after the wallet has been created

We can reopen once LND give access to the seed, I will expose it in `Server Settings / Services`.
