### ISSUE TITLE
Modify Wallet page and Wallet Setting page unification

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2626]
### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/2276

<div type='discussions-op-text'>

<sup>Originally posted by **pavlenex** February 11, 2021</sup>
With #2164 merged, we've introduced a new Modify Wallet page which in essence is very similar to the Wallet Settings page. However, they do have different information.

I'm opening this discussion to discuss on how we can either distinguish them or unify those pages. Because, right now the flow is quite confusing.
- What is the difference between the two?
- What's the goal of having a modify wallet page?
- What's the goal of having wallet settings page?
- What kind of information are we trying to show with them to the user?

![Screenshot from 2021-02-11 13-20-31](https://user-images.githubusercontent.com/36959754/107636057-5f88ca00-6c6c-11eb-9144-ee14428d618d.png)

![Screenshot from 2021-02-11 13-20-49](https://user-images.githubusercontent.com/36959754/107636067-644d7e00-6c6c-11eb-97c4-ac7b7d9b431d.png)

Ping @dennisreimann @dstrukt @NicolasDorier </div>

**Comment by dstrukt** [comment]
We've discussed this quite a few times in the last design call or two and have a rough plan of action, will determine what else is needed to do and get this resolved.
