### ISSUE TITLE
Shapeshift gives 404

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#263]
Kemoantemo on Slack, discovered a bug, where shapeshift conversion does not work at the checkout, instead it gives 404 error.
I was able to replicate on both live and test installation. Can't say if it's a temporary or a permanent issue.
![screen shot 2018-09-03 at 07 56 48](https://user-images.githubusercontent.com/36959754/44969818-1be3ef00-af4f-11e8-91f4-2ab31b590de6.png)

![screen shot 2018-09-03 at 07 58 22](https://user-images.githubusercontent.com/36959754/44969836-2f8f5580-af4f-11e8-96d0-742e5e397a74.png)

**Comment by kemoantemo** [comment]
ty for reporting here :)

**Comment by bitcoinshirt** [comment]
@NicolasDorier  It looks like the shifty button is depreciated. Shapeshift integration no longer works.

https://twitter.com/ShapeShift_io/status/1036988332235022336

**Comment by astupidmoose** [comment]
Is Skeleton a possibility? Seems more complex: https://info.shapeshift.io/tools/skeleton/#1535055281184-5220b052-34ae

I don't know enough about the code to be able to say if it can work.

**Comment by rockstardev** [comment]
OK we've removed Shapeshift for now, for well known reasons. Moving on ;(

**Comment by Kukks** [comment]
@astupidmoose It's all a bit more complex now which requires some ui development and storing configuration. Hopefully I can find the time to do a changelly version of what is needed and then we can expand form there. See #267
