### ISSUE TITLE
Create a unique identifier for the invoice user for different use-cases (Tag, Customer ID, Product IT)

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2631]
One of our bigger users brought up to our attention that they'd like to have a better way of identifying (grouping) invoices by customer.

> Many customers use BTCPay for payments and frequently we have a need to find in BTCPay all the invoices related to a specific customer. 

> There is a Buyers info section which we could fill in, fill in "Name" and email for example,  and then try to search by buyers info. However, in case I have Users: Joe1 Joe12 Joe123 and search by Joe1, I will receive the info of all listed users

> MB it would be good to have Username field like the OrderID one, that is present in the grid and which could be used for the precise search by this field (mb consider search by full match).

### This has also been brought up by @dstrukt in https://github.com/btcpayserver/btcpayserver/discussions/2630

<div type='discussions-op-text'>

<sup>Originally posted by **dstrukt** June 28, 2021</sup>
One thing I've been considering after seeing all of the new customer fields being added to the "create invoice" view is the notion of adding a customer, so that the "customer" becomes a reusable, re-selectable entity when filling out an invoice.

It's tedious and frustrating if you have to re-enter this information multiple times on an invoice, and this seems like a reasonable means of addressing that problem.

However, there are potentially privacy concerns with this, but I suppose if that information is already being input and stored (?), would enabling this a distinct feature be much different?

There's definitely more to think about here, and what the implementation of this might look like more concretely, but I wanted to throw this out there to get some feedback / get some perspective on something I might not be considering.

Anyway, all feedback and thoughts welcome!</div>

**Comment by pavlenex** [comment]
For this particular use case, I've suggested we create a `Customer ID` field, however, @NicolasDorier pointed out that grouping should also be done by different criteria, such as `Product ID`. Nicolas suggested we call this field `tags` so that it can allow flexibility. Personally, I am not 100% sold on `tags` though it's quite common wording, if `Customer ID` and `Product ID` are the only use-cases perhaps we can have those two fields. The main question is, would `tags` make sense for people?

**Comment by dstrukt** [comment]
AFAIA, those would be the only two use-cases.

Need to think on the "tag" notion though.

**Comment by pavlenex** [comment]
#2648
