### ISSUE TITLE
Broken image for Specter

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#2634]
**Describe the bug**
Spector wallet image is a broken link.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to Server settings
2. Click on Services
3. Click on Full node RPC - See information
4. See broken Specter image

**Expected behavior**
Displays Specter image

**Screenshots**

![image](https://user-images.githubusercontent.com/39231115/123750734-2dbb7d00-d874-11eb-9629-5d2e48fa6549.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: 1.1.2.0   
- Deployment Method:  LunaNode      
- Browser:  chrome                

**Logs (if applicable)**

**Setup Parameters**

**Additional context**
😢

**Comment by pavlenex** [comment]
Nice catch, can confirm on Safari.
![Screenshot 2021-06-29 at 13 02 24](https://user-images.githubusercontent.com/36959754/123786725-4f4f4f80-d8da-11eb-98f7-d5cd8521784c.png)

**Comment by dennisreimann** [comment]
It's fixed on master already :)
