### ISSUE TITLE
Show the `network fee` in the invoice summary

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2637]
It's been brought up by one of our larger merchants that it would be useful for them to have the [network fee ](https://docs.btcpayserver.org/FAQ/FAQ-Stores/#add-network-fee-to-invoice-vary-with-mining-fees)displayed.

While this data can be achieved with the [invoice export ](https://docs.btcpayserver.org/Accounting/#invoice-export) it seems their workflow differs and that customer supporter representatives would benefit from having a network fee displayed on the invoice itself.

### Use Case

The merchant provides a use-case:

> We have a network fee enabled for every transaction. 

> The customer creates the invoice and the invoice expires. After the invoice expiration, a customer sends partial payment(s) to the invoice and contacts the support team to credit at least a partial amount. As the invoice is expired and BTC are sent after, we do not credit funds automatically and the CS team does it manually.
However, to credit the correct amount, we need  to deduct the amount of network fee (which is not stated anywhere in the invoice for the transaction) 

> Correct partial amount to credit = (Amount Paid - Amount of Transaction Fee) * Rate

Thinking about this, a good place to showcase this would be in the `On-chain payments` invoice summary section between the `Amount` and `Transaction ID`

![Screenshot 2021-06-29 at 13 16 51](https://user-images.githubusercontent.com/36959754/123788725-a1917000-d8dc-11eb-8c65-c5973b29c92b.png)

**Comment by dstrukt** [comment]
Concept ACK.
