### ISSUE TITLE
Disable "Add network fee to invoice (vary with mining fees)" by default 

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#265]
As discussed on Slack this is really pita when network gets spammed: https://forkbitpay.slack.com/archives/C6PSCRFAM/p1536066819000100

Additionally it would be great to add a more detailed explanation that this option is primarily to avoid merchant getting spamed by partial payments by customers.

For customers it is otherwise a penalty fee because the fee gets added to the payment amount and on the other hand the customer still needs to pay the fee for the tx too. On the frontend invoice widget this fee is not visible until you open the details.

**Comment by ndeet** [comment]
Also brought up by @bitcoinshirt that if you uncheck that option the network fee is still visible in the invoice details and should be removed from there as it is possibly confusing for users.
![image](https://user-images.githubusercontent.com/1136761/45057441-ef86ba80-b095-11e8-8982-953f00b4c607.png)

**Comment by NicolasDorier** [comment]
@rockstardev can we have like a small <sup>?</sup> that the user can over with to know the reason of those fees?

I disagree with disabling it by default. This is merchant protection which is needed when the fee will get high. And is only relevant if the customer pays with several wallet (this happen more often if the amount is big).

One thing we can do though, is disabling this fee for the first payment, then enable it from the second payment by default.

**Comment by ndeet** [comment]
@NicolasDorier 
Please take a look at my screenshots in above linked thread. Not sure if this works in high fee situations like now on testnet. I payed 100k sats of 322k sats total which ended up in +500k sats because of the fee. Beside that in high fee situations like now on testnet with $10+ fees you would be stupid to do partial payments if not really needed, so the problem solves itself on high fee situations?

I'm still not convinced that the feature should be enabled by default but only applying it after the first partial payment makes total sense to me as a compromise. Somehow the user should be informed that if they do partial payment the fee will be applied and that they are better off paying the whole amount.

**Comment by NicolasDorier** [comment]
> Somehow the user should be informed that if they do partial payment the fee will be applied and that they are better off paying the whole amount.

how?

**Comment by bitcoinshirt** [comment]
I think that:

1. We should remove the "network cost" from the checkout when it's disabled.
2. Charge the network fee only if 2nd, 3rd, 4th, etc payment is made. It makes no sense to charge it for the 1st payment.
3. Make sure to communicate properly inside the UI of what it is and possibly link it to the future FAQ page where we can cover it more in-depth and possible side-effects of it.

**Comment by kemoantemo** [comment]
+1 for @bitcoinshirt
