### ISSUE TITLE
Cardano(ADA) Integration

### ISSUE THREAD

**Issue by bocd-buildoncardano** [btcpayserver/btcpayserver#266]
The Cardano Foundation released a project called Icarus, to develop Lightweight Clients on top of it. 
( https://github.com/input-output-hk/project-icarus )

I started the Project BOCD ( Build On Cardano ), and possible could do the implementation by myself,
but I want your feedback, did anyone already looked into it if its possible?

**Comment by NicolasDorier** [comment]
Sorry I have no interest into altcoin, I can't help you to integrate.

**Comment by rockstardev** [comment]
@bocd-buildoncardano let me know if and how you are progressing with this.

I am here if you need any questions answered - I can't do much of coding because I don't have experience with Cardano but for any other type of support let me know.

**Comment by Kukks** [comment]
@pavlenex  time to close?
