### ISSUE TITLE
Payment Requests stay open even after the underpaid invoice is marked settled manually

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver#2689]
**Describe the bug**
Payment Requests stay open even after the underpaid invoice is marked settled manually

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Create a Payment Request for a fiat amount (guess it can be in BTC too)
2. Underpay the invoice
3. Mark the invoice as settled manually even though it was underpaid.
4. Now the Payment Request remains open and believes there is still an amount due

**Expected behavior**
Close the Payment Request along with the manually settled invoice.

**Screenshots**
- Notice the amount of 2500 USD is marked complete
- Yet the Payment Request is still open and asking for 35.20 USD
![image](https://user-images.githubusercontent.com/71019/125032496-5884ad00-e08e-11eb-88af-8f1a9f7195f7.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.1.2.0
- Deployment Method:       docker
- Browser:                Does not matter

**Comment by NicolasDorier** [comment]
Ping @Kukks do you have any idea about this one? I checked `GetContributionsByPaymentMethodId` which seemed to account for this possibility already.

**Comment by bolatovumar** [comment]
I think this is because payment requests don't expect to be paid all at once in one invoice but can be paid across multiple invoices so marking just one invoice as complete does not mean that the status of the payment request should change.

**Comment by woutersamaey** [comment]
Honestly, that would be strange. The invoice was for the full amount and I settled that, so that should mean I expect no further payments.

**Comment by bolatovumar** [comment]
One thing I'm noticing which seems like a bug is that if you create a payment request for 1 BTC, pay 0.5 BTC, then edit the payment request to 0.2 BTC, for example, the status of payment request will still be "Pending" even though now it's overpaid by 0.3 BTC.

**Comment by damanic** [comment]
It would be helpful if payment requests could be marked as PAID manually.   

I just emailed a payment request link to a client which presents them with a `Pay Invoice` screen.  I included a alternative payment link for paypal, which they opted for  *booooos all around*     

I also get the impression that btcpayserver presents invoices as payment requests, and payment requests as invoices.  Its a little confusing.

Ultimately we should be able to create an invoice that can be presented to a client for payment, accept multiple payment transactions on that invoice AND allow the issuer to manually mark the invoice as paid should the client pay outside of the provided btcpayserver channel.

**Comment by woutersamaey** [comment]
@damanic an invoice in BTCPay Server is always short lived, so that's something you need to keep in mind.
A Payment Request is a tool to break this limitation and allows for multiple payments (using short lived invoices).

An "invoice" in BTCPay should not be seen as an "invoice" in general accounting terms.

**Comment by Zaxounette** [comment]
> An "invoice" in BTCPay should not be seen as an "invoice" in general accounting terms.

And that might be a problem right there.

**Comment by damanic** [comment]
@woutersamaey 

OK let me substitute the word invoice on my previous comment for the word payment request: 

> Ultimately we should be able to create a __payment request__ that can be presented to a client for payment, accept multiple payment transactions on that __payment request__ AND allow the issuer to manually mark the __payment request__ as paid should the client pay outside of the provided btcpayserver channel.

Any recipient you send a payment request to will see the generated page/document as an invoice.

It is confusing for end users because btcpayserver presents:

- A Payment Request page that has:
    - An invoice summary
    - A Pay invoice button:
        - creates a time limited system-invoice created to request a specific payment amount
        - adds a paid/unpaid system-invoice as an entry in the Payment History list (each with its own invoice id)

The way I see it, to the end user, invoices are being presented as payments/requests. And Payment Requests are presenting as invoices.

But regardless,  my issue at this point aligns with the OP -   there is no way to manually mark a payment request (invoice?!:) paid.
