### ISSUE TITLE
HTTP Onion Header ignored for local install

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#2692]
I have BTCPay Server installed on a rockpro64.

When opening it via Brave, with local ip or local domain, I don't see the `Open in Tor` option in brave.
This might come from the fact the page is not https.

But this is problematic, because there is no easy way to discover the onion address of your install outside going to server settings / services.

Maybe we should add again the Tor link in the login page...
That said, it seems to happen only if it is opened on HTTP. To make sure we don't get black listed again by google safe browsing, maybe we should show the Tor link on login page only if http.

**Comment by dennisreimann** [comment]
Some more context, as I started to look into this a bit and the references might be helpful …

At least from our [general Tor checks](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Hosting/BTCpayMiddleware.cs#L64) it seems we do not exclude the Onion-Location header when using http. 

The [docs](https://community.torproject.org/onion-services/advanced/onion-location/) state this, which explains why the button isn't displayed:

> The webpage defining the Onion-Location header must be served over HTTPS.

So this is indeed the problem and we need to fix it on our end to solve this. Unfortunately we never clearly found out where the [safe browsing issue](https://github.com/btcpayserver/btcpayserver/issues/2139) came from. Nevertheless the first pass of trying, which removed the Tor link from the login page, did not resolve the issue. So, having the link on the login page might actually solve this one without bringing back the safe browsing problem.

**Comment by Kukks** [comment]
ACK for re-adding the onion link -- may we can just have it in the footer so it is less in your face?

**Comment by pavlenex** [comment]
Let's put this on a list for the next design meeting. 
cc @Zaxounette @dstrukt 

I'm not sure where it would be suitable to add it. Once we have dashboard, it can make sense there, but until then, let's brainstorm on where and if we want this re-added.

**Comment by Kukks** [comment]
Personally, I think it should be available on every page to switch easily.

**Comment by dennisreimann** [comment]
I think having it available via the footer would be good, but right now we don't display the/a footer on unauthorized pages, which defeats the purpose of e.g. having it available on the login page. 

Maybe we can have a reduced footer there too. I know @dstrukt mentioned he is thinking about tweaking the footer.

**Comment by pavlenex** [comment]
> Personally, I think it should be available on every page to switch easily.
> […](#)

In a way like dark/light theme switch? I don't know I am still highly doubtful many people would use it or understand it, but let's see if designer/ux team can come up with something.

**Comment by bolatovumar** [comment]
> > Personally, I think it should be available on every page to switch easily.
> > […](#)
> 
> In a way like dark/light theme switch? I don't know I am still highly doubtful many people would use it or understand it, but let's see if designer/ux team can come up with something.

@pavlenex I interpreted the "switch" as just a Tor link for the same page so you can "switch" to the Tor version of whatever page at any time.

**Comment by pavlenex** [comment]
Thinking about this, if we re-design the footer (which we intend to do at some point, maybe it would make sense to have a switch button that can switch between tor version of any page and the clearnet version?

**Comment by dennisreimann** [comment]
@pavlenex Ideally yes, in practice this would only work with browsers that offer Tor support. For other browsers having a direct link doesn't work, that's why we had a "Copy Tor-URL" button originally. This way users can copy it, open a Tor-compatible browser and paste it there. Browsers that support Tor offer this feature natively via the onion location hint.

**Comment by pavlenex** [comment]
Exactly. Not really a benefit imo, but it seems people here want that button in, though for regular users it probably doesn't do much. Perhaps if we'd have a pop-up saying `to use this feature use tor browser` can solve that step of having a "broken page" experience on the clearnet.

**Comment by dennisreimann** [comment]
In the design meeting I think we already decided to re-add the button once we get to rework the footer. 
So we are in good shape, just need to find the time to implement it :)
