### ISSUE TITLE
Error message too verbose/cryptic on "Create an Invoice" field validation

### ISSUE THREAD

**Issue by satwo** [btcpayserver/btcpayserver#2696]
As discussed with @Zaxounette on chat.btcpayserver.org, the error message returned after a failed validation of the `Currency` field on the "Create an Invoice" page is a verbose log that is not suitable for nontechnical end users: 

![image](https://user-images.githubusercontent.com/4956763/125326543-d70d7300-e34a-11eb-9ae8-1e56c6180df7.png)

Elsewhere in BTCPay Server, the `Currency` error message is simple and cogent:

![image](https://user-images.githubusercontent.com/4956763/125327334-aaa62680-e34b-11eb-9d12-0c3ddcf333c8.png)

In the interest of improving UI/UX as well as maintaining consistency with other parts of BTCPay Server,  a simple "Invalid currency" message should suffice. The detailed error logs above could go in the internal logs (if they are not already).

**Comment by Kukks** [comment]
So, this is actually an interesting thing as the validation is very different. 

In the Invoice, we allow you to provide any currency symbol, provided that the rates settings of the store can resolve it. 

In the Apps (and other similar places), we use a hardcoded currency list that ships with BTCPay. 

The hardcoded list provides some benefits in that it provides us with metadata such as name and divisibility, while the rates method provides us with greater flexibility for users (they can also define their own currency in the rates source using the advanced system e.g. `HALFBTC_X = BTC_X * 0.5 `

**Comment by satwo** [comment]
Definitely interesting - that does clarify a few things I was uncertain about.

Given that, would it be better to just leave the message as it is, or do you think it could still benefit from some cleaning up/formatting? Maybe something like `This currency is not supported by your selected rate provider` as suggested by @Zaxounette,  or `Invalid currency - see logs for details`. On that note, is there any reason not to place the extended error messages in the debug logs?

**Comment by Zaxounette** [comment]
We could even give more precision in the error with Kukks info:

Something in the likes of `No rates are configured for this currency. Please check your store settings.`
An error like that could encompass even the custom rates and currencies like in Kukk's example.

**Comment by Kukks** [comment]
>Given that, would it be better to just leave the message as it is, or do you think it could still benefit from some cleaning up/formatting? Maybe something like This currency is not supported by your selected rate provider as suggested by @Zaxounette, or Invalid currency - see logs for details. On that note, is there any reason not to place the extended error messages in the debug logs?

We actually allow the configuration of multiple rate providers (though it is an advanced setting and only used by default by altcoins)

> We could even give more precision in the error with Kukks info:
> 
> Something in the likes of `No rates are configured for this currency. Please check your store settings.`
> An error like that could encompass even the custom rates and currencies like in Kukk's example.

It could be that the current rate provider stopped providing these rates, or is offline.

**Comment by bolatovumar** [comment]
> It could be that the current rate provider stopped providing these rates, or is offline.

Yeah, the error message would have to be something generic like "Please make sure you entered a valid currency symbol, rate provider is configured in store settings and your configured rate provider is online and provides rates for your selected currency.". It's a bit long but should cover most cases?

**Comment by pavlenex** [comment]
@bolatovumar I think that error message makes sense. Perhaps we should document this as well so we can link to it for more in-depth explanation @Zaxounette @britttttk it's a common error.
