### ISSUE TITLE
xpubkey masking via PGP

### ISSUE THREAD

**Issue by austrocoin** [btcpayserver/btcpayserver#27]
In my opinion the Xpub field should be secured with all available messures against unauthorized changes (so mail for approval & 2auth). 

An additional nice security layer would to add the option for an user based setting for PGP in mails. Add a text field on user settings page - so user can paste his public PGP key & all mails send to that user should be encrypted.

On registration & login page should be a captcha, have user setting for  IP whitelist (API & frontend) - last thing I think would round all up... deactivate accounts on X failed logins.

What do you think?

**Comment by NicolasDorier** [comment]
This is quite a lots of feature here.

Would be nice to have, the mails are not very essential though. It is just for renewing password.
Nothing really important is sent.
IP Whitelist I think are better suited to be handled by the reverse proxy configuration. (NGINX/IIS)

**Comment by Eskyee** [comment]
the mails are not very essential though. It is just for renewing password.
Nothing really important is sent. yes I agree .
Nginx takes care of this.. keeping it clean and simple :)

**Comment by austrocoin** [comment]
Agree of course but I would find an additional approval mail for changing xpub not a bad thing - here is where PGP is usefull in my eyes.

**Comment by NicolasDorier** [comment]
@austrocoin yes, actually I think .NET Core has a nice API for this kind of two step confirmation, did not had yet time to look to it though.

**Comment by Bashy** [comment]
@austrocoin 
> deactivate accounts on X failed logins.
In my opinion, this is not a good idea since it gives anyone the ability to deactivate any account in a really easy way.

**Comment by bitcoinshirt** [comment]
I think we can close this issue as it really does not provides concise feature request.

As @NicolasDorier it would be better if you can break it down into tiny specifics. Some of the features suggested by @austrocoin have already been suggested in different PR's.

Perhaps rename this feature to "xpub" security, but I really don't see the point of it quite honestly.

**Comment by pavlenex** [comment]
Closing this, if we mask the PGP  itself with encryption, it can't be used in BTCPay. You brought out some good ideas, some of them like 2FA are already implemented and for #53 there's a separate issue. Feel free to re-formulate with current state of BTCPay and re-open if you have further ideas.
