### ISSUE TITLE
Enhance the `Files` action to accept an array of `fileIds` instead.

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#2707]
Perhaps due to this change, we should enhance the `Files` action to accept an array of `fileIds` instead. We can do this in a separate PR.

_Originally posted by @Kukks in https://github.com/btcpayserver/btcpayserver/pull/2705#r673682464_

**Comment by Kukks** [comment]
@cypherbeerus this one's for you :)

**Comment by cypherbeerus** [comment]
Hi! Had a few suggestions regarding this topic.
- We are not using this status message passed as route parameters anywhere. I think it would make sense to use it to update the UI with "x files were inserted. y failed" information.
https://github.com/btcpayserver/btcpayserver/blob/a7f6bcf36c242197e6b0eccb3d332a757e62adc5/BTCPayServer/Controllers/ServerController.Storage.cs#L193-L200
- After enhancing the files actions to accept an array of fileIds, It makes sense to show a list of cards as confirmations that the file was successfully inserted.
https://github.com/btcpayserver/btcpayserver/blob/a7f6bcf36c242197e6b0eccb3d332a757e62adc5/BTCPayServer/Views/Server/Files.cshtml#L66-L69
- Some UI considerations here, suppose a user uploads a large amount of files, say 50. It would spam the UI with 50 file cards. I'm thinking we display the list of cards when <=10 files are added, else just give a status message confirmation "x files were added".

**Comment by Kukks** [comment]
> Hi! Had a few suggestions regarding this topic.
> 
> * We are not using this status message passed as route parameters anywhere. I think it would make sense to use it to update the UI with "x files were inserted. y failed" information.
>   

The `statusMessage` is actually a relic from an older pattern which we have since abandoned. Previously, we used to provide a statusMessage query parameter option to most GET actions but it bloated the endpoints. The new style is with  `SetStatusMessageModel` which sets a key in `TempData` which is automatically picked up by a `Partial View` that is almost always present (it is in a Layout file). 
I would just get rid of the property to get the code aligned with our current methods. :)


> * After enhancing the files actions to accept an array of fileIds, It makes sense to show a list of cards as confirmations that the file was successfully inserted.
>   

Exactly what I envisioning. 👍 

> * Some UI considerations here, suppose a user uploads a large amount of files, say 50. It would spam the UI with 50 file cards. I'm thinking we display the list of cards when <=10 files are added, else just give a status message confirmation "x files were added".

I think we should start by showing them all. I'm sure our UX pros can chime in once they see our bad UX in that particular case. cc @dstrukt @dennisreimann

**Comment by cypherbeerus** [comment]
a0086c8
Started working on this! Added a multiple boolean in the Files tab so that nothing breaks. Right now I am passing Json strings containing a list of fileIds. Any Suggestions?
