### ISSUE TITLE
Payment rewurst URL contains local IP instead of Tor onion hidden service

### ISSUE THREAD

**Issue by btc-pay-server-user** [btcpayserver/btcpayserver#2710]
**Describe the bug**
Order URL is saved with the domain and not respecting onion domain when accessing BTCPayServer over Tor.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Run BTCPayServer in a way that it can be accessed on local network + as Tor hidden service (in my case its Raspiblitz)
2. Access it from local IP and create and pay an Payment Request
3. Open Tor browser and access `/invoices` page
4. URL marked on screen leads to local 1P

**Expected behavior**
The current way of URL is used. Onion when accessing hidden service, and local network IP when accessing locally

**Screenshots**

![image](https://user-images.githubusercontent.com/87898821/126866678-9d25b31d-990a-4fbe-bc88-0d16e4082cb7.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:   BTCPayServer v1.0.7.2
- Deployment Method:        Raspiblitz
- Browser:                  Tor

**Comment by Kukks** [comment]
> **Describe the bug**
> Order URL is saved with the domain and not respecting onion domain when accessing BTCPayServer over Tor.
> 
> **To Reproduce the bug**
> Steps to reproduce the reported bug:
> 
> 1. Run BTCPayServer in a way that it can be accessed on local network + as Tor hidden service (in my case its Raspiblitz)
> 2. Access it from local IP and create and pay an Payment Request
> 3. Open Tor browser and access `/invoices` page
> 4. URL marked on screen leads to local 1P
> 
> **Expected behavior**
> The current way of URL is used. Onion when accessing hidden service, and local network IP when accessing locally
> 
> **Screenshots**
> 
> ![image](https://user-images.githubusercontent.com/87898821/126866678-9d25b31d-990a-4fbe-bc88-0d16e4082cb7.png)
> 
> **Your BTCPay Environment (please complete the following information):**
> 
> * BTCPay Server Version:   BTCPayServer v1.0.7.2
> * Deployment Method:        Raspiblitz
> * Browser:                  Tor

Tor browser should suggest the alternative hidden service endpoint and ask you to switch to it. The UI will keep showing you URLs based on the current endpoint irrespective of browser choice (if you are on `xxx.onion`, links will be `xxx.onion/..`).

**Comment by btc-pay-server-user** [comment]
Not sure if I understand. To put it in other words: I expect that all URLs will be working regardless of the way I access the BTCPayServer.

**Comment by pavlenex** [comment]
Tried on  v1.3.7.0 and it works, so this is possibly related to Raspiblitz having a different deployment method than our officialy recommended docker. If this is still an issue for you even with latest release, I recommend you ask them and re-open if they identify it's the issue on our end.
