### ISSUE TITLE
Refund of LN invoice not working (500 + exception in logs)

### ISSUE THREAD

**Issue by btc-pay-server-user** [btcpayserver/btcpayserver#2711]
**Describe the bug**
When I click refund I got blank page and 500 in console, logs contains an exception

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Create payment request
2. Pay it
3. Open invoice detail
4. click refund

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/87898821/126866880-58bec616-e9f7-4287-9169-a4d9d680ab16.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    BTCPayServer v1.0.7.2
- Deployment Method:        Raspiblitz
- Browser:                  Tor, Firefox

**Logs (if applicable)**
```
Jul 24 12:16:21 raspberrypi dotnet[14260]: fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMAE4PDNRBMF", Request id "0HMAE4PDNRBMF:00000001": An unhandled exception was thrown by the application.
Jul 24 12:16:21 raspberrypi dotnet[14260]: System.Collections.Generic.KeyNotFoundException: The given key 'BTC' was not present in the dictionary.
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at BTCPayServer.Services.Invoices.PaymentMethodDictionary.get_Item(PaymentMethodId index) in /home/btcpay/btcpayserver/BTCPayServer/Services/Invoices/PaymentMethodDictionary.cs:line 20
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at BTCPayServer.Controllers.InvoiceController.Refund(String invoiceId, RefundModel model, CancellationToken cancellationToken) in /home/btcpay/btcpayserver/BTCPayServer/Controllers/InvoiceController.UI.cs:line 240
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at BTCPayServer.Controllers.InvoiceController.Refund(String invoiceId, CancellationToken cancellationToken) in /home/btcpay/btcpayserver/BTCPayServer/Controllers/InvoiceController.UI.cs:line 210
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Jul 24 12:16:21 raspberrypi dotnet[14260]: --- End of stack trace from previous location where exception was thrown ---
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Jul 24 12:16:21 raspberrypi dotnet[14260]: --- End of stack trace from previous location where exception was thrown ---
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /home/btcpay/btcpayserver/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 92
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /home/btcpay/btcpayserver/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by Kukks** [comment]
> **Describe the bug**
> When I click refund I got blank page and 500 in console, logs contains an exception
> 
> **To Reproduce the bug**
> Steps to reproduce the reported bug:
> 
> 1. Create payment request
> 2. Pay it
> 3. Open invoice detail
> 4. click refund
> 
> **Expected behavior**
> 
> **Screenshots**
> 
> ![image](https://user-images.githubusercontent.com/87898821/126866880-58bec616-e9f7-4287-9169-a4d9d680ab16.png)
> 
> **Your BTCPay Environment (please complete the following information):**
> 
> * BTCPay Server Version:    BTCPayServer v1.0.7.2
> * Deployment Method:        Raspiblitz
> * Browser:                  Tor, Firefox
> 
> **Logs (if applicable)**
> 
> ```
> Jul 24 12:16:21 raspberrypi dotnet[14260]: fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMAE4PDNRBMF", Request id "0HMAE4PDNRBMF:00000001": An unhandled exception was thrown by the application.
> Jul 24 12:16:21 raspberrypi dotnet[14260]: System.Collections.Generic.KeyNotFoundException: The given key 'BTC' was not present in the dictionary.
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at BTCPayServer.Services.Invoices.PaymentMethodDictionary.get_Item(PaymentMethodId index) in /home/btcpay/btcpayserver/BTCPayServer/Services/Invoices/PaymentMethodDictionary.cs:line 20
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at BTCPayServer.Controllers.InvoiceController.Refund(String invoiceId, RefundModel model, CancellationToken cancellationToken) in /home/btcpay/btcpayserver/BTCPayServer/Controllers/InvoiceController.UI.cs:line 240
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at BTCPayServer.Controllers.InvoiceController.Refund(String invoiceId, CancellationToken cancellationToken) in /home/btcpay/btcpayserver/BTCPayServer/Controllers/InvoiceController.UI.cs:line 210
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
> Jul 24 12:16:21 raspberrypi dotnet[14260]: --- End of stack trace from previous location where exception was thrown ---
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
> Jul 24 12:16:21 raspberrypi dotnet[14260]: --- End of stack trace from previous location where exception was thrown ---
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /home/btcpay/btcpayserver/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 92
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /home/btcpay/btcpayserver/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
> Jul 24 12:16:21 raspberrypi dotnet[14260]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
> ```

This will be fixed by #2517
