### ISSUE TITLE
Migrating BTCPay from Azure to LunaNode

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#272]
I know at some point, someone will have this very same question, so I'm asking it here.

What's the least complex way to migrate btcpay to another VPS, or in my case LunaNode?

I'm primarily interested in keeping my c-lightning, but if I can migrate everything, why not.

**Comment by austrocoin** [comment]
Interesting as I just gave more or less same idea to R0ckstardev via twitter incl. some screenshot. Just had same idea for auto-backup settings & db :)

**Comment by bitcoinshirt** [comment]
After talking to both Rockstar and Nicolas, it appears that this is way too complex and can mess things up with my c-lightning. For now, I will not be doing it.
