### ISSUE TITLE
NBXplorer synchronization hanging

### ISSUE THREAD

**Issue by elvece** [btcpayserver/btcpayserver#2722]
**Describe the bug**
With a fully synced Bitcoin Core node, NBXplorer nondeterministically hangs at 99% at various block heights when synchronizing for the first time, or when BTCPayServer has been offline for an extended period. 

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Install Bitcoin Core on an Embassy and let it fully sync.
2. Install BTCPayServer on and Embassy, as well as necessary dependencies.
3. Configure and Start the BTCPayServer service.
4. Launch the service and log in - let the nodes sync.
5. Nondeterministically witness NBXplorer block height hanging at 99% synced. 

**Expected behavior**

With a fully synced Bitcoin Core node, NBXplorer should fully sync to the latest block during initial synchronization and not "get stuck" at 99%.

**Screenshots**

![image](https://user-images.githubusercontent.com/12953208/127543514-d899a9b1-62f6-4638-af8d-ec6898f14da7.png)

**Your BTCPay Environment:**
- EmbassyOS v0.2.14 on RPi4/armv7 
- BTCPay Server Version: 1.1.2
- NBXplorer Version: 2.1.52
- Bitcoin Core Version: 0.21.1
- Deployment Method: Custom Docker deployment on [Start9 Embassy](https://github.com/Start9Labs/btcpayserver-wrapper)
- Browser: Firefox

**Logs (if applicable)**

```
2021-07-28 22:16:09.703 +00:00 [INF] BTC: Explorer url is http://127.0.0.1:24444/

2021-07-28 22:16:09.818 +00:00 [INF] BTC: Cookie file is /datadir/nbxplorer/Main/.cookie

2021-07-28 22:16:10.487 +00:00 [INF] Starting listening NBXplorer (BTC)

2021-07-28 22:16:10.680 +00:00 [INF] Start watching invoices

2021-07-28 22:16:10.786 +00:00 [INF] Starting payment request expiration watcher

2021-07-28 22:16:11.232 +00:00 [INF] 0 pending payment requests being checked since last run

2021-07-28 22:16:11.318 +00:00 [INF] Importing 0 invoices into the search table in 0 pages

2021-07-28 22:16:11.319 +00:00 [INF] Full invoice search import successful

2021-07-28 22:16:11.505 +00:00 [INF] NBXplorer BTC: NotConnected => Synching

2021-07-28 22:17:18.468 +00:00 [INF] User 'cf8994e7-e435-411a-b0ad-221dbabea4b0' logged in.
```

**Additional context**

- Bitcoin Core is fully synced
- NBXplorer is properly whitelisted in bitcoind.conf
- In `settings-nbx.config`, `btc.startheight=-1`
- NBX cookie auth properly configured
- The block height value does not change with a page refresh
- I've read through the synchronization [docs](https://docs.btcpayserver.org/FAQ/FAQ-Synchronization/) and ruled out all scenarios here. Running `ps aux --sort -rss` yields:
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      3035  8.9 16.8 735128 661312 ?       SLl  Jul27 268:09 bitcoind -onion=<redacted>:9050 -externalip=<redacted> -datadir=/root/.bitcoin -conf=/root/
root     26350 18.2  8.2 1223052 325108 ?      Sl   Jul28 237:27 lnd
root      1394  2.1  5.3 677752 211564 ?       SLl  Jul28  28:28 dotnet /nbxplorer/NBXplorer.dll
root     32167  0.0  2.8 236724 111308 ?       Sl   Jul28   0:58 node /app/node_modules/.bin/next start
root     30536  0.7  2.5 211804 99804 ?        Ssl  Jul28   9:48 node /relay/dist/app.js
root      1395  0.6  2.4 711140 96960 ?        SLl  Jul28   9:02 dotnet ./BTCPayServer.dll
```
- Issues I've explored and ruled out their solutions as fixes: [#1215](https://github.com/btcpayserver/btcpayserver/issues/1215) [#2134](https://github.com/btcpayserver/btcpayserver/issues/2134) [ #143](https://github.com/dgarage/NBXplorer/issues/143)

I'm wondering if some value is getting cached as the current blockchain height, and NBXplorer keeps trying to sync from that point and hanging. 

Not using FastSync but wondering if a solution like [this](https://github.com/btcpayserver/btcpayserver/issues/1145#issuecomment-552666023) is necessary to clear out corrupted data.

Please let me know if you need additional logs or information.
Thank you to the team for everything you have created thus far.
CC: @ProofOfKeags

**Comment by NicolasDorier** [comment]
that's bad, can you config me the version of NBXplorer? We had this problem in the past, but long time I saw anyone complain about it.

**Comment by NicolasDorier** [comment]
What may happen though: 

Imagine you turn off your server at block X, and it has pruning for P blocks.
If you turn on again the server at block say `X + P + 1`, NBX would be stuck because it can't get the block X since it has just been pruned. Might it be the issue?

**Comment by guadama** [comment]
The same thing happened to me a few days ago .. run the command btcpay restart and it restarted all services and completed 100%. With dockert

**Comment by elvece** [comment]
The NBXplorer version is currently 2.1.52 - I see there's been an update, so I will upgrade to the latest.

We utilize the on demand block fetching capabilities of [Bitcoin RPC Proxy](https://github.com/Kixunil/btc-rpc-proxy#on-demand-block-fetching) so the bitcoin node behaves as if unpruned. No errors indicating a failure to fetch a block were logged in this service during investigation.

But given that point, is there a recommended value that the `btc.startheight` in the `settings.config` should be set to?

**Comment by kn0wmad** [comment]
> Is this still an ongoing issue? @NicolasDorier anything we need to identify this?

Yes. Have a user that just reported this same issue.  NBXplorer hanging on block 704140.

![image](https://user-images.githubusercontent.com/39687477/138171042-618f8ae0-eed6-48eb-8d5f-0ff1610168c8.png)

**Comment by kn0wmad** [comment]
User was able to fix with a reinstall (even with a data restore, which is a nice bonus).  Currently our only fixes are restarts / re-installs.  Any further insight would be appreciated - thanks for your time.

**Comment by NicolasDorier** [comment]
@kn0wmad @elvece sadly, I am unable to reproduce, maybe fixed as of `2.2.16`?

If that happen again, please ping me. (If I don't reply, contact me on chat.btcpayserver.org)

**Comment by Spixmaster** [comment]
@NicolasDorier I have the same issue with btcpayserver v1.3.7, nbxplorer v2.2.20 and bitcoin-daemon v22.0 pruned to 500 blocks. My server was turned off for about 10 days. I turned on the server yesterday and nbxplorer is stuck at the same block for all the time. I attached the console output and the message on the website.

![screenshot-20220122-101432](https://user-images.githubusercontent.com/46067952/150632711-1a31e2a4-7acb-49a8-8dcc-8cc0215aaa41.png)
![screenshot-20220122-101421](https://user-images.githubusercontent.com/46067952/150632716-a8263342-8950-40be-ac0d-cbfccab7b340.png)

**Comment by nostitos** [comment]
![image](https://github.com/btcpayserver/btcpayserver/assets/48504624/192e2b92-49ca-4ae0-9bb1-deef4b5b526f)
It's happening rather regularly here, about once a month.

**Comment by tonydavis629** [comment]
> ![image](https://github.com/btcpayserver/btcpayserver/assets/48504624/192e2b92-49ca-4ae0-9bb1-deef4b5b526f) It's happening rather regularly here, about once a month.

I'm having the same issue, regularly happening.

**Comment by pavlenex** [comment]
Update btcpay https://x.com/btcpayserver/status/1922845019494318519?s=46

**Comment by Delitants** [comment]
> Update btcpay https://x.com/btcpayserver/status/1922845019494318519?s=46

Updates don't solve it. This issue is quite of a nuisance.

![Image](https://github.com/user-attachments/assets/b11023c0-b42b-4d8a-9de6-9c5e95d3655d)
