### ISSUE TITLE
Core plugins and other system plugins shouldn't be disable-able

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2741]
**Describe the bug**

Core plugins and other system plugins shouldn't be disable-able

ATM it seems that it's possible to attempt to uninstall core plugins. I've verified that this is a bug.

Click Uninstall, then click the restart button

Wait for the server to restart and return to the Plugins page. 

The plugin appears the same as it was originally. 

![pasted image 0-2](https://user-images.githubusercontent.com/36959754/127993124-22df3d4d-253d-4758-8feb-5c413444617d.png)
![pasted image 0](https://user-images.githubusercontent.com/36959754/127993129-0e85974c-4574-4b20-940d-949867bc3e64.png)

**Comment by dennisreimann** [comment]
Looks like something in the loading process doesn't work, these plugins aren't marked as `SystemPlugin` anymore.
