### ISSUE TITLE
Improve look of 404 (and other) error pages

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#275]
When a user clickc on a pay button and the feature is disabled on the store, they are greeted with 
![image](https://user-images.githubusercontent.com/1818366/45693191-d7ff0580-bb5c-11e8-855a-cff28d26e6e6.png)

perhaps we should have a more friendly page version

**Comment by rockstardev** [comment]
This is wider issue... how our error pages (404, 500, etc) are displayed... I guess I can take this on when I have time.
