### ISSUE TITLE
Unify Fido2 authentication under two-factor tab

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2754]
**Description**
As discussed on Mattermost UX/UI
In BTCPay Server user settings (`/Manage/Index`), currently, we have two tabs:

- Two Factor Authentication 
- FIDO2 Authentication

![Screenshot 2021-08-07 at 10 40 04](https://user-images.githubusercontent.com/36959754/128594639-6db3c4d5-b81b-4f15-9e49-4a65a1122076.png)

We should probably unify them in a single Two Factor Authentication view and then offer two options in the same way the current `Two Factor Authentication page does.

Something like: (though precise text can be discussed)

- Two-step log in
   - Authenticator App (Authenticate with 6-digit PIN provided by apps such as Google or Microsoft Authenticator)
   - Security Key (Authenticate with your hardware wallet supporting FIDO2 or a USB key like - Yubikey) 

![Screenshot 2021-08-07 at 10 58 07](https://user-images.githubusercontent.com/36959754/128594921-96553f24-3a29-45a5-b553-f7419bdef8c0.png)

Relevant Mattermost discussion here https://chat.btcpayserver.org/btcpayserver/pl/z4n517jrn7fhjk57cqtz6omeir

**Comment by pavlenex** [comment]
Whoever is tackling the issue (seems like 	@cypherbeerus applied), would be good to double-check with @Kukks that we aren't breaking anything in #2504 or at least develop with #2504 in mind

**Comment by pavlenex** [comment]
@cypherbeerus is assigned to this issue.

**Comment by pavlenex** [comment]
This issue is available for grabs, as the person earlier assigned can not commit to it.

**Comment by dennisreimann** [comment]
I can take care, it makes sense to wait for #2614 to be merged beforehand, as both pages also contain changes from that PR.

**Comment by pavlenex** [comment]
Makes sense @dennisreimann. With #2614 now in, I guess we can put this on a to-do.

**Comment by dennisreimann** [comment]
Yes, will do it this week!
