### ISSUE TITLE
Store Settings will show warning sign (incomplete setup) even if LN as a payment method is configured

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2755]
**Describe the bug**
The store settings will show a warning sign icon (incomplete store setup) even though if Lightning Network is selected.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Create a new store
2. Set up Lightning Network only (do not set up on-chain wallet)
3. You are able to receive payments, but the store settings still show setup incomplete icon

**Expected behavior**

If one of the payment methods is selected, there shouldn't be a warning sign.

**Screenshots**
![Screenshot 2021-08-08 at 18 56 19](https://user-images.githubusercontent.com/36959754/128639614-67997821-bf69-48d4-a98e-7322c8793c6b.png)
![Screenshot 2021-08-08 at 18 56 25](https://user-images.githubusercontent.com/36959754/128639617-141268f4-2739-4bb5-bd9c-c45b375ea86a.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:  v1.1.2.0  
- Deployment Method:      Docker  
- Browser:        Safari 14          

-->

**Comment by bolatovumar** [comment]
Yeah, I noticed this as well but wasn't sure if it's actually a bug as the tooltip you are getting is correct (you don't have an on-chain wallet set-up). In any case #2760 makes it so that this warning shows up only if you don't have any payment methods set-up.
