### ISSUE TITLE
How can i add a wallet?

### ISSUE THREAD

**Issue by JorgeOrtegaHdz** [btcpayserver/btcpayserver#276]
My question is for add a wallet because in the interface I can’t see any bottom and I can’t add a public key for payment in the Derivation scheme.

**Comment by bitcoinshirt** [comment]
In Store>Settings> Derivation Scheme. Depending on the cryptocurrencies you added, on the right-hand side click modify and set up your derivation scheme correctly. This video covers how to set derivation scheme manually (with Electrum or any other wallet) and automatically with a hardware wallet - Nano S.

https://www.youtube.com/watch?v=xX6LyQej0NQ

**Comment by JorgeOrtegaHdz** [comment]
Thank you
