### ISSUE TITLE
I would like to be able to set the routing fee for lightning transactions

### ISSUE THREAD

**Issue by JWWeatherman** [btcpayserver/btcpayserver#277]
It appears to be 1 sat as the default. I would like to be able to increase this or decrease it. It appears to be an option using the command line interface "Incli" but I'm not sure if this is installed correctly as I get a command not found error and it would be nice to have it in the UI (maybe).

**Comment by bitcoinshirt** [comment]
@JWWeatherman Have you figured this one out? I see there was a [discussion on Slack]( https://forkbitpay.slack.com/archives/C6PSCRFAM/p1537297924000100) If so can you post the solution and close the issue? If not let's leave it open.
