### ISSUE TITLE
Invoice with amount = null created by the old bitpay and Greenfield API created lightning invoice with 0.00000000 BTC amount

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#2771]
**Describe the bug**
I've modified the PHP API Toolkit to accept the amount null in order for it to create a Top-Up invoice. However this led to the creating of a Lightning invoice with amount 0.00000000 BTC, which shouldn't happen.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. You can see the bug in action on my [POS site](https://www.we-love-btc.com/v2/?receiver_email=markus%40petzsch.eu&step=create_invoice&product=5)

**Expected behavior**

I would expect on the invoice page to only show the on-chain BTC payment method.

This is what it currently looks like:
[screen1](https://chat.btcpayserver.org/api/v4/files/6t5ozhfxipbp5ffyarj6qssj6c/preview)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    v1.2.0.0
- Deployment Method:        Docker
- Browser:                  Chrome

**Comment by pavlenex** [comment]
Topup invoices aren't supported in the legacy BitPay API ony in Greenfield, as explained on Mattermost, closing this one.

**Comment by petzsch** [comment]
Going to adjust my client. When amount is null, I'll pass paymentMethods as only BTC for the time being.
Still think this should happen serverside wise.

**Comment by bolatovumar** [comment]
@petzsch I just tried both on latest `master` branch locally and on my BTCPay mainnet personal instance with version 1.2.1.0 and it seems to be working as expected (i.e., I get a top-up invoice).

The payload I'm using (you can also skip `amount` entirely, works the same way):

![Screen Shot 2021-08-15 at 9 52 23 PM](https://user-images.githubusercontent.com/1934678/129513100-77131de9-ba53-4226-b7d7-4e9c3f081fae.png)

This is the invoice that I get by following the `checkoutLink` property from the response:

![Screen Shot 2021-08-15 at 9 52 12 PM](https://user-images.githubusercontent.com/1934678/129513137-f157bd7a-04ff-4e0d-a1e9-c6d0db115b44.png)

Also, the link you posted for the POS site doesn't seem to be working.

**Comment by petzsch** [comment]
The first link was using Bitpay API, the [second one](https://www.we-love-btc.com/v2/index_new.php?receiver_email=markus%40petzsch.eu&step=create_invoice&product=5) was Greenfield and should be still working.

Actually your second screenshot shows the problem very well: If you click on Bitcoin under "Pay with", you will be presented with the possibility of selecting Lightning. That lightning invoice should not have been created, as it's not supported for top-up invoices.

About the amount field. So leaving it out and setting it to null worked, but what about the string "undefined", that was mentinoned [here](https://blog.btcpayserver.org/btcpay-server-1-2-0/#top-up-invoices-%F0%9F%A7%BE). - or maybe I misunderstood that one: undefined could just mean leaving it undefined. ^^

**Comment by bolatovumar** [comment]
@petzsch by `undefined` the docs mean the JavaScript value of `undefined` which is equivalent to just not specifying the amount at all. You can't use `undefined` from PHP.

**Comment by petzsch** [comment]
ok, that solves that mystery :-)

Then the question only remains: Why a LN invoice when it's not supported for top-up invoices?

Got arround the issue by setting CheckoutOptions accordingly, when the amount is null. (clientside wise)

**Comment by pavlenex** [comment]
@petzsch is this realted to this https://github.com/btcpayserver/btcpayserver/issues/2772

**Comment by pavlenex** [comment]
> ok, that solves that mystery :-)
> 
> Then the question only remains: Why a LN invoice when it's not supported for top-up invoices?
> 
> Got arround the issue by setting CheckoutOptions accordingly, when the amount is null. (clientside wise)

@petzsch Is this maybe related to this https://github.com/btcpayserver/btcpayserver/issues/2772 ?

**Comment by petzsch** [comment]
> Once again this only happens when Only enable the payment method after user explicitly chooses it is enabled.

That is not enabled on my machine.
Buy yeah, it sounds related.

**Comment by bolatovumar** [comment]
@pavlenex yeah #2772 looks like the same issue to me.

**Comment by bolatovumar** [comment]
@petzsch yeah, you are right, for some reason the invoice allows you to select LN when created via API but not when you create it via GUI. Looking into it.

**Comment by bolatovumar** [comment]
I verified that this [PR](https://github.com/btcpayserver/btcpayserver/pull/2780) should also fix this issue.
