### ISSUE TITLE
Topup invoice shows LN in the checkout -when `Only enable the payment method after user explicitly chooses it` is enabled

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2772]
**Describe the bug**
For some reason, LN shows up as a payment method for a top-up invoice, but once you select it disapperas. However, it provides error n the invoice logs.

**To Reproduce the bug**

Steps to reproduce the reported bug:
1. Make sure you're on 1.2.0 and have LN enabled
2. Make sure to enable `Only enable the payment method after user explicitly chooses it` (This is critical to enable to be able to replicate)
3. Create an invoice without an amount
4. Go to the checkout, you'll see LN as the option
5. Choose LN from the drop-down, nothing happens

**Expected behavior**

LN Shouldn't appear as a payment method option for toupup invoices.

**Screenshots**
![2021-08-12_19-00-41 (1)](https://user-images.githubusercontent.com/36959754/129239416-22d19a49-159d-49a1-bd99-400490d183a1.gif)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:  1.2.0   
- Deployment Method:   Docker, using clightning     

**Logs (if applicable)**

The invoice logs are as a result spammed

Date | Message
-- | --
12/08/2021 19:00:43 | Creation of invoice starting
12/08/2021 19:00:43 | BTC_USD: The rating rule is coingecko(BTC_USD)
12/08/2021 19:00:43 | BTC_USD: The evaluated rating rule is 44089.639
12/08/2021 19:00:43 | BTC (On-Chain): Payment method details creation took 1 milliseconds
12/08/2021 19:00:43 | BTC (Off-Chain): Payment method details creation took 0 milliseconds
12/08/2021 19:00:43 | Saving invoice took 260 milliseconds
12/08/2021 19:00:43 | Invoice W1smhpJQ42aDMBh1PULYWA new event: invoice_created (1001)
12/08/2021 19:00:45 | BTC: Activating
12/08/2021 19:00:45 | BTC (On-Chain): Payjoin is enabled for this invoice.
12/08/2021 19:00:52 | BTC_LightningLike: Activating
12/08/2021 19:00:52 | BTC_LightningLike: Payment method unavailable (Impossible to create lightning invoice (msatoshi: should be positive msat or 'any': invalid token '0'))
12/08/2021 19:00:52 | BTC_LightningLike: Activating
12/08/2021 19:00:52 | BTC_LightningLike: Payment method unavailable (Impossible to create lightning invoice (msatoshi: should be positive msat or 'any': invalid token '0'))
12/08/2021 19:00:52

**Setup Parameters**

**Additional context**

**Comment by pavlenex** [comment]
Once again this only happens when `Only enable the payment method after user explicitly chooses it` is enabled.

**Comment by bolatovumar** [comment]
Looking...
