### ISSUE TITLE
Slow performance of Wallet with large number of BTC transactions

### ISSUE THREAD

**Issue by danielalexiuc** [btcpayserver/btcpayserver#2775]
I have a BTCPayServer store wallet with around 30,000 BTC transactions in it.

Clicking on the "Transactions" Tab in the Wallets page takes around 12 seconds to load. Seems to be getting worse as the number of transactions increases.

I could live with that, but using the Greenfields API endpoint to query recent transactions takes the same amount of time, even if the "limit" parameter is used: e.g.

/api/v1/stores/STORE_ID/payment-methods/OnChain/BTC/wallet/transactions?limit=50

**Comment by pavlenex** [comment]
@NicolasDorier anything we can do about this?
