### ISSUE TITLE
Refund invoice: rounding error in amount

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#2778]
**Describe the bug**
It seems there is a rounding problem in the refund invoice feature. The first amount, should (from my understanding) be the amount received in BTC. (exact amount)

What I get is an offset of 0.00000012 BTC

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Create an Invoice (requested amount was: 0.00027585 BTC / 10.80 €)
2. have the user pay it partial and let it expire (paid: 0.00023152 ₿)
3. try to issue a refund and check the first option. it will display: 0.00023164 ₿

**Expected behavior**

I would have expected to find the exact amount the user sent to be able to send it back.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    v1.2.1.0
- Deployment Method:        Docker
- Browser:                  Chrome

**Comment by Kukks** [comment]
There are various options around the refund rate options, can you provide more info?

**Comment by pavlenex** [comment]
Seems to be truth, we do some weird rounding on the total, it's never the same as the originally paid one 😱

**Comment by NicolasDorier** [comment]
We need to fix this one and make small release.
