### ISSUE TITLE
Lightning payments cannot be detected if `Only enable the payment method after user explicitly chooses it` is selected

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2779]
**Describe the bug**

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to Store Settings > `Only enable the payment method after the user explicitly chooses it` and `enable`
2. Have `Lightning` as a default payment method below a certain amount
3. Create an invoice
4. Pay the invoice 
5. The invoice is paid in LN, and the LN node shows it, but BTCPay doesn't detect the invoice payment at all

**Expected behavior**

**Screenshots**

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:  v1.2.1.0  
- Deployment Method:      Docker  
- Browser:        Safari          

**Logs (if applicable)**

Nothing I can notice

```


16/08/2021 17:50:02 | Creation of invoice starting
-- | --
16/08/2021 17:50:02 | BTC_BTC: The rating rule is 1.0
16/08/2021 17:50:02 | BTC_BTC: The evaluated rating rule is 1.0
16/08/2021 17:50:02 | BTC (Off-Chain): Payment method details creation took 0 milliseconds
16/08/2021 17:50:02 | BTC (On-Chain): Payment method details creation took 0 milliseconds
16/08/2021 17:50:02 | Saving invoice took 11 milliseconds
16/08/2021 17:50:02 | Invoice 59FsW2Sizm3Dhoz1r1Ubpa new event: invoice_created (1001)
16/08/2021 17:50:02 | BTC_LightningLike: Activating
16/08/2021 17:50:16 | BTC: Activating
16/08/2021 17:50:16 | BTC (On-Chain): Payjoin is enabled for this invoice.


```

**Setup Parameters**

**Additional context**

**Comment by pavlenex** [comment]
I think @astupidmoose reported this bug at some point as well.

**Comment by astupidmoose** [comment]
Can confirm, I disabled this feature because I couldn't figure it out. It also seemed to randomly happen and at other times did not.

**Comment by pavlenex** [comment]
@cypherbeerus can you confirm you're still working on this one?

**Comment by Kukks** [comment]
I think I have found a fix for this in my ongoing LNURL pull request.

**Comment by pavlenex** [comment]
@cypherbeerus informed me he cannot commit to this issue, so he's no longer assigned to it.

**Comment by pavlenex** [comment]
This is no longer an issue in 1.3.1, @astupidmoose you may want to check it out.
