### ISSUE TITLE
CSV Import/Export invoices

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#278]
I think it would be really handy if we allow the import and export of invoices in csv and other formats.

Also, we need to allow exportation by filter (export - completed, paid, unpaid, etc).

It appears that merchants could use them for calculating their taxes.

Import feature would come in handy when moving from one btcpay to another to ensure no information is lost.

**Comment by Kukks** [comment]
Would be better off split as two issues. :) Export is easy enough but import may have some restrictions in terms of the invoice id: will need to check it out.

**Comment by rockstardev** [comment]
Actually this one of the oldest issues we have is still open (by @astupidmoose):

https://github.com/btcpayserver/btcpayserver/issues/9

Let's definitely see to first close that one and we can then discuss Import/migration. OK to close this one as duplicate?

**Comment by bitcoinshirt** [comment]
@rockstardev My bad missed it. Closed as a duplicate.
