### ISSUE TITLE
Remove the tagline character limit in the crowdfunding app

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2781]
**Describe the bug**
There's really no need to have a character limit for the `Tagline` in the crowdfunding app.

We should remove it, once we redesign the crowdfunding app, it'll not make much sense to have a limitation there.

**Comment by Patil2099** [comment]
I would love to take this up.

**Comment by pavlenex** [comment]
Sure thing @Patil2099 sounds great! It's a bit related to #2783 to have a bigger picture in mind 😄
