### ISSUE TITLE
Embedded  media in the crowdfunding app isn't responsive

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2782]
**Describe the bug**
When you embed an image, or a video via the crowdfunding app, it's not responsive.

**To Reproduce the bug**
Add video or an image in the crowdfund app, check on mobile. Media looks cut-off.

**Additional context**

Suggested Fix for images

```
/* IMAGE FIX */
div#crowdfund-body-description img {
    max-width: 100%!important;
```

The suggested fix for videos can be something like:

To embed something like this in the editor,
```
<div class="embed-responsive"> <iframe.... </div>
```

Then 
```
.embed-responsive iframe,
.embed-responsive object,
.embed-responsive embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```

**Comment by PresidentNick** [comment]
I'll attempt getting a PR for this one today

**Comment by PresidentNick** [comment]
Too ambitious to get a PR today, lol. I need to deploy this locally first. Running into issues with local building :(

**Comment by pavlenex** [comment]
hey @PresidentNick no worries, take your time. Jump on our mattermost chat https://chat.btcpayserver.org, there's a dev channel there where someone can help troubleshoot the issues you're having if you're stuck.
