### ISSUE TITLE
Confirm the addresses (BTC) in Derivation Path can be bypassed

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#279]
Strange bug, in **Confirm the addresses (BTC)** when setting up the derivation scheme.

The checkup only happens when you clear the public key field, disable derivation scheme and save.

I think it's important this checkup is always shown as soon as the derivation scheme is changed. Strangely I was able to bypass this checkup most of the times. 

![screen shot 2018-09-19 at 22 57 25](https://user-images.githubusercontent.com/36959754/45781102-6b206400-bc5f-11e8-91e3-7fd3a869b2e4.png)

**Comment by Kukks** [comment]
Seems like this was introduced during the addition of Enabled/Disabled payment methods feature.

**Comment by bitcoinshirt** [comment]
Not sure what it is, but I am confident that it can cause users to set the incorrect derivation path since they wouldn't double-check.
We have to display the checkup every time and don't allow the bypass in any case.

**Comment by NicolasDorier** [comment]
Fixed by dcc859a#diff-96fe038a36fee5ba45b97e848ec1d70eR106
