### ISSUE TITLE
Don't show the `due` amount if the invoice has been paid

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2790]
**Describe the bug**
For some reason, when the invoice is paid, we show the `due amount` = 0, which is a confusing UX. 
In our recent crowdfunding, two people reported they are confused by seeing `0` on the invoice page that has been paid already. 

My proposal is that we completely remove it from the invoice page or communicate it as a `due` but it doesn't really make sense because `due = 0` is still not something that we should show, if the invoice is paid (settled), it's logical that it's been paid in full.

Furthermore the `expand arrow` isn't really visible.

![Screenshot 2021-08-18 at 13 09 22](https://user-images.githubusercontent.com/36959754/129888178-08bc71d0-ae64-4226-94d8-6c62e8e8b0ff.png)
![Screenshot 2021-08-18 at 13 09 28](https://user-images.githubusercontent.com/36959754/129888201-64e2267e-d39e-470e-b574-7075e6116024.png)

We can also discuss removing that entire text header which IMO seems to be an overkill of info.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Create an invoice with an amount
2. Pay it fully
4. See the `0` on the checkout page.

**Expected behavior**

**Screenshots**

![Screenshot 2021-08-18 at 12 39 30](https://user-images.githubusercontent.com/36959754/129887846-2712ab76-b293-4f2c-a49e-378a69823899.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    
- Deployment Method:        
- Browser:                  

**Logs (if applicable)**

**Setup Parameters**

**Additional context**

**Comment by bolatovumar** [comment]
@pavlenex I adjusted the invoice to:

1. Not show the "due" row in details at the bottom if it's zero
2. Not show the "due" amount at the top if it's zero <-- this looks a bit weird because once amount owed is zero it quickly disappears and then the paid amount appears in its place right away.

You can see the change in the videos attached to the draft PR.

**Comment by pavlenex** [comment]
#2798
