### ISSUE TITLE
Coinswitch exchange closed

### ISSUE THREAD

**Issue by Spixmaster** [btcpayserver/btcpayserver#2799]
I tried to create an account at Coinswitch which does not work. So I contacted the support and they told me that they closed their exchange permanently.

This is the response they sent me.
> Dear Customer, 
> 
> Thanks for contacting CoinSwitch Support.
> ​
> Our apologies on the delay. Unfortunately we have decided to close of our exchange platform indefinitely. As such the login feature would also be unavailable. 
> ​
> We apologize for any inconvenience caused on the matter.
> 
> Sincerely,
> Anurag

Therefore, the Coinswitch integration in this software is no longer usable.

**Comment by pavlenex** [comment]
CoinSwitch will be packed as a plugin soon. The reason why we don't want it removed is that perhaps it can serve as an inspiration for people who may want to do a similar plugin, but this will very soon be abstracted from the btcpayserver itself.

**Comment by SplatDev** [comment]
They told me via support they only allow Indians (I contacted them after getting a firebase error when registering)

**Comment by pavlenex** [comment]
CoinSwitched has been removed from the `master` will be removed in the next release.
