### ISSUE TITLE
Greenfield API: Remove redundant/unused parameters in payment methods

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#2801]
**Describe the bug**
As discussed on Mattermost chat there are a few endpoints with parameters that make no sense in the context.

1) `cryptoCode` in "Updating payment methods" requests:
https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreOnChainPaymentMethods_UpdateOnChainPaymentMethod
and
https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreLightningNetworkPaymentMethods_UpdateLightningNetworkPaymentMethod

2) `enabled` in "preview of payment addresses":
https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreOnChainPaymentMethods_GetOnChainPaymentMethodPreview

**Comment by NicolasDorier** [comment]
Fixed
