### ISSUE TITLE
[Greenfield Internal Lightning PAY] returns 200 "success" when payment actually fails due to the invoice being already paid

### ISSUE THREAD

**Issue by ethanrose** [btcpayserver/btcpayserver#2803]
**Describe the bug**
The greenfield API POST call to pay an invoice:
`/api/v1/server/lightning/btc/invoices/pay`
Returns a 200 success if attempting a duplicate payment.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Pay an invoice via the API
2. Pay the same invoice again.
3. Get a 200 success even though the payment wasn't successful

**Expected behavior**

Probably either a 400 or 422 response since the payment doesn't happen / balance doesn't change when I repay a paid invoice.
(Actually, RTL shows a 500 when attempting a repeat payment via the UI, but the greenfield API proceeds to send a 200.)

Thanks so much for your amazing work, btcpayServer is incredible.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.2.1.0
- Deployment Method:        LunaNode
- Browser:                  Chrome

**Comment by pavlenex** [comment]
Talked with @Kukks about it, but it seems there's not much we can do on our end.

The suggested approach was:

Add enum value to the pay results (add already paid?) btcpay.lightning. But we have to go through **all** implementations and see if they have `already paid` enum.

So at the moment seems a bit out of scope.
