### ISSUE TITLE
when scanning an animated QR of signed PSBT from Specter-DIY only 1/n parts is scanned successfully

### ISSUE THREAD

**Issue by dimaatmelodromru** [btcpayserver/btcpayserver#2813]
**Describe the bug**
when scanning an animated QR of signed PSBT from Specter-DIY only 1/n parts is scanned successfully

**To Reproduce the bug**
Steps to reproduce the reported bug:
Attempt to spend from a watch-only wallet
Scan unsigned PSBT QR with Specter-DIY (the best HWW ever)
Sign, display QR
Attempt to scan the signed QR 

**Expected behavior**
N of N is scanned

**Screenshots**
video attached

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    
- Deployment Method:        
- Browser:                  
Latest version
Lunanode docker deployment
**Logs (if applicable)**
none

**Setup Parameters**
not relevant

**Additional context**

https://user-images.githubusercontent.com/4951450/131164918-d93f6eb2-8d36-49bc-94ff-55f9d7ab71bd.mp4

**Comment by pavlenex** [comment]
@Kukks can you look into this one? If it's really a bug maybe we can include it in a bug-fix release.
