### ISSUE TITLE
'Form submission failed' error when trying to update Point of Sale app in Chromium browser

### ISSUE THREAD

**Issue by musdom** [btcpayserver/btcpayserver#2816]
**Describe the bug**
Unable to perform any updates on the default PoS app in BTCPay Server mainnet demo. Same problem in btcpayjungle.com running v1.1.0.0. 

Bug only occurs in Chromium but not in Firefox.

**To Reproduce the bug**
Steps to reproduce the reported bug:
Using Chromium browser,
1. Go to Apps > Settings
2. Edit any field, then click 'Save Settings'
3. Nothing happens. In browser dev console:
`Form submission failed, as the <TEXTAREA> element named '' was implicitly closed by reaching the end of the file. Please add an explicit end tag ('</TEXTAREA>')`

**Expected behavior**
Refresh >  'App updated' notification. PoS app updated.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    v1.2.0.0
- Deployment Method:        https://mainnet.demo.btcpayserver.org/
- Browser:                  Chromium, Ubuntu 20.04

**Comment by dennisreimann** [comment]
I cannot reproduce it with the following setup:

- BTCPay Server v1.2.1.0
- Chromium 92.0.4515.159

Also works as expected on the mainnet test instance, which is running v1.2.0.0

![pos](https://user-images.githubusercontent.com/886/131368617-5f1690af-3193-4c65-85fd-5b8838f6e90a.png)

@Eskyee you gave a thumb up to the issue, can you reproduce it?

**Comment by musdom** [comment]
I'm using that exact Chromium version. I also tried incognito mode.

I initially asked esky because I was testing on his instance, before trying out btcpayserver's test instance and running into the same problem.

Not an urgent problem as I am able to update it with Firefox, but I didn't have this problem a few months ago.

![image](https://user-images.githubusercontent.com/9629456/131459204-4e05d42c-56a6-439b-86db-71c2d142f7e8.png)

**Comment by Eskyee** [comment]
@dennisreimann no I couldn't reproduce bug, he asked me if the problem was on my end, also I don't use that browser, so sorry the thumbs up was to acknowledge him reporting the issue, that was all, since we spoke about the issue.. ☕️

**Comment by dennisreimann** [comment]
@musdom There seems to be an error with the textarea that backs the rich text editor. What does the Description field (the rich text editor) contain? There might also be something weird in the HTML, you can switch to that view using the Code view button.

![codeview](https://user-images.githubusercontent.com/886/131491565-91cfe17a-53d6-4da0-8110-a11087fdb7e2.png)

**Comment by musdom** [comment]
@dennisreimann Description field was empty, but shows `<p><br></p>` in code view

Could it be related to this: https://github.com/summernote/summernote/issues/3820

**Comment by dennisreimann** [comment]
@musdom Thanks for digging that up -- I've opened a PR that addresses the issue and will hopefully fix it for you. Unfortunately I still could not reproduce it, but those changes made in the PR should be rather uninvasive and restore compatibility of the rich text editor in Chrome and Chromium.
