### ISSUE TITLE
Impossible to pay to more than 2 people

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#2825]
No way to add another destination
![image](https://user-images.githubusercontent.com/3020646/131450654-6e675fd8-e457-493e-9722-d68ddf498540.png)

**Comment by NicolasDorier** [comment]
Ping @dennisreimann @dstrukt I also changed the design of the current `Add destination` link.
When I tried to find it, it took me a while because my brain just skip over a gray link.

![image](https://user-images.githubusercontent.com/3020646/131452571-9c7e7213-fb1c-4227-a9c1-77a80aed65c4.png)

**Comment by dennisreimann** [comment]
Yes, fair enough, I messed this up in #2750 by forgetting to also add the link to the multiple recipients use case.

**Comment by NicolasDorier** [comment]
I added the link in the last destination as well, since adding a new destination add at the bottom of the list, it prevent the need to scroll back up.
