### ISSUE TITLE
New BTCPay version admin notifications in UI

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#283]
Recently, I made an experiment and noticed that a vast majority of BTCPay merchants use outdated versions. Some big merchants use versions that are a few months old.

When we add features and minor bug-fixes, I assume it's okay if they don't update, but for critical updates, it would be good if we can somehow find a way to notify server admin.

"Enable e-mail notifications about updates"

1. Check for the version on GH occasionally
2. Send an email from their own server in a template

New version xyz available.
To update do xyz
Changelogs:
Type: Critical, Non-Critical,  etc

I'm not sure if this is the way to go or are those callbacks a security issue themselves, but we need a way to notify the users of new versions. 

Thoughts?

**Comment by astupidmoose** [comment]
This can be done via a simple opt-in mailing list, however, it requires a central person to maintain.

**Comment by bitcoinshirt** [comment]
@astupidmoose I don't like the mailing list idea. You pretty much stated that it's central point of failure.
Not sure if it's technically possible, but can't we make some sort of script, which checks Github for the releases and automatically sends an email from BTCPay SMTP to the server admin with a template which provides instructions how to update, changelogs and other important information.

Does anyone else have a better solution? The mailing list can be the easy way out, but it would require for someone to maintain it on the regular basis unless we can automate it somehow.

**Comment by astupidmoose** [comment]
Agreed, if there was a way to monitor releases on github and email that would be cool. 

There seems to be a slack integration here that might also be cool:
https://github.com/sbstjn/github-releases-slack

**Comment by NicolasDorier** [comment]
Can show it in the header as well.

**Comment by bitcoinshirt** [comment]
@NicolasDorier Not quite sure where in the header?

My suggestion to handle updates in the future: 
- Show it as a pop-up as we do with sync
- Changelog on BTCPay site
- Social media sharing (we do this already)
- e-mail notification 

I know you hate e-mail and, but for businesses, it's the most convenient way of communication.

**Comment by bitcoinshirt** [comment]
@NicolasDorier  I like the header/pop-up idea.

Ugh, a centralized mailing list should be maintained and AFAIK you need a physical address displayed at the bottom of the email for [CAN anti-spam laws](https://www.ftc.gov/tips-advice/business-center/guidance/can-spam-act-compliance-guide-business)

Maybe in future, when we have fewer releases @harding can post updates (or at least critical updates) to [Bitcoin Optech newsletter,](https://bitcoinops.org) which is by far the best newsletter out there and we can advise people to subscribe to newsletter like Optech if they don't regularly follow social media, github or watch their own btcpayserver page.

What do you think?

**Comment by NicolasDorier** [comment]
Well I think a mailing list is ok using mailchimp or sendgrid should be OK.
People interested to update can subscribe as they want.

**Comment by bitcoinshirt** [comment]
Alright, so let's add the suggested pop-up or/and notification in the header?

**Comment by NicolasDorier** [comment]
well, if anybody is motivated to code any mailchimp or sendgrid integration I am open for it. Unsure about the best UX, I never used any of those services.

**Comment by britttttk** [comment]
Both are only free for 2000 subscribers or less. I think in terms of scaling the pop-up is better for version updates but sendgrid/mailchimp could be a solution for the admin contact issue @BobleChinois mentioned.

**Comment by bitcoinshirt** [comment]
I've been thinking about this, and I think it's enough that we add a notification somewhere in the UI that there is a new version. E-mails and everything else is too cumbersome to manage.

**Comment by pavlenex** [comment]
I will re-formulate this issue since we don't auto-update, we've discussed to have BTCPay notifications, one of those notifications can be new version notification.
