### ISSUE TITLE
Improve the warning when creating an invoice without the configured wallet

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2834]
This warning is very unclear to a newbie.

Instead of `You need to configure the derivation scheme in order to create an invoice`

We should say something like: `To create an invoice, you need to set up your wallet first`, possibly with the link to the store wallet setup. 

To replicate:
1. Create a store
2. Do not create a wallet
3. Try to create an invoice

![Screenshot 2021-09-02 at 11 34 11](https://user-images.githubusercontent.com/36959754/131820855-21e2c16b-103d-452b-b50a-025e2c2a2948.png)

**Comment by mariodian** [comment]
Should you even be able to create a store without first setting up the wallet? 

I think not. An inexperienced user may just create a store, publish one of the apps (haven't checked if this is possible without the wallet though) and then just think it's all set up properly. Unless they try making a test payment, they wouldn't find out about it until first few paying customers notified them.

**Comment by dennisreimann** [comment]
We'll tackle this problem anbd offer a better UX and more guidance for that soon. Until then this fix by @bolatovumar is a good way to mitigate the problem imho.
