### ISSUE TITLE
Footer is failing to keep in place after last update when using Custom CSS

### ISSUE THREAD

**Issue by bitcoinheiro** [btcpayserver/btcpayserver#2839]
**Describe the bug**
The footer is not behaving as expected. Black string covers UI when scrolling down.
This happens only when using Custom Bootstrap CSS file

**Screenshots**
![image](https://user-images.githubusercontent.com/50273260/132086723-be9df1c9-6dec-4a0d-8512-7848a6a05ca7.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.2.2.0
- Browser:                  Chrome

**Comment by bolatovumar** [comment]
@bitcoinheiro could you specify what custom Bootstrap CSS file you are using? This will make it easier to track down the source of the issue.

**Comment by bitcoinheiro** [comment]
Sure! https://bootswatch.com/5/darkly/bootstrap.min.css
Added as the "Custom Bootstrap CSS file"

**Comment by bolatovumar** [comment]
> Sure! https://bootswatch.com/5/darkly/bootstrap.min.css
> Added as the "Custom Bootstrap CSS file"

I couldn't repro this issue with this theme but found another theme-related issue which I created here: #2850

**Comment by pavlenex** [comment]
Could be something similar to #1536 that was fixed in #1796, but anyways we really shouldn't try to support custom themes imo.

**Comment by dennisreimann** [comment]
I can reproduce this with v1.2.1.0, but not on current master. We recently refactored a lot around the themes, deprecated the Casa and Classic ones and will focus on the default light/dark ones for now.

If possible I'd advise to switch to the default theme and do customizations using the [CSS variables](https://design.btcpayserver.org/styles/btcpayserver-variables.css) we offer.

**Comment by bitcoinheiro** [comment]
Perfect. Problem is with Casa Theme as base - so probably that's the case. Cheers
