### ISSUE TITLE
Feature Idea: Make "Worker Account" - only need admin clone with restriction on server setting

### ISSUE THREAD

**Issue by austrocoin** [btcpayserver/btcpayserver#286]
It would be great to have some "Limited Admin" account for internal workers.

Easy would be a cloned "Admin" and it would just need restriction on server settings menu except "Users" as this the internal workers must setup new ones & be able to edit existing.

**Comment by bitcoinshirt** [comment]
@austrocoin Can you explain a little bit more about the use-case for this?
Why is it helpful and what problem it solves?
