### ISSUE TITLE
Greenfield API: LightningNetwork Payment Method update, requires connectionString

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#2860]
When using the [LN store payment method endpoint](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreLightningNetworkPaymentMethods_UpdateLightningNetworkPaymentMethod) to update LN payment method (pm) it is not possible to just disable the pm by setting `enabled=false` because the endpoint requires `connectionString` to be provided. However in the API docs the `connectionString` is not marked as required and it also makes no sense to be required for just enabling/disabling?

Error if only `enabled=false` is set (and not also `connectionString`) in the request:

```
Got response (422): [{"path":"ConnectionString","message":"Missing connectionString"}]
```

A somewhat related issue with this is if you do not have permission to use the internal node you also can't set the connection string; I assume enabling/disabling should still be possible anyway.

```
Got response (422): [{"path":"ConnectionString","message":"You are not authorized to use the internal lightning node"}]%
```

- BTCPay Server Version:   v1.2.2.0

**Comment by Kukks** [comment]
We made a conscious decision to not allow partial updates for this version of the API to reduce complexity. We may implement this later on as a PATCH endpoint.

**Comment by pavlenex** [comment]
Soo, should this one be closed then?

**Comment by ndeet** [comment]
I think the `connectionString` should then be marked as required on the api docs?

**Comment by bolatovumar** [comment]
@ndeet seems like marking these properties as `required` in the docs doesn't do anything in terms of how they are displayed in the UI.

@Kukks I don't actually see `DisableBOLT11PaymentOption`  being used in the code for the `/api/v1/stores/{storeId}/payment-methods/LightningNetwork/{cryptoCode}` API endpoint at all (maybe I'm just missing something).

**Comment by ndeet** [comment]
@bolatovumar interesting, thank you for trying 💚  Maybe @Kukks has a hint how this works? 😇
