### ISSUE TITLE
Unable to connect to a new peer after upgrade to v1.2.3.0

### ISSUE THREAD

**Issue by mrvickter** [btcpayserver/btcpayserver#2869]
**Describe the bug**
Unable to establish new connection to a peer after upgrade to v1.2.3.0

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to 'Ride The Lightning'
2. Click on 'Lightning'
3. Scroll down to 'Peers>Click "Add Peer">Paste Pubkey'
4. See error "Need: lnc pubkeyhash@hostname"

**Expected behavior**

Expect to establish connection to peer. Attempted with multiple peers.

**Screenshots**

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    v1.2.3.0
- Deployment Method:        Docker
- Browser:                  Chrome v 93.0.4577.63

**Logs (if applicable)**

**Setup Parameters**

**Additional context**

**Comment by NicolasDorier** [comment]
Would you have a screenshot around? Maybe it's RTL issue.

**Comment by NicolasDorier** [comment]
I could reproduce

**Comment by NicolasDorier** [comment]
This is a bug from RTL, they released a new version see https://github.com/Ride-The-Lightning/RTL/releases/tag/v0.11.2 I will bump.

**Comment by NicolasDorier** [comment]
I bumped RTL, and checked it fixed the bug, and it did. Just update again.
