### ISSUE TITLE
Add social icons to footer and remove logo credits

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2884]
As discussed a while ago on Mattermost, we should remove the logo credits and add social icons there instead.

Add links to: 
- GitHub
- Mattermost
- Twitter
![Screenshot 2021-09-15 at 18 26 27](https://user-images.githubusercontent.com/36959754/133472401-73be1f22-bad2-4cfa-b44c-49e573c7fb62.png)

**Comment by 1nF0rmed** [comment]
Hey - I'd like to pick this up

**Comment by pavlenex** [comment]
Feel free to @1nF0rmed 🚀
