### ISSUE TITLE
Update invoice and use latest rate

### ISSUE THREAD

**Issue by ridetothefuture** [btcpayserver/btcpayserver#2888]
Hey guys, How're you?

Why it is not possible to update the invoice and use the latest rate.
My business requirement is to update invoices after every 2 hours if not paid. I wanna lock the price for 2 hours.

I know the payment request but it always uses the latest price.
Thanks

**Comment by Kukks** [comment]
Please follow the issue template next time.

You can configure invoices to expire after 2 hours instead.
