### ISSUE TITLE
Import and export of BTCPay options (migration)

### ISSUE THREAD

**Issue by Karem-sobhy** [btcpayserver/btcpayserver#289]
I think there should be import and export options so we can move Btcpay to another server or maybe a good documented way on how to do this and ty.

**Comment by Kukks** [comment]
Duplicate: 
https://github.com/btcpayserver/btcpayserver/issues/278 & 
https://github.com/btcpayserver/btcpayserver/issues/9

**Comment by rockstardev** [comment]
OK boys, will close this as duplicate and first give you export -> #9

Will be done by the end of the week (Friday)

**Comment by NicolasDorier** [comment]
this was reverted because of reasons
