### ISSUE TITLE
troubleshoot payments from chivo wallet El Salvador

### ISSUE THREAD

**Issue by jquiros2** [btcpayserver/btcpayserver#2890]
So we are in El Salvador, and using BTCPay to help with our BTC adoption especially because it is required by every commerce to accept BTC.

Several days ago we implemented a btcpay node and have done several tests accepting payments from previously existing wallets (Trust, muun, electrum) with no problems.

But the Government created chivo wallet would just crash right after scanning the btcpay payment QR, either with BTC or with lightning.

Now, however, it just says "esta wallet no es valida" (improper wallet) and I presume the Gov has just added that error message to avoid the app crash.
There are $30 "chivo dollars" given to each Salvadorean who installs and registers the wallet, and other things going on.  Maybe these initial $30 can only be spent chivo-chivo?

I am wondering now, how to troubleshoot what the chivo app is trying to do.  Legally, commerce HAS to accept bitcoin.  So far, though, they say it is up to the commerce as to which BTC wallet/payment portal to use.

So... logs-wise, I can' t find issues:

general:
2021-09-16 17:07:51.040 +00:00 [INF] BTC: New block
2021-09-16 17:10:56.046 +00:00 [INF] Invoice Etv..................fKSM new event: invoice_created (1001)
2021-09-16 17:10:56.132 +00:00 [INF] BTC (Lightning): Start listening unix://etc/clightning_bitcoin/lightning-rpc

------------
lightning:
2021-09-16T16:31:52.364Z INFO    lightningd: --------------------------------------------------
2021-09-16T16:31:52.364Z INFO    lightningd: Server started with public key ...................., alias SOMBERSUCKER (color #03116f) and lightningd basedon-v0.10.1-1
2021-09-16T16:31:54.958Z UNUSUAL lightningd: Bitcoin backend now synced.
-------------

nbxplorer:
info: Configuration:  BTC: Loading chain from node
info: Explorer:       BTC: Loading chain...
info: Explorer:       BTC: Chain loaded
info: Explorer:       BTC: NBXplorer is correctly whitelisted by the node
info: Configuration:  BTC: Height: 700819
info: Configuration:  BTC: Saving chain to cache...
info: Configuration:  BTC: Chain cached
info: Explorer:       BTC: Handshaked node
info: Explorer:       BTC: Starting scan at block 700819
info: Events:         BTC: Node state changed: NotStarted => NBXplorerSynching
info: Events:         BTC: Node state changed: NBXplorerSynching => Ready
info: Events:         BTC: New block ....... (700820)
info: Events:         BTC: New block ....... (700821)
info: Events:         BTC: New block ....... (700822)
info: Events:         BTC: New block ....... (700823)
info: Events:         BTC: New block ....... (700824)
info: Events:         BTC: New block ....... (700825)
------------------

I believe it is still on chivo wallet's side, especially because it immediately says "improper wallet" when it gets the address, but any tips on what else to check, overall fitness and our best practices to ensure compatibility for our implementation are welcome!

Thank you in advance.

**Comment by pavlenex** [comment]
This is on Chivo side, awesome that you're using BTCPay in El Salvador. Please join our community chat to discuss this further as it's nothing on our end. https://chat.btcpayserver.org
