### ISSUE TITLE
Invoice email notifcations not being sent

### ISSUE THREAD

**Issue by sipsorcery** [btcpayserver/btcpayserver#2891]
I only noticed recently that I'm not getting invoice notifications from my btcpayserver anymore. It's only a low volume server so it took me a while to notice. I've triple checked the Server and Store email settings and I am able to get test emails though. I've also checked all the boxes on the `Manage/NotificationSettings/notifications` page for my admin user account.

I tried stepping through the code on a local instance and couldn't work out how `InvoiceDetailsModel.NotificationEmail` is ever going to get set. Without that happening it seems like invoice notification emails will also never be sent.

I'm testing by creating invoices manually from the admin portal. Everything works as expected but no notification emails are sent.

Update: The email notifications do work if I hard code my email address in the`InvoiceController` [here](https://github.com/btcpayserver/btcpayserver/blob/603bd2692e892701f0c8ac1e6dc171c1fed6ea16/BTCPayServer/Controllers/InvoiceController.cs#L104).

**Comment by Kukks** [comment]
Indeed they are not meant to be sent by default, only when an invoice's NotificationEmail is set during creation. 

This is really a BitPay compatibility thing. I don't recommend using it.

In the future, we'll be moving the rule engine from BTCTransmuter into BTCPay so you could set up notifications easily.

**Comment by sipsorcery** [comment]
I would still humbly suggest this is a bug.

I am using the old NBitpayClient and setting the `invoice.NotificationEmail` field. On my BtcPay server instance I can see the `NotificationEmail` set when it arrives at the `InvoiceController`. From there it disappears into a transform or two and gets stored in the DB as a blob making it hard to track down where the value is being lost.

I do plan to switch to the new greenfield API in the future but that's a bigger task than fixing a bug with a single field.

I'll keep tracking it down.

**Comment by sipsorcery** [comment]
False alarm. No bug. The new'ish `Manage/NotificationSettings/notifications` options most likely stopped my notification emails being sent. Prior to discovering them I switched to mailgun to see if my mail server was the problem and got caught by only being able to send to a single email address. Once I set the notifications and set mailgun up just right I'm getting notifications again.
