### ISSUE TITLE
Can't create a new webhook through the API. Status 200 with empty body, but no webhook created.

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver#2892]
**Describe the bug**
During the development of an integration we ran into the issue where we can no longer create webhooks through the API. This was working for quite some time, but now suddenly it doesn't anymore.

The create webhook call returns status 200 (success), but the body if empty instead of containing the webhook details. When we  go looking for the webhook in de admin UI, it is not there, so it was not created properly.

We can still create new webhooks though the admin, just not via de API.

I have no errors.

One error I did see earlier, but possibly unrelated is this:
```
fail: PayServer:      Unexpected error when processing a webhook
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.HostedServices.WebhookNotificationManager.Process(String id, Channel`1 channel)
```

I believe this happened during another webhook that was doing a redelivery in the background, so please don't assume this is it. I may be filing another bug report for this once I can be more certain of the cause.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Try to create a webhook through the API
2. Receive 200, but no body.
3. No webhook is created when checking the admin

**Expected behavior**
- Webhook should be created as requested.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:   My own branch "easier-payment-testing" so a few commits behind. Not sure if it matters.
- Deployment Method:       Docker, regtest
- Browser:                N/a

**Logs (if applicable)**
No log messages

**Additional context**
We have been creating quite a few API keys and webhooks during development of our integration, so maybe it broke after a certain time or certain amount of hooks. At present we have 2 stores and 2 webhooks, so nothing overkill.

**Comment by woutersamaey** [comment]
Tested on master branch and the issue is there as well (I was previously a few commits behind).

Is there a way to get a full stack trace instead of this short error?

**Comment by woutersamaey** [comment]
Turns out this was an issue with the Greenfield PHP libary. It did a GET instead of a POST.
I'd still like to keep this issue open as I feel the current behaviour is wrong. The GET call always returns a 200 OK as per the current C# code. Can't we return a 400 Bad Request when data is sent in the body? This would be applicable to more calls, most likely.

**Comment by woutersamaey** [comment]
@NicolasDorier I called the create webhook endpoint but by mistake used a `GET` instead of `POST` so the mistake was on my end. Still, the API responds with `200` and an empty body. I believe this is wrong of the API and it should respond with `400 Bad Request`.
I looked at the code and it's a bit crudely implemented. Some better input validation / error handling would be nice. This would've helped me out + anybody else who makes silly mistakes in the future :)

**Comment by woutersamaey** [comment]
@NicolasDorier Not sure if it helps, but I believe we need an Action Filter as described here:
![image](https://user-images.githubusercontent.com/71019/137452762-6c8df8ad-5166-4a92-a27b-ec85a18f522d.png)

The URL of this page is https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-5.0

The logic would be along these lines:
- Check the arguments of the method vs the parameters in the route (also considering optional arguments)
- Check if the method also takes an object that is filled with the parsed request body
   - If not and there is a request body present. That request would be invalid as it should not contain a request body, so `400 Bad Request`. This is my case.
   - If there is exactly 1 object argument and a request body present, then fine
   - If there are multiple object arguments and a request body present, that would also be bad. Most likely this case is already breaking. I can't imagine ASP being able to identify where to parse the body into.

Does this help?

**Comment by Pornprasert** [comment]
Hi

**Comment by Pornprasert** [comment]
Hi I'm SUCHEEP
