### ISSUE TITLE
Ability to set LN payment as default

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#290]
This seems similar to issue #240 but as it is closed I'm opening a new one here as it is slightliy different anyway.

Goal:
LN payment option should be selectable as default and not on-chain, ability to choose myself.

Current state: can't choose, on-chain always default.

In store settings there is the option: 
> Default crypto currency on checkout

The dropdown only shows BTC and I have no way to choose if LN or on-chain should be default. From what I read on #240 it seems that LN should be the default if available, but for me always on-chain qr code is shown by default.

Other relevant settings:
Invoice sum 18,-
"Do not propose lightning payment... if invoice above": 200 USD
"Do not propose on chain payment ... invoice below": 10 USD

**Comment by bitcoinshirt** [comment]
Slightly related to #251

**Comment by Kixunil** [comment]
I'd love to see this implemented as well.
