### ISSUE TITLE
When creating invoice manually 'OrderId' is converted to octagonal presentation

### ISSUE THREAD

**Issue by JudithWebdev** [btcpayserver/btcpayserver#2906]
**Describe the bug**

When creating an invoice through the BTCPay Server, 'OrderId' is converted to an octagonal number. This does not happen when invoice was created using the Greenfield API. In other words: you can't create an invoice in BTCPay with an OrderId starting with a 0.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. create an invoice in the BTCPay Server with OrderId '000000161'.
2. You will see the number is converted to '113'

**Expected behavior**
OrderId stays '000000161'

**Comment by NicolasDorier** [comment]
I can repro... interesting bug! on it.
