### ISSUE TITLE
LIGHTNING_ALIAS breaks BTCPay and Zap integration - http2 header with status: 502

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#291]
I think I found another bug in BTCPay and Zap.

1. I had no alias for my LND node. Everything worked.
2. Changed the alias with : `export LIGHTNING_ALIAS='MySexyNewAlias'`
3. `. btcpay-setup.sh -i`
4. Getting “Unable to connect to host: Received http2 header with status: 502” in Zap.
5. Tried copying the new config file - same issue. Dang.

In Store Settings when I try to test the connection to my LND node :
Error: Error while connecting to the API (Connection refused)

Be aware that this is with latest Zap and it worked before me giving the Alias to my node.

**Comment by rockstardev** [comment]
I'll ping Jack on this...

**Comment by rockstardev** [comment]
@bitcoinshirt when you SSH into instance can you do `docker ps`? And then if LND is not running properly can you do `docker log <hashoflnd>` to see what problem LND is throwing?

**Comment by bitcoinshirt** [comment]
Here are the logs : 

```
2018-09-25 18:24:04.034 [ERR] UTXN: Failed to re-register for kindergarten sweep transaction at height=542856: -26: 66: min relay fee not met
2018-09-25 18:24:04.034 [ERR] UTXN: Failed to regraduate outputs at height=542856: -26: 66: min relay fee not met
2018-09-25 18:24:04.035 [INF] NTFN: Cancelling epoch notification, epoch_id=3
2018-09-25 18:24:04.035 [ERR] SRVR: unable to start server: -26: 66: min relay fee not met

2018-09-25 18:24:04.035 [INF] FNDG: Funding manager shutting down
2018-09-25 18:24:04.035 [INF] LTND: Shutdown complete
-26: 66: min relay fee not met
```

As you pointed out on Slack it appears to be  [a bug in LND](https://github.com/lightningnetwork/lnd/issues/1541). How on earth it was activated after changing the alias and restarting btcpay - God knows.

**Comment by bitcoinshirt** [comment]
After further investigation and talking with @rockstardev and LND community, I believe that the issue happened quite randomly and I doubt you'll be able to replicate it on your end.

I'm not 100% sure but possibly my node restarted after changing the alias activated the bug mentioned above.

Some of the solutions the community proposed either to apply the patch or "change minrelaytxfee=0  in bitcoin.conf"

However, "this will cause a channel to be stuck as pending until the sweep transaction is mined" so the LND community I upgrade to LND 0.5 after I do this.

So I need to figure out how to change `minrelaytxfee=0`  in btcpay and update LND to 0.5. This is the last time I'm changing my alias.

**Comment by bitcoinshirt** [comment]
The solution : 
` sed -i "s/whitelist=0.0.0.0.0/\\0\\n minrelaytxfee=0/" "$BTCPAY_DOCKER_COMPOSE"`

Just need to update my LND to 0.5 now. Closing te issue.
