### ISSUE TITLE
Feature Request: Dash "InstantSend" support

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#292]
Dash has a feature in their codebase to have transactions send via "Instant Send". This allows for, in my understanding, some transactions to be deemed safe to spend without the needed block confirmations. 

It would be nice for DASH enabled nodes and transactions to be able to use this feature allowing customers who pay in Dash with instant send to skip the store's confirmations. 

Tagging @BenjaminNitschke as he did the original dash support PR in BTCPay and @bdangh as he added the NBXplorer/NBitcoin support

**Comment by BenjaminNitschke** [comment]
Sure, we can add an option to enable InstantSent for DASH tx to the store. Will check what should be done in the code later this week.

**Comment by rockstardev** [comment]
Can you @BenjaminNitschke and @bdangh join our Slack on http://slack.forkbitpay.ninja/ ? We are having small issue with Dash integration and would appreciate help.

**Comment by astupidmoose** [comment]
Does anyone know if any progress has been made on this? 

We'd love to be able to mark any inbound instantsend transactions as confirmed instantly

**Comment by BenjaminNitschke** [comment]
Sorry for the lack of updates, this is currently not in active development, but some work has been done by the dash core team to update the docker images and fix some of the issues. The basic tech is ok, but more testing is needed and we really want to do a Dash example store to give users a better way to get into BtcPayServer. Sadly not much time, but we are planning this work for late April/early May right now.

**Comment by andrasfuchs** [comment]
I would be interested in joining your efforts if InstantSend is still not yet implemented. I worked with NBitcoin before, so I'm not a total newbie, but I would appreciate a little guidance from the more experienced developers here.

Have you started the implementation and do you have a branch that I could fork and continue the work? 
Is there anybody from the Dash Core team watching this thread?

@BenjaminNitschke, is there a preview available of that Dash example store you mentioned?

**Comment by strophy** [comment]
I'm from Dash Core and keeping an eye on this. I'm not a dev, but can put you in touch with the right people if you have specific questions. I was thinking of writing up documentation or a guide on how to get BTCPayServer working from scratch for Dash over the next week or two.

If it was docker holding things up, updates have been pushed since this issue was last updated:
https://hub.docker.com/r/dashpay/dashd

**Comment by andrasfuchs** [comment]
Thank you @strophy, that's very good to know that you are also here! I'll check out the updated docker image.

Technically I would like to know first which part of the BTCPayServer needs more development to complete the InstantSend feature. 
[NBitcoin](https://github.com/MetacoSA/NBitcoin), [NXBExplorer](https://github.com/dgarage/NBXplorer), [BTCPayServer](https://github.com/btcpayserver/btcpayserver) or all of them?

**Comment by astupidmoose** [comment]
I believe some work was committed during the may "contractor expenses" from dash core. However I don't know where that ever ended. 

@snogcel has been active with getting docker images updated for btcpay, so I think the latest docker build includes the most upto date implementation.

**Comment by BenjaminNitschke** [comment]
Hi, thanks for the interest, the work on InstantSend within BtcPayServer is almost done, just didn't have time to test it and we lost a dev last month that was supposed to complete it.

@snogcel has already provided some help and working docker files and a fork: https://github.com/snogcel/btcpayserver

Hopefully by next week this is finally done and closed

**Comment by snogcel** [comment]
Thanks Benjamin,

I really appreciate everything you've attempted to do.

Best regards,
Jon

**Comment by andrasfuchs** [comment]
Thanks guys for the update, I'm looking forward to it!

I still would be interested in joining the Dash team, specially if I can speed up the integrations to various web shops or exchanges (using BTCPayServer). @strophy , is there presently an "integration team" of sorts who I could join or who could connect me with potential Dash accepting clients who need technical help?

I could start up by writing documentation about the process, if it's not already available.

**Comment by strophy** [comment]
Thanks for the offer @andrasfuchs - there is an integrations team, and I'm actually responsible for writing user and business-facing documentation myself. Give me a few days to establish where we are with all of this and I'll get back to you here or in private.

**Comment by andrasfuchs** [comment]
@BenjaminNitschke How is the work going, could you give us a short update?

@strophy What do you think, is there any way I can help your integration team?

**Comment by BenjaminNitschke** [comment]
@andrasfuchs all work is done and has been tested: https://github.com/DeltaEngine/btcpayserver
It is currently being merged into this repo by Dash Core https://github.com/snogcel/btcpayserver/pull/1

I have also added a 5 page guide with all tips and tricks how to develop this and get it up and running, @strophy I will try to cc you.

**Comment by Kukks** [comment]
I took a look at the PR and have a few concerns.

You seem to be bypassing the main feature of the btcpay stack of verifying
your payments through your own full node and relying on a third-party block
explorer. This
data should be coming from NBXplorer.

I also noticed `if` clauses for dash specific code for the UI and the
Invoice Watcher. You should have a separate `HostedService` for Dash
handling in invoices and an abstraction layer built for displaying dash
specific tx data in the UI.

I highly doubt this can be merged in the main BTCPay in its current state

**Comment by andrasfuchs** [comment]
@Kukks You clearly know btcpay much better then I do, could you recommend a way to approach this then?

As I read your comment, my impression is that we would need to extend NBXplorer first to support the Dash InstantSend transaction type. Would you accept that PR for that even if that's not used yet on the UI? (The UI/invoices part would be a separate PR later on)

I'm not sure if that's technically required (I need to investigate the case further), but what if we also need to connect to the Dash masternode network (meaning connecting to multiple Dash nodes using RPC calls) to confirm the InstantSend transactions? Would you be ok with that?

**Comment by Kukks** [comment]
> @Kukks You clearly know btcpay much better then I do, could you recommend a way to approach this then?
> 
> As I read your comment, my impression is that we would need to extend NBXplorer first to support the Dash InstantSend transaction type. Would you accept that PR for that even if that's not used yet on the UI? (The UI/invoices part would be a separate PR later on)
> 
> I'm not sure if that's technically required (I need to investigate the case further), but what if we also need to connect to the Dash masternode network (meaning connecting to multiple Dash nodes using RPC calls) to confirm the InstantSend transactions? Would you be ok with that?

@NicolasDorier  makes the final judgment calls on what gets merged, I help keep his todo list lean. :)
It's important that alts do not pollute the main codebase so those `if DASH` branches would be best converted in independent services.

As far as I am aware, you need to first add that TxLock property to the Dash Transaction in NBitcoin
https://github.com/MetacoSA/NBitcoin/blob/4e71c14cb835163daa38fefda81e34c9b9137347/NBitcoin.Altcoins/Dash.cs#L309
and then you can also add some extension methods to the transaction class like `tx.IsInstantSend()`
From the NBX side of things, you need to make sure that the extra data of Dash is not lost and is forwarded on to the NBX.Client correctly so there is not much work there imo

In BTCPay, I would find a way to either: 
* create a whole parallel service for processing Dashlike network payments( Follow `PaymentTypes` and `IPaymentMethodHandler` and `ICryptoPaymentData`)
* Create a `IHostedService` implementation that listens to new payments, checks if it is InstantSend and then confirms the payment

**Comment by NicolasDorier** [comment]
I would be ok with making a small exception in the current on chain PaymentHandler for Dash.
As Kukks said, I can't merge the proposed PR as it rely on a third party service, pollute UX (a bitcoiner should not have any mention of "Instasend" in the UI)

**Comment by andrasfuchs** [comment]
Thanks @Kukks and @NicolasDorier, I appreciate your input!

@strophy, could you point me to the latest technical documentation about InstantSend? I just want to make sure I have the proper understanding of it before I start working on it ;)

@BenjaminNitschke, would you be interested in joining me with this recommended implementation, or you would rather let me start with it and see how it goes?

**Comment by strophy** [comment]
@BenjaminNitschke knows more about how to go about this, but I can point you to these resources:

https://docs.dash.org/en/stable/developers/integration.html#instantsend
https://dash-docs.github.io/en/developer-guide#llmq-instantsend
https://github.com/dashpay/dips/blob/master/dip-0010.md

**Comment by BenjaminNitschke** [comment]
Thanks for all the interest and update on this discussion. We can do the mentioned changes, the hardest one is to change the NBXplorer, which we really like, but since the dash insight explorer has been working so well, we didn't update NBXplorer and are not using it anywhere (even though our backend is also c#). When we find more time we will update those projects and libraries and then make use of it in BtcPayServer. For now people wanting the new feature, they can simply fork from our repo or wait until it is all proper and merged into the official BtcPayServer.

**Comment by andrasfuchs** [comment]
@strophy Thanks for the links!

@BenjaminNitschke, when you refer to "we", who do you mean? Are you part of the Dash Core team, or do you have a team focusing on the BTCPayServer integrations? 
I might have read it wrong, but my impression is that you would prefer me not to start the work on the InstantSend's preferred implementation, because you already have some resources for it. Is that right?
If so, do you have a time estimate when this feature will be ready to use in BTCPayServer natively?

**Comment by BenjaminNitschke** [comment]
@andrasfuchs we means my company DeltaEngine (where I pushed all the changed, not on my private account used for commenting here), we have 10 developers and I don't do all the work myself ;)
We are not Dash Core nor affiliated, but we started the Dash integration into BtcPayServer over a year ago (based on community requests, not by Dash Core) and were asked by some Dash Core members earlier this year and community members more recently (especially from Austria and Thailand, which seem to be using BtcPayServer quite a bit) to help out, but we didn't have much time this year as we are very overwhelmed with work. We like BtcPayServer/NBitcoin/NBXplorer and feel quite comfortable with it, just the whole docker system is a mess imo.

Anyway, I will check this weekend on what needs to be done and get everything fixed. Feel free to help out if you want, I am always open for push requests on my repos at https://github.com/deltaengine

**Comment by andrasfuchs** [comment]
@BenjaminNitschke Great stuff! Looking forward to your update! ;)

Alright then, I might look into it as well, because I'm interested in learning about NBitcoin and BTCPayServer, and let you know if I've done something related to Dash or InstantSend.

**Comment by andrasfuchs** [comment]
@Kukks, @NicolasDorier I started to dig into the InstantSend feature, and I might be wrong but Dash would probably need its own version of the raw transaction parser.

If I look at the current [RPCClient.GetRawTransactionInfoAsync method](https://github.com/MetacoSA/NBitcoin/blob/0f0af7cffa0b31079a953289378c71d12999ff56/NBitcoin/RPC/RPCClient.cs#L1558), I can see how NBitcoin parses the RPC message from the node to fill in the properties of the Transaction object. 

When I use my client to get the raw transaction of an InstantSend tx in my Dash Core client, I get some extra values (like `instantlock`, `instantlock_internal` and `chainlock`), that would be necessary to process in order to do InstantSend. Ideally I would have them as properties of the DashTransaction object as @Kukks mentioned above.

> getrawtransaction 7f0d4c3c798e4d43de362d930898e35386d31863bf20c3421da5c66cbf345bfb 1

![image](https://user-images.githubusercontent.com/910321/64326663-a92aab00-cfca-11e9-838d-c8af16597e9d.png)

Do I think correctly that this would need a new DashRPCClient class to override the GetRawTransactionInfoAsync method with a Dash-specific parser?

**Comment by NicolasDorier** [comment]
@andrasfuchs you need to modify NBitcoin.Altcoins and add proper properties to `DashTransaction` type (if it exists), else you need to create the type yourself.

Look how we do for other Altcoins (like BCash).

This is not specific to `GetRawTransactionInfo`, this is how all transactions in NBitcoin get created.

**Comment by PastaPastaPasta** [comment]
Hey @andrasfuchs, just found this thread, and I'm wondering if there have been any additional developments over the past year regarding this feature.

Thanks

**Comment by andrasfuchs** [comment]
@PastaPastaPasta I worked on it for a few days, but I got stuck and I didn't reach the point where I could create a good quality pull request, and I got discouraged.

**Comment by BenjaminNitschke** [comment]
@andrasfuchs @PastaPastaPasta we can finish the integration, we still have a open issue in our backlog, but had not much requests this year to finish it up and we don't use it ourselves atm. Will try and see this weekend to clean up the last work and merge it all (plus update to latest btcpayserver and latest dash releases) .. maybe some of the stuff got easier over time as well (just remember the initial setup to be painful to have it easily developable/changeable with all the docker stuff preconfigured) ..

**Comment by astupidmoose** [comment]
I'm still interested in instantsend, and was a main driver behind this but tbh I simply gave up hope it would ever come lol

**Comment by astupidmoose** [comment]
On a semi related note, I just got an email that Dashcore 0.16 is out. Is this a needed upgrade? Will it kill btcpays dash integration? 

I honestly think 0.14.0.1 is the latest version running on btcpay.

**Comment by BenjaminNitschke** [comment]
Except for some rpc calls that changed (most importantly getinfo) nothing important for BtcPayServer has changed, but it is always good to run the latest version. Have updated to v16 and still testing (didn't have much time last weekend, hopefully will get into it again next weekend) ..

**Comment by BenjaminNitschke** [comment]
sorry, we have abandoned this as it wasn't as easy to get the dev environment setup, as mentioned above docker is not our cup of tea and if it doesn't work out of the box on our dev machines, we do not have time to setup a different system atm
