### ISSUE TITLE
Can't send from wallet using camera to scan due to CSP issue

### ISSUE THREAD

**Issue by bolatovumar** [btcpayserver/btcpayserver#2922]
**Describe the bug**

Can't send from wallet using camera to scan on wallet send page. Console indicates that this is due to CSP.

![Screen Shot 2021-09-26 at 5 02 34 PM](https://user-images.githubusercontent.com/1934678/134828929-a854d906-1656-49e9-9336-a2c671eab076.png)

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to wallet
2. Click on "Send" tab
3. Click on "camera" icon to scan address
4. Notice that QR code scanning doesn't work

**Expected behavior**

Expect to be able to use camera to scan a QR code representing a valid address.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.2.4
- Deployment Method: Lunanode
- Browser: Chrome (most likely the same in all other browsers which support CSP)

**Comment by NicolasDorier** [comment]
on it
