### ISSUE TITLE
QR format

### ISSUE THREAD

**Issue by jquiros2** [btcpayserver/btcpayserver#2929]
Hi!  I finally figured out why a wallet (chivo) was not liking addresses.  It is because it can only read "bitcoin:bech32" (both lowercase) addresses in the QR.  See https://github.com/btcpayserver/btcpayserver/issues/2110 for reference.

Right now btcpay server is making them lower:UPPER.

Since I do not know if the wallet developers will update this anytime soon, what might the quickest way to make btcpay generate them as "lower:lower"

**Comment by pavlenex** [comment]
No way to fix it on btcpay-server level, you need to contact Chivo to fix this, they're not following the BIP entirely.
