### ISSUE TITLE
Inline JS doesn't work in Safari due to CSP

### ISSUE THREAD

**Issue by bolatovumar** [btcpayserver/btcpayserver#2930]
**Describe the bug**

Inline JS doesn't work in Safari and it makes @pavlenex  sad. When you try to interact with an element that has inline JS you see this error in the console:

![Screen Shot 2021-09-29 at 9 26 10 PM](https://user-images.githubusercontent.com/1934678/135387453-6d522c08-ae61-4996-9fd5-d77548777c8e.png)

To solve this issue we can either relax CSP settings or update the inline JS to be not inline.

We have quite a bit of inline JS throughout:

![Screen Shot 2021-09-29 at 9 27 05 PM](https://user-images.githubusercontent.com/1934678/135387502-12c10ac4-3f8b-417f-8ef6-7d03b05bd6b0.png)
![Screen Shot 2021-09-29 at 9 27 24 PM](https://user-images.githubusercontent.com/1934678/135387505-fa4ce554-274e-4ba6-82ff-8d9412ada9e6.png)

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to invoices page in Safari (I'm using Safari 14 but newer version should be fine as well)
2. Click on the checkmark on the top left which is supposed to select all invoices on the page
3. Notice it does nothing
4. Notice there is a CSP error in the console

https://user-images.githubusercontent.com/1934678/135387716-1116f77f-6435-4d5c-adaa-d3ecebafe7b3.mov

**Expected behavior**

Expect behaviors which rely on JS to work.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: 1.2.4.0
- Deployment Method: Doesn't matter
- Browser: Safari 14.1.2

**Comment by pavlenex** [comment]
Actually I didn't encounter that many issues on Safari 15.0 the only thing that didn't work for me was #2923

**Comment by pavlenex** [comment]
No, actually you're right @bolatovumar just tested on latest and safari 15.0 and what you mention is indeed broken.

**Comment by dennisreimann** [comment]
@bolatovumar They need the `csp-allow`, because recently Nicolas added strict CSP enforcement.

**Comment by bolatovumar** [comment]
@dennisreimann `csp-allow` doesn't work here, it only works on those elements which use inline JS like this: `href="javascript:console.log('stuff here')"`. This issue happens on inline JS that's used like this `onClick="console.log('stuff here')"`.

**Comment by 2ge** [comment]
I am not sure if this is related issue, but running latest synced from github BTCPayServer v1.2.4.0, one creates Invoice, and in Firefox, Chrome, Brave see blank page on checkout like ".../i/TcyuZbaXJEEVHa8eNNpKPz", in browser console I see many errors like this:

![image](https://user-images.githubusercontent.com/1067032/135918105-6b7e469e-0933-446c-97ad-1768e0ef91cb.png)

result is blank page, I dont see any problems in any logs in btcpayserver docker, I can see source in browser and response code is also 200, so I guess it is problem with JS. Funny enough, in Safari 15 it is working fine.

**Comment by NicolasDorier** [comment]
@2ge we don't have any rocket-loader stuff. So I am wondering if that's not an extension of yours.

**Comment by NicolasDorier** [comment]
We can't just let it works like before, before for that we would need to remove CSP, and for security reason we can't (we got stung by way too many XSS vulnerabilities)

But maybe we can add some way to configure it at server level. (like adding whitelisted sources)

**Comment by 2ge** [comment]
removing rocket-loader from Cloudflare helped. It would be great if this would work also with it. Thanks for support.
