### ISSUE TITLE
Request for 2 new fields on "Get Invoice" response for easier eCommerce integration

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#2933]
### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/2908

<div type='discussions-op-text'>

<sup>Originally posted by **woutersamaey** September 22, 2021</sup>
Can we get 2 new fields on the "Get Invoice" API response?
- Field `canBeMarkedAsInvalid` as boolean
- Field `canBeMarkedAsSettled` as boolean

This makes it easier on the eCommerce integration to know when an invoice can be manually changed without re-implementing the logic on BTCPay Server's end. This offers greater flexibility and if BTCPay Server were to get more rules and logic (through plugins perhaps?) following this logic would be nearly impossible.

Or another solution:

- Field `availableStatusesForManualMarking` as array, containing "Invalid" and "Settled" (or any other string compatible with the "Mark invoice status" API call.

This would allow a more flexible list of statuses for the future.</div>

**Comment by woutersamaey** [comment]
This issue should be closed. It’s been handled.
