### ISSUE TITLE
Blockchain.com wallet stopped recognizing QR-codes

### ISSUE THREAD

**Issue by treasurehunter012** [btcpayserver/btcpayserver#2937]
Hello,

Blockchain.com app stopped recognizing QR codes generated by btcpayserver. We use BIP 49 addresses.

1. QR code generated on the payment page by btcpayserver.
2. Client scans QR code with blockchain.com. Scan completes.
3. After QR scan, wallet address is not passed to the blockchain.com app.

**Comment by pavlenex** [comment]
That's because they're not following the BIP.

See this https://github.com/btcpayserver/btcpayserver/issues/2110

And contact them to update.
