### ISSUE TITLE
Electrum Personal Server Integration

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#294]
It's been discussed before, leaving it on GitHub to save it from oblivion. 

It would be great if somehow users would be able to deploy [Electrum Personal Server](https://github.com/chris-belcher/electrum-personal-server) from BTCPay docker.

As a merchant using Electrum for my BTCPay, I'd love if I could use my own Node with Electrum.

Maybe @chris-belcher can help with this.

**Comment by NicolasDorier** [comment]
I think I need to develop an Electrum server in C# (Might do) on top of NBXplorer.

Chris one is limited in the sense that you need to reboot for changing the HD Key, also, one server support tracking of only one HD Key.

**Comment by chris-belcher** [comment]
Is OP talking about connecting your BTCPay and EPS to the same full node that is easy to install with docker?

> one server support tracking of only one HD Key.

Unless I've misunderstood, this is wrong. One server can support monitoring of any number of master public keys or watch-only addresses.

> limited in the sense that you need to reboot for changing the HD Key

In theory there could be coded an option to Electrum Personal Server for adding new HD keys at runtime. But you'll always need to rescan if they have historical transactions, you don't need to rescan if they're completely new. Rescan can be done at runtime with the `rescanblockchain` RPC call, but it's very slow and not compatible with pruning.

**Comment by bitcoinshirt** [comment]
@chris-belcher My idea is simple - have an easy way for merchants to install EPS right from BTCPay.

**Comment by NicolasDorier** [comment]
@chris-belcher I think if I can add xpub keys at runtime, this might work. For the rescan, this is fine. I already warn users to use BTCPay with a brand new wallet.

**Comment by larry-beck** [comment]
What is the status of being about to install EPS with BTCPay on BTC and LND?

**Comment by pavlenex** [comment]
I originally opened this since I used Electrum with my BTCPay, from there I just now use BTCPay internal wallet which relies on my full node, so I have no need for EPS anymore. There's no progress. Not many people requested this sort of "integration".

**Comment by chris-belcher** [comment]
The relevant issue in EPS is https://github.com/chris-belcher/electrum-personal-server/issues/71

**Comment by pavlenex** [comment]
Ongoing pull-request here. https://github.com/btcpayserver/btcpayserver-docker/pull/227

**Comment by pavlenex** [comment]
EPS is now [integrated](https://github.com/btcpayserver/btcpayserver-docker/pull/227) 🎆
