### ISSUE TITLE
Spark c-lightning wallet Integration

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#295]
It's been discussed before, leaving it on GitHub to save it from oblivion.

It would be nice if c-lightning users could use  [Spark wallet ](https://github.com/shesek/spark-wallet)in BTCPay, similar to LND users have with Zap. 

I'm not sure what's needed here, but the ability to connect without hassle like with Zap (via QR code or something similar) would be epic.

Pinging @shesek as he might be able to help us with this one.

**Comment by NicolasDorier** [comment]
I have not tested anything yet, but already talked with @shesek about what is needed. He added everything I needed, so it should be good here.

**Comment by shesek** [comment]
The login file functionality (requested for more convenient integration in BTCPay's docker compose setup) is still [an open PR](https://github.com/shesek/spark-wallet/pull/8) and was not merged to master, but I'll merge as soon as you confirm it works as expected.

**Comment by bitcoinshirt** [comment]
Ta-da! Implemented by @NicolasDorier
