### ISSUE TITLE
How to let users send dynamic amount btc?

### ISSUE THREAD

**Issue by nguyendangdung** [btcpayserver/btcpayserver#296]
Let's say that I want to create an invoice that not specify amount of bitcoin. Then users can deposit any amount of bitcoin he want like Coinbase Commerce

**Comment by nguyendangdung** [comment]
@bitcoinshirt 
The current behavior is suitable when you sell some products/services have specified prices. When creating a new invoice, you have to give amount that will be shown in payment window as well

**Comment by nguyendangdung** [comment]
@bitcoinshirt 
The current behavior is suitable when you sell some products/services have specified prices. When creating a new invoice, you have to give amount that will be shown in payment window as well

But when the customers don't buy anthing but want to deposit some btc to the store (he has a balance amount in the application). So developers should be able to create the invoice without amount (Amount is not mandatory) and then the payment window won't show the amount too

The the customer cound send any btc he want using a wallet

**Comment by Kukks** [comment]
Ok so to get back to this: It is slightly achievable if you can live with some inferior UX. 
In your store settings, set this:
![image](https://user-images.githubusercontent.com/1818366/46334261-b6555200-c623-11e8-9a31-0a36ee610dbe.png)

Any confirmed transaction that goes through should mark the invoice as paid.

**Comment by nguyendangdung** [comment]
Thank you, @Kukks
I went for your way

**Comment by markgukov** [comment]
Sorry for re-opening the issue, but it's been a year and I'm wondering if there's been any additions or improvements to the suggestion here.

I'm wondering if it's possible to use BTCPay to mimic something that's possible with BitGo:

Imagine a platform where each user gets a single, unique BTC deposit address. The address never changes. Can BTCPay then monitor all addresses and use something like a webhook to notify whenever a deposit has been made?

Thank you for your time.

**Comment by Eskyee** [comment]
It’s never a good idea to reuse a Bitcoin address !!

Not sure to sure about your question 🤔 but check out the Transmuter by Kukks this can do a lot of wizard stuff

**Comment by Kukks** [comment]
@markgukov You should probably use NBXplorer directly for this functionality(it is used by BTCPay under the hood to track xpubs and addresses and txs made to them) 

If you still want to use BTCPay for this:
* Create an xpub for each user
* Create a store for each user and assign the xpub to it
* Generate invoices for each deposit
