### ISSUE TITLE
Rates for Argentinian Peso are always off no matter the exchange

### ISSUE THREAD

**Issue by jfrader** [btcpayserver/btcpayserver#2960]
I know this is not an issue on BTCPAY's end but I wanted to share that usually exchanges use USD/ARS official value to translate to BTC/ARS.

The problem with this approach is that Argentina's regulations have bifurcated into 2 actual USD values: 
- Official Regulated Price
- Free/Black Market Price

If you check local exchanges like ripio.com you can see that its BTC/ARS rate is much higher compared with coingecko or any other.
This is because there's no one selling at the price listed by these exchanges. Only local exchanges know the real usd rate to ars.

So, I'd like to propose to add https://exchange.ripio.com/en/api/ as an option for rates.
Another good example is coinmonitor.info which is used by Muun wallet because of this exact reason.

**Comment by Goro2030** [comment]
I strongly back you up  on this one. It would be great to have coinmonitor.info integrated, or at least Ripio's and BUDA's or Cryptomarket ( that will cover Chile, Colombia, Argentina, Brazil ).

The exchange rate from Coingecko for Chile is also off , not by 180% as in Argentina, but still off.

**Comment by NicolasDorier** [comment]
hi, will do it.

**Comment by NicolasDorier** [comment]
Is it the right rates: https://api.exchange.ripio.com/api/v1/rate/all/ ?
