### ISSUE TITLE
v1.2.4.0 Default payment ignored

### ISSUE THREAD

**Issue by BTCBellyButton** [btcpayserver/btcpayserver#2963]
**Describe the bug**
Below $5 presents only Lightning network payment method  ->   Correct.
Above $150 presents only On chain payment method ->  Correct
Between $5 and $150 presents the on chain payment method  ->  BUG

**To Reproduce the bug**
Set the checkout experience like this:

![Screenshot from 2021-10-09 19-55-21](https://user-images.githubusercontent.com/68573637/136681815-cdecb473-02c3-47f8-977c-366d21414db5.png)

**Expected behavior**

When the amount is between $5 and  $150 the default payment option should be Lightning.
Instead on chain payment is presented.
![Screenshot from 2021-10-09 23-25-55](https://user-images.githubusercontent.com/68573637/136682033-db8c64ed-84b9-41dc-a6f6-60aedc2e3137.png)

It worked fine until after the update to versionv1.2.4.0.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.2.4.0
- Deployment Method:          Manual
- Browser:                              Brave, Chrome,

**Comment by satwo** [comment]
I reproduced this using the same settings you had. Interestingly, my settings for "Enable payment methods only..." are flipped: "BTC (On-Chain)" is above "BTC (Off-Chain).

@pavlenex , I'd be happy to try to solve this one.

**Comment by pavlenex** [comment]
Feel free to @satwo 🚀

**Comment by NicolasDorier** [comment]
We need to fix that before next release.

**Comment by BTCBellyButton** [comment]
How can I test it?
