### ISSUE TITLE
Electrum pull payment

### ISSUE THREAD

**Issue by cryptokq** [btcpayserver/btcpayserver#2979]
I am trying to make a test pullpayment using electrum 4.0.2 seed but I am getting the following error:

The master fingerprint and/or account key path of your seed are not set in the wallet settings.

Where do I get the master finger print or account key path for electrum?

**Comment by pavlenex** [comment]
This is something that you should ask in Electrum community as it's not related to btcpay. Also please in the future post your support questions on our chat.btcpayserver.org or in a github discussion, we use issue only for bug reports.
