### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by shaftzy** [btcpayserver/btcpayserver#299]
Hi guys,

Super new here, but I think the "BTC" part of the name of the project should be dropped. Since it's possible to use other coins and tokens (in the future).

Unsure if this has already been discussed.

Eg: cryptopayserver etc

**Comment by bitcoinshirt** [comment]
ShitCoin Server?

**Comment by Kukks** [comment]
Naaaaaah

**Comment by shaftzy** [comment]
Moonpay!

**Comment by rockstardev** [comment]
ShitPay™ already reserved by BitPay... so we can't use that phrase or they'll get us for trademark infringement.

**Comment by rockstardev** [comment]
OK, everyone had fun
so we are closing this one

1 down, 64 more issues to go
