### ISSUE TITLE
[Bug] custom root path override in crowdfund redirect

### ISSUE THREAD

**Issue by ghost** [btcpayserver/btcpayserver#2992]
**Describe the bug**
When a custom root path is set [in my case `domain.com/btcpay/apps/`], the crowdfund redirect link after successful payment does NOT have the custom root path, and instead redirects to `domain.com/apps/`.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Set custom root path
2. Create crowdfund
3. Pay a perk

Or try it out at https://towardsliberty.com/PraxeologyOfPrivacy

**Expected behavior**

Put the proper custom root path also in the crowdfund redirect.

**Screenshots**

![screenshot_20211019_121307](https://user-images.githubusercontent.com/30683012/137890067-55c8c02f-ed6b-48e5-965a-385b367ac960.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.2.4
- Deployment Method:        deb package Cryptoanarchy Repo
- Browser:                  All

**Additional context**

This was already reported for file storage in #2315 by @kixunil, and fixed in #2318 by @bolatovumar.

**Comment by MaxHillebrand** [comment]
I updated to 1.2.4, and bug is still present.

The crowdfund app settings has no manual input for redirect.
