### ISSUE TITLE
Greenfield API: API docs missing InvoiceProcessing event

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#2999]
The Greenfield API sends an `InvoiceProcessing` event which is also mentioned here in the "authorizedEvents" -> "specificEvents" section:
https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Webhokks_GetWebhook

but is not listed on the left sidebar and also not mentioned in the description of the "type" like here:
https://docs.btcpayserver.org/API/Greenfield/v1/#tag/Webhooks/paths/InvoiceCreated/post

![image](https://user-images.githubusercontent.com/1136761/138072825-c92f6495-c512-4054-875a-e9ed82389dca.png)

**Comment by woutersamaey** [comment]
I guess the docs are outdated and need to be regenerated.
I remember from before that there were 6 event types, but if I look at the C# code, there are now 7.
So, it looks like this event is new and the docs need regeneration.
How this works, I dunno, but I do know there is a process.
I believe the last time this happened, @bolatovumar helped me out.

**Comment by bolatovumar** [comment]
@ndeet @woutersamaey yeah, you are right, it was renamed but docs were not updated.

PR to update the docs here: https://github.com/btcpayserver/btcpayserver/pull/3104
