### ISSUE TITLE
UI: can't see to which URLs webhooks got sent

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#3000]
This is only a minor thing but maybe would be helpful for others too. On the invoice details page you can see the webhook events that got fired which is very nice. You can't see from the UI where that webhook was sent to (URL registered on creating the webhook). So you would need to check the webhook config to know. It get's even more confusing if you have registered multiple webhooks, you can check the exact payload but not where it was sent to.

![image](https://user-images.githubusercontent.com/1136761/138074043-1d83fc96-f585-4bde-be2a-393d52931697.png)

**Comment by satwo** [comment]
Have a fix coming for this shortly.

**Comment by satwo** [comment]
@ndeet Solved this with #3034 but there's a  [small edge case](https://github.com/btcpayserver/btcpayserver/pull/3034#issuecomment-955241265), maybe you could weigh in on it?

**Comment by ndeet** [comment]
Fixed by #3034
