### ISSUE TITLE
[Feature Request] Expose the LND REST API

### ISSUE THREAD

**Issue by danielalexiuc** [btcpayserver/btcpayserver#301]
Expose the LND REST API, in a similar way to the LND GRPC API is already exposed.

This will permit external integration with the LND node for people who won't/can't use GRPC, or who are more familiar with REST.

1. Route external calls and map them directly to the LND REST API:  https://api.lightning.community/rest/index.html#lnd-rest-api-reference

2. Update the Server Settings/Services page with the new REST access type, explaining connection information.

**Comment by rockstardev** [comment]
Coming up in next day or two, definitely before NY Lightning Hackaday
