### ISSUE TITLE
Bump to .net 6.0

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3020]
Opening this on behalf of emperor who's suggested that we should bump from .net 3.1 to 6.0 for our next major release (1.4.0).

Leaving this issue opened for discussion and as a reminder.

**Comment by NicolasDorier** [comment]
6.0 is an LTS, so it is safe to say we won't be bothered for long time (2-3 years) after the update.
I think there is many new cool things, though I don't have it on top of my mind anymore.

Maybe the most significant is hot reload that work not only for cshtml files but for C# files, reducing considerably the feedback loop during development.

**Comment by pavlenex** [comment]
#3198
