### ISSUE TITLE
Payment method unavailable (Lightning Network payment method is not available for top-up invoices)

### ISSUE THREAD

**Issue by mikeriss** [btcpayserver/btcpayserver#3021]
**Describe the bug**
I am using BtcPay Server which I installed through umbrel and want to use the lightning option.  When I try to click on the paybutton I received the error: Error BTC: Payment method unavailable (Lightning Network payment method is not available for top-up invoices).

**To Reproduce the bug**
By clicking "BtcPay Button"

**Expected behavior**
Lightning Invoice to be created

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    BTCPayServer v1.2.3.0
- Deployment Method:      docker through umbrel
- Browser:                  chrome

**Logs (if applicable)**
10/27/2021 10:15:02:Info Creation of invoice starting 10/27/2021 10:15:02:Info BTC_USD: The rating rule is coingecko(BTC_USD) 10/27/2021 10:15:02:Info BTC_USD: The evaluated rating rule is 58870.703 10/27/2021 10:15:02:Info BTC (Off-Chain): Payment method details creation took 0 milliseconds 10/27/2021 10:15:02:Error BTC: Payment method unavailable (Lightning Network payment method is not available for top-up invoices)

**Comment by w0aw** [comment]
Still not released, and if we put amount 0, it instantly settled out

**Comment by bigg-bb** [comment]
Hey @pavlenex @NicolasDorier 

please review and approve [this PR](https://github.com/btcpayserver/BTCPayServer.Lightning/pull/175).

atleast unblock the amountless (0 amount invoice) pathway for LND (only).

atleast allow this Repo's deps to not to block such behavior, so users like me can make custom changes here on own risk and give it a try.

Thank you.
