### ISSUE TITLE
Print view improvements

### ISSUE THREAD

**Issue by satwo** [btcpayserver/btcpayserver#3026]
Some desired improvements for the new `print` view for PoS apps:

> @satwo if you wish, we can open a new issue to iron this one for the next release:
> - Create a better warrning and hide the view when ln is disabeld or lnurl is turned off.
> - Add a print button and adjust print view
> 
> _Originally posted by @pavlenex in https://github.com/btcpayserver/btcpayserver/pull/3019#pullrequestreview-790404431_

**Comment by satwo** [comment]
@pavlenex Reflected on this a little bit; some thoughts.

Regarding the first point, I think it might be a cleaner and simpler solution to keep the current logic of keeping the print view visible, and simply adding the warning label when it can't be used properly. Doing so:

-Gives exposure to this option in case the user isn't aware of it (or is looking for it and can't figure out why it isn't there), while gently informing the user of what is needed to enable it 
-Saves us from having to worry about edge cases such if a user selects the "print" option and then disables ln/lnurl. 

That said, perhaps we could improve the error message by linking to the appropriate settings page. Ex., `To enable this feature, enable LNURL in "Store Settings" -> "Payment Methods" -> "Lightning Settings"` or even a direct link to that page.

Regarding point no. 2, what do you have in mind exactly for adjusting the print view? The main thing that comes to mind for me is to remove the "Open in wallet" button.

One last thing - if the "adjusted" print view is really the true "print view" (i.e. designed solely to be printed), maybe we should rename the current view?

**Comment by pavlenex** [comment]
I think this page should be all about allowing user to easily print the data, that's what I meant by adjusting, having a print button or something to emhpesize this feature can be used offline. Open in a wallet feature is not really ideal for this usecase, but I assume Kukk's left it there for people who may want to use it online, but I still think we should focus on having the `print view` for an offline use and develop it in that direction.

**Comment by pavlenex** [comment]
@satwo does #3050 close this isssue or is there something more we can address? If this is done, let's close it.
