### ISSUE TITLE
Opacity when using the JavaScript Modal switches to 0% (white background), when switching the payment method

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#3032]
**Describe the bug**
When a user creates an invoice on my page, the invoice gets opened within the JavaScript Modal. However once the user changes the payment method (i.e. from bitcoin to btc lightning), the see through effect showing my own page in the background stops working. This behaviour was introduced with 1.3.0.0

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to my [checkout page](https://www.we-love-btc.com/?email=markus@petzsch.eu) which uses the modal.
2. select any package you want and click Pay
3. On the opening BTCPayServer invoice, select another payment method
4. and boom: no see through background

**Expected behavior**

opacity staying the way it is even after changing the payment method.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.3.0.0 (altcoins)
- Deployment Method:        Docker
- Browser:                  Chrome

**Comment by pavlenex** [comment]
Fixed in 1.3.1
