### ISSUE TITLE
Edit item in PoS only shows "Fixed" price type selected

### ISSUE THREAD

**Issue by satwo** [btcpayserver/btcpayserver#3049]
**Describe the bug**
After loading the Update PoS Settings page and selecting an item to edit, it will always show the price type selected as `Fixed` regardless of what the actual price type is.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to Update Point of Sale
2. Edit an item -> change the price type to `Minimum` or `Custom`
3. Save the item, then save settings
4. Go back to edit the same item. It will again show `Fixed` as the price type (although it is the correct price type in the raw editor)

**Expected behavior**

The selected price type should be the same one you selected previously.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.3.1.0
- Deployment Method:   Docker/development
- Browser:  Brave

**Additional context**

This seems to be only a front-end issue, as the database reflects the change and everything else works correctly.

**Comment by fabu21** [comment]
I could reproduce and fix this bug. Will create a PR.

**Comment by fabu21** [comment]
Created PR #3052
