### ISSUE TITLE
Lightning address pay fails if millisatoshi is not 0 mod 1000

### ISSUE THREAD

**Issue by laanwj** [btcpayserver/btcpayserver#3056]
I've noticed this with btcpay.coincharge.io, I think this is a general issue in the new lnurlp implementation (but feel free to close if not). If the number of msatoshi is not round % 1000, it shows a fairly non-descript error:
```
$ curl "https://btcpay.coincharge.io/.well-known/lnurlp/<user>"
{"callback":"https://btcpay.coincharge.io/BTC/LNURL/pay/i/…", …
$ curl 'https://btcpay.coincharge.io/BTC/LNURL/pay/i/…?amount=123123&comment='
{"status":"ERROR","reason":"Lightning node could not generate invoice with description hash"}
```

**Comment by pavlenex** [comment]
Thanks for reporting it @laanwj. 

cc @Kukks this could be related to problems people had (BTCPay Jungle/CoinCards)?

**Comment by NicolasDorier** [comment]
no it's not, found out the problem for them

**Comment by NicolasDorier** [comment]
So I tried in dev environment, I couldn't reproduce (on LND), maybe that's a bug on c-lightning, will try.

**Comment by NicolasDorier** [comment]
I could reproduce on LND

**Comment by NicolasDorier** [comment]
Old version of LND (2 years old) didn't support at API level sub satoshi invoices. Our library kept using the old field of the old API.

This fix at our library level
https://github.com/btcpayserver/BTCPayServer.Lightning/commit/f66aa0ef8083e309625271c131b4f3cd8db674ce

I will release new version tonight with this bug fix.
