### ISSUE TITLE
lnurl-pay returns error 400 for both Phoenix and Breez

### ISSUE THREAD

**Issue by Kixunil** [btcpayserver/btcpayserver#3057]
**Describe the bug**
When testing LNURL-pay with the same instance as in #3054 it returns error code 400.
While it is likely it's related to the problem there, if that is the case, the error code should be 5xy not 400 because it's a server problem.
It is possible that it's unrelated, so I suggest to resolve #3054 first to find out.
There are also no relevant logs after it fails.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Setup LNURL-pay with comment allowed (other settings are default)
2. Create an invoice
3. Try to pay the invoice from Breez/Phoenix, enter `Hello world` into comment

**Expected behavior**

Either the transaction succeeds or, if there's actually a problem with LN implementation, error 5xy is returned. 500 seems to be the most reasonable. The details of the problem are logged.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.3.1
- Deployment Method:        Debian package
- Browser:                  irrelevant (not a browser)

**Logs (if applicable)**

None/missing

**Setup Parameters**

LN node: Eclair
Store Lightning settings:
Enable LNURL: true
LNURL Classic Mode: true
LNURL enabled for standard invoices: true
Do not offer BOLT11 for standard invoices: false
Allow payee to pass a comment: true

**Comment by NicolasDorier** [comment]
can you try again on 1.3.3?

**Comment by Kixunil** [comment]
Same error 400. Also tried without comment - also E400.

**Comment by pavlenex** [comment]
Cannot replicate this so it's possibility related to you using Eclair.

Is this still the issue for you?

**Comment by Kixunil** [comment]
Don't have much time lately but will try to check in upcoming days.

**Comment by NicolasDorier** [comment]
There was a bug, possibly it was there on 1.3.1, where you could have problem with ln address on the altcoins version of btcpay.

If that's the problem, it is already solved by now. (1.3.7)

**Comment by Kixunil** [comment]
Sorry for it taking such a long time. I do NOT have shitcoins enabled, nevertheless I tested with 1.3.7 and still same error. Unfortunately I can't upgrade to 1.4.* because of build issue. Looks like Microsoft messed up something in their official dotnet packages. Going to investigate.
