### ISSUE TITLE
Improve the error message on invoice creation

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3059]
**Describe the bug**
In #2978 we improved the error message, however our UI improvements have now obscured this error message and may lead into confusion on what's really wrong.  Leading to confusions like #3054

The suggested steps are that we combine what we had but also add back in some of the indicators we had in the earlier version, making sure we spit out a proper warning that's contextual.

@NicolasDorier can potentially expand on this as he'd like to address this.

**Comment by satwo** [comment]
I have to take some blame for this by bringing up the original cryptic error issue in the first place. 

I agree with what @NicolasDorier said [here](https://github.com/btcpayserver/btcpayserver/pull/2978#issuecomment-947460305), basically that a cryptic error message that presents usable information is better than a non-cryptic one that doesn't.

In #2978 the cryptic messages were moved to the logs and in #3054 a further check of the logs did yield more actionable information, so at a minimum (if nothing else) the current error message on invoice creation should say something like "Please see logs for more details".
