### ISSUE TITLE
Improve Invoice Product Information

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#306]
Right now, Invoice >**Product Information** section is pretty useless. It displays the total fiat value.
![screen shot 2018-09-30 at 10 24 44](https://user-images.githubusercontent.com/36959754/46255301-9eeb5d00-c49b-11e8-907b-6bb136a6614a.png)

Is there a way we can add actual product information
1. Product 1 - Price in Bitcoin / Fiat
2. Product 2 - Price in Bitcoin/ Fiat

It only provides aggregate fiat value currently. Separating here by product and price in BTC paid would make this more like an actual invoice and could be useful for refunds, especially for merchants who want to refund according to the rate at a specific time and for specific product.

**Comment by ndeet** [comment]
From the BitPay API side the item is only a single value. One of the reasons why the BitPay API is called "messy" or "pita". They did not think through it or did it halfassed, dunno.

For compatibility reasons it is like this for now. But I guess when we split from BitPay API and go our own path this would make sense. On the other hand afair @Kukks  and others wanted to keep it simple and leave it completely out. 

I'm not sure tbh, if we see BTCPay only as payment processor that might be fine. If we see it really as invoice which can be used by customers we need those multiple line items support and some more like
- Export invoice as PDF / print
- possiblity to add merchant info
- VAT-ID etc. 

I doubt this will be priority for now but I think a fully fledged invoicing system would be nice to have 👍

**Comment by bitcoinshirt** [comment]
Whoever needs a more complex invoice possibly has everything in the e-commerce system. But the information for price per item paid in BTC is not available anywhere. It's very important for me, because of the refunds, etc. As you stated, I don't think it's easily doable.

**Comment by bitcoinshirt** [comment]
I'm getting senile. Duplicate of #100
