### ISSUE TITLE
[Translation] Add chinese

### ISSUE THREAD

**Issue by BobleChinois** [btcpayserver/btcpayserver#307]
Hi, I noticed that there is no chinese translation for the moment. I can't find the process for submitting new translation, so I thought I might just open an issue here.

The way I see it, it should be better to have both simplified and traditional characters to be usable both by people from PRC and HK, Taïwan, Singapour etc. Should I make two separate PR or only one ? 

I think I'll have a look at the way the recent arabic translation was done to know what file to modify, except if you have better suggestion.

**Comment by britttttk** [comment]
Hey Sosthene this question was asked in the Slack and recently answered by Smarkus. You need to modify these 3 files: #1) ~/wwwroot/checkout/js/langs #2) ~/Views/Invoice/Checkout.cshtml #3) ~/Services/LanguageService.cs

**Comment by BobleChinois** [comment]
Thanks, I'll do that then

**Comment by britttttk** [comment]
That is to translate the checkout page. I'm not sure if that's what you are asking.

**Comment by BobleChinois** [comment]
I was thinking about the checkout page indeed. Maybe the rest of the interface another time !

**Comment by britttttk** [comment]
Also I'm working with some translators right now to translate into: Chinese, Russian, Kazakh, Italian, Bosnian and I have already received a finished Nepal, I just need to update the files today. I believe my friend is doing simplified Chinese. I can check and get back to you. I have a friend who can do Hebrew but I don't really want to mess with the rtl problems that Kemoantemo is having with arabic...

**Comment by BobleChinois** [comment]
If your friend already did simplified chinese, turning it into traditionnal chinese is trivial. Please let me know so that we don't do redundant work :)

**Comment by britttttk** [comment]
Ok sounds good. He should be finished within two weeks. If you can help me review it that would be great too. I'll keep you updated.

**Comment by BobleChinois** [comment]
Ok let's do that. Ping me when he is done and I'll have a look. 

I'm closing this issue for the moment.

**Comment by NicolasDorier** [comment]
You can keep it open I think

**Comment by BobleChinois** [comment]
PR for simplified chinese [#326](https://github.com/btcpayserver/btcpayserver/pull/326)

**Comment by BobleChinois** [comment]
I keep it open for now, I still intend to do the traditionnal chinese version when I have the time.

**Comment by Kukks** [comment]
Since we have transifex, we can track that there @bitcoinshirt  close?

**Comment by BobleChinois** [comment]
I already joined the Transifex team for traditional chinese, so I guess we can close this (but it's the boss decision of course). 
Sorry guys it's been kinda crazy recently I'll do that when things cool down.

**Comment by NicolasDorier** [comment]
Ok closing now! :)
Looking forward.
