### ISSUE TITLE
Add grouping capabilities for pull payments

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3070]
### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/3066

<div type='discussions-op-text'>

<sup>Originally posted by **NicolasDorier** November  4, 2021</sup>
![image](https://user-images.githubusercontent.com/3020646/140291714-59f71d32-e6c5-48ac-b3e8-0ddf60b24fb6.png)
</div>

**Comment by bolatovumar** [comment]
I'm on it.
