### ISSUE TITLE
Prevent the creation of below dust limit on-chain payment method for small amount invoices

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#3071]
**Describe the bug**
Currently a user can create an invoice for a small amount i.e. 0.10 EUR and get back a qr code for an onchain payment that is below bitcoin's dust limit. Thus no customer could actually pay such an invoice from there wallet.

Imho it would be better to skip the creation of btc-onchain payment method in such cases, so that the invoice view moves on the lightning payment option (if it is available) instantly.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. create invoice with amout 0.10 EUR
2. try to pay it with your wallet (spoiler: it won't let you)

**Expected behavior**

As described above: I wouldn't allow onchain payment method creation in such cases.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    v1.3.2.0 (altcoins)
- Deployment Method:        Docker
- Browser:                  Chrome

**Comment by NicolasDorier** [comment]
We should just hardcode the limit to 600 satoshi. Bitcoin core and NBX doesn't carry this information.
Best place is in `BitcoinLikePaymentHandler.CreatePaymentMethodDetails`

**Comment by satwo** [comment]
I can take this one @pavlenex

**Comment by pavlenex** [comment]
Do we want to give a proper error when such invoice is created as well?

**Comment by satwo** [comment]
That would be a good idea. Perhaps we can integrate this into the payment methods criteria flow?

**Comment by NicolasDorier** [comment]
no, this is really a hard limit, shouldn't be configurable.

**Comment by satwo** [comment]
Right, I mean that we can set the minimum BTC On-Chain amount to be the dust limit, or prevent users from setting a lower limit.

**Comment by NicolasDorier** [comment]
not really, because the limit is denominated in currency, while the dust limit is always satoshi.

**Comment by satwo** [comment]
Good point. I guess we could check the conversion rate but that's a constantly moving target.

The real-world problem that this brought up for me is, how do we best prevent a small shop in El Salvador from creating on-chain invoices for low-priced items that really should only be off-chain? It will be a bad experience for that shopkeeper if his customers can't pay or are paying more in fees than the cost of the item itself.

I understand this is already getting beyond the scope of this issue, but something worth considering as adoption spreads.

**Comment by NicolasDorier** [comment]
> It will be a bad experience for that shopkeeper if his customers can't pay or are paying more in fees than the cost of the item itself

That's why we have the payment method criteria.
But the dust limit is different, it is a limit at the protocol level that doesn't move. If you send a transaction below this amount, the network will just reject it.

**Comment by petzsch** [comment]
Are you shure that Bitcoind doesn't expose the dust limit? For some reason SBW (electrum based as far as I know) knew it couldn't send the transaction and greyed out the OK button when I tried to. That information must have come from somewhere or did they perhaps also use a fixed limit? If this limit changes depending on network load/feeschedule etc. it would be good to have it dynamically adjusted in btcpay as well imho.

I'm all for micro payments and also preventing customers from overpaying on fees. But that is up to the merchant to configure by the min/max amounts for on-chain vs. lightning payments as it's already possible. @satwo

**Comment by satwo** [comment]
>That's why we have the payment method criteria.
Indeed, but why not have it default to some reasonable minimum (i.e. 600 sats) for on-chain, rather than zero? The average non-Bitcoiner just getting started most likely won't know to set that criteria. The merchant (and customer) could learn the hard way, but that's not ideal.

A default minimum of 600 sats is currently ~0.36 USD. There are likely shops in El Salvador that sell items which cost less than that. If Bitcoin continues to rise in value, that likelihood will grow.

**Comment by NicolasDorier** [comment]
@petzsch the dust limit doesn't change with time. What change with time is the relay transaction fee. (Minimum fee in order for your transaction to spread in the network)

**Comment by NicolasDorier** [comment]
So the dust is actually tied to the min relay fee which is fixed by the node policy to default to 1 sat/bytes.

This is not tied to the relay fee which can vary above the min relay fee.

**Comment by NicolasDorier** [comment]
The dust is tied to the dust relay fee which is fixed by default. So I think it's fair we hardcode it. I don't see the dust relay fee exposed by APIs.

**Comment by NicolasDorier** [comment]
@satwo  if you take care of it, it's in `BitcoinLikePaymentHandler.CreatePaymentMethodDetails`.
Update NBitcoin in the project to the latest version, then 
Getting the dust is:

```csharp
var txout = network.NBitcoinNetwork.Consensus.ConsensusFactory.CreateTxOut();
txout.ScriptPubKey = reserved.Address.ScriptPubKey;
var dust = txout.GetDustThreshold();
```
