### ISSUE TITLE
Error when changing coin in invoice

### ISSUE THREAD

**Issue by netzih** [btcpayserver/btcpayserver#3075]
**Describe the bug**
When going to an app and an invoice comes up, The default is BTC but when switching to an altcoin available on the server it freezes up and does not show anything,
This seems to be recent with a recent update (I am currently on 1.3.3) This happens sometimes when switching the second time.

**Screenshots**

![ezgif com-gif-maker](https://user-images.githubusercontent.com/48005023/140634831-585a1a49-7aec-4fec-a2de-82d746f2fd99.gif)
**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.3.3
- Deployment Method:        Docker through azure
- Browser:                  chrome

**Comment by mariodian** [comment]
Do you see any error in the browser's console (cmd+opt+i on mac, or I believe ctrl+alt+i on windows/linux)?

**Comment by netzih** [comment]
I'll look tomorrow, but console was clean of errors until switching the final time and then there was a 404 error on the invoice, have to double check the url that was throwing the error.

**Comment by NicolasDorier** [comment]
can you give us so we can see it? I can't repro now. Seems like a bug I should have fixed in 1.3.1

**Comment by netzih** [comment]
The error logs show the following 
![image](https://user-images.githubusercontent.com/48005023/140653222-dcdc37b2-cbfa-4e74-b1e5-2e943fbd4869.png)
The URL that is throwing the 404 is "https://example.com/invoice/status?invoiceId=XKDhkEsmxxJevArj5gCVdx&paymentMethodId=undefined&_=1636302045617

**Comment by bolatovumar** [comment]
@netzih The reason it's failing is because `paymentMethodId` parameter is `undefined` for some reason for the altcoin you are selecting. If that happens then the behavior that you are getting will happen.

**Comment by bolatovumar** [comment]
For some reason crypto code for LTC here is not set. No idea why that would be though.

**Comment by mizzking** [comment]
Please I send Btc to your wallet mistakenly without buy coins please check and refund it pls

**Comment by mizzking** [comment]
I send Btc to your wallet without buying gift cards please check and cancel or refund it please I beg you

**Comment by NicolasDorier** [comment]
This bug happen when clicking on the label.
Should have been fixed in 1.3.7.0 on #3169, but I missed to merge #f8e6b51e9d1b1391a64ce95d73868faf0280bec2 before releasing. :(

It is fixed on master.
