### ISSUE TITLE
Checkout UI bug: Strange UI flickering when trying to change coin (maybe in cheat mode only)

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#3076]
Whe the coin selection open, the checkout is flickering left/right.

![2021-11-07 19-33-49](https://user-images.githubusercontent.com/3020646/140641577-03403f88-f924-4b11-9b8f-f93efbe2aad8.gif)

I checked on my mainnet instance, the bug doesn't appear, so I think it is caused by the cheat mode. Ping @dennisreimann

**Comment by dennisreimann** [comment]
This seems to be caused by the scrollbar hiding and showing when the overlay is presented and closed.

**Comment by NicolasDorier** [comment]
@dennisreimann probably a side effect of cheat mode then, since we show some stuff below
