### ISSUE TITLE
Greenfield API: invoice: payment methods return cryptoCode

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#3087]
Currently the results return the paymentMethod string which contains the cryptoCode but you need to extract the cryptoCode if you want to. To be consistent with the store payment methods data it would make sense to also return the cryptoCode here. This is useful e.g. for showing Payment history listed by cryptoCode. 

https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Invoices_GetInvoicePaymentMethods

**Comment by bolatovumar** [comment]
@ndeet PR here: https://github.com/btcpayserver/btcpayserver/pull/3099

**Comment by ndeet** [comment]
Thank you 💚
