### ISSUE TITLE
When target currency in the crowdfunding is BTC, the goal amount is only denominated with up to three decimals and doesn't update

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3097]
**Describe the bug**
As reported on Twitter. When you have `BTC` as a target currency, it's only denominated in two decimals for some reasons, not eight.

This leads into false display of the amount in the crowdfunding app, showing 0.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Create a crowdfunding app
2. Put `BTC` as a target currency
3. Make a payment of `0.00001`
4. See error the 0 balance 

**Expected behavior**
The balance should be correctly updated with correct unumber of decimals.

**Screenshots**

https://user-images.githubusercontent.com/36959754/141652744-d38ddae3-6e72-4f56-811c-a91b2fb865b0.mov

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:     master
- Deployment Method:         regtest
- Browser:                   safari

**Logs (if applicable)**

**Setup Parameters**

**Additional context**

Update it worked for up to three decimals for me.

**Comment by as-schug** [comment]
![image](https://user-images.githubusercontent.com/67750682/141814603-0d79de5f-8151-4934-8b98-40d613850404.png)

Also perkle totals do not display correctly

**Comment by pavlenex** [comment]
@as-schug what is the version of btcpay where you're testing this?
