### ISSUE TITLE
bug with fraction amount display in crowdfund app

### ISSUE THREAD

**Issue by as-schug** [btcpayserver/btcpayserver#3109]
Related to https://github.com/btcpayserver/btcpayserver/issues/3097

In version v1.3.5, perk does not show BTC total correctly

![image](https://user-images.githubusercontent.com/67750682/141815532-99e1688b-9098-4584-9a34-c80a4e45f179.png)

**Comment by pavlenex** [comment]
@bolatovumar this seems similar to the one you've tackled recently so perhaps it can be something good to squash?  🐛 🔫

**Comment by bolatovumar** [comment]
@pavlenex lol, yeah, that's the one place I missed to fix.
