### ISSUE TITLE
IsTaprootActivated build error

### ISSUE THREAD

**Issue by denuoweb** [btcpayserver/btcpayserver#3113]
Upon building via 
$ dotnet build -c Altcoins-Release BTCPayServer/BTCPayServer.csproj
I get a build failed due to 'WalletSetupViewModel' does not contain a definition for IsTaprootActivated.

I expect the build to complete with default option being No, Taproot is Not Activated.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: git clone as of 11/16/21
- Deployment Method:   manual
- Browser:    n/a

**Logs**
  BTCPayServer.Data -> /home/USER/btcpayserver/BTCPayServer.Data/bin/Altcoins-Release/netcoreapp3.1/BTCPayServer.Data.dll
  
  Bundler: Begin processing bundleconfig.json
  Bundler: Done processing bundleconfig.json
Views/Stores/ImportWallet/Seed.cshtml(24,35): error CS1061: 'WalletSetupViewModel' does not contain a definition for 'IsTaprootActivated' and no accessible extension method 'IsTaprootActivated' accepting a first argument of type 'WalletSetupViewModel' could be found (are you missing a using directive or an assembly reference?) [/home/USER/btcpayserver/BTCPayServer/BTCPayServer.csproj]
Views/Stores/ImportWallet/Seed.cshtml(24,62): error CS1061: 'WalletSetupViewModel' does not contain a definition for 'IsTaprootActivated' and no accessible extension method 'IsTaprootActivated' accepting a first argument of type 'WalletSetupViewModel' could be found (are you missing a using directive or an assembly reference?) [/home/USER/btcpayserver/BTCPayServer/BTCPayServer.csproj]
Views/Stores/ImportWallet/Xpub.cshtml(89,40): error CS1061: 'WalletSetupViewModel' does not contain a definition for 'IsTaprootActivated' and no accessible extension method 'IsTaprootActivated' accepting a first argument of type 'WalletSetupViewModel' could be found (are you missing a using directive or an assembly reference?) [/home/USER/btcpayserver/BTCPayServer/BTCPayServer.csproj]

**Comment by denuoweb** [comment]
I was able to checkout 1.3.5, upon building that I got a MSBuild Error: ContextID 72 should have been in the ID-to-project file mapping but wasn't!

I fixed this by setting an environment variable $ export MSBUILDDISABLENODEREUSE=1

**Comment by dennisreimann** [comment]
Fixed with #3119
