### ISSUE TITLE
Mynode showing an error in BTCpay server application

### ISSUE THREAD

**Issue by Trabbtc** [btcpayserver/btcpayserver#3124]
Hi there,
Noob here, completely ignorant about all this stuff, but running my bitcoin node and want to connect to my e/commerce website.

I am using Mynode v 0.2.45
I installed the latest version 1.2.4 of BTCPay Server a couple of days ago and am getting an error and a red dot.
When I try to restart the application, there is a message saying there is an error restarting>
![image](https://user-images.githubusercontent.com/94610502/142402713-238c2817-eb8b-418b-911a-b547a843f5c4.png)

I tried Reinstalling the app and also didn't work.

These are the logs>
Logs begin at Thu 2021-11-18 05:00:21 CST, end at Thu 2021-11-18 05:05:39 CST. --
Nov 18 05:01:55 myNode systemd[1]: btcpayserver.service: Job btcpayserver.service/start failed with result 'dependency'.
Nov 18 05:01:55 myNode systemd[1]: Dependency failed for BTCPayServer service.

Other applications that are showing error are Dojo and Docker, but not sure if it matters.

I have asked Mynode support and they suggested to come here to look for the issue, couldn't find it so submitting a new one.
Hope someone can help

thanks

**Comment by pavlenex** [comment]
I am not sure why MyNode passes their responsibility to us. We have no idea how they're deploying BTCPay as they're using a non-standard deployment method. Please contact them, this isn't really our issue.
