### ISSUE TITLE
Payment Requests

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#314]
I regularly pay freelancers with Bitcoin. The problem is that once we agree on the amount, due to volatility, the amount changes, so sometimes I have to pay again, or they have to refund, etc. It's a pain. Especially if we agree on the amount a few days before the payment. Someone is always at a loss.

I've seen that Blokonomics[ launched a very nice tool.](https://www.blockonomics.co/invoicecreate/) From what I see it's an invoice which creates a countdown every time you open of the link with dynamic amounts refreshing.

![screen shot 2018-10-05 at 09 50 28](https://user-images.githubusercontent.com/36959754/46522899-632e0a00-c884-11e8-8511-5794bc750fb1.png)

I think we can do this easily to make BTCPay useful for freelancers. @Kukks and I discussed it a while ago, but we forgot about it, so I'm opening an issue for future reference and discussion.

**Comment by NicolasDorier** [comment]
Why not just doing a payment button?

**Comment by Kukks** [comment]
Ok so these are long-lived invoices where the invoice data in itself cannot be fully immutable, particularly the rates. There is a discussion over on the #asps channel in slack on how we could extend the invoice system and be more scalable on it( look for `InvoiceType` in that channel)

**Comment by Kukks** [comment]
@NicolasDorier  it's particularly useful because he wants to issue an invoice that can be agreed upon from btcpay and then paid upon completion.

**Comment by NicolasDorier** [comment]
I don't understand. Why the button does not work ? you specify the amount in fiat, and when the guy wants to pay, he just click on it and has the latest rate.

**Comment by NicolasDorier** [comment]
or even custom input in POS app

**Comment by NicolasDorier** [comment]
or a POS app with only one button

**Comment by bitcoinshirt** [comment]
@NicolasDorier The freelancer can easier share the invoice via email, chat ,etc than payment button which needs to be input via html.

**Comment by bitcoinshirt** [comment]
@NicolasDorier I like the idea of having an invoice that can be shared via the link. I definetelly see that both customer and freelancer can benefit from this. 

A freelancer can just send a link via the email, and the customer can click and checkout. 

The concept is to allow freelancer to create permanent invoices manually, the invoice time and add the fixed amount and that invoice will be created with will change dynamically. I think we're on the same page. I would just like if we can think a bit cooler name than Permanent Invoices :-)

**Comment by NicolasDorier** [comment]
> The concept is to allow freelancer to create permanent invoices manually, the invoice time and add the fixed amount and that invoice will be created with will change dynamically

We can't do this without massive work which take month.

The nearest we can do is giving a link which generate an invoice valid for 15 min.

**Comment by bitcoinshirt** [comment]
@NicolasDorier If a user could set the amount per invoice, I think that will be more than enough.

**Comment by NicolasDorier** [comment]
Related https://twitter.com/thechaz/status/1051875479353880577

**Comment by bitcoinshirt** [comment]
For the Patreon, I think it's more of a combination of #313 and maybe #213 or with a pre-paid subscription?

**Comment by hubiktomas** [comment]
I think that enough would be some simple interface, where a merchant/freelancer can just input an amount and optionally item description and this will generate some link. When a buyer visits this link, a new invoice with standard expiration will be generated. Then after repeated visiting of the same link there should be probably two cases - if the invoice is paid or still pending payment, the original invoice should be showed. If the original invoice is expired or not generated yet, a new invoice with new expiration should be generated.

**Comment by bitcoinshirt** [comment]
That's great summary @hubiktomas exactly what I had in mind.

**Comment by Kukks** [comment]
Ok, so this is just a wrapper on top of the current invoice system? 
Couldn't this just be a non-expiring/long-lived invoice?

**Comment by bitcoinshirt** [comment]
Okay, me and @Kukks discussed and though it would be cool idea to add printer-friendly version of that invoice somewhere.

Here's the summary of our convo:

> we can create the ui to look like a traiditional invoice, have a button that opens the payment invoice modal, and a print button that styles the page for a printer friendly version

**Comment by Kukks** [comment]
Can we rename this to "Payment Requests" @bitcoinshirt
