### ISSUE TITLE
[minor improvement] hidden inputs in the pay button html form take space in the page

### ISSUE THREAD

**Issue by BobleChinois** [btcpayserver/btcpayserver#315]
I noticed that the input of type `hidden` in the pay button form, while invisible, still take some space in a page. 

I tested it with Firefox 62.0 and Opera 56.0.3051.36.

This can be annoying when you add more optional inputs and/or try to fit the pay button in a contrived space, for example a page footer in my case, as it add seemingly "blank" space on top of the button.

Only solution I came up with was to add a `<div style="display: none;">` around the hidden lines (excluding the image obviously). For example : 
```
<form action="https://btcpay.sosthene.net/api/v1/invoices" method="POST">
<input style="width: 209px;" alt="Pay with BtcPay, Self-Hosted Bitcoin Payment Processor" name="submit" src="https://btcpay.sosthene.net/img/paybutton/pay.png" type="image" />
<div style="display: none;">
<input name="storeId" type="hidden" value="2kUDmoLQMrwvxansY2YkhSaKoo2Y91skauJjtfVqzDYH" />
<input name="price" type="hidden" value="10" />
<input name="currency" type="hidden" value="USD" />
<input name="email" type="hidden" value="USD" />
<input name="currency" type="hidden" value="USD" />
</div>
</form>
```

I don't know if there is downside to this solution, or a more obvious, simpler way to achieve this result. If not, I'd like to propose a pull request to add this by default when the button's code is generated.

**Comment by Kukks** [comment]
hmm, that is probably some css in your host page that styles input tags irrespective of type

Your fix is good but we can avoid more html tags by adding `style="display: none;"` to each  hidden input

**Comment by BobleChinois** [comment]
I gave it a quick try, doesn't seem to work, at least on my blog.

**Comment by rockstardev** [comment]
@BobleChinois link to page?

**Comment by BobleChinois** [comment]
I made a dummy page on my blog to show what I mean : 

[https://www.sosthene.net/test-pay-button/](https://www.sosthene.net/test-pay-button/)
password : btcpay

Here is the html of this page.
```
Lorem ipsum ...

<form action="https://btcpay.sosthene.net/api/v1/invoices" method="POST"><input name="storeId" type="hidden" value="2kUDmoLQMrwvxansY2YkhSaKoo2Y91skauJjtfVqzDYH" />
<input name="price" type="hidden" value="10" />
<input name="currency" type="hidden" value="USD" />
<input style="width: 209px;" alt="Pay with BtcPay, Self-Hosted Bitcoin Payment Processor" name="submit" src="https://btcpay.sosthene.net/img/paybutton/pay.png" type="image" /></form>

Lorem ipsum ...

<form action="https://btcpay.sosthene.net/api/v1/invoices" method="POST"><input name="storeId" type="hidden" value="2kUDmoLQMrwvxansY2YkhSaKoo2Y91skauJjtfVqzDYH" />
<div style="display: none;"><input name="price" type="hidden" value="10" />
<input name="currency" type="hidden" value="USD" /></div>
<input style="width: 209px;" alt="Pay with BtcPay, Self-Hosted Bitcoin Payment Processor" name="submit" src="https://btcpay.sosthene.net/img/paybutton/pay.png" type="image" />

</form>
```

**Comment by Kukks** [comment]
I see that there are `<br/>` tags generated on your form after each input. You might have a script in your wordpress generating the extra html on input fields in forms..

**Comment by BobleChinois** [comment]
Interesting, I made a quick research and installed [this plugin](https://wordpress.org/plugins/dont-muck-my-markup/), now there are no parasite `<br>` anymore in the page html, and no blank spaces.

The preview in wordpress text editor is still fucked up though, I think I'm gonna unplug this shit.

What do you think then ? Maybe a simple entry in the FAQ could do the trick, in case someone else has the same issue (which is very likely because lot of people use Wordpress).

**Comment by rockstardev** [comment]
That editor is direct culprit... if you are pasting in HTML mode he shouldn't be converting newlines into <br />

We can definitely reference this issue in some FAQ for fellow Wordpress users.

**Comment by BobleChinois** [comment]
Ok I'll make it when I have a sec this week or next maybe

**Comment by rockstardev** [comment]
❤️
