### ISSUE TITLE
Have better generic way to show/hide new features to users.

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#3160]
https://github.com/btcpayserver/btcpayserver/pull/3090#issuecomment-980006588

**Comment by pavlenex** [comment]
A notification or a welcome message in dashboard #1711 but this can only be done in 1.5.0?

Perhaps something to discuss on a design meeting cc @dstrukt @Zaxounette

**Comment by dstrukt** [comment]
Noting this, and will add to the discussion as we continue to refine 1.4.0, might be something we can work into the release, or a follow release.

**Comment by pavlenex** [comment]
Just noticed the waveapp communicates new features through a `What's new` notification button. Posting for inspiration.

![Screenshot 2021-12-22 at 14 48 50](https://user-images.githubusercontent.com/36959754/147102692-5c00b6ef-3411-4936-89e1-0f298cd4debf.png)


![Screenshot 2021-12-22 at 14 47 30](https://user-images.githubusercontent.com/36959754/147102560-38a4e7ce-abea-40f7-bc8e-938e99b47798.png)

**Comment by pavlenex** [comment]
We can potentially add this as a widget to the upcoming dashboard #1711

**Comment by dstrukt** [comment]
Can confirm, this would make sense as a card in the Dashboard view, working into the mocks for the next design call.
