### ISSUE TITLE
WarriorPlus

### ISSUE THREAD

**Issue by RMOORE73** [btcpayserver/btcpayserver#3161]
**Describe the bug**

**To Reproduce the bug**
Steps to reproduce the reported bug:

**Expected behavior**

**Screenshots**

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    
- Deployment Method:        
- Browser:                  

**Logs (if applicable)**

**Setup Parameters**

**Additional context**

**Comment by Pornprasert** [comment]
Hi
