### ISSUE TITLE
Issue with setting up a store

### ISSUE THREAD

**Issue by Myshiro** [btcpayserver/btcpayserver#3178]
Hi there; I understand that “BTCPay Server is a free and open-source Bitcoin payment processor which allows you to accept bitcoin without fees or intermediaries.”

I was wondering how do I go about setting up a store / a single transaction someone is paying me bitcoin and if Bitcoin goes down in price will I lose money?

How would I be able to convert the Bitcoin to GBP; or will this take place in a different app; I hope there are no fees regardless.

Many thanks.

**Comment by bolatovumar** [comment]
@Myshiro BTCPay doesn't offer any functionality for selling for fiat, you have to handle that yourself. There are solutions that help you with this like BtcTransmuter: https://docs.btcpayserver.org/Transmuter/
