### ISSUE TITLE
Ignore 

### ISSUE THREAD

**Issue by ndaxio** [btcpayserver/btcpayserver#319]

**Comment by Kukks** [comment]
Please don't shill unrelated projects on GitHub issues in here

**Comment by ndaxio** [comment]
apologies that were not the intention, we wanted to contribute to this project.

**Comment by rockstardev** [comment]
@Kukks we need to give you space to shill your project when it's ready ;). Closing now... and reminder that all future unrelated discussions are much better initiated on Slack: http://slack.btcpayserver.org/
