### ISSUE TITLE
Bug allowing Spam/Denial of Service, due to gap limits in other wallets (& related feature requests to fix)

### ISSUE THREAD

**Issue by ChristopherA** [btcpayserver/btcpayserver#3190]
We are using the docker version of BTCPay v1.3.6.0 at https://btcpay.blockchaincommons.com.

Original report: https://github.com/btcpayserver/btcpayserver-docker/issues/561

**Describe the bug**

BTCPay does to make it easy to stop spam attacks, resulting in a possible large address gap, breaking spending wallets (in particular, Ledger Live).

Details:

We had a spammer hit our BTCpay server, creating just under 500 invoices in a bit less than an hour. All with the same email address (sample@email.tst), all for either 0 BTC or 1 BTC. I presume they were all from the same IP address, though that's not recorded with the invoices and if it's somewhere else, I don't know where.

It'd be nice to automatically block a spammer like this, after they've generated several invoices within a very short period of time.

Alternatively, it'd be nice to be able to manually block them, perhaps with a "block IP" or "block email" button on an invoice.

It turns out that this many requests for addresses breaks Ledger Live's gap limit, so it does not see a valid UTXO transaction even though I've increased the Gap Limit in their Settings/Experimental there to the max 999.

So this is now not just spam, but a denial-of-service attack.

It this point I know what my xpub path is, but not the specific index that this particular payment's address is on that path (I'm presuming 1000+?) such that I can manually generate the private key spend this UTXO. (I'll also have to start BTCPay up with a new xpub & path.)

Thus a secondary feature request is that BTCPay's "Invoice Details" add the path and index for each of the addresses it created, and maybe support creation of single UTXO PSBT QR/UR to spend it based on the xpub and path (for details on QR/UR, see https://github.com/BlockchainCommons/crypto-commons/blob/master/README.md#urs).

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:   BTCPayServer v1.3.6.0
- Deployment Method:        Docker
- Browser:                 Safari

cc/ @ShannonA

**Comment by pavlenex** [comment]
@NicolasDorier any thoughts on this one?

**Comment by NicolasDorier** [comment]
Invoice creation is typically done via a backend, so we can't filter by IP. (Except in the specific case of the pay button, crowdfund)

As for the request of seeing the path and index of each address created, you can find it in the invoice details already.

![image](https://user-images.githubusercontent.com/3020646/148946904-2b7ca35f-dbb1-4c93-b8d8-92b455c5c633.png)

**Comment by ChristopherA** [comment]
We are being spammed again, with hundreds (maybe thousands) of invoices being created and addresses reserved.

Without a fast fix will have to abandon BTCPay as there is no way to filter by IP or address due to this fix not being prioritized and allowing  DOS attacks.

/cc @ShannonA

**Comment by NicolasDorier** [comment]
what do you ask for exactly? You asked for a way to see the index in invoice, but that is already provided.

**Comment by ChristopherA** [comment]
The real problem is that we can’t block the spammer: 

> It'd be nice to automatically block a spammer like this, after they've generated several invoices within a very short period of time.

> Alternatively, it'd be nice to be able to manually block them, perhaps with a "block IP" or "block email" button on an invoice.

**Comment by NicolasDorier** [comment]
How can I be able to block the spammer? We don't even know his IP on BTCPay side.
What is the problem with having gap of unused addresses?

**Comment by ChristopherA** [comment]
> It'd be nice to automatically block a spammer like this, after they've generated several invoices within a very short period of time.

**Comment by some1ataplace** [comment]
I agree that spamming is a big problem when creating invoices. It would be great if the btcpayserver team can have some sort of built in solution for this. I would make it an optional setting to turn on/off with a custom wait time in seconds/minutes/hours/days to create another invoice depending on the method used to prevent spam. 

@NicolasDorier I do not know exactly what the index is in that image you posted (to me it just looks like a division math problem and is not useful in any way). It seems that the index shows up on an invoice when the customer pays that invoice. The problem we have here with spamming invoice creations is that the user creates an invoice and does not pay, goes back to the website's payment page and creates another invoice without paying and keeps repeating this process over and over. This clogs up the database showing tons of invoices that will eventually become expired. 

Here are a few ideas to combat this. 

Rate limiting, captcha (do not use google for privacy reasons - maybe use hcaptcha instead), storing a key value pair in the cache (redis, memcache, database cache), or storing the recent submitter's username/email in the database with the timestamp of the invoice creation. Each person who creates an invoice will then not be able to create another invoice until the timestamp in the cache or database is less than the current timestamp minus a certain amount of seconds/minutes/hours/days that you are able to set.

**Comment by NicolasDorier** [comment]
> It'd be nice to automatically block a spammer like this, after they've generated several invoices within a very short period of time.

how do we identify the spammer?

**Comment by NicolasDorier** [comment]
@some1ataplace  as I said `HTTP_X_FORWARDED_FOR` will be the address of your backend server, not the address of the spammer.

**Comment by some1ataplace** [comment]
@NicolasDorier Is there any protection for the actual invoice page itself with the Awaiting Payment...  countdown timer containing the Scan/Copy buttons? If so, what is the mechanism? If not, what can we do to protect that page? Maybe we would need to configure our apache/nginx servers we deployed btcpayserver on with rate limit protections - https://www.nginx.com/blog/rate-limiting-nginx/? 

Stripe for example has a rate limit on API requests. This is just an idea maybe you can do something similar. https://stripe.com/docs/rate-limits

**Comment by pavlenex** [comment]
@NicolasDorier what should we do with this one?

**Comment by ChristopherA** [comment]
This is still a problem for us.

**Comment by NicolasDorier** [comment]
Refreshing the checkout page doesn't save any data, so problematic spam doesn't happen there. The problematic spam is when one is creating an invoice, which is your backend. If I was implementing something, all it would do is to kick your backend from contacting btcpay.

**Comment by bolatovumar** [comment]
@ChristopherA can you describe in more detail what happens in your case? Is this spammer creating invoices by automating clicks on products in base BTCPay PoS app or something of the sort?

**Comment by ChristopherA** [comment]
A simple script or a timed JavaScript button pusher is my best guess, given 1000 or so of them. They happened all over the course of an hour. Twice now over a couple months.

**Comment by NicolasDorier** [comment]
This #3782 will fix it for public endpoints. For non-public endpoint, as in your case, there is no solution we can implement even if we wanted. You need to implement the solution on the server calling the greenfield API.

**Comment by ChristopherA** [comment]
I’m confused — my endpoint is public: https://btcpay.BlockchainCommons.com

**Comment by NicolasDorier** [comment]
You should have told me before it was a crowdfund! I thought it was your own server and that you were using the greenfield API to create invoices.

In this case https://github.com/btcpayserver/btcpayserver/pull/3889 will fix it.

**Comment by landabaso** [comment]
I came across this thread while researching BTCPay Server's strategy against spam, Gap limit,... It's a shame that Hashcash, originally designed for purposes like this, has been largely confined to Bitcoin use. Its could have been useful in situations such as this one. I'm sharing this reflection here in hopes of sparking further exploration in the future. Thank you to the team for developing BTCPay Server!
