### ISSUE TITLE
Can not add security device (Safari WebAuthn)

### ISSUE THREAD

**Issue by iBobik** [btcpayserver/btcpayserver#3197]
**Describe the bug**
When I try to add my Trezor as a security device it will fail on this error:

> Could not create credentials in browser. Probably because the username is already registered with your authenticator. Please change username or authenticator.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to /Manage/TwoFactorAuthentication
2. Click on write "Trezor" to Security device name
3. Click Add security device

**Expected behavior**

It will work

**Screenshots**
<img width="970" alt="Snímek obrazovky 2021-12-13 v 1 03 28" src="https://user-images.githubusercontent.com/614232/145735082-13ba879e-8870-4105-b0cf-9a0e2a7e3893.png">

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    v1.3.6.0
- Deployment Method:        Docker
- Browser:                  Safari

**Logs (if applicable)**
Nothing relevant in container logs.

**Comment by Kukks** [comment]
Could you try a different browser? I vaguely remember that safari used to have some issues with FIDO support.

Could you also verify that you are using https?

**Comment by pavlenex** [comment]
I can confirm this is the issue on Safari. Not sure if there's a workaround to it though, so using a different browser or having a backup login (authenticator) can bypass the FIDO.

**Comment by iBobik** [comment]
Hi,
I use U2F with Safari with multiple services (e.g. GitHub), so it could work.

Honza Pobořil

**Comment by Kukks** [comment]
This is using the FIDO2 protocol which is backwards compatible with FIDO1
devices, but the browser must support WebAuthN.

**Comment by iBobik** [comment]
Safari sports WebAuthN:

https://caniuse.com/?search=WebAuthN

Honza Pobořil


> 16. 12. 2021 v 18:24, Andrew Camilleri ***@***.***>:
> 
> WebAuthN

**Comment by pavlenex** [comment]
I can confirm that FIDO2 works on Safari on any other site, so this is something we should look into and address. Seems like a bug.

**Comment by NicolasDorier** [comment]
@pavlenex can you give another try? it may have been related to CSP stuff we may have fixed by now.

**Comment by pavlenex** [comment]
```
[Error] WebSocket connection to 'wss://btcpay762502.lndyn.com/Notifications/SubscribeUpdates' failed: WebSocket is closed due to suspension.
[Error] Failed to load resource: the server responded with a status of 404 () (bootstrap.bundle.min.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (bootstrap.bundle.min.js.map, line 0)
[Error] Could not create credentials in browser. Probably because the username is already registered with your authenticator. Please change username or authenticator. – "exception:NotAllowedError: This request has been cancelled by the user."
    showErrorAlert (helpers.js:75)
    (anonymous function) (register.js:32)
    asyncFunctionResume
    (anonymous function)
    promiseReactionJobWithoutPromise
    promiseReactionJob
[Error] Failed to load resource: the server responded with a status of 404 () (bootstrap.bundle.min.js.map, line 0)
```
![Screenshot 2022-01-11 at 17 01 08](https://user-images.githubusercontent.com/36959754/148977894-ad0ebd58-1ce3-4cbf-9f93-2ab3450a08dd.png)


```
