### ISSUE TITLE
lnurl malformed in printview

### ISSUE THREAD

**Issue by jensgertsen** [btcpayserver/btcpayserver#3199]
The LNURLs generated in print view point-of-sale is unreadable by LN wallets (muun, bluewallet). 
If invoice is created manually, the LNURL QR works as expected.

BTCPayServer v 1.3.4.0 on umbrel

![Screenshot 2021-12-13 at 13 13 08](https://user-images.githubusercontent.com/8363477/145810302-46da7784-8881-42a2-a017-eea1a24980cb.png)

br/
Jens

**Comment by Kukks** [comment]
> The LNURLs generated in print view point-of-sale is unreadable by LN wallets (muun, bluewallet). If invoice is created manually, the LNURL QR works as expected.
> 
> BTCPayServer v 1.3.4.0 on umbrel
> 
> ![Screenshot 2021-12-13 at 13 13 08](https://user-images.githubusercontent.com/8363477/145810302-46da7784-8881-42a2-a017-eea1a24980cb.png)
> 
> br/ Jens

I attempted to replicate the issue and couldn't. This could very well be that you are using Umbrel and that your btcpay is only accessible when on your local network.  LNURL requires your btcpay domain to be publicly accessible (or use tor but then blue wallet/muun must also be using tor).

**Comment by jensgertsen** [comment]
Hmm.. If setting the app to "List" and getting and lnurl qr after clicking "Pay", it renders fine:

![Screenshot 2021-12-15 at 13 58 00](https://user-images.githubusercontent.com/8363477/146190899-92612045-45e9-437c-a870-fe8c858ac4ac.png)

The "print" is in all uppercase while the invoice is in lowercase - they are not identical (seems obvious), but looks largely similar.

**Comment by pavlenex** [comment]
@jensgertsen 

- I tried with Muun (iOS) and obviously it doesn't support LNURL-Pay yet.
- Bluewallet was able to scan both QR's.

v1.3.7.0. You also may want to update just in case. 

Anyway, let us know if the issue still occurs, and I'll re-open it, for now closing as we weren't able to replicate it.
