### ISSUE TITLE
 BTCPayServer v1.0.0.78 - "Manage Settings" menu URL/page not working

### ISSUE THREAD

**Issue by austrocoin** [btcpayserver/btcpayserver#32]
With newest version when logged in (as admin) the URL of menu "Manage Settings" is delivering a 500 error - so wrong URL or page not working.

URL: https://domain.com/Manage/Index

Anyone have same?

**Comment by Eskyee** [comment]
Yes I get the same errors !! My Settings link version 0.78  Also when I build in Visual Studio ! I also see a error my settings, 

An unhandled exception occurred while processing the request.
InvalidOperationException: Unable to resolve service for type 'BTCPayServer.Services.Wallets.BTCPayWallet' while attempting to activate 'BTCPayServer.Controllers.ManageController'.
Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, bool isDefaultParameterRequired)

**Comment by Eskyee** [comment]
BTCPayServer v1.0.0.79 
Updated to
BTCPayServer v1.0.0.80

Manage Settings" menu URL/page Working Ok now 
after Updated to BTCPayServer v1.0.0.80 :)

**Comment by austrocoin** [comment]
Confirm - working again on BTCPayServer v1.0.0.81 :)
Thanks a lot & issue closed.

**Comment by NicolasDorier** [comment]
yay!
