### ISSUE TITLE
Support Tor Browser and non-javascript invoice

### ISSUE THREAD

**Issue by ghost** [btcpayserver/btcpayserver#320]
For all the evil that BitPay has done, they have, to their credit at least have the invoice working without JavaScript. I miss this feature in BtcPay.

Currently, to pay a BtcPay invoice:
- I have to whitelist the scripts in NoScript
- I have to change Tor Browser security level to 'Lowest' (No idea why, but the invoice still refuses to work with security 'High' and scripts whitelisted) 

Please make the Tor Browser a supported target - and bonus points for a NoScript functionality!

**Comment by Kukks** [comment]
I noticed in the code the other day that there is a noscript version of the checkout if you append `/invoice-noscript` to the url. There shoudl also be a failsafe in noscript mode to tell the user to follow that link

**Comment by NicolasDorier** [comment]
I doubt the noscript version works. We probably need to do a second checkout page.

**Comment by pavlenex** [comment]
@NicolasDorier close?

**Comment by NicolasDorier** [comment]
I don't quite understand, Tor Browser works for me.
That said I wished to have a non JS page as well.

**Comment by pavlenex** [comment]
@NicolasDorier This is an old issue requesting Tor + non js invoice page. Since we now support Tor I wanted to know if we should close it or rename it only for non-js page?

**Comment by Kukks** [comment]
Let's split the non js invoice into a new issue and close this one :)
ᐧ

**Comment by NicolasDorier** [comment]
ACK
