### ISSUE TITLE
Delete User modal inconsistency

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#3207]
Good first issue candidate as well.

Current view:
<img width="1792" alt="Screen Shot 2021-12-17 at 1 07 13 AM" src="https://user-images.githubusercontent.com/6250771/146519189-c72ad6a7-2cc1-4904-a7f4-84b1cf0964e8.png">

Expected:
Should look like the other modals.

cc @dennisreimann

**Comment by dennisreimann** [comment]
The delete user case is rather complex and involves backend logic, because there are checks for if this is an admin or even the last admin you are about to delete. That's why I didn't refactor this one.

**Comment by dstrukt** [comment]
Oh right, I remember this being mentioned now.

Will remove the "first issue candidate".

@dennisreimann Do you think this is worth leaving as an issue, so we eventually get to it? Obviously not a high priority at this time.

Can also remove if you think we should keep it this way.

**Comment by dennisreimann** [comment]
I'd leave it as it is.
