### ISSUE TITLE
[UX Improvment] Move Payment Button into the "Apps"

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#321]
I think we should move the Pay button to the “Apps” 

It makes more sense to have the POS and Payment buttons in one place, especially as we possibly expand features in the future ( #313 and #314 )

Also, I've seen people being confused about what are the apps, so we could add concise description since the current one only says "Create and manage apps." I'd rather explain what are the apps what can user though with them possibly with the link to the demo on btcpay main site.

Thoughts?

**Comment by Eskyee** [comment]
I like keeping the PayButton in the store section as it’s a click away from the end user, But have no problems with it being moved to the app section... 
excited to see the new features coming too

**Comment by bitcoinshirt** [comment]
@Eskyee We can also add the links to Apps in store settings,  good point. But I'd like if we could keep all the features in one place and not have them scattered around.

**Comment by Eskyee** [comment]
I agree, just like to keep most things, we have! just one click away for the user!! And not hidden away under multi clicks deep!!

**Comment by rockstardev** [comment]
https://forkbitpay.slack.com/archives/C6PSCRFAM/p1538937924000100?thread_ts=1538903675.000100&cid=C6PSCRFAM

You guys OK if I close this for now?
