### ISSUE TITLE
Payment request doesn't create an invoice

### ISSUE THREAD

**Issue by btceb** [btcpayserver/btcpayserver#3211]
I'm running btcpayserver on a raspiblitz. When creating a payment request I can access to it, but I can't proceed the payment. I get the following error message when pressing the "Pay invoice" button:

<img width="1440" alt="Bildschirmfoto 2021-12-17 um 20 54 23" src="https://user-images.githubusercontent.com/96315050/146601222-d8a29167-c6a4-4681-bd38-14967dd45385.png">

**Comment by pavlenex** [comment]
Have you solved this one? Since Raspiblitz is using different deployment method than our docker, it's best to reach out to them and see what may be blocking it.
