### ISSUE TITLE
Problem with creating a lighting invoice from Greenfield API

### ISSUE THREAD

**Issue by ruahman** [btcpayserver/btcpayserver#3212]
Hello, I am currently having problems generating a lighting invoice using the Greenfield API.  

The API key was generated from a non admin account.  

I gave the following permissions set to the API Key.
![image](https://user-images.githubusercontent.com/360398/146607841-eb9dad2f-abd8-4597-92b3-cd5950838de4.png)

However when I try to call the API endpoint for creating a lighting invoice (http://127.0.0.1:14142/api/v1/stores/{storeId}/lightning/{cryptoCode}/invoices),

I get the following response.

![image](https://user-images.githubusercontent.com/360398/146608002-17d2bf32-6fa8-4e94-b177-66866309ea0c.png)

I was recommended on mattermost to allow internal access in permission for API key.
Internal access to a lighting node is only available to those with admin permission.
However, giving a guest account server access is not a good option for the project I am working on.
I would like to avoid it if possible.

Any advice or help would be appreciated.  

Thank you.

**Comment by NicolasDorier** [comment]
The source of this error was also affecting #3256, and I fixed it on #3275.

Long story short: You need to allow non-admin users to use the internal lightning node (you can find this option in the server's settings policies)

My PR improve the error message.

**Comment by NicolasDorier** [comment]
Reopening. Actually it should have worked I think.

**Comment by NicolasDorier** [comment]
Have you tried `btcpay.store.cancreatelightninginvoice` ?

**Comment by NicolasDorier** [comment]
So now the error is better:

```json
{
    "code": "missing-permission",
    "message": "The user should be admin to use the internal lightning node"
}
```

Shouldn't require it though...
