### ISSUE TITLE
Pay Button Custom/Slider CSP violation.

### ISSUE THREAD

**Issue by dschaper** [btcpayserver/btcpayserver#3241]
**Describe the bug**

Version 1.3.7.0 has a CSP violation when using the custom/slider options for the Pay Button.

`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 2 paybutton.js:169:4`

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to Pay Button
2. Click on Custom amount or Slider
3. No amounts are shown and slider does not change any values.
4. Dev Tools reports above CSP violation.

**Expected behavior**

Pay Button with custom amounts should work.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    v1.3.7.0
- Deployment Method:        Docker
- Browser:                  Firefox, Edge

**Comment by dennisreimann** [comment]
It is the same for switching to "Custom amount", because both options insert HTML with inline event handlers.

@NicolasDorier Do you have an idea on how to best handle this? This is different from the modal script, because the slider and custom amount scripts take user input values, which modifies the inserted scripts.

**Comment by dschaper** [comment]
This is holding up our deployment of btcpayserver, if someone could take a look and see what needs to be fixed it would be appreciated.

**Comment by dstrukt** [comment]
Posted the issue to our Mattermost support, hopefully someone will be able to help you!

**Comment by NicolasDorier** [comment]
yeah will do

**Comment by NicolasDorier** [comment]
This is difficult to solve, as the script `oninput` is constructed dynamically.
I think we need to `data-max` and `data-min` and fetch that so that `oninput` isn't dynamic.

Then the scripts should be in a html template with `csp-allow`.

**Comment by NicolasDorier** [comment]
Actually `csp-allow` may not work, need to add to the `ContentSecurityPolicies.AllowUnsafeHashes`. (Like we did with another script at the top of the `PayButton.cshtml`)

This has the downside to not work on safari, but I don't think there is any other solution.

**Comment by NicolasDorier** [comment]
Btw, both the +/- and the slider have the same issue.

**Comment by dennisreimann** [comment]
@NicolasDorier yes, the idea with the data attributes is quite good, I'll explore if we can solve it that way!
