### ISSUE TITLE
Replace Square Crypto with spiral

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3253]
Square crypto, our supporter [is now Spiral. ](https://spiral.xyz/blog/we-were-square-crypto-now-were-spiral/)
We need to change the readme and login page to reflect that change.
New url:  https://spiral.xyz
SVG can be downloaded by clicking the logo on their website.

- [ ] Remove old squarecrypto.svg logo
- [ ] Add new spiral.svg logo
- [ ] Add it to the readme
- [ ] Add it to the login page and btcpaysupporters view

**Comment by franciscode12** [comment]
Puedo estar en tu equipo
