### ISSUE TITLE
Greenfield API: Creating store wallet transaction permission 

### ISSUE THREAD

**Issue by Drabuna** [btcpayserver/btcpayserver#3256]
**Describe the bug**
It's either a documentation typo or a bug . It definitely looks more like a bug, since you need to provide `StoreID` as a path param.

https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreOnChainWallets_CreateOnChainTransaction - the required permissions are specified as `btcpay.store.canmodifystoresettings`. When you actually try to perform this request with those permissions, you will get a `401`. In reality, it only works with `btcpay.server.canmodifyserversettings` or `unrestricted`.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Create an API key with `btcpay.store.canmodifystoresettings` with global/specific store selection.
2. Use the API key to perform the request https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreOnChainWallets_CreateOnChainTransaction
3. Be amazed by 401 error
4. Be sad

**Expected behavior**
Should work with `btcpay.server.canmodifystoresettings`

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:     v1.3.7.0
- Deployment Method:        Docker
- Browser:                 Chrome

**Comment by NicolasDorier** [comment]
So the reason is that non-admin should have the right to use hot wallets on your instance.
You can activate that in the server's settings policy. I will improve the messaging.
