### ISSUE TITLE
Add concise 1-sentence description for features

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3266]
As discussed on UX channel on Mattermost, we have plenty of features that sometimes may not be entirely clear to people who use BTCPay. Adding a concise description of features may help with this.

![Screenshot 2022-01-07 at 12 21 05](https://user-images.githubusercontent.com/36959754/148537372-faff0e4c-aaf0-439b-8ee8-f04630ee420b.png)

_For example, explaining a payment request as a invoice which doesn't have expiration time, always provides current rate when a payer and is good for sharing a link with a clients._

This requires wider discussion, but I think, for starters we can improve the definitions of:
- Payment Request
- Invoice
- Pull Payments
- Payouts

**Comment by dennisreimann** [comment]
Also relevant for #3255.

**Comment by dstrukt** [comment]
Happy to take care of the PR when we have the wording, might take a shot this week while I browse the docs.

cc @Zaxounette

**Comment by bolatovumar** [comment]
This is a great idea!

**Comment by pavlenex** [comment]
I think we can expand the scope of it, for not just the pages mentioned, but also some sub-pages. For example I think `Payments` page in `Store Settings` deserve explanation. For example `Configure your store payment settings that global for all payment methods`. We'll probably need copywriter to help with these.

**Comment by dstrukt** [comment]
@pavlenex Tend to agree it would be helpful to provide more context for the some of the sub-pages that are integral to the functionality and use of btcpay.

I've been thinking about this more as I step through all of these views, and the big question in my mind is not that we should explain the feature, definitely clear we should, but where?

1. For example, even having a 1-2 sentence explanation on the Payment Request / Payout / Pull Payment, etc.. list view would be incredibly obtrusive and become quite a nuisance after a short while if it's always "present".

We could alleviate this by treating the short explanation like an alert (could be styled slightly differently) that can be dismissed once the user has read or feels they understand.

2. Exploring the concept from no.1 further ... we have the (?) asset, which has historically linked directly out to the external documentation. We could leverage this to drop an accordion explaining the feature in a simple way, and providing a link to read more in the docs. More permanent and less obtrusive than no.1. Even further, we could even "expand" it on first-time users, and when they close the section, it's then always accessible.

For example. I used @BenGWeeks' copy, but obviously we could refine this, add more simple line-by-line (second item), etc.. bu this should give an idea of what's possible:
<img width="952" alt="Screen Shot 2022-06-05 at 4 00 39 PM" src="https://user-images.githubusercontent.com/6250771/172074139-fccdc3f1-9b27-4175-bed7-df7e4bc61644.png">
![Uploading Screen Shot 2022-06-05 at 4.02.39 PM.png…]()

3. We also have the "Create" views for some of the features (Pull Payment / Payment Request / Invoice) where the same logic from no. 1 applies .. there are some drawbacks to this approach, but it's also worth considering...

Still thinking on this, but wanted to push it further for more discussion / feedback!

**Comment by pavlenex** [comment]
Concept ack.

**Comment by NicolasDorier** [comment]
concept ack
