### ISSUE TITLE
Cannot batch unarchive invoices

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3270]
When I'm in archived:true search, I'd expect if there was a way to batch unarchive invoices, but there isn't.

We should add an `unarchive` button.

To currently unarchive an invoice you have to go to an individual invoice and click the `unarchive`. It happened that I mass archived 30+ settled invoices while performing my regular cleaning of the expired invoices.

![Screenshot 2022-01-08 at 18 53 40](https://user-images.githubusercontent.com/36959754/148654445-4d10277c-fa2c-4c3d-a0c3-65166138174a.png)

**Comment by dennisreimann** [comment]
Done as part of the invoice list cleanup PR.
