### ISSUE TITLE
BTCPay marked as completed but still not on my account 

### ISSUE THREAD

**Issue by ellesuper** [btcpayserver/btcpayserver#3271]
**Describe the bug**

**To Reproduce the bug**
Steps to reproduce the reported bug:

**Expected behavior**

**Screenshots**

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    
- Deployment Method:        
- Browser:                  

**Logs (if applicable)**

**Setup Parameters**

**Additional context**

**Comment by pavlenex** [comment]
Please contact your merchant. We use github for bug reports only.
