### ISSUE TITLE
Tabbed Navigation Functionality for Tablet & Mobile

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#3277]
Will update this, but creating a ticket for now for tracking, discussion, and the eventual PR.

<img width="1296" alt="Screen Shot 2022-01-06 at 7 23 13 PM" src="https://user-images.githubusercontent.com/6250771/148752465-8155bb9f-7879-4f58-a82c-2b96d53934ca.png">

**Comment by pavlenex** [comment]
First one is good. I asked a few people and vertical scrolling is pretty normal and expected behaviour. Having to click around the menu for any action will make the experiecne very slow.
