### ISSUE TITLE
Errors for Currency pairs on exchanges that used to exist (Ex: Kraken - LTC_CAD)

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#328]
This issue exists when an exchange used to have a currency pair but no longer does, but still has it in their API. 

The example I have is Kraken, LTC_CAD. Kraken used to have LTC_CAD and pinging the API returns a null result. This causes BTC to not display the rates instead of using an alternative calculation. There should probably be some logic that if a rate is broken because it used to exist, it then calculates as other altcoins do. 

Error: 
ERR_RATE_UNAVAILABLE(kraken, LTC_CAD)

**Comment by NicolasDorier** [comment]
mmmh I think it is better that it break than silently change the rate. Changing the way rates are calculated might change the rate from several %.

**Comment by astupidmoose** [comment]
Any idea on how to fix this that might be better? 

I think if the rate is broken (because it doesn't exist) its OK to follow the same logic as if a rate pair does not exchange. 

This instance seems to be an old API that might still exist but serves no data. It prevents us from being able to use Kraken because we have a need for LTC_CAD pairings

**Comment by NicolasDorier** [comment]
I don't understand. If you can't calculate `Kraken(LTC_CAD)`, then just LTC payment will be disabled if you depends on it. You can then switch to another one.

**Comment by astupidmoose** [comment]
Turning on Advanced scripting and adding a rule explicitly for LTC on Kraken fixed this error: 

LTC_CAD = kraken(LTC_BTC) * kraken(BTC_CAD);
