### ISSUE TITLE
Pull payments expiry date configuration/setting

### ISSUE THREAD

**Issue by braydonf** [btcpayserver/btcpayserver#3281]
When attempting a pull payment, as the use case of a refund, using the [ACINQ Phoenix wallet ](https://github.com/ACINQ/phoenix) it will warn/error with a message "The BOLT 11 invoice must have an expiry date of at least 30 days from submission (Provided was only 6)."

Is there a way to configure the expiry time for pull payments? If not I think this would make a good feature.

**Comment by braydonf** [comment]
Please see associated issue https://github.com/ACINQ/phoenix/issues/235

**Comment by NicolasDorier** [comment]
No way to change, it is hardcoded.
ping @Kukks should we change this to 6 days?

**Comment by braydonf** [comment]
From the perspective of a monthly subscription pull payment it would make sense for it to be 30 days, that may have been the intention? For the case of a refund, I think 6 days (roughly a week) is likely enough.

**Comment by Jossec101** [comment]
As commented in my #3332, we suggest that this should be a parameter of the app, either via UI or environment variable ;) 

Cheers
