### ISSUE TITLE
"BTCPay is expecting you to access this website from"

### ISSUE THREAD

**Issue by ketominer** [btcpayserver/btcpayserver#329]
Could you clarify the use case for the "BTCPay is expecting you to access this website from" alert? It doesn't make much sense, and it's really painful to deal with with any kind of load balancer in front of the server. Also it makes it impossible to use custom domain names for multi-tenant installations...

**Comment by bitcoinshirt** [comment]
Well, it's giving you a message that you incorrectly setup up the protocol (ex http).
[See this to fix the issue](https://nbitstack.com/t/btcpay-is-expecting-you-to-access-this-website-from-externalurl-error/87)

**Comment by NicolasDorier** [comment]
@ketominer BTCPay need internally to know what is his "public URL". If it detect you are not accessing BTCPay through the public URL, then some stuff will break, hence the warning.

**Comment by ketominer** [comment]
> Well, it's giving you a message that you setup up the protocol incorrectly (ex http).
> [See this to fix the issue](https://nbitstack.com/t/btcpay-is-expecting-you-to-access-this-website-from-externalurl-error/87)

Actually this is so broken that last time it happened, the URL "requested" by BTCPay was exactly the one used to access it... (including the scheme)

**Comment by ketominer** [comment]
> @ketominer BTCPay need internally to know what is his "public URL". If it detect you are not accessing BTCPay through the public URL, then some stuff will break, hence the warning.

I think it would be great to remove this dependency... multiple white label instances should quickly become the norm so it should be possible to run one instance with many domains pointing at it. I realise it's probably deep in the code and will not happen fast but I really believe it's something worth doing.

**Comment by ketominer** [comment]
Hi,

After many tests, I'm sure now that whatever the first name is used to call btcpay, it remembers it and cowardly refuses to be called by any other name. If this is really a requirement (which seems weird) if should be per session and not global. This is currently a blocking issue as we are delivering devices that have to be accessible on the local network (through internal IP or .local address) as well as from the Internet with a public domain. We're ready to pay to have it fixed. @Kukks perhaps?

**Comment by NicolasDorier** [comment]
@ketominer is it possible that this problem is at nginx level? Because I am quite certain I don't cache anything.

**Comment by NicolasDorier** [comment]
Closing this I just removed it in `1.0.3.67`. The reverse proxy is however responsible to set `X-Forwarded-Proto` and not rewriting the HTTP `Host`.

**Comment by leblitzdick** [comment]
And now i get an Error like this in version 1.0.3.73:

BTCPay is expecting you to access this website from http://10.8.12.1/. If you use a reverse proxy, please set the X-Forwarded-Proto header to http:

No changes on any config file just rebuild an run the new Version.

**Comment by NicolasDorier** [comment]
@leblitzdick what reverse proxy do you use?

**Comment by NicolasDorier** [comment]
@leblitzdick I just documented the problem

Can you take a look to https://github.com/btcpayserver/btcpayserver-doc/blob/master/FAQ/FAQ-Deployment.md#btcpay-is-expecting-you-to-access-this-website-from

**Comment by fluidvoice** [comment]
I see this also, but I'm not using any proxy that I know of. But my wifi router is connected to my ISP's broadband router (that I don't have admin rights to).  How should I resolve this problem?
