### ISSUE TITLE
Login via code QR should auto-submit when scanned

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3321]
**Describe the bug**
Can we **auto-submit** when a login code is scanned? 

On my phone submit CTA was below the fold and took me a few moments to figure out I actually had to scroll and click submit.

![logincode](https://user-images.githubusercontent.com/36959754/149744369-7be8a865-50d5-4219-b775-0a7ca8fe37eb.jpg)

**To Reproduce the bug**
Steps to reproduce the reported bug:

**Expected behavior**

**Screenshots**

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:  master 
- Deployment Method:     test instance https://btcpay762502.lndyn.com    
- Browser:           safari ios     

**Logs (if applicable)**

**Setup Parameters**

**Additional context**

**Comment by bolatovumar** [comment]
Sounds reasonable to have it auto-submit unless we think it's valuable to have the "Retry" and "Cancel" actions.

![Screenshot_20220117-175116](https://user-images.githubusercontent.com/1934678/149857621-35911dad-970f-46f0-9eec-2fe0ce788254.png)
