### ISSUE TITLE
Remove LNURL-Pay from the checkout page

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3324]
**Describe the bug**
LNURL-pay doesn't really make sense on the checkout page and should only be used for offline pos. Too many options in the checkout are confusing for users.

**To Reproduce the bug**
Steps to reproduce the reported bug:

**Expected behavior**

**Screenshots**

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    
- Deployment Method:        
- Browser:                  

**Logs (if applicable)**

**Setup Parameters**

**Additional context**

**Comment by Kukks** [comment]
NACK, LNURL Pay is the only option that works for topup invoices in conjunction with lightning.

**Comment by pavlenex** [comment]
Good point. Haven't thought about this.

Only activate when amount is `0`? It's just weird to have several "bitcoin" options?

**Comment by Kukks** [comment]
> Good point. Haven't thought about this.
> 
> Only activate when amount is `0`? It's just weird to have several "bitcoin" options?

This is the default behavior afaik

**Comment by pavlenex** [comment]
It's not LNURL is generated with any invoice with the amount, check out pavlenex.com

**Comment by Kukks** [comment]
> > Good point. Haven't thought about this.
> > Only activate when amount is `0`? It's just weird to have several "bitcoin" options?
> 
> This is the default behavior afaik

Checked, it is not. We should change it  then. 

I propose:
* we enable lnurl by default when LN is configured
* NOT enable lnurl when invoice is not a topup invoice as a default
* We make "Only enable the payment method after user explicitly chooses it" on by default

**Comment by pavlenex** [comment]
ACK to all suggestions from above.

**Comment by pavlenex** [comment]
> NACK, LNURL Pay is the only option that works for topup invoices in conjunction with lightning.

Getting back to this, it seems that LNRURL isn't the only option and that amountless invoices have been around for a while. It also seems that whatever security concerns were, they were [addressed](https://twitter.com/roasbeef/status/1414359992426139650?s=21). We'd have to check this, but if correct, then LNURL-Pay can potentially be removed entirely from the checkout itself and be used for an offline PoS, exciting to see people using this feature already.

**Comment by Kukks** [comment]
> > NACK, LNURL Pay is the only option that works for topup invoices in conjunction with lightning.
> 
> Getting back to this, it seems that LNRURL isn't the only option and that amountless invoices have been around for a while. It also seems that whatever security concerns were, they were [addressed](https://twitter.com/roasbeef/status/1414359992426139650?s=21). We'd have to check this, but if correct, then LNURL-Pay can potentially be removed entirely from the checkout itself and be used for an offline PoS, exciting to see people using this feature already.

We would need to ensure that LN implementations have *all* included this alteration. Another drawback is potentially bad UX on wallets which will show a payment screen with "0 sats to pay and confirm"

**Comment by pavlenex** [comment]
After testing plenty of wallets as part of the [Wallet Improvement Project](https://github.com/BitcoinDesign/Guide/issues/493), I don't remember any that doesn't support the amountless invoice, but will have to check. Same compatibility can be made for LNURL.

Do you suggest we create a different issue for this one and try to bring it to attention of c-lightning/eclair devs?

Though, looking at Phoenix, it supports amountless, so I assume eclair does support it already.
