### ISSUE TITLE
[Feature Request] LN invoices to sort by store and settle on-chain

### ISSUE THREAD

**Issue by nwilson1412** [btcpayserver/btcpayserver#333]
Currently BTCPay allows any store to accept LN payments, but each store requires to host their own LN node if they'd like that stores invoices to be received into separate LN wallets. It'd be nice to be able to see each stores individual invoice totals and settle/close on chain to their BTC addresses after they reach x in BTC amount.

**Comment by bitcoinshirt** [comment]
This is a good suggestion, but I am not sure if it's easy to implement.

@NicolasDorier any way we could display LN network and wallet balance in store balance? or is it better to wait for #295 ?

**Comment by bitcoinshirt** [comment]
Cool. so I guess we can close this one and open a larger Accounting issue where we can discuss features.

**Comment by nwilson1412** [comment]
Sounds good 👌
