### ISSUE TITLE
Public Node Info Modal Overlay

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#3338]
Ignore the details of the modal, it's the functionality of an overlay I'm concerned with.

Currently it links out to a new tab, but should just be an overlay ideally.

<img width="1551" alt="Screen Shot 2022-01-20 at 2 10 51 PM" src="https://user-images.githubusercontent.com/6250771/150431061-9689d250-d096-449b-a589-e9daccdf2d01.png">

cc @dennisreimann

**Comment by dennisreimann** [comment]
I'm not sure about this one. To me the public page is more a feature for the outside: a page merchants can link to to offer an easy way of connecting to the store's node or see its online status.

**Comment by dstrukt** [comment]
Ahhh, that's a good point, wasn't thinking about it that way...hmm, never mind, might just clean it up a bit more then.

Will close.
