### ISSUE TITLE
Possible QR code bug

### ISSUE THREAD

**Issue by readmor** [btcpayserver/btcpayserver#334]
I have a Btcpayserver set up on Lunanode. The whole BTC node is synced. I have set up my Zap wallet using the macaroon string. I have checked if my LN node is working on Btcpayserver via stores-settings-modify (Lightning nodes)- test connection. Received the message 'Connection to the lightning node succeeded'.

I opened up a channel between my node and my eclair wallet. Created an invoice request from zap and managed to pay from eclair wallet. Up until here, everything was smooth. However, I have encountered an error which may be QR code related. 

On my BtcPayServer I created a new invoice to be paid out off-chain via the lightning network. When I tried to **SCAN** the invoice through my eclair wallet I received the message; 'This is not a valid payment address. Please use a Mainnet Bitcoin address or Lightning payment request to initiate a payment.'

I can pay the same invoice if I **copy and paste** the invoice into the Eclair wallet instead of scanning. 

It also gives back the correct URI when I scan the node info.

**Comment by rockstardev** [comment]
Thanks for reporting this.

**Comment by rockstardev** [comment]
And also regarding scanning QR Code... once we push this and you update we'll need to test if Eclair doesn't like `lightning:` prefix... and if that is causing problems.

**Comment by readmor** [comment]
Thanks for the response, I will check once it is updated. 

I also attached a screenshot showing both zap wallet and btcpayserver qr codes and request codes. 

Request codes are 100% identical but qr codes differ. Eclair successfully identified the qr code generated with zap but had the same problem with Btcpayserver's qr. 

<img width="553" alt="bps" src="https://user-images.githubusercontent.com/35035900/47043960-a9923b80-d197-11e8-9c36-c8d2c952d695.png">

**Comment by rockstardev** [comment]
@NicolasDorier is there any reason why we are doing `ToUpperInvariant()` on `cryptoInfo.PaymentUrls.BOLT11`? Seems like most wallets would expect that string to be lowercase.

**Comment by NicolasDorier** [comment]
yes @rockstardev , Bech32 is case agnostic and specifically ask upper case inside QR Code because it is making more easily scannable QR Code.

I am myself using eclair on my node, it always worked though.

**Comment by NicolasDorier** [comment]
I tried scanning this with my eclair mobile wallet and it worked

**Comment by NicolasDorier** [comment]
Maybe you have old version of eclair?

**Comment by rockstardev** [comment]
Yeah @NicolasDorier, I've opened channel to @readmor and now scanning invoice - it works. Could be that he has outdated Eclair that doesn't handle `lightning:`.

Merge bugfix regardless... it should problems @bitcoinshirt had.

**Comment by bitcoinshirt** [comment]
@readmor I've also tested and was unable to replicate the issue, everything works for me. It must be that you're using an outdated version of Eclair as Rockstar said. Try with the latest one.

**Comment by rockstardev** [comment]
@readmor I'm closing this now, feel free to re-open if you again run into problems, or ping us on Slack: http://slack.btcpayserver.org/
