### ISSUE TITLE
[UI/UX Proposal] Fixed Header on Apps, Server Settings, Account Settings & Store Settings

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#3344]
Will update as I think of more.

Apps Animated Example (doesn't seem to animate in Safari):
![FixedHeaderFeature](https://user-images.githubusercontent.com/6250771/150664553-9c6adfb7-ec9e-4a97-9e12-73917f857973.gif)

Advantages:
- Puts CTAs up top as opposed to the bottom, helps with long content scroll
- Makes CTAs a little more clear
- Keeps Delete button down at the bottom
- Could be a design pattern we carry over to all views similar to this...

Drawbacks:
- Potential inconsistency in some other views w.r.t CTAs
- On mobile, would this be fixed at the top, or would we resort to dropping it to the bottom?

Considerations:
The content starts at a top offset of 80px with the addition of the heading / spacings, but we may not want the element to be that tall, so we could shorten the height of the header element on scroll, after a certain scroll position, while still keeping the `<div>` at `top: 0px;`. I would have illustrated that in the prototype, but it's not an easy (or even possible) thing to do with Figma. Can discuss this more in-depth on a design call.

Server Settings Animated Example (doesn't seem to animate in Safari):
![FixedHeaderFeatureSS](https://user-images.githubusercontent.com/6250771/150665105-3f608a0b-9268-4187-9289-3c06e0a360f2.gif)

Considerations:
- Would we fix this on mobile? I'd imagine so.
- It does potentially remove the need for the header on mobile, but we could simply hide this...

**Comment by bolatovumar** [comment]
Concept ACK. I like the idea of having CTAs in a consistent spot which doesn't require scrolling. The only concern that I have is that on mobile the fixed header and CTAs would end up taking a lot of space.

**Comment by dstrukt** [comment]
Very valid concern @bolatovumar .. and this implementation does need a little bit more scoping, esp. for mobile, but trying to get the mocks and thinking out in the open asap, so we can keep working through it.

Need to make sure the CTA will be consistent in all views as well, but feel pretty confident about this.
