### ISSUE TITLE
Improve currency dropdown input field using JavaScript

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver#3349]
As suggested in https://github.com/btcpayserver/btcpayserver/pull/3347#issuecomment-1019830274

Created this issue so we don't forget for after the 1.4.0 release. Maybe for 1.5.0 ?

**Comment by dstrukt** [comment]
@woutersamaey Is this a task you want to pick up? Otherwise might be helpful to spec out how this should be improved for whoever picks it up.

**Comment by woutersamaey** [comment]
I think Nicolas already improved it. Not using JavaScript, but I think he found a HTML5 way of doing it (probably datalist).

**Comment by dstrukt** [comment]
Ahh I see, guess I missed that, should we close this issue?
