### ISSUE TITLE
Greenfield API: InvoiceReceivedPayment + InvoicePaymentSettled incomplete data

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#3369]
The [InvoiceReceivedPayment](https://docs.btcpayserver.org/API/Greenfield/v1/#tag/Webhooks/paths/InvoiceReceivedPayment/post) (and also [InvoicePaymentSettled](https://docs.btcpayserver.org/API/Greenfield/v1/#tag/Webhooks/paths/InvoicePaymentSettled/post)) should sent the following payment specific payload according to docs:
```
...
"payment": {
    "paymentMethod": "string",
    "cryptoCode": "string",
    "destination": "string",
    "paymentLink": "string",
    "rate": "string",
    "paymentMethodPaid": "string",
    "totalPaid": "string",
    "due": "string",
    "amount": "string",
    "networkFee": "string",
    "payments": [],
    "activated": true
}
...
```

instead the payment data does not match at all the documentation and important data like `rate`, `amount`(value=?), `due`, `totalPaid` is missing. Also below the `status` invalid seems wrong as it was a valid payment on-chain `BTC-OnChain`. 

```
...
 "payment": {
    "id": "768000d775cd462acdc51fc9d965db045e037b7bfecbf353383fd283f83b2a99-0",
    "receivedDate": 1643299264,
    "value": "0.00018242",
    "fee": "0",
    "status": "Invalid",
    "destination": "mrLG7XVdtn7fVa5Yok8kWqaBNFcirWKhqz"
  },
...
```

same for a `BTC-LightningNetwork` payment:

```
...
"payment": {
    "id": "148c1837eea0f256f024e55cb4707ec24d9374d140340343d4062a88d101d69d",
    "receivedDate": 1643292129,
    "value": "0.00006059",
    "fee": "0.0",
    "status": "Settled",
    "destination": "lntb60590n1psl9fdspp5zjxpsdlw5re9dupyu4wtgur7cfxexax3gq6qxs75qc4g35gp66wsdzq2pskjepqw3hjqcn5vdcxz7thwqszsmr0vdskc2fq9p8hyer9wgsyj3p6yqcnwwpfxqzftcqp2sp5jx03gds3nrl8zj36mzgml0vx00gcgtselnz2me6sfkvuvrmu0tpq9qyyssq272u98a52275p2q5m4fdt44a8x4ang0lz0n2tke7m3z06epsamt4jjzm9v09tpuvtg5xsnypvjvwnzqskmc93pv4l985pg2wavlxxzcp3accxr"
  },
...
```

Minor inconsistency: `fee` is decimal for LN payment but integer for BTC above.

Another one: InvoiceReceivedPayment + InvoicePaymentReceived; why not InvoicePaymentReceived + InvoicePaymentSettled (so both times InvoicePaymentX) 😬 

This was tested with BTCPay 1.3.7 and 1.4.0.

Would be great if all the useful data as written in the API docs are delivered as it would avoid a separate request to the API to get the full payment details.

**Comment by bolatovumar** [comment]
@ndeet the documentation is just wrong. Looks like these additional properties were never there. The docs for these Webhook events are reusing the type definition for the response of `"/api/v1/stores/{storeId}/invoices/{invoiceId}/payment-methods"` endpoint which is obviously incorrect.

**Comment by bolatovumar** [comment]
@ndeet the docs for these webhooks are just wrong. Docs point to `InvoicePaymentMethodDataModel` type for `payment` property while they should point to the `Payment` type which actually corresponds to what's in the code.

See PR here: https://github.com/btcpayserver/btcpayserver/pull/3405
