### ISSUE TITLE
Serialization precision on PullPaymentData BOLT11Expiration

### ISSUE THREAD

**Issue by Jossec101** [btcpayserver/btcpayserver#3370]
**Describe the bug**
It looks that BOLT11Expiration is not being properly serialized into the blob, Newtonsoft.Json is serializing only days of the TimeSpan instead of the format ##:##:## (days.hours:minutes) so if you set for example 1 hour of expiration for the invoices, it will be serialized to 0.

For example with a timespan of 15 minutes it is serialized to 0: 
![devenv_vXWaYFl7we](https://user-images.githubusercontent.com/53834183/151426260-a0f74527-23d3-49fb-894d-96944ba02d5d.png)

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Create a pullpayment with a BOLT11Expiration with less than one day of duration,
2. Check that BOLT11Expiration in https://github.com/btcpayserver/btcpayserver/blob/090da6cfb6ef52423df1003d7a4773fe544dc350/BTCPayServer/Data/Payouts/LightningLike/LightningLikePayoutHandler.cs#L111 is always 0 and useless to validate

**Expected behavior**

TimeSpan should be serialized with more precision, imo up to minutes (days:hours:minutes)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:     1.4.0
- Deployment Method:         Docker
- Browser:                   Chrome

**Comment by bolatovumar** [comment]
> Create a pullpayment with a BOLT11Expiration with less than one day of duration,

How did you manage to do this in BTCPay? AFAIK you can only use integer values for days when creating a Pull Payment in BTCPay so it can't have an expiration date less than one day,

**Comment by Jossec101** [comment]
Oh I have been messing with the code and with the BOLT11Expiration format, I know that from UI you can't put less than 1 day of expiration but nonetheless, I think that the precision is important for future use-cases. imho.

**Comment by pavlenex** [comment]
@Kukks anything we can do about this one, does it make sense to add precision on expiration?
