### ISSUE TITLE
Newly created guest cannot login in  BTCPay Server v1.4.1.0

### ISSUE THREAD

**Issue by lucidddreams** [btcpayserver/btcpayserver#3373]
**Describe the bug**
Newly created guest cannot login in  BTCPay Server v1.4.1.0

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to 'Server -> users > create user. Add the user to store as guest'
2. Login using the newly created user
3. See error
<img width="456" alt="Screen Shot 2022-01-28 at 8 48 42 AM" src="https://user-images.githubusercontent.com/8253590/151467596-ed6cab81-8e21-423e-9f37-5c85dbbac373.png">

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:     BTCPay Server v1.4.1.0
- Deployment Method:       Docker
- Browser:                  Chrome

Other info
 Tested with cleared cache and restarted server.

**Comment by NicolasDorier** [comment]
1.4.2 released
