### ISSUE TITLE
Refactoring "Send from wallet" screen

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#338]
Currently the send from wallet is too tightly coupled with Ledger.

If the ledger is not detected, the fields to make the transaction does not even appear.

Because we want to support PSBT and Trezor in the future, we need to always show all the fields for creating the transaction, and having a "Sign transaction with Ledger Nano S" button.

Later, we would provide `Sign transaction with Trezor` button, `Create PBST` button or `Sign with Mnemonic`.

**Comment by pavlenex** [comment]
We need to prioritize this issue.

**Comment by pavlenex** [comment]
@NicolasDorier PSBT added, Trezor not yet, should we close this one and open a new one for Trezor or?
