### ISSUE TITLE
Conversion with sideshift behave different...

### ISSUE THREAD

**Issue by fiction3** [btcpayserver/btcpayserver#3381]
When trying conversion from ex. XRP to BTC the exact invoice value is not shown correctly in the first try, when restart the conversion it suddenly works correctly.

https://user-images.githubusercontent.com/73464663/151517729-fe646618-1c21-4d0f-9c79-a4f872cd5bf3.mp4

**Comment by Kukks** [comment]
This is an issue with Sideshift not BTCPay. Please message them directly at https://t.me/sideshift
