### ISSUE TITLE
Scan QR codes with "[fingerprint/derivation_path]" prepended to a SLIP-0132 zpub

### ISSUE THREAD

**Issue by kdmukai** [btcpayserver/btcpayserver#3382]
**Describe the bug**
Scanning an xpub QR code from SeedSigner (and possibly/probably other QR-enabled wallets) fails because the xpub is formatted as:

```
[abcd1234/84'/0'/0']zpub....
```

Unclear if it's because of the prepended info or if it's because it's in SLIP-0132 format.

Note that the xpub QR import for Specter Desktop, Blue Wallet, and Sparrow all read this same format.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Import an existing wallet
2. Choose Scan wallet QR code

**Expected behavior**
Successfully parse xpub from QR

**Your BTCPay Environment (please complete the following information):**
n/a

**Logs (if applicable)**

**Setup Parameters**

**Additional context**

**Comment by pavlenex** [comment]
Is this still an issue with 1.5.1 consider the issue is few releases behind?
