### ISSUE TITLE
PSBT Signing from Seedsigner not working. QR/Base64 Paste/File all not working

### ISSUE THREAD

**Issue by newtonick** [btcpayserver/btcpayserver#3383]
**Describe the bug**
When I QR scan, paste, or open a PSBT in a on chain wallet "Transaction Details" screen. It does not appear to work. Nothing in the UI indicates that the PSBT is signed or updated. No option to broadcast is shown.

**To Reproduce the bug**

Screenshots from a main net test wallet I have with little funds. I have removed some sensitive information from screenshots.

Steps to reproduce the reported bug:

Create send (tx)
![image](https://user-images.githubusercontent.com/127377/151622450-1c65ec59-d2a5-494e-b4cb-76cb4a6ce6cb.png)
"Click on Sign Transaction"

Then choose PSBT
![image](https://user-images.githubusercontent.com/127377/151623525-56331391-a96c-4fc5-9f8a-57db0ea2d77b.png)

Download the PSBT file
![image](https://user-images.githubusercontent.com/127377/151623570-57ee39b5-2008-46ac-b91a-4bc746cdc74c.png)

Open PSBT file in Sparrow
![image](https://user-images.githubusercontent.com/127377/151622717-d4d6be74-a061-4bf9-9ef8-710ea1b52458.png)

Signed tx in Sparrow with SeedSigner
![image](https://user-images.githubusercontent.com/127377/151622895-18092c6a-2839-4c5a-b7eb-2f335305c2c4.png)

Saved signed TX as PSBT in sparrow to file
![image](https://user-images.githubusercontent.com/127377/151622931-6b1fc692-38f7-4bd5-9616-33db82daf9dd.png)

Load signed tx into BTCPay under the "Provide updated PSBT" section, and click "Decode PSBT"
![image](https://user-images.githubusercontent.com/127377/151623062-a1029f99-898b-4d02-a98e-d551b3697f9d.png)

Nothing happens, Nothing indicates the PSBT is signed.
![image](https://user-images.githubusercontent.com/127377/151623157-c8a12e8f-ba3f-4ef6-876f-9545e6726277.png)

**Expected behavior**
I would expect the PSBT to be signed. I expect any of the methods (file, paste base64, or QR scan or BCUR format) to decode and update the PSBT with the signatures.

Obviously I could just broadcast from Sparrow. But I included Sparrow Wallet in this example workflow/steps to show the PSBT is valid and signed.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:  v1.4.2.0
- Deployment Method:  docker-compose
- Browser:  Chrome and Safari

**Comment by NicolasDorier** [comment]
@newtonick, can you check if your wallet settings show the wallet fingerprint with the account key path?

**Comment by pavlenex** [comment]
Unsure if this is related to #3417 

Pinging @newtonick check comment above and reply so we can proceed troubleshooting.

**Comment by NicolasDorier** [comment]
It isn't related

**Comment by pavlenex** [comment]
What do we do with this issue then? Is this something we can fix?
