### ISSUE TITLE
Unexpected character encountered while parsing value

### ISSUE THREAD

**Issue by enorrmann** [btcpayserver/btcpayserver#339]
I'm running NBXplorer compiled from master with bitcoind 0.17 both on testnet
they are online and fully synced
When I start btcpayserver with run.sh --testnet

info: Hangfire.BackgroundJobServer:     Schedule polling interval: 00:00:15
info: Configuration:  BTC: Explorer url is http://127.0.0.1:24445/
info: Configuration:  BTC: Cookie file is /home/enorrmann/.nbxplorer/TestNet/.cookie
info: PayServer:      Starting listening NBXplorer (BTC)
info: PayServer:      Start watching invoices
**fail: PayServer:      BTC: NBXplorer error `Unexpected character encountered while parsing value: <. Path '', line 0, position 0.`**

and in the web UI it says 

BTC
The node is offline
Last error: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

**Comment by NicolasDorier** [comment]
do you have a stack trace?

**Comment by enorrmann** [comment]
that was the std output
I can't find any log file, on linux

**Comment by enorrmann** [comment]
after running for a day or so the error disappeared
may be the node was not in full sync yet
