### ISSUE TITLE
Payments Requests shows an error

### ISSUE THREAD

**Issue by peter-rounce** [btcpayserver/btcpayserver#3392]
**Describe the bug**
After updating to v1.4.2.0, the menu item 'Payments > Requests' throws an error.

**To Reproduce the bug**
1. Go to Menu
2. Click on 'Payments > Requests'
3. See error

**Expected behaviour**
A page listing the Payment Requests created so far and a button for 'New Request'.

**Actual behaviour**
An error is shown:
_[{"path":"expiryDate","message":"Unexpected json token type, expected is Integer and actual is Date"}]_

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:  v1.4.2.0
- Deployment Method:  luna node hosting
- Browser:  Chrome

**Comment by bitcoinheiro** [comment]
Yep, I confirm this issue. Same happens to me in a store with several payment requests.
Probably incompatibility with old version. Problem is that this blocks access to the complete page and only renders the error message, as bellow:
![image](https://user-images.githubusercontent.com/50273260/151981026-62e568dd-9cdf-4b8f-957d-ee3f28520c65.png)

**Comment by jaonoctus** [comment]
Same here, for stores that have had an open request before

**Comment by NicolasDorier** [comment]
Making new version now

**Comment by NicolasDorier** [comment]
Fixed in 1.4.3

**Comment by peter-rounce** [comment]
confirmed - the fix in v1.4.3.0 works for me
