### ISSUE TITLE
Pay Button request failed Please fix following errors: The Currency field is required.

### ISSUE THREAD

**Issue by valerie16901** [btcpayserver/btcpayserver#3396]
**Issue:**
When creating a payment button the currency field appears not to be passing along.

**Steps to reproduce:**

1. Go to Payments > Pay button
2. Fill out the following details:
- Price 
- Currency 
- Checkout Description 
- Order ID
3. Click on the preview button or the alternative link
<img width="977" alt="Screenshot 2022-01-31 at 15 24 48" src="https://user-images.githubusercontent.com/10710104/151811019-bc7c0e7d-30aa-49c7-8afc-cbeec857ec73.png">

**Comment by dstrukt** [comment]
cc @NicolasDorier @dennisreimann
