### ISSUE TITLE
Vue giving lot's of errors

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#34]
![image](https://user-images.githubusercontent.com/3020646/35035143-c06ca008-fbb3-11e7-9c6e-269f02f76d9e.png)

**Comment by lepipele** [comment]
After reviewing code this has to do with custom HTML5 elements that were used in `Checkout.cshtml`. I've looked through logic and it seems the only reason why those elements were used is to make intent of elements more intuitive... 

There doesn't seem to be specific usage in JavaScript... elements are only targeted with CSS.

Short-term we can use `Vue.config.ignoredElements` explained here: https://vuejs.org/v2/api/#ignoredElements ... long term we can see to replace those elements with regular ones.
