### ISSUE TITLE
LNURL is available when bitcoind is down

### ISSUE THREAD

**Issue by iBobik** [btcpayserver/btcpayserver#3409]
**Describe the bug**
When Bitcoin daemon is down, payment method LNURL is available.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Turn on Lightning wallet and LNURL
2. Stop Bitcoin container
3. Create invoice by POS app
4. See it behaves like LNURL method is available

**Expected behavior**

Invoice page serve some reasonable error.

**Screenshots**
<img width="451" alt="Snímek obrazovky 2022-02-03 v 20 10 50" src="https://user-images.githubusercontent.com/614232/152437793-1eae22d5-f3f2-4c25-8d56-02061f70443b.png">

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    v1.4.3.0
- Deployment Method:       Docker
- Browser:                  Safari

**Comment by Kukks** [comment]
This cannot be solved, and is also an existing scenario for when the lazy payments checkout option is enabled.

The reason behind it is that the lightning/bitcoin node is only needed once the Paynent method activates and not on invoice creation.
