### ISSUE TITLE
Cannot redirect to /stores from frontpage APP

### ISSUE THREAD

**Issue by sargatxet** [btcpayserver/btcpayserver#3412]
I've configured an APP to show as server frontpage with a link to /stores to go into server configuration, but, after login, it shows a 404 error page.

Is there any way to aviod it to change frontpage app?

**Comment by Kukks** [comment]
The `/stores` is no longer there. I would consider redirecting to  `/account` instead?

**Comment by dennisreimann** [comment]
You can simply remove the redirect and you'll be redirected to either your last selected or first store. From there you can use the store selector to switch to an other store or create a new one.

If that doesn't work for you: Can you elaborate on the use case?

**Comment by sargatxet** [comment]
Done, thanks.
