### ISSUE TITLE
Signed PSBT QR from Specter-DIY is not recognized

### ISSUE THREAD

**Issue by silent-link** [btcpayserver/btcpayserver#3417]
When attempting to scan a signed PSBT QR code from Specter-DIY, it is visually marked in the viewport but not recognized:

![Screenshot from 2022-02-03 03-25-23](https://user-images.githubusercontent.com/97920047/152604561-d7795106-9a11-4de9-9214-55039666a93f.png)

**Expected behavior**

QR code recognized, the transaction is finalized and broadcast

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.4.2
- Deployment Method:        Docker
- Browser:                  Chromium on Ubuntu 20.04

**Comment by NicolasDorier** [comment]
Apparently the format used by Specter-DIY changed. We support bc-ur v0, but now it needs bc-ur v1.

The new format is more complicated so we can't easily solve this issue for a while.

**Comment by pavlenex** [comment]
Hey @stepansnigirev and @moritzwietersheim do you guys have a fallback format as per @NicolasDorier comment above?

**Comment by stepansnigirev** [comment]
Specter DIY didn't change QR code format.
We also don't support new version of bcur, only the legacy one.
We also support a simple text format where we split base64 PSBT in chunks and prepend it with `pMofN `.

**Comment by pavlenex** [comment]
@NicolasDorier @Kukks so what exactly is the problem here? ^

**Comment by NicolasDorier** [comment]
He sent on mattermost
```
My Specter-DIY was providing me with UNCOMBINED signed PSBT.
BTCPay just wasn't providing me with any error that the PSBT is incomplete.
Once PSBT is combined and uploaded, the TX sends flawlessly.
Please close the ticket or I'll close the ticket once I restore my access to Github

[3 wk. ago](https://chat.btcpayserver.org/btcpayserver/pl/4fywdzwektgbbe1pdqme4zxbnh)
Maybe the problem with parsing relates to the specific QR code format being required?
```
