### ISSUE TITLE
Filtering for "paid invoices" produces no results

### ISSUE THREAD

**Issue by dergigi** [btcpayserver/btcpayserver#3434]
**Describe the bug**

The `Paid` invoices filter doesn't work anymore. All other invoice filters still work as expected (Invalid, Paid Late, Paid Partial, Paid Over, Unusual, Archived).

This worked in all versions up to 1.3.7 and broke in 1.4.0.

When filtering for "paid", the filter query will change to `status:processing,status:settled` as defined here: https://github.com/btcpayserver/btcpayserver/blob/f3592c4782f160a597f845ae5a023bede846e148/BTCPayServer/Views/UIInvoice/ListInvoices.cshtml#L284

Either this code is wrong or the documentation/explanation is, as per here: https://github.com/btcpayserver/btcpayserver/blob/f3592c4782f160a597f845ae5a023bede846e148/BTCPayServer/Views/UIInvoice/ListInvoices.cshtml#L259

My current workaround is to manually enter `status:complete` which will show all paid (settled) invoices.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to 'invoices'
2. Click on 'Paid invoices', via the drop-down menu on the right side of the search button
3. Observe an empty list

**Expected behavior**

I would expect paid invoices to show up, as they did in previous versions.

**Screenshots**

<img width="395" alt="Screenshot 2022-02-07 at 21 35 37" src="https://user-images.githubusercontent.com/109058/152870241-0c6ec4a4-92d2-47d7-bd02-0c337cec1758.png">

<img width="365" alt="Screenshot 2022-02-07 at 21 52 28" src="https://user-images.githubusercontent.com/109058/152870272-837613a5-1c5f-479b-8bfb-e53c6981df5b.png">

<img width="390" alt="Screenshot 2022-02-07 at 21 52 34" src="https://user-images.githubusercontent.com/109058/152870285-aeed7916-d45e-4e44-b617-4f178f7c33d9.png">

<img width="694" alt="Screenshot 2022-02-07 at 21 52 48" src="https://user-images.githubusercontent.com/109058/152870300-4c54a21b-4a32-431d-b8e8-59608cdc1a83.png">

(I removed the storeId when taking the screenshots above, but it doesn't matter)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:     v1.4.3.0 
- Deployment Method:        Docker
- Browser:                  Firefox

**Comment by pavlenex** [comment]
Thanks for reporting this, we no longer have `paid` status as of 1.4.0. Paid is now called `processing` and we should definitely update our UI to reflect that.

**Comment by dergigi** [comment]
For what it's worth, `status:processing` doesn't produce any results either, so this might be a bug in the model or the logic, not purely in the UI.

![Screenshot from 2022-02-08 14-50-31](https://user-images.githubusercontent.com/109058/153000517-e6a99f3a-d7ed-4bab-8c7d-e5f3981de04c.png)

**Comment by dennisreimann** [comment]
The state shown in the list is the new label and it looks like the filter is still applied based on the old status labels. I can reproduce it and filter the invoices using the old labels:

- `paid` (old) -> `processing` (new)
- `completed` (old) -> `settled` (new)
- `confirmed` (old) -> `settled` (new)

Fixing this now.

**Comment by dennisreimann** [comment]
Fix in #3436, as a workaround `status:paid,status:confirmed,status:complete` can be used.

**Comment by NicolasDorier** [comment]
use `status:paid,status:confirmed,status:complete,status:settled,status:processing` instead.
