### ISSUE TITLE
Greenfield API: LN Endpoints should be GET not POST

### ISSUE THREAD

**Issue by barrydeen** [btcpayserver/btcpayserver#3445]
Two end points to Get deposit address are using the POST method instead of GET:

Doc: https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreLightningNodeApi_GetDepositAddress
Endpoint: https://docs.btcpayserver.org/api/v1/stores/{storeId}/lightning/{cryptoCode}/address

Doc: https://docs.btcpayserver.org/API/Greenfield/v1/#operation/InternalLightningNodeApi_GetDepositAddress
Endpoint: https://docs.btcpayserver.org/api/v1/server/lightning/{cryptoCode}/address

**Comment by dennisreimann** [comment]
I think that's because they "generate" a new receive address for the wallet each time they are used. In that sense it is a manipulating action and GETs are supposed to be non-manipulating.

**Comment by barrydeen** [comment]
Ok that actually makes sense, thanks for clarifying.
