### ISSUE TITLE
Litecoin (LTC) Lightning Network UI page points to BTC lightning-wallet & RTL

### ISSUE THREAD

**Issue by ksdhans** [btcpayserver/btcpayserver#3452]
The Litecoin Lightning Network UI page service links point to the Bitcoin lightning wallet & RTL services instead of Litecoin equivalents. In my case, that's a "C-Lightning (Spark server)," and "Ride the Lightning server." It does have a link to show the Litecoin Lightning server's public info. 

This is probably both a bug and a missing feature. Linking to the bitcoin lightning services is confusing and clearly wrong (i.e., bug). And, there appears to be no built-in wallet or RTL to manage the Litecoin lightning server (i.e., missing feature).

EDIT: Forgot to say, this is with v1.4.3.0 (Altcoins).

**Comment by ksdhans** [comment]
This is a separate issue, but do Litecoin lightning nodes run on the same lightning network as Bitcoin? Or is it a separate network? I can only find info on how to find Bitcoin lightning nodes to connect to.

**Comment by dennisreimann** [comment]
You are correct, those services shouldn't be shown in that case. We need to filter the services [here](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Controllers/UIStoresController.LightningLike.cs#L48) based on the `cryptoCode`.

> Or is it a separate network? 

As they are based on Litecoin, this is a separate network. Not sure if any or what kind of similar services exist to manage Litecoin Lightning nodes.

**Comment by ksdhans** [comment]
Thanks. Should I create a separate enhancement request for adding the spark and RTL servers for Litecoin?

I just discovered that 1ml.com have a Litecoin lighting directory: https://1ml.com/litecoin

**Comment by dennisreimann** [comment]
@ksdhans Yes, that would be a new addition to the Docker Lightning integration ([LND](https://github.com/btcpayserver/btcpayserver-docker/blob/master/docker-compose-generator/docker-fragments/litecoin-lnd.yml), [c-lightning](https://github.com/btcpayserver/btcpayserver-docker/blob/master/docker-compose-generator/docker-fragments/litecoin-clightning.yml)). I'm not whether or not those services (RTL, Spark) support Litecoin.

**Comment by pavlenex** [comment]
Closing since not really related to btcpay and issues already opened to dedicated repositories.
