### ISSUE TITLE
Greenfield API: Apps 

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#3458]
### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/3439

<div type='discussions-op-text'>

<sup>Originally posted by **AndrewIammatteo** February  8, 2022</sup>
Hi,

I have not come across the feature of being able to copy/export/import apps. This would be a very useful features. This has mostly been a headache for testing, but I am also working on a workaround for tips going to a separate Store wallet than the original purchase and this would be very helpful. (I am redirecting the base store app to the employee tipping apps and there needs to be one per employee)

Thanks</div>

**Comment by bolatovumar** [comment]
I can't believe we haven't added support for apps in Greenfield API yet. I created a draft PR which implements basic functionality for adding an app here: https://github.com/btcpayserver/btcpayserver/pull/3511.

Feedback welcome!

**Comment by bolatovumar** [comment]
@dennisreimann basic functionality is done but I will probably be adding more as all you can do at the moment is just create a new app, you can't do anything else.

**Comment by pavlenex** [comment]
@bolatovumar would you like to open a separate issue for that as to-do or update this one so we're aware what's left to implement? Would a separate tracker issue be useful?

**Comment by bolatovumar** [comment]
@pavlenex I can update this one with a list to track progress.

**Comment by bolatovumar** [comment]
List of things to implement below

**Basic stuff**

- [x] Add endpoint for creating a PoS app: https://github.com/btcpayserver/btcpayserver/pull/3511
- [ ] Add endpoint for updating a PoS app
- [ ] Add endpoint for creating a Crowdfund app
- [ ] Add endpoint for updating a Crowdfund app
- [x] Add endpoint for deleting apps: https://github.com/btcpayserver/btcpayserver/pull/3894
- [x] Add endpoint for retrieving an app: https://github.com/btcpayserver/btcpayserver/pull/3894
- [ ] Add endpoint for listing all apps

**Improvements**

- [ ] Return app details for PoS app (not just the basics)
- [ ] Return app details for Crowdfund app (not just the basics)

**Comment by bolatovumar** [comment]
@PatMulligan yes, it will! The PR is ready: https://github.com/btcpayserver/btcpayserver/pull/4102

**Comment by dennisreimann** [comment]
Seems like this is done, @Kukks @bolatovumar ?

**Comment by pavlenex** [comment]
Seems so to me, I think @bolatovumar would know for sure.

**Comment by bolatovumar** [comment]
@dennisreimann @pavlenex yup, all of the features planned originally are now done. There might be more feature we will still want to include but I think we can close this ticket now.
