### ISSUE TITLE
Lightning Network Pop-Up warrning

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#346]
We should add a pop-up warning when the user clicks on the "Save" in the Lightning Network setup.

Something like this:

```
Before you proceed, please understand that Lightning Network is still in the experimental stage. Do not put the money you can't afford to lose. There is a high risk of you losing the money.
 
Take time to familiarize yourself with the risk. There's no backup for LND or c-lightning keys in BTCPay. Your keys are in a hot-wallet. This means :

    If you erase your BTCPay Server virtual machine - you lose all the funds.
   If your server gets hacked - a hacker can take all of your funds by accessing your keys.
```

It's very important to familiarize users with the risks.

**Comment by ketominer** [comment]
Although I agree with the general idea, this is fully correct only for "one click magic deployments". We run BTCPay on fully redundant and replicated servers and the "no backup" part is not related to lightning but to the way it's deployed by some people.

The remaining part, if you erase your LND/clightning server (not BTCPay) and if your server gets hacked, remains correct.

**Comment by bitcoinshirt** [comment]
This is now added in v1.0.3.26, so closing the issue.
