### ISSUE TITLE
Invoice Personal data retention - Erase Personal Data

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#347]
It would be good to give the option where merchants can select to anonymize or delete personal data stored in BTCPay Invoice after a certain period or immediately. 

Erase Refund E-mail Address after X Days

Also, Buyer Information appears to be empty anyway, so why not remove that entirely and leave a refund e-mail?

**Comment by bitcoinshirt** [comment]
Closing this due to lack of interest/activity and probably the fact we need to handle many things before this can be tackled. It's bad privacy practice to keep customers email indefinitely on the server or to keep it at all, specially if using an e-commerce software..

**Comment by elvece** [comment]
I discovered this issue today after I was about to create a this exact feature request. Our team would definitely be interested - specifically the ability to delete / anonymize certain fields of buyer information on an invoice generated from a POS app after X days. We are mainly interested in removing buyer addresses and names. 

What further considerations need to be addressed before this can be tackled?

**Comment by Kukks** [comment]
hey all, thanks to our new plugin system, this was a breeze to finally implement. Let me know how it goes :)

![](https://i.imgur.com/wY53D1b.png)

**Comment by elvece** [comment]
This is amazing, thank you!

Our only request would be to have the option to not delete all fields
