### ISSUE TITLE
Make `Payment Request` list view consistent with `Invoices` by adding mass action (Archive, Clone?)

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3473]
**Describe the bug**
In Design call it's been discussed that we should aim towards consistency when it comes to invoices and payment requets lists.

**Additional context**

![Screenshot 2022-02-17 at 18 20 23](https://user-images.githubusercontent.com/36959754/154535862-4998f632-897e-4fdf-8ab4-02e9ae301b33.png)
![Screenshot 2022-02-17 at 18 20 29](https://user-images.githubusercontent.com/36959754/154535867-aac33917-a9ea-41fd-bd2c-0d12a5b72a73.png)

A follow up from #3471

**Comment by dstrukt** [comment]
I think one of the other things worth discussing in the future is the combination of these views / create / share, and the potential unification of concepts .. as there is significant overlap, it's been brought up before, but I believe there were technical consideration (maybe something i'm not aware of).

**Comment by bolatovumar** [comment]
Looking at these two screenshots side by side I notice a couple of things:

1. "Actions" column on invoices page doesn't really make sense as there are no actions to speak of, just the "Details" link. It feels like that column should not have a header at all or something
2. I kind of appreciate how the "Actions" column for payment requests allows you to do just about anything in one click. If we were to hide them behind a mass action button it would be at least two clicks to perform an action. I wonder if it would make sense to hide them under an action button only on mobile OR keep all of the actions in the same place while adding mass action button

**Comment by dstrukt** [comment]
There's obviously quite a bit here, and if there's love, will break down into the respective tasks and issues, will still likely do this.

Think it makes the most sense and would scale to all of the other views, from the filtering/search at the top to the mass action functionality at the table level.

<img width="699" alt="Screen Shot 2022-06-09 at 11 08 46 PM" src="https://user-images.githubusercontent.com/6250771/173002082-407e9be4-df20-4c0e-b1ba-69c31941b6d2.png">

<img width="1388" alt="Screen Shot 2022-06-09 at 11 08 40 PM" src="https://user-images.githubusercontent.com/6250771/173002068-c0d8df82-f70c-43c9-a9e2-3d2b379456a0.png">

**Comment by dstrukt** [comment]
More on this .. leaning towards the header bar being replaced.

cc @pavlenex @dennisreimann 

![MassActions](https://user-images.githubusercontent.com/6250771/173175241-6878d429-df10-44cb-a65b-9de647f972ba.gif)

**Comment by aboundice** [comment]
Request for widraw funds request to my account on RBC account number is already sent couple days ago
