### ISSUE TITLE
Wrong HTTP status code when called by curl

### ISSUE THREAD

**Issue by iBobik** [btcpayserver/btcpayserver#3482]
**Describe the bug**
When queried by CURL it returns 405 status code which brakes some tools (e.g. monitoring, API clients). When accessing this URLs in Safari I see 200 status codes in devtoools.

**To Reproduce the bug**
Steps to reproduce the reported bug:
```
?1 ~ $ curl -I https://example.com/apps/2N6kWbcqHeCmtHVia3oABEBCymqC/pos
HTTP/2 405 
allow: GET, POST
content-security-policy: script-src 'self' 'unsafe-eval'
date: Sun, 20 Feb 2022 20:00:36 GMT
referrer-policy: same-origin
server: Kestrel
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block

~ $ curl -I https://example.com/                                     
HTTP/2 302 
content-security-policy: script-src 'self' 'unsafe-eval'
date: Sun, 20 Feb 2022 20:04:39 GMT
location: https://example.com/login?ReturnUrl=%2F
referrer-policy: same-origin
server: Kestrel
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block

?1 ~ $ curl -I https://example.com/login              
HTTP/2 405 
allow: GET, POST
content-security-policy: script-src 'self' 'unsafe-eval'
date: Sun, 20 Feb 2022 20:04:50 GMT
referrer-policy: same-origin
server: Kestrel
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block

~ $ curl -I https://example.com/api/v1/health
HTTP/2 405 
allow: GET
content-security-policy: script-src 'self' 'unsafe-eval'
date: Sun, 20 Feb 2022 20:05:04 GMT
referrer-policy: same-origin
server: Kestrel
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block
```

**Expected behavior**

All routes will return semantically correct status codes, so all tools can understand if request was success or failure.

**Screenshots**

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    v1.4.3.0
- Deployment Method:        Docker
- Browser:                  CURL

**Logs (if applicable)**

Nothing interesting in server logs.

**Comment by bolatovumar** [comment]
I tried `curl` both on Windows (version 7.79.1) and macOS (version 7.64.1) against my BTCPay Server instance and it worked as expected for all of the URL examples from above (i.e., I got a 200 status code back).

**Comment by iBobik** [comment]
I've just tried to exec into the container and called BTCPay server directly:
```
root@270561f29207:/app# curl localhost:49392/login -I
HTTP/1.1 405 Method Not Allowed
Date: Tue, 22 Feb 2022 01:30:22 GMT
Server: Kestrel
Allow: GET, POST
Content-Security-Policy: script-src 'self' 'unsafe-eval'
Referrer-Policy: same-origin
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

root@270561f29207:/app# curl localhost:49392/api/v1/health -I
HTTP/1.1 405 Method Not Allowed
Date: Tue, 22 Feb 2022 01:31:23 GMT
Server: Kestrel
Allow: GET
Content-Security-Policy: script-src 'self' 'unsafe-eval'
Referrer-Policy: same-origin
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
```

**Comment by pavlenex** [comment]
@iBobik is this still an issue for you, it's been a while?

**Comment by iBobik** [comment]
It is still hard to monitor, but I understand it is not your priority.Honza Pobořil💬Signal19. 12. 2022 v 12:12, Pavlenex ***@***.***>:﻿
@iBobik is this still an issue for you, it's been a while?

**Comment by dennisreimann** [comment]
@iBobik The `405 Method Not Allowed` error comes from using the `-I` parameter, which makes it a `HEAD` request. You habe to use whatever the API supports, e.g. `GET` for the health endpoint - like `curl localhost:49392/api/v1/health` (without the `-I`).

I'm monitoring my instance that way as well and can confirm it works. Please reopen with more detail if something is still not working or unclear.
