### ISSUE TITLE
"Copy Link" button on pull payment and payment request pages doesn't work

### ISSUE THREAD

**Issue by bolatovumar** [btcpayserver/btcpayserver#3499]
**Describe the bug**

**To Reproduce the bug**

1. Go to any pull payment or payment request page
2. Click on the "Copy Link" button
3. Notice that the link is not copied
4. Notice there is an error in the console

![Capture](https://user-images.githubusercontent.com/1934678/155662842-19293b96-60b8-48e2-95c3-0c9c746451ad.PNG)

**Expected behavior**

Expect link to be copied to the clipboard.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:  1.4.6.0

**Comment by pavlenex** [comment]
Nice catch. Replicate, awesome that you've addressed it already 🧙 🚀
