### ISSUE TITLE
[`Roles`] Error 403 while `issue refund` as `Guest`

### ISSUE THREAD

**Issue by jaonoctus** [btcpayserver/btcpayserver#3512]
**Description:**
Guest users cannot access the refund page anymore.

**Steps to reproduce the reported bug:**
1. Go to any invoice under `/invoices/ID` as a Guest.
2. Click on `Issue Refund`.
3. See `403 - DENIED` page.

![image](https://user-images.githubusercontent.com/7918067/156096953-b242ffa7-54bb-4b8c-891e-291b99fb873e.png)

**Expected behavior:**

Instead of 403 error, a guest user could issue the refund and send the link to the customer in case of a partial paid invoices

![image](https://user-images.githubusercontent.com/7918067/156097043-13f5fa07-f24f-453b-a66e-37cfa6a1efbe.png)

**Environment:**
- BTCPay Server Version: ` v1.4.6.0`
- Deployment Method: Docker
- Browser: Chrome

**Comment by bolatovumar** [comment]
Just tried on `v1.4.6.0` as a guest and I'm able to click on the "Issue refund" button and get the expected page.

**Comment by jaonoctus** [comment]
https://user-images.githubusercontent.com/7918067/156109698-fb550251-4340-4c27-93cc-2a09a9f7f391.mp4

**Comment by dennisreimann** [comment]
I can confirm this exists and I can reproduce it. 

However, I think we need to define how to properly fix it: It's been available to store guests in the past and with the recent store-centric refactorings we restricted it to store owners. Our assumption in changing it was that it should only be available to store owners, as it is possible to drain the funds that way.

Depending on how you look at it and interpret the role of a guest, it can be seen as a limitation now: From what I read it seems like you (@jaonoctus) are using the store guest role for "store managers", which have access to limited features (like refunds) but should not have full access. Correct?

**Comment by jaonoctus** [comment]
Exactly @dennisreimann.

---
Related to this, would be nice to have more pre-defined roles like a "manager" as you mentioned. Or even, a "create role" feature that would work simiraly to the "API Keys" thing. 

_(we can move this to Discussions if it makes sense)_

![image](https://user-images.githubusercontent.com/7918067/156398306-4036558b-c067-4745-9475-778a29b2f5f5.png)

**Comment by dennisreimann** [comment]
Yes, let's keep the issue scoped to fixing it by either

- removing the refund functionality for guests (hide the button, the rest is already ok), or
- allowing access to refunds for guest (update the action policies to allow for that)

Your call, @NicolasDorier :)

Additionally, we should spec out how to allow more finegrained control in a separate discussion, as proposed by @jaonoctus.

**Comment by dennisreimann** [comment]
@jaonoctus Yes, correct. This illustrates how there are different ways to model a flow that might fit, but we aren't really giving a clear direction on how to best achieve things. Thanks you brought this up, we'll need to iterate here.

**Comment by pavlenex** [comment]
So what do we do with this? I was able to reproduce, a store with `guest` permissions can see the refund button but cannot create a refund, it gets 403. @Kukks any ideas on how to approach this? Do we simply disable guest to attempt to issue refunds or should a store guest be able to create a refund, but not authorize it, which I think makes sense.

**Comment by jaonoctus** [comment]
@pavlenex My personal preference would be to keep the functionality to create the a refund as guest, since we have it before.

And you could, as you mentioned, not authorize/finalize it or (what I was doing) use a watch-only wallet

**Comment by Kukks** [comment]
> @pavlenex My personal preference would be to keep the functionality to create the refund as guest, since we have it before.
> 
> And you could, as you mentioned, not authorize/finalize it or (what I was doing) use a watch-only wallet

Thanks for feedback and perspective.

We have the transfer professors feature in progress which will be rolled out in the next release. This feature automatically pays out payouts awaiting payment so your last option will no longer be enough unless you use watch only wallets..

I think  a store guest should be able to create  a refund (pull payment) but not be able to approve payouts for them.

**Comment by pavlenex** [comment]
> I think a store guest should be able to create a refund (pull payment) but not be able to approve payouts for them.

I agree, what's the best way to tackle this? Let's rename this issue and try to do it in 1.6.0 after processors are done in 1.5.0 it can be a good fit I think big merchants would appreciate this as well.

**Comment by pavlenex** [comment]
@kukks said he will add a permisson tag and tackle this one, later on expand it via role manager.

**Comment by jaonoctus** [comment]
@pavlenex @Kukks Great to hear, appreciate it
