### ISSUE TITLE
Updated Integrations View

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#3529]
## Updated:

IMO, we should push the plugins into the plugins sidebar/tabs, and rename this section back to `Integrations` and clean it up like so.

<img width="870" alt="Screen Shot 2022-09-18 at 8 21 55 PM" src="https://user-images.githubusercontent.com/6250771/190944841-e9388fe6-fec0-4159-9d85-1a4586351d6c.png">

## Old:

A simple first pass visual update to the Integrations view.

A lot of time is spent on our integrations by our awesome team, so felt like the page should have that same love put into this view.

Still thinking through the configured view for the "Built in Integrations" (or just Integrations? we probably should make the delineation of the sections better than Integrations and "Other" imo) as we're moving away from the old component we're currently using there, so will likely follow up on these designs, but wanted to get the discussion going. 

Need to do something for Lightning Address, but figured if this gets approval, should be fairly easy to work something in there.

cc @ndeet @dennisreimann @woutersamaey We missing anything?

cc @Zaxounette @pavlenex Could use some refined copy for these :)

<img width="763" alt="Screen Shot 2022-02-26 at 7 58 27 PM" src="https://user-images.githubusercontent.com/6250771/156758018-7c5bc2bd-0ef3-40b9-b4c9-59e3001933f1.png">

**Comment by dennisreimann** [comment]
Nice, @Zaxounette and I discussed in yesterdays meeting that – once the dashboard is done – we should bring more sexyness to the plugins page and "app storify" that one as well. 👍

**Comment by dstrukt** [comment]
Nice, and yes the plug-ins page is definitely getting some love as well .. this one was just easier to start a while back 😄

**Comment by woutersamaey** [comment]
I'd love to see Zapier under a special title "Automation" if possible, because in my book it's about automating your BTCPay and less of a "software package" you're linking as is the case with there other shop systems. 
Another idea might be to mention Zapier on the page where we talk about APIs, as Zapier is a no-code way of automating your install. Same goes for Transmuter.

Come to think of it, we could have multiple titles like "eCommerce Software", "Automation", ... depending on that it does? Just a thought really. I can see this is maybe taking it too far.

**Comment by woutersamaey** [comment]
One nitpick is maybe the large white area in the middle. There's little content left and right and the middle is empty. We could list in 2 columns (if the viewport is wide enough) so it fills the screen better. But like I said: nitpick.

**Comment by dstrukt** [comment]
> Come to think of it, we could have multiple titles like "eCommerce Software", "Automation", ... depending on that it does? Just a thought really. I can see this is maybe taking it too far.

I could definitely see categorizing these, and to your points, it's true that these serve different functions, and providing that categorical context makes it easier to have a short and sweet explanation for how it relates to BTCPay explicitly .. and I imagine in time, there will be more Integrations, like Plug-ins.

> One nitpick is maybe the large white area in the middle. There's little content left and right and the middle is empty. We could list in 2 columns (if the viewport is wide enough) so it fills the screen better. But like I said: nitpick.

Fair, this would be filled with the descriptions ideally, but assuming the descriptions are incredibly short, then we'd likely shorten the width of the rows to accommodate. I also wasn't sure if there was potentially more information we might have wanted in these tables, so I left a bit of space to explore.

**Comment by dstrukt** [comment]
Considering we renamed this section and are shifting to "plugins", some of those decisions happened after this ticket, I'm going to remove this from 1.6.0 so we can reassess what makes the most sense .. there's still some polish work, but the original prompt from this ticket no longer makes sense.

Might ultimately result in closing this ticket and re-opening a new one with a clearer direction.

cc @pavlenex

**Comment by dstrukt** [comment]
No it's a great question.

For context:
https://github.com/btcpayserver/btcpayserver/pull/3712

Currently, AFAIU we have "Plugins", Store "Plugins" and External "Integrations". We just simply renamed this section.

However, in time, if possible, I'd propose that all plugins (regardless of store/server, system/external) consolidated into singular a views and shown simply based on permission & if they're enabled/disabled .. then Integrations cleaned up a bit (like above) and maybe even given their own left sidebar tab.

I imagine this tab will be a little ambiguous until we fully make that transition .. and there might be some context I'm missing as well.

**Comment by ndeet** [comment]
Thanks for the link to the other issue, makes total sense what was discussed already Admin/User and why it is named the same.

**Comment by dstrukt** [comment]
Updated this one with just a cleaned up view of the Integrations.

Ultimately think we should consolidate and move the specific Plugins over to the Plugins view, rename this back to Integrations, and clean up the view with the latest above.

**Comment by pavlenex** [comment]
As discussed, in 1.9.0 we'll be abstracting things from "integrations" which makes that tab dead, so we should probably close this one.
