### ISSUE TITLE
Problem performing service side pairing

### ISSUE THREAD

**Issue by herrvendil** [btcpayserver/btcpayserver#353]
I think there is a problem performing a custom integration following the guide for Server Side Pairing:
https://docs.btcpayserver.org/integrations/customintegration#server-side-pairing

After performing all the steps I get a notification about 'pairing successful' but never the actual token generated. I have tried to get the token using the /tokens REST API but then is always a new token generated that needs pairing.

However if I after perform server side pairing and view the source in access token list page I can find the token in a hidden tag:
<input type="hidden" name="tokenId" value="8zxKrx39TBcQPXgR4R2ih1b1V7YMVxHMT6Njcd2LQpzL">

If I use it in my API it works. 

It seems to me that something is missing in the 'service side pairing' flow. Would it be possible to retrieve the token id in the list?

**Comment by bitcoinshirt** [comment]
@herrvendil  Did you solve this issue?

**Comment by herrvendil** [comment]
Not really, I have mananged to continue integrating, but I still think there is something missing in the 'service side pairing' workflow. The only way I have found to extract the token value is to view the HTML source of the token list page.

I think the either should the token value be displayed (or hidden) or a link to a popup that displays it or something similar. Or maybe there exist another way to get the token value, but I haven't found any in the documentation.

**Comment by NicolasDorier** [comment]
Will add a way to copy paste the token.

**Comment by herrvendil** [comment]
Thank you for your response. 

That sounds great to be able to copy n paste the token.

I have tried for a long time to get the token from the API, but there always seemed  that a new token was generated. I tried all sorts of REST (POST/GET) calls to /tokens according to BitPay API reference but only managed to get client side pairing to work that way.

**Comment by NicolasDorier** [comment]
Fixed in next release
