### ISSUE TITLE
Pay button warning about commercial use is unclear

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3535]
### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/3534

<div type='discussions-op-text'>

<sup>Originally posted by **veebch** March  6, 2022</sup>
Loving your work! One minor point:

The current warning text regarding commercial use of Play Buttons is not clear, in that it does not describe the potential vulnerability with clarity. Perhaps insert a link to a page that gives a little more detail. The [FAQ on pay buttons](https://docs.btcpayserver.org/FAQ/Apps/#what-is-a-payment-button) seems to need updating anyway. 

</div>

**Comment by pavlenex** [comment]
Agreed, it looks super-scary and it's very unclear for people what to do. 
We should:
- Explain the actual vulnerability (spam attack?)
- Using the term `commercial` is confusing

**Comment by pavlenex** [comment]
People don't understand this warrning, it's basically "don't use this feature"

![Screenshot 2022-05-29 at 23 14 43](https://user-images.githubusercontent.com/36959754/170891713-1cb667da-91bc-4abc-89fd-71800b6b4608.png)

**Comment by pavlenex** [comment]
![Screenshot 2022-05-29 at 23 39 07](https://user-images.githubusercontent.com/36959754/170892330-17fc0c06-25a5-44c2-856e-a610c891ab0e.png)

**Comment by NicolasDorier** [comment]
If you have a btcpayserver store plugged to woocommerce for example. An attacker can:

1. Order something of 100$ on woocommerce, get an orderId
2. Use the paybutton to create an invoice of 1$ with the same orderId 
3. Pay the 1$ invoice and enjoy a 99% discount on woocommerce

**Comment by dstrukt** [comment]
Hmmm, yeah that's quite an attack vector .. it's valid to express the very real threat to leaving this enabled on a commercial store.

As we've seen it clearly scares away quite a few people who either:

A) don't understand what that message means, and simply turn it off, render it a useless feature
B) aren't willing to take the risk of that attack vector being leveraged against them, and they shouldn't, as BTCPay becomes more popular, the higher the likely-hood of these types of attacks, so it can't be ignored

If we simply reduce the messaging or make it more "friendly" or hiding some of the risk, we run the risk of putting our users in a compromising situation...and I'm very hesitant to do this.

However, from a UX perspective, having to create an entirely separate store for just the Pay Button seems like a lot .. but if we ultimately don't change anything fundamentally, we may want to push the user to create a store specifically for this as part of / before the enable flow. 

I suppose fundamentally changing the way the Pay Button works, so that it doesn't expose this type of vulnerability is an option, but I wouldn't have much to add on that point, and/or it may not be as feasible as I think.

**Comment by NicolasDorier** [comment]
@dstrukt it is possible to change the way the pay button work, but it would need a different kind of UX.

1. Click on Payment Buttons
2. You arrive on the Payment Buttons list.
3. Click Create new payment button.
4. Customize it like today, and click save.
5. You are back in the Payment Buttons list
6. In the row of the new payment button, you can click on "copy the HTML" to get something ready to copy/paste to your website.

It may be interesting to do it anyway if one day you want some analytics like how many people clicked it, from which utm_media etc...

**Comment by dstrukt** [comment]
Interesting.. multiple Pay Buttons per store instance, and agree those analytics would be a valuable gain. 

But for my own understanding, how would it help mitigate the existing attack vector?

**Comment by NicolasDorier** [comment]
in the HTML, there would only be a pay button id. Nothing that the attacker can modify.

**Comment by laurent1983** [comment]
Thanks for these answers pavlenex, Nicolas, and dstrurt. I am the one who ask this on twitter and telegram.

What about a server-side hash function of the price+orderid+privatekey ? It would make the 1$ payment invalid?

Parameter of the button would be:

orderId, price, securityfield

securityfield = hash(orderId, price, privateKey)

On the call back btcpay btn paiement page you just have to add a simple test:

if(securityfield != hash(orderId, price, privateKey) => Display a error message

**Comment by NicolasDorier** [comment]
where do you store the security field?

**Comment by laurent1983** [comment]
The security field should be an HTML field (public) and calculated server-side in PHP. 

<input type="hidden" name="orderID" value="1234">
<input type="hidden" name="price" value="10">
<input type="hidden" name="currency" value="USD">
<input type="hidden" name="securityfield" value="<?php echo hash("1234-10-".hash("1234-10-".$privateKey)); ?>">

**Comment by NicolasDorier** [comment]
If you have a server able to make this kind of stuff, then you don't need the pay button. Just use BTCPay's greenfield API to generate invoices.

**Comment by NicolasDorier** [comment]
That said, @laurent1983 your solution may still be an improvement, without changing too much the current UX.
I think I will do it. (though using HMAC instead)
I don't see downsides about it.

**Comment by laurent1983** [comment]
Sure I'll do and I will use the greenfield API! I didn't have time to do it yet. Thanks

**Comment by NicolasDorier** [comment]
So we have two ways of fixing the problem:
* Making the payment buttons stateful like I described above (https://github.com/btcpayserver/btcpayserver/issues/3535#issuecomment-1140648903)
* Add a HMAC like suggested by @laurent1983  (https://github.com/btcpayserver/btcpayserver/issues/3535#issuecomment-1140768415)
* Removing the abilty to set the orderId in the payment button


**About stateful payment buttons:**
**Advantages:**

* Can do interesting things, like tracking how many clicks.

**Disadvantage**

* A bit more steps to create a button
* More works for all

**About HMAC:**
**Advantages:**
* Simple, stateless as before, same UX

**Disadvantage**
* Once a button has been created a malicious actor can always use it again. (replay attack)

** Removing ability to set the orderId for payment button **

**Advantages:** 
* Simple

All of the solutions have one downside: It will break either all, or a lot of payment buttons

**Comment by dennisreimann** [comment]
> Removing ability to set the orderId for payment button

That sounds like a plan.

**Comment by pavlenex** [comment]
> Removing ability to set the orderId for payment button

Bear in mind quite a few custom integrations use pay button for their stores, removing this sounds like a breaking change for them, so we'd need to communicate this and announce it, so that update doesn't break their stores.

**Comment by pavlenex** [comment]
If we're taclking this by modifing text only, here's how we may want to change it:

```
Payment button should be used for tips and donations. 
Using payment button for e-commerce integrations is not recommended since `order id` can be modified. For e-commerce, you should use our Greenfield API (LINK)
```

**Comment by veebch** [comment]
What's wrong with 'Always cross-check with the walllet for significant transactions'. Donations aren't some kind of lesser thing where it's ok to be misled. 

That way the button can be used for any kind of transaction.

**Comment by clementmas** [comment]
Having used a simple PayPal button to accept payments in the past, I was quite confused about the fact that I shouldn't use the BTCPay button.

In the end, I manually added a button that uses the Greenfield API in the backend (specifically the [btcpayserver-greenfield-php](https://docs.btcpayserver.org/Development/GreenfieldExample-PHP) package) to create an invoice and redirect to the payment page (using `$invoice->getCheckoutLink()`). It works well.

I believe that's the suggested way to accept payments using BTCPay Server. If so, I think it should be explained plainly in the docs.
