### ISSUE TITLE
ZigZag as a conversion provider

### ISSUE THREAD

**Issue by nwilson1412** [btcpayserver/btcpayserver#354]
ZigZag (zigzag.io) allows for BTC and lightning conversions from different coins (Eth/BCH/LCT/Dash). API: https://api.zigzag.io/graphiql

**Comment by bitcoinshirt** [comment]
I think this can only be done when #112 so it's sort of a duplicate imho.

**Comment by Kukks** [comment]
No I haven't

**Comment by pavlenex** [comment]
We've looked into this and does not seem easy to integrate, furthermore, there has not been many requests for this. Closing this for  now, if there are people who'd want to do this, just let me know and we'll re-open it.
