### ISSUE TITLE
Rename `Add plugin` to `Manage plugins`

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3540]
**UPDATE: We decided the best course of action for this issue is to simply rename `Add plugin` to `Manage plugins`**

_________________________________________________
Right now, in the sidebar we do have `Plugins` section, but the only way to access plugins through sidebar is by clicking on the `add new plugin`. This is confusing, because a user isn't always necessarily adding a new plugin, sometimes they may want to view, update them or something similar.

![Screenshot 2022-03-07 at 09 18 10](https://user-images.githubusercontent.com/36959754/156993616-c70f5a87-9d02-46af-a71d-4c2684a04b93.png)

I suggest we make `plugins` heading in the sidebar clickable and leading to `plugins page`

cc @dstrukt @dennisreimann

**Comment by pavlenex** [comment]
For `Apps` we should every created app in the sidebar, for plugins we show only lightning address which isn't really a plugin per se (integration). So either we showcase all plugins via expandable list in the sidebar or we have a link to view them all on a separate page /plugins.

**Comment by dstrukt** [comment]
A valid request, few things to consider though, and why I didn't push for it in 1.4.0 

1. decoupling the down carrot from the title, as currently clicking that section collapses/expands everything
2. does the functionality need to be a consistent action across all header sections (payments, wallet, etc..)?
--- we could make an exception for plug-ins, but could also argue it's a bit confusing that plug-ins is the only section with this functionality
--- but could be addressed by making the section link a different color if there is a "see all of {X}" type of view 
--- regardless having a view like this introduces a larger question for each of the other "sections"

Unless we want to address the above and create a solution for it, as I see you're already touching on with "Apps". I'd propose we introduce the concept of "Manage Plugins" (which I think we've already merged a PR with this wording change cc @dennisreimann), and it takes you to the current plug-ins screen to manage/add/update/etc.. and "Adding/Uploading" a plug-in is a secondary step in the "Manage" view .. with each plug-in eventually having their own detail view, etc..

**Comment by pavlenex** [comment]
I think `Manage plugins` is the simplest solution here as you proposed. Simply renaming it makes sense to me. 

I don't see that change on current master so it's not merged yet for sure.

**Comment by dstrukt** [comment]
Ahh it might not be, not 100% sure, might still be in an un-merged PR, but @dennisreimann and I have discussed that wording change, at least.

Overall, plug-ins, and the direction of these views definitely deserve more discussion, and this a great issue to raise! We pushed them front and center with 1.4.0, but def some area for improvement :)

Probably worth some time in the next design call.

**Comment by pavlenex** [comment]
Right, let's leave this issue opened, if you know which PR addresses this we can link it up, won't close it until we're sure we have this addressed somewhere 😄

**Comment by dennisreimann** [comment]
There's not a PR yet, the wording change was proposed in this discussion: btcpayserver/btcpayserver#3487
