### ISSUE TITLE
When NBXplorer is not ready/synced, LN is used as payment option - (LNURL should not activate if the node is down)

### ISSUE THREAD

**Issue by BitcoinMitchell** [btcpayserver/btcpayserver#3541]
# Describe the bug

If an order is created via the Greenfield API (and NBXplorer is not synced) LN is used as the only payment checkout option, but doesn't shown an QR code (and it should not have been an option to begin with).

## Reproduce 
1. Setup BTCPayServer using Docker
2. Set `BTCPAYGEN_CRYPTO1` to `btc` and enable LN
3. Start BTCPayServer and wait until it's ready (but before NBXplorer is ready)
4. Create an order via the Greenfield API (might work from the interface as well).

## Expected behavior

I expected some kind of error or information screen that would warn the developer/user that BTCPayServer is not yet ready to process payments. 

## Screenshots

| **Starting** | **Payment page**|
|---|---|
| ![image](https://user-images.githubusercontent.com/27309467/157012310-3879eb09-7aa6-416a-a6c6-d35b034965e5.png)  | ![image](https://user-images.githubusercontent.com/27309467/157014419-207d7390-cc69-4108-9432-8afb204ca88b.png) |

## Your BTCPay Environment:

- BTCPay Server Version: v1.4.7.0
- Deployment Method: Docker
- Browser: Chrome

### Setup Parameters

```
-------SETUP-----------
Parameters passed:
BTCPAY_PROTOCOL:https
BTCPAY_HOST:btcpay.example.com
BTCPAY_ADDITIONAL_HOSTS:
REVERSEPROXY_HTTP_PORT:80
REVERSEPROXY_HTTPS_PORT:443
REVERSEPROXY_DEFAULT_HOST:none
BTCPAY_ENABLE_SSH:false
NBITCOIN_NETWORK:mainnet
LIGHTNING_ALIAS:example.com
BTCPAYGEN_CRYPTO1:btc
BTCPAYGEN_CRYPTO2:
BTCPAYGEN_CRYPTO3:
BTCPAYGEN_CRYPTO4:
BTCPAYGEN_CRYPTO5:
BTCPAYGEN_CRYPTO6:
BTCPAYGEN_CRYPTO7:
BTCPAYGEN_CRYPTO8:
BTCPAYGEN_CRYPTO9:
BTCPAYGEN_REVERSEPROXY:nginx
BTCPAYGEN_LIGHTNING:lnd
BTCPAYGEN_ADDITIONAL_FRAGMENTS:opt-add-tor;opt-lnd-autopilot
----------------------
Additional exported variables:
BTCPAY_DOCKER_COMPOSE=/server/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml
BTCPAY_BASE_DIRECTORY=/server/BTCPayServer
BTCPAY_ENV_FILE=/server/BTCPayServer/.env
BTCPAYGEN_OLD_PREGEN=false
BTCPAY_SSHAUTHORIZEDKEYS=/datadir/host_authorized_keys
BTCPAY_HOST_SSHAUTHORIZEDKEYS:/server/.ssh/authorized_keys
BTCPAY_CRYPTOS:btc
BTCPAY_ANNOUNCEABLE_HOST:btcpay.example.com
```

**Comment by BitcoinMitchell** [comment]
Fun fact, once NBXplorer is ready, it will show the QR code for LN, but Bitcoin is still not a payment option.

![image](https://user-images.githubusercontent.com/27309467/157014017-9f240638-bc25-4a43-8feb-f9b4a874bc6b.png)

**Comment by pavlenex** [comment]
This is expected. Why it shouldn't work? NBXplorer has nothing to do with LN.

**Comment by BitcoinMitchell** [comment]
> This is expected. Why it shouldn't work? NBXplorer has nothing to do with LN. This is good fallback, imagine your nbxplorer for onchain getting stuck and your LN payments which are completely unrelated get stuck.
> 
> LN Node and on-chain node work independently of each other.

@pavlenex I see and that does make sense, however the QR code still doesn't work, as shown in the screenshot above (I did not hide it for privacy, as it never existed to begin with).

**Comment by pavlenex** [comment]
I see so the issue here is that if nbxplorer is down, LN invoice cannot be generated (or it's generated but the QR is not shown) from what I understood?

**Comment by BitcoinMitchell** [comment]
> I see so the issue here is that if nbxplorer is down, LN invoice cannot be generated (or it's generated but the QR is not shown) from what I understood?

Yeah, I think that is what happened. Since it did show up as soon as NBXplorer went into a "syncing" state, but it didn't work as long as _bitcoind_ was still syncing.

**Comment by ndeet** [comment]
I think instead of showing the not working/empty invoice page, BTCPay Server should throw an error on invoice creation from an API perspective. This way 3rd party integrations can avoid that users get redirected to the broken invoice page causing confusion.

**Comment by Kukks** [comment]
This is because LNURL is a "lazy" payment method, where it does not need the bitcoin/lightning node on invoice creation but only once it is shown.  Realistically, we should check for it I think..

**Comment by pavlenex** [comment]
@Kukks what do you propose  we do with this one? Any ideas on how we can check for it?

**Comment by Kukks** [comment]
I will make lnurl not activate if node is down I guess
