### ISSUE TITLE
Payment is settled but not confirmed network

### ISSUE THREAD

**Issue by LeMaX10** [btcpayserver/btcpayserver#3548]
**Describe the bug**
The payment is marked settled immediately as a transaction with enough amount to pay the bill hit the network. At the same time, all available webhooks are sent almost immediately.

Unfortunately, with such webhooks, it is not possible to accurately determine that the payment was confirmed by the network. The settings for the number of confirmations do not affect the payment status.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Create an invoice via API
2. We send a transaction sufficient to pay the invoice
3. All hooks are sent as soon as the transaction hit the network.

**Expected behavior**
To accurately understand that the invoice was paid in an external system, you need to receive an accurate invoice about the status of the payment. Invoice payment should not depend on the transaction entering the network, in my opinion, an invoice should be considered paid if the transaction was confirmed or according to the "Consider the invoice confirmed when the payment transaction" setting.

**Screenshots**
<img width="518" alt="wallet" src="https://user-images.githubusercontent.com/10564391/157416084-9c0c777b-0982-481a-9342-c85bfc0106a6.png">
<img width="1294" alt="webhooks" src="https://user-images.githubusercontent.com/10564391/157416093-8a07d0b2-de22-4cec-9f08-593d8a7a2885.png">
<img width="954" alt="screen" src="https://user-images.githubusercontent.com/10564391/157416098-22b7a741-8c1d-4506-84b4-dab2c307898c.png">

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    v1.4.7.0 (BTC Testnet)
- Deployment Method:       Docker
- Browser:                  Safari, Firefox

**Logs (if applicable)**
-

**Setup Parameters**
-

**Additional context**
-

**Comment by pavlenex** [comment]
@NicolasDorier any ideas on why this may happen on testnet?

**Comment by pavlenex** [comment]
@LeMaX10 since you're a few releases behind, does this happen with 1.5.1?
