### ISSUE TITLE
Installation on Windows Server 2016 with ssl letsencrypt

### ISSUE THREAD

**Issue by espriweb** [btcpayserver/btcpayserver#355]
Hi,

i installed btcpay server on a VPS with Windows Server 2016, it works perfectly even with a domain (btcpay.myname.com).

But now I should install a ssl certificate with "Let's Encrypt", I usually use the "certify the web" tool but it works only with iis, I tried to configure the port on 443 with ssl authentication through DNS but I returns "ERR_SSL_PROTOCOL_ERROR".

Can you tell me how to configure btcpay server with ssl on Windows Server 2016?

PS: I also disabled the firewall

Thanks in advance

**Comment by NicolasDorier** [comment]
I have no idea, but please if you find out document it! I advise you to run the docker-compose though, typically so you don't have to deal with this.

**Comment by espriweb** [comment]
All solved!
Follow the steps below:

1 )
Replace and uncomment the port and the ip "127.0.0.1" with the public one of your server in this file: 
C:\Users\Administrator\AppData\Roaming\BTCPayServer\Main\settings.config

2)
Follow this guide:
https://developers.coveo.com/display/public/SearchREST/Configuring+HTTPS+Reverse+Proxy+in+IIS;jsessionid=8CC247A01316F11632003C660D5983BF

3)
Debug absolute path of css: "BTCPayServer\Views\Shared\_Layout.cshtml"

4)
Disable the following javascript in: "BTCPayServer\Views\Shared\_Layout.cshtml"

This:
`
<script type="text/javascript">
        var expectedDomain = @Html.Raw(Json.Serialize(env.ExpectedHost));
        var expectedProtocol = @Html.Raw(Json.Serialize(env.ExpectedProtocol));
        if (window.location.host != expectedDomain || window.location.protocol != expectedProtocol + ":") {
            document.getElementById("badUrl").style.display = "block";
        }
    </script>
`
With this:
`
<script type="text/javascript">
        var expectedDomain = @Html.Raw(Json.Serialize(env.ExpectedHost));
        var expectedProtocol = @Html.Raw(Json.Serialize(env.ExpectedProtocol));
        if (window.location.host != expectedDomain || window.location.protocol != expectedProtocol + ":") {
            //document.getElementById("badUrl").style.display = "block";
        } else {
            window.location.href = "https://bitpay.dvlserver.com/";
        }
    </script>
`
For the moment everything is, now I try to enable the SSH and so it becomes complete.

Windows Forever

**Comment by espriweb** [comment]
Unfortunately, it inserts the absolute path of the reverse proxy

**Comment by NicolasDorier** [comment]
You need to properly setup `--externalurl` of BTCPay.

**Comment by NicolasDorier** [comment]
do not disable this stuff, other things will break, you just don't see it

**Comment by espriweb** [comment]
It does not work with https, at least for the few tests I've done but I update you

**Comment by espriweb** [comment]
I confirm, if I use `--externalurl=https://www.examle.com`  it works correctly, excellent.

**Comment by bitcoinshirt** [comment]
If you solved the issue, can you please close the issue @espriweb? Thanks.
