### ISSUE TITLE
Clear filter doesn't remove the label in wallet

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3550]
**Describe the bug**
In wallet, when you click on a label in the transaction list, it filters all transactions with that label, however if you want to remove that label, you have to refresh the page.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Label a transcation or have an automatic `invoice` label in transactions.
2. Click on the label, for example `invoices`
3. See the filtered view
4. Try to remove the label, you can't.

**Expected behavior**

We should be able to easily unfilter, remove labels once they're selected without having to refresh the page.

**Screenshots**
![Screenshot 2022-03-09 at 11 24 18](https://user-images.githubusercontent.com/36959754/157423362-726f0efe-31b4-4e10-8707-d5c22dddc204.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: © BTCPay Server v1.4.7.0 Environment: Development (Debug)    
- Deployment Method:      Locally  
- Browser:              Safari 15.00    

**Logs (if applicable)**

**Setup Parameters**

**Additional context**

**Comment by bolatovumar** [comment]
I added this feature a few weeks ago: https://github.com/btcpayserver/btcpayserver/pull/3474.

Do you not see a "Clear filter" button on the very right of the bar with filter buttons? Are you using the latest version?

I checked both in Chrome and Safari and it show up in both for me.

**Comment by pavlenex** [comment]
Hmm can't replicate this anymore, will re-open if it keeps happening.

**Comment by pavlenex** [comment]
Meh couldn't replicate, will reopen if I do.
