### ISSUE TITLE
Remove the extra `click here` step when accessing lightning service.

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3552]
**Describe the bug**

Currently, in order to access your lightning funds, you have to click on `Lightning`, select the external LN service, then the landing page has barely visible famous `click here` link, where a scan to access `QR Code connection` seems like a main call to action.  The `QR connection` basically allows user to open thie external service from a different device without authenticating. However:
1. Most users use external wallets like Zeus for node management.
2. We have `login codes` that allow users to authenticate with a QR code anyway.

**Expected behavior**A user should be able to open their Lightning interface right away as they click on the icon. If for some reason a user wants to authenticate on a different device, they can use the `login codes`

**Proposed solution**
1. Remove the extra step and open external service right away without scanning.
2. If there's a use-case for QR code scanning, then move it in a tab of the main Services page.

**Screenshots**
![Screenshot 2022-03-10 at 12 50 58](https://user-images.githubusercontent.com/36959754/157657581-e59ecb41-1cf1-44c6-bc67-55e553edf58b.png)

![Screenshot 2022-03-10 at 12 50 46](https://user-images.githubusercontent.com/36959754/157657574-150f8e01-cf38-4b05-baf3-e5f1d425875e.png)

![Screenshot 2022-03-10 at 12 51 21](https://user-images.githubusercontent.com/36959754/157657584-3a7b30da-5419-44db-b6ab-ef17ba3f25dd.png)
![Screenshot 2022-03-10 at 12 51 52](https://user-images.githubusercontent.com/36959754/157657587-a420c910-bec5-4b14-baa8-3569584400da.png)
ux

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    
- Deployment Method:        
- Browser:                  

**Logs (if applicable)**

**Setup Parameters**

**Additional context**

**Comment by pavlenex** [comment]
@dennisreimann @dstrukt What was the consensus on this one on a design call 30? I was a bit late so unsure if we've decided to tackle it or not.

**Comment by dennisreimann** [comment]
I want to tackle it, but haven't found a good way to test it locally yet. In dev mode we don't have those LN services and I need to integrate them to properly build and test it.
