### ISSUE TITLE
Unable to connect to host: cannot retrieve macaroon: cannot get macaroon: root key with id 0 doesn't exist

### ISSUE THREAD

**Issue by danielalexiuc** [btcpayserver/btcpayserver#356]
I started getting this error on ZAP when connecting to my BTCPayServer using the GRPC settings:
 
`Unable to connect to host: cannot retrieve macaroon: cannot get macaroon: root key with id 0 doesn't exist
`
I'm pretty sure this happened only after setting up a "wallet" on BTCPayServer using a Ledger; the ZAP grpc connection was working fine before that.

**Comment by bitcoinshirt** [comment]
@danielalexiuc This probably happened after an update? What's your version and setup?

If so maybe this:
1. Try to copy your GPRC in Zap again. See if that works.
2. If that does not work Try [this solution in FAQ](https://github.com/btcpayserver/btcpayserver-doc/blob/master/FAQ.md#lnd-connection-issues-after-an-update)
3. Copy the config in Zap again.

If it's in-production setup, you may wait for some of the devs to confirm.

**Comment by danielalexiuc** [comment]
Thanks - sorry I didn't see that in the FAQ, I'll try that.

**Comment by danielalexiuc** [comment]
The instructions in the FAQ fixed this problem:

https://github.com/btcpayserver/btcpayserver-doc/blob/master/FAQ.md#lnd-connection-issues-after-an-update

Thanks for your help @bitcoinshirt !

**Comment by sipsorcery** [comment]
Note link is now https://github.com/btcpayserver/btcpayserver-doc/blob/master/FAQ/FAQ-LightningNetwork.md#lnd-connection-issues-after-an-update
