### ISSUE TITLE
Joomla Virtuemart Integration

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3569]
This issue is just a simple tracker for ` Joomla Virtuemart` integration we're planing on having for BTCPay Server. No ETA yet, but putting for 1.6.0 just in case, though it'll probably come after 1.6.0

**Comment by subn3t1** [comment]
Wonderful news!

**Comment by ndeet** [comment]
Finally everything has been put together 😅  

I applied to get listed on the [Joomla Extension Directory (JED)](https://extensions.joomla.org) but not sure how long it takes as it requires manual review. 

This means the JED installation mentioned in the docs is not supported yet (but the manual installation works anyway). For docs see here: https://github.com/btcpayserver/btcpayserver-doc/blob/9ebc2942eb9dcde703cb3477ad5a1a146ecde8aa/docs/VirtueMart.md

Repo and downloads: 
https://github.com/btcpayserver/joomla-virtuemart/releases

Demo Site (Joomla 3 + VirtueMart 4):
https://joomlavm3.demo.btcpay.tech/

Would be great if some Joomla users could test before public release.


@pavlenex not sure but afair there was some other Joomla/Virtuemart issue no - would be good to ping some other Joomla users to test? I can't find it atm, so maybe I just remembered it wrong 🤔

**Comment by subn3t1** [comment]
@pavlenex 

It will be pleasure for me to do tests. I am on the job already :)

**Comment by subn3t1** [comment]
First impressions :

1. Install goes fine. Maybe a message that the plugin should be activated may be added.
2. Configuration is straight forward and easy. Documented as help notes just fine.
3. When you click the final "Check out" button on the frontend, no redirect to the btcpay server happens. 

The loaded page just says : "Thank you for your order! Your order has been processed. " 

And this is all. No redirect to the payment server at all. 

Here is the configuration of the server: 

Apache 2.4.51
PHP 7.4.23  FPM
MYSQL 5.7.35 
Joomla 3.10.9
Virtuemart 3.8.8 

Hope this helps!

**Comment by ndeet** [comment]
Hey @subn3t1, thanks a lot for testing!

> When you click the final "Check out" button on the frontend, no redirect to the btcpay server happens.
The loaded page just says : "Thank you for your order! Your order has been processed. "

This is very strange, maybe I forgot a szenario where something goes wrong but I do not catch the error to abort. If there is something wrong you should never see that page but get redirected to the cart page. VM 3 or 4 should be fine, locally I use 3 and on the demo server VM 4 is running. Both on Joomla 3 and PHP 7.4.

Do you happen to find any error in some error logs? Would be really great if I could reproduce the error.

> By the way, in the Wordpress plugin there is a "Pair"-ing part that pairs the website with the btcpay server. I see that you go the other way round , but maybe with pairing will be much more convenient. Just my 2 cents ...

Pairing was done previously with the old BitPay API, the latest BTCPay WooCommerce V2 plugin does also use Greenfield API like this plugin with api key and webhook.

**Comment by ndeet** [comment]
@subn3t1 I could reproduce the problem in case the api key is wrong (or maybe some other error happens). Working on a fix now and will let you know when new release available.

**Comment by ndeet** [comment]
@subn3t1 had a "todo: add cart redirect" in case there goes something wrong in the code 😅  It is now proper handled and you will see a message and stay in cart. It will also force write into the VM log. Likely your api key was wrong or some other connection error happens on your site.

https://github.com/btcpayserver/joomla-virtuemart/releases/tag/v1.0.4

**Comment by ndeet** [comment]
@pavlenex 
> This is impressive amount of work. I think we'll have to follow up with good video and documentation after the testing phase. 

I was long overdue to deliver - sorry, client work took out much more time than anticipated 🙈  But until holidays have now more time to catch up with stuff. 

I can do screencast like for WC V2 plugin, magic voice and video edit skills of webwor can then use it as a base like we did with WC V2 plugin. 

Re: twitter, sure lets do it after @subn3t1 can confirm it works otherwise it would be too embarrassing to have everyone run into a wall because I did not catch something obvious 😬  😆

**Comment by subn3t1** [comment]
> @subn3t1 had a "todo: add cart redirect" in case there goes something wrong in the code sweat_smile It is now properly handled and you will see a message and stay in cart. It will also force write into the VM log. Likely your api key was wrong or some other connection error happens on your site.
> 
> https://github.com/btcpayserver/joomla-virtuemart/releases/tag/v1.0.4

Now when "Confirm order" is pressed the page says
"Error
There was an error processing the payment on BTCPay Server. Please try again and contact us if the problem persists."

**Comment by ndeet** [comment]
@subn3t1 The error is logged in /administrator/logs/btcpayvm.X.log where X is a number, e.g. btcpayvm.0.log etc. 

For security reasons backend errors should not show up in the frontend and therefore it only shows some standard message. Likely this is a problem with authentication/api key. Will add that to the Troubleshooting docs.

**Comment by subn3t1** [comment]
> @subn3t1 The error is logged in the filesystem `/administrator/logs/btcpayvm.X.log.php` where X is a number, e.g. `btcpayvm.0.log.php` etc.
> 
> For security reasons backend errors should not show up in the frontend and therefore it only shows some standard message. Likely this is a problem with authentication/api key. Will add that to the Troubleshooting docs.

Thank you. Seems an authentication problem:

2022-05-25 08:37:11 ERROR Error during POST to https://mybtcserver.tld/api/v1/stores/mystoreid/invoices. Got response (401): {&quot;code&quot;:&quot;unauthenticated&quot;,&quot;message&quot;:&quot;Authentication is required for accessing this endpoint&quot;}

P.S. I replaced here the server name and the store ID.

**Comment by ndeet** [comment]
Double check you gave the api key the right permissions and also to the right store. Also make sure you entered the correct api key and store id. Make sure you do not have whitespace in front or after it. You can also try to create an api key with all permissions for all stores just for testing if it works with that and there is a problem with that specific api key configuration.

**Comment by subn3t1** [comment]
Strange. I checked everything. The anyone can create invoice option is ON too. I put the Legacy API Key and the store ID correctly in Virtuemart. 
Still the log from the BTCpay Server says:

2022-05-25 10:53:28.344 +00:00 [INF] Greenfield.APIKeys was not authenticated. Failure message: ApiKey authentication failed
2022-05-25 10:53:28.346 +00:00 [INF] AuthenticationScheme: Greenfield.APIKeys was challenged.
2022-05-25 10:53:28.346 +00:00 [INF] AuthenticationScheme: Greenfield.Basic was challenged.

But I have two keys in the btcpay server store. One is for Basic authentication (which should be passed with headers of the POST) and the other is the API Key. I use the API Key.

**Comment by petzsch** [comment]
"Legacy API Key" -> thats the issue

You need the API Key from your user account settings:
![image](https://user-images.githubusercontent.com/1374810/170249340-82b1bc2c-62b1-4ea2-a99b-372744d44888.png)

**Comment by subn3t1** [comment]
> "Legacy API Key" -> thats the issue
> 
> You need the API Key from your user account settings: ![image](https://user-images.githubusercontent.com/1374810/170249340-82b1bc2c-62b1-4ea2-a99b-372744d44888.png)

I just found my mistake too!

**Comment by subn3t1** [comment]
Yes. Now it send me to the payment gateway with the correct amount.
I will now test it with real transaction so to confirm that everything works

**Comment by ndeet** [comment]
Ah so you assumed it is the same way and skipped the docs 😆  https://github.com/btcpayserver/btcpayserver-doc/blob/9ebc2942eb9dcde703cb3477ad5a1a146ecde8aa/docs/VirtueMart.md#22-create-an-api-key-and-configure-permissions

Great it works now 👍

**Comment by subn3t1** [comment]
> Ah so you assumed it is the same way like on the old BitPay pairing and skipped the docs laughing https://github.com/btcpayserver/btcpayserver-doc/blob/9ebc2942eb9dcde703cb3477ad5a1a146ecde8aa/docs/VirtueMart.md#22-create-an-api-key-and-configure-permissions
> 
> Great it works now +1

Shame on me :)

**Comment by pavlenex** [comment]
Is there something we can do to reduce ambiguity between the legacy and greenfield API keys, having them on two different places certainly isn't ideal?

**Comment by ndeet** [comment]
> Shame on me :)
Nah it is a bit confusing and if you are familar with the whole process and not aware that there is a new way to do it then you easily miss it. Been there, done that 🙌  

> Is there something we can do to reduce ambiguity between the legacy and greenfield API keys, having them on two different places certainly isn't ideal?

Afair it was discussed in the UI channel or maybe posponed? The main problem is that the legacy key was store related while the new api keys are account related, so they are in completely different places. What would maybe help is to add some note with a link to accounts api keys on the legacy tab?

**Comment by ndeet** [comment]
Awesome, thank you for testing 🙏  💚

**Comment by pavlenex** [comment]
@ndeet I think we can close the issue now and now that we have docs, perhaps we can tweet it out to ask for more testers if that's what's needed?

**Comment by ndeet** [comment]
@pavlenex agree, let's do it. 

For anyone testing we have the plugin in the JED (Joomla Extension Directory) so you can install via UI or download as outlined in our docs https://docs.btcpayserver.org/VirtueMart/

**Comment by subn3t1** [comment]
Hello guys!

After:
1.Upgrading the host from PHP 7.4 to PHP 8.1
2. Opening the cart view or after adding a product to the cart

The result was the following error:
0 Unsupported operand types: string * float

I use:
Firefox under Fedora Linux 36

My fix:
I found that the fix is to add (float) before the strings in line 792 in btcpayvm.php

Probably there is a better way but it is up to the developers to decide.

Hope this helps for the project.

**Comment by ndeet** [comment]
Hey @subn3t1 thanks a lot for bringing this up. As answered in the issue you opened [here](https://github.com/btcpayserver/joomla-virtuemart/issues/1) there is a new release [v1.0.5 ](https://github.com/btcpayserver/joomla-virtuemart/releases/tag/v1.0.5) which fixes the problem
