### ISSUE TITLE
How to access BTCPayserver from outside localhost

### ISSUE THREAD

**Issue by danbadjar** [btcpayserver/btcpayserver#357]
Hello, sorry...newbie here.
I'm testing BTCPayserver on Linux and everything is working fine but I would like to access from outside localhost since I don't have a gui on that remote server in which I installed BTCPayserver.
I'm configuring it remotely

The default port 23000 is closed so I can't connect.

Is there a way to do that?

Thanks

**Comment by danbadjar** [comment]
Solved using bind 0.0.0.0

**Comment by danbadjar** [comment]
yes I used dotnet run 
thanks

**Comment by NicolasDorier** [comment]
please use `run.sh` if you use dotnet run, it might use Debug mode and the launch profile, which you don't want.
