### ISSUE TITLE
Rename `Wallet` to `Bitcoin` in the sidebar

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3571]
As agreed on Mattermost[ in the UX channel.](https://chat.btcpayserver.org/btcpayserver/pl/xzx4djan73gcdn7mx5oumgykxy)

Using `wallet` for bitcoin payment method doesn't really make sense. As when you want to address payment method settings, you have to change wallet settings, which is a bit incorrect.

Considering that we already have wallets title in the sidebar, I propose that we change Wallet for on-chain, to Bitcoin. Now segregating BTC and LN isn't ideal UX, but one day we'll get there to unify these. Users shouldn't have to think on or off chain, they should only think bitcoin.

![Screenshot 2022-03-09 at 09 58 04](https://user-images.githubusercontent.com/36959754/160001408-dfa7d7d2-c034-4b6f-9b1a-45bd9092c865.png)

**Comment by phershbe** [comment]
I'm relatively new to open source but know Git. Is it possible for me to change this? Would I make a pull request?

**Comment by pavlenex** [comment]
Hey @phershbe absolutely. Perhaps our master @dennisreimann can give you some guidance on where in code this needs to be changed in case you're having trouble.

**Comment by phershbe** [comment]
@pavlenex Yeah exactly, that would be good, I got a little bit nervous after posting because I was digging through the code and could not figure out where to go. I'll check the other issue too.

**Comment by phershbe** [comment]
@pavlenex @dennisreimann I found the file obviously. Sorry to bother you but did I do everything correctly? I had never made a pull request before other than on my own projects.

**Comment by bolatovumar** [comment]
@phershbe you did everything correctly. One thing you can do is add something like "close #3571" and it will automatically close the issue once your PR is merged.

See here for more details: https://stackoverflow.com/questions/12235620/automatically-closing-issue-from-pull-request-in-github

**Comment by pavlenex** [comment]
Closing, fixed in https://github.com/btcpayserver/btcpayserver/issues/3572 🎉

**Comment by phershbe** [comment]
@bolatovumar @pavlenex Great, the additional information is exactly the kind of thing that I'm trying to learn in order to use this efficiently and correctly. Thank you.
