### ISSUE TITLE
Notifications `Invoice was confirmed paid` to `Invoice is settled`

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3572]
We no longer have `paid` status, and I am not really sure why we ever used `paid` for the `complete` invoice status in notification.

![Screenshot 2022-03-24 at 21 12 09](https://user-images.githubusercontent.com/36959754/160002150-6cd3940d-972f-4afd-b5f0-fb96cee80116.png)

I propose that instead `invoice was paid`, a notifications properly reflects the greenfield API terminology and says `Invoice is settled` I am not sure why we use past tense in notifications? 

With #2510 we can potentially even put settled green label inside notification to make it more obvious to merchants that it's all good.

**Comment by phershbe** [comment]
I would be happy work on this if you need somebody to

**Comment by pavlenex** [comment]
Sure, take it over @phershbe, let us know if you face any issues along the way :)

**Comment by phershbe** [comment]
@pavlenex It's late here so I'm going to look at this again tomorrow. I haven't found the file yet but I can find it. I found the file and made the change on the other issue: https://github.com/btcpayserver/btcpayserver/issues/3571

**Comment by phershbe** [comment]
@pavlenex I'm going to check out https://github.com/btcpayserver/btcpayserver/issues/2510 too like you mentioned. Since I'm new to open source, I wanted to make this PR before in order to not feel overwhelmed.

**Comment by pavlenex** [comment]
Awesome, keep 'em coming @phershbe you're on a roll 🔥 

Closing this issue since I verified it's fixed with #3576

**Comment by MytiMouse1** [comment]
Thank you for your help
