### ISSUE TITLE
[Payment Request] - `Email field` incorrectly communicates the functionality 

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3579]
**Describe the bug**

When making a payment request, the email field ` asp-for="Email"` says: `Receive updates for this payment request.` which isn't correct as no updates are send once the email is entered.

In current form, the function of that field, to my research, is to simply pass customer's email into the invoice details field, same way we have it when creating a new invoice.

Ideally, this field should send updates.

There are two ways to address this:
1. Simple rename and make it consistent with what we have in our invoice page (easy)
2. We implement a proper email  sending functionality for invoices that will address this and a couple of other problems/feature requests

I would vote for option 2, but I guess this one is up for a discussion.

Ideally, the receiver of the payment request could get notification email to make a payment as soon as the payment request is sent, then they could get updates depending on the status.

   
**Screenshots**

![Screenshot 2022-03-28 at 10 46 02](https://user-images.githubusercontent.com/36959754/160362295-8784c2b3-121e-46d8-b40e-7c90cee5aecf.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:   © BTCPay Server v1.4.7.0  
- Deployment Method:    Docker    
- Browser:                  

**Logs (if applicable)**

**Setup Parameters**

**Additional context**

**Comment by Kukks** [comment]
Bear in mind that the pr that sets lazy payment as default removes this
functionality

**Comment by Kukks** [comment]
I was referring to https://github.com/btcpayserver/btcpayserver/pull/3353

**Comment by pavlenex** [comment]
So this function doesn't work anyway. The only way the email field works is that it passes it into the invoice details. I still am not sure I understand how lazy payment may have influence over this field in particular.

**Comment by Kukks** [comment]
I think it's important but there is a lot of nuance in what the feature means to who.

For example, some would want it to be sent instantly and others once the invoice is settled. Some may want to provide a different subject or text based on what was paid, etc. Some may want the email sent both to the customer but also to the store owner

I have a few ideas around this.

**Comment by pavlenex** [comment]
I think we should be as generic and concise as we can in a built in functionality, as I tried to propose in #3580 ,but any customization should be handled externally, via plugins or integrations like Zapier.

In this particular case:

`Hello, payment request `PaymentReqestID` is awaiting for your payment. To pay, click on the link` sth like that.

**Comment by Kukks** [comment]
> I think we should be as generic and concise as we can in a built in functionality, as I tried to propose in #3580 ,but any customization should be handled externally, via plugins or integrations like Zapier.
> 
> In this particular case:
> 
> `Hello, payment request `PaymentReqestID` is awaiting for your payment. To pay, click on the link` sth like that.

In #4917, I did a change that makes the a store email rule that links to the receipt work well for pay requests. I think it should be sufficient. I vote for removing the email option in pay requests.

**Comment by pavlenex** [comment]
@Kukks It seems what you reffered to relates to email supplied through POS?

I am not in favor of removing this option, it's pretty standard process when you're invoicing a client to add their email so that the invoice is sent to them.

**Comment by Dreadfullove** [comment]
> **Describe the bug**
> 
> When making a payment request, the email field ` asp-for="Email"` says: `Receive updates for this payment request.` which isn't correct as no updates are send once the email is entered.
> 
> In current form, the function of that field, to my research, is to simply pass customer's email into the invoice details field, same way we have it when creating a new invoice.
> 
> Ideally, this field should send updates.
> 
> There are two ways to address this:
> 
> 1. Simple rename and make it consistent with what we have in our invoice page (easy)
> 2. We implement a proper email  sending functionality for invoices that will address this and a couple of other problems/feature requests
> 
> I would vote for option 2, but I guess this one is up for a discussion.
> 
> Ideally, the receiver of the payment request could get notification email to make a payment as soon as the payment request is sent, then they could get updates depending on the status.
> 
> **Screenshots**
> 
> ![Screenshot 2022-03-28 at 10 46 02](https://user-images.githubusercontent.com/36959754/160362295-8784c2b3-121e-46d8-b40e-7c90cee5aecf.png)
> 
> **Your BTCPay Environment (please complete the following information):**
> 
> * BTCPay Server Version:   © BTCPay Server v1.4.7.0
> * Deployment Method:    Docker
> * Browser:
> 
> **Logs (if applicable)**
> 
> **Setup Parameters**
> 
> **Additional context**

"tiredoftired0648@gmail.com"

**Comment by pavlenex** [comment]
Alright, I'll open a new issue this one changed.
