### ISSUE TITLE
Implement most basic `store email functionality` for certain invoice statuses to help with troubleshooting and reduce user-error

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3580]
People using BTCPay often see the `email field` when creating invoices, using POS, issuing a refund, or creating a payment request. The reasonable thing to expect when you see an email field is that the customer will be notified on the invoice receiving. However, this is not the case.

Currently our SMTP functionality is only used for `forgot your password` which is only useful for third-party host admins. I propose that we add the most basic email functionality for certain invoice statuses. This will not only fix the issue of BTCPay users getting confused, but will also help address common invoice problems when troubleshooting an invoice.

  For example, BTCPay Server, if store SMTP is set up, should be able to notify a customer about an incoming refund, an incoming payment request, a failed payment status, a partially paid status with the option to pay the due.

I propose that we try to document very generic and concise messages that will be built into the software and can be disabled (but are enabled by default). Any further customization should be out of scope, and merchants willing to customize messages should use integrations like Zapier, but very bare bone functionality should be there for anyone.

One thing to pay attention to, is that if SMTP isn't set up, and this option is implemented we grey it out in the UI and  add instructions next to the `Email field (like we do for forgot your password).

We can create a table and start document most common cases email would be a core function.

### Proposed Emails for important statuses

These are three statuses that should interest customer, other statuses are more for merchant. Text is just suggestion, would be great if we can try to come up with text. If there's someone from community willing to test a few different competitors and how they communicate statuses over email, I think that would be helpful.

| Invoice Status | Email Text |
| ---------------------- | ------- |
| **Expired (paidPartial)** | Your `invoiceID` has not been paid in full. Please click here to pay due so we can process your payment, or reply to this email to request a refund. | 
| **Settled** | Your payment has been received and settled. We will process your order shortly. Thank you |
| **Processing**| Your payment has been received and is now processing. Once it confirms on the blockchain, we'll let you know.  |

Emails would really be helpful for:
- Refunds (You've received a refund. Please claim it by clicking here to collect a payment.
- Payment requests (You've received a payment request by `StoreID`. Click here to pay it #3579

**Comment by dstrukt** [comment]
Love that this feature is being worked on, lot of areas we can utilize and improve this functionality across the app!
