### ISSUE TITLE
Set default store currency in new invoices

### ISSUE THREAD

**Issue by Bangalisch** [btcpayserver/btcpayserver#3581]
Hey guys, 

When creating a new invoice the Currency field is empty, while we do set a default store currency. 
This feels very weird and as a extra since you can leave it empty and it does fill in the default store currency. 

![CurrencyDefault](https://user-images.githubusercontent.com/102448109/160448743-a3daf6a9-e656-40db-b73d-33d6cd5fcb99.JPG)

It would very nice if this would read (consistantly) that i set a default currency in the store. 

Greatings.

**Comment by dstrukt** [comment]
Hey, we agree, and this is definitely something we intend to tackle, as it should be filled be default .. thanks for opening an Issue!

**Comment by Bangalisch** [comment]
Niceee! thanks for the response dstrukt :) 
Filled by Store Default, as there's places ( https://github.com/btcpayserver/btcpayserver/issues/3582 ) where its defaulted to BTC :D
