### ISSUE TITLE
[GreenField API] Get store on-chain wallet transactions

### ISSUE THREAD

**Issue by keepjhonnying** [btcpayserver/btcpayserver#3587]
Is there any way to find, via API, on-chain wallet transactions by the comment field or label?

The doc [https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreOnChainWallets_ShowOnChainWalletTransactions](url) don't mention any way.

**Comment by bolatovumar** [comment]
@keepjhonnying no, there isn't a way to do that currently. It probably makes sense to allow filtering by label as that's a functionality we have in the UI but not in Greenfield API.
