### ISSUE TITLE
Shopify integration fails to connect to API

### ISSUE THREAD

**Issue by beeforbacon** [btcpayserver/btcpayserver#3589]
**Describe the bug**
After generating the APIs required for btcpay to interact with shopify through the settings --> integration --> shopify setup. Error occurs from btcpay that states "Shopify rejected provided credentials, please correct values and try again"

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Generate API key and secret key on spotify backend with "orders" as read/write (as per the doc guide).
2. Settings --> integration --> shopify setup
3. plug in the info including the mystore.myshopify.com url
4. error "Shopify rejected provided credentials, please correct values and try again"

**Expected behavior**
Successful connection to shopify

**Screenshots**
"Shopify rejected provided credentials, please correct values and try again"

![image](https://user-images.githubusercontent.com/51864803/160862831-2d0bf0bd-1c36-4c62-be5a-aaade4422ceb.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:     v1.4.7.0
- Deployment Method:       Docker
- Browser:             chrome, firefox

**Comment by pavlenex** [comment]
Thanks for the screenshots @Kukks I'll put improving Shopify docs accordingly as a priority today.
