### ISSUE TITLE
After refund total sum of refund + fees isnt reflected in the wallet

### ISSUE THREAD

**Issue by Bangalisch** [btcpayserver/btcpayserver#3591]
Hey, 

Was going trough the flow of Refunds and might have found a little bug. 
Whenever you have gone trough the Payout motion of a refund it shows up as a transaction in your wallet. 
For display i used fixed amounts. The refund is 1 BTC, since im doing this in regtest fee is fixed to 0.00020900. 
So simply put i expect Wallet to reflect -1.00020900, it does not it only puts the fee as a minus.
Now it could be because of regtest, but i couldnt find this anywhere. 
after discussion with @pavlenex decided to post here. 

Cheers

![screenshot 8](https://user-images.githubusercontent.com/102448109/160922137-9b57de22-a2a6-47cf-80a5-49c756a7c75c.jpg)

![Inkedscreenshot 9](https://user-images.githubusercontent.com/102448109/160922169-ab6d7545-5f46-444a-80a1-306b5e46cc2a.jpg)

**Comment by Kukks** [comment]
Was the address you paid belonging to your own wallet?

**Comment by Kukks** [comment]
Then that is why. The amount there reflects the change in the balance of the underlying wallet. 

Perhaps we could have a view in the future showing actual outputs, but that is way harder.

**Comment by pavlenex** [comment]
Makes sense then. @Bangalisch can you try replicating this by creating a new store and then providing the address from that store?

**Comment by Bangalisch** [comment]
@pavlenex yep kukks is right thats it :) Ty 
Close it :) 

![screenshot 11](https://user-images.githubusercontent.com/102448109/161092053-da3137b9-05cd-4b71-a79f-080cbb290984.jpg)
