### ISSUE TITLE
Lightning Address doesn't get deleted when deleting store

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#3596]
On v1.4.7.0 I noticed that deleting a store, does not delete it's coresponding Lightning Addresses. After recreating another store and trying to add the same Lightning Address, I get an error that it already exists: Though I have no mean of finding it anymore.

I guess this is a missing FK constraint with cascading delete missing. Hope it can be fixed easily. (+perhaps a migration script that deletes orphaned Lightning Address)

**Comment by bolatovumar** [comment]
@petzsch thanks for reporting. I could repro this and it's addressed in this PR: #3603
