### ISSUE TITLE
Improve handling of `refunded` invoice in invoices, invoice details and invoice export.

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3597]
Currently, if an invoice is `refunded`:

- It's not visible in `invoice export` as `refunded` it's `settled` the amount is in +, which can lead to accounting problems.
- In `invoices view` you cannot distinguish refunded invoices, they say `settled` so it's hard for a merchant to pick a particular invoice that may need to be refunded or view a refunded one as they're all `settled`
- In the `invoice details` there's no field indicating an invoice is refunded in any way
- In invoice details there's no indicator of the refunded amount , and you can even click `issue a refund` on an invoice already refunded.

This is an example of an invoice detail of an already refunded invoice.
![Screenshot 2022-03-31 at 16 11 47](https://user-images.githubusercontent.com/36959754/161121562-7dc30dc1-d3aa-460a-8c4f-768479807c23.png)
This invoices view shows 3 invoices as settled, all of them `refunded`
![Screenshot 2022-03-31 at 20 08 43](https://user-images.githubusercontent.com/36959754/161121685-1332d7f9-4c8d-41fa-b568-f23fe1a8d62a.png)
And most problematic of all, this is an invoice export containing reporting for refunded invoices

![Screenshot 2022-03-31 at 20 10 30](https://user-images.githubusercontent.com/36959754/161122013-0cffc780-986e-4f7d-9dc0-8959ee1a32a2.png)

This issue can potentially be broken down into several issues, but for now we'll use it as a tracker

- [ ] Add refunded invoices in invoice export and show refunded amount
- [x] Add refunded `label` in invoices page view to distinguish easier refunded from settled.
- [x] Add indicator that invoice is refunded in invoice details and don't show `issue a refund` button, instead show `preview a refund`

Luckily we log in refunded in database, but we don't show it in the UI, show a fix for all of these shouldn't be that hard as @Kukks pointed out.
I had an idea of introducing `refunded` and `refunded-partial` status, but Kukks was against it.

Thanks to Bas for pointing majority of these problems, I'm just logging an issue.

**Comment by rustywave** [comment]
Hi @Kukks , was advised that updating the export was the only thing remaining on this ticket. Found a couple items for clarification if you have time:

1. Refunds are list of Pull Payments. However, through the invoice detail page you can only perform a full or partial refund once. Should we anticipate multiple refunds in the future? Seems like we should.
2. If yes to 1, how should we deal with summing multiple refunds that may be in different currencies? Is there a function for this already? Easy solution would be to just take the first one but may cause problems in the future. But I guess we'd have to refactor in multiple areas anyway.

Another separate-but-related issue:
- Export doesn't appear to go off of selected invoices but rather the search bar

**Comment by rustywave** [comment]
@pavlenex

Need a little clarification for desired result -- invoice export actually can have multiple payments per invoice.  Refunds have multiple pull payments per refund and could be added separately like payments. However, as @Kukks  pointed out this is not really an invoice export now.

Some options:

1. Make this a top-level, invoice-only export (no multiple payments or pull payments)
2. Add pull payments, by line like we do for payments
3. Other

Also a separate issue to consider is that exporting invoices does not respect the checkbox selections -- it exports all invoices that have been listed on the page (via filter terms). Will try to join the call!

**Comment by pavlenex** [comment]
Hey @rustywave are you still up for tackling this one?

**Comment by rustywave** [comment]
@pavlenex, sorry for being MIA! i won't be able to finish this or any others at this time. update is partway done but there are still some clarifications needed on which are the correct fields to use. i can either create a PR or push my changes to a remote branch for the next person to review.

**Comment by rustywave** [comment]
If it helps, branch is here:
[feature/3597-add-refund-to-invoice-export](https://github.com/rustywave/btcpayserver/tree/feature/3597-add-refund-to-invoice-export)

Can delete if not needed anymore or just let me know and I'll delete.

**Comment by NicolasDorier** [comment]
The invoice export isn't an invoice export but a payment export. We shouldn't try to change the nature of it.

If we need exports on other things, we need more discussion and refactor completely our data export system.
It isn't an easy topic as there are multiple use cases to consider, and it is never clear for each use case which fields and data would make sense.

But would be to inspire from fireflyiii.

**Comment by pavlenex** [comment]
@NicolasDorier Agreed. Can you explain what fireflyiii does that you like?

**Comment by RSALDANA31** [comment]
Ok
