### ISSUE TITLE
Store List Dropdown Menu Overflow

### ISSUE THREAD

**Issue by leesalminen** [btcpayserver/btcpayserver#3598]
**Describe the bug**
When you have access to many stores, the dropdown selector of stores overflows the page and isn't scrollable. This results in some stores being inaccessible.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to your BTC Pay Server instance and log in.
2. Click on the store dropdown select menu
3. Unable to scroll down in the list

**Expected behavior**

You should be able to scroll down in the list to see all stores (and the Create New Store button that is last).

**Screenshot
<img width="1435" alt="Screen Shot 2022-03-31 at 3 31 03 PM" src="https://user-images.githubusercontent.com/3018359/161153040-05e73766-c065-4101-9ef1-9bd17414bd2d.png">
s**

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:   1.4.7.0
- Deployment Method:      Manual
- Browser:                  MacOS 12.3 Safari 15.4

**Logs (if applicable)**

**Setup Parameters**

**Additional context**

I have access to >25 stores. You have to have a lot of stores to notice this issue.

**Comment by Goro2030** [comment]
It will be great also if the stores would be sorted alphabetically in the dropdown list to quickly find what you're looking for.

**Comment by leesalminen** [comment]
> It will be great also if the stores would be sorted alphabetically in the dropdown list to quickly find what you're looking for.

Hi @Goro2030, I agree! Unfortunately, I don't have any experience with .NET so would probably take me a bit to clone down the repo and work on that. I was able to make and test this issue/PR with browser dev tools only so I avoided that step :). Perhaps we should open a separate issue for alpha sort on the list?
