### ISSUE TITLE
Any idea about shopify integration?

### ISSUE THREAD

**Issue by sysout** [btcpayserver/btcpayserver#36]
Is there any integration support with e commerce SaaS?

**Comment by NicolasDorier** [comment]
Shopify's bitpay plugin is closed source, can you try to ask them about this ?
If they open source it, I can adapt for BTCPay.

**Comment by DaDre** [comment]
Any updates on this? Would be super useful and would cut out BitPay / Coinbase with their merchant fees.

**Comment by NicolasDorier** [comment]
A company is working on it...

![image](https://user-images.githubusercontent.com/3020646/36766112-c6e0b4b2-1c77-11e8-9712-b6682511a0ea.png)

It does not depends on me though, you can come on http://slack.forkbitpay.ninja/ to follow him

**Comment by Kukks** [comment]
open node injects this js code into the shopify checkout page:
```
! function() {
    "use strict";
    const e = document.querySelector.bind(document),
        n = (document.querySelectorAll.bind(document), (e, n) => {
            n.parentNode.insertBefore(e, n.nextSibling)
        }),
        t = "https://api.opennode.co";
    let i = {},
        o = "Thank you!",
        r = null,
        d = null;
    const s = () => {
            i = {
                mainHeader: e("#main-header"),
                orderConfirmed: e(".os-step__title"),
                orderConfirmedDescription: e(".os-step__description"),
                continueButton: e(".step__footer__continue-btn"),
                checkMarkIcon: e(".os-header__hanging-icon"),
                orderStatus: e(".os-header__title"),
                paymentMethod: e(".payment-method-list__item__info")
            }
        },
        c = () => {
            clearInterval(r), i.mainHeader.innerText = o, i.orderConfirmed.style.display = "block", i.orderConfirmedDescription && (i.orderConfirmedDescription.style.display = "block"), i.continueButton.style.visibility = "visible", i.checkMarkIcon.style.visibility = "visible", d.style.display = "none"
        };
    window.setOrderAsPaid = c, window.openNodeShopify = function e(a) {
        if (s(), "Order canceled" === i.orderStatus.innerText) return;
        const l = i.paymentMethod;
        if (null === l) return void setTimeout(() => {
            e(a)
        }, 10);
        if (-1 === l.innerText.toLowerCase().indexOf("bitcoin")) return;
        o = i.mainHeader.innerText, i.mainHeader.innerText = "Review and pay!", i.continueButton.style.visibility = "hidden", i.checkMarkIcon.style.visibility = "hidden", i.orderConfirmed.style.display = "none", i.orderConfirmedDescription && (i.orderConfirmedDescription.style.display = "none"), d = document.createElement("div");
        const p = window.location.pathname.split("/")[3],
            u = window.location.pathname.split("/")[2],
            y = `${t}/shopify/create?token=${a.token}&checkout=${p}&type=${u}`;
        d.innerHTML = `\n    <a href="${y}" target="_blank">\n      <img src="https://app.opennode.co/payment-button.svg"/>\n    </a>\n  `, n(d, i.orderConfirmed);
        const m = `${t}/shopify/status?token=${a.token}&checkout=${p}&type=${u}`;
        r = setInterval(() => {
            fetch(m).then(e => e.json()).then(e => {
                ["paid", "processing"].includes(e.data.status) && c()
            }).catch(function(e) {})
        }, 1e3)
    }
}();
```

**Comment by ruigomeseu** [comment]
Let me know if you need any help with the code I've written, happy to help :)

**Comment by Kukks** [comment]
Thanks for the offer! Could you perhaps walk us through your process briefly to see if we understood it? :)

**Comment by ruigomeseu** [comment]
The trick is that Shopify allows merchants to inject scripts into their thank you page, so we use this to hijack the page and inject our payment button. We also change the copy so it's clear to the customer that they still have to pay.

We also created a Shopify app that our merchants install so we can access the order details and mark orders as paid automatically.

This has a lot of drawbacks but it's the best you can do without Shopify's permission to access their payments SDK:

Orders are not correctly marked as abandoned checkouts, you can't add the bitcoin logo to the payment selection, emails go out before users actually pay, but it works ¯\_(ツ)_/¯

**Comment by djseeds** [comment]
I adapted / deobfuscated the open node code above to integrate with BTCPay Server. The code is available here for anyone interested: https://github.com/djseeds/btcpay-shopify-checkout/blob/master/btcpay-shopify-checkout.js 
Would it make sense for BTCPay Server to host a script like this, similar to how the modal works?

**Comment by Kukks** [comment]
definitely makes sense, cool! There is still the backend code on the btcpay side of course

**Comment by djseeds** [comment]
Yeah it would be nice for btcpay to mark orders as complete/cancelled in shopify -- currently this just sets the order ID in btcpay and we manually mark the shopify order as complete/cancelled by looking at the corresponding btcpay invoice.

**Comment by pavlenex** [comment]
This question gets asked once every few days, so just to post an update here for everyone.
Native Shopify integration is not possible. BTCPay as a non-central entity can't "apply" or provide "fees" that Shopify requires from payment processors. 

A while ago their dev team indeed poked around with BTCPay and they even had a hackaton on it, but our API was confusing so they never managed to get it work. From what I understood their idea was for them to be payment processor and/or allow others to plug their BTCPay's. This won't happen any time soon, if it ever does.

A workaround to make Shopify work with BTCPay is to use script provided by @djseeds. Bear in mind it's not a native integration, it's a hackish workaround, but it works. 

If you need a dev to integrate this for you, @djseeds has on-boarded a few stores for now. 

On our end, it would be great if we can either document the process and do changes that would make this integration feel more native as mentioned [here](https://github.com/btcpayserver/btcpayserver/issues/36#issuecomment-489869204).

**Comment by zachherbert** [comment]
Checking in to see if there is any guide or further documentation on the process of implementing @djseeds script. We are going to be implementing this workaround into our Shopify store in the next ~30 days.

**Comment by djseeds** [comment]
@zachherbert 
Maybe I can write up a more formal guide sometime, but basically these are the steps:
1. In your BTCPayServer store you need to check "Allow anyone to create invoice"
2. In Shopify Settings > Payment Providers > Manual Payment Methods add one which contains "Bitcoin"
3. In Shopify Settings > Checkout > Additional Scripts input the following script, with the details from your BTCPayServer instead of the placeholder values.

```
<script>
	const btcPayServerUrl = 'https://your-btcpay-server-url:port';
	const storeId = 'your-btcpayserver-store-id';
</script>
<script src="https://your-btcpay-server-url:port/modal/btcpay.js"></script> 
<script src="https://djseeds.github.io/btcpay-browser-client/btcpay-browser-client.js"></script>
<script src="https://djseeds.github.io/btcpay-shopify-checkout/btcpay-shopify-checkout.js"></script>
```

And that’s it! It's a bit of a hack, but it's been working so far for TFTC’s store -- you will just have to crosscheck payments in BTCPayServer based on the order id in Shopify, since it won't automatically mark orders as complete in Shopify.

By default the script assumes your Shopify store's currency is USD -- if that's not the case you'll have to set the following variables as well, so that the script can scrape the correct value from the Shopify page and create the invoice in BTCPayServer with the correct currency.
```
const currencySymbol = '£';
const currency='GBP';
```

**Comment by pavlenex** [comment]
@djseeds This is great. Would be awesome if we can have a more formal guide on how people can set it up, but more importantly we should see how we can make the intergration smoother and more automatic on our end. I remember me talking with @rockstardev how we can improve this, would be cool to team and see how we can improve it.

**Comment by djseeds** [comment]
Thanks @pavlenex -- this would be great if we can integrate this on the BTCPay side.

I think the first improvement would be simply serving a similar script from BTCPayServer, similar to how the modal script works. That way users wouldn't be taking additional dependency on my github account / github pages.

After that, the integration would be much improved by enabling BTCPayServer to call the Shopify API to automatically mark invoices as complete

**Comment by zachherbert** [comment]
Thanks so much @djseeds we will attempt to follow these instructions over the next few weeks to get everything configured. I think we will have the time to write a guide based on our experience. Hopefully you and TFTC can help review and contribute. 

@pavlenex a deeper integration with Shopify would be helpful. I'm not sure we will have the dev bandwidth to work on this, but we may be able to help with a small amount of funding in the near future if it would move the needle.
