### ISSUE TITLE
Store configuration 

### ISSUE THREAD

**Issue by espriweb** [btcpayserver/btcpayserver#362]
How can I configure the store to send bitcoins to a "31zbT6rbHL9HEhT6gDAvzHXKtAdSHNYxf6" type address without using xpub?

**Comment by Kukks** [comment]
You can't. Btcpay needs xpub to generate an address per invoice otherwise we wouldn't be able to tell which payment is for which invoice.

**Comment by espriweb** [comment]
Ok, thanks.
