### ISSUE TITLE
Small workflow/ visual bug in creating a Crowdfund app

### ISSUE THREAD

**Issue by Bangalisch** [btcpayserver/btcpayserver#3625]
Yo,

Just created a couple of Crowdfund apps. 
Was playing around with the reset at some point and found a small "bug". 

In the Topic Goal 
Set all fields except dates cuz it doesn't tell you to. 
Select reset goal to Day, still date doesn't tell you it's mandatory. 

Fill up the rest of the crowdfunding page. 
Save and now it tells you you forgot to put a start date.
Again where it earlier did not tell you it's mandatory. 
It might need a * just like the Description fields or display field once you set it to reset differently then Never.

See screen shots for example ; 
![screenshot 7](https://user-images.githubusercontent.com/102448109/162595798-bd310322-2baf-4762-84a7-5466206622c5.jpg)

![screenshot 8](https://user-images.githubusercontent.com/102448109/162595801-983111b7-e696-47dc-9476-0abcd0a16f8d.jpg)

Cheers

**Comment by bolatovumar** [comment]
It's a bit tricky here as the rules of what's required or not change depending what user selected in the UI and validation happens on the back end. Unless we expose the back end validation rules to the front end somehow it will not work.

**Comment by pavlenex** [comment]
@bolatovumar so should we close this one or is there a solution you think is viable?

**Comment by bolatovumar** [comment]
@pavlenex I addressed these issues in the above PR (#3708).
