### ISSUE TITLE
Implement the new/latest Currency selector on the Pay Button

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#3630]
This may have been intentional, but currently the new Currency selector is not implemented on the Pay Button view:

<img width="908" alt="Screen Shot 2022-04-12 at 4 00 55 PM" src="https://user-images.githubusercontent.com/6250771/163068571-89af90da-03ef-4175-95ca-b75bdd6a5c7d.png">

**Comment by dafunction** [comment]
@dstrukt just to make sure i'm understanding, you're talking about the dropdown selector, yes?

something like this:
![2022-04-14 18-03-48 2022-04-14 18_04_33](https://user-images.githubusercontent.com/18316226/163491275-0c3c84fb-fbef-4a29-a02a-e2d35bbcd989.gif)

**Comment by NicolasDorier** [comment]
His PR should have fixed it

**Comment by dstrukt** [comment]
@dafunction This is just a visual inconsistency.

Notice how the carrot for the currency selector only appears on hover/select, unlike the Select input right below it, always present, same icon/glyph asset .. the two should, ideally, be the same.

Will check out the PR though.
