### ISSUE TITLE
LNURL does not pass description to LN invoice

### ISSUE THREAD

**Issue by iBobik** [btcpayserver/btcpayserver#3634]
**Describe the bug**
When paying by LN invoice it will correctly pass description to the wallet, but when used LNURL method the description was not passed.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Configure LN store with LNURL enabled and description configured.
2. Create some invoice, select Bitcoin (Lightning) (Sats) and pay
3. You will see description in a wallet correctly.
4. Create some invoice, select Bitcoin (Lightning LNURL) (Sats) and pay5. 
5. You will see invoice ID (22 alpha characters) in a description field in a wallet.

**Expected behavior**

Both LN methods will consistently pass description to the LN invoice, so customer will know what he paid.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    v1.4.9.0
- Deployment Method:        Docker

**Comment by pavlenex** [comment]
I tried to replicate this and I couldn't the LNURL comment is passed in the invoice. I tried with Phoenix.
![Screenshot 2022-04-20 at 10 55 51](https://user-images.githubusercontent.com/36959754/164191701-64d72545-f62e-45c4-b1d5-1a97b08087c4.png)

**Comment by iBobik** [comment]
@Pavlenex This is different comment. My issue is about description passed from BTCPay to the wallet.

Honza Pobořil

**Comment by pavlenex** [comment]
Our internal wallet doesn't support lighting. Are you referring to lnbank or one of the external services? In any case neither is related to btcpay directly.

**Comment by iBobik** [comment]
I use internal LND node. BTCPay creates that invoices and in that creation API call can be passed some metadata, cannot? What other reason is for that field?
<img width="797" alt="Snímek obrazovky 2022-04-21 v 0 46 00" src="https://user-images.githubusercontent.com/614232/164337206-1c46ad16-1166-4db8-bee7-5a78cae7a7c6.png">

**Comment by pavlenex** [comment]
Okay, I see what you mean, I think that the `description` works for BOLT11 only cc @Kukks should be able to tell.
