### ISSUE TITLE
Introduce Transifex support

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#364]
Thanks to @britttttk 's insane amount of translation work, we need the locales system to scale a bit better. Someone mentioned Transifex( btc uses it) and we checked it out. It is free to OSS projects so that's good.  

Right now we load locale files from a .js and the only way that Transifex can load them is through Requirejs so I propose we change our locale loading to be through key-value json files. We can fetch them on demand in the ui when a suer changes language. :)

I've applied for an OSS license on Transifex and added in the first language file(english) to it at
https://www.transifex.com/btcpayserver-1/public/

**Comment by Kukks** [comment]
Just a quick update here: 
We switched over to @britttttk 's Transifex account as she had the better name(without the `-1` suffix) :P

Did you apply for an OSS license for it @britttttk?

**Comment by britttttk** [comment]
@Kukks On transifex dashboard it shows our OSS link under settings and I believe it's been verified but I sent a message to Transifex just now to verify this for us.

[https://www.transifex.com/btcpayserver/btcpayserver/](https://www.transifex.com/btcpayserver/btcpayserver/)

**Comment by britttttk** [comment]
@Kukks received confirmation from Transifex support the (Transifex/BTCpayserver/BTCpayserver) OSS license is verified and approved for use.

**Comment by NicolasDorier** [comment]
that's super cool! Now only need https://github.com/btcpayserver/btcpayserver/issues/386 and we are good.
