### ISSUE TITLE
Server URL

### ISSUE THREAD

**Issue by Caretuition** [btcpayserver/btcpayserver#3649]
Hopefully a simple one - where do I find my server URL when setting up the WordPress plugin please?

**Comment by pavlenex** [comment]
You need to deploy a server or pick a third party host that hosts it for you.

Essential reading to understand how btcpay works:
- https://docs.btcpayserver.org/Deployment/
- https://docs.btcpayserver.org/Deployment/ThirdPartyHosting/
- List of third party hosts if you decide to use them https://directory.btcpayserver.org/filter/hosts

For self hosting try:
- http://voltage.cloud
- lunannode.com https://youtu.be/oce_fvRdLLY
- deploy it on any VPS which meets[ minimum] requirements (https://docs.btcpayserver.org/FAQ/Deployment/#what-are-the-minimal-requirements-for-btcpay) https://docs.btcpayserver.org/Docker/#full-installation-for-technical-users
