### ISSUE TITLE
Liquid (LBTC) stuck in sync loop on Lunanode one-click installation

### ISSUE THREAD

**Issue by john-magill** [btcpayserver/btcpayserver#3650]
**Describe the bug**
Liquid initial block download fails at approx. 30% every time, and the node restarts. I had initially increased the swap size to 4GB (based on https://github.com/btcpayserver/btcpayserver/issues/2216#issuecomment-854272393), which allowed the node to get a bit further, but now it just fails at ~30%.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Follow the one-click installation at [lunanode](https://launchbtcpay.lunanode.com/)

**Expected behavior**
Liquid blockchain should sync to the dedicated 60GB Volume on Lunanode VM.

**Screenshots**
<img width="524" alt="lbtc-sync-loop_1" src="https://user-images.githubusercontent.com/12265052/163852483-e543cd10-5da7-423d-840b-9bcefea8fc31.png">
<img width="527" alt="lbtc-sync-loop_2" src="https://user-images.githubusercontent.com/12265052/163852493-5620c2d1-a986-443b-81fe-a57001b21dfd.png">

**Your BTCPay Environment:**
- BTCPay Server Version:    1.4.9.0 (Altcoins)
- Deployment Method:        Lunanode one-click installation
- Browser:                  Firefox
- Lunanode: VM: m.4, OS: ubuntu20.04-btcpay

**Logs (if applicable)**
The logs don't seem to show anything other than: 
```
2022-04-18 18:01:26.474 +00:00 [ERR] LBTC: NBXplorer error `Response status code does not indicate success: 500 (Internal Server Error).`
```

**Additional context**

Does Liquid need more resources to do an IBD? 
Should the one-click be changed from m.4 to m.8?
Anything I can do to get this synced?

**Comment by john-magill** [comment]
For anyone else interested, Liquid really needs an m.16 to do an IBD. It won't work on an m.4 VM.
The problem is, you cannot easily downgrade the VM on Lunanode, and an m.16 is very expensive to run once the IBDs are complete.
I'm having issues getting things back up and running on a new m.4, but I'll report back once I find a solution.

**Comment by pavlenex** [comment]
Closing since this one isn't really related to BTCPay. Thanks for reporting back though.
