### ISSUE TITLE
Shopify identifier - Buyer information missing

### ISSUE THREAD

**Issue by Danielalui** [btcpayserver/btcpayserver#3652]
I use BTC Pay Server integration with Shopify and I am not able to identify my customers' orders. 

**To Reproduce the bug**
![screenshot-btcpay btc-boutique com-2022 04 19-11_00_55](https://user-images.githubusercontent.com/59447274/163969350-f3997679-8151-484f-91eb-8043e50dd3d9.png)

1. Go to Invoices
2. Click on Details
3. Buyer information is empty
4.  Shopify order ID is not correct (eg.  shopify-4747043373278)

**Expected behavior**
Buyer information is filled in. 
Shopify Order ID is correct (eg. shopify-#1005)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:  1.9.0
- Deployment Method:   Third-Party-host
- Browser:  Firefox

**Comment by pavlenex** [comment]
Duplicate #3636
