### ISSUE TITLE
Windows Server SSH update

### ISSUE THREAD

**Issue by espriweb** [btcpayserver/btcpayserver#367]
Hello,

I have a btcpay installation on a Windows Server 2016 I have enabled the SSH on the following path "C: \ Btcpayserver \" where there are two main folders and run.sp1 files etc.

I did the update through the "Maintenance" menu, I entered the username and password of the SSH I get a green notification bar "The server might restart soon if an update is available ...", if I restart the server the version remains unchanged (v1.0.2.113).

Question does not work something? I have the current version is the last (v1.0.2.113)?

Thanks in advance for your patience

**Comment by bitcoinshirt** [comment]
1. If there's no new version nothing will happen.
2. The new version has been released a few moments ago [v1.0.3.0](https://github.com/btcpayserver/btcpayserver/releases).
3. Maybe you did not set your SSH keys correctly, [see here](https://github.com/btcpayserver/btcpayserver-doc/blob/master/FAQ.md#warning-the-btcpay_sshkeyfile-variable-is-not-set-when-running-docker).
4. You can always [update manually through ssh](https://github.com/btcpayserver/btcpayserver-doc/blob/master/FAQ.md#how-to-update-btcpay-server)

**Comment by espriweb** [comment]
Ok thanks!
