### ISSUE TITLE
Pull Payment automatic approval table display error

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#3693]
Despite checking "automatically approve", it's displayed incorrectly in the table. 

Repro:

<img width="1139" alt="Screen Shot 2022-04-29 at 4 17 49 PM" src="https://user-images.githubusercontent.com/6250771/166079988-6a16eab0-3361-4936-a5ec-b262dc0679e4.png">
<img width="1110" alt="Screen Shot 2022-04-29 at 4 18 00 PM" src="https://user-images.githubusercontent.com/6250771/166079990-34b53cb7-4a26-4d25-a40a-c872e3fa2c4c.png">

**Comment by pavlenex** [comment]
Did you have payout processors configured? I wonder if this is tied to that? cc @Kukks

**Comment by dstrukt** [comment]
Yes I did, just the default 60min configuration.

**Comment by bolatovumar** [comment]
Looks like whoever implemented this just forgot to set the flag for display. Simple fix in #3738.
