### ISSUE TITLE
`Pay Button` to become a system plugin

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#3701]
As mentioned in the Mattermost, would be a nice improvement and consolidation to clean up the "Payments" section.

- [ ] Pay Button plug-in
- [ ] Move current position in left sidebar

If this is not feasible, or there's something I'm overlooking, please feel free to close the issue.

**Comment by pavlenex** [comment]
I agree with this, but would be worth discussing if any technical complexities may occur, or even worse back-compatability invaded as a result of the migration. @Kukks anything we should pay attention to if we decide to do this?

**Comment by Kukks** [comment]
We can do this, but it will have to live as a system plugin as too many depend on it to simply remove..

**Comment by pavlenex** [comment]
I'm absolutely fine at it being a system plugin, as long as it's a plugin.

**Comment by cassa72** [comment]
Hmm
