### ISSUE TITLE
Invoice `Order ID` table row broken line 

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#3714]
As originally reported by @pavlenex on Mattermost. Creating this ticket as a reminder for myself - I haven't had a moment to submit a fix yet, and I don't want it to get buried & forgotten.

![image](https://user-images.githubusercontent.com/6250771/166886296-a413005e-808b-48f0-9a56-8e6837af999f.png)

**Comment by dstrukt** [comment]
Trying to replicate to fix, but I'm unable .. @pavlenex not certain how to reproduce, anything specific you did?

<img width="1633" alt="Screen Shot 2022-05-05 at 2 44 23 AM" src="https://user-images.githubusercontent.com/6250771/166900377-049bc523-4217-4e52-bfb2-9a199246883e.png">

**Comment by bolatovumar** [comment]
@dstrukt you need to have an invoice that doesn't have a redirect URL associated with it to be able to repro. I fixed it in #3765.

**Comment by dstrukt** [comment]
Awesome, nice catch!
