### ISSUE TITLE
Lightning address with http 301 magic

### ISSUE THREAD

**Issue by Sjors** [btcpayserver/btcpayserver#3722]
Here's what I'd like to do:

Run a BTC Pay server on `pay.example.com`, but use `me@example.com` as the lightning address. Why? Because it looks nicer than `me@pay.example.com`.

I was thinking this should be a matter of adding an http 301 redirect for `example.com/.wellknown/whatever` to `pay.example.com`. However in the Lightning Address plugin, I would need the option to override the domain name.

(I could also set up the BTC Pay server at `example.com/pay`, but a subdomain seems a bit more practical for every use case except a vanity lightning address)

**Comment by dennisreimann** [comment]
That's a very good point, I want to do that as well, let's get it going!

**Comment by dennisreimann** [comment]
I can confirm it works with a simple redirect, the Lightning Address code doesn't need a change.

**Comment by Sjors** [comment]
Very cool, I'll try to replicate this soon(tm) and will close. Maybe we can document the process somewhere? I could imagine other people would love to use their regular email as their Lightning Address, without having to run BTCPay on the bare domain.

**Comment by dennisreimann** [comment]
Yes, I'll add an FAQ item to the docs – thanks for the suggestion!
