### ISSUE TITLE
ERR_RATE_UNAVAILABLE - BTCPay Doesn't Seem To Be Able to Get Rates From ANY Exchange

### ISSUE THREAD

**Issue by jonathanalevi** [btcpayserver/btcpayserver#3733]
Hi All
Running BTCPAY on Umbrel through a reverse proxy. I've had it working before in the past, however, for some reason, it now isn't able to get rates from anywhere, which is causing the checkout to fail completely. 

<img width="867" alt="image" src="https://user-images.githubusercontent.com/1540530/167823055-30e3621b-ab8a-4eac-a8a3-33ea8f6ef54b.png">

I've tried:

- Switching to different exchanges
- Trying different rates
- Waiting
- Restarting the entire Umbrel server
- Bypassing traffic directly (there's PiHole on this Umbrel)
- Pinging the different exchanges to make sure I can send and get info to those URLS (I can)
- Pulling my hair out

Nothing seems to help. Any ideas? 

Thanks!

**Comment by pavlenex** [comment]
You tried coingecko, our default?

**Comment by jonathanalevi** [comment]
Yes of course :)

**Comment by jonathanalevi** [comment]
I've tried setting a fixed DNS, among other things, still can't get this to work

**Comment by pavlenex** [comment]
This has to be something within your deployment that's causing it. @NicolasDorier @Kukks  any idea why a reverse proxy on umbrel may cause problems with contacting rate provider such as coingecko?

**Comment by Kukks** [comment]
It shouldn't as the reverse proxy won't touch outgoing requests. Ensure that the btcpay container is able to connect to clearnet
