### ISSUE TITLE
Azure deploy

### ISSUE THREAD

**Issue by devfxplayer** [btcpayserver/btcpayserver#3740]
I deployed the app using the template from azure and I cannot get it started.
https://xvbtcpayserver.westeurope.cloudapp.azure.com/
Is it possible to log in remotely to VM to see what is happening?

**Comment by pavlenex** [comment]
Is this still an issue? You should be able to SSH into a VM and then troubleshoot it https://docs.btcpayserver.org/Troubleshooting/#troubleshooting-an-issue-in-btcpay-server

TBH, Azure is overpriced and there are easier ways to deploy btcpay https://docs.btcpayserver.org/Deployment/webdeployment/
