### ISSUE TITLE
The sounds in the Crowdfund App have outdated base URLs

### ISSUE THREAD

**Issue by Perlover** [btcpayserver/btcpayserver#3745]
**Describe the bug**

The sounds in the Crowdfund App have outdated base URLs:

Your examples are:

```
//github.com/ClaudiuHKS/AdvancedQuakeSounds/raw/master/sound/QuakeSounds/dominating.wav
//github.com/ClaudiuHKS/AdvancedQuakeSounds/raw/master/sound/QuakeSounds/doublekill.wav
//github.com/ClaudiuHKS/AdvancedQuakeSounds/raw/master/sound/QuakeSounds/doublekill2.wav
//github.com/ClaudiuHKS/AdvancedQuakeSounds/raw/master/sound/QuakeSounds/eagleeye.wav
```

But original github now has other base URL: `https://github.com/ClaudiuHKS/AdvancedQuakeSounds/tree/master/sound/AQS`

So to be need change in sources a baseurl from from `//github.com/ClaudiuHKS/AdvancedQuakeSounds/raw/master/sound/QuakeSounds/` to `//github.com/ClaudiuHKS/AdvancedQuakeSounds/raw/master/sound/AQS/`

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to Apps -&gt; App name -&gt; Sound -&gt; Sounds to play when a payment is made. One sound per line
2. To see there `textarea` tag's value

**Comment by pavlenex** [comment]
Good catch.
