### ISSUE TITLE
Can't find PGP key of recent releases

### ISSUE THREAD

**Issue by erikarvstedt** [btcpayserver/btcpayserver#3751]
The recent releases were signed by @Kukks with key id `8E5530D9D1C93097`, but the full pubkey isn't available on the internet.
@Kukks, can you please publish your pubkey?
-  Send it to a keyserver
    ```
    gpg --send-keys --keyserver hkps://keyserver.ubuntu.com 8E5530D9D1C93097
    ```
- Add it to https://www.kukks.org

**Comment by Kukks** [comment]
Is https://keybase.io/kukks/pgp_keys.asc sufficient?

**Comment by erikarvstedt** [comment]
Yes, thank you.
