### ISSUE TITLE
[Feature] Add new Chilean exchange BUDA

### ISSUE THREAD

**Issue by Goro2030** [btcpayserver/btcpayserver#3766]
**Describe the feature**
Addition of Buda.com ( the largest Chilean Exchange ) to the Rates

**Changes needed**
In the source file "RateProviderFactory.cs":

`yield return new AvailableRateProvider("buda.com", "Buda.Com", "https://www.buda.com/api/v2/markets/btc-clp/ticker");
`

Also, an addition to the Tests is needed:
[BTCPayServer.Tests/ThirdPartyTests.cs](https://github.com/btcpayserver/btcpayserver/blob/722c39a6ffe6efa173c79efeff82428f21933185/BTCPayServer.Tests/ThirdPartyTests.cs)

Buda's API documentation is here: `https://api.buda.com/en/#introduction`

**Comment by Goro2030** [comment]
> **Describe the feature** Addition of Buda.com ( the largest Chilean Exchange ) to the Rates
> 
> **Changes needed** In the source file "RateProviderFactory.cs":
> 
> `yield return new AvailableRateProvider("buda.com", "Buda.Com", "https://www.buda.com/api/v2/markets/btc-clp/ticker"); `
> 
> Also, an addition to the Tests is needed: [BTCPayServer.Tests/ThirdPartyTests.cs](https://github.com/btcpayserver/btcpayserver/blob/722c39a6ffe6efa173c79efeff82428f21933185/BTCPayServer.Tests/ThirdPartyTests.cs)
> 
> Buda's API documentation is here: `https://api.buda.com/en/#introduction`

@NicolasDorier  this is the Chilean exchange we discussed adding, besides Cryptomarket.

**Comment by pavlenex** [comment]
@NicolasDorier can we add this, seems like @Goro2030 and people in Chile really need it.

**Comment by Goro2030** [comment]
> @NicolasDorier can we add this, seems like @Goro2030 and people in Chile really need it.

Thanks @pavlenex ! And yes, we do need BUDA to be incorporated to the list of exchanges :)

**Comment by Goro2030** [comment]
Thanks @pavlenex  and @Kukks for doing this! When will this be pulled into a new released version?

**Comment by pavlenex** [comment]
3 weeks approx.
