### ISSUE TITLE
Missing Shopify Order IDs

### ISSUE THREAD

**Issue by BenGWeeks** [btcpayserver/btcpayserver#3769]
**Describe the bug**

Since 11/05/2022 (presumably around the time of us upgrading to 1.5.2) we no longer see the Shopify Order ID.

**To Reproduce the bug**

Steps to reproduce the reported bug:
1. Go to 'Invoices'
2. See missing entries (we can see matching amounts in Shopify)

**Expected behaviour**

The Shopify Order Id should be there.

NB This may be related to https://github.com/btcpayserver/btcpayserver/pull/3718 or https://github.com/btcpayserver/btcpayserver/issues/3636

![image](https://user-images.githubusercontent.com/5950171/169687939-3582a98f-b133-4a93-8a68-5ae847035ab9.png)

**Your BTCPay Environment:**

- BTCPay Server Version: 1.5.2.0
- Deployment Method: Umbrel update (0.4.18)
- Browser: Microsoft Edge Version 101.0.1210.47 (Official build) (64-bit)

**Comment by NicolasDorier** [comment]
seems like something broken in the last update @Kukks

**Comment by NicolasDorier** [comment]
Probably caused by https://github.com/btcpayserver/btcpayserver/commit/21bd35accdab9768f9f43312ac4c82bccdbaee0d

@BenGWeeks when you go to invoice detail, do you see the id somewhere in the page?

**Comment by pavlenex** [comment]
Also if you search for shopify ID in the invoice search it should filter that invoice, nevertheless we should also show it in the invoice list.

**Comment by NicolasDorier** [comment]
@BenGWeeks can you give a try. Sadly we can't automatically test shopify stuff... :/
