### ISSUE TITLE
Add BTCPay WooCommerce plugin into WordPress Repository

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#377]
I think this should be one of the top priorities. I know there has been some work. I would be happy to write docs and format the text for SEO.
We really need to add this ASAP, it will attract tons of new WordPress users, we have a bunch of tutorials and docs to educate them properly, we just need someone to re-write BitPay's plugin and add it to the WP repo.

Anyone with an experience that can do that properly?

**Comment by astupidmoose** [comment]
Why do we need to re-write it? Our current plugin works so what is stopping it as is right now. What is actually needed to make this happen?

**Comment by bitcoinshirt** [comment]
By re-writing I meant some minor things that haven't passed the QC earlier.

**Comment by Eskyee** [comment]
ok this is the ref from our past convo's... about the problem why wordpress dont accept our plugin. @astupidmoose @bitcoinshirt 
https://github.com/btcpayserver/woocommerce-plugin/issues/7

**Comment by Eskyee** [comment]
this was the main points... they wanted us to change.
Remove/refactor update checker to use their preferred way (no phone home or to Github allowed)
Sanitize direct handling of possible insecure variables returned by API via $_POST

**Comment by Eskyee** [comment]
So we just need a PHP don to come clean up the code to pass the QC.

**Comment by Eskyee** [comment]
our contact at Wordpress plugins@wordpress.org Mika Epstein

Thank you for uploading BTCPay for WooCommerce to the WordPress Plugin Directory. We will review your submission as soon as possible and send you a follow up email with the results.

Your plugin has been given the initial slug of btcpay-for-woocommerce, however this is subject to change based on the results of your review.

If there is a problem with this submission, such as an incorrect display name or slug, please reply to this email and let us know. In most cases, we can correct errors as long as the plugin has not yet been approved. Please do not submit your plugin multiple times in an attempt to correct the issue, just email us.

Remember to read the developer guidelines: https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/ 

Please make sure to follow our official blog: https://make.wordpress.org/plugins/

--
The WordPress Plugin Directory Team
https://make.wordpress.org/plugins

**Comment by Kukks** [comment]
Can you post the followup here @Eskyee
