### ISSUE TITLE
Hide dashboard balance / hide sensitive data (lurking wife mode)

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3779]
Currently, our dashboard flashes your balance. It's a good privacy practice to allow users to optionally hide the wallet balance. I think similar has to be applied to the charts in the dashboard.

This may relate to #3752, as we can allow toogle between a currency, btc and hide balance.

Bitcoin Design Guide has some good practice on how to hide the balance  https://bitcoin.design/guide/daily-spending-wallet/privacy/#quickly-hiding-balances

**Comment by dstrukt** [comment]
Definitely a good privacy feature to have.

Some interesting solutions, but some are a bit overkill for our purposes imo.

My vote goes for the original discussed implementation: 

Simple tap/hover icon to show / hide, with the setting being saved for the account in the user's localStorage/equivalent, even with the different browser/device trade-off, it's a clear and simple UX, and easy enough to invoke on different/multiple machines as needed .. @dennisreimann any technical considerations missing?

OR 

Possibly a global config. but this would be a bit nested, and until we flatten and consolidate more of the settings views, it has the potential to getting buried.

**Comment by bolatovumar** [comment]
> Simple tap/hover icon to show / hide, with the setting being saved for the account in the user's localStorage/equivalent, even with the different browser/device trade-off

Would the default be to hide the balance or show it? I assume show it and if user chooses to hide, it stays that way until they unhide it?

**Comment by dennisreimann** [comment]
Yes, we have a user preferences cookie and should store that setting the same way we store the light/dark mode setting for instance.

**Comment by pavlenex** [comment]
I think one way to approach this is to add eye icon next to the currency to indicate that it should be hidden. Should be [following BDG](https://bitcoin.design/guide/daily-spending-wallet/privacy/#quickly-hiding-balances) on how information is presented.
![Screenshot 2022-07-05 at 18 11 09](https://user-images.githubusercontent.com/36959754/177371506-70556c1a-ce20-4ff8-a32c-d46f4841f688.png)

**Comment by pavlenex** [comment]
You're right if we add it in the tile, it would imply it is only for a single tile, though it should be for the entire dashboard.

**Comment by dennisreimann** [comment]
Decision in the design meeting was to put it into the Account menu (e.g. next to the theme toggle), so that we can make it a more general setting and later on also introduce it on other views like the invoices or transactions lists.

Still to be defined:

- [ ] How do we want to call it? "Hide sensitive info"?
- [ ] How to obfuscate the data? Blur, ***, …?

**Comment by dstrukt** [comment]
- copy suggestion `Private Mode`?
- I like the idea of it being next to the Dark/Light toggle, and similar functionality ON/OFF
- I think I like ***** more, but could be persuaded to blur

**Comment by dennisreimann** [comment]
Goind for something like this then ….

![private-mode](https://user-images.githubusercontent.com/886/236412759-f3877079-596a-44b2-8f25-3dbfaabaac73.png)

**Comment by pavlenex** [comment]
Concept ACK. Good work.

**Comment by dennisreimann** [comment]
I agree that "Hide sensitive info/data" is better terminology.

**Comment by pavlenex** [comment]
I think Bitcoin Design Guide proposes `Hide Sensitive Info`.

**Comment by dstrukt** [comment]
Fair points, still like the succinctness of `Private Mode`, but realize the potential implications, but also like `Hide Sensitive Info`, might be a little tight with the toggle, so we may want to extend the width of the modal 20-40px?

Otherwise, think this looks great @dennisreimann ... will do a proper review asap!
