### ISSUE TITLE
Zero Value Invoices

### ISSUE THREAD

**Issue by damanic** [btcpayserver/btcpayserver#3782]
I have a situation where many Invoices are being created from an unknown source.  

A payment button for the store exists online, so I suspect this is the channel being used to create the invoices.  

The value amount on these invoices is always 0.00000000 ₿  .

I am seeing 100s of on-chain addresses being laid to waste every week which makes for a rapidly growing gap-limit.

This issue could be mitigated with:

1) The ability to block ZERO VALUE invoices from being created.

2) Some additional data on invoice records that expose the IP/source of the created an invoice.

**Comment by pavlenex** [comment]
Hey @damanic thanks for filing an issue. Can you elaborate on what are you using, is it a e-commerce integration, point of sale app or a, or btcpay pay button? 

@NicolasDorier this seems like a good use-case for spam prevention you wanted to implement?

**Comment by damanic** [comment]
@pavlenex 
The zero value invoices are being created on a store that uses the btcpay button exclusively .

**Comment by bolatovumar** [comment]
I see something similar on my instance of BTCPay. It doesn't really matter in my case, it's just a bit annoying. But in cases where a store might be receiving more traffic it can be used to spam the BTCPay instance easily.

Also, this issue seems related to this: https://github.com/btcpayserver/btcpayserver/issues/3190

**Comment by NicolasDorier** [comment]
https://github.com/btcpayserver/btcpayserver/issues/3190 is unrelated and unsolvable.

What we want is spam protection on public, unauthenticated endpoints. #3190 wants spam limit on authenticated endpoint. (which doesn't make sense.)
