### ISSUE TITLE
Archived invoices are visible on the dashboard

### ISSUE THREAD

**Issue by ishristov** [btcpayserver/btcpayserver#3783]
**Describe the bug**
Archived invoices are visible on the dashboard.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to the invoices page and archive one of the last 2-3 invoices.
2. The invoice will disappear from the invoices page.
3. Go the dashboard.
4. The archived invoice is in the "Recent Invoices" section.

**Expected behavior**
Archived invoices are not present in the "Recent invoices" on the dashboard.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.5.3.0

**Comment by pavlenex** [comment]
Thanks for reporting this. I was able to reproduce this, and it doesn't seem like this is a desired behaviour. 
@dennisreimann @bolatovumar could any of you guys look into this and see why `archived` invoices are shown on the dashboard, but not on the invoices list ,it seems like we can improve this.
