### ISSUE TITLE
Improve security.md and better document our response processes.

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3787]
Filing this issue as to-do to myself, as I think we can do a bit better job documenting our vulnerability response processes.

We should put a bit more context on how we handle security and reporting.
It's been recommended that we follow the following runbooks:

- https://github.com/google/oss-vulnerability-guide/blob/main/runbook.md
- https://github.com/google/oss-vulnerability-guide/blob/main/guide.md#the-vulnerability-response-process
- https://github.com/google/oss-vulnerability-guide/blob/main/guide.md#if-you-are-using-github-2

- [ ] Re-write the [security.md ](https://github.com/btcpayserver/btcpayserver/blob/master/SECURITY.md)page with proper introduction on why reporting sec vuln is important
- [ ] Add vulnerability response process and steps we take
- [ ] Discuss about how to handle vulnerability patching, privately via GitHub advisory vs publicaly, a resource [here](https://github.com/google/oss-vulnerability-guide/blob/main/guide.md#if-you-are-using-github-2)
- [ ] Define bug bounties and add https://huntr.dev as a resource

**Comment by Zaxounette** [comment]
Just commenting to align everybody that's assigned to this issue.
I'm taking it on.

Just FYI, won't be done for 1.8.0 though, that's 100% certain.

**Comment by pavlenex** [comment]
@Zaxounette We release 1.8.0 on Thursday, seems a bit of a tight time-frame, but we can do this for 1.8.x release? Of course if you have it ready, we can include it for 1.8.0, but I don't think it's essential to be added in a major release, since it's just process documentation end-users probably don't care much about, but us and security researchers do.

**Comment by Zaxounette** [comment]
Sorry, didn't get the mention for this.
I should have something to push for review not this monday (27/02), but the next (06/03) TOPS.

**Comment by Zaxounette** [comment]
Sorry for the delay!

PR up for the reporting process and refactor of security.md: https://github.com/btcpayserver/btcpayserver/pull/4815

Regarding completing this issue entirely, on my TODO list:
* Add a fully fledged vulnerability response and management process to our documentation, as a dedicated page, to not bloat the purpose of the security.md page

**Comment by pavlenex** [comment]
@Zaxounette since @NicolasDorier now merged https://github.com/btcpayserver/btcpayserver/pull/4815 is there something else you plan to do in order to consider the issue complete? Or should we close it if everything was addressed?

**Comment by Zaxounette** [comment]
Sorry, a bit late on this one.

The main question is are you @pavlenex satisfied with the file wording and such? If not, we can revise it appropriately.

The second question was more so about the something that kukks proposed in a past dev call: Not publicize the security email or hunt.dev anymore, but just speak about reporting issues via the native Security Disclosure feature in github.
In parallel we'd still honor any reports in emails or hunt.dev when they come in, but in our docs we'd gently nudge to report on github only.

**Comment by Zaxounette** [comment]
Regarding a TODO, it'll be the one I posted in the above comment: https://github.com/btcpayserver/btcpayserver/issues/3787#issuecomment-1484607462

But if you're satisfied with the previous PR, then this issue can be closed, as that TODO can be considered additional enhancements, not MVP stuff I guess.

**Comment by pavlenex** [comment]
Yes I'd recommend we open an issue in docs repo for this @Zaxounette.
