### ISSUE TITLE
Feature Request -  Add Cancel button on invoice page

### ISSUE THREAD

**Issue by bigbryan98** [btcpayserver/btcpayserver#379]
Feature Request - Request to add a cancel button to the invoice page that cancels the screen and then takes the user back to the previous screen.

This is not needed very much online due to browser back buttons, but we are starting to use these on iPads and integrating with other POS systems, and once the system goes to the BTCPayServer, there needs to be a way to cancel the window.  This needs to be initiated from the BTCPayServer side.  

It would be nice to have optionality in this, perhaps a check box under the store,  in either general setting or checkout experience (I lean to the latter).

**Comment by sipsorcery** [comment]
+1.

The PayPal checkout flow has a cancel button. For better or worse a lot of users want to go through all the way to the payment page to check the final price (check for hidden fees) and then cancel to consider the purchase properly.

![paypal_checkout](https://user-images.githubusercontent.com/197660/47934478-a4dbc000-ded7-11e8-9b77-9cf63fd71828.png)

**Comment by bitcoinshirt** [comment]
Good idea, but has to be **optional**. I prefer not to have an easy way for customers to bounce and leave unpaid just because they find button interesting.

**Comment by sipsorcery** [comment]
@bitcoinshirt the customer is always right ;). 

If a customer wants to bounce back and forth 10 times before making a payment we should facilitate it. PayPal and credit card systems do. If lightning isn't involved it's only a database record that needs to be deleted when the cancel button is clicked. Small amount of effort for a potential sale :).

**Comment by bigbryan98** [comment]
Can you detail "custom modal" a bit more?  I've been looking for a work around.  (unless the feature request will be integrated soon, then just THANKS!)

**Comment by Kukks** [comment]
You can load the invoice URL in an iframe in your own modal. If you can wait, @r0ckstardev s pr will make this much easier for you :)

**Comment by bigbryan98** [comment]
I guess I'll wait for the PR.  Whats the PR #?  is there an ETA? Thanks @rockstardev !  you rock!

**Comment by Kukks** [comment]
@bigbryan98  https://github.com/btcpayserver/btcpayserver/pull/381

**Comment by bitcoinshirt** [comment]
One way of using this with modals can be a simple "X" that was posted on the Slack.

![screen shot 2018-12-16 at 16 41 51](https://user-images.githubusercontent.com/36959754/50055627-94169f00-0151-11e9-868e-1f32cf3167b5.png)

I actually think that for modal invoices a cancel button like the one above can be good idea.

**Comment by Kixunil** [comment]
We need this feature very much in Paralelna Polis. We are currently in the process of migrating to Btcpay server and would like to use it on iPad as PWA.

It sometimes happens that people remember they want to change something when QR code is presented. PWA doesn't have back button itself, so back is impossible. Restarting the app is not optimal because that empties whole cart.

**Comment by pavlenex** [comment]
@Kixunil Good suggestion, as earlier explained, cancel button exists for modal invoices, so I'll open an issue to add a modal invoice for Point of Sale, it makes quite a lot of sense.

**Comment by pavlenex** [comment]
@Kixunil I now remembered that we actually have a confirmation pop-up which can be closed, then the order can be adjusted.

![Screen Shot 2019-04-20 at 19 35 04](https://user-images.githubusercontent.com/36959754/56460479-ac1e5980-63a3-11e9-9c8b-ffaa118ad697.png)

Why does that not work out for you?

**Comment by Kixunil** [comment]
Thanks for considering! The thing is our baristas explained that it sometimes happens the moment QR code is presented, not before. So the QR code should also be cancelable. Also I sometimes demonstrate the interface without actually paying anything (but that is minor issue for me).
