### ISSUE TITLE
Status Exception "paidLate" creating new events every 30 seconds

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#38]
Looks like paidLate creates some sort of loop where it continuously sends new events to let you know its been paid late. See attached

![screencapture-btcpay-stufftech-io-invoices-fdkpgsuqeuut7r6zhcevb-1516307245471](https://user-images.githubusercontent.com/3916318/35120134-07cced02-fc4c-11e7-84f9-c04e4e6b12b3.png)

**Comment by astupidmoose** [comment]
Further to this issue for woocommerce plugin users:

Each notification is writing a note in the woocommerce database: "A payment has been received after expiration". Approx every 30 seconds. 

Manually changing the status in Woocommerce to another status results in the status being pushed back to the paidLate status once this IPN is received from BTCPay again.

**Comment by NicolasDorier** [comment]
fixed in 1.0.1.12 available in 10 minutes

**Comment by Eskyee** [comment]
🍻

**Comment by astupidmoose** [comment]
Same issue is also present in paidOver

**Comment by NicolasDorier** [comment]
mmh should definitively not happen... Can you screenshot the logs of the invoice so I understand wtf is going on?
