### ISSUE TITLE
Is it OK if run a btcpayserver on a "prune" node?

### ISSUE THREAD

**Issue by nguyendangdung** [btcpayserver/btcpayserver#380]
I dont have alot of space to host a fulll note. Any issues if I run the server on a prune node?

**Comment by NicolasDorier** [comment]
There is no reason to not run on a pruned node. If you use docker deployment, we document how on this page https://github.com/btcpayserver/btcpayserver-docker

**Comment by nguyendangdung** [comment]
Thank you. @NicolasDorier
