### ISSUE TITLE
Creating a `Payment Request` should redirect you to the list view upon creation

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#3803]
Similar to `Pull Payments`, `Invoices`, etc.. to be consistent.

However, currently when you first create one it keeps you back on the "Update/Edit" view.

An additional consideration is should it also take you back to the List view when you're editing an existing Payment Request...? I would think so.

**Comment by rustywave** [comment]
Is anyone working on this yet? If not I can try

**Comment by rustywave** [comment]
#3821 

Both "Create" and "Edit" actions redirect to list view upon creation now. Also updated the success notification message to reflect which action was taken.

**Comment by rustywave** [comment]
Not complete, need to review tests first

**Comment by dstrukt** [comment]
I don't believe anyone is working on it, thanks for picking it up.. will review when the PR is ready!

**Comment by rustywave** [comment]
> I don't believe anyone is working on it, thanks for picking it up.. will review when the PR is ready!

Done, thanks! I left some notes for clarity on the unit tests.

**Comment by pavlenex** [comment]
Done in https://github.com/btcpayserver/btcpayserver/pull/3825
