### ISSUE TITLE
Side nav bottom section cut off on mobile

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#3807]
**Describe the bug**
When using BTCPay Server on a mobile device's browser, the bottom elements of the navigation are not visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/1818366/171334985-58a366e4-d1e3-4e17-881b-aa18390f7f79.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.5.4
- Deployment Method:      Docker
- Browser: Edge for Android

**Comment by dennisreimann** [comment]
Unfortunately I don't have an Android device to test with.

**Comment by dstrukt** [comment]
Don't either, but might be able to get access to one to resolve :) will follow up

**Comment by bolatovumar** [comment]
I can repro this in Chrome as well on and Android device. I can take a look into what's causing this.
