### ISSUE TITLE
Greenfield API: Explain speedPolicy setting

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#3808]
The speedPolicy (checkout options) api docs need to be explained further as we do not have an equivalent setting in the wallet settings and this is confusing new developers. 

In stores wallet settings you can set the number of confirmations 0, 1, etc. when an invoice is considered "settled" but on the `speedPolicy` setting we only have enum values which do not make clear how many confirmations this will mean:

Enum: "HighSpeed" "MediumSpeed" "LowSpeed" "LowMediumSpeed" 

We should add additional info e.g. "HighSpeed" = 0 confirmations etc. 

Also add a note that this will override the wallet settings.

**Comment by pavlenex** [comment]
@ndeet are you taking on this one or you need any help on direction?

**Comment by ndeet** [comment]
Added it here mostly for myself or if anybody needs a good starter issue. Will look into it 👍
