### ISSUE TITLE
UX Help Tooltip

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#382]
There are some features in BTCPay that are really hard to understand. I talked to @NicolasDorier about providing a way for users to easier understand certain functions.

My suggestion is either a links or a tiny tool tips like this:

![new mockup 1 copy](https://user-images.githubusercontent.com/36959754/48202482-4c884080-e365-11e8-936e-ea230c18539c.png)

This is a screen shoot from Store settings, as you can see all of these features are important, but they can't be explained easily. I suggest we add some sort of pop-up for those and if it's too complex to explain, we can add a link to documentation.

I would like to use this issue as a way to collect all those "confusing" features and we can tackle them after that. In docs, I can cover all these options in-depth if needed.

**Comment by NicolasDorier** [comment]
@rockstardev what can I use to make tooltips in bootstrap?

**Comment by mariodian** [comment]
@NicolasDorier you have to run after the DOM has been built `$('[data-toggle="help-tooltip"]').tooltip()` and add an icon next to a label `<label for="NetworkFee">Add network fee to invoice (vary with mining fees) <i data-toggle="help-tooltip" class="fa fa-question-circle-o" title="Help text goes here..."></i></label>`

Similarly for popovers:

`$('[data-toggle="help-popover"]').popover({trigger: 'hover', title: 'Help'})`

<label for="NetworkFee">Add network fee to invoice (vary with mining fees) <i data-toggle="help-popover" class="fa fa-question-circle-o" data-content="Help text goes here..."></i></label>

**Comment by NicolasDorier** [comment]
@mariodian we don't want popover but ling to the doc. 
Will check `fa-question-circle-o`.

**Comment by NicolasDorier** [comment]
![image](https://user-images.githubusercontent.com/3020646/48395179-bfc0f680-e759-11e8-8e2c-bf7fb0f8bb47.png)

**Comment by NicolasDorier** [comment]
@bitcoinshirt if you find and document other place where it is needed, let me know.
