### ISSUE TITLE
Some plugins are hidden on left sidebar when navigating to other views

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#3824]
This is a strange one I'm not 100% sure why it happens or if it only happens to SideShift & FixedFloat plugins, those seem to be the ones where this occurs most commonly, but recorded a quick video just clicking between views to show the behavior:

https://user-images.githubusercontent.com/6250771/172049376-86f2c96f-1a48-449a-a243-38814a676b4e.mov

If not a bug, I'll close.

**Comment by rustywave** [comment]
On first glance it looks like there is an api call to GitHub which can result in a rate-limited failure. There is caching implemented but not sure if there's an issue with it.  Will try to dig in more later but I can reproduce the issue somewhat.

[api.github.com/repos/btcpayserver/btcpayserver-plugins/git/trees/master?recursive=1](https://api.github.com/repos/btcpayserver/btcpayserver-plugins/git/trees/master?recursive=1)

**Comment by dstrukt** [comment]
Ahh I see, appreciate the explanation .. also welcome aboard!

**Comment by rustywave** [comment]
Thanks for the welcome! I think I'm wrong about the rate-limit call being the issue however. Will update when I have something

**Comment by Kukks** [comment]
This happens because of the new store context mode, where the store id is also stored in a cookie instead of just part of the URL. Will need to add new capabilities in btcpay so that plugins can switch to using it instead of detecting based on url

**Comment by dennisreimann** [comment]
> Will need to add new capabilities in btcpay so that plugins can switch to using it instead of detecting based on url

I think these capabilities are already there — we made the context getter methods available to the plugins as well, so it might just be a matter of using them within the plugins.

**Comment by rustywave** [comment]
@dennisreimann , do you happen to know which file(s) to look at? Seems like we're losing the plugins somewhere between the view component and the view but I'm not sure.
