### ISSUE TITLE
[Design] Improved sidebar & sub-page navigation functionality

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#3827]
# CURRENT

With more thought; I think the third option makes the most sense, and could be applied to all views, from the On-Chain Wallet to the Store Settings to a Plugin and it's settings view.

The breadcrumbs would only appear a layer or more deeper than what the sidebar shows.

e.g.

Forms > Edit / Create (which Forms are accessible via the left sidebar)

Example:
![output](https://github.com/btcpayserver/btcpayserver/assets/6250771/b4a537a4-984a-4c16-a38e-b29a4a55d949)

# OLD

Discussed this a bit with @dennisreimann, and we ultimately decided this is something we may consider prototyping in the future, but for now, I'm going to post it so the work isn't lost .. might inspire something else.

Will likely update with some more "polished" mocks, but not intended to be worked on yet!

This is an early, rough iteration, no prototypes, etc... yet.

## Pros:

1. To put simply, this would move the tabbed navigation for Store Settings, Server Settings, and Account to the left sidebar.

Once clicked on the parent level navigation element, you would be dropped on the first child navigation item, and the menu for that section would be expanded, like so:

<img width="1139" alt="Screen Shot 2022-05-31 at 9 36 37 PM" src="https://user-images.githubusercontent.com/6250771/171328627-904945ce-ad56-41e2-b43a-3c9f5f688289.png">

This functionality could hypothetically be expanded to `Plugins`, think `LNBank`, etc... shows just LNBank at the parent level, you click the parent, then it expands / shows the child navigation items.

2.  We benefit from the nested navigation structure that is currently not the best at the moment.

e.g. You want to go to `Store Settings > Access Tokens > Create`, you can get there quite easily, and get back to the parent(s) by clicking on the tabbed menu or the sidebar menu as well. However, you lose a bit of context in the third level (which is the deepest BTCPay goes), and a bit of potential bread-crumbing could help in these situations, like so:

<img width="1359" alt="Screen Shot 2022-05-31 at 9 19 57 PM" src="https://user-images.githubusercontent.com/6250771/171327078-04947116-184c-4a1a-b945-2ec277a44384.png">

3. Intuitive, pushes people to the sidebar for everything, and keeps the focus of action in the "main" area, as well as works really well on Desktop.

## Cons:

1. The mobile implementation has its drawbacks, I suppose, but arguably this could be a pro for some e.g:

A) Currently you can access all of the tabbed views quite easily after clicking into "Store Settings" for example:

<img width="403" alt="Screen Shot 2022-05-31 at 9 47 55 PM" src="https://user-images.githubusercontent.com/6250771/171329978-790961c0-93a3-4fb4-b206-32df151cc204.png">

B) With the newer navigation structure, you'd have to go to the hamburger menu to switch views, however there's an edge case here ... you would have to click `Store Settings`, let it load the first tab, then re-open the hamburger menu to get to the `Store Settings` sub-nav items. 

<img width="324" alt="Screen Shot 2022-05-31 at 9 57 41 PM" src="https://user-images.githubusercontent.com/6250771/171330914-684c7668-bc5d-43dd-9e77-c08ffe400886.png">

This could arguably be resolved by expanding the menu via JS when you click on the parent nav item without it directing you anywhere until you choose one of the sub-nav items .. but there are some obvious drawbacks to this solution as well. 

C) Alternatively we could leverage the existing tabbed menu solely on mobile, and use this new navigation structure on desktop, but there is possibility for some confusion there...

2. The moment between clicking the parent level item and the expanding of the sub-nav items could be jarring, slow, or unwanted by some users who don't like to solely use the left sidebar, but would prefer to do this navigation on the "main" content area. This is a bit more subjective, and would come down to a potential prototype/implementation, but it's a real consideration.

---

There's probably more I'm not thinking of, as this is a rough idea I just wanted to cobble together to gather feedback, but feel free to drop thoughts, opinions, etc.. and we'll talk through some iterations or explorations .. maybe it'll inspire an even better idea.

**Comment by dstrukt** [comment]
Tracking the removal of the collapsable headers...
`24px` padding bottom
<img width="314" alt="Screen Shot 2023-05-06 at 4 27 03 PM" src="https://user-images.githubusercontent.com/6250771/236650271-33eccc40-6933-4dce-8435-a6b2e79a3b58.png">
`16px` padding bottom
<img width="335" alt="Screen Shot 2023-05-06 at 4 27 17 PM" src="https://user-images.githubusercontent.com/6250771/236650272-45ec1f72-1e3b-4fee-a504-b9921b045541.png">

**Comment by dstrukt** [comment]
3 Alternative Navigation solutions to consider:

Double Sidebar (could function the same way it does on mobile now):
<img width="717" alt="Screen Shot 2023-05-06 at 8 30 41 PM" src="https://user-images.githubusercontent.com/6250771/236656252-bb32897b-a2e4-49b4-a47f-3cedbd48773a.png">

A generalized with description menu before the subpages (pretty straightforward on mobile):
<img width="1117" alt="Screen Shot 2023-05-06 at 8 30 51 PM" src="https://user-images.githubusercontent.com/6250771/236656254-fbf9c00b-3dd8-4a9d-94ef-60a38ac349a1.png">

Expanded left sidebar (trickier on mobile to resolve):
<img width="855" alt="Screen Shot 2023-05-06 at 8 32 34 PM" src="https://user-images.githubusercontent.com/6250771/236656257-485e42c3-d67b-4c85-bc7b-05ff6f4d7723.png">

**Comment by dennisreimann** [comment]
Intuitively I like the third option best as it fits with what we established for the plugins/apps and the other options seem more like a compromise to avoid the sidebar from growing. 

In general we might try to reduce the number of nav items, e.g. we already discussed consolidating invoices/payment requests and pull payments/payouts. As the subnav would only be shown once you are in the main section, I could see this to work without getting too long. 

The situation on mobile right now isn't ideal either – so wrt this might not even be a degradation.

**Comment by dstrukt** [comment]
Appreciate the feedback!

Definitely support consolidating some of the pages, and have some clear ideas and suggestions for this, will make some tickets for us soon so we can kick around ideas for the next few releases.

Hypothetically the Store Settings / Account / Server Settings sub-navigation items could also only be expanded when the parent level item is clicked, and collapsed when they're not .. this is a bit tricker with Account / Server Settings, as they could expand up, or we just extend them down, but I suppose this is an issue to resolve at that time.

I'm still not fully certain where my preference is, but I think atm it's the first and third options.

**Comment by yashrajd** [comment]
2 sats FWIW:

- re: double sidebar: how do users know there will be another sidebar?
- agree mobile is a challenge, look forward to see solutions
- Concerned about side-bar doing excessive heavy lifting
- like 3rd, dislike 1st
- how about very diff layout for desktop, mobile: so 3rd for desktop, 1st for mobile/app

**Comment by dstrukt** [comment]
> * re: double sidebar: how do users know there will be another sidebar?
It would just appear if you've selected the Settings or Server Settings, Account, etc.. and default to the first page on the list; General, think the functionality will become apparent upon first use

> * agree mobile is a challenge, look forward to see solutions
Feel confident it can be addressed, will provide follow up mocks here soon!

> * Concerned about side-bar doing excessive heavy lifting
Understand this, but think it should be fine, we'll be relying on it for quite a while to come, so think it should be as robust as possible.

> * how about very diff layout for desktop, mobile: so 3rd for desktop, 1st for mobile/app
Definitely an option - will continue to explore this!

Thanks for all of the feedback!

**Comment by dstrukt** [comment]
The more I think about it, the more I think the third option makes the most sense, and could be applied to all views, from the On-Chain Wallet to the Store Settings to a Plugin and it's settings view.

**Comment by pavlenex** [comment]
I honestly don't think we need to address this one. I think it can potentially add a lot of things in the sidebar which is handled for primary and important navigation, and I am a bit hesitant of introducing navigational changes since a lot of users are already familiar with the flow. I just don't see the UX benefit of this, but happy to be proven wrong!
