### ISSUE TITLE
Improve Refund Flow (Part 2)

### ISSUE THREAD

**Issue by dennisreimann** [btcpayserver/btcpayserver#3839]
The remaining tasks from #3731:

- [ ]  Should alert the user if they're going over pay the refund amount when selecting the custom amount
- [ ]  An option to also offer a refund LESS the costs involved in issuing the refund (for example onchain fee to send it out)

More details in #3715.

**Comment by dstrukt** [comment]
Is this something we want to keep for 1.6.0? Will we have time to address some of these points in time? 

If so, will start working on this evening.

**Comment by dennisreimann** [comment]
I don't see it in this release, I think that was also the reason why we split it.

**Comment by dstrukt** [comment]
Going to remove, if for whatever reason we get to it, will re-add to 1.6.0, but moved to 1.7.0.
