### ISSUE TITLE
why not show Doge wallet

### ISSUE THREAD

**Issue by mengdodo** [btcpayserver/btcpayserver#3841]
hello , why not show doge wallet after add `export BTCPAYGEN_CRYPTO3="doge"`

maybe this is a bug ?
```
 BTCPay Server v1.5.4.0 (Altcoins)
```

<img width="1331" alt="iShot_2022-06-09_08 57 01" src="https://user-images.githubusercontent.com/21698573/172742161-90df1514-1d97-4fc9-9a5c-ee279c6bb404.png">

**Comment by Kukks** [comment]
Is it synced? Please follow the issue template next time.
