### ISSUE TITLE
Add support for logo white-labeling on Payment Requests, Invoices, Receipts, Pull Payments, etc...

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#3842]
- [ ] Payment Request
- [x] Checkout Invoices
- [x] Receipts (https://github.com/btcpayserver/btcpayserver/pull/4435)
- [ ] Pull Payments

As an admin... I'd like to be able to promote my brand with more than just my website, but with the POS front-end, Payment Requests, etc...

Ideally this functionality would enable an admin to upload their brand/store's logo in the `Store Settings > General` that we would then add to Invoices, Payment Requests, Pull Payments, and (now)Receipts .. and wherever potentially applicable, possibly as a default or a switch on/off functionality .. working this into mocks as well.

This Issue ties into the larger initiative of making files easier to manage as well, but after configuring your File system (would prompt if you haven't), you could simply upload your logo and we'll handle the rest.

We would still keep "Powered by BTCPay Server" at the bottom on all of these views.

Curious to hear other's thoughts.

**Comment by tmcphail67** [comment]
I think this is a great Idea.  It would also be great to be able to white label the the login screen and store screens with the hosts logo and name.  Providing the service to brick and mortar merchants and web stores, merchants would see the hosts brand with the powered by BTCPay Server in the footer.

**Comment by dstrukt** [comment]
Exactly!

We discussed some other basic optional functionality as well in our design call .. e.g. things like a primary theme color,  "business name or LLC", "address", etc.. for those who may also need that use-case, but one step at a time.

**Comment by dennisreimann** [comment]
We can tackle this once #4459 is merged.
