### ISSUE TITLE
Greenfield API: exchange rates endpoint

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#3855]
### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/3837

<div type='discussions-op-text'>

<sup>Originally posted by **ndeet** June  8, 2022</sup>
We have a somehow [undocumented exchange endpoint](https://github.com/btcpayserver/btcpayserver-doc/issues/1124) that was inspired by BitPay but needs to be store specific /api/rates/?storeId=XYZ, e.g. https://testnet.demo.btcpay.tech/api/rates?storeId=46y7JuD7dUHEN1BxeAmtReA5zjUzSho7HVXVteQr1XUW

The discussion here is about if we want that endpoint also to be available in Greenfield API. I think it would make sense but eager to hear what you think.</div>

**Comment by ndeet** [comment]
As discussed with @Kukks we should also provide exchange rates in Greenfield API.

**Comment by Bangalisch** [comment]
@Kukks takes this on

**Comment by bolatovumar** [comment]
What would be different in the Greenfield version of this endpoint vs the one that already exists? Is it the route so it's like `/api/v1/stores/{storeId}/rates`?

**Comment by ndeet** [comment]
Aside from a more consistent api endpoint inside Greenfield namespace/paths, the exchange rates will be based depending on the rate provider (and rating rules) from the store settings which would be imo expected and allows for customization. 
While the legacy endpoint works it is unclear which exchange rate source it uses and it is not as flexible and completely outside of the Greenfield endpoint paths structure. It would make ugly hacks necessary for Greenfield libraries (e.g. our PHP library) to use a different root path for the endpoint.
