### ISSUE TITLE
Consolidate `Server Settings > Services > External storage services` with `Server Settings > Files`

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#3861]
Currently you tab back and forth between Server Settings > `Services` > External storage tab, and the `Files` tab to manage files and the configuration of your BTCPay Server file server.

I propose we combine the two so that all of your files / settings are managed in the same tab.

### Current `Server Settings > Services > External storage`:
<img width="1116" alt="Screen Shot 2022-06-12 at 6 41 48 PM" src="https://user-images.githubusercontent.com/6250771/173265495-a1112ea0-6204-46d4-987c-b7924300c0ff.png">
<img width="884" alt="Screen Shot 2022-06-12 at 6 42 13 PM" src="https://user-images.githubusercontent.com/6250771/173265497-897ecaae-abe5-43a4-b0f2-3e774393056e.png">
<img width="802" alt="Screen Shot 2022-06-12 at 6 42 32 PM" src="https://user-images.githubusercontent.com/6250771/173265498-a82f062a-fc5a-4d9e-93b9-24725999261d.png">

### Current `Files`:
[ ]

### Proposed: 

[TODO MOCKS]

**Comment by forcemilitary** [comment]
![Uploading Screenshot_20220617-232338.png…]()

**Comment by forcemilitary** [comment]
Can you please help me so I can have the results of the bitcoin

**Comment by forcemilitary** [comment]
![Screenshot_20220618-012221](https://user-images.githubusercontent.com/107775373/174458307-32e0da9d-fb62-4a17-b853-9d1727a733d5.png)
