### ISSUE TITLE
[Bug]: can't set fee via api/ui

### ISSUE THREAD

**Issue by hell0-w** [btcpayserver/btcpayserver#3864]
### What is your BTCPay version?

BTCPAY 1.5.4

### How did you deploy BTCPay Server?

Docker

### What happened?

Every time when I create an invoice via API, UI  on the address  BTC i got a static minimum fee ~13.682-14.2Sat, can't change it to a minimum value.

![image](https://user-images.githubusercontent.com/17591751/173450184-8bcac054-3044-4b4e-98d4-75a357ad90b2.png). 
Please need help, how to get it work properly. 
How can i change these buttons/preset (10min/1hour...etc), to my own manual setting, or minimum fee 1-2Sat.
Thanks

### How did you encounter this bug?

1. installed new server via generator confiruration (docker)
2. sync all node chain
3. create wallet BTC
4. try to set 2 or 1 sat, every send transaction with 13.682Sat
5. server is updated, 

### What browser do you use?

chrome, FF

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
I am not sure if I understand your questions correctly, but you're asking how to  change the values in the fee field in the UI?
![Screenshot 2022-06-14 at 11 25 36](https://user-images.githubusercontent.com/36959754/173544212-72b1c962-e47d-473b-b7c3-8e7963e6f6c8.png)

Fee field you can type in whatever you want in there, or is your question about how to do it via the API?

**Comment by hell0-w** [comment]
> I am not sure if I understand your questions correctly, but you're asking how to change the values in the fee field in the UI? ![Screenshot 2022-06-14 at 11 25 36](https://user-images.githubusercontent.com/36959754/173544212-72b1c962-e47d-473b-b7c3-8e7963e6f6c8.png)
> 
> Fee field you can type in whatever you want in there, or is your question about how to do it via the API?
> Screen.Recording.2022-06-14.at.11.29.00.mov

Adding some detalization. 
Hello **pavlenex**,
Now I have 2 test nodes (video file attached)
So from UI now i can send and set the fee rate by manual mode ~1Sat (yesterday all transactions was minimum 13-14Sat, so if I set 1,2,3,Sat I get 13-14Sat). today from UI, all working. Strange situation. 
 
my question is: where can i set the value for this buttons fee rate which show in the Video fragment, and why the values are not the same on nodes? where can I get data via API request. (my node get recommended data, where can i see values according block size (time buttons)) ? 
As I understand the time on a buttons it's a size of blocks
10min = 1-2 block
1 hour = 6 blocks
6 hours = 36 blocks
1 day = 144blocks

and the second question is:
I do the test on 2 nodes, according to API documentation i build a curl request, create API keys, etc... 

curl -s \
     -H "Content-Type: application/json" \
     -H "Authorization: token <code>" \
     -X GET "https://URL//api/v1/stores/{storeId}/payment-methods/onchain/btc/wallet/feerate?blockTarget=144"

My results are: 

NODE1  = {"feeRate":1}
NODE2 = {"feeRate":18.173}
why? 

Thanks for answers. 

https://user-images.githubusercontent.com/17591751/173581890-c9496dba-616c-483b-9b16-9945a773eafc.mp4

**Comment by hell0-w** [comment]
After one day restarts several times docker-compose it was set to 1Sat. 
I solve one problem. 
But the Fee rate can't be set in sat via API.  Only you can set block.
