### ISSUE TITLE
Fix Build warnings

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3866]
When building `master` these are the warnings I get, we should address them.

![Screenshot 2022-06-14 at 11 09 30](https://user-images.githubusercontent.com/36959754/173546737-71120578-bc03-4c4e-88d2-f8897b2053e1.png)

**Comment by rafaelmalheiros** [comment]
```c#
var store = await _StoreRepository.FindStore
```
 could return `null`, what will throw `NullReferenceException`.

How should it behave on such cases?

There is a warning about `StoreNavPages.Integrations` been obsolete, but it is used after `StoreNavPages.Plugins ||`, so it will only be used if `StoreNavPages.Plugins` doesn't exist. 
Is such veification still necessary or should it be removed to fix the warning?

**Comment by pavlenex** [comment]
cc @dennisreimann @NicolasDorier  any guidance for this one?

**Comment by dennisreimann** [comment]
Added a PR #3870.
