### ISSUE TITLE
Improved Notifications List View

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#3871]
For the developer who picks up this Issue, feel free to reach out to me on Mattermost @dstrukt for any feedback, additional mocks, or discussion of specific items!

Few things involved in this improvement, but all the changes should be consistent with what we're doing in the Invoice / Payment Request views already, so that could act as a reference for code / implementation:

- [x] Mass Action buttons that replace the table header when `> 1` are selected
- [x] Introduction of the `Store` from which the notification originated to the table column ... might just be adding more noise though, but an option, thoughts?
- [x] Ability to filter based on the `Store`, regardless if we add to the column
- [x] A `Read/Unread` or `Seen/Not Seen` toggle, would be similar styling to the `Store Invoices / All Invoices` in the Invoice List View, but this is also an optional choice .. thoughts?
- [x] Filter by the `type` e.g. `Invoice`, `Payment Request`, etc.. similar functionality to the filtering in other views

.gif might take a second load

![Notifications+MassActionsV0 1](https://user-images.githubusercontent.com/6250771/173712851-e3641f1c-c92d-447c-a60a-4cb9e6043f40.gif)

**Comment by pavlenex** [comment]
@TChukwuleta This one is now fully specified and it can be something to tackle if you're up for it!

**Comment by TChukwuleta** [comment]
sure.. @pavlenex

**Comment by NicolasDorier** [comment]
Reopening this one, maybe still stuff left in the list. @dstrukt close again if that's done!

**Comment by dstrukt** [comment]
Oh, no I think @TChukwuleta covered everything, going to close again - thanks for looking out @NicolasDorier!
