### ISSUE TITLE
Edit pull payment

### ISSUE THREAD

**Issue by dennisreimann** [btcpayserver/btcpayserver#3878]
Working on #3873 I noticed that we do not have an edit view for pull payments. Though the amount might be fixed after creation, we now have some more fields like title and description, which should be editable afterwards.

**Comment by dstrukt** [comment]
ACK.

**Comment by daviogg** [comment]
Can I try to implement this issue?

**Comment by dennisreimann** [comment]
Sure, go ahead and let me know if you have any questions. You can get in touch via [Mattermost](https://chat.btcpayserver.org).

**Comment by HamroRamro** [comment]
Someone please close this issue since it has been merged in https://github.com/btcpayserver/btcpayserver/pull/4016
