### ISSUE TITLE
[Bug]: Reset password email not getting triggered on demo mainnet 

### ISSUE THREAD

**Issue by decypherpunk** [btcpayserver/btcpayserver#3896]
### What is your BTCPay version?

N/A

### How did you deploy BTCPay Server?

N/A

### What happened?

Not sure I'm filing this issue on the correct repo, but reset password email does not seem to be triggered when I do forgot password for my account on https://mainnet.demo.btcpayserver.org/login

The email is functional, I'm receiving other emails on that account. This has happened multiple times. I checked spam too.

Happy to file issue on the correct repo if I'm doing it wrong or provide more info.

### How did you encounter this bug?

1. Go to https://mainnet.demo.btcpayserver.org/login
2. Click Forgot Password
3. Enter email on the Forgot Password page
4. Click Submit button

### What browser do you use?

Safari 15.4 on macOS

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
We don't have SMTP enabled on that server, so email won't work, not a bug, expected behaviour.

@NicolasDorier you may want to enable SMTP for a demo server.
