### ISSUE TITLE
App Deletion Redirect Destination?

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#3898]
Currently when you delete an `App`, it brings you back to a list view of your `Apps`:

<img width="1429" alt="Screen Shot 2022-06-25 at 1 03 01 PM" src="https://user-images.githubusercontent.com/6250771/175789033-d7990bd7-d56b-4538-9754-524fd24e18e9.png">

I'm wondering if this should be the intended functionality, as this is not a view the user sees otherwise and this *could* potentially be a bit confusing...? In addition to being a view we don't actively support.

Not 100% sure how to handle atm, we could just shelve the issue, and wait until we transition these apps to `Plugins`.. thoughts?

Noting this issue for the future.

**Comment by bolatovumar** [comment]
I agree @dstrukt. There is no other way to get to this view besides just typing it out manually so it's kind of weird that we redirect to it after app delete. I made a PR to instead redirect to the dashboard: #3941.

**Comment by dstrukt** [comment]
Dope!

Tagged @dennisreimann for a review, see if he has any additional thoughts for us, but uACK from me.
