### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver#39]
https://btcpay-server-testnet.azurewebsites.net/vendor/bootstrap/css/bootstrap.css.map
https://btcpay-server-testnet.azurewebsites.net/vendor/popper/popper.min.js.map

So i found these errors with the Safari Develop Inspect Element tools, 
which I'm sure, will also show up in Chrome etc etc browsers, 

When Loading The Test Site.
same error in happens in the latest version update.

bootstrap.css.map
popper.min.js.map
I don't see these in the BTCPAYSERVER Source file ??

<img width="1440" alt="fail bootstrab css map" src="https://user-images.githubusercontent.com/30862925/35397231-dea6e978-01e6-11e8-9f13-c637aefc5e05.png">

**Comment by NicolasDorier** [comment]
We should probably remove them so, can you do a PR for this ?

**Comment by Eskyee** [comment]
yes I think so, i think we dont need for this for our production environment,
just for debug purpose. sourceMappingURL=bootstrap.css.map
cheers

**Comment by Eskyee** [comment]
with popper/popper.min.js.map 
found with errors with the Safari Develop Inspect Element tools, 404
not so sure about this fix without breaking something else .

https://btcpay-server-testnet.azurewebsites.net/vendor/popper/popper.min.js.map

**Comment by lepipele** [comment]
@Eskyee you need to remove these two lines:

https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/wwwroot/vendor/bootstrap/css/bootstrap.css#L9893

https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/wwwroot/vendor/popper/popper.min.js#L5

I was actually thinking to work on bundling JS/CSS files so that eventually server just serves one of each which would speed up rendering and performance. Plus we would get free minimization. But I haven't had chance to talk with @NicolasDorier about it.

Thus if you only wish to solve those errors for now, removing those two lines will do it.

**Comment by NicolasDorier** [comment]
I am open to anything. I don't really know how to do smart js stuff in a .NET CORE project.

**Comment by lepipele** [comment]
@NicolasDorier PMed you on Slack

**Comment by Eskyee** [comment]
//# sourceMappingURL=popper.min.js.map 
when I removed created a problem, in bootstrap.css
which breaks the appearance tag, so I added -webkit-appearance on line 4187 which solved  the new problem, but I don't think this is correct solution .. 
I sure its when we are minifying and combining the JavaScript files, thats where we solve our 404 develop debug problems

**Comment by lepipele** [comment]
@Eskyee agreed. I'll update you once I am done with #47

**Comment by NicolasDorier** [comment]
@Eskyee should I revert 698b3c46cd76850e44619f277ef8099705ed9855 and df81051d0720c1cf4adafa64e6482c8677d19c1f ?

**Comment by Eskyee** [comment]
I would wait till , once lepipele comes with the solution sorted, we will have permanently solved 404 mapping errors fixed, my solution then wouldn’t be needed

**Comment by lepipele** [comment]
Moving to: https://github.com/btcpayserver/btcpayserver/issues/47
