### ISSUE TITLE
Add `receipt` button in the checkout

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3915]
We introduced a concept of receipts, a public information any customer can access in #3612.

Currently, it can be visible to the end-user if it's sent over by email via the API, or something along those lines.
Once we're done reconstructing our invoice checkout page in #3567 I think we could add a button somewhere that would simply say `receipt` similar to what we have with `back to store` button once invoice is in the`settled` status.

Obviously, as Kukks pointed out, for on-chain payments, people will most likely close the page and forget the link, but for LN payments they probably can instantly get a receipt. Merchants would need to use receipts in combination with email functionality we introduced for best experience and to ensure customers always has access to a receipt.

![Screenshot 2022-06-29 at 18 55 07](https://user-images.githubusercontent.com/36959754/176493111-a13fe340-80ca-4bd8-9933-9aa5290b4907.png)

If anyone would like to take this on, please wait for #3567 since it's a blocker.

**Comment by dstrukt** [comment]
Resolved in https://github.com/btcpayserver/btcpayserver/pull/3612
