### ISSUE TITLE
Simplify `Wallets` menu in store

### ISSUE THREAD

**Issue by Bosch-0** [btcpayserver/btcpayserver#3925]
Seems unnecessary to show the 4 options for wallet types on the side bar like the below image. It would simplify things to just have an `Add wallet` button if no wallet is setup and only show wallets that are setup here. When you click `Add wallet` it would give you the option to choose what type of wallet you want to connect.

Absolutely loving the redesign btw guys, finally taking the leap and am going to accept payments via BTCPay

![image](https://user-images.githubusercontent.com/55287964/177022955-ca30c334-1d7b-41d8-9949-225b5e3d295f.png)

**Comment by dstrukt** [comment]
That's awesome, cheers!

That day might be coming fairly soon as wouter is introducing the concept of adding wallet ui experience specifically for interacting with exchanges and other custodians which will require an "add wallet" functionality, so ultimately could see something like this could get rolled into that experience ... the dashboard config could drop you into the relevant setup path or we'd push the user to that first screen with all options.

a screenshot he shared in one of the PRs

![image](https://user-images.githubusercontent.com/6250771/177065722-6f9c397c-9db5-4ed9-b4a5-87700f7dfb8d.png)
