### ISSUE TITLE
I have disabled LTC but still see "Some of your nodes are still synchronizing..." error

### ISSUE THREAD

**Issue by mariodian** [btcpayserver/btcpayserver#394]
Hey, I don't even know why, but I see LTC in my store settings. I haven't enabled it in `~/.btcpayserver/Main/settings.config`, nor I run any LTC node. 

I've disabled it in the store settings yet I'm seeing the following "popup" message:

<img width="523" alt="screen shot 2018-11-12 at 12 15 58 pm" src="https://user-images.githubusercontent.com/3636406/48326535-d6d9e880-e674-11e8-8fcf-521605544ed2.png">

Is there any way of getting rid of it?

Thanks!

P.S. I'm running b16b1c3e8bdcb62f92b97f43695877a256d2ff9c.

**Comment by mariodian** [comment]
I figured it out. Had to add `chains=btc` to `~/.btcpayserver/Main/settings.config`

**Comment by mariodian** [comment]
> What command line are you using to start BTCPay? 

`/usr/bin/dotnet run -p "/home/satoshi/source/btcpayserver/BTCPayServer/BTCPayServer.csproj" -c /home/satoshi/.btcpayserver/Main/settings.config --network=mainnet`

**Comment by NicolasDorier** [comment]
`dotnet run --no-launch-profile --no-build -c Release -p "BTCPayServer/BTCPayServer.csproj" -- $@`

**Comment by NicolasDorier** [comment]
see the `--no-launch-profile`
