### ISSUE TITLE
[Bug]: LTC. Invalid bitcoin object of type OutPoint

### ISSUE THREAD

**Issue by sadovojav** [btcpayserver/btcpayserver#3946]
### What is your BTCPay version?

BTCPay Server v1.5.4.0 (Altcoins)

### How did you deploy BTCPay Server?

Docker

### What happened?

Get an error when try to create transaction LTC from API with selectedInputs params [doc](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreOnChainWallets_CreateOnChainTransaction)

`Error during POST to https://***/api/v1/stores/***mUKNFFhRDHMcdw***3pGyk86xvSzaGL***/payment-methods/OnChain/LTC/wallet/transactions. Got response (422): [{"path":"selectedInputs[2]","message":"Invalid bitcoin object of type OutPoint"}]`

Request:

URL: `https://***/api/v1/stores/***XaYMv4NmUKNFFhRDHMcdw***3pGyk86xvSzaGL***/payment-methods/OnChain/LTC/wallet/transactions`
Method: `POST`
Body:
```json
{
  "destinations": [
    {
      "destination": "M8JXAGhTQqAJUZhpyJbmrnNp5WJ6h*****",
      "amount": "0.84420310",
      "subtractFromAmount": true
    },
    {
      "destination": "ltc1qta3h9ygyqeg42x496tyz8kclhf72muyvd*****",
      "amount": "0.00337500",
      "subtractFromAmount": false
    },
    {
      "destination": "M9sWLPc5tqN9EY15hm3fjdi6NBKGu*****",
      "amount": "0.00037500",
      "subtractFromAmount": false
    }
  ],
  "feeRate": 1,
  "proceedWithPayjoin": true,
  "proceedWithBroadcast": true,
  "noChange": false,
  "rbf": null,
  "selectedInputs": [
    "MQgncns69xPAv6ncPx8r1YMvTCkFaAVY6g",
    "MNtsrp7YKR1fPyMbSbwyxzmCTZuvts6qFG",
    "MA4bhP2n6t9UCq9gaSL6ysf1t3hHTEJCHz"
  ]
}
```
`selectedInputs` - this is the address in the invoices that I received payments

### How did you encounter this bug?

Wallet LTC
1. Create 2 invoices
2. Pay both invoices
3. Create a transaction via API with-param`selectedInputs`

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Kukks** [comment]
`SelectedInputs` is requesting the outpoint format, which is a combination of transaction id and output index. That means if you received funds in `MNtsrp7YKR1fPyMbSbwyxzmCTZuvts6qFG` in transaction [768d4db46b9aae1ea85caebe5b87e7e56d4a683f90e1499d9472706c41068c1b ](https://blockchair.com/litecoin/transaction/768d4db46b9aae1ea85caebe5b87e7e56d4a683f90e1499d9472706c41068c1b) with the index of 0,  you should provide selectedInputs with `768d4db46b9aae1ea85caebe5b87e7e56d4a683f90e1499d9472706c41068c1b:0`

There is an http endpoint which provides this data already at [https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreOnChainWallets_GetOnChainWalletUTXOs](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreOnChainWallets_GetOnChainWalletUTXOs)
