### ISSUE TITLE
[BUG] v1.6.0.0 Pull Payment LNURL Bech32 QR Not Updating

### ISSUE THREAD

**Issue by pardus79** [btcpayserver/btcpayserver#3949]
When I create a pull payment for off-chain and the receiver wants to use the LNURL QR feature, the QR does not update to a Bech32 QR when selected unless, the QR window is closed and reopened (sometimes a few times).

This issue actually captured in the feature video on the release notes ([https://blog.btcpayserver.org/btcpay-server-1-6-0/#lnurl-withdraw-support-for-payouts-](https://blog.btcpayserver.org/btcpay-server-1-6-0/#lnurl-withdraw-support-for-payouts-)). You can see that the QR doesn't change when it is changed from URI to Bech32.

**Comment by pavlenex** [comment]
@Kukks can you look into this?
