### ISSUE TITLE
The server use inmemory store to store hangfire tasks. What's wrong with postgres?

### ISSUE THREAD

**Issue by smallswan399** [btcpayserver/btcpayserver#395]
https://github.com/btcpayserver/btcpayserver/blob/dc749462ec09d2e6b7b5e4372bb035d80e6b5ee2/BTCPayServer/Data/ApplicationDbContextFactory.cs#L102-L110

We will lost tasks if restart the server

For example, the server is tracking some invoices to send notifications via webhook url. restart the server that then it may the client application never get notifications from server for some invoices

**Comment by ketominer** [comment]
Removing hangfire would be nice as it will allow for true clustered deployments. Currently I have to cheat and do a kind of active/passive setup. A good alternative would be to use a persisted redis cluster as the backend for this kind of things...

**Comment by NicolasDorier** [comment]
well the good alternative would be to just use the database we already have.

**Comment by nguyendangdung** [comment]
How does the database process background tasks like hangfire do?

**Comment by Kukks** [comment]
@pavlenex  please close, hangfire is no longer used

**Comment by smallswan399** [comment]
So we have an alternative way to process background tasks or have no background tasks at all?

**Comment by Kukks** [comment]
There are still background tasks, they are just small tasks which didn't
need the complexity of hangfire.
