### ISSUE TITLE
My BTCPayServer v1.3.5.0 wont update to a newer version

### ISSUE THREAD

**Issue by clarketowson** [btcpayserver/btcpayserver#3951]
Hi there,

I'm running BTCPayServer v1.3.5.0 and when I try to upgrade it to a newer version via the web interface nothing happens.  I'm not sure why.  The only changes I have made are I have written some custom scripts which I have placed in the btcpayserver-docker directory.  They're just shell scripts to extend the functionality so I can do things on the command line like getting node ip addresses, node names, node public keys, etc.

Does the upgrade not work if there are custom files in the btcpayserver-docker directory?

Are there any suggestions as to what I might try to successfully upgrade?

Any help would be much appreciated.

Kind Regards,

Clarke

**Comment by Kukks** [comment]
It won't work because the update mechanism attempts to do a git pull which
fails if you've added or modified the default files

**Comment by Kukks** [comment]
Perhaps you can do a git stash, update and then unstash. I'll see if we can
add a specific directory to gitignore that you can add custom stuff to
which won't block you in the future

**Comment by clarketowson** [comment]
Thanks Andrew I appreciate the advice.  

So for now if I want to upgrade to the latest version of BTCPay I could do a git stash, update and then unstash or perhaps alternatively if I copy the custom scripts I wrote and any custom directories I have created out of the btcpayserver-docker directory and then remove those custom scripts and custom directories and then attempt to upgrade again and it should work?  

Or perhaps I could wait for a future upgrade where the gitignore has been added as a feature and then I could move my scripts to that directory and then upgrade?

A specific directory added to gitignore for custom scripts which wouldn't block upgrades in the future would be really fantastic.  The scripts I have written are very useful to me as I do bitcoin lightning network consulting to the general public and my scripts run as cron jobs on my btcpay server and they update my main business website with specific stats I want made public from my btcpay server and lightning node.  You can see the stats page here: 

https://intjbilling.com/ulysseslateststats.html 

and the scripts I have also made public here: https://intjbilling.com/bashscripts.html

I did that work approx 1 year ago.

Kind Regards,

Clarke

**Comment by NicolasDorier** [comment]
@clarketowson I think if you are starting to change `btcpayserver-docker` for other things than the custom fragments (which are handled by gitignore), then you should switch your btcpayserver install to use your own repository.

This would give you more flexibility, but require one more steps for the update: You will need to merge our upstream branch before updating.

**Comment by clarketowson** [comment]
OK thanks Nicolas I appreciate the feedback and advice.
