### ISSUE TITLE
[Bug]: cannot withdraw refund with LNURL

### ISSUE THREAD

**Issue by theDavidCoen** [btcpayserver/btcpayserver#3953]
### What is your BTCPay version?

BTCpay server 1.6.0

### How did you deploy BTCPay Server?

VPS

### What happened?

I tried to withdraw funds using refund offchain via LNURL-withdraw using Breez Wallet and Wallet of Satoshi.
In both cases I get problem processing LNURL.
Also, I tried to enter a bolt 11 invoice and a LN address from Wallet of Satoshi: initially I got an error, something like the Lightning Address is offline, then I was able to put the refund in pending but when I send I get "Failed - LNURL uses bech32 and 'lnurl' as the hrp (LUD1) or an lnurl LUD17 scheme.
abidingkevin89@walletofsatoshi.com"

### How did you encounter this bug?

From the new Issue Refund with LNURL-withdraw feature.
Tried to scan the LNURL-withdraw and to paste both a bolt11 and a LNURL (lightning address)

### What browser do you use?

Chrome

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by theDavidCoen** [comment]
![Screenshot_2022-07-09-21-45-48-738_com breez client](https://user-images.githubusercontent.com/38695835/178120523-848550b6-7465-4fe2-a2c0-e8c5b3a0ad64.jpg)
![Screenshot_2022-07-09-20-11-58-271_com livingroomofsatoshi wallet](https://user-images.githubusercontent.com/38695835/178120529-1d514cc5-ab34-4a9c-87f0-c128f7425fa7.jpg)

Here with Breez and with Wallet of Satoshi

**Comment by Blineberger** [comment]
> ### What is your BTCPay version?
> BTCpay server 1.6.0
> 
> ### How did you deploy BTCPay Server?
> VPS
> 
> ### What happened?
> I tried to withdraw funds using refund offchain via LNURL-withdraw using Breez Wallet and Wallet of Satoshi. In both cases I get problem processing LNURL. Also, I tried to enter a bolt 11 invoice and a LN address from Wallet of Satoshi: initially I got an error, something like the Lightning Address is offline, then I was able to put the refund in pending but when I send I get "Failed - LNURL uses bech32 and 'lnurl' as the hrp (LUD1) or an lnurl LUD17 scheme. [abidingkevin89@walletofsatoshi.com](mailto:abidingkevin89@walletofsatoshi.com)"
> 
> ### How did you encounter this bug?
> From the new Issue Refund with LNURL-withdraw feature. Tried to scan the LNURL-withdraw and to paste both a bolt11 and a LNURL (lightning address)
> 
> ### Relevant log output
> _No response_
> 
> ### What browser do you use?
> Chrome
> 
> ### Additional information
> _No response_
> 
> ### Are you sure this is a bug report?
> * [x]  I confirm this is a bug report

**Comment by NicolasDorier** [comment]
ping @Kukks

**Comment by Kukks** [comment]
So just tried WOS:
* I dont think they support lnurl-withdraw? I manually ran the flow on 1.6.1(copied the lnurl from page HTML and executed it in the browser manually) and it worked. 

Tried Blue wallet:
* lnurl withdraw uri format does not work but the bech32 version worked. 

* #3955 fixes a bug where the qr code was not being rendered correctly. 
* https://github.com/btcpayserver/btcpayserver/pull/3960 fixes the bug where it could not pay to ln address payouts

**Comment by theDavidCoen** [comment]
@Kukks wallet of Satoshi do support LNURL-withdraw and so Breez.
I always tested both during my tests with custom LNURL-withdraw links also related to NFC card.
Here an example with a link generated with Fountain.
![Screenshot_2022-07-12-09-47-52-943_com livingroomofsatoshi wallet](https://user-images.githubusercontent.com/38695835/178437583-b578c88f-480f-4f23-9370-7823b28bd48e.jpg)
![Screenshot_2022-07-12-09-47-59-762_com livingroomofsatoshi wallet](https://user-images.githubusercontent.com/38695835/178437601-397b4db9-bba7-4f67-954a-d903900351d4.jpg)

**Comment by pavlenex** [comment]
Can confirm URI doesn't work on Breeze. Bech32 does.
Error that breez throws is: `Does not contain an LNURL: uknown response tag method :fetch lnurl`

**Comment by Kukks** [comment]
> Can confirm URI doesn't work on Breeze. Bech32 does.
> Error that breez throws is: `Does not contain an LNURL: uknown response tag method :fetch lnurl`
> 
> @Kukks I am curious why do we have two QR's what's one and what's other used for? Perhaps one has wider adoption and the other doesn't?

This. The uri is the recommended approach while the bech32 is the most widely used one currently.

**Comment by NicolasDorier** [comment]
Fixed in 1.6.2
