### ISSUE TITLE
[Bug]: Edit Webhook: specific events not shown

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#3958]
### What is your BTCPay version?

v1.6.0.0

### How did you deploy BTCPay Server?

btcpay-docker 

### What happened?

When editing an existing webhook which has only specific events set under "Send specific events" dropdown selection the actual events are not editable or even shown at all. See screenshot:

![image](https://user-images.githubusercontent.com/1136761/178295092-6ba635e2-6eb3-47b6-a90a-1942ba220c37.png)

### How did you encounter this bug?

Go to store settings -> tab Webhook and edit an existing webhook which has specific events selected.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by rustywave** [comment]
Looks like it's not loading the select list when "Send specific events" is the default. If you select "Send me everything" then go back to "Send specific events" it works fine. Will take a stab at it

**Comment by NicolasDorier** [comment]
thanks @rustywave  for the fix
