### ISSUE TITLE
It would be good if you can share, which mining pool we can connect through btcpayserver.

### ISSUE THREAD

**Issue by hpx127** [btcpayserver/btcpayserver#3997]
It would be good if you can share, which mining pool we can connect through btcpayserver.
Few other questions as below:

btcpayserver can able to connect with any mining pool or not ? if yes, then how we can able to connect.

_Originally posted by @hpx127 in https://github.com/btcpayserver/btcpayserver/discussions/3939_

**Comment by pavlenex** [comment]
You can't connect btcpay to a mining pool, it's not a mining software, as we already replied in that discussion.

**Comment by hpx127** [comment]
sorry for trouble, my question are, 
after lightning network create funding for the both sender and receiver parties then this funding transection or settlement transection how to push in any miner pool because without any miner pool how to miner would get this funding and settlement transection and mine this two block of blockchain network..?
and
so how to connect lightning network with miner pool ...?
so please suggest related any document….
