### ISSUE TITLE
Secret Code

### ISSUE THREAD

**Issue by Pavlos584** [btcpayserver/btcpayserver#4002]
### What is your BTCPay version?

BTCPay Server v1.6.1.0

### How did you deploy BTCPay Server?

Ubuntu

### What happened?

Hello, where can I find the secret code for ipn?

### How did you encounter this bug?

IPN

### Additional information

Hello, where can I find the secret code for ipn?

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Pavlos584** [comment]
Hello, where can I find the invoice verification code? I need to secure IPN.

**Comment by pavlenex** [comment]
Please ask support quesitons on chat.btcpayserver.org
