### ISSUE TITLE
How to populate invoice data in an email with TriggerData?

### ISSUE THREAD

**Issue by Nailz776** [btcpayserver/btcpayserver#4005]
### What is your BTCPay version?

1.6.2.0

### How did you deploy BTCPay Server?

Docker

### What happened?

Invoice data not populating in emails when using TriggerData.

### How did you encounter this bug?

By setting this in the Email Rules body:
```

<!DOCTYPE html>
<html lang="en">
  <body>
	<p style="text-align: left">
	Invoice Id: {{TriggerData.Invoice.Id}} <br/>
	Item Description: {{TriggerData.Invoice.ItemDesc}} <br/>
	Amount Paid in BTC: {{TriggerData.Invoice.BtcPaid}} <br/>
	Invoice Url: {{TriggerData.Invoice.Url}}
	</p>
  </body>
</html>
```

### Additional information

How can I get invoice data to be populated when an email is sent? I couldn't find anything in the docs. Thank you.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
We use GitHub for bug reports, so please post a question on our Mattermost Chat (you can download mattermost app or preview via web) over at chat.btcpayserver.org or on Telegram group.
