### ISSUE TITLE
[Bug]: Server Error 500

### ISSUE THREAD

**Issue by valsha** [btcpayserver/btcpayserver#4008]
### What is your BTCPay version?

1.6.3

### How did you deploy BTCPay Server?

Docker

### What happened?

Dashboard 500 Internal Server Error
When I am open https://pay.site.com
I am ALWAYS redirecting to -  https://pay.site.com/stores/G4N1wLM6CCHziRHSmAX8NBTbiWWzspseHZgPQNbQLWrx
I can see only a BLANK page, nothing more.

### How did you encounter this bug?

Added Litecoin as a second CRYPTO2
export BTCPAYGEN_CRYPTO2="ltc"

### What browser do you use?

Firefox

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Seems like a duplicate or very similar issue to #4007

**Comment by valsha** [comment]
Maybe.
Can I delete this store manually via CLI to fix this problem?

**Comment by pavlenex** [comment]
Possibly resolved with https://github.com/btcpayserver/btcpayserver/commit/c53fcde12acb2d2a2b3d221c114cd12543605c89

**Comment by valsha** [comment]
> Possibly resolved with [c53fcde](https://github.com/btcpayserver/btcpayserver/commit/c53fcde12acb2d2a2b3d221c114cd12543605c89)

No, is not. The dashboard is offline. 
Status 500 Internal Server Error

**Comment by JubrilO** [comment]
@valsha Were you able to resolve the issue? I am currently facing this issue with my Monero only setup.

**Comment by VityaSchel** [comment]
I'm not able to run btcpayserver and logs doesn't seem to contain any errors
