### ISSUE TITLE
[Bug]: Greenfield API: Update a Webhook bug and undocumented request param

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#4010]
### What is your BTCPay version?

BTCPay v1.6.3.0

### How did you deploy BTCPay Server?

btcpayserver-docker

### What happened?

The ["Update a Webhook"](https://docs.btcpayserver.org/API/Greenfield/v1/#tag/Webhooks/paths/~1api~1v1~1stores~1{storeId}~1webhooks~1{webhookId}/put) endpoint has a major issue causing webhooks to fail. 

1. the request body schema does not mention `secret` (but it works actually if you put it there)
2. if `secret` is not present the secret gets reset or replaced by nothing, not sure

As it is now the update webhook will make your webhooks fail as it seems if the (undocumented) `secret` is not set it resets the passwort.

**Expected behaviour:**  
1. if the `secret` is missing it should not change the webhook secret at all
2. if `secret` should be available to overwrite at all on that endpoint it needs to get documented on API docs

**To discuss**:
- Should secret be allowed to be updated via the update webhook endpoint at all?
- If yes, what happens if the secret is not present in the request, it should imo keep the old secret and not generate a new one because you do not get back the automatically generated secret in the response either
 

### How did you encounter this bug?

see above

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Kukks** [comment]
IMO, it should not accept the secret, and it should not update the secret. If there is a need for a secret update, we can add an additional endpoint for that

**Comment by ndeet** [comment]
Agree that it should not be allowed it at all, however the problem I have now though:

Say I with WooCommerce I want to update the specificEvents with a new release. Assuming this will be fixed in > 1.6.3.0 I need now to send the secret in calling Update Webhook (and also add it in the PHP library) to be backward compatible with releases up to >1.6.3.0 to not have the existing and stored secret get overwritten by the API call. 
So it would be great if the fixed bug release would not throw an error if `secret` is send and not throw an error but just ignore it silently? Howewer this will be maintenance pain as the param will stop working with >1.6.3.0 on the PHP library too (but needs to be present for all releases before). So this is bc break even it was never documented? 😬  

Or we document the param as it works now and change it in GF v2 to not break bc?

**Comment by Kukks** [comment]
Since the GET does not return the secret, I'm inclined to make it so that update ignores the secret

**Comment by ndeet** [comment]
Ok, this means I will add the secret to the PHP lib so I can support updating webhook event subscriptions for all older releases. But starting with an upcoming version this will just silently get ignored. What do we do with the API docs? Just keep them as is without the `secret` param? So I will add a comment to the PHP lib function that this will stop working at some point in case anybody want's to set the secret via update webhook. Sounds good, tbh not many use that endpoint anyway it seems, otherwise there would be more complaints about failing webhooks 😅
