### ISSUE TITLE
BTC Lighting

### ISSUE THREAD

**Issue by Pavlos584** [btcpayserver/btcpayserver#4012]
### What is your BTCPay version?

1.6.1.0

### How did you deploy BTCPay Server?

Ubuntu

### What happened?

Hello, it sometimes happens that when I click the pay button, this error pops up and payment via lighting is not available: BTC: Payment method unavailable (The lightning node did not reply in a timely manner). I have to click the pay button again for it to load correctly. Don't know what to do with it?

### How did you encounter this bug?

I clicked the pay button.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Replied on Mattermost, this means your node is offline, you'd have to dig deep into the logs to see why your node is behaving like that.
