### ISSUE TITLE
[Bug]: 413 Request Entity Too Large

### ISSUE THREAD

**Issue by valsha** [btcpayserver/btcpayserver#4018]
### What is your BTCPay version?

1.6.5

### How did you deploy BTCPay Server?

Docker

### What happened?

413 Request Entity Too Large when I am trying to upload my XMR (Monero) keys.
my nginx.conf
```
client_max_body_size 100M;
client_body_buffer_size     100M;
```

### How did you encounter this bug?

I am trying to upload my XMR (Monero) keys.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by valsha** [comment]
Good day, any update? Thanks.

**Comment by Kukks** [comment]
I would suggest you use a new wallet instead. You're trying to upload a massive file that will inevitably grow more when used for merchants.

**Comment by valsha** [comment]
This is a NEW wallet, created using this manual https://sethforprivacy.com/guides/accepting-monero-via-btcpay-server/
you have this manual in your https://docs.btcpayserver.org/FAQ/Altcoin/
![image](https://user-images.githubusercontent.com/7966513/184216700-63e51c48-1388-4004-9d04-29d51b6568aa.png)

**Comment by VIEWVIEWVIEW** [comment]
Happenes to me too. Completely new wallet, only 4MB in size.

**Comment by valsha** [comment]
Yes, my NEW wallet - only 4MB

**Comment by valsha** [comment]
> Happenes to me too. Completely new wallet, only 4MB in size.
@VIEWVIEWVIEW You also used Feather wallet + hardware wallet (Ledger or Trrezor)?

**Comment by VIEWVIEWVIEW** [comment]
> @VIEWVIEWVIEW You also used Feather wallet + hardware wallet (Ledger or Trrezor)?

I'm using feather wallet, but without storing keys on a hardware wallet.

**Comment by valsha** [comment]
@Kukks can you please fix this problem? Thank you.

**Comment by Kukks** [comment]
> @Kukks can you please fix this problem? Thank you.

Altcoins are not my priority and there is no obvious fix since the nginx config is already set to allow up to 100m and the default dotnet size is set to ~28mb. I'll try explicitly disabling the file size in btcpay on some routes but I doubt it will be fixed.

**Comment by valsha** [comment]
Very strange, but this error is indicated by nginx
![image](https://user-images.githubusercontent.com/7966513/184893243-21f300fc-8fd4-4fff-bc2f-93eb8a11b1b4.png)

**Comment by dennisreimann** [comment]
What does `docker logs -f nginx` report when you try to upload the file?

**Comment by valsha** [comment]
@dennisreimann 
`2022/08/16 18:34:11 [error] 8#8: *8160 client intended to send too large body: 4396695 bytes`

**Comment by valsha** [comment]
Just check your https://github.com/btcpayserver/btcpayserver-docker/blob/master/Production/nginx.tmpl
I can see you have 
`client_max_body_size 100M;` in your `server {` config section
maybe you need to add this setting `client_max_body_size 100M;` to global `nginx.conf`in `http` section?
this will apply `client_max_body_size 100M;`  to all nginx server config.
just thinking out loud :)

**Comment by dennisreimann** [comment]
@valsha Yes, I think you are right. Added btcpayserver/btcpayserver-docker#699

**Comment by valsha** [comment]
Any ETA to the new release? Thanks.

**Comment by dennisreimann** [comment]
You can add the snippets from my pull request to the nginx.tmpl yourself, run `. ./btcpay-setup.sh -i` and verify it fixes the issue for you.

**Comment by valsha** [comment]
try it right now, run
1.` ./btcpay-down.sh`
2.` . ./btcpay-setup.sh -i`
nothing has changed, the error is still the same :(

**Comment by valsha** [comment]
just run 
`./btcpay-update.sh`
all is ok, no more 413 error

**Comment by dennisreimann** [comment]
Nice, glad it's working for you now! Thanks for the pointer 🎯👍
