### ISSUE TITLE
Improving labeling and consolidating issues

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#402]
This is a proposal to improve labeling system in this repository so that users who want to help and have a particular skill can help without spending much time and also to help us organize and prioritize issues better.

### Current labels
 - Backlog 
 - Bug
 - discussion-in-progress (don't really see a benefit of this one)
 - duplicate 
 - feature
 - help wanted 
 - invalid (removed, not helpful at all)
 - need-resolve-conflict (this is for PR's only maybe add PR-Conflict or something shorter)
 - next-release (good but we never really used it)
 - pr-need-fix sort (similar to pr-need-resolve-conflict)
 - preparing-to-close 
 - question
 - wontfix - quite useless we never used it
 - Zombie - quite useless we never used it (preparing to close is better)

### New label suggestions 

- Altcoin (issues related to alts, so that alt devs can easily find it, and BTCPay devs ignore it)
- Bug 
- Backlog (back-end issue)
- Documentation - issue relegated to doc repo
- Deployment - issues when deploying BTCPay Server
- Enhancement - Improves existing feature
- Integration - issues related to integration (WooCommerce, etc)
- Feature Request - New feature suggestion
- New-Feature - When a suggestion is good enough and it's decided to turn it into a feature
- PR-conflict (replaces PR-need-resolve-conflict and pr-needs-fix)
- UX/UI - Issues related to front end UX/UI/Design changes
- Question -  Question about BTCPay that can be resolved by non-technical BTCPay user
- Question-tech - Technical question (not an issue) about BTCPay that can be resolved only by a developer.

## Transferring issues

On another note GitHub now has the ability to transfer issues from one repo to another, so I suggest that we transfer issues that aren't related to particular repo to this main repository. 

## Summary

The proposal suggests we improve labeling issues and consolidate issues among different repositories.  Please discuss and propose your own labels.

I like organizing things, so I'll be happy to take on labeling the issues and transferring them if nobody else wants to do it. We've been doing labeling in Doc repo, and I noticed it improves productivity and enables me and other contributors to easier organize.

Yes I know this is an issue on how to organize the issues.

**Comment by NicolasDorier** [comment]
seems good to me

**Comment by bitcoinshirt** [comment]
Okay, @Kukks @rockstardev if you have any suggestions for labeling that would make your life easier to find and tackle issues let me know.

I can take over to go over issues and label them (the ones I'm sure how to label).
