### ISSUE TITLE
Invoice creation error re-ordering

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#4030]
When an invoice is being created using a specific payment method, and the rate fails, we are returning an incorrect error message. 
Currently, we return the wallet is not configured, when we should return that the rate is not available.

_Issue created from a [Mattermost message](https://chat.btcpayserver.org/_redirect/pl/5567eazpsi8h9dd48ooo58tejc) *by `@gauravp`*._

**Comment by HamroRamro** [comment]
https://github.com/btcpayserver/btcpayserver/pull/4039 <- PR for your review, sir @Kukks . 

cc: @pavlenex

**Comment by HamroRamro** [comment]
Good to close since its merged now. @Kukks @pavlenex @ndeet
