### ISSUE TITLE
Pay with "Ledger" or "Trezor" buttons

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#404]
This is based on direct feedback from one of our customers:

> Implement "Trezor Connect" and the equivalent for Ledger, if it exists. Basically, I believe the thought behind this is to have "Ledger" and "Trezor" buttons below the "Open in Wallet" button which would directly communicate to the customer's hardware wallet and fill in the values. 

I'm not entirely convinced this is doable or required, but I thought I would open this since its based on actual customer feedback. Open for discussion

**Comment by sigHash** [comment]
@astupidmoose This is promising, yet still under development

https://github.com/MelbourneDeveloper/Hardwarewallets.Net

**Comment by NicolasDorier** [comment]
We can't use Trezor Connect directly, we need complete control of the transaction.
https://github.com/MelbourneDeveloper/Trezor.Net is sufficient for our purposes, and I plan to use it.

We also need a way to forward the HID packet to the browser, which forward them to the trezor bridge.

**Comment by NicolasDorier** [comment]
https://doc.satoshilabs.com/trezor-tech/api.html#low-level-hid-api

**Comment by NicolasDorier** [comment]
So the idea is

`Trezor.NET <-> Websocket <-> trezord (bridge)`

The websocket bridge should be equivalent of the ledgerwebsocketbridge I developped for ledger. (https://github.com/btcpayserver/ledgerwebsocket)

**Comment by NicolasDorier** [comment]
Last, should not use 2 buttons. But 1 and the signing page need to detect whether it is trezor or ledger.

**Comment by NicolasDorier** [comment]
@rockstardev if it interest you... :D

**Comment by rockstardev** [comment]
I'm too drunk for this tonight, proceeding with ARM32

**Comment by NicolasDorier** [comment]
Ok so I digged a bit and noticed we are stuck if they don't remove this limitation https://github.com/trezor/trezord-go/issues/160 . We don't want to use trezor connect, it is serving a popup from their website.

**Comment by NicolasDorier** [comment]
Ok so after discussion it seems we need to use WebUSB connection to Trezor.

**Comment by Kukks** [comment]
I will as soon as I have a device to play with :)

**Comment by NicolasDorier** [comment]
@Kukks so actually we can do what we want with https://github.com/trezor/trezor-link !

**Comment by Kukks** [comment]
There is also this: https://github.com/karel-3d/trezor-webusb-js-experiment

**Comment by Kukks** [comment]
oh wait, same thing!

**Comment by pavlenex** [comment]
@astupidmoose How realistic is that people (besides that one person) need this? For me this is weird request, I never understood  why we need it.

**Comment by astupidmoose** [comment]
Can probably be closed. The idea was to make it easy to have a one-click pay button with hardware wallets. This doesn't seem needed anymore
