### ISSUE TITLE
[Bug]: Monero wallet

### ISSUE THREAD

**Issue by valsha** [btcpayserver/btcpayserver#4049]
### What is your BTCPay version?

1.6.7

### How did you deploy BTCPay Server?

Docker

### What happened?

Monero wallet is not working, but present
Using this tutorial to install Monero on the BTCPay server https://sethforprivacy.com/guides/accepting-monero-via-btcpay-server/

### How did you encounter this bug?

Upload wallet and key files to Monero

![image](https://user-images.githubusercontent.com/7966513/185322151-0e424285-dba6-4014-82bb-37caad664400.png)

### Relevant log output

```shell
docker logs --tail 100 btcpayserver_monero_wallet

2022-08-18 06:52:08.051 W Loading wallet...
2022-08-18 06:52:15.271 E !r. THROW EXCEPTION: error::wallet_files_doesnt_correspond
2022-08-18 06:52:15.272 E Wallet initialization failed: file /wallet/wallet does not correspond to /wallet/wallet.keys
```

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Kukks** [comment]
It looks to me that you uploaded a wallet file and a wallet keys file that were not exported from the same wallet.

**Comment by valsha** [comment]
I just re-create the view_only wallet and upload new files (walet+keys), it does not help :(

```
2022-08-18 07:21:21.751 W Loading wallet...
2022-08-18 07:21:22.881 E !r. THROW EXCEPTION: error::wallet_files_doesnt_correspond
2022-08-18 07:21:22.881 E Wallet initialization failed: file /wallet/wallet does not correspond to /wallet/wallet.keys
```

**Comment by valsha** [comment]
is this correct info?
```
chmod 666 /var/lib/docker/volumes/generated_xmr_wallet/_data/wallet.keys /var/lib/docker/volumes/generated_xmr_wallet/_data/password
chown 101:101 /var/lib/docker/volumes/generated_xmr_wallet/_data/wallet
```
because all my files in /var/lib/docker/volumes/generated_xmr_wallet/_data are:

```
-rw-rw-rw- 1 root root       7 Aug 18 07:20 password
-rw-rw-rw- 1 root root 4920871 Aug 18 07:20 wallet
-rw-rw-rw- 1 root root    1634 Aug 18 07:20 wallet.keys
```
root owner, maybe this is a  problem?

**Comment by Kukks** [comment]
Cc @sethforprivacy

**Comment by sethforprivacy** [comment]
@valsha As Kukks said, it looks like you're not even using corresponding wallet files. Can you try these steps and re-add them from scratch?

https://sethforprivacy.com/guides/accepting-monero-via-btcpay-server/#replacing-monero-view-only-wallet-files

After you do those steps line by line the files will also have the correct permissions.

If you're not sure how to do that you can re-export them following these steps:

https://sethforprivacy.com/guides/accepting-monero-via-btcpay-server/#create-a-view-only-monero-wallet-via-feather-wallet

**Comment by valsha** [comment]
@sethforprivacy 
I think the problem is....I am using Ledger, and when I am trying to create a view-only key, there is no any Secret view key :(
![image](https://user-images.githubusercontent.com/7966513/185412775-79147cda-79d9-44c1-9d86-e483c60770ec.png)

**Comment by sethforprivacy** [comment]
Ahh, yes, IIRC when you create the wallet you can choose to export the view key from the device or not -- you must have selected no in this case.

I would either try re-creating the wallet in Feather or creating one in the Monero desktop wallet (https://www.getmonero.org/downloads/#gui) and saying yes when it prompts to export the view key.

Then you can follow these instructions on generating a view-only wallet with the Monero desktop wallet: https://www.getmonero.org/resources/user-guides/view_only.html

**Comment by valsha** [comment]
@sethforprivacy 
Yes, I will create a new wallet in Feather not using Ledger, and then create these view-only keys.
Too bad it can't be used Ledger+Monero+BtcPay
All other cryptocurrencies (BTC, LTC, etc) i can use this way.
Thank you for your help.

**Comment by sethforprivacy** [comment]
As I said, I think you can do this you just need to create the wallet *and* allow it to export view keys from the Ledger.

More (somewhat outdated) info here: https://monero.stackexchange.com/questions/10500/why-do-i-have-to-export-the-private-view-key-every-time-i-use-my-ledger

**Comment by sethforprivacy** [comment]
Let's close this issue as this isn't relevant to BTCPay Server itself, but feel free to contact me here with more questions:

https://sethforprivacy.com/about/#how-to-contact-me
