### ISSUE TITLE
[Bug]: PayButton with custom amount use wrong logo path

### ISSUE THREAD

**Issue by ElucGeek** [btcpayserver/btcpayserver#4053]
### What is your BTCPay version?

I'm running BTCPay v1.6.3.0

### How did you deploy BTCPay Server?

Deployed with Umbrel

### What happened?

I think there is a mistake here:
https://github.com/btcpayserver/btcpayserver/blob/2e6246e385fccf606ecd3171644f8410b3ec61e2/BTCPayServer/Views/Shared/PayButton/PayButton.cshtml#L122

When I want to generate a PayButton with a custom amount it use a path for the BTCPay logo that doesn't exist. If I replace in the code by one of the logo listed [here](https://github.com/btcpayserver/btcpayserver-media/find/master) like btcpay-logo-white-txt.svg then it works again.

### How did you encounter this bug?

By creating a custom amount PayButton.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Thanks for reporting, fixed in #4054. For now you can use one of the files you mentioned.
