### ISSUE TITLE
BTC Lighting stop working

### ISSUE THREAD

**Issue by Pavlos584** [btcpayserver/btcpayserver#4056]
Hello, I am running a node on a vpn and I have a problem with this. I changed the ip address but the node still shows up on 1ml.com with the old ip address. It also happens to me that if my vpn drops out several times and then starts up, bitcoin lighting stops working and I have to restart the entire btcpayserver so that the payments start working again. How should I solve this?

**Comment by Pavlos584** [comment]
How should I solve this?

**Comment by pavlenex** [comment]
Please for support ask on chat.btcpayserver.org, we only handle bug reports here.
