### ISSUE TITLE
btcpayserver.org website

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#406]
This is a proposal for btcpayserver.org website

BTCPay Server needs a website which will provide important information and redirect people to important places.

Currently, we have a decent documentation, so the website should only provide general type of information (what it is, how it works, how is it different) and showcase the possibilities and features visually and redirect visitors to necessary places (download, deploy, demo, documentation)

Te website should:
- Be simple
- Not look like an ICO page or an enterprise crap
- Represent BTCPay what the project really is (free software build to free people)
- Mobile friendly and clean
- Informative but concise
- Redirect people to important places.

I will use this issue to put my own ideas, but community members, feel free to give your own suggestions if you have any.

**Comment by britttttk** [comment]
I think it's a good idea for more mainstream adoption... Mainly because it's hard for the average person to understand what BTCPay is from Github, and Gitbooks is also a lot of information to process for someone who might not be committed to using it yet. I do think it could be useful to link some of the existing resources. 

> -  Represent BTCPay what the project really is (free software build to free people)

Maybe some brief information relating open source software and BTCPay. The only owners of software are the users. Any user who wants to suggest an improvement can participate in discussion with other users and community developers. 

> -  Informative but concise

Why merchants shouldn't use a static QR code... 
Would be cool to see a really simple & short video (~30 s): 
1. Open Invoice > Pay Invoice > Invoice Paid Quickly
2. Video of the invoice system/POS

> -  Redirect people to important places.

 GitHub
 GitBook
 NBitStack
 Demo Stores

**Comment by bitcoinshirt** [comment]
Here's my first mock-up of the home page. 

![website](https://user-images.githubusercontent.com/36959754/48725918-fc935e80-ec2d-11e8-9977-54304f2ea562.png)

The idea is to immediately make clear what BTCPay is, how it works and showcase how it looks without visitor ever having to scroll. Meaning, all important elements go above the fold. That's not rocket-science everyone knows that.

@Kukks suggested[ this theme](https://demos.creative-tim.com/vue-argon-design-system/#/landing) (coloring can easily be changed). I think we can combine that one [with this](https://quickbooks.intuit.com/). I like an interactive way in which the second website showcases the 'product'. My suggestion is to showcase the checkout process on the right. Interactive and simple like in that example. Also [something like](http://thetheme.io/thesaas/demo/mailchimp.html) this suggested by @vortex is also cool

If there are any web-devs lurking, feel free to join the discussion.

**Comment by bitcoinshirt** [comment]
Basic paging structure:

- Home
- How it works(?)
- Download  
- Features
- Demo
- Community

Notes:
- How it works - we'll see if we have enough for this page
- Demo - can just be a page to showcase and link in an interactive ways to different applications.

**Comment by bitcoinshirt** [comment]
Just to keep everyone in the loop, @vswee designed a few demo pages [that can be found here.](https://btcpayserver.flat18.co.uk/). On the right hand side, there's a link "Versions" where you can see a few different versions he designed according to the feedback.

We're actively discussing new website on Slack in #website channel, but feedback via GitHub is always welcome. I'll keep updating this issue with important information. Everyone is welcome to join us and help, no matter the platform.

**Comment by rockstardev** [comment]
Demo pages look cool... let me know when you are at point where you need tester - would be fun to reverse roles a bit ;)

**Comment by Kukks** [comment]
One thing to test for is in a no js environment for those paranoid people

**Comment by bitcoinshirt** [comment]
After talking to myself on #website on Slack and looking at the website, I think we'll be able to squeeze all the important stuff onto a single page.

The page should be devided into sections:
- Section 1 - How it works
- Section 2 - Features 
- Section 3 - Integration and deployment options?
- Section 4 - Important CTA 
- Section 5 - Footer

## Section 1 - How it works
In the above the fold section of the size, with current version, we inform the visitor what BTCPay is, we show them a demo and provide a "Deploy" call to action. I think here everything looks okay.

![screen shot 2018-11-29 at 21 54 59](https://user-images.githubusercontent.com/36959754/49251564-f8332680-f421-11e8-9745-09cd657faaeb.png)

**Todo:** 
- Add non-intrusive scroll which leads people to Section 2. - Features. 

## Section 2 - Features
Display [wide variety of features](https://docs.btcpayserver.org/#features) in a tabbed box that doesn't take much space. I like how this is achieved [on this website](https://quickbooks.intuit.com/how-it-works/), but if others have better examples, feel free to chime in. This method shows the core features of the software in a concise way.

![screen shot 2018-11-29 at 21 38 01](https://user-images.githubusercontent.com/36959754/49251766-827b8a80-f422-11e8-87f3-8dc203df6cb6.png)

## Section 3 - Integrations
Can be similar to section 2, it should display all possible [integrations BTCPay offers](https://docs.btcpayserver.org/integrations/). 

## - Section 4 - Important CTA 
- Documentation
- Support and Community
- Contribute

![screen shot 2018-11-29 at 22 05 42](https://user-images.githubusercontent.com/36959754/49251925-f4ec6a80-f422-11e8-93a8-a00ec06e6f0a.png)

## - Section 5 - Footer
Easy one, just add links to all the important places.

## Challenges:
- Deployment - I think this is the only challenge. I have no idea how to pull this one of without scaring people away. The thing I hate is when open-source software has "download" or deploy button which leads to GitHub. It's such a UX nightmare for newbs. If anyone has a solution, please chime in.

**Comment by bitcoinshirt** [comment]
There's been quite a lot of progress regarding the website. We're getting close. 
If anyone follows this and wants to contribute, #website channel on BTCPay SLack is where you can follow with updates.

Preview is still [available here](https://btcpayserver.flat18.co.uk/)

**Comment by britttttk** [comment]
@bitcoinshirt some comments I have on the current site content:

* In the “Accept Bitcoin payments, 0% fees, no third party” box:
I would prefer to change the sentence: “With BTCPay you’re your own payment processor” to:
“With BTCPay you are your own payment processor” 
* LIVE DEMO: no link (any ideas what to put here?)
* HOW IT WORKS: video doesn’t work very well (any ideas what to put here?)
* DEPLOY A SERVER: Remove newline character before “We support diversity in deployment methods for users”. It adds a line but doesn't really separate, it’s just taking up white space.
* ALTCOINS: Remove generic “Another Bit of Information” items at the top of the list. Should we mention something like "You can also pay with altcoins other than the ones the merchant directly accepts using 3rd party altcoin payment conversion providers." 
ACCOUNTING: Add the QB Video. Can add more text if needed.
* PROCESS PAYMENTS FOR OTHERS: I was thinking about using text from the new third-party host doc. 
    * "A third-party host is an individual or a business which self-hosts a BTCPay instance and enables other users to register and use the server. The owner can add an unlimited amount of users and stores and allow those users to manage their stores independently and receive payments to their own wallets." also maybe:
    * "Third-party hosts play an important role in the ecosystem since they provide an easy and cost-effective way for users to try and use BTCPay. The role of honest hosts who provide free service to others is essential in the early phase of BTCPay Server adoption."

I think the content for each of the icons is pretty good and even though some have more information than others, I think that's fine for now, the community can always add more details.

**Comment by bitcoinshirt** [comment]
Great @britttttk, agreed with changes suggested, so here's to-do for the website **content**:

1. Change With BTCPay you are your own payment processor (intro box)
2. Put a link in "Live demo" http://mainnet.demo.btcpayserver.org/
3. How it works video is WIP by IB. I have 2 possible suggestions:
 3a. We remove how it works and add "GitHub" button
 3b. We add the [walk-through ](https://www.youtube.com/watch?v=ZIfJyq9RimM)video
4. Remove newline character before “We support diversity in deployment methods for users”. 
5. Remove mockup text from "Altcoin" feature box. (@britttttk the providers are still experimental, I'd avoid adding them)
6. Add [this video](https://www.youtube.com/watch?v=srgwL9ozg6c) to accounting feature box 
7. Add a bit more text in accounting:
> We make accounting easy. Use export functions to export invoices and import them into your accounting software. If you are QuickBooks user, you can try QuickBooks connector plugin and sync your QuickBooks company to your BTCPay. 
@britttttk feel free to build on this one or change it 
8. Add text o process payment for others feature box
> A third-party host is an individual or a business which self-hosts a BTCPay instance and enables other users to register and use the server. The owner can add an unlimited amount of users and stores and allow those users to manage their stores independently and receive payments to their own wallets.
Third-party hosts play an important role in the ecosystem since they provide an easy and cost-effective way for users to try and use BTCPay. The role of honest hosts who provide free service to others is essential in the early phase of BTCPay Server adoption
9. Add CTA to process payments for others feature box "[Learn More](https://docs.btcpayserver.org/deployment/thirdpartyhosting)
10. Add [payment button video](https://www.youtube.com/watch?v=MIWGvl6_WzI&feature=youtu.be) to payment button feature box image is nice maybe move it to the left side and video on the right, it would be good to keep both)

We're getting there. These and minor back-end improvements and we're good to go.

**Comment by vswee** [comment]
@britttttk What would we do without you! Fixed the typo errors.

How it works video really needs some love. 
Would an infographic be too tacky a solution for the "Process payments for others" block?

**Comment by britttttk** [comment]
@bitcoinshirt I agree with 1-10. 
My only comment is to rephrase 7 to this:

> We make accounting easy. Use the built-in export features, to manage all your invoice data and import it into your accounting software. If you are QuickBooks user, you can try QuickBooks connector plugin and sync your QuickBooks company to your BTCPay.

@vswee 
I would love to do an infographic for 3rd party hosts. Might be something to add at a later point also.

Can you please add the hand cursor to the invoice page (with +5-) where the "Pay BTCPay" button is. I see you've added it on plus and minus, but not on the button :)

**Comment by vswee** [comment]
Went with option 3b there for now. Rest of the list is sorted too (will double check that in a minute). @britttttk fixed the cursor and inversely bastardised the "process payments for others" text. Only say the word and I'll put it back the way you have it above.

**Comment by bitcoinshirt** [comment]
Proudly closing this one. What an amazing community effort.
All further website feedback and suggestions can be [forwarded to the appropriate repository].(https://github.com/btcpayserver/btcpayserver.github.io)
