### ISSUE TITLE
[Bug]:  UIX Monero

### ISSUE THREAD

**Issue by valsha** [btcpayserver/btcpayserver#4062]
### What is your BTCPay version?

1.6.9

### How did you deploy BTCPay Server?

Docker

### What happened?

UIX is not complete 

![image](https://user-images.githubusercontent.com/7966513/185747833-8b0de13d-74aa-48b6-8093-0106d26e75fa.png)

clicking on Monero wallet 

![image](https://user-images.githubusercontent.com/7966513/185747841-e5317e37-acdd-4358-b3e4-bb1b5433a89d.png)

all wallets are green now

default behaver (only active wallet is green)

![image](https://user-images.githubusercontent.com/7966513/185747847-9bcdd3a4-5f50-4137-9b0b-b7db6cc31791.png)

### How did you encounter this bug?

UIX is not correct

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Is this still an issue @valsha ?
