### ISSUE TITLE
[Bug]: Top-Up Invoice paidLate doesn't have a coresponding fiat value

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#4067]
### What is your BTCPay version?

v1.6.9.0

### How did you deploy BTCPay Server?

btcpayserver-docker

### What happened?

A customer paidLate a top-up invoice and the amout settled did not update to the corresponding fiat value, it also did not update upon marking it as settled.

This broke my webhook integration code (sending a 0.00 EUR fiat value for the invoice to my upstream provider)

### How did you encounter this bug?

1. user created a top-up invoice
2. waited 30 minutes
3. paid the invoice sometime after expiry

### Relevant log output

```shell
20.8.2022 16:33:35 	Creation of invoice starting
20.8.2022 16:33:35 	BTC_EUR: The rating rule is coingecko(BTC_EUR)
20.8.2022 16:33:35 	BTC_EUR: The evaluated rating rule is 21230.65
20.8.2022 16:33:35 	BTC (On-Chain): Payment method details creation took 0 milliseconds
20.8.2022 16:33:35 	BTC (Off-Chain): Payment method details creation took 0 milliseconds
20.8.2022 16:33:35 	BTC: Payment method unavailable (Lightning Network payment method is not available for top-up invoices)
20.8.2022 16:33:35 	BTC (LNURL-Pay): Payment method details creation took 13 milliseconds
20.8.2022 16:33:35 	Saving invoice took 25 milliseconds
20.8.2022 16:33:35 	Invoice WBdkhaef3eHGDP48Qs25ZA new event: invoice_created (1001)
20.8.2022 16:33:35 	BTC: Activating
20.8.2022 17:03:36 	Invoice status is Expired
20.8.2022 17:03:36 	Invoice WBdkhaef3eHGDP48Qs25ZA new event: invoice_expired (1004)
20.8.2022 18:56:44 	Invoice WBdkhaef3eHGDP48Qs25ZA new event: invoice_receivedPayment (1002)
20.8.2022 18:56:44 	Invoice status is Expired (paidLate)
20.8.2022 18:56:44 	Invoice WBdkhaef3eHGDP48Qs25ZA new event: invoice_paidAfterExpiration (1009)
20.8.2022 19:38:01 	Invoice WBdkhaef3eHGDP48Qs25ZA new event: invoice_paymentSettled (1014)
20.8.2022 19:38:11 	Invoice WBdkhaef3eHGDP48Qs25ZA new event: invoice_markedComplete (2008)
20.8.2022 19:47:15 	Invoice WBdkhaef3eHGDP48Qs25ZA is not monitored anymore.
```

### What browser do you use?

Mozilla Firefox 103.0.2

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by bolatovumar** [comment]
Couldn't repro on my end. 

@petzsch can you provide an example of the payload that went out that's wrong (don't need all of it, just the part that's wrong)? If you go to the invoice page and click on one of the webhook events it should give you the entire payload.

**Comment by petzsch** [comment]
The webhook payload is as expected (since the amount is never part of it). Just when querrying the invoice the amount stays sitting at 0.00 EUR (according to @Kukks on Mattermost this is intended behavoiour as the rate could have changed substantially between invoice creation (when rates are usuually pulled) and actual payment beyond expiry date.

Since there is no simple solution to this without breaking established workflows or introducing another config option and taken how much of an EDGE Case this is, I would be fine with documentanting this behavoiur as something that top-up users should be aware of when handling such invoices. :-)

**Comment by bolatovumar** [comment]
@petzsch created a PR with updated description here: https://github.com/btcpayserver/btcpayserver/pull/4095
