### ISSUE TITLE
[Bug]: Monero is not available in BTCPay widget

### ISSUE THREAD

**Issue by valsha** [btcpayserver/btcpayserver#4071]
### What is your BTCPay version?

1.6.9

### How did you deploy BTCPay Server?

Docker

### What happened?

Monero installed

![image](https://user-images.githubusercontent.com/7966513/186237107-bd0939ff-71cf-4eae-a332-259905e87306.png)

![image](https://user-images.githubusercontent.com/7966513/186237197-2ce1a9c7-69bf-4e70-8170-26216ed6a4f7.png)

**But not available in BTCPay widget**

![image](https://user-images.githubusercontent.com/7966513/186237520-cb1fdcc0-b913-418d-bf30-b7259a1246f4.png)

### How did you encounter this bug?

Using BTCPay widget

### Relevant log output

XMR: Unexpected exception (BTCPayServer.Services.Altcoins.Monero.RPC.JsonRpcClient+JsonRpcApiException: account index is out of bound at BTCPayServer.Services.Altcoins.Monero.RPC.JsonRpcClient.SendCommandAsync[TRequest,TResponse](String method, TRequest data, CancellationToken cts) in /source/BTCPayServer.Common/Altcoins/Monero/RPC/JsonRpcClient.cs:line 73 at BTCPayServer.Services.Altcoins.Monero.Payments.MoneroLikePaymentMethodHandler.CreatePaymentMethodDetails(InvoiceLogs logs, MoneroSupportedPaymentMethod supportedPaymentMethod, PaymentMethod paymentMethod, StoreData store, MoneroLikeSpecificBtcPayNetwork network, Object preparePaymentObject, IEnumerable`1 invoicePaymentMethods) in /source/BTCPayServer/Services/Altcoins/Monero/Payments/MoneroLikePaymentMethodHandler.cs:line 52 at BTCPayServer.Controllers.UIInvoiceController.CreatePaymentMethodAsync(Dictionary`2 fetchingByCurrencyPair, IPaymentMethodHandler handler, ISupportedPaymentMethod supportedPaymentMethod, BTCPayNetworkBase network, InvoiceEntity entity, StoreData store, InvoiceLogs logs, HashSet`1 invoicePaymentMethods) in /source/BTCPayServer/Controllers/UIInvoiceController.cs:line 410)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Kukks** [comment]
Please post the invoice event logs

**Comment by valsha** [comment]
> Please post the invoice event logs

Cay you please tell me where this log is located?
I just check `docker logs --tail 100 generated_btcpayserver_1` but no luck 
Thank you.

**Comment by valsha** [comment]
```
<html><body>
<!--StartFragment-->

8/23/2022 9:50:19 PM | XMR: Unexpected exception  (BTCPayServer.Services.Altcoins.Monero.RPC.JsonRpcClient+JsonRpcApiException:  account index is out of bound    at  BTCPayServer.Services.Altcoins.Monero.RPC.JsonRpcClient.SendCommandAsync[TRequest,TResponse](String  method, TRequest data, CancellationToken cts) in  /source/BTCPayServer.Common/Altcoins/Monero/RPC/JsonRpcClient.cs:line 73    at  BTCPayServer.Services.Altcoins.Monero.Payments.MoneroLikePaymentMethodHandler.CreatePaymentMethodDetails(InvoiceLogs  logs, MoneroSupportedPaymentMethod supportedPaymentMethod,  PaymentMethod paymentMethod, StoreData store,  MoneroLikeSpecificBtcPayNetwork network, Object preparePaymentObject,  IEnumerable`1 invoicePaymentMethods) in  /source/BTCPayServer/Services/Altcoins/Monero/Payments/MoneroLikePaymentMethodHandler.cs:line  52    at  BTCPayServer.Controllers.UIInvoiceController.CreatePaymentMethodAsync(Dictionary`2  fetchingByCurrencyPair, IPaymentMethodHandler handler,  ISupportedPaymentMethod supportedPaymentMethod, BTCPayNetworkBase  network, InvoiceEntity entity, StoreData store, InvoiceLogs logs,  HashSet`1 invoicePaymentMethods) in  /source/BTCPayServer/Controllers/UIInvoiceController.cs:line 461)
-- | --


<!--EndFragment-->
</body>
</html>
```

**Comment by Kukks** [comment]
It seems like you probably configured a wallet, set an account index on the store, and then maybe replaced the wallet, where the account is now not available?

**Comment by valsha** [comment]
@Kukks So what should I do now?
Because I did not do anything that the server would not allow, I uploaded the wallet through the upload form.

**Comment by Kukks** [comment]
Change the account on the UI

**Comment by valsha** [comment]
> Change the account on the UI

![image](https://user-images.githubusercontent.com/7966513/186855050-1e702931-4f66-4ef2-94e2-0d02f4fc1387.png)

is there something that needs to be changed?
Thanks.

**Comment by valsha** [comment]
> Change the account on the UI

@Kukks Can you give me some more information about what needs to be done? Thank you.

**Comment by Kukks** [comment]
@sethforprivacy can you assist?

@valsha Please remember that our primary focus is on Bitcoin only and that the coin's respective community should provide support and maintenance.

**Comment by sethforprivacy** [comment]
@valsha please follow these steps to replace the wallet files and ensure proper permissions:

https://sethforprivacy.com/guides/accepting-monero-via-btcpay-server/#replacing-monero-view-only-wallet-files

You likely either have bad wallet files or have incorrect permissions on those files somehow.
