### ISSUE TITLE
[Bug]: API Key Unauthorized

### ISSUE THREAD

**Issue by hiroashikawa** [btcpayserver/btcpayserver#4079]
### What is your BTCPay version?

I am running `© BTCPay Server v1.6.9.0 (Altcoins)`

### How did you deploy BTCPay Server?

I deployed BTCPayServer using Docker (No Reverse Proxy, behind Cloudflare)

### What happened?

I am currently trying to use the BTCPayServer API, and what I tried to do is generating an API Key, then putting an `Authorization` Header with the '**Basic SOMEKEYHERE**' as the Content, I also tried the API Key, but I always get a 401 Unauthorized.

### How did you encounter this bug?

1. Generate Legacy API Key
2. Set the Authorization Header with the Token provided, in any REST Client
3. Send the Request to the v1 API
4. 401 Unauthorized

### Relevant log output

```shell
2022-08-26 02:47:09.579 +00:00 [INF] AuthenticationScheme: Greenfield.APIKeys was challenged.
2022-08-26 02:47:10.061 +00:00 [INF] AuthenticationScheme: Greenfield.APIKeys was challenged.
```

### What browser do you use?

Latest Firefox (104.0 64-bit)

### Are you sure this is a bug report?

- [x] I confirm this is a bug report

**Comment by bolatovumar** [comment]
@hiroashikawa try `Authorization: token $apikey` instead like in the example here: https://docs.btcpayserver.org/Development/GreenFieldExample/#create-a-new-store

**Comment by hiroashikawa** [comment]
> @hiroashikawa try `Authorization: token $apikey` instead like in the example here: https://docs.btcpayserver.org/Development/GreenFieldExample/#create-a-new-store

That doesn't seem to work. Still getting 401'd

**Comment by dennisreimann** [comment]
Your description mentions the Legacy API key. For the Greenfield API you need to create one via the Account Settings > API Keys page.

**Comment by hiroashikawa** [comment]
Ah, Alright thanks, my mistake then.
