### ISSUE TITLE
[Bug]: Installing Plugins is not handled

### ISSUE THREAD

**Issue by arbadacarbaYK** [btcpayserver/btcpayserver#4094]
### What is your BTCPay version?

1.6.8.0 

### How did you deploy BTCPay Server?

Umbrel/Citadel <-> Cloudflare

### What happened?

Istallation of Plugin fails

### How did you encounter this bug?

choose plugin to install (e.g. NFC) -> Restart needed 

not possible like documented https://docs.btcpayserver.org/FAQ/ServerSettings/#how-to-restart-btcpay-server
 -  referring to maintainance->restart which isnt available anymore
 -  ssh-commands not working anylonger on citadel/umbrel
 
Restarting node through GUI cancels request to install the plugin 

### Additional information

https://github.com/getumbrel/umbrel/issues/1495#issue-1359307810

### Are you sure this is a bug report?

- [x] I confirm this is a bug report

**Comment by leesalminen** [comment]
I had to upgrade to v1.6.10 for v1.0.4.0 of the nfc plugin to install properly.

**Comment by arbadacarbaYK** [comment]
Yes its a feature of the new version - which is installed, see 
What is your BTCPay version?
1.6.8.0

**Comment by Kukks** [comment]
Umbrel is not configured to handle btcpay plugins yet

**Comment by arbadacarbaYK** [comment]
Cloned to citadel 🥹 Could you update the documentation on the restarting process anyway, please 🙏🏻

**Comment by AaronDewes** [comment]
> Umbrel is not configured to handle btcpay plugins yet

As Citadel developer, what configuration would be required?

We already set `BTCPAY_PLUGINDIR: /data/plugins` and have `/data` as a persistent mounted volume, but it still isn't working, I think it's the same on Umbrel.

**Comment by Kukks** [comment]
Since you are not using our docker deployment method, ( we detect via the `BTCPAY_DOCKERDEPLOYMENT: "false"`), we cannot automate restarting btcpay, which is needed after installing/updating/removing plugins. Curious to hear if you have any possible solutions.

My solution would be to build a specific plugin for "Citadel" where it reimplement our restart functionality but calling your stack's equivalent.

**Comment by AaronDewes** [comment]
My problem is that if I do a manual restart, plugins still do not get installed. Is there a good way to debug this?

**Comment by arbadacarbaYK** [comment]
Can we (users) have some love on this topc, please ? Would like to use our btcpayshop WITH nfc on the conferences coming..

**Comment by dennisreimann** [comment]
I just verified with someone, that they are able to install an run plugins (LNbank in this case) without problems on Umbrel. 

> Could you update the documentation on the restarting process anyway, please

@arbadacarbaYK The restart section hasn't been removed and it is still present in regular installs. So I assume this must be related to the Umbrel/Citadel deployment. 

Maybe the SSH key for the maintenance features isn't set up there?

**Comment by arbadacarbaYK** [comment]
Yes, given in the description its about Umbrel/Citadel and the NFC-Plugin.. On manual restart the plugin is not intsalled. If restart has to be done somehow special it should be in the documentation. The documented way doesnt work here, so Plugin not usable on Umbrel/Citadel

**Comment by slaapyhoofd** [comment]
> I just verified with someone, that they are able to install an run plugins (LNbank in this case) without problems on Umbrel.
> 
> > Could you update the documentation on the restarting process anyway, please
> 
> @arbadacarbaYK The restart section hasn't been removed and it is still present in regular installs. So I assume this must be related to the Umbrel/Citadel deployment.
> 
> Maybe the SSH key for the maintenance features isn't set up there?

So how did they restart in Umbrel? Because I also can't get it to work with the NFC plugin...

**Comment by ElucGeek** [comment]
Hello, I'm in the same boat, any update on this case?

**Comment by leesalminen** [comment]
> Hello, I'm in the same boat, any update on this case?

I had to update BTCPayServer to the latest version in order to install the LNURL NFC plugin on my Umbre. 

On Umbrel, I did this by adding the LNURL NFC plugin to the install queue in BTCPayServer, then editing `~/umbrel/app-data/btcpay-server/docker-compose.yml, under `services` -> web, I changed `image: btcpayserver/btcpayserver:1.6.3@sha256:fb514c417933fc088dec2fb841f5d3572e35429412e79bb12b25fb4437519162` to `image: btcpayserver/btcpayserver:1.6.12@sha256:2115512b5e11b284efeb58f030ce246e7549ff4350573c71e22b16b177a14d5f`. I saved the changes to that file, then ran sudo ~/umbrel/scripts/start to restart the docker container.

BTCPayServer then showed the plugin as installed:

![photo_2022-10-28 22 15 25](https://user-images.githubusercontent.com/3018359/198813393-043c3a53-7623-497d-a5ea-f7470e2d61a8.jpeg)

**Comment by ElucGeek** [comment]
Umbrel just update on their app store the latest version, now the NFC plugin is installed but still not working when I scan a Boltcard. I have to investigate and open a separate issue if needed.

**Comment by leesalminen** [comment]
> > Hello, I'm in the same boat, any update on this case?
> 
> I had to update BTCPayServer to the latest version in order to install the LNURL NFC plugin on my Umbre.
> 
> On Umbrel, I did this by adding the LNURL NFC plugin to the install queue in BTCPayServer, then editing `~/umbrel/app-data/btcpay-server/docker-compose.yml, under `services`-> web, I changed`image: btcpayserver/btcpayserver:1.6.3@sha256:fb514c417933fc088dec2fb841f5d3572e35429412e79bb12b25fb4437519162`to`image: btcpayserver/btcpayserver:1.6.12@sha256:2115512b5e11b284efeb58f030ce246e7549ff4350573c71e22b16b177a14d5f`. I saved the changes to that file, then ran sudo ~/umbrel/scripts/start to restart the docker container.
> 
> BTCPayServer then showed the plugin as installed:
> 
> ![photo_2022-10-28 22 15 25](https://user-images.githubusercontent.com/3018359/198813393-043c3a53-7623-497d-a5ea-f7470e2d61a8.jpeg)

This workaround is no longer required due to https://github.com/getumbrel/umbrel-apps/pull/234. Users can now update BTCPayServer to the latest version (v 1.6.12.0) on their Umbrel from the App Store.

**Comment by pavlenex** [comment]
Does this mean your concerns have been addressed and we can close this issue?

**Comment by slaapyhoofd** [comment]
> Does this mean your concerns have been addressed and we can close this issue?

I updated BTCPay server on Umbrel, and the NFC plugin was installed.
There was also an update to the NFC plugin, installed that and seems to work after running a manual restart:

`~/umbrel/scripts/app restart btcpay-server`

**Comment by arbadacarbaYK** [comment]
Fix works - only on Umbrel so far, hopefully tomorrow on Citadel as well.
Would be good to include tests for the node implementations and include this info wjem announcing features.
Documentation is not updated yet
