### ISSUE TITLE
[Bug]: Invoice display broken on Shopify

### ISSUE THREAD

**Issue by BenGWeeks** [btcpayserver/btcpayserver#4105]
### What is your BTCPay version?

BTCPay Server: v1.6.3.0 (on Umbrel)
Store: https://robotechy.com/

### How did you deploy BTCPay Server?

Umbrel Raspberry Pi docker image.

### What happened?

We have our Umbrel node server the JS file over HTTPS as per https://jorijn.com/installing-nginx-reverse-proxy-with-ssl-certificate-umbrel-btcpayserver/. I noticed that the JS file was failing to load for two reasons, (1) our SSL had expired, and (2) the URL to the JS file has been changed. The JS file is now loading (after updating the link), and we see the "Pay with BTCPay" icon again. However, when you click on it, it just has "Displaying Invoice..." but nothing actually pops up.

### How did you encounter this bug?

1. Go to https://robotechy.com
2. Go through to the checkout for an item (feel free to enter "BTCPayServer" and will tell son to ignore order).
3. Choose "BTCPay Server" method.
4. Click on "Pay with BTCPay".

### What browser do you use?

Browser(s): Edge and Chrome

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by BenGWeeks** [comment]
I do see the warning:

`DevTools failed to load source map: Could not load content for https://<domain>/bundles/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Comment by BenGWeeks** [comment]
I also notice that the JS file, located at:

`https://somedomain/stores/D6rzmTybqsxWAgpcv45kuwQBT7T6J8wUHPBT8C8mWtWZ/plugins/shopify/shopify.js`

has the following first line:

`var BTCPAYSERVER_URL = "http://somedomain";`

However, it's using HTTP not HTTPS.

**Comment by bolatovumar** [comment]
@BenGWeeks looks like everything is actually working correctly in your case except at the very end we don't show the actual iframe that allows you to make a payment.

If you run `window.btcpay.showFrame()` in the console after clicking the BTCPay pay button it will in fact show up.

![Capture](https://user-images.githubusercontent.com/1934678/189040337-f4fd573c-ab2f-4635-b3dd-10f80c078931.PNG)

**Comment by bolatovumar** [comment]
@BenGWeeks if you can modify the `shopify/btcpay-shopify.js` file and add that one line of code that I added to it then it should work.

**Comment by bolatovumar** [comment]
> It looks like some automated tests are failing for some reason. 

tests are unrelated, you can ignore it
