### ISSUE TITLE
OrderId Missing in list of Placeholders for the new email feature

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#4112]
I had a user on Telegram who wants to use the WooCommerce generated OrderID in his confirmation email - If I read the source correctly (BTCPayServer/HostedServices/StoreEmailRuleProcessorSender.cs) we only have:

```
    private string Interpolator(string str, InvoiceData i)
    {
        //TODO: we should switch to https://dotnetfiddle.net/MoqJFk later
        return str.Replace("{Invoice.Id}", i.Id)
            .Replace("{Invoice.StoreId}", i.StoreId)
            .Replace("{Invoice.Price}", i.Amount.ToString(CultureInfo.InvariantCulture))
            .Replace("{Invoice.Currency}", i.Currency)
            .Replace("{Invoice.Status}", i.Status.ToString())
            .Replace("{Invoice.AdditionalStatus}", i.AdditionalStatus.ToString());
    }
```

Can we get OrderId added to the list? Or was there a reason not to include it? @kukks

_Issue created from a [Mattermost message](https://chat.btcpayserver.org/_redirect/pl/iuxtar9fzprc8gti8nf5cy9qoo) *by @petzsch*._

**Comment by o3k1n** [comment]
I could use BTCPrice placeholder very much (denominated in Sats would be nice)
