### ISSUE TITLE
`User can input custom amount` in POS should be disabled by default

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#4118]
I believe currently it's on by default after watching the Voltage BTCPay workshop demo.

**Comment by bolatovumar** [comment]
Yeah, it is on by default. Hasn't it always been like this?

**Comment by dstrukt** [comment]
I think so, but I'm not sure why it's always been on by default considering the use case of letting a customer determine their own price is a smaller % for sure.

**Comment by daviogg** [comment]
Don't know if is needed but I created a pull request, let me know if are needed some other changes or to discuss more :)

**Comment by simpson420b** [comment]
Where's my money
