### ISSUE TITLE
Why doesn't payout move to "In Progress" after broadcasting it or "Completed" after settled?

### ISSUE THREAD

**Issue by olimits7** [btcpayserver/btcpayserver#4123]
### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/4110

<div type='discussions-op-text'>

<sup>Originally posted by **olimits7** September  8, 2022</sup>
Hi,

I created an invoice refund and then broadcasted this payout successfully but it still shows under "**Awaiting Payment**" instead of moving over to "**In Progress**".  And then when refund gets settled it's not moving over to "**Completed**" status.  Shouldn't this happen automatically within **BTCPay Server**?

https://docs.btcpayserver.org/Payouts/

Thank you!</div>

**Comment by Kukks** [comment]
It should happen automatically IF
* you used the btcpay send wallet UI
* you sent EXACTLY the same amount of the payout (as per https://github.com/btcpayserver/btcpayserver/discussions/4110#discussioncomment-3657056, you used `Subtract fees from amount`, which changes the amount sent)

**Comment by olimits7** [comment]
> It should happen automatically IF
> 
>     * you used the btcpay send wallet UI
> 
>     * you sent EXACTLY the same amount of the payout (as per [Why doesn't payout move to "In Progress" after broadcasting it or "Completed" after settled? #4110 (reply in thread)](https://github.com/btcpayserver/btcpayserver/discussions/4110#discussioncomment-3657056), you used `Subtract fees from amount`, which changes the amount sent)

@Kukks thanks for the reply!

- Just to confirm, the "**Issue Refund**" function uses the BTCPay send wallet UI, right?  I notice it looks exactly the same as the UI that I see under "**Wallet > Send**"
- What's the best way to send the exact/same amount so this works properly?
  - When I uncheck "**Subtract fees from amount**" it doesn't let me "**Sign Transaction**" because it keeps showing this "**You are sending your entire balance to the same destination, you should subtract the fees**" message.

Thank you!

**Comment by olimits7** [comment]
**Update:** I was able to test this more and it does work properly when I don't check "**Subtract fees from amount**".  It didn't let me submit before because I didn't have a high enough balance in my BTCPay Server, but it seems to be working properly now. Ty.
