### ISSUE TITLE
[Bug]: I cannot create payment request invoices

### ISSUE THREAD

**Issue by leblitzdick** [btcpayserver/btcpayserver#4125]
### What is your BTCPay version?

v1.6.10 (rpi)
v1.6.9   (ubuntu)

### How did you deploy BTCPay Server?

two installations same error

raspberrypi no docker
ubuntu 18.4.6 no docker

both postgressql

### What happened?

I cannot create payment request invoices 

### How did you encounter this bug?

when i create a payment request, there is no storeid choice, and in the next step when i choose "invoice" an "+ create invoice" an error occoured  "You need to select a store before creating an invoice." and i am back on the dashboard 

### What browser do you use?

brave v1.43.93

### Additional information

https://user-images.githubusercontent.com/22169878/190681734-acb84311-b140-481d-9a2c-9ee05822955a.mp4

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
So you need to click on `view` but indeed this is a bug, because we shouldn't do invoice filtering, I don't even think that invoice filtering within a payment request is useful.

**Comment by pavlenex** [comment]
@dennisreimann this seems to be cause with the our new store centric approach and somehow we missed the `invoice` filter.

**Comment by leblitzdick** [comment]
OK, this problem is gone, but there is an following problem. when i try to push the "Pay invoice" button the _"invoice qr code box"_ doesn't show up. i think invoice and payment request are not connected, because search invoice by payment request also ends in no result.

https://user-images.githubusercontent.com/22169878/190846843-1222ab60-a655-4a6d-982a-e4d55c18a5fe.mp4

**Comment by dennisreimann** [comment]
Please note that in the latest video you are creating an invoice that is not connected to the payment request. Invoices connected to payment requests can only be created by using the "Pay Invoice" button on the payment request page.

However, can you see the log for errors which might have occured in the last step of your video, in which you try using the "Pay Invoice" button — this should indeed create a new invoice for that payment request.

**Comment by leblitzdick** [comment]
you're right, there was a network problem that block my "_invoice box_".

thanx for your help
