### ISSUE TITLE
Consolidate Access Token Pairing Permission view

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#4133]
Currently when creating an Access Token, this is the flow

1. Hit `Create Token` CTA
2. Token Details
<img width="996" alt="Screen Shot 2022-09-18 at 7 17 42 PM" src="https://user-images.githubusercontent.com/6250771/190940359-f02cc9a5-e94d-47de-b7b3-b2adcd51f185.png">
3. Choose Store Pairing
<img width="564" alt="Screen Shot 2022-09-18 at 7 19 04 PM" src="https://user-images.githubusercontent.com/6250771/190940338-4d560257-4217-48c7-93a9-6c3747dce619.png">

I can see an instance of why you might want to create a token for another store from this view, but it seems unnecessary and redundant.

I propose removing that Pairing view, and just associating the token to the current store you're creating it from.
- Removes the additional Pairing view step
- Less bugs or permissions, etc.. to potential worry about, and/or test

Open to hearing opposing opinions as well, but wanted to toss this one out there.

**Comment by cvchris** [comment]
Hello, I am willing to implement this as a first issue. Is it still active?

**Comment by dennisreimann** [comment]
@cvchris yes, go ahead and feel free to reach out to me (on our Mattermost or here) if you have questions!

**Comment by Kukks** [comment]
Keep in mind that this page is often linked to from an integration to
"pair", which often does not know about stores and thus needs the store
selector up front. But, we can hide it if it was loaded from inside the
store obviously

**Comment by dennisreimann** [comment]
Good point, @kukks. I think something similar like we did in #3880 would work well here too.

**Comment by dstrukt** [comment]
Agreed @dennisreimann!
