### ISSUE TITLE
[Bug]: Error parsing reponse when using NFC Plugin

### ISSUE THREAD

**Issue by gorrdy** [btcpayserver/btcpayserver#4152]
### What is your BTCPay version?

v1.6.10.0 + LNURL NFC Support v1.0.4.0

### How did you deploy BTCPay Server?

Lunanode automatic deployment

### What happened?

If I pay with LNURLw NFC or LNURLw, the BTCPayServer send error code 500 even when the payment is successful and the NFC plugin struggles with parsing the response and the alert at the end is triggered in the try/catch at the bottom of lnurlwnfc.js. The payment is successful but it is annoying to close the javascript alert every time.

I hardly found the source code there
https://github.com/Kukks/btcpayserver/tree/plugins/collection/Plugins/BTCPayServer.Plugins.NFC

`sendData: function (lnurl) {

            this.submitting = true;
            //Post LNURLW data to server
            var xhr = new XMLHttpRequest()
            xhr.open('POST', window.lnurlWithdrawSubmitUrl, true)
            xhr.setRequestHeader('Content-Type', 'application/json')
            xhr.send(JSON.stringify({lnurl, destination: this.$parent.srvModel.btcAddress}))
            const self = this;
            //User feedback, reset on failure
            xhr.onload = function () {
                if (xhr.readyState === xhr.DONE) {
                    console.log(xhr.response);
                    console.log(xhr.responseText);
                    self.scanning = false;
                    self.submitting = false;

                    if(self.readerAbortController) {
                        self.readerAbortController.abort()
                    }

                    try {
                        var data = JSON.parse(xhr.response)

                        if(data && data.status == "ERROR") {
                            alert(data.reason)
                        }
                    } catch (err) {
                        alert("Error parsing response.")
                    }
                }
            }
        }`

### How did you encounter this bug?

1. Created a btcpayserver invoce via Keypad only app
2. Tried to pay via (NFC) LNURLw tag
3. Payment is successful but the alert appeared

### What browser do you use?

Safari 16.0

### Additional information

<img width="457" alt="Snímek obrazovky 2022-09-22 v 10 06 46" src="https://user-images.githubusercontent.com/80678558/191693026-ec78a1b4-6819-4c1b-8a65-e22756b3ad84.png">
<img width="470" alt="Snímek obrazovky 2022-09-22 v 10 06 57" src="https://user-images.githubusercontent.com/80678558/191693036-4d832daa-58bc-4cbb-9cc6-c7919ba708c6.png">
<img width="351" alt="Snímek obrazovky 2022-09-22 v 10 07 06" src="https://user-images.githubusercontent.com/80678558/191693031-e9060262-0406-41cd-a028-99b9740f0603.png">

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by PeterRounce** [comment]
I am experiencing the same issue.  
BTCPay Server shows the message `Error parsing response.` when the lnurlw service returns `{"status": "OK"}`

**Comment by pavlenex** [comment]
@Kukks Can you look at this one? Should I move it to /plugin repo?

**Comment by gorrdy** [comment]
Thanks @Kukks for looking into this issue. I just updated the plugin and tried both LNURLw and NFC LNURLw payment with my btcpayserver. 

It seems to be resolved for the LNURLw entered manually but not for **NFC** LNURLw

Is this possible?
![image](https://user-images.githubusercontent.com/80678558/192518811-34f2f2c4-a027-4d5e-a0f7-63ee2af50aa7.png)

**Comment by Kukks** [comment]
That can't be as it runs the same code 😅 Must be some caching issue on the device..

**Comment by gorrdy** [comment]
Thanks for the information, I cleared cache and cookies, reset the NFC access permission in Chrome and it's working now. Thanks a lot!

**Comment by PeterRounce** [comment]
I cleared cookies and cache. The issue persists for me.

Also tested on a diffferent device (without NFC) and the LNURLw link gives the same error dialog.

Is there some logging or a way you can recommend for gathering more data on this.

Still very much an issue.

**Comment by gorrdy** [comment]
Try to reset NFC permission in your browser.I'm not sure if clearing the cache or reseting the permission did the trick. Also you can test it here, there is a updated version of btcpayserver that works well with my devices.
https://btcpayserver.cz/apps/4VQpFMQ6kbea5N5u5WZ14GrD2N3p/pos

**Comment by PeterRounce** [comment]
Thank you for your POS link.

### My POS https://btcpay.whitewolftech.com/apps/2wREaZ7ziMxDU6aShk4tHZCUYySh/pos
**There is an error dialog** using both boltcard NFC payment and lnbits LNURLw text payment.
BTCPay Server v1.6.11.0
![Screenshot 2022-09-28 07 49 53](https://user-images.githubusercontent.com/99006127/192708282-99fa3abb-34ad-4c37-ba59-2137c6b73a32.png)

### Your POS
https://btcpayserver.cz/apps/4VQpFMQ6kbea5N5u5WZ14GrD2N3p/pos
There is **no error dialog** both boltcard NFC payment and lnbits LNURLw text payment.

**Comment by gorrdy** [comment]
Update the plugin, in 1.0.4.0 there is the bug we discussed earier.

**Comment by PeterRounce** [comment]
Updating "LNURL NFC Support" to v1.0.5.0 followed by clearing cookies and cache fixed the issue. Thanks for your help.

**Comment by vindard** [comment]
I had this issue as well. Clearing the cache did it for me, thanks!
