### ISSUE TITLE
[Bug]: LNBank's LNURL has incorrect a text/identifier format in metadata

### ISSUE THREAD

**Issue by Perlover** [btcpayserver/btcpayserver#4165]
### What is your BTCPay version?

v1.6.10

### How did you deploy BTCPay Server?

Docker

### What happened?

Inside the LNBank plugin, I created wallets. When I try to pay LNURL via SBW wallet (the wallets Phoenix & Zeus work without error), I get an error: "requirement failed: text/email or text/identity format is wrong". At first I thought it was an incorrect SBW operation. I started researching the LNURL format and got from BTCPay server (the field "Callback URL" of 1st LNURL response):

```
{"callback":"https://domain.com/api/v1/lnbank/lnurl/ff4d4d8d-6fc4-40be-844f-992202bf5308/pay","metadata":"[[\"text/plain\",\"Bank # 1\"],[\"text/identifier\",\"ff4d4d8d-6fc4-40be-844f-992202bf5308\"]]","tag":"payRequest","minSendable":1000,"maxSendable":612000000000,"commentAllowed":615}
```

The [LUD-16](https://github.com/fiatjaf/lnurl-rfc/blob/luds/16.md) has description about `text/identifier` field of metadata:

> If providing such a scheme, SERVICE MUST add to the metadata JSON array either a text/email entry or a text/identifier entry, as in examples below:
>
>[
>    "text/identifier", // indication that this payment link is associated with an internet identifier string
>    content // an internet identifier string in standard user@site.com format
> ]

But the LNBank plugin generates a text/identifier of the GUID format, which really violates the standard.

### How did you encounter this bug?

1. Install LNBank plugin
2. Create wallet
3. Inside wallet click Receive button
4. There is text with links: "Alternatively you can use LNURL to receive to your wallet."
5. Click a link "LNURL"
6. Try to pay through SBW. Or try to decode LNURL by service https://lightningdecoder.com/ and after to see a response of "Callback URL" field

### What browser do you use?

Firefox

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Thanks for reporting and coming up with such a detailed description — really appreciate that! Can you try v1.3.1?

**Comment by Perlover** [comment]
> Thanks for reporting and coming up with such a detailed description — really appreciate that! Can you try v1.3.1?

Thanks! I tested under BTCPay v1.6.11 & LNBank v1.3.1 - now everything works! I saw metadata object of "Callback URL" field of LNURL - there a "text/identifier" JSON property was deleted! From SBW wallet it works! Thanks!

**Comment by dennisreimann** [comment]
Thanks for the feedback!
