### ISSUE TITLE
[Bug]: LNBank LNDHub, can't load transactions

### ISSUE THREAD

**Issue by vindard** [btcpayserver/btcpayserver#4168]
### What is your BTCPay version?

BTCPayServer: v1.6.11.0
LNBank: v1.3.1.0 

### How did you deploy BTCPay Server?

LunaNode, with lnd

### What happened?

This happens in two instances with BlueWallet:
1. When I try to import an existing LNBank wallet with transactions, it fails to import with this error popping up
2. After I successfully import a new wallet with no transactions and create my 1st invoice I get this. Note, if the invoice is paid, the balance view updates in BlueWallet, but if I "Pull to refresh" the txns this error pops up

(cc @dennisreimann)

![lnbank-lndhub-error](https://user-images.githubusercontent.com/17693119/192541899-4f93fec8-8046-4875-ad3f-04104f476cc8.jpg)

### How did you encounter this bug?

When using LNBank's LndHub feature

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Thanks for reporting! This is fixed with [v1.3.2](https://github.com/dennisreimann/btcpayserver/releases/tag/BTCPayServer.LNbank/v1.3.2).
