### ISSUE TITLE
Pruning not working

### ISSUE THREAD

**Issue by way2many** [btcpayserver/btcpayserver#417]
Hi all,

I try to test btcpay docker on an OVH VPS server with 20gb. Pruning is therefore activated with "opt-save-storage-xxs". This doesn't work unfortunately as every two days I need to restart the btcpay server to actually prune otherwise it just slowly take the full 19gb and then bitcoind is stuck.

I tried the btcpay-setup.sh multiple times to be sure that "opt-save-storage-xxs" is taken into account and there is never a problem. See my last run

```
`-------SETUP-----------
Parameters passed:
BTCPAY_HOST:my-real-host
BTCPAY_HOST_SSHKEYFILE:/root/.ssh/id_rsa_btcpay
LETSENCRYPT_EMAIL:my-real-email
NBITCOIN_NETWORK:testnet
LIGHTNING_ALIAS:
BTCPAYGEN_CRYPTO1:btc
BTCPAYGEN_CRYPTO2:
BTCPAYGEN_CRYPTO3:
BTCPAYGEN_CRYPTO4:
BTCPAYGEN_CRYPTO5:
BTCPAYGEN_CRYPTO6:
BTCPAYGEN_CRYPTO7:
BTCPAYGEN_CRYPTO8:
BTCPAYGEN_CRYPTO9:
BTCPAYGEN_REVERSEPROXY:nginx
BTCPAYGEN_LIGHTNING:none
BTCPAYGEN_ADDITIONAL_FRAGMENTS:opt-save-storage-xxs
BTCPAY_IMAGE:
ACME_CA_URI:https://acme-v01.api.letsencrypt.org/directory
```

Is it also normal that after a +- 10 minutes of sync I'm already between 11 and 17% and then it just restart from 0%?

I'm willing to give root access to any developer as I don't care about this server. It's just for testing.

Thank you.

**Comment by NicolasDorier** [comment]
interesting. I can take a look, can you come on the slack and give me keys to your server?

**Comment by way2many** [comment]
Would love to but it's timing out. http://slack.forkbitpay.ninja/ is redirecting to http://slack.btcpayserver.org/ which is not responding. Any other way I could send you the access?

**Comment by Kukks** [comment]
@way2many  Use this for now till we sort out this invite issue https://join.slack.com/t/forkbitpay/shared_invite/enQtNDg3MjQwMDk0MzQwLTgzYjY2OGRhZGRlNTNjNWViNDZhN2QzYmJiMTM1N2E0ZDExYTBiZDViMTE5YmNlYmE0YjZiYWY2YzJkYTVhNzU

**Comment by way2many** [comment]
For those that might encounter the same issue; Nicolas Dorier had a look at the server and the configuration was fine but the log file was taking over all the harddrive. After deleting it, restarting the server and adding a swap file (the VPS has only 2Gb of RAM) the sync went without any issue or restart.

I re-installed the VPS two times and I've added the swap from the very first beginning and both times the sync completed in a few hours with no issues.
