### ISSUE TITLE
Add donate link to sidebar

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#4173]
BTCPay Server Foundation can now accept donations from individuals through OpenSats. This is big for two reasons:
- Finally individual users can donate
- Entities can also donate through OpenSats and get tax deduction if they're US entity.

For this reason, it would be nice if we could add a link or a button somewhere (sidebar?) that can guide people through process of donating? A simple thing would just be linking to [btcpayserver.org/donate](https://btcpayserver.org/donate/) where we could have a step by step donation process (Individual vs Corporate donation pop up or something). Thoughts? A tracking issue for UX on btcpayserver.org [here](https://github.com/btcpayserver/btcpayserver.org/issues/173)

We can potentially utilize "what's new" section for 1.7.0 or minor release in between to notify people of this new possiblity.

_Issue created from a [Mattermost message](https://chat.btcpayserver.org/_redirect/pl/f5mbnhm38b8zi8xqyrwxbet8na) *by @pavlenex*._

**Comment by dstrukt** [comment]
Only additional question I have .. how prominent do we want this to be? I ask because I could potentially see it being on the sidebar or the bottom bar along with the other socials, etc...

**Comment by pavlenex** [comment]
Sure, I don't have a preference. I originally suggested the sidebar because I thought the footer is already stuffed enough, but whatever you feel is best `donate` certainly isn't a core functionality for the user, so if you can fit it in somehow, I woudln't mind it. Perhaps dashboard could be another solution, I don't know :) ?

**Comment by dennisreimann** [comment]
I think putting it in the sidebar might be distracting, because this isn't a core functionality and it'd also link to the website and out of the app. 

Instead and as @dstrukt suggested, let's make it a link in the footer ("Support the project" besides "Copy Tor URL" – an icon for that would be nice). 

In addition to that we can also have a link in the supports section, like: "View all supports" or "donate to BTCPay Server".

**Comment by dstrukt** [comment]
Maybe in the future it might make sense to put tiny links at the bottom of the sidebar, but agree with @dennisreimann certainly for for the time being.

However I think I prefer pav's original wording .. e.g. `[heart icon] Donate` would probably be sufficient and it a bit more succinct than `Support the project`.
