### ISSUE TITLE
Remove direct link functionality from the File Storage system and remove the link to temp link but leave the functionality

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#4174]
@NicolasDorier recently suggested that we should remove the entire functionality of a `direct link` in the File Storage System and remove the `temp link` **link** in the UI  but leave the code functionality of the temp link on the backend for now.

This is to avoid confusion when uploading files.

![Screenshot 2022-09-28 at 10 35 08](https://user-images.githubusercontent.com/36959754/192731095-883539ef-3d86-43d1-bc06-58928df0f6bc.png)

**Comment by daviogg** [comment]
I have created a  #4177 PR for this issue, let me know if everything is OK :)

**Comment by dstrukt** [comment]
ACK @dennisreimann glad you brought this up! was hesitant to propose myself, as I thought there were additional use-cases for this I wasn't aware of .. love it

**Comment by dennisreimann** [comment]
Done with #4177.
