### ISSUE TITLE
[Bug]: bundled RTL continues to show zero on-chain balance

### ISSUE THREAD

**Issue by urcheon2022** [btcpayserver/btcpayserver#4186]
### What is your BTCPay version?

v1.6.10.0

### How did you deploy BTCPay Server?

BTCPay server deployed on an EC2 node using docker:

git clone https://github.com/btcpayserver/btcpayserver-docker

Everything is operational in the BTCPay server node itself

### What happened?

the internal btc wallet of the node is funded (and has 100+ confirmations), but the balance visible in ride the lightning interface continues to show ZERO

### How did you encounter this bug?

1. install the node using docker
2. sync the node
3. fund node
4. go to ride the lightning
5. no on-chain balance visible, opening channels using RTL not possible

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Kukks** [comment]
The lightning node wallet and the btcpay onchain wallet are separate
wallets. Lightning nodes do not currently allow us to specify to them to
use external wallets.

**Comment by urcheon2022** [comment]
Be it as it may: how am I supposed to fund the internal lightning node in this case? Or more specifically: the RTL on-chain wallet initialization process is very opaque: I don't believe I was every prompted to write down a seed phrase for RTL... I assumed that the btc node wallet and the RTL ones are one and the same. Did I miss something?
Any pointers appreciated

**Comment by dennisreimann** [comment]
You wouldn't receive the seed from or for RTL, but the underlying node implementation. For LND this can be found in the Server Settings > Services section, as explained [here](https://docs.btcpayserver.org/FAQ/LightningNetwork/#where-can-i-find-recovery-seed-backup-for-my-lightning-network-wallet-in-btcpay-server). 

You can use RTL to fund the onchain wallet of the Lightning node though: RTL will display a bitcoin address you can send funds to, after confirmation they will be available to open channels with.

**Comment by urcheon2022** [comment]
perfect, I was running c-lightning instead, I switched to LND and now it is clear, thanks!

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
