### ISSUE TITLE
incorrect handling of lnd uri(s)

### ISSUE THREAD

**Issue by ketominer** [btcpayserver/btcpayserver#419]
Currently, btcpay requires --externalip to be set for lnd. This breaks lightning support in several cases:
- if lnd is running totally over tor, externalip should not be set. In addition, if it is, btcpay uses the first value from getinfo->uris as the public address of the lightning node, except usually the onion address is last
- if lnd is running with multiple externalips (for example ipv4 and ipv6), only one is displayed in btcpay

I think this requirement should be dropped and use getinfo->uris as the public uri if there is only one, or let the user (or shop admin, or paying user) select which node uri to display if the paying user wants to open a channel.

**Comment by NicolasDorier** [comment]
I am unsure what you mean. I am taking lnd's ip from an RPC call to LND.

**Comment by Kixunil** [comment]
Alternatively, allow forcing the address by admin and skipping `getinfo` call - this would be useful as a workaround for #525 as well.

**Comment by NicolasDorier** [comment]
@ketominer is this problem still actual? If so I need to know where it is crashing now in btcpayserver and where it should not be crashing

**Comment by NicolasDorier** [comment]
labeling for closing because I don't think that's still the case. Will close in 30 days if not news.
