### ISSUE TITLE
[Bug]: Plugin Pay Button Errors

### ISSUE THREAD

**Issue by gibby85** [btcpayserver/btcpayserver#4203]
### What is your BTCPay version?

v1.6.11.0

### How did you deploy BTCPay Server?

Lunanode

### What happened?

The plugin Pay Button shows error from the beginning under almost all setting options. HTML code is not created. Screenshot is attached below under additional information.

### How did you encounter this bug?

1. Pay Button Plugin
2. Enabled Plugin
3. Errors showing

### Additional information

![paybutton-errors](https://user-images.githubusercontent.com/115238287/194556871-1c680f93-1485-407d-a910-5686a4c26fb2.JPG)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Do you have JavaScript enabled? If so, can you check if the browser console reports any errors?

**Comment by dennisreimann** [comment]
This is caused by JavaScript being disabled. Please reopen with a potential error log from the web console in case JavaScript is enabled, but failing.
