### ISSUE TITLE
Changelly Requires "KYC" Text to be displayed

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#421]
Right now, the changelly integrations says:

> This service is provided by 3rd party. Please keep in mind that we have no control over how providers will forward your funds. Invoice will only be marked paid once funds are received on BTC Blockchain.

However according to changelly, they also want:

“Exchange services provided by Changelly.  By clicking “Accept”, I acknowledge and understand that my transaction may trigger AML/KYC verification according to Changelly AML/KYC.”

"Changelly AML/KYC" is also hyperlinked to https://changelly.com/aml-kyc

We don't have an accept button, but we do have something that says "Changelly" (The button also appears to be broken)
![image](https://user-images.githubusercontent.com/3916318/49096824-3e209c80-f220-11e8-96f3-c99548b7d1b6.png)

CC @Kukks

**Comment by astupidmoose** [comment]
Full email for reference: 

![image](https://user-images.githubusercontent.com/3916318/49097009-b71ff400-f220-11e8-83b4-a985ba5f8c48.png)

**Comment by Kukks** [comment]
You're kidding me. Did they break the popup already?

**Comment by NicolasDorier** [comment]
ahah, @Kukks maybe you should just remove changelly support :D

**Comment by Kukks** [comment]
@astupidmoose  We fixed the styling for now at least.  Let me know if you contacted them and checked if we really need that stupid disclaimer when we only use their own UI and not direct api transactions

**Comment by astupidmoose** [comment]
Closing this for now. As @Kukks mentioned, we are using their own URL's and popup windows. If they have any issues, they should be building this language into their site.
