### ISSUE TITLE
[Bug]: Cannot send transaction BTG(Bitcoin Gold) 

### ISSUE THREAD

**Issue by hell0-w** [btcpayserver/btcpayserver#4212]
### What is your BTCPay version?

BTCPay Server v1.6.12.2

### How did you deploy BTCPay Server?

via https://install.btcpayserver.org/

### What happened?

Cannot send transaction 
[btcpay_server.log](https://github.com/btcpayserver/btcpayserver/files/9783397/btcpay_server.log)
[btcpay_server2.log](https://github.com/btcpayserver/btcpayserver/files/9783422/btcpay_server2.log)

![firefox_NB8hcqt2LT](https://user-images.githubusercontent.com/17591751/195785433-659bcdf8-99a3-4013-a9c1-4e94c02c6e3f.png)
![firefox_36qoFGfj0y](https://user-images.githubusercontent.com/17591751/195785458-8955a36e-6933-46a3-a4ac-0bc70619bca0.png)

### How did you encounter this bug?

try to send transaction to new wallet, legacy, SegWit same issue

### What browser do you use?

Firefox, chrome

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by valsha** [comment]
@hell0-w 
Did you instal Bitcoin Gold via `export BTCPAYGEN_CRYPTO2="btg"` ?

**Comment by hell0-w** [comment]
> @hell0-w Did you install Bitcoin Gold via `export BTCPAYGEN_CRYPTO2="btg"` ?

Here is standard installation config via docker

`sudo su -
apt-get update && apt-get install -y git wget
if [ -d "btcpayserver-docker" ] && [ "$EXISTING_BRANCH" != "master" ] && [ "$EXISTING_REMOTE" != "master" ]; then echo "existing btcpayserver-docker folder found that did not match our specified fork. Moving. (Current branch: $EXISTING_BRANCH, Current remote: $EXISTING_REMOTE)"; mv "btcpayserver-docker" "btcpayserver-docker_$(date +%s)"; fi
if [ -d "btcpayserver-docker" ] && [ "$EXISTING_BRANCH" == "master" ] && [ "$EXISTING_REMOTE" == "master" ]; then echo "existing btcpayserver-docker folder found, pulling instead of cloning."; git pull; fi
if [ ! -d "btcpayserver-docker" ]; then echo "cloning btcpayserver-docker"; git clone -b master https://github.com/btcpayserver/btcpayserver-docker btcpayserver-docker; fi
export BTCPAY_IMAGE=""
export BTCPAY_HOST="btg.url"
export NBITCOIN_NETWORK="mainnet"
export LIGHTNING_ALIAS=""
export BTCPAYGEN_LIGHTNING=""
export BTCPAYGEN_CRYPTO1="BTG"
export BTCPAY_ENABLE_SSH=true
cd btcpayserver-docker
. ./btcpay-setup.sh -i`


Also found BTC fee when i send BTG, do I need BTC blockchain for running BTG? 

![image](https://user-images.githubusercontent.com/17591751/196041479-4671d2fe-10c5-48ce-ac00-f3e0336002f2.png)

**Comment by valsha** [comment]
> Also found BTC fee when i send BTG, do I need BTC blockchain for running BTG?
I think...yes, you need to install BTC

**Comment by NicolasDorier** [comment]
did it ever worked in the past?

**Comment by hell0-w** [comment]
> did it ever worked in the past?

I would like to find out too, someone using BTG??? 
From my side it's new VM for BTG coin.

**Comment by NicolasDorier** [comment]
Seem to be an error in NBitcoin, trying to fix it. Nobody probably use this coin.

**Comment by NicolasDorier** [comment]
Fixed on NBitcoin, in 5 years this has never worked, but nobody saw it until now lol.

https://github.com/MetacoSA/NBitcoin/commit/99f246c9cbd20b7818e961c7aa2106b2e2f0c134
https://github.com/MetacoSA/NBitcoin/commit/7ee95023d689ea3cefd18e279dc3c48c58c2ef71
