### ISSUE TITLE
Fatal error: Cannot redeclare woocommerce_bitpay_init()

### ISSUE THREAD

**Issue by ihqtzup** [btcpayserver/btcpayserver#422]
"Fatal error: Cannot redeclare woocommerce_bitpay_init() (previously declared in /var/www/html/site/wp-content/plugins/bitpay-for-woocommerce/class-wc-gateway-bitpay.php:52) in /var/www/html/site/wp-content/plugins/btcpay-for-woocommerce/class-wc-gateway-bitpay.php on line 1500

**Comment by bitcoinshirt** [comment]
That's okay just enable plugin again, it should disappear.

**Comment by ihqtzup** [comment]
Does not work. The same error message appears again. I think this should be fixed by renaming the function.

**Comment by Kukks** [comment]
You need to give more context. Which version do you have installed?

**Comment by Kukks** [comment]
`woocommerce_bitpay_init` does not exist from version 3 upwards.

**Comment by ihqtzup** [comment]
We have Version 2.2.24

Reason for that is that the latest version throws an error "The plugin does not have a valid header."
Also you (@btcpayserver) really dont recommend installing it: https://twitter.com/BtcpayServer/status/1067601021021515777

Yes, Bitpay plugin is also installed as we are making the migration to the BTCPayserver. We need to have both enabled until we have confirmed the functionality of BTCPayserver.

**Comment by NicolasDorier** [comment]
Uninstall 2.2.24 and install the version in the store.
I did not recommended to update from 2.2.24 to 3.0.2 but since it is a new install, you can update to 3.0.2 (from wordpress store)

**Comment by Kukks** [comment]
You cannot install version 2 alongside the bitpay plugin.  
How did you install the 3.x version?

**Comment by ihqtzup** [comment]
I did it like every other Wordpress plugin from the admin panel. "There is a new version of BTCPay for WooCommerce available. View version 3.0.2 details or update now."

I don't really understand your link:

"Installation

This plugin requires Woocommerce. Please make sure you have Woocommerce installed.
To integrate BTCPay Server into an existing WooCommerce store, follow the steps below."

There are no steps.

**Comment by NicolasDorier** [comment]
@ihqtzup the problem is that you should not have installed 2.2.24 in the first place. Migrating from 2.2.24 to 3.0.2 is flaky. If possible, just uninstall BTCPay for Woocommerce completely, then make reinstall via the wordpress store.

**Comment by ihqtzup** [comment]
Thanks! It is working now with alongside Bitpay.
