### ISSUE TITLE
[Bug]: Metadata provided with invoice creation is not found in related webhooks

### ISSUE THREAD

**Issue by K1D77A** [btcpayserver/btcpayserver#4223]
### What is your BTCPay version?

BTCPay Server v1.6.12.0 

### How did you deploy BTCPay Server?

Docker

### What happened?

I send the following Json to https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Invoices_CreateInvoice along with the correct store ID 
```lisp
"{
  \"metadata\": {
    \"intention-id\": \"~gdsfpskp94jwrgs48w5y9qtnbu4czzospaeg5c6q8pbzjq2htrchpqmp2tfrlkg\",
    \"service-id\": \"!742g352asgebjfn2vzchmdbm0g6tv0hhygc5eofjbj9dkz6afkppnzfs1dhrqlf\"
  },
  \"checkout\": {
    \"redirectUrl\": \"https:....ess\"
  },
  \"amount\": \"10.11\",
  \"currency\": \"GBP\"
}" 
``` 
(excuse the escape characters)

The invoice is created.
I then navigate to the payment URL and my server receives webhooks regarding this invoice but the metadata is not found within the information in the webhook.
The info I receive is:

```
"{
  \"deliveryId\": \"UiA2K7pBZP8zrtbRzEfbjB\",
  \"webhookId\": \"FhSDJPmCU2ptDFfwjCyzzE\",
  \"originalDeliveryId\": \"SrS5wSuQehsDCLcqDLo4pL\",
  \"isRedelivery\": true,
  \"type\": \"InvoiceCreated\",
  \"timestamp\": 1666201794,
  \"storeId\": \"BNQU1r5n5eFcKCzej6hStUaCKLnkuYe7ibaLm8J4PkT1\",
  \"invoiceId\": \"DdDEbrGqCKPd4p1Rhmbo6H\"
}" 
```
InvoicePaymentSettled contains a few other fields but none of them contain the metadata.
What is the point of the metadata if it is not appended to the webhook :(

Thanks.

### How did you encounter this bug?

By interacting with the Greenfield API

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by K1D77A** [comment]
Thanks :+1:

**Comment by deadcoder0904** [comment]
yo i'm still facing this. every webhook event does not contain metadata for me:

https://github.com/btcpayserver/btcpayserver/discussions/5633

**Comment by deadcoder0904** [comment]
i'm on testnet bdw using clovyr.app's hosted btcpayserver.

cc @bolatovumar @NicolasDorier can you guys confirm if this should work on testnet too? i'm not seeing it for some reason.

**Comment by deadcoder0904** [comment]
even made a minimal repo to show you it doesn't show `metadata`. instructions in readme on how to install & get it going -> https://github.com/deadcoder0904/btcpayserver-nextjs
