### ISSUE TITLE
Add a "Subtract fees from amount" Request Body Parameter to the Greenfield API

### ISSUE THREAD

**Issue by AustinWildgrube** [btcpayserver/btcpayserver#4227]
The Greenfield API seems to be missing a `Subtract fees from amount` request body parameter. Right now, `Pull payments payout (Public)` -> `Get Payout` is returning only the amount the customer requested despite any kind of fees. On the dashboard, after the customer has accepted the pull payment and provided their address, I can then move to `Approve & Send selected payouts` which allows the option to subtract fees. I'm thinking it would need to be a multi-step process since it involves multiple endpoints.

We will need to add a `subtractFees` boolean in the request body and also return it in the 200 response along with the `amount` key/value, which would be the original amount requested and a `fee` key/value. That way, we know the amount is the `requested amount - fee`. This would affect the following `POST` request: 
- `Pull payments (Public)` -> `Create Payout`

For the following `GET` requests, the 200 response will need to have a `subtractFees` boolean along with the `amount` key/value and the `fee` key/value:
- `Pull payments (Public)` -> `Get Payout`
- `Pull payments (Public)` -> `Get Payouts`
- `Pull payments payout (Public)` -> `Get Payout`

**Comment by AustinWildgrube** [comment]
True, but I still think it is still viable to put the `Subtract fees from amount` option on the post request and then once the payout is marked complete, it would show the fees. Right now, the only possible way to know the fees of a pull payment is to look at the transaction and do the math of `amount transacted - requested amount`. One issue with that, though, is that we do not know which transaction is associated with the request. If you pull all the transactions using `Get store on-chain wallet transactions` you can sift through them to find the Pull Payment ID and see if it matches, but that seems quite tedious.

Another option could be to have [webhooks for Pull Payments](https://github.com/btcpayserver/btcpayserver/discussions/3906#discussioncomment-3900749). When it is marked as `PayoutSettled`, we can see the associated fees in the payload.

**Comment by pavlenex** [comment]
@NicolasDorier So how should we proceed this one?

**Comment by NicolasDorier** [comment]
will work on it

**Comment by NicolasDorier** [comment]
Our API for making a on chain transaction already have `subtractFromAmount`

**Comment by NicolasDorier** [comment]
The main problem we have with this feature is that we don't have the fee of the transaction saved in NBXplorer.

While we could in theory, there might be some edge case where we don't get the fee information. (A wallet external to BTCPay pay the payout, or NBX wasn't online when the transaction was made with a wallet internal to BTCPay)

Right now if `amount transaction != requested amount` then the payout isn't considered paid.
We could add a flag to the payout to allow fee to be substracted and still considered paid.

As such, `amount transacted - requested amount` would be considered `fee`, because that's the best we can do if we don't know the real fee. Then any payment to the payout would be considered valid?

**Comment by pavlenex** [comment]
@AustinWildgrube Is the above solution proposed by @NicolasDorier satisfactory?

**Comment by AustinWildgrube** [comment]
Yeah, from what I gather, it sounds okay. The main feature I am looking for is just adding a `subtract fees from amount` parameter on the `Create Payout` post request. If the fee amount cannot be returned in the body of the request, that is fine to leave out in my case.
