### ISSUE TITLE
[Bug]: After installing/uninstalling plugin "Remote plugins lookup failed." error

### ISSUE THREAD

**Issue by Bangalisch** [btcpayserver/btcpayserver#4228]
### What is your BTCPay version?

BTCPay Server v1.6.12.0 

### How did you deploy BTCPay Server?

New deployed LunaNode

### What happened?

When installing/uninstalling plugin "Remote plugins lookup failed. Try again later." error shows up. 
Plugin in question i've installed/uninstalled was NFC. 
Available plugins fully disappears afterwards out of UI. 

### How did you encounter this bug?

Install plugin in question. 
Restart of the server happens. 
When the server is restarted and you go back into Plugins in UI it's unable to load. 

### Relevant log output

```shell
Source map error: Error: request failed with status 404
Resource URL: https://XXXXX.lndyn.com/bundles/bootstrap-bundle.min.js?v=OYOQ4I7-grW_3pDlVCmi9W5SU5Pqx_IuTZaDYehKBbY
Source Map URL: bootstrap.bundle.min.js.map
```

### What browser do you use?

Firefox latest. 
Have seen it happen on Safari too. 

### Additional information

![btcpayPSBT59](https://user-images.githubusercontent.com/102448109/197358746-61cf6e1f-8b76-4d1f-9877-acbc709a714d.jpg)
![btcpayPSBT58](https://user-images.githubusercontent.com/102448109/197358747-4d0b5010-83cf-4900-87eb-4b2a8578747b.jpg)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
This is most likely a temporary issue, caused by the GitHub API not responding or rate limiting our requests.
