### ISSUE TITLE
[Bug]: Greenfield API docs: Invoice: missing monitoringExpiration

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#4248]
### What is your BTCPay version?

BTCPay v1.6.12.0

### How did you deploy BTCPay Server?

docker 

### What happened?

The invoice object returns an undocumented field `monitoringExpiration` which is not documented in the swagger API docs. We have a field `monitoringTime` documented but either this was never working or we had a breaking change introduced at some point?

### How did you encounter this bug?

Query get invoice or create invoice endpoints.

### Relevant log output

```shell
"status": "New",
    "additionalStatus": "None",
    "monitoringExpiration": 1667150955,
    "expirationTime": 1667064555,
    "createdTime": 1667064435,
```

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
@ndeet I assume this one wasn't resolved through https://github.com/btcpayserver/btcpayserver-greenfield-php/pull/82?

**Comment by pavlenex** [comment]
@bolatovumar What do you think? ^

**Comment by bolatovumar** [comment]
@ndeet @pavlenex I looked into this and looks like Swagger docs were just always wrong. Created a PR to fix it here: https://github.com/btcpayserver/btcpayserver/pull/4348
