### ISSUE TITLE
[Bug]: WebNFC Doesn't Work In iFrames

### ISSUE THREAD

**Issue by leesalminen** [btcpayserver/btcpayserver#4251]
### What is your BTCPay version?

I'm running BTCPayServer v1.6.12.0 and LNURL NFC extension v1.0.5.0.

### How did you deploy BTCPay Server?

Manual

### What happened?

The NFC plugin doesn't work when the invoice checkout is loaded in a modal (like with the crowdfunding app). This is happening because the WebNFC spec restricts its usage to top-level contexts. 

Here's a screenshot from a debugging session on an Android device:

![photo_2022-10-30 07 59 41](https://user-images.githubusercontent.com/3018359/198882646-bdf9b57e-2bb7-4df0-ae18-2d53562087b1.jpeg)

I think we should set `this.supported` to `'NDEFReader' in window && window.self === window.top` in `lnurlwnfc.js`. I can make a PR if the is the desired change.

### How did you encounter this bug?

1. Create a Crowdfund app
2. Make a donation using this app
3. When the invoice modal loads up, click the "Pay by NFC" button
4. Try and tap a NFC tag
5. The tag tap isn't captured by the browser, but the host device

### What browser do you use?

Chrome v106

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Kukks** [comment]
updated in 1.0.6

**Comment by Jossec101** [comment]
This is still happening as of 1.9.3 @Kukks

**Comment by dennisreimann** [comment]
@Jossec101 I just checked and with the now native NFC handling in BTCPay Server (the NFC plugin is deprecated by now) the code works correctly. As initially reported by @leesalminen, the browser permits access only on the top-level. 

This is a screenshot I took with the top-level check removed to verify it is not available within iframes. Nothing we can do about it as this is a browser security measure. 

![image](https://github.com/btcpayserver/btcpayserver/assets/886/7b4ae90a-4a2d-48dd-9e02-0d397e689032)

**Comment by Kukks** [comment]
> @dennisreimann I guess [postMessage()](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) could be used to hack this, like having the code on the top level and invoke from the widget the required NFC-related features.

Yes, we can build this bridge by adding postmessage communication code in the modal.js code
