### ISSUE TITLE
Remove Nomics as BTCPay Supporter

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#4265]
- Remove from BTCPay main repo
- Remove from the foundation website
- Remove from the Blog 
- Remove from the Docs

**Comment by dennisreimann** [comment]
Will propagate the changes once #4268 is merged.

**Comment by pavlenex** [comment]
@dennisreimann Merged, foundation site, blog and directory sites next?

**Comment by dennisreimann** [comment]
Yes, will send them later or tomorrow. 👍

**Comment by dennisreimann** [comment]
All done now :)
