### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by b47w0m4n** [btcpayserver/btcpayserver#4270]
### What is your BTCPay version?

I'm not a developer, I'm an user.

### How did you deploy BTCPay Server?

Don't know

### What happened?

Sometimes when I pay using XMR on a site which uses BTCPay Server the transaction fall short for 0.000000010000 XMR. I sent the exact amount required by BTCPay but it falls short as you can see in this image.
![Screenshot from 2022-11-04 15-19-19](https://user-images.githubusercontent.com/85874278/199997579-3dbf67e9-fb2e-4fa2-b289-1ed498e8cf8b.png)
you can see in the image:
Order Amount 0.137694120000 XMR
Already Paid  -0.137694120000 XMR
Due 0.000000010000 XMR
maybe you have a round issue, but it creates a huge problem, because I have to send 0.000000010000 XMR to complete the order in a short time, and sometimes I have to wait the last transaction to confirm what it takes time. 

### How did you encounter this bug?

paying on bitvps with monero

### What browser do you use?

Brave

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Kukks** [comment]
This is because when you pay in multiple transactions (the screenshot shows you paid the amount in txs), we add a fee to cover the additional costs of having 2 utxos instead of one (this costs more spend than have 1 coin). I think this is the default but it is also configurable on a store level.
