### ISSUE TITLE
[Bug]:  Custom price for an item not showing input field

### ISSUE THREAD

**Issue by Atitlanio** [btcpayserver/btcpayserver#4275]
### What is your BTCPay version?

v1.6.12.0

### How did you deploy BTCPay Server?

Rpi4 (32-bit)

### What happened?

1) Created a PoS app in a store

2) Added an item and selected `Price: custom` in the Edit modal
![image](https://user-images.githubusercontent.com/106037272/200324005-a22ef7ba-12f6-41d3-abf6-2ccfacb8a543.png)

3) Saved the app and viewed it, trying Point of Sale styles **Item list only** and **Item list and cart** - in both cases, the item displays but it does not show a field to input the custom amount.
![image](https://user-images.githubusercontent.com/106037272/200324882-fa414d9a-c1ff-401f-a517-873e089aab13.png)

4) however, if In the item field I use `Price: minimum` , it does show the input field
![image](https://user-images.githubusercontent.com/106037272/200324555-a5d9e709-cb20-4b6f-8502-08fc00b83a5a.png)
![image](https://user-images.githubusercontent.com/106037272/200324645-6469f356-7d51-4848-87f7-3de3eae8736d.png)

### How did you encounter this bug?

reference above

### What browser do you use?

Tried in  Mozilla Firefox 106.0.1 and Chromium Version 103.0.5060.53 (Official Build) (64-bit), same result

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
This isn't a bug, but I agree that it's a bit confusing: The amount does not get specified on that page, but when paying. The invoice will have a zero amount and it can be payed with whatever amount the customer decides.

We'll redo the POS views with #4114 and we will keep this in mind for the next iteration!

For now, you could circumvent this by changing the custom button text to something like "Pay what you want".

**Comment by pavlenex** [comment]
@dennisreimann Should we close this one and track it in #4114 or do you want it opened?

**Comment by dennisreimann** [comment]
Added it as an item there and closing this, since it ain't a bug per se.
