### ISSUE TITLE
[Bug]: QR code address is in all caps

### ISSUE THREAD

**Issue by BumbleBeeeeeeeeeee** [btcpayserver/btcpayserver#4292]
### What is your BTCPay version?

not sure

### How did you deploy BTCPay Server?

nor sure

### What happened?

not sure

### How did you encounter this bug?

trying to pay for a service with Coinbase app and scanning the QR code doesn't work because the address is in ALL CAPS. It should be in small caps.

### Relevant log output

```shell
none
```

### What browser do you use?

chrome

### Additional information

no

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Hey, this is not a bug, can you please report to coinbase that their wallet doesn't follow the BIP21 standard practice, uppercase address is actually in BIP.
