### ISSUE TITLE
[Bug]: Greenfield REST API endpoint Get Lightning Invoice fails on Expired invoices.

### ISSUE THREAD

**Issue by javateer** [btcpayserver/btcpayserver#4298]
### What is your BTCPay version?

v 1.6.12.0

### How did you deploy BTCPay Server?

One-click install/deployment on LunaNode.com.

### What happened?

This is about behavior as described in the following reference documentation:
https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreLightningNodeApi_GetInvoice

Whether a Lighting invoice is Unpaid, Paid, or Expired, the above RESTful inquiry should return a HTTP response status code 200. Requesting the server about an invoice that never existed should return 404, the documentation states. This all makes sense.

When actually requesting an invoice that does exist, a status code of 200 will return but only if the invoice is Paid or Unpaid. If it reaches its time of expiration, the same REST call returns 404 instead of 200. So, from the client-side's point of view, the server does not recognize the difference between an existing invoice that has expired and an invoice that never existed in the first place.

### How did you encounter this bug?

Writing 3rd layer Bitcoin code that makes use of the Lightning Network via the BtcPayServer's Greenfield REST API, my application successfully creates an invoice to present to the User. But then, while waiting for the User to pay the invoice, my application polls the server via the REST API to know if the proposed transaction has been completed by the User. Everything works as expected until / unless the invoice has expired while still waiting for payment. My client-side code expects a 200 response with JSON object sub-value "Expired" but instead crashes because of the unexpected 404 Not Found reply from the server.

### Relevant log output

```shell
No log. Stating the Greenfield API endpoints called and the server's HTTP Response returned is sufficient to explain the problem and how to recreate it.
```

### What browser do you use?

No browser. The problem is in the Greenfield API's server-side behavior.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by bolatovumar** [comment]
@javateer is the error message that comes through with the 404 `Impossible to find a lightning invoice with this id`?

**Comment by dennisreimann** [comment]
Just checked and for me it seems fine. Please keep in mind, that for the LN invoice endpoint, you have to use the Lightning invoice ID you got back from the create call — not the BTCPay invoice ID. These are two different entities.

Here are the responses from what I just checked …

## Create invoice

`POST /api/v1/stores/STORE_ID/lightning/BTC/invoices`

```json
{
    "id": "2MCyZKYN3s4V44Sohof4D9vM2N83", <- use this ID in the following GET call
    "status": "Unpaid",
    "BOLT11": "lnbcrt10n1...",
    "paidAt": null,
    "expiresAt": 1671023382,
    "amount": "1000",
    "amountReceived": null
}
```

## Get invoice

`GET /api/v1/stores/STORE_ID/lightning/BTC/invoices/2MCyZKYN3s4V44Sohof4D9vM2N83`

```json
{
    "id": "2MCyZKYN3s4V44Sohof4D9vM2N83",
    "status": "Expired",
    "BOLT11": "lnbcrt10n1...",
    "paidAt": null,
    "expiresAt": 1671023382,
    "amount": "1000",
    "amountReceived": null
}
```
