### ISSUE TITLE
Server Backup / Servers Sync between 2 servers

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#431]
As [discussed on Slack](https://forkbitpay.slack.com/archives/C7M093Z55/p1543784023183300) we should allow:

1. Easy manual backup of the entire server including server settings, invoices, etc (used for migration from one host to another and for those who can't afford running 2 servers) - Export/Import BTCPay from the front end.
2. Continuous API sync between the main and the backup server in case the main goes down.

With more retail merchants coming, it's been discussed that this feature is something needed. The use-case would be: Merchant in retail has a POS BTCPay app, but his server gets down for some reason. Imagine the chaos in the restaurant if customers were unable to pay. Of course, this is theoretical example.
We had several issues when merchant would do something bad to the main server causing his entire online store to go down (myself included and few others).

This could also increase censorship-resistance if user had his server hosted with 2 different host or even on two hardware devices in case one breaks down.

**Comment by bitcoinshirt** [comment]
Opened this on the behalf of merchants on Slack, however, it appears they found other solutions. Closing this for now. May re-open in future if the community shows interest for such a feature. There's already talk in #289 where users request to export server options from what I understand.
Anyway closing this.

**Comment by Eskyee** [comment]
Would be great to solve this 🙏

**Comment by JeffVandrewJr** [comment]
With regard to the Dockerized version:

The backup could be just a shell script that executes this command that @lightbo_lt uses: https://chat.btcpayserver.org/btcpayserver/pl/bi15ze9iipgrueaw7zcj4pmd4r Maybe that could even run as like a cron job.

**Comment by pavlenex** [comment]
There's progress on this by @JeffVandrewJr and @Kukks so I'm closing this one, as it was not formulated properly anyway and was too broad request.
