### ISSUE TITLE
[Bug]: Toggle User doesn't deactivate a user

### ISSUE THREAD

**Issue by setavenger** [btcpayserver/btcpayserver#4310]
### What is your BTCPay version?

I'm running BTCPay v1.6.12.0

### How did you deploy BTCPay Server?

I deployed the server with a script generated by the btcpayserver-Configurator 

### What happened?

I used the api to lock (toggle) a user but it doesn't seem to have any effect. It returns a 200 but the user still has access. It does work when I lock the user via the web interface.

### How did you encounter this bug?

1. I called the endpoint /api/v1/users/{idOfUser}/lock with the corresponding body
{
"locked": true
}
2. returns a 405 (despite having an unrestricted key)

### What browser do you use?

Postman

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
The `405` error indicates that you might have used an incorrect HTTP method: THe docs state that `DELETE` should be used, but actually it's `POST`. Can you check if that works for you?

Fix contained in #4377.

**Comment by setavenger** [comment]
Works like a charm! Thanks for pointing this out.
