### ISSUE TITLE
Add field validation for `Shipping address`

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#4317]
In 1.7.0 we introduced a way for user to enable requesting the shipping information from their customers #4137 however the fields there don't have any validation.

![Screenshot 2022-11-21 at 11 39 19](https://user-images.githubusercontent.com/36959754/203029886-4566a5bb-1c60-4d54-82f7-65343d6a02c4.png)

**Comment by btwomey873** [comment]
Hey I'd love to help out with this project.  Seems like a good starting point?

Thanks

**Comment by Scottpulido5** [comment]
Thank you it's been a pain in the ass to never lets me withdraw I'll go back to the site manager and it just sends me back LOL

**Comment by pavlenex** [comment]
Hi @btwomey873, what's the time frame you're looking at for tackling this one?

**Comment by Wayne4167** [comment]
So what do l have to do to with draw

**Comment by pavlenex** [comment]
@btwomey873 are you still working on this one?

**Comment by jeremyikwuje** [comment]
@pavlenex I would have loved to take this, but I don't have a C# background yet. How fast do you think I can pick up the language and begin contributing to BitPayServer?

**Comment by pavlenex** [comment]
Feel free to give it a try @jeremyikwuje. We don't have this as a high-priority item, so it's fine if takes more time. You can join our dev channel (download Mattermost app) and the server URL is https://chat.btcpayserver.org if you have any questions.

**Comment by cdmoss** [comment]
@jeremyikwuje If you decide you don't want to work on this anymore, let me know because I would take a stab at it. But if you still plan on learning C# and taking this then it remains all yours :)

**Comment by jeremyikwuje** [comment]
@pavlenex alright, thanks!

**Comment by jeremyikwuje** [comment]
> @jeremyikwuje If you decide you don't want to work on this anymore, let me know because I would take a stab at it. But if you still plan on learning C# and taking this then it remains all yours :)

Already picked up C# yesterday, and hope to get it done this month. If it isn't something I can do, I will let you know by first week of January.

Thanks!

**Comment by cdmoss** [comment]
Ok sounds good, good luck :)

**Comment by Scottpulido5** [comment]
510-695-4923

**Comment by jeremyikwuje** [comment]
hi @cdmoss, you can take it up and let me know when you get it done so I can see how you did it.

PS: Been studying C# for 2 weeks now and getting pretty good at it.

**Comment by jeremyikwuje** [comment]
> 

@pavlenex downloaded the Mattermost app, but it's requesting a username and password after connecting to btcpayserver.

How do I create one?

**Comment by pavlenex** [comment]
Hey @jeremyikwuje, this is very confusing UI on Mattermost's end, but there's a create an account in the upper right corner of that page.
![Screenshot 2023-01-11 at 10 15 31](https://user-images.githubusercontent.com/36959754/211766196-afc0d5a1-d0e9-4df9-8e9e-1abc324e5f74.png)

**Comment by pavlenex** [comment]
@cdmoss Would you like to grab this one then?

**Comment by dennisreimann** [comment]
Done as part of #4561 

![grafik](https://user-images.githubusercontent.com/886/218784165-bd5ff975-831c-4b63-9688-b5b2f346a703.png)

**Comment by jeremyikwuje** [comment]
@dennisreimann great job.

**Comment by kovivac** [comment]
A kapott bónuszok nem jutnak el a számlámra..!?
