### ISSUE TITLE
Fix build warnings `UIFormsController``UIPaymentRequestController`

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#4323]
After 1.7.0 we should try to address these build warrnings.
![Screenshot 2022-11-21 at 11 20 50](https://user-images.githubusercontent.com/36959754/203032124-b736c067-5a60-4604-befd-d268d8a170c6.png)

I noticed them by using Rider on #4137 not sure if this PR introduces them or is it something else, but worth testing and fixing. 

A good first issue for anyone willing to contribute.

**Comment by jesterhodl** [comment]
I'd like to take this one on

**Comment by pavlenex** [comment]
Feel free to grab it @jesterhodl 🙏

**Comment by pavlenex** [comment]
Done in https://github.com/btcpayserver/btcpayserver/pull/4331
