### ISSUE TITLE
UI of partially paid invoice

### ISSUE THREAD

**Issue by hubiktomas** [btcpayserver/btcpayserver#433]
I have a feedback from our customers - when they do accidentally a partial payment (for instance by not calculating the fee), the whole UI just updates the remaining amount without any other notification of accepted payment and notification of the need to pay the remaining payment. So if they did not notice the changed number, it looks like just nothing happened. We should probably make more visible in the UI that some funds are received and some still have to be sent.

**Comment by britttttk** [comment]
It's very hard to see partial payments when viewing the invoice on QR code screen. If it's on the copy address screen the amount due is updated in large text. But I do agree it's hard to see the change. I also think the dropdown arrows are very faint to reveal the details. Even though this is standard for invoices I think it's not very user friendly. 

Some solution ideas:

partial payment changes the color of the "Awaiting Payment..." bar
change the "Awaiting Payment..." message to like "Partial Payment Received"

**Comment by NicolasDorier** [comment]
ping @rockstardev

**Comment by astupidmoose** [comment]
I think a small popup wouldn't be too extreme either since its a time sensitive issue and one that could result in cancelled orders. I like the "Partial Payment Received", but i think it would also make sense to deliver a "UH OH" popup as a call to attention

**Comment by bitcoinshirt** [comment]
@astupidmoose I think that can be a good idea, but it needs to be handled so that the pop-up is not affected by adblockers and that it works well on mobile devices (most mobile browsers will block pop up from what I know?),  but that's a good approach, we clearly need to give them info right away.

**Comment by astupidmoose** [comment]
Maybe a popup is a bad term here. But a change in the UI that involves the customer acknowledgement before proceeding and something that's so different it makes the customer look cause it's not just ticking down with a remaining amount.

**Comment by pavlenex** [comment]
@rockstardev any idea how we can tackle partially paid the invoice and make it clearer that the invoice is partially paid and that customer has to pay the remaining amount.

How about something that @mariodian suggested in #434 that got overlooked IMO, at least the clear red warrning.

![49869081-4399fb80-fe4a-11e8-96d1-01162bd1b9ce](https://user-images.githubusercontent.com/36959754/54391858-6d132f00-46a6-11e9-8448-80c69843d294.png)
.

**Comment by pavlenex** [comment]
@rockstardev any chance you can snug a warring when the invoice is partially paid to make it clearer for people that they need to pay the rest, right now it's so unclear unless they select the drop-down arrow.

I think @mariodian suggestion for at least the warning in different color should be a good place to start.
![Screen Shot 2019-04-19 at 16 22 52](https://user-images.githubusercontent.com/36959754/56428434-a0f1fd80-62bf-11e9-9687-5944272a2623.png)

**Comment by astupidmoose** [comment]
I agree, this would be a very good thing. Something that makes the customer think "Oh shit I did something wrong, but I can still fix it". 

I like this red bar
