### ISSUE TITLE
[Bug]: UI Print View on Payment Requests

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#4341]
### What is your BTCPay version?

v.1.7.x.x Altcoins (integration branch from dennis)

### How did you deploy BTCPay Server?

Docker

### What happened?

When printing a succeeded payment request, I got the following in the printing preview:
![image](https://user-images.githubusercontent.com/1374810/203632648-70e75276-c233-43bf-b63d-7c958f6bd5ae.png)

### How did you encounter this bug?

I created a payment request, paid it and opened the "print" view. Microsoft Edge opened the print preview window and the above came to show on a Lightning payed payment request.

### What browser do you use?

Microsoft Edge on MacOS

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by inomag** [comment]
Hi @pavlenex, I would like to work on this issue. Can you tell me what the expected print view is? Should we trim the description or expand the description cell in the table?

**Comment by petzsch** [comment]
@woutersamaey responded in Mattermost that this might not be as easy as expected. See the discussion [here](https://chat.btcpayserver.org/btcpayserver/pl/1k3tyaruc3ra7fmob5iafezmce).

**Comment by bolatovumar** [comment]
@petzsch I found an obscure CSS property which fixes this issue. Please take a look in #4447.
