### ISSUE TITLE
Fix TempData`with PostRedirect

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#4343]
I would like to report this feature for a future release.

1. There is the `TempData` stuff to fix with PostRedirect
2. The creation of a new Form via the UI doesn't work (it says that `id` is required)
3. Because the tests pass, it means it wasn't tested.
4. The form primary key should probably include the store, as it's a property of the store settings
5. Various warnings due to #nullable

_Originally posted by @NicolasDorier in https://github.com/btcpayserver/btcpayserver/issues/4137#issuecomment-1326129185_

**Comment by NicolasDorier** [comment]
https://github.com/btcpayserver/btcpayserver/pull/4346
