### ISSUE TITLE
[Bug]: No back to store button when invoice expires for the new checkout

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#4344]
### What is your BTCPay version?

master https://github.com/btcpayserver/btcpayserver/commit/a4ee1e98055b54af11355facf309739ec00c8f81

### How did you deploy BTCPay Server?

dev env

### What happened?

We don't have back to store button for expired invoices

### How did you encounter this bug?

1. When invoice expires, there's no back to store button. This only happens for `Expired` invoices.

### What browser do you use?

Safari 16.00

### Additional information

![Screenshot 2022-11-24 at 11 13 44](https://user-images.githubusercontent.com/36959754/203759009-03f4ec31-4f3c-4cb1-9c53-0265d789354e.png)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Are you sure the store had a URL defined before the invoice got created? I couldn't reproduce it and there's also a [test for this case](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer.Tests/Checkoutv2Tests.cs#L80).

**Comment by pavlenex** [comment]
Yes, this was with the checkout v2.

**Comment by pavlenex** [comment]
@dennisreimann I figured it out, it needs http or https prefix in the store field. However if this is not set, we should just go back to the original page? It feels weird that we tell people to return to store but give them no way to return to a previous page?

**Comment by pavlenex** [comment]
Okay, so this is a bug on both legacy and v2 checkout.

When there's no store url set up in store settings and invoice expired, we:
1. For legacy invoices, if public receipt is selected, show back to store but redirect to the receipt page
2. For legacy invoices, if public receipt is disabled, we do have a return to store which I think redirects to a previosly visited page, which would be the appropriate behaviour 
3. For checkout v2 we show no button as explained in screenshot above.
