### ISSUE TITLE
[Bug]: No QR code on checkout v2 when payment method != on-chain

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#4352]
### What is your BTCPay version?

v1.7.0

### How did you deploy BTCPay Server?

RPI 4 with Docker

### What happened?

Invoice appears with details drop down, but QR code is missing.

### How did you encounter this bug?

1. Updated my 1.6.0 and switched on checkout v2 and unified QR code, leaving my default payment method un-changed on off-chain.

### What browser do you use?

Microsoft Edge on MacOS

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Confirmed it's a bug ,was able to replicate with having off-chain as a default payment method.

**Comment by dergigi** [comment]
Confirmed too on my side, just wanted to track this 🐛
