### ISSUE TITLE
Withdraw myassets from Binance New Checkout Feedback

### ISSUE THREAD

**Issue by Wayne4167** [btcpayserver/btcpayserver#4353]
### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/4308

<div type='discussions-op-text'>

<sup>Originally posted by **dennisreimann** November 18, 2022</sup>
We're curious to hear your thoughts about the new checkout, which we ship as an opt-in feature with v1.7 — let us know below!</div>

**Comment by petzsch** [comment]
replied to under your Discussion comment.
**This one should be closed.**

**Comment by Wayne4167** [comment]
Then why haven't I received my withdraw transfer

**Comment by Kevinloganlee** [comment]
Never withdrew

**Comment by Kevinloganlee** [comment]
This shit is a scam beware

**Comment by Kevinloganlee** [comment]
Scam

**Comment by Wayne4167** [comment]
"bitcoin:bc1qmdhtk6h09p56tggyethcgh32sdyt2r6fzyzd94"
https://cryptosavepro.com/i/KJfgK9qCoMCiZd66UBz5BZ#:~:text=bitcoin%3Abc1qmdhtk6h09p56tggyethcgh32sdyt2r6fzyzd94
