### ISSUE TITLE
replied to under your Discussion comment.

### ISSUE THREAD

**Issue by Kevinloganlee** [btcpayserver/btcpayserver#4356]
replied to under your Discussion comment.
**This one should be closed.**

_Originally posted by @petzsch in https://github.com/btcpayserver/btcpayserver/issues/4353#issuecomment-1328004832_ no I need to open it

**Comment by Adek1355** [comment]
> ```
>     replied to under your Discussion comment.
> ```
> 
> **This one should be closed.**
> 
> _Originally posted by @petzsch in [#4353 (comment)](https://github.com/btcpayserver/btcpayserver/issues/4353#issuecomment-1328004832)_ no I need to open it

**Comment by Adek1355** [comment]
Bsjfjjfjrhcjdjch hchdb hf
