### ISSUE TITLE
[Bug]: FixedFloat Plugin doesn't work on 1.7

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#4360]
### What is your BTCPay version?

v1.7.0.0+def5095d7

### How did you deploy BTCPay Server?

docker

### What happened?

![image](https://user-images.githubusercontent.com/1374810/204087594-c0ea9a50-bc45-4d94-8f1a-344abd0cef13.png)

widget.fixedfloat.com has denied the connection.

### How did you encounter this bug?

tun on old checkout, create invoice with plugin enabled

### What browser do you use?

Microsoft Edge on MacOS

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
Another user reported fixedfloat works for him

![image](https://user-images.githubusercontent.com/3020646/204093377-f24689de-fac0-42d0-af5c-a8eef53c1553.png)

**Comment by petzsch** [comment]
I can confirm it works again. Must have been a server hickup on fixedfloats side of things.
