### ISSUE TITLE
Feature Request: Add API support to query LNURL Withdrawl URLs on pull payments

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#4365]
As an integrator who would like to create LNURL-Withdrawl based coupon codes / vouchers, it would be very helpful to automate the creation of the same.

Currently it's only possible to get the urls and QR codes through the public URL of the pull payment, by clicking on the QR Code icon on the top left.

In this [discussion](https://chat.btcpayserver.org/btcpayserver/pl/unu5izbqo3g53ccp8gho6pgy6a) @Kukks stated he wanted a separate API endpoint for this.

**Comment by petzsch** [comment]
If someone takes this on: Could we also make Pull Payments denominated in SATS work with LNURL-Withdrawl?

**Comment by bolatovumar** [comment]
@petzsch do you want to be able to retrieve this info for a pull payment or something else?

![Capture](https://user-images.githubusercontent.com/1934678/209063831-19e65799-7582-413f-97f5-c66793593e84.PNG)

> Currently it's only possible to get the urls and QR codes through the public URL of the pull payment

Public pull payment pages don't have QR codes so I'm not sure if I understand what you want correctly here.

**Comment by petzsch** [comment]
When you enable off-chain payments and denominate the pull payment in BTC, there is a QR code button on the top left corner here: 
![grafik](https://user-images.githubusercontent.com/1374810/209076919-826dcfc2-1014-4dc6-aef4-6a9189662018.png)

I would like to be able to retrieve the content of these QR codes via API.
