### ISSUE TITLE
Embed POS store

### ISSUE THREAD

**Issue by CarlosRoldanx** [btcpayserver/btcpayserver#438]
Hi,

I am trying to embed the store from the app POS into my website. I am having the problem xframe = SAME ORIGIN. Is there any way to embed it without having to add a 'allow host' option?

Thanks!!

**Comment by NicolasDorier** [comment]
ok I will remove it next update.

**Comment by NicolasDorier** [comment]
a533a96598db27db1f74502ef8a3204d1c8cf537

**Comment by CarlosRoldanx** [comment]
Hi! I updated btcpayserver. But I am still receiving the same error for embedding the button using iframe.

` 'https://lnd.satoshis.games/apps/24XWRYHrBEkbygBNYKBkV6ujVVLr/pos' in a frame because it set 'X-Frame-Options' to 'deny'.`

**Comment by NicolasDorier** [comment]
Hey @CarlosRoldanx maybe cache issue?I don't seeany X-Frame-Options in this page.

**Comment by NicolasDorier** [comment]
I can't replicate, look:

![image](https://user-images.githubusercontent.com/3020646/50506061-42a7d180-0aba-11e9-8823-bd64d11eb432.png)

Give me a page where I can replicate this.

**Comment by CarlosRoldanx** [comment]
This issue only seems to happen when running the web locally. I have just deployed globally at https://Satoshis.Games and it works great 😉
