### ISSUE TITLE
[Bug]: Bad Gateway

### ISSUE THREAD

**Issue by Al-Bsharat** [btcpayserver/btcpayserver#4387]
### What is your BTCPay version?

1.7.1

### How did you deploy BTCPay Server?

Docker

### What happened?

When I run btcpay-update.sh to update the system from 1.6.12 to 1.7.1 I can't access BTCPay Now I get 502 Bad Gateway

### How did you encounter this bug?

When I run btcpay-update.sh to update the system from 1.6.12 to 1.7.1 

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
This is usually temp and only for a few minutes. Just be patient.
