### ISSUE TITLE
NFC Payment doesn´t work

### ISSUE THREAD

**Issue by titusz** [btcpayserver/btcpayserver#4393]
### What is your BTCPay version?

BTCPay v1.7.1.0+e11a775be with LNURL NFC Support 1.0.7.0

### How did you deploy BTCPay Server?

BTCPay Server Configurator

### What happened?

Bolt Card Payment via POS App fails with `[{"path":"payLink","message":"Invalid Uri value"}]`

### How did you encounter this bug?

Activated NFC payment on POS checkout and scanned BoltCard.

### Relevant log output

```shell
`[{"path":"payLink","message":"Invalid Uri value"}]`
```

### What browser do you use?

Chrome 107.0.5304.141 on Android 11

### Additional information

I am regularly testing NFC payment since version 1.0.5 release of the plugin on different devices and having trouble to make it work consistently. Another thing that happens it that when scanning the NFC card another app like breeze opens and tries do a withdraw. Using the same BoltCard I have none of these problems using LNBits TPOS. Maybe it would help to check how they use the NFC Browser API: https://github.com/lnbits/lnbits/blob/main/lnbits/extensions/tpos/templates/tpos/tpos.html

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by petzsch** [comment]
Can't confirm that the NFC plugin 1.0.7.0 doesn't work. (at least in my case it does what it should)

For me it worked quite well with a BoltCard from coincorner.com
Does your Boltcard include a valid payLink URI?
Where you able to use the same bolt card to withdraw to i.e. Breez?

One thing I ran into: If I load a LNURLW on a new Boltcard stemming from a Pull Payment of my server, then I can't pay invoices from my own server with it. Which I guess is to be expected when you come to think of it.

**Comment by titusz** [comment]
I am using a [BoltRing](https://www.bitcoin-ring.com/) which is compatible with BoltCard (same chip). It is connected via CoinCorner and returns dynamic URLs of the format:

`lnurlw://coincorner.io/lnurl/withdraw/auth/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx?picc_data=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&cmac=xxxxxxxxxxxxxxxx`

The initial response has the following format:

```
{
    "callback": "https://coincorner.io/lnurl/withdrawreq/auth/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx?picc_data=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "defaultDescription": "CoinCorner Withdrawal ⚡️",
    "maxWithdrawable": 363003000,
    "minWithdrawable": 1000,
    "k1": "xxxxxxxxxx",
    "tag": "withdrawRequest",
    "payLink": ""
}
```
Note that payLink is an empty string. Yet it works with Breeze.

**Comment by petzsch** [comment]
My payLink from coincorner is not empty... strange:

```json
{
    "callback":"https://coincorner.io/lnurl/withdrawreq/auth/XXXXXXXXXXXXXXXXXXXXXXX?picc_data=XXXXXXXXXXXX",
    "defaultDescription":"CoinCorner Withdrawal ⚡",
    "maxWithdrawable":362503000,
    "minWithdrawable":1000,
    "k1":"CoinCorner",
    "tag":"withdrawRequest",
    "payLink":"https://coincorner.io/lnurl/pay/XXXXXXXXXXXXXXXXXXXX"
} 
```

**Comment by titusz** [comment]
Yes that is strange. But I guess we have found the problem. It seems that the plugin tries to check the `payLink` json-field to be a valid URI. An emtpy string is not valid. But the `payLink` field is optional according to the spec. It would be best to not fail but ignore the `payLink` field if it is an emtpy string or null. I have been searching but I could not find the code for the NFC plugin. Any hints?

**Comment by petzsch** [comment]
I haven't really looked at much of the code (other then the PHP lib and the swagger.json)
So can't tell you where the implementation for the NFC plugin lives.

Our "EvilScientist" @Kukks would be my first thought who could help you.

**Comment by za-kk** [comment]
Yes it would make sense to just ignore `payLink` if empty rather than fail. I will look at resolving our end too (CoinCorner) to not return `payLink` in the response if it's empty.

**Comment by Kukks** [comment]
I'm on it. Will fix tomorrow

**Comment by NicolasDorier** [comment]
https://github.com/Kukks/LNURL/commit/69c0018a0b18039251df8b33bb554533b76d1f66

**Comment by titusz** [comment]
I still get the "Error parsing response" popup using BTCPay server  v1.7.4 with LNURL NFC plugin 1.0.8.
