### ISSUE TITLE
[Bug]: Core Lightning 22.10 requires jsonrpc: "2.0" in request

### ISSUE THREAD

**Issue by Sjors** [btcpayserver/btcpayserver#4399]
### What is your BTCPay version?

v1.7.1

With Core Lightning v22.10

### How did you deploy BTCPay Server?

Maximum pain (self hosted, no Docker, Ubuntu 22.10)

### What happened?

Lightning node info page showed status offline.

Testing the connection string resulted in:

```
Error while connecting to the API: jsonrpc: "2.0" must be specified in the request
```

### How did you encounter this bug?

Noticed after reboot.

### Additional information

Relevant deprecation:
https://github.com/ElementsProject/lightning/pull/5490/commits/986a0c2880f84d7f450e9f88f9a4b47e1946d3f7

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Once ElementsProject/lightning#5657 is resolved we can upgrade our Core Lightning stack. By now we're behind quite a bit and we don't easily notice issues like this, because our tests also use the outdated versions in our containers. 

Sorry for the hassle, we'll get to it!

**Comment by pavlenex** [comment]
@Sjors  Is this still the issue considering we've bumped CLN yesterday?

**Comment by Sjors** [comment]
I just updated to `v1.7.1` and get the same error.

**Comment by sethforprivacy** [comment]
I too am on v1.7.1 and have the same issue, but the changelog for v1.7.2 makes it sound like it will be fixed in that release?

**Comment by petzsch** [comment]
A little OT, but since you are all on the new CLN: Are you also seeing problems with more inactive channels? Trying to open a channel to an LND node and after opening it keeps on droping the connection.

Also note: last night we got another Update to CLN (to not advertise dns names but ips).

**Comment by dennisreimann** [comment]
@sjors @sethforprivacy yes, the upcoming v1.7.2 should fix it.
