### ISSUE TITLE
[Bug]: Invoice is not marked as settled with the new checkout page when LN payment is made to LNBank

### ISSUE THREAD

**Issue by ishristov** [btcpayserver/btcpayserver#4408]
### What is your BTCPay version?

v1.7.1.0+e11a775be

### How did you deploy BTCPay Server?

Lunanode deployment.

### What happened?

I made a LN payment with the new checkout UI and the store is configured to receive the payment to a LNBank wallet.

When I made the payment, the sats were received to the LNBank, but the invoice is still shown as "new" and the checkout page stays on the QR code as if nothing happened.

I've seen this behaviour (payments to LNBank) very often and have reported bugs in the past. It gets resolved with the next update but then at some point it stops working again. Since the idea is to move to ln payments, is there something that can be done so that this lnbank regression doesn't happen that often? :)

### Are you sure this is a bug report?

- [x] I confirm this is a bug report

**Comment by ishristov** [comment]
I have another btcpayserver instances and I got the same result there (money goes to LNbank) but invoice is stuck on new (eventually expired) and the checkout doesn't change.

I changed the lightning setting to "internal node" instead of "lnbank" and the next ln payment went through immediatelly and was properly settled and parked as paid.

**Comment by pavlenex** [comment]
@dennisreimann Where should we move LNBank issues, they can't just keep getting posted in the main repo?

**Comment by petzsch** [comment]
LNBank issues are being tracked here: (not sure if we can move this issue there)
https://github.com/dennisreimann/btcpayserver-plugin-lnbank/issues

👍

**Comment by pavlenex** [comment]
We can't since it's not under different organization.

**Comment by ishristov** [comment]
@pavlenex, for this particular issue I know that the problem is with LNBank (I've seen in before) but someone else might see the invoice not working and not know that it's plugin related. This is an issue that is making btcpayserver not working properly. From user's perspective it should be here and you shouldn't expect them to go search for random repositories to post issues there. It's good enough that someone is reporting issues. Just add a few "projects" and "labels" and tag these issues respectively...

**Comment by pavlenex** [comment]
Nobody said users should do that.
