### ISSUE TITLE
Feature Request: Allow more then 20 accounts when using BTCPayServer.Vault

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#4410]
![image](https://user-images.githubusercontent.com/1374810/206013912-a31ff029-c953-48e0-ab37-5b542983991e.png)

In the above screen account is a dropdown which lets you choose from 0..19

I have brought this topic up before, and @NicolasDorier had confirmed that there is no technical reason for this 20 account limit.

So... could we turn it into a numeric input field?

**Comment by NicolasDorier** [comment]
yeah we could
