### ISSUE TITLE
[Bug]: Adding LNDHUB URL from LNBits leads to error

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#4414]
### What is your BTCPay version?

1.7.1

### How did you deploy BTCPay Server?

docker

### What happened?

Adding the LNDHUB Admin URL I got form LNBits as Lightning Store Wallet(Custom) in BTCPayServer leads to this error:

lndhub://admin:(long string with 32 chars)@https://lnbits.4sats.net/lndhub/ext/

> Specified argument was out of the range of valid values.

### How did you encounter this bug?

see above

### What browser do you use?

Edge on MacOS

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
The LNbits LNDhub extension isn't behaving well: Their [`getinfo` call](https://github.com/lnbits/lnbits/blob/main/lnbits/extensions/lndhub/views_api.py#L22) simply returns `bad auth` everytime, which breaks the integration for us. They need to fix it on their end and return [valid information](https://github.com/BlueWallet/LndHub/blob/master/doc/Send-requirements.md#get-getinfo) we can use to connect.

**Comment by tlindi** [comment]
This is not reproduce on clearnet LNbits 0.12.4.
