### ISSUE TITLE
Add Rules for User Roles

### ISSUE THREAD

**Issue by darkban** [btcpayserver/btcpayserver#442]
guys how about implementing a feature that allows the administrator to create the accounts manually what kind of account to create for the end user with rules?

for example:
to the user Bob assign 1 pos and therefore all the management of the wallet and of the products and invoices but not of the store

user alice assign 1 store but not the pos can then give all the management inherent to the store and wallet

Robert assign 1 store and 1 pos and then give all necessary permission

the number of rules can obviously change.

**Comment by bitcoinshirt** [comment]
User roles and what you refer to admin account creating already possible.
![screen shot 2018-12-10 at 18 18 01](https://user-images.githubusercontent.com/36959754/49749241-0dbd1180-fca8-11e8-8b4f-fb413d5d2d7a.png)
Currently there are two roles:
1. Owner
2. Guest (not able to modify store settings)

If you need additional role, please be specific and concise on restrictions and names of those roles, it's hard to understand from your examples what is it that you need.

**Comment by darkban** [comment]
Yes I know that there are those rules but that's not what I said

It would be nice to implement a rule that allows the administrator to choose what to assign to each client

for example

I want the BOB user to have access only to the application and then have access to the pos and its management

instead to another user, for example, ALICE only has access to bees for its e-commerce but not to the POS application

instead, the user ROBERT has access to both functions ... do you understand what I mean?

In practice, give the administrator the ability to access the user

guys forgive my bad english.

**Comment by bitcoinshirt** [comment]
Seems to complex concept with many things to add and I don't quite get the use-case for that much complexity. 

You can already  create a new store  > PoS 1 Store, add user PoS manager 1 > Add as guest. The only thing here is that such user can create new apps. The only downside is that such user can create his own stores and apps. If we want to limit that, why just not add new user-role PoS manager?

**Comment by bitcoinshirt** [comment]
How about a new user role: **app manager** with a drop-down to select a certain app(s) or a checkbox.
Not sure how feasible it is, but I think it's good to limit access, can come in handy in retail for PoS managers where we want them to be able to check invoices and payments in wallet, but not to create stores and apps themselves.

**Comment by darkban** [comment]
I think it's a good idea ... but you should also choose the amount of services

for example ... the BOB user can create 3 stores and 6 pos ...
therefore limit the services and quantities available

**Comment by bitcoinshirt** [comment]
I don't think second suggestion makes sense. 

Why would I allow my pos manager to create 3-6 stores? If you want you can easily add same manager to any applicable store.

The only-use case for limiting amount of stores a user can create is for people who try to white-label and re-sell BTCPay services, and those people should know how to code it themselves.

**Comment by darkban** [comment]
yes, but I think you have to put a certain limit for each account otherwise you generate many stores or pos and this would weigh down the process so I think it is correct to limit this because it makes no sense that a user can create unlimited stores to unlimited pos do not you think?

**Comment by pavlenex** [comment]
FYI, someone posted a bounty that's quite similar to this issue https://github.com/btcpayserver/btcpayserver/discussions/2650

**Comment by pavlenex** [comment]
On a dev call, it was discussed that we may want to add a custom role system, similar to our API permission system, where store owner would be able to create custom role and just hand-pick the permissions.
