### ISSUE TITLE
Lightning QR codes need to show text as an alternative

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#443]
As pretty and convenient QR codes can be, I found myself scanning the node info qr on my phone and then sending it to my pc to open a channel in clightning. Can we get some easily copy-able text like we have for payment amounts and payment addresses?

**Comment by bitcoinshirt** [comment]
We have that already.
Copy tab. Is that what you mean?
![screen shot 2018-12-11 at 00 28 34](https://user-images.githubusercontent.com/36959754/49768164-c2245b00-fcdb-11e8-8c6c-f5aa2a4b0333.png)
No need to scan the QR.
