### ISSUE TITLE
[Checkout V2] Payment Request skips custom form input information

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#4446]
Repro:
1. Create Payment Request
2. Configure Checkout V2 with address/email custom form input
3. Skips step number 2 and doesn't show the form, but simply displays the QR

Seems to work on Checkout V1 just fine, labelled as a bug, but possibly something we overlooked.

**Comment by Kukks** [comment]
This is intended as a payment request sets its  own form requirement(albeit
it should take the default of the store). The payment should ask for the
form details before displaying the invoice.

**Comment by dstrukt** [comment]
Ahh I see, it does take the default of the store, so that's working as intended, but it's not asking for the form details in Checkout V2 flow, it just skips the form and goes straight to the QR.

Will likely record when I get a chance to decrease any confusion.

**Comment by dennisreimann** [comment]
> 2. Configure Checkout V2 with address/email custom form input

Where do you configure this? As kukks mentioned, for payment requests that is configured on the payment request itself and there is no more global setting for that anymore (like in the Checkout v2 PR phase).

Are you maybe using an outdated branch?

**Comment by dennisreimann** [comment]
Another possibility: You once already submitted the data for that payment request. If so, you should see it on the "Edit Payment Request" page for that PR.

**Comment by dstrukt** [comment]
> > 2. Configure Checkout V2 with address/email custom form input
> 
> Where do you configure this? As kukks mentioned, for payment requests that is configured on the payment request itself and there is no more global setting for that anymore (like in the Checkout v2 PR phase).
> 
> Are you maybe using an outdated branch?

Yeah this was configured on the payment request itself, and I'm on the latest for master.

Tried to repro the issue and not getting that issue anymore, not really sure what was happening in that 1 instance, going to keep trying, if can't, will close.
