### ISSUE TITLE
Add upload logo, favicon and edit home page whitout fork

### ISSUE THREAD

**Issue by darkban** [btcpayserver/btcpayserver#445]
I think this implementation is very important and would allow not to fork a lot to modify the home page ... I think it's important to take care of this aspect both to add your logo, favicon and to correct the home without having to fork

**Comment by bitcoinshirt** [comment]
Duplicate of #437 and on top of that discussed and explained on Slack on more than one occasion
Related sort of with #442 
This user keeps asking for us to make white-labeling easier. All of these changes can already be done and are not our priority on the front-end. Closing this as it's really been discussed already.
