### ISSUE TITLE
[Bug]: [Checkout v1] Persian is missing from the language dropdown

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#4451]
### What is your BTCPay version?

BTCPay v1.7.2.0 

### How did you deploy BTCPay Server?

Docker

### What happened?

On the checkout page in the language dropdown it seems there is Persian missing although we have it on the transifex page.

See this conversation for context: https://chat.btcpayserver.org/btcpayserver/pl/3q7jc5m357f8jxfz7n1ahyew5c

### How did you encounter this bug?

Go to any invoice checkout page. Click on the language dropdown. 

### What browser do you use?

Brave 1.46 based on Chromium 108 on MacOS

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
It seems @britttttk disactivated it 4 years ago.
Unsure why, reactivating it and will ask review from our persian user.

![image](https://user-images.githubusercontent.com/3020646/208334041-dade2d38-bb0b-419b-9306-40aae2bb1ea0.png)

**Comment by NicolasDorier** [comment]
Ah indeed I remember now thanks. I don't know if it's still the case.
We will see if the persian user complains.

**Comment by NicolasDorier** [comment]
btw, the "English" keyword in persian shouldn't be "English" but "Persian". I changed it with google translate: 

فارسي

**Comment by firildax** [comment]
Ok, I will have look at transifex, and I knew it's not @britttttk fault, she and also all of you doing well I appreciate it.
