### ISSUE TITLE
[Bug]: HTTP 500 when select Bitcoin from /WALLETS after wallet has been created/imported

### ISSUE THREAD

**Issue by kulisekf** [btcpayserver/btcpayserver#4454]
### What is your BTCPay version?

v1.7.2.0

### How did you deploy BTCPay Server?

Manual install with PSQL

### What happened?

After select Bitcoin from /wallets after wallet has been created I got HTTP ERROR 500 -> if I access the https://.../wallets/.../transactions
The problem appeared after updating to version v1.7.1.0. (everything worked on the previous version), the problem persists even after the update to version 1.7.2.

### How did you encounter this bug?

After setting up Bitcoin wallet -> click on Wallets/Bitcoin -> see error HTTP ERROR 500

### Relevant log output

```shell
Log from btcpay server sevice:

Dec 17 20:05:29 btcpay-server dotnet[2305777]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
Dec 17 20:05:29 btcpay-server dotnet[2305777]:   Exception data:
Dec 17 20:05:29 btcpay-server dotnet[2305777]:     Severity: ERROR
Dec 17 20:05:29 btcpay-server dotnet[2305777]:     SqlState: 42703
Dec 17 20:05:29 btcpay-server dotnet[2305777]:     MessageText: column "AType" does not exist
Dec 17 20:05:29 btcpay-server dotnet[2305777]:     Hint: Perhaps you meant to reference the column "wos.Type".
Dec 17 20:05:29 btcpay-server dotnet[2305777]:     Position: 278
Dec 17 20:05:29 btcpay-server dotnet[2305777]:     File: parse_relation.c
Dec 17 20:05:29 btcpay-server dotnet[2305777]:     Line: 3393
Dec 17 20:05:29 btcpay-server dotnet[2305777]:     Routine: errorMissingColumn
```

### What browser do you use?

Google chrome 108.0.5359.125
Microsoft Edge 108.0.1462.46
Opera GX 93.0.4585.52

### Additional information

When creating a new store, setting up a wallet (using various methods), the problem persists.
If i try to access /WALLETS/Bitcoin by entering full address like https://.../stores/.../onchain/BTC/settings -> everything works
I mean this issue is linked to [https://github.com/btcpayserver/btcpayserver/issues/4403](url).
Discovered and solved together with @mbio16

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
@kulisekf does the [solution provided here](https://github.com/btcpayserver/btcpayserver/issues/4403#issuecomment-1347606557) help you solve the issue?

**Comment by kulisekf** [comment]
If i create hot wallet i also get ERROR 500 at the end of the process. However when i go to https://.../stores/... everything works.
At the same time, if I manually enter https://.../stores/.../onchain/BTC/settings in the search bar, I can see that the wallet is created and I can, for example, generate a receive address and make changes to the settings. From this I conclude that the wallet has been created and is working properly in the background. The problem occurs when I try to go to https://.../wallets/.../transactions, as if the subpage itself is not working. Also not working https://.../wallets/.../export?format=...
But for example https://.../wallets/.../rescan and other links related to working with the wallet work (or at least I didn't find another one that didn't work). Also i put wallet through xpub which has some satoshi and after rescan i can see the balance.

**Comment by NicolasDorier** [comment]
This can only happen if you deployed BTCPay on master branch.

**Comment by NicolasDorier** [comment]
This error is related to a breaking change we made between two versions while in development.
The master branch should not be run in production, and we only attempt to avoid breaking change between versions, not between commits in devs.

I can't help you to fix this problem. But basically your db schema is different from what is expected in the latest release, you should try to fix it via psql by yourself, or just start from scratch.

**Comment by mbio16** [comment]
can we just wipe out db, and restart service.   Will schemas be created on the fly?

**Comment by NicolasDorier** [comment]
Yes. You are developping? If you use the docker-compose in dev time (in BTCpayServer.Tests), it's just `docker-compose down --v`

**Comment by NicolasDorier** [comment]
Closing this as this isn't really supported. If you are developing, you can come on the development channel on chat.btcpayserver.org
