### ISSUE TITLE
Add/Remove products on PoS itself and limit it with user-role

### ISSUE THREAD

**Issue by darkban** [btcpayserver/btcpayserver#446]
Guys I had an idea to make more userfriendly people who want to manage the pos but who are not familiar ... I thought about adding an ADD PRODUCTS type button where mercant insetendo a password can easily add or delete their products without need to enter the backend but directly in frontend ... to step ...

step 1 title
step 2 image
step 3 price
step 4 description

**Comment by bitcoinshirt** [comment]
What you're referring as back-end is not really a back-end. 
Your request is to make it more user-friendly on the front-end to add products, modified the title accordingly.

**Comment by mariodian** [comment]
> That said I don't think this is needed, but maybe a better and cleaner way to add products on BTCPay side.

I'm thinking of hiding the json textarea (in the POS creation) and replacing it with a javascript UI with input fields. That way no change need to be done on the backend but it would make it much easier for vendors to manage products. Will start working on it when the PoS frontend is finalized and implemented.

**Comment by darkban** [comment]
guys I was thinking about what to improve on the pos and I realized that missing the language of defaul that I think is essential

**Comment by bitcoinshirt** [comment]
This is now added in #456
