### ISSUE TITLE
Low contrast of Pay button when bright color is set for branding

### ISSUE THREAD

**Issue by prusnak** [btcpayserver/btcpayserver#4466]
### What is your BTCPay version?

v1.7.1.0

### How did you deploy BTCPay Server?

manual

### What happened?

I see low contrast of Pay button when using the new checkout and set custom branding with bright color

### How did you encounter this bug?

1. set "Use the new checkout"

<img width="317" alt="Screenshot 2022-12-22 at 12 13 17" src="https://user-images.githubusercontent.com/42201/209122463-39fc904c-5d2c-4746-bfd4-74b2ca32cdee.png">

2. set bright color in Brand Color

<img width="157" alt="Screenshot 2022-12-22 at 12 11 04" src="https://user-images.githubusercontent.com/42201/209122479-c7ae7e7b-2c2b-4091-8996-f0760230652b.png">

3. generate a payment

4. observe low contrast on `Pay with wallet` button

![Screenshot 2022-12-22 at 11 52 00](https://user-images.githubusercontent.com/42201/209122537-876ea63d-157b-4b98-b7eb-d8b930eb5c91.png)

### What browser do you use?

Safari

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by prusnak** [comment]
I would expect the dark color to be used as a button label for bright backgrounds:

<img width="317" alt="Screenshot 2022-12-22 at 12 15 56" src="https://user-images.githubusercontent.com/42201/209122820-c9bc5f31-3e7b-4758-a54b-eb077bdeff26.png">

I think we can use a simple logic: when all R, G, B components of branding color are >= 0x80, a dark text color should be used.

**Comment by dennisreimann** [comment]
#4459 adds a custom CSS option which you can then use to do more advanced customization in case the simple brand color option does not work for you.
