### ISSUE TITLE
[Bug]: i bought a subscription for redengine but i didn t received it

### ISSUE THREAD

**Issue by Raresstef** [btcpayserver/btcpayserver#4467]
### What is your BTCPay version?

I don t know

### How did you deploy BTCPay Server?

I don t know

### What happened?

![image](https://user-images.githubusercontent.com/121233552/209128452-df58126f-25b8-4672-9cfe-292a7332ada8.png)
I bought it trought an alt coin and it said confirmed but i didn t get the sub

### How did you encounter this bug?

i bought it  trought an al coin and they didn t received it

### Relevant log output

```shell
I don t know
```

### What browser do you use?

Chrome

### Additional information

none

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
We do not sell anything — we just offer BTCPay Server as an open-source project for merchants, which run their own instances. Please contact the merchant to resolve this issue, we cannot help you with that.
