### ISSUE TITLE
[Feature] Greenfield: Add the preimage in GET {invoiceId}/payment-methods

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#4475]
A user would need the pre image for a successful payment in [the invoice's payment methods route](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Invoices_GetInvoicePaymentMethods)

I believe it can be add in `LightningListener.AddPayment` however the passed `LightningInvoice` object doesn't contain the pre-image. So it probably require a change in the lightning library as well. Or maybe there is a call in the lightning client to fetch the payment image?

See: https://twitter.com/JohnOnChain/status/1606299203415597058?s=20&t=yEYK8OAUqNpnGkNLX2kXiA

**Comment by dennisreimann** [comment]
I recently added it in this PR https://github.com/btcpayserver/BTCPayServer.Lightning/pull/111

We could merge it, though the original purpose of the PR isn't done yet. Would need to remove the CLN custom records part as it isn't correct.

**Comment by dennisreimann** [comment]
Extracted the necessary prerequisites in btcpayserver/BTCPayServer.Lightning#117

**Comment by NicolasDorier** [comment]
I think the invoice's payment methods route should still have this data. We should also add it to the lightning payment endpoints.
