### ISSUE TITLE
Password Reset UX Issues

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#448]
When a user resets their password for BTCPay these issues occur:

1.  User clicks on the email link for password reset, it takes them back to BTCPay to reset it.
    * **Issue**: Page is completely left aligned
    * **Possible Solution**: Page needs some white space added between left page edge and password boxes.
    * Reason: looks ugly

![image](https://user-images.githubusercontent.com/39231115/49891544-0579e900-fe04-11e8-918d-c63c7f71e75d.png)

2.  User provides new password information and clicks update password.
    * **Issue**: Page is completely blank after updating.
    * **Possible Solution**: Add confirmation text on page, "Password has been updated"
    * Reason: new password status is unknown to user

**Comment by Eskyee** [comment]
@rockstardev can fix this up, when he's back in town ;)

**Comment by sipsorcery** [comment]
Fixed in #449.

**Comment by NicolasDorier** [comment]
thanks!
