### ISSUE TITLE
[Bug]: LNBank and LNDHub (via lnbits extension) Stopped to work

### ISSUE THREAD

**Issue by PraiaBitcoin** [btcpayserver/btcpayserver#4482]
### What is your BTCPay version?

I'm running BTCPayServer 1.7.13

### How did you deploy BTCPay Server?

Running on MynodeBtc via Docker

### What happened?

After upgrade to version 1.7.13 all stores with wallets using LNBits LNDHub Extension or LNBank stopped to work. 

### How did you encounter this bug?

When you create a store, and setup a lightning wallet to use LNBank wallet or a LNBits wallet (via LNDHUb extension), BTCPayServer shows the node as offline and it can't generate invoices. 

![image](https://user-images.githubusercontent.com/94765727/209577348-117f6562-c3e0-4c5f-8703-c9faa42e5a2f.png)

No Idea how to fix. I think is a bug! 

Any help is welcome!  

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
LNbank needs to be upgraded to v1.3.8 — you can do so on the "Manage Plugins" page.

For LNDhub via LNbits: We discussed the issue in lnbits/lnbits#1182 and LNbits just doesn't offer full LNDhub API-compatibility, so that we cannot integrate it.
