### ISSUE TITLE
OpenGraph tag support

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#4493]
Not 100% sure technically if we can or want to support this, or already do (doesn't look like it) but...

Would be nice to be able to post a Payment Request, Pull Payment, Receipt, etc.. and have OpenGraph tags generated.

This needs design, but starting the Issue to collect any thoughts or feedback before I update the ticket with the relevant work.

**Comment by pavlenex** [comment]
We could, but this is usually private links, I doubt someone would share receipt, invoice or  a payment request on social? So is it really relevant to support opegraph tags for SEO? I assume SEO would only be the benefit here or am I missing something else?

**Comment by dennisreimann** [comment]
I also don't think this is necessary as the only beneft I can see would be an enhanced p[review when sharing on social media, which I doubt is a frequent use case.

We could think about this for the public Crowdfunding though, because those pages tend to get shared.

**Comment by dstrukt** [comment]
Yes, the original intention was Receipts and Crowdfund .. or possibly other plugins that might have more public visibility in the future. Ideally we have a relatively dynamically generated OG tag, but wanted to surface for discussion.
