### ISSUE TITLE
[Bug]: Get invoices/{id} returns invoice-not-found for expired invoices

### ISSUE THREAD

**Issue by waggyza** [btcpayserver/btcpayserver#4495]
### What is your BTCPay version?

 v1.7.3.0+09d5f5a08

### How did you deploy BTCPay Server?

Azure Docker

### What happened?

When I query an expired invoice by its id I received the following:

{
    "code": "invoice-not-found",
    "message": "Impossible to find a lightning invoice with this id"
}

However if I query all invoices, then I do see that invoice with the status as "Expired"

My expectation is to get the same information for a particular invoice that is seen under the get all invoices response i.e. get the invoice with status as "Expired"

### How did you encounter this bug?

Post a new invoice using:
https://docs.btcpayserver.org/api/v1/server/lightning/{cryptoCode}/invoices

Wait for expiry time to pass

Query the invoice using the id received in the post above:
https://docs.btcpayserver.org/api/v1/server/lightning/{cryptoCode}/invoices/{id}

Note the response:
{
    "code": "invoice-not-found",
    "message": "Impossible to find a lightning invoice with this id"
}

Now query all invoices using:
https://docs.btcpayserver.org/api/v1/server/lightning/{cryptoCode}/invoices

Note that the invoice that was shown as invoice-not-found in the previous GET request is showing up in the list of all invoices with status as "Expired"

### What browser do you use?

Firefox

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Hey, can you check if what I wrote in [this comment](https://github.com/btcpayserver/btcpayserver/issues/4298#issuecomment-1351459082) applies here? Namely, are you using the correct ID?

**Comment by pavlenex** [comment]
ping @waggyza we're waiting for your reply.

**Comment by dennisreimann** [comment]
Pleae reopen with more details if it still doesn't work.
