### ISSUE TITLE
[Bug]: LNBank + Lightning Address = error "could not generate invoice with description hash"

### ISSUE THREAD

**Issue by Perlover** [btcpayserver/btcpayserver#4496]
### What is your BTCPay version?

BTCPay v1.7.3.0+09d5f5a08
LNBank v1.3.8.0
Lightning backend as LND internal

### How did you deploy BTCPay Server?

LunaNode Docker setup

### What happened?

If we for a Store with LNBank wallet type create  a Lightning Address, then receiving funds to Lightning Address is not possible - an error occurs on the side of the sender of funds "lightning node could not generate invoice with description hash"

### How did you encounter this bug?

1. Install plugin LNBank
2. Create a Store with "Use LNbank wallet" Lightning Wallet type (may be to be needed to create a LNBank wallet before)
3. In "Lightning Address" from left panel to create lightning address
6. To try to send there from SBW/Phoenix and other wallets - we get error "lightning node could not generate invoice with description hash"

### Additional information

If a Store created with a Lightning wallet type as "Use internal node"-  a sending to Lightning Addresses works flawlessly!

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Perlover** [comment]
May be relevanted with this issue: https://github.com/btcpayserver/btcpayserver/issues/4490

**Comment by Perlover** [comment]
In Wallets / Lightning / Settings I have turned on "LNURL enabled for standard invoices/Required for Lightning Address, the pay button and apps." (I tried with and without turned this option) - the same error.

**Comment by Perlover** [comment]
Correction: the bug appears only when the Lightning Address is created for a Store that has a Lightning Wallet as "Use LNbank wallet" type. If a Store has a Lightning wallet type as "Use internal node" - a sending to Lightning Addresses works flawlessly!

**Comment by dennisreimann** [comment]
We'll fix this with the next release
