### ISSUE TITLE
[Bug]: Crash when accessing /register endpoint after a fresh install on Ubuntu

### ISSUE THREAD

**Issue by pox** [btcpayserver/btcpayserver#4497]
### What is your BTCPay version?

Running v1.7.3

### How did you deploy BTCPay Server?

I have followed the [Extended Manual Setup](https://docs.btcpayserver.org/Deployment/ManualDeploymentExtended/) guide to install on Ubuntu. All the steps seemingly succeeded.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

### What happened?

Once the server is up and running (`syslog` does not show any errors) I try to GET the main page, get redirected to `/register` and when the browser requests `/register` the server crashes.

Logs attached below (trimmed because the stack dump is huge).

### How did you encounter this bug?

See above.

### Relevant log output

```shell
Jan 01 18:11:52 btcnode run.sh[55888]: info: Configuration:  Data Directory: /home/bitcoin/.btcpayserver/Main
Jan 01 18:11:52 btcnode run.sh[55888]: info: Configuration:  Configuration File: /etc/btcpay/btcpay.config
Jan 01 18:11:53 btcnode run.sh[55888]: info: BTCPayServer.Plugins.PluginManager: Loading plugins from /home/bitcoin/.btcpayserver/Plugins
Jan 01 18:11:53 btcnode run.sh[55888]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.7.3.0
Jan 01 18:11:53 btcnode run.sh[55888]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 1.7.3.0
Jan 01 18:11:53 btcnode run.sh[55888]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Crowdfund - 1.7.3.0
Jan 01 18:11:53 btcnode run.sh[55888]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PayButton - 1.7.3.0
Jan 01 18:11:53 btcnode run.sh[55888]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PointOfSale - 1.7.3.0
Jan 01 18:11:53 btcnode run.sh[55888]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Custodians.Fake - 1.0.0.0
Jan 01 18:11:53 btcnode run.sh[55888]: info: Configuration:  Supported chains: BTC
Jan 01 18:11:53 btcnode run.sh[55888]: info: Configuration:  BTC: Explorer url is http://127.0.0.1:24444/
Jan 01 18:11:53 btcnode run.sh[55888]: info: Configuration:  BTC: Cookie file is /home/bitcoin/.nbxplorer/Main/.cookie
Jan 01 18:11:53 btcnode run.sh[55888]: info: Configuration:  Network: Mainnet
Jan 01 18:11:55 btcnode run.sh[55888]: info: Configuration:  Root Path: /
Jan 01 18:11:56 btcnode run.sh[55888]: info: Configuration:  Connection to NBXplorer's database successful, dashboard and reporting features activated.
Jan 01 18:11:56 btcnode run.sh[55888]: info: PayServer:      Starting listening NBXplorer (BTC)
Jan 01 18:11:56 btcnode run.sh[55888]: info: PayServer:      Start watching invoices
Jan 01 18:11:56 btcnode run.sh[55888]: info: PayServer:      Starting payment request expiration watcher
Jan 01 18:11:56 btcnode run.sh[55888]: info: PayServer:      BTC: Checking if any pending invoice got paid while offline...
Jan 01 18:11:56 btcnode run.sh[55888]: info: PayServer:      0 pending payment requests being checked since last run
Jan 01 18:11:56 btcnode run.sh[55888]: info: Configuration:  Now listening on: http://127.0.0.1:23000
Jan 01 18:11:56 btcnode run.sh[55888]: info: PayServer:      BTC: 0 payments happened while offline
Jan 01 18:11:56 btcnode run.sh[55888]: info: PayServer:      Connected to WebSocket of NBXplorer (BTC)
Jan 01 18:12:36 btcnode run.sh[55888]: fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMNC2BNDTR2R", Request id "0HMNC2BNDTR2R:00000002": An unhandled exception was thrown by th
e application.
Jan 01 18:12:36 btcnode run.sh[55888]: System.InvalidOperationException: Cannot find compilation library location for package 'System.Security.Cryptography.Pkcs'
Jan 01 18:12:36 btcnode run.sh[55888]:    at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
Jan 01 18:12:36 btcnode run.sh[55888]:    at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
Jan 01 18:12:36 btcnode run.sh[55888]:    at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPartExtensions.<>c.<GetReferencePaths>b__0_0(CompilationLibrary library)
Jan 01 18:12:36 btcnode run.sh[55888]:    at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
```

### What browser do you use?

Happens with curl, safari, chrome...

### Additional information

Possibly related to https://github.com/btcpayserver/btcpayserver/pull/4113 or to https://github.com/btcpayserver/btcpayserver/issues/3258

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pox** [comment]
Guys, I'd appreciate eyes on this. It seems the non-docker setup is currently broken.

**Comment by dennisreimann** [comment]
Can you check if this works for you? https://stackoverflow.com/a/70741481

**Comment by pox** [comment]
Yes! Thanks @dennisreimann that did it.

**Comment by dennisreimann** [comment]
@NicolasDorier Can we add this in general or should we just document it on the manual deployment guide?

**Comment by NicolasDorier** [comment]
This is weird I believe it happens only on some distro. I never been able to replicate it.  Maybe we cna put this property, but I don't understand the consequences.

**Comment by NicolasDorier** [comment]
I am thinking instead, we should rewrite the manual deployment and ask people to run `dotnet publish` rather than `dotnet build`.
Or maybe I can add `GenerateRuntimeConfigDevFile`  only for `dotnet build -c Release`. Will check

**Comment by NicolasDorier** [comment]
It seems people having this problem are on 20.04. I tried from scratch couldn't replicate.
That's weird...

**Comment by raucao** [comment]
I can confirm that this happens for me on Ubuntu 20.04.

**Comment by raucao** [comment]
> Yes! Thanks @dennisreimann that did it.

@pox Where exactly did you add that config line? Doesn't seem to fix the problem for me.

**Comment by NicolasDorier** [comment]
@raucao  add `GenerateRuntimeConfigDevFile` in [the BTCPayServer.csproj](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/BTCPayServer.csproj)

```csproj
<PropertyGroup>
   ...
   <GenerateRuntimeConfigDevFile>true</GenerateRuntimeConfigDevFile>
  ...
</PropertyGroup>
```

Alternatively what you can try is to not modify the csproj and instead use

```bash
export GenerateRuntimeConfigDevFile="true"
```
before building. Please let us know.

**Comment by raucao** [comment]
OK, thanks. I thought that's what I had done in https://github.com/67P/btcpayserver/commit/bb4637a82f696cd84301f459f0c2f921276326cb but that didn't fix it.

Is there a way to force a fresh build that definitely respects the config change? It seems like maybe it didn't compile the whole program with the new flag after I changed it. (I have near-zero experience with .NET., so I'm just running `build.sh` after changing things.)

**Comment by dennisreimann** [comment]
@raucao Running `dotnet clean && dotnet restore` should give you a clean state for a new build.

**Comment by raucao** [comment]
Thanks. Same runtime exception with both the flag enabled (as linked above) and when exporting the variable in bash.

**Comment by NicolasDorier** [comment]
@raucao let me try something. I can maybe change the run.sh and the build.sh to avoid the bug

**Comment by NicolasDorier** [comment]
@raucao can you try this:
In the BTCPayServer folder:

```
dotnet publish --no-cache -c Release
```

Then run

```
cd bin\Release\net6.0\publish\
dotnet BTCPayServer.dll
```

**Comment by raucao** [comment]
This worked! :clap:

**Comment by dennisreimann** [comment]
@NicolasDorier can you update the docs? This seems to be something a few people run into.

**Comment by NicolasDorier** [comment]
@dennisreimann rather than updating the doc, I will update the scripts.

**Comment by dennisreimann** [comment]
Better yet, just wanted to ensure this doesn't come up again :)
