### ISSUE TITLE
Feedback on Invoices page

### ISSUE THREAD

**Issue by lepipele** [btcpayserver/btcpayserver#45]
Not urgent

![invoice-page](https://user-images.githubusercontent.com/5191402/35430018-1a5ec2b0-023c-11e8-981f-a0f794aba42e.png)

  1. Please add OrderId 
  2. For confirmed/completed orders, Checkout link should go away
  3. Hyperlink few things: ORDER ID and BTC Addresses
    - In the BTCPay server settings, have a URL pattern so we can generate links that hyperlink direct to the view order link on WooCommerce (or whatever). For example `https://oururl.com/?post=1234`... in configuration we would put `https://oururl.com/?post={order_id}` and now {order_id} would be replaced for each valid hyper link
     - hyper link email addresses with mailto:
     - make the link Url Redirect - Clickable

**Comment by NicolasDorier** [comment]
[x] Please add OrderId

**Comment by NicolasDorier** [comment]
Closing this, this has been done
