### ISSUE TITLE
srvModel.currencyInfo wrong data

### ISSUE THREAD

**Issue by mariodian** [btcpayserver/btcpayserver#450]
I see that a new `currencyInfo` object was added to `srvModel` (for PoS). However for many currencies it shows wrong data.

For example for Indian Rupee it looks like this:

```
{
currencySymbol: "INR"
decimalSeparator: "."
divisibility: 2
prefixed: true
thousandSeparator: ","
}
```

However, `srvModel.items` will show amounts with the correct symbol: `Buy for ₹ 1,000.00`

For example for Euro, the object looks alright (the Euro symbol is provided):

```
{
currencySymbol: "€"
decimalSeparator: ","
divisibility: 2
prefixed: false
thousandSeparator: " "
}
```

But the Euro symbol in `srvModel.items` is separated by space like so: `100,00 €` and the `currencyInfo` object returns the symbol without the space. And I have no way of knowing which currency uses a space separator for symbols and which don't.

Is it possible to fix this? Otherwise i'll have to stick with my custom formatCurrency function which predefines the symbol for major currencies.

**Comment by mariodian** [comment]
Found other issues.

For example one of the Arab currencies IRR says the `divisibility` is 2:

```
{
currencySymbol: "IRR"
decimalSeparator: "٫"
divisibility: 2
prefixed: true
thousandSeparator: "٬"
}
```

but the `srvModel.items` show amounts like this `Buy for ریال1٬000` (thousand) which completely omits the decimal separator.

There are inconsistencies for most currencies except for 10 or so major ones.

**Comment by NicolasDorier** [comment]
Don't come back to what you were doing, it was not working for JPY nor for BTC. I will fix this.

**Comment by NicolasDorier** [comment]
It does not show `Buy for ریال1٬000` for me but `1,000/00ريال`
