### ISSUE TITLE
[Bug]: NBXplorer is synchronizing

### ISSUE THREAD

**Issue by hb2uk** [btcpayserver/btcpayserver#4507]
### What is your BTCPay version?

BTCPay Server v1.7.3.0+09d5f5a08

### How did you deploy BTCPay Server?

Docker image on an antsle

### What happened?

NBXplorer is synchronizing and has been for 5 days now. I removed the data file to force a resync and it gets stuck at the same point. 

### How did you encounter this bug?

I log into the server and see node status syncing.

### Relevant log output

```shell
no specific log
```

### What browser do you use?

Edge, chrome, firefox

### Additional information

I had a power cut, the ups held the server for sometime then it dropped, when it powered up the node syncd then nxexplorer hangs and has stayed hung. I deleted the data files as another issue resolved it, however this is still hanging.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Can you check the Docker container logs for NBXplorer and the Bitcoin container?

**Comment by dennisreimann** [comment]
Please reopen with more information if this is still a problem.
