### ISSUE TITLE
[Bug]: In Crowdfunding, if Shop sales are included, are considered as Paid contributions the Expired invoices

### ISSUE THREAD

**Issue by Luca399** [btcpayserver/btcpayserver#4508]
### What is your BTCPay version?

v1.7.3.0+09d5f5a08

### How did you deploy BTCPay Server?

Lunanode

### What happened?

Hi. I created a Shop and a Crowdfunding Page and chose the option to "Count all invoices created on the store as part of the goal". But made some fake big buys of 50.000 -  1.000.000 € on the Shop, few months ago, that obviously Expired, but on the Crowdfunding page they still appear as "real sales" :slightly_smiling_face: Any idea why? 
Shop:
https://btcpay.eroaward.com/apps/4UoDbZyeDxYEuF66XASN3hBP4rSq/pos
Crowdfunding:
https://btcpay.eroaward.com/apps/3ZWUwerGVezpSRJdLUc38BbqAscS/crowdfund
Printscreens:
https://chat.btcpayserver.org/api/v4/files/jch1mwtddfd3bp5py6sc8ohbqa/preview

https://chat.btcpayserver.org/api/v4/files/sudrtfru3t8xffykb1qa56cdrc/preview

### How did you encounter this bug?

Described above

### What browser do you use?

Google Chrome, Version 108.0.5359.125 (Official Build) (64-bit)

### Additional information

Printscreens:

https://chat.btcpayserver.org/api/v4/files/jch1mwtddfd3bp5py6sc8ohbqa/preview

https://chat.btcpayserver.org/api/v4/files/sudrtfru3t8xffykb1qa56cdrc/preview

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by ndeet** [comment]
@Luca399 I tried to reproduce but was not able to. Although I had a 10 million and 5000 USD invoices created manually which expired. They are not counted against the crowdfunding goal as it should be.

Q1: did you create those invoices also manually or did you do that via the API or somewhere else?

Q2: Can you post a screenshot of your invoices, maybe one showing all and the second one filtered only by settled ones?

Q3: Can you try to create a new crowdfund app and try to reproduce the problem there?

**Comment by aim2pleas55** [comment]
Alot of this I don't understand I need help with the steps ít take to complete this please 

Sent from Yahoo Mail on Android 
 
  On Sat, Jan 7, 2023 at 11:41 AM, ***@***.***> wrote:   


@Luca399 I tried to reproduce but was not able to. Although I had a 10 million and 5000 USD invoices created manually which expired. They are not counted against the crowdfunding goal as it should be.

Q1: did you create those invoices also manually or did you do that via the API or somewhere else?

Q2: Can you post a screenshot of your invoices, maybe one showing all and the second one filtered only by settled ones?

Q3: Can you try to create a new crowdfund app and try to reproduce the problem there?

**Comment by ndeet** [comment]
> Q1: did you create those invoices also manually or did you do that via the API or somewhere else?

The question here is, did you create the "fake big buys" directly in the BTCPay Server interface?

> Q2: Can you post a screenshot of your invoices, maybe one showing all and the second one filtered only by settled ones?

In your store, you have the menu entry "Invoices" on the left and it looks like this:
![image](https://user-images.githubusercontent.com/1136761/211165563-e42bb7e8-56aa-4e14-aa17-91f7cd17804f.png)

You can also set a filter to only show "settled" invoices like here:
![image](https://user-images.githubusercontent.com/1136761/211165634-e65e5541-abf7-47a3-bb1f-9141f9e65d15.png)

> Q3: Can you try to create a new crowdfund app and try to reproduce the problem there?

Like you did with your current crowdfund app, can you please create a new one and try to make some invoices and let them expire to see if the problem is also on a new crowdfund app:

![image](https://user-images.githubusercontent.com/1136761/211165692-767a237d-d900-4a04-8f4e-053afe9f3410.png)

Hope it is clearer now.

**Comment by Luca399** [comment]
> > Q1: did you create those invoices also manually or did you do that via the API or somewhere else?
> 
> The question here is, did you create the "fake big buys" directly in the BTCPay Server interface?
> 
> > Q2: Can you post a screenshot of your invoices, maybe one showing all and the second one filtered only by settled ones?
> 
> In your store, you have the menu entry "Invoices" on the left and it looks like this: ![image](https://user-images.githubusercontent.com/1136761/211165563-e42bb7e8-56aa-4e14-aa17-91f7cd17804f.png)
> 
> You can also set a filter to only show "settled" invoices like here: ![image](https://user-images.githubusercontent.com/1136761/211165634-e65e5541-abf7-47a3-bb1f-9141f9e65d15.png)
> 
> > Q3: Can you try to create a new crowdfund app and try to reproduce the problem there?
> 
> Like you did with your current crowdfund app, can you please create a new one and try to make some invoices and let them expire to see if the problem is also on a new crowdfund app:
> 
> ![image](https://user-images.githubusercontent.com/1136761/211165692-767a237d-d900-4a04-8f4e-053afe9f3410.png)
> 
> Hope it is clearer now.

Hi.
You were right, I tried to repeat this process, but couldn't...and now that you told me to watch all the invoices, indeed I did a mistake, I manually "Marked as settled" one of this 1 million sale, to test how it works and forgot that I did it :)))
So, no bugs here, it was my mistake, I apologize and many thanks for the help!
Anyway, I am very happy it works well, as my plans were to use it a lot!
Case closed.
