### ISSUE TITLE
Reset template to default values

### ISSUE THREAD

**Issue by 2pac1** [btcpayserver/btcpayserver#451]
It would be useful if we could have a text link bottom right, bellow the POS store, in order to reset the code for the dummy store to default values.

**Comment by bitcoinshirt** [comment]
I don't know but this now feels redundant with #456 so newbies can use that regardless.
What do you think @2pac1 should we close this one?

**Comment by bitcoinshirt** [comment]
I don't understand what you mean. Can you elaborate?

**Comment by bitcoinshirt** [comment]
I talked to @2pac1 and since the issue related to old way of adding products via templates, now that #456 was merged, it's the best to close this one, especially because we'll probably remove code templates from the UI at some point as they are cumbersome to manage.
