### ISSUE TITLE
[Bug]: Wrong messages sent to webhook if transaction is RBF

### ISSUE THREAD

**Issue by rtarnaud** [btcpayserver/btcpayserver#4515]
### What is your BTCPay version?

v1.7.3.0+09d5f5a08

### How did you deploy BTCPay Server?

Docker

### What happened?

When using a RBF transaction to pay an invoice, messages regarding an expired invoice are sent in priority to (any pre-defined) webhook, instead of the "real" ones.

### How did you encounter this bug?

- Creation of a webhook to handle all the events (everything) via the API
- Creation of an invoice via the API
- Creation of an iframe of the checkout link within the web app
- Selection of the BTC on-chain payment method
- Went to Electrum (testnet) to send the payment but realised that I did not have enough funds. Hence, I requested some test BTC from a faucet and as as soon as the transaction had been detected and my balance credited on the wallet, I sent the payment for my invoice. Electrum labeled that transaction as RBF.
- The widget on the checkout page set itself to the paid state which is the expected behavior as the invoice speed policy was set to High.
- Now comes the weird part: Instead of receiving some notifications of my invoice status change (that had just been set to Processing) on the webhook, I received notifications (on that same webhook) for another invoice that I had created more than a month ago while testing BTCPay trough the PoS UI. I can see that the messages are related to my recent payment because the amount mentioned in the message payload is exactly the one I have sent for the recent invoice.

### Additional information

My biggest issue here is that those junk messages have precedence over the real ones that my app need to update the invoice status. I imagine that they all need to be sent and depleted first before the real ones in the queue can be sent.

In my previous tests where I only sent payments from fully confirmed UTXOs, I did not encounter this behavior so I imagine this has something to do with RBF but of course, this is just an assumption.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
@NicolasDorier Can you look into this one please?

**Comment by rtarnaud** [comment]
Closing it as the Bitcoin wallet that was active at the time of the generation of the old invoice was watch-only and might have been generated with the xpub from Electrum. Although, interestingly enough, this problem only shows when the payment transaction is RBF.
