### ISSUE TITLE
POS template error - highlight the error and point to it

### ISSUE THREAD

**Issue by 2pac1** [btcpayserver/btcpayserver#452]
Hey guys,
 
When you modify your template, if you forget : then you get an error at the end and cant find what you did wrong.
Can we highlight the part that is wrong so user does not have to go back, and edit again hoping that he doesnt make a mistake this time.

If it is highlighted then it can be corrected right away. 
That would be useful.

**Comment by bitcoinshirt** [comment]
I don't know but this now feels redundant with #456 so newbies can use that regardless.
What do you think @2pac1 should we close this one?

**Comment by bitcoinshirt** [comment]
I talked to @2pac1 and since the issue related to old way of adding products via templates, now that #456 was merged, it's the best to close this one, especially because we'll probably remove code templates from the UI at some point as they are cumbersome to manage.
