### ISSUE TITLE
Get internal lightning node invoices should have separate authorization

### ISSUE THREAD

**Issue by ArttuPakarinen** [btcpayserver/btcpayserver#4523]
BTCPayServer Greenfield API provides an endpoint to get internal ligthning node invoices. This requires authorization of canuseinternallightningnode. Isn't this way too wide authorization for a GET ? With the same authorization numerous other things can be done to internal LN.

For creating internal LN invoices there exists already an authorization of cancreatelightninginvoiceinternalnode, which is perfect. Such separate authorization should be made for GET LN invoice also.

**Comment by ArttuPakarinen** [comment]
I looked into the code and made changes to make this happen, i will later try to figure out how to push commit to the project and how to test the changes, have never taken part to another github project

**Comment by ArttuPakarinen** [comment]
Tried building;
error CS0117: 'Policies' does not contain a definition for 'CanViewInternalLightningNode' [/.../BTCPayServer/BTCPayServer.csproj]

Are the policies are in binary form? Could not find any migration to add to them?

**Comment by pavlenex** [comment]
cc @bolatovumar @dennisreimann

**Comment by ArttuPakarinen** [comment]
So here is the diff of changes i made if its any use, its looks like a no-brainer to add this.

I couldn't test properly tho, but it built at least.
[diff.txt](https://github.com/btcpayserver/btcpayserver/files/10417089/diff.txt)
