### ISSUE TITLE
[Bug]: BTCPAY does not show successful LN payments

### ISSUE THREAD

**Issue by jstrnbrg** [btcpayserver/btcpayserver#4525]
### What is your BTCPay version?

v1.6.9.0

### How did you deploy BTCPay Server?

On-premise

### What happened?

We recently had issues detecting LN payments by our BTCPAY instance which time-wise correspond to when we ran out of inbound liquidity. Some customers managed to pay a few orders successfully but BTCPAY did not recognise those payments whereas LND shows them as successful. 

As an example (invoice 3bja3Cx8hQkX4TDvhdVHs6):
- BTCPAY invoice creation date: 06/01/2023 22:14:08
- LND Settle date: 06/01/2023 22:15:21 (1 min after creation)
- BTCPAY invoice status: Expired
- BTCPAY Expiration Date: 07/01/2023 04:14:08
- BTCPAY Monitoring Date: 09/01/2023 04:14:08

Any idea what happened here?
How can we make BTCPAY re-monitor the invoice to detect the payment received by LND?

Thank you!

<img width="1060" alt="Screenshot 2023-01-11 at 10 12 28" src="https://user-images.githubusercontent.com/34884458/212089348-ae2f2bbf-7109-4af5-a3a7-d50069041cd0.png">

### How did you encounter this bug?

n/a

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
1.6.9 is a few releases behind, can you update and see if that happens in 1.7.2? Are you by any chance using LNBank?

**Comment by jstrnbrg** [comment]
@pavlenex Ok will try updating but that won't automatically fix it for the 3x affected LN payments? Since then (after we rebased channels) it seems be working again without issues.

No, we are not using LNBank, just BTCPAY without any add-ons.

**Comment by pavlenex** [comment]
I'm not really sure what the issue is in the first place tbh, if you haven't had the liquidity , there shouldnt' be payments in the first place, so unsure how you mapped those two. 

How can you know if this is true:

> Some customers managed to pay a few orders successfully

Anyway, update won't hurt, but I don't think it will solve your issue, as I it's really hard to understand what's the issue in the first place from your bug report.

**Comment by jstrnbrg** [comment]
@dennisreimann Marking as settled isn't available for these invoices. Not sure why, maybe because BTCPAY does not associate any payment with the invoice? (so far I've only seen that button for invoices that had at least a partial payment)

**Comment by NicolasDorier** [comment]
is it a docker deployment? or is LND separately hosted?

**Comment by jstrnbrg** [comment]
@NicolasDorier BTCPAY is deployed on premise via docker. The LN node is deployed separately on premise but not via docke

**Comment by NicolasDorier** [comment]
@jstrnbrg are you using the internal node?

**Comment by dennisreimann** [comment]
It seems he's using an external node configured via connection string, correct @jstrnbrg?

**Comment by jstrnbrg** [comment]
Correct @dennisreimann

**Comment by pavlenex** [comment]
Is this still an issue with latest version of btcpay @jstrnbrg ?

**Comment by bbrouwer45** [comment]
Wat moet ik doen om het geld te incasseren op mijn bankrekening nummer is; NL87RABO 0369079027    Cart number; 6697

**Comment by bbrouwer45** [comment]
TNV ,BBROUWER
