### ISSUE TITLE
[Feature] Greenfield: Add user creation via invite-link 

### ISSUE THREAD

**Issue by skyracer2012** [btcpayserver/btcpayserver#4534]
There currently is no valid option to create a user without a password.
This can be seen in [the API docs](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Users_CreateUser) and [source code](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Controllers/GreenField/GreenfieldUsersController.cs#L128).
The user creation in btcpay now supports to create a user without password, which generates a link with which a new password can be set.
I am not really confident with doing this securely myself so I would appreciate if there was a way to add it to the api.

**Comment by NicolasDorier** [comment]
Fixing this at API level. In the UI it is possible
