### ISSUE TITLE
[Bug]: Balance not displayed after rescanning

### ISSUE THREAD

**Issue by Saineolach** [btcpayserver/btcpayserver#4542]
### What is your BTCPay version?

BTCPay Server v1.4.6.0

### How did you deploy BTCPay Server?

Running BTCPay on Lunanode

### What happened?

After rescanning an LTC wallet, the tx was picked up but balance remained at 0 until maybe 10minutes later.

### How did you encounter this bug?

1. Actions>Replace Wallet 
2. Rescan wallet for missing transactions
3. Gap Limit 1000, start scan. 
4. TX appeared, balance 0

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
BTCPay Server v1.4.6.0 is an older version, does upgrading to the current version help? The Litecoin sync had some trouble a while ago and users had to reindex the blockchain — is your node fully synced?

**Comment by NicolasDorier** [comment]
@Saineolach yes on those old version there was a cache for the balance of 10min. It has been fixed in a later version. A later version still after removed the need for cache.

Update.

**Comment by dennisreimann** [comment]
Please simply reopen if this is still a problem after upgrading to a more recent version.
