### ISSUE TITLE
"Disable user-registration" to "Allow/Enable" and uncheck by default

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#455]
The ability for other users to register and use someone else's BTPay Server should be disabled by default and imo the user needs to give an explicit permission for others to register.

Admins in most cases do not want to allow others to use their server. In some jurisdictions it may be even tricky and the user (even though it's stupid) can be considered an illegal payment processor.

So my proposal is to disable the registration for others in policy and change it to "Enable user registration" With a description: Allow other users to register and use your server. 

The admin should give a permission explicitly.

**Comment by kubko32459** [comment]
I agree.

**Comment by sipsorcery** [comment]
Like this?

![serversettings](https://user-images.githubusercontent.com/197660/50058710-6e52bf80-017c-11e9-82e9-de35ebe4f040.png)

**Comment by sipsorcery** [comment]
Subsequent to last post I noticed that the setting seems to already exist. Does the "Disable Registration" setting on the Policies page already satisfy this issue?

![policies](https://user-images.githubusercontent.com/197660/50058962-ad830f80-0180-11e9-9ca6-27c129941157.png)

**Comment by bitcoinshirt** [comment]
@sipsorcery Yes, I was referring to "Disable Registration" in policies. 
I think that one is unchecked by default and that's bad for the reasons I provided in the first post.

Perhaps it's better to ask users if they want to Enable it and leave it unchecked, that's much better logic than with having it enabled out of the box, most of the people don't want other people on their server.

What do you think?

**Comment by sipsorcery** [comment]
@bitcoinshirt personally I'd vote to have it disabled by default. It's an easy setting to miss, I did. I would think someone who want other users to create stores will find and apply the setting but not vice-versa.

I'll submit a PR to disable it by default and let the power(s) that be decide.

**Comment by bitcoinshirt** [comment]
Nice, thanks marking this as "prepare to close".
