### ISSUE TITLE
Unable to login in new install

### ISSUE THREAD

**Issue by 99Percent** [btcpayserver/btcpayserver#457]
I recently installed with docker version btcpay on my bare metal server, then added 2FA and changed the password but for some reason the new or old password is no longer working. I tried to recover the passward via the email password recovery method but the email is not arriving despite sending success message from the front end. Probably I had not yet configured the email settings of the server. I have root access to the server but have no idea on how to manually reset the password from there.

I had also added another user and a store and that user can login successfully.

**Comment by bitcoinshirt** [comment]
You can [try this.](https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#forgot-btcpay-admin-password)

**Comment by 99Percent** [comment]
This worked. I also had trouble configuring the gmail smtp server because I had 2FA enabled so I followed the instructions also at that FAQ. Thanks
