### ISSUE TITLE
[Bug]:  Top-Up Invoices display fiat amounts to 9 decimal places

### ISSUE THREAD

**Issue by xrybxby** [btcpayserver/btcpayserver#4570]
### What is your BTCPay version?

I am running BTCPay Server v1.7.5

### How did you deploy BTCPay Server?

I'm running BTCPay on Lunanode

### What happened?

The output value of {Invoice.Price} in the email body delivers fiat amounts up to 9 decimal places for example one shows a payment of 4.980326560 in USD

### How did you encounter this bug?

I just put the {Invoice.Price} in the body section of the email notifications on BTCPay server

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by petzsch** [comment]
Proposed fix would be in this [line](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/HostedServices/StoreEmailRuleProcessorSender.cs#L93):
`            .Replace("{Invoice.Price}", i.Amount.ToString(CultureInfo.InvariantCulture))`

and add rounding to 2 decimal places. (or are there currencies in the world with more/less then 2 decimal places?)
