### ISSUE TITLE
[Bug]: Unsupported operand types: string * float

### ISSUE THREAD

**Issue by subn3t1** [btcpayserver/btcpayserver#4571]
### What is your BTCPay version?

Latest

### How did you deploy BTCPay Server?

Docker, Self hosted, BTCPay Server v1.7.5

### What happened?

Unsupported operand types: string * float

### How did you encounter this bug?

1. Upgrading the host from PHP 7.4 to PHP 8.1
2. Opening the cart view or after adding a product to the cart

### Relevant log output

```shell
Unsupported operand types: string * float
```

### What browser do you use?

Firefox under Fedora Linux 36

### Additional information

I found that the fix is to add (float) before the strings in line 792 in btcpayvm.php

### Are you sure this is a bug report?

- [ ] I confirm this is a bug report

**Comment by Kukks** [comment]
Btcpay does not use php and the docker deployments isolates btcpay from any
of those host env changes. You need to provide more info on what's going on
as btcpayvm.php is not even part of btcpayserver?

**Comment by subn3t1** [comment]
Sorry for the mistake. Did not intend to post it here. It was for the BTCPay Server Virtuemart plugin team.
