### ISSUE TITLE
[Bug]: OpenCart BTCPAY Server Extension

### ISSUE THREAD

**Issue by polanskys** [btcpayserver/btcpayserver#4576]
### What is your BTCPay version?

hi pros im new with this last version running on ubuntu for opencart

https://paste.pics/4e44d95a86df6ad2447ca0aa6a8a5854

### How did you deploy BTCPay Server?

ubuntu

### What happened?

https://paste.pics/4e44d95a86df6ad2447ca0aa6a8a5854

error on checkout doesnt goes forward and gives this error 

Warning: You have payment methods configured but none of them match any of the requested payment methods or the rate is not available. See logs below:
01/31/2023 04:30:27:Info Creation of invoice starting
01/31/2023 04:30:27:Info BTC_USD: The rating rule is coingecko(BTC_USD)
01/31/2023 04:30:27:Info BTC_USD: The evaluated rating rule is 22826.549
01/31/2023 04:30:27:Info BTC (On-Chain): Payment method details creation took 0 milliseconds
01/31/2023 04:30:27:Error BTC: Payment method unavailable (Full node not available)

### How did you encounter this bug?

trying the checkout of the site

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by ndeet** [comment]
Hi, can you still reproduce the problem? It could be:
- your BTCPay server is not yet fully synched 
- you did not set up Bitcoin wallet in the store
- Coingecko has connectivity issues (try another exchange rate provider)

**Comment by polanskys** [comment]
Thanks already solved only was need to upgrade from shared hosting to a dedicated server with enough bandwitch to be able to fully synch and download the entire blockchain and nodes.

**Comment by ndeet** [comment]
Thanks for reporting back. If you have a "close issue" button please do.
