### ISSUE TITLE
Testnet to Mainet script

### ISSUE THREAD

**Issue by CarlosRoldanx** [btcpayserver/btcpayserver#458]
Hi!

I was wondering if it is possible to switch from trestnet to mainet without having to do the setup.

**Comment by bitcoinshirt** [comment]
It's not possible to simply switch from testnet to mainnet from the front-end. I think testnet is mostly used by developers, and they don't mind doing it manually. 

You'd have to setup [environment variables ](https://github.com/btcpayserver/btcpayserver-docker#environment-variables) you'd like to change and apply `. ./btcpay-setup.sh -i`
In your case that would be something like this, if you're using docker.
```
sudo su -
cd btcpayserver-docker
export NBITCOIN_NETWORK="mainnet"
. ./btcpay-setup.sh -i
```

**Comment by CarlosRoldanx** [comment]
This was a great answer/explanation. Thank you!
