### ISSUE TITLE
[Bug]: FixedFloat Plugin doesn't load after v1.7.5 Update

### ISSUE THREAD

**Issue by ShopinBit** [btcpayserver/btcpayserver#4593]
### What is your BTCPay version?

Running v1.7.5 + Altcoins

### How did you deploy BTCPay Server?

Docker

### What happened?

![grafik](https://user-images.githubusercontent.com/45580007/216595859-9380b80a-3b2f-409c-9814-9a5d7e92b801.png)
FixedFloat doesn't load. Tested with Firefox, Chrome and Chromium.

### How did you encounter this bug?

Opened Pay Request, clicked on FixedFloat.

### What browser do you use?

Firefox, Chrome and Chromium

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Kukks** [comment]
have you updated the fixed float plugin? @NicolasDorier  We need to find a way to stop these breakages with every version..

**Comment by petzsch** [comment]
Can confirm the same issue (empty page) with a freshly installed FixedFloat Plugin on v1.7.5

**Comment by ShopinBit** [comment]
@Kukks Yes Updated and did a restart.

**Comment by Kukks** [comment]
can you check the browser console when on the invoice?

**Comment by petzsch** [comment]
just reinstalled the plugin to get the JS console output and it worked.
Very odd/flaky or @Kukks already fixed it.

**Comment by ShopinBit** [comment]
@Kukks can confirm we reinstalled the plugin and it now works again.
![grafik](https://user-images.githubusercontent.com/45580007/216758675-26e12849-5f21-4661-8d66-a993f554ebc2.png)

**Comment by NicolasDorier** [comment]
@Kukks  sadly, that's the nature of plugins. It is all powerful and flexible, but it can break.
If we wouldn't want to break it, it should be on the main repository, with tests and review, which defeat the purpose of plugins.

There is something we can do about it, like having a template for unit tests on plugins, and the plugin builder could run them to see if something break when a new version happen.
