### ISSUE TITLE
Invalid Derivation Scheme when trying to add Dogecoin wallet xpub from Coinomi

### ISSUE THREAD

**Issue by 99Percent** [btcpayserver/btcpayserver#460]
I have successfully added the derivation schemes for Bitcoin, Litecoin and Dash from the same Coinomi generated wallet. However when I try to add Dogecoin from this same wallet I get "Invalid Derivation Scheme" error and I am unable to continue. I have tried manually adding "-[p2sh]" and "-[legacy]" at the end to no avail.

I can paste here the xpub value if required (I am only in the testing phase so I can regenerate another wallet later).

**Comment by bitcoinshirt** [comment]
@astupidmoose may be able to tell you his setup for Doge.

**Comment by 99Percent** [comment]
Where can I find a tool or the code in btcpayserver that checks the derivation scheme, so I can check it directly?

**Comment by darkban** [comment]
guys but if i not use electrum but my wallet private on coinomi i can convert bitcoin address in xpub?

**Comment by NicolasDorier** [comment]
@99Percent I advise you against using BTCPay with other wallets because of gap limits issues.
I advise you to take a ledger, it is way more sure.

**Comment by bitcoinshirt** [comment]
@99Percent Have you solved the issue? If so can you please close it.
As Nicolas mentioned, it's highly recommended to use Ledger Nano S or Electrum.
