### ISSUE TITLE
[Bug]: Invalid LNURL created for top-up invoices in new checkout

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#4609]
### What is your BTCPay version?

v1.7.6+ed0ccd6f1 

### How did you deploy BTCPay Server?

Docker

### What happened?

Breez and many other wallets can't scan the combined QR code including the LNURL for my top-up invoices.

### How did you encounter this bug?

I scanned a top-up invoice QR code, it failed in Breez, I reported the bug to breez and they tested it with all sorts of wallets with the same outcome.

### Relevant log output

```shell
Parsing the LNURL with https://lightningdecoder.com/ gives:
JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```

### What browser do you use?

Firefox 109

### Additional information

could this be related to the CORS change introduced in this version?
For testing, create a fresh invoice [here](https://otr.4sats.net/?email=markus@petzsch.eu).

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
This seems to be a bug with our LNURL handling. Will investigate tomorrow.
