### ISSUE TITLE
[Bug]: Failed update 1.7.5 -> 1.7.6 using admin web UI

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [btcpayserver/btcpayserver#4610]
### What is your BTCPay version?

BTCPay Server v1.7.6

### How did you deploy BTCPay Server?

Docker

### What happened?

I updated from 1.7.5 to 1.7.6 using the UI updater, and I can no longer get past the login page to see the store page.

### How did you encounter this bug?

1. I updated the server using the UI in the server admin settings.
2. I refreshed the page after a few minutes.
3. I could not longer access any pages through the web UI.
4. I confirmed that in a new browser, I can reach the login page (if not already logged in), but I cannot see anything after I login.

### Relevant log output

```shell
Will have team provide.
```

### What browser do you use?

Firefox and Edge desktop, latest versions.

### Additional information

Our team is investigating this error. Please let us know what troubleshooting steps we should take so that 1) we can fix the issue, and 2) we can provide the necessary information for the bug to be addressed.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by petzsch** [comment]
Is this an Altcoin build? I just have another user who has some monero related log entry in his btcpayserver containerlog.
Logs would be essential to help fix this.

Please provide output from:
`docker logs generated_btcpayserver_1`

**Comment by oskar321** [comment]
I have the same issue!! Exactly same.

**Comment by oskar321** [comment]
Here is my log file 
[logfile.txt](https://github.com/btcpayserver/btcpayserver/files/10688485/logfile.txt)

**Comment by SamsungGalaxyPlayer** [comment]
@petzsch I asked our team member for the log output. Yes, this is an altcoin built with Bitcoin and Monero enabled.

**Comment by oskar321** [comment]
:D same here.

**Comment by tannerdsilva** [comment]
@petzsch logs related to the host that @SamsungGalaxyPlayer is referring to.

[btcpay-log.txt](https://github.com/btcpayserver/btcpayserver/files/10688543/btcpay-log.txt)

version 1.7.6-altcoin

**Comment by oskar321** [comment]
I see a small difference... I updated via ssh but same result. So it is not the way we updated which caused this issue. 
I can login only if I delete previous cookies and after login I see a blank page. 
I also could reset my password via "Forgot Password". I received my mail and could also store a new password which was functional after changing. 
I only don't have any dashboard. Anything else seems to work.

**Comment by SamsungGalaxyPlayer** [comment]
Our integration with the API appears to be down, since users of [the service this supports](https://buy.cakepay.com) can't make BTCPay invoices currently. It doesn't appear to solely be a missing dashboard page on our side.

**Comment by oskar321** [comment]
Forgot to mention, that my transmuter page is also working without any issue and a payment link which was created previously is showing all content but the "Pay Invoice" button is not forwarding anywhere and without any error message. There is a small circle flashing some times on the button but nothing happens.

**Comment by oskar321** [comment]
As my payment links are not working I think it is still same behaviour. Invoices are not created here also :(

**Comment by oskar321** [comment]
After login (2FA is also working) I see a error message when I get the HTTP ERROR 500 message:
crbug/1173575, non-JS module files deprecated.
(anonymous) | @ (index):6750

**Comment by NicolasDorier** [comment]
checking

**Comment by NicolasDorier** [comment]
https://github.com/btcpayserver/btcpayserver/releases/tag/v1.7.7

Please follow the procedure to update there.
