### ISSUE TITLE
[Bug]: Replace BTC wallet popup is broken

### ISSUE THREAD

**Issue by jaonoctus** [btcpayserver/btcpayserver#4611]
### What is your BTCPay version?

 v1.7.5+372df93c1

### How did you deploy BTCPay Server?

Docker

### What happened?

HTML is being displayed as text

![image](https://user-images.githubusercontent.com/7918067/217601835-86e616a1-0730-4e08-ab09-8de0a9fa406f.png)

### How did you encounter this bug?

1. Go to the onchain wallet settings (`/stores/<STORE_ID>/onchain/BTC/settings`)
2. Click on the `Actions` dropdown menu
3. Click on `Replace wallet`

### What browser do you use?

Chrome 110.0.5481.77

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
This has been fixed with v1.7.6 ­— thanks for reporting though!
