### ISSUE TITLE
Greenfield API:

### ISSUE THREAD

**Issue by esteban2006** [btcpayserver/btcpayserver#4613]
### What is your BTCPay version?

v1.7.5+372df93c1

### How did you deploy BTCPay Server?

sudo su -

mkfs.ext4 /dev/vdc
mkdir /mnt/dockervolume
mount /dev/vdc /mnt/dockervolume
echo "/dev/vdc        /mnt/dockervolume        ext4   defaults        0 0" >> /etc/fstab

ln -s /mnt/dockervolume /var/lib/docker

apt-get update && apt-get install -y git

git clone https://github.com/btcpayserver/btcpayserver-docker
cd btcpayserver-docker

export NBITCOIN_NETWORK="mainnet"
export BTCPAYGEN_CRYPTO1="btc"
export BTCPAYGEN_LIGHTNING="lnd"

export ACME_CA_URI="https://acme-v01.api.letsencrypt.org/directory"
ssh-keygen -t rsa -f /root/.ssh/id_rsa_btcpay -q -P ""
echo "# Key used by BTCPay Server" >> /root/.ssh/authorized_keys
cat /root/.ssh/id_rsa_btcpay.pub >> /root/.ssh/authorized_keys

BTCPAY_ENABLE_SSH=true
export BTCPAY_HOST="xxxxxxxxxxxxxo.com"
export LETSENCRYPT_EMAIL="xxxxxxxxxx@gmail.com"
export BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-save-storage-s"
. ./btcpay-setup.sh -i

### What happened?

I would like to request: that in the reponse of:

AMAZING_BTCPAY/api/v1/stores/{storeID}/invoices [POST]

you could include the fields:

"invoiceBitcoinUrl": "btc address that has been reserved by the system to the newly created invoice"

### How did you encounter this bug?

N/A

### Relevant log output

```shell
N/A
```

### What browser do you use?

N/A

### Additional information

N/A

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by petzsch** [comment]
Check the destination or paymentLink in this API Requests respsonse:
https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Invoices_GetInvoicePaymentMethods

Should solve your problem. 😄 

Please close this issue on your end, when this solves it.
