### ISSUE TITLE
[Bug]: CORS-related - snort.social still doesn't play with our lnaddress implementation

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#4615]
### What is your BTCPay version?

 v1.7.6+ed0ccd6f1

### How did you deploy BTCPay Server?

Docker

### What happened?

![grafik](https://user-images.githubusercontent.com/1374810/217799345-67297eba-a4e6-4d73-a25c-34e6b95ee65b.png)

### How did you encounter this bug?

1. Add lnaddress to my nostr account
2. click on address in profile, 500 sats and Zap
3. "Failed to load invoice" appears + JS console output from above

### Relevant log output

```shell
none
```

### What browser do you use?

Firefox 109

### Additional information

my public nostr profile on snort if you wanna try:
https://snort.social/p/npub1l2q2pyyjlt5qsgwnmk3ga0dme2aafj35j25fk878p58uzanyfcsqqzlgc2

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by mjlamb** [comment]
Snort Zaps are working for my btcpay lightning address, now. Thanks Team
