### ISSUE TITLE
[Bug]: Pull-Payments LNURL-W BECH32 links include html in the description

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#4624]
### What is your BTCPay version?

v1.7.9+57f5c1567 

### How did you deploy BTCPay Server?

Docker

### What happened?

created a pull payment denominated in btc, clicked on view, on the qr code, on bech32 and scanned it with Breez
result is this:
![grafik](https://user-images.githubusercontent.com/1374810/218252751-c820adc6-bb40-4baa-8deb-80b31be52ea5.png)

The html code that the WYSIWYG editor inserts, shouldn't end up in the bech32 code imho.

### How did you encounter this bug?

see above

### Relevant log output

```shell
none
```

### What browser do you use?

Firefox 109

### Additional information

none

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Kukks** [comment]
Should it be the description or the name of the pull payment

**Comment by petzsch** [comment]
either use the name of the pull payment which should be plain/text
or
strip html tags from the description field, though we could still run in length limitations there.

personal opinion: just use the pull payment name for the bech32 description.

**Comment by NicolasDorier** [comment]
fixed in 1.7.11
