### ISSUE TITLE
[Bug]: Unable to Edit amount when cloning paid Payment Request

### ISSUE THREAD

**Issue by jacobburrell** [btcpayserver/btcpayserver#4639]
### What is your BTCPay version?

© BTCPay Server v1.7.3.0+09d5f5a08

### How did you deploy BTCPay Server?

Docker, Luna node

### What happened?

I cannot edit the amount of the cloned payment request as the state that determines the payment request being paid or not is also carried over, despite the fact that this should be a **brand new payment request** without the value of it being paid or not cloned over.

By default, every new/cloned payment request should be unpaid and thus be able to have it's value set.

Amount and currency are not editable once the payment request has invoices

### How did you encounter this bug?

I cloned an already settled invoice with a single payment more than the amount due.

### Additional information

This is a regression that seems to have arisen from the fix implemented in [the other bug fix](https://github.com/btcpayserver/btcpayserver/issues/4241) I posted that was fixed.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by jacobburrell** [comment]
I noticed that this bug happens on the immediate screen after attempting to create the payment request.

If you try to make the payment request with the cloned amount:

1. The page reloads
2. The form validation error message shows under the amount `Please provide an amount greater than 0` and the amount field becomes editable.

Still, there's something odd making it only possible **after** the initial attempt.

**Comment by NicolasDorier** [comment]
Checking this
