### ISSUE TITLE
Webhook: cannot assign requested address

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#4648]
please help my webhook (callback) not work
please write me in telegram https://t.me/tervin

_Originally posted by @tefikoff in https://github.com/btcpayserver/btcpayserver/issues/4643#issuecomment-1430532600_
            
After talking to the author of this post in telegram, I gathered the following info:

Version: 1.7.11

I was able to talk to his webhook URL from my btcpayserver, however when he tries from his, he gets this error:
![screen_uz_redacted](https://user-images.githubusercontent.com/1374810/219011179-5a7fd734-0c19-442a-bfc0-9f8df08a64a8.jpg)

(no matter if http:// or https://)

**Comment by petzsch** [comment]
@NicolasDorier  I think I narrowed down the issue:

the webhook url hostname is running dualstack (IPv4 and IPv6 aka AAAA and A DNS records), however the btcpayserver seems to be IPv4 only, hence cant bind a tcp6 socket, hence this error.

We are doing something wrong when creating the connection, it should fall back to ipv4 in these situations.

I couldn't repro the error on my instance as it's IPv4+IPv6.

**Comment by NicolasDorier** [comment]
@petzsch would you have a domain I can try this?

**Comment by NicolasDorier** [comment]
I checked on lunanode: 
![image](https://user-images.githubusercontent.com/3020646/222633238-0d957afe-44de-4a62-a06c-e8ac46b48e9b.png)

**Comment by NicolasDorier** [comment]
tested locally, it also work... not sure

**Comment by petzsch** [comment]
It was a "working hypotehesis". Perhaps something else in that users network failed (dns resolver, perhaps ipv6 only target).
Since the user found a workaround for himself (hosting the webhook endpoint somewhere else), this issue **can** probably **be closed**.
