### ISSUE TITLE
Feature Request: Make NIP-05 Plugin Multi Domain capable

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#4649]
I'd like to create multiple username "_" accounts for different domains on my btcpayserver. The domains are added as additional domains via docker.

Maybe this can be done somehow.

cc:
@Kukks

**Comment by Kukks** [comment]
AFAIK every  domain mapped to btcpay will accept the configured names on NIP5

**Comment by petzsch** [comment]
they do, but I want different pubkeys coming up, depending on the domain.

**Comment by pavlenex** [comment]
Shouldn't this be posted in the repository of the plugin itself?

**Comment by pavlenex** [comment]
Closing, since it's plugin-related. Not core.
