### ISSUE TITLE
[Shopify]: check if our integration is affected by shopify changes as of 1st April 2023

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#4650]
### What is your BTCPay version?

v1.7.11.0

### How did you deploy BTCPay Server?

docker

### What happened?

Report by user using the Shopify integration. He got an email from shopify warning about changes in the REST API effective with 1st of April 2023.

One of our shopify integration users reported that the following fields will be removed, see original post [here](https://snort.social/e/note1sladws7peqjpucuda6t6de73glz6n3pzvu6wmupvg6de6uyhgxyqt8qglr)

> Warning that april 1st certain API requests will be rejected:

> The "total_price_usd" field in the "Order" section has been rejected by the ordering resource of the Admin REST API.

> The "origin_location" and "destination_location" fields on items have been rejected by the ordering resource of the Admin REST API.

> As part of inventory management at multiple locations, a change was introduced that caused a break for the Order.line_items.fulfillment_service field. This field should be removed from both the GraphQL and REST API for the admin area. When using the GraphQL API, consider using FulfillmentOrder.assigned_location. If using the REST API, see FulfillmentOrder.assigned_location for more information.

### How did you encounter this bug?

Use shopify integration.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Probably a duplicate of #4510 but will leave this one opened as it has more context, this is certainly something we should prioritize.

**Comment by ndeet** [comment]
Oh my bad, did not search. I think we can close this one then, I added the link to the changelog on the original issue.
