### ISSUE TITLE
Payjoin payment link generated even when hot wallet has no UTXOs

### ISSUE THREAD

**Issue by yashrajd** [btcpayserver/btcpayserver#4651]
Since receiver cannot contribute UTXOs for payjoining if the hot wallet is empty, this behaviour results in an error on the sender wallet.

BTCPay version: 1.7.11

Steps to reproduce:
- connect/create hot wallet
- ensure it is empty
- ensure payjoin is enabled
- generate a QR/payment link

You will observe that a BIP-21 URI with pj endpoint link is generated, but if you try to pay to it, the payment fails (screenshots) attached.

<img width="930" alt="Screenshot 2023-02-15 at 11 27 30" src="https://user-images.githubusercontent.com/114083781/219147292-a2b15174-2156-4c43-9154-086eeeb266b2.png">

<img width="360" alt="Screenshot 2023-02-12 at 23 55 44" src="https://user-images.githubusercontent.com/114083781/219147409-701c2e97-4234-4bce-8aac-65901e89b934.png">

![IMG_5420](https://user-images.githubusercontent.com/114083781/219147465-8c95986a-bb54-4028-b59e-4a0c1a47ab54.PNG)

Suggested fix: do not generate a payjoin payment link/QR if the connected hot wallet is empty

Hope this info is useful...

**Comment by NicolasDorier** [comment]
Fixing this.

**Comment by NicolasDorier** [comment]
Note that this error should be notified to the wallet provider as well.

**Comment by NicolasDorier** [comment]
Which wallet is this? it shouldn't be an error, this is a bug of the wallet.

**Comment by NicolasDorier** [comment]
I see you are tracking here https://github.com/BlueWallet/BlueWallet/issues/5313

**Comment by NicolasDorier** [comment]
Closing this @yashrajd thinking about it, I believe it's a bug from BlueWallet that should be fixed: A failed payjoin should never prevent sending money.

**Comment by yashrajd** [comment]
> A failed payjoin should never prevent sending money.

A privacy-dependent user may want to **not** send money if it's not heuristic breaking.
