### ISSUE TITLE
[Bug]: "BTC: Payment method unavailable (Impossible to create lightning invoice (Object reference not set to an instance of an object.))"

### ISSUE THREAD

**Issue by raucao** [btcpayserver/btcpayserver#4658]
### What is your BTCPay version?

1.7.12

### How did you deploy BTCPay Server?

Manual

### What happened?

Switched Lightning back-end to LNDHub, cannot create Lightning invoices anymore. Invoice logs contain this error:

```plain
BTC: Payment method unavailable (Impossible to create lightning invoice (Object reference not set to an instance of an object.))
```

No exception in the server logs.

### How did you encounter this bug?

Switched the Lightning back-end from local LND to an LNDHub account.

### Relevant log output

```shell
BTC: Payment method unavailable (Impossible to create lightning invoice (Object reference not set to an instance of an object.))
```

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Just checked and it works for me. 

* Does the Public Node Info page (see the Lightning settings) report the node/connection to be online? 
* What LNDhub backend are you using? It's a known problem that this doesn't work e.g. with the LNbits LNDhub wrapper.

**Comment by raucao** [comment]
> Does the Public Node Info page (see the Lightning settings) report the node/connection to be online?

Yes. The test connection works (when adding the config), and the public node info page reports it as online.

> What LNDhub backend are you using? It's a known problem that this doesn't work e.g. with the LNbits LNDhub wrapper.

[LndHub.go](https://github.com/getAlby/lndhub.go)
