### ISSUE TITLE
[Bug]: POS fails with NFC & LNURLw payment

### ISSUE THREAD

**Issue by PeterRounce** [btcpayserver/btcpayserver#4663]
### What is your BTCPay version?

BTCPay Server v1.7.12+9344113ae

### How did you deploy BTCPay Server?

lunanode

### What happened?

error message shown when payment is attempted
```
Could not fetch bolt11 invoice to pay to:
Amount is out of bounds.
```

### How did you encounter this bug?

Using the POS app on an Android phone as a PWA

- Set up a charge for 10 sats
- Clicked `pay by NFC & LNURLW`
- Tapped a card to make payment

message was displayed and payment was not made

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by PeterRounce** [comment]
The card was verified to work using the Breez POS.

**Comment by PeterRounce** [comment]
@Kukks is this one you can help with please?

**Comment by dennisreimann** [comment]
I can reproduce and will fix it.
