### ISSUE TITLE
[Bug]: Cannot obtain user data on checkout

### ISSUE THREAD

**Issue by lopezdp** [btcpayserver/btcpayserver#4666]
### What is your BTCPay version?

BTCPay Server v1.7.12+9344113ae

### How did you deploy BTCPay Server?

AWS EC2

### What happened?

I want to collect an email or shipping address in the point of sale

<img width="556" alt="Screenshot 2023-02-19 at 5 39 15 PM" src="https://user-images.githubusercontent.com/5707191/219979508-37e2e36b-e187-4aa6-81fc-77d7f377f8d5.png">

this is the error encountered on front end when data collection is set in point of sale

<img width="688" alt="Screenshot 2023-02-19 at 5 41 14 PM" src="https://user-images.githubusercontent.com/5707191/219979651-45dad96d-8ee5-4665-880f-d4fe2bba66eb.png">

### How did you encounter this bug?

configure either collect email or shipping address options and get error on ui

### Relevant log output

```shell
2023-02-19 04:21:55.187 +00:00 [WRN] Error while contacting exchange coingecko: The operation was canceled.
2023-02-19 17:10:04.131 +00:00 [INF] BTC (Lightning): Start listening unix://etc/clightning_bitcoin/lightning-rpc
2023-02-19 17:40:48.303 +00:00 [INF] BTC (Lightning): No more invoice to listen on unix://etc/clightning_bitcoin/lightning-rpc, releasing the connection.
```

### What browser do you use?

chrome and safari

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
I cannot reproduce this. Does the problem persist and are there more logs from the BTCPay Server container? The error above points to the exchange rate not being fetched.

**Comment by lopezdp** [comment]
> I cannot reproduce this. Does the problem persist and are there more logs from the BTCPay Server container? The error above points to the exchange rate not being fetched.

@dennisreimann I just tested it and when I use the market place link directly it works, however when I use it in an iframe embedded in a website it crashes

this is the error I get:

```
Invalid 'X-Frame-Options' header encountered when loading 'https://btcpay.domain.com/': 'allow-all' is not a recognized directive. The header will be ignored.
```

im thinking its something along these lines:

https://stackoverflow.com/questions/73284217/x-frame-option-error-not-a-recognized-directive-the-header-will-be-ignored

im leaving the error on the page I have the implementation at: you can test it and see the error for yourself here: https://davidplopez.com

**Comment by NicolasDorier** [comment]
@de

**Comment by lopezdp** [comment]
@dennisreimann wondering if your solution causes any CORS issues down stream? not sure atm...

what release will this be a part of v1.8 maybe?
