### ISSUE TITLE
[Bug]: Greenfield API: Create API Key allow to set/limit store scope

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#4673]
### What is your BTCPay version?

v1.7.12

### How did you deploy BTCPay Server?

docker

### What happened?

On the [create API key endpoint](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/ApiKeys_CreateApiKey) you can set the permissons but not limit the API key to one or more stores like you can do in the UI. 

### How did you encounter this bug?

Creating an API key with the Greenfield API

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
This is already possible. `btcpay.store.canmodifystoresettings:abciuewi` where `abciuewi` is the storeid.
