### ISSUE TITLE
[Bug]: Greenfield API: allow to create API key for different user

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#4675]
### What is your BTCPay version?

v1.7.12

### How did you deploy BTCPay Server?

docker

### What happened?

When you set the API key with basic auth then you [generate that API key](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/ApiKeys_CreateApiKey) for the user. If you do that with an unrestricted API key then it would be great to create the keys for a specific user. E.g. your webapp has an unrestricted API key and creates users and separate API keys for them. At the moment the unrestricted API key will always create the new API key for that same user (admin) and therefore does not allow 3rd parties to generate users and api keys automatically. (only if they use basic out for each specific user which means they would need to know the password)

### How did you encounter this bug?

Tried to automate user creation and give them an API key they can use to control their BTCPay Server account. 

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
on it
