### ISSUE TITLE
[Bug]: HTML injection in forms for payment requests

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#4678]
### What is your BTCPay version?

1.7.11

### How did you deploy BTCPay Server?

docker

### What happened?

HTML injection

### How did you encounter this bug?

Credit to @thewhiteevil

* Go to the website
* Click payment request.
* Request new payment.
* Remember to enable the >>> Request customer data on checkout >>> Request shipping address.
* Create the payment request.
* Now click view, we/user need to enter the address and other stuff.
* Use the following HTML payload
* Back in the edit view of payment request:

![image](https://user-images.githubusercontent.com/3020646/220509185-f5e874b3-d5aa-4068-8224-e3e242020f87.png)

https://drive.google.com/file/d/1Pn33vZ4TeFovvkK50eVBUGAkeVSfCQf-/view?usp=sharing
https://huntr.dev/bounties/2e734209-d7b0-4f57-a8be-c65c82208f2f/

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
This was caused by https://github.com/btcpayserver/btcpayserver/pull/3612 @Kukks why do you use `Html.Raw` everywhere like this?

Please never do it, or if you do, do it in a separate PR with proper description instead of hiding it in a thousand line of code PR.

**Comment by Thewhiteevil** [comment]
Hello Team,

I hope this message finds you well. 

I am reaching out to request your assistance in collecting Google business page reviews for Hacker Bro Technologies. As part of my efforts, I am requesting reviews from my clients, interns, and bug bounty targets. I would greatly appreciate it if you could contribute by leaving a 5-star rating and a positive review for our company. Your support would mean a lot and would be a token of appreciation for my contributions. Thank you for your time and consideration. 

Links for both Hacker Bro Technologies/Codify360 Technologies pages.

https://g.page/r/CQUPIFfZT7B_EAI/review

https://www.justdial.com/jdmart/coimbatore/Hacker-Bro-Technologies/0422PX422-X422-221206185058-L8V6_BZDET/catalogue?rStatus=1

https://g.page/r/CQ2_WaQLh-wZEBM/review

At Codify360, we specialize in designing and developing custom web and mobile applications. Additionally, we offer a platform for users to upload and sell their scripts. I would like to extend a personal invitation to you to consider uploading your scripts to our platform for potential sales. Thank you for considering Codify360 for your web and app development needs. We look forward to the opportunity to serve you.

Best regards, 

Manojkumar J (TheWhiteEvil), Founder/CEO of Hacker Bro Technologies/Codify360 Technologies.
