### ISSUE TITLE
Request features: 

### ISSUE THREAD

**Issue by darkban** [btcpayserver/btcpayserver#469]
to respond to the volatility of the crypts, how about implementing a system that allows you to connect the exchange through api?

example:
on Exchange kraken bistamp or Coinbase I own 1 btc, a customer makes a payment of 0.23btc and automatically on Exchange sells the sum of 0.23 btc I received ... in this way there will be no more problem with the volatility of the crypto.

**Comment by bitcoinshirt** [comment]
Duplicate #112
