### ISSUE TITLE
`Custom Form Builder` Metadata in custom forms isn't displayed in the `invoice`

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#4691]
My impression was that data collected through custom forms should be displayed in the invoice somehow.
Currently, this only happens with `email` and `buyer's address`. But for any other custom field, end-user has no way to access the data customer added, so practically custom forms are useless for the merchants as they have no easy way to access the information.

To replicate:
1. Store Settings > `Forms`
2. `Create form`
3. Add following 
```
{
  "topMessages": [],
  "fields": [
    {
      "name": "tableNumber",
      "constant": false,
      "type": "number",
      "value": null,
      "required": true,
      "label": "Let us know which table you would like",
      "originalValue": null,
      "helpText": null,
      "validationErrors": [],
      "fields": []
    },
    {
      "name": "allergies",
      "constant": false,
      "type": "text",
      "value": null,
      "required": false,
      "label": "Any allergies?",
      "originalValue": null,
      "helpText": null,
      "validationErrors": [],
      "fields": []
    }
  ]
}
```
4. Add form either as stand alone or as a part of the POS
5. Fill in the form pay the invoice
6. Go to invoices, no data is shown

**Comment by Kukks** [comment]
There is more to it than this. The forms maps  to the invoice `Metadata`.
Some of those properties are shown  on the invoice details page such as
buyer data and pos data) , some are shown on the receipt page.

This is especially useful for api integrations and just in general having a
storage for this data.

One way to have fields show in the invoice details page is to create a
field of type fieldset and name posData and fill its fields properties with
the data you want to show in the invoice details page

**Comment by pavlenex** [comment]
@Kukks I get that, and it's great that we're allowing this sort of ability through the API, however one of the biggest reasons why we wanted forms is because end-users (merchants) wanted a way to collect information from their customers. If we don't expose this in the UI for them to be able to see any field in the invoice (because invoice is their single sort of truth when fulfilling an order), then arguably, we can just not expose the custom forms in the UI, since they'll be useful only for those who use API. 

Could you give an example please on what gets displayed on a receipt? Bear in mind a receipt is an end-user (customer) document, and any info there should be relevant only for the customer. Merchants have invoices int he backoffice to process things.

> One way to have fields show in the invoice details page is to create a
field of type fieldset and name posData and fill its fields properties with
the data you want to show in the invoice details page

So there is a way to expose these fields, but it would have to be done through POSData. Why is this? Do you think it would be useful to expand this to all fields? Is it technically possible?

**Comment by Kukks** [comment]
Discussed via DM but this image should be explanatory of what happens if we expose the root metadata object in UI
![image](https://user-images.githubusercontent.com/1818366/220861533-223ce203-91d3-4354-ba91-41561b6e806a.png)
