### ISSUE TITLE
Replace `Copy` text with an icon across all views

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#4699]
UPDATE: We're widening the scope of the issue, and instead of just the checkout page, we should add copy icons across all views and unify this.

Having a text means we have to translate it. In certain languages the text may get lengthy and the experience may seem odd. A simple copy icon is something everyone understands these days, so I suggest we use copy icon instead of the copy text.

![Screenshot 2023-02-24 at 10 19 10](https://user-images.githubusercontent.com/36959754/221140763-266b5a27-8e46-4a35-94be-c941e50dc745.png)

**Comment by dennisreimann** [comment]
Agreed, let's widen the scope of this issue a bit and use it as a chance to unify those buttons across the app. We have several places in which we are using the text.

**Comment by pavlenex** [comment]
@dennisreimann Okay, updated the issue, I assume it would be relatively easy to detect which areas require text replacement with an icon? I think we already have icon for this (copy icon appears on paid checkout).

**Comment by TChukwuleta** [comment]
Hi @pavlenex  @dennisreimann, I would really like to join you in solving this issue. Can you please let me know how I can assist?

**Comment by dennisreimann** [comment]
@TChukwuleta I'm already working on this, but maybe there's another issue you can tackle? What about e.g. #4304?

**Comment by TChukwuleta** [comment]
Thank you, @dennisreimann . I would look at it.

**Comment by dstrukt** [comment]
Icons sent to @dennisreimann via MM, but @TChukwuleta if you're going to implement, feel free to message me on Mattemost as well, or hopefully you can snag them here.

<img width="540" alt="Screen Shot 2023-03-10 at 3 17 33 PM" src="https://user-images.githubusercontent.com/6250771/224447410-4db5ef63-9087-41f3-b1e0-0abee039dcec.png">

![copy-success](https://user-images.githubusercontent.com/6250771/224447386-6a96778a-ba94-4857-b31d-627ab93e4b37.svg)
![copy](https://user-images.githubusercontent.com/6250771/224447389-3976adcb-e48c-47c8-a624-5cf66cacde84.svg)
