### ISSUE TITLE
Automating bundling of JS/CSS files

### ISSUE THREAD

**Issue by lepipele** [btcpayserver/btcpayserver#47]
We are currently not making distinction between different environments - development, staging, production. As described in #39 resources are linked statically... we link JS/CSS directly and that stays same between environments.

Ideally we want system where in development we would link full JS/CSS files which would help during development and debugging... but once project is deployed to production there should be automatic process of minimization and bundling of all referenced files so we ideally serve just one JS and one CSS file.

This way we will also resolve issue of versioning - if certain JS/CSS file is updated, server should automatically create new bundle with new version string (i.e. `http://btcpay-server-url.com/renderjs?version_guid`). That way you also prevent confusion with client browsers who'll always have latest versions of JS/CSS files (without requiring clients to CTRL+Refresh your page). See this url for example: https://stackoverflow.com/questions/16395595/mvc4-bundling-version-control

**Comment by Eskyee** [comment]
yes I sure this is our best solution lepipele .. nice !

**Comment by Eskyee** [comment]
https://docs.microsoft.com/en-us/aspnet/mvc/overview/performance/bundling-and-minification

**Comment by NicolasDorier** [comment]
this link is not about asp.net core.

**Comment by lepipele** [comment]
@NicolasDorier no worries - concept is pretty much the same and I've done it previously. Will be done with this by tomorrow evening and will update both you and @Eskyee

**Comment by Eskyee** [comment]
I’m on my machine tonight!! Looking forward to see the Solution lepipele ;)

**Comment by lepipele** [comment]
@Eskyee here is the first pass - comparison of HTTP requests and loading size when there is no bundling:

![non-bundled](https://user-images.githubusercontent.com/5191402/35494475-81af40c0-0480-11e8-97b6-724bdf6aa61f.png)

And then where bundling is activated:

![bundled](https://user-images.githubusercontent.com/5191402/35494481-88304f7a-0480-11e8-8972-01983023fd0f.png)

I want to make this automatic between different environments so I'll not create pull request yet, but rather when I am fully done with this. In the meantime feel free to take a break when it comes to that pull request you are submitting - I'll resolve that problem. There are some other errors with jquery.validation and I'll handle all that in this single issue.

Will keep both you and Nicolas updated.

**Comment by Eskyee** [comment]
:)

**Comment by lepipele** [comment]
For that Jquery Unobtrusive Validation... here is how it looked before:

![01-before-unobtrusive](https://user-images.githubusercontent.com/5191402/35590714-4b5c521c-05cd-11e8-853b-5dd603aa9c8a.gif)

And here is how it looks now:

![02-after-unobtrusive](https://user-images.githubusercontent.com/5191402/35590726-537c2e86-05cd-11e8-9f58-e36cdffc05ae.gif)

**Comment by NicolasDorier** [comment]
should we close this now?

**Comment by lepipele** [comment]
Implemented: https://github.com/btcpayserver/btcpayserver/pull/48
