### ISSUE TITLE
Enable "Pay by LNURL-withdrawal" (NFC) by default in browser

### ISSUE THREAD

**Issue by gorrdy** [btcpayserver/btcpayserver#4702]
Would it be possible to implement a solution, where the Point of sale is expecting the NFC "Pay by LNURL-withdrawal" by default?

This would improve the practical usage when a restaurant or store uses a simple device with Keypad only POS and generates an invoice for a customer that wants to pay with NFC.

Now, the cashier needs to manually click the "Pay by LNURL-withdrawal" button, which can be confusing for some users not familiar with the BTCPayServer UI.

I'm aware this is not a priority, but I have a personal experience getting this request from several of my customers that are actually using BTCPayServer in their business that the "one other click" on the button to activate the NFC reader is a pain in the neck.

Thanks guys for your fantastic work.

**Comment by Kukks** [comment]
This is not possible due to the browser nfc capabilities, which requires an
interaction with an element before it can be used.

**Comment by Rudylop** [comment]
Igi

**Comment by gorrdy** [comment]
Good to know it was possible and this really helps a lot in 1.9.0. Thanks guys.
