### ISSUE TITLE
As @dennisreimann pointed out on Mattermost: This is hard to fix because of legacy CSS code.

### ISSUE THREAD

**Issue by Amenonx7** [btcpayserver/btcpayserver#4704]
As @dennisreimann pointed out on Mattermost: This is hard to fix because of legacy CSS code.
Closing this issue.

_Originally posted by @petzsch in https://github.com/btcpayserver/btcpayserver/issues/4701#issuecomment-1444334029_

**Comment by Webbdlee74** [comment]
Should I cancel it all together.
