### ISSUE TITLE
From redirect url to http request

### ISSUE THREAD

**Issue by CarlosRoldanx** [btcpayserver/btcpayserver#471]
Hi @NicolasDorier 

When a payment is successful the option to redirect the user to an url is available. But, what about doing an http request, so It can trigger a more complex event from a backend?

**Comment by Kukks** [comment]
Please read the related bitpay docs at
https://bitpay.com/docs/invoice-callbacks

**Comment by CarlosRoldanx** [comment]
The documentation from bitpay has been very helpful
