### ISSUE TITLE
`Retail checkout mode`

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#4712]
Suggested by @NicolasDorier, we should have a way for retailers using btcpay for in-person payments can abstract all the unnecessary options such as `address copy`, `open in a wallet`,

**Comment by ndeet** [comment]
Not sure if the right place here but ideally the NFC button should be more on top in the main screen without scrolling.

**Comment by NicolasDorier** [comment]
There are three part in this:

1. There should have individual checkboxes in the checkout experience for hiding/showing some parts of the checkout.
2. There should be a way for the merchant to automatically optimize the settings for a use case in the store creation
3. Same thing but in the store settings

Something like that



![Image](https://user-images.githubusercontent.com/3020646/223940806-88a52831-5085-4231-963b-f3155facf3cf.png)

@dstrukt

**Comment by pavlenex** [comment]
@NicolasDorier Can we scope this to what we agreed on on dev meeting? Adding a wizard vs having a simple checkbox in checkout experience doen't seem like proper optimizaiton, especially since we cannot assume how people use btcpay, what if they're not online nor physical, we don't have onboarding path for them. I really think we should keep this simple for now and add the wizard at a later stage, when more optimization can be added not just "hide checkout stuff"

**Comment by NicolasDorier** [comment]
There are simple checkboxes already.
It's just people will not even look at them.

Move conversation here:
https://github.com/btcpayserver/btcpayserver/pull/4756

> what if they're not online nor physica

What matter is where the checkout page is shown: on the merchant device, or on the customer device. It can't be different.
