### ISSUE TITLE
Improvement to receipts, display items, tips and discounts on receipt.

### ISSUE THREAD

**Issue by Bangalisch** [btcpayserver/btcpayserver#4715]
Yo yo. 

As mentioned in the last Design call, i would make an issue for this. 
i ran into not seeing my bought products, added discounts or tips in the costumers receipt.

I think we should add these products to the receipt view if bought from PoS app / Crowdfund. 
This also applies to Tips and Discounts that are added to the receipt if it comes from a Keypad only store.

**Comment by Kukks** [comment]
@dennisreimann  This should be easy enough if we duplicate the data from posData to receiptData as well

**Comment by pavlenex** [comment]
Duplicate of #4716
