### ISSUE TITLE
Optimize invoice print view

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#4729]
Invoice is critical peace of information for merchant to deliver and fulfil the order. Some merchants that don't use CMS, may find it useful to have an easy way to print out the invoice and attach it to the order, or use it externally (for example storage unit worker receives and invoice to pack up the order).

Currently, you can print `invoice` just like any other web-page, but it's unoptimized, lengthy and requires a lot of paper waste which can end up being costly. 

I would like to propose that we add `print` button on the invoice, and optimize the print view to contain only order-critical data such as:

-  General Information
- Invoice Summary
- Additional information

We should not include `events/invoice log` as this information isn't typical for an invoice.

**Comment by dennisreimann** [comment]
Let's do one more round here once #4782 is merged, because we can use the concept of payment proof for the invoice details as well and also reuse the truncate center component, to make things look nicer.

Also @petzsch made a r[emark to use plain black/white](https://chat.btcpayserver.org/btcpayserver/pl/wtx7znqpxt83urxujrbbq1kfxc) on the print view. Will update that as well.

**Comment by petzsch** [comment]
As later on commented on that message: I think it was a printer driver issue. The preview in Chrome also showed color for the logo, when it should have been black+white. Also the print preview in Firefox on desktop shows clear black+white - so not sure if this is a a btcpay issue.

Maybe someone with a sumi POS device can verify if there is a printing issue?

**Comment by NicolasDorier** [comment]
Can this one be closed since #4782 is merged?

**Comment by dennisreimann** [comment]
@NicolasDorier No, see my comment above, I'll do one more PR because we can now improve the view some more.
