### ISSUE TITLE
Expose LND Invoice Macaroon and Readonly Macaroon in UI

### ISSUE THREAD

**Issue by hubiktomas** [btcpayserver/btcpayserver#474]
It would be good to expose also the readonly and invoice LND macaroon in the Server Settings > Services > lnd-grpc/lnd-rest > More Details in the same way as we have the admin macaroon now. Some external tools/apps may use them - for example some LND POS would need just invoice macaroon or some monitoring tool would need just readonly macaroon and giving it admin macaroon might be just a security risk/undesirable.

**Comment by NicolasDorier** [comment]
It is already exposed, if you don't see it, update and run https://docs.btcpayserver.org/faq-and-common-issues/faq-lightningnetwork#lnd-connection-issues-after-an-update

**Comment by hubiktomas** [comment]
Really? I am not talking about the API exposure, but about literally showing the macaroon in the user interface. I can see just the admin macaroon there.

**Comment by NicolasDorier** [comment]
Yes I mean in the UI, please do https://docs.btcpayserver.org/faq-and-common-issues/faq-lightningnetwork#lnd-connection-issues-after-an-update

**Comment by hubiktomas** [comment]
Cool, it works. Thank you!
