### ISSUE TITLE
Custom Role system

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#4741]
On a dev call, it was discussed that we may want to add a custom role system, similar to our API permission system, where store owner would be able to create custom role and just hand-pick the permissions.

Builds from the idea in https://github.com/btcpayserver/btcpayserver/issues/442

**Comment by dennisreimann** [comment]
This is started with #4595. ONce that is done and merged, we should come up with a UI to configure those custom roles — similar to what we have for creating an API key.

**Comment by pavlenex** [comment]
I am not sure if we should do this for 1.9.0 then, because coming up with mocks may take a while, perhaps we add it as abackedn for 1.9.0 and then add UI in 2.0.0, similary what we did for the custom forms?

**Comment by Kukks** [comment]
Yes, it's also more involved than the api keys UI. We have to have a crud
operation both on a server level and on a store level

**Comment by dennisreimann** [comment]
Maybe @Kukks can come up with something (either a rough scaffold code-wise or a quick mockup) to give dstrukt a direction. If you think we can go the code way, than it might be enough if we come up with a 80% suolution first and then @dstrukt can finalize it based on that.

**Comment by ndeet** [comment]
in Drupal you have lots of modules, custom roles and stuff and they do a pretty good job on organizing it, so as an inspiration how it looks 
https://drupalize.me/sites/default/files/tutorials/content-moderation-overview-permissions.png

(you see one section "content moderation" with different permissions that can be assigned to roles; there would be multiple of such sections)
