### ISSUE TITLE
Have `processing` checkout screen / state

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#4742]
When a user makes an on-chain payment, we show that the invoice is paid (settled state), when in fact, it's `processing`. This may lead to confusion and perhaps we should have a checkout scree/message that can communicate this more accurately.

This issue has extensively been discussed in #1319 but it got sidetracked with multiple topics (RBF for example).

The scope of this issue is straightforward, let's design a checkout screen, that will communicate that `Payment is processing and is waiting for confirmation on blockchain`. 

> Your payment has been received and is currently processing. Once it confirms on the blockchain, the status will be updated to settled.

**Comment by dstrukt** [comment]
I mocked up something in the process of doing the CheckoutV2 screens, will review it post it here if it looks good!

**Comment by dstrukt** [comment]
The old(er) mocks that haven't been updated.

<img width="313" alt="Screen Shot 2023-03-09 at 10 32 55 AM" src="https://user-images.githubusercontent.com/6250771/224122298-e8802e93-c910-4501-95c8-9ee15f394071.png">

**Comment by dstrukt** [comment]
@dennisreimann Want to confirm, as discussed in the design call, will we be attempting to support displaying X of Y confirmations, and a respective visualization? Or should we roll with something simple like the posted mock, and possibly follow up on a visualization. 

Posting for transparency.
