### ISSUE TITLE
[Bug]: BTCPAY creates non functional LNURLS if I use LNbank wallets 

### ISSUE THREAD

**Issue by kieselbert** [btcpayserver/btcpayserver#4745]
### What is your BTCPay version?

BTCPay Server v1.8.1+5caa0e072

### How did you deploy BTCPay Server?

Docker (in VM)

### What happened?

If I use the internal Lightning Node my LNURLs works fine. If I use LNbanks, create a Wallet and switch to "Use LNbank wallet" it creates LNURLs that do not work. What not working means : I can scan the qr-code and see the payment details, after I press the pay button I see Errors like:
Failed to connect to pay.domain.de. 400 (lnbits)  or
Problem with processing of LNURL (Wallet of Satoshi).

### How did you encounter this bug?

1. Create a LNbank Wallet
2. Connect the Lightning via "Change connection" with LNbanks with this Wallet
3. Create a Point of Sale App
4. Use PoS to create an Invoice --> "Bitcoin (Lightning LNURL) (BTC)"
5. Use a Wallet App with Lightning support to pay the invoice
6. U see the payment Details in the App after scanning the qr code (payment description and price in sats)
7. U press pay now, it tooks 1 minute and the payment failed 

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
This doesn't seem to be a general problem, just tested it and it worked for me. Can you see what the decoded LNURL gives you? https://lightningdecoder.com/

**Comment by dennisreimann** [comment]
Do the callback URLs work for you? Or does the latter yield an error page? If so, can you check what might be wrong about the invoice with ID `GLqDM2tbdLgfH8Hz7Ukj7T`?

To me they look OK, do you see any errors in the server logs after trying to pay the LNbank invoice?

**Comment by kieselbert** [comment]
The callback URLs both provide the strings that I mentioned {......}   
but I dont know what the Apps do with that information and what happens in background.
The logs in the Web-UI are not helpful, where can I find debug logs on console?

**Comment by dennisreimann** [comment]
You can find them with `docker logs`, but that'd be the same as in the web UI:

```bash
docker logs -f generated_btcpayserver_1
```

Just tested it again with WOS and LNbits ­— it's working for me, so I assume this might be a connection problem: What do you see in the Lightning Balance tile on the Dashboard when the LNbank wallet is set as the Lightning node? If there's a connection problem, see the [troubleshooting guide](https://docs.btcpayserver.org/LNbank/Troubleshooting/).

**Comment by kieselbert** [comment]
on the Dashboard i see only this --> LNbank (https://pay.domain.de/)
but when I click on "public node info" I see an "Unavailable" <-- is this normal?

**Comment by dennisreimann** [comment]
That indicates the connection problem I mentioned above. Please see the linked troubleshooting guide to resolve it.

**Comment by kieselbert** [comment]
Ok but a connection problem that only occurs when I use LNbanks. The internal Lightning with LNURL works fine.

**Comment by dennisreimann** [comment]
You can use `docker ps` on the server to see the port mappings: the one you mentioned refers to port 8080 of the `lnd_bitcoin` Docker container. 

Did you follow the troubleshooting guide and see if there might be a DNS problem with the resolving of the domain? I'm pretty sure that's the case as others had this issue before …

**Comment by kieselbert** [comment]
"and see if there might be a DNS problem with the resolving of the domain" you are right. 
I tried a curl to  https://pay.doityourself.de/plugins/lnbank/api/lightning/info 
and it works from everywhere but not from the btcpayserver itself. 
*   Trying 123.456.789.123:443...
* connect to 123.456.789.123 port 443 failed: Connection timed out
My router resolves the IP (because he know his own intefaces) and then it try to connect to the ip directly. The ip points to my reverseproxy and the proxy says "what should I do with an direct ip access? call a domain and I will hand you to the right server.".
Ok, now I need to figure out how to configure btcpay to connect its stuff internally...or maybe I can find a setting on my router to point the internal connection from the btcpay server to the external interface. weird stuff.

**Comment by kieselbert** [comment]
ok, case can be closed. What I needed was a /etc/hosts entry that points to my reverseproxy. now it works.
Thank you @dennisreimann , you guided me to the solution.
