### ISSUE TITLE
Create embeddable page for ln node info connections

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#475]
We should allow btcpayserver stores with enabled ln nodes to be able to display a page with just the node connection info so that they can embe/link to d in their sites without requiring you to go to a checkout screen.

Something like btcpayhost.com/stores/{storeid}/lightning/{cryptoCode}

**Comment by bitcoinshirt** [comment]
They can get the QR from http://1ml.com/ and embed it wherever they want.
I have this in footer.
![screen shot 2018-12-26 at 16 07 18](https://user-images.githubusercontent.com/36959754/50449549-5fac9b00-0928-11e9-9f60-e191ed5d721c.png)

**Comment by Kukks** [comment]
Do we really want to depend on a third party site to show our own node though? :D

**Comment by bitcoinshirt** [comment]
Well, we're not depending, you can get that very same info from the checkout page of your own BTCPay, right? 1ML was merely an example.

What would that widget do different, perhaps I'm missing something?
