### ISSUE TITLE
[Bug]: API Call - Update configured store automated payout processors - "Method Not Allowed"

### ISSUE THREAD

**Issue by strnly** [btcpayserver/btcpayserver#4752]
### What is your BTCPay version?

BTCPay Server v1.8.0

### How did you deploy BTCPay Server?

I'm running BTCPay Server on a VPS, CLN deployment.

### What happened?

When trying to run API call `Update configured store onchain automated payout processors`
https://docs.btcpayserver.org/API/Greenfield/v1/#operation/GreenfieldStoreAutomatedOnChainPayoutProcessorsController_UpdateStoreOnChainAutomatedPayoutProcessorForPaymentMethod

Using correct storeID and paymentMethod = BTC

We get Error: “Method Not Allowed”

When trying to run API call `Update configured store Lightning automated payout processors`
https://docs.btcpayserver.org/API/Greenfield/v1/#operation/GreenfieldStoreAutomatedLightningPayoutProcessorsController_UpdateStoreLightningAutomatedPayoutProcessor

Using correct storeID and paymentMethod = BTC-LightningNetwork

We get Error: “Method Not Allowed”

When trying to run alternate API call 
https://docs.btcpayserver.org/API/Greenfield/v1/#operation/GreenfieldStoreAutomatedOnChainPayoutProcessorsController_UpdateStoreOnChainAutomatedTransferSenderFactory

We get error “Not Found”

Note that we tried the above using a TEST api key with ALL permissions 

@petzsch tried and got same error 405 "Method Not allowed"

Response Header shows ALLOW: DELETE

### How did you encounter this bug?

Simply by calling the following API calls 

https://docs.btcpayserver.org/API/Greenfield/v1/#operation/GreenfieldStoreAutomatedOnChainPayoutProcessorsController_UpdateStoreOnChainAutomatedTransferSenderFactory

https://docs.btcpayserver.org/API/Greenfield/v1/#operation/GreenfieldStoreAutomatedLightningPayoutProcessorsController_UpdateStoreLightningAutomatedPayoutProcessor

### What browser do you use?

Brave, Chromium, Safari

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by strnly** [comment]
Is this merged in available update? if not ? what's the ETA ? THx

**Comment by Kukks** [comment]
> Is this merged in available update? if not ? what's the ETA ? THx

Hey @strnly,this was an API documentation mishap - try the same code but with the URLs `/api/v1/stores/{storeId}/payout-processors/LightningAutomatedPayoutSenderFactory` and `/api/v1/stores/{storeId}/payout-processors/OnChainAutomatedPayoutSenderFactory`

**Comment by strnly** [comment]
Lightning does not work.

https://docs.btcpayserver.org/api/v1/stores/{storeId}/payout-processors/LightningAutomatedTransferSenderFactory/{paymentMethod}

We did https://docs.btcpayserver.org/api/v1/stores/{storeId}/payout-processors/LightningAutomatedTransferSenderFactory/BTC-LightningNetwork

and also 

We did https://docs.btcpayserver.org/api/v1/stores/{storeId}/payout-processors/LightningAutomatedTransferSenderFactory/BTC-LNURLPAY

We get “Not Found”

 OnChain works.

**Comment by Kukks** [comment]
> @Kukks
> 
> Lightning does not work.
> 
> [https://docs.btcpayserver.org/api/v1/stores/{storeId}/payout-processors/LightningAutomatedTransferSenderFactory/{paymentMethod}](https://docs.btcpayserver.org/api/v1/stores/%7BstoreId%7D/payout-processors/LightningAutomatedTransferSenderFactory/%7BpaymentMethod%7D)
> 
> We did [https://docs.btcpayserver.org/api/v1/stores/{storeId}/payout-processors/LightningAutomatedTransferSenderFactory/BTC-LightningNetwork](https://docs.btcpayserver.org/api/v1/stores/%7BstoreId%7D/payout-processors/LightningAutomatedTransferSenderFactory/BTC-LightningNetwork)
> 
> and also
> 
> We did [https://docs.btcpayserver.org/api/v1/stores/{storeId}/payout-processors/LightningAutomatedTransferSenderFactory/BTC-LNURLPAY](https://docs.btcpayserver.org/api/v1/stores/%7BstoreId%7D/payout-processors/LightningAutomatedTransferSenderFactory/BTC-LNURLPAY)
> 
> We get “Not Found”
> 
> OnChain works.

Try `BTC` for payment method

**Comment by strnly** [comment]
@Kukks 

we get error -> “Method Not Allowed” using "BTC"

**Comment by strnly** [comment]
It finally worked ! NVM 

All good. We can close this issue. 

it needs 

[https://docs.btcpayserver.org/api/v1/stores/{storeId}/payout-processors/LightningAutomatedTransferSenderFactory/BTC-LightningNetwork](https://docs.btcpayserver.org/api/v1/stores/%7BstoreId%7D/payout-processors/LightningAutomatedTransferSenderFactory/BTC-LightningNetwork)

**Comment by NicolasDorier** [comment]
released new version 1.8.4 for this
