### ISSUE TITLE
[Feature Request]: QR scanner in Pull payment for lightning

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#4754]
In pull payments, it is possible for the user to copy/paste a BOLT11 or LNUrl to get paid.

![image](https://user-images.githubusercontent.com/3020646/223887886-838fb14d-cfb7-4ed5-9bea-88f5e4e62e97.png)

However, very often a user has his lightning wallet on mobile, and the pull payment opened on his laptop. Making it very difficult to transfer this information without relying on some chat software shared between the phone and laptop.

This could be solved by adding a QR scanner in this page. Then the customer can just scan the BOLT11/LNURL of the phone from his laptop.

**Comment by petzsch** [comment]
As said in my closed issue #4787 -> we might also want to have the QR code scanner for on-chain addresses available. (as this issue only talks about bolt11/lnurl)

Also it would be nice to reconsider the wording "BTC (off-chain)", most endusers would refer to this as just "BTC Lightning" - could reduce questions to support if we name it like that. Open for discussion on that one. :-)

**Comment by J2g276** [comment]
![2306077fft2053](https://github.com/btcpayserver/btcpayserver/assets/135845358/3f6234d4-33bd-4eca-b5d5-b450bc7fc3d1)

**Comment by pavlenex** [comment]
@NicolasDorier was this addressed here? https://github.com/btcpayserver/btcpayserver/pull/5274

**Comment by Kukks** [comment]
> @NicolasDorier was this addressed here? #5274

no
