### ISSUE TITLE
[Bug]: Getting CORS error message while using fetch method with the greenfield API

### ISSUE THREAD

**Issue by guillaumehussong** [btcpayserver/btcpayserver#4758]
### What is your BTCPay version?

I am running v.18.1

### How did you deploy BTCPay Server?

Docker

### What happened?

[https://chat.btcpayserver.org/btcpayserver/pl/335q3uhjdjfdpnu13h8ox74kww](url)

Get this CORS error(405) above while trying "Generate store on-chain wallet" of the greenfield api

### How did you encounter this bug?

making a fetch POST call to my btcpay instance from my typescript project

### Relevant log output

```shell
2023-03-09 13:36:04.705 +00:00 [INF] Greenfield.APIKeys was not authenticated. Failure message: ApiKey authentication failed
2023-03-09 13:36:04.746 +00:00 [INF] AuthenticationScheme: Greenfield.APIKeys was challenged.
2023-03-09 13:36:04.748 +00:00 [INF] AuthenticationScheme: Greenfield.Basic was challenged.
```

### What browser do you use?

Brave and Chrome

### Additional information

![image](https://user-images.githubusercontent.com/66718486/224039531-c918bb9d-948d-4047-a2b4-e2fee493a82d.png)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
try 1.8.4  please

**Comment by matborowiak** [comment]
I'm on 1.8.4
![image](https://user-images.githubusercontent.com/50250127/232237328-75cf3d77-912e-48aa-81bc-a5808f5ef813.png)

It seems `invoices/.../payment-methods/` still does not have required CORS header for web browser clients
