### ISSUE TITLE
[Bug]: Cannot create some of the permissions for Greenfield API

### ISSUE THREAD

**Issue by ilearnio** [btcpayserver/btcpayserver#4765]
### What is your BTCPay version?

1.6.12.0

### How did you deploy BTCPay Server?

Deployed to LunaNode, using one-click installation

### What happened?

For some reason I cannot create Greenfield API token with the following permissions: `btcpay.store.cancreatepullpayments`, `btcpay.store.cancreatenonapprovedpullpayments` even though creation of the `btcpay.store.canviewinvoices` works just fine.

Here is a bash script I'm running:

```
btcpayserver_url=...
user=...
password=...
store_id=...

body="{ \"permissions\": [ \"btcpay.store.canviewinvoices:$store_id\", \"btcpay.store.cancreatepullpayments:$store_id\", \"btcpay.store.cancreatenonapprovedpullpayments:$store_id\" ] }"
curl -s \
  -H "Content-Type: application/json" \
  --user "$user:$password" \
  -X POST \
  -d "$body" \
  "$btcpayserver_url/api/v1/api-keys"
```

So when I only leave the first permission (`btcpay.store.canviewinvoices:$store_id`) then the token gets created perfectly, but when I add two additional permissions it returns an error `[{"path":"permissions[1]","message":"Invalid 'Permission' String"}]`

### How did you encounter this bug?

Just follow the steps I provided above

### What browser do you use?

Just CLI

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by ilearnio** [comment]
Could someone confirm if it's a bug or it is just me me doing it wrong?

**Comment by Kukks** [comment]
Some of the permissions did not exist in your old version. As @dennisreimann said, please try updating first.

**Comment by ilearnio** [comment]
Ok, will do today and will let you know. Thank you so much for responses!

**Comment by ilearnio** [comment]
It worked, thanks again! The update of BTCPay from the UI or from CLI didn't work though. When updating from CLI it was saying that everything is up to date. So had to setup new BTCPay server from ground up

**Comment by dennisreimann** [comment]
@ilearnio might it be the case that you did modifications or manually switched the branch of the Docker setup? The "everything is up-to-date already" though it's on an old version kinda indicates the latter.

**Comment by ilearnio** [comment]
@dennisreimann All I did was I installed FastSync, didn't touch anything else
