### ISSUE TITLE
[Greenfield API]: streamline docs and get rid of apps (visually)

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#4776]
### What is your BTCPay version?

v1.8.1

### How did you deploy BTCPay Server?

docker

### What happened?

We have some ambiguity at the moment in the API docs https://docs.btcpayserver.org/API/Greenfield/v1

We have that main section "[Apps](https://docs.btcpayserver.org/API/Greenfield/v1/#tag/Apps)" which includes creating pos and crowdfund apps but then we also have separate main sections of [Crowdfund](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Apps_CreateCrowdfundApp) and [Point of Sale](https://docs.btcpayserver.org/API/Greenfield/v1/#tag/Point-of-Sale) which only have a subset of those methods.

Suggestion that can be done now:
- We move everything crowdfund and pos related to their respective toplevel sections
- This will leave [this](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Apps_GetAllApps) and [this](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Apps_GetAllAppsForStore) methods in the general apps section
- Rename "Apps" to Plugins?

All those enpoints are under /apps/ stores/:id/apps paths at the moment and we cant remove them until v2 of the API. 

We could keep it like that or add addional paths even v1 for now (add deprecation notice to others:

/apps/ -> /plugins/
/apps/crowdfund/* -> /crowdfund/*
/apps/pos/* -> /pos/*

What do you think? 

### How did you encounter this bug?

Visited API docs :P

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by ShawnRthom88** [comment]
Ho

**Comment by ndeet** [comment]
As discussed in dev call, we keep the /apps endpoint for now. Maybe use v2 of Greeenfield to consolidate. 

Nicolas also mentioned that pluins can hook into /apps endpoint. I think we should not encourage that and make them use their own endpoints /pluginname to not have it mixed but clearly separated.

**Comment by pavlenex** [comment]
@ndeet Does that mean we're closing this issue?
