### ISSUE TITLE
NFC Request Payment for POS

### ISSUE THREAD

**Issue by darkban** [btcpayserver/btcpayserver#479]
![pos](https://user-images.githubusercontent.com/32014414/50515754-d53e7580-0aa6-11e9-848e-00739c045535.jpg)

Hi guys I have an idea it would be nice to give the possibility to its customers to make payments with an NFC card that can be promoted by traders. The idea is to be able to make payment requests through our gateway. Generalbytes company has accomplished such a function

exsample video: https://www.youtube.com/watch?v=tmidgyQT4iE

**Comment by Kukks** [comment]
This is not possible. 
* Browsers do not have native NFC reading capabilities, we would need to build a native device app.
* These NFC cards are managed by a centralized authority that has control over your funds. 
* We are at the mercy of mobile wallet developers' support for NFC payment requests. I'm not sure there are any that support this at all

**Comment by darkban** [comment]
surely it makes people use the card and not the smartphone can serve as:

- purchases card
- loyalty card
- promotional purchases card

just think about how long it takes to take the smartphone, scan the core qr, enter the confirmation password ... too slow ...

with a card nfc everything would be much more immediate and more accessible to everyone as well as being able to better sponsor cryptocurrencies.

Mine is just an idea from which to draw inspiration.

**Comment by hubiktomas** [comment]
Hi, the NFC card contains your private key and the POS makes the transaction on your behalf. You have to obviously trust the POS that it will not spend all your funds. It is basically just an NFC version of a paper wallet for fast and easy purchases of a coffee for instance. It is not in any means a safe storage of funds.

**Comment by hubiktomas** [comment]
Btw, it might be possible in the future: https://w3c.github.io/web-nfc/

And it may be useful just in the POS running on a mobile phone or tablet. Probably not much in the normal gateway.

**Comment by darkban** [comment]
Yes, no central entity is needed and it would be convenient to implement it in the POS. As for security is the same thing as traditional cards visa or mastercard is always to be trusted or not ... even the classic pos with nfc technology can empty the entire amount ... But the realization of this function could give a turning point to those people who are tied to the cards or for the purpose of loyalty or paper purchases ... certainly a function of this kind would be larger than bitpay

**Comment by darkban** [comment]
If you reflect the usefulness there is and not a little ... I think as a trader ... so the functionality of which I speak is physical using the POS ... when you pay with your smartphone if you think well there are of the not indifferent slowdowns

1. take the smartphone
2. open the wallet
3. enter the first password or fingerprint
4. scan the qr code while you are standing in line at the store
5. enter the confirmation password
6. sending

are too many steps that with a simple NFC card would save a lot of time and would be much more userfriendly compared to a smartphone ... always that your smartphone is charged because if it is not then you can not pay: D

But not only this one could also use the nfc function to login in your administrative area.

**Comment by hubiktomas** [comment]
@darkban That is actually not a good example because in case of cards, there is always a central authority, that can reverse the transaction in case of a fraudulent behavior. This is not possible with crypto.

@bitcoinshirt It is always a balance between security and convenience. Paying with a NFC card takes milliseconds. So paying with that for your coffee or beer during a conference, where you have hundreds of people makes a real difference when compared to mobile wallet payments. Every second counts. So I would not say that it is useless. And as for the security - you can always write your own private key on the card. Of course it is not safe to have large amounts there. But for some coffee money it is ok as well as it is not OK to store your savings in any mobile wallet. But I agree that the BTCPayServer purpose is a little bit different and there will probably not be many people using it. But lets let the community do decide. We may find someone who will be willing to implement it in the future.

**Comment by pieman64** [comment]
@darkban steps 1 to 6 that you refer to do seem quite time consuming but the practicality is that steps 1 to 3 should be done by a buyer before they get to the checkout.

If it's a busy store I would send the buyer to the back of the queue if they haven't got their "wallet" ready  when it's time to pay.

**Comment by darkban** [comment]
I speak as a trader and the client takes out his wallet or smartphone when he is at the cash desk and not before ... I am a trader with several physical services and 98% of people do it this way and the process assures you that it is slow especially for those with a lot of traffic.

Not to mention if the line does not take well in store, the customer's battery is exhausted ... The card would simplify everything ... 

but I talk about card and NFC function because it is and will be the future ... guys but have you ever heard talk about nFC chips implemented on the hand? maybe I'm too futuristic :)

**Comment by pieman64** [comment]
When I stated "wallet" I was referring to a CDA wallet, not a traditional leather wallet. Folks today are stood in the queue using their smartphone. Not ready, back of the queue mate.

**Comment by bitcoinshirt** [comment]
@hubiktomas 
> And as for the security - you can always write your own private key on the card. 

So now we went from it's convenient and quick to newbies have to re-program them.

No matter the steps you listed,[ mobile wallet's aren't slow](https://youtu.be/Mz4uajz0z9Y?t=413) and the speed can't be the argument for this proposal. The whole Chinese economy is based on WeChat and it works even in busy stores.

I am just trying to understand the main benefit: speed/ease of use because I don't see either, especially taking into consideration clunkiness (my whole life is in my phone, I don't want to carry around crappy cards) and terrible security practice.

**Comment by darkban** [comment]
Guys your point of view is very restrictive and I think you should expand your view ... I'm not saying that the wallet on the smartphone is better than the card nfc ... I'm just saying it would be nice to implement a function that would allow to spend their own crypto without the need to use a smartphone in perspective even the payments with implementation on the hand as can be the nfc chip. it is a function, useful to some to others, no doubt it is faster.

**Comment by hubiktomas** [comment]
@bitcoinshirt 

> So now we went from it's convenient and quick to newbies have to re-program them.

No, we went to "anyone can rewrite them if they are concerned about security of their couple of bucks for coffee. Reprogramming is a strong word here as it takes just something like 3 clicks in any app capable of writing NFC tags.

As already mentioned. It is just a matter of preference. Somebody as you prefer using smartphone, somebody can prefer NFC card. Luckily this is a colorful world and open-source project so anyone seeing the benefit can implement this feature and anyone not seeing the benefit can just ignore or disable this feature. :) I think that there is no point in arguing about that. It is objectively faster and easier to use and it is up to everyone if it is worth using for saving these 2 seconds or 2 clicks per payment. :)

**Comment by Kukks** [comment]
Until the web spec for Web NFC is widely adopted or somebody builds us a native pos app, this discussion is useless people :)  We have a bazillion features to add that's already a lot more mission-critical :)

**Comment by Kukks** [comment]
@bitcoinshirt  Let's close until this https://whatwebcando.today/nfc.html gives us the go ahead :P

**Comment by taxmeifyoucan** [comment]
@pavlenex @Kukks Any update on this? Chrome in Android currently supports NFC and that is huge part of audience - Bitcoin PoS terminals are mostly android devices, physical merchants I interact with are using android phones/tablets with Btcpay. Doesn't make sense to me to wait for e.g. iPhone devices. 
NFC tags with private keys were discussed here but great use case might be support for LNURL-withdraw. NFC contains just lnurl string and Btcpay can withdraw requested amount. Enabling paying with 'lightning cards' would be great pioneering :)

**Comment by taxmeifyoucan** [comment]
@Kukks @pavlenex Check this for example https://twitter.com/gladstein/status/1444398232692576259 Let's make visa obsolete as well.

**Comment by tlindi** [comment]
> @pavlenex @Kukks Any update on this? Chrome in Android currently supports NFC and that is huge part of audience - Bitcoin PoS terminals are mostly android devices, physical merchants I interact with are using android phones/tablets with Btcpay. Doesn't make sense to me to wait for e.g. iPhone devices. NFC tags with private keys were discussed here but great use case might be support for LNURL-withdraw. NFC contains just lnurl string and Btcpay can withdraw requested amount. Enabling paying with 'lightning cards' would be great pioneering :)

@pavlenex @Kukks Now I find "Pay with NFC & LNURL-Withdraw" is on checkout :-)
![image](https://user-images.githubusercontent.com/7249767/211380624-6399b8bf-6b84-40e7-aba7-9560f62745e2.png)

When I click it on Chrome Android - it turns to running circle on blue background (XX) 
I show NFC to phone, card is read (twice firs light brr and then normal NFC read BLING) but phone suggests only NFC Capable Lightning Apps. 
If I click again on XX background changes to green. But no matter I do I cant get NFC paymant througth.

Yes same card works on eg Breez, and no it is no boltcard - just LNURLw).

Here guy in video shows how to enable sites to work (if he had NFC Enabled):
https://www.youtube.com/watch?v=W6XcskU7Fi8
his last settings page shows me my BTCPay address - and I have enabled it as approved too.

Ideas ?
