### ISSUE TITLE
[Bug]: Altcoin Monero using Trezor HW results in Ghost Wallet

### ISSUE THREAD

**Issue by itsMikeLowrey** [btcpayserver/btcpayserver#4791]
### What is your BTCPay version?

BTCPay Server v1.8.4+fadb05e97 (Altcoins)

### How did you deploy BTCPay Server?

I deployed on a vps using seths guide: https://sethforprivacy.com/guides/accepting-monero-via-btcpay-server/#add-the-view-only-wallet-to-btcpay-server

### What happened?

I created a view only wallet using my trezor wallet and (monero GUI and featherwallet) but the addresses do not go to a wallet that I am aware of exist. I think something about a trezor being used in this setup causes a ghost wallet to be created. I tried using a feather wallet without hw wallet and it worked fine. 

### How did you encounter this bug?

I noticed that my payments were not going to my wallet. 

### Additional information

I am not sure where the issue lays, but I am posting this just in case anyone else tries to use monero+ trezor + btcpay setup. I will try with a ledger soon and see if it causes a similar issue. 

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by valsha** [comment]
Yes, the hardware wallets are not working.  As far as I remember, it has always been like this.

**Comment by pavlenex** [comment]
Yes this is something we don't plan to work on
