### ISSUE TITLE
[Bug]: Invoice creation is very slow

### ISSUE THREAD

**Issue by status21** [btcpayserver/btcpayserver#4800]
### What is your BTCPay version?

v1.8.0

### How did you deploy BTCPay Server?

raspiblitz

### What happened?

When I create an invoice after a day of not having created one, it takes 3 to 10 seconds until the invoice appears, sometimes not at all. When I create a second one afterwards the invoice appears within <1sec.
Edit: New version of checkout was enabled. It seems that the old checkout doesn't have this issue.

### How did you encounter this bug?

click on paybutton

### What browser do you use?

Safari, Firefox, Edge

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Not enough context for us to attempt to replicate, I recommend you asking for help on chat.btcpayserver.org or our Telegram then we can reopen the issue once the bug is replicated.
