### ISSUE TITLE
[Bug]: ndefreader should't stop scanning immediately after the card is read. 

### ISSUE THREAD

**Issue by JssDWt** [btcpayserver/btcpayserver#4807]
### What is your BTCPay version?

I'm not actually running BTCPay, just reporting an issue.

### How did you deploy BTCPay Server?

The issue is on a POS device in the browser.

### What happened?

Some people run into the issue that another app opens when someone pays with an NFC card. This is because when the ndefreader scan is aborted, the OS takes over the nfc scan. The card will be read again and the default app to handle the link on the card will be opened (sometimes it's the 'choose app' screen).

You'll probably want to stop scanning after a few seconds or so, when the card has been removed from the reader, before stopping the scan.

### How did you encounter this bug?

I'm not sure about the exact steps.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by titusz** [comment]
This illustrates the issue.

https://user-images.githubusercontent.com/278556/227247722-88cde5d4-094e-40ee-bd2c-9813bea2e29f.mp4

If you remove the tag faster you may get lucky and it does not happen. I am not sure if/how this can be prevented. But it would help to give an audio signal instantly when the tag has been read. Maybe it is possible to only release the handler to the NFC reader after it is out of reach?
