### ISSUE TITLE
[Bug]: Cannot refund invoices with set expiration time less than 24h

### ISSUE THREAD

**Issue by frnandu** [btcpayserver/btcpayserver#4830]
### What is your BTCPay version?

1.8.2

### How did you deploy BTCPay Server?

Kubernetes

### What happened?

Even when set to 1 day, when I get invoices for refunds, most are less than 24h, so they get refused with "...Invoice must have an expiry date of at least 1 day...".
Shouldn't there be an option for specifying hours instead of days???

### How did you encounter this bug?

when refunding

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
@Kukks can you look into this one please?

**Comment by Bobbieann0709** [comment]
[Your incoming transaction waiting  id - 25052444.pdf](https://github.com/btcpayserver/btcpayserver/files/11155334/Your.incoming.transaction.waiting.id.-.25052444.pdf)

**Comment by Kukks** [comment]
> @Kukks can you look into this one please?

I'm not sure what the best course of action is here. If we allow this requirement to be optional, then way more payouts will fail if a payout processor is not configured to run often.

Should we make it an optional setting, and maybe merge the payout processing settings cta PR?

**Comment by frnandu** [comment]
I don't know how you guys do refunds, but I'm just asking the user to send me an invoice with the agreed amount, and usually I get an invoice with a few hours expiration time, which makes it impossible to do the refund on btcpayserver. So either I don't understand what is the appropriate way for refund procedure, or you guys are ignoring this kind of workflow not allowing shorter expiration time for manual refunds.

**Comment by frnandu** [comment]
I understand, but IMO it is not enough argument against allowing refunding invoices which users send to me with < 24h expiration time. I think most cases people aren't even aware (and shouldn't need to be) that the invoices they generate on a given wallet has an expiration time or doesn't have the option of modifying it.
