### ISSUE TITLE
[Bug]: Lightning Addresses not working when using external reverse proxy

### ISSUE THREAD

**Issue by timmornYE** [btcpayserver/btcpayserver#4836]
### What is your BTCPay version?

BTCPay Server v1.8.4+fadb05e97

### How did you deploy BTCPay Server?

Docker on Debian with Reverse Proxy configured like [described in FAQ](https://docs.btcpayserver.org/FAQ/Deployment/#can-i-use-an-existing-nginx-server-as-a-reverse-proxy-with-ssl-termination).

### What happened?

When I am using btcpay Server reverse Proxy, all works fine. If I switch to extrenal Proxy like [described in FAQ](https://docs.btcpayserver.org/FAQ/Deployment/#can-i-use-an-existing-nginx-server-as-a-reverse-proxy-with-ssl-termination), everything works fine, except generated "Lightning Address" is not working anymore. If I try to use them with Wallet of Satoshi it says "Failed to decode invoice, please try again". If I switch back to btcpay Proxy, all works fine again. 

### How did you encounter this bug?

1. Setup btcpay with Docker so that everything works fine
2. Setup external proxy like [described in FAQ](https://docs.btcpayserver.org/FAQ/Deployment/#can-i-use-an-existing-nginx-server-as-a-reverse-proxy-with-ssl-termination)
3. Try to do payment to "Lightning Address"

### What browser do you use?

Chrome

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Can you check the `Access-Control-Allow-Origin` header for the Lightning Address endpoint when accessed via the external proxy? The endpoint is `/.well-known/lnurlp/{username}` — it should allow all access (`*`).

Can you also check the proxy log to see what the responses look like and if there's additional information?

**Comment by dennisreimann** [comment]
Seems good, anything we might be overlooking @NicolasDorier ? Checked my instances and they only contain `acme-challenge` inside the `.well-known` directory — I'll go ahead and update the docs.
