### ISSUE TITLE
[Bug]: BtcPayServer stops responding if there are at least 3 request in a row, the 4th request takes up to 30 seconds

### ISSUE THREAD

**Issue by gorrdy** [btcpayserver/btcpayserver#4837]
### What is your BTCPay version?

BTCPay Server v1.8.0+2b3d15bf4

### How did you deploy BTCPay Server?

Lunanode Cloud

### What happened?

I tried to generate 4 invoices quickly one after each other and 3 went smoothly.

The 4th invoice is generating a long time (sometimes 20s+) - the browser is just waiting for the server response.

Is there any limit for number of requests that the BTCPayServer is capable of?

### How did you encounter this bug?

1. Visit https://btcpayserver.cz/apps/4VQpFMQ6kbea5N5u5WZ14GrD2N3p/pos
2. Set any amount of e.g. 10 CZK
3. Click charge
4. Click BACK in your browser
5. Repeat 3&4 until the btcpayserver is stuck

### What browser do you use?

Safari

### Additional information

Also simulated this issue on different cloud instances, also Umbrel with RPi, Lunanode etc.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by gorrdy** [comment]
@petzsch found this in the code base..

If it is not a development environment, then a rule of 4 invoices/minutes is applied.
https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Hosting/Startup.cs#L244

`rateLimits.SetZone($"zone={ZoneLimits.PublicInvoices} rate=4r/min burst=10 delay=3");`

I do not find this necessary to have such a small number of invoices per minute limitation because many users can generate easily more invoices than this.

Currently it limits guys from BTCPrague to sell their tickets on conference.

**Comment by Kukks** [comment]
Maybe we can make it so that the rate limit doesn't apply if logged in

**Comment by gorrdy** [comment]
@Kukks Hi, this wouldn't help. We need to fix this for people accessing the server from the internet so they do not have any account on that specific btcpayserver.

**Comment by petzsch** [comment]
Just tested through my Greenfield API created app: The rate limit doesn't affect greenfield invoice creation

**Comment by Kukks** [comment]
There is nothing wrong with nginx or ip as they are using a Luna node
standard deployment.

This sounds like a misunderstanding, because you can replicate it when you
use one machine, but when many users are using it, it does not occur.

**Comment by gorrdy** [comment]
If 5 users uses some free VPN or the same VPN, it will trigger the limit though, right? @Kukks

It is not a problem with smaller btcpay serves, but BtcPrague has a lot of bitcoin people that probably uses VPN that easily triggers the limit of 4.

Is there any change how to workaround this? It would be cool to set your own limits for some specific cases.

**Comment by Kukks** [comment]
cc @NicolasDorier  Is there a way to configure the rate-limiting at runtime?

**Comment by Kukks** [comment]
> If 5 users uses some free VPN or the same VPN, it will trigger the limit though, right? @Kukks
> 
> It is not a problem with smaller btcpay serves, but BtcPrague has a lot of bitcoin people that probably uses VPN that easily triggers the limit of 4.
> 
> Is there any change how to workaround this? It would be cool to set your own limits for some specific cases.

working on it.

**Comment by Kukks** [comment]
![](https://i.imgur.com/QiZfoe0.png)

very reckless, untested, but it should do the trick

**Comment by gorrdy** [comment]
> ![](https://camo.githubusercontent.com/fb0ffb3e1f574f9daecb97d2c034df211da946679448f485532eb5ba90a2adcb/68747470733a2f2f692e696d6775722e636f6d2f51695a666f65302e706e67)
> 
> very reckless, untested, but it should do the trick

I set higher limits through that Dynamic Rate Limit plugin and I confirm it works as expected for now. Thank you very much @Kukks  .

This doesn't "resolve" the problem but it is a possibility how to nearly eliminate the risk of not generating an invoice with a possibility to increase the limit if needed.

Keep in mind please that this happened with a standard integration of a btcpayserver so this limit will be triggered if there is some decent traffic e.g. bitcoin conference that uses btcpayserver as a payment method (tickets online or even on physical location). Also if a group of 4 in e.g. an office or a few people with the same VPN (we've experienced it with normal web traffic) it will trigger the limit also.

This prevents btcpay to scale more. Now it is not a "general" problem because there are just a few projects that have an impact that big to trigger it but when bitcoin and btcpay will be more popular, it could be a problem.

My ideas:
1. Increase the limit of 4 to at least 20 or so, not that big of a deal I think but it will provide a decent number of users to generate invoices in a one-minute time span.
2. make these limits configurable - the plugin is OK for now I think

Thank you again. It helped us a lot!

**Comment by Kukks** [comment]
> > ![](https://camo.githubusercontent.com/fb0ffb3e1f574f9daecb97d2c034df211da946679448f485532eb5ba90a2adcb/68747470733a2f2f692e696d6775722e636f6d2f51695a666f65302e706e67)
> > very reckless, untested, but it should do the trick
> 
> I set higher limits through that Dynamic Rate Limit plugin and I confirm it works as expected for now. Thank you very much @Kukks .
> 
> This doesn't "resolve" the problem but it is a possibility how to nearly eliminate the risk of not generating an invoice with a possibility to increase the limit if needed.
> 
> Keep in mind please that this happened with a standard integration of a btcpayserver so this limit will be triggered if there is some decent traffic e.g. bitcoin conference that uses btcpayserver as a payment method (tickets online or even on physical location). Also if a group of 4 in e.g. an office or a few people with the same VPN (we've experienced it with normal web traffic) it will trigger the limit also.
> 
> This prevents btcpay to scale more. Now it is not a "general" problem because there are just a few projects that have an impact that big to trigger it but when bitcoin and btcpay will be more popular, it could be a problem.
> 
> My ideas:
> 
> 1. Increase the limit of 4 to at least 20 or so, not that big of a deal I think but it will provide a decent number of users to generate invoices in a one-minute time span.
> 2. make these limits configurable - the plugin is OK for now I think
> 
> Thank you again. It helped us a lot!

This is actually the first complaint we've had around this. Actually, we've had the opposite where people wanted stricter rate limiting (that I doubt would have worked out well at all). We do have some very high-volume merchants, but they almost always use the API to generate invoices as their custom integrations require it. 

Anyway, this opt-in plugin should help anyone adjust to their needs and superficially turn off the rate limit by setting it to a crazy number.
