### ISSUE TITLE
[Bug]: Invoice monitoring dies after LND restarts

### ISSUE THREAD

**Issue by Jossec101** [btcpayserver/btcpayserver#4840]
### What is your BTCPay version?

v1.7.2.0

### How did you deploy BTCPay Server?

Docker container

### What happened?

If LND restarts, already existing and new invoices never settle though they are paid on lightning.

### How did you encounter this bug?

1. Create invoice
2. Restart LND (docker restart)
3. Pay invoice (using polar)
4. Check that the invoice monitoring does not detects the payment yet it was paid on LN

### Additional information

After some time, btcpayserver will recover but its a downtime

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Sounds similar to #4525.
