### ISSUE TITLE
[Bug]: Order Amount = Already Paid Bug

### ISSUE THREAD

**Issue by itsMikeLowrey** [btcpayserver/btcpayserver#4845]
### What is your BTCPay version?

v1.8.4+fadb05e97 (Altcoins)

### How did you deploy BTCPay Server?

Deployed using seth for privacy guide. 

### What happened?

If a person pays at my monero store, sometimes the already paid = the order amount but btcpay will still request a payment of a very small amount of monero. Here is an example. https://imgur.com/aC2Tpcy

### How did you encounter this bug?

A customer brought it to my attention when it occurred to them. 

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by petzsch** [comment]
Check your Store Settings under General Tab:
![grafik](https://user-images.githubusercontent.com/1374810/229270833-0a1a8bc5-7a11-4456-bc3f-e4febc770c3e.png)

The problem happens usually when customers pay directly from an exchange and they take out a transaction fee.

If this solves your issue, please close it yourself. 😄

**Comment by itsMikeLowrey** [comment]
Thanks for the help!
