### ISSUE TITLE
[Bug]: Update not working anymore

### ISSUE THREAD

**Issue by nexondo** [btcpayserver/btcpayserver#4847]
### What is your BTCPay version?

1.8.1

### How did you deploy BTCPay Server?

Lunanode Ubuntu Vm

### What happened?

Hey, before it was always working. Once a new Version came out I just did the update. It still shows if there is Update available the server will restart soon. Sadfully nothing happens now I stay on 1.8.1 even 1.8.4 is features in the Notifications. I already restarted the whole server and still not working. Is this a Bug or is there any solution for it?

Thanks Jason

### How did you encounter this bug?

Server Settings, Maintenance, Update

Also additional when you change the BTC in Sats (Dashboard Graph) it will still show BTC in the X-Graph and not switch to sats also not in the amount (maybe it's already fixed in 1.8.4 don't know this)

### What browser do you use?

firefox

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
It doesn't seem you were able to provide enough information for us to troubleshoot this, I recommend first providing more information perhaps chat.btcpayserver.org can help to figure things out. Let's re-open this once there's more context.

**Comment by guymass** [comment]
I have the same issue im using BTCPay Server v1.7.12 and when I try to run btcpay-update.sh I get an error:

![Screen Shot 5783-07-29 at 13 13 42](https://user-images.githubusercontent.com/58882903/233336710-6b0f4a03-a694-4e62-b641-d7b35f138acb.jpg)

**Comment by nexondo** [comment]
for me it was still with the new 1.9 version not possible to upgrade through the GUI (Dashboard)
but the btc-update.sh was working withhin the first attempt.
maybe try to restart the system and execute the command again?
