### ISSUE TITLE
Overpayment lightning (c-lightning) not visible in invoice details

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#486]
As reported by @nadav in Slack it seems that with c-lightning the overpayment is not visible in the invoice details, see: https://forkbitpay.slack.com/archives/C9VJNV9EJ/p1546435685153400

Copied screenshots here from that convo.

1. you see that I double paid the amount of the invoice
![image](https://user-images.githubusercontent.com/1136761/50693214-a1c79200-1036-11e9-89b1-c19f85217b9a.png)

2. on btcpay invoice details this is not showing up
![image](https://user-images.githubusercontent.com/1136761/50693240-b441cb80-1036-11e9-9c69-93db0b440c71.png)

3. example of @Kukks on-chain BTC payment where it shows up correctly
![image](https://user-images.githubusercontent.com/1136761/50693338-ebb07800-1036-11e9-9471-1fe2722a7fe6.png)

**Comment by ndeet** [comment]
Can anybody test this with LND please?

**Comment by NicolasDorier** [comment]
How an over payment with lightning is even possible? The user can't input amount

**Comment by ndeet** [comment]
On my Eclair + Lightning wallet both allow me to edit amount (see screenshots below). As this feature (display of overpayment) is available on on-chain payments I think it would be handy also available for LN payments?

Eclair Mobile
![image](https://user-images.githubusercontent.com/1136761/50724210-1c051e80-10ea-11e9-8766-4f1011a29ff0.png)

Lightning Wallet
![image](https://user-images.githubusercontent.com/1136761/50724214-2d4e2b00-10ea-11e9-9bf8-9f2702a7832e.png)

**Comment by NicolasDorier** [comment]
Shit, the fact that somebody theorically can pay more is pain in the ass.
