### ISSUE TITLE
 user-id14187092  BitCoin Mining wanted a transaction fee after paying the $64 fee (twice) . When I pay the trans fee, will it remember the paid $64 fee last night? night  

### ISSUE THREAD

**Issue by smallchange55** [btcpayserver/btcpayserver#4863]
### What is your BTCPay version?

 user-id14187092  BitCoin Mining wanted a transaction fee after paying the $64 fee (twice) . When I pay the trans fee, will it remember the paid $64 fee last night?

### How did you deploy BTCPay Server?

 user-id14187092  BitCoin Mining wanted a transaction fee after paying the $64 fee (twice) . When I pay the trans fee, will it remember the paid $64 fee last night? 

### What happened?

 user-id14187092  BitCoin Mining wanted a transaction fee after paying the $64 fee (twice) . When I pay the trans fee, will it remember the paid $64 fee last night?  

### How did you encounter this bug?

 user-id14187092  BitCoin Mining wanted a transaction fee after paying the $64 fee (twice) . When I pay the trans fee, will it remember the paid $64 fee last night? night  

### What browser do you use?

Chrome Version 112.0.5615.50 (Official Build) (64-bit)

### Additional information

Version 112.0.5615.50 (Official Build) (64-bit)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Kukks** [comment]
https://blog.btcpayserver.org/bitcoin-bonus-scam/

**Comment by dennisreimann** [comment]
See this https://blog.btcpayserver.org/bitcoin-bonus-scam/
