### ISSUE TITLE
warn: Configuration:  BTC: The macaroon file path of the external LND grpc config was not found (D:\admin.macaroon)

### ISSUE THREAD

**Issue by jarole** [btcpayserver/btcpayserver#487]
Hi . I run btcpay on Linux  and I see weird warning from the output:
`warn: Configuration:  BTC: The macaroon file path of the external LND grpc config was not found (D:\admin.macaroon)`

I don't have that path on Linux, so I am not sure what configuration it means. Any ideas?
My config file has this line with correct path to admin.macaroon:

`BTC.lightning=type=lnd-rest;server=https://127.0.0.1:8080/;macaroonfilepath=~/.lnd/data/chain/bitcoin/mainnet/admin.macaroon;certthumbprint=.........`

**Comment by bitcoinshirt** [comment]
Can you provide error logs? [Here's how.](https://docs.btcpayserver.org/support-and-community/troubleshooting#2-2-lightning-network-logs)
What happens when you go to Store Settings > Lightning Network (experimental) > Modify and click test connection? 
Also, [check this](https://docs.btcpayserver.org/faq-and-common-issues/faq-lightningnetwork#lnd-connection-issues-after-an-update)

**Comment by jarole** [comment]
only this kind of errors are in my lnd errorlog:
`2019-01-04 14:50:17.459 [ERR] CMGR: Can't accept connection: unable to accept connection from 92.53.65.45:48064: EOF`
`2019-01-04 14:52:47.616 [ERR] CMGR: Can't accept connection: unable to accept connection from 92.53.65.45:53270: EOF`
`2019-01-04 14:55:17.616 [ERR] CMGR: Can't accept connection: unable to accept connection from 92.53.65.45:58274: EOF`
`2019-01-04 14:57:47.874 [ERR] CMGR: Can't accept connection: unable to accept connection from 92.53.65.45:35224: EOF`
`2019-01-04 15:00:17.511 [ERR] CMGR: Can't accept connection: unable to accept connection from 92.53.65.45:40298: EOF`
`2019-01-04 15:02:47.860 [ERR] CMGR: Can't accept connection: unable to accept connection from 92.53.65.45:45388: EOF`
`2019-01-04 15:05:17.264 [ERR] CMGR: Can't accept connection: unable to accept connection from 92.53.65.45:50424: EOF`
`2019-01-04 15:07:47.586 [ERR] CMGR: Can't accept connection: unable to accept connection from 92.53.65.45:55454: EOF`
`2019-01-04 15:10:17.890 [ERR] CMGR: Can't accept connection: unable to accept connection from 92.53.65.45:60596: EOF`
`2019-01-04 15:12:48.024 [ERR] CMGR: Can't accept connection: unable to accept connection from 92.53.65.45:37388: EOF`
`2019-01-04 15:15:17.614 [ERR] CMGR: Can't accept connection: unable to accept connection from 92.53.65.45:42636: EOF`
`
I will take a closer look at my lnd , This russian IP is weird, I have no channel with it. 
Thanks for hint.

**Comment by jarole** [comment]
Update of lnd (to `0.5.1`) and go-lang (to `1.11`) solved my issue.
Just fyi
