### ISSUE TITLE
txid missing in json reply from Invoice API?

### ISSUE THREAD

**Issue by hlooman** [btcpayserver/btcpayserver#488]
I am looking for a way to retrieve the txid of the transaction of the payment. By the looks of it, it is not included in the reply from a query to the Invoice API... ( server.tld/invoices/{invoiceid} )
Am I missing something?

**Comment by Kukks** [comment]
Yes, it is not included. The issue comes that the current API only matches the bitpay spec. We'll be rolling out a new API in the short to medium term that will be infinitely better than their relatively shitty one.

**Comment by hlooman** [comment]
Awesome! I will close the issue, knowing that it's on the radar! Thanks for the quick reply.

**Comment by pasquantonio** [comment]
How can we get the transaction id in the meantime?

**Comment by Kukks** [comment]
There is a property when get fetching the invoice called `cryptoInfo`. It has all the data you need

**Comment by pasquantonio** [comment]
```
'cryptoInfo': [{'cryptoCode': 'BTC', 'paymentType': 'BTCLike', 'rate': 1.0, 'exRates': {'BTC': 0.0}, 'paid': '0.00080000', 'price': '0.00250000', 'due': '0.00170118', 'paymentUrls': {'BIP21': 'bitcoin:removedaddress?amount=0.00170118', 'BIP72': None, 'BIP72b': None, 'BIP73': None, 'BOLT11': None}, 'address': 'removedaddress', 'url': 'https://removedurl/i/BTC/EaRKSGoqM882VaXkhLQVDA', 'totalDue': '0.00250118', 'networkFee': '0.00000118', 'txCount': 1, 'cryptoPaid': '0.00080000', 'payments': [{'id': 'c873eb2f2d005e9cb17dfbde6ecb25dc4d5251e4c679163400ecf4b087ab5da0-1', 'receivedDate': '2020-06-08T03:25:05.225', 'value': 0.0008, 'fee': 0.0, 'paymentType': 'BTCLike', 'confirmed': True, 'completed': True, 'destination': 'bc1q8any9676wsczga6xuwtsssnmchahaqs8ce7lsw'}]}]
```
This is the data I am getting back with `cryptoInfo` Do you mean that I can use this to get the transactionId?

**Comment by bolatovumar** [comment]
@seniordev-ca if you look [here](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Invoices_ArchiveInvoice) you will see that the response has a `payments` property which has an array of objects with an `id` property. That `id` property is the transaction id I believe.
