### ISSUE TITLE
I have paid twice for a service and have a web reciept for both times and have gotten nothing

### ISSUE THREAD

**Issue by Kstar68** [btcpayserver/btcpayserver#4880]
### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/4879

<div type='discussions-op-text'>

<sup>Originally posted by **Kstar68** April 14, 2023</sup>
I have already paid twice for a service and have seen nothing and have web reciept for both now what do I do?</div>

**Comment by petzsch** [comment]
please read my reply in #4879 and don't spam our development tools.
