### ISSUE TITLE
[Bug]: When updating to version v1.9.0 the mapping to the APP stops working.

### ISSUE THREAD

**Issue by jairunet** [btcpayserver/btcpayserver#4882]
### What is your BTCPay version?

BTCPay Server v1.9.0+717f1610f

### How did you deploy BTCPay Server?

BTCPay is running on docker.

### What happened?

Before updating to version BTCPay Server v1.9.0+717f1610f the mapping from the URL to the APP (POS) worked, but once the update was completed, the URL mapping stopped working, and the redirection was taking users to the BTCPay server admin login page of the POS.

### How did you encounter this bug?

I logged in to the BTCPay server POS APP without issues before the update, then noticed that there was a new version available, I went to `server settings` -> `maintenance` -> `update`

After the update was completed I tried to access the APP and the redirection was not working anymore.

### What browser do you use?

Google Chrome & Firefox

### Additional information

I solved the issue by going to `server settings` -> `policies` -> `customization settings` and changing the `Point of Sale` details to `None` save it, and then switch the information back to `Point of Sale` and save it.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
I noticed that to and it's odd, because I don't think we changed something in that regard @NicolasDorier 

For now, a quick fix is to simply save the mappings again as they are – at least that worked for me.

**Comment by mjlamb** [comment]
I've just had the same problem, the problem was I had removed a "crowdfund" site that was no longer used, I still had a mapping for it in the server polices screen, this was failing all other mappings that were listed after it, so I was getting 404, pretty NicolasD pics. I removed the mapping that was listed for the removed crowdfund site and they all started working again, this could be your issue?

**Comment by mjlamb** [comment]
I believe a failing mapping should not cause the others no to work, maybe an extra check is needed here.

**Comment by NicolasDorier** [comment]
That's bad, checking

**Comment by NicolasDorier** [comment]
I found the problem, with our "Plugins can make apps" feature, we changed a field from Enum (with output as numeric) to a string.

I am on it.

**Comment by NicolasDorier** [comment]
Will make a new release shortly.

**Comment by mjlamb** [comment]
@NicolasDorier This change you have made looks to be around migration, but my issue I think might have been different, my one failed due to the under lying "crowdfund" app had been removed and the mapping failed. FYI

**Comment by NicolasDorier** [comment]
@mjlamb I just bumped to 1.9.1

**Comment by NicolasDorier** [comment]
@mjlamb your problem may be different, I need to check

**Comment by NicolasDorier** [comment]
I tested locally by using two local domain, couldn't repro your problem @mjlamb

**Comment by mjlamb** [comment]
@NicolasDorier I'll give it a go tonight, but the process would be. 
Add croudfund app, add a mapping for it for domain. i.e. map3.domain.com
Make sure you have other existing domain mappings, i.e. map1.domain.com, map2.domain.com
Delete crowdfund app. (this leaves map3.domain.com in server screen)
See if you can load the existing mappings. map1.domain.com, map2.domain.com

**Comment by NicolasDorier** [comment]
yes that's what I tried, seemed to work though.
