### ISSUE TITLE
[Bug]: New receipt in Shop + cart doesnt display items properly and missing additional info.

### ISSUE THREAD

**Issue by Bas02** [btcpayserver/btcpayserver#4890]
### What is your BTCPay version?

1.9.1

### How did you deploy BTCPay Server?

LunaNode standard deployment 

### What happened?

Using the PoS app in the Shop + Cart configuration the following happens with receipts. 
When there's only 1 item purchased, the name of the item does not get displayed, but rather the title of Cart and item price.

### How did you encounter this bug?

Whenever selecting just 1 item, no discounts or tips, the receipt shows ;
![1](https://user-images.githubusercontent.com/102448109/232549157-8cb0cc68-5c02-4153-802f-1f6e539e9b66.jpg)

When you add discount or tips, the selected items name doesn't show ; 
![2](https://user-images.githubusercontent.com/102448109/232549437-a640f310-5550-475a-9671-d77f7318cde4.png)

However when you select multiple items, it looks as follows ; 
![3](https://user-images.githubusercontent.com/102448109/232549353-25dfdd9c-0b11-426c-8913-c5b4c2f7f11e.jpg)

Additionally, the custom form data doesn't get represented on the receipt

### What browser do you use?

firefox. 

### Additional information

Additionally to the Shop + cart config. If you use the product list only, the receipt looks as follows : 
![4](https://user-images.githubusercontent.com/102448109/232550574-02f862e3-2672-470a-924e-3d15c8286d09.jpg)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by c3piio** [comment]
> Additionally, the custom form data doesn't get represented on the receipt

Hello, the custom form data is not displayed on the receipt in version 1.9.2 although the cart details from the POS store are now displayed correctly. How can the custom form data be included on the receipt?

**Comment by Kukks** [comment]
> > Additionally, the custom form data doesn't get represented on the receipt
> 
> Hello, the custom form data is not displayed on the receipt in version 1.9.2 although the cart details from the POS store are now displayed correctly. How can the custom form data be included on the receipt?

Custom form data is not meant to be displayed on the receipt by default. However you can mirror entries from the form to the receipt by following the example at https://github.com/btcpayserver/btcpayserver/pull/4774#issue-1625306770

**Comment by c3piio** [comment]
> > > Additionally, the custom form data doesn't get represented on the receipt
> > 
> > 
> > Hello, the custom form data is not displayed on the receipt in version 1.9.2 although the cart details from the POS store are now displayed correctly. How can the custom form data be included on the receipt?
> 
> Custom form data is not meant to be displayed on the receipt by default. However you can mirror entries from the form to the receipt by following the example at [#4774 (comment)](https://github.com/btcpayserver/btcpayserver/pull/4774#issue-1625306770)

I tried mirroring more than the email address, but it threw an error: "Form config was invalid: Form contains duplicate field names 'receiptData_buyerEmail')"

If I want more than buyer email to appear on the receipt page, how should I modify your json code? The code that threw and error is here: https://github.com/btcpayserver/btcpayserver/pull/4774#issuecomment-1532270898 Do I need to include "name": "receiptData" for every field? I used it once and included all the fields below. It would be super helpful if you could show an example with two fields being mirrored, to know how to do it.
