### ISSUE TITLE
[Bug]: QR Code not rendering with invoice

### ISSUE THREAD

**Issue by dragon-foobar** [btcpayserver/btcpayserver#4898]
### What is your BTCPay version?

I'm running BTCPay Server v1.9.1 

### How did you deploy BTCPay Server?

I'm running the BTCPay Server on an Ubuntu headless machine manually.

### What happened?

When an invoice is generated, the 'Awaiting payment' bar and the amount display, but not the QR Code.

### How did you encounter this bug?

A customer notified me then I checked myself.

### What browser do you use?

LibreWolf (firefox). I'm not sure what the customer uses.

Have also tried on Chome with same results.

### Additional information

<img width="383" alt="Screen Shot 2023-04-21 at 3 39 19 pm" src="https://user-images.githubusercontent.com/129810153/233549742-b65fa245-40e8-44fa-b299-f76656c2c172.png">

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dragon-foobar** [comment]
Both my lightning node and full node appear to be working and synced.

**Comment by pavlenex** [comment]
Can you post console logs from your browser?

**Comment by dennisreimann** [comment]
Can you also check the logs on the invoice details page? I recently debugged a similar case and it was that the invoice couldn't get properly generated. No available payment method.

**Comment by pavlenex** [comment]
Closing as no info was provided, will open up if there's more updates
