### ISSUE TITLE
[Bug] Cannot create a payout to destination if one already exists for another store that is potentially not mine

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver#4899]
Damn, I think I found a design issue with Payouts. The API suggests they are store scoped (fetching is done using 1 pull payment ID or getting all for 1 store ID, canceling also requires a store ID or pull payment ID), but they are in fact not store scoped. I cannot create a payout to an address because one already exists for that address in another store (potentially a store that is not mine). I'm in a new project so I can manage, but this is an architectural issue people could run into.

Example: I need to get a refund from 2 stores so I try to enter my address in the pull payment form for each store. I know, address reuse is bad, but noobs exist.

This sounds like an edge case, but for my auto-forwarding plugin this makes the plugin single store only - which is fine, for now.

**Comment by woutersamaey** [comment]
Sorry but your AI-generated response is BS. What you propose is already implemented this way. Just not consistent because destinations are expected to be unique across all stores for a to me unknown reason.

**Comment by pavlenex** [comment]
@Kukks can you take a look?

**Comment by Kukks** [comment]
The same reasons still apply on an instance level. This is by design. The fix is users becoming more educated about address reuse. The workaround is maintaining payout amounts by canceling and recreating.
