### ISSUE TITLE
Add support for Ledger/Trezor Litecoin addresses (LTub and MTub)

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#49]
Trezor and Ledger use a different derivation scheme for generating xpub addresses. 

Ltub is used for legacy addresses, but Mtub is used for segwit addresses

More information: 
"Officially Litecoin uses the same BIP32 prefixes as Bitcoin (see here). This is on purpose, as it makes sense to generate addresses for multiple cryptocurrencies from a single master key.

The Ltub/Ltpv prefixes were independently made up by the author of the website bip32.org before BIP32 was even discussed by the Litecoin development team. As far as I know they were never officially supported, but unfortunately some developers who believed they were official used them in their software, contributing to the confusion."

**Comment by NicolasDorier** [comment]
closing, tracked on https://github.com/btcpayserver/btcpayserver/issues/66
