### ISSUE TITLE
modal false-positive btcpay.js

### ISSUE THREAD

**Issue by labrocca** [btcpayserver/btcpayserver#4901]
This is the 2nd time in 3 months that Avast (anti-virus) has false positive this file for me.  They removed it the first time but now this time they are saying it's a confirmed Malware.  

https://imgur.com/PNZwvIN

I have sent them more follow up but also contacting BTCpay dev's hoping they know what the problem is.   I assume they don't want their BTCpay installs triggering AV's.  

Any help is appreciated too.

**Comment by pavlenex** [comment]
Short story: 
I don't think there's anything we can do about it
Long story https://github.com/btcpayserver/btcpayserver/issues/2139

**Comment by labrocca** [comment]
I disagree. This is a project that's many years old.  If dev's contact Avast or any AV that flags them, they can get answers to why their being flagged as malicious and either change the code or change how the AV flags.  I think just shrugging and believing nothing can be done by Dev's is not going to work long-term.  If one AV flags you, then so can others, and eventually all AV's will flag you and no one will have working invoices.

**Comment by pavlenex** [comment]
I really wish we had capacity to do this, we're very small team focused on coding, we just cannot do these type of things, you're however free to help us and would be much appreciated, thank you.

**Comment by labrocca** [comment]
I'd be happy to try and advocate and contact AV's on behalf of the team.  Basically whatever it takes to keep BTCpay kicking butt as a free merchant payment solution.    I'd like to send Avast a contact that was more official.  What do you suggest?

**Comment by NicolasDorier** [comment]
Hey @labrocca thanks for contacting AV on our behalf. If they ask you can use `security@btcpayserver.org`.

**Comment by labrocca** [comment]
After some back and forth I think they have permanently solved this.  At least that's what they are telling me.

**Comment by dennisreimann** [comment]
@labrocca nice, thanks for the effort!
