### ISSUE TITLE
[Bug]: can't register new account

### ISSUE THREAD

**Issue by ArmanTheParman** [btcpayserver/btcpayserver#4915]
### What is your BTCPay version?

1.9.1

### How did you deploy BTCPay Server?

downloaded repo from git
build on home Linux server

### What happened?

I deleted my test store, but the whole account got deleted; wasn't paying attention at 5am.
Not sure if I was warned or if just foggy brain, BUT...

Now I can't register a new account. I only have options to sign in or forgot password. The register
new account link doesn't exist.

### How did you encounter this bug?

As above.

### Relevant log output

```shell
none
```

### What browser do you use?

Firefox

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Heya, this is not a bug, you can reset your password here https://docs.btcpayserver.org/FAQ/ServerSettings/#forgot-btcpay-admin-password

**Comment by pavlenex** [comment]
You need to reset your admin account, and then enable registration for new users in server settings > policies if you want users to be able to sign up.

**Comment by ArmanTheParman** [comment]
Hi Pav,
I'm having trouble; can you point me in the right direction?
The link you gave probably works fine for docker, but I've built btcpay
directly with build.sh
Got it working in my own docker container with postgres, dot net, NBXplorer
all together.
Got the website working at port 23001, except, no button to register first
user.
The link you sent suggest to change to do this...

sudo su -
cd $BTCPAY_BASE_DIRECTORY/btcpayserver-docker/
# Re-open registrations
./btcpay-admin.sh reset-server-policy


but that directory does not exist, cant locate btcpay-admin.sh with

cd my_btcpay_dir
find ./ -name "btcpay-admin.sh"

any help is much appreciated.
Thanks
Arman
