### ISSUE TITLE
[Bug]: Checkout V2 addresses are cut off

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#4919]
### What is your BTCPay version?

BTCPay Server v1.9.1+d738f797e

### How did you deploy BTCPay Server?

docker

### What happened?

When using a checkout V2 addresses both on chain and bolt 11 are truncated in a way it doesn't really allow for easy way to verify it.

![Screenshot 2023-04-26 at 12 21 06](https://user-images.githubusercontent.com/36959754/234547392-4d9b4d60-a261-4367-9b82-ace47fd8fd77.png)

### How did you encounter this bug?

When using checkout v2
1. Create an invoice
2. Go to checkout

### What browser do you use?

Safari Version 16.3 (18614.4.6.1.6)

### Additional information

I propose we do something like this instead 
![Screenshot 2023-04-26 at 12 15 37](https://user-images.githubusercontent.com/36959754/234547101-aa8f84e0-426c-49bc-8010-e67709a061aa.png)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Bootman44** [comment]
When I go to copy. The it won't work to put in the address bar

**Comment by pavlenex** [comment]
Hmm that looks good to me @dennisreimann, how do you feel about it? Do you have any concerns about the way it's displayed atm? To me what you shared looks good, but I assume there may be some scenarios where this shouldn't be done, that I haven't considered?
