### ISSUE TITLE
[Bug]: Link to Shopify Plugin missing

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#4945]
### What is your BTCPay version?

BTCPay Server 1.9.2

### How did you deploy BTCPay Server?

docker

### What happened?

The link to the shopify settings is missing in the UI. 

### How did you encounter this bug?

Tried to find the link to shopify but it is gone. Url still accessible though.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Yappadappa** [comment]
> ### What is your BTCPay version?
> 
> BTCPay Server 1.9.2
> 
> ### How did you deploy BTCPay Server?
> 
> docker
> 
> ### What happened?
> 
> The link to the shopify settings is missing in the UI. 
> 
> ### How did you encounter this bug?
> 
> Tried to find the link to shopify but it is gone. Url still accessible though.
> 
> ### Relevant log output
> 
> _No response_
> 
> ### What browser do you use?
> 
> _No response_
> 
> ### Additional information
> 
> _No response_
> 
> ### Are you sure this is a bug report?
> 
> - [X] I confirm this is a bug report

Payment
