### ISSUE TITLE
[Bug]: Zpub converted to Xpub, addresses not the same, funds not seen by wallet

### ISSUE THREAD

**Issue by c3piio** [btcpayserver/btcpayserver#4953]
### What is your BTCPay version?

v1.9.2+6193835ea

### How did you deploy BTCPay Server?

LunaNode One Click

### What happened?

I imported a zpub into btcpayserver. The addresses matched when confirming. Funds sent to btcpayserver do not appear in electrum, and when generating a new receiving address in btcpayserver, they no longer match with electrum.

### How did you encounter this bug?

1. I imported a wallet into btcpayserver by entering the extended public key. 
2. My wallet is Electrum Android. I pasted the zpub into btcpayserver.
3. When asked to confirm the addresses, they all matched with the addresses showed in Electrum Android.
4. Click confirm.
5. **Btcpayserver now shows the derivation scheme for the wallet as xpub (not zpub).**
6. When clicking receive / generate next available BTC address, the address no longer matches what Electrum shows.
7. Funds that have been sent to btcpayserver are not visible in Electrum.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Can you check on the wallet settings page, whether or not the account key data matches what you have in Electrum?

![grafik](https://user-images.githubusercontent.com/886/236524968-6f5cf3ad-68dd-4361-ba1d-5eab0cb13b0c.png)

Can you also ensure that this is not a [gap limit problem](https://docs.btcpayserver.org/FAQ/Wallet/#the-gap-limit-problem)?

**Comment by pavlenex** [comment]
It's been 2 weeks, closing tihs one until further info is provided, then we can troubleshoot

**Comment by c3piio** [comment]
Hello, sorry for not getting back to you earlier.

In Electrum, the master public key in Electrum begins with zpub6n... When I import the wallet into BTCPayServer with this zpub, it displays addresses, which all correspond with Electrum. After saving and going to the wallet settings, the account key says xpub68.... There is a balance in the wallet according to BTCPayServer. According to Electrum, there is no balance. Also, the addresses generated by BTCPayServer no longer match what Electrum generates. This happens after saving the wallet. 

You can try it yourselves by making a standard Electrum wallet with 12 seed words. Import the zpub into btcpayserver, see the addresses matching, zpub now displayed as xbpub in btcpayserver, addresses no longer matching. 

I made a payment earlier via BTCPayServer and when I load that transaction id into Electrum, it says "transaction unrelated to your wallet".

I don't know if it matters, but Electrum's seed words aren't compatible with most wallets, such as Wasabi. Is there perhaps some conflicting logic due to this?

**Comment by c3piio** [comment]
Is the above info sufficient for troubleshooting? The issue is reproducible as noted above:

> You can try it yourselves by making a standard Electrum wallet with 12 seed words. Import the zpub into btcpayserver, see the addresses matching, zpub now displayed as xbpub in btcpayserver, addresses no longer matching.

**Comment by pavlenex** [comment]
I think you're having either a gap limit problem (there's info in docs how to address it) or you misconfigured the step after the xpub pasting, imo it's now much easier to just import wallet file rather than xpub. https://www.youtube.com/watch?v=kf3BHaQWSAc it ensrues all other stuff is imported and the same, not just the xpub.

**Comment by c3piio** [comment]
> I think you're having either a gap limit problem (there's info in docs how to address it) or you misconfigured the step after the xpub pasting, imo it's now much easier to just import wallet file rather than xpub. https://www.youtube.com/watch?v=kf3BHaQWSAc it ensrues all other stuff is imported and the same, not just the xpub.

Hello, the gap limit was the problem. You can mark it as solved. The docs had a good guide for how to increase it here: https://docs.btcpayserver.org/FAQ/Wallet/#the-gap-limit-problem
