### ISSUE TITLE
[Bug]: ToolTip causes glitching when scrolling down on mobile

### ISSUE THREAD

**Issue by MarnixCroes** [btcpayserver/btcpayserver#4956]
### What is your BTCPay version?

idk

### How did you deploy BTCPay Server?

-

### What happened?

https://user-images.githubusercontent.com/93143998/236450904-05362b4f-c796-4196-98d3-1333573371c8.mp4

Normal scrolling works, but when you click the tooltip, the tooltip is not fully displayed and when you scroll it glitches back all the time.
I had a longer video, but can only upload 10MB.

### How did you encounter this bug?

click the `i` to display the tooltip

### What browser do you use?

Vanadium

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
@dennisreimann can you check this one please?
