### ISSUE TITLE
[Bug]: Create user API - password length

### ISSUE THREAD

**Issue by strnly** [btcpayserver/btcpayserver#4975]
### What is your BTCPay version?

I'm running BTCPay Server v1.9.3 on a VPS. 
CLN implementation.

### How did you deploy BTCPay Server?

VPS

### What happened?

I noticed that when using [CreateUser]https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Users_CreateUser
We cannot pass any password above 12 characters. 
It does seem to create an account in BTCPay Server, but does not allow for authentication to then create an API key for that user. Even after creating the user, when trying to Create New API Key (https://docs.btcpayserver.org/API/Greenfield/v1/#operation/ApiKeys_CreateApiKey) we get Authentication is required to access that endpoint. 

And we noticed it does so only after creating a user with more than 12 characters in the password. 

### How did you encounter this bug?

See above. A user tried to create a BTCPay account via API, using a long password, and then could not create the API key to set up his store and wallet. 

### What browser do you use?

Did so on Safari, Brave and Chromium

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
@ndeet can you take a look at this one?

**Comment by ndeet** [comment]
@strnly Are you sure it only fails with 12 chars passwords and not lower too? I used the Create User api you mentioned to create an user with a 20 char password (using admin API key). After that I successfully used the [Create a new API Key for User](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/ApiKeys_CreateUserApiKey). I could also successfully logged in BTCPay and created an API key via the UI.

Note: the endpoint you mentioned above is not the same, [Create API Key](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/ApiKeys_CreateApiKey) is only used for the currently used API key. E.g. if you send the request with the Admin API key you will create another API key for the Admin user and not for the new user you created before. To do this you need the "Create a new API Key for User" endpoint I mentioned above. Note that you here pass the Admin API key in the request too, not the user password.

Was there a misunderstanding in the API or can you give more details how I can reproduce? I used BTCPay v1.10.1

**Comment by ndeet** [comment]
fyi, I also tried with this 60 char password and it worked too `NrxTE4TdvP9TNJ7NjEhTP3sLMZ#zoLdMzT!Y6!Pt&aYkQmm%qdD6nR^B^&f8`

**Comment by strnly** [comment]
It failed only with 13 characters or more via API. 
No issue via UI. 
We did it for Create a new API Key for User.

**Comment by pavlenex** [comment]
@ndeet can you verify the above please?

**Comment by ndeet** [comment]
@dennisreimann thank you for confirming it works as expected

@pavlenex my results are the same see https://github.com/btcpayserver/btcpayserver/issues/4975#issuecomment-1597737105
