### ISSUE TITLE
[Bug]: loop invoice_paymentSettled

### ISSUE THREAD

**Issue by hell0-w** [btcpayserver/btcpayserver#4978]
### What is your BTCPay version?

BTCPay Server v1.9.3+781190a65

### How did you deploy BTCPay Server?

https://install.btcpayserver.org/

### What happened?

After update from v.BTCPay Server v1.7.5+372df93c1 to new version BTCPay Server v1.9.3+781190a65

For now I have 3 invoices with this issue.
Sends status in loop that invoice_paymentSettled 

![image](https://github.com/btcpayserver/btcpayserver/assets/17591751/21fa4e7b-14fd-48e5-9abb-4f68417601cf)
![image](https://github.com/btcpayserver/btcpayserver/assets/17591751/ce51fa4b-3453-4fac-847a-aa0ddef1ff0b)

How to solve it? 

Thanks.

### How did you encounter this bug?

web hook sends in loop that invoice_paymentSettled 

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
Checking the timestamp, the interval seems random. Wondering if that's a bug or just somebody sending multiple payments.

**Comment by hell0-w** [comment]
> Checking the timestamp, the interval seems random. Wondering if that's a bug or just somebody sending multiple payments.

I have cases where users send money to the same wallets, sometimes I have to do a scan to find utxo.

the option (Invoice expires if the full amount has not been paid afterwards) is checked - 1440 value, the payments come to the same invoice even after expires  ) -  previous versions BTCPay it's now work like that. 

in this case it's not clear to me. 

maybe:
if the invoice has already expired for one address (paid or not), after new sending founds to same address, the system creates new invoice. but falls into a loop. !?

**Comment by NicolasDorier** [comment]
so are you sure it is a loop and not just paying again same address?

**Comment by NicolasDorier** [comment]
I believe my server is experiencing this issue. On it.

**Comment by NicolasDorier** [comment]
So on my server, this is caused by somebody havign setup 1900 webhooks to the same store...

**Comment by NicolasDorier** [comment]
@hell0-w can you check how many webhook your registered to your store?

**Comment by hell0-w** [comment]
@NicolasDorier 
Checked I have one webhook. 
Status of invoice  - Invalid shows in 3 days after. 

![image](https://github.com/btcpayserver/btcpayserver/assets/17591751/21fa70bb-e76f-4715-920b-72d55f1f79e8)
![image](https://github.com/btcpayserver/btcpayserver/assets/17591751/6a777d13-4a42-4b17-9a00-5b8f0004d6bc)
![image](https://github.com/btcpayserver/btcpayserver/assets/17591751/f7de6f16-7c7b-40c8-b31a-bf815f613d8e)

**Comment by NicolasDorier** [comment]
@hell0-w I believe the issue is that somebody is sending money to the same address over and over. Everytimes this address receive money, a webhook is sent. Can you check your on-chain wallet to see if you aren't receiving anything?

**Comment by hell0-w** [comment]
@NicolasDorier checked yesterday, All works fine now. 
Thanks
