### ISSUE TITLE
[Bug]: After deleting a store, the webhooks aren't deleted

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#4979]
### What is your BTCPay version?

1.9.3

### How did you deploy BTCPay Server?

docker

### What happened?

When remove a store, the data concerning webhooks aren't deleted.

### How did you encounter this bug?

Create store, have webhook, delete store.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
not fixed nope

**Comment by driquelme** [comment]
I wanted to pick up this, but it's fixed [here](https://github.com/btcpayserver/btcpayserver/blob/0a0cf97c55ae978c7a2c68fcdb17610330ae3391/BTCPayServer/Services/Stores/StoreRepository.cs#L515).

**Comment by pavlenex** [comment]
@NicolasDorier can you confirm this one was fixed as @driquelme mentions ^

**Comment by NicolasDorier** [comment]
@driquelme  mmh you seem to be right, I'll take a look tomorrow. I don't remember I fixed it...

**Comment by NicolasDorier** [comment]
You are right, damn didn't remember that.
