### ISSUE TITLE
No clear documentation on how to use c-lightning.

### ISSUE THREAD

**Issue by thestick613** [btcpayserver/btcpayserver#498]
I want to connect to a c-lightning node on a different server, so i can't use the lightning-rpc file. The docs say that i should try something like this:

`type=clightning;server=tcp://1.1.1.1:27743/`

Should i put my c-lightning ip and port in there? I don't think so. I've tried it anyway, but i get this error

`Error: The lightning node did not replied in a timely maner`

What exactly should listen on that port? Maybe a HTTP interface which connects to my c-lightning node?

I've used c-lightning several times, and i know i've set it up correctly.

**Comment by bitcoinshirt** [comment]
Just to be clear, you're trying to use an external lightning node with your BTCPay?

**Comment by thestick613** [comment]
Yes, my own lightning node, which is located on a different server.

**Comment by NicolasDorier** [comment]
```
I want to connect to a c-lightning node on a different server, so i can't use the lightning-rpc file. The docs say that i should try something like this:
```

This is actually if you use `socat` to forward linux socket to TCP socket. Don't do this, this is unsecure. On production, keep c-lightning on the same server.
