### ISSUE TITLE
[Bug]: BTCPay Server: Top 10 Mistakes in Bitcoin Financial Application Code

### ISSUE THREAD

**Issue by onlineapps-cloud** [btcpayserver/btcpayserver#4982]
### What is your BTCPay version?

last version

### How did you deploy BTCPay Server?

from source code

### What happened?

found 10 errors

### How did you encounter this bug?

long to explain

### Additional information

hi on habr.com, guys from pvs-studio analized btc pay server code and found 10 erros, in link you will find all relevand info. best regards.
https://habr.com/ru/companies/pvs-studio/articles/735726/

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Thanks for notifing us about this! We're on it, fixing in #4983

**Comment by NicolasDorier** [comment]
Seems a good static analyzer, if we could integrate that to our CI we would do
