### ISSUE TITLE
Accessibility Testing: Paid Invoice, Pull Payment, Create Invoice: Tested on Windows

### ISSUE THREAD

**Issue by mouxdesign** [btcpayserver/btcpayserver#4986]
Hey team,

Thanks for joining us today on the accessibility kick off call. Tested the following screens:
- Paid Invoice
- Pull Payment
- Create Invoice

Pretty much just enabled the voice over feature for windows and tested by clicking on various aspects of the UI.  
Video walkthrough of how it was tested here; https://www.loom.com/share/eb2c9eb030f24528a3dbc3e14abb01ad

I used some blue and yellow color coding so that it's a quick and easy reference. Most items were labelled, just a few items here and there where it might be helpful to edit or add in labels. Hope this is helpful and if there's any questions feel free to ask. 

![Group 3](https://github.com/btcpayserver/btcpayserver/assets/90313394/3dfa8145-1001-47d1-b25f-5eec859af7dc)

![Group 1 (4)](https://github.com/btcpayserver/btcpayserver/assets/90313394/05fbdafc-774c-4816-805b-5f25a3609ceb)
![Group 2 (4)](https://github.com/btcpayserver/btcpayserver/assets/90313394/21841b66-4c5a-4545-9f4e-050f1aecbab4)

**Comment by pavlenex** [comment]
Thanks for posting this @mouxdesign!

We'd go through video and log these issues as a task-list here, then proceed with tackling them 
cc @Bas02 & @petzsch

**Comment by dstrukt** [comment]
Thanks for the review and breakdown @mouxdesign!

🚀

**Comment by Fahadshahzad797** [comment]
Did any tell how to use this app without pay

**Comment by Spenda9** [comment]
I've tried everything to get my bitcoin payment and now for some reason I am here?

**Comment by dennisreimann** [comment]
@mouxdesign Can you elaborate on what it means that a label is missing or needs improvement? For instance, how would the "Paid invoice" screen be improved and what needs to be changed in terms of HTML? If you could provide a link for guidance, that would also be fine — I'm just struggling to see what needs to be changed concretely, as the spots you marked seem to be "labels" already.

**Comment by dennisreimann** [comment]
@mouxdesign Can you help me understand what to do exactly? (See my previous comment)

@pavlenex Let's put this into the backlog until we clarify the actual TODOs.

**Comment by mouxdesign** [comment]
Sure!

The labels on the paid invoice screen as an example:

Labels are the way that the screen reader would read the text to a blind/visually impaired person.

On the invoice paid screen:
The label for Invoice ID would read Invoice ID. This is the aria label on the html side of things.

![using-aria-label-identif-89ed5dcc8c595](https://github.com/btcpayserver/btcpayserver/assets/90313394/8a0e7ac6-6b96-4dcc-850e-92056dfa0c5d)

So its pretty much ensuring that those aria labels are relevant and directly connected to the text there itself.

Imagine that a person cannot see the text on the screen so when they hover over each element, the element itself reads out very succiently what it is. 

- View reciept: The aira text would read "view reciept"
- Return to developer wallet: The aria text would read "return to developer wallet" 

Hope this is helpful, feel free to shoot over any questions will do my best to help! If you like feel free to send a screen shot of the html of for example the paid invoice screen and then together we can look at the labels.

**Comment by pavlenex** [comment]
@dennisreimann There's some work by @TChukwuleta done here https://github.com/btcpayserver/btcpayserver/pull/5452

**Comment by dennisreimann** [comment]
@pavlenex I saw that, yet it doesn't address what's described here.

**Comment by TChukwuleta** [comment]
Hello @dennisreimann  

I made an update to the PR, for the different things that was pointed out in terms of accessibility and labelling.

Please kindly review.

**Comment by mouxdesign** [comment]
Just circling back to this one:

<div>
    <dt id="dt_invoice_id">Invoice ID</dt>
    <dd aria-labelledby="dt_invoice_id">9AgMUeAYBJbSt3xxcHGdSV</dd>
</div>


The aria label here would describe the text as best as possible to the user. So in this case "invoice id" would also be ok. The voice reader will read out "invoice id".

Then for the button labels.
The buttons would have their own additional labels called aria labels. Like this:
![Screenshot 2024-02-02 125156](https://github.com/btcpayserver/btcpayserver/assets/90313394/f4c202f8-87ed-4268-b162-9a7830dfeafc)

Would the text "view buttons" be readable there by a screen-reader? I am not a programmer and so hard to tell how a users device will read out the text. To my knowledge if the code does not contain the word "aria label" then the screen reader of the users computer does not recognize it as text that it should read out. Hope that makes sense.

**Comment by Megoy-Tambayan** [comment]
hey
