### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by learntheropes** [btcpayserver/btcpayserver#5000]
### What is your BTCPay version?

BTCPay Server v1.9.3+781190a65

### How did you deploy BTCPay Server?

On lunanode using their installation script.

### What happened?

Greenfield api, under the payment methods endpoint, always returns 0 as the network suggested fee for on-chain payment.

Btcpay Server checkout page suggests a more accurate value (e.g. 58.944 sat/byte) for the same invoice.

Tested with a medium speed confirmation policy.

### How did you encounter this bug?

1. Generate an invoice
2. Call the invoice payment methods endpoint for the same invoice
3. Check the `networkFee` property for the on-chain payment method and verify that is always 0
4. Open the checkout page for the same invoice and notice a more appropriate value in sat/byte

### What browser do you use?

Postman

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Kukks** [comment]
This is not the suggested network fee, but part of a separate feature: https://docs.btcpayserver.org/FAQ/Stores/#add-network-fee-to-invoice-vary-with-mining-fees
