### ISSUE TITLE
Improve create a first store view

### ISSUE THREAD

**Issue by Bas02** [btcpayserver/btcpayserver#5008]
Yoo 

I just noticed the new intro to creating your first store. 
![btcpayformbuilder11](https://github.com/btcpayserver/btcpayserver/assets/102448109/1bde4365-b339-4c1f-8a7c-4f2f7fcf0cb7)

It feels very empty and should be properly thought out. 
To me it seems like context is missing for one who creates their first BTCPay Server now.

Maybe we should update this " First store Wizard ", center the creation, and have a little more context textually? 
Again, to me currently, it feels very empty and non explanatory of what a store is gonna do for me at this point.

**Comment by pavlenex** [comment]
Agreed, especially on a larger screen it looks a bit weird. Let's tag this one for the next major release after we're done with 1.1.11.
