### ISSUE TITLE
[Bug]: Rename existing LNBank Wallet

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#5009]
### What is your BTCPay version?

1.10.0-rc1
LNBank: 1.5.1

### How did you deploy BTCPay Server?

docker

### What happened?

https://github.com/btcpayserver/btcpayserver/assets/1374810/3cbcec6f-9abf-4f09-89d6-5bcae31cc87e

### How did you encounter this bug?

see above

### Relevant log output

```shell
none
```

### What browser do you use?

Firefox

### Additional information

none

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Will be fixed in LNbank v1.5.2 — thanks for reporting!
