### ISSUE TITLE
Error while connecting to the lightning node via <my external IP>:9735 (The operation was canceled.) 

### ISSUE THREAD

**Issue by jarole** [btcpayserver/btcpayserver#501]
Hello, 
I try to set up lightning network (lnd 0.5.1) in my store . BTCpay server is on the same machine as lnd and bitcoind. No docker.

I am getting this error:
`Error: Error while connecting to the lightning node via <my external IP addr>:9735 (The operation was canceled.) `

I don't know why it connects to my external IP (what is of course not reachable from LAN) if I have localhost (127.0.0.1) configured in the connection string:

`type=lnd-rest;server=https://127.0.0.1:8080/;macaroonfilepath=/home/user/.lnd/data/chain/bitcoin/mainnet/admin.macaroon;certthumbprint=123456abcdefgh`

My lnd.conf is configured:
```
listen=0.0.0.0:9735
restlisten=127.0.0.1:8080
rpclisten=127.0.0.1:10009
tlsextraip=127.0.0.1
externalip=<my external IP addr>

```

Do you have some idea for a reason or workaround? Any help very appreciated.

PS: Communication with lnd API works fine for me with this python script:
```
import base64, codecs, json, requests
url = 'https://localhost:8080/v1/getinfo'
cert_path = '/home/user/.lnd/tls.cert'
macaroon = codecs.encode(open('/home/user/.lnd/data/chain/bitcoin/mainnet/admin.macaroon', 'rb').read(), 'hex')
headers = {'Grpc-Metadata-macaroon': macaroon}
r = requests.get(url, headers=headers, verify=cert_path)
print(r.json())
```

**Comment by jarole** [comment]
**More details:**

when I disable external IP in lnd.conf I got
`Error: Error while connecting to the API (Lnd External IP not set, make sure you use --externalip=$EXTERNALIP parameter on lnd) `

when I set `externalip=<my LAN IP addr>` It works :) But my node is not visible for others who want open a channel with me.

**Comment by jarole** [comment]
related topic:
NAT=true not working
https://github.com/lightningnetwork/lnd/issues/2008

**Comment by NicolasDorier** [comment]
`externalip=` must be your public internet address. I think you should not try to setup things by yourself if you don't know what that mean (except if you want to learn, but I can't hand hold you).

https://medium.com/@BtcpayServer/launch-btcpay-server-via-web-interface-and-deploy-full-bitcoin-node-lnd-in-less-than-a-minute-dc8bc6f06a3

**Comment by jarole** [comment]
`externalip=` is  set to my public internet address, that is the point of the report. 
When I am configuring stores>(store) settings> lightning node modify>test connection I got the error mentioned. 

Setting up my LAN address as `externalip=192.168.0.2` is just workarround which makes it working, because it pass the configuration wizard. Then BTCpay server connects to my LNd node. Also LN payments work fine.

**Comment by NicolasDorier** [comment]
The error mentioned is probably NAT or firewall not properly configured on the machine running the lightning node.

**Comment by NicolasDorier** [comment]
Ah I remember as well. Sometimes people can't access access his own public ip from his home network. Have you tried to connect to your lightning node from outside your home networK?

**Comment by jarole** [comment]
Yes. I can open channel from outside or connect to gRPC. But BTCpay server is on the same machine so I have not tested it.
I don't understand why BTCpay server depends on `externalip` while connecting to my localhost node, especially if 127.0.0.1 is set in connection string.

-------- Original Message --------

**Comment by NicolasDorier** [comment]
btcpay does not depends on `externalip`. People who will want to connect to your c-lightning node to send you payment does. If the error you get is only on the `Test connection`, you can ignore it people can still open a channel with you.

You need to open lightning network ports on your NAT.

**Comment by jarole** [comment]
To make btcpay working in my environment and to have a correct `externalip` advertising by my lnd, I have done a "little hack" following  these steps:
1. Add `/etc/hosts` entry with my my local IP addr `192.168.77.88` to `ln.mydomain.com`
2.  set `externalip=ln.mydomain.com` in my `lnd.conf` (so both services - BTCpay and lnd are resolving` ln.mydomain.com` to my LAN IP `192.168.77.88`)
3.  start lnd, NBxplorer, BTCpay 
4.  Configure Lightning Payments in my BTCpay store _stores >(store) settings > lightning node modify>test connection_
5.  Test passed with msg like 

> ...sucessfully connected to node 030abcd..@192.168.77.88:9735

6.  In this phase, my node is advertising my local IP what is wrong. So I had to change `/etc/hosts` back and comment out the entry which resolves `ln.mydomain.com` to my LAN ip `192.168.77.88`
When the node will be asked for `externalip=ln.mydomain.com` it will return my external IP because of DNS resolution and no more entry in `/etc/hosts`
7.  No restart is needed, my node is now visible on `1ml.com` or `explore.casa` with my external IP
8. BTCpay is working, channels and LN payments work like a charm.

Sorry for spam, but I'd like to document this behavior of btcpay as detailed as possible. You say that btcpay does not depend on `externalip` , but I have experienced that btcpay works different with different `externalip` configured in lnd.  Offcourse my lightning port is open (9735). Otherwise I would not be able to open a channel with the node.
I can close this issue, but I want to summarize it for people struggling with similar issues. Perhaps somebody finds this usefull somehow.

Thank you for your time and work so far!

**Comment by NicolasDorier** [comment]
@jarole I think you are over complicating.

You said that before, it was giving you this:
```
Error: Error while connecting to the lightning node via <my external IP addr>:9735 (The operation was canceled.)
```
I guess you talk about the `Test connection` right?
If so, it happen that commercial ISP does not allow to connect to your own router via its public IP.
If that's the case and people still can create a channel with you, just use the local network IP inside the connection string in BTCPay settings, check that you can create invoice, and you just ignore the error.

I think your node would have still been visible on `1ml.com` or `explore.casa`, it just takes time to appear.

**Comment by jarole** [comment]
Yes, I talk about `Test Connection` .  
You are right, Now I understand.
I can Submit the configuration regardless the Test failed :) I thought if Test fails, configuration will not be working. Perhaps the Test confused me too much.
Sorry for complications.   :)
