### ISSUE TITLE
I didn't get paid

### ISSUE THREAD

**Issue by Redone84** [btcpayserver/btcpayserver#5014]
I haven't been paid yet I don't know what happened https://mempool.space/address/bc1pu0wh7s0576nluv4v4rj3evhvtdsh9875q0u3w4c5jm9m9xu5q0xqdan32m.    This is the address for the person

**Comment by pavlenex** [comment]
You should contact your merchant, if a merchant is giving you free bitcoin, it's a scam 

https://blog.btcpayserver.org/bitcoin-bonus-scam/

**Comment by Redone84** [comment]
> You should contact your merchant, if a merchant is giving you free bitcoin, it's a scam
> 
> https://blog.btcpayserver.org/bitcoin-bonus-scam/

No I'm not getting it for free
