### ISSUE TITLE
[Bug]: RC2 Sidebar navigation (Switch Store) takes me to invoice list, not to Dashboard

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#5015]
### What is your BTCPay version?

BTCPay Server v1.10.0+215a36e7a (RC2)

### How did you deploy BTCPay Server?

Docker

### What happened?

When viewing the dashboard of "Pav's Storea", I clicked in the top left corner on the store list and chose "petzsch's teststore". Now instead of landing on the my dashboard, it took me to the invoice list.

Compared this behaviour with what we had in 1.9.3 it's definitly a change.

### How did you encounter this bug?

see above

### Relevant log output

```shell
none
```

### What browser do you use?

Firefox

### Additional information

none

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Good catch, this is def a weird and unexpected, I'd expect to land on a dashboard.

**Comment by dennisreimann** [comment]
I think it's also related to the roles changes. I can take a look!
Based on the user's role we redirected either to the dashboard (owner) or the invoices list (guest) – I assume that got lost.
