### ISSUE TITLE
[Bug]: Checkout v2: metadata.itemDesc is not visible

### ISSUE THREAD

**Issue by AbsurdlySuspicious** [btcpayserver/btcpayserver#5023]
### What is your BTCPay version?

BTCPay Server v1.9.3+781190a65 (Altcoins) 

### How did you deploy BTCPay Server?

Docker

### What happened?

In api docs, in section about create invoice method, `metadata.itemDesc` field is described as follows:
>  [...] This information is included in the CSV invoice export feature and appears in the invoice details view.

It is indeed shown in v1 checkout, but not in v2. No product info is shown at invoice page at all which may be confusing for buyers. 

### How did you encounter this bug?

1. Uncheck classic checkout in store settings
2. Make invoice via api with `metadata.itemDesc` field specified 
3. Proceed to checkoutLink from response

### Additional information

I'm not sure if `metadata.posData` should also be shown there (doc description makes me believe so) but it is also not visible on v2

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
@AbsurdlySuspicious is tthis still the issue with btcpay 1.13.3?

**Comment by dennisreimann** [comment]
@pavlenex Yes it is, I posted a PR with a fix and containing more info.
