### ISSUE TITLE
[Bug]: NFC payment does not work from some browsers.

### ISSUE THREAD

**Issue by JeanlChristophe** [btcpayserver/btcpayserver#5037]
### What is your BTCPay version?

I'm running BTCPay v1.9.3

### How did you deploy BTCPay Server?

Docker

### What happened?

NFC payment does not work from some browsers.

Some of our users wanted to use NFC payment. However, it's impossible to use this function if the PoS is opened from Vanadium or Brave browsers. The button loads indefinitely. However, it works fine with Google Chrome (unfortunately).

### How did you encounter this bug?

1. Open PoS on Vanadium or Brave browser
2. Select an item
3. Click on 'Pay'

### What browser do you use?

Vanadium
Brave

### Additional information

![Screenshot_20230603-094844](https://github.com/btcpayserver/btcpayserver/assets/46056211/6860b87c-be22-4497-9dfa-5dc388b37509)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Kukks** [comment]
Only edge and chrome support nfc.
