### ISSUE TITLE
Withdrawal

### ISSUE THREAD

**Issue by Estebancriger** [btcpayserver/btcpayserver#5042]
### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/4526

<div type='discussions-op-text'>

<sup>Originally posted by **Jacknyams** January 13, 2023</sup>
Am anable to withdraw my coins how do I goabout it</div>

**Comment by petzsch** [comment]
Please read to understand why this is a scam:
https://blog.btcpayserver.org/bitcoin-bonus-scam/
