### ISSUE TITLE
Request Buyer Address

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#505]
Since we support storing buyer info in the invoice, we should allow a store owner to input the address of a buyer through the invoice UI. Furthermore, we should also have a "Request Address By Email" button, which sends an email to the buyer and links him to a form which requests their address. Upon submission, form updates the invoice Buyer fields. 

The use-case here is specifically for the crowdfund app but I'm sure it could easily be reused. 
* User contributes via a perk, let's say a pair of socks for 0.1BTC
* Store owner sees invoice with perk and clicks on "Request Address By Email"
* Store owner is notified, checks invoice and ships socks to address listed down.

I'm not 100% certain if this is the right way to go. Suggestions welcome.

**Comment by bitcoinshirt** [comment]
Agreed, I've seen people use PoS app to sell things online, like an e-store, and since those fields are already available in invoice, I don't see why not.
There's definitely a use-case here. 

However, storing address and e-mail address can potentially require some sort of data retention mechanism. Store data for x amount of days then anonymize or delete, or delete on request. I opened issue earlier for this but there hasn't been much interest #347

**Comment by slack333** [comment]
Hi guys, I'd made a Pos app, for an inbound LN liquidity service. The customer need to fill out some info like node info. When the user click buy could show a popup or and extra plane text area appears or something? That info could appear in the invoice after the customer pays.
This info area could be great for small web bussineses that cannot do big web stuff.

Thank you guys for all the work you are providing to the world.

**Comment by pavlenex** [comment]
Okay so besides standard format + notes field or custom message, we should also have an easy way for them to get e-mail notification that there is an order through store SMTP.

![serveimage](https://user-images.githubusercontent.com/36959754/53678658-a8832600-3cc2-11e9-8dae-78b3b8bc1791.png)

**Comment by ascisco** [comment]
This feature should definitely be added for people hosting their own store front via BTCPay. The invoice summary already has address fields listed right alongside customers email.

**Comment by beeforbacon** [comment]
With the new layout of btcpay, and the continuing demand for sovereign bitcoin payments, this is the missing link that can make btcpay a native commerce platform. I look forward to the ability to get shipping info before invoice is generated at my btpcay-native webshop.

**Comment by Kukks** [comment]
I think we can build a plugin for this easily now. I'll add it to my list of things to prototype after 1.5 release.

**Comment by pavlenex** [comment]
@Kukks @beeforbacon expressed the desire to code it as well, so perhaps you can just provide some guidance. Not really sure it needs to be a plugin, it's quite a core functionality, but whatever it takes as long as it's in, as people have been requesting this for so long.

**Comment by dstrukt** [comment]
ACK to core functionality, but agreed, def a feature people would love to see!

**Comment by orangesurf** [comment]
I would love to see this. 100,000 sat bounty from me.

Additional 100,000 sat bounty for an option to automatically purge shipping information & contact email after a customizable time after payment.

For background I currently have a website (VPS running ghost), and use a btcpayserver POS (self hosted) with a reverse tor proxy (VPS) for a donation page subdomain.  I would rather not set up another website (wordpress+woo) just for collecting shipping information.

**Comment by pavlenex** [comment]
#4137

**Comment by orangesurf** [comment]
Bounty Paid
