### ISSUE TITLE
[Bug]: For POS Plugin, Receipt Contains Redundant  OrderID Link to POS App

### ISSUE THREAD

**Issue by yuriygeorge** [btcpayserver/btcpayserver#5054]
### What is your BTCPay version?

I'm running BTCPay 1.10.0

### How did you deploy BTCPay Server?

manual

### What happened?

I'm running BTCPay v1.10.0
I have created a POS Plugin App - For example (https://btcpay.kapitalex.com/apps/2kXpfKAZfBxzU3J34wmmQfjfD9T5/pos)

And generated an invoice, and the invoice has been paid. When I send the receipt to the buyer:
https://btcpay.kapitalex.com/i/3aYoYz8R9jmsFTqjgASpVF/receipt

It contains an Order ID, automatically generated by BTCPay, with a link to the POS app.
I think this is a bug. Because I don't want the buyer to have access/Link to the Store's POS plugin.

Also, this Order ID is copied over and over again for all invoices. So even if it was some Order ID, it is not uniquely generated. 
We would like this Order ID to be blank by default. Or at the very least, can it not include a private link to the POS Plugin?

One solution would be for us to call the API later and to update all invoices to remove such Order ID's. 

But, I believe this is a bug, it should
1) not include the POS Link as an order ID, leave it blank
2) or at the very least, it should create a unique order ID for every invoice.

Can you please leave this ORDER ID field blank? 

Thanks!

### How did you encounter this bug?

1) Create BTCPay Plugin POS .
2) Generate invoice via the plugin.
3) Pay the invoice.
4) Send the Receipt to the buyer, and notice that Receipt contains link to private POS Plulgin app.

### What browser do you use?

any browser

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
@dennisreimann should we remove the order ID though? I am unsure, but customer should have some sort of invoice id on the receipt to be able to distinguish? App id is def not helpful, thoughts?

**Comment by dennisreimann** [comment]
@pavlenex in the PR I did not remove the order id, just the link  associated with it. I get that the order id in its current form isn't good and not an id, changing it would be breaking though – something to discuss in the next dev meeting.

**Comment by NicolasDorier** [comment]
@dennisreimann we shouldn't remove the link in all case though.
I saw somebody relying on the fact that the receipt has a link to the `orderUrl` as part of the flow for the customer. (In woocommerce, this would redirect to the woocommerce order page)

**Comment by pavlenex** [comment]
@ndeet can you chime in here and see if it's possible that receipt orderid link as shown [here](https://btcpay.kapitalex.com/i/3aYoYz8R9jmsFTqjgASpVF/receipt) could be useful for WooCommerce in some cases, for example returning to an order page, as Nicolas said?

**Comment by dennisreimann** [comment]
@pavlenex I can confirm that it makes sense to have those order URLs in case they contain meaningful info, e.g. for the flow that @NicolasDorier described. However, I agree with the initial sentiment of @yuriygeorge that this isn't really the case for simple links to the raw POS app. That's why I removed the order URL for POS and re-added the links on the invoice receipt. [Details](https://github.com/btcpayserver/btcpayserver/pull/5077/commits/bd5d3b9d7e0989b9a17eea7e9042cb708114fba8)

**Comment by NicolasDorier** [comment]
@dennisreimann another question.
When a retailer come with point of sale, then print the receipt.

How do they return to the point of sale without the link to the PoS?

**Comment by NicolasDorier** [comment]
Or we make it configurable

**Comment by NicolasDorier** [comment]
@dennisreimann can you put back the orderUrl for the PoS? we discussed in the dev meeting. Let's come back on it on 1.11.0.

**Comment by NicolasDorier** [comment]
Wait the Receipt improvement PR shouldn't be in next minor?

**Comment by yuriygeorge** [comment]
> @dennisreimann another question. When a retailer come with point of sale, then print the receipt.
> 
> How do they return to the point of sale without the link to the PoS?

How do they start the PoS app in the very beginning, before any receipts are yet to be made?

**Comment by yuriygeorge** [comment]
It's just we share the receipts URLs with the buyers. So when they go home, or view the receipt on their own devices at home, then they would be able to access the POS app, even though the POS app was intended to be only for the merchant device in the store.

Just might open up the opportunity down the road for abuse by malicious actors.

It's not really that big of a deal, though, no worries.

**Comment by yuriygeorge** [comment]
We don't really want buyers/consumers to have access to the POS link, such as to create dust empty invoices, or spam the servers. The POS link is supposed to be with the merchant only. For a few buyers here and there, no problem. But if there are many many buyers, it's opening up this opportunity exponentially, because every receipt will have the PoS link. If there were thousands of buyers, then there are thousands of receipts with the POS Link. And if these receipts are shared with others on the web, it creates even more problems.

I guess I don't want to discuss this any further. I've said what I wanted to say. It's no problem.
We might be able to create an internal solution. We'll see if there a way to override the OrderID and URL via API. Thanks for your consideration either way.

**Comment by NicolasDorier** [comment]
> So when they go home, or view the receipt on their own devices at home, then they would be able to access the POS app, even though the POS app was intended to be only for the merchant device in the store.

So basically you don't want the URL and QR Code in the paper receipt, but don't mind on the browser?

**Comment by Kukks** [comment]
> > So when they go home, or view the receipt on their own devices at home, then they would be able to access the POS app, even though the POS app was intended to be only for the merchant device in the store.
> 
> So basically you don't want the URL and QR Code in the paper receipt, but don't mind on the browser? If so, I believe it makes sense in general. That said, for voucher features, the QR Code might be useful. Should we make it off by default, but allow in the API to show it?

He needs it hidden for all, as the paper receipt has a qr link to the online receipt and the user can go on it trivially

**Comment by NicolasDorier** [comment]
I see. I thought the QR code was a link to the orderUrl.

**Comment by NicolasDorier** [comment]
Note that I believe the QR Code and URL can be hidden in the paper receipt by applying a custom CSS style to the store. right @dennisreimann ?

**Comment by yuriygeorge** [comment]
1) If you go to this receipt, for example:
https://btcpay.kapitalex.com/i/3aYoYz8R9jmsFTqjgASpVF/receipt

2) The link OrderID (pos-app_2kXpfKAZfBxzU3J34wmmQfjfD9T5), click on it, please.

Then it will make sense. This link follows to the Point of Sale Merchant app. I don't want buyer/consumer, to have a link to the merchant POS app.

(I do not have any problem with QR code. QR Code works fine. QR Code, I believe, points to the Receipt link)

**Comment by NicolasDorier** [comment]
> This seems to be a problem with the POS Plugin. For some reason, the Point of Sale plugin sets the OrderID to be the ID of the Point of Sale plugin, not the actual individual order itself.

You are right, this doesn't feel right.

**Comment by dennisreimann** [comment]
> You are right, this doesn't feel right. Internally we do not rely on the orderId to track PoS payments, so we could potentially change that.

@NicolasDorier Right now we have Order IDs like `pos-app_4BPMc3oqazLim9H67qc36JLvRmMt`, which is basically the App ID. We could simply append a randomized value to make it a uniquew Order ID, like `pos-app_4BPMc3oqazLim9H67qc36JLvRmMt_lashdDu4f8gy`. 

We have to keep in mind though, that the invoices search uses the App Id prefix for filtering. Hence we'd have to switch [trhis part](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Services/Invoices/InvoiceRepository.cs#L680) to something using `StartsWith` instead of an equal match.

**Comment by pavlenex** [comment]
So TLDR, is that:

1. Order ID is not really useful and it's actually app ID which is useless for being able to distinquish an invoice.
2. Some people use this order ID link to get back from receipt to home
3. We don't have a way to go back to home

So let's juts add the ability to go back to home from a receipt and remove orderID,?

**Comment by dennisreimann** [comment]
@NicolasDorier Done in #5127.
