### ISSUE TITLE
Pos issue with rounding

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5055]
![image](https://github.com/btcpayserver/btcpayserver/assets/36959754/b21006d0-9555-42e8-a583-84417b3e541a)

**Comment by TLEEDUCHARME89** [comment]
So what's the deal then to the nearest 10th or 100th

**Comment by petzsch** [comment]
I think it depends on the fiat curreny used. Not entirely sure about it, but there might be some like the indian rupee that need 3. More research is needed. Of the fiat shitcoins I usw 2 decimal places would do.

Hopefully we nail it right away. 😅

Am 10. Juni 2023 05:22:50 MESZ schrieb TLEEDUCHARME89 ***@***.***>:
>So what's the deal then to the nearest 10th or 100th
>
