### ISSUE TITLE
Add support for creating hodl invoices

### ISSUE THREAD

**Issue by aaronkopplin** [btcpayserver/btcpayserver#5059]
### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/5058

<div type='discussions-op-text'>

<sup>Originally posted by **aaronkopplin** June 10, 2023</sup>
Hi there,

I would like it if BTC pay server could create hold invoices. These invoices would allow for free refunds without multiple lightning transactions, and would save on fees. Without hold invoices, stores are vulnerable to a type of attack where the attacker creates an order, sends a payment, then requests a refund. This requires two payments and the attacker could have a routing node in the middle, collecting routing fees from the merchant. 

for those that arent familiar with hold invoices, here is a good primer:

"Hold invoices are LN invoices where the receiver doesn’t immediately release the preimage upon receiving a payment. Instead, the receiver performs some action and then either accepts the payment, explicitly rejects it, or lets it time out.

For example, Alice could automatically generate hold invoices on her website but wait until a customer actually paid before searching her inventory for the requested item. This would give her a chance to cancel the payment if she couldn’t deliver."

source: https://bitcoinops.org/en/topics/hold-invoices/#:~:text=Hold%20invoices%20are%20LN%20invoices,or%20lets%20it%20time%20out.

A longer explanation: https://thebitcoinmanual.com/articles/hodl-invoice/

Hold invoices also allow for other beneficial types of transactions. If anyone knows of any benefits, please post them here. Thanks!</div>

**Comment by pavlenex** [comment]
Duplicate #5058 let's keep discussing it there, we turn discussions into issues, once we decide we want to implement it and there's enugh interest from community which is measure through upvotes, hence discussion is more suitable place.
