### ISSUE TITLE
[Bug]: Two-factor authentication (2FA) QR Code is not scanning into phone

### ISSUE THREAD

**Issue by jahway603** [btcpayserver/btcpayserver#5060]
### What is your BTCPay version?

I'm running BTCPay Server v1.10.2+6d0f9120b (Altcoins)

### How did you deploy BTCPay Server?

Docker

### What happened?

When I attempt to scan the 2FA code on my phone, it will not work. The QR code appears to be a very strange rendering.

### How did you encounter this bug?

1. Click on Account Settings.
2. Click on Two-Factor Authentication.
3. Click on Enable 2FA.
4. Attempt to scan QR Code into my OTP phone app.
5. QR Code will not scan.

### Relevant log output

```shell
N/A
```

### What browser do you use?

Chromium Version 114.0.5735.106 (Official Build)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by astantoid** [comment]
second user lunch problen here

**Comment by dennisreimann** [comment]
I cannot reproduce this with Bitwarden and also checked that the QR code contains the right information. Which app are you using to scan?

**Comment by jahway603** [comment]
I have tried scanning the BTCPayServer obscure QR code with both [andOTP](https://f-droid.org/en/packages/org.shadowice.flocke.andotp/) and [SecScanQR](https://f-droid.org/en/packages/de.t_dankworth.secscanqr/), but neither of them are functioning with it. I am able to scan other QR codes with both of these apps.

**Comment by petzsch** [comment]
Samsung has in control Center, if you edit the Icons.

Am 14. Juni 2023 06:43:35 MESZ schrieb jahway603 ***@***.***>:

**Comment by dennisreimann** [comment]
@jahway603 just checked, for me it works flawlessly with andOTP v0.9.0.1 and SecScanQR v1.2.8 — both latest on F-Droid.
