### ISSUE TITLE
Pay?

### ISSUE THREAD

**Issue by Johnathanodom** [btcpayserver/btcpayserver#5063]
bitcoin:bc1qf3mq0fq635hxw64d643vz3l6t5yw0w3h56fdpd

**Comment by petzsch** [comment]
https://blog.btcpayserver.org/bitcoin-bonus-scam/

@btcpayserver/github-security we are getting hammered by these. can I at leasts setup a slash command somehow so that it pastes the link everytime?

**Comment by Johnathanodom** [comment]
https://github.com/dennisreimann/btcpayserver/commit/c0bc19ea5908a98263df8a006571c1a6064c24cd

**Comment by Johnathanodom** [comment]
Idk

**Comment by jamesj6150** [comment]
Need help
