### ISSUE TITLE
[Bug]: 'Failed to load refund options' for an overpaid invoice

### ISSUE THREAD

**Issue by JCZwier** [btcpayserver/btcpayserver#5066]
### What is your BTCPay version?

I'm running BTCPay v1.10.2+6d0f9120b (Altcoins).

### How did you deploy BTCPay Server?

I deployed it with Docker.

### What happened?

When I want to issue a refund because the customer overpaid, selecting the first option in the pop-up menu ('The cryptocurrency amount that was overpaid.') generates an error: 'Failed to load refund options'

### How did you encounter this bug?

1. I clicked 'Issue Refund' on the page for the invoice that was overpaid
2. I selected the first option to refund the overpaid amount (see below)

![image](https://github.com/btcpayserver/btcpayserver/assets/6506941/12e8a101-b974-446f-bea5-657b883c4851)

### What browser do you use?

Firefox 114

### Additional information

Manually entering the overpaid amount under 'Custom amount' worked fine.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Thanks for reporting, will be fixed in the next version!
