### ISSUE TITLE
NotificationUrl dont query invoice id

### ISSUE THREAD

**Issue by CarlosRoldanx** [btcpayserver/btcpayserver#508]
Hey,

I am severely trying to get the invoice id from the notificationUrl. I added a POST route to handle the notification and print them in the server console the request. However, I am not getting anything and this is quite frustrating. I have gone through the Bitpay documentation and nothing...

I made sure the request is HTTPS. This is the code in the client:
```
 <form method="POST" action="https://lnd.satoshis.games/apps/Gg4XypPUkxv5XiBjeEjjaxxLh5X/pos">
            <input type="hidden" name="email" value="customer@example.com" />
            <input type="hidden" name="orderId" value="CustomOrderId" />
            <input type="hidden" name="notificationUrl" value="https://satoshis.games/confirm" />
            <input type="hidden" name="redirectUrl" value="https://satoshis.games/start" />
            <button type="submit" name="choiceKey" value="Satoshis Games sticker" class="nes-btn is-success">CONFIRM</button>
</form>
```

This is the code in the server:

```
async getNotification({request}) {
        try{
            console.log(request.id)
        }catch(error){
            console.log(error)
        }
    }

```

The route is `/confirm`

**Comment by JeffVandrewJr** [comment]
Can you log into your BTCPay admin panel and look at the invoice history? That should give you a history of the IPN (whether it was sent, accepted by your server, got a 404, etc).

**Comment by NicolasDorier** [comment]
As @JeffVandrewJr said, you have logs about errors BTCPay got while trying to send notification on the invoice's page in BTCPay.

**Comment by CarlosRoldanx** [comment]
Thank you so much for this information. It's returning  me a 500 error code. 

CSRF token protection would affect this right?

Is there any error log of more in detail from BTCPay Server?

**Comment by NicolasDorier** [comment]
What is returning you an "500 error code." ?

**Comment by JeffVandrewJr** [comment]
If you're getting a 500, that means BTCPay is operating correctly but something on your server side code is crashing when it receives the POST of JSON data. In the BTCPay log, check the time that BTCPay received the 500, then look up that time on your server logs to see what error was logged by your server that caused the 500. It should be pretty apparent.

**Comment by CarlosRoldanx** [comment]
Check the code from the issue (server-side code) with the following log from btcpay server, I can't find sense on this problem as the server does not log any error but BTCPay Server does. 
<img width="773" alt="captura de pantalla 2019-01-10 a las 16 48 28" src="https://user-images.githubusercontent.com/31220861/50983595-b05eef00-14f7-11e9-98e8-e64994541f11.png">

**Comment by JeffVandrewJr** [comment]
@CarlosRoldanx Your server is returning a 500, so it must be logging something. If it has separate access and error logs, check the access log if nothing is in the error log. 

My totally understand uninformed guess is that you're not parsing the JSON correctly. [Totally uninformed on my part because I don't know what language/framework you're backend Is using or what server you have handling the requests.

**Comment by CarlosRoldanx** [comment]
Thanks for your patience and understanding @JeffVandrewJr. I was using [AdonisJS](https://adonisjs.com/) framework for NodeJS.

I solved my issue:

- [x] When adding middleware such CSRF token protection, I have to add my BTCPay Server URL as an exception.

- [x] Adding my BTCPay Server URL as an allowed host.

**Comment by JeffVandrewJr** [comment]
@CarlosRoldanx No problem!
