### ISSUE TITLE
Add direct file upload in POS

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5086]
> When I want to add photo to POS app and copy the file, it doesn't work (absolute vs relative paths)

@NicolasDorier and I talked about this, I'll add direct file upload in the POS. No need to consider it here then.

_Originally posted by @dennisreimann in https://github.com/btcpayserver/btcpayserver/issues/5081#issuecomment-1595863402_

**Comment by dennisreimann** [comment]
Let's do this after #5078.

**Comment by Kukks** [comment]
We will probably need some file size limits if you are not an admin. I am
worried it may become an attack vector by non admins

**Comment by dstrukt** [comment]
ACK to file size limits and validation

**Comment by NicolasDorier** [comment]
We allow upload in different part of BTCPay now. We validate that image are actually uploaded.
Size limitation should be a different PR, as it will touch parts unrelated to POS.
