### ISSUE TITLE
Add `Shipping field` option to custom forms

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5087]
We've had a few very reasonable requests to add shipping options to custom forms. @rockstardev suggested an approach where we add a dropbox with few fixed rate shipping options customer can pick and keep it simple. We won't extend this one to more advanced shipping rates options.

**Comment by rockstardev** [comment]
Upon review, Custom Form system already has ability to add generic select dropdown. However the current system does not have ability to impact amount for the invoice.

In order for my new code not to impact existing ideas behind what @Kukks and @dennisreimann have done, we agreed that I sync with Kukks separately before moving forward to implement PR to address this issue.
