### ISSUE TITLE
Improve invoice reporting

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5095]
This issue will be updated with proper context and description as soon as we get specific feedback from people who requested better invoice exporting/reporting.

Update:

![Screenshot 2023-06-20 at 10 37 50](https://github.com/btcpayserver/btcpayserver/assets/36959754/222cac99-06bb-48cd-83c4-f0f5d44d87bc)

**Comment by pavlenex** [comment]
Possibly we can add items from POS 

https://github.com/btcpayserver/btcpayserver/issues/937

**Comment by EscapeToElSalvador** [comment]
I haven't found it discussed elsewhere, but automating the reporting (e.g. send email with report attached periodically) would be helpful, imo
