### ISSUE TITLE
Instant print `receipt` upon settled invoice

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5098]
We've received feedback that people would love to be able to have an option which automatically triggers receipt printing without them having to click through few buttons to get it done, as sometimes, devices are held in fixed position and it's inconvenient for merchant to reach in order to print a receipt.

**Comment by dennisreimann** [comment]
I'm not sure we can implement this, as mobile browsers oftentimes require user interaction to trigger those actions. Will investigate — sounds like a good follow-up to #5077.

**Comment by pavlenex** [comment]
Thanks @dennisreimann do you want me to tag this for 1.11 or should we keep it on the roadmap and determine after you investigate, sounds like the later approach is better?

**Comment by Shine3488** [comment]
Great

**Comment by dennisreimann** [comment]
@pavlenex With #5077 I created a separate receipt view, which is supposed to be customized for printing on thermal printers (text-only version) like with the Sunmi devices. That view is opened via the "Print" link on the receipt and directly triggers the printing dialog to come up — we cannot skip that dialog and start printing right away though.

Manually printing the standard receipt view gives the full HTML print view as we had before. 

So basically I think this is very store/use case specific and I think we will need to make it configurable, because we cannot foresee what the use case will be.  We have these receipt options in the Checkout Appearance already:

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/ee765368-ba00-4528-b623-a955b38faed7)

I think we might add a fourth option "Opening receipt triggers printing" — if that's activated we can also let the merchant decide, if this should trigger printing the HTML or text-only version.

**Comment by pavlenex** [comment]
>  "Opening receipt triggers printing" 

How about "instantly trigger receipt printing"?

**Comment by Amperstrand** [comment]
There are a couple of different ways I have seen traditional payment terminals print receipts:
 - receipts printed in a remote location
 - single click to print receipts: the user is prompted if they want a receipt (Yes/No)
 - receipts that start to print when the payment is initiated, pause until the payment has cleared or failed and then prints the rest. This gives a visual queue that the user facing part of the transaction is completed once the receipt starts printing and that the waiting now is for the payment to clear.
   - checkout-v2/nfcread.mp3 --> start printing receipt
   - checkout-v2/payment.mp3 --> print payment confirmed
   - checkout-v2/nfcread.mp3 --> optionally print error about why the payment did not go through

Receipts printed in a remote location has at least a couple of use cases:
 - A waiter can accept payment and the order is printed in the kitchen as soon as the payment goes through
   - The payment doesn't even have to go through: it can just be that the waiter (or table) has created an order
     - for this use-case, a restaurant can use btcpayserver for order management. It would make an excellent free order management system even if it you ignore all of the bitcoin payments aspects of it:
       1. customer sits down at table and scans QR code or NFC link
       2. customer orders food and drink using Product list with cart point of Sale plugin
       3. fiat denominated invoice is created which shows what table the customer is sitting at and what they have ordered
       5. order is printed in kitchen and brought to customers table when ready
       6. customer is prompted if they want to pay now in bitcoin or pay later in fiat by signalling that they are ready to pay to a waiter.

**Comment by Amperstrand** [comment]
If/when BTC-payserver is a standalone app, it could also be a print server.

https://play.google.com/store/apps/details?id=ru.a402d.rawbtprinter is a print server (free for testing but paid for commercial use). It allows you to set up a watch folder, and anything that is put in the watch folder gets printed. So you can do automatic printing today by:
- Use btcpayserver to send a webhook to ifttt.com or stackstorm.com
- this in turn triggers some software that downloads the receipt and uploads it to a folder that is somehow shared or synced with the payment terminal
- the printing app monitors the folder and prints the receipt either on the waiters POS and/or at a remote POS

**Comment by Amperstrand** [comment]
Another use case:

A shop can now accept bitcoin payments with just a QR-code or an LNURL QR-code and a printer.

Bitrefill could use this to make a network-connected store-specific gift card printer:
 - Customer taps NFC that takes them to https://soho-till5.starbucks.btcpayserver.bitrefill.com
 - Customer (or merchant) uses keypad POS to enter the amount that they want to buy a gift card for
 - Customer pays the amount in bitcoin to bitrefill
 - Bitrefill prints the gift card at the printer that is next to the merchant register

This can be done with any old networked printer: a dedicated thermal printer, a POS device, or just a WIFI printer.

It would be much better to do the integration with the merchants payment system, but this requires a big project where you involve many parts of the organisation where as a dedicated device that just shows or prints bitrefill gift vouchers that can be scanned by the legacy store payment system does not.

"Do you accept Bitcoin?"
"Not really, but use this dedicated device here to buy a coupon that will mark your payment as cleared when I scan it"

No integration required from IT or management and can just be done by any brave store manager or clerk.

**Comment by pavlenex** [comment]
We'll add this to the BTCPay App , seems hard to achieve on the server side atm.
