### ISSUE TITLE
allow marking invoice as payed

### ISSUE THREAD

**Issue by thestick613** [btcpayserver/btcpayserver#512]
I can mark a new transaction only as "Mark Invalid". After i mark it as invalid, i can refresh and mark it as "completed". It would be nice to be able to mark it as completed from the first step.

**Comment by bitcoinshirt** [comment]
I see what you mean, but if the invoice is actually paid, it can be marked as completed right on the first step.

Why would anyone want to be able to marked an unpaid invoice paid? This two-step process eliminates accidental errors.

**Comment by thestick613** [comment]
I just wanted to submit a few dozen test payments without actually paying.

**Comment by bitcoinshirt** [comment]
Yeah, that's why the suggestion does not have a real use-case. You can already mark an unpaid invoice as complete in two steps. It's better to eliminate the chance of mistakes for real usage than making testing easier.

**Comment by thestick613** [comment]
I know, but marking it as invalid first triggers a IPN callback notification. I've actually had to close the callback endpoint, get an "Error while sending IPN: Connection refused" and then restart the endpoint, and then mark it as completed.

**Comment by bitcoinshirt** [comment]
In that case, I understand the need for it. Still for testing, if you do not want to spend actual funds, you can always use testnet as I said.
 
It's scary to me that a cashier using BTCPay PoS can accidentally trigger an unpaid invoice as paid easily. Just my two cents, let's see what others think and if anyone else would need this.

**Comment by sipsorcery** [comment]
NACK.

I agree with @pavlenex that it sounds dangerous to add this feature to the main product solely for test convenience.

Perhaps an alternative is to see if a web API could be added as part of #189 that would allow an invoice's status to be easily updated via a command line or script. There is already `InvoiceControllerUI.ChangeInvoiceState` that could do it but since it uses cookie authorisation it'd be tricky to script.

**Comment by NicolasDorier** [comment]
I agree with the others, closing this. Actually I don't think a tricky script can do anothing, because we use anti forgery tokens on pretty much every POST form.
