### ISSUE TITLE
[Bug]: BTCPayServer.Client NuGet package is missing 'GetStoreRates'

### ISSUE THREAD

**Issue by celldra** [btcpayserver/btcpayserver#5122]
### What is your BTCPay version?

I'm running BTCPay Server v1.10.2+6d0f9120b (Altcoins)
NuGet package version v1.7.2 (https://www.nuget.org/packages/BTCPayServer.Client)

### How did you deploy BTCPay Server?

I'm running BTCPay Server on a dedicated instance via Docker

### What happened?

It seems that on the GitHub repository, in the `BTCPayServer.Client/BTCPayServerClient.StoreRatesConfiguration.cs` file, there is a method to get the store rates `GetStoreRates`. Although, the same method seems to be missing from the NuGet package edition.

I could not find the method when disassembling the DLL directly from NuGet.org:
![image](https://github.com/btcpayserver/btcpayserver/assets/124086032/d258dd2c-37cd-48a8-b391-99a94f498ec2)

And if I attempt to call it on my `BTCPayServerClient` instance, my IDE gives me this:
![image](https://github.com/btcpayserver/btcpayserver/assets/124086032/85a28381-192c-4a0a-b7df-d9cb7036e713)

Is this some sort of bug with the packaging or intended behaviour?

### How did you encounter this bug?

1. Download NuGet package for BTCPayServer.Client (v1.7.2)
2. Setup an instance of the `BTCPayServerClient` object
3. Attempt to call `GetStoreRates` on the `BTCPayServerClient` object, it should say the symbol was not found, intended behaviour would be that it is accessible.

### Relevant log output

```shell
N/A
```

### What browser do you use?

N/A

### Additional information

N/A

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
Correct, sorry for the wait, I released 1.7.3
