### ISSUE TITLE
Configuration Fail 

### ISSUE THREAD

**Issue by Freefromchainz** [btcpayserver/btcpayserver#513]
After a successful build  and setting up postgresql, I tried to run the app an ended up with the this fail message. 
![btcpayserver error1](https://user-images.githubusercontent.com/8317700/51003832-7f7dba80-14f5-11e9-8640-346967e31059.PNG)

**Comment by NicolasDorier** [comment]
What do you want to do? develop or deploy on windows?

**Comment by Freefromchainz** [comment]
deploy!

**Comment by NicolasDorier** [comment]
well `devtest.pfx` is nowhere in the source code, except in the documentation of the configuration file, commented. If you uncommented it, you should recomment it.

**Comment by Freefromchainz** [comment]
Roger that thanks again!

**Comment by Freefromchainz** [comment]
Settled that, now this!
![btcpayserver error2](https://user-images.githubusercontent.com/8317700/51088953-3612b280-1723-11e9-8e49-a8137ba4889e.PNG)

**Comment by NicolasDorier** [comment]
as the error message say, you need to run as admin.

**Comment by Freefromchainz** [comment]
After running as admin still getting the same error
![btcpayserver error3](https://user-images.githubusercontent.com/8317700/51127240-450c6a00-17e2-11e9-8fba-ec1573500adc.PNG)

**Comment by Freefromchainz** [comment]
yes I think postgres is on 23000 somehow

**Comment by Freefromchainz** [comment]
that was it!
