### ISSUE TITLE
Sql server support. Any issues the BTCpayserver does not support Sql Server?

### ISSUE THREAD

**Issue by smallswan399** [btcpayserver/btcpayserver#514]

**Comment by Kukks** [comment]
Shouldn't be an issue afaik. Would you be willing to test if I push out a pr?

**Comment by NicolasDorier** [comment]
@Kukks if you do it, please first make it possible to have CircleCI running all the tests for all the databases.

After merging mysql, we found out issues that are still unsolved: Mysql primary keys column are limited to 255 chars, so sometimes it fails with lightning.

Different implementations always have gotchas like this and we can't find them out if the tests are not using those database.

**Comment by pavlenex** [comment]
Closing this one, as it's zombie. If you still need it please let us know.
