### ISSUE TITLE
Ive paid btc fees thou the btcpayserve but for some reason  my payment hasent been released casue its not verifying it throu the server yet its been recieved  from my wallet successfully  on blockchain ive been waiting 3 plus months now and nothing has come bk all i keep recieving  is  to pay more of a fee for transferimg instead of btcpayserver ahowimg its been paid how can i fix this as ive tried every angle and this is the site it keeps forwarding me to 

### ISSUE THREAD

**Issue by Barbry15** [btcpayserver/btcpayserver#5145]
Ive paid btc fees thou the btcpayserve but for some reason  my payment hasent been released casue its not verifying it throu the server yet its been recieved  from my wallet successfully  on blockchain ive been waiting 3 plus months now and nothing has come bk all i keep recieving  is  to pay more of a fee for transferimg instead of btcpayserver ahowimg its been paid how can i fix this as ive tried every angle and this is the site it keeps forwarding me to

**Comment by pavlenex** [comment]
https://blog.btcpayserver.org/bitcoin-bonus-scam/
