### ISSUE TITLE
Payment made 

### ISSUE THREAD

**Issue by Barbry15** [btcpayserver/btcpayserver#5148]
Payment has been verified  and successfully  recieved  on their end and on blockchain but for some reason my payment hasent been released to my account  ..i just keep getting a new email telling me to pay more fees then the initial  fees i alreDy paid to transfer the btc to my wallet .. how can i fix the glitch so i can recieve my payment in my account... as ive tried contacting  all different customer service reps in this regard and im not geyting any answers to get this issue fixed its quite ridiculous  that not one of yhese companies  have a number to call it just says we have to wait for a reply ...well its been 3plus months now and i still havr no answets ca  someone please assist me on this as i had to put money out of my own povket to pay requested fees of btc being i was supposed  to recieve my psyout 10 mins after transaction was made ... km sure 3 plus months iz mucn more then 10mins

**Comment by Kukks** [comment]
https://blog.btcpayserver.org/bitcoin-bonus-scam/
