### ISSUE TITLE
Override of "Requires a refund email" for PoS and Crowdfunding

### ISSUE THREAD

**Issue by hubiktomas** [btcpayserver/btcpayserver#515]
If someone creates a PoS of Crowdfunding app in a store, that does not require refund e-mail, users will pay, but we will not know, who paid/purchased the items. It would be good to have an option to override this store setting in the app settings.

One workaround can be creating a new store with exactly the same settings except this one. However, not sure, what will happen if I use the same derivation scheme for two stores.

**Comment by bitcoinshirt** [comment]
For PoS, e-mail is not needed it's physical.
For Crowdfund, add a new field "require e-mail address" if refund e-mail is not set in the store settings?

Honestly, the "refund email" is on by default anyway, if you were a newbie, you would already have it, so no space for confusion for newbs.  If you're a user who used BTCPay you'll know how to disable/enable or setup a different store. Not really sure how useful this is.

**Comment by hubiktomas** [comment]
Well the usefulness depends on my second part of the post - what will/can happen if two stores use the same derivation scheme. If it is completely ok, than it is possible to use the workaround. However it might be just unnecessary overhead to setup the whole new store just because of this one option.

And regarding the PoS - yes, it can be physical, or you can use it as a payment button where you have more customization options.

**Comment by Kukks** [comment]
@hubiktomas  it should be fine, invoices are linked to Store Id not to the derivation path.

**Comment by Kukks** [comment]
If I remember correctly, nbxplorer is the one that handles this which
doesn't care about your different stores using the same derivation. It will
just hand out the next address for the request derivation upon request

**Comment by hubiktomas** [comment]
All right. So the only problem would occur if I use the xpub outside BTCPay Server as nbxplorer would have no way how to find which addresses are unused (unless there is already some balance on them). I do not really know, how nbxplorer works inside. So if I use the same xpub twice, nbxplorer would notice it and handle them as one? Where is this persistence stored? It looks like nbxplorer does not have any DB. Really confused here.

**Comment by Kukks** [comment]
@hubiktomas If I remember correctly, NBXplorer uses a flat file storage solution of some sort. I haven't dug into it deep enough yet to be able to tell you more.

**Comment by hubiktomas** [comment]
@Kukks Ok, no problem. Basically if there is a possibility for workaround by creating a new store with the same derivation scheme and it will not cause any conflicts, then no problem and I can live with that. :) Issues caused by two stores using one xpub was my main concern.

**Comment by Kukks** [comment]
@NicolasDorier  Can yo ushed some light? :)

**Comment by NicolasDorier** [comment]
You can use same derivation on two different store.

**Comment by hubiktomas** [comment]
No problem then. :)
