### ISSUE TITLE
[Bug]: PoS Product list with cart style + custom amount 

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#5150]
### What is your BTCPay version?

1.10.3

### How did you deploy BTCPay Server?

docker

### What happened?

When you use a PoS with the "product list and cart" style and you enter a custom amount it will skip the invoice but directly show the receipt instead. See report and his store to reproduce by k3m here https://chat.btcpayserver.org/btcpayserver/pl/6yz751numtfytpe87dq9w4tdqw

I also reproduced it on mainnet demo here https://mainnet.demo.btcpayserver.org/apps/PvS5r1W28eymcynxEjaVdU8ofjh/pos

### How did you encounter this bug?

enter custom amount in "pay what you want" and hit button pay

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pretyflaco** [comment]
I think it was introduced with latest version 1.10.3, as merchant confirmed he was able to create LN invoices with "pay what you want" 26 days ago (early June)

**Comment by dennisreimann** [comment]
@NicolasDorier I think this is a regression introced with #5079 — the fix in 76faf77a1c3b4c78e787a7d9ae628df26677dd41 doesn't seem to be enough.

**Comment by dennisreimann** [comment]
Hmm, since this commit 43096033173c0bd05c03f64047f96bcb8769dda0 topup items/custom amount isn't even featured with the cart view anymore — it was part of the v1.10 release.

**Comment by dennisreimann** [comment]
Ok, finally got it, this isn't even about the item config, but the general "User can input custom amount" option that causes this. Will work on a fix now ;)
