### ISSUE TITLE
Refund for this thing that literally stole my bitcoin out my cashapp 

### ISSUE THREAD

**Issue by sixgod13** [btcpayserver/btcpayserver#5152]
ination Received Paid Rate Payment
lnbc1642280n1pjr550xpp5yaz5w3
clp99xh4q78qyzgmzkcpcj4g0ayre
590dhzrrwegme02ysdzz2pskjepqw
3hjqnmsv4h9xct5wvszsnmjv3jhyg
zfgsazqcn5vdcxz7tnv4e8vetj9yc
qzpgxqzuysp5ft37ftqkjzchw0sl2
30a8z5l8r09wwer8t9jajfq0qfr9d
40eecs9qyyssq8u6ljlwuvp0jsa6j
stur9c7nc6jsuqskqur8dx4spdgcy
yqr7fs9cn0qe2dw6m04m8wrsle5g6
t8ean2j8hy3fd044y8v7r7aknndlg
qlvgrjz
04/15/2023
07:29
$50.00 $30,445.51 0.00164228 BTC (Off-Chain)
Transaction Id: 274547471f094a

**Comment by pavlenex** [comment]
Please read this https://blog.btcpayserver.org/bitcoin-bonus-scam/
