### ISSUE TITLE
How to change first page content?

### ISSUE THREAD

**Issue by thestick613** [btcpayserver/btcpayserver#517]
I'd like to change the logo, the splash text, some descriptions. What is the preferred way to do this?

**Comment by bitcoinshirt** [comment]
General questions like this are much better if asked on Slack.
[This is documented in FAQ.](https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#how-to-customize-my-btcpay-theme-style)
For smaller CSS changes you can [use Bootstrap theme
](https://docs.btcpayserver.org/development/theme)

**Comment by thestick613** [comment]
I'm not using docker, and even if i was, i wouldn't know where the code for the first page resides.

**Comment by bitcoinshirt** [comment]
If you can't find it in code, I really don't recommend doing it. You'd need to maintain your own fork and it's a hassle right now. 

But you can customize the checkout page easily though.

@Eskyee or @LinoxBE may be able to explain how they do it specifically for their sites https://btcpayjungle.com/ and https://lightbo.lt/

**Comment by thestick613** [comment]
So fork, and edit right into https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Views/Home/Home.cshtml
Got it.
