### ISSUE TITLE
[Bug] MessageText: permission denied for table txs

### ISSUE THREAD

**Issue by mingw-io** [btcpayserver/btcpayserver#5177]
### What is your BTCPay version?

I'm running BTCPay v1.10.3

### How did you deploy BTCPay Server?

I'm running BTCPay Server on Windows 10 x64 deployed in a masochist way (a.k.a. manual)

### What happened?

I can see some errors on the console such as:

![image](https://github.com/btcpayserver/btcpayserver/assets/70483213/70e6c9bd-72a1-4231-af34-9c1d4dbf4db2)

### How did you encounter this bug?

Whenever I click on 'Dashboard' on the UI.

![image](https://github.com/btcpayserver/btcpayserver/assets/70483213/ebb8b980-dcc5-47ba-a84f-006ae282594d)

All other options (or hyperlinks on the menu/pages) seem to work fine.

![image](https://github.com/btcpayserver/btcpayserver/assets/70483213/ef2d3a0d-38e6-4f82-b611-6a823589211e)

### What browser do you use?

Chrome

### Additional information

I am brand brand brand new to this project. First attempt at deploying this server. So ..... bear with me!
Thanks for this awesome project.

![image](https://github.com/btcpayserver/btcpayserver/assets/70483213/e052ed6f-cc03-4215-9dee-2167f2538b36)

![image](https://github.com/btcpayserver/btcpayserver/assets/70483213/12702a43-50bc-406a-94bb-668449853440)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Does this happen with 1.12.0?
