### ISSUE TITLE
How to make your checkout page?

### ISSUE THREAD

**Issue by hazratgs** [btcpayserver/btcpayserver#518]
Greetings friends! I would like to completely rewrite the payment page:

![image](https://user-images.githubusercontent.com/4028580/51058580-56931d80-15fa-11e9-8cdc-ebf6405253f1.png)

Tell me, how can this be done? Where can I get the API documentation?

I did not find a field in the store settings where I could enter a link to another payment page.
Do you really need to fork the project and the path to the HTML files on the payment page should be inside the project?
Is it possible, like without a fork, to use this project as an API for your own form of payment?

I would not like to fork, because so I will remain without updates...

**Comment by Kukks** [comment]
Hi @hazratgs You can customize it by adding a custom css link in the store settings last I checked. Beyond that, it is not possible for now. I have some PRs coming in the next few months that will allow you to use btcpay from just an api but it is still early
