### ISSUE TITLE
Wallet-rescan shows different results between same xpub on two different servers

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#519]
## Issue: 
Wallet balance different after importing xpub to a different server and doing re-scan.

## How to replicate
Use xpub that has transactions from one server, load it up to another, wallet re-scan and compare results.

## Specifics 
Not much  difference between servers one LND the other c-lightning, but that's irrelevant. Both running  v1.0.3.42

Added same xpub to two different servers and created two stores. One server used to receive payment, the other sitting around. After a while, I decided to wallet re-scan with same default setup.

Both wallet found the same amount of UTXOs - 13, but different UTXO set size. 
The only difference between two setups is that one is LND and other c-lightning, but that's really irrelevant, but for me it's easier to differentiate them that way.

**BTCPay Server LND:**

![screen shot 2019-01-12 at 22 27 32](https://user-images.githubusercontent.com/36959754/51078666-50b04180-16b9-11e9-95f1-77b549f42278.png)

**BTCPay Server c-lightning:**

![screen shot 2019-01-12 at 22 28 16](https://user-images.githubusercontent.com/36959754/51078669-602f8a80-16b9-11e9-8ec6-5eab04e49d68.png)

The balances were different as a result. I experimented with up to 50.000 gap limit which is quite crazy anyway.

 _Scanning the UTXO set allow you to restore the **balance** of your wallet, but not all the transaction history._ 

Well for me this did not work.

Posting this to see if someone can replicate.

## Note
On a side note, constantly having to re-fresh the page to see the progress of the scanning is not ideal UX.

**Comment by bitcoinshirt** [comment]
One more attempt, and now the The total UTXO set size is the same for both servers, but the wallet balances are different.

**Comment by pavlenex** [comment]
Closing this for now. Will re-open if anybody else notice the same.

**Comment by NicolasDorier** [comment]
different utxoset size is possible as some blocks were mined between your two attempt.

**Comment by pavlenex** [comment]
@NicolasDorier Got that, and I finally managed to get same utoxset, but the balance is still different very weird.

**Comment by pavlenex** [comment]
After a few days the balances are still different, but transactions are not identical either.

**Comment by pavlenex** [comment]
Fixed by NicolasDorier.

**Comment by NicolasDorier** [comment]
https://github.com/dgarage/NBXplorer/commit/b311287a970ddf241ef9d886a7e26c075eb5b402
