### ISSUE TITLE
Add modal to POS

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5194]
Having checkout flow without having to interrupt it seems to be very beneficial, especially if a cashier makes a mistakes, having the ablity to easily click x and return to the pos to re-generate a new one seems important.

I am proposing that we implement modal into POS. 

Am I missing on any potential negative consequences?

Current flow

https://github.com/btcpayserver/btcpayserver/assets/36959754/5b6befbe-a5e1-458d-a9c9-ca28cb06c6cb

Implemented solution should look like the one in the Crowdfunding app

https://github.com/btcpayserver/btcpayserver/assets/36959754/63903158-7316-4229-8cbc-0621b413f8a9

**Comment by dstrukt** [comment]
Makes sense. Don't see any downsides outside of invoice gap limit spamming. ACK!

**Comment by peewee5431** [comment]
[3cf9fd0f-0cd2-4147-8739-dec0d2128f65.pdf](https://github.com/btcpayserver/btcpayserver/files/12198631/3cf9fd0f-0cd2-4147-8739-dec0d2128f65.pdf)

**Comment by dennisreimann** [comment]
> Am I missing on any potential negative consequences?

This might be tricky if there's a custom form attached to it. I'd be hesitant to do it via modal if there's no form and keep the current flow in case there is, because that'd be one more layer of complexity.  /cc @Kukks

**Comment by Kukks** [comment]
> > Am I missing on any potential negative consequences?
> 
> This might be tricky if there's a custom form attached to it. I'd be hesitant to do it via modal if there's no form and keep the current flow in case there is, because that'd be one more layer of complexity. /cc @Kukks

I agree. I do wish we can find a solution to this though, so that we can take this experience and applying a revamp to the crowdfund plugin
