### ISSUE TITLE
[Bug]: PoS receipt order id links to PoS

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#5196]
### What is your BTCPay version?

BTCPay 1.11.0-rc4

### How did you deploy BTCPay Server?

docker

### What happened?

On the PoS receipt page there is the new unique order ID, but the order ID link is pointing to the PoS URL.

Not sure if there needs to be a link at all or it should link to the receipt page? 

![image](https://github.com/btcpayserver/btcpayserver/assets/1136761/d81267d5-1f66-44b8-9cbe-9c834c606d01)

### How did you encounter this bug?

Paid PoS invoice, clicked on receipt

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
@ndeet I think we debated this one in #5054, basically it seems people use this as a way to get back to home, which is weird, but I understand. I'd say we remove that link or we leave it for now, we can keep it and see.

> Not sure if there needs to be a link at all or it should link to the receipt page?



I don't see why it should lead back to the same receipt on the receipt page as you proposed here, or am I misunderstanding something you've proposed?

**Comment by dstrukt** [comment]
Would a more clear CTA be adding a `Return to Store` at the bottom of the receipt ..or something equivalent? As I agree, clicking the Order ID (if I follow all of this correctly) to the Store is confusing.
