### ISSUE TITLE
Add Underpaid order support

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#52]
It's been discussed several times on the Slack that there should be the ability to add the support for underpaid orders since some users pay directly from exchanges and even though it rarely happens it would be a very useful feature.

![accept-underpayments-automatically](https://user-images.githubusercontent.com/36959754/36848765-1f27081e-1d5a-11e8-8e62-7d576aceea8e.png)

Previous payment processor we used handled it [in this way.](https://blog.coingate.com/2017/08/bitcoin-merchant-accept-underpaid-orders/)

**Comment by NicolasDorier** [comment]
Very useful link, thanks taking a look.

**Comment by NicolasDorier** [comment]
@astupidmoose this is not an "underpaid" state, but what about having this solution? A way to accept invoices as paid even if a little below what is needed? Would it solve bulks of merchant issue?

**Comment by astupidmoose** [comment]
We have a very slim margin, so even having a 1-2% amount is a huge chunk of our profit and not feasible in our situation. Also, if the payment discrepancy is above this threshold, there is no way for the merchant to know. 

I would much prefer the ability to simply be able to set underpaid to a specific status. From here the merchant will have actions to complete (choose to contact the customer, choose to allow underpaid invoice, refund transaction, etc). 

Thoughts?

**Comment by bitcoinshirt** [comment]
I personally would not mind any of the suggested solutions. Both make sense, automatic accepting will save the time, but I totally get @astupidmoose point about the low margins.

**Comment by astupidmoose** [comment]
If underpaid has the same dropdown status select as the latepaid status, you could technically set the status to go to "processing" in woocommerce. This would emulate the auto acceptance behavior.

**Comment by bitcoinshirt** [comment]
So after talking with @astupidmoose , we agreed that merchants need to be alerted somehow when the order is underpaid and also overpaid.

I know that for overpaid there is "paidOver" in the status exception.

![status exception](https://user-images.githubusercontent.com/36959754/37627500-fd5ad02e-2bd4-11e8-9216-a2cfea683efb.PNG)

@NicolasDorier @lepipele is there the "paidUnder" for underpaid in the status exception?

A proposed solution is : 

1. To have a **percentage** like in the first post where a merchant can set a value even below 1% (ex 0.25%) and the order will be **marked as paid**. Otherwise, the PaidOver or paid under state can trigger "failed" or any other status a merchant set in the Woo plugin. The problem here is that regardless if an order is marked as paid, the merchant would like to be able to be notified somehow that there was an issue.

2. To have a way to **notify the merchant** that the order is underpaid or overpaid. The merchant can choose one of the built in order statuses in in Woocommerce.
If an order is underpaid the merchant will get a status "failed".

3. Merchant will be alerted with a custom order status in Woocommerce Overpaid or Underpaid which will deviate from the [standard woocommerce order statues](https://docs.woocommerce.com/document/managing-orders/) I am really not 100% sure if custom order statuses can cause problems with integrations of woo or cause conflicts with other plugins, that can be an issue here, but there's no way to know this for certain.

I am leaning toward proposal one because it automates the process, but I am not sure how a merchant can be pinged, perhaps some custom warning in the invoices? I'd like to hear what @astupidmoose  thinks.

**Comment by Kukks** [comment]
@bitcoinshirt See https://github.com/btcpayserver/btcpayserver/pull/155
I'm implementing the original goal of this for other reasons( not making users fail a donation because of a mismatch for example) But we can onbiosuly extend it to send notifications when it was paid with a % mismatch  of totalpaid vs totaldue

**Comment by NicolasDorier** [comment]
https://github.com/btcpayserver/btcpayserver/pull/155 implemented the tolerance thanks to @Kukks 

https://github.com/btcpayserver/btcpayserver/commit/7872b3ec55607a103a378af6ba31c6cbb99f384c added a new event: 2000 invoice_expiredPaidPartial which could be used on woocommerce to point to a new state.

**Comment by NicolasDorier** [comment]
Released new version of woocommerce to use this event https://github.com/btcpayserver/woocommerce-plugin/releases/tag/v2.2.21

**Comment by NicolasDorier** [comment]
Closing this as I think it solve all the issues reported by @bitcoinshirt and @astupidmoose
