### ISSUE TITLE
[Bug]: Overpaid shows amount in all cryptocurrencies, not just the one which was used to pay with

### ISSUE THREAD

**Issue by michnovka** [btcpayserver/btcpayserver#5207]
### What is your BTCPay version?

Running 1.11.0

### How did you deploy BTCPay Server?

Lunanode docker

### What happened?

When an invoice is paid with Monero and overpaid, it shows correctly amount paid, due, but not overpaid for BTC:

![image](https://github.com/btcpayserver/btcpayserver/assets/16553087/fe0c80d9-3387-4dd7-b349-f2528ce2a87e)

There was NO overpayment in BTC, so it should say 0 on that line.

Same thing happens vice versa, when overpaid in BTC, it shows the amount in Monero as well:

![image](https://github.com/btcpayserver/btcpayserver/assets/16553087/b5abf529-951e-42db-8dbb-0c57384b41b8)

### How did you encounter this bug?

Happens when multiple cryptocurrencies are accepted and there is an overpayment

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Kukks** [comment]
I believe this is not a bug.  This table shows you a list of payment methods enabled on the invoice, and what would be required to pay in this payment to consider the invoice paid, but also shows what this payment method considers as overpaid in the invoice in its entirety. @NicolasDorier  maybe you can confirm this

**Comment by pavlenex** [comment]
@ndeet Can you try to test and replicate this one please?

**Comment by ndeet** [comment]
@pavlenex can confirm, tested with L-USDT. Imo it should not show BTC or any other currency as overpaid in that case, as there was no payment in any other currency. 

![image](https://github.com/btcpayserver/btcpayserver/assets/1136761/dabdee02-fb6b-4c18-b569-a13a3a2a7d8b)

@Kukks not sure if Liquid related or a general rounding error, mayber related to the last rounding error attempt to fix by @NicolasDorier. I made a 0.01 USD invoice but on scanning the qr code the amount appended by the address was 0.01001664 instead of 0.01000000
(let me know if I should open a separate issue)

**Comment by NicolasDorier** [comment]
I don't believe this is a bug, nor is it a change of behavior compared to previous release.
It basically says: "You can refund by either paying back 0.01 USDT or 0.000000034 BTC". 

In the case of @michnovka "You can refund with 0.00000210 BTC or 0.0003... XMR".

I agree it is confusing though, but unclear what we can do about it.

**Comment by pavlenex** [comment]
> It basically says: "You can refund by either paying back 0.01 USDT or 0.000000034 BTC".

But this is now handled through refund functionality, is there a need to introduce it here? Should only show currency it's paid in imo.

**Comment by tight-sketch** [comment]
Mine is asking me to  pay for my winnings with my Bitcoin. And I can’t at in advance this is my 4th attempt to get you to change my services to  take it out of my winnings

**Comment by NicolasDorier** [comment]
In some case I believe the refund system can't be used. Such as if the reimbursed currency isn't supported in our wallet. (xmr, liquid)
