### ISSUE TITLE
Fix Payjoin constraints limiting widespread adoption

### ISSUE THREAD

**Issue by DanGould** [btcpayserver/btcpayserver#5209]
### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/4960

<sup>Originally posted by **DanGould** May  6, 2023</sup>

The Human Rights Foundation has two separate donation portals. [One to bitcoin cold storage or lightning](https://hrf.org/btc), and [one for payjoin](https://hrf.org/payjoin). One of the great benefits of payjoin is that it fits in unified URIs & QR codes. Separating them defeats the purpose of a unified QR and loses many opportunities to payjoin by default without user knowhow.

They two stores are separated because HRF wants to secure as much as they can with cold storage, and BTCPay Payjoin requires hot wallet only. I see two ways to address this problem.

## Fix 1: Payjoin Output Substitution to Cold Storage

Payjoin output substitution lets the receiver direct inbound funds to any address during receipt without including them in the URI or QR. This works because the sender requests a Payjoin PSBT after offering their input and transfer where the receiver can include new addresses.

If the Payjoin module could request both cold storage addresses and hot wallet addresses, it could consolidate funds to cold storage based on application logic. When a payjoin is incoming, if the incoming amount exceeds a threshold, or if the hot wallet balance does, the Payjoin PSBT could accept inbound sats and send funds to cold storage at once (and keep sats in the hot wallet for future payjoin, too). This solves the custody security problem and allows unified QR to offer payjoin on the same store that typically directs funds to cold storage.

This setup would still require a store owner to create and back up a hot wallet, but banners could guide owners through this setup step to be done by default.

## Fix 2: Use lightning wallet as payjoin (or store-wide) hot wallet

Other than engineering complexity, I see no security reason not to use a lightning capable wallet for both store hot wallet and Payjoin. Combining these wallets would eliminate the need for two stores by HRF and allow BTCPayServer to open lightning channels directly from inbound funds as Payjoin outputs.

However, I acknowledge that internal architecture of BTCPayServer may make this a difficult engineering problem in practice, so I suggest Fix #1 to address the immediate problem and to explore Fix 2 as aspiration to keep in mind as BTCPay develops.

[Nolooking](https://github.com/chaincase-app/nolooking) demonstrates using a payjoin with LND's hot wallet and RPC. LND maintains at least one hot UTXO as anchor which is available to contribute to Payjoin. Nolooking is written to support lightning rpc as an abstraction, so CLN cold be supported in this model too, it just haven't been wired together yet.

**Comment by pavlenex** [comment]
Is there a reason why this needs to be an issue and not an already existing discussion? We tend not to duplicate things, and only have issues as a to-do and something to be tackled.

**Comment by DanGould** [comment]
yes, I wanted to add it to the payjoin roadmap as something that needs to be tackled

**Comment by NicolasDorier** [comment]
> If the Payjoin module could request both cold storage addresses and hot wallet addresses,

It isn't possible, and allowing this in BTCPay would require massive UX and UI changes, as well as backend code.

> Other than engineering complexity, 

This is only the tip of the iceberg, making a UI/UX somebody will understand doing this is out of reach.
Also, BTCPay needs control over wallet, because other wallet API sucks and doesn't provide features we need.

I will close this issue which is way too wide in scope, we can't realistically tackle this.
Even in the event the architecture was in place (which it isn't) to start working on these, it would be significant work that would require each several issues discussing the UI/UX.
