### ISSUE TITLE
[Bug]: products fields does not exist in Point of Sale

### ISSUE THREAD

**Issue by onlineapps-cloud** [btcpayserver/btcpayserver#5214]
### What is your BTCPay version?

BTCPay Server v1.11.1+83536bee8

### How did you deploy BTCPay Server?

mynodebtc

### What happened?

cannot add products in Point of Sale

### How did you encounter this bug?

go to new store, click to store

### Additional information

hi, i updated btcpay server to latest version, but option to add products in store is missing, i tried to login in incognito mode, not help.
![image](https://github.com/btcpayserver/btcpayserver/assets/69077240/d8b4da27-4676-4b3d-a056-f143dddba93a)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by onlineapps-cloud** [comment]
products option was betwen description and checkout, where is now?

**Comment by onlineapps-cloud** [comment]
i downgraded to BTCPay Server v1.10.3+983b8c1f5 
![image](https://github.com/btcpayserver/btcpayserver/assets/69077240/40287988-6f8a-435a-bf79-40154e9a7e8d)
and option appear as expected, please investigate, best regards

**Comment by Kukks** [comment]
Please post browser logs

**Comment by onlineapps-cloud** [comment]
hi, today i will paste logs

**Comment by pavlenex** [comment]
Seems related to #5226

**Comment by dennisreimann** [comment]
@onlineapps-cloud are you using the file seller plugin? If so, this is the same error as in #5226.
