### ISSUE TITLE
[Bug]: POS when adding category to items, shop + cart view breaks

### ISSUE THREAD

**Issue by Bas02** [btcpayserver/btcpayserver#5217]
### What is your BTCPay version?

BTCPay Server v1.11.1

### How did you deploy BTCPay Server?

Lunanode

### What happened?

Created a PoS product list + cart. 

Added categories to all items, saved, viewed the store. 

Store layout breaks see Screenshots. Clicking the Buy button, does not deliver any action or bring up the actual cart. 
When there's no items in the cart, the cart should still be there on the right hand side of the screen? It's currently not for me. 

### How did you encounter this bug?

Created a PoS product list + cart. 

Added categories to all items, saved, viewed the store. 

Store layout breaks see Screenshots. 

### What browser do you use?

Latest Safari and Latest Firefox

### Additional information

<img width="857" alt="Screenshot 2023-07-31 at 19 42 23" src="https://github.com/btcpayserver/btcpayserver/assets/102448109/89491ae5-3f69-4778-8f62-c1ba0805b846">

<img width="979" alt="Screenshot 2023-07-31 at 19 38 56" src="https://github.com/btcpayserver/btcpayserver/assets/102448109/3e8e60c1-74b6-4983-86a3-ca87486e58d4">

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Bas02** [comment]
Yezzir I can. This was recorded on safari. 
I've not added the category to every item this time just the first two in standard TeaShop 

https://github.com/btcpayserver/btcpayserver/assets/102448109/d42e0fbc-23a7-4bc7-a55c-a17a0c90a3b5

**Comment by Bas02** [comment]
Another thing that seems to happen is when I take out the categories, they still show up in the store view. 


https://github.com/btcpayserver/btcpayserver/assets/102448109/539e957d-050f-4ba5-a4c6-53877385c89d

**Comment by dstrukt** [comment]
Wow, tried to repro exactly on Safari, and no issues.

The second issue, I'm not sure what's going on...

Going to continue to test.

**Comment by Bas02** [comment]
> The second issue, I'm not sure what's going on...

I dunno what happens in the second one either, created multiple new stores just now, only happened once.

**Comment by Goro2030** [comment]
I'm seeing the same issue, both using EDGE or Chroe ... an "artifact" appears before the product, that's : "]"="">

Look:
![image](https://github.com/btcpayserver/btcpayserver/assets/10875290/0e747cec-f3b0-46b6-9119-8e2830eb8ad3)
