### ISSUE TITLE
[Bug]: GetStoreLightningNetworkPaymentMethod always returns insufficient permissions

### ISSUE THREAD

**Issue by celldra** [btcpayserver/btcpayserver#5219]
### What is your BTCPay version?

BTCPay Server v1.11.1+83536bee8 (Altcoins)

### How did you deploy BTCPay Server?

I'm running BTCPayServer on a Hetzner dedicated instance, although the system used to call the API is on my physical machine, BTCPayServer is on the Hetzner server.

### What happened?

It seems that the permissions checker is somewhat broken when it comes to managing the Lightning Network Payment Methods. No matter what API permissions I grant the key, including the ones it asks for, it always returns the following exception:

```
BTCPayServer.Client.GreenfieldAPIException: Insufficient API Permissions. Please use an API key with permission "btcpay.store.canmodifystoresettings". You can create an API key in your account's settings / Api Keys.
```

Here is a screenshot of the API key permissions
![image](https://github.com/btcpayserver/btcpayserver/assets/124086032/45e8b259-8545-467e-b651-73e66cb78171)

The endpoints I've tested and gotten this error are `GetStoreLightningNetworkPaymentMethod` which is a Greenfield C# API call to `api/v1/stores/{storeId}/payment-methods/LightningNetwork/{cryptoCode}`.

The specified crypto code in this instance is `btc`.

My code to call the API, looks like the following:
![image](https://github.com/btcpayserver/btcpayserver/assets/124086032/48f033ea-95cd-4a4c-a59d-b68326873cf0)

And the code to initialise the client:
![image](https://github.com/btcpayserver/btcpayserver/assets/124086032/efeb8510-7b3e-475b-a8d5-57fd3c870738)

Finally, the `HttpClient` code:
![image](https://github.com/btcpayserver/btcpayserver/assets/124086032/9983a01c-7e24-45f7-a6a7-2ab978604883)

### How did you encounter this bug?

1. Created an API key with all permissions but manage API keys
2. Attempted to call `GetStoreLightningNetworkPaymentMethod` using the API key
3. The API client throws an exception stating that there are `Insufficient API permissions`, although the key has the permissions it is asking for

### Relevant log output

```shell
BTCPayServer.Client.GreenfieldAPIException: Insufficient API Permissions. Please use an API key with permission "btcpay.store.canmodifystoresettings". You can create an API key in your account's settings / Api Keys.
         at BTCPayServer.Client.BTCPayServerClient.HandleResponse(HttpResponseMessage message)
         at BTCPayServer.Client.BTCPayServerClient.HandleResponse[T](HttpResponseMessage message)
         at BTCPayServer.Client.BTCPayServerClient.GetStoreLightningNetworkPaymentMethod(String storeId, String cryptoCode, CancellationToken token)
```

### What browser do you use?

Chromium Version 114.0.5735.198 (Official Build, ungoogled-chromium) Linux (64-bit)
Greenfield API wrapper (built from source, not NuGet), version 1.7.5? (it has not been modified at all)
.NET version 7.0.109
Host OS: Arch Linux - 6.1.39-1-lts x86_64
Server OS: Rocky Linux 8.8 - 4.18.0-477.15.1.el8_8 x86_64

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
Checking this one

**Comment by NicolasDorier** [comment]
I tested on our mainnet, and it worked as expected.

```csharp
var apikey = "....";
string url = "https://mainnet.demo.btcpayserver.org/";
var storeId = "...";
var client = new BTCPayServerClient(new Uri(url), apikey, new System.Net.Http.HttpClient());
var method = await client.GetStoreLightningNetworkPaymentMethod(storeId, "BTC");
```

Note that the node is internal node in my case.

**Comment by NicolasDorier** [comment]
@celldra maybe the difference is in the version of the library I am using. I just bumped the library's version on nuget. Can you bump it and try again?

**Comment by celldra** [comment]
Hi there, I was using a git build of the library instead of NuGet since it hadn't been updated for a while. I can try installing it through NuGet to see if it makes a difference. I will get back to you

**Comment by NicolasDorier** [comment]
@celldra any news?
