### ISSUE TITLE
[Bug]: PoS cart does not show on mobile

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#5224]
### What is your BTCPay version?

BTCPay Server 1.11.1

### How did you deploy BTCPay Server?

docker

### What happened?

On PoS with cart view on mobile the top right cart icon does nothing.

### How did you encounter this bug?

- on mobile device or small screen
- go to PoS with cart 
- add item to cart
- try to open cart by clicking top right cart icon

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by elvece** [comment]
+1
