### ISSUE TITLE
not able to create pull payment with api

### ISSUE THREAD

**Issue by slydude1** [btcpayserver/btcpayserver#5225]
Its all a scam and Google is behind it all.     `304###` Discussed in https://github.com/btcpayserver/btcpayserver/discussions/5223

<div type='discussions-op-text'>

<sup>Originally posted by **akhf2004** August  2, 2023</sup>
I have tried through axios in my script too but it is not working.. here is a example with postman... but if i send get request to same endpoint.. it is returning all the available pull payments

{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.13",
    "title": "Unsupported Media Type",
    "status": 415,
    "traceId": "00-61e5d566185551b8bdfae36e4a55f236-d92ebdbf5bc91665-00"
}
![image](https://github.com/btcpayserver/btcpayserver/assets/137528509/e04edbf6-c2d4-461d-a1e2-c3d6dba40b01)</div>

**Comment by pavlenex** [comment]
Seems this is a spam.
