### ISSUE TITLE
AspNet.Core 2.1.6 or 2.1.4?

### ISSUE THREAD

**Issue by bolatovumar** [btcpayserver/btcpayserver#523]
Documentation [here](https://github.com/btcpayserver/btcpayserver#how-to-build) specifies .NET Core v2.1.4 while the .csproj file specifies v2.1.6 ([see here](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/BTCPayServer.csproj#L72)). Are these things referring to the same thing but the versions are in conflict? Or am I missing something here?

**Comment by Kukks** [comment]
So, we currently run .net core 2.1, I think specifically we use 2.1.500 SDK but the other newer ones (2.1.502 and 2.1.503) might work too. 

So it is v2.1.6 for now. We plan to update on the .net core 3 release.

**Comment by bolatovumar** [comment]
Should the documentation be updated to say to use v2.1.6 instead of v2.1.4 then?
