### ISSUE TITLE
[Bug]: Allignment of custom amount (only) shops is not centered anymore

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#5230]
### What is your BTCPay version?

 © BTCPay Server v1.11.1+83536bee8 

### How did you deploy BTCPay Server?

Docker

### What happened?

I opened my own donation page and found that the input box for the custom amount isn't centered anymore:
https://coffee.petzsch.eu/

### How did you encounter this bug?

see above

### Relevant log output

```shell
none
```

### What browser do you use?

Chrome and Firefox

### Additional information

none

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
@petzsch Can you check if updating to v1.11.2 fixes this for you? If so, we can close this.
