### ISSUE TITLE
Delete custom labels

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#5237]
### What is your BTCPay version?

BTCPay Server 1.11.1 + 1.10.3

### How did you deploy BTCPay Server?

docker

### What happened?

On the wallet transaction list there seems no way to delete labels after they were assigned to transactions.

### How did you encounter this bug?

- Go to bitcoin wallet transaction list
- Add label
- Try to remove label

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
@petzsch can you try to replicate this?

**Comment by petzsch** [comment]
Can confirm: I'm also unable to remove a label once I've added it to a tx.

Something like a small X when hovering over a label would be helpful.

**Comment by dennisreimann** [comment]
Maybe it's too simple to even notice, because you can just use the backspace/delete key. You can also select  and then remove it.

![g](https://github.com/btcpayserver/btcpayserver/assets/886/35c7aeec-8c63-4031-94e9-d3b33a3f3001)

**Comment by petzsch** [comment]
current UI for deleting labels seems a bit unintiuitiv. I also think we should consider changing it.

The little x which shows on hover which I originally proposed, might not work for mobile users.
personal opinion: Delete on click sounds about right to me.

Or is there any other functionality (planned) with selected labels that we needed the selected state for?

**Comment by Terryman7306** [comment]
OK I'm lost I'm new and don't even know what my wallet is lol I need lot's of help
