### ISSUE TITLE
[Bug]: Invoice details pos metadata not parsed anymore

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#5240]
### What is your BTCPay version?

BTCPay 1.11.1 (same with 1.10.3)

### How did you deploy BTCPay Server?

docker

### What happened?

The PoS metadata set via API was always rendered in a nice way in the past, this seems to have gone missing. Not sure if deliberately or just a sideeffect of another change.

![image](https://github.com/btcpayserver/btcpayserver/assets/1136761/8e5d0540-5b99-4249-ac86-13feb9a1b59c)

### How did you encounter this bug?

- Set PoS metadata via the API
- Visit invoice details page

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
@NicolasDorier It seems like the `posData` is now stored as a string instead of the raw JSON. Might this be something that changed with 0a78846e8d50a7d50b2d9a84b04706f3794571a6?

**Comment by dennisreimann** [comment]
I think so, because the `PosData` and `PosDataLegacy` properties get [treated differently](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Services/Invoices/InvoiceEntity.cs#L151).

**Comment by NicolasDorier** [comment]
@ndeet I can't reproduce. Can I see your client code?

**Comment by petzsch** [comment]
I've noticed the same for my implementations.

I [pack 3 possible return_url's in the posData](https://github.com/petzsch/btcpay-logicboxes/blob/main/index.php#L102) and they used to be rendered as a table in the invoice details view. However now they are just displayed as text:

![grafik](https://github.com/btcpayserver/btcpayserver/assets/1374810/519a73ff-4e11-47cc-bf27-c1415cba92c1)

It's been like this since a couple of versions already. Can't say for certain when it changed.

**Comment by NicolasDorier** [comment]
@petzsch `json_encode` is converting the object into a string?

**Comment by petzsch** [comment]
returns a string or false: https://www.php.net/manual/en/function.json-encode.php

**Comment by NicolasDorier** [comment]
Additional Information is showing the whole metadata as a Json object. So indeed, if you set a string it will show as a string.

**Comment by NicolasDorier** [comment]
The thing I could do is to treat PosData as special, and do conversion from string to JSON object only for this page... unsure it's a good idea though. Rather, the clients shouldn't encode string in PoSData.

**Comment by petzsch** [comment]
ommitting json_encode and json_decode when reading it, leads to a correct rendered table view:
![grafik](https://github.com/btcpayserver/btcpayserver/assets/1374810/9cd7501d-027b-4ede-8196-cfccb7bd83cc)

Maybe that is all that @ndeet needs to do as well.

**Comment by ndeet** [comment]
The problem seems that it worked before if the posData itself was an escaped JSON string, see this example payload:
```
{
    "metadata": {
        "metaone": "metavalue",
        "posData": "{\"WooCommerce\":{\"Order ID\":746,\"Order Number\":\"746\",\"Order URL\":\"https:\\\/\\\/btcpaywp.ddev.site\\\/wp-admin\\\/post.php?post=746&action=edit\",\"Plugin Version\":\"2.2.2\"}}"
    },
    "receipt": {
        "enabled": true
    },
    "amount": "5.00",
    "currency": "USD"
}
```

**Comment by ndeet** [comment]
It used to not work the other way around it seems, there is no reason why we would have especially encoded the posData and not used just built a nested array in PHP and encode the whole thing. Seems this was not possible before and we needed to encode the posData otherwise it did not work. Not sure if it is good to do a bc break now, we could update all integrations but then again there will be various other implementations out there maybe. I would wait for this for a Greenfield v2 probably or make both ways work for now if possible?

**Comment by Kukks** [comment]
> The thing I could do is to treat PosData as special, and do conversion from string to JSON object only for this page... unsure it's a good idea though. Rather, the clients shouldn't encode string in PoSData.

Yes, but that's a breaking change for integrations, as it has always been requested as a string, and the bitpay API does so too

**Comment by ndeet** [comment]
> Yes, but that's a breaking change for integrations, as it has always been requested as a string, and the bitpay API does so too

Ah nice one of those strange bitpay API "features". Agree we should not do a breaking change here and keep the old weird way working until Greenfield v2

**Comment by NicolasDorier** [comment]
Notes that the "breaking change" is only at the UI level for the invoice details.
