### ISSUE TITLE
[Bug]: [API] GetInvoices Call only returns settled invoices

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#5244]
### What is your BTCPay version?

BTCPay Server v1.11.1+83536bee8

### How did you deploy BTCPay Server?

Docker

### What happened?

I've used this API call:
https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Invoices_GetInvoices

on my test store which has plenty of Settled and Expired invoices. When querring the endpoint, I only get a result for status=Settled.

This issue was brought up by a user in [Telegram](https://t.me/btcpayserver/61504).

### How did you encounter this bug?

see the provided screenshots:

![grafik](https://github.com/btcpayserver/btcpayserver/assets/1374810/1059c00a-7a2b-4aec-9a81-754afa2dd2f8)

![grafik](https://github.com/btcpayserver/btcpayserver/assets/1374810/7cdb25bf-97b5-4ee3-a0d5-f36a4e4f2f73)

![grafik](https://github.com/btcpayserver/btcpayserver/assets/1374810/6be6a580-8599-4057-86a7-08ad1482b699)

### Relevant log output

```shell
none
```

### What browser do you use?

Firefox + Postman

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by ndeet** [comment]
Damn, Dennis is so fast :tada:
