### ISSUE TITLE
When clicking on `view` payment request link it adds store ID in the link which is unnecessary 

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5253]
When you create a new payment request and click on the link to preview it it it appends `storeId=xxxxx` and makes link you're sharing with a potential client uglier, there's no need to append store id there.

![Screenshot 2023-08-11 at 16 32 09](https://github.com/btcpayserver/btcpayserver/assets/36959754/5308b025-dd9d-49e3-97a2-0f6f07db1f4c)

**Comment by dstrukt** [comment]
I'll take this one.
