### ISSUE TITLE
Create a new invoice via Api will set status Settled

### ISSUE THREAD

**Issue by esteban2006** [btcpayserver/btcpayserver#5257]
### What is your BTCPay version?

I am running BTC pay 1.10.3

### How did you deploy BTCPay Server?

1. apt-get update && apt-get install -y git
2. git clone https://github.com/btcpayserver/btcpayserver-docker
3. cd btcpayserver-docker
4. export NBITCOIN_NETWORK="mainnet"
5. export BTCPAYGEN_CRYPTO1="btc"
6. export BTCPAYGEN_LIGHTNING="lnd"
7. export ACME_CA_URI="https://acme-v01.api.letsencrypt.org/directory"
8. ssh-keygen -t rsa -f /root/.ssh/id_rsa_btcpay -q -P ""
9. echo "# Key used by BTCPay Server" >> /root/.ssh/authorized_keys
10. cat /root/.ssh/id_rsa_btcpay.pub >> /root/.ssh/authorized_keys
11. export BTCPAY_HOST_SSHKEYFILE=/root/.ssh/id_rsa_btcpay
12. export BTCPAY_HOST="my host.com"
13. export LETSENCRYPT_EMAIL="[nicolas.dorier@example.com](mailto:nicolas.dorier@gmail.com)"
14. export BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-save-storage-s"
15. . ./btcpay-setup.sh
16. . ./btcpay-setup.sh -i

### What happened?

calling https://myDomian.com/api/v1/stores/{storeId}/invoices
will perfectly generate the invoice response status new , but sets the status settled at the same time

now check the image from ther server 

![btcPaySettingStatus](https://github.com/btcpayserver/btcpayserver/assets/11742223/ebcad2bc-d3ee-4277-85df-5708d2fff8c2)

### How did you encounter this bug?

buy calling my api method 

### Relevant log output

```shell
invoice creation response 



{'additionalStatus': 'None',
 'amount': '201',
 'archived': False,
 'availableStatusesForManualMarking': ['Settled', 'Invalid'],
 'checkout': {'checkoutType': None,
              'defaultLanguage': None,
              'defaultPaymentMethod': 'BTC',
              'expirationMinutes': 10,
              'lazyPaymentMethods': None,
              'monitoringMinutes': 15,
              'paymentMethods': ['BTC'],
              'paymentTolerance': 100.0,
              'redirectAutomatically': True,
              'redirectURL': 'localhost:5000/payed-successfuly',
              'requiresRefundEmail': None,
              'speedPolicy': 'HighSpeed'},
 'checkoutLink': 'https://myDomiancom/i/Wa1xtNN3sykmY99LjNNFrT',
 'createdTime': 1691804518,
 'currency': 'USD',
 'expirationTime': 1691805118,
 'id': 'Wa1xtNN3sykmY99LjNNFrT',
 'metadata': {'Request Origen': {'city': 'San',
                                 'country': 'El',
                                 'ip': '',
                                 'region': 'Departamento'},
              'buyerAddress1': 'direccion 01',
              'buyerAddress2': 'Direccion 02',
              'buyerCity': 'Santa xxx',
              'buyerCountry': 'El',
              'buyerName': 'Taimoor ',
              'buyerPhone': 'xxxxxxxxxxxxx',
              'orderId': 'DEOCT-9yjldZBnE'},
 'monitoringExpiration': 1691806018,
 'receipt': {'enabled': True, 'showPayments': True, 'showQR': True},
 'status': 'New',
 'storeId': 'xxxxxxxxxxxxxxxxxxxxxxxxx',
 'type': 'Standard'}
```

invoice status 

```

{'additionalStatus': 'None',
 'amount': '201',
 'archived': False,
 'availableStatusesForManualMarking': [],
 'checkout': {'checkoutType': None,
              'defaultLanguage': None,
              'defaultPaymentMethod': 'BTC',
              'expirationMinutes': 10,
              'lazyPaymentMethods': None,
              'monitoringMinutes': 15,
              'paymentMethods': ['BTC'],
              'paymentTolerance': 100.0,
              'redirectAutomatically': True,
              'redirectURL': 'localhost:5000/payed-successfuly',
              'requiresRefundEmail': None,
              'speedPolicy': 'HighSpeed'},
 'checkoutLink': 'https://xxxxxxxxxxxxxx.com/i/Wa1xtNN3sykmY99LjNNFrT',
 'createdTime': 1691804518,
 'currency': 'USD',
 'expirationTime': 1691805118,
 'id': 'Wa1xtNN3sykmY99LjNNFrT',
 'metadata': {'Request Origen': {'city': 'San xxxxxx',
                                 'country': 'El xxxxxxxxxx',
                                 'ip': 'xxxxx',
                                 'region': 'Departamento xxx'},
              'buyerAddress1': 'direccion 01',
              'buyerAddress2': 'Direccion 02',
              'buyerCity': 'Santa x',
              'buyerCountry': 'El x',
              'buyerName': 'Taimoor ',
              'buyerPhone': 'xxxxxxxxxxxxxx',
              'orderId': 'DEOCT-9yjldZBnE'},
 'monitoringExpiration': 1691806018,
 'receipt': {'enabled': True, 'showPayments': True, 'showQR': True},
 'status': 'Settled',
 'storeId': 'xxxxxxxxxxxxxxxxxxxxxxxxxx',
 'type': 'Standard'}
```
```


### What browser do you use?

Chrome and Opera

### Additional information

this happened after updating to the latest verrsion

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by esteban2006** [comment]
I have noticed that pasisng amount as 0 will create the invoice as new, on the contrary passing amount as any other value will return status Settled


![btcPaySettingStatus01](https://github.com/btcpayserver/btcpayserver/assets/11742223/85d1451d-ac37-46ee-83b6-ed9c895e042f)



this is my data payload

```
   data = json.dumps({
        "metadata": {
            "orderId" : orderId,
            "buyerName": buyerName,
            "buyerAddress1": str(buyerAddress1),
            "buyerAddress2": str(buyerAddress2),
            "buyerCity": str(buyerCity),
            "buyerCountry": str(buyerCountry),
            "buyerPhone": str(buyerPhone),
            "Request Origen": self.getUserLocation()},
        "checkout": {
            "speedPolicy": "HighSpeed",
            "paymentMethods": ["BTC"],
            "defaultPaymentMethod": "BTC",
            "expirationMinutes": expirationMinutes,
            "monitoringMinutes": 15,
            "paymentTolerance": 100,
            "redirectURL": 'localhost:5000/payed-successfuly',
            "redirectAutomatically": True,
            "requiresRefundEmail": None,
            "checkoutType": None,
            "defaultLanguage": None},
        "receipt": {
            "enabled": True,
            "showQR": True,
            "showPayments": True},
        "amount": str(amount),
        "currency": "USD",
        "additionalSearchTerms": additionalSearchTerms,
        "availableStatusesForManualMarking" : ["None" "PaidLate" "PaidPartial" "Marked" "Invalid" "PaidOver"],
        "status" : ["New" "Processing" "Expired" "Invalid" "Settled"]
        })
```

**Comment by esteban2006** [comment]
Found the problem 

"redirectAutomatically": True,

will set the status settle by default

**Comment by dennisreimann** [comment]
I'd suspect the `"paymentTolerance": 100` is the problem. We recently had someone else [reporting the same problem on Telegram](https://t.me/btcpayserver/61490) — do we have this in the docs somewhere, giving a bad example of how it should be used?

**Comment by esteban2006** [comment]
ok, I am debbuging and sharing 

1. current state of the server options, the problem was in the  api payload being passed

![btcPaySettingStatus03](https://github.com/btcpayserver/btcpayserver/assets/11742223/f7539327-0708-4428-8af3-e932ce4c58cc)

2. same payload as mention before, just modifying , "paymentTolerance":  to "paymentTolerance": 0.2

![btcPaySettingStatus04](https://github.com/btcpayserver/btcpayserver/assets/11742223/f491ce05-10b3-469e-9cbe-7670166f78d3)

3. result: successfull
4. Conclusion: your response is correct, setting "paymentTolerance" : 100 will make the api set the invoice as Settled, as the value set to pay will be already 100% tolarated.
5. Recommendation: users expecting to have full payment amount will have to set "paymentTolerance": 0
