### ISSUE TITLE
[Bug]: LNbank.AccessKey was challenged

### ISSUE THREAD

**Issue by strnly** [btcpayserver/btcpayserver#5259]
### What is your BTCPay version?

BTCPay Server v1.11.1

### How did you deploy BTCPay Server?

VPS. Digital Ocean. CLN.

### What happened?

LNBank wallet is no longer rendered in our front end / UI where we call GET LN wallet. The wallet (LN Bank) works fine and can be accessed via the BTCpay UI but the API call  https://docs.btcpayserver.org/API/Greenfield/v1/#operation/ApiKeys_CreateUserApiKey   seems broken.

we use authorization through the API key, but now it has stopped working. The documentation also lost the possibility of authorization through the API key.
https://prnt.sc/ltsmzgkR1C7k

We wanted to make an API key with new permission, but got an error ‘Invalid permission string’
https://prnt.sc/eTf4oSNlLZ9D

Regarding authentication. In the Logs, we get 

LNbank.AccessKey was challenged.

### How did you encounter this bug?

LNBank wallet is no longer rendered in our front end / UI where we call GET LN wallet. The wallet (LN Bank) works fine and can be accessed via the BTCpay UI but the API call  https://docs.btcpayserver.org/API/Greenfield/v1/#operation/ApiKeys_CreateUserApiKey   seems broken.

we use authorization through the API key, but now it has stopped working. The documentation also lost the possibility of authorization through the API key.
https://prnt.sc/ltsmzgkR1C7k

We wanted to make an API key with new permission, but got an error ‘Invalid permission string’
https://prnt.sc/eTf4oSNlLZ9D

Regarding authentication. In the Logs, we get 

LNbank.AccessKey was challenged.

### Relevant log output

```shell
2023-08-14 00:54:31.440 +00:00 [INF] AuthenticationScheme: LNbank.AccessKey was challenged.
2023-08-14 00:54:44.412 +00:00 [INF] AuthenticationScheme: LNbank.AccessKey was challenged.
2023-08-14 01:05:17.829 +00:00 [INF] AuthenticationScheme: LNbank.AccessKey was challenged.
```

### What browser do you use?

Safari. Chromium
 Brave. Firefox

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
> LNBank wallet is no longer rendered in our front end / UI where we call GET LN wallet.

Can you check the BTCPay Server container logs for exceptions?

> The wallet (LN Bank) works fine and can be accessed via the BTCpay UI but the API call https://docs.btcpayserver.org/API/Greenfield/v1/#operation/ApiKeys_CreateUserApiKey seems broken.

[LNbank access keys](https://docs.btcpayserver.org/API/Greenfield/v1/#section/Authentication/LNbank_Access_Key) aren't the same as BTCPay API Keys. A LNbank access key can be created via the LNbank wallet settings.

**Comment by strnly** [comment]
You can close this issue. I figured that out. 

You did changes to the authentication API during past release. That was not super obvious. Thanks

**Comment by strnly** [comment]
You can close this issue. I figured that out.

You did changes to the authentication API during past release. That was not super obvious. Thanks
