### ISSUE TITLE
The button to return to PoS redirects to main page

### ISSUE THREAD

**Issue by Kixunil** [btcpayserver/btcpayserver#526]
When the invoice is paid or expired, a button to return to <app name> is provided, but instead of returning to PoS, it returns to main page. This is highly undesirable for PoS, as it's not only confusing, but returning to actual PoS is needed, to avoid additional clicks between each payment.

**Comment by pavlenex** [comment]
I agree this is not a good UX.
As a temporally workaround, you can go to Store Settings >  General Settings > Store website and add the link to your PoS app, that should take care of the redirecting back to the PoS.

![2019-01-14_17-04-53](https://user-images.githubusercontent.com/36959754/51124614-03e67b00-181f-11e9-88eb-ae4461342a8d.png)

**Comment by Kixunil** [comment]
It helped, than you!

I'm leaving this open in order to track making it the default behavior.

**Comment by Kukks** [comment]
Thanks for reporting, PR incoming

**Comment by hubiktomas** [comment]
Just one note - PoS has a feature to be hosted externally, so careful about the redirect in this case.
