### ISSUE TITLE
[Bug]: The redirect url provided within the checkout object to the endpoint for creating invoices isn't recognized by the server.

### ISSUE THREAD

**Issue by nemanja-z** [btcpayserver/btcpayserver#5262]
### What is your BTCPay version?

I'm running BTCPay Server v1.11.2+1c5fcfe09

### How did you deploy BTCPay Server?

Docker

### What happened?

The redirect URL cannot be specified via the Greenfield API. The API response returns null for this field.

### How did you encounter this bug?

1. Send POST request to serverUrl/api/v1/stores/{storeId}/invoices 2. Request body included checkout object with redirectURL field 3. Redirect url wasn't listed in the response 4. Return to the store button on the checkout page wasn't displayed

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by petzsch** [comment]
Couldn't repro on my end (yet).

The following snippet creates an Invoice using the PHP Greenfield Toolkit and the resulting invoice redirects as expected to the returnurl.php?....

I'll have a closer look at the returned invoice object... usually don't utlize those besides storing the invoiceID.

```php
$metadata = [
    'buyerCountry' => $country_code,
    'itemDesc' => $description,
    'itemCode' => $transid,
    'posData' => json_encode($link_array)
];

$checkoutOptions = new InvoiceCheckoutOptions();
$checkoutOptions
   ->setSpeedPolicy($checkoutOptions::SPEED_MEDIUM)
   ->setRedirectURL('https://' . $_SERVER['HTTP_HOST'] . '/returnurl.php?invoice_id={InvoiceId}');

try{
   $invoice = $client->createInvoice(
      $storeid,
       "USD",
      PreciseNumber::parseString($sellingcurrencyamount),
      (string)$transid,
      $user_email,
      $metadata,
      $checkoutOptions
   );
} catch (\Throwable $e) {
   echo "Error: " . $e->getMessage();
   exit(1); // don't continue if a error occours
}

header("Location: ".$invoice->getData()['checkoutLink']);
```

**Comment by nemanja-z** [comment]
You are right. It's my bad. Checkout object somehow ended up outside body. That's why it didn't work.
