### ISSUE TITLE
Crowdfunding app "awaiting payment" pop up is not working

### ISSUE THREAD

**Issue by guiguy2018** [btcpayserver/btcpayserver#527]
I'm having a problem getting the crowdfunding app to work properly.
    
From Btcpay server top menu, if I click invoices, create new invoice, the ‘awaiting payment’ pop up  appears when I go to checkout.

Similarly from BTCPay server top menu if I click apps, store settings, invoices generated by app, create new invoice , I also get the ‘awaiting payment’ pop up when I go to checkout.

However, when I click on apps and view, the crowdfunding payment screen appears but when I try to contribute and enter amount the ‘awaiting payment’ pop up does NOT appear when I click continue.

Mr Kukks suggested that websockets are used in the crowdfunding app and that something is blocking the websocket.  

My setup is a bit unconventional.   I have the standard BTCPay docker installed in a virtual machine and a separate nginx operating as reverse proxy on another vm (listening on 80 and 443).  The reverse proxy sends traffic by proxy pass according to the server name I use for BTCPay server.  All this works well including https traffic and letsencrypt certificates.

So if it is a blocked websocket problem, can I configure the nginx reverse proxy (not the Docker nginx) to get the websockets redirected?  Anyone got any other suggestions?

Thanks!

**Comment by guiguy2018** [comment]
seems sorted now, by inserting websocket support in nginx reverse proxy

    # WebSocket support
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

I now get the awaiting payment pop up

**Comment by NicolasDorier** [comment]
By doing this, you also fix ledger support (https://docs.btcpayserver.org/faq-and-common-issues/faq-wallet#why-is-my-ledger-not-detected-by-btcpay-server)

**Comment by crashmax** [comment]
Just testet 

> seems sorted now, by inserting websocket support in nginx reverse proxy
> 
> ```
> # WebSocket support
> proxy_http_version 1.1;
> proxy_set_header Upgrade $http_upgrade;
> proxy_set_header Connection "upgrade";
> ```
> I now get the awaiting payment pop up

Hi, I have the same issue. With this solution Crowdfund App is working, but now PoS App is not working anymore. Any ideas? Thx.

**Comment by NicolasDorier** [comment]
What does not work exactly? What happen on the PoS app?

**Comment by crashmax** [comment]
I can insert the amount and click the pay button. After that, no QR Code is shown. Page gets blank. I'm using iframes.

**Comment by crashmax** [comment]
This is my Nginx derective:
location ~ / {
	proxy_set_header        Host $host;
	proxy_set_header        X-Real-IP $remote_addr;
	proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header        X-Forwarded-Proto $scheme;
	proxy_redirect          http:// https://;
	proxy_pass              http://0.0.0.0:23000;
	proxy_http_version 1.1;
	proxy_request_buffering off;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "upgrade";
}

**Comment by NicolasDorier** [comment]
what is giving Error 400 exactly?

**Comment by crashmax** [comment]
I got only this one:
Failed to load resource: the server responded with a status of 400 (Bad Request)

**Comment by NicolasDorier** [comment]
Can you try to have this

```
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
proxy_set_header Host $http_host;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
```

Do not put it in the `location` block, but globally.

**Comment by crashmax** [comment]
Thank you. Just tried, but no luck.

I got some more informations though.

[2019-03-22T14:02:24.723Z] Information: Normalizing '/apps/hub' to 'https://btcpay.tobg.com.de/apps/hub'.
crowdfund:1 Unchecked runtime.lastError: The message port closed before a response was received.
crowdfund-bundle-1.min.js?v=mulVxjyLncjx5MLBrApxllCMkW1MAjlx_tHlsp-uAmQ:39 WebSocket connection to 'wss://btcpay.tobg.com.de/apps/hub?id=9GdqMnsDtHgSRW4x44eCxw' failed: Error during WebSocket handshake: Unexpected response code: 200
(anonymous) @ crowdfund-bundle-1.min.js?v=mulVxjyLncjx5MLBrApxllCMkW1MAjlx_tHlsp-uAmQ:39
(anonymous) @ crowdfund-bundle-1.min.js?v=mulVxjyLncjx5MLBrApxllCMkW1MAjlx_tHlsp-uAmQ:39
s @ crowdfund-bundle-1.min.js?v=mulVxjyLncjx5MLBrApxllCMkW1MAjlx_tHlsp-uAmQ:39
(anonymous) @ crowdfund-bundle-1.min.js?v=mulVxjyLncjx5MLBrApxllCMkW1MAjlx_tHlsp-uAmQ:39
(anonymous) @ crowdfund-bundle-1.min.js?v=mulVxjyLncjx5MLBrApxllCMkW1MAjlx_tHlsp-uAmQ:39
e @ crowdfund-bundle-1.min.js?v=mulVxjyLncjx5MLBrApxllCMkW1MAjlx_tHlsp-uAmQ:39
n.connect @ crowdfund-bundle-1.min.js?v=mulVxjyLncjx5MLBrApxllCMkW1MAjlx_tHlsp-uAmQ:39
(anonymous) @ crowdfund-bundle-1.min.js?v=mulVxjyLncjx5MLBrApxllCMkW1MAjlx_tHlsp-uAmQ:39
s @ crowdfund-bundle-1.min.js?v=mulVxjyLncjx5MLBrApxllCMkW1MAjlx_tHlsp-uAmQ:39
(anonymous) @ crowdfund-bundle-1.min.js?v=mulVxjyLncjx5MLBrApxllCMkW1MAjlx_tHlsp-uAmQ:39
(anonymous) @ crowdfund-bundle-1.min.js?v=mulVxjyLncjx5MLBrApxllCMkW1MAjlx_tHlsp-uAmQ:39
e @ crowdfund-bundle-1.min.js?v=mulVxjyLncjx5MLBrApxllCMkW1MAjlx_tHlsp-uAmQ:39
n.createTransport @ crowdfund-bundle-1.min.js?v=mulVxjyLncjx5MLBrApxllCMkW1MAjlx_tHlsp-uAmQ:39
(anonymous) @ crowdfund-bundle-1.min.js?v=mulVxjyLncjx5MLBrApxllCMkW1MAjlx_tHlsp-uAmQ:39
s @ crowdfund-bundle-1.min.js?v=mulVxjyLncjx5MLBrApxllCMkW1MAjlx_tHlsp-uAmQ:39
(anonymous) @ crowdfund-bundle-1.min.js?v=mulVxjyLncjx5MLBrApxllCMkW1MAjlx_tHlsp-uAmQ:39
o @ crowdfund-bundle-1.min.js?v=mulVxjyLncjx5MLBrApxllCMkW1MAjlx_tHlsp-uAmQ:39
crowdfund-bundle-1.min.js?v=mulVxjyLncjx5MLBrApxllCMkW1MAjlx_tHlsp-uAmQ:39 [2019-03-22T14:02:25.104Z] Error: Failed to start the transport 'WebSockets': null

**Comment by NicolasDorier** [comment]
put 
```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```
on the global scope. Also you need to restart nginx to get the new changes taken in account.

**Comment by crashmax** [comment]
Thank you.

Tried it but still the same issue. This is my nginx derective:

proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";

location ~ ^/.* {
	proxy_pass http://0.0.0.0:23000;
	proxy_set_header Host             $host;
	proxy_set_header X-Real-IP        $remote_addr;
	proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
}

**Comment by NicolasDorier** [comment]
I don't know, but here is my personal nginx config as generated in the docker deployment:

```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Prevent Nginx Information Disclosure
server_tokens off;
# Default dhparam
# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 443 ssl http2;
        access_log /var/log/nginx/access.log vhost;
        return 503;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/default.crt;
        ssl_certificate_key /etc/nginx/certs/default.key;
}
upstream btcpay {
        ## Can be connected with "generated_default" network
        # generated_btcpayserver_1
        server 172.24.0.18:49392;
}
server {
        server_name fc4booz5wmoq3knc63gf4sn7oisz45sc7zxtlgnqkeqb2pvzqow6ydqd.onion;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        include /etc/nginx/vhost.d/default;
        location / {
                proxy_pass http://btcpay;
        }
        location /lnrpc.Lightning {
                grpc_pass grpcs://lnd_bitcoin:10009;
        }
        location /lnd-rest/btc/ {
                rewrite ^/lnd-rest/btc/(.*) /$1 break;
                proxy_pass http://lnd_bitcoin:8080/;
        }
        location /btcqbo/ {
                proxy_pass http://btcqbo:8001;
                proxy_redirect off;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /rtl/ {
                proxy_pass http://lnd_bitcoin_rtl:3000/rtl/;
        }
}
server {
        server_name mainnet.demo.btcpayserver.org;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        return 301 https://$host$request_uri;
}
server {
        client_max_body_size 100M;
        server_name mainnet.demo.btcpayserver.org;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_protocols TLSv1.2;
        ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/mainnet.demo.btcpayserver.org.crt;
        ssl_certificate_key /etc/nginx/certs/mainnet.demo.btcpayserver.org.key;
        ssl_dhparam /etc/nginx/certs/mainnet.demo.btcpayserver.org.dhparam.pem;
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_trusted_certificate /etc/nginx/certs/mainnet.demo.btcpayserver.org.chain.pem;
        add_header Strict-Transport-Security "max-age=31536000" always;
        include /etc/nginx/vhost.d/default;
        location / {
                proxy_pass http://btcpay;
        }
        location /lnrpc.Lightning {
                grpc_pass grpcs://lnd_bitcoin:10009;
        }
        location /lnd-rest/btc/ {
                rewrite ^/lnd-rest/btc/(.*) /$1 break;
                proxy_pass http://lnd_bitcoin:8080/;
        }
        location /btcqbo/ {
                proxy_pass http://btcqbo:8001;
                proxy_redirect off;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /rtl/ {
                proxy_pass http://lnd_bitcoin_rtl:3000/rtl/;
        }
}
upstream librepatron {
        ## Can be connected with "generated_default" network
        # librepatron
        server 172.24.0.10:8006;
}
server {
        server_name patron.btcpayserver.org;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        return 301 https://$host$request_uri;
}
server {
        client_max_body_size 100M;
        server_name patron.btcpayserver.org;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:!DSS';
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/patron.btcpayserver.org.crt;
        ssl_certificate_key /etc/nginx/certs/patron.btcpayserver.org.key;
        ssl_dhparam /etc/nginx/certs/patron.btcpayserver.org.dhparam.pem;
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_trusted_certificate /etc/nginx/certs/patron.btcpayserver.org.chain.pem;
        add_header Strict-Transport-Security "max-age=31536000" always;
        include /etc/nginx/vhost.d/default;
        location / {
                proxy_pass http://librepatron;
        }
        location /isso {
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Script-Name /isso;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_pass http://isso:8080;
        }
}
upstream woocommerce {
        ## Can be connected with "generated_default" network
        # generated_woocommerce_1
        server 172.24.0.11:80;
}
server {
        server_name store2.mainnet.demo.btcpayserver.org;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        return 301 https://$host$request_uri;
}
server {
        client_max_body_size 100M;
        server_name store2.mainnet.demo.btcpayserver.org;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:!DSS';
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/store2.mainnet.demo.btcpayserver.org.crt;
        ssl_certificate_key /etc/nginx/certs/store2.mainnet.demo.btcpayserver.org.key;
        ssl_dhparam /etc/nginx/certs/store2.mainnet.demo.btcpayserver.org.dhparam.pem;
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_trusted_certificate /etc/nginx/certs/store2.mainnet.demo.btcpayserver.org.chain.pem;
        add_header Strict-Transport-Security "max-age=31536000" always;
        include /etc/nginx/vhost.d/default;
        location / {
                proxy_pass http://woocommerce;
        }
}
```

**Comment by crashmax** [comment]
Thank you very much!
I did setup a new root server without Plesk. Now it works. I guess it was because of Plesk managing Nginx.
