### ISSUE TITLE
invoice status expired right after it was created

### ISSUE THREAD

**Issue by NicolaLS** [btcpayserver/btcpayserver#5286]
Hi,

We had a problem with our BTCPay server recently where a successful lightning payment was not recognized.
1. The LN Node was online as it successfully received the payment but btcpay showed this error:
`NodeInfo failed to be fetched: The lightning node did not reply in a timely manner`
2. Then the invoice status was expired right after its creation...

I 've also attached a screenshot of this, would anyone have an idea what the issue could be/ why this happened ?

![btcpay_issue_censored](https://github.com/btcpayserver/btcpayserver/assets/90551797/6abda793-7229-4bfb-ac17-40601cfc4459)

**Comment by vbouzon** [comment]
Hi @NicolaLS 

On your screenshot, there is 6 hours of difference between invoice_created and invoice_expired but you mention "right after"?

On my side, not able to reproduce.

**Comment by NicolasDorier** [comment]
The logs are show that there is 6 hours between the time the invoice get created and expired. So I'm not sure about the "immediately" part.

Are you sure it is the right invoice?

**Comment by NicolasDorier** [comment]
Also, which node are you using for ln payments? LND?

**Comment by NicolaLS** [comment]
Thank you for the quick response @NicolasDorier! You're right there must've been a miscommunication with my colleague and I did not notice that, sorry.
The weird thing is that the Node received the payment which means it must have been online but btcpay server never recognized it.
I'll tell my colleague to provide more info in this issue as I do not know the details of the situation and our setup (not sure if we're using LND)

**Comment by jstrnbrg** [comment]
@NicolasDorier 

> Also, which node are you using for ln payments? LND?

LND version 0.16.2

6h is the time window we have set in the "Invoice expires if the full amount has not been paid after …" field. 
However, the LN payment was received by LND within that time frame.
