### ISSUE TITLE
Mine is asking me to  pay for my winnings with my Bitcoin. And I can’t at in advance this is my 4th attempt to get you to change my services to  take it out of my winnings

### ISSUE THREAD

**Issue by tight-sketch** [btcpayserver/btcpayserver#5289]
Mine is asking me to  pay for my winnings with my Bitcoin. And I can’t at in advance this is my 4th attempt to get you to change my services to  take it out of my winnings

_Originally posted by @tight-sketch in https://github.com/btcpayserver/btcpayserver/issues/5207#issuecomment-1704602008_

**Comment by Nazarumi** [comment]
A mí me pasa algo similar me pide que pague el intercambio de bitcoin a USD. 
 La pregunta es por qué si doy la dirección de la billetera de bitcoin para que aser un irtecambio?

**Comment by dennisreimann** [comment]
https://blog.btcpayserver.org/bitcoin-bonus-scam/
