### ISSUE TITLE
[Bug]: Payment request doesn't have a concept of `processing` status, goes immediately to settled for on-chain payments

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5297]
### What is your BTCPay version?

 BTCPay Server v1.11.2+1c5fcfe09

### How did you deploy BTCPay Server?

Docker

### What happened?

When a payment request is paid on-chain, the status doesn't get to `processing` instead goes to `settled`.

Two problems:
1. We don't recognize the `processing` status in payment request
2. In payment details, we do use `processing` but it's designed as `settled`, should use the same design/style as `processing` label in invoice view.

### How did you encounter this bug?

1. Create a payment request
2. Pay on-chain
3. Check the payment request view

### What browser do you use?

Safari 15.00

### Additional information

![Screenshot 2023-09-07 at 13 56 23](https://github.com/btcpayserver/btcpayserver/assets/36959754/3f482175-2230-4922-b42d-f633104bf852)
![Screenshot 2023-09-07 at 14 01 08](https://github.com/btcpayserver/btcpayserver/assets/36959754/7a942548-b5f6-4804-b98b-8308b6f322de)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Mickledmoore** [comment]
> ### What is your BTCPay version?
> BTCPay Server v1.11.2+1c5fcfe09
> 
> ### How did you deploy BTCPay Server?
> Docker
> 
> ### What happened?
> When a payment request is paid on-chain, the status doesn't get to `processing` instead goes to `settled`.
> 
> Two problems:
> 
> 1. We don't recognize the `processing` status in payment request
> 2. In payment details, we do use `processing` but it's designed as `settled`, should use the same design/style as `processing` label in invoice view.
> 
> ### How did you encounter this bug?
> 1. Create a payment request
> 2. Pay on-chain
> 3. Check the payment request view
> 
> ### Relevant log output
> _No response_
> 
> ### What browser do you use?
> Safari 15.00
> 
> ### Additional information
> ![Screenshot 2023-09-07 at 13 56 23](https://user-images.githubusercontent.com/36959754/266309292-3f482175-2230-4922-b42d-f633104bf852.png) ![Screenshot 2023-09-07 at 14 01 08](https://user-images.githubusercontent.com/36959754/266309645-7a942548-b5f6-4804-b98b-8308b6f322de.png)
> 
> ### Are you sure this is a bug report?
> * [x]  I confirm this is a bug report
