### ISSUE TITLE
[Bug]: Improve generic NFC reference error undefined

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5298]
### What is your BTCPay version?

 BTCPay Server v1.11.2+1c5fcfe09

### How did you deploy BTCPay Server?

Docker

### What happened?

On the checkout page, when there's a failiture on NFC, the only error we give is generic `eference error undefined` which in practice lead to a lot of questions by merchants using devices in Riga. We need to me more contextual, and @Kukks confirmed we can do a way better job here and that this is a bug.

### How did you encounter this bug?

1. Try to pay an invoice with NFC
2. See generic error always in case of failiture

### Additional information

![IMG_1704](https://github.com/btcpayserver/btcpayserver/assets/36959754/041e6a17-d214-4f00-aefe-030353ce2219)

Good example is to look at Wallet Of Satoshi which gives contextual error such as insufficient balance, etc.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Gezzy27** [comment]
It's easy
