### ISSUE TITLE
Add plus + functionality in Point of Sale

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5299]
In practice it has been shown that merchants sometimes have multiple items that they're charging for, in this scenarios they'd had to use calculator or do it on top of their head. Instead a pos device can shave a simple + functionality that would allow merchant to add 2+2+3+4+55+6+7+12.30 and then generate an invoice.

In this scenario we don't really need `.` just replace it with `+` I think?

Some examples:
![Screenshot 2023-09-07 at 11 46 31](https://github.com/btcpayserver/btcpayserver/assets/36959754/b8da6d48-dd2e-4f16-85b7-4c28b1dee8f6)
![IMG_1706](https://github.com/btcpayserver/btcpayserver/assets/36959754/6528a177-b8cd-438f-9a3f-f959c654af50)

It would be worth checking how POS in fiat industry handle this and if they have dot as a decimal separator or is the flow more similar to Breez and WOS. 

I don't recommend tackling this issue until @dstrukt takes a look and decides how to approach this UX wise.

**Comment by dstrukt** [comment]
Will follow up, but 100% ACK to the original discussion regarding handing the `.` by default, which would free up that bottom left space, which would make sense to fill with a `+`.

Something else to consider.. do we want to push the `Clear` button into the keypad replacing the `Back/Remove 1`? Not the biggest fan of `C`, feels like it could be clearer .. would make the Charge CTA more prominent.

Also, tested out SQ POS terminal last time I bought a coffee, lady thought I was kinda slow lol, but the behavior is consistent with the change we want to make, wanted to confirm what they're doing these days.

Also have some old POS research I need to dig up from when I worked at PM/CK.

**Comment by dennisreimann** [comment]
> do we want to push the Clear button into the keypad replacing the Back/Remove 1? Not the biggest fan of C, feels like it could be a clearer label, but maybe that's just me? 

One thing to watch out for — especially once we introduce the + functionality — would be that it'd clear everything, so this might be unintended if it takes the position of the current delete key.
