### ISSUE TITLE
[Bug]: Checkout - don't show `Pay with and payment method` pill, when there's only one payment method

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5301]
### What is your BTCPay version?

BTCPay Server v1.11.2+1c5fcfe09

### How did you deploy BTCPay Server?

Docker

### What happened?

On the checkout page, when there's only one payment method, there's no need to showcase the `Pay with` and payment method selector, either in retail and even online mode, it's just redundant.
![Screenshot 2023-09-07 at 11 47 34](https://github.com/btcpayserver/btcpayserver/assets/36959754/a4918193-45f0-4c3f-88e1-a193e3e8f72c)

### How did you encounter this bug?

1. Have a single payment method invoice
2. See checkout page

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
This should be the case already so there must be something else going on that's just not showing up. E.g. a plugin hooking into the payment process.

**Comment by pavlenex** [comment]
You're right @dennisreimann I had prism and sideshift plugin enable, probably the later one caused this. Should we close the issue then?

**Comment by dennisreimann** [comment]
See if there are errors whioch prevent the SideShift part from showing up, most likely in the browser console. 
If it works correctly with SideShift disabled, then we should move this to the SideShift plugin repo.
