### ISSUE TITLE
[Bug]: The return of the `remember me` on login page

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5302]
### What is your BTCPay version?

BTCPay Server v1.11.2+1c5fcfe09

### How did you deploy BTCPay Server?

Docker

### What happened?

Kukks and I noticed in Riga, that we nuked the `remember me` checkbox from the login page, which made logins challenging for us on point of sales.

@dstrukt @dennisreimann I remember we used to have this ,was it intentionally removed or? Once we have clarity, someone can tackle this one, even a new contributor, it's quite trivial to add it back.

### How did you encounter this bug?

1. Go to login page

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
no fucking clue, I don't remember any of that. I guess I removed by mistake
