### ISSUE TITLE
First Setup Wizard - Creating Store + Derivation scheme

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#533]
Currently, BTCPay's method of adding store + wallet is not intuitive. I've noticed again and again that new users who want to try BTCPay, register an account, but from there they have no idea what to do.

My proposal is to create a **startup-wizard** that will guide users step by step on setting up their account + store + adding derivation scheme.

In the ideal world, user would just need to plug in the hardware wallet and enter store name, while BTCPay does all the work in the background including securing the account via U2F #53 

Unfortunately we can't expect everyone to have hardware wallets, nor us to be compatible with all wallets on the market, so the process still needs to include manual pasting of the xpub.

_Edit: After re-thinking, BTCPay front page does not make much sense for admins. When no user is register, we should display the setup wizard right and from there, guide the user from registering admin account to setting up everything._ Users should not have to think at all what to do.

00. Syncing should be communicated better. (Maybe add fast-sync button? for those who need to sync urgently?)
0. Create admin account
1. Add Store Name and site
2. Paste your derivation scheme
3. Verify your derivation scheme
4. Integrate your store, create payment button, etc.

![0a copy 2](https://user-images.githubusercontent.com/36959754/51865941-f74a4280-2347-11e9-8c9d-1bb2ec7556ad.png)
![0a copy](https://user-images.githubusercontent.com/36959754/51865942-f74a4280-2347-11e9-8193-9c04e1b18724.png)
![1](https://user-images.githubusercontent.com/36959754/51865944-f7e2d900-2347-11e9-839a-75879347ae43.png)
![2](https://user-images.githubusercontent.com/36959754/51865946-f87b6f80-2347-11e9-8b95-430bdd027c28.png)
![3](https://user-images.githubusercontent.com/36959754/51865947-f9140600-2347-11e9-9867-684a316f48dd.png)
![3a](https://user-images.githubusercontent.com/36959754/51865953-fa453300-2347-11e9-847a-af305e261cf7.png)
![3b](https://user-images.githubusercontent.com/36959754/51865956-fa453300-2347-11e9-9f81-b5b0cb5d22a6.png)
![4](https://user-images.githubusercontent.com/36959754/51865958-fa453300-2347-11e9-8c49-af2167d51ba9.png)

Hopefully at some point in future a UX/UI guru will appear and help us figure this out and also implement, until then, leaving this for brainstorming.

Related slightly #483 #361

**Comment by zaowens** [comment]
I agree with compressing the pages into a few. This is a great start. Likely will need some clickable help icons to help users if they get stuck in a certain section, but those can be worked out later. 

This looks great.

**Comment by pavlenex** [comment]
I updated and condensed the steps based on feedback.
Wallet xpub is such a critical feature, not sure if it should be a separate step, especially because people should know they can just plug in their hardware wallet to add it.

**Comment by pavlenex** [comment]
After some thinking, I decided that Wallet Setup should be a separate step. Still WIP.

**Comment by pavlenex** [comment]
It seems this one will be possible partially when we do new interface and #1055 so closing it for now.
