### ISSUE TITLE
[Bug]: Payouts won't go out to CashApp

### ISSUE THREAD

**Issue by strnly** [btcpayserver/btcpayserver#5334]
### What is your BTCPay version?

BTCPay Server v1.11.4

### How did you deploy BTCPay Server?

Running BTCPay Server on a dedicated VPS.

### What happened?

I have to issue refunds (payouts) on a regular basis.
I noticed that payouts to CashApp wallets go to Awaiting Payments queue under Payouts. 
I need to select them and then "Action" > Send Selected Payouts.

See attached screenshots
![Screenshot 2023-09-21 at 12 01 21 PM](https://github.com/btcpayserver/btcpayserver/assets/25166070/898217a5-ec6b-4abb-80ae-59f95af83405)

When I try sending the payouts, they fail (red)

![Screenshot 2023-09-21 at 12 05 23 PM](https://github.com/btcpayserver/btcpayserver/assets/25166070/70fd8e0d-879d-4c97-94ca-790f5f2e331d)

![Screenshot 2023-09-21 at 12 05 40 PM](https://github.com/btcpayserver/btcpayserver/assets/25166070/11d57d2b-047d-43dc-98af-e67d089b39f9)

I therefore assumed it was a liquidity issue and I opened new channels with large peers that Lightning Labs confirmed they were connected with CashApp. 

I spent hours with Michael, Product Manager at CashApp trying to debug this. They said they (CashApp and OKCoin nodes had an LND issue that was causing routing issues and they fixed it).

It seems the payouts worked for a week or so (can only speculate). 

However, this Failed payout issue resumed a week ago. BUT, BUT... I just realized one thing. 

If I open Ride The Lightning with my same node, go to Lightning > Transactions and I send the payout manually using the exact same LN invoice that the recipient submitted in the payout, the payouts work! 

So, the payouts will fail when processed via the BTCPay Server UI, but will go through when manually processing them via RTL. It tells me it is not a liquidity issue (especially because I have 1 BTC in fat channels with peers I know are well connected to CashApp, such as OKCoin or OpenNode...). 

It does not seem like a trivial one to figure out but I thought I should open this issue. I am available to do a video call to replicate the issue. 

### How did you encounter this bug?

Using the PullPayment and Payout features of BTCPay Server.

### What browser do you use?

Brave

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Alexander1690** [comment]
I'm trying to withdraw my bitcoin from my binance wallet. I've to pay 64dollars for the transfer but. For some reason I can't get paying it.when I try all it says is copied to clipboard? All I want is an answer on how to pay the 64dollars and to whom?

**Comment by dennisreimann** [comment]
@Alexander1690 Read this https://blog.btcpayserver.org/bitcoin-bonus-scam/
