### ISSUE TITLE
[Bug]: Yadio Price Source selects a wrong link

### ISSUE THREAD

**Issue by learntheropes** [btcpayserver/btcpayserver#5347]
### What is your BTCPay version?

BTCPay Server v1.11.4

### How did you deploy BTCPay Server?

lunanode script

### What happened?

When you select Yadio as a price source under store setting > rates, a different source and link is selected (exchangeratehost).

### How did you encounter this bug?

1. In a new or existing store, go to `Store setting` > `Rates`
2. Change the `Preferred Price Source` field and select `Yadio`
3. A different source is selected: `exchangeratehost` instead of `Yadio`

### What browser do you use?

Brave Version 1.57.53 Chromium: 116.0.5845.114 (Official Build) (64-bit)

### Additional information

Initially I fought that exchangerate.host was a rebranding of Yadio, but is not.

They still have different api links: https://api.exchangerate.host/latest?base=BTC and https://api.yadio.io/exrates/BTC

With completely different exchange rate:  
For BTC/ARS for example, is 19640223.99 on Yadio and 9323242.125 on exchangerate.host (the double).  

With previous Btcpay Server versions, it was working correctly. 

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by learntheropes** [comment]
The same with BTCPay Server v1.11.5

**Comment by NicolasDorier** [comment]
@learntheropes this is a bug, actually, if you look at the list, you will find that there are two `Yadio`.
One appear in the correct alphabetical order, the other appear oddly at the `e` position of the alphabetical order.

If you select the one in the `Y`s, then you'll have the real Yadio. I will fix this.

**Comment by NicolasDorier** [comment]
@learntheropes do you think we also should set up `Yadio` as the recommended exchange rate source for ARS?

**Comment by learntheropes** [comment]
@NicolasDorier yes, as far as I know, is the only API that provides Blue Dollar rate for Argentina. 

Maybe there are some more countries in the same situation, I'm not aware, like Venezuela and Zimbabwe. But again, I'm sure only about Argentina.

**Comment by NicolasDorier** [comment]
@learntheropes did the workaround I told you worked?

As said, there are two `Yadio` in the list of exchanges. One is exchangerate (misnamed Yadio), the other is yadio (also Yadio).

If you select the one that appear in the `e` alphabetical order, it is exchangerate.

If you select the one that appear in the `y`, it's the real yadio.

**Comment by learntheropes** [comment]
@NicolasDorier Yes it worked. Thank you a lot!  
I didn't notice the duplicate when I opened the issue, because the wrong one is the first that comes out if you search for it.

**Comment by NicolasDorier** [comment]
Yes fixed it for next release
