### ISSUE TITLE
Add Payment request link trigger for email rules setting and remove redundant message in the UI

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5356]
Right now, it's not possible to send a payment request link through an email, even though our UI says it is.
We need to add payment request functionality within the email configuration so that users could send payment links to their clients, it's pretty common feature in invoicing. 

![Screenshot 2023-09-27 at 14 31 08](https://github.com/btcpayserver/btcpayserver/assets/36959754/1b88f7c4-45f1-4a6e-aacc-8743f9e8ca09)

Furthermore, the message in the payment request UI is redundant.

```The recipient's email. This will send notification mails to the recipient, as configured by the email rules, and include the email in the invoice export data..```

I don't think the other part matters, it's normal that if email is used it should be added to the invoice.

```[tasklist]
### Tasks
- [x] Add payment request setting in email configuration
- [x] Remove the second part of the message The recipient's email. This will send notification mails to the recipient, as configured by the email rules.
```

**Comment by pavlenex** [comment]
Slightly related and can be tackled as part of this issue https://github.com/btcpayserver/btcpayserver/issues/5345

**Comment by Hipurr** [comment]
BITCOIN MINING IS A SCAM!!!!! $38,000+ AND 5 MONTHS LATER I'M STILL TRYING TO WITHDRAW IT!!!! HACK THESE THEIVES UNTIL THEY CANT EVEN GET A DRIVER'S LICENSE!!!!
