### ISSUE TITLE
[Bug]: NBXplorer hangs randomly

### ISSUE THREAD

**Issue by nostitos** [btcpayserver/btcpayserver#5359]
Requires a reboot.

![image](https://github.com/btcpayserver/btcpayserver/assets/48504624/971cea46-9c87-44e1-8f63-436cc6134c8e)

Maybe there's something special in that block that's bugging it out. I'll keep posting which blocks it hangs on maybe we'll see a pattern.

another one
![image](https://github.com/btcpayserver/btcpayserver/assets/48504624/515deecb-7c24-4005-a608-186c41238c43)
From this issue https://github.com/btcpayserver/btcpayserver/issues/4906

https://mempool.space/block/00000000000000000004748e9800a0e9e83843bad7f659541d71ce52fb291d7a
https://mempool.space/block/0000000000000000000560268dbd186dbecdd347e6dad829c10c0fd3cffb2b1a
https://mempool.space/block/0000000000000000000076d6ba131ea8181fccd09f3452f07d321c8e4f4b2259

Only pattern I see is that the Weight are 3.99MB

**Comment by nostitos** [comment]
![image](https://github.com/btcpayserver/btcpayserver/assets/48504624/b4200d10-8e9a-4402-bd07-cbccf7a6bbc3)
![image](https://github.com/btcpayserver/btcpayserver/assets/48504624/f619abd1-886b-46d5-8020-bbbfef6af827)
![image](https://github.com/btcpayserver/btcpayserver/assets/48504624/4c3ca400-39d6-42e6-8432-e926176b9af0)

From https://github.com/btcpayserver/btcpayserver/issues/2722

**Comment by NicolasDorier** [comment]
hey @nostitos I see those are all different height. You have several server and it happened to all of them like that?

**Comment by LouisWayne** [comment]
Have you fixed the issue?

**Comment by LouisWayne** [comment]
I fixed the issue, check this out link: https://github.com/btcpayserver/btcpayserver-docker/issues/519

**Comment by warioishere** [comment]
same here too after a short network down:

![btcpaynbxplorer](https://github.com/btcpayserver/btcpayserver/assets/117512622/175f58a9-5e02-44ba-ade7-61b9d1932c75)

**Comment by iBobik** [comment]
I found NBXplorer stuck too many time, but I think it is happening only after the power down.

**Comment by pavlenex** [comment]
Closing this one since it's related to very old version of btcpay try replicating it with 1.13.3 and if you still have issues let us know and we can re-open. https://github.com/btcpayserver/btcpayserver-docker/issues/519

**Comment by nostitos** [comment]
It hasn't happened in a while, I also consider this solved.
