### ISSUE TITLE
btcpayservice 

### ISSUE THREAD

**Issue by ReginaIverson** [btcpayserver/btcpayserver#5369]
bitcoin:bc1qkrlcnc5fn045rmffw5xe8aa9ndm6spurt94rpf?amount=50000

**Comment by wearyalice** [comment]
> bitcoin:bc1qkrlcnc5fn045rmffw5xe8aa9ndm6spurt94rpf?amount=50000

**Comment by wearyalice** [comment]
SOMEBODY.. what am I screwing up...it will NOT send enough BTC to pay the fee

**Comment by Kukks** [comment]
https://blog.btcpayserver.org/bitcoin-bonus-scam/
