### ISSUE TITLE
Wallet balance visible for shop owner

### ISSUE THREAD

**Issue by TacoScheltema** [btcpayserver/btcpayserver#538]
Hi, this is a feature request for your consideration;

As an admin user I can see the balances of all wallets. 
As a shop owner I would like to see the balance of the wallet attached to my shop.

Currently when logging in as a shop owner I can see invoices for my shop, I can see the shops that I have access to but on the wallet page I see no balances. The 'Manage' link leads to a 404 page.

**Comment by Kukks** [comment]
Wallets page works for me..

**Comment by TacoScheltema** [comment]
I see the following when logged in as admin user:
<img width="1226" alt="screenshot 2019-01-17 at 14 47 54" src="https://user-images.githubusercontent.com/17812055/51323068-72b61500-1a67-11e9-8d6d-def6eec484f0.png">

This is what I see when I log in as a shop owner (i.e. merchant)
<img width="1197" alt="screenshot 2019-01-17 at 14 51 05" src="https://user-images.githubusercontent.com/17812055/51323108-85c8e500-1a67-11e9-9f68-307fd172ead7.png">

Are the balances meant to show up for the merchant? if so, I might have misconfigured something?

**Comment by lippoliv** [comment]
👍 

This is defenetly needed, also for Admin (why not?). I will file an feature proposal soon. This will need the described functinality too.

**Comment by TacoScheltema** [comment]
Well, I discovered that when a user is shop owner he can see the wallet totals for his shop(s). When a user is defined as guest for a particilar shop then the wallet total isn't visible. So I think this was just me misunderstanding the roles.

**Comment by pavlenex** [comment]
@TacoScheltema Alright, in that case, closing the issue.

**Comment by lippoliv** [comment]
I do not see any good reason why to Show an empty column!?
Shouldnt the row be inivisible, if the logged in user has no rights to see the value? 

/cc @pavlenex
