### ISSUE TITLE
[Bug]: XMR Reporting omitted from "Reports"

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#5383]
### What is your BTCPay version?

BTCPay Server v1.11.6+44a7e9387 (Altcoins)

### How did you deploy BTCPay Server?

Docker

### What happened?

The new reporting feature seem to have XMR omitted from it's reporting. I am using the Altcoin build and Doge, LTC and Dash all show their relevant transactions. I'm assuming this is because of how XMR is built, however the XMR transactions were accessible via the CSV dump in previous versions. 

https://github.com/btcpayserver/btcpayserver/pull/5155itsseems

### How did you encounter this bug?

using the reporting feature in the latest version

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
ping @astupidmoose

**Comment by astupidmoose** [comment]
Yes, this is fixed now. Thanks!
