### ISSUE TITLE
Consider using BIP21-compatible Lighnting URIs

### ISSUE THREAD

**Issue by Kixunil** [btcpayserver/btcpayserver#540]
BOLT-11 [specifies BIP21-compatible URI scheme](https://github.com/lightningnetwork/lightning-rfc/blob/46c454cb567326f03107d249b3ac56df965bfd7f/11-payment-encoding.md#encoding-overview), which allows both lightning and on-chain payments to be encoded in a single URI/QR code, where Lightning wallets prefer lightning and may fall back to on-chain and non-Lightning wallets simply ignore Lightning and do on-chain transactions.

It'd be useful to be able to enable this feature, so that people don't have to distinguish between on-chain and LN payments.

**Comment by pavlenex** [comment]
I'll close this one since there's an ongoing discussion in #1064 and this seems exactly the same.
