### ISSUE TITLE
[Bug]: State and Zip fields are not set as required fields.

### ISSUE THREAD

**Issue by ascisco** [btcpayserver/btcpayserver#5401]
### What is your BTCPay version?

v1.11.6

### How did you deploy BTCPay Server?

LunaNode VPS

### What happened?

During checkout when customer is prompted for their shipping address, "State" and "Postcode" are not required fields. 

If left blank by the customer it can cause confusion for the merchant when shipping items to the correct address. 

Ensuring that, "State" and "Postcode" are required fields will save the merchant time in finding the correct shipping the address. 

[Field.Create("Postcode", "buyerZip", null, false, null),](https://github.com/btcpayserver/btcpayserver/blob/018e4c501d459a40041e0b56d708b9f93a994548/BTCPayServer/Forms/FormDataService.cs#L46-L47)

### How did you encounter this bug?

During customer checkout when prompted for shipping address. 

### Are you sure this is a bug report?

- [x] I confirm this is a bug report

**Comment by knocte** [comment]
Hey, but there are countries that don't have post codes, like Hong Kong.

**Comment by dennisreimann** [comment]
> there are countries that don't have post codes, like Hong Kong

Replied here https://github.com/btcpayserver/btcpayserver/pull/5405#issuecomment-1798077363
