### ISSUE TITLE
[Bug]: Lightning Payouts fail due to double fiat rate conversion

### ISSUE THREAD

**Issue by silent-link** [btcpayserver/btcpayserver#5414]
### What is your BTCPay version?

BTCPay Server v1.11.6+44a7e9387 (Altcoins) 

### How did you deploy BTCPay Server?

Docker

### What happened?

E.g.:
Pull Payment for 0.94 USD is created (3492 sats)
When payout request is created, the amount, the sats amount is calculated according to the actual exchange rate, that could change.
Hence a payout request is created for 3490sats.
When payout is processed, we get error (through UI or API): `Failed - The BOLT11 invoice amount (0.0000349 BTC) did not match the payout's amount (0.00003492 BTC)`

### How did you encounter this bug?

with API, reproduced with UI

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
@Kukks do you know if we ever resolved this one?

**Comment by silent-link** [comment]
We have also emailed @Kukks the steps to reproduce:1. we create a pull payment for e.g. 10 USD2. we request exchange rate from btcpay and present our user with the amount in sats3. user creates an LN invoice with the given amount4. exchange rate changes substantially5. user enters the invoice and we try to create a payout6. payout creation **fails**, since the amount in the provided LN invoice does not match the amount set in the pull payment.If we skip step 2, as it works with the standard BTCPay UI, the chances to match the amount are even lower.Silent TeamOn 8 Apr 2024, at 12:19, Pavlenex ***@***.***> wrote:﻿
@Kukks do you know if we ever resolved this one?

**Comment by pavlenex** [comment]
@silent-link Is this one still the issue with 1.13.3?
