### ISSUE TITLE
Wallets - Send - Expert mode clears previously entered amount

### ISSUE THREAD

**Issue by 2pac1** [btcpayserver/btcpayserver#542]
When I select on my complete balance, it populates the amount field with my whole balance, thats cool.

Then I am like, look..the expert mode..I need this, and when I open it, my amount is reverted back to zero.

We need the amount number to remain populated with previous entered value.

**Comment by pavlenex** [comment]
This is indeed a bug.
Noticed it earlier, but completely forgot about it, thanks for reporting.
Replicated on both Chrome and Firefox.

After some testing I noticed it happens only with more than two decimals. 
For example amount 0.03 will work, but 0.003 0.0003 or 0.000003 will get reset to 0.00

![2019-01-18_21-54-33](https://user-images.githubusercontent.com/36959754/51413082-01ad5500-1b6e-11e9-9c67-c766186b5fcc.gif)

**Comment by NicolasDorier** [comment]
it is already fixed, will be in next version!
