### ISSUE TITLE
[Bug]: LNURL not shown in invoice details for top-up invoice

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#5424]
### What is your BTCPay version?

BTCPay Server v1.11.7+a921504bc 

### How did you deploy BTCPay Server?

Docker

### What happened?

![image](https://github.com/btcpayserver/btcpayserver/assets/1374810/649eaae8-a4fd-4cf6-89d9-14dea57e35fb)

Despite the last event in the screenshot showing that a LNURL was generated, it's not shown in the invoice summary above.

### How did you encounter this bug?

Created a top-up invoice via API and viewed the details in the backend.

### Relevant log output

```shell
none
```

### What browser do you use?

Firefox on MacOS

### Additional information

none

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by petzsch** [comment]
additional infos:
- using GetAlby.com via LNDHUB
- the LNURL shown at checkout is not scannable with Zeus 0.8.0 ("Error loading invoice: Error: invoice not for current active network 'mainnet'")

**Comment by Kukks** [comment]
Can you provide the lnurl?

**Comment by petzsch** [comment]
Just choose the last payment option [here](https://otr.4sats.net/?email=markus@petzsch.eu) (custom amount).

Just tried copy&pasting the LNURL and it worked. Problem seems to be within the QR code (combined QR)

**Comment by petzsch** [comment]
one more observation. Once paid with LNURL, the details seem to show up in invoice details.
Which is kind of different then it is with the bitcoin on-chain address:

![image](https://github.com/btcpayserver/btcpayserver/assets/1374810/c2aa87a7-b3ef-4bc8-9cf2-0f47fdfd418e)

**Comment by petzsch** [comment]
I think the main problem was the way Zeus handled our combined QR code including a lnurl. They seem to have fixed that.

That the lnurl doesn't get shown as a payment method in backend until it was paid, as of when it becomes shown as bolt11 invoice could be by design. Only scenario where this could be problematic is when the store owner wants to fetch payment method details via API and display them on their own website. Then there would be nothing to show.
