### ISSUE TITLE
[Bug]: Marking Invoices Settled or Invalid Broken

### ISSUE THREAD

**Issue by labrocca** [btcpayserver/btcpayserver#5430]
### What is your BTCPay version?

BTCPay Server v1.11.7+a921504bc (Altcoins) 

### How did you deploy BTCPay Server?

LunaNode

### What happened?

Updated from 1.11.6 and now the Mark Settled or Mark Invalid no longer works neither on the Invoice list or the Invoice Details page.

### How did you encounter this bug?

Tried to mark an invoice as Invalid after testing the update.

### What browser do you use?

Firefox latest version.

### Additional information

Seems when I click the option, nothing happens. Attempted to do a browser refresh in case of updated JS cache.  

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Can you check the browser logs/dev console for errors? Is the BTCPay instance deployed under a subdirectory (`https://mydomain.com/btcpay/`) or at the root (`https://mybtcpay.com/`) ?

**Comment by labrocca** [comment]
It's sub.domain.com (subdomain).   Using Dark theme.  Tried it in Chrome, same thing. Clicking does no action.  Console not showing any errors that seemed to be causing this.  I just upgraded and tested a second BTCpay server I run, it works on it.  This one with bug is an altcoin version while the other is just BTC.  Not sure that makes any difference.  

Also the one I'm bug reporting is still syncing if that matters.  I'll be happy to provide a Store for testing if someone call tell me the problem.

Actually I just realized, I think the popup for the "nodes are syncing" might actually be the js conflict causing the problem.

**Comment by dennisreimann** [comment]
Can you check in de browser dev console and see the Network Requests tab? It should show a new request whenever you try to toggle the invoice state. What status code and response does it report?

**Comment by labrocca** [comment]
Nothing when I click it.  Almost for sure it's an interference from the syncing window. I've had this before a couple years ago and I forgot about it.  Probably should be fixed by devs but it's one of those fringe bugs only when you're syncing.  Likely a JS conflict of some sort.  I am terrible with JS so I can't really troubleshoot this.  In a week when I'm done syncing, I'll report back. XMR takes a week to sync.

**Comment by dennisreimann** [comment]
Just checked the code and the missing sync shouldn't be a problem here. I also checked if it's a frontend issue in case the sync modal is present, but that also worked for me. So you don't see anything in the web inspector network requests tab?

![Peek 2023-10-27 08-16](https://github.com/btcpayserver/btcpayserver/assets/886/6dd0b505-2667-42db-a3bf-2a82dc67e395)

**Comment by labrocca** [comment]
It does nothing when I attempt to mark.  In Console there is a lot of errors related to Blazor. 

https://imgur.com/rTwT9GL

Also my interface doesn't look like yours.  

https://imgur.com/k66waD9

I have these dropdowns.

**Comment by labrocca** [comment]
The sync modal is gone, still have the issue.  Are the Role permissions something newer?  

![image](https://github.com/btcpayserver/btcpayserver/assets/5331740/bbab18c0-f48c-4d92-94b9-5ab4591b36ad)

I see the "btcpay.store.canmodifyinvoices" under Roles.

**Comment by labrocca** [comment]
I wish I could duplicate this.  It's happened to me twice.  Oh well, closing this.
