### ISSUE TITLE
[Bug]: bitcoin-cli.sh doesn't see the wallet transactions 

### ISSUE THREAD

**Issue by 021-projects** [btcpayserver/btcpayserver#5442]
### What is your BTCPay version?

v1.11.6+44a7e9387

### How did you deploy BTCPay Server?

[Docker](https://docs.btcpayserver.org/Docker/)

### What happened?

In the script `bitcoin-cli.sh` the option `-datadir="/data"` is passed, in Docker it is attached to the `/var/lib/docker/volumes/generated_bitcoin_datadir/_data` directory on the server. This is where the blockchain data is stored, but the wallet files are stored in this directory: `/var/lib/docker/volumes/generated_bitcoin_wallet_datadir/_data/mainnet`, therefore the Bitcoin core does not see transactions and wallet balance.

**Updated:** Not sure if the problem is that the core doesn't see wallets. Probably `/var/lib/docker/volumes/generated_bitcoin_wallet_datadir/_data` is an alias for the `/walletdata` directory, the path to which is already specified in `/data/bitcoin.conf`, so the core should see wallets. But `getbalance` and `listtransactions` still return empty values for unknown reason . This also happens when you try to run commands directly in the container:
```bash
docker exec -t -i btcpayserver_bitcoind /bin/bash
bitcoin-cli -datadir="/data" getbalance
# 0.00000000
```

### How did you encounter this bug?

1. Run `./bitcoin-cli.sh listtransactions`
2. It's empty even if wallet has transactions.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by 021-projects** [comment]
Not sure if the problem is that the core doesn't see wallets. Probably `/var/lib/docker/volumes/generated_bitcoin_wallet_datadir/_data` is an alias for the `/walletdata` directory, the path to which is already specified in `/data/bitcoin.conf`, so the core should see wallets. But `getbalance` and `listtransactions` still return empty values for unknown reason . This also happens when you try to run commands directly in the container:
```bash
docker exec -t -i btcpayserver_bitcoind /bin/bash
bitcoin-cli -datadir="/data" getbalance
# 0.00000000
```

**Comment by dennisreimann** [comment]
When you generated or imported the wallet, did you use the "Import keys to RPC" option? If not, then the wallet won't be present. You can check the existance of imported wallets with `bitcoin-cli listwallets`, but I'm pretty sure it will simply list only the default one: `[""]`.

**Comment by 021-projects** [comment]
`When you generated or imported the wallet, did you use the "Import keys to RPC" option?`
I find it difficult to remember. Without this option I can't manipulate transactions? For example, I want to call the `abandontransaction` method, but the core does not know that such a transaction has been sent

**Comment by dennisreimann** [comment]
Yes, if the wallets hasn't been imported to RPC you cannot use the bitcoin-cli to interact with the wallet.

However, you may be able to reimport it with that setting if that's necessary.

**Comment by 021-projects** [comment]
> Yes, if the wallets hasn't been imported to RPC you cannot use the bitcoin-cli to interact with the wallet.
> 
> However, you may be able to reimport it with that setting if that's necessary.

If RPC does not have a wallet, then how does BTCPay interact with the blockchain? How does it track transactions and balances?
Is it possible to mark a transaction as abandoned without re-importing a wallet?

**Comment by dennisreimann** [comment]
BTCPay tracks the wallet via NBXplorer ([details here](https://docs.btcpayserver.org/Development/)), which is also part of the stack.

> Is it possible to mark a transaction as abandoned without re-importing a wallet?

Maybe @NicolasDorier can help here.

**Comment by pavlenex** [comment]
cc @NicolasDorier check if you can help on this one please.
