### ISSUE TITLE
[Bug]: LNURLPay URL at API Docs

### ISSUE THREAD

**Issue by HappyBerrysBoy** [btcpayserver/btcpayserver#5443]
### What is your BTCPay version?

v1.11.6

### How did you deploy BTCPay Server?

docker

### What happened?

About API : Update store LNURL Pay payment method

1. different URL
API Docs show the url like : https://docs.btcpayserver.org/api/v1/stores/{storeId}/payment-methods/LNURL/{cryptoCode}
But real url(from source) : https://docs.btcpayserver.org/api/v1/stores/{storeId}/payment-methods/LNURLPay/{cryptoCode}

2. different parameter name
request param name : lud12Enabled
returned param name : luD12Enabled

3. didn't work set lud12Enabled
- I requested above API with (lud12Enabled = true), but it didn't work well(returned luD12Enabled = false)
- 

### How did you encounter this bug?

Requested API

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
@dennisreimann can you check this one please?

**Comment by pavlenex** [comment]
https://github.com/btcpayserver/btcpayserver/issues/5440 unsure if it's related
