### ISSUE TITLE
btcpayserver in powershell is looking for regtest as the datadirectory

### ISSUE THREAD

**Issue by mattnook** [btcpayserver/btcpayserver#545]
I keep getting this error when trying to set up btcpayserver (Bitcoin Core and NBXplorer are working fine)

`PS C:\Users\user\btcpayserver\BTCPayServer> dotnet run
C:\Program Files\dotnet\sdk\2.2.103\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(153,5): warning NETSDK1071: A PackageReference to 'Microsoft.AspNetCore.App' specified a Version of `2.1.6`. Specifying the version of this package is not recommended. For more information, see https://aka.ms/sdkimplicitrefs [C:\Users\user\btcpayserver\BTCPayServer\BTCPayServer.csproj]
[33m[1m  No files matched the pattern wwwroot/crowdfund-admin/**/*.js[0m[39m[49m
info: Configuration:  Data Directory: C:\Users\user\AppData\Roaming\BTCPayServer\RegTest
info: Configuration:  Configuration File: C:\Users\user\AppData\Roaming\BTCPayServer\RegTest\settings.config
info: Configuration:  Creating configuration file
info: Configuration:  Network: Regtest
info: Configuration:  Supported chains: BTC,LTC
info: Configuration:  Network: Regtest
info: Configuration:  Supported chains: BTC,LTC
info: Configuration:  Root Path: /
info: Configuration:  Postgres DB used (User ID=postgres;Host=127.0.0.1;Port=39372;Database=btcpayserver)
Application startup exception: System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it`

I don't know what the issue is but it seems like the DataDirectory is trying to go to regtest rather than Main. How do I fix this? The " No files matched the pattern wwwroot/crowdfund-admin" also seems weird. I am using default settings in settings.config.

**Comment by NicolasDorier** [comment]
I advise you against on setting up BTCPay on windows. 
BTCPayServer is using Regtest by default, and you can mainnet

The environment variables known by BTCPay are here https://github.com/btcpayserver/btcpayserver-docker#environment-variables if you want mainnet, set `NBITCOIN_NETWORK` correctly.

**Comment by NicolasDorier** [comment]
Manual deployment is not cheaper. It is just more time consuming.
Please use https://www.youtube.com/watch?v=oce_fvRdLLY

You can see dependencies then with `cat $BTCPAY_DOCKER_COMPOSE`.

**Comment by mattnook** [comment]
ok, I switched to BtcPayServer. It works great. Thanks for all your work on this, it's really incredible. 

One thing I noticed, on BtcPayServer, under "Services", it says "Crypto services
You can get access here to LND (gRPC, Rest) services exposed by your serve"

I believe this is no longer true as the new services are Spark and Lightning Charge (c-lightning).

Anyways, I'll close this thread
