### ISSUE TITLE
[Bug]: Command to checkout latest tag does not return what was expected

### ISSUE THREAD

**Issue by twofaktor** [btcpayserver/btcpayserver#5454]
### What is your BTCPay version?

I'm trying to run v1.11.7

### How did you deploy BTCPay Server?

Manual deployment following: https://docs.btcpayserver.org/Deployment/ManualDeploymentExtended/#1-build-btcpay-server

### What happened?

When you run this command to check the latest tag:

#### Checkout latest tag:
```
~$ git checkout $(git tag --sort -version:refname | awk 'match($0, /^v[0-9]+\./)' | head -n 1)
```

It returns immediately before `rc` version `v1.11.7-rc1`, not the latest one `v1.11.7`, so it doesn't install the latest version

```
Note: switching to 'v1.11.7-rc1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 018e4c501 Changelog 1.11.7 (#5394)
```

![imagen](https://github.com/btcpayserver/btcpayserver/assets/89636253/8bb8aac6-68d9-47f3-8b14-18961201c91e)

### How did you encounter this bug?

Simply follow [these instructions](https://docs.btcpayserver.org/Deployment/ManualDeploymentExtended/#1-build-btcpay-server)

### Relevant log output

```shell
Note: switching to 'v1.11.7-rc1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 018e4c501 Changelog 1.11.7 (#5394)
```

### What browser do you use?

Does not apply

### Additional information

- This is solved by skipping this step, but I think it should not be the expected behavior according to the parameter comment
- Possibly you forgot to reassign the v1.11.7 tag as the latest version
- I already found this same error in other previous versions

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
We recently started to work with release candidate versions and haven't updated the docs yet. Does this work for you?

```bash
git checkout $(git tag --sort -version:refname | awk 'match($0, /^v[0-9]+\.[0-9]+\.[0-9]+$/)' | head -n 1)
```

**Comment by twofaktor** [comment]
> We recently started to work with release candidate versions and haven't updated the docs yet. Does this work for you?
> 
> ```shell
> git checkout $(git tag --sort -version:refname | awk 'match($0, /^v[0-9]+\.[0-9]+\.[0-9]+$/)' | head -n 1)
> ```

Yeah! Was solved! now I can see the latest version! thanks!

![imagen](https://github.com/btcpayserver/btcpayserver/assets/89636253/60e1fcf8-08d2-4f48-ab87-a8b1935eed7a)

**Comment by dennisreimann** [comment]
NBXplorer doesn't use RC tags, at least not yet. I'll add a PR for the docs to fix the commend for BTCPay Server — thanks for the pointer!
