### ISSUE TITLE
[Bug]: Pay in Wallet Button in Lightning unified doesn't prefill amount

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#5455]
### What is your BTCPay version?

1.11.7

### How did you deploy BTCPay Server?

docker

### What happened?

The "Pay with Wallet" button on unified Bitcoin/LN checkout doesn't allow the wallet to pay on lightning.

### How did you encounter this bug?

* Install phoenix
* Create an invoice with unified Bitcoin/LN QR code.
* Open the invoice on your phone
* Click on "Pay with Wallet"

Expected: Phoenix opens and allow you to pay on lightning.

Actual: Phoenix opens on-chain payment, and doesn't even prefill the sats amount to send.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
I'm not sure this is something on our end or up for us to fix, because the [BIP21 URI](https://bitcoinqr.dev/) seems to be correct.

For reference there are similar issues with Phoenix:

- ACINQ/phoenix#321
- ACINQ/phoenix#346

**Comment by NicolasDorier** [comment]
@dennisreimann  I think you are right, this is the point of sale in question.

![image](https://github.com/btcpayserver/btcpayserver/assets/3020646/fa4b1708-ef32-4124-a3ea-6fe71e44f5bb)

**Comment by NicolasDorier** [comment]
Wait, closing for now. I can't repro, need to find out if the store owner changed something since I tried.

**Comment by NicolasDorier** [comment]
Reopening it, you can trigger this by having an amount larger than 1500 JPY on

https://mainnet.demo.btcpayserver.org/apps/3Q3sWFpWkCEcsPoJnoB3k9x3qS3m/pos

I think this is an issue with Phoenix.

**Comment by NicolasDorier** [comment]
Closing it, follow up https://github.com/ACINQ/phoenix/issues/466 there is nothing we can do here.
