### ISSUE TITLE
[Bug]: 10min suggested that fee is overpaying by 500% (276 sat/bytes) 

### ISSUE THREAD

**Issue by nostitos** [btcpayserver/btcpayserver#5459]
### What is your BTCPay version?

I'm referring to the send btc page but this should also be in the suggested receive fee.

À more optimal calculation for choosing a short term fee is to use both bitcoin core estimates BUT never send more than to fit in next megabyte for the 10min estimate. Accesible from Mempool.space api

The high fee environment has stopped about 8h ago 

### How did you deploy BTCPay Server?

. 

### What happened?

. 

### How did you encounter this bug?

. 

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by nostitos** [comment]
This is awful, Need urgent fix.
![image](https://github.com/btcpayserver/btcpayserver/assets/48504624/9da32106-9306-41be-9461-9bbaa03e4ed5)

![image](https://github.com/btcpayserver/btcpayserver/assets/48504624/cf87abd3-8ae0-4c16-80c3-47a2ce4a7fe7)

![image](https://github.com/btcpayserver/btcpayserver/assets/48504624/dc53ab6f-d763-4f00-bd3c-9ddc860b3e65)

**Comment by nostitos** [comment]
![image](https://github.com/btcpayserver/btcpayserver/assets/48504624/9fda4b11-701d-42a0-8fe1-96a3431e2fb5)

Fee calculation is retarded on every possible level.

Only if doing a 365 day average are 6h period averaging to 9sat/bytes.

**Comment by pavlenex** [comment]
This has been mentioned already a few times, these are bitcoin core estimates, to improve this we're introducing better estimates via mempool.space #5490 so this issue can be closed after 1.12 is released.

**Comment by nostitos** [comment]
Thank you very much, it's to wonder how many people actually transact with core for this to get fixed upstream.
