### ISSUE TITLE
[Public LN Node] Consistency update

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#5465]
### For the checkout, we do:

<img width="357" alt="Screen Shot 2023-11-10 at 11 52 39 AM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/97d9178d-6675-4119-830f-96defa4fda6e">

### But for the public LN node view, we do (specifically the pubkey section):

<img width="372" alt="Screen Shot 2023-11-10 at 11 52 46 AM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/5d79125f-5fd0-46d0-a1d2-b5a661c87f06">

### Proposal:
- [ ] We should update the pubkey to match what we do for the checkout invoice on-chain address, etc..
- [ ] We should use the pill component for the `Tor` / `Clearnet` switch

There might be 1-2 more things, and this is minor, but an easy issue to tackle!

**Comment by dennisreimann** [comment]
Let's do this once #5462 is merged.
