### ISSUE TITLE
Registration disabled by default - admins getting locked out

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#547]
Unfortunately my suggestion in #463 that was kindly implemented by @sipsorcery to solve the obvious issue and disabled registration by default for users, to prevent other people from registering to their server without them knowing, now created another issue - admins are getting locked out.

Admin forgets his password. He's not aware that he has to configure SMTP settings to reset the password, so he doesn't. He tries to add a new user as we[ suggest in documentation,](https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#forgot-btcpay) but the default settings now prevent him from doing that.

Possible solutions
1. Enable registration
2. Document a workaround in the documents that enables registrations + adds another user. (probably the most optimal solution)
3. Make it more obvious in [getting started guide ](https://docs.btcpayserver.org/btcpay-basics/gettingstarted)that proper SMTP is required to prevent lock-outs.

Ideally one day we can have a more obvious way for users to set their SMTP settings like in #533 

I've noticed that users began to get locked out quite frequently. Opening  this for brainstorming possible solutions to the problem.

**Comment by sipsorcery** [comment]
Maybe one option would be to have a shell script that can be run on the server to reset a user's password directly in the database?

**Comment by pavlenex** [comment]
Anything that can help us bail the users out is good enough. Most people who followed the docs earlier were able to recover without any problems, so I don't see why a shell script wouldn't work.

**Comment by NicolasDorier** [comment]
https://github.com/btcpayserver/btcpayserver-doc/commit/d26abd17d188caba3f7f42e03c4190425987b8f0
