### ISSUE TITLE
Custom Forms: get_invoice endpoint custom form field data

### ISSUE THREAD

**Issue by jayparalejas** [btcpayserver/btcpayserver#5484]
### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/5483

<div type='discussions-op-text'>

<sup>Originally posted by **jayparalejas** November 16, 2023</sup>
Is there any way to fetch the custom form field data from the official api?

https://docs.btcpayserver.org/Forms/

Searched everywhere but can't seem to figure out how the custom form field is exposed in the endpoint.</div>

**Comment by dennisreimann** [comment]
Do you want the data of the form itself or the actual data which has been provided by the user connected with a payment? Right now there are no API endpoints for the former, but the latter can be accessed via the invoice metadata ([GetInvoice](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Invoices_GetInvoice)).

**Comment by jayparalejas** [comment]
I created a custom field to collect a single input field. But i guess there is no way to fetch it. Any other alternatives? Build a new endpoint?

**Comment by dennisreimann** [comment]
Again, what exactly do you want to fetch? The data about the form or the data that the form collects in conjunction with an invoice?

**Comment by jayparalejas** [comment]
Aldready figured it out to mirror the data on receiptData.

https://docs.btcpayserver.org/Forms/

Thanks
