### ISSUE TITLE
Consolidate and improve iconography across app

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#5485]
Will fill in later.

**Comment by dennisreimann** [comment]
Replaced most of them in #5938. List of remainders:

- fa-sort + fa-sort-desc
- fa-sort-alpha + fa-sort-alpha-desc
- fa-remove
- fa-lock
- fa-exclamation + fa-exclamation-triangle
- fa-spinner
- fa-send
- fa-cube
- fa-question-circle
- fa-times-circle

We have most of those by now, so this is mostly about going through it in a dedicated manner and e.g. also replace the ones in Vault.
