### ISSUE TITLE
Improve delete user message

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#549]
It would be better if there was a unique message for when the Admin is deleting the Admin. 

Right now the 'delete user' message is the same for all users: "This user will be permanently deleted"

I think we should check:

- If the user being deleted is the admin, display a different message such as:
    * "Are you sure you want to delete this Admin and delete all accounts, users and data associated with the server account?"

I understand admins may want to start over and delete their server account for some reason. However when the Admin deletes himself, I think some users could be confused about what happens next and some hearts could be broken if they are not warned.

**Comment by rockstardev** [comment]
MY ISSUE, NOBODY TOUCH IT!
