### ISSUE TITLE
[Bug]: Webhook InvoiceSettled, field overPaid gone

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#5496]
### What is your BTCPay version?

BTCPay v1.11.7

### How did you deploy BTCPay Server?

docker

### What happened?

On the InvoiceSettled and InvoiceProcessing event the formerly available property `overPaid` is missing. This breaks implementations relying on that field.

See docs [here](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Webhook_InvoiceSettled) and [here](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Webhook_InvoiceProcessing)

Webhook:
```
{
"manuallyMarked": false,
"deliveryId": "LJMTFbSEobW7mpmAbfVzJv",
"webhookId": "V9YybsYgDaguxf98N54SJr",
"originalDeliveryId": "LJMTFbSEobW7mpmAbfVzJv",
"isRedelivery": false,
"type": "InvoiceSettled",
"timestamp": 1700562873,
"storeId": "HUZAUrnnsHztegnRKHhe9LQMcykQVq1Uaj8UyEbkgcWS",
"invoiceId": "4cLstvvUwbmTRpdQ3nAPCG",
"metadata": {
"orderId": "167",
"taxIncluded": 0
}
}
```

### How did you encounter this bug?

receiving and processing that webhook event causing an error

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by ndeet** [comment]
This flag was also available in the "InvoiceProcessing" event.

**Comment by dennisreimann** [comment]
@ndeet Can you check and confirm that the PR fixed it?

**Comment by dennisreimann** [comment]
I pushed 379286c36657a87ebf7218e0e63c01859abfb76e straight to `master`. fyi @Kukks

**Comment by ndeet** [comment]
@dennisreimann thank you, works now as before only on InvoiceSettled and InvoiceProcessing events. :partying_face:
