### ISSUE TITLE
[Bug]: Maximum response size reached / 504 gateway time-out

### ISSUE THREAD

**Issue by hell0-w** [btcpayserver/btcpayserver#5499]
### What is your BTCPay version?

 BTCPay Server v1.11.7+a921504bc

### How did you deploy BTCPay Server?

docker

### What happened?

Hello everyone. my server is updated from 1.9 to 1.11 latest

I have a lot of transaction, when i get transactions from wallet i get this:
![image](https://github.com/btcpayserver/btcpayserver/assets/17591751/369b1341-672d-467a-94c4-348fb5eeb1bc)

![image](https://github.com/btcpayserver/btcpayserver/assets/17591751/f57a1eb6-004e-4639-af24-808adca2cacc)

If I set limit to 150k it works but to long request (limit=150000)

if 200k or without limit - i get 504 or Error: Maximum response size reached error or 504 gateway timeout

docker logs --tail 500 -f nginx
![image](https://github.com/btcpayserver/btcpayserver/assets/17591751/4cc2a4cb-b278-4018-b499-1cbaa8c0923f)
Other logs blank.

how to fix it? 

Thanks.

### How did you encounter this bug?

get transactions from wallet
https://URL/api/v1/stores/STOR-ID/payment-methods/OnChain/BTC/wallet/transactions

### What browser do you use?

postman

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Closing this one since it's related to very old version of btcpay try replicating it with 1.13.3 and if you still have issues let us know and we can re-open.
