### ISSUE TITLE
[Bug]: core lightning docker container continuously tries to fetch block which has been pruned by bitcoind container

### ISSUE THREAD

**Issue by Amperstrand** [btcpayserver/btcpayserver#5506]
### What is your BTCPay version?

BTCPay Server v1.11.7

### How did you deploy BTCPay Server?

docker

### What happened?

docker logs btcpayserver_clightning_bitcoin shows that core lightning container is repeatedly failing to get a block which is several years old from  the btcpayserver_bitcoind container.

This is happening about once per second.

as the bitcoin user in the btcpayserver_bitcoind docker container I can confirm that this block is not available because it is a pruned node:
```
bitcoin-cli  -rpcconnect=bitcoind getblock 0000000000000000001283e48f96161de940924dca2d2c236217ff920627a5ba 
error code: -1
error message:
Block not available (pruned data)
```

### How did you encounter this bug?

I might have done some unusual things when setting up the core lightning container, so this might not be a bug that will happen if you follow the normal install procedures.

Still, I would like to get to the bottom of why core lightning is repeatedly connecting to bitcoin-core to request a block even though bitcoin-core is responding that it is not going to respond because it is a pruned block.

expected or desired behaviour would be that either:
 - core lightning gives up in requesting the block
 - core lightning convinces bitcoin-core to redownload the block
 - there was a way to tell core lightning to stop scanning old blocks

Also, I am wondering if during inital block download there is a way to ensure that both bitcoind and core-lightning see the blocks before they are pruned.

I could probably fix this by pointing core-lightning to a bitcoin-core instance that is not pruned, but creating an issue to hear if  this behaviour is something that should be fixed in either btcpayserver or core-lightning.

### Relevant log output

```shell
2023-11-23T17:51:48.616Z UNUSUAL plugin-bcli: bitcoin-cli -datadir=/etc/bitcoin -rpcconnect=bitcoind getblock 0000000000000000001283e48f96161de940924dca2d2c236217ff920627a5ba 0 exited with status 1
2023-11-23T17:51:49.624Z UNUSUAL plugin-bcli: bitcoin-cli -datadir=/etc/bitcoin -rpcconnect=bitcoind getblock 0000000000000000001283e48f96161de940924dca2d2c236217ff920627a5ba 0 exited with status 1
2023-11-23T17:51:50.633Z UNUSUAL plugin-bcli: bitcoin-cli -datadir=/etc/bitcoin -rpcconnect=bitcoind getblock 0000000000000000001283e48f96161de940924dca2d2c236217ff920627a5ba 0 exited with status 1
```

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
@NicolasDorier any idea what may be the problem here?

@Amperstrand is this still an issue with 1.2.3?

**Comment by Amperstrand** [comment]
This is not unique to btcpayserver.

It also happens when you try to install core-lightning with a pruning bitcoin node.

core-lightning tries to ask bitcoind for a block, but that block has been pruned.

I'm not sure how to fix this: maybe core-lightning should give an error message telling you not to use a pruned node (or at least something more informative then exited with status 1).

Closing this issue because it is not btcpayserver specific. I'm also not sure exactly how to trigger it: I think you can run core-lightning with a pruned node, but the amount of pruned data to keep needs to be at least of a certain size.
