### ISSUE TITLE
Payments not showing in wallet 

### ISSUE THREAD

**Issue by TacoScheltema** [btcpayserver/btcpayserver#551]
Hi, I have a bit of a strange issue; after updating btcpayserver about a week ago from GIT (around Jan 17) new payments aren't showing up in my Electrum wallet.
On my btcpayserver I can see 6 payments made after 17 January but my Electrum wallet linked to this store doesn't see them. the wallet total shown on the server is showing a total of 1.23710756 BTC but the Electrum wallet is showing a total  of 1.02731981, the difference is the total of the 6 payments done after the 17th of Jan.
Similarly this same store has a LTC wallet that has received 1 payment. in the Electrum-ltc wallet that's linked to this store I don't see that payment and the balance remains 0. I have verified the receive addresses for BTC and LTC after adding the derivation scheme and they match. 

I have a custom install on a Debian 9 vps. I'm using an apache reverse proxy in front of btcpayserver and the server is behind an OPNSense firewall with NATed ports 80, 443, 8333 and 9333

The apache reverse proxy config is as follows:
```
RewriteEngine on
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /(.*)           ws://127.0.0.1:23000/$1 [P,L]
    RewriteCond %{HTTP:Upgrade} !=websocket [NC]
    RewriteRule /(.*)           http://127.0.0.1:23000/$1 [P,L]
```
in the btcpayserver log I see a number of these lines:
```
warn: PayServer:      Error while contacting binance: The operation has timed out.
warn: PayServer:      Error while contacting binance: The operation has timed out.
warn: PayServer:      Error while contacting poloniex: The operation has timed out.
warn: PayServer:      Error while contacting poloniex: The operation has timed out.
```
in the bitcoind log I see lots of these:
```
2019-01-23T07:29:13Z socket recv error Connection reset by peer (104)
2019-01-23T07:29:22Z socket recv error Connection reset by peer (104)
2019-01-23T07:30:44Z socket recv error Connection reset by peer (104)
2019-01-23T07:30:46Z socket recv error Connection reset by peer (104)
```

I'm a bit at a loss as to what to do next, any ideas?
Let me know if I need to provide more information.

**Comment by NicolasDorier** [comment]
https://docs.btcpayserver.org/faq-and-common-issues/faq-wallet#missing-payments-in-my-software-or-hardware-wallet

**Comment by TacoScheltema** [comment]
Awesome! that worked :) I guess I should improve my google skills ;)

**Comment by NicolasDorier** [comment]
Just improved a bit the message https://github.com/btcpayserver/btcpayserver/commit/37e6931d331e196602b2f64a194e890baf1a66fe
