### ISSUE TITLE
[Bug]: Importing Taproot account from Passport fails with no error

### ISSUE THREAD

**Issue by sethforprivacy** [btcpayserver/btcpayserver#5518]
### What is your BTCPay version?

v1.11.7+a921504bc (Altcoins)

### How did you deploy BTCPay Server?

Docker

### What happened?

Attempted to import a Taproot account export using the new format specified for us in https://github.com/btcpayserver/btcpayserver/pull/5423#issuecomment-1777009350, but the import always failed with no error message beyond:

QR import failed:

OR

Importing wallet failed:

### How did you encounter this bug?

1. Export from Passport for Taproot
2. Import to BTCPay
3. Get error

### Relevant log output

None visible for me.

### Additional information

The export format from Passport was as follows:

`{"Source": "Passport", "Descriptor": "tr([REDACTEDFINGERPRINT/86'/0'/0']REDACTEDXPUB/0/*)", "FirmwareVersion": "v1.0.0"}`

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by sethforprivacy** [comment]
Ping @Kukks

**Comment by pavlenex** [comment]
@sethforprivacy does this still happen with 1.2.3 version?

**Comment by sethforprivacy** [comment]
> @sethforprivacy does this still happen with 1.2.3 version?

Just tested, unfortunately no, still just getting `Importing wallet failed:` via file or QR code.

**Comment by sethforprivacy** [comment]
@pavlenex is there an easy way for me to get some actual logs out of this? I don't see any in the container logs and nothing at all in the web UI.

**Comment by dennisreimann** [comment]
Debugged this and this is mostly due to NBitcoin not supporting Taproot (`tr`) descriptors, yet. 

@NicolasDorier I checked the [OutputDescriptorParser](https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin/Scripting/OutputDescriptorParser.cs) — is this not implemented yet or am I missing it?

**Comment by NicolasDorier** [comment]
will take a look at it

**Comment by sethforprivacy** [comment]
From my testing this is not fixed. I updated to `v1.12.4+2111b67e2 (Altcoins)` and still get an import failure when importing a Taproot account from Passport:

`Import failed, make sure you import a compatible wallet format`

The file used:

[1731cab2-btcpay-001.json](https://github.com/btcpayserver/btcpayserver/files/14056049/1731cab2-btcpay-001.json)

Raw JSON:

```json
{"Source": "Passport", "Descriptor": "tr([1731CAB2/86'/0'/0']xpub6Cg81Cejmn4DoXZYMJVX8cUe97ab7HAMc1QVqJoXaPPzyzpgtuz4oedtAdNxShY4k2sBetB18BrsS8Kapmn6YJppjEfSMewWbiM1Kw8XHKb/0/*)", "FirmwareVersion": "v1.0.0"}
```

Which should yield a receive address 0 of:

![snapshot-$j-10_37_40](https://github.com/btcpayserver/btcpayserver/assets/40500387/1986b872-1ea7-45b3-bab8-1fce42e78232)
