### ISSUE TITLE
Confusion when entering xpub memos / derivation scheme

### ISSUE THREAD

**Issue by Transisto** [btcpayserver/btcpayserver#552]
![image](https://user-images.githubusercontent.com/388716/51664118-a4a70a00-1f86-11e9-9b27-0df3866247bd.png)

The example given confused me.

The xpub I get from my wallet is either X Y or zpub6BtMW7Rc5wX83YQgvjHNRmFu5PGgqLxXGh598547y...

To get legacy addresses do I need to enter xpub-[legacy]6BtMW7Rc5wX83YQgvjHNRmFu5PGgqLxXGh598547y... ?

I suggest just adding "..." to point out that the memo goes at the end of the long xpub....
![image](https://user-images.githubusercontent.com/388716/51665033-d8832f00-1f88-11e9-8c5f-02404d6d7981.png)

https://github.com/btcpayserver/btcpayserver/blob/b15267be4d563760bbf7f2d0cbc6e16714bd805b/BTCPayServer/Views/Stores/AddDerivationScheme.cshtml

**Comment by Kukks** [comment]
no.. `xpub-fjojwegpgkerpgkep-[legacy]`

**Comment by Kukks** [comment]
ah you figured it out, yeah good call in that case :)
