### ISSUE TITLE
PoS app show QR code in settings for easy setup

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5532]
### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/5527

<div type='discussions-op-text'>

<sup>Originally posted by **ndeet** December  1, 2023</sup>
When setting up PoS terminals you link the PoS app on the home screen, as it contains a very long uuid it would be very helpful to display a QR code on the PoS settings page, so you can scan instead of type it. </div>

**Comment by TChukwuleta** [comment]
Hey @pavlenex  

is there like a screenshot to this, cos I am finding hard to understand or replicate the issue

**Comment by ndeet** [comment]
Hey @TChukwuleta it is basically a QR-code of that same link that is behind the "View" button on the top right on when you edit the POS settings, below an example where we would have place to put it but better get feedback on the placement from @dstrukt and @dennisreimann 

![screenshot-mainnet demo btcpay tech-2024 03 05-11_28_58](https://github.com/btcpayserver/btcpayserver/assets/1136761/91a2edf1-b12f-462a-8e06-9d18ac6b2a69)

**Comment by TChukwuleta** [comment]
Thank youu @ndeet

**Comment by dennisreimann** [comment]
Imho we could simply turn the View button into a [button group](https://getbootstrap.com/docs/5.3/components/button-group/#basic-example) with the QR option as the second button. This could then show a [modal](https://getbootstrap.com/docs/5.3/components/modal/) with the QR code.

The behaviour could be the same as on the API keys page:

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/f7d8029f-32dc-40e4-93d1-51f33f456bd7)

**Comment by ndeet** [comment]
Sounds also like a good plan and more consistent with what we have on other places
