### ISSUE TITLE
Add support for Veil

### ISSUE THREAD

**Issue by grigorov** [btcpayserver/btcpayserver#554]
Hi, we can add support Veil ? 

https://veil-project.com/specs/

https://github.com/Veil-Project/veil
Codebase | Bitcoin Core version 0.17.1

**Comment by Kukks** [comment]
You need to code it in yourself or hire a developer to do it. https://docs.btcpayserver.org/development/altcoins

**Comment by Kukks** [comment]
@pavlenex  time to close?
