### ISSUE TITLE
[Bug]: v1.12.0-rc3 New Store Screen not clean anymore = includes parts of menu

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#5542]
### What is your BTCPay version?

© BTCPay Server v1.12.0+d78267d7e 

### How did you deploy BTCPay Server?

docker

### What happened?

Crated a new store, saw this:

![grafik](https://github.com/btcpayserver/btcpayserver/assets/1374810/0994fa66-33a3-42d6-84c5-c2dd09f4a0c9)

### How did you encounter this bug?

see above

### Relevant log output

```shell
see above
```

### What browser do you use?

Firefox on MacOS

### Additional information

none

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by petzsch** [comment]
If I click on the Serilog one as normal user, I get a 403.

**Comment by dennisreimann** [comment]
> I remember this screen to be clean without menu items.

Ok, the question here is whether or not we still want to force the wizard after the user initially dismissed it (exiting the initial wizard via the close button). I think the current behaviour is OK and would keep it like this. /cc @dstrukt 

> If I click on the Serilog one as normal user, I get a 403.

This nees to get fixed on the plugins end.

**Comment by dstrukt** [comment]
ACK to Serilog fix.

Yeah I think the current functionality would work - but alternatively I guess it does beg the question if it's worth removing the `X/cancel` on the wizard on the first store creation, as realistically, you can't do much without a store .. maybe that will change with more plugins, etc... but the wizard flow simplifies that first step.

**Comment by dennisreimann** [comment]
@dstrukt I have user accounts just using LNbank and with those it's even annoying to see the wizard after login. For those accounts I do not need a store and as much as I think the wizard makes sense for the first login, it's imho a distraction on subsequent ones.

**Comment by dstrukt** [comment]
Hmmm..my first thought is, does it make sense to keep the wizard on the first step only? Such that any additional store would only show the left sidebar.. Or even force the user to create a store via the wizard even if they don't use/need it ultimately, no `x/cancel`? 

If not, the wizard, while cleaner, doesn't make a lot of functional sense. Yes it's cleaner, but the intention was to push the user through a simplified and focused set of steps to get them onboarded.

Just trying to simplify the scope of functionality, so apologies if I'm missing something.

**Comment by dennisreimann** [comment]
@dstrukt Right now it is very simple: If the user has a store already, the standard layout is used. If it's the first store, the wizard is used and the user sees it right after login.

I think it makes sense that way and we don't have to repeat the wizard usage for subsequent new stores.
