### ISSUE TITLE
Admins should have an option to approve registered users to their instance

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5548]
If someone decides to expose their instance to public, I think we should have an option where admin first has to approve registered users. This is to prevent abuse and perhaps malicious users registering. I think the ability for admin to allow registertaion to anyone, can still be an option, but by default, I believe that admins should have the ability to approve users manually. 

This feature can be re-used in BTCPay App as well. If we expect ambassadors to onboard people, we should ensure they have sufficient mechanisms to pick who registers on their public instance.

**Comment by dstrukt** [comment]
cACK, will be helpful in refining the onboarding flows necessary for the App

**Comment by pavlenex** [comment]
One thing that should be added here, is that Server admins should be able to gatekeepe user registration via paywall @dennisreimann is working on a subscription plugin, but imo it would be great if that can also touch on this. @dennisreimann let us know if new issue for this is needed. https://github.com/btcpayserver/btcpayserver/issues/461
