### ISSUE TITLE
[Bug]: Remove Bittrex as a rate source since their service is terminated

### ISSUE THREAD

**Issue by Delitants** [btcpayserver/btcpayserver#5550]
### What is your BTCPay version?

 BTCPay Server v1.11.7+a921504bc (Altcoins)

### How did you deploy BTCPay Server?

Self-hosted on VPS, Ubuntu 20.04.4 LTS.

### What happened?

Rates are very off, for example and BTC and that’s not up to current rates. Provider change makes no difference because it’s all going via coin gecko.
bittrex(DOGE_BTC) * gdax(BTC_USD) = 0.0004106549
https://www.coingecko.com/en/coins/dogecoin
This rate does not make sense and during check out for $10 it asks to pay a crazy amount of doge.
Same for BTC.

### How did you encounter this bug?

During checkout

### Relevant log output

See attached

### Are you sure this is a bug report?

- [X] I confirm this is a bug report
[log.txt](https://github.com/btcpayserver/btcpayserver/files/13641934/log.txt)

**Comment by Delitants** [comment]
Had to enable advanced scripting and replace the following line
DOGE_BTC = bittrex(DOGE_BTC);
with
DOGE_BTC = bitpay(DOGE_BTC);
And set default provider to bitpay as well.

**Comment by pavlenex** [comment]
@Kukks @NicolasDorier It seems we need to remove bittrex from the source of rates as they are dead?
