### ISSUE TITLE
[Bug]: import rss feed for podcaster plugin crashes server

### ISSUE THREAD

**Issue by ralyodio** [btcpayserver/btcpayserver#5559]
### What is your BTCPay version?

Enable podcast hosting plugin, and import an feed.rss file.

Click "import" -- from then on everything is a blank screen on the server.

### How did you deploy BTCPay Server?

lundanode

### What happened?

Enable podcast hosting plugin, and import an feed.rss file.

Click "import" -- from then on everything is a blank screen on the server.

### How did you encounter this bug?

Enable podcast hosting plugin, and import an feed.rss file.

Click "import" -- from then on everything is a blank screen on the server.

### What browser do you use?

firefox/linux

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Closing and tracking this in dennisreimann/btcpayserver-plugin-podserver#8
