### ISSUE TITLE
[UI] Error message, red on black font can easily be missed.

### ISSUE THREAD

**Issue by nostitos** [btcpayserver/btcpayserver#5564]
When saving a setting page and there's error it jump to the top and the error are summarized there but red on black makes it easily missed.

Instead the error message could be as part of a red box like green 2nd image.

![image](https://github.com/btcpayserver/btcpayserver/assets/48504624/51b4669a-7ca1-4a6c-ac3a-f4cdf9ef7669)

VS

![image](https://github.com/btcpayserver/btcpayserver/assets/48504624/a621a7b2-0e27-4bd9-b564-ad67e65213b5)

**Comment by pavlenex** [comment]
cc @dstrukt @dennisreimann anything we can do in our design system to address this, it's a fair statement I think, should we handle this warnings in more obvious way?

**Comment by dennisreimann** [comment]
As suggested we could display them in the alert style, with white text on red background.
