### ISSUE TITLE
Rework code examples and prominently display them in the Greenfield API documentation

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5572]
**Problem:**
One thing @ndeet noticed, is that people often type in "BTCPay API" in google, they land here https://docs.btcpayserver.org/API/Greenfield/v1/ but then they always come to the chat to ask for examples, especially authentication examples. 

While we have examples in dev docs here https://docs.btcpayserver.org/Development/ they are not referenced in the Greenfield API docs, so it's obvious it's very hard for a new dev to  figure out where they need to go.
![Screenshot 2023-12-20 at 12 14 13](https://github.com/btcpayserver/btcpayserver/assets/36959754/ac75dbe7-37c2-4b05-988d-ad731fdb1e26)

Since we're automatically generating this page, is there something we can do to improve this experience, what is the best practice here, should we simply link to these examples in the Authentication paragraph, should we add these links in the sidebar? I am definitely not an API/Architecture expert, so before implementation, we should come to a consensus on how this should be achieved.

**Comment by dennisreimann** [comment]
What about matching the docs header like this? Instead of having the docs links like on the right, we could have links to the API docs instead.

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/b5eba4b7-73c2-431a-99db-931490a4c234)

**Comment by pavlenex** [comment]
Sure that can help, i still think these specific examples should be a bit more visible in the API for devs who want to get immediately started. Perhaps just linked as examples in bullets or something? @ndeet any thoughts?

**Comment by hiluan** [comment]
> **Problem:** One thing @ndeet noticed, is that people often type in "BTCPay API" in google, they land here https://docs.btcpayserver.org/API/Greenfield/v1/ but then they always come to the chat to ask for examples, especially authentication examples.
> 

This is 100% true, especially concerning the "authentication examples." Last year, I gave up after trying for a while. This year, I decided to give it another try, and I managed to make it work with authentication, thanks to ChatGPT. So the user experience is not ideal, requiring users to jump through many loops to get it right.

In my opinion, we could include the examples directly in the documentation so that new users don't have to navigate across various websites and pages for sample code. Like these:

![Screenshot 2023-12-26 193451](https://github.com/btcpayserver/btcpayserver/assets/76276426/c5f48432-cdff-4125-beb5-da88b446812b)
https://finnhub.io/docs/api/company-basic-financials

![Screenshot 2023-12-26 193236](https://github.com/btcpayserver/btcpayserver/assets/76276426/938bdd18-0094-4ad8-a313-5eebfd5494e4)
https://stripe.com/docs/upgrades/manage-payment-methods

**Comment by pavlenex** [comment]
@hiluan That's pretty solid suggestion.  @Kukks @NicolasDorier @dennisreimann thoughts on adding examples directly in the API docs like this?

**Comment by dennisreimann** [comment]
I just checked and we can do this [in ReDoc via the `x-codeSamples` extension](https://github.com/Redocly/redoc/blob/main/docs/redoc-vendor-extensions.md#code-sample-object). It would look something like this:

![Peek 2024-01-04 12-53](https://github.com/btcpayserver/btcpayserver/assets/886/5ff782cb-54fe-4a1e-8641-9e0dbcb11543)


Two minor drawbacks:

- It works only on the operation level, so we cannot directly add this to the authentication section.
- As we use JSON, which doesn't support multiline strings, it is tedious to write the samples.

This is what the JSON for the Create User samples would look like:

```json
"x-codeSamples": [
    {
        "lang": "shell",
        "label": "cURL",
        "source": "BTCPAY_INSTANCE=\"https://mainnet.demo.btcpayserver.org\"\nUSER=\"MyTestUser@gmail.com\"\nPASSWORD=\"NOTVERYSECURE\"\n\nbody=\"$(echo \"{}\" | jq --arg \"a\" \"$USER\" '. + {email:$a}' \\\n                  | jq --arg \"a\" \"$PASSWORD\" '. + {password:$a}')\"\ncurl -s \\\n     -H \"Content-Type: application/json\" \\\n     -X POST \\\n     -d \"$body\" \\\n     \"$BTCPAY_INSTANCE/api/v1/users\""
    },
    {
        "lang": "javascript",
        "label": "Node.js",
        "source": "const btcpayserverurl = 'https://mainnet.demo.btcpayserver.org'\nconst apiendpoint = '/api/v1/users'\nconst token = 'APIKEYTOKEN'\nconst headers = {\n  'Content-Type': 'application/json',\n  Authorization: 'token ' + token\n}\nconst user = {\n  email: 'MyTestUser@gmail.com',\n  password: 'NOTVERYSECURE',\n  isAdministrator: false\n}\n\nfetch(btcpayserverurl + apiendpoint, {\n  method: 'POST',\n  headers: headers,\n  body: JSON.stringify(user)\n})\n  .then(response => response.json())\n  .then(data => { console.log(data) })"
    },
    {
        "lang": "PHP",
        "source": "require __DIR__ . './vendor/autoload.php';\n\n$host = 'https://mainnet.demo.btcpayserver.org';\n$apiKey = 'pQc2FYhYwNzhf4DF7Foo6YpQc2FYhYwNzhf4DF7Foo6Y';\n$email = 'test@test.com';\n$password = 'Testing##123';\n$isAdministrator = false;\n\ntry {\n  $client = new \\BTCPayServer\\Client\\User($host, $apiKey);\n  var_dump($client->createUser($email, $password, $isAdministrator));\n} catch (\\Throwable $e) {\n  echo \"Error: \" . $e->getMessage();\n}"
    }
]
```

**Comment by ndeet** [comment]
@pavlenex the docs header link was fixed here https://github.com/btcpayserver/btcpayserver/pull/5772

not sure about the other outlined parts where we have those examples in different languages like suggested by @dennisreimann did we say we don't do it for now or what was the conclusion?

**Comment by pavlenex** [comment]
The conclusion is that we want to implement them, and re-work and improve existing ones and add them in a  way @dennisreimann proposed. Kukks said he'll do it , but on the last dev call you offered to help with those examples?

**Comment by ndeet** [comment]
I would think the ones shown by Dennis can be generated? 

My offer for help was for the general examples in the docs here https://github.com/btcpayserver/btcpayserver-doc/issues/1371

**Comment by pavlenex** [comment]
@ndeet Yeah, but we should feature those in the /api not on /docs to ensure they're visible there ? I guess once there's text and code examples, D11n can implement it visually stylistically?

**Comment by ndeet** [comment]
Normally the api reference docs are only describing the endpoints and document that, like we have now. Not sure duplicating the examples in there is possible in a nice way as swagger works with datasets and generates the output. Also not sure it is the right place to do it, api reference is only describing the endpoints normally. How to guides and walksthroughs are often on blog posts or docs., so it seems the wrong place for overall examples using multiple endpoints and the docs are the right place for it, imho.

We already link the to the docs examples at the top of the swagger docs as done here https://github.com/btcpayserver/btcpayserver/pull/5772

**Comment by pavlenex** [comment]
@ndeet How is Stripe handling this? I think whenever we're in doubt wrt API, we look there and approach it in a same way.

**Comment by pavlenex** [comment]
Closing in since it's broken down in smaller tasks in #5820 #5821 #5822 thanks @ndeet
