### ISSUE TITLE
[Bug]: prism: payouts always stuck

### ISSUE THREAD

**Issue by massmux** [btcpayserver/btcpayserver#5574]
### What is your BTCPay version?

btcpay 1.12
prism updated today latest.

### How did you deploy BTCPay Server?

ubuntu 

### What happened?

tested with these sources: lnbits, alby, localnode
payouts are always stuck. in the previous version all was ok (a part with lnbits which did not work even before)

### How did you encounter this bug?

just activate a prism to a destination. when a payment arrives that should trigger the payout. it always remain pending awaiting

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
This needs to be in Prism repo not here, plugins aren't part of BTCPay Server main repo, they belong to their own repos where authors  maintain them.
