### ISSUE TITLE
Remove `Randomize RBF`from wallet UI advanced settings and use mempoolrbf=enabled as a default

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5580]
Context: Currently, in advanced wallet settings, we offer `Randomize RBF` which apparently can help with privacy, however this default option often.

Recent conversation from Mattermost is here for more context:
![Screenshot 2023-12-21 at 13 55 37](https://github.com/btcpayserver/btcpayserver/assets/36959754/ae550602-c985-4451-bece-72bb39da83b9)

Solution: Remove this option from the UI, since the privacy enhancements it brings are minuscule compared to UX improvements enabling it by default could bring, and  enable it by default. 

Related  #5578 #2082

**Comment by TChukwuleta** [comment]
Can I tackle this or is someone else on it?

**Comment by pavlenex** [comment]
@TChukwuleta No because there's no consensus on this yet.

**Comment by NicolasDorier** [comment]
can be removed I think.

**Comment by NicolasDorier** [comment]
@pavlenex I think there is? probably something @TChukwuleta can do

**Comment by NicolasDorier** [comment]
@TChukwuleta we discussed internally and this issue is good to go if you feel motivated tackling it.

If you can remove from the UI and cleanup the dead code resulting from it, it would be perfect.

**Comment by TChukwuleta** [comment]
Sure.  Thanks @NicolasDorier

**Comment by Kukks** [comment]
@nicolasdorier are you sure that it is to be removed entirely? If you turn
off mempool rbf on your bitcoin node, setting rbf on the tx still applies?

**Comment by NicolasDorier** [comment]
You can't turn off mempool rbf on a bitcoin node. What you can turn on is for the node to ignore rbf signaling (and thus consider every transaction as RBF)

The PR of @TChukwuleta will just set every transaction to signaling RBF, whichever your node config this will always be correctly interpreted.
