### ISSUE TITLE
Wallet UI for multisig

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5582]
_This issue is a placeholder, not to be worked on immediately, the goal is to kick-start a wider discussion if and how this can be achieved._

Context:
BTCPay currently supports multisig to be added as a derivation source allowing users to accept bitcoin to their multisig wallet. However our UI currently doesn't support multisig UI, so it's not really intuitive for an enterprise merchant to sign transactions through our UI. 

Perhaps we don't really need a UI, but instead want to communicate which external wallets should be used, this would be easier to achieve.

Opening this one for discussion as agreed on a dev call.

**Comment by Ashleyhen** [comment]
[unchained capital](https://unchained-capital.github.io/caravan/#/wallet) has a pretty cool multi-sig wallet might be cool if we could somehow integrate with that
https://github.com/unchained-capital/caravan

**Comment by hell0-w** [comment]
Very good topic, I'm looking forward to the multi-signature functionality in the API/Webhook implementation.

I have a small project created to work with API/Webhook, which requires increased security when withdrawing funds. 

I would like to get the functionality (concept):
microservice allows to prepare payment (according to different triggers: hours, accumulation amount, day of the week, etc.) by signing 1 of 2 signatures.
then I or some automatic checker makes the withdrawal by signing 2 out of 2 signatures. 

Now I have tested it with electrum wallet. (multisign)
everything works. 
If two wallets are installed, I can take turns signing a payment with signatures, I am looking for options how to automate this.

If caravan/electrum wallet or any other implementation with multi-signature key operation will be introduced, it will help me a lot in my project and will also increase the security of the transaction work in general.
