### ISSUE TITLE
(bug) interpolation broken for email placeholders in 1.12

### ISSUE THREAD

**Issue by MattDHill** [btcpayserver/btcpayserver#5584]
After updating to 1.12, our email placeholder for Invoice.OrderId is not interpolating. Exact text below.

"Thank you for your purchase! Your payment for order #{Invoice.OrderId} is confirmed."

**Comment by pavlenex** [comment]
I replicated this one, due to holidays it's unlikely we'll be able to push a release soon, but we'll see if we can do something tomorrow. 

Meanwhile, I recommend trying Zapier integration as a temporarily solution until our email form is fixed. https://docs.btcpayserver.org/Zapier/#free-to-use

**Comment by NicolasDorier** [comment]
did emergency release on this 1.12.2
