### ISSUE TITLE
[Bug]: Uninstall Plugins via UI not possible (Button missing)

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#5585]
### What is your BTCPay version?

BTCPay Server v1.12.1+ebc053aca 

### How did you deploy BTCPay Server?

Docker

### What happened?

When trying to uninstall a plugin, I'm missing the button to do so:
![grafik](https://github.com/btcpayserver/btcpayserver/assets/1374810/e4002859-8abe-418a-ad32-54a6591f2d79)

### How did you encounter this bug?

Install 1.12.0, update all the plugins, trying to uninstall a plugin => no button for it.

### Relevant log output

```shell
none
```

### What browser do you use?

Firefox on Windows 11

### Additional information

none

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Replicated this one in 1.12.1 this is quite concerning and should be addressed in the next bug-fix release. Perhaps meanwhile here we can tell people how to uninstall plugins via command line cc @dennisreimann ?

**Comment by dennisreimann** [comment]
To delete a plugin via CLI one can proceed like this:

```bash
# Go to plugins directory
cd /var/lib/docker/volumes/generated_btcpay_pluginsdir/_data

# List all installed plugins
ls -lA 

# Uninstall a plugin (this only removed it from the file system, it keeps the data in the database)
rm BTCPayServer.Plugins.PluginName
```

**Comment by pavlenex** [comment]
Thanks @dennisreimann, I'll make sure to mention that to people.

**Comment by NicolasDorier** [comment]
did emergency release on this 1.12.2
