### ISSUE TITLE
[Bug]: occasional false altcoiner accusations at boot

### ISSUE THREAD

**Issue by Sjors** [btcpayserver/btcpayserver#5595]
### What is your BTCPay version?

v1.12.3

### How did you deploy BTCPay Server?

Built from source (organic Docker free) on Ubuntu 23.10.

### What happened?

Once every other restart I get:

``
Dec 22 12:41:04 sjimmie systemd[1]: Started btcpay.service - BtcPayServer daemon.
Dec 22 12:41:04 sjimmie dotnet[347872]: info: Configuration:  Data Directory: /home/btcpay/.btcpayserver/Main
Dec 22 12:41:04 sjimmie dotnet[347872]: info: Configuration:  Configuration File: /home/btcpay/.btcpayserver/Main/settings.config
Dec 22 12:41:04 sjimmie dotnet[347872]: info: BTCPayServer.Plugins.PluginManager: Loading plugins from /home/btcpay/.btcpayserver/Plugins
Dec 22 12:41:05 sjimmie dotnet[347872]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.NIP05 - 1.1.3.0
Dec 22 12:41:05 sjimmie dotnet[347872]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.LNbank - 1.9.0.1
Dec 22 12:41:05 sjimmie dotnet[347872]: fail: Configuration:  This build of BTCPay Server does not support altcoins
Dec 22 12:41:05 sjimmie systemd[1]: btcpay.service: Deactivated successfully.
Dec 22 12:41:05 sjimmie systemd[1]: btcpay.service: Consumed 1.853s CPU time.
```

This started happening after upgrading from v1.12rc3 to v1.12.3. The only plugin I had at the time was Nostr, which I had updated to 1.1.3.0. I later installed LNbank as you can see in the log, but the issue was already happening.

One or two restarts got rid of the problem. But it comes back.

### How did you encounter this bug?

See above

### Relevant log output

```shell
See above
```

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
We merged #5593 already and @NicolasDorier is taking a look what's going on.

**Comment by Sjors** [comment]
Cool, if I see it again after the next update I'll post additional log details here.

**Comment by NicolasDorier** [comment]
It seems that the `BitcoinPlugin` isn't running for some reason.

**Comment by NicolasDorier** [comment]
I found the issue.

This happen because some plugin is resolving `BTCPayNetworkProvider` before `BitcoinPlugin` ran.

**Comment by NicolasDorier** [comment]
Fixed by https://github.com/btcpayserver/btcpayserver/commit/0b0a8f82180edc4b7bc1db1fe3c6d72fe33e5e43

When the server restart after installing a new plugins, some plugin management commands need to run. When it was happening, all the system plugins wouldn't run, resulting in the above message.
