### ISSUE TITLE
Handle Reset password link on login when Server's SMTP is not configured

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5597]
**Context:**
Often time users register to a server which doesn't have email smtp configured, which then leads them into coming to our chat asking they're not receiving email reset password upon submitting the form:

**Solution:**
There are two possible solutions to this:
1. We hide the password link the server doesn't have SMTP configured. It's easy to implement, but still doesn't solve a problem for users and can potentially lead them into coming to chat and asking how to recover the account.
2. Instead of hiding link, we show a different view when user clicks `forgot password`. That view ideally could give a bit more context. 

_Email password reset functionality is not configured for this server. Please contact the server administrator to assist with account recovery. If you are the administrator, please follow these steps to [configure email password resets](https://docs.btcpayserver.org/Notifications/#smtp-email-setup) or reset your admin password through [command line](https://docs.btcpayserver.org/FAQ/ServerSettings/#forgot-btcpay-admin-password)_

So this is not yet to be implemented, let's discuss how we can acheive this.

**Comment by dennisreimann** [comment]
We should go for the second option and replace the form on the forgot password page with that text.

To make contacting the amin easier, we could then also add a contact email address for the server instance, which can be maintained in the `Server Settings > Maintenance` section alongside with the domain.

**Comment by pavlenex** [comment]
Yes, I agree with what you've pointed out @dennisreimann. Since this is for 1.14, let's not prioritize discussion on specifics right now, but I think what you outlined makes sense as an action plan to tackle this issue.

**Comment by gkrizek** [comment]
I think the Admin should be able to reset a user's password in the Admin section of the dashboard. Right now an Admin can list all users on the server, Disable/Enable them, and remove them. We should have the ability to also reset their password too because SMTP or CLI arent' always good options.

**Comment by dennisreimann** [comment]
@gkrizek Agreed, good point and thanks for the feedback!

**Comment by TChukwuleta** [comment]
> setting up an SMTP server.

Was thinking, since there is already a contact address in branding, would there be need for another under maintenance.
