### ISSUE TITLE
Disable `tips` and `discounts` by default in POS

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5600]
For some reason, by default we add discount and tips features, which in most cases should be left to the user to enable if needed, and we should show a straightforward barebone keypad pos by default.

**Comment by TChukwuleta** [comment]
Hello @pavlenex 

So I made an update that disables tips and discounts by default. However the second part of the issue:
"we should show a straightforward barebone keypad pos by default."

Please can you give more details to this.

**Comment by dstrukt** [comment]
ACK to no discount / tips by default, and @TChukwuleta I believe @pavlenex means no other changes beyond turning off tips / discounts, that is "additional" functionality to the default / out of the box keypad functionality

**Comment by TChukwuleta** [comment]
Oh, Ok.

Thanks @dstrukt
