### ISSUE TITLE
[Bug]: upgrade dashd

### ISSUE THREAD

**Issue by chostorg** [btcpayserver/btcpayserver#5605]
### What is your BTCPay version?

Latest version

### How did you deploy BTCPay Server?

docker script

### What happened?

dash won't sync up to date

### How did you encounter this bug?

dash won't sync

### Relevant log output

```shell
This is related to #5034, current dash version doesn't work properly, and needs to be updated to latest version.
```

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
I think the log error gives you pretty good explanation? https://github.com/btcpayserver/btcpayserver/issues/5034#issuecomment-1602509873

**Comment by chostorg** [comment]
I've already done that (removing the data files, everything except wallet.dat), multiple times.

**Comment by chostorg** [comment]
Please bump again to the latest version of dashd, the current included one is not working.
