### ISSUE TITLE
Add optional, pre-defined fields (default metadata) in payment request to make it look like an actual invoice

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5606]
**I am still thinking on a proper on this one but filing an issue so I don't forget.**

**Context**:
Payment requests in BTCPay are great example how people can pay each other online. There is one obvious use-case around which we designed payment request - people invoicing each other. There are several simple improvements we can make in payment requests to cater for this use-case even better.

**Problem:**
Currently payment requests don't look like a typical invoice which a freelancer can share with a client, it's missing certain obvious fields that are required in order to make it look like traditional invoice. 

<img width="591" alt="Screenshot 2023-12-22 at 16 42 23" src="https://github.com/btcpayserver/btcpayserver/assets/36959754/0e8ba09a-490f-4be6-963d-606e5bb2fab0">

**Comment by dennisreimann** [comment]
@NicolasDorier I don't think we have to go that far. The main use case here is to have whatever info one would put on an invoice, so as a merchant/freelancer/whatever I know whom I'm sending this too and can provide the address etc. myself.

**Comment by NicolasDorier** [comment]
But isn't it already the case? You can put whatever you want in the description

**Comment by pavlenex** [comment]
@NicolasDorier Sure, but when I send you the invoice, are you the one filling in my data then? As I said before, `Description` don't really make it look like an actual invoice, actual invoice has a certain fields that are structured in a very specific way.

**Comment by dstrukt** [comment]
I still think the notion of combining `Payment Requests` (essentially an invoice with a public facing link and UI) and `Invoices` makes sense.

Agree that the description field is not sufficient to capture all of the mostly standardized information. That would be a place you'd put a nice note such as `Thanks for your business!`

### On the admin side:

- You can add a Product/Item (either something from your POS) or a 1-time custom Item, with the item description, price, and quantity associated. It could be extended to even allowing either rate OR quantity, and you'd cover most cases with this. This would be extended to total cost breakdowns on the payment request (as opposed to the single value price to pay we currently display).

- You can add your own store metadata (if you wish): Address, Phone Number, etc...) and allow the admin to Enable (or Disable) showing this publicly on your payment request.

- If you know your customer's information (address, name, etc..), that could also be added to the invoice/payment request as an optional field (to match the standard invoice format @pavlenex describes), or if the admin doesn't have this information, but wants it, they can just collect it via our custom form checkout process.

- We have the Due Date / Creation Date / Invoice # and IDs

- We already have Store Name, Logo, website, etc.. but we could add a toggle to allow admins to show every piece of information (we currently don't)

### On the end-user side:

They see the typical payment request / invoice, and depending on what information the admin has enabled to see (the Store address info, Product list, etc...) the end-user proceeds to the checkout flow, and collect any additional information (Name, Address, etc...) that they want, in case they don't already have that info to begin with (as mentioned above).

Maybe I've missed something or additional context, but if I understand correctly, all of this could be mocked up quite easily so we have mocks to reference and draw scope around!

**Comment by LynnK1947** [comment]
What does it mean when it Trust error 400

**Comment by pavlenex** [comment]
Closing this one, we have so much work to do that we can't get to this one in the next few months, will re-scope and re-open as I think more about it.

**Comment by prepsin** [comment]
From a business point of view, 'payment requests' is very basic and does not give the sender/business the ability to create an invoice or even attach an invoice to the request. 

Having used the feature, the only thing that can be set is the amount, a subject email title and a description.

Of course you can put in the description what you are selling (requesting money for), e.g.
10x Widgets at a cost of $10/unit for a total of $100
Shipping is $20
Taxes $20
Total invoice value is $140.00

But typing this is quite tedious and does not allow the sender to save a copy of this invoice somewhere.

Invoices and storing/keeping invoices is pretty standard amongst businesses no matter what country you are in. It would be good to use BtcPayServer as a way to request money from other businesses in a professional way.
