### ISSUE TITLE
[Bug]: Checkout v2 copy on QR code does not have lightning invoice

### ISSUE THREAD

**Issue by iBobik** [btcpayserver/btcpayserver#5625]
### What is your BTCPay version?

v1.11.7+a921504bc

### How did you deploy BTCPay Server?

Docker

### What happened?

QR code is correct, texts under it is correct, but when I click on the QR code it will copy only on-chain address.

### How did you encounter this bug?

Created invoice and clicked on the QR code.

### What browser do you use?

Safari

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
I can't replicate this,  can you please try a newer version.

**Comment by pavlenex** [comment]
Alright, replicated, so the issue is not scanning, but clicking on the QR.

**Comment by iBobik** [comment]
I see the cause in this line:
https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Views/Shared/Lightning/LightningLikeMethodCheckout-v2.cshtml#L6

26. 12. 2023 23:08:27, Pavlenex ***@***.***> napsal:
