### ISSUE TITLE
[Bug]: Metadata isn't sent to Webhook

### ISSUE THREAD

**Issue by deadcoder0904** [btcpayserver/btcpayserver#5637]
### What is your BTCPay version?

© BTCPay Server v1.6.12.0

### How did you deploy BTCPay Server?

Clovyr's hosted version

### What happened?

`metadata` isn't sent to webhook despite being set.

i've explained everything in depth [in a discussion with reproduction](https://github.com/btcpayserver/btcpayserver/discussions/5633)

### How did you encounter this bug?

I wanted to add user to database from webhook like stripe works but couldn't get `email` & payment details so went on a search.

### What browser do you use?

Edge

### Additional information

I've made a minimal repo with a working version. Installation instructions can be found in `README.md` -> https://github.com/deadcoder0904/btcpayserver-nextjs/

I have to send [1 additional call](https://github.com/deadcoder0904/btcpayserver-nextjs/blob/36550e38c8b0e754d85c8a41a2bc33eec7adb4f9/src/app/api/btcpayserver/webhook/route.ts#L50-L61) which shouldn't be needed at all.

It looks like [someone opened a similar issue](https://github.com/btcpayserver/btcpayserver/issues/4223) before & [it was solved](https://github.com/btcpayserver/btcpayserver/pull/4370) but it didn't work for me.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by leesalminen** [comment]
Per [0], the latest version available version is v1.12.3. Your version (v1.6.12.0) is over a year old. Contact your hosting provider and ask them to update your instance of btcpayserver. 

[0] https://github.com/btcpayserver/btcpayserver/releases

**Comment by deadcoder0904** [comment]
hot damn, i thought they keep updated versions since clovyr is recommended on btcpayserver itself.

didn't know it was an old version issue haha. makes sense since it was already solved in linked pr. i was stupidly scratching my hair for a week.
