### ISSUE TITLE
Repetitive IPNs

### ISSUE THREAD

**Issue by JeffVandrewJr** [btcpayserver/btcpayserver#564]
With `fullNotifications` set to `True`, BTCPay server correctly sends multiple IPNs for different invoice statuses. However, on fast confirming payments (namely lightning and also payments where the user has set BTCPay to consider zero confirmations as confirmed) BTCPay sends multiple duplicate IPNs instead separate IPNs.

Example:

With `fullNotifications` set to `True`, with an **on-chain payment**, BTCPay will send an IPN on 'paid', and another IPN on 'confirmed', and another one on 'complete'. All is good. 

With `fullNotifications` set to `True`, with a **lightning** payment, the BTCPay logs will show an IPN will sent an IPN on 'paid,' and another on 'confirmed', and another on 'complete', as would be expected. But in reality, the receiver instead gets 3 IPNs that all say 'confirmed' instead of getting 1 'paid', 1 'confirmed', and 1 'complete.'

I just pushed an update to LibrePatron that works around this issue by ignoring the duplicate IPNs (submitted a PR for the new Docker fragment so my users can get a fix, please merge into btcpayserver-docker!), but this would create problems in other scenarios.

It seems like a short delay between status updates would be the fix. Send a 'paid' IPN, give a short delay for the recipient to receive the IPN, then recipeint pings BTCPay for 'paid' status. Then change the status to 'confirmed', again another short delay so that the recipient can receive and ping for status, then finally send 'complete'.

**Comment by pavlenex** [comment]
I've noticed the same in WooCommerce plugin. It does not trigger any bugs there, but just looks very weird when you preview the order notes.

![screen shot 2019-01-28 at 10 09 40](https://user-images.githubusercontent.com/36959754/51825351-df8da280-22e4-11e9-81f6-83c44b3e66ca.png)

**Comment by JeffVandrewJr** [comment]
Closing because I think I figured this out.

**Comment by Kukks** [comment]
Reopen if it's still a bug in BtcPayCon @JeffVandrewJr

**Comment by NicolasDorier** [comment]
What happened @JeffVandrewJr ?

**Comment by JeffVandrewJr** [comment]
@NicolasDorier @Kukks Based on your comments, I am reopening this issue. Feel free to close it if you think it's not worth adjusting.

I apologize for the long explanation as to the underlying cause of the behavior that I've seen and which @pavlenex also has seen in WooCommerce.

The underlying cause of seeing triplicate `complete` notifications is somewhat related to #205. Right now, when `fullNotifications` is set to `True`, you get 3 IPNs: paid, confirmed, and complete. 

The underlying issue is that the `status` field in the JSON data received is always set to `new` for all three IPNs regardless of the real status, which in turn means the only "real" status updates you get are from pulling the current status from BTCPay, which in the case of lightning will always be `complete`. Hence you see `complete` in triplicate.

I know that the JSON data in the IPN is unsigned and therefore insecure, and that upon receipt I have to take the `id` and pull the real data from BTCPay. But having every IPN set to `new` is still inefficient because it requires that I check every IPN with BTCPay, even ones I may not care about. 

It also creates weird logging issues, as @pavlenex pointed out. I don't use WooCommerice, but I can assume the reason @pavlenex sees that weird data in the WooCommerce plugin relates to this. Because the plugin is getting multiple IPNs with identical `new` status, it has to check all three of them and pull the status for each directly from BTCPay. In the case of a lightning payment, all three status checks will yield `complete`. meaning his plugin logs `complete` status three times.

The better solution would be to send the three IPNs with their real statuses: `paid`, `confirmed`, and `complete`. I would still need to ping BTCPay to check their validity, but this would be an improvement for two reasons:

1. I can have my backend logic accept the posted JSON data as correct so long upon checking with BTCPay the payment status is at equivalent or higher. For example, if I get a `paid` IPN for a lightning invoice, when I check it BTCPay will tell me `confirmed`, but because `confirmed` is greater than `paid` I can still log that IPN as `paid` IPN. In the case of the WooCommerce plugin, this would give the merchant a clearer picture, showing a log of `paid` --> `confirmed` --> `complete` instead of `complete` --> `complete` --> `complete`.

2. It improves efficiency. Some software may not care about certain statuses. You could have an app that doesn't care about `complete` invoices if it has already logged `confirmed`, for example, so when it receives an IPN marked `confirmed`, it can just return `200` and not bother checking BTCPay for status. In the current system, it can't assume anything and it needs to check every IPN, even the ones it may find irrelevant.

The most current versions of LibrePatron and BTC-QBO work around this issue, but the backend could be more efficient if the `fullNotifications` gave real statuses. Currently `extendedNotifications` does give real status on the IPNs, but setting that to `True` gives a level of notifications that few applications need.

**Comment by NicolasDorier** [comment]
I may have fixed it, checking...

**Comment by NicolasDorier** [comment]
@JeffVandrewJr I pushed `1.0.3.51`. However I don't want to update the `btcpayserver-docker` until you try it.

Can you update your `$BTCPAY_DOCKER_COMPOSE` manually, run `btcpay-up.sh` and test again?
What you should see is that events now have proper status.

**Comment by NicolasDorier** [comment]
Cool will release new version later today. (Still some other fixes in the pipes)
