### ISSUE TITLE
Point of Sale app - introduce advanced link for hosting externally 

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#565]
At the bottom of the POS app, there's a lot of clutter that not only is not useful for regular users, but it also is incorrect.

We should either have a simple "copy url" link with an iframe `<iframe style="width: 100%; height: 300px;" src="https://store.btcpay.co/apps/31231231123/pos/"></iframe>` for people to embed the POS into their sites easily (like we have with payment button) and hide the rest of the advanced stuff with "Advanced" toggle link.

![2019-01-28_10-51-33](https://user-images.githubusercontent.com/36959754/51827992-e61f1880-22ea-11e9-834b-a24b6bf55380.png)

This is how it looks (and works) with the Pay Button

![screen shot 2019-01-28 at 10 55 06](https://user-images.githubusercontent.com/36959754/51828168-4dd56380-22eb-11e9-8912-0d050662be32.png)

- Remove or modify the "Host button externally section" as it's obviously just bluntly copied from pay button
- Add advanced toggle link which will toggle additional options i those are really needed.

**Comment by NicolasDorier** [comment]
hu? why is it incorrect?

**Comment by pavlenex** [comment]
Idk, because it adds a button and has all sorts of overwhelming info for regular users.
It should allow in most cases embed of entire POS and not the button itself.

Or if you really want button: 
- Have copy link for button
- Have copy link for iframe or other way of embedding the POS on a page
- Hide other things with a discreet advanced link

**Comment by pavlenex** [comment]
[Added.](https://github.com/btcpayserver/btcpayserver/pull/576)
