### ISSUE TITLE
Add support for a follow up `Account Approved` email

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#5656]
## Reasoning:
If the `Admin Approval` flag is enabled, a user must wait for admin approval before logging in, but currently there is no indication that the admin has approved your account unless the user or admin reach out to each other directly.

## Proposal:
A simple follow up email letting the user know their pending account sign up has been approved. This will become more relevant with the upcoming app flows.

@pavlenex Feel free to add any additional context.

**Comment by dennisreimann** [comment]
Added this in #5647.
