### ISSUE TITLE
Cleanup in Server Settings > Policy to reduce ambiguity when enabling/disabling certain settings

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5660]
Currently, we're inconsistent with certain options in Server settings, and user not reading carefully may enable certiain options by ticking the box (which is what should be default behaviour).

Example 
<img width="841" alt="Screenshot 2024-01-15 at 13 34 44" src="https://github.com/btcpayserver/btcpayserver/assets/36959754/655a1c20-96d7-48d2-ba75-663be63d250a">

- `Enabling public user registration`
   - Enabling this allows anyone to register to your server and may expose your BTCPay Server instance to potential security risks from unknown users.
 - `Allowing non-admins to access API endpoints`
 -  Enabling this may expose your BTCPay Server instance to potential security risks from unknown users.

Cc @dstrukt @dennisreimann for suggestions on the copy

**Comment by dennisreimann** [comment]
Let's do this once #5647 and #5629 are done, because they also change the policies view and already contain changes to the wording of some settings.

**Comment by OscarZara** [comment]
bitcoin:bc1qfkxmqz70p95yxl5d407d4w44x3e44l82q8f9xs?amount=0.00150064

**Comment by dstrukt** [comment]
Few thoughts on the UI, will revisit the copy once we have #5647 and #5629 merged: 

- we should use toggles to make the On/Off state more clear

- @pavlenex and I also discussed, we should be consistent in state/direction, e.g. Turning something On should Enable it, as opposed to the above where checking something On is instead Disabling it, bit confusing to describe, but I think the idea is clear

- Just tense nits (wrt consistency):
`Enabling public user registration` -> `Enable public user registration`
`Allowing non-admins to access API endpoints` -> `Allow non-admins to access API endpoints`

Worth a bit of discussion in tomorrow's design call, time permitting.

**Comment by dennisreimann** [comment]
Status once #5647 is merged:

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/af989b51-bea3-452a-ac16-a78729cddcfe)

**Comment by dstrukt** [comment]
Proposal for this:

Combine Maintenance (as it will become more important with the introduction of plugins), Theme (similar to branding, etc...), and Policies (generalized, but somewhat specific server settings from my POV) into a `General` tab that is the first item. Thus that the list becomes:
- General
- Users
- Roles
- Email
- Services (still think this could use a better name IMO)
- Files
- Logs

Will explore a mock of the above, but wanted to float the idea.
