### ISSUE TITLE
[Bug]: Your nodes are synching message stays forever

### ISSUE THREAD

**Issue by sync-tester** [btcpayserver/btcpayserver#5661]
### What is your BTCPay version?

I'm running  BTCPay Server v1.12.3+f23078df1 (Altcoins) 

### How did you deploy BTCPay Server?

Docker

### What happened?

My nodes are synced, but the pop up never updates.

### How did you encounter this bug?

Load the WebGui

### Relevant log output

```shell
None
```

### What browser do you use?

Firefox

### Additional information

![nodes](https://github.com/btcpayserver/btcpayserver/assets/5975376/5bc43f1b-9c84-4aee-a48f-a3785ac79a71)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
In this case it's because for Monero there is no wallet available. The nodes seem to be synched.

**Comment by sync-tester** [comment]
> In this case it's because for Monero there is no wallet available. The nodes seem to be synched.

Thank you!  but then the Pop up should say something about the wallet, isn't it?

**Comment by dennisreimann** [comment]
It mentions the XMR wallet not being available, don't know why it is a requirement though. /cc @sethforprivacy @Kukks

**Comment by Kukks** [comment]
> It mentions the XMR wallet not being available, don't know why it is a requirement though. /cc @sethforprivacy @Kukks 

It's a singular wallet file that would be used for all wallets therefore it's added as if it is a sync requirement.

This is an altcoin related minor ux thing anyway. Closing.
