### ISSUE TITLE
[Bug]: Problems with login into BTCPay Server after updating Raspiblitz / Umbrel deployments

### ISSUE THREAD

**Issue by rockstardev** [btcpayserver/btcpayserver#5666]
Third-party deployments have updated to v1.12.3 and now some of them are not working. Moving conversations from Telegram - https://t.me/btcpayserver/68290

```
Tassilo, [1/16/2024 1:24 PM]
Hi!

After updating my Raspiblitz to v1.10.0 I can’t log in to my BTCPAY Server any more.
When I try to log in with my email and password I get a “invalid login attempt”

Did anyone else had the same problem and can help me please?

Riccardo | ARAN, [1/16/2024 1:44 PM]
Same same but with umbrel! I didn’t find any solution at the moment!
```

Also, it seems that Raspiblitz v.1.10.0 they have switched from MySql to Postgres database. There was migration included, needs to be checked if it worked as expected. https://github.com/raspiblitz/raspiblitz/blob/v1.10/CHANGES.md#whats-new-in-version-1100-of-raspiblitz

**Comment by 7gQdm9zxtSq** [comment]
I have had the same problem when I was switching from the raspiblitz v1.09.0 fatpack to the v1.09.0 minimal version. I could not log in to my BTCpay Server any more and had to install a new one.

**Comment by rockstardev** [comment]
I've logged the issue for Umbrel team at this link:
https://github.com/getumbrel/umbrel/issues/1734

**Comment by pavlenex** [comment]
This seems to be an issue with an old verison of the BTCPay Server. Since we don’t see any reaction from users, and since them migration is deprecated in 2.0, it seems that for now we’ll close it, and track if users complain.
