### ISSUE TITLE
Overview of the stores and apps in user list for administrators

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5674]
This issue is a portion of https://github.com/btcpayserver/btcpayserver/issues/396.

As we agreed on a dev call, to properly tackle #396 we need to tackle it step by step and ask for ambassador's (third-party hosts) feedback in each steps.

#396 summarizes 3 different use-cases

1.  Overview of the stores
2. Reporting aspect, how much users are earning
3. Managing of store, supporting users, removing malicious stuff and so on

The goal of this ticket is to tackle 1. and give admins better overview on who is using their Server. Currently, admins only have overview of users, but not on stores and public facing pages (such as apps) these users are using. 
As our overall goal to give admins more gradual control over who's using their server

The scope of this issue is to (upon @dstrukt mockup on the UI) is to add an expandable list of stores and apps for every user registered on the instance and also their role in a store.  We agreed that list shouldn't be extendable by default but rather admin can expand it on clicking.

**Out of scope**: add ability for admin to manage, preview stores and store report (2. and 3.)

**Blocker:** Waiting for @dstrukt to provide mockup before it can be tackled

**Comment by dstrukt** [comment]
Is there a typo in the title? `store's stores`? I'm guessing you meant to type `Server's stores and apps`?

**Comment by pavlenex** [comment]
Feedback from ambassador: 

>   We would like to see how many stores are associated to that user and the user’s role for every stores is associated.

**Comment by pavlenex** [comment]
@dstrukt Do we have mocks for these?

**Comment by dstrukt** [comment]
Yeah I posted in the UI/UX channel to discuss before dropping here, but will copy the context.

Still working in feedback and refining, but think we're getting close:

- mass actions
- filters
- last active
- current store balance (we might need to make that label explicitly clear)
- role (under account name - needed the space)
- number of stores

had to push things into the `...` (with the primary action being the exposed CTA), so Store Balance, and Last Active, and the longer potential Pending Email Verification Status on other lists, would onto the row, assuming we want all of this information

all feedback welcome (still looking to minify where possible, and experimenting with displaying some of the expanded data more compactly)

![Server Settings - Users](https://github.com/btcpayserver/btcpayserver/assets/6250771/80189698-33ad-4fb1-942c-dbf0505b5313)

![Server Settings - Users Expanded](https://github.com/btcpayserver/btcpayserver/assets/6250771/af247691-5b0b-4c76-88ff-10f4c907dce0)

Additional note, we might be able to get away with this (or add back Pending Approval only), to get even more space back after we merge the existing PR, but realize it's quite minimal compared to the current state:

<img width="448" alt="Screen Shot 2024-01-27 at 8 18 51 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/9d74d3b1-c5e4-44f3-9c51-85e1f58aab79">

**Comment by dennisreimann** [comment]
> mass actions

I think we need to define which actions we want to have here, because e.g. Approve or Disable could only be applied to unapproved or enabled (and vice versa) users. So not all selected rows might be able to get handled uniformly or we'd have to enable/disable mass actions based on the selection.

> filters 

Yes, role and status filters will be helpful as we are about to add some roles. This will allow for better overview for ambassador instances.

> last active

Right now we don't have that info, but we could add it if this is seen as helpful.

> current store balance (we might need to make that label explicitly clear)

Users might have multiple stores, so this could be per store in the details and an aggregate in the main row.

> had to push things into the ... (with the primary action being the exposed CTA)

The way I understand the screenshot would mean, that in some cases e.g. Disable is the "primary" action and hence shown, whereas in others (e.g. Pending Approval) it'd be Approve and hence Disable would be inside the `...`. I think that's kinda unfortunate and harder to understand.

I'd say in that case we should have only Resend and Approve immediately visible, everything else being part of the `...` actions menu. Disabling is most likely less used anyway, whereas Resend/Approve exclude each other and would be actions that are more likely to be used from the overview.

I like the status pills, nice to distinguish.

**Comment by dstrukt** [comment]
> I think we need to define which actions we want to have here, because e.g. Approve or Disable could only be applied to unapproved or enabled (and vice versa) users. So not all selected rows might be able to get handled uniformly or we'd have to enable/disable mass actions based on the selection.

Yes, this would be conditional, I just listed all of them in the mock for the sake of communication every mass action it *could* be, but great call out!

> Right now we don't have that info, but we could add it if this is seen as helpful.

Can always drop this if it's too much of a pain to retrieve. I'd imagine it'd be useful as an Admin to see how often/regularly a user is utilizing the instance.

> Users might have multiple stores, so this could be per store in the details and an aggregate in the main row.

Yes, I'll work this the individual store balances into the mock - good catch!

> The way I understand the screenshot would mean, that in some cases e.g. Disable is the "primary" action and hence shown, whereas in others (e.g. Pending Approval) it'd be Approve and hence Disable would be inside the `...`. I think that's kinda unfortunate and harder to understand.
> 
> I'd say in that case we should have only Resend and Approve immediately visible, everything else being part of the `...` actions menu. Disabling is most likely less used anyway, whereas Resend/Approve exclude each other and would be actions that are more likely to be used from the overview.

I imagined `Resend`, `Disable`, and `Enable` being the primary (outside of the `...`) and most immediate necessary action, but tend to agree with you that Disable is a little less likely, and *could* be hidden away - don't have a strong preference.

> I like the status pills, nice to distinguish.

Sweet! I'll work that into a proper issue so we can tackle this whenever we're ready.

Appreciate all of the feedback!

**Comment by dennisreimann** [comment]
Design PR for the new badge variation: btcpayserver/btcpayserver-design#64

**Comment by dennisreimann** [comment]
Not closed yet, will need a follow-up PR to #5745 once @Kukks has denoe the permission refactoring. 

Right now, admins can view the list of stores per user, but they won't be able to access foreign stores. This functionality was remove in f6878b5a6a668bd6012fa8104ed64144cfed50e8 and needs to be brought back for this issue to be closed.
