### ISSUE TITLE
[Bug]: Invoice Amounts of 0

### ISSUE THREAD

**Issue by some1ataplace** [btcpayserver/btcpayserver#5682]
### What is your BTCPay version?

© BTCPay Server v1.12.3+f23078df1 

### How did you deploy BTCPay Server?

I am using the latest https://testnet.demo.btcpayserver.org

### What happened?

When creating an invoice amount of 0 (after using a 100% off discount promo code on the initial price), I get redirected to the hilarious 404 page of:

404 - Page not found
This is like searching for a person more beautiful than Nicolas Dorier.
It doesn't exist.
You can always try navigating back to home (https://testnet.demo.btcpayserver.org/).

The webhook successfully executes though, and the user gets a free subscription which is what I want. However, I would like to have a different page besides the 404 page since it will not make sense to my users who are using a 100% off promo code to get a free subscription. I would like the new page you would have to make to have a button at least return back to my website's URL and have some sort of success message even though the invoice was for 0. 

### How did you encounter this bug?

Programmatically create an invoice of 0 and try to have the user pay for it as if was a normal payment. 

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Hi, how are you creating promo codes? cc @Kukks unsure if there's something wrong with the logics in discounts and 0 invoice.

**Comment by Kukks** [comment]
Is this a public form, pos o payment request that creates the invoice and form?

**Comment by some1ataplace** [comment]
I am using a django form I made on my site where the user could pass in a promo code before getting redirected to the btcpay invoice payment page. On the django form submission, I apply the percent off discount amount to the invoice amount so that when I get to redirected to the btcpay invoice payment page, the discount is already applied to the amount. 

I store the percent off variable from the promo code in a session variable from the form submission. I am actually using stripe's API of promo codes to store and lookup promo code data. I wish you guys had your own way of creating and handling promo codes, but at least this works for me for all payment types on my site (fiat and crypto) for now. 

I just realized that you have this:

https://docs.btcpayserver.org/Forms/#promo-codes

Which I might switch to, but I do not necessarily need this custom form field on every single btcpay invoice payment page. I am mainly using promo codes on the one product I sell, not all product types. 

Discussion topics:

https://github.com/btcpayserver/btcpayserver/discussions/5425
https://github.com/btcpayserver/btcpayserver/discussions/5288

Example django form:
Product type -> Monthly or Yearly subscription
Payment type -> Stripe or Btcpay
Promo Code -> free form varchar text input box

**Comment by some1ataplace** [comment]
@pavlenex Can I ask why this is not being planned? To me, it is bad UX having a customer pay for something (even if they have a 100% off discount) and then see an error message with Nicolas Dorier's picture right away, making them think they got scammed or something.
