### ISSUE TITLE
Delete & Disable users should be displayed in an overlay modal

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#5687]
Server Settings > Users

## Current

<img width="691" alt="Screen Shot 2024-01-22 at 6 09 19 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/ba261206-0dbf-42bd-86bd-c80f39222f2f">
<img width="951" alt="Screen Shot 2024-01-22 at 6 04 57 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/733f5c69-f050-4814-9327-0c0a50a15d4c">
<img width="903" alt="Screen Shot 2024-01-22 at 6 05 14 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/bdbaa966-c6e4-40f3-9cf3-12b444c9cbbf">

## Proposed

All of these states should be displayed in our standard overlay modal, not the opaque background in the current view.

**Comment by dennisreimann** [comment]
We omitted this, because there are some more checks involved on the backend, like verifying this is not the last admin. I can take another look, but it was a concious decision to have it like this, not an oversight.

**Comment by dstrukt** [comment]
Ahh apologies if it was conscious decision, enough time has passed for me to forget!

If it's not feasible, feel free to close.

**Comment by pavlenex** [comment]
@dennisreimann so we should close it because it's not feasible?

**Comment by dennisreimann** [comment]
Yes, let's keep it as it is.
