### ISSUE TITLE
[Bug]:  v1.12.4-RC Importing a wallet file from Wasabi defaults to legacy wallet 

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5691]
### What is your BTCPay version?

 v1.12.4 RC

### How did you deploy BTCPay Server?

https://mainnet.demo.btcpayserver.org

### What happened?

Importing a wallet file from Wasabi defaults to legacy, even though the wallet is SegWit native.

### How did you encounter this bug?

1. Create a brand new wallet in Wasabi
2. Import a wallet file in BTCPay
3. Check addresses that are legacy

### What browser do you use?

RC IMPORT 

https://github.com/btcpayserver/btcpayserver/assets/36959754/8a4a72c8-8ede-4f8d-aab8-0181883ef1b9

NON RC IMPORT
![Screenshot 2024-01-23 at 12 46 36](https://github.com/btcpayserver/btcpayserver/assets/36959754/92e3daa5-815f-4348-b3d2-1772b7245a83)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by ndeet** [comment]
Can confirm, same with my RC2 install.
