### ISSUE TITLE
Confirm Addresses view should have a back button

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#5693]
Originally reported by @pavlenex, and will most likely be picked up by @dennisreimann, but creating an Issue to track.

## Current 
![___Screenshot 2024-01-23 at 12 46 36](https://github.com/btcpayserver/btcpayserver/assets/6250771/dd7a63b7-4b4a-4c7f-90fc-b40a8ad77bdb)

## Proposed
We should use our standard back button in the top left of the full page view.

**Comment by dennisreimann** [comment]
Hmm, for me it is there and the [view code also has it without conditions](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Views/UIStores/ImportWallet/ConfirmAddresses.cshtml#L9). Can both of you check why it might be missing? Tried with both themes, it's also visible with the light theme for me.

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/5a4edbc8-7a68-4987-b9a8-e0ce2d065f19)

**Comment by pavlenex** [comment]
@dennisreimann you're right, I guess screen size was too wide.

Unsure if we can do something to tighten it up a bit?
![Screenshot 2024-01-24 at 11 24 02](https://github.com/btcpayserver/btcpayserver/assets/36959754/cac39874-6c9c-461e-8b6c-b4c4fe68aa4f)
