### ISSUE TITLE
Feature Request: Add option to whitelist IPs for login

### ISSUE THREAD

**Issue by djmelik** [btcpayserver/btcpayserver#57]
Hi,

I would like to make a feature request. Can we implement a security feature to allow us to whitelist IPs (individual or subnets) for logging in via the web interface. I don't know how hard it would be to implement this, but thank you for your consideration. Please let me know if you'd like additional information. 

Best,
Melik

**Comment by NicolasDorier** [comment]
yep, should not be that hard.

**Comment by pavlenex** [comment]
Ok, while we don't have a way to whitelist certain IP, we do have you can use 2fa or u2f to secure the login page. We also have rate limiting and account login cooldowns so you cant bruteforce.

So I'll go ahead and close this one, but if you really want to whitelabel a single IP and want to tackle the issue, let me know and we'll re-open it.
