### ISSUE TITLE
Ledger Accounts hidden and difficult to choose using dropdown

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#570]
Accounts 0 and 1 are hidden under the header when I use the Ledger account dropdown. Is there a way to implement a scroll on this list? 

I can only choose Account 0 if I choose an incorrect account and cancel it on my Ledger, scroll the page and then they are displayed differently.. but if I scroll the page up it hides them above again. 

![image](https://user-images.githubusercontent.com/39231115/51879435-a0853e80-2330-11e9-821d-3c779a379606.png)

**Comment by NicolasDorier** [comment]
@Kukks

**Comment by NicolasDorier** [comment]
.50 released, it put the list to 5.

**Comment by Kukks** [comment]
I did a booboo, incoming fix
