### ISSUE TITLE
Adjust precision and remove decimals for Colombian `COP` and Argentina's Peso `ARS`

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5708]
Feedback from telegram:

> Is there a way to not show decimal places (cents) in a PoS when creating an invoice?

> cents disappeared from our national shitcoin (aka colombian peso) a long time ago... and it will disappear from yours eventually lol

![photo_2024-01-26_14-03-33](https://github.com/btcpayserver/btcpayserver/assets/36959754/1916b384-495b-4db5-983a-c2f0f4dcd9bb)

**Comment by pavlenex** [comment]
@TChukwuleta This may be something good to tackle if you're up for it.

**Comment by Kehinde13** [comment]
Hello, I would like to work on this 
Here's my email balogunkehinde3@gmail.com

**Comment by TChukwuleta** [comment]
Hey @Kehinde13 

If you are up for this, sure. Take a go at it

**Comment by manasadepu** [comment]
Is this still available?

**Comment by TChukwuleta** [comment]
Not anymore @manasadepu 

You can go through the issues and see if you would find anyone that you can tackle
