### ISSUE TITLE
Improve Crowdfund invoice error message

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#572]
This unknown error happens when the user doesn't have a derivation scheme for their store connected to their crowdfund. 

Is it possible to update 'Unknown Error' to explain this?

![image](https://user-images.githubusercontent.com/39231115/51887248-3a101880-2350-11e9-84c5-bf1006d14a8c.png)

**Comment by pavlenex** [comment]
Nice catch, we should probably add the same error as [here](https://github.com/btcpayserver/btcpayserver/commit/575b6ca2226bcc8966440b8b47f66e0ac0f50fd8).
