### ISSUE TITLE
Amount column on dashboard goes out of the layout on mobile

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5721]
Good first issue for anyone to tackle. Image speaks for itself. ![image](https://github.com/btcpayserver/btcpayserver/assets/36959754/026180bf-4231-4c89-9608-1f1a2e81ea4f)

Replicated on iPhone 13, Safari.

**Comment by dennisreimann** [comment]
This calls for another approach for handling tables. I've tried to do a grid-based version that would work on mobile as well, but never succeeded to make it universal enough. We have this problem on almost every table view.

From my experience this would needs some custom CSS grid classes that do 70% of the general work and then one would need to tackle the remaining 30% on a per table basis. The invoices table is the most tricky one, I couldn't get it to work yet.

**Comment by Jem256** [comment]
Hello @dennisreimann @pavlenex I'd like to handle this issue if it's available.
