### ISSUE TITLE
Unusual positioning of the filter and clear filter button UI for wallet  labels

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5722]
On mobile the positioning of the labels looks awkward mostly due to the clear button and filter who take majority of the screen.
This issue shouldn't be tackled until discussion happens on design meeting and mockup is posted.

![image](https://github.com/btcpayserver/btcpayserver/assets/36959754/05145e73-384d-415d-85cd-6316c7fc7dcb)

**Comment by dstrukt** [comment]
Following up on this as it may have slipped between the cracks on a call, did we decide on a resolution? Maybe I'm hallucinating, but IIRC we opted to turn this into a horizontal scrollable table-like view? cc @dennisreimann

**Comment by dennisreimann** [comment]
Nope, we didn't, but I could imagine a dropdown solution. Imho this would work better than something horizontally scrollable.

**Comment by dstrukt** [comment]
ACK to dropdown or accordion, agree it would look better - could have sworn we discussed that particular solution, but guess not!
