### ISSUE TITLE
User role labels on mobile look squashed

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5726]
![image](https://github.com/btcpayserver/btcpayserver/assets/36959754/3a5db78e-78e8-4082-b9f4-8fe929aa0c6e)

**Comment by dennisreimann** [comment]
Done in that PR.

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/0f5dc15f-1886-4c6a-9084-afee289afaaf)

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/a6abf277-8818-4211-ac08-eef7c3237b23)
