### ISSUE TITLE
BTCPay Server 1.3.5 running btcpay-update fails with error "The fragments bitcoin-clightning, bitcoin-lnd can't be used simultaneously (group 'lightning') Failed to generate the docker-compose"

### ISSUE THREAD

**Issue by clarketowson** [btcpayserver/btcpayserver#5727]
Hi Everyone,

I thought I would post this here as I think it's more of an issue than a discussion.  It may also affect others that are upgrading from an older release of BTCPay.  I did my best to try to figure out what was going on under the hood but i'm unsure of exactly how to proceed.

I have a lot of payment channels open with other nodes and I really need the upgrade process to go smoothly.  

Any tips and advice would be very much appreciated as always.

Kind Regards,

Clarke

--

### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/5725

<div type='discussions-op-text'>

<sup>Originally posted by **clarketowson** February  5, 2024</sup>
Hi Everyone,

I'm trying to update my BTCPay Server from version 1.3.5 to the latest using the btcpay-update.sh script.

I'm receiving this error message: "The fragments bitcoin-clightning, bitcoin-lnd can't be used simultaneously (group 'lightning')
Failed to generate the docker-compose"

Here is the full output after running the btcpay-update command:

[root@ulysses btcpayserver-docker]# ./btcpay-update.sh
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

remote: Enumerating objects: 2163, done.
remote: Counting objects: 100% (1817/1817), done.
remote: Compressing objects: 100% (307/307), done.
remote: Total 2163 (delta 1590), reused 1698 (delta 1510), pack-reused 346
Receiving objects: 100% (2163/2163), 900.81 KiB | 13.25 MiB/s, done.
Resolving deltas: 100% (1686/1686), completed with 55 local objects.
From https://github.com/btcpayserver/btcpayserver-docker
   07519d8..df71ca2  master                -> origin/master
 + 910c240...c068f89 Kukks-patch-2         -> origin/Kukks-patch-2  (forced update)
 + e151b42...a35ec66 dcg-latest            -> origin/dcg-latest  (forced update)
 * [new branch]      feat/lnd-v0.17.0-beta -> origin/feat/lnd-v0.17.0-beta
 * [new branch]      joinmarket-0.9.10     -> origin/joinmarket-0.9.10
 * [new branch]      revert-674-fastsync   -> origin/revert-674-fastsync
 * [new branch]      revert-675-master     -> origin/revert-675-master
   332194e..eb7a414  split-cl              -> origin/split-cl
Updating 07519d8..df71ca2
Fast-forward
 .circleci/config.yml                                                     |  79 +++-------------------
 Production/README.md                                                     |   1 +
 Production/nginx.tmpl                                                    |  76 ++++++++++++++++-----
 README.md                                                                | 116 +++++++++++++++++++-------------
 Traefik/README.md                                                        |   2 +-
 btcpay-admin.sh                                                          |   2 +-
 btcpay-backup.sh                                                         |  77 +++++++++++++++------
 btcpay-restore.sh                                                        |  71 ++++++++++++++++----
 btcpay-setup.sh                                                          |  13 +---
 btcpay-teardown.sh                                                       |  51 ++++++++++++++
 btcpay-update.sh                                                         |   5 +-
 contrib/DockerFileBuildHelper/Program.cs                                 | 130 +++++++++++++++++++++++------------
 contrib/FastSync/README.md                                               | 184 ++++++++++++++++++++++++++++++++++----------------
 contrib/FastSync/load-utxo-set.sh                                        |  10 +--
 contrib/FastSync/sigs/JUnderwood.utxo-sets.asc                           |  17 ++---
 contrib/FastSync/sigs/NicolasDorier.utxo-sets.asc                        |  29 ++++----
 contrib/FastSync/sigs/baspeters.utxo-sets.asc                            |  21 ++++++
 contrib/FastSync/sigs/bitkarrot.utxo-sets.asc                            |  20 ++++++
 contrib/FastSync/sigs/brittkelly.utxo-sets.asc                           |  27 ++++----
 contrib/FastSync/sigs/kiwi_.utxo-sets.asc                                |  20 ++++++
 contrib/FastSync/sigs/petzsch.utxo-sets.asc                              |  21 ++++++
 contrib/FastSync/sigs/rexh.utxo-sets.asc                                 |  20 ++++++
 contrib/FastSync/sigs/sbrooks24.utxo-sets.asc                            |  20 ++++++
 contrib/FastSync/utxo-sets                                               |   5 +-
 contrib/build-all-images.sh                                              | 726 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------------------------------------------------------------------------
 docker-compose-generator/{linuxamd64.Dockerfile => Dockerfile}           |   4 +-
 docker-compose-generator/crypto-definitions.json                         |  11 +--
 docker-compose-generator/docker-fragments/bitcoin-clightning.yml         |  61 ++++++-----------
 docker-compose-generator/docker-fragments/bitcoin-eclair.yml             |   4 +-
 docker-compose-generator/docker-fragments/bitcoin-lnd.yml                |  24 ++++++-
 docker-compose-generator/docker-fragments/bitcoin.yml                    |   7 +-
 docker-compose-generator/docker-fragments/btcpayserver.yml               |   7 +-
 docker-compose-generator/docker-fragments/dash.yml                       |   2 +-
 docker-compose-generator/docker-fragments/dogecoin.yml                   |   2 +-
 docker-compose-generator/docker-fragments/groestlcoin-clightning.yml     |   2 +-
 docker-compose-generator/docker-fragments/groestlcoin.yml                |   2 +-
 docker-compose-generator/docker-fragments/liquid.yml                     |   9 ++-
 docker-compose-generator/docker-fragments/litecoin-clightning.yml        |  34 ----------
 docker-compose-generator/docker-fragments/litecoin-lnd.yml               |  52 --------------
 docker-compose-generator/docker-fragments/litecoin.yml                   |   5 +-
 docker-compose-generator/docker-fragments/monero.yml                     |   6 +-
 docker-compose-generator/docker-fragments/nbxplorer.yml                  |   4 +-
 docker-compose-generator/docker-fragments/nginx-https.yml                |   6 +-
 docker-compose-generator/docker-fragments/nginx.yml                      |   4 +-
 docker-compose-generator/docker-fragments/opt-add-bluewallet-lndhub.yml  |  10 +--
 docker-compose-generator/docker-fragments/opt-add-btctransmuter.yml      |   3 +
 docker-compose-generator/docker-fragments/opt-add-cloudflared.yml        |   4 +-
 docker-compose-generator/docker-fragments/opt-add-electrumx.yml          |   5 +-
 docker-compose-generator/docker-fragments/opt-add-fireflyiii.yml         |   1 +
 docker-compose-generator/docker-fragments/opt-add-lightning-terminal.yml |   8 ++-
 docker-compose-generator/docker-fragments/opt-add-mempool.yml            |  69 +++++++++++++++++++
 docker-compose-generator/docker-fragments/opt-add-nostr-relay.yml        |   7 +-
 docker-compose-generator/docker-fragments/opt-add-pihole.yml             |   2 +-
 docker-compose-generator/docker-fragments/opt-add-sphinxrelay.yml        |   2 +-
 docker-compose-generator/docker-fragments/opt-add-tallycoin-connect.yml  |   3 +-
 docker-compose-generator/docker-fragments/opt-add-thunderhub.yml         |   6 +-
 docker-compose-generator/docker-fragments/opt-add-tor-relay.yml          |   5 +-
 docker-compose-generator/docker-fragments/opt-add-tor.yml                |   4 +-
 docker-compose-generator/docker-fragments/opt-add-torq.yml               |  46 +++++++++++++
 docker-compose-generator/docker-fragments/opt-add-woocommerce.yml        |   5 +-
 docker-compose-generator/docker-fragments/opt-lnd-autocompact.yml        |   7 ++
 docker-compose-generator/docker-fragments/opt-lnd-watchtower.yml         |  11 +++
 docker-compose-generator/docker-fragments/opt-mempoolfullrbf.yml         |   8 +++
 docker-compose-generator/docker-fragments/opt-txindex.yml                |   3 +
 docker-compose-generator/docker-fragments/postgres.yml                   |   4 +-
 docker-compose-generator/docker-fragments/traefik.yml                    |  17 -----
 docker-compose-generator/linuxarm32v7.Dockerfile                         |  23 -------
 docker-compose-generator/linuxarm64v8.Dockerfile                         |  23 -------
 docker-compose-generator/src/DockerComposeDefinition.cs                  |   2 +-
 docker-compose-generator/src/docker-compose-generator.csproj             |   6 +-
 docs/backup-restore.md                                                   |   8 ++-
 docs/img/fastsync/btcpayfastsync1.jpg                                    | Bin 0 -> 78593 bytes
 docs/img/fastsync/btcpayfastsync2.jpg                                    | Bin 0 -> 78707 bytes
 docs/img/fastsync/btcpayfastsync3.jpg                                    | Bin 0 -> 157722 bytes
 docs/img/fastsync/btcpayfastsync4.jpg                                    | Bin 0 -> 96068 bytes
 docs/img/fastsync/btcpayfastsync5.jpg                                    | Bin 0 -> 13143 bytes
 docs/img/fastsync/btcpayfastsync6.jpg                                    | Bin 0 -> 68728 bytes
 docs/lightning-terminal.md                                               |   2 +-
 helpers.sh                                                               | 131 ++++++++++++++++++++++++++++++++----
 79 files changed, 1474 insertions(+), 940 deletions(-)
 create mode 100755 btcpay-teardown.sh
 create mode 100644 contrib/FastSync/sigs/baspeters.utxo-sets.asc
 create mode 100644 contrib/FastSync/sigs/bitkarrot.utxo-sets.asc
 create mode 100644 contrib/FastSync/sigs/kiwi_.utxo-sets.asc
 create mode 100644 contrib/FastSync/sigs/petzsch.utxo-sets.asc
 create mode 100644 contrib/FastSync/sigs/rexh.utxo-sets.asc
 create mode 100644 contrib/FastSync/sigs/sbrooks24.utxo-sets.asc
 rename docker-compose-generator/{linuxamd64.Dockerfile => Dockerfile} (74%)
 delete mode 100644 docker-compose-generator/docker-fragments/litecoin-clightning.yml
 delete mode 100644 docker-compose-generator/docker-fragments/litecoin-lnd.yml
 create mode 100644 docker-compose-generator/docker-fragments/opt-add-mempool.yml
 create mode 100644 docker-compose-generator/docker-fragments/opt-add-torq.yml
 create mode 100644 docker-compose-generator/docker-fragments/opt-lnd-autocompact.yml
 create mode 100644 docker-compose-generator/docker-fragments/opt-lnd-watchtower.yml
 create mode 100644 docker-compose-generator/docker-fragments/opt-mempoolfullrbf.yml
 delete mode 100644 docker-compose-generator/linuxarm32v7.Dockerfile
 delete mode 100644 docker-compose-generator/linuxarm64v8.Dockerfile
 create mode 100644 docs/img/fastsync/btcpayfastsync1.jpg
 create mode 100644 docs/img/fastsync/btcpayfastsync2.jpg
 create mode 100644 docs/img/fastsync/btcpayfastsync3.jpg
 create mode 100644 docs/img/fastsync/btcpayfastsync4.jpg
 create mode 100644 docs/img/fastsync/btcpayfastsync5.jpg
 create mode 100644 docs/img/fastsync/btcpayfastsync6.jpg
Trying to install docker-compose by using docker/compose-bin (x86_64)
Unable to find image 'docker/compose-bin:v2.23.3' locally
v2.23.3: Pulling from docker/compose-bin
8f4a2c4a4400: Pull complete
Digest: sha256:3ef9f4997af9858b9ec57414b770ec3f72426e41d5a85662f11ff2eab6d1fca5
Status: Downloaded newer image for docker/compose-bin:v2.23.3
Successfully copied 59.7MB to /root/BTCPayServer/btcpayserver-docker/dist/docker-compose
6795983eb0501bb074d34b721bcf82aae5d4f67ec6f37482db0a2b247c7f1ead
set 'docker compose' to /usr/local/bin/docker-compose
Using default tag: latest
latest: Pulling from btcpayserver/docker-compose-generator
2f44b7a888fa: Pull complete
9615f6c2b3e3: Pull complete
0c33680d7216: Pull complete
5f37777da376: Pull complete
8d53130e324d: Pull complete
074da642b678: Pull complete
56a5a362f649: Pull complete
1e220b1495e7: Pull complete
Digest: sha256:9100544323b6ead72d6337e668052307fafe522e54f3d056926c679a8589a514
Status: Downloaded newer image for btcpayserver/docker-compose-generator:latest
docker.io/btcpayserver/docker-compose-generator:latest
Crypto: btc
Lightning: clightning
ReverseProxy: nginx
Generating /app/Generated/docker-compose.generated.yml
The fragments bitcoin-clightning, bitcoin-lnd can't be used simultaneously (group 'lightning')
Failed to generate the docker-compose

Please let me know if you have any ideas on what I should do to complete the update.

Best Regards,

Clarke

Clarke Towson, BCMS (Bachelor of Computer & Mathematical Science)
CEO
INTJ Billing
 
m: +61 432 359 166
a: 7 Cullen Court Spotswood Victoria 3015 AUSTRALIA
w: https://intjbilling.com/
e: [clarketowson@intjbilling.com](mailto:clarketowson@intjbilling.com)

Bitcoin Lightning Network Node Name: CHILLYCALENDAR 
Node Public Key: 025124c73ef7ecf527e0114ead02a0cc6e3ecbc0c99474ee3f5506c4503b089693 
Status Page: https://intjbilling.com/INTJBillingStatusPage.php 

amboss.space: https://amboss.space/node/025124c73ef7ecf527e0114ead02a0cc6e3ecbc0c99474ee3f5506c4503b089693 
1ml.com: https://1ml.com/node/025124c73ef7ecf527e0114ead02a0cc6e3ecbc0c99474ee3f5506c4503b089693
Lightning network+: https://lightningnetwork.plus/nodes/025124c73ef7ecf527e0114ead02a0cc6e3ecbc0c99474ee3f5506c4503b089693
</div>

**Comment by clarketowson** [comment]
Hi dennisreimann,

Yes I think so too.  I'm just unsure of why this is happening and exactly what config file I need to change so the upgrade works.  As far as I can tell after looking through various files on each of my BTCPay Servers everything is correct.  I was able to upgrade my two other BTCPay Servers fine the last couple of days.  They were however running much newer versions of BTCPay.

The output of those commands is:

[root@ulysses ~]# echo $BTCPAYGEN_LIGHTNING
clightning
[root@ulysses ~]# echo $BTCPAYGEN_ADDITIONAL_FRAGMENTS
opt-save-storage;opt-add-thunderhub

I have two other BTCPay Servers running the latest version of BTCPay and the output from those servers is:

[root@redadmiral scripts]# echo $BTCPAYGEN_LIGHTNING
clightning
[root@redadmiral scripts]# echo $BTCPAYGEN_ADDITIONAL_FRAGMENTS
opt-save-storage-s

[root@rhetus dailyreports]# echo $BTCPAYGEN_LIGHTNING
clightning
[root@rhetus dailyreports]# echo $BTCPAYGEN_ADDITIONAL_FRAGMENTS
opt-save-storage-s

Best Regards,

Clarke

**Comment by clarketowson** [comment]
I set up the first server ulysses back in March of 2021.  At the time I was new to BTCPay Server.  You can see that opt-add-thunderhub is present and I must have set that environment variable when first setting up the server.  The server uses c-lightning though and I use RTL on it and not LND.

Might the presence of the opt-add-thunderhub fragment be causing the update to fail and cause the error message -

"The fragments bitcoin-clightning, bitcoin-lnd can't be used simultaneously (group 'lightning')
Failed to generate the docker-compose"

**Comment by clarketowson** [comment]
I was thinking perhaps I should try this (but i'm not sure):

export BTCPAYGEN_ADDITIONAL_FRAGMENTS=opt-save-storage-s
./btcpay-update.sh

thus unsetting opt-add-thunderhub and having the update script run without opt-add-thunderhub.  Thinking that perhaps the btcpay-update.sh script will then not consider the fragments bitcoin-clightning and bitcoin-lnd are being simultaneously.

Thoughts?

**Comment by dennisreimann** [comment]
The [Thunderhub fragment has the dependency on LND](https://github.com/btcpayserver/btcpayserver-docker/blob/master/docker-compose-generator/docker-fragments/opt-add-thunderhub.yml#L35), so if you do what you proposed you should be able to run the update:

```bash
export BTCPAYGEN_ADDITIONAL_FRAGMENTS=opt-save-storage-s
./btcpay-update.sh
```

**Comment by dennisreimann** [comment]
Did this work for you, @clarketowson?

**Comment by clarketowson** [comment]
Hi dennisreimann,

Thank you for your advice on this very much appreciated.

I ran into some further issues this morning attempting the upgrade.  Three of the docker processes had a - instead of an _ 

such as:

generated-btcpayserver-1 
instead of: generated_btcpayserver_1

generated-postgres-1 
instead of: generated_postgres_1

generated-nbxplorer-1 
instead of: generated_nbxplorer_1

I do not know how or why this happened.  This caused another issue in the backup script throwing errors because it expected: generated_postgres_1 and not generated-postgres-1 so I couldn't complete either a partial nor a full backup.

example:

[root@ulysses btcpayserver-docker]# ./backup.sh --only-db
No BACKUP_PROVIDER set. Backing up to local directory.
Dumping database …
Error response from daemon: No such container: pg_dumpall
tar: Removing leading `/' from member names
/var/lib/docker/volumes/backup_datadir/_data/postgres.sql.gz
Backed up to /var/lib/docker/volumes/backup_datadir/_data/backup.tar.gz
Backup done.

In helpers.sh you can see the cause (bolded):

btcpay_dump_db() {
    pushd . > /dev/null
    cd "$(dirname "$BTCPAY_ENV_FILE")"
    local file_path=${1:-"postgres-$(date "+%Y%m%d-%H%M%S").sql.gz"}
    docker exec $(docker ps -a -q -f "name=**postgres_1**") pg_dumpall -c -U postgres | gzip > "$file_path"
    popd > /dev/null
}

So I did this:

docker rename generated-btcpayserver-1 generated_btcpayserver_1
docker rename generated-postgres-1 generated_postgres_1
docker rename generated-nbxplorer-1 generated_nbxplorer_1

This resolved that issue.

Tomorrow morning I will perform another full backup of the BTCPay Server using the backup.sh script and then I will attempt as suggested:

export BTCPAYGEN_ADDITIONAL_FRAGMENTS=opt-save-storage-s
. ./btcpay-setup -i
./btcpay-update.sh

and I will provide an update as to whether it worked or not.

Best Regards,

Clarke

**Comment by dennisreimann** [comment]
Consider using the `btcpay-backup.sh` and `btcpay-restore.sh` scripts, as they are more versatile. Also see the [Backup & Restore docs](https://docs.btcpayserver.org/Docker/backup-restore/).

**Comment by clarketowson** [comment]
Yes I did originally try the btcpay-backup.sh script a while ago but for some odd reason it tried backing up the blocks and I had to stop it from running.  I'm not sure why it did that either as the script looked fine and did have the exclude set on the blocks directory.

I'm hoping that once I get the server upgraded it will resolve several of the issues i'm facing.

The server became a bit of an unexpected success.  I have a lot of payment channels open due to joining the lightningnetwork+ website.  My routing and forwarding logs are about 5GB in size and several of the bitcoin-lightning.sh commands just sit there now and hang up BTCPay and the docker processes then restart.  It's become a bit unusable.

I built 2 additional BTCPay Servers one as a secondary production and the other as a test/dev box.  I'm change managing each of them very carefully now.

I would have upgraded the primary production server a lot earlier but I was in Thailand introducing BTCPay Server to people working in the entertainment districts in Pattaya (you can see my work on this on YouTube) and then when I got back to Melbourne I spent 9 months re-stumping my families house which seriously distracted me.

Going forward I will keep each of the servers as up to date as possible.

With Best Regards,

Clarke

**Comment by clarketowson** [comment]
Hi @dennisreimann,

A big thanks for your advice on all this.  I managed to upgrade the server this morning to the latest version of BTCPay by following your advice.

I did a full backup using the backup.sh script which was successful.  I double checked all my existing environment variables were correct and then I did:

export BTCPAYGEN_ADDITIONAL_FRAGMENTS=opt-save-storage-s
. ./btcpay-setup -i

and the server upgraded successfully!

The setup script did take 807 seconds to pull postgres.  I'm assuming this is due to the large 5GB approx size of my postgres database given all the routing and forwarding my node has been doing since early 2021.

I didn't need to run /btcpay-update.sh it turns out.  I did a docker ps and I see all the docker containers contain the latest versions.  I can login to the UI and all is working as expected!

Very Best Regards,

Clarke

**Comment by dennisreimann** [comment]
Great, glad to hear this. So we can close the issue now?

**Comment by clarketowson** [comment]
Yes please close this issue.

I will be opening additional issues with RTL and c-lightning over on their githubs.

I have noticed since the upgrade I'm not able to send out funds either on chain or via lightning and I just had the server run out of RAM whilst attempting these tasks via RTL.  

I highly suspect it's due to the very large amount of routing and forwarding logs my server has generated since 2021 and c-lightning not being able to handle them.  I will seek advice for this.

Best Regards,

Clarke
