### ISSUE TITLE
[Bug]: Unable to place "mailto" hyperlink into store description

### ISSUE THREAD

**Issue by Liongrass** [btcpayserver/btcpayserver#5728]
### What is your BTCPay version?

I'm running BTCPay Server v1.12.5+a86165ac0 

### How did you deploy BTCPay Server?

Lunanode

### What happened?

I'm editing the description of a web store. I am using the editor to insert a hyperlink `mailto:email@email.com`. I save the edits and view the store, but I can't click on or see the hyperlink I created.
In the source, I can see: `please send an \u003ca href=\u0022mailto:email@email.com\u0022\u003eemail\u003c/a\u003e by clicking here`
I placed a hyperlink to `https://btcpay.containerbrewing.ca` somewhere else in the text, and it shows up properly. In the source I can see:
`checkout in order to <a href="[https://btcpay.containerbrewing.ca/](view-source:https://btcpay.containerbrewing.ca/)" target="_blank">notify</a> you`

### How did you encounter this bug?

Edit web store description and enter `mailto:email@email.com` hyperlink.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Just to check: By store you mean a POS and its description, right?
