### ISSUE TITLE
App Name in POS should be the display title

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5757]
There's no reason to have this duplication. 
App name should be a display name, whoever doesn't like it can change it.
People deploying btcpay stores  at scale are reporting they:
a) either accidentally leave tea shop in POS
b) always have to rename it

Approach, there's no reason to have both, App Name should be what is displayed in Display Title, let's remove redundancy and unify this view.
<img width="1012" alt="Screenshot 2024-02-16 at 12 40 46" src="https://github.com/btcpayserver/btcpayserver/assets/36959754/07ebed48-784b-4fcd-b9cc-07d995e4d0f8">

**Comment by dennisreimann** [comment]
We need to keep it if set though to maintain backwards compatibility. I suggest we do it the same as with deprecating the custom CSS options (#5735):

- Display the field if the value is set already, hide it otherwise, ensuring it won't get set
- In the view use `DisplayTitle` if set, falling back to `AppName`
- Remove the `required` attribute for that property

**Comment by pavlenex** [comment]
I don't think we need compatibility here, I would just display the app name on the POS.

**Comment by dennisreimann** [comment]
Ok, but that might be a "(UI) breaking change" for existing apps then. Most users will likely have chosen the same name, but I thought it would be worth to not change it for those who didn't.

**Comment by pavlenex** [comment]
I think it's just text, no need to be worried about it, App Name is Display name on POS, worst case they can change the text back.

**Comment by Unicorntracry** [comment]
![Screenshot_20240306-190359](https://github.com/btcpayserver/btcpayserver/assets/162515815/6ca8bc20-ac39-4ce7-8095-c8f00221d232)
![Screenshot_20240306-143917](https://github.com/btcpayserver/btcpayserver/assets/162515815/28b907a7-b96f-4de3-b150-1071fd029c34)
![Screenshot_20240304-163728](https://github.com/btcpayserver/btcpayserver/assets/162515815/2311e0f3-155e-4ac4-b5fa-9c3506d4f739)
