### ISSUE TITLE
Reposition the camera scan icon is the wallet > send

### ISSUE THREAD

**Issue by Transisto** [btcpayserver/btcpayserver#5784]
https://github.com/btcpayserver/btcpayserver/discussions/5366

This is low hanging fruit that would make using the wallet much better on mobile

![271641565-5ea6596e-0947-416f-b114-74d1c7a93b96](https://github.com/btcpayserver/btcpayserver/assets/36959754/5ba074c8-29b9-4cfa-8b84-1b8cc0a9b7fa)

**Comment by pavlenex** [comment]
I think this is a good suggestion. 

@TChukwuleta feel free to tackle it if you wish!

cc @dstrukt i don't see any better way to achieve this than what @Transisto proposed, if you do, let us know.

**Comment by TChukwuleta** [comment]
Sure @pavlenex

**Comment by dstrukt** [comment]
Agree with @Transisto's original proposal, and agree @pavlenex we should use the QR code icon instead of the camera icon, which should already be in the icon set, if not @TChukwuleta feel free to reach out and I'll get you what you need!
