### ISSUE TITLE
[Bug]: doge, Greenfield.Basic was forbidden, Insufficient API Permissions

### ISSUE THREAD

**Issue by hell0-w** [btcpayserver/btcpayserver#5785]
### What is your BTCPay version?

© BTCPay Server v1.12.5+a86165ac0 (Altcoins)

### How did you deploy BTCPay Server?

docker

### What happened?

After several days of updating to the latest version, my server showed me this error, and became nonstable, 1 time a day sync problem with doge node, need to restart containers to fix it. 

```
doge.master.somehost.io 2.2.246.1 - - [24/Feb/2024:04:42:09 +0000] "POST /api/v1/stores/DtVXB9YEPX9vKEPDSA6u98QtWwdUGDDSARpnyN7KFKAA/invoices HTTP/2.0" 403 261 "-" "-"
info: BTCPayServer.Security.Greenfield.BasicAuthenticationHandler: AuthenticationScheme: Greenfield.Basic was forbidden.
info: BTCPayServer.Security.Greenfield.APIKeysAuthenticationHandler: AuthenticationScheme: Greenfield.APIKeys was forbidden.


from request:
Answer:HTTP/1.1 400 Bad Request  {"status":"error","message":"Error during POST to https:\/\/doge.master.somehost.io\/api\/v1\/stores\/DtVXB9YEPX9vKEPDSA6u98QtWwdUGDDSARpnyN7KFKAA\/invoices. Got response (403): {\"missingPermission\":\"btcpay.store.cancreateinvoice\",\"code\":\"missing-permission\",\"message\":\"Insufficient API Permissions. Please use an API key with permission \\\"btcpay.store.cancreateinvoice\\\". You can create an API key in your account's settings \/ Api Keys.\"}","data":null,"timestamp":1708753474}
```

### How did you encounter this bug?

check docker logs nginx and btcpayserver

### What browser do you use?

FF chrome

### Additional information

Several times restarted the server and all containers worked well, for a short period it helped me,
Now when I see 403 I create even a new API with all permissions, and the error same. 
Need help to debug and fix, thanks.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
We don't provide doge support here, you should join our mattermost chat and try to find community that maintains it in support-altcoin channel.

**Comment by vitorlimadev** [comment]
@pavlenex I'm having the exact same problem (same error, same permission "btcpay.store.cancreateinvoice", same 403). I don't use Doge or any other altcoins on my server, just plain BTC and Lightning. I believe this is specific to the authorization modules.

We should probably re-open this issue.
