### ISSUE TITLE
[Bug] Lightning experimental text removal removed heading

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5795]
In https://github.com/btcpayserver/btcpayserver/pull/5610 @NicolasDorier removed lightning experimental text, and I prematurely merged it without testing, which ended up in a page looking like this. 
<img width="907" alt="Screenshot 2024-02-28 at 18 09 47" src="https://github.com/btcpayserver/btcpayserver/assets/36959754/356efd2b-f97c-48f7-8247-4f3a5421624d">

Looks pretty empty, no head title even `Connect to a Lightning node` which was there, so let's bring it back.

@dstrukt let us know if you have any other suggestions for improving this one. We could do it in a separate issue but looking at this page could be right time to unify how we approach it in wallet setup as well instead of this awkward pill.

<img width="814" alt="Screenshot 2024-02-28 at 18 16 38" src="https://github.com/btcpayserver/btcpayserver/assets/36959754/37621fbc-0d58-47f2-b17f-723cdcaf3898">

**Comment by cpwallah** [comment]
hi @dennisreimann  i can do this

**Comment by pavlenex** [comment]
it's tackled already in #https://github.com/btcpayserver/btcpayserver/pull/5796 @cpwallah, but feel free to help review if you want.
