### ISSUE TITLE
Adding DPOS Coins to BTCPAY

### ISSUE THREAD

**Issue by mody199610** [btcpayserver/btcpayserver#58]
Hi Nicolas,

I was wondering if there was a way to add Dpos coins to your payment gateway like Oxycoin , Ark , Shift and Definetely Lisk to your BTCPay Infrastructure , Since they all use nearly the same codebase so implemnting only one of these coins with simple alteration would guarntee that everyone in the dpos community can use your payment gateway in their stores.

I really do think that this would add really a very high value to this project if this can happen.

I'm eager to hear your response! 

Regards,
Mody1996

**Comment by NicolasDorier** [comment]
If someone make a PR tested and testable, yes.

**Comment by mody199610** [comment]
In that case , what should i be adding or changing in your code? As a hint to start from there

**Comment by NicolasDorier** [comment]
I don't know, I never used Dpos. You should probably hire some C# and .NET expertise (not me, I have no time :( ), if you are asking this question it might be a bit ambitious for you to do.
