### ISSUE TITLE
Removing Discount field in POS

### ISSUE THREAD

**Issue by nodecheck** [btcpayserver/btcpayserver#580]
Is it possible to disable showing the "Discount in %" field by default in the POS app?  I've not been able to find it anywhere in the settings, nor the documentation.

**Comment by nodecheck** [comment]
@NicolasDorier thanks for moving and sorry for posting in wrong place.

If it would be possible to allow the ability to remove the discount field in POS, and also for when the pay button has been clicked to also remove the tip option as well, that would be good.  At present, I can't see a way to do it.  Some check boxes for enabling/disabling these options would be great.

**Comment by rockstardev** [comment]
I agree that Discount % being enabled by default is a problem. @mariodian I thought you love me man and you left this one like this ;)

**Comment by rockstardev** [comment]
But we'll try to handle this one during my talk, so it's all awesome - thank you @mariodian for your awesome POS

**Comment by mariodian** [comment]
I'll add checkboxes however what is the reasoning for it to be disabled **by default**?

**Comment by nodecheck** [comment]
For me, I have no problem with it being enabled by default, just would be good to have the option to disable it with a checkbox, and a checkbox to enable/disable the tip option also.

**Comment by mariodian** [comment]
Done.

**Comment by NicolasDorier** [comment]
merged
