### ISSUE TITLE
Shopify Reporting BTCPay Server making API calls that will be removed. Needs to be updated

### ISSUE THREAD

**Issue by iggy097** [btcpayserver/btcpayserver#5804]
### What is your BTCPay version?

BTCPay Server v1.12.5+a86165ac0

### How did you deploy BTCPay Server?

Luna Node

### What happened?

- Email from Shopify - 

Hello there,   We’re   sending you this email because one or more apps installed on your Shopify   store are making calls to APIs that will be removed soon and will soon be   unsupported. These apps   must be updated by a developer before April 1, 2024 to continue working   normally.   We encourage you to forward this email to the partner or   developer who maintains your apps, and have them update your apps based on   the information below. If   you don’t currently have a developer maintaining your apps, you can hire a Shopify expert.   What   your developer needs to know   One   or more of your custom apps have made deprecated API calls in the last 30   days. Support for   these versions will be removed on April 1, 2024. Please   update the apps listed below to API version 2023-07 or later to ensure they   continue to function correctly.   Store:   Seductive   Studios   App:   BTCPayServer 3   Breaking changes:       The delivery_category        field has been removed from the ShippingLine REST Admin        API. View change.     The gateway,        payment_details,        and processing_method        fields on the Order        resource have been removed. The `orders/transactions.json` REST        endpoint, and the `transactions` GraphQL connection provide correct        information per transaction set. View change.                To   learn more about unsupported apps, read our Unsupported Apps guide.   If you still have questions, chat with us in the API forums or   contact us via Support.   Regards,   Shopify Apps Team
--

### How did you encounter this bug?

Shopify Emailed

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
@iggy097 can you provide these two **view change** links so we can compare?

**Comment by iggy097** [comment]
Removal of the delivery_category field on order shipping lines. — Shopify
developer changelog
<https://shopify.dev/changelog/removal-of-the-delivery_category-field-on-order-shipping-lines>

Payment properties deprecation on the Admin API Order resource — Shopify
developer changelog
<https://shopify.dev/changelog/payment-properties-deprecation-on-the-admin-api-order-resource>

**Comment by pavlenex** [comment]
Hey, so we've investigated this issue, and we confirm it's a false claim by Shopify. It seems they're using some sort of automatic code scanning which has been triggering false positives. We don't use any of the API calls they've mentioned. So you're all good. This has been a re-occuring issue for months now, and we keep checking, but it's always a false warrning. If you in the future experience problems or get a different email , feel free to comment on this issue, and we'll look into it again, but for now - you're all good.
