### ISSUE TITLE
[Bug]: BTCPayServer.Client has not been updated since September 2023 (current version is 1.7.3).

### ISSUE THREAD

**Issue by 0x627562** [btcpayserver/btcpayserver#5806]
### What is your BTCPay version?

v1.12.5+a86165ac0 (Altcoins)

### How did you deploy BTCPay Server?

Azure

### What happened?

I started experiencing serialization issues with Webhooks. I use `var webhookEvent = JsonConvert.DeserializeObject<WebhookEvent>(webookContent, WebhookEvent.DefaultSerializerSettings);` to deserialize webhooks, and I'm encountering the following error: `Error converting value "PayoutUpdated" to type 'BTCPayServer.Client.Models.WebhookEventType'. Path 'type', line 6, position 25. Requested value 'PayoutUpdated' was not found.`

WebhookEventType has new values introduced with this commit:  https://github.com/btcpayserver/btcpayserver/commit/a97172cea6b9b51018b7781300fe12bda85f6e37#diff-f43bf6a52c8018a401052fd3f749772ddcfb6d402dafcaee75fb659667711af8L3

### How did you encounter this bug?

N/A

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
bumped to 1.7.4, please reopen if you still experience issue!
