### ISSUE TITLE
[Bug]: 500 server error when asking for an email address and buying a product where you can enter the amount

### ISSUE THREAD

**Issue by Amperstrand** [btcpayserver/btcpayserver#5811]
### What is your BTCPay version?

© BTCPay Server v1.12.4+2111b67e2

### How did you deploy BTCPay Server?

https://signet.demo.btcpayserver.org/apps/2aQznnhetq7ZHW9fiFfFfGrY5B4A/pos

### What happened?

When you ask for an email address, selling an item where the user can choose what they pay results in a server error.

### How did you encounter this bug?

1. go to https://signet.demo.btcpayserver.org/apps/2aQznnhetq7ZHW9fiFfFfGrY5B4A/pos
2. pay for fruit tee
3. here you would normally enter the amount because it is an item that you can pay anything for. but this never happens
4. fill in an email address
5. get 500 server error

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by RaduskaCibrikova** [comment]
Co to znamená ja tomu nerozumím  ale vůbec může mi někdo pomocí

**Comment by RaduskaCibrikova** [comment]
Pomoc

**Comment by Karlitos88** [comment]
TENGO UN PROBLEMA ME GUSTARÍA ME CONTESTARAN PODER SER , SOBRE BITCOIN MINING COMO PUEDE SER QUE ME COBRARON LA TASA EN 6 O 7 OCASIONES SIN NINGÚN RESULTADO A CAMBIO Y SIGUEN MANDÁNDOME TODAVÍA 
Y TODOS LOS DÍAS INFORMACION PERO PARA VOLVER PAGAR 
CUANDO YA LO HECHO Y LO MIO DONDE ESTA ES RIDÍCULO SEGUIR ENVIANDO DINERO PARA PAGAR LA TASA ES MAS QUIERO CREER QUE NO ES UNA ESTAFA PORQUE YA LA CANTIDAD SUPERA LIMITE PARA PODER PRESENTAR UNA DENUNCIA POR ESO ANTES QUIERA MIRAR DE VER O PEDIR UNA EXPLICACIÓN SI PUDIERAN DEDICARME SU TIEMPO PARA VER CUAL ES MI PROBLEMA CON MI CUENTA 
THENEWFACTORY@ART&CONTENTS.RED 
JCARLOSSANTOSFERREIROS77@GMAIL.COM 
BARCELONA LUNES 4 MARZO 2024
![Screenshot_1.png](https://github.com/btcpayserver/btcpayserver/assets/104910602/22b3037a-5db6-4dd3-a4a0-b4641732ee74)

![20240124_155857.jpg](https://github.com/btcpayserver/btcpayserver/assets/104910602/4f4c6e3b-a767-4c7b-9bdb-f5ee80e19397)

![20240124_155608.jpg](https://github.com/btcpayserver/btcpayserver/assets/104910602/194aa465-6f99-4efd-ae31-a5717b1598ed)

![20240124_155827.jpg](https://github![20240124_155933.jpg](https://github.com/btcpayserver/btcpayserver/assets/104910602/69e50428-63b3-4f84-9971-ce10bde8bf2f)

/104910602/c4fe4aa0-8fc8-4224-997e-ab6bd78d1fb1)

![Cargando 20240124_155933.jpg …]()

**Comment by pavlenex** [comment]
@NicolasDorier do we have anything in signet demo logs that we can use to help debug?
