### ISSUE TITLE
Send link to choose password when creating new user

### ISSUE THREAD

**Issue by Bardesss** [btcpayserver/btcpayserver#582]
When the admin creates a new user, the admin must choose a password for the new user. 

It would be better if, when manually creating a new user, an email would be sent to the email address filled in by the admin so that the user can choose a password himself.

In this way, the user is also the only one who knows the password and does not have to trust a third party.

**Comment by pavlenex** [comment]
Admin would have to configures [SMTP settings](https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#how-to-configure-smtp-settings-in-btcpay) first to achieve that.

I don't really see why the user should choose the password when added manually by admin, they can always change it at a later point or just normally register through your server and create an account.

WordPress handles adding new users similarly. They generate a random password which you can show and change and then sends it to the new user. New user does not generate the password unless they register.
![screen shot 2019-02-01 at 15 27 14](https://user-images.githubusercontent.com/36959754/52128814-345b5100-2636-11e9-858d-1cfdc169f84a.png)

The only improvement we can do here is to have this random password generators, but again, you'd have to trust the admin that he didn't looked at it, so it's a bit pointless.

**Comment by Bardesss** [comment]
> I don't really see why the user should choose the password when added manually by admin, they can always change it at a later point or just normally register through your server and create an account.

For example, I do not want anyone to be able to register on my BTCPayserver. That's why I manually create users. But most do not trust others with their password. I can of course say that they can change it themselves, but it would be more user-friendly if they could choose a password themselves with the help of a link in a registration email.

**Comment by woutersamaey** [comment]
A checkbox that says “User must choose a new password on next login”, may also work here. 
Or, you can just don’t give the new user his password and force them through forgot password?

**Comment by pavlenex** [comment]
This is now possible in v1.0.5.6 that will be release in 2 days, so I'll go ahead and close the issue but if that does not fit your use-case feel free to re-open it guys.
![Screenshot 2020-09-29 at 19 09 43](https://user-images.githubusercontent.com/36959754/94590723-71526d80-0287-11eb-9dd4-253cd9c8b8ec.png)
