### ISSUE TITLE
[API docs]: Generate code examples for multiple languages 

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#5822]
As explored by @dennisreimann [here](https://github.com/btcpayserver/btcpayserver/issues/5572#issuecomment-1876976263) it might make sense to add code examples in different languages for the most basic stuff like stripe does as this will be a manual process, with cURL you have a vanilla api call but e.g. with PHP you need to show the example by using the PHP library.

Stripe also has those multi language examples only in their introduction/explanation section and not for the actual endpoints, they look the same as hours, see [here](https://docs.stripe.com/api/balance).

I think what we need to decide here is if it is enough to link to our [api examples on docs](https://docs.btcpayserver.org/Development/GreenFieldExample/) and improve them or move most important parts like authentication into the swagger doc with multiple language examples like it is done by stripe.

**Comment by ndeet** [comment]
So basically doing #5820 and #5821 with multi language examples will solve this one.

**Comment by pavlenex** [comment]
Let's then close it and focus on them.
