### ISSUE TITLE
Migrate BoltCard plugin (Bitcoin Atlatnis)

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5833]
During Bitcoin Atlantis, there have been numerous new changes and plugins around BoltCard. The consensus on a dev call was that @NicolasDorier will pack up all boltcard related changes (BoltCard Factory & BoltCard Balanced) packed into a single plugin and release between 1.13.0 and 1.14.0.

**Comment by NicolasDorier** [comment]
https://github.com/NicolasDorier/boltcards-plugin
