### ISSUE TITLE
Abstract XMR code in a plugin

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5836]
Depending on how things go with #5835 eventually XMR should be moved as a separate payment method into a plugin, to further reduce stress on the codebase.

**Comment by IndigoNakamoto** [comment]
Hi pavlenex, 
Would you please add: Abstract LTC code in a plugin to the Roadmap for 2.0.

**Comment by NicolasDorier** [comment]
Bitcoin clones won't be as plugin for a while as they share the same code as Bitcoin which will never be a plugin.

We might one day do it, but not planned in the short term.

**Comment by pavlenex** [comment]
closing as tracker is now #5588, so let's track it there.
