### ISSUE TITLE
Specify `mailto:` prefix for emails in `Server Settings > Branding > Contact`

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5843]
We should specify that for emails `mailto:` needs to be added, otherwise if user adds email@email.com and someone clicks, `contact us` on login page,  it gives 404. Even better if we can recongize it's an email and no need for mailto.

**To replicate:**

1. In Server Settings > Branding > Contact us add email@test.com
2. Log out
3. Go to login page, click contact us
4. 404 
5. To fix add mailto:email.test.com

##Solution: 
- Recognize it's email and apply mailto so user doesn't have to,
- less ideal: add text that for emails mailto: prefix is required.           

<img width="651" alt="Screenshot 2024-03-15 at 23 08 24" src="https://github.com/btcpayserver/btcpayserver/assets/36959754/eb7b79d8-83db-4cf1-89c3-30096fb69c34">
<img width="1172" alt="Screenshot 2024-03-15 at 23 08 51" src="https://github.com/btcpayserver/btcpayserver/assets/36959754/b6fa9f96-affe-45cc-acf0-c837f0ea7060">

Feature Introduced in this PR https://github.com/btcpayserver/btcpayserver/pull/5718

**Comment by pavlenex** [comment]
@TChukwuleta Here's another good first issue if you'd like to tackle it.

**Comment by TChukwuleta** [comment]
Sure @pavlenex
