### ISSUE TITLE
Item editor: Each item needs to be `saved` separately

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5847]
When dealing with a bulk of items, adding or changing, our POS currently expect that for every product change user needs to click on the `Apply`

Is there a way to unify these so that `Save` is the only call to action necessary? I'd assume it can be done as part of https://github.com/btcpayserver/btcpayserver/issues/5581 or https://github.com/btcpayserver/btcpayserver/issues/3827 that would need to be completed beforehand.

**Comment by dennisreimann** [comment]
There's a reason I implememted it like this, but right now I cab't recall exactly why. Maybe it was about generating the ID when addig items, but I'll need to check.

In general I agree this isn't optimal and I'll try to solve it so that changes can get applied directly.
