### ISSUE TITLE
[Bug]: Getting "missing-permission" for "btcpay.store.cancreateinvoice" forbidden 403

### ISSUE THREAD

**Issue by vitorlimadev** [btcpayserver/btcpayserver#5855]
### What is your BTCPay version?

v1.12.5

### How did you deploy BTCPay Server?

Docker, on digital ocean following the tutorial. No altcoins configured, just pure BTC/Lightning.

### What happened?

I'm the admin of a testnet BTCPay server.

I created several Greenfield API keys with all permissions, some with just unrestricted permission, and some with just invoice permissions. I built the header as `"Authorization": "token {key here}"`, and since I'm not getting 401, I assume the setup on my client application is correct.

I'm always getting this error when trying to create an invoice:

{
   "code": "missing-permission",
   "message": "Insufficient API Permissions. Please use an API key with permission \"btcpay.store.cancreateinvoice\". You can create an API key in your account's settings / Api Keys.",
   "missingPermission": "btcpay.store.cancreateinvoice"
 }
 
 My keys are configured like this:
 
![image](https://github.com/btcpayserver/btcpayserver/assets/30941353/4f8b0fa3-972b-495e-a029-675bdae9a2e3)

What could be causing this? I believe I followed the tutorial correctly, and I managed to make this work once with another instance of BTC Pay server a while ago with the exact same client/server code.

### How did you encounter this bug?

I'm getting this response when calling the API to create an invoice with a valid API key.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by vitorlimadev** [comment]
Update: I have a mainet server configured and running with the BTC node pruned and fully synced in the same 1.12.5 version. This error also happens on the mainet server. So it's not exclusive to testnet deploys.

**Comment by dennisreimann** [comment]
I cannot reproduce this and checked the permissions for the create invoice action, it should work with both API keys that are listed in your screenshot. btw the second one also has `unrestricted` permissions as far as I can see, so they should be equal in the end.

Which tutorial are you following?

**Comment by vitorlimadev** [comment]
@dennisreimann I have two very basic setups on Digital Ocean using this tutorial: https://molthoff.medium.com/running-btcpay-on-digital-ocean-for-10-month-how-to-add-other-coins-7a497339fb2f

One testnet and one mainet envs. My testnet env is synced using FastSync, my mainet is synced with the pruned Blockchain.

The configuration itself is very basic, I saw another issue from someone getting the same problem, but his issue was closed as a member believed it was Doge related: https://github.com/btcpayserver/btcpayserver/issues/5785

**Comment by vitorlimadev** [comment]
Closing since the issue was resolved on my side, will open a PR to fix this later.

**Comment by dennisreimann** [comment]
What was the problem and how did you resolve it?
