### ISSUE TITLE
[Bug]: QR Code Unscannable in dark mode on Samsung Internet browser

### ISSUE THREAD

**Issue by leesalminen** [btcpayserver/btcpayserver#5860]
### What is your BTCPay version?

v1.13.0
1fe766cb16fdff35e1e29952a0bd1996fdf36960

### How did you deploy BTCPay Server?

Manual

### What happened?

When attempting to pay an invoice using Checkout V2 using Samsung Internet browser with dark mode enabled, the SVG QR code is modified by the browser and becomes unscannable.

Screenshot:
![Screenshot_20240323_080611_Samsung Internet](https://github.com/btcpayserver/btcpayserver/assets/3018359/19aa583d-acf9-4058-85ff-066479b6c647)

### How did you encounter this bug?

1. Create an Invoice
2. Attempt to pay invoice with Checkout V2 enabled
3. Cannot scan QR code with any other device

### What browser do you use?

- Samsung A54 5G (SM-A546E/DS)
- Android 14
- One UI 6.0
- Samsung Internet v23.0.1.1
- Dark Mode Enabled

### Additional information

I found this post on Samsung forums: https://forum.developer.samsung.com/t/websites-dark-mode-gets-overridden-by-samsung-internets-dark-mode/22937/27 . The most recent comment is interesting:

```
Hello,

I am pleased to share with everyone that from Samsung Internet v24.0.6.15 you can specify the supported color schemes for the page via the color-scheme meta tag or CSS property:
<meta name=”color-scheme” content=”light dark”>

Please check out this [blog 3](https://medium.com/samsung-internet-dev/dark-mode-in-samsung-internet-7d6e974ba09e) for more information.

Additionally, the Samsung Internet team is improving their algorithm to adaptively “respect” the Web developers’ dark colors if defined like above, as per [CSS Color Adjustment Module Level 1 (w3.org) 2](https://www.w3.org/TR/css-color-adjust-1/#color-scheme-prop),
and if not defined, apply the browser’s algorithm. Hopefully, this will provide an enhanced experience to users and also give more options to the developers.

This is a “work in progress” under the same experimental flag, for upcoming versions like 25.0, 26.0, or above to be released later this year.

Sincerely,
Samiul Hossain
Samsung Developer Relations
```

I tried adding `<meta name=”color-scheme” content=”light dark”>` to the `<head>` of Checkout V2, but it did not have any impact on the issue. This is because the latest version of Samsung Internet available for my device is v23.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
It's "interesting" how the Samsung Internet browser applies its own dark theme and even overrides the webpage's settings. You can temporarily circumvent this by switching to the Light mode in the browser's setting ­— you'll stiill be able to use our dark mode afterwards and also see the proper colors ;)

I will submit a PR that incorporates the `color-scheme` meta tag, however, I'm also not able to test itright now because the latest released version of the browser on Android is still v23.

**Comment by dennisreimann** [comment]
> I am pleased to share with everyone that from Samsung Internet v24.0.6.15 you can specify the supported color schemes for the page via the color-scheme meta tag or CSS property:

Checked with v24.0.7.1 and this doesn't seem to be fixed.

**Comment by dennisreimann** [comment]
It still behaved the weird way even with v25 of the browser. According to the ongoing [discussion on the forum](https://forum.developer.samsung.com/t/websites-dark-mode-gets-overridden-by-samsung-internets-dark-mode/22937/27), Samsung seems to be convinced that managing these preferences manually via the settings if you don't want their proprietary default seems to be the way to go. We cannot help with that.
