### ISSUE TITLE
problem with xpub/ypub - no matching addresses

### ISSUE THREAD

**Issue by talentpierre** [btcpayserver/btcpayserver#587]
i tried to use my ypub from samourai to set up a wallet. last time it worked, now it doesn't.
after generating the ypub i pasted it into the wallet section. 
because i use my wallet quite often i have more then 10 addresses used, so i had to enter my actual address in the hintfield of btcpayserver because no address matched to my receiving address. after entering i got this message from btcpayserver:
> Impossible to find a match with this address >

why btcpayserver couldn't find my address?
afterwards i tried to insert an address from the list, presented by btcpayserver but i got the same message.

maybe you can help

**Comment by pavlenex** [comment]
> had to enter my actual address in the hintfield
You should enter the receiving address that you see in Samourai, make sure you've added the appropriate sufix as explained [here](https://youtu.be/xX6LyQej0NQ?t=123).

**Comment by talentpierre** [comment]
i did it exactly as described in the video but btcpayserver can't find my address. 
I tested it with electrum desktop wallet and it worked (no addresses used until now). 
what could be the problem with samourai wallet or the derivation path after 10 addresses?

**Comment by pavlenex** [comment]
It's explained in documentation, most of wallet do not have gap limit above 20, so if you have 20 unpaid invoices, the money won't show up. Use internal btcpay wallet or Electrum, everything else will just bring more confusion.
