### ISSUE TITLE
[Bug]: email not obfuscated when adding "contact us" information

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#5870]
### What is your BTCPay version?

v1.13.0-rc2

### How did you deploy BTCPay Server?

docker

### What happened?

When adding a contact mail in server settings -> branding and it is displayed on the login page the email is not obfuscated and so it can be scraped by webcrawlers and get added to spam lists.

### How did you encounter this bug?

1. add email to server settings -> branding
2. on login page check the "contact us" link

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
What can or should be done about this?

**Comment by ndeet** [comment]
The basic idea to prevent this is to output obfuscated garbage on initial page load and html source and then make it a proper mailto link with javascript. Maybe there is something prebuilt for vue.js, the basic idea is like this https://www.npmjs.com/package/email-scramble

Obviously this won't work if the crawler parses JS like a webbrowser. Safest thing there would be a contact form but there you then have again that spam problem where you need some kind of captcha or trap to prevent spam :disappointed:

**Comment by dennisreimann** [comment]
Maybe we should then simply remove it from the public pages and only handle it via #5866? @pavlenex

**Comment by ndeet** [comment]
If the user forgets his password and smtp is not setup it might be the only way to contact the owner though? :sweat_smile:
