### ISSUE TITLE
New item view for keypad (possible improvements)

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5873]
Leaving this for discussion for design meeting, but I've tested our new keypad pos on bitcoinize, and +- experience is a bit challenging. All other buttons are okay, but these seem to be hard. I assume same exprience would happen on other places where we have thi.

I just imagine burger guy with gloves trying to navigate around to add/remove items, when I had troubles.

This is me attempting to add/remove. (gif may not be that good)

![IMG_3687-2](https://github.com/btcpayserver/btcpayserver/assets/36959754/9cb08b24-30a7-4b04-9956-b8ff8db90d1b)

Possible solution could be something that Wolt app does, asically you can click on item itself, or swipe left/right it's pretty snappy 

unsure if we can do it in a same way though.

![RPReplay_Final1711456164-2](https://github.com/btcpayserver/btcpayserver/assets/36959754/38f1b8d3-5981-4d39-ba14-4d0664e0e6a2)

This issue is just a discussion for design call and shouldn't be tackled until there's consensus on how to approach it (possibly in other pos views) as well. cc @dstrukt @dennisreimann

**Comment by nostitos** [comment]
Would increase + - size first, I've never seen that interface before and I suspect most people would get stuck not knowing what to do.
