### ISSUE TITLE
Server Settings Not Appearing

### ISSUE THREAD

**Issue by Freefromchainz** [btcpayserver/btcpayserver#588]
Here we have my Lunanode setup 
![btcpay no server settings](https://user-images.githubusercontent.com/8317700/52357590-a5fb1c80-29f3-11e9-908e-927dd589e90a.PNG)

and here we have my local test environment 
![btcpay with server settings](https://user-images.githubusercontent.com/8317700/52357664-c1662780-29f3-11e9-944d-c5e0901296f3.PNG)

I am missing something with my lunanode setup?

**Comment by Kukks** [comment]
your user is not an admin on the luna node env

**Comment by pavlenex** [comment]
Yes, you need to be logged in as admin. First account you created is admin account.

**Comment by Freefromchainz** [comment]
ha thanks fellas!
