### ISSUE TITLE
[Bug]: Receipt Data does not show on printed paper version from POS.

### ISSUE THREAD

**Issue by mjlamb** [btcpayserver/btcpayserver#5882]
### What is your BTCPay version?

BTCPay Server v1.13.0

### How did you deploy BTCPay Server?

Manual deployment.

### What happened?

I'm using the POS app and I have a form that collects some data before the invoice is displayed for payment, I want this data on the receipt screen page AND printed paper version, but the data only displays on the screen page. I use the receiptData "fieldset" in the form and the mirror type to get the data on the receipt page, however when i use the [Print] option to create a paper receipt, it only prints the basic, orderid and total on the receipt, no other data. I would expect it to print the form data collected for receipt also. 

### How did you encounter this bug?

Setup form to collect data, added receiptData with a mirror type

### What browser do you use?

Pos app, used on chrome or brave, same result.

**Screen display showing fields on the page OK.**
![image](https://github.com/btcpayserver/btcpayserver/assets/2274034/cbb623d5-1e5c-4c7c-b4d5-c6373de602bb)

**Print paper receipt shows no fields**.
I would expect to see name, title, description, guess

![image](https://github.com/btcpayserver/btcpayserver/assets/2274034/ecf22d7d-ae94-4dbc-9d81-b892e4826c92)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by mjlamb** [comment]
Also the TIME is wrong on the paper receipt, it is ONE hr (or 13hr) different from the transaction time.
The transaction happened 11:30PM, but the paper receipt is showing 10:33 , maybe it is a timezone and is 13hr out.
It is hard to tell if the 10:33 is a 12hr or 24hr time.

**Comment by dennisreimann** [comment]
Thanks for reporting this. I've added fixes for the issues you mentioned.

**Comment by mjlamb** [comment]
Looking forward to merge, will test once merged.
