### ISSUE TITLE
Fix Crowdfund missing user input fields

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#589]
Improve the user input fields for Crowdfund:

1. Add asterisks for required user input.
2. Fix message for primary currency (remove extra "The")
![cf_createfields](https://user-images.githubusercontent.com/39231115/52370245-a30e2500-2a0f-11e9-9ec1-d17241042e21.PNG)

**Comment by rockstardev** [comment]
Thanks Brit, I got it tonight
