### ISSUE TITLE
Problem with resetting Bolt Cards

### ISSUE THREAD

**Issue by rockstardev** [btcpayserver/btcpayserver#5894]
Occasionally reset of bolt cards fails. Here is the server logs:

![image](https://github.com/btcpayserver/btcpayserver/assets/5191402/af680809-e244-4b7f-8a27-9d0473adadfa)

https://github.com/btcpayserver/btcpayserver/blob/v1.12.5-r0-atlantis/BTCPayServer/Controllers/UIBoltcardController.cs#L136

The problem seems to be with `HexToBytes` method from Extensions.cs

![image](https://github.com/btcpayserver/btcpayserver/assets/5191402/df2ab7d4-27b0-4e8a-9c1a-2ea8b5b87f1d)

**Comment by pavlenex** [comment]
I wasn't able to replicate this one, it seems that the issue comes when there's a change in lightning wallet setup (for example from one blink to another) or when a different store is used. I just wasn't able to go deep into this one and debug it.

**Comment by NicolasDorier** [comment]
may or may not be related https://github.com/NicolasDorier/boltcards-plugin/issues/18
