### ISSUE TITLE
No UTXO left to bump fee

### ISSUE THREAD

**Issue by nostitos** [btcpayserver/btcpayserver#5895]
TX spends an entire single UTXO from coin selection BUT the option "take fee from sent amount" was selected.

Seems like it's only going to try bump by trying to reduce the change

![image](https://github.com/btcpayserver/btcpayserver/assets/48504624/8c69a13c-3a0f-4c27-8cc5-b81f163ef46f)

**Comment by pavlenex** [comment]
Can you please provide more details? Also don't ignore but report templates, they are there for a reason, so we don't have do these hops. Once this issue is properly formatted, I'll re-open it.
