### ISSUE TITLE
BTCPay Server 2.0: Megathread

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#5899]
This is a mega thread to track everything that should be cleaned up for BTCPay Server 2.0:
Could use project milestone, but at this stage this is more of a brainstorm.

- [x] [The Big Cleanup: Refactor BTCPay internals](https://github.com/btcpayserver/btcpayserver/pull/5809/commits/11068605209b6807c3c86b0be1f18e589a8fa74f) 
```[tasklist]
### Deprecations and Cleanups
- [x] Remove Checkout v1 https://github.com/btcpayserver/btcpayserver/pull/5906
- [x] Cleanup the AddressInvoice table from non on-chain data (https://github.com/btcpayserver/btcpayserver/pull/5905)
- [x] Remove MySql/Sqltite depedency (https://github.com/btcpayserver/btcpayserver/pull/5910)
- [x] Remove any migrations code older than 2020 (https://github.com/btcpayserver/btcpayserver/pull/5939)
- [ ] #5744
- [ ] Remove Guest role
- [ ] Cleanup uppercase/lowercase inconsistencies in POS metadata and receiptData
- [x] Update status field of Invoices to not use legacy bitpay's status, but the BTCPay native one (https://github.com/btcpayserver/btcpayserver/pull/5982)
- [x] Decoupling PaymentMethodId from Payouts with PayoutMethodId https://github.com/btcpayserver/btcpayserver/pull/5944
- [ ] Rename *PaymentData to *PaymentDetails
- [ ] VACUUM (ANALYZE) as part of the migration to 2.0
- [ ] Cleanup data such as old expired invoices logs
- [x] Removing periodicity of pull payments (https://github.com/btcpayserver/btcpayserver/pull/5963)
- [ ] https://github.com/btcpayserver/btcpayserver/issues/5903
- [x] Remove docs on https://docs.btcpayserver.org/Development/Theme/#checkout-page-themes (https://github.com/btcpayserver/btcpayserver-doc/pull/1385)
- [ ] Onchain: Introduce pending transactions (#5743) as new concept/layer between transaction creation and signing
- [ ] Refactor onchain support to be similar to LN (connection string style, allows plugins to provide their own onchain tracker system instead)
- [ ] Cleanup all `[Obsolete]` declarations
- [x] Migration of Payouts
- [ ] https://github.com/btcpayserver/btcpayserver/issues/5485
- [ ] Restrict creation of new stores to Owner role
```

```[tasklist]
### Pluginization
- [ ] Move Bitpay integration as system plugin
- [ ] Make ZCash support an external plugin
- [ ] Make system plugin enableable/disableable
- [ ] Add test for migration of Monero payments
- [ ] Move boltcard code/schema as a plugin (alongside with the bolt card factory stuff)
- [ ] Convert payjoin receiver to use the payjoin receiver nuget lib to allow more complex workflows through plugins
- [ ] Onchain: Abstractify hot wallet signing to service so that we can support various new modes (such as remote signing via app)
```

```[tasklist]
### Optional / Nice to have
- [ ] Remove direct dependency of NBXplorer (allow an LN only instance for example)
- [ ] Introduce modifiable Server roles ( allows users without store creation for example)
- [ ] Convert various UIs to Blazor
- [ ] Convert Dashboard to Blazor
- [ ] Merge -LN and -LNURL payment methods
- [ ] Allow topups on pull payments
- [ ] Allow extensions to add fields to Receipts (Proof field got removed in #5809)
- [ ] One payment method config can create several payment prompts? @Kukks
- [ ] ~Remove Invoice Archival?~ (Seems to be used, ask @d11n)
```

**Comment by NicolasDorier** [comment]
> Refactor onchain support to be similar to LN (connection string style, allows plugins to provide their own onchain tracker system instead)

@Kukks I believe it isn't possible. We are querying NBX database directly in SQL.

**Comment by pavlenex** [comment]
>  Convert various UIs to Blazor

Can we be more specific when listing issues, what does this mean?

**Comment by Kukks** [comment]
> >  Convert various UIs to Blazor
> 
> Can we be more specific when listing issues, what does this mean?

I believe it is any UI that uses Vue currently. We can work on a list later

**Comment by pavlenex** [comment]
Alright, I understood this list should be a list of breaking changes, but it seems we're pilling quite a lot of things here, and I am trying to understand how to prioritize what is now becoming quite a massive list of tasks.

**Comment by ndeet** [comment]
**API: Permission on [Refund Invoice endpoint](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Invoices_Refund)**
The current permission is `btcpay.store.cancreatepullpayments` but it should imo be `btcpay.store.cancreatenonapprovedpullpayments`

**Comment by Kukks** [comment]
> **API: Permission on [Refund Invoice endpoint](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Invoices_Refund)** The current permission is `btcpay.store.cancreatepullpayments` but it should imo be `btcpay.store.cancreatenonapprovedpullpayments`

I believe we can do this without a breaking change as it softens the permission

**Comment by ndeet** [comment]
**API: Invoice refund inconsistency**
With the [pull payments endpoint](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Invoices_Refund) you can set paymentMethods as an array and if not set it will apply all available payment methods, with the [invoice refund endpoint](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Invoices_Refund) you only can pass a string and it is required too.

Suggestion: Make it a nullable array too to be consistent and more flexible

**Comment by NicolasDorier** [comment]
> API: Invoice refund inconsistency

We can do it without breaking change, don't have to be for 2.0.

**Comment by NicolasDorier** [comment]
Given we need to release 2.0 in september, I am kicking the can for anything that isn't a breaking change.
I think there is good suggestions here that we should definitely do after in a minor or major release.

**Comment by NicolasDorier** [comment]
> Use of GIN index for invoice search rather than separate table

Removed this. The current search that is implemented support suffix (searching nicolas will returns nicolasdorier as well). This isn't possible to really do the same with GIN index. Maybe we are fine into dropping this, but better to kick the can down the road.

**Comment by NicolasDorier** [comment]
> **API: Invoice refund inconsistency** With the [pull payments endpoint](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Invoices_Refund) you can set paymentMethods as an array and if not set it will apply all available payment methods, with the [invoice refund endpoint](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Invoices_Refund) you only can pass a string and it is required too.
> 
> Suggestion: Make it a nullable array too to be consistent and more flexible

Opened https://github.com/btcpayserver/btcpayserver/issues/6185. This doesn't have to be in 2.0, as it isn't a breaking change.
