### ISSUE TITLE
Lightning Payment max value

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#59]
Would be nice for it be possible to allow a configurable amount at which anything below that amount is shown the option to checkout in lightning, but anything over is not. 

For example, if I offer $25 amazon gift cards, and want to have those purchasable on lightning but not $50, I could set the threshold to $25 so anytime BTC pay needs more than $25 lightning simply doesn't show. 

This would allow a few testers to start taking lightning with minimal risk. #reckless

**Comment by Eskyee** [comment]
#reckless & simple

**Comment by NicolasDorier** [comment]
Done .64
