### ISSUE TITLE
Export - PoS tips data

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#590]
Now that #548 is merged, is it possible to add Tips info to the export? This would be helpful for the Quickbooks integration and any US brick and mortar stores (because tips are taxed differently). 

Some possible solutions suggested by @JeffVandrewJr in Mattermost:

1. BTCPay supported a tipsIncluded field similar to taxIncluded.
2. The POS app split tipped transactions into two separate invoices, one for the real transaction and a second one for tips, with the tip transaction consistently being designated as a tip either in the orderId or item field.

**Comment by Kukks** [comment]
Second option is too crazy and would be a horrible ux and encourage buyers to not pay a tip.

We can include the tipdata in the `PosData`. That would be the easiest solution but not sure if it would help the quickbooks integration much

**Comment by cryptomulde** [comment]
So let’s assume I am a Restaurant and I want to easily accept BTC via LN and btcpayserver. The easiest way I found out is using the POS App with custom amount.

What I would need is the ability to add an Order ID to my invoices so  that the accounting of the restaurant can get linked with btcpay. The easiest way would be to extend that custom amount field with some sort of order reference/order id. Anyone can help me to get this done?

steps:
The waiter creates the invoice for 2 beers and 2 wines in their "normal cash system". They book it as "cash payment or cash payment with tag btc". The cash system creates an invoice number for every receipt it prints. Waiter creates receipt, after creation opens btcpayserver pos —> inputs created amount and invoice number —> customer pays and takes receipt from "traditional cash system".

You would have a link between Btcpay accounting and your "traditional cash system". No need to change anything for the shop. They can go their old way and simply add one step in the end, which allows them to input their amount and order id.

![photo_2019-03-06_18-26-52](https://user-images.githubusercontent.com/48246159/53900739-79134700-403d-11e9-9bd1-fe79de3de7d1.jpg)
![photo_2019-03-06_18-26-57](https://user-images.githubusercontent.com/48246159/53900740-79134700-403d-11e9-9f5b-1a587387bba4.jpg)

**Comment by britttttk** [comment]
QB and fiat system integration is a bit beyond the scope of the issue at the moment (see Advanced PoS Considerations below). The important thing for now in BTCPay, is that store owners need to know how much to pay back to the employee in tips. Meaning the store owner needs to be able to easily distinguish between "item" sales and "tip" sales. 

Simple PoS Tips Accounting:

- If the tips are paid to someone using a pay button or a tip donation page, then one store can be assigned per person and this would be easy. There are only "tips" and no "items". All payments to this tips store can be paid to the employee. 

- However, when the tips are earned through the PoS, this is where the issue occurs. The tips may be earned as a percentage of item sales or paid in addition to an invoice of items. Currently, the store owner needs to manually view each invoice and then sum the tip values to distribute to the employee. 

- As a UI solution, maybe the PoS App or Store could keep a "tips value" button of tip payments per store, that would accumulate the total value (or perhaps percentage of sales), and the owner could press a "Pay Out" button to clear. Even if it's just an accounting button and does not actually pay from the wallet. 

Advanced PoS Considerations:

- In the future, for QB and US accounting software, it's mainly important to keep tips data so that store owners can deduct the tips from their earnings because the employee would pay taxes on this as earned income, not the store owner since they do not keep this money. 

- Tipped employees do not work constantly. The store owner needs to recall which employee was working at the time of the tipped invoice. Typically the store owner would review sales and pay out the tips prior to the employee leaving work to avoid having this as a backlog task. 

- Multiple tipped employees may be working using the same "store". This would be a tipping nightmare and would incentivize shared tipping which is not always ideal. This might be solved by one PoS per employee, per store or some type of user function within PoS. 

- @cryptomulde the custom payment idea you mentioned is a good way for businesses to accept crypto on the fly but it's really unlikely that a business owner would do this in high level production because it's complicated in terms of fiat & BTC accounting, taxes, etc. If a business owner was serious about accepting BTC payments, they should build out their PoS and use it alongside their fiat PoS.

**Comment by cryptomulde** [comment]
> but it's really unlikely that a business owner would do this in high level production because it's complicated

Why would it be complicated? Isn't it a challenge everyone would have to face, that wants to use btcpay for their business? If they have a section in their "old" accounting that refers to BTC we know which order was paid using BTC, each order has a unique invoice-ID. We would export our btcpayserver invoices and merge those with our existing accounting. Btcpayserver accounting more or less acts as a "proof" to verify the payment booked in their "old" cash system.

If the customer paid in BTC but value was denominated in FIAT currency I don't see a problem. Bitcoin would act as the payment method, like Paypal, Visa or Cash. The invoices of btcpayserver would act as "proof" for these payments.

> If a business owner was serious about accepting BTC payments, they should build out their PoS and use it alongside their fiat PoS.

I don't think it's unlikely at all. We have to provide them with easy solutions, so they don't get that much scared of upcoming changes in their way of accepting payments.

They don't want to create a completely new solution, best would be to integrate it in their existing structures IMO. Later on we can tweak their POS systems for BTC, but right now we have to make it as easy as possible for them to accept BTC with their existing hardware. (smartphones, tablets, laptops) 

Immagine being a small restaurant or souvenir-shop that wants to give their customers an option to pay via bitcoin. You don't really care about bitcoin at all, you just want it to work easily. You would not  make a huge investment to accept BTC. You don't want complicated solutions. 

Only thing they need is a zap wallet or "tweaked donation button", they click receive and input order number created by their cash system plus amount for the invoice. 
Easy, no problems, very uncomplicated and easy to understand.

You could also show them how to create a manual invoice via btcpayserver, but user experience with creating manual invoice is really bad in comparison to ZAP or donation button.

If zap integration to btcpay accounting is not possible, an effort could be made to tweak the donation button and add an additional field for text, that can act as order id in "invoices" overview for btcpayserver.

I don't think its complicated to do, but I'm lacking the abilities to do so.

I appreciate your feedback!

**Comment by britttttk** [comment]
> Why would it be complicated?
> If the customer paid in BTC but value was denominated in FIAT currency I don't see a problem.

This makes no sense. The exchange rate between these two is constantly changing. If you accept BTC, then your asset is BTC, not fiat. Until you convert the asset, from an accounting perspective, it's completely pointless to document the value of your BTC in fiat. 

> steps:
The waiter creates the invoice for 2 beers and 2 wines in their "normal cash system". 

They should use their cash system for fiat, that's what it's designed for. 

> They book it as "cash payment or cash payment with tag btc". 

What cash system or PoS are you referring to? There is no enterprise cash PoS system that will allow you to "create an order" and simply not pay it but mark it as paid?... Unless you just want your cash drawer to be missing money. Why over-complicate your fiat payment system? 

> The cash system creates an invoice number for every receipt it prints. 

BTCPay creates invoice numbers for you. Why do you want to associate your BTC payments with an invoice number for a completely different payment processor?

> Waiter creates receipt, after creation opens btcpayserver pos —> inputs created amount and invoice number —> customer pays and takes receipt from "traditional cash system".

Why does the customer care which system the receipt comes from? They're paying in BTC, why do they care about your cash system?

> You would have a link between Btcpay accounting and your "traditional cash system". No need to change anything for the shop. They can go their old way and simply add one step in the end, which allows them to input their amount and order id.

So what are they doing about the cash that is missing in their fiat system drawer? From creating invoices/transactions in your fiat system and not paying them because they are being paid with the BTCPay payment processor? It's so much extra work this way. 

> Only thing they need is a zap wallet or "tweaked donation button", they click receive

How are you showing this to the customer? Why can't you show them the BTCPay interface on this device instead? Like I said, if a small business owner just wants to accept BTC on the fly, then great pull out your wallet and let someone pay you. If you are an actual large business, you need a PoS system, BTCPay has one already. 

BTCPay is also free for merchants using some third-party providers. I understand that you want to allow merchants to integrate BTCPay into their traditional accounting but they are completely different systems. :)

**Comment by pavlenex** [comment]
Obsoleted by #2631 and the future configurable fields.
