### ISSUE TITLE
[Bug]: UX: Possible double sent on pull-payments/payouts

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#5913]
### What is your BTCPay version?

v1.13.0

### How did you deploy BTCPay Server?

docker

### What happened?

When doing pull-payments and having a payout processor enabled it could lead to double sending the transaction as after clicking button "approve + pay" the user is redirected to sign transaction screen where it would sign it a scecond time, the processor already sent the tx on click of the button in the previous step.

Problem description from Nicolas:

> The problem is: The automated payout processor will automatically pay from a hotwallet any payout that become approved. 
> 
> When the user click on the "Approve & Pay", he approves the payout, and thus the automated payout processor send the money. Then the user not noticing it, proceed with doing his own transaction.

### How did you encounter this bug?

1. have payout processor enabled
2. create a pull payment (add payout address)
3. in payouts: approve + pay the pull (sends first tx)
4. on sign tx screen, sign and broadcast (sends second tx)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by ndeet** [comment]
UX wise, would it make sense to not proceed to signing screen when payout processor is enabled or just not show it at all? @dennisreimann and @dstrukt likely have better insights how to handle it.

**Comment by dennisreimann** [comment]
Yup, agreed. We should alter that flow and instead of sending the user to the signing proces, it should notify them about the payment getting handled via the automated payout processor.
