### ISSUE TITLE
[Bug]: 404 when visiting POS or crowdfund over Tor

### ISSUE THREAD

**Issue by elvece** [btcpayserver/btcpayserver#5917]
### What is your BTCPay version?

BTCPay Server v1.13.0

### How did you deploy BTCPay Server?

Issue is relevant on both the official Docker deployment and StartOS v0.3.5.1 deployment.

### What happened?

When visiting a POS store or crowdfund on its Tor url, the page returns a 404. 
Both plugins were already installed and working over Tor prior to updating to 1.13.0.

### How did you encounter this bug?

1. Logged into BTCPay
2. On left sidebar, navigate to Point of Sale or Crowdfund plugin section, and click on either the store or fund. 
3. Once store/fund loaded, click "View".
4. Page returns 404.

### Relevant log output

```shell
There are no relevant logs within BTCPay Server.
```

### What browser do you use?

Firefox 124.0.1 (64-bit)

### Additional information

<img width="1725" alt="Screenshot 2024-04-09 at 12 12 32 PM" src="https://github.com/btcpayserver/btcpayserver/assets/12953208/3ac5d4b7-580b-4906-b8f2-b3b213746ec2">
<img width="1722" alt="Screenshot 2024-04-09 at 12 13 40 PM" src="https://github.com/btcpayserver/btcpayserver/assets/12953208/59a09f40-2e87-4c0c-86c6-b713ac52fd0b">
<img width="1725" alt="Screenshot 2024-04-09 at 12 13 50 PM" src="https://github.com/btcpayserver/btcpayserver/assets/12953208/ebac1b33-6f9d-4098-93a4-a175487458e7">

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by elvece** [comment]
To note, when the .onion address is proxied via clearnet it works fine (and works fine over a .local address).

**Comment by elvece** [comment]
Any more information needed or fixes in progress for this?

**Comment by dennisreimann** [comment]
> Any more information needed or fixes in progress for this?

No, thanks for reporting! This will be fixed in the next update, sorry for this :)

**Comment by elvece** [comment]
Sure thing thanks for working on it!
