### ISSUE TITLE
Looking to configure for Lightning Charge and Spark

### ISSUE THREAD

**Issue by Freefromchainz** [btcpayserver/btcpayserver#592]
First I would like to state that I did not do the one click fast lunanode setup. Currently I am trying to setup the server to use the lightning publisher plug-in on wordpress. Currently this is all my server is exposing at the moment. 

![btcpay no lightning charge server settings](https://user-images.githubusercontent.com/8317700/52390387-459cc700-2a55-11e9-8518-77b2c1c21224.PNG)
  
Should I scrap this server and start another with the fast setup  using the Api key? Will that setup have lightning charge and spark ready to expose? Or am I missing something in all the various documentations that would let me add charge and spark to my existing server?

**Comment by pavlenex** [comment]
Lightning publisher is c-lightning only and you're running the LND implementation. That was mentioned in videos and documentation.

If you're using Docker, you can easily [change from one to another:](https://docs.btcpayserver.org/faq-and-common-issues/faq-lightningnetwork#how-to-change-from-c-lightning-to-lnd-or-vice-versa)

If your LND node has some funds in it already that you don't want to loose, close all channels and withdraw from your on-chain LN wallet to some other wallet before doing the changes.
