### ISSUE TITLE
[Bug]: logs have not datetime

### ISSUE THREAD

**Issue by tlindi** [btcpayserver/btcpayserver#5928]
### What is your BTCPay version?

0.13.0

### How did you deploy BTCPay Server?

Integrated to MyNodeBTC Premium

### What happened?

Follow troubleshootin instructions: to [https://docs.btcpayserver.org/Troubleshooting](https://docs.btcpayserver.org/Troubleshooting)

### 2.2.1 - Lightning Network LND - Docker

use command:
`docker logs --tail 100 generated_btcpayserver_1`

You see log entries, but there is no way to know when they have happened.

### How did you encounter this bug?

I followed the instructions.

### Relevant log output

```shell
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: BTCPayServer.Plugins.PluginManager: Loading plugins from /root/.btcpayserver/Plugins
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.13.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 1.13.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PointOfSale - 1.13.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PayButton - 1.13.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.NFC - 1.13.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Crowdfund - 1.13.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Bitcoin - 1.13.0
```

### What browser do you use?

Not related

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
You can use the `-t` option like this: `docker logs --tail 100 -t generated_btcpayserver_1` - does this work for you?

**Comment by tlindi** [comment]
> You can use the `-t` option like this: `docker logs --tail 100 -t generated_btcpayserver_1` - does this work for you?

works great. Thank you!
