### ISSUE TITLE
[Bug]: Lightning indicator always green in Dashboard

### ISSUE THREAD

**Issue by Nisaba** [btcpayserver/btcpayserver#5940]
### What is your BTCPay version?

1.13.1

### How did you deploy BTCPay Server?

Docker

### What happened?

Hi,
I've stopped the lightning docker.
But the Lightning indicator stays green in dashboard.

![image](https://github.com/btcpayserver/btcpayserver/assets/34550856/556a1fb9-1650-412b-bc12-6d9010f030f5)

Whereas it's shown as unavailable, as expexted, in the public node info

![image](https://github.com/btcpayserver/btcpayserver/assets/34550856/320a20dd-b593-4dfe-997e-1909a918f826)

### How did you encounter this bug?

After stopping the lightning docker

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Yeah I think that green indicator is indicating the setup success not the status of the node. Perhaps something to be discussed as I think we could easily implement it. @dstrukt something for design call I guess.

**Comment by dstrukt** [comment]
@dennisreimann's PR fulfill the original intention behind this feature!
