### ISSUE TITLE
[Bug]: Bringin Plugin not starting on MyNode

### ISSUE THREAD

**Issue by tlindi** [btcpayserver/btcpayserver#5941]
### What is your BTCPay version?

0.13.0

### How did you deploy BTCPay Server?

With MyNode custom app version. 

### What happened?

Add "BringIn Plugin" restart btcpay server.

"Menu - Plugins" has Bringin. click it and page shows only 

> Loading Bringin offramp

In log is repeating following (where only string after `circuit '` changes):

```
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Unhandled exception in circuit 'ylFvN-3k_oTzMDFR1Jghs2feJyxQQxhgxa1GYjnxAwg'.
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Bringin.Components.BringinWidget.OnAfterRenderAsync(Boolean firstRender) in /build/Plugins/BTCPayServer.Plugins.Bringin/Components/BringinWidget.razor:line 77
   --- End of inner exception stack trace ---
```

### How did you encounter this bug?

By installing and clicking meny Bringin

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Hey, if this is still an issue please file this in appropriate repo since plugins aren't related to BTCPay main repo or codebase https://github.com/Kukks/BTCPayServerPlugins/pulls
