### ISSUE TITLE
[Bug]: Approve & Send option not visible after update

### ISSUE THREAD

**Issue by danish-dct** [btcpayserver/btcpayserver#5957]
### What is your BTCPay version?

BTCPay Server v1.13.1+ca55e1f30

### How did you deploy BTCPay Server?

Docker

### What happened?

After I updated the BTCPayServer, the Approve & Send option is missing because of which I am unable to send payments.
The only option showing is Approve and Cancel. If I click on Approve button, it will instantly complete the selected payout without sending any payment.

![image](https://github.com/btcpayserver/btcpayserver/assets/105282628/32c58408-31ca-46aa-8c5c-359f0dd2206c)

### How did you encounter this bug?

1. Create a Pull Payment.
2. Add wallet address to the pull payment.
3. Go to Payouts and select the payment to Send. (At selecting, earlier it used to show option to Approve & Send but it's not showing anymore)

### What browser do you use?

Chrome Version 124.0.6367.60 (Official Build) (64-bit)
Firefox 125.0 (64-bit)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
We removed this on purpose for cases in which an automated payout processor is enabled. The reasoning behind this is that the processor will take care of the sending and there were cases in which this resulted in double payouts, because users weren't aware of this and additionally also did a payout manually. For details see #5913 and #5931.

**Comment by danish-dct** [comment]
Okay, I read those issues and it seems like we have to enable the automatic payout processing if I'm not wrong.
Could you share some doc link that shows how to do the Pull Payments & Payout's using automatic payout processing?

**Comment by dennisreimann** [comment]
Unfortunately we haven't covered this feature yet, but I just added an issue for that (btcpayserver-doc#1388).

For now you can simply check the Store Settings > Payout Processors section and configure either onchian or lightning processors:

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/bb4e3c59-5923-47f8-b186-78c22df704a3)

For onchain you'll need a hot wallet for the store, here's what the config looks for Lightning and it's similar to onchain:

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/36d64080-8179-420a-ba77-1767307167c6)
