### ISSUE TITLE
[Bug]: unable to create wallet with "Import keys to RPC"

### ISSUE THREAD

**Issue by tomholford** [btcpayserver/btcpayserver#5961]
### What is your BTCPay version?

v1.3.1

### How did you deploy BTCPay Server?

followed the docker guide

### What happened?

![telegram-cloud-photo-size-1-5003645352791880041-y](https://github.com/btcpayserver/btcpayserver/assets/16504501/6d9f8e6b-e798-4d70-9cad-12bd63718269)

Saw this when trying to create a new wallet with "Import keys to RPC". It works as expected when disabled.

### How did you encounter this bug?

1. Install new instance on Ubuntu
2. Onboard to new store
3. Attempt to create new wallet with the aforementioned Advanced feature

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
@tomholford can you access the logs of bitcoind `docker logs btcpayserver_bitcoind`.

Check when the node start, if you see something like `The wallet does not exists, creating it at`.

Also check `ls /var/lib/docker/volumes/generated_bitcoin_wallet_datadir/_data/mainnet`  is there any data there?

**Comment by pavlenex** [comment]
@tomholford can you provide required info, otherwise we'll assume you solved it and proceed with closing this issue.
