### ISSUE TITLE
Getting "Invalid destination or payment method" when trying to payout a pull payment to a LN to LIQUID swap invoice

### ISSUE THREAD

**Issue by strnly** [btcpayserver/btcpayserver#5966]
Node is CLN on VPS.
Good liquidity. Fat channels with leading nodes. Never had liquidity issues. Well balanced. 

- When trying to pay out a LN to LIQUID swap invoice (generated either from Boltz.exchange UI or AQUA wallet) from that same node but via the RTL UI, it works fine. 
- When trying to pay out the pull payment from BTCPay to Phoenix or WoS, it works fine. 
- BUT... When trying to pay out the pull payment to a LN Invoice (lnbc...) that was generated by Boltz.exchange or AQUA Wallet, from the BTCPay pull payment page, I get the  "Invalid destination or payment method", on the payout page where we Claim the Funds. 

![photo_2024-05-01_14-54-14](https://github.com/btcpayserver/btcpayserver/assets/25166070/fd3b2a5b-12e3-4a27-8bde-c434822c0da7)

It seems BTCPay Server does not recognize this type of LN invoice, despite the node recognizing it from RTL UI and paying to that invoice flawlessly (when bypassing BTCPay UI). 

EDIT = Problem comes Minimum expiry date for Bolt11 invoices. By default, when issuing a refund from an existing invoice, it is set to 30 days (assuming). This can be edited only when creating a pull payment from scratch but not when issuing a refund on an existing invoice. 

![image](https://github.com/btcpayserver/btcpayserver/assets/25166070/e2314a90-8767-44f5-905f-9ccad45b3b2d)

**Comment by kilrau** [comment]
Might our new magic routing hints be the issue? https://docs.boltz.exchange/v/api/magic-routing-hints

**Comment by NicolasDorier** [comment]
I don't think it should be an issue.
Can you share to me the BOLT11 that is causing issues? Which version?

**Comment by strnly** [comment]
Any LN invoice created with Boltz UI or AQUA wallet will appear as invalid for a BTCPay pull payment. I was able to reproduce the issue multiple times. Only when swapping from LN to LIQUID. 

2 test invoices below for 1000 sats each. 


AQUA
lnbc10u1pnr8x44sp54595keqveqrmtmly0healsudgqvd8a40dsfj7jfp5y2sq5ejcczspp5vvmt4h8rvz9dld6z5gkagphxc362dq9vckgqt40n253vpyhwkgdqdpz2djkuepqw3hjqnpdgf2yxgrpv3j8yetnwvxqyp2xqcqz959qxpqysgq93yrxxveh4paq328n3rgu8zkvwfz6qtzn863s69lcc3z4l24vcanyls2y6lr4psgmgf45vphtkmv5wa6l8egxqd2nac97a2xmvw7yxgqg9thy6

Boltz
lnbc10u1pnr8xhksp5y28yways8zh7hgkrwml75nk4ypqvscwv0l4x2nsavty5ug74cv7spp5vsregxqr5k0vulye3066xusa7mqpt3d4kmwranpp3d4ap0pn46pqdpz2djkuepqw3hjqnpdgf2yxgrpv3j8yetnwvxqyp2xqcqz959qxpqysgqnkajku4cfcggflywd8d6td8petshkufuqpnncx55p8h4xfde7tc8fmgp3mpljkr5dtz2whzy3cz9mnyslrfczgvjh2vgnmz6ed5xt6qqc0a0qy

**Comment by NicolasDorier** [comment]
So for now those BOLT11 doesn't appear because they are expired. (We should show better error message...)

**Comment by kilrau** [comment]
Just create a new Lightning to Chain swap via boltz.exchange and paste the lightning invoice into BTCpay @NicolasDorier

**Comment by strnly** [comment]
EDIT = Problem comes Minimum expiry date for Bolt11 invoices. By default, when issuing a refund from an existing invoice, it is set to 30 days (assuming). This can be edited only when creating a pull payment from scratch but not when issuing a refund on an existing invoice.

**Comment by Kukks** [comment]
![msedge_g16euvSkSG](https://github.com/btcpayserver/btcpayserver/assets/1818366/9cfca560-7679-41e3-a05f-f214150353e9)

**Comment by strnly** [comment]
Thanks @Kukks

**Comment by strnly** [comment]
It works now. Was not a bug but a default setting I overlooked combined with a not descriptive enough error message. Thanks a lot guys! 
@NicolasDorier @Kukks

**Comment by strnly** [comment]
@NicolasDorier @Kukks problem is CashApp applies an expiry date and if we put 0 it seems the invoice won't go through in BTCPay. So basically, when we put 0, it should handle any situation, 1. when there is no expiry date and when there is an expiry date, whatever that is. 

We can't know in advance what wallet the user will use to claim the refund.
