### ISSUE TITLE
[Bug]: Liquid wrong derivation path/addresses

### ISSUE THREAD

**Issue by marcocattaneogotam** [btcpayserver/btcpayserver#5967]
### What is your BTCPay version?

I'm running BTCPay Server v1.13.1+ca55e1f30****

### How did you deploy BTCPay Server?

I'm running BTCPay Server on a VPN, enabling LBTC native support.

### What happened?

I've imported a LIQUID hot wallet seedphrase in btcpay but addresses don't match with Green's ones. BTCPay shows a m/84'/1776'/0' derivation path for a native segwit account. Why? Also if I manually change the dev path, addresses don't change. 

Alternatively, importing an XPUB via QR code, I get a list of liquid testnet VT*** addresses on the screen, again why?

### How did you encounter this bug?

1. enabled LBTC support 2. waited for Element core to be synced

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
There isn't any logic or standard for derivation paths. We picked one documented here https://github.com/satoshilabs/slips/blob/master/slip-0044.md

> Also if I manually change the dev path

Yes, it doesn't change anything in the wallet's settings. This is only used for the PSBTs.

If you want your own path, try to import an output descriptors by "importing an existing wallet"., Then "Enter Extended Pubkey".

![image](https://github.com/btcpayserver/btcpayserver/assets/3020646/ae9aa00a-45a5-4116-9521-a54010f65330)

However, I really advise you against doing this for 2 reasons:

1. It's easy to mess up
2. Sharing a wallet with another software will probably cause [gap limit issues](https://docs.btcpayserver.org/FAQ/Wallet/#missing-payments-in-my-software-or-hardware-wallet)
3. Compatibility between the app and BTCPay isn't assured.

**Comment by NicolasDorier** [comment]
Also, I think @Kukks worked on something to make things more compatible with Green. But I don't really know about it.
You may try to ping him on chat.btcpayserver.org.

**Comment by marcocattaneogotam** [comment]
First of all, thank you for your response.

If the derivation path is not the same as Green's and cannot be customized, there is no way to spend the funds received, since BTCPay does not allow sending from the Liquid hot wallet.

**Comment by NicolasDorier** [comment]
@marcocattaneogotam you can through liquid's command line. When you create your hot wallet you need to import the keys in it.

![image](https://github.com/btcpayserver/btcpayserver/assets/3020646/9793e337-d8d8-44be-9a39-c6cb9fd7ea99)
