### ISSUE TITLE
Add Confirmed_balance to api response.

### ISSUE THREAD

**Issue by kemoantemo** [btcpayserver/btcpayserver#597]
I asked about that from the early days of btcpay but i'm asking again why even we don't have such thing in the api response?

It will be useful when accepting payments with any amount by making "consider payment is done even when under..." to 100%

Or don't do this and it will be better ux that if we have blind invoices without amounts specified

**Comment by pavlenex** [comment]
Closing this since we're now discussing the new API features in #1320
