### ISSUE TITLE
[Bug]: Can't import wallet file / Electrum and Sparrow

### ISSUE THREAD

**Issue by Nisaba** [btcpayserver/btcpayserver#5970]
### What is your BTCPay version?

BTCPay 1.13.1

### How did you deploy BTCPay Server?

Docker

### What happened?

I Get this error when I try to import wallet file generated by Electrum or Sparrow :
"Import failed, make sure you import a compatible wallet format"

![image](https://github.com/btcpayserver/btcpayserver/assets/34550856/8b986cad-cc5c-4e87-a5d7-39e72257e487)

### How did you encounter this bug?

Select wallet file (generated by Electrum or Sparrow) then click on Continue

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by nostitos** [comment]
Not sure if it'd make a difference but did you follow the export instruction or just used a wallet file?

**Comment by Nisaba** [comment]
Yes of course, I followed the export instructions

**Comment by ndeet** [comment]
Hey @Nisaba tried to reproduce but it works as expected for me. Did you ensure you exported as electrum compatible json format? Is it a multisig or singlesig? Maybe you can send a test-wallet export?

**Comment by Nisaba** [comment]
The files are not JSON, but encoded files.
So the issue could come from password encryption ?
So maybe a little touch-up on the instructions... Because we could assume that the mention on encrypted protection relates to the backup (which is what I thought) and not initially on the wallet itself. Since wallets are in fact almost always password protected...

**Comment by ndeet** [comment]
We have the instructions right on the import wallet page, it says you need to go to 
File -> Export wallet.. -> Electrum: Export file

It would also work with an additional passphrase afaik. An encrypted wallet backup is something else and would be used to create a hot wallet, the above mentioned import only adds a watch-only wallet. If you want to have a hot wallet you can only do that by entering the seed words.

Can you point out the docs where this is unclear so we can fix it?

**Comment by Nisaba** [comment]
Since the backups generated by Electrum and Sparrow are not json but encoded files, so the issue comes from the password of the wallet.
Just saying that for Electrum, the sentence "(not encrypted with password)" could be understand that the encryption is related to the backup, not the wallet.
And this is not mentioned with Sparrow, whereas the situation is same.

> It would also work with an additional passphrase afaik. An encrypted wallet backup is something else and would be used to create a hot wallet, the above mentioned import only adds a watch-only wallet. If you want to have a hot wallet you can only do that by entering the seed words.

-> Maybe this could be added to avoid misunderstanding...
