### ISSUE TITLE
Equalize card height in POS

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#598]
As seen on https://twitter.com/ideaslikeflames/status/1095019294923112448

**Comment by thedon-chris** [comment]
Something like Bootstrap `card-deck` class may do the trick?

https://getbootstrap.com/docs/4.0/components/card/#card-decks

**Comment by Kukks** [comment]
Yup, should be simple and straight forward. :)

**Comment by mariodian** [comment]
Card deck will break the layout when the cart is open though. When `.row` is used the viewport is relative to the parent element size. When `.card-deck` is used the breakpoints get the size based on the window size instead, not the parent element.

Have a look:

<img width="1436" alt="screen shot 2019-02-25 at 9 19 30 am" src="https://user-images.githubusercontent.com/3636406/53308760-b01b8700-38de-11e9-8e51-b98579ffc535.png">
<img width="1433" alt="screen shot 2019-02-25 at 9 19 38 am" src="https://user-images.githubusercontent.com/3636406/53308761-b3af0e00-38de-11e9-8335-15ba752c094d.png">

There is no easy way to hack it with css.
