### ISSUE TITLE
[Bug][UI]: Invoices could be permanently filtered via SearchTerm stored in cookies

### ISSUE THREAD

**Issue by mizhgan** [btcpayserver/btcpayserver#5984]
### What is your BTCPay version?

I'm running BTCPay Server v1.13.1+ca55e1f30

### How did you deploy BTCPay Server?

I'm running BTCPay Server on dedicated VPS deployed with Docker

### What happened?

If you are filtering out Invoices list by clicking "Invoices" in Requests list - it goes into cookies and Invoices list became filtered forever

### How did you encounter this bug?

1. Install BTCPay server
2. Create store and wallet
3. Make some invoices
4. Make a Payment Request
5. Open that request and try to pay it, that should create invoices with Order Id linked to request - e.g. PAY_REQUEST_ID
6. Observe that now we have different invoices in Invoices list
7. Go to Requests page, click three dots at the end of the request row and click "Invoices"
8. Observe Invoices list which only contain invoices that linked to the request
9. Click anywhere else on the web UI and click again on the Invoices - you should return to the Invoices list which will be still filtered by the request with no obvious way to reset this filter

### What browser do you use?

Chrome 124.0.6367.119

### Additional information

There are three ways to reset filter:
1. LogOut-LogIn
2. Put focus on search input in Invoices page, press Enter, that will bring params into URL, delete SearchTerm content in URL, press Enter to reload page
3. Delete SearchTerm field from cookies

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
@dennisreimann can you look into this one please?
