### ISSUE TITLE
Label clicking seems like it should do something but doesn't

### ISSUE THREAD

**Issue by GeetaCX** [btcpayserver/btcpayserver#5988]
![image](https://github.com/btcpayserver/btcpayserver/assets/167935789/4cc4f056-01ab-4158-9734-ad4313c32906)

When mousing over the label changes colors and when clicking it stay solid. Nothing else happens.

maybe it's meant to select all with the same label? I don't know

**Comment by dennisreimann** [comment]
You can select and remove them (via the delete key) this way.

**Comment by dennisreimann** [comment]
Anything we can still help with here?

**Comment by GeetaCX** [comment]
No that's fine,  https://github.com/btcpayserver/btcpayserver/discussions/5998
