### ISSUE TITLE
Crowdfunding improvements: Stretch Goals

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#599]
- Extend goals feature to show stretch goals( please discuss on UX)

My thoughts on stretch goals:
* Possibly show another column next to goal raised area "% Next Strectch Goal"
* Progress bar grows by relative percentage of stretch goal (e.g. main goal of 100 eur, stretch goal of 10, once raised amount at 100 eur, progress bar changes to 100% at 110 instead, possibly show marker for each goal hit)

**Comment by pavlenex** [comment]
Not many people requested this one and its' been 2 years, closing until we see more requests for strech goals.
