### ISSUE TITLE
[Bug]: PosApp/PrintView - articles with minimum price are treated as fixed price on checkout

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#5995]
### What is your BTCPay version?

BTCPay Server v1.13.1+ca55e1f30 

### How did you deploy BTCPay Server?

Docker

### What happened?

When I scan the QR Code of "Herbal Tea (minimum)" with Breez, I get a input field where I could modify the amount. But when hitting next after changing the amount +1 sats, I get an error: highest amount XYZ sats.

From my understanding the customer should be able to spend the minimum amount or anything above that for the product.

### How did you encounter this bug?

1. scan the qr code of herbal tea minimum
2. incremenet the amount in breez with +1
3. hit next
4. see screenshot (sorry for the german locale)

![WhatsApp Bild 2024-05-21 um 09 38 26_d8247941](https://github.com/btcpayserver/btcpayserver/assets/1374810/be82860c-f4cb-43e1-a9b7-3b02bfcfdb72)

### Relevant log output

```shell
none
```

### What browser do you use?

Firefox on Windows 11

### Additional information

none

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by ndeet** [comment]
Tested static qr of the "Herbal Tea (minimum)" with Phoenix and can confirm the price is fixed.

**Comment by petzsch** [comment]
[decoded](https://lnurl.fiatjaf.com/codec/) the lnurl and got this URL: https://btcpay.host/BTC/UILNURL/pay/app/2sZfhihthmnaGAUbtu84xCprDPcj/herbal-tea

this gives me the following JSON:

```json
{
   "callback":"https://btcpay.host/BTC/UILNURL/pay/i/4zx8fA99kyspYfZi87pqFj",
   "metadata":"[[\"text/plain\",\"Paid to petzsch's kitty (Order ID: JYyciymvLP9wZnKF6f96Vk)\"]]",
   "tag":"payRequest",
   "minSendable":2757000,
   "maxSendable":2757000,
   "commentAllowed":0,
   "nostrPubkey":"cd0ed24fdaf5efed5f4cd80fd36c0734ae32670bcbe8fdd5ddbad272a063d305",
   "allowsNostr":true
}
```

Not sure what's the deal with all the nostr stuff (I have the plugin enabled but wouldn't expect it here).
maxSendable should be a higher or unlimited value here, I guess.
