### ISSUE TITLE
Network cost configurable

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#6]
Network cost is currently hard coded at .0001 BTC

This should be configurable to each store under the webui settings page, with the ability to turn off as well if it does not make sense for the business. 

Also, currently with each payment additional network cost is added. This is by design, however perhaps this should also be an option.

**Comment by NicolasDorier** [comment]
Done https://github.com/btcpayserver/btcpayserver/commit/5f8407b4b1db30cc0208661506ad8d84aeb6abec
