### ISSUE TITLE
Compilation error "csc.dll" exited with code 134 on ARM

### ISSUE THREAD

**Issue by enorrmann** [btcpayserver/btcpayserver#600]
uname -a 
Linux odroid 4.14.5-92 #1 SMP PREEMPT Mon Dec 11 15:48:15 UTC 2017 armv7l armv7l armv7l GNU/Linux
dotnet --version 
2.1.504

./build.sh output [HERE](https://www.dropbox.com/s/8diu0987jykbeyg/compile.log?dl=1)

**Comment by pavlenex** [comment]
Oops seems this issue went under the radar.
@enorrmann you resolved it or?

**Comment by enorrmann** [comment]
> @enorrmann you resolved it or?

still no luck

**Comment by NicolasDorier** [comment]
This is weird. Probably a bug of the SDK. I advise you to use the docker deploy for raspberry though.

Can you try with .NET 2.2 SDK?

**Comment by enorrmann** [comment]
> Can you try with .NET 2.2 SDK?

error persists with dotnet version
2.2.104

**Comment by NicolasDorier** [comment]
`dotnet build /bl -c Release BTCPayServer/BTCPayServer.csproj` and share the msbuild.binlog file?

**Comment by enorrmann** [comment]
[msbuild.binlog](https://www.dropbox.com/s/4ic7z1j7qnh72iv/msbuild.binlog?dl=1)
for dotnet 2.2.104

**Comment by NicolasDorier** [comment]
I reported your error on another repo, please provide there your `dotnet --version`

**Comment by NicolasDorier** [comment]
If you don't mind building on the odroid, to play with btcpay, you can use the btcpayserver-docker deployment instead.

**Comment by enorrmann** [comment]
@NicolasDorier I think you closed the wrong issue .. this one

**Comment by pavlenex** [comment]
@enorrmann is this now solved? It seems all related issues to it have been closed and we moved to a different SDK quite a while ago.

**Comment by enorrmann** [comment]
I can't say.. I'm not using Odroid anymore

**Comment by pavlenex** [comment]
Ehh, okay I'll close this one (I think it should be fixed anyway) and re-open if anybody else complains, thanks for a quick reply Norm!
