### ISSUE TITLE
[Bug]: Payout broadcast a transaction but do not change to "In Progress" status when "Subtract fees from amount" is active

### ISSUE THREAD

**Issue by 021-projects** [btcpayserver/btcpayserver#6007]
### What is your BTCPay version?

v1.13.1

### How did you deploy BTCPay Server?

Docker

### What happened?

When I approve the payout and the transaction is sent, the transaction is created, it is visible in BTCPay with the payout label, but Payout itself does not go into the status "In Progress" and is not associated with the sent transaction.

### How did you encounter this bug?

1. Create a payout via [Greenfield API](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Payouts_CreatePayoutThroughStore)
2. Go to "Awaiting Approval" payouts
3. Click "Approve & Send"
4. Check "Subtract fees from amount"
5. Broadcast a transaction 

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
The reason is that we are checking for the exact amount to be sent to the destination.

**Comment by 021-projects** [comment]
> The reason is that we are checking for the exact amount to be sent to the destination.

But it's still a bug / inappropriate behavior because the transaction related to the payout is sent and the checkbox is part of the interface, there is no warning anywhere that this is how it works and in the end it looks like the payout is not paid, although in fact it was paid. From a UI point of view this does not make sense, because you send a transaction related to the payout, use the built-in interface and in the end the payout is not processed, which can confuse the end user and force them to send the payment again. It turns out that now, as a result of sending a transaction from the payout interface with this checkbox, the user does not see any response - this is a confusing behavior, especially when you have a lot of payout requests

**Comment by NicolasDorier** [comment]
I kind of agree that this is a bad UX. I will put a note in the discussion there, as we want to rework this area soon.

https://github.com/btcpayserver/btcpayserver/discussions/6403
