### ISSUE TITLE
[Bug]: kraken(XMR_BTC) is hardcoded, regardless of Preferred Price Source

### ISSUE THREAD

**Issue by d2ro** [btcpayserver/btcpayserver#6025]
### What is your BTCPay version?

I'm running BTCPay Server v1.13.1+ca55e1f30 (Altcoins)

### How did you deploy BTCPay Server?

btcpayserver-docker

### What happened?

The XMR_EUR price calculation uses `kraken(XMR_BTC)` even if the preferred price source is not Kraken:

![1regular](https://github.com/btcpayserver/btcpayserver/assets/78594032/5fa1f465-a197-430b-9f8a-7d462ef09ca5)

A workaround is to use advanced rate rule scripting:

![3adv](https://github.com/btcpayserver/btcpayserver/assets/78594032/7a2630e6-8ce4-49d8-a766-63f9024e70ab)

According to the other bug reports, other Monero pairs (such as XMR_USD) may also be affected.

### How did you encounter this bug?

The Kraken price ticker had issues yesterday. See issues #4027 and #6022. Switching to a different price source fixed the issue, except for Monero, whose price calculation still relied on Kraken.

### Additional information

Thank you so much for developing BTCPay server <3

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

_Edit: Better advanced rule scripting example_

**Comment by pavlenex** [comment]
I think this is expected and the way integration works, perhaps @sethforprivacy knows more.
