### ISSUE TITLE
Notification when an invoice was created

### ISSUE THREAD

**Issue by andres-pinilla** [btcpayserver/btcpayserver#603]
It would be excellent a notification when an invoice is created.

**Comment by NicolasDorier** [comment]
It is already the case if you set extendedNotification

**Comment by pavlenex** [comment]
Hey @andres-pinilla does the above answer your question or you need additional help?
I'll mark this issue as closing, but will give you a time to give a bit more context and clarification if it's not what you wanted.

**Comment by andres-pinilla** [comment]
Hi, thanks @pavlenex for your response. I would like the possibility that BTCPay send an email when someone generates a new invoice so that the store is alert to the purchase.

**Comment by pavlenex** [comment]
How you use BTCPay? What feature of btcpay are you using that needs e-mail notification? Please be a bit more clear.

As Nicolas said, you can already do that [via the API.](https://bitpay.com/api#resource-Invoices). Otherwise, if you use CMS software like WooCommerce, it does that for you already.

**Comment by NicolasDorier** [comment]
@andres-pinilla you can already receive a mail for notifications normally (@Kukks did it)

**Comment by andres-pinilla** [comment]
@NicolasDorier @Kukks @pavlenex 

Guys, you are the best. In the latest versions of BTCP, I receive an email from WooCommerce as soon as a customer makes a payment and the order is marked as pending at WooCoomerce. Now I have a small problem, I am not receiving an email when the payment is marked as confirmed in BTCPay (depending on the configuration of confirmations configured in the plugin or in BTCPay) and the order is marked as in process in WooCommerce.

Ideal would be to receive an email as soon as the customer makes a payment and the order is marked pending in WooCommerce and receive another email when the order is confirmed (in my case with 2 confirmations of the network) and the order changes to processing in WooCommerce.

Thanks,

Andrés Pinilla
CEO Compudemano Colombia
Apple Authorized Reseller & Service Provider
www.compudemano.com

**Comment by andres-pinilla** [comment]
@NicolasDorier @Kukks @pavlenex 

Complementing the above, I must be aware that the order has 2 confirmations to send the purchase which can cause a delay and poor customer service, instead it would be easier, if I receive an email as soon as the payment has the necessary confirmations and be marked as in process in WooCommerce.

Thanks again,

Andrés Pinilla
CEO Compudemano Colombia
Apple Authorized Reseller & Service Provider
www.compudemano.com

**Comment by pavlenex** [comment]
Check this https://docs.btcpayserver.org/integrations/woocommerce#btcpay-order-statuses 

You have to do a research on how to send an [email for particular order](https://www.cloudways.com/blog/how-to-customize-woocommerce-order-emails/) status in Woo.

**Comment by andres-pinilla** [comment]
Thanks @pavlenex for your response.

I used to receive an email when the payment was confirmed on the network (according to the configuration made in BTCPay or in the WooCommerce plugin) and the order changed to processing in WooCommerce ... now I am receiving an email as soon as a payment is made but not when it is confirmed in BTCPay and when the status in WooCommerce changes to processed.

**Comment by pavlenex** [comment]
In that case, you just have to configure the plugin statuses. 

I don't know your store setup, but it should be like this, leave the blank if you don't want to send email for paid, but for confirmed put `processing`. Save settings. 

![screen shot 2019-03-06 at 21 38 14](https://user-images.githubusercontent.com/36959754/53912027-4aef3080-4058-11e9-818e-76d0047f8744.png)

**Comment by andres-pinilla** [comment]
This is my configuration and it does not work:

https://www.dropbox.com/s/h018y9uivejkmdz/Captura%20de%20pantalla%202019-03-06%2015.42.08.png?dl=0

**Comment by pavlenex** [comment]
Yeah, read the docs on order statuses, then configure emails in WooCommerce as I said earlier.

**Comment by andres-pinilla** [comment]
Ok, I'll do tests and I'll keep you informed.

**Comment by pavlenex** [comment]
If you really want to send email for both `confirmed` and `paid` then you need `processando` and `processando2` where processando2 is [custom status ](https://businessbloomer.com/woocommerce-set-custom-order-status-for-new-orders/)that you need to create in WooCommerce and then find a way to trigger email for [custom order status](https://businessbloomer.com/woocommerce-send-custom-email/) `processando2`.

**Comment by andres-pinilla** [comment]
I think this configuration could be more useful to me:

https://www.dropbox.com/s/aadgzn7lb8ad4su/Captura%20de%20pantalla%202019-03-06%2016.02.50.png?dl=0

**Comment by andres-pinilla** [comment]
Better like this:

https://www.dropbox.com/s/akqtc3wmfssbno3/Captura%20de%20pantalla%202019-03-06%2016.09.51.png?dl=0
