### ISSUE TITLE
[Bug]: Can not delete a Webhook.

### ISSUE THREAD

**Issue by jpdelon** [btcpayserver/btcpayserver#6034]
### What is your BTCPay version?

© BTCPay Server v1.13.1+ca55e1f30 

### How did you deploy BTCPay Server?
We use voltageapp.io

### What happened?

When we try to delete a webhook which is not working we get the following error after typing "Delete"

504 Gateway Time-out
nginx

### How did you encounter this bug?

I clicked on the Menu Webhook.
Then I clicked on DELETE to delete the Webhook.
A Pop up came up and I had to write DELETE again and confirm it.
I confirmed it and the website started loading.
After that I received 

504 Gateway Time-out
nginx

### Relevant log output

```shell
I don't seem to find it. I am logged in at BTCpay with "Owner" Role.
```

### What browser do you use?

Firefox.126.0.1 (64-bit)

### Additional information

![26](https://github.com/btcpayserver/btcpayserver/assets/126243877/03ab90ab-e000-4905-9459-255ea750a3cb)
![59](https://github.com/btcpayserver/btcpayserver/assets/126243877/198b35f4-1968-47ca-97e0-0d9dc92fe9e7)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Hi @jpdelon Do you still have problems with this? I cannot replicate it with 1.13.2

<img width="1059" alt="Screenshot 2024-07-03 at 10 50 13" src="https://github.com/btcpayserver/btcpayserver/assets/36959754/012c3e4f-7751-4646-9afa-2ac571dc8174">

**Comment by jpdelon** [comment]
Yeah I am still not able to delete it. 
I am getting the error:

504 Gateway Time-out
nginx
