### ISSUE TITLE
[Coinjoin] Trailing slash is required in coordinator info to connect

### ISSUE THREAD

**Issue by yahiheb** [btcpayserver/btcpayserver#6039]
I'm not sure this is the right place for this issue. Feel free to close if it's not.

This was first reported in Wasabi https://github.com/WalletWasabi/WalletWasabi/issues/13122 but apparently it is a problem on btcpayserver: https://github.com/WalletWasabi/WalletWasabi/pull/13146#discussion_r1627421410

When you set your coordinator in Wasabi to `https://btcpay.kruw.io/plugins/wabisabi-coordinator/` it works, but if you exclude the slash at the end `https://btcpay.kruw.io/plugins/wabisabi-coordinator` it does not work.

**Comment by pavlenex** [comment]
Hey, No, this has nothing to do with btcpayserver, this is an external plugin. Probably better to post it here https://github.com/Kukks/BTCPayServerPlugins
