### ISSUE TITLE
crowdfunding not fetching data from backend. all invoices are there ?? .58

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver#604]
Any idea of this Problem @Kukks 

these guys @soumitra.mandhata not getting data from backend 
https://btcpayjungle.com/apps/2PNvnN4u9rFyQQsshJtxoAUDrf2J/crowdfund 

I`m running BTCPayJungle v1.0.3.58

**Comment by pavlenex** [comment]
Alright, to clarify a bit, after the .55 update, crowdfunding progress bar does not fetch any invoices from the store, it just shows 0.
![screen shot 2019-02-21 at 18 08 33](https://user-images.githubusercontent.com/36959754/53187563-b8847100-3603-11e9-915c-3e56bf740c6f.png)

**Comment by Eskyee** [comment]
<img width="1140" alt="screenshot 2019-02-21 at 17 10 28" src="https://user-images.githubusercontent.com/30862925/53187783-c7ffbc00-35fb-11e9-9e13-1fab5302f964.png">

**Comment by Eskyee** [comment]
issue fixed by @Kukks
