### ISSUE TITLE
[Bug]: Incorrect billing

### ISSUE THREAD

**Issue by maxg555865** [btcpayserver/btcpayserver#6052]
### What is your BTCPay version?

BTCPay Server v1.13.2+5884850e2 (Altcoins)

### How did you deploy BTCPay Server?

I'm running BTCpay server on VPS

### What happened?

Hello everyone!
I encountered a problem with invoicing in the BTCPay server.
The site is connected to the BTCPay server via API.
For example, a store issues an invoice in BTCPay for payment of 13.65 USD, that is 0.17745000 LTC.
But on the payment page the amount changes and it turns out to be 0.177 USD, which is 0.00219827 LTC.
The same problem exists with BTC.
What could this be connected with? Where do you need to configure what? 
I think it's a matter of Rate Rules. But I don’t know how to configure it correctly.

### How did you encounter this bug?

An error occurs when issuing invoices from a third-party site to the BTCPay server.

### What browser do you use?

Chrome 125.0.6422.142

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Hi @maxg555865 did you figure this one yet? It's most likely that you've added some custom scripting in advanced rate rules or selected a rate source that is inaccurate. So three things:
1. Are you still facing this issue?
2. What's your rate source provider
3. Screenshot your advanced rate section so we can see all options


This is very unlikely a bug, more of a misconfiguration on your end.
