### ISSUE TITLE
[Bug]: Reporting RAW Data View - 2 issues

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#6065]
### What is your BTCPay version?

BTCPay Server v1.13.3+9d84ec4aa 

### How did you deploy BTCPay Server?

Docker

### What happened?

I've clicked on the Reporting link (left menu) and got this:
![grafik](https://github.com/btcpayserver/btcpayserver/assets/1374810/47257f67-d282-482b-890f-eecb8ecc6b8d)

Here are the issues I see:
- default sorting: by Payment Type and then Date -> should be just Date I think
- the shortend label for "BTC-LightningNetwork" is showing "BTC-LightningNe … ightningNetwork" which is kind of unexpected

### How did you encounter this bug?

see above

### Relevant log output

```shell
none
```

### What browser do you use?

Firefox 127.0.1 on Win11

### Additional information

none

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
I removed the text-truncate column from Payment Id, and fixed the bug on sorting.

@dennisreimann will also make a PR for fixing the `text-truncate` components.
