### ISSUE TITLE
[Bug]: PoS dashboard, top selling items "view all" link broken

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#6068]
### What is your BTCPay version?

v1.13.3

### How did you deploy BTCPay Server?

docker

### What happened?

On the PoS dashboard on the "top items" widget you have a "view all" link, that link brings you to PoS settings. Expected to see a more detailed list of top items.

![image](https://github.com/btcpayserver/btcpayserver/assets/1136761/6241ebf6-f534-4131-b3b6-406a191fc2dc)

### How did you encounter this bug?

- Open PoS app with items and some sales.
- On "top items" widget, click "View All"

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by DatOneJuice** [comment]
I still have no idea what I'm doing. I need some serious help over here.

**Comment by dstrukt** [comment]
Ahh yeah, this is a valid issue - think we could go in one of two directions:

- Remove the `View All` link here to remove the expectation to see more
- Add a modal (on click) that displays all products & the sale numbers (in a similar key -> pair fashion)

**Comment by dstrukt** [comment]
Discussed on design call:

Let's just go with Option 1, removing the View All link. This should be done on the Crowdfund widget as well.
