### ISSUE TITLE
[Bug]: Printable LNURL in POS app does not work with LNDhub

### ISSUE THREAD

**Issue by iBobik** [btcpayserver/btcpayserver#6070]
### What is your BTCPay version?

BTCPay Server v1.13.3+9d84ec4aa

### How did you deploy BTCPay Server?

Docker

### What happened?

When LN backend is LNDhub then printable QR codes in POS app stopped working.
```
 {"status":"ERROR","reason":"Lightning node could not generate invoice with description hash: DescriptionHash ('h' field) is not specified in the BOLT11 object"}
```

 Keypad or cart POS or manually created invoices works. When used the same printable POS with LNbank it worked.

### How did you encounter this bug?

1. Switched store LN to the LNDhub wallet
2. Used POS app to create printable QR code
3. Tried to pay it

### Relevant log output

```shell
No errors in btcpay nor lndhub containers.
```

### What browser do you use?

Breez, Phoenix, WoS

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by petzsch** [comment]
Is the used LNDhub wallet by chance using LNbits? They seem to have a bug with 0 amount invoices, see:
https://github.com/lnbits/lnbits/issues/2207 and https://github.com/lnbits/lndhub/issues/25

**Comment by iBobik** [comment]
@petzsch No, [LNDhub is connected directly to the LND](https://github.com/btcpayserver/btcpayserver-docker/blob/master/docker-compose-generator/docker-fragments/opt-add-bluewallet-lndhub.yml) and amount was not zero.

**Comment by dennisreimann** [comment]
It looks like the [LNDhub](https://github.com/BlueWallet/LndHub) and [its Docker image](https://hub.docker.com/r/bluewalletorganization/lndhub/tags) aren't maintained anymore and simply lack support for the description hash. 

Can you try this with another LNDhub-compatible backend like Alby? For the BlueWallet LNDhub backend there's nothing we can do about this I guess.

**Comment by iBobik** [comment]
Aha, haven't noticed it is not active project.

About Alby, I read it is just browser extension, not an account manager between BTCPay and LND like LNDHub. LN bank plugin was discontinued too and LNbits does not have good security culture too.

Is there another solution?

**Comment by dennisreimann** [comment]
Alby is not just a browser extension. They offer LNDhub compatible API access as well for their user accounts.

**Comment by iBobik** [comment]
Aha, thank you.getAlby/lndhub.go: Accounting wrapper for the Lightning Network. It provides separate accounts for end-users. (LndHub compatible API written in Go)github.com3. 7. 2024 v 23:28, d11n ***@***.***>:﻿
Alby is not just a browser extension. They offer LNDhub compatible API access as well for their user accounts.

**Comment by regressivetassive** [comment]
I've been exploring different options for managing my BTC transactions and came across an interesting alternative: flash BTC software. I've found that using a reliable flash BTC software can provide a more efficient and secure way to handle transactions. If anyone is interested in learning more, look at that repository (https://github.com/CrypToprexofficial/Free-flash-btc-sender) that provides more information and resources on the topic. Please keep in mind that it's essential to do your own research and due diligence when exploring new tools and methods.

**Comment by pavlenex** [comment]
@dennisreimann I see you referenced this issue a couple of times in the past, were we able to tackle it?

**Comment by dennisreimann** [comment]
This is nothing we can do something about. See https://github.com/btcpayserver/btcpayserver/issues/6070#issuecomment-2205892096

**Comment by NicolasDorier** [comment]
Also, you can now connect Alby with btcpay through the Nostr plugin (via NwC). This works just fine.

**Comment by tlindi** [comment]
Paying to QR Code 
-created by BTCPay Server v2.1.6+57d42ab10 which is using Lightning connection to 
-LNbits v1.2.1 extension 
-LNDhub v1.0.1
- works!
