### ISSUE TITLE
BTCPay scammed me

### ISSUE THREAD

**Issue by jordix96** [btcpayserver/btcpayserver#6073]
I used BTCPay to purchase a year long MovieBoxPro subscription on June 27 at around 2AM, it's now been well over 24 hours and my money is gone of course, but I still do not have the subscription I paid for. Did I get scammed? Who can I contact to get this fixed?

**Comment by pavlenex** [comment]
BTCPay is just a software, contact your merchant https://docs.btcpayserver.org/FAQ/General/#what-if-i-have-a-problem-with-a-paid-invoice
