### ISSUE TITLE
[Bug]: Can't save email settings on store level

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#6076]
### What is your BTCPay version?

v1.13.3

### How did you deploy BTCPay Server?

docker

### What happened?

When you do NOT have email setup on server settings BUT you want to setup email at store settings it will fail to save.

I suspect this has to do with the toggle that appears once you have set up the server email you can toggle so you can save also different settings on the store level. But maybe something else

### How did you encounter this bug?

- do not SETUP email in server settings
- try to setup email in the store settings 
- fails to save, gives a 302 http response code

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
> I suspect this has to do with the toggle that appears once you have set up the server email you can toggle so you can save also different settings on the store level.

💯🎯
