### ISSUE TITLE
Crofunding - custom price for the perk - mandatory fields

### ISSUE THREAD

**Issue by 2pac1** [btcpayserver/btcpayserver#608]
Hello guys,
<img width="519" alt="screenshot 2019-02-22 at 08 51 34" src="https://user-images.githubusercontent.com/35058480/53227648-2621b300-367f-11e9-8da1-e731e49fb4ab.png">

When the price is not entered, field should be selected and should be in red. It is not all clear that you are here basically specifying minimum amount but later on people have the chance to enter custom amount.
Can we sort this out?
Tnx

**Comment by 2pac1** [comment]
Same goes for all the fields..

**Comment by Eskyee** [comment]
this would make the UX more clear with less mistakes from noobs, I agree

**Comment by Kukks** [comment]
We will most likely rewrite this part of the UI in Vue soon

**Comment by pavlenex** [comment]
#1544
