### ISSUE TITLE
Update CLN for 1.13.4

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#6090]
CLN needs to be updated for the upcoming minor 1.13.4 release. This is the issue for docker repo but opening it in the main due to convenience of putting it on a project board.

Afaik Kukks was working on doing it for 1.13.3 but it's unclear if it happened.

**Comment by Kukks** [comment]
There is a pr in the docker repo. It is tested in both the lightning repo and the btcpay repo. We should test on an instance first but with the current tests done it is expected to work

**Comment by 2urkivip** [comment]
> CLN needs to be updated for the upcoming minor 1.13.4 release. This is the issue for docker repo but opening it in the main due to convenience of putting it on a project board.
> 
> 
> 
> Afaik Kukks was working on doing it for 1.13.3 but it's unclear if it happened.
