### ISSUE TITLE
[Bug]: Shopify Integration allows user to generate invoice after order is cancelled

### ISSUE THREAD

**Issue by beeforbacon** [btcpayserver/btcpayserver#6104]
BTCPay version 1.13.3
Running BTCPayServer from Voltage service. 

When a Shopify cancel timer hits zero, the button to generate an invoice still allows an invoice to be generated. 

1. Cancelled Shopify Order
2. Clicked PayWith BTCPay button on the Shopify checkout page. The invoice was generated even though the order was cancelled. 
 

This issue is written on behalf of a Voltage user from uncute.com having issues with the shopify checkout. 
Worked with @pavlenex and customer on July 12, 2024 conference call.

**Comment by pavlenex** [comment]
Direct Feedback from  the user:

> Button is being added to order status page with option to pay, even if order has been cancelled in shopify. Script should check to see if order is cancelled before allowing payment (visible in the html).
