### ISSUE TITLE
other denomination units for products like mBTC, bits or satoshi in POS

### ISSUE THREAD

**Issue by talentpierre** [btcpayserver/btcpayserver#611]
Because issue #250 refers to the customer, i opened a new one for merchants.

it would be great for a merchant to choose the denominations of bitcoin like mBTC, bits or satoshi for his products. products with a price less than one cent are difficult to read in bitcoin in pos of btcpay and therefore not practical to use.

**Comment by rockstardev** [comment]
Hey talentpierre... per detailed discussion we had, we agreed on doing BTC only for on-chain transactions and providing Satoshis as option for off-chain - that's what we'll stick with for now.
