### ISSUE TITLE
[i18n] Translate payment requests

### ISSUE THREAD

**Issue by coinlighter** [btcpayserver/btcpayserver#6115]
### What is your BTCPay version?

I'm running BTCPay v1.13.5

### How did you deploy BTCPay Server?

docker

### What happened?

Payment-Request display only in english even if store's default language is different. 

### How did you encounter this bug?

How to repeat:

Set Store settings to a non english default language:
-> Checkout Appearance
-> Default Language on Checkout
-> select language other than english

Create a payment request and notice the view is not translated and there is no translation link.
Invoice generated from the payment request does display the store's default language and allows translation.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
This is not a bug, the checkout page transation is only that - checkout page translation, it doesn't affect any other element. We're working on #5662 which will introduce translations  for the rest, but that one is 2 months away for now at least.
