### ISSUE TITLE
[Bug]: 404 on settled free invoice checkoutLink url

### ISSUE THREAD

**Issue by robwoodgate** [btcpayserver/btcpayserver#6123]
### What is your BTCPay version?

 v1.13.5+30d91d0bd

### How did you deploy BTCPay Server?

Docker container

### What happened?

Created invoice via Greenfield API with 0 amount (ie Free). It settles immediately, as expected, however the checkoutLink of the invoice then goes to a 404 page. It should, if settled, redirect to the receipt page like normal settled invoices do.

(Note: This came up because I'm building an integration in a system that allows recurring subscriptions - so each "rebill" is a new invoice raised - and some subscriptions may have a 0 first period (aka free trial)).

### How did you encounter this bug?

1. Create invoice via Greenfield API using 0 as amount (eg a "Free Trial")
2. Let it settle
3. Visit CheckoutLink for that invoice - a 404 is returned, there is no redirect to the receipt page

### Relevant log output

```shell
Output from invoice->getData()

Array ( [id] = MzfTcuNBkFfsBPaX7KXq8i [storeId] = 6L8ts1kKHp5C755uUjSZnXoJJVmNtSxhjQd3tjhQtWRL [amount] = 0.0 [checkoutLink] = https://[*******redacted****]/i/MzfTcuNBkFfsBPaX7KXq8i [status] = New [additionalStatus] = None [monitoringExpiration] = 1722091924 [expirationTime] = 1722005524 [createdTime] = 1722004624 [availableStatusesForManualMarking] = Array ( [0] = Settled [1] = Invalid ) [archived] = [type] = Standard [currency] = USD [metadata] = Array ( [orderUrl] = [*******redacted****] [buyerName] = Rob Woodgate [buyerCountry] = GB [receiptData] = Array ( [Cart] = Array ( [Test Free Trial] = $0.00 x 1 = $0.00 ) ) [itemDesc] = Test Free Trial [physical] = [taxIncluded] = 0 [orderId] = [*******redacted****] [buyerEmail] = [*******redacted****] ) [checkout] = Array ( [speedPolicy] = HighSpeed [paymentMethods] = Array ( ) [defaultPaymentMethod] = BTC [expirationMinutes] = 15 [monitoringMinutes] = 1440 [paymentTolerance] = 0 [redirectURL] = https://[*******redacted****] [redirectAutomatically] = 1 [requiresRefundEmail] = [defaultLanguage] = [checkoutType] = [lazyPaymentMethods] = ) [receipt] = Array ( [enabled] = [showQR] = [showPayments] = ) )
```

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
@ndeet can you replicate this one?

**Comment by ndeet** [comment]
@pavlenex can confirm this seems to be a bug, the receipt page works but not the invoice page:
https://testnet.demo.btcpay.tech/i/AC61GmkMJTEoXuBBmm3w69/receipt
https://testnet.demo.btcpay.tech/i/AC61GmkMJTEoXuBBmm3w69

@robwoodgate thanks for reporting :+1:
