### ISSUE TITLE
[Bug]: Invoice filter showing expired too

### ISSUE THREAD

**Issue by bitcoinbrisbane** [btcpayserver/btcpayserver#6124]
### What is your BTCPay version?

v1.13.3+cbeb32808a119a4f458e21e1d0d1e96fc8a3270b 

### How did you deploy BTCPay Server?

Manually

### What happened?

Filtering invoices by status, shows expired too.

![image](https://github.com/user-attachments/assets/53284897-667a-4133-973a-05303809f07f)

### How did you encounter this bug?

1. go to invoices
2. select expired (correct behaviour)
3. select settled, remove expired

### What browser do you use?

Chrome

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Can you check if there isn't any other filter active and whether or not it persists in v1.13.5? I'm not able to replicate this with the current version.

![Peek 2024-07-27 14-33](https://github.com/user-attachments/assets/bef731da-fecf-4e14-b978-406e13ade9f3)

**Comment by ndeet** [comment]
Also tested with 1.13.5 and it works as expected for me

**Comment by dennisreimann** [comment]
@bitcoinbrisbane Please reopen if this is still an issue for you after upgrading.
