### ISSUE TITLE
[Bug]: No payment button on payment requests

### ISSUE THREAD

**Issue by jacobburrell** [btcpayserver/btcpayserver#6133]
### What is your BTCPay version?

© BTCPay Server v1.13.5+30d91d0bd

### How did you deploy BTCPay Server?

Docker

### What happened?

Any payment request made lacks a button to pay the payment request.

### How did you encounter this bug?

1. Made payment request
2. Open payment request

### What browser do you use?

Chrome 127.0.6533.88 (Official Build) (x86_64) 

### Additional information

<img width="1183" alt="image" src="https://github.com/user-attachments/assets/47b46f00-67d8-4ace-b97e-384c8d3c9239">

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Can you check if there's a JavaScript error in the browser console?

**Comment by pavlenex** [comment]
@jacobburrell Can you check what @dennisreimann mentioned or share a live link with u. I cannot replicate your issue.

**Comment by jacobburrell** [comment]
I recognize I should have taken down more info for reproducing the issue.

After restarting BTCPayServer I can't seem to replicate it. No changes to Chrome beyond regular updates.

I did recall there was the common issue with [NBXplorer is synchronizing](https://docs.btcpayserver.org/FAQ/General/#stuck-synching-nbxplorer-is-synchronizing-) but that shouldn't have affected it.

Will try a few things to try to replicate, otherwise will close out.
