### ISSUE TITLE
Removing Strike as BTCPay Server Foundation supporter

### ISSUE THREAD

**Issue by rockstardev** [btcpayserver/btcpayserver#6143]
It needs to be done across repositories:

- This repo
- https://github.com/btcpayserver/blog
- https://github.com/btcpayserver/btcpayserver-doc
- https://github.com/btcpayserver/foundation.btcpayserver.org

**Comment by siwatanejo** [comment]
So as soon as they publicize the Strike plugin they get out? just curious what was the rationale :)
