### ISSUE TITLE
Add hover to easier check total sales per day

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#6161]
Right now we don't show daily number of sales, I don't know what's the best way to expose them, but we should do that at least on mouse hover, which we currently don't.

<img width="592" alt="Screenshot 2024-08-24 at 05 59 11" src="https://github.com/user-attachments/assets/899dfb72-2f6f-4be8-bb52-4b203a7369eb">

**Comment by dstrukt** [comment]
huge ACK - was going to make an issue similar to this as i've been playing with this feature on the app - should work on tap for mobile too

**Comment by Toyin5** [comment]
Can I get assigned to this?
