### ISSUE TITLE
Feature req: Pay BOLT11 invoices via BTCPay Server API

### ISSUE THREAD

**Issue by baebb** [btcpayserver/btcpayserver#618]
Hi all,

With LN being _so hot right now_, one feature that would be super useful to me as a merchant is the ability to pay BOLT11 invoices via the BTCPay Server API.  

Not the whole lncli/lightning-cli API is needed. Just the ability to:
**1) Initiate payment of an lnbc invoice** 
and
**2) Check the status of that payment.**

How I imagine it would work:
When initiating a withdrawal, the initiate endpoint would need to create and return a withdrawal ID. The check status endpoint, when provided the withdrawal ID, would then return a `success`, `failure`, or `processing` status of the withdrawal.

For reference see the [OpenNode docs](https://docs.opennode.co/) under Withdrawals Endpoints => Initiate a withdrawal & Withdrawal info

> But why don't you just SSH in and run the commands yourself?

I'd like to be able to this programmatically and save myself from making a separate webserver + authentication on the same VM as my BTCPay Server instance.

**Comment by NicolasDorier** [comment]
Why not using the embedded Ride the Lightning or Spark wallet?

**Comment by justrossthings** [comment]
@NicolasDorier for my user case I need to programmatically make payouts to users

**Comment by Kukks** [comment]
There is still no API for most operations in any case. You need to wait
till we plan it all

**Comment by lippoliv** [comment]
👍 

This is defenetly needed. I will file an feature proposal soon. This will need the described functinality too.

**Comment by pavlenex** [comment]
Closing this one as all API discussion is now happening in #1320. So if you guys still have any specific requests, please let us know there.
