### ISSUE TITLE
Consider changing the `C` (Delete) icon as it's not clear to merchants globally, change to ERASE ❌or Trash🗑 icon 

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#6195]
Really interesting feedback, cc @dstrukt 

> the brazilian users aren't familiar with the C symbol, must be an ERASE ❌or Trash🗑 icon

**Comment by dstrukt** [comment]
Could be a case where depending on location or language, we might show a different asset.

Alternatively, we adopt something similar to the iOS/Android keyboard for all cases.

<img width="82" alt="Screen Shot 2024-09-06 at 11 12 11 AM" src="https://github.com/user-attachments/assets/a2fc681f-d7c4-4ff5-a252-08ddccb36de5">

Will do a bit more research to see how it's handled!

**Comment by pavlenex** [comment]
> Could be a case where depending on location or language, we might show a different asset

I am not convinced such complexity is needed for this little improvement. Let's do a bit more research and have things outlined on the board, I do think X or trash/delete can icons could be more universal than C (clear).

**Comment by dstrukt** [comment]
Think this could work, adjust the `x` and `+` icons as i wasn't happy with them, will export for @dennisreimann 

<img width="807" alt="Screen Shot 2024-10-25 at 4 36 01 PM" src="https://github.com/user-attachments/assets/3bd6769c-df84-4f47-9fe1-2eff3432e03a">
