### ISSUE TITLE
Adding Unbank as BTCPay Server Foundation supporter

### ISSUE THREAD

**Issue by rockstardev** [btcpayserver/btcpayserver#6196]
Tracking all changes across repositories:

- This repository
- https://github.com/btcpayserver/blog
- https://github.com/btcpayserver/btcpayserver-doc
- https://github.com/btcpayserver/foundation.btcpayserver.org

**Comment by dstrukt** [comment]
Ahh nice! 

I've seen, but not used, a few of these ATMs in my travels, will need to change that!

**Comment by dstrukt** [comment]
Might try to tackle if i get a moment, but the logo file for anyone who does:

![unbank-logo](https://github.com/user-attachments/assets/c55364c1-f6ad-4ea3-9032-b7aedf37d91c)

**Comment by rockstardev** [comment]
@dstrukt that file from their website is a PNG is disguise, I got us raw SVG here: https://github.com/btcpayserver/foundation.btcpayserver.org/blob/master/assets/unbank.svg

Included it in all the different places and linked, so this issue is resolved and can be closed.

**Comment by dstrukt** [comment]
Oh, damn, great catch - thanks for picking this up!
