### ISSUE TITLE
Feature request: Changelly integration

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#62]
A followup of #17, I'd like to allow changelly integration.
What is missing for it from them? @lepipele

**Comment by astupidmoose** [comment]
Full API Documentation here: 
https://changelly.com/developers

Here is an example of my "payment button" code I just created (Merchant ID has been changed, this is just an example). Scenario below is as follows:

Destination Coin = Bitcoin
Default Payment Coin  = Ether
Destination Address (needs to be BTCPay generated) = 123456789
*Default payment amount = 987

`<link rel="stylesheet" href="https://changelly.com/widget.css"/> <a id="changellyButton" href="https://changelly.com/widget/v1?auth=email&from=ETH&to=BTC&merchant_id=b95c53453f28&address=123456789&amount=987&ref_id=b95c6c2d3f28&color=00cf70" target="_blank"> <img src="https://changelly.com/pay_button_pay_with.png" /> </a> <div id="changellyModal"> <div class="changellyModal-content"> <span class="changellyModal-close">x</span> <iframe src="https://changelly.com/widget/v1?auth=email&from=ETH&to=BTC&merchant_id=b95c53453f28&address=123456789&amount=987&ref_id=b95c6c2d3f28&color=00cf70" width="600" height="500" class="changelly" scrolling="no" style="overflow-y: hidden; border: none" > Can't load widget </iframe> </div> <script type="text/javascript"> var changellyModal = document.getElementById('changellyModal'); var changellyButton = document.getElementById('changellyButton'); var changellyCloseButton = document.getElementsByClassName('changellyModal-close')[0]; changellyCloseButton.onclick = function() { changellyModal.style.display = 'none'; }; changellyButton.onclick = function widgetClick(e) { e.preventDefault(); changellyModal.style.display = 'block'; }; </script> </div>`


*Default payment amount makes no sense to me. This is NOT what is needed to pay for your invoice to be completed, but rather a default amount that you can set to be sent. It does not seem useful as a merchant and confusing to a customer.

**Comment by lepipele** [comment]
Yeah... that's the showstopper. Here is how the process looks in Shapeshift after dialog is open:

![animation](https://user-images.githubusercontent.com/5191402/37567760-776da270-2a99-11e8-90f3-7166e6f3eba9.gif)

With Changelly they go with that "default payment amount"... if you want to test how their process looked, I've actually left code for that:

https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Views/Invoice/Checkout.cshtml#L291

Just un-comment those few lines and you'll see what dialog you get and how process looks.

**Comment by NicolasDorier** [comment]
Received from them:
```
Hey Predrag,


I'm Mark, head of Changelly product. 

Thanks for your interest in our service!


You are welcome to use our API for crypto to crypto exchanges.

Kindly note that our API is created for crypto to crypto transactions only, no USD or EUR payments are available


We don't have an option to ask for the fees by Destination coin and it's amount cause we don't fix the rates.  https://changelly.com/faq#why-not-fix-rates

Would like to offer you this option later. 


Should you require any further assistance, feel free to write me.


Regards,

Mark
```

I think we can close this as changelly is unlikely to implement what we need. :/
