### ISSUE TITLE
Minor Server Settings spacing bug

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#6223]
In the Server Settings (Policies) page, I sometimes see this (not on every build it seems?), but thought I should post

<img width="686" alt="Screen Shot 2024-09-11 at 6 08 49 PM" src="https://github.com/user-attachments/assets/e98fade0-725d-409c-8990-8561dcfbbb27">

**Comment by dennisreimann** [comment]
Fixed with e389d6a96b3b657e5ca02508a97f138f41f5163c
