### ISSUE TITLE
Where to Integrate new coin price

### ISSUE THREAD

**Issue by junierkl** [btcpayserver/btcpayserver#623]
Hello guys, after integrating an altcoin to BTCPay everything is working perfectly fine, but when i generate an invoice, price shows in USD and the coinaverage doesn't support that altcoin, there is a way to integrate other source for coin price? Can someone point me in the right direction? thanks a lot for this great project.

**Comment by pavlenex** [comment]
In-store settings > Rates you can set the proper source that supports your coin. You should look there if none is supported.

**Comment by junierkl** [comment]
i am thinking more abut adding a new api to fetch the data from a different exchange not listed in there. i appreciate if you guys have the time to tell me which files i need to modify, thanks  a lot

**Comment by Kukks** [comment]
@junierkl The recommended approach is to integrate your exchange in https://github.com/jjxtra/ExchangeSharp and then add it to `RateProviderFactory`  in `InitExchanges` in btcpay.

If you don't want to take that route: 
* You need to create a class similar to `ExchangeSharpRateProvider`
* Add it to `RateProviderFactory` in `InitExchanges`
