### ISSUE TITLE
Payment request - No expiration

### ISSUE THREAD

**Issue by 2pac1** [btcpayserver/btcpayserver#625]
<img width="1262" alt="screenshot 2019-02-28 at 09 12 47" src="https://user-images.githubusercontent.com/35058480/53551236-1865a500-3b39-11e9-9286-2fb41bad52ae.png">

Wouldnt it be better, when nothing is selected, to put pre-selected text there that says: Invoice currently does not have an expiration date or something.
Makes for a better UX.

X on the right makes no sense, as nothing is selected. Makes sense when you have something selected.

**Comment by 2pac1** [comment]
<img width="899" alt="screenshot 2019-02-28 at 09 20 16" src="https://user-images.githubusercontent.com/35058480/53551669-151ee900-3b3a-11e9-979c-3601ba9e0646.png">
Also, would be cool if you could click on the BTC and see drop down menu to all the stuff you can change it to, so you remove thinking out of it.

**Comment by NicolasDorier** [comment]
We can't put a drop down, as we can't have an extensive list of supported pairs.

**Comment by pavlenex** [comment]
You can create invoice without setting expiration time, putting such error would imply to the user that he needs to set expiration time.

**Comment by 2pac1** [comment]
"currently no expiration date has been set" would let users know what is
going on

**Comment by 2pac1** [comment]
Forgot that now btcoay supports how many pairs? Then we need to have a link
for those non listed or something to let them know they can use it if it's
not listed

**Comment by NicolasDorier** [comment]
@2pac1 it depends on the exchange rate provider you are setting in your store config.
