### ISSUE TITLE
Problem with paying lightning invoices.

### ISSUE THREAD

**Issue by nodecheck** [btcpayserver/btcpayserver#626]
I've configured lnd, everything seems fine, public IP is correct, etc.  However, when I attempt to pay an invoice with BlueWallet, all I get is an error.  This makes me believe it's unable to connect to the lnd node I guess, or perhaps something else?

When BlueWallet scans the invoice, it shows correctly the store information so it obviously recognises this.  The error when attempting to click pay is:

API error: LND failue (code 7)

of course that is the error from BlueWallet.  I've attempted searching 1ml to find my node but it doesn't appear - maybe it takes time, but the node has been running for days, I've even attempted resetting the macaroon stuff in case it was because of an update, but it doesn't seem to be this either.

The btcpay logs don't show any connection issues, it sees that an invoice has been created.  What do I need to do to get btcpay to allow me to pay lightning invoices?

**Comment by pavlenex** [comment]
Not really an issue in BTCPay. Simply, Bluewallet does not have a direct channel with your node.
Please open an issue on their github about making that 
API error: LND failue (code 7)` more contextual, it's really unclear UX on their end.
Your node will be visible on explorers only after you have at least 1 direct channel with someone, and it takes time.

**Comment by nodecheck** [comment]
OK thanks for clarification.  I'll take it up with them.  As I could telnet my public IP, and also use the btcpay-lnd.sh script to get getinfo, nodeinfo, listpeers, etc, I did wonder.  I was pretty sure my node was accessible.

**Comment by pavlenex** [comment]
I opened an issue for you there https://github.com/BlueWallet/BlueWallet/issues/367
Closing this one now.
