### ISSUE TITLE
Add warrning in crowdfund about CF page not being public

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#627]
We should have some sort of warring in the UI to let people know that their page won't be public unless they tick the box. I've seen tons of people sharing their apps on Twitter which were private and resulted in 404.

**Comment by Eskyee** [comment]
agreed, yes its not very clear, if you dont check the box to be public..

**Comment by pavlenex** [comment]
Tested and [fixed](https://github.com/btcpayserver/btcpayserver/pull/640).

I wish we've added a bit more descriptive message about what user should do or at least a link for user to return back and alter the settings. Let's hope it's clear, we'll see.

![screen shot 2019-03-04 at 11 36 20](https://user-images.githubusercontent.com/36959754/53727972-d490d980-3e71-11e9-9b10-d9a86c541d34.png)
