### ISSUE TITLE
Pay Request "No store" error consistent with warring in apps

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#628]
We should make the error message consistent with the one in apps as it gives the user a link and exact action on what to do when no store is created.

Add a link to store /stores.

![2019-02-28_22-06-53](https://user-images.githubusercontent.com/36959754/53598640-8e9ff100-3ba5-11e9-9587-336517fea749.png)
![2019-02-28_22-06-54](https://user-images.githubusercontent.com/36959754/53598641-8f388780-3ba5-11e9-96f3-c89a342e9a5b.PNG)

**Comment by pavlenex** [comment]
Fixed grammar for tor the Apps [here](https://github.com/btcpayserver/btcpayserver/pull/630/commits/40efdf01099ab21dddfa3b7e6506df59fbea3e9f).

**Comment by Kukks** [comment]
plz close @pavlenex ? :D

**Comment by Kukks** [comment]
or not, my bad
