### ISSUE TITLE
Add more options for "Consider the invoice confirmed when the payment transaction..."

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#63]
I would like to see this field have a few more options for merchants. 

Specifically, we would like to see the option for 2 confirmations to be deemed safe to ship. I don't feel confident in 1 confirmation, but 2 is safe for our needs. Some others might like 4 etc.. 

It might make sense to add all the options between 0-6 if it does not require a huge refactor

**Comment by bitcoinshirt** [comment]
I think this is a good and reasonable suggestion and I see why some stores need this sort of customization.

**Comment by NicolasDorier** [comment]
So the reason I think it is difficult is that each blockchain have different block time. So "Low" might be 6 blocks in Bitcoin but 20 on litecoin.

**Comment by astupidmoose** [comment]
Yea maybe simply adding a middle ground of 2-3 confirmations on the BTC blockchain might help. 

The difference between 1 or 6 can sometimes be an hour or so. 

Lightning should make this all go away though :P

**Comment by NicolasDorier** [comment]
done
