### ISSUE TITLE
Increase adoption, lower the barrier of entry and costs by extending support to Snipart, SSG's and more..

### ISSUE THREAD

**Issue by fraktar** [btcpayserver/btcpayserver#631]
The title is pretty explicit, but I will go into it a bit.

**Currently users have to:**

(1) Install Wordpress+Woocommerce, Magento, Prestashop or Drupal
&
(2) Install the actual BTCPay server in a VPS
&
(3) Purchase a domain name with traditional payment systems

**Issues:**

- both of those services cost $, which is fine but we can do better
- users already having a static website/blog/etc would need to install a database-driven CMS separately (and/or migrate content)
- speed, security and bloat (Wordpress is famous here)
- too many features in a traditional cart system (we need a very easy way for anyone to spin up a shop in under 30 minutes)
- privacy could be enhanced (for both hosting services and domain name registration)

How about eliminating the database host (1) by supporting [Snipcart](https://snipcart.com) and [Static Site Generators](https://www.staticgen.com/) (like [Jekyll](https://jekyllrb.com) for instance)? 

SSG's don't require a database and are made up of normal static files (HTML, CSS, JS). This eliminates the need for Wordpress.

**What about the shopping cart?** 

Snipcart is the answer. 

This is very simple to install in ANY static website by dropping in a few lines of code in the <head> of the website. Note that Snipcart is also [open-source](https://github.com/snipcart).

Example (taken from [Snipcart's official docs](https://docs.snipcart.com/getting-started/installation)):

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

<script src="https://cdn.snipcart.com/scripts/2.0/snipcart.js" data-api-key="YOUR_API_KEY" id="snipcart"></script>

<link href="https://cdn.snipcart.com/themes/2.0/base/snipcart.min.css" rel="stylesheet" type="text/css" />
```

**How does this lower costs?** 

Easy: there are a lot of free static content hosts, like [Netlify](https://www.netlify.com) which is 100% free and even provisions a Let's Encrypt cert for all websites. (Also [Netlify CMS](https://www.netlifycms.org/) -- which uses git and is open source).

You only need to pay for the BTCPay VPS (if you want to self host, otherwise the cost is **ZERO**).

**Can I pay with BTC for my custom domain name?**

Give me a reason why you should NOT. [Namecheap](https://www.namecheap.com/support/payment/bitcoin.aspx) comes to mind first.

What about s* coins? Maybe [Njalla](https://njal.la/), didn't try it though. Let me know how it goes!

**Let's wrap up. That would mean:**

- lower costs (users don't need to pay for a CMS host)
- increased privacy (users can pay with BTC for domain names)
- increased speed and security, zero bloat (_anything_ is faster, more secure and less bloated than WP)
- lower barrier of entry (it's easy and fast to test your shop with no db, no credit card and no complex cart system config)
- **increased adoption (has to be?!)**

I'm personally not technical enough to accomplish this task (the Snipcart integration/support). That's why the long tl;dr -- maybe you think this is worth it. If not, thanks for reading!

_<3 BTCPay, keep up the good work @NicolasDorier and everyone._

**Comment by NicolasDorier** [comment]
The step (1) can already be eliminated, you just have to add woocommerce plugin when you setup btcpay.

**Comment by fraktar** [comment]
> The step (1) can already be eliminated, you just have to add woocommerce plugin when you setup btcpay.

You mean the Woo commerce plugin can be used with static websites without WP?

**Comment by NicolasDorier** [comment]
I mean https://medium.com/@BtcpayServer/btcpay-woocommerce-cheap-ab6fcdd97075

**Comment by pavlenex** [comment]
Thanks for posting feedback.

I'd like to add that if you want to spread adoption locally with people who don't have site, you can use WordPress multisite (hosting multiple WordPress / WooCommerce stores) from a single host to many people (idea by @Kukks)

BTCPay already has [apps](https://docs.btcpayserver.org/features/apps) that people who don't have website can use. For simple shop they can use Point Of Sale app, hopefully once we have #505 

You can already set up btcpay + custom domain + woocommerce for as little as $4 in the article Nicolas posted.

Don't get me wrong, I am all in for more solutions, plugins, integrations, but at this point it depends on people who need it to integrate it. The only real requests for CMS we have is Shopify.

**Comment by fraktar** [comment]
Thanks for your reply!

> You can already set up btcpay + custom domain + woocommerce for as little as $4 in the article Nicolas posted. 

I totally understand that but as I already stated we can get the same result with $0 and benefit from the Jamstack, which means increased speed and zero bloatware from traditional CMS's.

> I am not sure if it helps you with integration, but this may be a [good starting point](https://medium.com/@apotdevin/using-react-and-btcpayserver-to-receive-bitcoin-payments-2098b2856a3b) of a good custom integration.

That's very interesting, thanks for sharing. Seems like a nice example but I have zero experience with React. Will duplicate it just for the sake of experimenting though, see what I can make it do.

> Don't get me wrong, I am all in for more solutions, plugins, integrations, but at this point it depends on people who need it to integrate it. The only real requests for CMS we have is Shopify.

Well, if we can make Snipcart work I for one would use it in all my future client work projects and also migrate existing clients to this and support BTCPay.

**Comment by pavlenex** [comment]
I'll mark this brainstorming as `closing` as it is a bit too generic. @fraktar if you ever wish to work on Snipart integration, feel free to create a new issue.
