### ISSUE TITLE
[Bug]: Cannot remove my store SMTP settings

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver#6317]
### What is your BTCPay version?

Running latest version: 1.13.5

### How did you deploy BTCPay Server?

Docker

### What happened?

My store has SMTP settings from earlier. The UI says that I can remove them, and then my server's SMTP will be used as a fallback.
I, however, can turn off the slider, collapsing the SMTP settings form, but this also collapses the "Save" button, making it impossible for me to save.
If I use some web inspection tweaking to re-show it, and force the form, it also does not save.

The store emails config first appears like this (I replaced the values with "XXX" on purpose)
![image](https://github.com/user-attachments/assets/efdabef6-bb8e-4388-a882-83db41e705dc)

When I change the slider, the "Save" button disappears and I have no way of saving...

![image](https://github.com/user-attachments/assets/fec287e8-f01c-4553-853b-8430d65624c9)

### How did you encounter this bug?

1. Wanted to turn of store SMTP settings

### What browser do you use?

Latest Chrome

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
This will be fixed in v2.0 :)

**Comment by woutersamaey** [comment]
@dennisreimann should I change the data manually in Postgres or will updating to v2 fix it for me? And if I should update manually, is it just the 1 record in the 1 table? I imagine NBXplorer may also have the wrong date etc...

**Comment by woutersamaey** [comment]
@dennisreimann Sorry yes. Deleted my comment.
