### ISSUE TITLE
Can't Delete any user on the server (Unable to Delete Last Admin)

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#632]
This is a confirmed bug. I believe related to #550.

## Steps to replicate
1. Try to delete an already registered user to your server (a regular user, not an admin)
2. You'll get the message `Unable to Delete Last Admin`

**Comment by britttttk** [comment]
#632

While we fix, you can make the user an admin then you are able to delete them.

**Comment by pavlenex** [comment]
The issue has been resolved [here](https://github.com/btcpayserver/btcpayserver/commit/fee936b569548ecd4d93533697b3b4db75c8d06c).

Tested and it works. Closing.
