### ISSUE TITLE
[Bug]: Transaction dates are wrong after server / BTC node downtime

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver#6322]
### What is your BTCPay version?

Latest version, v1.13.5+30d91d0bd

### How did you deploy BTCPay Server?

Docker

### What happened?

My server was down for a few months due to hardware failure.
I restarted it 2 days ago and the BTC node started syncing again. This took a long time, but ultimately went well.

During the downtime, I had only 1 transaction.

This transaction appears now as "yesterday", which is the WRONG date. If I look at the blockchain, the transaction was 2 months ago. Thus: BTCPay seams to use the date the transaction was first seen, and not the date it was actually included on the blockchain.

This wrong date is visible everywhere:
- The balance graph on the dashboard also shows the wrong date.
- Wallet page has the transaction at the wrong date
- Dashboard "Recent Transactions" is wrong
- etc...

### How did you encounter this bug?

See previous answer

### What browser do you use?

Not relevant

### Additional information

I can share transaction details privately if needed.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
@NicolasDorier This seems like an NBX issue?

**Comment by NicolasDorier** [comment]
https://github.com/dgarage/NBXplorer/commit/f3aeea447ddc6189200aae3f457e2c333048d340

Will release a new NBX shortly. This doesn't fix the issue for transactions already scanned though.

**Comment by woutersamaey** [comment]
@NicolasDorier how can I best correct the data? In DB? Which DB? Which tables? Do you maybe have some SQL for me?

**Comment by NicolasDorier** [comment]
@woutersamaey I don't have a SQL for you, but the table is `txs` table. One of the column is a timestamp normally.
