### ISSUE TITLE
[Bug]: 400 bad request

### ISSUE THREAD

**Issue by herraristotle** [btcpayserver/btcpayserver#6324]
### What is your BTCPay version?

© BTCPay Server v1.13.5+30d91d0bd

### How did you deploy BTCPay Server?

I am running btcpayserver on an local ubuntu vm, using ngrok to expose to the internet for testing.

### What happened?

It was working fine generating invoices via api, then it suddently start giving 400 bad request when the invoice is called via api

![image](https://github.com/user-attachments/assets/4dd9067f-cb66-4f58-be8e-a2bc1c6fc315)

### How did you encounter this bug?

running via a telegram bot

### What browser do you use?

Chrome

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Fresh-Mess** [comment]
fuck this n00b project faggots

**Comment by librty** [comment]
I have the same 400 bad request with a custom pay button implementation, which fails to load resource on "xhttp.send(new FormData(event.target));" inside the js.

![Screenshot from 2024-11-04 15-18-25](https://github.com/user-attachments/assets/5aabe00e-ce34-4b80-87d4-5ec48d21329c)

**Comment by herraristotle** [comment]
What info do you need @pavlenex

**Comment by pavlenex** [comment]
Code examples or logs would be a good start.

**Comment by librty** [comment]
My issue seems to have been related to the fact that Indonesia is blocking access to Kraken, and I am not getting the rates from kraken, and it fails. Just switching to a US based connection, all was good.

**Comment by dennisreimann** [comment]
@herraristotle Can you check if this is a DNS issue for you as well? Otherwise, a code sample of your pay button HTML and logs from the BTCPay Docker container (`docker logs generated_btcpayserver_1`) would be needed to debug this.
