### ISSUE TITLE
Newline during import of multisig xpub results in different addresses for wallet

### ISSUE THREAD

**Issue by rockstardev** [btcpayserver/btcpayserver#6328]
Here is the video illustrating the issue, when I am entering multisig xpub for the second time I am adding newline and that causes wallets with `3...`

https://github.com/user-attachments/assets/2aa321bf-5b8a-4dec-a29b-875a77d10bb9

Expected addresses:
![image](https://github.com/user-attachments/assets/a200361e-54f9-46b3-8896-4b2d33a1bcdb)

Addresses with newline in multisig:
![image](https://github.com/user-attachments/assets/305703e5-e5a3-4a5c-b029-06663adf2208)

**Comment by Fresh-Mess** [comment]
fuck rockstar imma expose your dumb ass and kill this project faggot ass

**Comment by Fresh-Mess** [comment]
fuck a slut
that means fuck your mother
