### ISSUE TITLE
Integration tests consistently failing on CanUseLNPayoutProcessor

### ISSUE THREAD

**Issue by rockstardev** [btcpayserver/btcpayserver#6335]
Now that @NicolasDorier has recently fixed tests with Lightning library, we still have them failing on `CanUseLNPayoutProcessor`, see the stack log:

![image](https://github.com/user-attachments/assets/011eee08-b54a-4469-b687-c5101d0d1407)

https://app.circleci.com/pipelines/github/btcpayserver/btcpayserver/13908/workflows/d55a5179-05a7-4f11-b4e9-706115f2d55b/jobs/43441

```
[xUnit.net 00:01:44.11]         10/25/2024 13:56:29 +00:00 :Tests:   BTCPayTester disposed
  Failed CanUseLNPayoutProcessor [23 s]
  Error Message:
   Assert.Equal() Failure: Values differ
Expected: Completed
Actual:   null
  Stack Trace:
     at BTCPayServer.Tests.GreenfieldAPITests.<>c__DisplayClass48_0.<<CanUseLNPayoutProcessor>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at BTCPayServer.Tests.TestUtils.EventuallyAsync(Func`1 act, Int32 delay) in /source/BTCPayServer.Tests/TestUtils.cs:line 115
   at BTCPayServer.Tests.TestUtils.EventuallyAsync(Func`1 act, Int32 delay) in /source/BTCPayServer.Tests/TestUtils.cs:line 127
   at BTCPayServer.Tests.GreenfieldAPITests.CanUseLNPayoutProcessor() in /source/BTCPayServer.Tests/GreenfieldAPITests.cs:line 4207
--- End of stack trace from previous location ---
```

It seems we need to fix the way GetStorePayouts logic is working.

![image](https://github.com/user-attachments/assets/ec1dd686-5d33-42f7-accf-e978c0b8e150)

**Comment by NicolasDorier** [comment]
Not a test issue or a bug issue. It is a problem where in some conditions payment from merchant to customer fails because lightning implementations sucks for testing... need to fix it but it is very hard to find out how to replicate.

**Comment by NicolasDorier** [comment]
Fixed with https://github.com/btcpayserver/btcpayserver/commit/0e59107eeec5ee790056a207b269203b89bb22d6

**Comment by NicolasDorier** [comment]
NNOOOO IT ISN"T FOR FUCK SAKE

**Comment by NicolasDorier** [comment]
https://github.com/btcpayserver/btcpayserver/commit/9bb1a5b80a0772aa09aeb20d00ab92bdefd7e906
