### ISSUE TITLE
[Bug]: `includePreRelease` setting isnt honored when downloading plugin manifest

### ISSUE THREAD

**Issue by jackstar12** [btcpayserver/btcpayserver#6344]
### What is your BTCPay version?

v1.13.5, v2

### How did you deploy BTCPay Server?

Manually, regtest

### What happened?

When installing a non-prerelease plugin which has a newer pre-release version available, the wrong plugin manifest will be downloaded by btcpay. This can cause the install to not happen since the new manifest might have other btcpay version requirements then the actual manifest for the version.

The issue lies here:
https://github.com/btcpayserver/btcpayserver/blob/910801d30542602a732490f78a59d8eb6176f285/BTCPayServer/Plugins/PluginService.cs#L77

The pre-release server settings isnt honored here. A quick fix would be to simply honor this settings, but the plugin builder should provide an endpoint to fetch the exact manifest for a version (https://github.com/btcpayserver/btcpayserver-plugin-builder/issues/38).

### How did you encounter this bug?

1. disable pre-release plugins on server
2. install a plugin which has a newer version in pre-release
3. see that the wrong version is showed on pending install

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
on it
