### ISSUE TITLE
[Bug]: Intermittent Timeout and 502 Gateway Errors Through External Proxy After Update to BTCPayServer v2.0.0

### ISSUE THREAD

**Issue by TowyTowy** [btcpayserver/btcpayserver#6349]
### What is your BTCPay version?

I'm running BTCPay v2.0.0.

### How did you deploy BTCPay Server?

I'm running BTCPay Server on Docker.

### What happened?

After updating to BTCPayServer v2.0.0, I'm experiencing intermittent timeouts and 502 Gateway errors when accessing the server through an external Nginx proxy setup. The issue tends to occur if there’s no page load for around 5 minutes, after which any new request results in a timeout.

### How did you encounter this bug?

Access BTCPayServer through Cloudflare, routed via an external proxy server.
Wait approximately 5 minutes without loading any page.
Attempt to navigate to the login page or any other page.
Observe intermittent timeout and 502 Gateway errors.

### Relevant log output

```shell
Proxy Server Logs: upstream prematurely closed connection while reading response header from upstream
upstream timed out (110: Connection timed out) while SSL handshaking to upstream
BTCPayServer Logs: No error logs found for these requests. The logs indicate normal behavior.
```

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by TowyTowy** [comment]
Okay, now it is seems to be working again without hiccups.

**Comment by NicolasDorier** [comment]
it may have been caused by the traffic of the migration in the background.
Re-open if it still happen.
