### ISSUE TITLE
Pay Button with a QR code

### ISSUE THREAD

**Issue by leblitzdick** [btcpayserver/btcpayserver#635]
Hi people i love your project i have BTCPay server running on my raspberrypi i am very excited!!

I have the desire for a feature that I think might be interesting for many!

For me as a freelancer who also prints invoices on paper or sends them by mail it would be a great feature if you could equip the Pay Button with a QR code, which creates an invoice for me directly at the time the customer scans the QR code.

At the moment I help myself with an intermediate step, by copying the code from the pay button on my server and scanning it there with a QR code generated by me on the invoice, which then leads/calls me to this html code. That looks something like this: 

```
<form name="myform" method="POST" action="https://xxx.xxx.xxx.xxx/api/v1/invoices">
    <input type="hidden" name="storeId" value="####mystore###" />'
    <input type="hidden" name="price" value="12,34" />
    <input type="hidden" name="currency" value="EUR" />
    <input type="hidden" name="checkoutDesc" value="Bill No. />
    <input type="hidden" name="orderId" value="2" />
    <input type="hidden" name="notifyEmail" value="xxx@xxx.biz" />
</form>

<script type="text/javascript">
  document.myform.submit();
</script>
```

This works well, but unfortunately it is a bit complicated, because a lot has to be edited by hand.

What I imagine would be the generation of a QR code with BTCPay server logo in the middle which directly calls this code on top of the server itself without the intermediate step...

I have dream :-)

**Comment by Kukks** [comment]
@leblitzdick  You can use the new Payment Requests feature. :) Just share its url and you are good to go

**Comment by pavlenex** [comment]
Regardless, creating an invoice by scanning a unique QR code is genius idea. People in China use it all the time with WeChat. Store owner just prints the QR code and people can pay him. People can use BTCPay just with a piece of paper.

I'm not quite sure if I got the idea right though.

**Comment by leblitzdick** [comment]
Yes the Payment Request will do the job. But the problem is, that the payment request does not take current Bitcoin rates but the rate used when creating the request! So if I have an invoice where the customer has 2 weeks time to pay I can't know when he pays. He always gets the course from the creation of the request. That can be good for him but it does not have to be. In any case it would be better to use the current rate. So far this only works via the Pay button, because a new invoice will be created there. 

Perhaps it would also be a solution that you can select when creating the payment request whether the current rate is displayed or whether it is dynamically updated when called. 

In any case it would be cool to get a QR code which you can easily copy to the paper invoice.

**Comment by britttttk** [comment]
Why not just make the payment request URL into a QR code and send that? Then the user is taken to the payment request, rates are current when they pay, and there is no address reuse.

**Comment by pavlenex** [comment]
>  Payment Request does not take current Bitcoin rates but the rate used when creating the request!

Each time you click pay button on the payment request, it creates an invoice with the current rate.

**Comment by leblitzdick** [comment]
I would like to try again to explain why I would find it nice to have current courses in creating bills. 

What I do is I create an invoice for e.g. 200 EUR which is valid for 2 weeks (20160). Now the customer has time in these 2 weeks to decide when he wants to pay. So he could speculate to wait to get a cheaper rate. Of course this can't end well for him either. 

What I personally as a customer would not like at all is that I receive payment courses that have the date of the invoice. That has for me the taste of manipulation over the course, since I can not be sure when the calculation was provided and which course lies to the basis. Maybe too low a rate distorts the invoice to my disadvantage. 

Personally I would find it better to always get current courses for payment, like with the pay button. If this would be possible with the payment request at least as an option to always get the current rate calculated, I would be happy.

**Comment by pavlenex** [comment]
The only solution I can think of for this is to add the option to use the rate at the time payment requests was created and ignore the rest. I'm again not quite sure, it seems too specific use-case and might require quite a lot of work for invoices.
@Kukks what do you think?

**Comment by Kukks** [comment]
![frame](https://user-images.githubusercontent.com/1818366/56429819-88d0ad00-62c4-11e9-861f-9e5297b5eb4a.png)

Behold!

**Comment by Kukks** [comment]
> The only solution I can think of for this is to add the option to use the rate at the time payment requests was created and ignore the rest. I'm again not quite sure, it seems too specific use-case and might require quite a lot of work for invoices.
> @Kukks what do you think?

This would completely destroy the purpose of payment requests...

If you really really wanted to have an invoice that kept the same rate, just extend the lifetime of invoices in the store settings from 15minutes to as long as you want.

**Comment by mariodian** [comment]
> For me as a freelancer who also prints invoices on paper or sends them by mail it would be a great feature if you could equip the Pay Button with a QR code, which creates an invoice for me directly at the time the customer scans the QR code.

That is not possible. There is some entropy involved in the invoice creation process so you have no way of knowing what the QR code will look like before you create the invoice. 

The invoice comes first, it creates static data and then you can create a QR based on that.

**Comment by mariodian** [comment]
And if what you meant was that:

1) the customer scans a QR code 
2) upon the scan, an invoice is created
3) the new invoice's QR code is displayed to the customer
4) the customer scans that as well

then I think that's a terrible design.

**Comment by Srishapattabiraman** [comment]
Hi All, On clicking on "Pay with B?TCpay" button, how do i have a callback with specific userid
