### ISSUE TITLE
[Bug]: Broken char escape. Apostrope( ' ) turns into `&#x27;`

### ISSUE THREAD

**Issue by mar101xy** [btcpayserver/btcpayserver#6352]
### What is your BTCPay version?

BTCPay Server v2.0.0+5ad0b128a 

### How did you deploy BTCPay Server?

I installed a fresh btcpay which gave me the version 1.13 then after that i quickly upgraded to btcpay 2.0
using Docker compose deployment

### What happened?

I updated the "Server Name" in "Branding" to "Mar's BTCPAY"

https://btcpay.mar101xy.com/server/branding

saved it and went to my url 

https://btcpay.mar101xy.com

and it showed up as:

Welcome to 

`Mar&#x27;s BTCPAY`

You can check my url to see the issue.

### How did you encounter this bug?

I updated the name in  "Server Name" in "Branding"

I tried using an grave accent ( `  ) instead of the apostrope. And the issue did not happen

![btcpay-bug](https://github.com/user-attachments/assets/de6c6b83-ed06-4e7d-8d74-bea1f6702c8e)

### What browser do you use?

It seems to happen in all browsers

Firefox 132-0(64 bit)
Chrome Version 130.0.6723.91 (Official Build) (64-bit)
Microsoft Edge Version 130.0.2849.56 (Official build) (64-bit

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Thanks for filing this one @mar101xy. I was able to replicate it in 2.0.2

@dennisreimann I'll add this one to 2.0.3 milestone as a low-priority.

**Comment by Buildervt** [comment]
> ### What is your BTCPay version?
> 
> BTCPay Server v2.0.0+5ad0b128a 
> 
> 
> 
> ### How did you deploy BTCPay Server?
> 
> I installed a fresh btcpay which gave me the version 1.13 then after that i quickly upgraded to btcpay 2.0
> 
> using Docker compose deployment
> 
> ### What happened?
> 
> I updated the "Server Name" in "Branding" to "Mar's BTCPAY"
> 
> 
> 
> https://btcpay.mar101xy.com/server/branding
> 
> 
> 
> saved it and went to my url 
> 
> 
> 
> https://btcpay.mar101xy.com
> 
> 
> 
> and it showed up as:
> 
> 
> 
> Welcome to 
> 
> 
> 
> `Mar&#x27;s BTCPAY`
> 
> 
> 
> You can check my url to see the issue.
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ### How did you encounter this bug?
> 
> I updated the name in  "Server Name" in "Branding"
> 
> 
> 
> I tried using an grave accent ( `  ) instead of the apostrope. And the issue did not happen
> 
> 
> 
> ![btcpay-bug](https://github.com/user-attachments/assets/de6c6b83-ed06-4e7d-8d74-bea1f6702c8e)
> 
> 
> 
> 
> 
> ### Relevant log output
> 
> _No response_
> 
> ### What browser do you use?
> 
> It seems to happen in all browsers
> 
> 
> 
> Firefox 132-0(64 bit)
> 
> Chrome Version 130.0.6723.91 (Official Build) (64-bit)
> 
> Microsoft Edge Version 130.0.2849.56 (Official build) (64-bit
> 
> ### Additional information
> 
> _No response_
> 
> ### Are you sure this is a bug report?
> 
> - [X] I confirm this is a bug report

With this
