### ISSUE TITLE
Paid Lightning Network Invoices are not updating to "settled" transaction status.

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#6355]
### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/6353

<div type='discussions-op-text'>

<sup>Originally posted by **abitcoinperson** November  2, 2024</sup>
What is your BTCPay version?

- BTCPay Sever version, v1.13.5+30d91d0bd
- LND version, 0.18.3-beta

How did you deploy BTCPay Server?
Voltage.cloud

What happened?
- We've been using BTCPay Server as an organization, deployed on Voltage, for the last few years. 
- We use BTCPay Server to accept Bitcoin donations from the public.
- Everything has been working as intended for quite some time, but a couple months ago our Lightning Network invoices are not changing to the "settled" state within BTCPay Server. This is creating issues with our operational workflow of sending automated receipts, as we rely on the "settled" state to trigger our email provider to send receipts to donors. 
- NOTE: On Chain donations are working just fine and properly update status to "Settled", however none of our LN Payments have been updating for quite some time. This is occuring 100% of the time and I can confirm that our node is actually receiving payments via Lightning, but the invoice status simply doesn't get updated within BTCPay. 

How did you encounter this bug?
We had reports of our receipts not being sent to donors who contribute to our organization via the Lightning Network.

What have you done to troubleshoot?
We've been working with the voltage team to troubleshoot, testing our BTCPay Server connection string (it works), however they are not able to get to the bottom of the issue and asked us to reach out directly to see if you've encountered this issue before.</div>

**Comment by Kukks** [comment]
After some internal troubleshooting we found the issue was related to the macaroon that was in use no longer being valid despite it still supposedly so. Generating a new one worked. It seems to be some lnd.18 related bug from what I could tell as when they downgraded the node to .17 the existing macaroon worked again!

**Comment by pavlenex** [comment]
Oh wow, thanks for troubleshooting this one @Kukks it was something they've been trying to track for a while!
