### ISSUE TITLE
[Bug]: Failed payouts (routing issue) aren't canceled but left in awaiting payment status for days/possibly indefinitiatly?

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#6377]
### What is your BTCPay version?

2.0.2

### How did you deploy BTCPay Server?

docker

### What happened?

I tried to pay a 100 sats with my boltcard (linked to btcpay and to blink) to a Zeus wallet which is only reachable via private channel from LNBIG (Hub-3).

The payment doesn't happen and in the pull request it remains in " Awaiting Payment " status. As a end user, I have no chance to cancel this payment attempt (owners of boltcards don't have an interface for that). And as server admin I can only cancel the payouts manually.

I would suggest:

1. cancel the payout when the invoice from Zeus that it's trying to pay has expired (by default with this wallet 60 minutes)
2. after 10 retries each after the automatic payment processors interval, not just stop attempting the payment, but also cancel the payout. So that in the case of boltcard users, their balance is no longer blocked.

### How did you encounter this bug?

see above

### Relevant log output

```shell
none
```

### What browser do you use?

Firefox on Windows 11

### Additional information

none

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NAKKIABW** [comment]
Crazy question I am not exactly sure what I am need to do on this application just trying to accept crypto and this  crap is confusing literally

**Comment by petzsch** [comment]
> Crazy question I am not exactly sure what I am need to do on this application just trying to accept crypto and this crap is confusing literally

This is not the place for your questions. Please join the [BTCPay Server Telegram](https://t.me/btcpayserver) or [Mattermost](https://chat.btcpayserver.org/).

**Comment by NicolasDorier** [comment]
From 2.0, if a lightning payment made by the automated payout processor fails, then the payout stays in the state "Awaiting for payment" so it can be attempted again after 10 minutes or manually.

This behavior while being useful for refunds, isn't good for Boltcards, where the payout is better cancelled if it can't be immediately done, so the user can try to pay again with a whole new payout.
