### ISSUE TITLE
[Bug]: API/Swagger doc: paymentTolerance

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#6378]
### What is your BTCPay version?

2.0.2

### How did you deploy BTCPay Server?

docker

### What happened?

A [user on Mattermost](https://chat.btcpayserver.org/btcpayserver/pl/t11oioombjreibu9jjo6c1qh6r) reported his invoices instantly settleing. He didn't have slippage configured in the store settings, but gave paymentTolleracne a 100.

According to https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Invoices_CreateInvoice

> A percentage determining whether to count the invoice as paid when the invoice is paid within the specified margin of error. Defaults to the store's settings. (The default store settings is 100)

The default should be 0.

### How did you encounter this bug?

see above

### Relevant log output

```shell
none
```

### What browser do you use?

none

### Additional information

none

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by marcinx** [comment]
Also in the Payload Sample:

<img width="541" alt="Screenshot 2024-11-10 at 10 01 26 PM" src="https://github.com/user-attachments/assets/d60cb20d-828e-465b-b2d8-5e4df30c7989">
