### ISSUE TITLE
[Bug]: Payment History in payment requests is invisible for `pending payment` and invalid invoices shown as pending

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#6409]
### What is your BTCPay version?

2.0.3

### How did you deploy BTCPay Server?

Docker

### What happened?

Due to our recent changes in the logic https://github.com/btcpayserver/btcpayserver/pull/6381 we overlooked certain scenarios that is leading to UX confusion. In this concrete scenario, a payment request invoice is `invalid` but the payment request UI shows it as `Pending`. What is even more confusing that this is that the `Payment history` below doesn't even recognize that the payment has been made, leading to the confusion on the end of the user who paid, thinking he didn't make a payment to an adequate address.

Expected behaviour:
1. Invalid invoice should be shown as invalid state in the payment request (lower prio)
2. Payment history should recoginze and show any payments , regardless of the status, making it easier to troubleshoot and understand what's happened. (in this case tx is stuck in the mempool) (higher prio)

### How did you encounter this bug?

1. Create a payment request
2. Pay
3. Invoice is invalid
4. Check payment request UI, you'll see pending
5. No payment history is shown

### Additional information

<img width="1073" alt="Screenshot 2024-11-18 at 14 40 23" src="https://github.com/user-attachments/assets/74a1ff7b-1e59-477e-a944-b5174dd1716a">

<img width="855" alt="Screenshot 2024-11-18 at 14 52 18" src="https://github.com/user-attachments/assets/409020fd-d9f9-4e07-926e-c7f788b3ed3e">

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
So there are two bugs in one issue:
1. Why is it still pending when the invoice is invalid
2. Why the payment doesn't appear.

For `2.` the PR https://github.com/btcpayserver/btcpayserver/pull/6412 will fix it.

For `1`, a workaround is for the merchant to mark the invoice as Settled, then mark it as Invalid again.
There is an assumption in Payment Request and Crowdfund that an invalid invoice should still be accounted for. But not for `Invalid (marked)`. This is on purpose, and I think we can change this, but if we were deliberate into having this behavior, I feel that it will impact some people.
