### ISSUE TITLE
expecting you to access this website from

### ISSUE THREAD

**Issue by fluidvoice** [btcpayserver/btcpayserver#641]
I see this also, but I'm not using any proxy that I know of. But my wifi router is connected to my ISP's broadband router (that I don't have admin rights to).  How should I resolve this problem?

_Originally posted by @fluidvoice in https://github.com/btcpayserver/btcpayserver/issues/329#issuecomment-469075368_

**Comment by pavlenex** [comment]
See this https://docs.btcpayserver.org/faq-and-common-issues/faq-deployment#btcpay-is-expecting-you-to-access-this-website-from

**Comment by NicolasDorier** [comment]
Can you update? I solved one bug that might caused this to show while your install is good.

**Comment by NicolasDorier** [comment]
If not solved, can you share your server link here?

**Comment by fluidvoice** [comment]
> Can you update? I solved one bug hours ago that might caused this to show while your install is good.

I'm a new user. How do I update?

**Comment by pavlenex** [comment]
@fluidvoice Check this [guide](https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#how-to-update-btcpay-server ).

**Comment by fluidvoice** [comment]
OK updating via SSH now, thanks.  Will edit this post with results.

**Comment by fluidvoice** [comment]
The message is gone now, thanks. Closing this issue.
