### ISSUE TITLE
[Bug]: Planned Transaction creation occasionally fails with PK constraint violation

### ISSUE THREAD

**Issue by rockstardev** [btcpayserver/btcpayserver#6411]
This is sometimes replicated in our tests, an example:

https://app.circleci.com/pipelines/github/Kukks/btcpayserver/2776/workflows/65d3bb33-3aa7-4848-9384-b0e44a30b2bb/jobs/7612?invite=true#step-102-123596_169

It seems that the problem is around the line 372 in PayJoinTests: https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer.Tests/PayJoinTests.cs#L372

It would be good if @Kukks can take a look at this since it's part of the codebase he implemented. On retry test passed: https://app.circleci.com/pipelines/github/Kukks/btcpayserver/2776/workflows/f7e76c00-a283-4449-aec8-9bf437ee35e5/jobs/7615?invite=true#step-102-84374_34

**Comment by NicolasDorier** [comment]
About the exception: The exception isn't the issue, this exception is caught properly and those are just logs from inside entity framework.

**Comment by rockstardev** [comment]
https://github.com/btcpayserver/btcpayserver/pull/6416#pullrequestreview-2450066029
