### ISSUE TITLE
[Bug]: Bad transaction / invoice assignement

### ISSUE THREAD

**Issue by Nisaba** [btcpayserver/btcpayserver#6419]
### What is your BTCPay version?

1.13.6

### How did you deploy BTCPay Server?

Docker

### What happened?

I set a BTC wallet for a store, but sometimes I receive in this wallet transactions that have nothing to do with BTCPay.
I then noticed that BTCPay assigned these transactions to old expired or cancelled invoices. They then took an overpaid status.
This can be very annoying because it can throw unexpected triggers and deliveries

### How did you encounter this bug?

-

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Kukks** [comment]
You are most likely using another wallet software elsewhere that reuses old addresses that btcpay generated for invoices because they do not share wallet state.

**Comment by Nisaba** [comment]
Yes, probably.
so you advise against using a wallet simultaneously with BTCPay ?

**Comment by Kukks** [comment]
I would at the very least not use it for generating addresses for payments.
