### ISSUE TITLE
Label in URI is lost. Should fill into Label

### ISSUE THREAD

**Issue by nostitos** [btcpayserver/btcpayserver#6426]
Click URI with "?label=..."  label doesn't get filled in the BTCPAY SEND walelt.

**Comment by dennisreimann** [comment]
I just tested this and cannot reproce. The label field gets correctly filled if the label is provided via BIP21 on the wallet send page. Please provide more detail about what exactly does not work.

**Comment by dennisreimann** [comment]
Please reopen with more detail if this is still unclear or does not work.

**Comment by nostitos** [comment]
> Please reopen with more detail if this is still unclear or does not work.

It works, Was using "message=" instead of label: because that's what electrum prefered.
