### ISSUE TITLE
BTCPay server integration to wix

### ISSUE THREAD

**Issue by Jeans5** [btcpayserver/btcpayserver#643]
Hi, I try to integrate btcpay server to my Wix website (www.start2bitcoin.com). But each time I try to click on the pay button I receive this message:

What did I do wrong? Thx!

<img width="291" alt="schermafbeelding 2019-03-04 om 13 01 19" src="https://user-images.githubusercontent.com/41012465/53732405-22134380-3e7e-11e9-83fb-5a5df9dfa019.png">

**Comment by NicolasDorier** [comment]
Can you share your pay button here?

**Comment by Jeans5** [comment]
You can find the button [here](https://www.start2bitcoin.com/cart?appSectionParams=%7B%22origin%22%3A%22cart-popup%22%7D).

And this is the code:

> <form method="POST" action="https://mainnet.demo.btcpayserver.org/api/v1/invoices">
    <input type="hidden" name="storeId" value="DJNPmaKMfQjyXSyeQ8uTTuJzd49oZ99NVSxdvoDa91E3" />
    <input type="hidden" name="price" value="10" />
    <input type="hidden" name="currency" value="USD" />
    <input type="image" src="https://mainnet.demo.btcpayserver.org/img/paybutton/pay.png" name="submit" style="width:209px" alt="Pay with BtcPay, Self-Hosted Bitcoin Payment Processor">
</form><form

**Comment by pavlenex** [comment]
It looks like Wix is blocking iframe for some reason. Unfortunately I am unfamiliar with Wix and how it works.

```
Refused to display 'https://mainnet.demo.btcpayserver.org/api/v1/invoices' in a frame because it set 'X-Frame-Options' to 'deny'.
cart:1 Refused to display 'https://mainnet.demo.btcpayserver.org/api/v1/invoices' in a frame because it set 'X-Frame-Options' to 'deny'.
invoices:1 Failed to load resource: the server responded with a status of 400 ()
```

**Comment by pavlenex** [comment]
@Jeans5 Actually your problem is simple

You have not configured your BTCPay store.
```
"Warning: No wallet has been linked to your BTCPay Store. See the following link for more information on how to connect your store and wallet. (https://docs.btcpayserver.org/btcpay-basics/gettingstarted#connecting-btcpay-store-to-your-wallet)\n3/4/19 4:00:21 PM: Creation of invoice starting\n"
```

Please set your BTCPay Wallet as instructed.

**Comment by Jeans5** [comment]
I was too quick with integrating it:s Thanks for the help, it works now.

**Comment by pavlenex** [comment]
You usually would see the error, but for some reason Wix blocked it. Glad it's working now.

**Comment by Jeans5** [comment]
Yes indeed, Wix blocks a lot of things.. I'm also looking to make the amount dynamic dependant on the purchase someone did in the store? Now it's working with a fixed amount. Some recommendations where I can look or how to change this?

**Comment by pavlenex** [comment]
Unfortunately for now, we don't have dynamic amounts for pay button.
What you can do is try to create a Point Of Sale App, enable custom amount there, and remove all of the `products`. 
![2019-03-04_18-17-08](https://user-images.githubusercontent.com/36959754/53750396-f27a3080-3ea9-11e9-8bbd-49dda9684c90.png)

It will [look like this ](https://pay.bitcoinshirt.co/apps/2H9BtB9mfFR84HxHEdBncLvKSB7F/pos)

![2019-03-04_18-17-46](https://user-images.githubusercontent.com/36959754/53750407-f9a13e80-3ea9-11e9-96f5-8ffd98068988.png)

From there, you can try to embed it via one or the other method.

**Comment by Jeans5** [comment]
Alright, thx for the info!
