### ISSUE TITLE
Bylls price index for Canada

### ISSUE THREAD

**Issue by FrancisPouliot** [btcpayserver/btcpayserver#644]
Just noticed there aren't any price indexes for Canada other than Coinsquare.

Bylls price index is very useful since it is the defacto payment processing "spot* price in Canada. Merchants using BTCpay will be able to cash out with bylls, so makes sense they would want to use this price.

API endpoint: https://bylls.com/api/price?from_currency=BTC&to_currency=CAD

The response "to_price " is the BTC -> CAD ($BTC/$CAD) pair 

The reaponse "from_price" is the BTC -> CAD ($CAD/$BTC) pair.

Notes: bull bitcoin has a buy and sell rate. We use the Bylls rate as a substitute for Bitpay's rate. This index takes into account a little bit of liquidity, and it will look at Bitcoin bids and ask to reflect the fact that there is a much larger natural spread on order-book. Using an exchange's "last price" will expose merchant to price swings.

On bullbitcoin.com/rates the buy and sell rates are published.

"We buy" is denoted in our API as: "from_currency=BTC&to_currency=CAD"
"We sell" is denoted in our API as  
""from_currency=CAD&to_currency=BTC"

**Comment by Kukks** [comment]
Relevant: https://github.com/btcpayserver/btcpayserver/issues/623#issuecomment-469147486

**Comment by pavlenex** [comment]
[Done.](https://github.com/btcpayserver/btcpayserver/commit/9a239f99f4ab1f82f98817aef0686267eba5d944)
