### ISSUE TITLE
Cash Payment Method plugin

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#6446]
We've seen requests from users wishing to have Cash as a payment method in their point of sale. We've decided that this will be built as an optional plugin. First, because it's something not every user needs (especially in online), second it can be a great example on how people could build future payment method plugin.

- When user selects cash as a payment method, mark invoice as settled
- Indicate cash icon as $ or similar icon in invoice view 

The only tricky thing @rockstardev and I came across while brainstorming is that our invoice timer isn't really ideal for these scenarios, as there's no expiration time for cash invoices.

We're timing this one as 2.1.0, though it will be available in December as a pre-release plugin and stress tested at one of the conferences via early adopters, allowing us to further enhance it based on real-world feedback.

I've done a bit of googling at noticed Zaprite recently added this functionality which we can be inspired by.

![zaprite-pos-cash@2x](https://github.com/user-attachments/assets/ddf2f4ae-2aa2-4970-906c-25937c0abb08)

**Comment by rockstardev** [comment]
https://github.com/rockstardev/BTCPayServerPlugins.RockstarDev/tree/master/Plugins/BTCPayServer.RockstarDev.Plugins.CashCheckout
