### ISSUE TITLE
[Bug]: Incorrect fiat amount aggregation in Reporting 

### ISSUE THREAD

**Issue by marcinx** [btcpayserver/btcpayserver#6476]
### What is your BTCPay version?

BTCPay Server v2.0.2+b70c004f2

### How did you deploy BTCPay Server?

Self hosted docker deploy, via official bash scripts.

### What happened?

It looks like the "Payments Reporting" is calculating a wrong invoice currency aggregation. I have received several 1000 EUR equivalent in BTC/LTC payments but the aggregation shows 0.32 EUR. Instead of 0.32, the aggregation should show something like 5000 EUR. The EUR amounts on the invoices and, e.g. "legacy invoice export" are shown correctly however.

<img width="1364" alt="Screenshot 2024-12-11 at 4 00 55 PM" src="https://github.com/user-attachments/assets/95ec2a6b-e20d-4df2-99a5-afe3d0c83346">

### How did you encounter this bug?

Reporting -> Payments

### What browser do you use?

Latest Brave (WebKit)

### Additional information

While seemingly broken in Reporting -> Payments, the EUR amounts on the invoices themselves and, e.g. "Reporting -> Legacy Invoice Export" are shown correctly.

<img width="1361" alt="Screenshot 2024-12-11 at 4 04 50 PM" src="https://github.com/user-attachments/assets/0c2afbf7-e6de-4229-bd9e-6acb61758804">

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
To clarify, this isn't a bug. It's a feature request requesting we add fiat value at the time tx was made in the reporting of the wallet.

**Comment by marcinx** [comment]
PS: Just noticed that the bug also exists in the exported CSV file and in the itemized statements (the rows).

EUR amount does not match BTC/LTC payment amount.

<img width="1325" alt="Screenshot 2024-12-16 at 11 14 46 PM" src="https://github.com/user-attachments/assets/297f4584-91da-4cde-b2d8-330bb65fb007" />

<img width="799" alt="Screenshot 2024-12-16 at 11 14 39 PM" src="https://github.com/user-attachments/assets/2b71a374-fd85-488d-baa0-13c426d52d1a" />

**Comment by NicolasDorier** [comment]
@marcinx the rate is weird... 0.01 doesn't seem correct

**Comment by NicolasDorier** [comment]
@marcinx the bug seems to be on the rate.
Do you have the logs of one of those invoices? Is it possible you messed up rate rules?

**Comment by NicolasDorier** [comment]
I just could repro actually!

**Comment by NicolasDorier** [comment]
This was fixed in 2.0.3 (https://github.com/btcpayserver/btcpayserver/pull/6385)
