### ISSUE TITLE
[Bug]: Dashboard does not show fiat balance with LND backend

### ISSUE THREAD

**Issue by dsbaars** [btcpayserver/btcpayserver#6480]
### What is your BTCPay version?

BTCPay Server v2.0.4+6f9e0dca5

### How did you deploy BTCPay Server?

Docker

### What happened?

On the dashboard in the Lightning Balance section, by default it shows the BTC value of the BTC in channels and on-chain. In the top right there is a radio button so show the fiat value of those BTC, with the LND backend nothing happens when you click the fiat currency.

### How did you encounter this bug?

I have multiple stores, the store with the LND backend (REST) is the only one where this is not working.

I tried:
- Setting the default fiat currency to USD (I had it on EUR)
- Completely reinstalling BTCPayServer 2.0.4, this also happens on a fresh instance

With a Blink wallet backend this works fine (but there it only shows BTC in Channels)
With Bree  Greenlight backend this works fine

With Blink and Breez it also shows a chart, with LND backend it does not.

### Relevant log output

```shell
Unfortunately there are no log entries in both the BTCPayServer docker container, and also not in the Web Developer Tools Console.
```

### What browser do you use?

Brave Version 1.73.101 Chromium: 131.0.6778.139 (Official Build) (arm64)

### Additional information

Using LND v0.18.3-beta

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Can you please check the browser console for errors? 

@pavlenex I think this is the same problem you reported with #6458.

**Comment by dsbaars** [comment]
> Can you please check the browser console for errors?

I did, that's what I meant with "Web Developer Tools Console" but unfortunately nothing there (except the blazor info messages)

**Comment by dennisreimann** [comment]
In the browser console, do you see network request for `/api/rates` when switching the rate? If so, are these requests successful and what does the content look like?

What is the store's default fiat currency?

**Comment by dennisreimann** [comment]
Thanks for the detailed report. I think this will be fixed with the pull request I've added.

**Comment by NicolasDorier** [comment]
We removed the chart in 2..0.5, because it wouldn't work with big stores.
We will revisit it later.
