### ISSUE TITLE
i use postgres and newest version of nbxplorer and also newest version of btcpayserver but it show me "no chart" message

### ISSUE THREAD

**Issue by kosuodhmwa** [btcpayserver/btcpayserver#6486]
why? 
![image](https://github.com/user-attachments/assets/ddcf8d62-8f43-48e0-9f62-d10c62092475)

**Comment by kosuodhmwa** [comment]
maybe the problem is not a version one, but because there are not transactions (yet) ?

**Comment by kosuodhmwa** [comment]
thanks you in advance for your feedback(s) :-)

**Comment by kosuodhmwa** [comment]
maybe the question is too complex?

**Comment by dennisreimann** [comment]
How is BTCPay Server deployed and what does the connection string for NBXplorer look like? This is most likely a configuration problem.

**Comment by kosuodhmwa** [comment]
Hi Dennis

Thank you very very much for your feedback. :-) 

I used postgres from begin, i never used an earlier version that used that built-in, "embedded" other database called "DBTrie"

**i use that script to start nbx:**

_root@debian12-btc-node:~# cat start-nbx.sh
set -x;
cd ~/;
cd NBXplorer;
./run.sh --chains=btc --network=Main --postgres "Username=postgres;password=MY_PASSWORD;Host=127.0.0.1;Port=5432;Database=nbxplorer";
exit 0;_


**and that to start btcps:**

_root@debian12-btc-node:~# cat start-btcps.sh
set -x;
cd ~/;
cd btcpayserver;
./run.sh --port 8080 --bind 0.0.0.0 --postgres "Username=postgres;password=MY_PASS;Host=127.0.0.1;Port=5432;Database=btcpayserver";
exit 0;_


**BTW.:** There are some inconsistencies in the manual of both products - eg the DB username var is NOT "User ID" so something else - its "Username" and nothing else - at least with the most current versions ob btcps, nbx & postgres... 


-> https://github.com/btcpayserver/btcpayserver
and "dbtrie" is also not supported anymore (due to transaction race conditions so i read?) - so i would correct that things
https://docs.btcpayserver.org/Deployment/ManualDeployment/ 


With best regards
Jan

**Comment by kosuodhmwa** [comment]
https://github.com/dgarage/NBXplorer/issues/500

**Comment by pavlenex** [comment]
Closing since it's already posted on NBX.

**Comment by kosuodhmwa** [comment]
ok
