### ISSUE TITLE
[Bug]: Admin cannot see invoices of users

### ISSUE THREAD

**Issue by pretyflaco** [btcpayserver/btcpayserver#6489]
### What is your BTCPay version?

BTCPay Server v2.0.4+6f9e0dca5

### How did you deploy BTCPay Server?

Docker on VPS

### What happened?

It is my understanding that logged in as admin > server settings > users > details > store should show invoices of tenant user, but invoices are empty for all users 
![image](https://github.com/user-attachments/assets/2524aa22-fbe0-43c1-a83c-e27f74813534)

### How did you encounter this bug?

as admin > server settings > users > details > store

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
I can't replicate this on 2.0.4.

 @petzsch @TChukwuleta perhaps you could try?

**Comment by petzsch** [comment]
I can confirm this behaviour:

Created a separate user account and a store and created an unpaid/new invoice.

Logged back in as admin and followed the steps above, only to find an empty invoice list:

I think as admin we should be able to see the invoices of every user on our server.

![grafik](https://github.com/user-attachments/assets/24863f40-3292-4495-9d29-3d2265561d9b)

**Comment by dennisreimann** [comment]
My two sats: The underlying issue is a permissions problem, which we try to address with the [issues layed out here](https://github.com/btcpayserver/btcpayserver/issues/396#issuecomment-1898361454).
