### ISSUE TITLE
Inventory limit for store item

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#649]
Allow users to produce invoices for a store "item" up to a certain quantity. 

Use case example: ticket/event sales of limited quantity

Maybe it can be done with PoS?

**Comment by pavlenex** [comment]
We should add some sort of quantity limit for items when refactoring the PoS.

**Comment by royserpa** [comment]
> 
> 
> Allow users to produce invoices for a store "item" up to a certain quantity.
> 
> Use case example: ticket/event sales of limited quantity
> 
> Maybe it can be done with PoS?

You can keep track of that from your website's server. You could ask, on your site, how many tickets/items they would like to buy and if the number of tickets/items are less or equal than the ones available, send the users through a form and generate an invoice in your btcpayserver instance.

I think lots of these problems can be handled directly from the websites' server through databases and not really have to do that on the btcpayserver server.

**Comment by pavlenex** [comment]
@royserpa  Not all people use BTCPay + website. PoS is one of many examples of why such structure is needed.

**Comment by royserpa** [comment]
> 
> 
> @royserpa Not all people use BTCPay + website. PoS is one of many examples of why such structure is needed.

Wouldn't that affect the btcpayserver performance? Like, I think the server where btcpayserver is hosted on would be more efficient if it's only job is to handle btc payments, but just my humble opinion.

**Comment by pavlenex** [comment]
It wouldn't, btcpay is way more than just a payment processor.
