### ISSUE TITLE
[Bug]: [BTCPAY_ROOTPATH=/subdir] conflicts with "Forms" on checkout

### ISSUE THREAD

**Issue by mar101xy** [btcpayserver/btcpayserver#6493]
### What is your BTCPay version?

Tested on:
v2.0.4
v2.0.3

### How did you deploy BTCPay Server?

Tested on 2 different servers:
Ubuntu 24.04.1 LTS
Ubuntu 24.10

Both:
Docker Installation

1st Server:
BTCPAY docker Only listening on ports 80 & 443

2st Server:
Nginx on server Listening on ports 80 & 443
BTCPAY docker 

Tested:
export BTCPAY_ROOTPATH=/btcpay
export BTCPAY_ROOTPATH=btcpay.mydomain.com
export BTCPAY_ROOTPATH=mydomain.com

### What happened?

When i set:
`export BTCPAY_ROOTPATH=/btcpay`

When i update my store in:
`Update Point of Sale `

The section:
` Checkout - Request customer data on checkout`
 
 To:
`Request email address only `

or any other form i get an error message:
`404 - Page not found`

I tried different forms, custom forms and i always get the 404 message. 
If i disabled the form. I get an invoice and no error message.

This error only happens when i set my root path to a sub directory.
`export BTCPAY_ROOTPATH=/btcpay`

I tested with root domain and sub domain and the error does not happen
`export BTCPAY_ROOTPATH=btcpay.mydomain.com`
`export BTCPAY_ROOTPATH=mydomain.com`

### How did you encounter this bug?

I wanted to use the sub dir for my btcpay server
`mydomain.com/btcpay `

I need forms during checkout for shipping & email but the bug stops me from using it. 

Here is a video:

https://github.com/user-attachments/assets/d0361197-e6ff-47f2-8e06-29c44a9f7c4d

you cannot see the url in the video but the url looks like this:

store:
`https://mydomain.com/btcpay/apps/2Avkee3q57MS9e5ZNhbtJT9VSpAU/pos`

click buy - goes to form:
`https://mydomain.com/btcpay/apps/2Avkee3q57MS9e5ZNhbtJT9VSpAU/pos/form`

click submit - error page:
`https://mydomain.com/btcpay/btcpay/apps/2Avkee3q57MS9e5ZNhbtJT9VSpAU/pos`

### What browser do you use?

firefox 133.03

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
@dennisreimann can you look into this one?
