### ISSUE TITLE
Update server (manual deployment) not working

### ISSUE THREAD

**Issue by k3tan25** [btcpayserver/btcpayserver#650]
I've got a manual deployment of btcpayserver on Ubuntu 18.04. Not using docker.
I'm trying to update the server through the web interface (Server Settings -> Maintenance -> Click here to update your server)
Logs show this:
```
2019-03-06 14:08:03.859 +11:00 [INF] Running SSH command: sudo bash -c '. /etc/profile.d/btcpay-env.sh && nohup btcpay-update.sh > /dev/null 2>&1 & disown'
2019-03-06 14:08:03.869 +11:00 [INF] SSH command executed: 

```
These files (btcpay-env.sh and btcpay-update.sh) do not exist in my /etc/profile.d directory.
Please advise?

**Comment by astupidmoose** [comment]
How did you initially install btcpayserver? 

As far as I know, updating from within the software only works on a docker installation. 

If you used git, typically what I do is power down btcpay in the command lines, git pull for newest updates, checkout on current version and restart btcpay.

**Comment by Kukks** [comment]
This is not supported. If you built it manually, you have to update manually.

**Comment by k3tan25** [comment]
thanks for the info. yes I used git to install. could you please take me through the commands?
So far I've gone into my ~/btcpayserver folder
`git pull`

how do I checkout?

`git checkout`?
