### ISSUE TITLE
Remove BG as a supporter

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#6500]
BG http://bailliegifford.com  is no longer supporter, so we should remove them from standard places. 

Example of what needs to be removed when adding/removing supporter. 

Good first issue.

https://github.com/btcpayserver/btcpayserver/pull/5891

**Comment by rockstardev** [comment]
Whoever is handling this issue, please ensure that all the PRs across the repositories are handled and linked here. So:

- This repo
- https://github.com/btcpayserver/blog
- https://github.com/btcpayserver/btcpayserver-doc
- https://github.com/btcpayserver/foundation.btcpayserver.org

Take a look at this issue as template:
https://github.com/btcpayserver/btcpayserver/issues/6143

**Comment by pavlenex** [comment]
Hey @ConstantineGhost we also need to remove it from here https://directory.btcpayserver.org

**Comment by ConstantineGhost** [comment]
@pavlenex New PR open
