### ISSUE TITLE
Inconsistent responsiveness of the wallet dashboard label

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#6501]
The labels on the dashboard and /wallet aren't consistent in terms of responsiveness. We should probably make dashboard labels look like the wallet labels on smaller devices.

![image](https://github.com/user-attachments/assets/8cb744fc-ee8d-47fa-bbb0-50f853f37be1)

![image](https://github.com/user-attachments/assets/350a8edc-8430-4ff2-859d-de69a49b0f1a) 

Good first issue for developers wanting to get started with contributing to the project.

**Comment by dennisreimann** [comment]
I think this is something I recently broke with #6366.
