### ISSUE TITLE
externalurl option still present in --help output

### ISSUE THREAD

**Issue by enorrmann** [btcpayserver/btcpayserver#658]
I think this option was removed, but still showing in --help output
Also, I'm not sure how handle reverse proxys without this option

**Comment by NicolasDorier** [comment]
@enorrmann I removed the option. BTCPay just need your reverse proxy to handle the headers right (see https://github.com/btcpayserver/btcpayserver-doc/blob/master/FAQ/FAQ-Deployment.md#btcpay-is-expecting-you-to-access-this-website-from)
