### ISSUE TITLE
Credit card payment excepted terminal

### ISSUE THREAD

**Issue by deedeejo** [btcpayserver/btcpayserver#670]

**Comment by Kukks** [comment]
You can do better than that to describe what and why you want this.

**Comment by pavlenex** [comment]
Hi @deedeejo, when submitting a feature request, please follow the[ feature request format](https://github.com/btcpayserver/btcpayserver/blob/master/.github/ISSUE_TEMPLATE/feature_request.md) so that we can understand your request better.

**Comment by pavlenex** [comment]
Closing this one for now, until more information is provided.
