### ISSUE TITLE
Checkout Experience: configurable contact & refund email label text and description

### ISSUE THREAD

**Issue by fraktar** [btcpayserver/btcpayserver#671]
**Is your feature request related to a problem? Please describe.**
Store owners cannot edit the text for `Store > Settings > Checkout Experience > Requires a Refund Email` option.

**Describe the solution you'd like.**
Allowing contact & refund email label text/description to be configurable via the dashboard would be nice.

**Provide examples.**
The current text showed to clients on checkout:
> **Contact & Refund Email**
> Please provide an email address below. We'll contact you at this address if there is an issue with your payment.

**Comment by pavlenex** [comment]
Hi @fraktar , when submitting a feature request, please follow the[ feature request format](https://github.com/btcpayserver/btcpayserver/blob/master/.github/ISSUE_TEMPLATE/feature_request.md) so that we can understand your request better.

**Comment by fraktar** [comment]
@pavlenex sorry for that, I thought this was pretty clear an straightforward. **Updated post.**

And #505 might be related, but not quite what I was referring to. 

If you go to Store > Settings > Checkout Experience > Tick the "Requires a Refund Email" box, clients will be asked for an email on checkout when making the payment. 

There is a text there that *could* be editable by store owners, that's all.

**Comment by pavlenex** [comment]
That's much clearer now, thanks, will label accordingly.

**Comment by lrgeoemtry** [comment]
looking forward to this

**Comment by pavlenex** [comment]
#4137
