### ISSUE TITLE
username stays the same after changing email

### ISSUE THREAD

**Issue by cryptofuture** [btcpayserver/btcpayserver#673]
After I update email, username stays the same. And this is means to login I should use old email. 

**Your environment**
* `53cecc8c8a41033a88594b14521d3699f1a42d32`

**To Reproduce**
1. Go to `/Manage/Index`
2. Change email and confirm
3. Follow link in the email
4. New email used for password reset and notifications, but to actually login I still need to use the old one, as it actually not a email, but username on the login page

**Expected behavior**
username should be changed to the new email too

**Actual behavior**
username stays the same, and this is means I still need to use old details to login

**Comment by NicolasDorier** [comment]
I am unsure I can fix that at all. We rely on ASP.NET infrastructure to do this kind of stuff, this is fast development but hard to customize.
