### ISSUE TITLE
Payments from lightning don't show up in the UI.

### ISSUE THREAD

**Issue by Kixunil** [btcpayserver/btcpayserver#676]
**Describe the problem/bug**
When the customer pays with lightning, the invoice is correctly shown, the payment goes through, but the success message is not shown in the UI.

**Your environment**
* Version of BTCPay Server: 1.0.3.79 (commit 09837966b9e397a3ed6d12ec8da8a052763d4774)
* Deployment method: Manual compilation & installation
* Other relevant environment details: lnd version 0.5.2-99-beta-833-gcee18892b552ea2ad6e2ce6033302ea89f9a2d0d

**Logs (if applicable)**
"Error: File Logging Option not specified" - how do I configure the log file?

**To Reproduce**
1. Create invoice (using PoS in my case)
2. Pay the invoice using LN
3. The payment leaves the wallet and is received by lnd
4. Btcpayserver invoice window times out

**Expected behavior**
Success message shows up immediately after LND receives the payment.

**Actual behavior**
Invoice times out

**Additional context**
Could this be somehow related to #585, since it started happening after it was resolved - maybe the API changed somewhere else as well?

**Comment by britttttk** [comment]
Update your BTCPay (or any reason in particular for not updating?). When you say "the payment goes through" are you certain the entire invoice amount is being paid? Is it happening regardless of which wallet the user pays from?

**Comment by NicolasDorier** [comment]
@Eskyee got same problem. Was it on LND? did you fixed it?

**Comment by NicolasDorier** [comment]
@Kixunil no error in the logs either?

**Comment by NicolasDorier** [comment]
`docker logs generated_btcpayserver_1`

**Comment by Eskyee** [comment]
still get the same problem @NicolasDorier 
paid, but not showing up

**Comment by Eskyee** [comment]
Sending a spark wallet payment "c-lightning"  to my LND luna node Works @NicolasDorier payment shows up in checkout and invoices ok!!

**Comment by Eskyee** [comment]
invoice status complete...

**Comment by Eskyee** [comment]
Sending a Zap wallet payment "LND" to my Spark c-lightning azure node, Payment received by my spark wallet, but Payment not showing up in Check Out UI or Invoice Status still says New @NicolasDorier  that's my problem still !!

**Comment by Eskyee** [comment]
type=clightning;server=unix://etc/clightning_bitcoin/lightning-rpc 
My Connection string

**Comment by talentpierre** [comment]
I've got the same problem.
the btcpayserver was set up on luna node.  i connect my local raspiblitz node to a different account on this btcpayserver. the situation is the same. i create an invoice, the invoice gets paid but the checkmark doesn't show up. in btcpayserver the bookkeeping marks that payment as expired but the node gets the payment instantly.

**Comment by NicolasDorier** [comment]
@talentpierre with clightning or lnd?

**Comment by NicolasDorier** [comment]
Does restarting btcpay with btcpay-restart.sh solve the situation?

**Comment by Eskyee** [comment]
@NicolasDorier 
c-lightning for me.
Does restarting btcpay with btcpay-restart.sh solve the situation?
Not for me Nicolas

**Comment by talentpierre** [comment]
i use lnd. 
no, unfortunately it doesn't work.

**Comment by NicolasDorier** [comment]
@talentpierre @Eskyee can you share the logs with me when you start btcpay?

**Comment by talentpierre** [comment]
how do i do that? is there a tutorial for the logs?

**Comment by Eskyee** [comment]
sent you my logs in slack @NicolasDorier  

via ssh terminal 
@talentpierre  
docker ps
docker logs yourcontainernumberID

or check  your luna node logs

**Comment by NicolasDorier** [comment]
Does all of you sharing the btcpay server with other people?

**Comment by NicolasDorier** [comment]
If any of you can build their own version, please try on master

**Comment by Eskyee** [comment]
waiting on stable, yes I'm sharing btcpayjungle server with other people.

**Comment by Eskyee** [comment]
updated to stable branch @NicolasDorier btcpayjungle
Off-Chain payments are now fully working for me after .89 update

thanks if update working for @talentpierre we can close this issue.

**Comment by NicolasDorier** [comment]
mmmh I don't think I released my fix lol

**Comment by NicolasDorier** [comment]
yeah, .89 do not have my fix.

**Comment by Eskyee** [comment]
well Payments from lightning now show up in the UI, 
strange ?? lol but I`m happy it showing up in invoices now and checkout ;)

**Comment by Eskyee** [comment]
I send you my logs in slack @NicolasDorier

**Comment by talentpierre** [comment]
@NicolasDorier problem also solved. great. thank you.
 what did you change? what was the problem?

**Comment by NicolasDorier** [comment]
@talentpierre if you updated on master, I completely refactored the detection of lightning payments in a better way. I have not identified the root of the issue but the new code is more obviously correct.

**Comment by NicolasDorier** [comment]
I pushed .91 the bug should be properly fixed with it.

**Comment by Kixunil** [comment]
Hi, I'm very sorry for being this late, I was very overwhelmed and didn't have time to even test it. I did it and now it works perfectly.

Thank you very much for this and all other work you're doing! It helps a lot!
