### ISSUE TITLE
Pay Button - Type (Custom Amount, Slider)

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#678]
**Is your feature request related to a problem? Please describe.**
We should extend the pay button to have a button type such as:

- Fixed
- Custom
- Slider 

Fixed amount for receiving donations do not make much sense. The slider is really optional, I personally don't see much need for it, but customized widgets like we have on our site would certainly please some people.

**Describe the solution you'd like**
Add Button type option below the "Button Size" and above "Payment Notifications".
Give the user a clear choice on what each type does.

**Describe alternatives you've considered**
 For now, people use the workaround of [customizing the PoS](https://docs.btcpayserver.org/faq-and-common-issues/faq-apps#how-to-create-pay-button-with-a-custom-amount)

**Provide examples**
One of the centralized payment providers has[ something similar](https://coingate.com/button) it's a bit cluttered IMO, but gives a great example of what I mean.

**Additional context**
![button type](https://user-images.githubusercontent.com/36959754/54360664-a6777a80-4665-11e9-8dc5-081fd9730457.PNG)

![slider (maybe)](https://user-images.githubusercontent.com/36959754/54360808-f6eed800-4665-11e9-9918-c986d6c43f3d.PNG)

**Comment by Dolu89** [comment]
- For slider, do we need to add an extra field to define MIN and MAX amount?

**Comment by pavlenex** [comment]
@Dolu89 I guess we do, I'm not really sure if slider makes sense, but as I said it may work for some people.

**Comment by Dolu89** [comment]
@pavlenex Ok, let's see what I can do :)

**Comment by Dolu89** [comment]
I think you can close this issue now :)

**Comment by pavlenex** [comment]
Wooho, thanks @Dolu89
