### ISSUE TITLE
Numpad not showing on POS app

### ISSUE THREAD

**Issue by songproducer** [btcpayserver/btcpayserver#680]
**Describe the problem/bug**
Numpad does not show on POS app when price field is focused.

**Your environment** iOS iPhone 7s+
* Version of BTCPay Server: Latest
* Deployment method: lunanode

Maybe inserting these attributes into class "js-product-price form-control mb-2" will work:
`<input type="number" min="0" inputmode="numeric" pattern="[0-9]*"/>`

**Comment by bolatovumar** [comment]
I've had to apply the hack proposed by @songproducer on my projects as well. It's a PITA to get consistent behaviour for number input fields across devices. This is what I normally do:
```html
<input
   inputmode="numeric"
   type="number"
   pattern="\d*" />
```
