### ISSUE TITLE
Option to set a minimal fee/byte

### ISSUE THREAD

**Issue by songproducer** [btcpayserver/btcpayserver#681]
**Is your feature request related to a problem? Please describe.**
I want to help retail merchants accept Bitcoin but 0 confirmation payments will be too risky to accept if they have a low fee. Waiting for 1 confirmation is obviously not a workable solution for retail.

**Describe the solution you'd like**
A dynamic minimum satoshi fee/byte perhaps gotten using the Earn API?
https://bitcoinfees.earn.com/api

**Describe alternatives you've considered**
I'm not a coder but I've considered only accepting lightning payments, however this is not ideal for merchants wanting to accept Bitcoin.

**Comment by ser** [comment]
why waiting for 1 confirmation is not workable for retail? everyone who is using bitcoin understands confirmations.

earn is not the only source of fees, the network itself knows the average fee

**Comment by songproducer** [comment]
>why waiting for 1 confirmation is not workable for retail? everyone who is using bitcoin understands confirmations.

Because retail merchants who might want to accept Bitcoin will not want to make their customers wait around for the confirmation.

>earn is not the only source of fees, the network itself knows the average fee

Ok, can use the network average fee

**Comment by ser** [comment]
use lighthing then

**Comment by songproducer** [comment]
I will try to get customers to pay with lightning, but for people who haven't set up a lightning wallet yet, an option to accept 0 confirmations would go a long way for adoption.

**Comment by ser** [comment]
why you can't just write with <h1> it on your payment page, that they should pay XXX fee?

**Comment by songproducer** [comment]
Because people will pay wrong fees anyway (unintentionally or maliciously)

**Comment by ser** [comment]
But why? They are unable to understand written text or you assume that majority will cheat on you to save pennies?

**Comment by songproducer** [comment]
I assume there will be a few who will try to cheat the merchant, which will inevitably come out of my pocket (and it will be significantly more than pennies).

**Comment by ser** [comment]
OK, so i am afraid the only solution is lightning. 

btc or mastercard - both can be cheated with reverse charge or 0fees

**Comment by JeffVandrewJr** [comment]
@ser @songproducer Create the invoice with `fullNotifications` set to `true`. You'll then get a payment notification as soon as the guy pays, before confirmation. You can then send a receipt. 

You'll get a second notification on confirmation. You can then ship the product.

**Comment by pavlenex** [comment]
@JeffVandrewJr The original request is for merchants in retail, for in-person transactions. 

I personally don't see how fees can help with 0-confirmations, but we have something called `network fee` maybe that can be hacked in a way to suit @songproducer's particular use case, unfortunately, it's such an isolated use case that it probably has to be done on his end.

**Comment by JeffVandrewJr** [comment]
@pavlenex @songproducer I misunderstood the use case. My bad!

**Comment by pavlenex** [comment]
Closing this one, as I think it's a real niche case where a user who needs this needs to add it to their fork, I don't see how this benefits general users.
