### ISSUE TITLE
Feature Request: Show the NodeInfo on Lightning page

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#69]
@lepipele the unified invoice rfc is meant to make this useless, but meanwhile we need to expose how to create a channel with the merchant in the lightning payment method like:

02302abe6c40816525d43f5fd9352f3474dee5656786b26dba42b20369f2e4409a@52.232.97.9:9736

If you take care of the Checkout UX for exposing this data, I can easily plug this info in the page.

**Comment by lepipele** [comment]
Sure, let's do it - discuss this soon.

**Comment by lepipele** [comment]
Done in last batch of PRs
