### ISSUE TITLE
DASH NOT SYNCRHONIZED

### ISSUE THREAD

**Issue by darkban** [btcpayserver/btcpayserver#690]
Hello i have last version installed and have a problem 2 weeks about... not synchronize whit dash node... how to fix? before the latest updates it worked great ... it's not about waiting because it's been in this state for 2 weeks
![dash problem](https://user-images.githubusercontent.com/32014414/54493409-07a28680-48d0-11e9-967e-6667bb813226.PNG)

**Comment by Kukks** [comment]
Ping @snogcel

**Comment by snogcel** [comment]
Hello @darkban are you using Docker? FYI this week I'm going to be updating our docker image to use Dash Core v0.13.2 (https://blog.dash.org/dash-core-v0-13-2-on-mainnet-60818d2c1a3) and this might be a good option for you. In the meantime, I'll do some testing as I set up this up to see if I can reproduce the issue you reported.

**Comment by darkban** [comment]
yes use docker... thanks

**Comment by astupidmoose** [comment]
I can't replicate on my docker setup, dash is working fine. 

@darkban was dash part of the initial setup? I've noticed that if you install more then 2 coins on the initial install it often ends up crashing one or more nodes due to memory requirements and they need to be rebooted once the other chains are synched so they can then hog all the memory.

**Comment by darkban** [comment]
continue not work dash also whit the last updates

![screen](https://user-images.githubusercontent.com/32014414/55686828-62c31880-5966-11e9-96a7-50408bbd76f8.png)

**Comment by darkban** [comment]
> I can't replicate on my docker setup, dash is working fine.
> 
> @darkban was dash part of the initial setup? I've noticed that if you install more then 2 coins on the initial install it often ends up crashing one or more nodes due to memory requirements and they need to be rebooted once the other chains are synched so they can then hog all the memory.

I have a fairly large server, and before the last few updates all three worked without any problems

**Comment by pavlenex** [comment]
Has this been resolved?
