### ISSUE TITLE
Pairing Link that Locks in Merchant Facade

### ISSUE THREAD

**Issue by JeffVandrewJr** [btcpayserver/btcpayserver#692]
In apps that pair to BTCPay, right now we can give the user the link `<host>/api-tokens` and it conveniently takes them right to pairing. However many users get confused by the `facade` drop-down. 

It's a minor thing, but it would be cool to have it so a different sub-URI,  (maybe `<host>/merchant-api-tokens`) would take them to a different version of the pairing page where they are probibited from selecting a facade and `merchant` is just assumed. One less thing for them to screw up.

**Comment by NicolasDorier** [comment]
Fixed by 4067d4b00f0e2cffedffa06600f791d8efaed974
