### ISSUE TITLE
E-mail invoice notifications on a store-level

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#693]
**Is your feature request related to a problem? Please describe.**
Currently, if people aren't using CMS, it's impossible for them to get/send e-mail notifications for different invoice status. Of course, technically advanced users can use the API, but noobs have no way of setting that up.

**Describe the solution you'd like**
We now have SMTP settings at a store level and should extend the emails to be sent for different invoice statuses. Ideally it should be highly-customizable, but for starters, a standardized messages for each invoice status is fine imo.

**Provide examples**
This solution is mostly for people using BTCPay Apps.

Use case 1: Casa Hodl store uses payment button for their orders. They need to check BTCPay constantly to know when to ship the order.
Use case 2: Charity uses payment button to collect donation and wants to send thank you message to whoever donates.
Use case 3: Crowdfunding user wants to get notification when a new donation is received.

**Additional context**
Related #172 #468 #683

**Comment by Kukks** [comment]
Hey, this should actually be possible for apps already. I added the notificationEmail config to both crowdfund and Pos. Can you confirm?

**Comment by pavlenex** [comment]
@Kukks I guess you're referring to this one in CF
![Screen Shot 2019-04-19 at 16 13 44](https://user-images.githubusercontent.com/36959754/56427996-27a5db00-62be-11e9-9ea9-36dadfe513d0.png)

And this one for PoS
![Screen Shot 2019-04-19 at 16 14 53](https://user-images.githubusercontent.com/36959754/56428033-486e3080-62be-11e9-9f36-08004a28eb6d.png)

So we need to make it clearer that user needs to configure SMTP settings on a store level before just pasting e-mail here. People will just paste e-mail and then complain it does not work.
