### ISSUE TITLE
Can't start server over Https

### ISSUE THREAD

**Issue by sigHash** [btcpayserver/btcpayserver#696]
Hi, 

I started BTCPayserver on my machine with 

```
BTCPAYGEN_REVERSEPROXY="nginx"
BTCPAY_PROTOCOL="https"
NBITCOIN_NETWORK="testnet"
BTCPAY_HOST="test.btcpay.mydomain.com"
....
```

I have my domain name pointing to my IP address and still getting this error:

```
BTCPay is expecting you to access this website from http://test.btcpay.mydomain.com/. If you want to change this expectation:
Either starts BTCPay with --externalurl http://test.btcpay.mydomain.com/
Or, if using docker-compose deployment, setting environment variable BTCPAY_PROTOCOL=http and BTCPAY_HOST=test.btcpay.mydomain.com

```

I tried to restart lets-encrypt container and waited for half an hour but I still get this error.

P.S. My machine is behind a wifi router.

**Comment by Kukks** [comment]
Are you on the latest version?

**Comment by Kukks** [comment]
We got rid of the ExternalUrl flag a few versions back.

**Comment by sigHash** [comment]
my bad.
BTCPay moves fast :D
