### ISSUE TITLE
Unable to connect to lnd when IPv6 is enabled

### ISSUE THREAD

**Issue by jmaurice** [btcpayserver/btcpayserver#702]
[Issue]
When lnd.conf contains IPv6 addresses, btcpayserver returns a parse error for API requests from lnd.

[How to Reproduce]
1) Add `externip=2600::` to lnd.conf and restart lnd
2) Try to add `type=lnd-rest;server=hxxps://1.2.3.4:8080/;macaroonfilepath=/etc/foo/admin.macaroon;allowinsecure=true` to btcpayserver web configuration

[Expected Result]
lnd is connected

[Actual Result]
Error while connecting to the API (Input string was not in a correct format.)

**Comment by NicolasDorier** [comment]
Can you post this on LND repo? This is not a bug from btcpay.
