### ISSUE TITLE
BTCPayServer on ROCKPro64 (aarch64): docker issue with setup script

### ISSUE THREAD

**Issue by Xaspr** [btcpayserver/btcpayserver#714]
**Describe the problem/bug**
I can't run . ./btcpay-setup.sh -i successfully. It has to do with some docker issue on this system, but I can't figure out how to fix it. Any help would be awesome. 

**Your environment**
* Version of BTCPay Server: v1.03.89
* Deployment method: Hardware Deployment
* Other relevant environment details: -

**Logs (if applicable)**

> Parameters passed:
> BTCPAY_PROTOCOL:https
> BTCPAY_HOST:xxx
> LIBREPATRON_HOST:
> WOOCOMMERCE_HOST:
> BTCPAY_HOST_SSHKEYFILE:
> LETSENCRYPT_EMAIL:
> NBITCOIN_NETWORK:mainnet
> LIGHTNING_ALIAS:
> BTCPAYGEN_CRYPTO1:btc
> BTCPAYGEN_CRYPTO2:
> BTCPAYGEN_CRYPTO3:
> BTCPAYGEN_CRYPTO4:
> BTCPAYGEN_CRYPTO5:
> BTCPAYGEN_CRYPTO6:
> BTCPAYGEN_CRYPTO7:
> BTCPAYGEN_CRYPTO8:
> BTCPAYGEN_CRYPTO9:
> BTCPAYGEN_REVERSEPROXY:nginx
> BTCPAYGEN_LIGHTNING:lnd
> BTCPAYGEN_ADDITIONAL_FRAGMENTS:opt-save-storage-xs;opt-save-memory
> BTCPAY_IMAGE:
> ACME_CA_URI:https://acme-v01.api.letsencrypt.org/directory
> Additional exported variables:
> BTCPAY_DOCKER_COMPOSE=/root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml
> BTCPAY_BASE_DIRECTORY=/root/BTCPayServer
> BTCPAY_ENV_FILE=/root/BTCPayServer/.env
> BTCPAYGEN_OLD_PREGEN=false
> BTCPAY_SSHKEYFILE=
> BTCPAY_SSHTRUSTEDFINGERPRINTS:
> 
> BTCPay Server environment variables successfully saved in /etc/profile.d/btcpay-env.sh
> 
> BTCPay Server docker-compose parameters saved in /root/BTCPayServer/.env
> 
> Using default tag: latest
> Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
> docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
> See 'docker run --help'.
> Adding btcpayserver.service to systemd
> BTCPay Server systemd configured in /etc/systemd/system/btcpayserver.service
> 
> BTCPay Server starting... this can take 5 to 10 minutes...
> Failed to start btcpayserver.service: Unit docker.service is masked.
> BTCPay Server started
> -su: /usr/local/bin/docker-compose: No such file or directory
> grep: /root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml: No such file or directory
> grep: /root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml: No such file or directory
> grep: /root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml: No such file or directory
> grep: /root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml: No such file or directory
> grep: /root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml: No such file or directory
> grep: /root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml: No such file or directory
> grep: /root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml: No such file or directory
> grep: /root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml: No such file or directory
> grep: /root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml: No such file or directory
> grep: /root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml: No such file or directory
> grep: /root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml: No such file or directory
> grep: /root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml: No such file or directory
> grep: /root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml: No such file or directory
> grep: /root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml: No such file or directory
> grep: /root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml: No such file or directory
> grep: /root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml: No such file or directory
> grep: /root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml: No such file or directory
> Installed btcpay-down.sh to /usr/bin: Command line for stopping all services related to BTCPay Server
> Installed btcpay-restart.sh to /usr/bin: Command line for restarting all services related to BTCPay Server
> Installed btcpay-setup.sh to /usr/bin: Command line for restarting all services related to BTCPay Server
> Installed btcpay-up.sh to /usr/bin: Command line for starting all services related to BTCPay Server
> Installed btcpay-update.sh to /usr/bin: Command line for updating your BTCPay Server to the latest commit of this repository
> Installed changedomain.sh to /usr/bin: Command line for changing the external domain of your BTCPay Server

**To Reproduce**
Install BTCPayServer using the general Hardware Deployment, on a ROCKPro64 (aarch64) with Ubuntu 18.04.2 (bionic). After following the instructions on https://github.com/btcpayserver/btcpayserver-doc/blob/master/HardwareDeployment.md, launching the setup script leads to an error. 

**Expected behavior**
Installation guided by btcpay-setup.sh, including correct docker implementation. 

**Actual behavior**
Error, see log above. 

**Additional context**
I tried finding different docker installation methods, but this doesn't seem to work. I keep running into problems with running the script. 
How could I fix this? Is there some different docker installation required to use BTCPay on this system?

**Comment by NicolasDorier** [comment]
@Xaspr your problem probably come because you installed docker for aarch64, while you need to install docker for arm32.

Please uninstall docker, uninstall docker-compose and just run the setup which will install the correct binaries.

**Comment by Xaspr** [comment]
Thanks Nicolas. Is there any way to force the setup script to install docker for arm32? It seems that after docker is completely removed, the setup script does run a bit further but it tries to use docker-compose-builder for aarch64. Then I get this: 


> BTCPay Server environment variables successfully saved in /etc/profile.d/btcpay-env.sh
> 
> BTCPay Server docker-compose parameters saved in /root/BTCPayServer/.env
> 
> Trying to install docker for armv7 on a aarch64 board...
> OK
> Hit:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
> Hit:2 http://ppa.launchpad.net/ayufan/rock64-ppa/ubuntu bionic InRelease
> Hit:3 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
> Hit:4 https://download.docker.com/linux/ubuntu xenial InRelease
> Hit:5 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
> Hit:6 http://ppa.launchpad.net/ayufan/all-ppa/ubuntu bionic InRelease
> Hit:7 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
> Hit:8 https://deb.torproject.org/torproject.org bionic InRelease
> Get:9 http://deb.ayufan.eu/orgs/ayufan-rock64/releases  InRelease [1335 B]
> Fetched 1335 B in 3s (482 B/s)
> Reading package lists... Done
> Hit:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
> Hit:2 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
> Hit:3 http://ppa.launchpad.net/ayufan/rock64-ppa/ubuntu bionic InRelease
> Hit:4 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
> Hit:5 http://ppa.launchpad.net/ayufan/all-ppa/ubuntu bionic InRelease
> Get:6 http://deb.ayufan.eu/orgs/ayufan-rock64/releases  InRelease [1335 B]
> Hit:7 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
> Hit:8 https://download.docker.com/linux/ubuntu xenial InRelease
> Hit:9 https://deb.torproject.org/torproject.org bionic InRelease
> Fetched 1335 B in 3s (461 B/s)
> Reading package lists... Done
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package docker-ce:armhf
> Trying to install docker-compose by using the docker-compose-builder (aarch64)
> -su: /usr/bin/docker: No such file or directory
> mv: cannot stat 'dist/docker-compose': No such file or directory
> chmod: cannot access '/usr/local/bin/docker-compose': No such file or directory
> Failed to install docker
>

**Comment by NicolasDorier** [comment]
@Xaspr  normal, it should install docker for you, else try manually this

```bash
echo "Trying to install docker for armv7 on a aarch64 board..."
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RELEASE=$(lsb_release -cs)
if [[ "$RELEASE" == "bionic" ]]; then
    RELEASE=xenial
fi
add-apt-repository "deb https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $RELEASE stable"
apt-get update -y
apt-get install -y docker-ce:armhf
```

**Comment by Xaspr** [comment]
This script leads to the same:
> E: Unable to locate package docker-ce:armhf
> Failed to install docker

Even though the script does add the repository: 
> Hit:8 https://download.docker.com/linux/ubuntu xenial InRelease

I'd love to know how to fix this if there's another manual way.

**Comment by NicolasDorier** [comment]
I am myself running btcpay on ROCKPro64 so this is quite strange. And with ubuntu. Will take a look when I go to the office.

**Comment by NicolasDorier** [comment]
Any error somewhere during `apt-get update -y` by any chance?

**Comment by NicolasDorier** [comment]
Also the docker-ce:armhf is definitively in https://download.docker.com/linux/ubuntu

**Comment by NicolasDorier** [comment]
Ah try to run `dpkg --add-architecture armhf`  and run again

**Comment by NicolasDorier** [comment]
Can you try this
```bash
echo "Trying to install docker for armv7 on a aarch64 board..."
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RELEASE=$(lsb_release -cs)
if [[ "$RELEASE" == "bionic" ]]; then
    RELEASE=xenial
fi
if [ -x "$(command -v dpkg)" ]; then
    dpkg --add-architecture armhf
fi
add-apt-repository "deb https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $RELEASE stable"
apt-get update -y
apt-get install -y docker-ce:armhf
```

**Comment by Xaspr** [comment]
Thanks again Nicolas. Awesome part: your latest part of the script works. And so does the setup script after that. Weird that the right architecture was not in dpkg. 

But I'm still having some issues unfortunately after running the setup script.

> BTCPay Server starting... this can take 5 to 10 minutes...
> Job for btcpayserver.service failed because the control process exited with error code.
> See "systemctl status btcpayserver.service" and "journalctl -xe" for details.
> BTCPay Server started
> docker-compose: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory

`systemctl status btcpayserver.service` gives :
> btcpayserver.service - BTCPayServer service
>    Loaded: loaded (/etc/systemd/system/btcpayserver.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Tue 2019-03-26 07:53:40 UTC; 3s ago
>   Process: 2531 ExecStart=/bin/bash -c . /etc/profile.d/btcpay-env.sh && cd "$(dirname $BTCPAY_ENV_FILE)" && docker-compose -f "$BTCPAY_DOCKER_COMPOSE" up -d -t "$COMPOSE_HTTP_TIMEOUT" (code=exited, status=127)
>  Main PID: 2531 (code=exited, status=127)
> 
> Mar 26 07:53:40 rockpro64 systemd[1]: Starting BTCPayServer service...
> Mar 26 07:53:40 rockpro64 bash[2531]: docker-compose: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
> Mar 26 07:53:40 rockpro64 systemd[1]: btcpayserver.service: Main process exited, code=exited, status=127/n/a
> Mar 26 07:53:40 rockpro64 systemd[1]: btcpayserver.service: Failed with result 'exit-code'.
> Mar 26 07:53:40 rockpro64 systemd[1]: Failed to start BTCPayServer service.

Looking around for the error, I found the suggestion to do: `sudo mount /tmp -o remount,exec` . But this doesn't work and I get: 

> mount: /tmp: mount point not mounted or bad option

So I'm still stuck at the error:

> docker-compose: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory

**Comment by NicolasDorier** [comment]
we progress :p 
Is it possible that docker-compose is as well not the one installed from the setup script?

**Comment by NicolasDorier** [comment]
Can you also try `apt-get install -y zlib1g:armhf`

**Comment by Xaspr** [comment]
It was really that simple. And it works! 

Many thanks for your help and this great project.

**Comment by NicolasDorier** [comment]
adding this in the setup

**Comment by NicolasDorier** [comment]
I updated the `btcpay-setup.sh` so hopefully next time it works out of the box
