### ISSUE TITLE
Bitcoin Core Version

### ISSUE THREAD

**Issue by larry-beck** [btcpayserver/btcpayserver#717]
I have btcpayserver installed and running just fine, however, when I view the version of Bitcoin Core installed via the bitcoind --version or bitcoin-cli.sh getnetworkinfo, the install of btcpayserver is only installing v.0.17.0 and not v.0.17.1 which is the latest version of Bitcoin Core. Is there a way to upgrade this as I had a BC full node running before installing btcpayserver and it still shows from the bitcoind program that it is the latest version of v.0.17.1 which is the code base I would prefer for my node to be running. Or is there no way to install an upgrade to Bitcoin Core while running btcpayserver on the same hardware?

**Comment by pavlenex** [comment]
Closing since this is a [duplicate](https://github.com/btcpayserver/btcpayserver-docker/issues/118), please don't cross-post issues between repositories.

**Comment by pavlenex** [comment]
[Duplicate.](url)
