### ISSUE TITLE
Mismatching BTC deposit addresses

### ISSUE THREAD

**Issue by conscott** [btcpayserver/btcpayserver#718]
Occasionally when paying an invoice, I see the the `BTC (On-Chain)` Addresses listed is actually different than the address I deposited to listed under `On-Chain payments` (see image below).

![invoice](https://user-images.githubusercontent.com/14220652/55071320-bf3e5200-50a1-11e9-9915-1f3ea5eec695.png)

It seems to happen about 25% of the time, and I am not sure why. I would expect these two addresses listed to always be the same. The address displayed in the checkout page is the `On-Chain payments` address. 

**Environment**
Ubuntu 16.04
BTCPay Server `master` at be90172840f1a891da2ca6ace898bbac04b337c8
Manual Deploy with Bitcoin Core Testnet `master` / NBxplorer `master`

**To Reproduce**
* Turn on 0-conf 
* Pay several $1.0 invoices on testnet
* Inspect Invoice Details for Mismatch

**Comment by NicolasDorier** [comment]
wtf, can you copy and paste those addresses here?

**Comment by NicolasDorier** [comment]
Also, give me your tpub

**Comment by conscott** [comment]
Sure:
tb1qm04j6yvc230fsmdmrct7tuv3yvy8nmgpzquczq
tb1qmy7nr390vxa6lm4387tflmd7w528wyvveq0m8y

tpubD8QR9uwCZtjwg7p9xqNPaaR64vKTiEe4zwzThpwePKJDbeAsBjxVXpUGkkgEBz5aSdYw4qEseoJ5ZJeewtkXpFB48tiDZ65cMnnSzgbSArd

**Comment by astupidmoose** [comment]
This is normal for partial payments. 

Partial payments generate a second address to be used for the remainder of the payment. Your second payment should be going to the new address generated under "paid summary" vs the used address.

**Comment by conscott** [comment]
Ahhhh, okay that makes sense. 

In my test I was making partial payments on purpose, but with address re-use. I didn't notice the deposit addresses updating on partial pay, just the balance.

I suppose the UI can look a little confusing when this is done, since it lists an unused Onchain deposit address for a fully paid invoice.

I know address re-use _should be_ discoured, so I was doing things 'the wrong way', but if there is any action to take here I might suggest listing all deposit addresses associated to an invoice, although I know it's pain the for data structures in place. Your call.

I will go ahead and close this. Thank you all for the quick response!
