### ISSUE TITLE
API compatible with Abacus / Abaninja

### ISSUE THREAD

**Issue by ArbenKarb** [btcpayserver/btcpayserver#722]
**Is your feature request related to a problem? Please describe.**
Feature Request / Noob Question:

I've recently checked out a free web-based accounting solutions for small businesses (app.abaninja.ch) which is interfaced with the BitPay API. I then inquired support whether it would be possible to also interface it with BTCPay Server. According to them there is no API to do so. This surprised me, since based on how I understand it would work is simply pulling a new address from your BTCPay Backend.

I haven't deployed my instance of BTCPay as of yet, but am looking into it.

**Describe the solution you'd like**
If not already available - API to integrate into Abaninja.

**Additional context**
Email Response from Support:

"
Hi

No, we can only interface BitPay to accept Bitcon.
Because there is no open API or ither interfaces, which you can use.
"

**Comment by Kukks** [comment]
We already have a compatible Bitpay invoice api. They only need to point to a btcpay host instead of bitpay.com and they are good to go.

**Comment by ArbenKarb** [comment]
forwarded this to support, thanks
