### ISSUE TITLE
Problem with Changelly when select pay with USD / EUR

### ISSUE THREAD

**Issue by mrbianchi** [btcpayserver/btcpayserver#723]
It opens a popup
Everything looks fine
I press Exchange
And I get redirect to Changelly site
And here is the problem
Isn't customer friendly (should be because I'm using an API) , the label says to my customers "BTC address must be yours and under your full control."
and the parameters isn't being filled (Example, my invoice was 13 USD and the form has 120 USD )
and the address isn't filled with the invoice's address

**Comment by Kukks** [comment]
@mrbianchi  I just checked this out. It's definitely an issue from their end and only related to USD/EUR.

**Comment by Kukks** [comment]
Please contact their support and tell them to fix it :)
