### ISSUE TITLE
Ledger throws "The dongle must be reinserted" multiple times 

### ISSUE THREAD

**Issue by sigHash** [btcpayserver/btcpayserver#724]
I keep getting "The dongle must be reinserted" on chrome when calling SignTransactionAsync.

`"   at LedgerWallet.LedgerClientBase.Throw(Int32 sw)\n   at LedgerWallet.LedgerClientBase.ExchangeAsync(Byte[][] apdus, CancellationToken cancellation)\n   at LedgerWallet.LedgerClient.SignTransactionAsync(SignatureRequest[] signatureRequests, Transaction transaction, KeyPath changePath, CancellationToken cancellation)\n   at BTCPayServer.Services.HardwareWalletService.SignTransactionAsync(SignatureRequest[] signatureRequests, Transaction unsigned, KeyPath changeKeyPath, CancellationToken cancellationToken) in /Users/BTCPayServer/Services/HardwareWalletService.cs:line 194"`

**Comment by pavlenex** [comment]
Lately, there have been some issues with Ledger and Chrome. I usually encounter that error in Firefox.

- If I have another U2F plugged in (for example Yubikey)
- If you don't confirm transaction fast enough

**Comment by pavlenex** [comment]
@sigHash Can you provide info on your environment or something more?
Browser, ledger firmware, bitcoin app version, etc.

**Comment by pavlenex** [comment]
Ok, so this is a confirmed bug in Ledger in Google Chrome, actually, it's Chrome's issue. So the solution is to use Firefox, just enable U2F in about:config.

We'll try to add webusb support for chrome that should be better in the future.
