### ISSUE TITLE
updating lightning alias mishandles spaces

### ISSUE THREAD

**Issue by dannybitgo** [btcpayserver/btcpayserver#725]
**Describe the problem/bug**
The process for updating my LND alias does not handle aliases with spaces.

**Your environment**
* Version of BTCPay Server: v1.0.3.89
* Deployment method: Docker on google cloud

**To Reproduce**
I followed these steps to change my LND alias:
```
sudo su -
cd btcpayserver-docker
export LIGHTNING_ALIAS="two words"
. ./btcpay-setup.sh -i
```
**Expected behavior**
I would expect my new alias to be "two words"

**Actual behavior**
However, this results in an alias of "two" (it misses anything after the first space)

**Additional context**
I believe the problem might be in the regular expression at the bottom of the file at "/etc/profile.d/btcpay-env.sh"
```
if cat "$BTCPAY_ENV_FILE" &> /dev/null; then
    export $(grep -v '^#' "$BTCPAY_ENV_FILE" | xargs)
```

**Workaround**
For others: if you really want a multi-worded alias, you can manually open the file:
```
/btcpayserver-docker/docker-compose-generator/docker-fragments/bitcoin-lnd.yml
```
And replace
```
LND_ALIAS: ${LIGHTNING_ALIAS} 
```
with
```
LND_ALIAS: "your alias"
```

Then rerun:
```
. ./btcpay-setup.sh -i
```

**Comment by Eskyee** [comment]
Can confirm this too !

**Comment by NicolasDorier** [comment]
Thanks, I just fixed it now:

```bash
btcpay-update.sh
```
This will fail, but carry on

```bash
. btcpay-setup.sh -i
```

Then next `btcpay-update.sh` will work, even with a space.

**Comment by NicolasDorier** [comment]
@dannybitgo your work around is not good, because `btcpay-update.sh` will fail because your git repo has changes.

Revert your changes before doing what I said above.

**Comment by dannybitgo** [comment]
@NicolasDorier thanks for the heads up

**Comment by nexondo** [comment]
@dannydeezy this is great! thanks :)
maybe add nan for open file that also people can do it without knowing this otherwise you get error

cheers
