### ISSUE TITLE
Nethereum

### ISSUE THREAD

**Issue by jessemarco** [btcpayserver/btcpayserver#726]
Can you review for me, if it is worth to try this .NET integration library for Ethereum? I think it looks very promising.

https://github.com/Nethereum/Nethereum

**Comment by Kukks** [comment]
This really has nothing to do with this project at all?

**Comment by jessemarco** [comment]
I wanted to integrate this into btcpayserver, create PR, but want to know community opinion, what think about this ".NET integration library for Ethereum" in terms of architecture of btcpayserver.

Thank you.

**Comment by Kukks** [comment]
Nethereum is just base library of how to interact with ethereum. That said, it's the only decent eth library I've seen for  .net

**Comment by Kukks** [comment]
I'm going to go ahead and close this since there is not much here in terms of what you want to accomplish. Feel free to reopen once you've thought this out more
