### ISSUE TITLE
Problem with Changelly when select pay with USD / EUR

### ISSUE THREAD

**Issue by mrbianchi** [btcpayserver/btcpayserver#728]
![image](https://user-images.githubusercontent.com/25530181/55285455-f4c59280-5362-11e9-854e-80e41881769d.png)

**Comment by pavlenex** [comment]
Duplicate #723 
As said earlier, it's changelly issue, not btcpay's.

**Comment by mrbianchi** [comment]
but what I have to say to them? I'm not developer of btcpayserver, I don't know how works even the changelly api

**Comment by Kukks** [comment]
@mrbianchi  Send me an invoice url so I can see what the error is. 

In the future, don't ditch the issue template for bug reports.

**Comment by mrbianchi** [comment]
sorry by waiting time

https://btcpayjungle.com/invoice?id=6JKdyTDmSRWD8rBWm1k1ed

**Comment by mrbianchi** [comment]
![image](https://user-images.githubusercontent.com/25530181/55453873-0ce02080-55b4-11e9-82a3-4e1d7f6a8c3c.png)

**Comment by NicolasDorier** [comment]
Yep, this is a bug. @Kukks

**Comment by Kukks** [comment]
I have been trying with the same parameters as @mrbianchi  but it seems to work ok. are your api details valid?

**Comment by NicolasDorier** [comment]
@Kukks even if not valid, a NRE is a bug

**Comment by Kukks** [comment]
Can you message me in chat @mrbianchi We'll debug this together

**Comment by mrbianchi** [comment]
@Kukks  yes

**Comment by Kukks** [comment]
I haven't managed to recreate this issue once yet and I've tried both on my own deployments and on btcpayjungle. Can you please confirm that it still happens to you?

**Comment by mrbianchi** [comment]
> I haven't managed to recreate this issue once yet and I've tried both on my own deployments and on btcpayjungle. Can you please confirm that it still happens to you?

It still happens. https://t.me/mrb_0

**Comment by NicolasDorier** [comment]
Error 400... maybe you can tell us more by showing the requests sent to changelly via the network debugger of chrome.

**Comment by mrbianchi** [comment]
![image](https://user-images.githubusercontent.com/25530181/61187548-3136a900-a649-11e9-9f33-39d6b6cb33ad.png)
https://btcpayjungle.com/invoice?id=RW8jDTfS9RhuerxwutAFmk
