### ISSUE TITLE
Error while contacting any exchange

### ISSUE THREAD

**Issue by Janaka-Steph** [btcpayserver/btcpayserver#729]
**Describe the problem/bug**
I have warnings about failed connection to exchanges, also dumping full html page in the logs

**Your environment**
* Version of BTCPay Server: v1.0.3.89
* Deployment method: docker
* Other relevant environment details: Odroid xu4 / Ubuntu

**Logs (if applicable)**
$ docker logs generated_btcpayserver_1
https://pastebin.com/nKmZVHQc

**Comment by NicolasDorier** [comment]
That's happen. I close it, those warning should disappear once your node is fully synched and running.

**Comment by Janaka-Steph** [comment]
@NicolasDorier My node is fully synched and running!!

**Comment by NicolasDorier** [comment]
cool!

**Comment by Janaka-Steph** [comment]
So what? Do you want to consider the issue seriously?

**Comment by NicolasDorier** [comment]
This is not an issue. The first request to the exchange rate said: "It can't connect", which should indeed be a warning and can come from too much reason on which I have no control on. If things then work after, this is not an issue.
