### ISSUE TITLE
PoS - redirect to main screen a few seconds after payment

### ISSUE THREAD

**Issue by Janaka-Steph** [btcpayserver/btcpayserver#730]
**Is your feature request related to a problem? Please describe.**
In a public Point of Sale, a customer should always see the main screen. 
Currently, if a customer make a payment and doesn't return to the main screen manually, the next customer will not see the main screen but will be presented with the receipt of the previous customer (which is terrible UX).  

**Describe the solution you'd like**
In a PoS app, it should redirect automatically to the main screen a few seconds after a successful payment

**Comment by Kukks** [comment]
We should not do this. There is a button that should be clicked to return to the POS. If we automatically redirect back, you would not easily know if payment was paid, partially paid or expired if you do not pay close attention or looked away at the moment of payment.

**Comment by Janaka-Steph** [comment]
I think your point is valid for a PoS that a user access from his browser. He is the only one using his computer, it doesn't matter to go back to the main screen automatically. 

However my use case is having a PoS displayed on a tablet, in a public location, accessible to everybody. The delivery of the good is instant, triggered by notificationUrl callback. In case of expiry, it means that the user changed his mind, doesn't want the good anymore, and we can go back to main screen. 
Regarding the partial payments I want to disable it. Afaik we do that by setting `Consider the invoice paid even if the paid amount is ... % less than expected` to 0. Also with Blue Wallet and I guess all others, if you change the amount manually after a scan it doesn't change the actual amount you will pay.

To conclude, I still think this feature is needed for the specific use case I described, and that we should let the merchant the ability to decide the checkout behaviour by having a checkbox in the settings.

**Comment by Kukks** [comment]
@NicolasDorier  I would need to add another property to the `InvoiceData` model: `bool AutomaticRedirect`  that would do this. If you're ok with this, I'll push a pr soon
