### ISSUE TITLE
[Feature Request] Help onboarding via LNBig integration

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#733]
Recently, are [LNBig](https://lnbig.com/) is able to generate command lines that one can run on his BTCPay install so they can provide you with liquidity.

![image](https://user-images.githubusercontent.com/3020646/55477482-22a52280-5654-11e9-964c-dd9958e47dda.png)

It would be nice if it was integrated in BTCPay if we detect that the user has no incoming channel. We could propose them to on board easily with this.

**Comment by pavlenex** [comment]
Nice idea.

There are some questions raised about LNBig in LND community. While there has been no proof they're malicious in any way, many people question their motives behind having a major chunk of the network's capacity.

That said, it can certainly be a very handy tool in the UI, but in the future, I personally wish we can decentralize even more and provide other options as well.

There are already [a few options to consider](https://wiki.ion.radar.tech/tutorials/troubleshooting/bootstrapping-channels). 

I think at this stage of LN, we should go for it, with a mindset to add more providers in the future.

**Comment by NicolasDorier** [comment]
Maybe actually another idea would be to make a new BTCPay app so people can ask for incoming channel.

**Comment by pavlenex** [comment]
In my opinion that would make sense, but instead of the app, I think it would be better as a part of internal LN wallet #677?

**Comment by Kukks** [comment]
We can do this with transmuter :D
ᐧ

**Comment by NicolasDorier** [comment]
Dropping that here https://medium.com/@akumaigorodski/multipart-payments-647cdf5cc15a

**Comment by NicolasDorier** [comment]
hey @ziggamon we talked about it, what about this:
Bitrefill could ask their user for their BTCPay Url, then you would generate something like

https://btcpay.example.com/server/ln/channel-request?nodeid=bitrefill_node_id

When the user click on this link, it would go through a wizard on his own btcpay website to create the channel.

**Comment by pavlenex** [comment]
I've talked to @saubyk and ShahanaFarooqui from Ride The Lightning and will look into adding these sort of features into RTL UI, which means, we can use them as a built-in LN wallet on the server and let them improve the UI.

**Comment by saubyk** [comment]
We are looking to add `loop-out` on RTL. That should help address incoming liquidity problems.

**Comment by pavlenex** [comment]
It seems that loop-out has been added in RTL and that our efforts of doing this have faded mostly because people either figured out the liquidity part or the usage slowed down. 

Anyway , since we now have RTL and Thunderbolt as lightning UI's I'm closing this one for now. If we ever decide to unify the on-chain and btcpay experience will re-open. 

Eventually perhaps we can do it via #775 in the future.
