### ISSUE TITLE
PoS App Search Box Does Not Respond

### ISSUE THREAD

**Issue by pretyflaco** [btcpayserver/btcpayserver#734]
**Describe the problem/bug**
PoS App Search Box Does Not Respond

**To Reproduce**
1. Go to BTCPay PoS App e.g. 'https://btcpay283894.lndyn.com/apps/49qyXYZgocrWaeiFartj8gJLaAxw/pos'
2. Click on 'Find Product' on top of page
3. Enter query string e.g. 'Wasser'

**Expected behavior**
Product list narrows down to products whose name matches query string

**Actual behavior**
Nothing happens

**Screenshots/Links**
If applicable, add screenshots or links to help explain your problem.
![image](https://user-images.githubusercontent.com/32958103/55502013-f5ed0d00-564b-11e9-84cc-a02e9fb8d919.png)

**Additional context**
Search function used to work until recently - not any more. Tested several devices. Same result.

**Comment by britttttk** [comment]
I am also able to reproduce the issue.

**Comment by NicolasDorier** [comment]
checking this

**Comment by NicolasDorier** [comment]
Ping @Kukks the search depends on `.card-wrapper` that you removed on 4b342376
