### ISSUE TITLE
bitbank throws errors into BTCPay logs, "bitbank: the bid should be lower than ask"

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#741]
**Describe the problem/bug**
Bitbank seems to be giving errors in BTCPay server logs. 

**Your environment**
* Version of BTCPay Server: BTCPayServer v1.0.3.91
* Deployment method: Manual
* Other relevant environment details: 

**Logs (if applicable)**
2019-04-05 04:09:27.824 -07:00 [WRN] Error while contacting bitbank: the bid should be lower than ask
Parameter name: bid

**Expected behavior**
No Error

**Actual behavior**
Error

**Additional context**
I don't use "Bitbank" and have no idea what it is, but the errors are annoying.

**Comment by NicolasDorier** [comment]
the reason is that BTCPay continuously fetch rates of all exhcanges so we don't have to query them at invoice creation time (so crappy exchanges can't delay invoice creation)

**Comment by NicolasDorier** [comment]
That said, will take a look about why this particular exchange have an issue.
