### ISSUE TITLE
Account Registration Email Not Sending

### ISSUE THREAD

**Issue by stone212** [btcpayserver/btcpayserver#742]
**Describe the problem/bug**

**Your environment**
* Version of BTCPay Server:  
That's a good question.  If you didn't obscure this process so much I could tell you.  I followed the instructions here:https://blog.btcpayserver.org/btcpay-misconceptions/

* Deployment method: 

I did what this said: https://blog.btcpayserver.org/btcpay-misconceptions/

* Other relevant environment details:

docker is not for professional production use.  Please provide clear instructions for making this work securely and manually.  Probably with an apache2 or nginx reverse proxy, postfix etc.

**Logs (if applicable)**
Basic logs can be found in Server Settings > Logs.

What the hell is `Server Settings > Logs`?  What file on my server do you want me to paste here?

**To Reproduce**
1. Go to https://blog.btcpayserver.org/btcpay-misconceptions/
2. Follow the instructions
3. Go to your website
4. Register an account
5. Notice how no email arrives to confirm this account.

**Expected behavior**
I expect either an email to arrive to confirm my account, maybe instructions how to set up the email system to work (I can use postfix but everything is hidding in this docker container)

**Actual behavior**
Already explained.

**Comment by pavlenex** [comment]
First of all you're following a generic blog post, while there are tons of [deployment documentation](https://docs.btcpayserver.org/deployment/deployment) on how to install BTCPay.

In the earlier issue you opened #738 I directed you to [the getting started guide](https://docs.btcpayserver.org/btcpay-basics/gettingstarted), where SMTP configuration for emails is explained.

Please if your issues are about **documentation**, open it in [docs repository](https://github.com/btcpayserver/btcpayserver-doc) in the future.

**Comment by stone212** [comment]
@pavlenex 

> First of all you're following a generic blog post

No I'm following a specific blog post.  The one that convinced me (and many other people) that BTCPay might be something to take seriously.  I am not as confident now.

> In the earlier issue you opened #738 I directed you to the getting started guide, where SMTP configuration for emails is explained.

You did send a link to that document.  However

1. That document does not answer the question I asked.  At all.  

2. That document is not listed on the blog post that is where I installed from *because it said you could do that* so I am doing you the extra favor of helping you fix 1 and then link the fix to the blog post.

You are welcome.  I look forward to seeing you fix this, including providing SMTP configuration info which is definitely not in the place that the link that you sent links to.  That brings you to https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#how-to-configure-smtp-settings-in-btcpay.  I think it is obvious that this is not the answer.  Or do you need more help?

**Comment by pavlenex** [comment]
You're welcome to send PR's. https://chat.btcpayserver.org/ is where developers and contributors hang out, so feel free to join.

**Comment by stone212** [comment]
@pavlenex Is that a joke?  I support an infrastructure with at least 2,000 pieces of software but you think I will devote extra time to join your group instead of the one that everyone uses (GitHub/GitLab) because your project is more important than all of the others I depend on because why?  Based on the fact that you don't have docs?  Or the fact that you respond badly to tickets?  Thanks but until you are ready to take BTCPay seriously I won't either.  You can reply to me here when you're ready to fix the SMTP configuration problems either on a technical or a doc level.

**Comment by pavlenex** [comment]
No not a joke. 

You said you'd like to help and I directed you to a chat where community gathers which might help in avoiding work duplication. You're free to do a pull request and communicate via GitHub of course.

**Comment by stone212** [comment]
@pavlenex Okay.  Fix this issue by explaining to me how to configure SMTP for BTCPay and then put your docs in GH.  Then I'll write the docs and do a pull request.

**Comment by pavlenex** [comment]
Docs are already on GH https://github.com/btcpayserver/btcpayserver-doc/

**Comment by stone212** [comment]
@pavlenex I already told you they aren't.  Maybe if you'd listen instead of getting defensive you'd make use of someone willing to help.  you convinced me this is a vanity project, not ready for professional work.  I'm signing off this thread.  You can contact me if you're ready to listen and improve.  I mean seriously - you don't have a doc for how to configure SMTP settings.
