### ISSUE TITLE
Pos App refactoring

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#749]
So right now, the POS app splits into two:
the static item mode, where you pick an item and click buy and it creates the invoice
cart mode, which lets you pick multiple items, charge tips, allows donations, etc
The code for both of these are in one html file and it is a bit messy in there. The way we determine which is used is through a config setting in the POS app. I propose we remove that configuration, split these into separate views and allow any pos to use either view at any time through. 
So for example: 
* btcpay.com/apps/xyz/pos/static -> static item mode
* btcpay.com/apps/xyz/pos/cart -> cart mode
* btcpay.com/apps/xyz/pos/keypad-> keypad mode( no items, just an on-screen keyboard and an input field; people seem to really love this for some reason)

We can try and make the code between all the apps as reusable as possible between each view. I would say the static view doesn't need any js at all since it's, well, static.

Additionally, we can replace the "EnableShoppingCart" config item with a "DefaultView" which can be either of the views we create. This way `btcpay.com/apps/xyz/pos/` redirects to it.

**Comment by Kukks** [comment]
This potentially closes #679 and #680

**Comment by pavlenex** [comment]
I've now added the [PoS label ](https://github.com/btcpayserver/btcpayserver/labels/PoS)which should help when you guys refactor the pos.
