### ISSUE TITLE
[PoS app] Unable to have notificationUrl callback working

### ISSUE THREAD

**Issue by Janaka-Steph** [btcpayserver/btcpayserver#751]
**Describe the problem/bug**
I am unable to have notificationUrl  callback in PoS app working. 
To test it I set "https://test.com" in the "Callback Notification Url" form field in PoS settings, then I go to the PoS view and I do a payment.  
Then when I go to https://btcpay.example.com/invoices/{invoiceId} the "Notification url" and "Order Id" are empty. In nginx logs I don't see any call either.

Also, when I enter a value in the "Callback Notification Url" form field, click save and come back in settings, I don't see the value I have just set.

The feature doesn't seem to work.

**Your environment**
* Version of BTCPay Server: v1.0.3.92
* Deployment method: docker

**Comment by Kukks** [comment]
Sorry about that, just pushed a PR to fix this
