### ISSUE TITLE
Crowdfunding Order ID invoice link is broken

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#759]
**Describe the problem/bug**
The link in orderid for invoices created by the crowdfunding app is broken.

**Your environment**
* Version of BTCPay Server: v1.0.3.93
* Deployment method: LunaNode
* Other relevant environment details:

**To Reproduce**
1. Go to Invoices 
2. click on the orderid link 

**Expected behavior**
Should open invoice, instead opens `No Connection with that ID` page.

**Actual behavior**
Tell us what happens instead

**Screenshots/Links**
If applicable, add screenshots or links to help explain your problem.
![Screen Shot 2019-04-13 at 10 45 38](https://user-images.githubusercontent.com/36959754/56077193-7a245a80-5dd9-11e9-9e77-54b4743de396.png)
![Screen Shot 2019-04-13 at 10 41 35](https://user-images.githubusercontent.com/36959754/56077196-7d1f4b00-5dd9-11e9-8c2a-a86582b4102b.png)

**Additional context**

**Comment by decentralizedb** [comment]
After updating from version 1.7.2.0 to 1.7.3.0, I have this same behavior and message, in the same situation: No Connection with that ID

Some help?
![image](https://user-images.githubusercontent.com/58108487/209336578-91a04bd2-d39d-476c-80bf-3a2ec4c9d601.png)
