### ISSUE TITLE
Wallet (auto) connect with Ledger NanoS does not work

### ISSUE THREAD

**Issue by P0u1us** [btcpayserver/btcpayserver#764]
**Describe the problem/bug**
When adding details to Store settings and adding an BTC wallet address I am using the Ledger NanoS; the ( socalled automatic) recognition (by BTCpayServer) does not work!
I spent several days trying to figure out why and can not identify if this is with BTCpayServer, sofar I am thinking it relates to: U2F timeout in Chrome browser BUG:
From: https://support.ledger.com/hc/en-us/articles/360018810413

**Your environment**
* Version of BTCPay Server:
* Deployment method: manual build
* Other relevant environment details:
Have tried the use of Ledger Live on 2 different PC's and testing both Chrome and Opera

**Logs (if applicable)**
Nothing is shown in any log for this function

**Expected and Actual behavior**
Expecting some form of confirmation that the Ledger NanoS is found, but nothing what soever is emerging.

**Additional context**
I believe that more people are experiencing this issue for whatever reason, either bugs in Chrome or Ledger (live) or BTCpayserver; it already has too many potential dependencies to assume that it will simply work... this is the real issue: the provided documentation does not provide any alternative (manual) guidelines!
Please add to your documentation (on: https://github.com/btcpayserver/btcpayserver-doc/blob/master/GettingStarted.md#connecting-btcpay-store-to-your-wallet)
and as is also suggested in: https://github.com/btcpayserver/btcpayserver-doc/issues/44
The basic manual procedure to obtain the xpub_key from Ledger Live, as in: https://www.reddit.com/r/ledgerwallet/comments/9qlcl7/just_grabbed_a_ledger_nano_s_can_i_export_an_xpub/
This will resolve a lot of painstaking searches and less issue notifications on this forum ;-)

**Comment by pavlenex** [comment]
When you plug in your Ledger Nano S, do you open Bitcoin App in the wallet as instructed?
Also:
- If you have another U2F like Yubikey, plug it out
- For Firefox you need to enable U2F in about:config
- Turn off Ledger Live app on your PC if you have it opened.

**Comment by pavlenex** [comment]
I've just noticed you only mentioned Chrome, does it work in Firefox?
Might be related to #724

**Comment by P0u1us** [comment]
Hi, thnx for the quick response.
it is confusing to see that you state that the ledger Live app needs to be off, docs state it must be on?
I am using Chrome and Opera (which claims U2F works by default); I have no Yubikey.
When on the shop settings page, edit BTC: the line Checking if a ledger wallet is connected... stays light grey and nothing happens.
I have the LedgerNanosS connected and opened in the BTC app. (not the live app!)
I am fine with now having it manually edited, but please add those instructions to your docs pages.

**Comment by pavlenex** [comment]
I'm referring to the Ledger Live desktop app that needs to be off, as it may (or may not) cause conflicts.

Please try with Firefox and enable U2F in about:config on Firefox. 

It seems ledger has problems with Chrome, also state the version of Ledger app version, firmware, browser version and other relevant information so we can try to replicate.

**Comment by P0u1us** [comment]
Hi, I hope you dont mind that I am limiting the number of apps on my pc, dont like too much bloated ;-)
AS for the Opera install: that is clean, without any addins, and should (as per docs) work, but doesnt see the LedgerNS. My Chrome install is however bloated with lots of addins (mew/metamask, Adblock, badger, etc), thus can htink of that soemthing blocks access to ledgerNS; I have however also re-tried it without running LedgerLive and that makes no difference.
For now I am happy to have found the manual install method, hope you will add that to the docs.
Rgrds, Poul.

**Comment by P0u1us** [comment]
btw Opera always automatically updates to the latest version. now: 60.0.3255.27

**Comment by pavlenex** [comment]
Alright, closing this in that case as I re-opened a [similar issue in docs ](https://github.com/btcpayserver/btcpayserver-doc/issues/213)repo where I'll try to explain this more clearly. Thanks for the feedback.

**Comment by NicolasDorier** [comment]
hey @P0u1us have you updated your ledger wallet? this is normally a bug ledger fixed recently... except if chrome broke again U2F (they are messing up a lot recently with it)

**Comment by P0u1us** [comment]
Yip, always keep uptodate ;-).. rechecked: Live 1.7.0 and Firmware version 1.5.5

**Comment by NicolasDorier** [comment]
@P0u1us you mention you have manual install, can you do F12 and see if the page have javascript error? dpeending on your setup, websocket are not well configured and you would get this issue.

**Comment by P0u1us** [comment]
ledgerwebsocket.js:7 WebSocket connection to 'wss://btcpay.codain.net/stores/2WoCq66BTey4UJRTcogvdmkSVpBQPQyLqpkmRAN9tEz1/derivations/LTC/ledger/ws?command=test' failed: Error during WebSocket handshake: Unexpected response code: 404

**Comment by P0u1us** [comment]
;-) thanx... that did do the trick, it now works!
I do understand your preference on using containers; however...
it is my believe: if you dont build your system from base, then you dont understand your system;
I know it is farfetched to go fully indepth, but where possible I dont simply accept that/how it works, I am keen to understand as much so when time comes I could solve basic issues myself ;-)
Very much appreciate your effort and patience!

**Comment by tsukasagenesis** [comment]
well I try and it seems to not workk anymore, can connect with ledger, could you try again @P0u1us  if you can add your ledger ? I try even on demo but without success, with firefox or chrome it fail. ledger S lastest update.

**Comment by P0u1us** [comment]
Sorry guys, (@tsukasagenesis) but I have abandoned this project.

**Comment by pavlenex** [comment]
@tsukasagenesis this feature is no longer supported, you can use our [built in hardware wallet integration ](https://docs.btcpayserver.org/Vault/)

**Comment by tsukasagenesis** [comment]
@pavlenex Perfect, it's working great by vault !

If you could add the information that vault support ledger, it would be great (for search for example)

Also please remove "ledger" from import since it doesn't work anymore and is handle by VAULT, this is confusing and I search 3 hours to make it work yesterday ...

**Comment by pavlenex** [comment]
@tsukasagenesis the support has been dropped just a week ago or so, bad timing.

It should be removed in the next release. It's already removed from our documentation, but if you find any specific mentions that caused a confusion, link please so we can remove it.
