### ISSUE TITLE
btcpay_update.sh not updating to v1.0.3.93

### ISSUE THREAD

**Issue by larry-beck** [btcpayserver/btcpayserver#769]
When I run btcpay-update.sh as root, it says all is up-to-date as follows. My version is still showing BTCPayServer v1.0.3.92

root@XXXXX:~/BTCPayServer/btcpayserver-docker# btcpay-update.sh
Already up-to-date.
Using default tag: latest
latest: Pulling from btcpayserver/docker-compose-generator
Digest: sha256:5139f9ceb92f2a856910890a916de09e5a30a2eb54df580d55f1f7f9de604547
Status: Image is up to date for btcpayserver/docker-compose-generator:latest
Crypto: btc
Lightning: lnd
ReverseProxy: nginx
Generating /app/Generated/docker-compose.generated.yml
With fragments:
	nginx
	btcpayserver-nginx
	btcpayserver
	nbxplorer
	postgres
	bitcoin
	bitcoin-lnd
	opt-add-tor
Generated /app/Generated/docker-compose.generated.yml

Installed bitcoin-cli.sh to /usr/bin: Command line for your Bitcoin instance
Installed bitcoin-lncli.sh to /usr/bin: Command line for your Bitcoin LND instance
Installed btcpay-clean.sh to /usr/bin: Command line for deleting old unused docker images
Installed btcpay-down.sh to /usr/bin: Command line for stopping all services related to BTCPay Server
Installed btcpay-restart.sh to /usr/bin: Command line for restarting all services related to BTCPay Server
Installed btcpay-setup.sh to /usr/bin: Command line for restarting all services related to BTCPay Server
Installed btcpay-up.sh to /usr/bin: Command line for starting all services related to BTCPay Server
Installed btcpay-update.sh to /usr/bin: Command line for updating your BTCPay Server to the latest commit of this repository
Installed changedomain.sh to /usr/bin: Command line for changing the external domain of your BTCPay Server
generated_postgres_1 is up-to-date
tor is up-to-date
generated_lnd_bitcoin_rtl_1 is up-to-date
generated_nbxplorer_1 is up-to-date
tor-gen is up-to-date
btcpayserver_bitcoind is up-to-date
btcpayserver_lnd_bitcoin is up-to-date
nginx is up-to-date
generated_btcpayserver_1 is up-to-date
nginx-gen is up-to-date
letsencrypt-nginx-proxy-companion is up-to-date

**Comment by pavlenex** [comment]
v1.0.3.93 is not yet stable so you can't update it that way.
If for some reason you really need it, you can do:
```
cd btcpayserver-docker
export BTCPAY_IMAGE="btcpayserver/btcpayserver:1.0.3.93"
. ./btcpay-setup.sh -i
```
It's not recommended yet as we're still testing it and there are bugs that have to be addressed.
