### ISSUE TITLE
No slider over Pay button

### ISSUE THREAD

**Issue by Freefromchainz** [btcpayserver/btcpayserver#770]
**Describe the problem/bug**
Just did an update on the server to get the new slider button feature and it is not appearing over the button.

here is what i see 
![btcpay donate button2](https://user-images.githubusercontent.com/8317700/56223155-789da100-602a-11e9-81cb-62a2daf24779.PNG)
  
here is what i should see
![2019-04-16](https://user-images.githubusercontent.com/8317700/56223230-9cf97d80-602a-11e9-9032-322df4ea1a36.png)

**Your environment**
* Version of BTCPay Server:
* Deployment method: 
* Other relevant environment details:

**Logs (if applicable)**
Basic logs can be found in Server Settings > Logs.

**To Reproduce**

**Expected behavior**

**Actual behavior**
Tell us what happens instead

**Screenshots/Links**
If applicable, add screenshots or links to help explain your problem.

**Additional context**

**Comment by pavlenex** [comment]
Thanks for reporting.
@Dolu89 I was able to replicate this issue [on WordPress demo](https://store.demo.btcpayserver.org/index.php/test-button-slider/). Can you look into it why the slider is not working when embedded on a page?

**Comment by Dolu89** [comment]
@pavlenex I think here is a conflict because here is 2 slider in the same page.
I have seen that by change the first slider (no value changed) and change the second slider (the value of the first input is now changed). Can you try to remove one? 

About the error reported by @Freefromchainz to generate the slider button, I have no problem on my own production btcpay server :-/ I see you have a custom theme. MAYBE here is a conflict with your theme (but I'm pretty sure it's not that)

**Comment by pavlenex** [comment]
I now noticed I misunderstood @Freefromchainz initial issue. I can't replicate that one, what browsers are you using and are there any plugins, additions that might block the preview? Do you see any errors in developer mode of your browser in console log?

@Dolu89 It's not about two pages, does not work with one either. Tried on multiple themes including default with disabled plugins, it's something on our end. Lots of people will use this with WordPress so we'll have to figure out what's causing behavior like this.

**Comment by Dolu89** [comment]
@pavlenex I don't know how you copied the slider code, but this is why it's not working
![image](https://user-images.githubusercontent.com/4184590/56232044-29825b00-6080-11e9-8498-6b48d0202101.png)
Here is no event "oninput"

Event is here on the second slider 
![image](https://user-images.githubusercontent.com/4184590/56232111-4c147400-6080-11e9-8b47-ca97282f6e68.png)

**Comment by pavlenex** [comment]
@Dolu89 Tried both manual and "copy" button.

```
<form method="POST" action="https://mainnet.demo.btcpayserver.org/api/v1/invoices">
    <input type="hidden" name="storeId" value="EErYwCthBNfJUpuU1etH1uhg3x1YVH1q1F2zez7u1AAX" />
    <div style="text-align:center;width:209px"><input type="text" id="btcpay-input-price" name="price" value="10" style="border: none; background-image: none; background-color: transparent; -webkit-box-shadow: none ; -moz-box-shadow: none ; -webkit-appearance: none ; width: 209px; text-align: center; font-size: 25px; margin: auto; border-radius: 5px; line-height: 35px; background: #fff;" oninput="event.preventDefault();isNaN(event.target.value) || event.target.value <= 0 ? document.querySelector('#btcpay-input-price').value = 10 : event.target.value" onchange="document.querySelector('#btcpay-input-range').value = document.querySelector('#btcpay-input-price').value" /><select onchange="document.querySelector('input[type = hidden][name = currency]').value = event.target.value" style="-webkit-appearance: none; border: 0; display: block; padding: 0 3em; margin: auto auto 5px auto; font-size: 11px; background: 0 0; cursor: pointer;"><option value="USD">USD</option><option value="GBP">GBP</option><option value="EUR">EUR</option><option value="BTC">BTC</option></select><input class="btcpay-input-range" id="btcpay-input-range" value="10" type="range" min="1" max="20" step="1" style="width:209px ;margin-bottom:15px;" oninput="document.querySelector('#btcpay-input-price').value = document.querySelector('#btcpay-input-range').value" />
    <style type="text/css">input[type=range].btcpay-input-range{-webkit-appearance:none;width:100%;margin:9.45px 0}input[type=range].btcpay-input-range:focus{outline:0}input[type=range].btcpay-input-range::-webkit-slider-runnable-track{width:100%;height:3.1px;cursor:pointer;box-shadow:0 0 1.7px #020,0 0 0 #003c00;background:#f3f3f3;border-radius:1px;border:0 solid rgba(24,213,1,0)}input[type=range].btcpay-input-range::-webkit-slider-thumb{box-shadow:0 0 3.7px rgba(0,170,0,0),0 0 0 rgba(0,195,0,0);border:2.5px solid #cedc21;height:22px;width:23px;border-radius:12px;background:#0f3723;cursor:pointer;-webkit-appearance:none;margin-top:-9.45px}input[type=range].btcpay-input-range:focus::-webkit-slider-runnable-track{background:#fff}input[type=range].btcpay-input-range::-moz-range-track{width:100%;height:3.1px;cursor:pointer;box-shadow:0 0 1.7px #020,0 0 0 #003c00;background:#f3f3f3;border-radius:1px;border:0 solid rgba(24,213,1,0)}input[type=range].btcpay-input-range::-moz-range-thumb{box-shadow:0 0 3.7px rgba(0,170,0,0),0 0 0 rgba(0,195,0,0);border:2.5px solid #cedc21;height:22px;width:23px;border-radius:12px;background:#0f3723;cursor:pointer}input[type=range].btcpay-input-range::-ms-track{width:100%;height:3.1px;cursor:pointer;background:0 0;border-color:transparent;color:transparent}input[type=range].btcpay-input-range::-ms-fill-lower{background:#e6e6e6;border:0 solid rgba(24,213,1,0);border-radius:2px;box-shadow:0 0 1.7px #020,0 0 0 #003c00}input[type=range].btcpay-input-range::-ms-fill-upper{background:#f3f3f3;border:0 solid rgba(24,213,1,0);border-radius:2px;box-shadow:0 0 1.7px #020,0 0 0 #003c00}input[type=range].btcpay-input-range::-ms-thumb{box-shadow:0 0 3.7px rgba(0,170,0,0),0 0 0 rgba(0,195,0,0);border:2.5px solid #cedc21;height:22px;width:23px;border-radius:12px;background:#0f3723;cursor:pointer;height:3.1px}input[type=range].btcpay-input-range:focus::-ms-fill-lower{background:#f3f3f3}input[type=range].btcpay-input-range:focus::-ms-fill-upper{background:#fff}</style></div>
    <input type="hidden" name="currency" value="USD" />
    <input type="image" src="https://mainnet.demo.btcpayserver.org/img/paybutton/pay.png" name="submit" style="width:209px" alt="Pay with BtcPay, Self-Hosted Bitcoin Payment Processor">
</form>

**Comment by Dolu89** [comment]
@pavlenex This code works :-/

**Comment by pavlenex** [comment]
I know, but for some reason not in WordPress, will see what's the problem. Lots of people use WP so we should provide a workaround. Could be related to [this](https://docs.btcpayserver.org/faq-and-common-issues/faq-apps#how-to-fix-empty-spacing-around-payment-button)
Will investigate later and let you know.

**Comment by Kukks** [comment]
It is the same shitty WYSWIYG story where it sanitizes the input to protect
users :)
ᐧ

**Comment by pavlenex** [comment]
The situation is a bit better with WordPress blocks, where [slider works](https://blog.btcpayserver.org/test-slider/)
but [custom amount is broken](https://blog.btcpayserver.org/test/).

Weird if you guys have any idea how this could be improved, would be great if we can figure it out.

@Freefromchainz sorry for hijacking your issue.

**Comment by Dolu89** [comment]
@pavlenex Do you mean custom amount style is broken? That's only because of the current css used by wordpress :-/
I think we have to apply a hard css reset on these 2 new buttons.

**With current wordpress css**
![image](https://user-images.githubusercontent.com/4184590/56338748-98a89e00-61ab-11e9-826c-7d00d2981b40.png)

**Without wordpress theme**
![image](https://user-images.githubusercontent.com/4184590/56338734-8af31880-61ab-11e9-829e-2d1b0c4b2ea8.png)

**Comment by pavlenex** [comment]
@Dolu89 Yeah, sorry I didn't make myself clear, that's exactly what I had in mind. I'll run a few more tests today and let you know.

**Comment by Freefromchainz** [comment]
@pavlenex No worries about hijacking the issue did it ever get fixed?

**Comment by pavlenex** [comment]
@Freefromchainz I was not able to replicate your issue, but I see you're using a different theme than the standard, can you try to update to latest version and remove the custom theme from your btcpay? 

Also tell us what browser you're using and disable plugins and extensions that can mess up the preview.

**Comment by Freefromchainz** [comment]
Changing the theme worked thx @pavlenex
