### ISSUE TITLE
BTCPay UI Notifications

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#775]
**Is your feature request related to a problem? Please describe.**
We should have notifications in the UI, notifying users of:

- Invoices (paid, paid partially, invalid)
- New version (just tell users there's a new btcpay version, not auto-update

Notifications should warn users of important things, and should help with invoice managment #349 

I think it's very important to be notified of invoices with unusual status, as for updates, maybe, not really sure but we had some discussion in #283

**Comment by woutersamaey** [comment]
I would also save the notifications in the database and make them accessible from the backoffice so you can see past messages after dismissing them.
We should also consider the fact that messages will need to be localized (I'm now working on that in #972 )

**Comment by Kukks** [comment]
I'm proposing we expand the scope a bit on this to also include an "Audit Log". 

The Audit log would hold a record of every action done on the server, be it create a store, create an invoice, change password, log in etc 
Some of these actions can be tagged to appear as notifications, thus enabling the original feature request here. A scope should also be attached to these logs, to see who they should be visible to ( user level, store level, server level, etc)

Most enterprise systems have this kind of feature which is essential for accountability, and for security, especially when dealing with money management.

**Comment by pavlenex** [comment]
Good idea, completely agree @Kukks, that would help with #1374.

**Comment by NicolasDorier** [comment]
Audit log is fine, but this is a different concept than notifications.

**Comment by pavlenex** [comment]
I agree it would be something more suitable for the Server Settings > Logs > Audit logs, especially if we intend to go crazy and add bunch of things there.

But maybe we can add some basic to the notification @NicolasDorier as well? Perhaps user wants to be notified when someone changes an xpub and if we tie notifications to smtp that can make sense.

**Comment by NicolasDorier** [comment]
no we can't, those are two different feature for two different type of users. One is a UX feature for all users the other is a glorified audit log.

Typically you want to give the user the ability to filter notifications, but you don't want to allow them to filter the audit log. Please keep the feature focused.

**Comment by pavlenex** [comment]
After thinking a bit I agree, let's then open a new issue for the audit logs and stick focus  on notifications for now.

**Comment by pavlenex** [comment]
Added in #1674 🎉
