### ISSUE TITLE
Google Analytics Code

### ISSUE THREAD

**Issue by larry-beck** [btcpayserver/btcpayserver#776]
I have place the Google Analytics code is both instances of core.js that I found in two wwwroot directories, but analytics is not showing code in App when the page is loaded, can you tell me the exact path to the correct core.js file that needs the tracking code entered into it for this to work as the Docs website mentions ~/wwwroot/... but that notation does not work when I try to enter that path on my command line, invalid path. Please tell me the path from drive root in Docker based setup where this file is that I need to change.

**Comment by Kukks** [comment]
You can only these files before you build. Which means you have to fork, edit and build your own docker image
