### ISSUE TITLE
[Feature] Basic PSBT support for sending

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#778]
I wish to add basic PSBT support for signing.
Basically PSBT allows to have a portable format for signing a transaction for allowing software supporting PSBT to sign such transaction so BTCPay does not need the private keys.

Current use cases fixed by PSBT.

## Issues with gap limit

1. Copy xpub from your wallet
2. Paste in btcpay
3. Use BTCPay for a while
4. Freak out because BTCPay balance does not match what wallet is showing
5. ???

This happens because the wallet does not monitor big gap limits.

## Making multi sig usable

1. Copy the xpub of Alice
2. Copy the xpub of Bob
3. Put the multi sig derivation scheme in BTCPay
4. ???

## How PSBT saves the day

If BTCPay would implement PSBT, then the user could go to Wallets/Send like he would do if he used ledger integration.
Then he would click on "Send".

In the Send script, where ledger is normally detected, there would be a button: "Export as PSBT".

![image](https://user-images.githubusercontent.com/3020646/56496448-76f54100-6534-11e9-8e5f-35517f36b579.png)

Such PSBT could be saved in a file, or copy pasted into any wallet supporting PSBT to sign and broadcast the transaction.

In the case of multi sig, there would be a "Combine PSBT" options for multi sig wallet in BTCPay wallet menu. (this would appear only for multi sig)

![image](https://user-images.githubusercontent.com/3020646/56496295-c71fd380-6533-11e9-9cf8-915a574363b9.png)

Alice and Bob sign with their wallet, and export the signed PSBT. They can then exchange the signature and combine inside BTCPay.

**Comment by pavlenex** [comment]
This feature has been added 1.0.3.96 by @NicolasDorier
