### ISSUE TITLE
/home/admin/btcpayserver/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 55

### ISSUE THREAD

**Issue by bereska** [btcpayserver/btcpayserver#780]
**Describe the problem/bug**
btcpayserver webfront is not accessible with error in btcpayserver status:
/home/admin/btcpayserver/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 55

**Your environment**
Raspiblitz 1.1 on rpi 3b+ with:
lnd version 0.5.2-beta commit=v0.5.2-beta
Bitcoin Core Daemon version v0.17.0.1
Manually installed:
dotnet 2.1.505
NBXplorer latest
BTCPay server v.1.0.3.92

**Logs (if applicable)**
admin@bereskaLND:~ $ sudo systemctl status btcpayserver
● btcpayserver.service - BtcPayServer daemon
   Loaded: loaded (/etc/systemd/system/btcpayserver.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-04-22 05:48:02 BST; 16h ago
 Main PID: 9189 (dotnet)
   CGroup: /system.slice/btcpayserver.service
           ├─9189 /usr/local/bin/dotnet run --no-launch-profile --no-build -c Release -p /home/admin/btcpayserver/BTCPayServer/BTCPayServer.csproj --
           └─9236 dotnet exec /home/admin/btcpayserver/BTCPayServer/bin/Release/netcoreapp2.1/BTCPayServer.dll

Apr 22 22:39:14 bereskaLND dotnet[9189]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Apr 22 22:39:14 bereskaLND dotnet[9189]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Apr 22 22:39:14 bereskaLND dotnet[9189]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Apr 22 22:39:14 bereskaLND dotnet[9189]:    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Apr 22 22:39:14 bereskaLND dotnet[9189]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Apr 22 22:39:14 bereskaLND dotnet[9189]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Apr 22 22:39:14 bereskaLND dotnet[9189]:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Apr 22 22:39:14 bereskaLND dotnet[9189]:    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /home/admin/btcpayserver/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 55
Apr 22 22:39:14 bereskaLND dotnet[9189]:    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
Apr 22 22:39:14 bereskaLND dotnet[9189]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**To Reproduce**

**Expected behavior**

**Actual behavior**
Tell us what happens instead

**Screenshots/Links**
If applicable, add screenshots or links to help explain your problem.

**Additional context**

**Comment by bereska** [comment]
amendment
btcpayserver v1.0.3.94-9-gdc04839f

**Comment by bereska** [comment]
installed .NET SDK 2.2.102
no change
same error
server settings webpage is still not accessible https://btcpay.bereska-lnd.duckdns.org/server/users
help

**Comment by pavlenex** [comment]
So what's the issue? The Server Settings page is not available?

That's because you need to be logged in as Server **Admin** to see it. If you forgot password[ follow this guide](https://github.com/btcpayserver/btcpayserver-doc/blob/master/FAQ/FAQ-ServerSettings.md#forgot-btcpay-admin-password)
Otherwise, I can fully see and access your server front page.

**Comment by bereska** [comment]
I am logged in as admin, the front page and other pages are Ok, i see Server Settings Tab but i get HTTP ERROR 500

**Comment by bereska** [comment]
bitcoind, lnd, nbxplorer are all running OK

**Comment by NicolasDorier** [comment]
You should have more logs than this.

**Comment by NicolasDorier** [comment]
Also try
```
ExecStart=/usr/bin/dotnet run --no-launch-profile --no-build -c Release -p "BTCPayServer/BTCPayServer.csproj" --conf /data/btcpayserver/btcpayserver.conf --datadir /data/btcpayserver/
```

**Comment by bereska** [comment]
I am lost here, all permissions look here:
admin@bereskaLND:~ $ ls -lash /home/admin/.btcpayserver/Main
total 384K
4.0K drwxr-xr-x 3 admin admin 4.0K Apr 21 16:45 .
4.0K drwxr-xr-x 5 admin admin 4.0K Apr 10 05:33 ..
4.0K drwxr-xr-x 2 admin admin 4.0K Apr 23 17:24 InvoiceDB
4.0K -rw-r--r-- 1 admin admin 2.9K Apr 10 05:53 settings.config
368K -rw-r--r-- 1 admin admin 364K Apr 21 16:45 sqllite.db

**Comment by NicolasDorier** [comment]
I don't know. I only know what I gave you above work.

**Comment by bereska** [comment]
strange, everything is working except for that Server Settings web page(
maybe I should have run ./build.sh again both for nbxplorer and btcpayserver after updating DOTNet SDK to 2.2 since it was all manual install with git for me?
thank you

**Comment by bereska** [comment]
sure enough, after running ./build.sh both for nbxplorer and btcpayserver all is good now
this can be closed now
thank you
