### ISSUE TITLE
Feature Request: Additional Scheme for Bech32 on-top of Legacy style addresses

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#781]
**Is your feature request related to a problem? Please describe.**
Btcpay only offers the ability to have one derivation path tied to a store. I'd like to somehow start offering bech32 wallet addresses in addition to lightning and segwit compatible wallets. 

I see this as a first step towards pushing bech32 native addresses to the consumers. 

**Describe the solution you'd like**
Bech32 could be listed under BTC and lightning BTC as its own coin. There also could be a simple checkbox or button on the BTC page saying "native segwit/bech32" that when enabled the qr and addresses switch from the legacy/segwit compatible to bech32 and vice versa. This would only exist if both schemes existed as well.

**Comment by kemoantemo** [comment]
totally agree

**Comment by woutersamaey** [comment]
Is it currently possible for BTCPay Server to generate bech32 addresses? When connecting my Ledger Nano S, I don't get Bech32-style addresses. Is there a workaround - something to enter in manually?

**Comment by astupidmoose** [comment]
So this is quite old, and most wallets should support bech32 now, although I will still use legacy segwit for a while to come. 

That being said, I think the same theory applies, but for Taproot. I'd love to offer taproot to those who can use it, but also offer a traditional address to those who don't.
