### ISSUE TITLE
Calculate transaction costs with address weight in mind

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#782]
The option to always add the transaction fee to the invoice should help cover the fees involved in sending the collected funds to an exchange and therefore it would make sense to calculate the amount of fees dependant on the kind of address that the money was sent to (legacy/p2sh/native segwit). However from my test it seems to always calculate the fees based on an kind of optimal case. For example I did two payments in a row: native segwit and legacy and both times it calculated: 0.000039 BTC in fees. I twould have expected to see higher fees for the legacy payment target as it costs more to retrieve those funds.

@kukks added in Mattermost:
[..]The ocde currently assumes each tx is 100 bytes from the looks of it and ignores address weight
`onchainMethod.NextNetworkFee = onchainMethod.FeeRate.GetFee(100); // assume price for 100 bytes`

**Comment by NicolasDorier** [comment]
Well doing it correctly is more complicated, as we have to estimate the size of the actual scriptSig. 

Assuming 100 bytes is way easier and is not so far from the real cost. It overshoots for segwit but well, that does not happen often.

**Comment by petzsch** [comment]
As much as I like a perfect solution, a small improvement would already go a long way. :-)

Offering all 3 address types and asking customers for the transaction fee on checkout, it would incentives them to opt for bech32 if the other options are more expansive.

For me 3 size estimates, without taking into account multisig wallets, would already be an improvement.

**Comment by petzsch** [comment]
It can always just be an estimate anyway, as no-one knows where fees will actually be at at the time the wallet of a store is being transferred.

**Comment by Kukks** [comment]
How about a simple solution:

We allow you to enter the network fee yourself on the store level. If
blank, it defaults to the current implementation.
ᐧ

**Comment by petzsch** [comment]
I would prefer to enter a avg. transaction size rather than fixed fees (they can fluctuate) (maybe provide some documentation what typical avg values could be)

**Comment by bolatovumar** [comment]
Should we close this issue or do we still want to do something here? If we are still planning on doing something then I feel like @Kukks's suggestion above makes the most sense as I don't think most merchants will know what size their transactions will be. On the other hand, if a merchant sets a fixed fee they might end up with too low or too high of a fee while basing the fee off a custom transaction size would avoid this issue. I'm wondering if exposing a slider allowing the merchant to set a value on this slider with the currently used default value being somewhere in the middle.

cc @petzsch @pavlenex @Kukks

**Comment by Kukks** [comment]
We should probably expose this through a plugin, it feels like such a niche
feature as most won't understand it

**Comment by petzsch** [comment]
This feature is no longer relevant to me. I'm aggregating payments and sending them to the exchange when the [Broadcast1 twitter bot](https://twitter.com/Broadcastnow1) tells me that fees are low.

Imho this issue can be closed.

**Comment by pavlenex** [comment]
Aye, closing this one then, since there hasn't been much interest/consensus. Let's re-open if we see the need. Thanks for helping with the cleanup @bolatovumar and @petzsch.
