### ISSUE TITLE
Store Email Password not saving

### ISSUE THREAD

**Issue by whereskarlo** [btcpayserver/btcpayserver#786]
On the email settings for stores, the password does not save after clicking "Save". The server SMTP settings save all fields, and email works. For the store however, the password field is blank after saving and sending email generates a login error for the smtp server. The only way to send a test email for the store email settings is to enter the password and then click "test".

**Comment by pavlenex** [comment]
Thanks for reporting, this is indeed a bug that was fixed in [0b98e ](https://github.com/btcpayserver/btcpayserver/pull/642/commits/0b98e362d5c9e5f16898f214276e03c1060fcef0)for email settings on a Server level but has not been done for the store-level e-mails.

**Comment by whereskarlo** [comment]
Thanks. I haven't been able to find any documentation on this; what is the purpose of the store-level email settings? In what scenario will store-level emails be sent?

**Comment by pavlenex** [comment]
Not many stuff at this point, you can configure certain apps like crowdfunding, payment button or payment requests and receive emails (@Kukks on which actions will those be sent? Am I right on this one?). 

Should you need crazy complex email setup, I advise you to give our[ BTC Transmuter a try](https://github.com/btcpayserver/btcTransmuter), it's still in alpha though and may require a bit of tech knowledge to get started.

We'll document it better once everything is tied up neatly.

**Comment by Kukks** [comment]
Yup, if `fullNotifications` or `extendedNotifications` are enabled on an invoice along with having the `notificationEmail` set, you will receive an email with some json data on each status update and on each payment

**Comment by whereskarlo** [comment]
Got it. Maybe it's the wrong place for questions, but what is the purpose of "redirect invoice to redirect url automatically after paid"? If not enabled, is there a button for the user to be manually taken back to the redirect url after payment?

**Comment by Kukks** [comment]
It's for people that want to take their users to a thank you page right after an invoice is paid. And yes, there would be a button if not enabled.
