### ISSUE TITLE
Display bug on mobile for checkout page

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#79]
The logo of the QR is not exactly on the middle on mobile (Chrome IOS).

I hacked that myself, @lepipele any idea why I failed ? :(

**Comment by lepipele** [comment]
It seems this has to do with description text being long - @Eskyee reported later that it had to do with changes he did on the page: https://forkbitpay.slack.com/archives/C7M093Z55/p1521902675000056

**Comment by NicolasDorier** [comment]
Why closing this ? I think @Eskyee was talking about something else, this bug still happen.

**Comment by NicolasDorier** [comment]
Fixed in 1.0.1.69
