### ISSUE TITLE
POS Layout broken on iPad Safari 9.3.5

### ISSUE THREAD

**Issue by Kixunil** [btcpayserver/btcpayserver#793]
**Describe the problem/bug**
When PoS is opened on iPad with iOS/Safari 9.3.5, the layout is broken. Screenshot is worth thousand words.

**Your environment**
* Version of BTCPay Server: commit ad0edb5f4cfa872d959fabcf55d22a3ed29507dc
* Deployment method: Manual
* Other relevant environment details: Tried Safari in both Browser and PWA mode.

**To Reproduce**
1. Open PoS app from iPad with iOS 9.3.5
2. Look and see

**Expected behavior**
The items are shown with correct width

**Actual behavior**
Each item has near zero width.

**Screenshots/Links**
https://drive.google.com/file/d/17ROXaE0VJqyU4QnNhDmvTOUGBYUSv2lK/view?usp=sharing
https://drive.google.com/file/d/1vJwUwRoY-WYJNXKcNPF5DWIm1htUNfn_/view?usp=sharing

**Additional context**
The layout was fine in previous versions and broke once we updated to fix the latest issue with the LN payment not being confirmed on the screen.

**Comment by Kukks** [comment]
Does it work fine on Chrome?

**Comment by Kukks** [comment]
I've tried a few different versions of Ipad devices with Safari on Browserstack and had no luck.  Ca you give us your url?

**Comment by Kixunil** [comment]
I was unable to install Chrome. The URL is: https://pay.paralelnapolis.sk/apps/2U2FYaWXUAYjydExuhxzzGXE8xT2/pos

**Comment by Kukks** [comment]
I don't have any Apple products to test tablet-safari browsers.. I tried Browserstack but it look ok on that.

**Comment by pavlenex** [comment]
9.3.5 is a quite outdated version. Can't you update it to more recent one?

I tried via several testing tools and on actual Safari 12+ and everything works there.

Can grab console logs from the device itself and post them?

**Comment by jooray** [comment]
So I tested with more recent iPad/iOS and it is not broken.

Sadly we cannot update, Apple does not support this hardware version with new updates anymore, but it will be cheaper if we just buy a new tablet rather than waste time on fixing this.
