### ISSUE TITLE
P2E (Pay to endpoint)/Stowaway support

### ISSUE THREAD

**Issue by Kixunil** [btcpayserver/btcpayserver#795]
**Is your feature request related to a problem? Please describe.**
Bitcoin currently suffers in privacy. P2E/Stowaway are features that would help to address this problem, but they depend on the receiver to implement them. Implementing them to BTCPayServer would be great for convenience and privacy.

**Describe the solution you'd like**
Implement server side of P2E/Stowaway.

**Describe alternatives you've considered**
* Just use Lightning Network
* Fork the project and implement it there

**Additional context**
There's a security issue with these kinds of payments, as the private keys must reside on the server. A way to alleviate this problem would be to allow administrator to select a limit on maximum amount of bitcoins held in hot storage. Once this limit is reached, the next P2E/Stowaway transaction will be sent directly to the cold storage and the subsequent one will be performed without P2E/Stowaway.

**Comment by Kukks** [comment]
BtcPay won't hold any private keys on its deployment. Hot wallets have no place in BtcPay( with the exception of lightning). 
We do have a sideproject that acts as a plugin to btcpay that allows you to have hot wallets though. Just not sure we can offer P2E through it

**Comment by Kixunil** [comment]
Yeah, that's why I suggested to limit it. I'm looking forward to see the plugin!

**Comment by pavlenex** [comment]
Since this is obviously hard to happen in BTCPay, perhaps re-open it in the [Transmuter repository](https://github.com/btcpayserver/btcTransmuter).

I'll mark this one as `closing`
