### ISSUE TITLE
timeout when using lightning-charged? Only on-chain payment proposed

### ISSUE THREAD

**Issue by mocacinno** [btcpayserver/btcpayserver#799]
**Describe the problem/bug**
I have an experimental store that allows people to unblur images by paying a couple satoshi's for an unblurring step. I use lightning charged on top of c-lightning and i configured 
the connection to my lightning charged node.  
When i visit my store after a while, and click the pay button so an invoice would be generated, only an on-chain payment method is proposed. When i hit the back-button and re-create the invoice, both on-chain an LN payment methods are proposed.  
In the debug log, i only see the two invoices being created, but only after the second one i see the notice "BTC (Lightning): Start listening http://127.0.0.1:9112/"

**Your environment**
* Version of BTCPay Server: cloned the master from github about 5 days ago
* Deployment method: manual install
* Other relevant environment details: ubuntu 16.14, bitcoind 0.16.3, clightning fetched from github 5 days ago, lightning-charged fetched from github 5 days ago

**Logs (if applicable)**
2019-04-29 11:43:17.416 +00:00 [INF] Invoice Mojj1D6Zk7kH7yUTDsVYP6 new event: invoice_created (1001)
2019-04-29 11:43:52.342 +00:00 [INF] BTC: New block
2019-04-29 11:44:17.340 +00:00 [INF] Invoice YQyWbygSEBYsTedL7pUstB new event: invoice_created (1001)
2019-04-29 11:44:17.382 +00:00 [INF] BTC (Lightning): Start listening http://127.0.0.1:9112/
2019-04-29 11:47:16.803 +00:00 [INF] BTC: New block

**To Reproduce**
1. Go to https://unblur.ninja/image.php?id=114
2. Click on the payment button
3. Sometimes only on-chain payment is proposed, sometimes both on-chain and lightning

**Expected behavior**
Always show both onchain and lightning payment proposals, or at least log what went wrong

**Comment by pavlenex** [comment]
This is your Lightning Node issue, you should[ look at c-lightning logs](https://docs.btcpayserver.org/support-and-community/troubleshooting#2-2-2-lightning-network-c-lightning-docker). When your node is down, btcpay does not propose it.
