### ISSUE TITLE
Sorting on "Invoices" Screen

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#8]
Add a way to be able to sort/display certain order status. 

If the shop generates a lot of abandoned carts/unused addresses then it might become hard to find invoices needed. 

Adding a "Status" selector, or the ability to filter multiple status types will help.

**Comment by astupidmoose** [comment]
Example of Mycelium Gear:

![showall](https://user-images.githubusercontent.com/3916318/31879447-4c480a56-b792-11e7-80e7-3f9cdc945b3a.PNG)

**Comment by NicolasDorier** [comment]
any idea on which fields to export ? also normally such things are more handled by ecommerce website no?

**Comment by NicolasDorier** [comment]
Done in v1.0.0.35
