### ISSUE TITLE
2FA Recovery Code - Confusing navigation

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#806]
**Is your feature request related to a problem? Please describe.**
When someone sets up 2FA, they're asked to save their backup keys, but there's not a single indicator what to do from there. It's confusing and users just don't know what to do even when they write the backup keys. 

![Manage your account](https://user-images.githubusercontent.com/36959754/57094377-b845d780-6d10-11e9-972a-58949b156f75.PNG)

**Describe the solution you'd like**
Add a clear CTA button for user to navigate away.
"I wrote my backup codes" or something similar.

**Comment by bolatovumar** [comment]
@pavlenex where do you think this button should lead the user to? Back to the profile page?

**Comment by pavlenex** [comment]
@bolatovumar yeah, I think that would make sense.
