### ISSUE TITLE
Self host with WordPress

### ISSUE THREAD

**Issue by justin7942163** [btcpayserver/btcpayserver#810]
I'm running a self hosted WordPress server in a Ubuntu virtual machine with a custom URL to my public IP and port forwarding to my WordPress site. 

I don't want to pay a service to host a virtual machine for me to run BTC server. 

But I'm having troubling setting up BTCPay in a different virtual machine on my server PC as the ports BTCPay use are the same ports that WordPress uses. 

It's it possible to install BTCPay with my set up? Can someone please link me with a tutorial help with my problem?

**Comment by pavlenex** [comment]
There's a tutorial (experimental) to host WordPress inside BTCPay, but there's no vice-versa article.
https://medium.com/@BtcpayServer/btcpay-woocommerce-cheap-ab6fcdd97075

**Comment by justin7942163** [comment]
Thank you very much, so I just follow this tutorial but install the virtual machine on my own hardware instead of the VPS service and then I can avoid any monthy fees yeah?

**Comment by Eskyee** [comment]
@justin7942163 Thats correct thanks to BTCPay..

Q. so I just follow this tutorial but install the virtual machine on my own hardware instead of the VPS service and then I can avoid any monthy fees yeah?

**Comment by justin7942163** [comment]
Hey everyone, thanks for your help! I've got it up and running and can access both pages with my URL's.

Next issue is, the node sync doesn't seem to be moving. It's been stuck on 

NBXplorer headers height: 0
The node is starting...

For a while now.

![image](https://user-images.githubusercontent.com/31229612/57179447-6abc9c80-6ec1-11e9-914e-3c1293833cb7.png)

Here's all I see in the Terminal window.

![image](https://user-images.githubusercontent.com/31229612/57179468-a7889380-6ec1-11e9-9906-fa2d8a160a05.png)

Where do I go from here? Should I just restart the virtual machine?

**Comment by pavlenex** [comment]
[See the sync troubleshooting guides](https://docs.btcpayserver.org/faq-and-common-issues/faq-synchronization) to troubleshoot.

 Depending on your machine specs and the amount of coins added it can take from 1-7 days for your node to fully sync.

To speed that up you can use [FastSync](https://github.com/btcpayserver/btcpayserver-docker/tree/master/contrib/FastSync) (make sure to read to understand what Fast Sync is and how it works) 

Fast Sync instructions are from [Step 15 of this guide](https://github.com/btcpayserver/btcpayserver-doc/blob/master/RaspberryPiDeployment.md).

**Comment by justin7942163** [comment]
I've got the machine running on a Pentium G4650 with 8GB of DDR4 RAM and a 5400 HDD, my internet connection is decent.

![image](https://user-images.githubusercontent.com/31229612/57191710-e1ae6f80-6f6b-11e9-8fe2-e4fc4fe7bb2d.png)

I've enabled FastSync, restarted BTCPay with btcpay-up.sh and I'm still stuck on 'The Node is Starting'

**Comment by justin7942163** [comment]
It still hasn't made any progress, I've downloaded FastSync twice and still I am stuck on XBXplorer headers height: 0 and The node is starting...

What should I do?

Completely reinstall Ubuntu and try again?

**Comment by NicolasDorier** [comment]
@justin7942163 your error means that you somehow disabled pruning after activating it at first.

**Comment by NicolasDorier** [comment]
So you need to add the `opt-save-storage` in the additional fragments back.

**Comment by justin7942163** [comment]
This is on a fresh install of Ubuntu, I've just installed BTCPay Server WITH opt-save-storage enabled. I've stopped it to enable FastSync and I get this:

./btcpay-down.sh: line 10: syntax error near unexpected token `fi'
./btcpay-down.sh: line 10: `fi'


![image](https://user-images.githubusercontent.com/31229612/57299060-06931600-7117-11e9-9a89-b2cf1155dcab.png)

Does this mean anything or can it be ignored?

I'm downloading the utxo-snapshot right now, now that it's a fresh install hopefully it all works out. I'll report back here after it's done and I fireup BTCPayServer again.

**Comment by justin7942163** [comment]
It still isn't working, I've followed your instructions. Restarted everything and I am still stuck.

![image](https://user-images.githubusercontent.com/31229612/57354095-e5c9cf80-71ad-11e9-8854-22f53768e0f2.png)

This is all I see, it's the same everytime. The wordpress/woocommerce addon works fine but BTCPay won't sync.

![image](https://user-images.githubusercontent.com/31229612/57354116-fbd79000-71ad-11e9-85dc-3c83de5d586f.png)

**Comment by justin7942163** [comment]
I've downloaded Ubuntu 19, installed BTCPayServer with the XS prune option and FastSync. 

I am able to access the server page, it still says nodes are synching with 0 progress.

I ran the docker logs --tail 10 btcpayserver_bitcoind command and received this back.

![image](https://user-images.githubusercontent.com/31229612/57424094-d30cd480-7259-11e9-9a90-a117a899b83c.png)

Does this mean it's all working and I should see some progress with the node sync soon or is it still wrong?

**Comment by justin7942163** [comment]
I think the overall problem is adding the wordpress/woocommerce option prevents the node from syncing.

I've just shut down the server in order to add the wordpress addon and now I'm waiting for it to sync again.

![image](https://user-images.githubusercontent.com/31229612/57517189-9e804200-7359-11e9-9761-dbfa345fd6e3.png)

This is what I see, I'll keep the thread updated with what happens next.
