### ISSUE TITLE
You access BTCPay Server over an unsecured network.

### ISSUE THREAD

**Issue by mariodian** [btcpayserver/btcpayserver#818]
I'm getting the following message when I access btcpay frontend on https://btcpay.freedomnode.com: 

```
You access BTCPay Server over an unsecured network. If you are using docker deployment with NGINX and HTTPS is not available, you probably did not configured your DNS settings right. 
We disabled the register and login link so you don't leak your credentials.
```

As you can tell the website has a valid certificate. 

My settings.config:

```
network=mainnet
chains=btc
port=23001

BTC.explorer.url=http://127.0.0.1:24445
BTC.lightning=type=lnd-rest;server=https://127.0.0.1:8888/;macaroonfilepath=/home/satoshi/.lnd/data/chain/bitcoin/mainnet/admin.macaroon;certthumbprint=<fingerprint>

postgres=User ID=<user>;Password=<pas>;Host=localhost;Port=5432;Database=<db name>;
```

I installed btcpay manually using [this guide](https://freedomnode.com/blog/114/how-to-setup-btc-and-lightning-payment-gateway-with-btcpayserver-on-linux-manual-install)

So I'm running with Apache and reverse proxy.

Everything worked fine until I pulled from master just now (I usually update once a month).

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

**Comment by NicolasDorier** [comment]
manual deployment? https://docs.btcpayserver.org/faq-and-common-issues/faq-deployment#btcpay-is-expecting-you-to-access-this-website-from

**Comment by NicolasDorier** [comment]
Basically your Apache need to forward the Host and the protocol of the client down to btcpay server.

**Comment by Jagermeister56** [comment]
Same issue using docker. Can only visit http version, https version gives 500 error
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

**Comment by NicolasDorier** [comment]
@Jagermeister56 you need to open ports 80 and 443 and make sure your hostname is correctly set.
Once done, `docker restart letsencrypt-nginx-proxy-companion`.
If it still does not work `docker logs letsencrypt-nginx-proxy-companion`

**Comment by cryptoquick** [comment]
I came across the same issue, but was able to solve it by modifying my nginx config after having modified it with letsencrypt (certbot), as per these instructions:
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-18-04

Then, I went through these instructions, modifying them to work with my locally running BTCPay Server:
https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-with-ssl-as-a-reverse-proxy-for-jenkins

After restarting nginx, worked like a charm. Thanks for pointing me in the right direction, @NicolasDorier !

**Comment by cryptoquick** [comment]
Apologies if this is hijacking the original thread, but folks might run into this if following my instructions.

I noticed that I couldn't register on the server, and was instead routed to a URL with capitalized route segments.

I then took a look at the Docker config, and lo and behold, these are the lines you need:

https://github.com/btcpayserver/btcpayserver-docker/blob/master/Production/nginx.tmpl#L144-L153

But there's more; on a default nginx config, you don't have some important map directives to make that work. These need to be outside your server block:

https://github.com/btcpayserver/btcpayserver-docker/blob/master/Production/nginx.tmpl#L90-L126

And voila, it works.

**Comment by Jagermeister56** [comment]
seems to be a problem with docker and letsencrypt certificate. 
i generated a letsencrypt cert manually with certbot, can i force the docker companion to use this cert instead?

**Comment by NicolasDorier** [comment]
@Jagermeister56 the docker setup set things up automatically, you should not try to do manual things.

**Comment by Jagermeister56** [comment]
@NicolasDorier i don't really have a choice since my port 80 is blocked by ISP :(
If i can use the cert i generate with certbot in /etc/letsencrypt verified by TXT DNS and load it into the letsencrypt-companion container it should work. Any suggestions?

**Comment by NicolasDorier** [comment]
Yeah you can. Check in `/var/lib/docker/volumes/generated_nginx_somethingblahblah`.
It is possible that the cert renewal don't need port 80.

**Comment by mariodian** [comment]
> manual deployment? https://docs.btcpayserver.org/faq-and-common-issues/faq-deployment#btcpay-is-expecting-you-to-access-this-website-from

Thanks that fixed it!

**Comment by NicolasDorier** [comment]
Cool!

**Comment by atingupta2005** [comment]
> Apologies if this is hijacking the original thread, but folks might run into this if following my instructions.
> 
> I noticed that I couldn't register on the server, and was instead routed to a URL with capitalized route segments.
> 
> I then took a look at the Docker config, and lo and behold, these are the lines you need:
> 
> https://github.com/btcpayserver/btcpayserver-docker/blob/master/Production/nginx.tmpl#L144-L153
> 
> But there's more; on a default nginx config, you don't have some important map directives to make that work. These need to be outside your server block:
> 
> https://github.com/btcpayserver/btcpayserver-docker/blob/master/Production/nginx.tmpl#L90-L126
> 
> And voila, it works.

both ur suggesstions din worked
