### ISSUE TITLE
When viewed as portrait, BTCPAY Loads on iphone standard size display, & Text bleeds the screen, makes page wobble, untidy feel !! But landscape view is perfect.

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver#82]
Since landscape has more room, we need a fix, for small screens.
![image_uploaded_from_ios](https://user-images.githubusercontent.com/30862925/37914170-7ffd464a-310e-11e8-9c0c-8705ecf17ecf.png) this is perfect !! in Landscape.

![image_uploaded_from_ios-1](https://user-images.githubusercontent.com/30862925/37914467-2e4f3b72-310f-11e8-9d31-1f20907dc5ac.png)

 
BTCPay site is perfect in landscape view on a iPhone SE !! But since the screen size in portrait view is the most common way to view the BTCPay site!!! 

I thought it would be nice to fix the bleeding !! Since it’s only like one line I think that breaks the screen size rule.. so it wobbles about!!! Lol not so nice !! Makes it untidy !!!

this is the untidy view, with wobble, 

![image_uploaded_from_ios_1024](https://user-images.githubusercontent.com/30862925/37914295-d5305bc0-310e-11e8-9270-c0f1e0fa4abe.png)

Text leaves the display area !!

checked on most device's screen size, and BTCPAY looks good, no problems

**Comment by NicolasDorier** [comment]
I how can one read such big table on a mobile device?

**Comment by Eskyee** [comment]
Just researching here on guide lines https://developer.apple.com/ios/human-interface-guidelines/views/tables/

**Comment by Eskyee** [comment]
And here https://docs.microsoft.com/en-us/xamarin/ios/tvos/user-interface/table-views?tabs=vsmac

**Comment by Eskyee** [comment]
https://docs.microsoft.com/en-us/xamarin/ios/user-interface/controls/tables/

**Comment by Eskyee** [comment]
Been reading up here!! Sounds interesting!! Not sure if it can help our solution :  https://stackoverflow.com/questions/31267749/truncate-text-for-dynamic-width-responsive-through-css?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by NicolasDorier** [comment]
I don't think we can do more than what is already done now. Can you check if it is better since the last push on bootstrap4?

We should probably close this as this is problem that we just can't fit lot's of info in small screen so we can't do anything else than scrolling.

**Comment by Eskyee** [comment]
@NicolasDorier 
I have updated  BTCPay Server  v1.0.1.82
Hey its almost perfect !! the views now are looking right, no mess, just scrolling nice,
on all pages but one, 
invoice details page needs the same treatment, as the other pages, to scroll correctly now,
 
then as far as Mobiles iPhones, iPads, etc etc  looks good, feels good, much more clean and stable now.. 
great job Nicolas & Peusa

**Comment by Eskyee** [comment]
once invoice page updated with fix, you can close this issue,

**Comment by lepipele** [comment]
@Eskyee I've looked into that stuff when migrating to bootstrap4... will see to apply same thing to invoice details page and check how it looks in different resolutions. Will update you once done.
