### ISSUE TITLE
Issues on iOS Onion Browser when browsing a PoS 

### ISSUE THREAD

**Issue by Sosthene00** [btcpayserver/btcpayserver#825]
**Describe the problem/bug**
I noticed some issues when browsing a PoS on a testnet instance over Tor :
* sometimes there's nothing when clicking on "pay" button, just an empty screen. 
* the items picture doesn't show up (I'm using the default demonstration store with the tea)
* switching from bitcoin on-chain to lighting doesn't work, the qr code never shows up (see screenshot)
Everything is normal when on a laptop, so I guess it might be a specific issue with either iPhone or Onion Browser

**Your environment**
* Version of BTCPay Server: v1.0.3.94
* Deployment method: docker
* Other relevant environment details: testnet, no domain name set, the site is accessible only through onion address, the PoS is the default demonstration store (with the tea)

**Logs (if applicable)**
Nothing of interest, it just shows that invoice were created

**To Reproduce**
1. set a PoS app up
2. connect to it with Onion Browser on an iPhone
3. click on any "pay" button
4. try to switch from bitcoin to lightning payment

**Expected behavior**
I should be able to see the item pictures. A new page should open with an invoice so that it can be paid every time I click on "pay". I should be able to switch from bitcoin on chain to lightning

**Actual behavior**
Pictures don't get displayed. Invoices fail to be displayed erratically. Switching to lightning payment get stuck

**Screenshots/Links** (sorry they're huge I don't know why)
![btcpay_bug1](https://user-images.githubusercontent.com/11726747/57412723-fe5bd900-71f1-11e9-9302-9c237a8f1101.jpg)
![btcpay_bug2](https://user-images.githubusercontent.com/11726747/57412727-01ef6000-71f2-11e9-9f19-18c042540b4c.jpg)

**Additional context**

**Comment by pavlenex** [comment]
This seems to be related to f #793

**Comment by pavlenex** [comment]
@BobleChinois Can you check now on latest the QR code not showing`1.0.3.125` it should be fixed.

**Comment by BobleChinois** [comment]
Hi @pavlenex, sorry I've been away for the past month, I don't have the same testnet node anymore but I will try it out asap and let you know if my problem is solved

**Comment by pavlenex** [comment]
@Sosthene00 hey, still experiencing issues with this or can I close it? I can't seem to replicate it.
