### ISSUE TITLE
Wallets reset after update

### ISSUE THREAD

**Issue by hubiktomas** [btcpayserver/btcpayserver#829]
**Describe the problem/bug**
I have updated the BTCPayServer approx 10 days ago. I do not remember the version, but based on GitHub releases, it was probably 1.0.3.94. Transactions from my wallets got lost, @NicolasDorier  told me that there was some issue with NBxplorer. I have done rescan of the BTC wallet and created a ton of invoices for the LTC wallet as rescan is not implemented here and send all the funds so that balance from BTCPayServer interface will match the actual balance. All worked. But then I have done another update a couple of days ago to version 1.0.3.97 and hit the same problem - transactions are lost, so I did the rescan again for BTC and created ton of invoices for LTC + emptied the LTC wallet so the balance will match.

**Your environment**
* Version of BTCPay Server: 1.0.3.97
* Deployment method: Azure
* Other relevant environment details: Instance deployed approx 1 year ago, using BTC, LTC and LND

**To Reproduce**
1. Update the BTCPayServer from SSH command line using btcpay-update.sh
2. Open the web interface and look at the Wallets
3. Wallets balance does not match the actual balance, transactions are lost
4. Alternatively try to create an invoice - you will get an exception as the address was already used, BTCPayServer just does not know about it until you do the rescan

**Expected behavior**
Transactions should remain after update.

**Actual behavior**
Transactions are lost after update.

**Comment by NicolasDorier** [comment]
@hubiktomas transaction should not disappear, nor any money.
Please, try to go in Wallet/Rescan and do a rescan.

**Comment by NicolasDorier** [comment]
Ah sorry you did the rescan already!

**Comment by NicolasDorier** [comment]
Ah now I remember. It should not happen again. Happening once it is normal, as I messed up at one point. But twice it is strange. Try once again.

**Comment by hubiktomas** [comment]
Ok. So a short recap:
1. I updated the BTCPayServer, then it happened and you helped me out saying that this issue is already fixed and should not happen again.
2. I updated again and it happened again already knowing how to fix it/work around it and submitted this issue as it happened again.
3. I have updated the instance again now for the third time and everything looks good.

In another issue (#830) you told me that You have updated the litecoind so I can do rescan if there is a problem - you meant just using the command line or also using the web interface? Because the web interface keeps saying that this feature is not supported.

**Comment by NicolasDorier** [comment]
In the interface, it should be possible in the interface now, I tried on my own server and it works.

**Comment by NicolasDorier** [comment]
I just updated the stable branch try again

**Comment by hubiktomas** [comment]
Is it in the stable branch for update? I am running 1.0.3.103 and it cannot be run from the web interface.

**Comment by NicolasDorier** [comment]
run btcpay-update again

**Comment by hubiktomas** [comment]
The problem did not reappear and if it does, there is the rescan feature available now, thank you.
