### ISSUE TITLE
Most recent invoices not visible in Ride the Lightning

### ISSUE THREAD

**Issue by hubiktomas** [btcpayserver/btcpayserver#830]
**Describe the problem/bug**
When I open the Ride the Lightning interface, I do not see the most recent invoices. I can see the older ones (approx till the end od November 2018). When I try to create a new Invoice, it gets created and I can see it in the interface, but after page refresh, it is gone. I can see it using the command line interface.

**Your environment**
* Version of BTCPay Server: 1.0.3.97
* Deployment method: Azure
* Other relevant environment details: Installed approx 1 year ago, using BTC, LTC and LND

**Logs (if applicable)**
I cannot see any error in LND logs, nor in log files in the web interface.

**To Reproduce**
1. Open built in Ride the Lightning interface
2. Click on Invoices
3. Most recent invoices are not visible

**Expected behavior**
All the invoices should be visible,

**Actual behavior**
Only invoices till the end of November 2018 are visible.

**Additional context**
Not sure if it is relevant, but when I click Payments, I can see the loading bar, but it never stops loading.

**Comment by pavlenex** [comment]
RTL is application completely independent of BTCPay, you should [open an issue in their repository](https://github.com/ShahanaFarooqui/RTL).

**Comment by hubiktomas** [comment]
Looks like this issue was fixed in RTL 0.3.2 - I do not know, which version we have now in the stable BTCPayServer, because I am a little bit afraid to update because of the issue #829.

**Comment by NicolasDorier** [comment]
@hubiktomas I updated to 0.3.2

**Comment by NicolasDorier** [comment]
btw I updated Litecoin to 0.17.1 as well, so if it happens again, you can rescan.

**Comment by hubiktomas** [comment]
@NicolasDorier Is it in stable already? I have just updated the BTCPayServer and still see RTL 0.3.0

**Comment by NicolasDorier** [comment]
I just updated the stable branch

**Comment by hubiktomas** [comment]
Works now, thank you. :)
