### ISSUE TITLE
File Storage Issues

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#834]
**Describe the problem/bug**
- Timestamp of file upload is not my local time.
- Create temporary file link issues: 
    - expiry timer does not work properly
    - isDownload checkbox doesn't download the file

**Your environment**
* v1.0.3.103
* LunaNode
* FileSystem Storage Method

**To Reproduce**
1. Upload file
2. Get Temp Link > Generate

**Expected behavior**
1. Choose expiry time 10 seconds
2. isDownload box checked

**Actual behavior**
1. Link doesn't expire after 10 seconds
2. Doesn't download file when box is checked

**Comment by NicolasDorier** [comment]
ping @Kukks
