### ISSUE TITLE
Small Typo

### ISSUE THREAD

**Issue by mandelmonkey** [btcpayserver/btcpayserver#838]
**Describe the problem/bug**
Small typo on the sync screen

"If you really don't want to synch and that you are familiar with command line, check FastSync."
should be sync?

**Your environment**
* Version of BTCPay Server: Latest
* Deployment method: Lunanode

**Comment by Eskyee** [comment]
The spelling "synch" is a variant of "sync", and "sync" (synced) is the one mostly used. Both are the informal short form of synchronize (as in synchronization).

**Comment by mandelmonkey** [comment]
ah thanks I didnt know that, I learn something new everyday
