### ISSUE TITLE
Bitcoin c-lightning Channel "AWAITING_UNILATERAL" Peer connection lost closing, CPU 100% 

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver#839]
**Describe the problem/bug**
Bitcoin c-lightning Channel "AWAITING_UNILATERAL" Peer connection lost closing, CPU 100% Spikes

**Peer connection lost/bug Peer transient failure in CHANNELD_NORMAL: lightning_channeld: Owning subdaemon lightning_channeld died (9

**Channel AWAITING_UNILATERAL since days CPU Spikes CPU 100%. bitcoin-cli exec failed: Out of memory

**Your environment**
Ubuntu 18.04.1 LTS (GNU/Linux 4.18.0-1014-azure x86_64)

* Version of BTCPay Server: 
.103
* Deployment method:
 Azure
* Other relevant environment details:
 c-lightning

**Logs (if applicable)**
Basic logs can be found in Server Settings > Logs.

lightningd: Fatal signal 6 (version basedon-v0.7.0-3)
0x55647dd5b718 crashdump
	common/daemon.c:40
0x7f360077e0e9 ???
	???:0

I found one of my channels was in "AWAITING_UNILATERAL" so now I see it was for weeks in that state. 
plus another channel AWAITING_UNILATERAL for like a year, lol

so found a solution by closing this bugged out channels, 
bitcoin-lightning-cli.sh close "Full Channel ID:"  true 

bitcoin-lightning-cli.sh close °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°  true   
or with this command:   
bitcoin-lightning-cli.sh close -k force=true id=°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°

https://live.blockcypher.com/btc/tx/e15db667fb706165f7e7529af151ea294a26f7d3324a95d70a45a90d82f1b327/

Status: AWAITING UNILATERAL
Status: ONCHAIN
"ONCHAIN:Tracking our own unilateral close
 ONCHAIN:All outputs resolved: waiting 99 more blocks before forgetting channel"

Age: 1615 blocks (a couple of weeks)

check here for some past bug history.

re. https://github.com/ElementsProject/lightning/issues/2171
https://github.com/ElementsProject/lightning/issues/1865
Not sure why but I think this started around April 11th, 

also this seems to mess with spark wallet. container restarting!! sometimes

found this with other channels not closing after a long time.

bitcoin-lightning-cli.sh close "Full Channel ID:"  true 
seemed to solved my problems.

**Comment by Eskyee** [comment]
<img width="1080" alt="Screenshot 2019-05-14 at 20 53 38" src="https://user-images.githubusercontent.com/30862925/57724327-d5709380-768a-11e9-8c92-cdd8cfb9049d.png">
 watching docker stats for the last few hours, and CPU seem fine now, but will keep monitoring for a few days, Seems that was my was bug fixed for now

**Comment by Eskyee** [comment]
<img width="508" alt="Screenshot 2019-05-15 at 02 28 34" src="https://user-images.githubusercontent.com/30862925/57740998-d6b9b480-76ba-11e9-8b70-132728534e31.png"> lol had to force close this channel

**Comment by pavlenex** [comment]
This should probably be posted on the c-lightning repository, nothing we can do here about how c-lighting works I'm afraid.

**Comment by Eskyee** [comment]
Yes you are correct!! Pav 
But Nicolas ask me to to post a issue on Github here!! document in case someone else has this problem CPU spikes on their BTCPAY Server

**Comment by Eskyee** [comment]
Can close the issue anytime as my problem is solved now.

**Comment by pavlenex** [comment]
In that case, closing since it's resolved.

**Comment by pavlenex** [comment]
Re-opening this one since it continues to happen for @Eskyee

**Comment by Eskyee** [comment]
Thanks Pavlenex, yes this problem has seem to come back, from two channels I can see stuck in unilateral close limbo mode, will post a issue with the c-lightning guys today

**Comment by pavlenex** [comment]
Closing this one, since it's c-lightning issue already being addressed in their repo.
