### ISSUE TITLE
Directly uplading files via wysiwyg editor can cause performance issues (should be connected to internal storage)

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver#841]
**Describe the problem/bug**
Uploaded a 2.3MB jpeg "by mistake" as I have a smaller file size I didn't use.

uploaded picture to crowdfund app & the server froze !! 
had to hard restart!! now server back up and running fine.

Version of BTCPay Server: v1.0.3.103

@Kukks 

is their a limit uploading max limit, to stop this from being able to happen ??

**Comment by Eskyee** [comment]
<img width="509" alt="Screenshot 2019-05-15 at 15 08 53" src="https://user-images.githubusercontent.com/30862925/57779385-4618be00-7726-11e9-9927-23049b2eb98e.png">

**Comment by Kukks** [comment]
It crashed your server or your browser?

**Comment by Eskyee** [comment]
it crashed my server, it just froze, on uploading

**Comment by Eskyee** [comment]
I thought that's strange Kukks

**Comment by pavlenex** [comment]
I've added images up to 30mb in size on my and on your btcpunayjungle and found no issues.
That said it would be good if this could be integrated with internal storage and limited to admins, since this way anyone can upload a bunch of files and crash third-party host server.

**Comment by pavlenex** [comment]
I also see what you mean by "crashed" it has not crashed, but def performing slower.
wysiwyg editor's fault I think.

**Comment by Eskyee** [comment]
closing this as I dont have this problem anymore. thanks  
you can reopen if anybody else has this problem.
