### ISSUE TITLE
POS: It's impossible to learn why template is invalid

### ISSUE THREAD

**Issue by Kixunil** [btcpayserver/btcpayserver#843]
**Describe the problem/bug**
When an invalid template is entered into POS settings and saved, it says "Invalid template" without explaining what's invalid about it, so it's impossible to find out why it's invalid.

**Your environment**
* Version of BTCPay Server: commit ad0edb5f4cfa872d959fabcf55d22a3ed29507dc
* Deployment method: manual

**To Reproduce**
1. Go to POS app settings
2. Enter an invalid template
3. Click save
4. See unhelpful error message

**Expected behavior**
When an invalid template is entered, the error message clearly explains why it's invalid.

**Actual behavior**
The message contains no information about the reason why the template is invalid.

**Comment by pavlenex** [comment]
This is a well-known and quite annoying bug that I experienced numerous times. Unfortunately, I was not able to figure out when it happens. Usually, it happens when you add lots of new items or when you enter an inappropriate currency/price format.

I believe nobody was able to figure out exactly when it happens, but the weird thing is if you copy/paste that template entirely into a newly made PoS app, it usually works.

I think it's best to label this as a bug, perhaps @mariodian knows why it happens, but overall it will probably disappear once we refactor the PoS #749

**Comment by Eskyee** [comment]
I can recreate this bug, if any text is in front of the Title* this will create a Invalid template,
I have noticed this lots of times, but just figured it out today. Pav

**Comment by Eskyee** [comment]
<img width="1142" alt="Screenshot 2019-05-15 at 15 25 34" src="https://user-images.githubusercontent.com/30862925/57779068-b7a43c80-7725-11e9-9e13-d33c8b43fab0.png">

**Comment by dennisreimann** [comment]
I talked to @Kukks about this as I was looking for an issue to help with.

IMHO we should question whether it is a good idea to expose the underlying YAML representation.
As the js implementation for handling the data does not use a YAML parser but naive string parsing this is very fragile.
Unless I'm missing something essential I'd say it would be best to hide the textarea via JS (this way users without JS can still edit the perks). This way the YAML representation could be used as an implementation detai. Users with JS can still edit the perks via the UI and do not need the YAML.

**Comment by Kixunil** [comment]
Please do **not** remove the ability to import the data *somehow*, [we just started to rely on it](https://github.com/ParalelnaPolis/pos_articles_conversions). Funnily enough, I got it to work by finding out it's Yaml and using Yaml serializer.

Using CSV in the first place would be better, but I'm fine with Yaml.

**Comment by Kixunil** [comment]
Another question: is there any stable API to upload the template or will there be?

**Comment by Kukks** [comment]
Not yet, but I have it planned. Just need someone to sponsor my time for it since it's a big undertaking

**Comment by britttttk** [comment]
I've only seen this error for two reasons. 
1. If the text is not aligned properly
Ex1:
![image](https://user-images.githubusercontent.com/39231115/57999460-bc088680-7a92-11e9-94ad-9c05b03f0ce0.png)
2. When the item name is already in use
Ex2:
![image](https://user-images.githubusercontent.com/39231115/58000876-4f43bb00-7a97-11e9-9ce7-086fbd6c7a6e.png)
Matching titles are fine but not matching item names. They are assigned to the very first title given to the product and it remains the same even after changing the title.

**Comment by dennisreimann** [comment]
IMHO problems like the one shown above are only solvable by giving proper feedback based on the error message of a YAML parser. And even if: I don't think it's a good idea to let the user worry about this kind of stuff. This is way too technical for 95% of the users and having a text area for coding up YAML should not be the default.

**Comment by Kukks** [comment]
> IMHO problems like the one shown above are only solvable by giving proper feedback based on the error message of a YAML parser. And even if: I don't think it's a good idea to let the user worry about this kind of stuff. This is way too technical for 95% of the users and having a text area for coding up YAML should not be a default choice. (if it's reallt necessary make it optional by toggling the text area)

True dat. For js enabled browsers, we should show the gui editor only( when it replaced with a more bug-free version) and falback to the raw yml editor when noscript is needed

**Comment by mariodian** [comment]
How about a file upload which you can use to modify the hidden template textarea? It's hidden enough for basic users but still lets power users edit the data outside of the GUI.

**Comment by pavlenex** [comment]
Should've been fixed in #1544

**Comment by Kixunil** [comment]
@pavlenex could you provide a little bit more detail on what changed, please?

**Comment by pavlenex** [comment]
@Kixunil You can preview the changes by observing code change in that PR, if that's what you're asking. But Kukks refactored the code to show appropriate message so the invalid template bug should be fixed. Fell free to test. This has been added a while ago, but for some reason the issue didn't get closed by GitHub automatically.

**Comment by Kixunil** [comment]
> refactored the code to show appropriate message so the invalid template bug should be fixed

was what I wanted to know. Thanks!
