### ISSUE TITLE
On/Off switch for Tor and other important opt-in plugins

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#855]
**Is your feature request related to a problem? Please describe.**
People don't know ssh, people shouldn't know ssh. We already have plenty of option for the usage of BTCPay in the UI, but for opt-in plugins and options such as Tor, we should have an on/off switch which easily turns options on (opt-in) and then runs `. btcpay-setup.sh -i`

**Describe the solution you'd like**
Add on-off switch for:
- Tor
- Librepatron
- Transmuter
and other relevant plugins. `. btcpay-setup.sh -i` can be run immediately or after settings have been saved.

The trashcan removes the plugin entirely which should help people with [cleaning up things for unused services](https://github.com/btcpayserver/btcpayserver-doc/issues/214#issuecomment-483739105).

**Provide examples**
![Screen Shot 2019-05-09 at 12 13 27](https://user-images.githubusercontent.com/36959754/58229596-71a53500-7d32-11e9-9d6f-459c2eb2af5a.png)

Someone on Twitter suggested this as well, so I'm posting my old-idea again for further discussion. This would probably require cleaning up of the Server settings > Services page.

Thoughts?

**Comment by Eskyee** [comment]
Nice!! Noob friendly, everything that helps to simplify BTCPay for the end user is a great look @pavlenex

**Comment by Eskyee** [comment]
still a good idea!! @pavlenex

**Comment by pavlenex** [comment]
With #2006 this gets a bit too much since I'd assume plugins will take care of most external stuff in the future, closing.
