### ISSUE TITLE
Spark Server sign in

### ISSUE THREAD

**Issue by Freefromchainz** [btcpayserver/btcpayserver#856]
**Describe the problem/bug**

**Your environment**
* Version of BTCPay Server: Lastest
* Deployment method: Lunanode
* Other relevant environment details:

**Logs (if applicable)**
Basic logs can be found in Server Settings > Logs.

**To Reproduce**
1. Go to 'Spark server settings'
2. Click on 'Browser Connection'

**Expected behavior**
Connecting to the Spark server

**Actual behavior**
Tell us what happens instead 
It doesnt let me sign in even with the proper credentials 

**Screenshots/Links**
![Spark sign issue](https://user-images.githubusercontent.com/8317700/58262955-740a8d80-7d38-11e9-8aef-71f7819d6fbe.PNG)

**Additional context**
Add any other context about the problem here. I am Admin!

**Comment by NicolasDorier** [comment]
@Freefromchainz this is strange, it works on my instance.

You can try `docker restart generated_clightning_bitcoin_spark_1` and see if it changes?

**Comment by NicolasDorier** [comment]
Also, try with the browser in incognito mode, sometimes cached credentials interfere.

**Comment by Freefromchainz** [comment]
I tried incognito mode first and it worked so i had some cached credentials interference as you said!

**Comment by pavlenex** [comment]
Glad you solved it, closing this one.
