### ISSUE TITLE
Payment Request - Broken layout when text is lengthy and not broken into paragraphs

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#859]
**Describe the problem/bug**
When you create a payment request with a text that's lengthy, it breaks the layout.

**Your environment**
* Version of BTCPay Server: v1.0.3.105
* Deployment method: Docker
* Other relevant environment details: Replicated on mainnet.demo.btcpayserver.or

**To Reproduce**
1. Create a new payment request and add the following text:
```
This is a payment request demo. Payment Requests allow you to create custom invoices which can be shared with others, by sending a link to the custom payment request. A most common use-case for payment requests is invoicing buyers and getting paid in BTC or other coins on a go.
Payments made via pay request form use the exchange rate at the time of payment. To learn more about payment requests read our docs and the article on our blog.
```
2. Save
3. Preview

You can [preview my pay request here.](https://mainnet.demo.btcpayserver.org/payment-requests/71cc2883-166c-4c46-8079-e595a251b43e)

**Expected behavior**
The text should remain in the box.

**Actual behavior**
The text continues beyond the box limit.

**Screenshots/Links**
![Screen Shot 2019-05-24 at 17 49 38](https://user-images.githubusercontent.com/36959754/58340711-be7d2e80-7e4c-11e9-8c6c-737c22918d12.png)

**Comment by Kukks** [comment]
Did you copy paste it from some other editor? The linked one has some html formatting causing the issue

**Comment by pavlenex** [comment]
No I didn't. I typed in directly, the editor is so buggy sometimes.

```
<p>This is a payment request demo. <span style="white-space: pre">Payment Requests allow you to create custom invoices which can be shared with others, by sending a link to the custom payment request. A most common use-case for payment requests is invoicing buyers and getting paid in BTC or other coins on a go.<br>Payments made via pay request form use the exchange rate at the time of payment. To learn more about payment requests read our docs and the article on our blog.</span></p><p><iframe src="//www.youtube.com/embed/j6CvwDPvfzQ" class="note-video-clip" width="640" height="360"></iframe><span style="white-space: pre"><br></span></p>
```

**Comment by Kukks** [comment]
It's the `style="white-space: pre"` that causes the issue

**Comment by pavlenex** [comment]
I know, but it was typed directly into the editor, so it must have come from the broken editor, will do some more tests on this one.

**Comment by pavlenex** [comment]
You were right, it was a weird way of my browser copying the format, not an issue when copy-pasting from the text editor clipboard.
