### ISSUE TITLE
Unclear UX in Files when External Storage Services aren't set

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#874]
**Is your feature request related to a problem? Please describe.**
When someone goes to Server Settings > Files the message `no files` and the UX there is unclear, since there's no clear CTA on what to do.

![Screen Shot 2019-06-03 at 08 42 58](https://user-images.githubusercontent.com/36959754/58781305-db97c700-85db-11e9-8f11-60e34b285c48.png)

**Describe the solution you'd like**
User should be informed that they need to configure the External Storage Services (server/storage) so we should probably add a clear message with a link that will lead people to the storage configuration.

**Comment by britttttk** [comment]
@pavlenex Would you like a tooltip to the FS FAQ? https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#how-to-upload-files-to-btcpay

**Comment by britttttk** [comment]
> Add a clear message with a link that will lead people to the storage configuration.

@pavlenex tooltip and link has been added, can you give other suggestions for improvement or close request :)

**Comment by pavlenex** [comment]
I don't think the tooltip is useful in this case honestly, a redirection button with "Configure External Storage" would be far better.

**Comment by britttttk** [comment]
There is a redirect link to the user's configure external storage page. How would you like it improved?  Would you prefer this link to be replaced with a button?

**Comment by pavlenex** [comment]
It's okay @britttttk it seems it was a caching issue on my end, I think for now this is great.
