### ISSUE TITLE
Use explorer hidden service URL instead of clearnet when relevant

### ISSUE THREAD

**Issue by stevenroose** [btcpayserver/btcpayserver#878]
Self-reminder of @NicolasDorier: https://github.com/btcpayserver/btcpayserver/pull/869#issuecomment-497580440

Situations in which using the hidden service URL would be relevant:
- when the BTCPayServer is running as a hidden service as well
- when use of the Tor Browser is detected

**Comment by rockstardev** [comment]
@pavlenex @woutersamaey close this issue?

**Comment by woutersamaey** [comment]
I can't say. I'm not up to speed on this issue.
