### ISSUE TITLE
BTCPay says LND node is online but can't find it externally

### ISSUE THREAD

**Issue by j-alden** [btcpayserver/btcpayserver#882]
**Describe the problem/bug**
I have btcpayserver running, enabled the internal lightning node, successfully tested the connection, and the node shows online in btcpay. When trying to find that node using any website I don't find it. 

Trying to open a channel to btcpay node using Zap also fails. Searching for node via pubkey or alias doesn't find anything. Searching with pubkey@host lets me try opening a channel but it fails with `peer disconnected`

**Your environment**
* Version of BTCPay Server: v1.0.3.113
* Deployment method: LunaNode

**Expected behavior**
I can open a channel with my btcpayserver lnd node. 

**Actual behavior**
My btcpayserver lnd node can't be found via pubkey, pukey@host, or alias. I've tried a few ways to find it: 
- https://1ml.com/
- https://explorer.acinq.co/
- Via Zap on a separate device, separate node that already has a few channels

**Screenshots/Links**
btcpay lnd node info: 02eb9cc2c147c594bea9d41f4c00670d73d764760222b82ce4216ea9c8a2e2e9b5@172.81.177.141:9735
Alias: eyedea

Picture of `Open Public node Info Page`:
![image](https://user-images.githubusercontent.com/18519730/58953013-e462d700-875a-11e9-86d6-9faf1d8d81e1.png)

**Additional context**
I checked https://1ml.com/testnet to see if I was accidentally running testnet and couldn't find it there either. LND config has `bitcoin.mainnet=1` too

I tried restarting the server once which didn't resolve the issue.

**Comment by pavlenex** [comment]
Do you have Tor enabled? What's the URL to your server, I'm getting `Error: Unsuccessful HTTP response` from my c-lightning when trying to connect to you.


Node won't show up on explorers unless you have a channel opened.

**Comment by NicolasDorier** [comment]
@pavlenex `Error: Unsuccessful HTTP response` is probably a bug from your own node. Personally I managed to connect to you.

**Comment by NicolasDorier** [comment]
Funny thing: I actually connected to you from my mainnet node :D

**Comment by pavlenex** [comment]
@NicolasDorier you opened a channel to @j-alden?

**Comment by NicolasDorier** [comment]
I did not, but I could connect which should be enough for 1ml

**Comment by j-alden** [comment]
Thanks for the quick responses. I don't think I'm running TOR, I haven't explicitly tried to enable that. But I would have to verify later today. 

Server url: https://btcpay996878.lndyn.com/

**Comment by pavlenex** [comment]
You don't have Tor.
I can't open a channel to him, nor just connect from c-lightning.

For your node to be visible on explorers it needs to have a channel opened.

If it's a newly deployed installation, maybe give it some time or just `btcpay-down.sh` then `btcpay-up.sh` or `btcpay-restart.sh` but you said you already restarted.

In my experience LND sometimes need a few more kicks to start to operate normally. Unless there's a channel opened your node won't be visible on explorers as I said.

If the above doesn't work, you need to dig into your LND logs to see what's the problem.

[ssh into your lunanode ](https://github.com/JeffVandrewJr/patron/blob/master/SSH.md)then follow the instructions [here](https://docs.btcpayserver.org/support-and-community/troubleshooting#2-2-lightning-network-logs).

**Comment by j-alden** [comment]
@pavlenex thanks for the suggestions! I'll do some digging.

**Comment by j-alden** [comment]
Closing this. After a `btcpay-restart.sh` it seems to be working. I have a pending open channel between btcpay and my personal node. 

Thanks again for your help @NicolasDorier @pavlenex!
