### ISSUE TITLE
Magento 2 plugin

### ISSUE THREAD

**Issue by Code0Zero** [btcpayserver/btcpayserver#883]
I am frustrated that there is still any working magento 2 integration available. 
It would be great if someone could fork the bitpay magento2 plugin and port it for btcpayserver.
https://github.com/bitpay/magento2-plugin

**Comment by Kukks** [comment]
BtcPay is a community effort. Help us out and fork it. :)

**Comment by NicolasDorier** [comment]
@Code0Zero yes please do it, or pay somebody else to do. There should not be too much work to make it work, but people need to find the time to look at it.

Come on chat.btcpayserver.org you might find somebody willing to do it for you.

**Comment by Code0Zero** [comment]
@NicolasDorier  @Kukks how much time it would take to code such plugin to to modify an available plugin from bitpay? What is a fair reward to offer for that type of work?

**Comment by NicolasDorier** [comment]
On my side I am busy, but @Kukks might want to do it. Ah there is as well @woutersamaey which is a magento expert and currently hacking around btcpay, this might interest him.

**Comment by woutersamaey** [comment]
I’ve looked at the Bitpay module in the past and think it should work out of the box (if configured correctly). Don’t have it in production though, only did a quick source code review. 

Have you tried it?

**Comment by Code0Zero** [comment]
Thank you @NicolasDorier for the suggestion. @woutersamaey to avoid misunderstanding you did review the source code for the bitpay magento 2 module?

**Comment by woutersamaey** [comment]
Yes I did.

**Comment by Code0Zero** [comment]
@woutersamaey  after point the bitpay magento 2.3 extension to  redirect to https://btcpayjungle.com it seems not to work. Any suggestions what we are doing wrong?

**Comment by woutersamaey** [comment]
@Code0Zero I'm gonna need way more input before I can say anything about this...

**Comment by woutersamaey** [comment]
I'm working on a new plugin for Magento 2 that is going to be simple, easy and elegant.
Will release it as open source when ready.

By keeping this plugin simple, it should never conflict with other Magento plugins, which is often tricky.
The current plugins (like BitPay 3.0.8) have too much garbage and are not written using Magento best-practises. There are even some SQL injection issues.

**Comment by bitcoinbrisbane** [comment]
> @Code0Zero yes please do it, or pay somebody else to do. There should not be too much work to make it work, but people need to find the time to look at it.
> 
> Come on chat.btcpayserver.org you might find somebody willing to do it for you.

I wrote a Mangento / BitPOS plugin in 2014.  Ill try digout out the code.

**Comment by ion497** [comment]
I’m also interested in developing a high quality BTCPay Server extension for Magento 2. My team has implemented multiple payment integrations for Magento and this is something I’d love to help develop for the community.

@woutersamaey I’m not sure how far along you are on your implementation, but perhaps this is something we could collaborate on.

**Comment by woutersamaey** [comment]
My module is ready. Just needs a good production test case. A couple of essential tools for managing orders and recovering from errors / missed IPNs are also implemented, so should be very high quality (after final bug testing round).

**Comment by woutersamaey** [comment]
Will upload the code soon (maybe tomorrow) so you can review. Do you have a production use case?

**Comment by ion497** [comment]
@woutersamaey That's great to hear! We have a few clients that have expressed interest, but there is a lot of education that still needs to happen. I'm looking at spinning up a BTC Pay Server and an example Magento instance that we can use to educate merchants.

**Comment by woutersamaey** [comment]
This is what I have done too, but I’m not a merchant, so cannot test it “in the wild”. This is where my real interest lies, so you can definitely help me out with testing. 

The module is built and running on Magento 2.3.2, so you can setup this demo store and add the module as soon as I release it.

**Comment by jsheen1993** [comment]
> This is what I have done too, but I’m not a merchant, so cannot test it “in the wild”. This is where my real interest lies, so you can definitely help me out with testing.
> 
> The module is built and running on Magento 2.3.2, so you can setup this demo store and add the module as soon as I release it.

Came across this thread, we are just getting into accepting Bitcoin for our Magento 2 site(community) and would test it out on our demo store.

**Comment by woutersamaey** [comment]
Great! The new module is coming very soon now. Subscribe to this thread and you’ll know firsthand.

**Comment by jsheen1993** [comment]
@woutersamaey is there a way to directly contact you regarding a few questions? We have a web developer who can install/test out the module but have never used Bitcoin in any form.

**Comment by woutersamaey** [comment]
You can send me an email at wouter.samaey@storefront.be. I’ll do my best to help out any way I can.

**Comment by woutersamaey** [comment]
Just a quick update on my progress: The Magento 2 module is working fine, but uses the BitPay PHP API and not the BTCPayServer PHP API. Obviously, we don't want to keep using the BitPay PHP API and are looking into the best way to move forward. This is delaying the Magento 2 module a bit now...

**Comment by woutersamaey** [comment]
I have just released the Magento 2 module to integrate BTCPay Server at https://github.com/storefront-bvba/magento2-btcpay-module

**Comment by pavlenex** [comment]
@woutersamaey now that it's released, should we close the issue or keep it opened for visibility provided that you still require testers help?

**Comment by woutersamaey** [comment]
@pavlenex Testers can always report issues, so I think we can close this, yes.
