### ISSUE TITLE
Multiple domains for apps in BTCPay

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#887]
In #828 we added the ability for app to be on a website root. 

Next, we should allow multiple domains for apps so one btcpay instance can have apps on app 1 on domain1.com different app on app 2 on domain2.com etc.

**Comment by britttttk** [comment]
Just out of curiosity, what is the recommended way to navigate to your btcpayserver home page if you have set your app on the website root?

**Comment by Eskyee** [comment]
https://yoursitename.com/Account/Login
I use this as my starting point when a website has a app assign to its root BK

**Comment by pavlenex** [comment]
Well, when this issue is implemented it will make that experience better, as you can have your btcpay domain and then assign another to an app @britttttk

**Comment by ralyodio** [comment]
how do i work with this? i have two clients, and don't want to run two instances, but the 2nd store should have its own domain etc.

**Comment by dennisreimann** [comment]
@ralyodio You can define `BTCPAY_ADDITIONAL_HOSTS` like described here: https://docs.btcpayserver.org/Docker/#environment-variables

**Comment by ralyodio** [comment]
i'm using luna. can i define it in the ui under server settings?
