### ISSUE TITLE
Extend Payment Button to support GET link

### ISSUE THREAD

**Issue by iBobik** [btcpayserver/btcpayserver#889]
I want to send link in email in a form like: http://my.btcpay.server/api/v1/invoices?storeId=xxx&price=10&currency=USD&mail=customer@example.com

I would expect the same behavior like after click to payment button on a website, but I just want to be able to use it also in generated email where I just fill values with price and customer e-mail (so I will see who paid it).

I know I can create Payment Request but I will have to create it for every customer and I see no API how to do it easilly in docs.

**Comment by mariodian** [comment]
I get your point, but it wouldn't make sense from the REST point of view to **create** something with GET request (that's what POST is for). It would also interfere with the existing GET `/invoices` call that retrieves the list of invoices. 

We could make a new API call let's say GET `/invoices/create` but it would still be inconsistent with the rest of the REST API. 

Not sure how others feel about it?

**Comment by iBobik** [comment]
It is also inconsistent with REST to render HTML page on this request, so I thing best is to just not have it part of the REST API, or very visibly notice in docs it is not intended to be used by REST client but by human who was redirected to this URL.



Jan Pobořil
https://honza.poboril.cz/

10. 9. 2019 v 7:15, Mario Dian <notifications@github.com>:

**Comment by Kukks** [comment]
I think this makes sense. The pay button endpoint isn't quite a rest api endpoint since it just shows a view afterwards
