### ISSUE TITLE
running BTCPay Server on ports other than 80 and 443

### ISSUE THREAD

**Issue by bereska** [btcpayserver/btcpayserver#892]
**Describe the problem/bug**
after setting up btcpayserver docker on rpi 3b+ with custom ports http 8083 and https 4430 I can't access btcpay webpage. I get error 503 and btcpayserver sevice has "active (exited)" status

**Your environment**
rpi 3b+
* Version of BTCPay Server:
latest docker
* Deployment method:
docker on rpi
* Other relevant environment details:
traffic is forwaded to btcpayserver using nginx reverse proxy on another rpi
config part:
`# Redirect all http traffic to https
server {
    listen 80;
    return 301 https://$host$request_uri;
}
#SSL termination and offload for btcpay

upstream btcpayserver {
    server 192.168.2.135:8083;
}

server {
    listen 443 ssl http2;
    server_name btcpay.bereskapi-ha.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/btcpay.bereskapi-ha.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/btcpay.bereskapi-ha.duckdns.org/privkey.pem;
    ssl_protocols TLSv1.1 TLSv1.2;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://btcpayserver;
#        proxy_http_version 1.1;
#        proxy_set_header Connection "upgrade";
#        proxy_set_header Upgrade $http_upgrade;
#        proxy_set_header Host $host;
#        proxy_set_header X-Real-IP $remote_addr;
#        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
`

**Logs (if applicable)**
-------SETUP-----------
Parameters passed:
BTCPAY_PROTOCOL:https
BTCPAY_HOST:btcpay.bereskapi-ha.duckdns.org
REVERSEPROXY_HTTP_PORT:8083
REVERSEPROXY_HTTPS_PORT:4430
REVERSEPROXY_DEFAULT_HOST:none
LIBREPATRON_HOST:
WOOCOMMERCE_HOST:
BTCTRANSMUTER_HOST:
BTCPAY_HOST_SSHKEYFILE:
LETSENCRYPT_EMAIL:
NBITCOIN_NETWORK:mainnet
LIGHTNING_ALIAS:
BTCPAYGEN_CRYPTO1:btc
BTCPAYGEN_CRYPTO2:
BTCPAYGEN_CRYPTO3:
BTCPAYGEN_CRYPTO4:
BTCPAYGEN_CRYPTO5:
BTCPAYGEN_CRYPTO6:
BTCPAYGEN_CRYPTO7:
BTCPAYGEN_CRYPTO8:
BTCPAYGEN_CRYPTO9:
BTCPAYGEN_REVERSEPROXY:nginx
BTCPAYGEN_LIGHTNING:lnd
BTCPAYGEN_ADDITIONAL_FRAGMENTS:opt-save-storage-xs;opt-save-memory
BTCPAYGEN_EXCLUDE_FRAGMENTS:nginx-https
BTCPAY_IMAGE:
ACME_CA_URI:https://acme-v01.api.letsencrypt.org/directory
----------------------
Additional exported variables:
BTCPAY_DOCKER_COMPOSE=/root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml
BTCPAY_BASE_DIRECTORY=/root/BTCPayServer
BTCPAY_ENV_FILE=/root/BTCPayServer/.env
BTCPAYGEN_OLD_PREGEN=false
BTCPAY_SSHKEYFILE=
BTCPAY_SSHTRUSTEDFINGERPRINTS:
BTCPAY_CRYPTOS:btc
BTCPAY_ANNOUNCEABLE_HOST:btcpay.bereskapi-ha.duckdns.org
----------------------

BTCPay Server environment variables successfully saved in /etc/profile.d/btcpay-env.sh

BTCPay Server docker-compose parameters saved in /root/BTCPayServer/.env

Using default tag: latest
latest: Pulling from btcpayserver/docker-compose-generator
fac132c5d16f: Pull complete 
70db87399586: Pull complete 
e027ade004a6: Pull complete 
2e1cf48644bb: Pull complete 
3af75769c023: Pull complete 
6e041858ef5e: Pull complete 
7bc274dbb2fb: Pull complete 
Digest: sha256:59945a6a60d2651a7684a31a6331484b3e13dbaf30ac9c09b62359cea889f2e9
Status: Downloaded newer image for btcpayserver/docker-compose-generator:latest
Crypto: btc
Lightning: lnd
ReverseProxy: nginx
Generating /app/Generated/docker-compose.generated.yml
With fragments:
	nginx
	btcpayserver-nginx
	btcpayserver
	opt-add-tor
	nbxplorer
	postgres
	bitcoin
	bitcoin-lnd
	opt-save-storage-xs
	opt-save-memory
Generated /app/Generated/docker-compose.generated.yml

Adding btcpayserver.service to systemd
Setting limited log files in /etc/docker/daemon.json
BTCPay Server systemd configured in /etc/systemd/system/btcpayserver.service

Created symlink /etc/systemd/system/multi-user.target.wants/btcpayserver.service → /etc/systemd/system/btcpayserver.service.
BTCPay Server starting... this can take 5 to 10 minutes...
BTCPay Server started
generated_nbxplorer_1 is up-to-date
generated_lnd_bitcoin_rtl_1 is up-to-date
tor is up-to-date
generated_postgres_1 is up-to-date
btcpayserver_bitcoind is up-to-date
btcpayserver_lnd_bitcoin is up-to-date
tor-gen is up-to-date
generated_btcpayserver_1 is up-to-date
nginx is up-to-date
nginx-gen is up-to-date
Installed bitcoin-cli.sh to /usr/local/bin: Command line for your Bitcoin instance
Installed bitcoin-lncli.sh to /usr/local/bin: Command line for your Bitcoin LND instance
Installed btcpay-clean.sh to /usr/local/bin: Command line for deleting old unused docker images
Installed btcpay-down.sh to /usr/local/bin: Command line for stopping all services related to BTCPay Server
Installed btcpay-restart.sh to /usr/local/bin: Command line for restarting all services related to BTCPay Server
Installed btcpay-setup.sh to /usr/local/bin: Command line for restarting all services related to BTCPay Server
Installed btcpay-up.sh to /usr/local/bin: Command line for starting all services related to BTCPay Server
Installed btcpay-update.sh to /usr/local/bin: Command line for updating your BTCPay Server to the latest commit of this repository
Installed changedomain.sh to /usr/local/bin: Command line for changing the external domain of your BTCPay Server
pi@bereskapi:~ $ sudo systemctl status btcpayserver
● btcpayserver.service - BTCPayServer service
   Loaded: loaded (/etc/systemd/system/btcpayserver.service; enabled; vendor preset: enabled)
   Active: active (exited) since Mon 2019-06-24 00:25:57 MSK; 32min ago
  Process: 10493 ExecStop=/bin/bash -c . /etc/profile.d/btcpay-env.sh && cd "$BTCPAY_BASE_DIRECTORY/btc
  Process: 11341 ExecStart=/bin/bash -c . /etc/profile.d/btcpay-env.sh && cd "$BTCPAY_BASE_DIRECTORY/bt
 Main PID: 11341 (code=exited, status=0/SUCCESS)
   Memory: 0B
      CPU: 0
   CGroup: /system.slice/btcpayserver.service

Jun 24 00:25:21 bereskapi bash[11341]: Creating generated_postgres_1  ...
Jun 24 00:25:21 bereskapi bash[11341]: Creating generated_lnd_bitcoin_rtl_1 ...
Jun 24 00:25:29 bereskapi bash[11341]: [158B blob data]
Jun 24 00:25:29 bereskapi bash[11341]: Creating tor-gen                     ...
Jun 24 00:25:36 bereskapi bash[11341]: [276B blob data]
Jun 24 00:25:45 bereskapi bash[11341]: [99B blob data]
Jun 24 00:25:45 bereskapi bash[11341]: Creating nginx                       ...
Jun 24 00:25:50 bereskapi bash[11341]: [158B blob data]
Jun 24 00:25:57 bereskapi bash[11341]: [59B blob data]
Jun 24 00:25:57 bereskapi systemd[1]: Started BTCPayServer service.
**To Reproduce**

**Expected behavior**

**Actual behavior**
Tell us what happens instead

**Screenshots/Links**
If applicable, add screenshots or links to help explain your problem.

**Additional context**

**Comment by pavlenex** [comment]
Duplicate. [Check this out.](https://github.com/btcpayserver/btcpayserver-docker/issues/141)

**Comment by bereska** [comment]
@pavlenex, thank you. Sorry for wasting your time on such a small issue. 
My situation is similar but not quite the same. 
Rpi1 runs a bunch of containers under docker-compose including one container (organizr) with built-in nginx as a web gateway for ports 80 and 443 forwarded in the router to rpi1. 
Rpi2 runs exclusively BTCPay Server docker container with manually configured http and https ports different from 80 and 443.
After playing with nginx settings on rpi1 last night I think I got it working properly. Nodes are syncing slowly bu surely and web ui is available on https://btcpay.bereskapi-ha.duckdns.org/. Here is my nginx configuration on rpi1 for btcpayserver:

`# Redirect all http traffic to https
server {
    listen 80;
    return 301 https://$host$request_uri;
}
#SSL termination and offload for btcpay

upstream btcpayserver {
    server 192.168.2.135:8083;
    server 192.168.2.135:4430;
}

server {
    listen 443 ssl http2;
    server_name btcpay.bereskapi-ha.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/btcpay.bereskapi-ha.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/btcpay.bereskapi-ha.duckdns.org/privkey.pem;
    ssl_protocols TLSv1.1 TLSv1.2;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:$
    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://btcpayserver;
        proxy_http_version 1.1;
        proxy_set_header Connection "upgrade";
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}`

I hope this might be useful for others trying to archive the same

**Comment by bereska** [comment]
@pavlenex, i have just noticed that the bitcoin blockchain is being synced to the /dev/root on the SD card of my rpi instead of the mounted to /mnt/usb SanDisk flash drive! I am 18% and two days down the road syncing. I did run this command when setting it up `sudo ln -s /mnt/usb/docker /var/lib/docker`. Is there a way to solve this without syncing from the very start? Thank you

**Comment by pavlenex** [comment]
I have no rpi experience, but maybe @enorrmann or @NicolasDorier can help you with this.

**Comment by bereska** [comment]
@pavlenex, I am confused( does it look right or not?:

root@bereskapi:~# df -hT
Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/root      ext4       59G   31G   26G  54% /
devtmpfs       devtmpfs  433M     0  433M   0% /dev
tmpfs          tmpfs     438M   20K  438M   1% /dev/shm
tmpfs          tmpfs     438M   34M  404M   8% /run
tmpfs          tmpfs     5.0M  4.0K  5.0M   1% /run/lock
tmpfs          tmpfs     438M     0  438M   0% /sys/fs/cgroup
/dev/mmcblk0p1 vfat       43M   23M   21M  53% /boot
tmpfs          tmpfs      88M     0   88M   0% /run/user/33
tmpfs          tmpfs      88M     0   88M   0% /run/user/1000
/dev/sdc1      fuseblk   233G  149G   85G  64% /media/nas
/dev/sdd1      ext4       57G  2.1G   52G   4% /mnt/usb
overlay        overlay    59G   31G   26G  54% /var/lib/docker/overlay2/db75c935c78b010f982e79f4c7b7588e3a194148380e090d8401c2be51111581/merged
overlay        overlay    59G   31G   26G  54% /var/lib/docker/overlay2/dae0b7f9aeb4875889f9bf64d533d316bfba81163ef37457fbe0592c732af626/merged
shm            tmpfs      64M     0   64M   0% /var/lib/docker/containers/4c4be415b255a3e9598d9aca877bd33197b4a2fea30295c95582df3be2753656/mounts/shm
overlay        overlay    59G   31G   26G  54% /var/lib/docker/overlay2/946dd3bac8196f9ec1ce751ae089f51f179667a2cc83adb4893ccce093ae2eaf/merged
shm            tmpfs      64M     0   64M   0% /var/lib/docker/containers/e3bf7495b33b76a692620991f9666e01a278414e98511f82c9b6e3423ec689ab/mounts/shm
overlay        overlay    59G   31G   26G  54% /var/lib/docker/overlay2/a65eeca0d2a9faba26b5c24737ae308f55cab5560cd3cfbf9cb88b4c2ba25878/merged
shm            tmpfs      64M     0   64M   0% /var/lib/docker/containers/63307f707b13417b5d3219f85b57472115d0e3e447315ecaef6fb6bfccfb9118/mounts/shm
shm            tmpfs      64M  4.0K   64M   1% /var/lib/docker/containers/3dcf242f8b0d12fe38a06ca7ed4bfccba36b4f0129154e96fa3990eea771f6a4/mounts/shm
overlay        overlay    59G   31G   26G  54% /var/lib/docker/overlay2/bdd02b2bc4a9ed34724d2eb1070e8b2cb113e3534cf1769c3ac256f3b127ebd6/merged
overlay        overlay    59G   31G   26G  54% /var/lib/docker/overlay2/ee796306379ef980516bc6b7af1fab35f93f878e7af91ed86b1e208f3f7b7958/merged
shm            tmpfs      64M     0   64M   0% /var/lib/docker/containers/e52a8c3408f2c7d770a89b03de21504bc1b996b080c8efcbea90b68cc28e1b38/mounts/shm
shm            tmpfs      64M     0   64M   0% /var/lib/docker/containers/0f1c03b7f9af585aaaa471e2e4ba2cb0d0d627a541d35dedf238e0e03cf9728d/mounts/shm
overlay        overlay    59G   31G   26G  54% /var/lib/docker/overlay2/202f9badb2600e43c19b5e8ea906e2f68d6e05caeca91b2112db630eb335bfee/merged
shm            tmpfs      64M     0   64M   0% /var/lib/docker/containers/d54e0fd9331e45d70f646d17182f5d0c681168afa5a28b776b85b7aa0f0427fe/mounts/shm
overlay        overlay    59G   31G   26G  54% /var/lib/docker/overlay2/6b76cfd44b20f7bd564633c2dc0a81c7af31f499dc0b2d01f9d64e23787e92ce/merged
overlay        overlay    59G   31G   26G  54% /var/lib/docker/overlay2/4f1e115c5c81798ba5063c40d94d1136d8067ceabf1f38cd4a00b564bf4d719f/merged
shm            tmpfs      64M     0   64M   0% /var/lib/docker/containers/51befc776f79317d65d8184dd3df451648a6ea9bd45de6f43bb15b45db626d5a/mounts/shm
shm            tmpfs      64M     0   64M   0% /var/lib/docker/containers/1ce1f6dd8a56b8e5122d7018837f946caac9a74457b74ccb2578a7c3a2ea36de/mounts/shm
overlay        overlay    59G   31G   26G  54% /var/lib/docker/overlay2/6a2ed53765fdbd02168239b1894c9cc2fac09f881d145b36d2856836277cb9b9/merged
shm            tmpfs      64M     0   64M   0% /var/lib/docker/containers/8465bc1ff0c51fdceb6508191fcb47de4c51d821daaabc24e203e0c8a907acc8/mounts/shm

**Comment by pavlenex** [comment]
As I said I have no experience in RPI and BTCPay, but we do have[ extensive documentation for RPI ](https://docs.btcpayserver.org/deployment/raspberrypideployment)available here that might help you.

**Comment by NicolasDorier** [comment]
You need to look that you properly configure your nginx to not override HOST and forward websockets properly (https://docs.btcpayserver.org/faq-and-common-issues/faq-deployment#btcpay-is-expecting-you-to-access-this-website-from)

**Comment by bereska** [comment]
@NicolasDorier, than you. I think I configured the nginx right since the site is working just fine https://btcpay.bereska-lnd.duckdns.org. My concern is that the blockchain appears to be syncing to the SD card instead of the external USB mounted on mnt/usb. Please see the df -h output above.

**Comment by bereska** [comment]
oops, sorry that was my other btcpay server also running great). The new btcpay server site in question is https://btcpay.bereskapi-ha.duckdns.org. Thank you for your help

**Comment by NicolasDorier** [comment]
I can't help you for this, I am not myself super familiar with linux, all I know is 
https://docs.btcpayserver.org/deployment/raspberrypideployment

**Comment by bereska** [comment]
@NicolasDorier, it's ok) please keep up your great coding work on btcpay server and other apps!
I'll keep on experimenting with the btcpay server on arm devices since it's the cheapeast, most distributed and non-custodial way of growing bitcoin and lightning networks.
By the way, upgrading to lnd v0.7.0-beta-rc2 and btcpay server v1.0.3.118 on my rpi's did bring the memory and CPU usage down and improve overall web-front user experience a lot. So if rpi 3 with just 1 gb ram can pull it off, the new rpi 4 with 2-4 gb ram will rock)

**Comment by bereska** [comment]
@NicolasDorier, just looked at `/var/lib/docker/volumes/generated_bitcoin_datadir/_data/bitcoin.conf`
should i add `datadir=/mnt/usb/docker` to force it sync to the usb?
sorry, not very much familiar with docker inner workings

**Comment by NicolasDorier** [comment]
> By the way, upgrading to lnd v0.7.0-beta-rc2 and btcpay server v1.0.3.118 on my rpi's

How do you use 0.7.0-rc2? you made your own docker image? If yes, can you share?

I keep away from rc versions from LND. LND not being that stable, I don't want to try on rc versions.

**Comment by bereska** [comment]
I wish) just learning docker. 
Bitcoin, lnd, .NET, nbxplorer, btcpayserver, all were manually installed on my rpi 3b+
Can't wait to try watch tower and loop

**Comment by NicolasDorier** [comment]
docker is way easier to learn than managing to build all the stuff by yourself on a PI!
