### ISSUE TITLE
Download doesn't work with FileSystem storage

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#894]
**Describe the problem/bug**
Download checkbox IsDownload doesn't download for temp links when used with FileStorage

**Your environment**
* Version of BTCPay Server: v1.0.3.11
* Deployment method: LunaNode
* Other relevant environment details: Temp link time works great.

**To Reproduce**
1. Enable FileSystem storage
2. Upload file to FS
3. Create temp link
4. Select IsDownload & link expiration time 

**Expected behavior**
Temp link should download file when temp link is clicked. 

**Actual behavior**
No download occurs

**Additional context**
I will update the [FS FAQ](https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#how-to-upload-files-to-btcpay) by removing the comment that temp links don't work with FileSystem storage provider, but i'm wondering if it should be changed to say FileSystem doesn't work with downloads or if this is a bug.

**Comment by Kukks** [comment]
I feel like I fixed this a while ago, let me check it out
