### ISSUE TITLE
FileSystem - Need to click "Choose" when selecting provider

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#895]
**Describe the problem/bug**
When the user selects a storage provider and clicks next, there's no reason why they have to click the "Choose" button for the system to select that option.

**To Reproduce**
1. Go to server/storage/FileSystem
2. Click on Change Storage provider
3 Select the provider from the drop-down
4. Click next

At this point, nothing happens unless you click "Choose" the changes won't be saved, which makes no sense from the user perspective.

**Expected behavior**
Provider should be chosen when I click next

**Actual behavior**
I need to click "Choose" which is unclear UX.

**Screenshots/Links**
![2019-06-24_17-37-09](https://user-images.githubusercontent.com/36959754/60032772-8c5b2880-96a7-11e9-9658-a786f60298c3.gif)

**Comment by britttttk** [comment]
Why not simply change the button of "Choose" to "Save"?

**Comment by pavlenex** [comment]
Because that step is completely unnecessary, it should be auto-saved.

**Comment by pavlenex** [comment]
@Kukks You can rename the Next button to Save it would make more sense I think.

**Comment by Kukks** [comment]
Nah, I got rid of the button in general and it saves automatically after it is selected now.

**Comment by pavlenex** [comment]
Ok, great.
