### ISSUE TITLE
Crowdfunding as a backend/API

### ISSUE THREAD

**Issue by whiteyhat** [btcpayserver/btcpayserver#896]
Is it possible to reuse the backend already provided by my BTCPay Server instance as an API to generate native crowdfunding campaigns in my web application without having to depend on `iframe`?

**Comment by pavlenex** [comment]
Only when the new API is released, but there's no ETA for that yet.

**Comment by whiteyhat** [comment]
> Only when the new API is released, but there's no ETA for that yet.

Okay! Can you send me the file of the BTCPaye Server where this backend is?

**Comment by Kukks** [comment]
There is no api "backend" file currently available.
ᐧ
