### ISSUE TITLE
Allow bulk upload of images

### ISSUE THREAD

**Issue by thecrypt0hunter** [btcpayserver/btcpayserver#899]
**Is your feature request related to a problem? No.

> Currently uploading an image to BTCPayServer can only be done one at a time 

**Describe the solution you'd like** 

> It would save a bit of time if I could upload multiple images in one go. 

**Describe alternatives you've considered**

>The current way is just fine, until you have a bunch of files to upload.

**Comment by woutersamaey** [comment]
Where are you uploading these images? Is this for the POS app?
I’d suggest implementing plupload which is a very nice tool for multiple uploads at the same time, has drag and drop, progress bar, etc...

**Comment by pavlenex** [comment]
@woutersamaey No, he's referring to the Server Settings > Files. Eventually, that sort of uploading should be added to apps.

**Comment by cypherbeerus** [comment]
Hi! I'm looking into this issue. Can you clarify why would someone upload files to the server in the first place?

**Comment by rockstardev** [comment]
@cypherbeerus so you could reference them in various scenarios... from POS app for example (https://www.youtube.com/watch?v=Mz4uajz0z9Y).

Or you just want to upload files to reference them externally, outside of BTCPayServer.

**Comment by cypherbeerus** [comment]
Earlier, when a file was uploaded, a confirmation card, a card containing links for this SelectedFileId was rendered.
I've changed it such that when multiple files(>1) are uploaded, files are added but there isn't any confirmation. 
Any thoughts on if/how we can provide confirmation that files were uploaded.

**Comment by rockstardev** [comment]
@cypherbeerus for any additional work I would provide a new issue and link this one. Maybe coordinate with our UX experts @dstrukt & @dennisreimann.

Great job on getting 1st PR merged!

**Comment by rockstardev** [comment]
OK, I see the work is already happening on: https://github.com/btcpayserver/btcpayserver/issues/2707 ... game on!
