### ISSUE TITLE
Export Invoices in CSV/JSON/XML

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#9]
Add "Export" to invoices screen. 

This will help shop owners gather raw data from their shop. 

Export should include all fields from the "Invoice details" screens for all invoices exported. 

If invoice screen has filters, then export should only export filtered types:
[Sorting on "Invoices" Screen](https://github.com/btcpayserver/btcpayserver/issues/8)

**Comment by astupidmoose** [comment]
Often the ecommerce site does not actually have any BTC information, especially that which is generated on the BTCPay side. 

Merchants might want to for example export all paid orders with their Wallet ID's, BTC amounts and transaction ID's. If this information is not passed to the ecommerce site (plugins do not) then there is no way to extract this information in mass.

**Comment by NicolasDorier** [comment]
Good point, I agree.

**Comment by rockstardev** [comment]
ETA: 9/28

**Comment by Kukks** [comment]
can you make sure to include a query param to what format to export to? SO that we can support everything later on:)

**Comment by rockstardev** [comment]
Finally closed this: #425

And @Kukks yeah, there is param... CSV and JSON export for the start

**Comment by NicolasDorier** [comment]
Feeling sad to close this, the 9th PR of the project :'(
