### ISSUE TITLE
how to find notificationUrl for invoice

### ISSUE THREAD

**Issue by cryptofuture** [btcpayserver/btcpayserver#900]
Basically it more a question. How and where exactly notificationUrl for invoices stored? As I checked all postgres tables, but still couldn't find it. And in the ui it rendered from `model.ServerIpn` as `vm.NotificationUrl` if I understand right
invoices api doesn't provides notificationUrl, so the only place I'm able to see it is in in the ui, with actual login. But what I really want is to get notificationUrl value for certain invoice api-alike style

P.S.: I asked on tg and in mattermost without any result. So, I had no option, but to ask there

**Comment by NicolasDorier** [comment]
@cryptofuture It is stored in the Invoices table inside a blob.
