### ISSUE TITLE
channel.backup file not found error when using zap wallet

### ISSUE THREAD

**Issue by hakonamatata** [btcpayserver/btcpayserver#903]
Hi, great work on BTCPay server. Love the project. 

I have been using zap wallet with BTCPay for a while. Have BTC and Lightning using LND set up, but with the latest update I get this error when I try to connect with my zap wallet. 

**channel.backup file not found**

![IMG_2394](https://user-images.githubusercontent.com/4003969/60426143-57455d80-9bf4-11e9-8f11-1114d3ef38ed.PNG)

How can I create channel.backup and how can I receive the file?

As a feature request it would be nice if channel backups are done on a regular basis. The .json files containing the backups could be listed on the BTCPay server site for easy download.

**Comment by NicolasDorier** [comment]
Hey, can you post on Zap wallet repository? BTCpay Server does not support channel backups because we don't give the seed to the user.

**Comment by NicolasDorier** [comment]
I checked, actually even without the seed the backup file should be created. I don't know what zap is doing, you must ping them on their repo.

**Comment by hakonamatata** [comment]
posted the issue at https://github.com/LN-Zap

[channel.backup file not found when using BTCPay server #181](https://github.com/LN-Zap/zap-iOS/issues/181)

**Comment by NicolasDorier** [comment]
@hakonamatata can you update btcpay and try again? Tried Zap wallet and it works.

**Comment by pavlenex** [comment]
I can confirm that it works, @hakonamatata if you keep having issues with this after updating your btcpay and zap, let us know and we'll re-open and try to troubleshoot further.
