### ISSUE TITLE
Your nodes are synching... LTC and DASH

### ISSUE THREAD

**Issue by darkban** [btcpayserver/btcpayserver#904]
it happened again this time it happened with ltc ... initially after a dash update it did not synchronize anymore now after the last update happened also with ltc now the ltc node does not work, I reported already 3 months ago or maybe again plus the problem with dash but it has never been solved now the same problem has occurred with ltc ... how can I solve? the only thing I did was update the server

**Comment by andres-pinilla** [comment]
+1 with Dash

**Comment by andres-pinilla** [comment]
Stuck here several days after update: <img width="503" alt="Captura de Pantalla 2019-07-03 a la(s) 12 02 50 p  m" src="https://user-images.githubusercontent.com/29980213/60611145-3a8f5e00-9d8b-11e9-873a-1cdb6dc065ec.png">

**Comment by NicolasDorier** [comment]
Did a `btcpay-restart.sh` solve the situation? I noticed this happen only with altcoins.

**Comment by andres-pinilla** [comment]
Hello, I deleted the data folder and rebuilt the index.

Thanks.

**Comment by guiguy2018** [comment]
> Hello, I deleted the data folder and rebuilt the index.
> 
> Thanks.

Could you tell me exactly which folder you deleted please?  Thanks.

**Comment by andres-pinilla** [comment]
Delete all files within this directory:
/var/lib/docker/volumes/generated_dash_datadir/_data

```
sudo su -
. ./btcpay-setup.sh -i
```

**Comment by guiguy2018** [comment]
> Delete all files within this directory:
> /var/lib/docker/volumes/generated_dash_datadir/_data
> 
> Then run this command again and voila:
> 
> ```
> sudo su -
> . ./btcpay-setup.sh -i
> ```

ok thanks very much

**Comment by andres-pinilla** [comment]
Hi @guiguy2018, works for you?

**Comment by guiguy2018** [comment]
> Hi @guiguy2018, works for you?

nope.  working with ltc by the way.  Deleted the folder and it still stuck at 99%, ltc sync but nbxplorer stuck.  Tried it again and now getting errors when I do . ./btcpay-setup.sh -i

Starting btcpayserver_litecoind ... error

ERROR: for btcpayserver_litecoind  Cannot start service litecoind: network a0c41Recreating 7c15a0a9489e_7c15a0a9489e_7c15a0a9489e_7c15a0a9489e_generated_nbxplorer_1 ... error
ERROR: for 7c15a0a9489e_7c15a0a9489e_7c15a0a9489e_7c15a0a9489e_generated_nbxplorer_1  Cannot start service nbxplorer: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/docker/volumes/generated_litecoin_datadir/_data\\\" to rootfs \\\"/var/lib/docker/overlay2/1c284f4b6c3833a04b93b4f7061f4e4ec668befcfec6db577ab82c9b34cb4139/merged\\\" at \\\"/root/.litecoin\\\" caused \\\"stat /var/lib/docker/volumes/generated_litecoin_datadir/_data: no such file or directory\\\"\"": unknown

**Comment by NicolasDorier** [comment]
`mkdir -p /var/lib/docker/volumes/generated_litecoin_datadir/_data`

**Comment by Neolo** [comment]
Same problem with sync 1.6.3.0
![Screen Shot 2022-07-27 at 7 26 53 AM](https://user-images.githubusercontent.com/2836790/181310992-211c2e67-6683-48e5-b744-a3e9e3e88d52.png)

**Comment by NicolasDorier** [comment]
@Neolo you tried recently? I updated DOGE a few days ago. Did you try to run btcpay-update.sh ?

**Comment by Neolo** [comment]
> @Neolo you tried recently? I updated DOGE a few days ago. Did you try to run btcpay-update.sh ?

Yes, it’s latest version already. It’s flapping, shows 35% (stuck at it) and after page refresh shows starting node again. LTC stuck at block as on screenshot and not moving. 
Space and ram are sufficient. Reboot didn’t help? more over reboot broke ltc.

**Comment by NicolasDorier** [comment]
yes I believe that's a RAM issue. DOGE is very greedy in RAM. Checking now.

**Comment by NicolasDorier** [comment]
you can check `dmesg -T | egrep -i 'killed process'` if the processes get killed by RAM issue.

**Comment by NicolasDorier** [comment]
@darkban for LTC can you tyr to run `litecoin-cli.sh getblockchaininfo` ?

**Comment by Neolo** [comment]
> you can check `dmesg -T | egrep -i 'killed process'` if the processes get killed by RAM issue.

No output, there is 8GB of ram, plenty and half of it free, I watch over htop.



> for LTC can you tyr to run `litecoin-cli.sh getblockchaininfo` ?

litecoin-cli.sh getblockchaininfo
{
  "chain": "main",
  "blocks": 2304093,
  "headers": 2304093,
  "bestblockhash": "6c423f7481a59670e9f067e91b2225ee6649307ba85229db159f905e6bb9bcf9",
  "difficulty": 14020592.33052793,
  "mediantime": 1658785905,
  "verificationprogress": 0.9982360053107212,
  "initialblockdownload": true,
  "chainwork": "000000000000000000000000000000000000000000000897ad2b5fde0eac0764",
  "size_on_disk": 26001220633,
  "pruned": true,
  "pruneheight": 2138979,
  "automatic_pruning": true,
  "prune_target_size": 26214400000,
  "softforks": {
    "bip34": {
      "type": "buried",
      "active": true,
      "height": 710000
    },
    "bip66": {
      "type": "buried",
      "active": true,
      "height": 811879
    },
    "bip65": {
      "type": "buried",
      "active": true,
      "height": 918684
    },
    "csv": {
      "type": "buried",
      "active": true,
      "height": 1201536
    },
    "segwit": {
      "type": "buried",
      "active": true,
      "height": 1201536
    },
    "taproot": {
      "type": "bip8",
      "bip8": {
        "status": "active",
        "start_height": 2161152,
        "timeout_height": 2370816,
        "since": 2257920
      },
      "height": 2257920,
      "active": true
    },
    "mweb": {
      "type": "bip8",
      "bip8": {
        "status": "active",
        "start_height": 2217600,
        "timeout_height": 2427264,
        "since": 2265984
      },
      "height": 2265984,
      "active": true
    }
  },
  "warnings": ""
}

**Comment by NicolasDorier** [comment]
@Neolo it seems that `"initialblockdownload": true,` is stuck on LTC, I don't know why, probably a bug from the litecoin node.

Try `docker restart btcpayserver_litecoind`

**Comment by Neolo** [comment]
> Try `docker restart btcpayserver_litecoind`

I did that already, and rebooted the whole server 4 times, no changes

**Comment by NicolasDorier** [comment]
@Neolo I will try to check if there is an outstanding bug in litecoin and if yes, find a workaround

**Comment by NicolasDorier** [comment]
@Neolo is it a new instance or did you upgraded? if upgrade, https://github.com/litecoin-project/litecoin/issues/829 seems to say it needs to rescan. Is it upgraded or just new instance?

**Comment by Neolo** [comment]
New instance but because it's syncing like that for weeks, version was upgraded several times.

**Comment by NicolasDorier** [comment]
@Neolo that's a good question it says the block `163f5d4af9e77e7250c9448d17c44726fca346b6aa404108fba9f42203d45dd2 ` is invalid.

But it isn't https://litecoinblockexplorer.net/block/163f5d4af9e77e7250c9448d17c44726fca346b6aa404108fba9f42203d45dd2
so my guess is that your node is stuck for some reason, which may be a bug of litecoin or a corruption of the UTXO set, which a rescan would solve. 

I advise you to ask for advise on https://github.com/litecoin-project/litecoin/ and link the discussion here.

**Comment by Neolo** [comment]
> @Neolo that's a good question your logs says the block `163f5d4af9e77e7250c9448d17c44726fca346b6aa404108fba9f42203d45dd2 ` is invalid.
> 
> But it isn't https://litecoinblockexplorer.net/block/163f5d4af9e77e7250c9448d17c44726fca346b6aa404108fba9f42203d45dd2 so my guess is that your node is stuck for some reason, which may be a bug of litecoin or a corruption of the UTXO set, which a rescan would solve.
> 
> I advise you to ask for advise on https://github.com/litecoin-project/litecoin/ and link the discussion here. I am starting a new node to see how it goes.

ok I will rescan it. What about doge?

**Comment by NicolasDorier** [comment]
@Neolo I think DOGE is fine, the UI flicker probably because the CPU is busy synching. If the container is still synching and you sometimes see the progress then it is fine.

**Comment by Neolo** [comment]
> @Neolo I think DOGE is fine, the UI flicker probably because the CPU is busy synching. If the container is still synching and you sometimes see the progress then it is fine.

CPU is barely 45% loaded and it's been weeks, I don't understand why so slow.

**Comment by NicolasDorier** [comment]
@Neolo which VPS are you using? some VPS throttle CPU if you use it too much for too long.

**Comment by Neolo** [comment]
> @Neolo which VPS are you using? some VPS throttle CPU if you use it too much for too long.
> 
> Weeks to sync DOGE doesn't seem normal indeed.
> 
> My node already synched LTC, now DGE 88% and BTC 40% (using lunanode)

I own that VPS, I set 16 cores with no limit, it does not use them all.

**Comment by NicolasDorier** [comment]
@Neolo you use SSD? right now I have been using an M4 instance on https://www.lunanode.com/pricing and it seems to be synching nicely.

Maybe your RAM is swapping?

**Comment by Neolo** [comment]
> @Neolo you use SSD? right now I have been using an M4 instance on https://www.lunanode.com/pricing and it seems to be synching nicely.
> 
> Maybe your RAM is swapping?

No, regular 7200 RPM
Again, BTC synced just fine. Are these Alt coins even have pruning?

**Comment by Kukks** [comment]
They have pruning, but altcoins are not known to prioritize stability :)

**Comment by NicolasDorier** [comment]
@Neolo I just finished synching DOGE now. I believe you have some hardware issue. I can't really tell you where.

**Comment by NicolasDorier** [comment]
I will push a new version of NBXplorer so you don't have this flicker anymore

**Comment by Neolo** [comment]
> @Neolo I just finished synching DOGE now. I believe you have some hardware issue. I can't really tell you where.

Hardware problems but BTC synced in a day?

**Comment by NicolasDorier** [comment]
I have no idea then, DOGE consume more RAM so if you are swapping that may be the problem.
What I can say is that I started a node with BTC,LTC and DOGE and it successfully synched.

**Comment by Neolo** [comment]
> I have no idea then, DOGE consume more RAM so if you are swapping that may be the problem.
> What I can say is that I started a node with BTC,LTC and DOGE and it successfully synched.

I removed swap, nothing changed 50% of ram still unused and cpu 15% loaded, i/o 315-500 kbps

**Comment by davidpung8** [comment]
🎤Author.Cordial greetings from Pung  
I am a financial consultant and a wealth manager. I will Airdrop 0.0000001  to the community. To Participate, Transfer 0.00000003 BTC - 0.00000005 BTC and you will Get 0.00000007 BTC - 0.00000009 BTC back. and we will remove the Update when the 0.000000011 BTC  is reached.

BTC ADDRESS:

 bc1qcv874ny25h4aevfhekj3sl9rt5vaez9n3khtx6

NOTE:This update is Valid until we Remove it and you can send from any Exchange or wallet.

Best RegardsMR.PUNGI

**Comment by NicolasDorier** [comment]
@Neolo I don't know then :( my only guess would be to use SSD instead, but it doesn't make sense BTC synched right but not the rest.

**Comment by Neolo** [comment]
> @Neolo I don't know then :( my only guess would be to use SSD instead, but it doesn't make sense BTC synched right but not the rest.

LTC synchronized in one day after I removed it's data folder described earlier. DOGE is moving like 1% per day, now at 38%. CPU and HDD are barely loaded.

**Comment by NicolasDorier** [comment]
![image](https://user-images.githubusercontent.com/3020646/182635338-139e6b59-0eee-4ee3-bdfc-3e009892c7f1.png)

**Comment by Pingblue** [comment]
I had the same issue with Litecoin sync stuck at 99%, this is what resolved it for me.

```
rm -rf /var/lib/docker/volumes/generated_litecoin_datadir/_data/*
docker rm -f btcpayserver_litecoind
cd btcpayserver-docker
. ./btcpay-setup.sh -i
```

**Comment by labrocca** [comment]
Having same issue after I updated BTCpay server from 1.6.4 to 1.6.7 the server restarted and the LTC sync is stuck at the same blockheight. This is why updating is bad. :(

Running on Lunanode (plenty of resources) with DOGE, XMR, BTC, and LTC. Only LTC is stuck.  

Looks like I will have to delete the datadir and resync from block 1.  For me to experience the exact same issue I think there must be a bug somewhere.

**Comment by Kukks** [comment]
The bug can only be in litecoin's node software. Altcoins have been historically way more unstable. AFAIK the ltc node deployed is on the latest version.

**Comment by labrocca** [comment]
It was an update to the latest version that triggered the issue.  You seem defensive.  

Personally I have experienced a couple issues with syncing but imho they are more related to Lunanode hardware.  During setup of this server the BTC syncing also got stuck and I had to delete the data dir and start over.  Because the other person making the same bug report said he was on Lunanode as well. 

Please note took less than 12 hours for my LTC node to fully  resync from scratch.  So that's pretty good.

**Comment by Neolo** [comment]
Watch this, took 2 weeks and DOGE stuck at 99%.
It's purely BTCServer's issue, because it happens with every single altcoin
![Screen Shot 2022-08-24 at 8 13 00 AM](https://user-images.githubusercontent.com/2836790/186492706-26d86669-cd7d-4108-b97b-c1b2ade85f64.png)
.

**Comment by labrocca** [comment]
> Watch this, took 2 weeks and DOGE stuck at 99% and not moving. It's purely BTCServer's issue, because it happens with every single altcoin ![Screen Shot 2022-08-24 at 8 13 00 AM](https://user-images.githubusercontent.com/2836790/186492706-26d86669-cd7d-4108-b97b-c1b2ade85f64.png) .

Curious if you are also Lunanode?

**Comment by Delitants** [comment]
> Lunanode

No, I don't have that
