### ISSUE TITLE
Configure Email Settings warning link not working

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver#906]
**Describe the problem/bug**

Click on the configure store email settings link in Update Crowdfund page, it takes you to login screen.

**Your environment**
* Version of BTCPay Server:  v1.0.3.118
* Deployment method: LunaNode

**To Reproduce**
1. Go to an App (crowdfund or PoS) > Settings
2. Click on configure store email settings link

**Expected behavior**
Should take you to either the store/server email settings config page

**Actual behavior**
Takes you to login page

**Screenshots/Links**
![image](https://user-images.githubusercontent.com/39231115/60564816-5c063080-9d1e-11e9-8508-f95550d5f547.png)

**Additional context**
It could instead take you to the server email settings page but that wouldn't work for 3P users. :/

**Comment by NicolasDorier** [comment]
in 1.0.3.124
