### ISSUE TITLE
Getting 404;not found 

### ISSUE THREAD

**Issue by coder-d** [btcpayserver/btcpayserver#907]
**Describe the problem/bug**
Getting Status Code: 404; Not Found while trying to visit btcpay.mysever.com

**Your environment**
* Version of BTCPay Server: Latest
* Deployment method: Manual
* Other relevant environment details:
I haven't installed Lightning Network Daemon and Ride The Lightning 
Apache settings :
<VirtualHost btcpay.myserver.com:443>
		ServerAdmin webmaster@localhost

		ServerName btcpay.myserver.com
		ErrorLog ${APACHE_LOG_DIR}/error.log
		CustomLog ${APACHE_LOG_DIR}/access.log combined
		ProxyPass "/"  "http://127.0.0.1:23000/“
		ProxyPassReverse / "http://127.0.0.1:23000/“
		ProxyPreserveHost On

**Logs (if applicable)**

This is the status for the btcpay server in linux
Starting payment request expiration watcher
 run.sh[3006]: info: Configuration:  Listening on http://127.0.0.1:23000
run.sh[3006]: info: PayServer:      0 pending payment requests being checked since last run
run.sh[3006]: info: Events:         BTC: New block
run.sh[3006]: info: Events:         BTC: New block

Basic logs can be found in Server Settings > Logs.

**To Reproduce**

**Expected behavior**

**Actual behavior**
Tell us what happens instead

**Screenshots/Links**
If applicable, add screenshots or links to help explain your problem.

**Additional context**

**Comment by Zaxounette** [comment]
Is your domain/subdomain behind cloudflare ? They wen't down yesterday and all the problems aren't fixed on their end yet. Lots of 404's, 403's, 502's running around because of them.

**Comment by coder-d** [comment]
> Is your domain/subdomain behind cloudflare ? They wen't down yesterday and all the problems aren't fixed on their end yet. Lots of 404's, 403's, 502's running around because of them.

No its not behind cloudflare.

**Comment by NicolasDorier** [comment]
@coder-d I never used apache so I can't really help you. Does it works if you host btcpay with `--bind 0.0.0.0:23000`  and browse directly to it without apache?

**Comment by coder-d** [comment]
Hey guys thanks for your responses.I solved the issue it was just a syntax error.
Had to remove the quotes from the following line
ProxyPass "/"  "http://127.0.0.1:23000/“
