### ISSUE TITLE
EMAIL Server not working with SSL

### ISSUE THREAD

**Issue by sun1423** [btcpayserver/btcpayserver#909]
BTCpay doesn't accept SSL SMTP server details to send emails to users. Though it works fine without SSL enabled ! 

**Your environment**
* Version of BTCPay Server: BTCPayServer v1.0.3.118
* Deployment method: Docker

**Logs (if applicable)**
No Logs generated

**To Reproduce**
1. Go to '...' Server Settings
2. Click on '....' Email Server
3. Put your SMTP server details with SSL enabled:
4.  error : When you save and send a test email, it gives error "Error: Syntax error, command unrecognized. The server response was:"

**Expected behavior**
It should accept SMTP SSL enabled account details and send a test mail 
**Actual behavior**
it gives error "Error: Syntax error, command unrecognized. The server response was:""

**Comment by pavlenex** [comment]
I'm unable to replicate. Set up with [configuration from here](https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#how-to-configure-smtp-settings-in-btcpay) and it worked.

**Comment by pavlenex** [comment]
Closing this as it's obviously an error on SMTP server, which btcpay has no control of.
