### ISSUE TITLE
Show store name in "From" field instead of email address

### ISSUE THREAD

**Issue by zerobias2019** [btcpayserver/btcpayserver#910]
At present time, when Mail Server sends an email message, in mail client I see "From" http://prntscr.com/oazekt field an email address from Server settings / Email server http://prntscr.com/oazdub

Will be good if I can choose how From field would look like, if , at least, fetch a current store name to put it there to make it look like:

The Store Name <email@address.com>

**Comment by NicolasDorier** [comment]
in 1.0.3.124
