### ISSUE TITLE
LTC: port is already allocated

### ISSUE THREAD

**Issue by whiteyhat** [btcpayserver/btcpayserver#914]
**Describe the problem/bug**
BTC + LTC (lightning) nodes can not work simultaneously on the same btcpay instance

**Your environment**
* Version of BTCPay Server: v1.0.3.94
* Deployment method: Lunanode

**Logs (if applicable)**
Basic logs can be found in Server Settings > Logs.
```
Recreating btcpayserver_lnd_litecoin ... error

ERROR: for btcpayserver_lnd_litecoin  Cannot start service lnd_litecoin: driver failed programming external connectivity on endpoint btcpayserver_lnd_litecoin (91916bc6ca15d6f83d74412e164dd74e2c2915d881b9abf4eec66d3a9f40365e): Bind for 0.0.0.0:9736 failed: port is already allocated

ERROR: for lnd_litecoin  Cannot start service lnd_litecoin: driver failed programming external connectivity on endpoint btcpayserver_lnd_litecoin (91916bc6ca15d6f83d74412e164dd74e2c2915d881b9abf4eec66d3a9f40365e): Bind for 0.0.0.0:9736 failed: port is already allocated
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Deploy with lunanode BTC+LTC (lightning)
2. Wait for sync
3. Only btc (lightning) works

**Expected behaviour**
Allocate a different port to use LTC (lightning)
**Actual behaviour**
BTC (lightning) uses the port 9736 and therefore LTC (lightning) can not use the same one.

**Screenshots/Links**
![Captura de pantalla 2019-07-11 a las 17 41 47](https://user-images.githubusercontent.com/31220861/61065107-4d490900-a403-11e9-88b1-fdbd7e016b3d.png)

**Comment by NicolasDorier** [comment]
@whiteyhat please find what is listening on port 9736, BTC is configured for 9735

**Comment by whiteyhat** [comment]
@NicolasDorier Apparently is not being used... I have restarted and upgraded my instance and btcpay version. Now when I call the daemon this is the output:

```
root@mainnet:~/btcpayserver-docker# sudo ./litecoin-lncli.sh
Error response from daemon: Container a7bf089b6f986add89f908ce449c971f65dda0cbe9c57a648488a2aef7b04947 is restarting, wait until the container is running
```

It does not seem to stop restarting.. And the LTC lightning node remains unavailable

**Comment by NicolasDorier** [comment]
which container is a7bf089b6f986add89f908ce449c971f65dda0cbe9c57a648488a2aef7b04947 ?

**Comment by NicolasDorier** [comment]
check thelogs of the container with docker logs

**Comment by whiteyhat** [comment]
I checked the logs of such container and the same logs are repeating over and over again:

```console
missing address manager namespace
alias=Satoshis.Games added to /data/lnd.conf
LND_CHAIN=ltc
LND_ENVIRONMENT=mainnet
Added litecoin.active and litecoin.mainnet to config file /data/lnd.conf
Waiting /root/.nbxplorer/ltc_fully_synched to be created...
The chain is fully synched
Waiting /var/lib/tor/hidden_services/lnd-ltc/hostname to be created by tor...
externalip=mcm5h4kpwsrpobkizqrzirclakor7ijo37kj7scnknjka3roxzkwdeyd.onion:9736 added to /data/lnd.conf
Attempting automatic RPC configuration to litecoind
Automatically obtained litecoind's RPC credentials
2019-07-13 15:45:30.400 [INF] LTND: Version: 0.7.0-beta commit=basedon-v0.7.0-beta-dirty, build=production, logging=default
2019-07-13 15:45:30.400 [INF] LTND: Active chain: Litecoin (network=mainnet)
2019-07-13 15:45:30.402 [INF] CHDB: Checking for schema update: latest_version=9, db_version=9
2019-07-13 15:45:30.507 [INF] LTND: Primary chain is set to: litecoin
2019-07-13 15:45:30.514 [INF] LTND: Initializing litecoind backed fee estimator
2019-07-13 15:45:30.515 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on tcp://litecoind:28332
2019-07-13 15:45:30.515 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on tcp://litecoind:28333
unable to create wallet controller: missing address manager namespace
unable to create chain control: missing address manager namespace
2019-07-13 15:45:30.517 [INF] LTND: Shutdown complete
```

**Comment by whiteyhat** [comment]
> which container is a7bf089b6f986add89f908ce449c971f65dda0cbe9c57a648488a2aef7b04947 ? lnd litecoin?

Yes, this is for lnd litecoin

**Comment by NicolasDorier** [comment]
This is a LND problem (https://github.com/lightningnetwork/lnd/issues/1780) if you have no money on lnd litecoin, I advise you to delete all data from your litecoin lnd instance.

**Comment by whiteyhat** [comment]
@NicolasDorier is there any specific `.sh` command for this case where I want to delete all data from the lite coin lnd instance and install it again?

**Comment by NicolasDorier** [comment]
```
btcpay-down.sh
rm -rf /var/lib/docker/volumes/generated_lnd_litecoin_datadir/_data
mkdir /var/lib/docker/volumes/generated_lnd_litecoin_datadir/_data
btcpay-up.sh
```

**Comment by whiteyhat** [comment]
Great! Thank you 🙏
