### ISSUE TITLE
Invoice "Node info" should use TOR address if invoice is viewed over TOR

### ISSUE THREAD

**Issue by readevalprint** [btcpayserver/btcpayserver#915]
Not sure which is the best repo to make this issue. 
Would it make sense if the NODE INFO should show the TOR hidden service settings if the invoice is also viewed over tor? 
Or maybe show both the hidden service and clearnet?

![image](https://user-images.githubusercontent.com/118430/60714343-f5566200-9f2b-11e9-838e-509ee033d83d.png)

**Comment by NicolasDorier** [comment]
Note that the invoice show the onion link only if the invoice has been created via an onion link.

**Comment by readevalprint** [comment]
Ok so with my current version (v1.0.3.117) as you described, invoices made over Tor always show the Tor info, if viewed over Tor or clearnet. And invoices made over the clearnet always show the clearnet info even if viewed over Tor. 

Because I am using the LND API (over clearnet) to create invoices in my backend, and may display it to a user over Tor and would expect them to see the too. But that is fine, I'll just include the invoice in the checkout page directly and not use the pop up.

**Comment by NicolasDorier** [comment]
@readevalprint please update to the latest `1.123` I saw that in certain situation I could reproduce the bug, this should be fixed now.
