### ISSUE TITLE
Test mode so we can test payment flows without actually paying with BTC or tBTC

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver#917]
I am testing BTCPay Server integration with Magento 2 and was wondering if I can put BTCPay Server in "test mode" where I don't actually have to pay with BTC on the payment page.

Some payment providers allow you to put your store in "test mode" and a few buttons will appear on the payment page:
- Simulate full payment
- Simulate partial payment (not common for traditional credit card payments, but might be useful for crypto)
- Simulate payment failed

If you click on "Simulate full payment", the payment is considered OK and you proceed to the next step.
The order steps can be similar, but depends on what the payment page should do.

This is only for integration testing.

Another idea that might be handy is that instead of putting the store in test mode, the payment request itself indicates that it is a test request so in automated testing or end-to-end testing situations, one does not need to keep enabling and disabling test mode all the time.

Or, there could be a "test user" who is always in test mode while the rest is in production mode.

Not sure if this is a feature request or something is already present.

**Comment by pavlenex** [comment]
Hey @woutersamaey are you familiar with testnet and regtest?
Basically, you can run environment variable `export NBITCOIN_NETWORK="testnet"`
It will launch your server on testnet network which will look like [this](https://testnet.demo.btcpayserver.org/).

1. Set testnet network.
2. Get a testnet wallet and get some testnet coins via faucets online.
3. Pay and test
Small info on Testnet can be found [here](https://docs.btcpayserver.org/btcpay-basics/tryitout).

Not completely sure that's what you're looking for.

**Comment by woutersamaey** [comment]
@pavlenex I am familiar, but:
- It requires running a second BTCPay Server instance (test and prod) on another server (can't use Docker for running 2 instances on the same machine)
- Testers will need tBTC. In a larger organisation, testers may not be educated, will run out of tBTC, will need to share passwords, lose access to test wallets, etc. Additional overhead.
- Automated testing is not possible.

**Comment by Kukks** [comment]
How about just using Lightning to pay? creating 1sat invoices on mainnet will not break the bank and are instant anyway :)

**Comment by woutersamaey** [comment]
@Kukks for this we need to have test products set up to cost just 1 sat or 0,01 USD. Also takes time to change the prices, again the wallet problem, etc.

**Comment by pavlenex** [comment]
When you put it in that perspective, I see why you need it, I usually use LN as Kukks said, or just mark invoices as completed manually. Will mark this as a feature request, if you wish to expand more on it feel free to do so.

**Comment by woutersamaey** [comment]
@pavlenex I am willing to work on this, but I'm not a C# dev. I have installed VS Code on my Mac and can read and understand the code (looks a bit like Java Spring MVC to me).
The main issue I will face is best practises and logic issues. If someone is willing to coach me a bit, I'm happy to do it.

**Comment by pavlenex** [comment]
@woutersamaey Awesome, we do have a #developers chat on Mattermost at chat.btcpayserver.org where I'm sure some of the devs will be more than happy to help you out when you have the time join us and let's keep improving this, also thanks for your contributions so far.

**Comment by woutersamaey** [comment]
If I'm correct, the following scenario's are possible. Can someone confirm or add?
I want to compile a list of all possible scenario's a merchant can encounter, so we can create test flows and have BTCPay Server simulate those at the push of a button. For each of these, there should be a button on the "test payment" page.

I'd suggest making a "test payment" page that looks like the real payment page, except that the QR 
 and address should be replaced with these buttons. A different color or alert message would also help explaining this is not a production page.

**Before expiration**
- Simulate full payment (100%)
- Simulate minor underpayment (99%)
- Simulate minor overpayment (101%)
- Simulate big underpayment (80%)
- Simulate big overpayment (120%)

**After expiration**
- Simulate full payment after expiration (100%)
- Simulate minor underpayment after expiration (99%)
- Simulate minor overpayment after expiration (101%)
- Simulate big underpayment after expiration (80%)
- Simulate big overpayment after expiration (120%)

**Non-payment**
- Simulate abandonment (user leaves the page)
- Simulate payment failed (what does this look like?)


Anything else you can think of that a merchant would want to have test flows for?
Some of these may seam a bit extreme, but serious merchants WILL ask for these in my experience.

**Comment by pavlenex** [comment]
@woutersamaey all of those situations look okay. Some indeed look a bit extreme. 

For
Non-payment

    * Simulate abandonment (user leaves the page) - invoice simply expires without being paid
    * Simulate payment failed (what does this look like?) - I think the term here for the invoice `invalid` but the status it triggers can be `failed`  

**Invalid**
Paid, but failed to receive a sufficient amount of confirmations within the time specified in-store settings
Check the transaction on a blockchain explorer, if it received sufficient confirmations, mark as complete

**Comment by royserpa** [comment]
> 
> 
> When you put it in that perspective, I see why you need it, I usually use LN as Kukks said, or just mark invoices as completed manually. Will mark this as a feature request, if you wish to expand more on it feel free to do so.

Is it possible to manually mark invoices as all possible variables? It's to debug and so on. If it can be done, how can I do it? Thanks!

**Comment by pavlenex** [comment]
@royserpa You can manually change **certain** states by clicking on a single invoice drop-down in Invoices > Status column.
![Screen Shot 2019-08-16 at 11 58 38](https://user-images.githubusercontent.com/36959754/63160126-4ffbd700-c01d-11e9-8c72-f288e9c22697.png)

**Comment by royserpa** [comment]
> 
> 
> @royserpa You can manually change **certain** states by clicking on a single invoice drop-down in Invoices > Status column.
> ![Screen Shot 2019-08-16 at 11 58 38](https://user-images.githubusercontent.com/36959754/63160126-4ffbd700-c01d-11e9-8c72-f288e9c22697.png)

You are right, I saw that. But I don't think it's possible to mark invoices as paid, confirmed, complete :/

**Comment by royserpa** [comment]
> 
> 
> > @royserpa You can manually change **certain** states by clicking on a single invoice drop-down in Invoices > Status column.
> > ![Screen Shot 2019-08-16 at 11 58 38](https://user-images.githubusercontent.com/36959754/63160126-4ffbd700-c01d-11e9-8c72-f288e9c22697.png)
> 
> You are right, I saw that. But I don't think it's possible to mark invoices as paid, confirmed, complete :/

Without sending any btc/tbtc or lightning btc :/

**Comment by pavlenex** [comment]
It is not possible without sending anything. That's I think what this issue is about. 

But payments flow is way better tested in regtest and dev environment where you don't have to spend anything.
