### ISSUE TITLE
Some URLs are CamelCased while most are lowercased

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver#921]
**Describe the problem/bug**
Some URLs are have Capitals while most URLs are all lowercase.
The app is case insensitive, so didn’t want to report this as a real issue. Would be prettier though.

After looking at the code, it seams the “route” is not set for the Capitalized controllers.

**Your environment**
* Version of BTCPay Server: latest
* Deployment method: docker

**Expected behavior**
All URLs should be lowercase and have "-" between words.

**Actual behavior**
Some URLs aren't pretty:
- /Account/Login
- /Account/Logout
- /Account/ForgotPassword
- /Account/Register
- /Manage/Index
- /Manage/ChangePassword
- /Manage/TwoFactorAuthentication
- /Manage/U2FAuthentication

**Comment by woutersamaey** [comment]
@NicolasDorier here it is.

**Comment by woutersamaey** [comment]
A solution seams already available, but I'm not experienced enough to implement.
Details are here: https://stackoverflow.com/questions/40334515/automatically-generate-lowercase-dashed-routes-in-asp-net-core/45777372#45777372

This will automatically slugify the URLs, meaning lowercase and only [a-z0-9\-]

**Comment by NicolasDorier** [comment]
@woutersamaey you only need to add say `[Route("login")]` on top of each action.

**Comment by bolatovumar** [comment]
@NicolasDorier you could do that but it would get rather tedious to do it everywhere. Seems like the method posted by @woutersamaey would be easier and solve the issue everywhere at once. Unfortunately it requires .NET Core v2.2.0 or later. Any change BTCPay could be upgraded to use .NET Core v2.2.0 or later (latest is v2.2.5)?

Link to MS documentation: https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-2.2#use-a-parameter-transformer-to-customize-token-replacement
Link to Github issue where this was implemented: https://github.com/aspnet/Routing/issues/186#issuecomment-421493328

**Comment by NicolasDorier** [comment]
@bolatovumar I don't think this is tedious. Those are the only links impacted, this is easy to review and our tests cover all.

We won't move to .net core 2.2 because .net core 3.0 will release in a few week.

**Comment by woutersamaey** [comment]
I'll try the "clean" solution once we are on 3.0.
@NicolasDorier is right this isn't that tedious, but you keep introducing "ugly" URLs as controllers are added and devs may forget to add the `[Route]` part.
There may also be more URLs that I've not listed or found yet.
Imho, URL generation should be handled by the app and not require boilerplate code. If we have clean URL generator, the `[Route]` parts can be removed.

**Comment by bolatovumar** [comment]
It would be fairly easy to "fix" this now by using the `Route` decorator or we can just wait for when .net core 3.0 is released

**Comment by bolatovumar** [comment]
I was thinking of resurrecting this issue and trying to implement this now since we have switched to .NET Core v3.1. I'm trying to do it the way MS has it in their [documentation](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1#use-a-parameter-transformer-to-customize-token-replacement) but it's not working for me. See my attempt here: https://github.com/bolatovumar/btcpayserver/commit/fa2563fada28f86d639a8b577380bb9424ba4b97

Anyone have an idea why this is not be working?

**Comment by NicolasDorier** [comment]
it seems correct to me. Do you reach the breakpoint?

**Comment by bolatovumar** [comment]
@NicolasDorier for some reason I can't set the breakpoint in that method as it tells me that the code is different from before I ran "Run with debugging". I'm not sure why that would be as I didn't change any code during the debugging process. This happens consistently for me. I can set breakpoints everywhere else just fine though. Any idea why that could be? Is there something special about the Startup class that doesn't allow for breakpoints to be set?

**Comment by NicolasDorier** [comment]
@bolatovumar it seems some kind of cache problem or something like that. Have you tried running `dotnet clean` and/or remove your `bin` and `obj` folder??

**Comment by bolatovumar** [comment]
@NicolasDorier will try

**Comment by bolatovumar** [comment]
@NicolasDorier alright, `dotnet clean` did the trick and it works now. 

My only concern here is that this will update all urls automatically and if someone has the old version of the url bookmarked or relies on it existing in some other way, it will 404 now (e.g. `ForgotPassword` is now `forgot-password` and the old url will 404).

Also, this will not automatically slugify urls for those which do not have a controller action of the same name associated with them (e.g., `/Server/Logs` url stays the same as there is no `Logs` controller action in `ServerController` class, same for `/Server/Users`). I guess separate controller actions should be created for these?

**Comment by NicolasDorier** [comment]
I think it is not a big deal to break the page url from before.

**Comment by NicolasDorier** [comment]
For /Server/Logs and /Server/Users I think the easiest is to use a `[Route("server/users")]` instead of the previous one.

**Comment by pavlenex** [comment]
@woutersamaey is this still something we want to address in the future or not?

**Comment by woutersamaey** [comment]
@pavlenex I think so for consistancy's sake. Maybe in .NET 6 there are new ways of doing this across the board @NicolasDorier ? Or should we aim to make a test that fails if a URL is not consistent?

**Comment by dennisreimann** [comment]
Yes, let's just clean it up pragmatically – no more Microsofty URLs 😄

**Comment by NicolasDorier** [comment]
A few more url to do
