### ISSUE TITLE
Setting minimum on chain amount disabled lightning above that amount

### ISSUE THREAD

**Issue by Sjors** [btcpayserver/btcpayserver#922]
**Describe the problem/bug**

If I configure a minimum amount for on chain payments:

<img width="596" alt="Schermafbeelding 2019-07-15 om 20 59 13" src="https://user-images.githubusercontent.com/10217/61241226-6b847100-a743-11e9-950e-418358798574.png">

Then the checkout page will no longer show Lightning for amounts above that.

**Your environment**
* Version of BTCPay Server: v1.0.3.124
* Deployment method: Ubuntu without Docker
* Other relevant environment details: 

**Logs (if applicable)**
<img width="774" alt="Schermafbeelding 2019-07-15 om 21 00 17" src="https://user-images.githubusercontent.com/10217/61241307-940c6b00-a743-11e9-8294-fac4753fb4af.png">
`"BTC (Off-Chain): The amount of the invoice is too high to be paid with lightning"`

**To Reproduce**

See above.

**Expected behavior**
I expect Lightning invoices for amount above the maximum on-chain amount. That's the job for the other option "Do not propose lightning payment if value of the invoice is above" .

**Additional context**
This looks incorrect: 

https://github.com/btcpayserver/btcpayserver/blob/01787e2662efb4eece7c0144bce9f9a0c19e3aa8/BTCPayServer/Payments/Lightning/LightningLikePaymentHandler.cs#L149-L169

**Comment by pavlenex** [comment]
This is a bug, I was able to replicate it, thanks for reporting it.
Pinging @NicolasDorier

**Comment by HugoDoyon** [comment]
See Pull Request #951
