### ISSUE TITLE
Pay with fiat, merchant receives bitcoin

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver#923]
Has anyone ever considered developing a fiat to bitcoin service? Not for trading or as an exchange, but only 1 way: fiat to bitcoin. Not bitcoin to fiat. Could even be reselling of bitcoin bought at an exchange at a minimal profit or break-even. If we had this, we could let BTCPay Server accept fiat, and pay the merchant in bitcoin.

Take this Tor crowdfunding for example, someone who wants to donate but doesn’t have crypto cannot participate. This would also hugely boost BTCPay Server adoption as it would become a fully functional payment gateway.

I know this isn’t something for BTCPay directly, but trying you guys out first. 

BTCPay would need some huge changes like:
- Integrate with an external payment option (fiat) as it should present the option
- Redirect to another URL where the fiat payment happens
- Receive payment feedback and proceed the usual way

This idea is also similar to a BTC ATM where fiat goes in and bitcoin comes out (only in my case the bitcoin goes to the merchant and not to the buyer).

**Comment by Zaxounette** [comment]
There are multiple legal implications in this.

For example, being in France, if BTCPay Server implements a Fiat to BTC gateway, I couldn't use it, as I have to have a 500k Euro money transmitter licence.
I'd have to move shop abroad, with all the implications behind it if I wish to continu to use BTCPay Server.
I imagine other countries (USA, I see you) would have similar red tape around that kind of thing.

For an odd reason, BTC to Fiat doesn't have that red tape at all. Go figure.

**Comment by bitcoinbrisbane** [comment]
I think we should discourage fiat where ever possible.

**Comment by woutersamaey** [comment]
@bitcoinbrisbane I'm looking for ways to increase adoption, so if people want to use fiat (for now), they should be able to.

**Comment by bitcoinbrisbane** [comment]
Nothing personal, just my opinions

**Comment by johnchisenhall** [comment]
I’m also searching for the same solution. Not a computer science person either so most current merchant solutions available are difficult for me to integrate.

**Comment by pavlenex** [comment]
Just a heads up, there are now a couple of third-party solutions that work for the Lightning Network.

- [Strike](https://twitter.com/JackMallers/status/1222968353544904704)
- [Escher](https://twitter.com/EscherApp/status/1230610165629673488)

I don't think they're worldwide, but there is some progress in this field and it seems it's not something we have to do on our end.

**Comment by pavlenex** [comment]
Alright, I'll go ahead and close this one, since it's obvious that there are projects out there working on implementing this kind of features for merchants, which is very exciting. 
Since for anything fiat, trusted-third-party is needed, it's best we leave this on providers like the above mentioned. Both Strike and Escher are still in infancy, but you can join their communities and help test/develop, for now this is not something we think we can develop on our end.

**Comment by maltfield** [comment]
Is there any update or some solution to do this?

I'd like to accept donations in fiat on my website, but most donation tools use paypal -- which never works for me (everyone who ever bought me a coffee on ko-fi had their donation returned to them after some days). I just want to make it easier for folks to donate bitcoins to me for my work on open source software, and there doesn't appear to be a solution out there, yet..

See also:

 * https://bitcoin.stackexchange.com/questions/41191/i-need-fiat-btc-merchant-service/101281

**Comment by Zaxounette** [comment]
Hi @maltfield !

Strike recently opened to the world instead of previously only the US.
They provide such a service.

This is not, AFAIK, a feature that will be implemented in BTCPay Server core code.
But once plugins are defined, refined and come to a workable state, i'm sure independent devs will provide a plugin for that inside BTCPay Server.

In the mean time, Strike is your solution.
Zax.

**Comment by maltfield** [comment]
Thanks for the fast response!

Unfortunately Strike doesn't look like a real solution. I can generate some "payment request" QR code for $3, but it's only valid for 60 seconds! Maybe this will change with time..

I also wouldn't trust Strike; it looks like they have no sense of security. For example, you can't lock your account with a password (let alone a secure 2FA like TOTP) -- It uses just an OTP from email (insecure) and sms (insecure) for auth :facepalm:

...Not to mention they require a phone number to use their service

**Comment by Zaxounette** [comment]
You might have misunderstood me, or I didn't properly convey the info:

IMO, Strike is the solution for your customers.
You provide the invoice page through BTCPay Server to your customers as usual, they pay with Strike, paying in fiat and you receive BTC.
