### ISSUE TITLE
Defer onchain invoice creation until user selects the option

### ISSUE THREAD

**Issue by Sjors** [btcpayserver/btcpayserver#924]
**Is your feature request related to a problem? Please describe.**
When Lightning payments are the default, BTCPay server still creates an onchain invoice immediately. This causes a Bitcoin address to be reserved, which can cause problems for wallets that don't scan ahead very far (e.g. BIP32 gap limit is 20, Bitcoin Core uses a keypool of 1000 at a time).

<img width="711" alt="Schermafbeelding 2019-07-15 om 22 07 12" src="https://user-images.githubusercontent.com/10217/61245496-eb630900-a74c-11e9-8e59-fd7b5fd3ebe1.png">

**Describe the solution you'd like**
Don't reserve the Bitcoin address until the user selects on-chain.

**Comment by NicolasDorier** [comment]
Yes, but sadly, we can't change it without breaking the API.
Consumer of the API expect to be able to fetch the address after a call to create Invoice.

**Comment by Sjors** [comment]
What do you mean by "after"? Is the address returned in the same call, or in a separate call? If the latter, then you could use just-in-time derivation, right?

**Comment by NicolasDorier** [comment]
@Sjors basically you have one `Create invoice` call, and this must return all data for paying in all the different different payment methods. I can't change this without breaking API and clients.

**Comment by NicolasDorier** [comment]
Though I think, we can do in the new, non backward compatible `GreenField` API that @Kukks is working on.

**Comment by pavlenex** [comment]
Done in #1843
