### ISSUE TITLE
Change spanish string

### ISSUE THREAD

**Issue by andres-pinilla** [btcpayserver/btcpayserver#93]
Hi,

Please change the word "Escaniar" for "Escanear".

[https://i.imgur.com/rbCVoou.png](url)

Thanks,

Andres

**Comment by NicolasDorier** [comment]
@marcosrdz @felipehuicochea ACK?

**Comment by marcosrdz** [comment]
This was fixed recently.

**Comment by andres-pinilla** [comment]
Hola @marcosrdz @felipehuicochea, hace sólo algunas horas instalé BTCPay y los errores en la traducción aún aparecen. Como puede actualizar BTCPay a la versión que tiene las líneas corregidas. Otro punto, el plugin de WooCommerce no tiene opción para que sea traducido.

@NicolasDorier 
Nicolas would be a good idea if BTCPay Server had an option where each user could easily customize their translation.

**Comment by marcosrdz** [comment]
@andres-pinilla

https://github.com/btcpayserver/btcpayserver/blob/ca4585eee92af833950ec746e62e126caf3f7247/BTCPayServer/wwwroot/js/checkout/langs/es.js

Ahí podrás ver las traducciones actuales. Lo mas probable tienes que hacer un git pull para actualizar ese file.

**Comment by NicolasDorier** [comment]
Ah yeah indeed I remember, closing this!

**Comment by andres-pinilla** [comment]
@marcosrdz Hola Marco, podrías regalarme el comando para actualizar BTCPay a la última versión, estoy corriendo el server bajo Docker. Gracias.
