### ISSUE TITLE
Timezone differences in the wallet

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#930]
**Describe the problem/bug**
When several people from different timezones access the wallet, which timezone is shown?
I think that for some reason my transaction history got messed up because a person with a different timezone sent out from the shared store wallet so that transaction is shown after certain transactions that happened a few hours earlier before it.

**Your environment**
* Version of BTCPay Server: v1.0.3.124
* Deployment method: Docker
* Other relevant environment details:

**To Reproduce**
1. Send the incoming transaction to your wallet in one timezone
2. Send the outgoing transaction to your wallet in the other timezone a few hours after
3. Check transaction history, transactions are not displayed chronologically

**Expected behavior**
Transactions should be sorted chronologically regardless of the timezone.

**Actual behavior**
Transactions are not be sorted chronologically.
**Screenshots/Links**
![2019-07-17_22-28-43](https://user-images.githubusercontent.com/36959754/61409635-f3ed4800-a8e2-11e9-89f6-0f20b711d7f6.png)

**Additional context**
I hate my life.

**Comment by NicolasDorier** [comment]
Transactions are sorted topologically. (if A depends on B, then A appear after B)
In case of topological tie, then unconfirmed appear first.
In case both are unconfirmed, the last seen appear first.

This mean that they can be out of order chronologically. But it means that you are sure that your balance, by replaying transactions from bottom to top, will never become negative.

**Comment by pavlenex** [comment]
Ah, yeah, okay that makes sense. Not sure how I never noticed this before, thanks for clarifying.

**Comment by NicolasDorier** [comment]
Also, did you used rescan on this wallet by any chance? If that's the case you don't see the "first seen date" by the block time date, which is higher.

**Comment by pavlenex** [comment]
Yes I've used wallet re-scan just to make sure all balance is there, def not an issue.

**Comment by NicolasDorier** [comment]
The rescan may have messed up the timestamp (though I think I tested that it does not), resetting the "first seen" to the time where it was mined instead of the time where it was seen.
