### ISSUE TITLE
Wallet Labels

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#932]
**Is your feature request related to a problem? Please describe.**
It would be great if we had wallet labels, that would allow easier management and filtering of transactions.

**Describe the solution you'd like**
For a start, a simple way to label transactions, very similar to GitHub labels. Adding advanced auto-filters and auto-labeling could be something for the future.

**Provide examples**
![walletlablels](https://user-images.githubusercontent.com/36959754/61545367-9fafa880-aa47-11e9-86a5-e16eea2e3be6.jpg)

This may be slighty related to #662

**Comment by Zaxounette** [comment]
Thought:

That those labels get pushed (or pulled) to and from the different CMS plugins as well.

**Comment by NicolasDorier** [comment]
@pavlenex how do we add the label? where is the button?

**Comment by pavlenex** [comment]
@NicolasDorier How about when there's no label, there's  `add label` in the same place of a label? Where you can already assign an already existing label or create a new one? But it may look a bit cluttered with that setup.

**Comment by pavlenex** [comment]
Also, will we be able to assign a label to multiple transactions, in which can we need some sort of multi-choice that will easily allow you to select a few transactions and assign the same label?

**Comment by pavlenex** [comment]
@NicolasDorier Let's actually do it the same way GitHub does.
![Screen Shot 2019-07-21 at 16 22 53](https://user-images.githubusercontent.com/36959754/61592465-cef32080-abd3-11e9-8b04-fcd0fb898b9c.png)
When you click
![Screen Shot 2019-07-21 at 16 22 43](https://user-images.githubusercontent.com/36959754/61592466-d61a2e80-abd3-11e9-99c8-2ea788f69f4c.png)

**Comment by NicolasDorier** [comment]
Good idea.

**Comment by NicolasDorier** [comment]
Closing, reopen if not happy
