### ISSUE TITLE
Getting a 400 on new register

### ISSUE THREAD

**Issue by bitcoinbrisbane** [btcpayserver/btcpayserver#933]
**Describe the problem/bug**
On a new install, when I click register and complete the form, the redirected page is a 400.  You can replicate at https://payments.bitcoinbrisbane.com.au/Account/Register

**Your environment**
* Latest, just did a pull
* Manual deploy

**To Reproduce**
https://payments.bitcoinbrisbane.com.au/Account/Register

1. Complete form
2. Click register

**Screenshots/Links**
https://payments.bitcoinbrisbane.com.au/Account/Register

**Comment by NicolasDorier** [comment]
You need to give me details on your setup. This is probably a problem from your manual install.

**Comment by NicolasDorier** [comment]
check the documented stuff nginx config on 

https://docs.btcpayserver.org/faq-and-common-issues/faq-deployment#btcpay-is-expecting-you-to-access-this-website-from

if you have your own nginx

**Comment by NicolasDorier** [comment]
Also check the clock on your server is not off.

**Comment by bitcoinbrisbane** [comment]
> 
> 
> You need to give me details on your setup. This is probably a problem from your manual install.

Ubuntu 18 VM.
BTC Pay is running as a service, behind NGinx reverse proxy with lets encrypt cert.
NBXplorer running on the same VM.
BTC Core on a different VM but has 8333 & 8332 connectivity.

Ill try debug locally in Rider this week.

**Comment by bitcoinbrisbane** [comment]
> 
> 
> Also check the clock on your server is not off.

Ok

**Comment by NicolasDorier** [comment]
@bitcoinbrisbane it comes from the AntiForgeryToken stuff, you can't debug it, but you can activate the logs.

**Comment by NicolasDorier** [comment]
btw we just merged this to the doc https://github.com/btcpayserver/btcpayserver-doc/pull/268 this will help you.

**Comment by bitcoinbrisbane** [comment]
> btcpayserver/btcpayserver-doc#268

As per the above, I need to change my Nginx config to this.  I commented out the lines I had in there and amended the bottom. Ill post here incase it helps someone else.

```
        location / {
                proxy_pass http://localhost:8080;
                #proxy_http_version 1.1;
                #proxy_set_header Upgrade $http_upgrade;
                #proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                #proxy_cache_bypass $http_upgrade;
                #proxy_set_header X-Forwarded-Port 443;
                #proxy_set_header X-Forwarded-Proto https;

                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
```

**Comment by NicolasDorier** [comment]
BTCPay only care about `X-Forwarded-For` and `X-Forwarded-Proto`
