### ISSUE TITLE
I'm not receiving any data while getting IPN notification.

### ISSUE THREAD

**Issue by lvtz** [btcpayserver/btcpayserver#934]
Notifications are sent properly but don't contain any data.

![image](https://user-images.githubusercontent.com/18595528/61585738-8b60ce00-ab63-11e9-9145-d3f2d1bc8c31.png)

 I'm saving my requests on my server and saw empty logs.

I noticed this issue while testing: 

- payment button
- pos

![image](https://user-images.githubusercontent.com/18595528/61585720-3de46100-ab63-11e9-8ae0-731b6d031e42.png)

Are you able to help me? I'm don't using any third-party plugins, it's my custom integration, but it seems basic feature is broken for me. Maybe I've missed something?

The server is hosted on LunaNode. Everything else works fine.

**Comment by NicolasDorier** [comment]
problem is probably with your code saving the empty logs.

**Comment by lvtz** [comment]
@NicolasDorier - Yes, you are right. I spent a little bit more time and tried to save data by:
`
$json = file_get_contents("php://input");
$data = json_decode($json, true);
`

Now everything works well.
