### ISSUE TITLE
Possibility to use custom HTML / JS on specific pages

### ISSUE THREAD

**Issue by lvtz** [btcpayserver/btcpayserver#936]
While I'm using BTCPay Server with docker, I'm can't figure out how can I edit specific pages. I would like to add some HTML, and JavaScripts, for example, Google Analytics. 

Is there any way, to inject some stuff, to specific pages?

**Comment by pavlenex** [comment]
@lvtz have you seen this https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#how-to-add-google-analytics-code-to-btcpay ?

**Comment by lvtz** [comment]
@pavlenex - yes, but I'm a little bit confused and really don't know how to get access to `~/wwwroot/` directory.

**Comment by Kukks** [comment]
If you've deployed via docker on Linux, the data dir for btcpay is `var/lb/docker/volumes/generated_btcpay_datadir/_data` however this does not contain the compiled files directory. 

Your best course of action is to enter the docker container while it is running and modifying it through there: ` docker exec -ti generated_btcpayserver_1 sh` although this is hacky and overall a bad choice.

The only real way to do this is by following https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#how-to-customize-my-btcpay-theme-style

**Comment by NicolasDorier** [comment]
I think custom JS on some page can be cool (like checkout/crowdfund) like we do for CSS. However, it should be only authorized to admins.
