### ISSUE TITLE
Make ASCII non-alphanumerical characters valid in a POS item description

### ISSUE THREAD

**Issue by Zaxounette** [btcpayserver/btcpayserver#938]
**_Describe the problem/bug_**
In the PoS app, when editing the text description of a shopping item, it seems the character inputs can only be alphanumerical.

**_Your environment_**
* _Version of BTCPay Server:_ V1.0.3.120
* _Deployment method:_ Lunanode

**_To Reproduce_**
_Steps to reproduce the behavior:_
1. Create a POS app
2. Edit a shopping item
3. Try to input any ASCII non-alphanumerical character (#&@%µ£$§...)
4. Submit changes and get thrown back to general POS app settings (error) instead of POS app list (success).

**_Additional context_**
I have not tested every ASCII non-alphanumerical character, but as an example, I wanted to put a hashtag (#) for a shopping item in the description.
Without the hashtag the submission goes thought, with it, it fails.

**Comment by bitcoinbrisbane** [comment]
Asp.net defends against some characters to stop cross script attacks. It’s most likely that the error is because of that.  Do you have an error message?

**Comment by Zaxounette** [comment]
> Asp.net defends against some characters to stop cross script attacks. It’s most likely that the error is because of that. Do you have an error message?

I might have to rewrite this PR.

1°) The error "Invalid template" appears in fact when I have a backspace in the description (to separate sentences, for instance).

2°) On the other hand, when inputting for example a hashtag + a word ( #example ), update goes through, BUT hashtag does not appear in the UI viewer side.
On top of that, if put in the middle of the description, the hashtag makes the following characters appear blank in the UI viewer side.

No error ever appears on this second part.

**Comment by bolatovumar** [comment]
@Zaxounette the issue seems to be specifically with # and & characters. If you input # character then nothing after this character shows up (so in #&@%µ£$§🤣 nothing will show up). If you input & character then you get &amp; (so &@%µ£$§🤣 --> &amp;@%µ£$§🤣). If you don't use any of these characters then it seems to be fine.

**Comment by bolatovumar** [comment]
@Zaxounette see this screenshot for a workaround:
![Screen Shot 2019-08-21 at 11 30 59 AM](https://user-images.githubusercontent.com/1934678/63415963-397fc200-c407-11e9-9676-bc2e5b887760.png)

If you surround the your product description with single or double quotes down in the "Template" section then it seems to display these characters correctly.

**Comment by bolatovumar** [comment]
@Zaxounette unfortunately the above workaround doesn't work if you just edit the description by clicking on the "Edit" button and then save as their is client-side character escaping that happens once you click "Save". I'm not sure if this client-side escaping is needed as there is backend escaping that must be happening. I hope someone else can confirm this.

**Comment by darnton** [comment]
The product title and description are HTML-escaped twice - once when the new product is submitted from the modal form and again when the product card is displayed in the list. If the product is edited and re-saved, the title and description are escaped again.

I think the answer for this is to define trusted and untrusted areas and escape once when crossing that boundary so that we can 1) prevent XSS, and 2) prevent double-escaping.

It's probably best to assume that data on the client (i.e. input data and Product instances) is untrusted and so escape the client when displaying them and escape on the server when the Product data is stored. Data going from the database to the client should be unescaped.

**Comment by pavlenex** [comment]
Still happening in  **v1.0.4.4.** 
To replicate:
1. Create point of sale app
2. Edit in item description "John's description".
3. Click `Save`
4. It appears it's okay, no errors now.
5. Preview, description not shown.

![Snag_a8b6bb2](https://user-images.githubusercontent.com/36959754/82159359-dfc10100-988d-11ea-8b59-c8cb5b7998cc.png)

![steve](https://user-images.githubusercontent.com/36959754/82159373-f404fe00-988d-11ea-9275-e6d8c24c5f90.PNG)

**Comment by bolatovumar** [comment]
@pavlenex seems to work for me. The only weird thing is that `&` gets converted to `&amp`.

![Screen Shot 2020-05-17 at 7 21 48 PM](https://user-images.githubusercontent.com/1934678/82168475-b2fff000-9873-11ea-9c7a-709a4879f08b.png)

**Comment by pavlenex** [comment]
@bolatovumar For some reason it works for me today as well. No idea how to replicate it, but indeed the `&amp` issue is still present.

**Comment by Eskyee** [comment]
while doing some testing and updates, to my standard btcpay install vm on a lunanode this weekend, I noticed this UTF-8 unknown environment variables. Warning!

 
<img width="1189" alt="Screenshot 2020-05-18 at 09 21 08" src="https://user-images.githubusercontent.com/30862925/82190684-4fb0a500-98e9-11ea-8e10-0b6e27652b32.png">


then I read here about the amp problem we have.
https://stackoverflow.com/questions/3493405/do-i-really-need-to-encode-as-amp

not sure if this is anything to do with this problem ?? @bolatovumar @pavlenex .
