### ISSUE TITLE
Show warning when disk is full - Sync appears to be going backwards

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver#940]
**Describe the problem/bug**
When the disk is full, the sync runs forever and the progress bar goes back.
When the disk has become full, some data is lost and the progress bar is set back.
Show warning when disk is full.

**Your environment**
* Version of BTCPay Server: Latest version
* Deployment method: Docker

**To Reproduce**
1. Setup on a server with not enough disk space.
2. Let sync run.
3. Refresh after some time, sync will still be running, but progress bar has gone back a few %

**Expected behavior**
Warn me when disk is full.
Some idea of how much GB is needed would be a nice bonus, since resizing a disk is not something you wanna do every day.

**Actual behavior**
No error, just keeps syncing endlessly

**Comment by NicolasDorier** [comment]
Note that `btcpay-update.sh` clean up old image automatically since recently.

**Comment by woutersamaey** [comment]
That's good, but in my case the VM was simply way too small (by mistake). Deletion of old images would never have sufficed.

**Comment by woutersamaey** [comment]
@NicolasDorier maybe we can use a basic monitoring package / solution which we can implement into BTCPay Server? This way not only the disk space can be monitored, but maybe some other stuff.

I'm not so familiar with .NET and C#, so just proposing as a general idea. Maybe you know of something that would fit instead of building from scratch?

If such a thing doesn't exist, I still believe we should monitor disk space at the very least.

**Comment by Kukks** [comment]
We can add an optional service to the docker repo for a Linux stats dashboard web monitor. I have seen some nice, free ones around

**Comment by woutersamaey** [comment]
I don’t mind for a full logging / stats UI, but we should at least have some critical alerts visible in BTCPay Server itself, like this out of disk space issue. 
Having a separate container would mean separate configuration (like SMTP) and a separate interface to keep your eye on.

**Comment by woutersamaey** [comment]
Now that there are notifications in BTCPay Server, maybe we can add a "disk is (almost) full" alert there?

**Comment by pavlenex** [comment]
Sure, seems like a good idea if someone wants to code it, however unsure If most users will create an account before their instance is synced and ready, though I assume they might.

**Comment by woutersamaey** [comment]
OK, I will look into coding it.

**Comment by Zaxounette** [comment]
> Sure, seems like a good idea if someone wants to code it, however unsure If most users will create an account before their instance is synced and ready, though I assume they might.

Pretty sure they would, unless they want their instance to be hijacked.

**Comment by pavlenex** [comment]
@woutersamaey is this really something we'd want to add? I really don't recall anyone really requesting this one.

**Comment by woutersamaey** [comment]
@pavlenex I still believe this would be a worthy improvement, but I don't really know where to start with this one. Some help would be very welcome.

**Comment by woutersamaey** [comment]
@pavlenex Honestly I think adding a more encompassing 360 degrees monitoring tool to the docker deployment would make more sense than just watching for disk space alone, but then also I don't have any specific tool in mind as this is not really my area of expertise.
I think we can close this issue and consider again when a better idea comes up.
