### ISSUE TITLE
Crowdfunding request: Contribution confirmation e-mail for supporter

### ISSUE THREAD

**Issue by jooray** [btcpayserver/btcpayserver#942]
**Is your feature request related to a problem? Please describe.**
After starting my campaign, the contributors said that they did not receive any e-mail confirmation of payment and/or perk. They are used to receiving at least some confirmation e-mail. 

**Describe the solution you'd like**
I think even a plain text e-mail (to the customer's refund address, since this is the only contact we have without integrating with WooCommerce) saying that the contribution was successful would be useful.

**Describe alternatives you've considered**
I am e-mailing them manually once a day. @pavlenex suggested to use btcTransmuter, which I'll try as well, but I think this is a really basic feature with two input boxes in the Crowdfunding settings with a Subject and Body of the e-mail is enough.

**Comment by pavlenex** [comment]
@jooray I've noticed in your campaign that you now have this, care to elaborate on how you configured it? It would be great if we can document it somehow.

**Comment by jooray** [comment]
I didn't solve it yet, still doing the "add to mailing list manually and then fire it to the new cohort". But some more documentation about the crowdfunding portal is a good idea.

**Comment by Kukks** [comment]
For our BTCPay Day, we needed to create a way for users to buy tickets and receive it via email after confirmation. We set up the BTC Transmuter as follows:
 
![image](https://user-images.githubusercontent.com/1818366/64261834-71215a80-cf2d-11e9-98fb-04523158be2b.png)

![image](https://user-images.githubusercontent.com/1818366/64261953-a5951680-cf2d-11e9-8999-49c0d04a9a66.png)
