### ISSUE TITLE
Saving Block Data to LunaNode Attached Volume

### ISSUE THREAD

**Issue by ec4hunnid** [btcpayserver/btcpayserver#943]
After attaching 100GB volume to lunanode VPS and deploying BTCPayServer via Docker unable to save Block Data to attached volume resulting in server quickly running out of storage. 

**The following variables were used.** 
export BTCPAY_HOST=test.payserverjjgh.co
export NBITCOIN_NETWORK="mainnet"
export BTCPAYGEN_CRYPTO1="btc"
export BTCPAYGEN_REVERSEPROXY="nginx"
export BTCPAYGEN_LIGHTNING="clightning"
export BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-save-storage-s"
. ./btcpay-setup.sh -i

**Tried methods of attaching Volume and directing Docker to use Volume.** 

sudo mkfs.ext4 /dev/vdc
sudo mkdir /mnt/vdc
echo UUID=fdb6e3ff-98e2-42bb-89bb-cd89c5b6b0a3 /mnt/vdc ext4 defaults,nofail 0 | sudo tee -a /etc/fstab
sudo mkdir /mnt/vdc/docker
sudo ln -s /mnt/vdc/docker /var/lib/docker

~~~~~~~~~~~~~~

mkfs.ext4 /dev/vdc
mkdir /mnt/dockervolume
mount /dev/vdc /mnt/dockervolume
echo "/dev/vdc        /mnt/dockervolume        ext4   defaults        0 0" >> /etc/fstab


**After trying these the result can be seen below**

udev            481M     0  481M   0% /dev
tmpfs            99M  1.5M   98M   2% /run
/dev/vda1        20G   12G  8.2G  58% /
tmpfs           493M     0  493M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           493M     0  493M   0% /sys/fs/cgroup
/dev/vda15      105M  3.6M  101M   4% /boot/efi
tmpfs            99M     0   99M   0% /run/user/1000
/dev/vdc         98G   61M   93G   1% /mnt/dockervolume


**Additional Information**

Yes the volume is verified and identified by VDC on the server.
Yes the volume is attached to the lunanode VPS.
Yes the UDID is correct for the VDC volume

**Comment by pavlenex** [comment]
@ec4hunnid Were you able to figure this one?

**Comment by ec4hunnid** [comment]
@pavlenex No still not able to figure this out
