### ISSUE TITLE
Lightning shows enabled in the UI, confusing users that aren't admins.

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#944]
**Describe the problem/bug**
Currently, if you're not a server admin, in Store Settings LND shows as enabled confusing users.

**Your environment**
* Version of BTCPay Server: v1.0.3.124
* Deployment method: Docker
* Other relevant environment details:

**To Reproduce**
1. Register as a non-admin.
2. Go to store settings
3. Scroll to derivation scheme
4. See the error where Lightning is shown as enabled

**Expected behavior**
It should show as disabled or even better communicated to the user that Lightning is only available if they're server admin.

**Screenshots/Links**
![Screen Shot 2019-07-26 at 13 59 07](https://user-images.githubusercontent.com/36959754/61950502-51058f80-afae-11e9-8381-3b36408d91d4.png)

**Additional context**
![lnerror](https://user-images.githubusercontent.com/36959754/61950628-c40f0600-afae-11e9-88a0-18b8ccfaf056.jpg)

**Comment by NicolasDorier** [comment]
@pavlenex no, this allow users who have a LN node hosted by themselves to plug it to their btcpay account.

**Comment by pavlenex** [comment]
It's a bad UX, it should show as "X" like it normally does then you enable it, showing it as `enabled` when it fact it is not poor UX and confusing as you can see in the above message.

**Comment by NicolasDorier** [comment]
ah I see what you mean now.

**Comment by radWorx** [comment]
> It's a bad UX, it should show as "X" like it normally does then you enable it, showing it as `enabled` when it fact it is not poor UX and confusing as you can see in the above message.

@pavlenex @NicolasDorier 
The AddLightningNode.cshtml needs to change as well. Admins and non-admins have the same view. Non-Admins need a view with instructions on how to connect to their own lightning node.

**Comment by radWorx** [comment]
Non-Admin UpdateStore view.

![nonAdminLightning](https://user-images.githubusercontent.com/27673545/62262466-d510aa80-b3e6-11e9-9865-f8ea3a573d2a.PNG)

**Comment by radWorx** [comment]
All users AddLightningNode view: to @pavlenex point

![InternalLightningNode](https://user-images.githubusercontent.com/27673545/62262682-992a1500-b3e7-11e9-9961-baaa5eb7d795.PNG)

**Comment by radWorx** [comment]
this? for non-admins
![NoInternalLightningNode](https://user-images.githubusercontent.com/27673545/62263171-3d608b80-b3e9-11e9-8174-81ab53c14df1.PNG)

**Comment by NicolasDorier** [comment]
Fixed by https://github.com/btcpayserver/btcpayserver/commit/42d7ad02b0329b909aad9a02165493d470f5502a

Non admin can use lightning, just not the internal node.
