### ISSUE TITLE
DASH support when deploying to Azure

### ISSUE THREAD

**Issue by andrasfuchs** [btcpayserver/btcpayserver#945]
**Is your feature request related to a problem? Please describe.**
When I tried to deploy BTCPayServer to Azure, there were no option to enable [DASH](https://www.dash.org/), although BTCPayServer supports it.

**Describe the solution you'd like**
I would like to have an option to accept DASH when I deploy BTCPayServer to Azure.

**Describe alternatives you've considered**
I tried to use the Docker deployment locally on a Hyper-V virtual machine, and I succeeded and the DASH blockchain synced successfully. I wish I could do the same on Azure.

**Provide examples**
I'm not sure if it helps, but when I used the Docker deployment, I needed to change the configuration with this line `export BTCPAYGEN_CRYPTO1="dash"` before I executed `. ./btcpay-setup.sh -i` to finish the installation.

**Additional context**
These are the options now available in Azure:
![image](https://user-images.githubusercontent.com/910321/62078921-f4280480-b24d-11e9-9294-3e6ed4c30846.png)

**Comment by Kukks** [comment]
Open a pull request at https://github.com/btcpayserver/btcpayserver-azure/blob/master/azuredeploy.json and add `dash` to the available options.

**Comment by andrasfuchs** [comment]
Done ;)

**Comment by pavlenex** [comment]
Added [here](https://github.com/btcpayserver/btcpayserver-azure/pull/4).
