### ISSUE TITLE
Setting "Do not propose lightning payment if value of the invoice is above..." have no effect

### ISSUE THREAD

**Issue by HugoDoyon** [btcpayserver/btcpayserver#949]
**Describe the problem/bug**
In manage store > Checkout experience, setting a value to the field _"Do not propose lightning payment if value of the invoice is above..."_ have no effect on the lightning network payment method type in the POS apps

**Your environment**
* Version of BTCPay Server: v1.0.3.124
* Deployment method: Prod on the cloud and regtest local debug
* Other relevant environment details: Debian 9

**To Reproduce**
1. Go to 'manage store > Checkout experience'
2. Set 100.00 USD in the "Do not propose lightning payment if value of the invoice is above..." field
3. Click on 'Save'
4. Create a store and a pos apps
5. Create a product in the store of value 120.00$
6. Save POS App settings
7. Click "View" POS App
8. Click on the POS product of value 120.00$ 
9. Lightning Network Payment method will still be visible.

**Expected behavior**
In the scenario describe above, Lightning Network Payment method should not be visible.

**Actual behavior**
Lightning Network Payment method still visible

**Screenshots/Links**
![Annotation 2019-07-30 190446](https://user-images.githubusercontent.com/17368121/62171469-001ecf80-b2fd-11e9-9b05-32c14c82da95.jpg)

**Additional context**
LightningMaxValue field of the store settings have not been use in InvoiceController.cs. The logic does not seem to have been implemented yet.

**Comment by pavlenex** [comment]
Related #922

**Comment by NicolasDorier** [comment]
Bug caused by 90852fe9 @Kukks

**Comment by pavlenex** [comment]
@NicolasDorier I've just tested this upon the report of @HugoDoyon and we were both able to confirm the issue is still there even with [717cadc](https://github.com/btcpayserver/btcpayserver/commit/717cadc64b596a83761304686ca5e9a138255fc2) 

To replicate:
1. Do not propose lightning payment - Enter 100 USD
2. Create an invoice for 150 USD
3. Lightning is still proposed.

**Comment by HugoDoyon** [comment]
Will take care of it thank you!

**Comment by NicolasDorier** [comment]
@pavlenex  can you try on master please? I normally fixed it the commit after 717cadc

**Comment by pavlenex** [comment]
I did try it on the master, and it didn't work for me. The issue is still there. @NicolasDorier you can't replicate?

**Comment by pavlenex** [comment]
Could really be somehow related to #922

**Comment by HugoDoyon** [comment]
Yes, I will fix both issues at the same time

**Comment by HugoDoyon** [comment]
See Pull Request #951
