### ISSUE TITLE
Custom Key Derivation Paths

### ISSUE THREAD

**Issue by dannybitgo** [btcpayserver/btcpayserver#950]
I'm not sure if this is a problem or a feature request, but here is my issue: I have a 2-of-3 multisig wallet that I'd like to connect to my BTCPayServer. The derivation paths that my wallet uses are, for example:

m/0/0/0/0
m/0/0/0/1
m/0/0/0/2
m/0/0/0/3
... etc

However, it seems that BTCPayServer assumes that you use the key paths:
m/0/0
m/0/1
m/0/2
m/0/3
... etc

Is there a way to customize my BTCPay settings so that I can use the derivation path that my wallet uses? 

I tried hacking around this by manually deriving the path m/0/0 for each of my 3 xpubs, then inputting those as the keys, but then it was generating different addresses than I expected to see.

Any suggestions would be greatly appreciated

**Comment by NicolasDorier** [comment]
`I tried hacking around this by manually deriving the path m/0/0 for each of my 3 xpubs`

This is the right way to do. I guess the problem is the public key ordering, btcpay assume that the keys are ordered to protect privacy of signers. If it is not the case, add `-[keeporder]` to your derivation scheme

**Comment by dannybitgo** [comment]
> `I tried hacking around this by manually deriving the path m/0/0 for each of my 3 xpubs`
> 
> This is the right way to do. I guess the problem is the public key ordering, btcpay assume that the keys are ordered to protect privacy of signers. If it is not the case, add `-[keeporder]` to your derivation scheme

Awesome, that worked, thank you! Just curious, what is the order that BTCPay puts the public keys by default?

**Comment by NicolasDorier** [comment]
@dannybitgo by default it order the pubkeys in alphabetical order.
