### ISSUE TITLE
Not a valid domain name

### ISSUE THREAD

**Issue by realSConway** [btcpayserver/btcpayserver#958]
Hello experts,
Hope you can help me with setting up BTCpay-server at home.

Following Raspberry Pi deployment guide, I plan to only use this at home within my home network.

My end goal is to have a simple web-page where users can 'donate' BTC to.

I execute following commands.

    localhost:~/btcpayserver/btcpayserver-docker # export BTCPAY_HOST="localhost"
    localhost:~/btcpayserver/btcpayserver-docker # export NBITCOIN_NETWORK="mainnet"
    localhost:~/btcpayserver/btcpayserver-docker # export BTCPAYGEN_CRYPTO1="btc"
    localhost:~/btcpayserver/btcpayserver-docker # export BTCPAYGEN_REVERSEPROXY="nginx"
    localhost:~/btcpayserver/btcpayserver-docker # export BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-save-storage-xs;opt-save-memory"
    localhost:~/btcpayserver/btcpayserver-docker # . ./btcpay-setup.sh -i
    BTCPAYGEN_REVERSEPROXY is set to nginx, so BTCPAY_HOST must be a domain name which point to this server, but the current value of BTCPAY_HOST ('localhost') is not a valid domain name.

Secondly, I already have a fully synced BTC node running EPS, I would like to use this node as the node that  BTCpay-server connects to. Is this possible?

**Comment by pavlenex** [comment]
You need a domain name with DNS that points to the IP of your machine. The error message is pretty self-explanatory.
`BTCPAYGEN_REVERSEPROXY is set to nginx, so BTCPAY_HOST must be a domain name which point to this server, but the current value of BTCPAY_HOST ('localhost') is not a valid domain name.`

>  I already have a fully synced BTC node running EPS, I would like to use this node as the node that BTCpay-server connects to
In theory yes, but there are no guides and you'll have to do a lot of thinking yourself, best is to already use what btcpay provides out of box and save time.

**Comment by realSConway** [comment]
So not possible for localhost?
I only need this for my home network subnet 192.168.1.0\24, I'd prefer not to register with DNS.

**Comment by pavlenex** [comment]
Pinging @wiz, I think he has some docs or guides on it.
I think it's `BTCPAY_HOST=btcpay.local`
There's also an [entire channel on](https://chat.btcpayserver.org/btcpayserver/channels/raspberry-pi) our Mattermost [chat.btcpayserver.org ](https://chat.btcpayserver.org/)dedicated to RPI setups.

**Comment by realSConway** [comment]
Oh, thanks for that link, i will check it out.

**Comment by realSConway** [comment]
> I think it's `BTCPAY_HOST=btcpay.local`

CORRECTION: export BTCPAY_HOST=raspberrypi.local

**Comment by normandmickey** [comment]
FYI: btcpay.local would work if you set the hostname of your Pi to "btcpay" instead of "raspberrypi".  
sudo raspi-config
Select Network Options then N1 Hostname

**Comment by wiz** [comment]
Right, if you're only planning to use the Raspberry Pi on your LAN, and don't need it accessible from the internet, you can `export BTCPAY_HOST=raspberrypi.local` or whatever hostname your RPI is set to, and BTCPay will be accessible on the LAN at https://raspberrypi.local/ - of course since it's using a self-signed SSL certificate, you will get a security warning dialog in your browser.
