### ISSUE TITLE
Browser Titlebar customization for BTCPay invoice screen

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#96]
We now have CSS customization, which is awesome! 

Is it possible to also allow for custom <title> and possibly a custom favicon for further branding and customization?

**Comment by rockstardev** [comment]
I got you @astupidmoose ;)

Added title customization in #154

**Comment by astupidmoose** [comment]
Any chance for a custom favicon? :)

Not a big deal, but a nice bonus if possible :P 

Trying to make customers feel like they never left the site
