### ISSUE TITLE
Allow receiving funds on BTCPay Wallet

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#965]
**Is your feature request related to a problem? Please describe.**
BTCPay is a very feature-rich wallet. However, there is no way outside of generating invoices(through apps or manuall) to be able to get an address to send bitcoin to directly.

**Describe the solution you'd like**
Add a new section to the wallet UI: "Receiving"
Here, you can click a button "Generate new address" which would reserve a new address to send bitcoin to and display it on screen with a QR code. Optionally, you should also be able to pre-assign labels to this receiving address so that once funds are received, the wallets shows the label.

**Describe alternatives you've considered**
Create an invoice manually or through an app. This has the drawback that the invoice shows a specific amount and an unnecessary UI for something you want quick. 

**Provide examples**
Transferring some bitcoin from an exchange to your cold-storage wallet linked to your btcpay store. Just generate a receiving address and attach a label "funds bought from binance exchange after receiving August salary "

**Comment by pavlenex** [comment]
I'd like to see this as well, a bit tired of having to create invoices anytime I do something outside btcpay itself.

**Comment by smallswan399** [comment]
Is this way that allow create invoices that not specified Amount? And the checkout window not show amount and countdown as well. People sometime don't want to specify amount when he create a deposit request, just a destination address

**Comment by Kukks** [comment]
> Is this way that allow create invoices that not specified Amount? And the checkout window not show amount and countdown as well. People sometime don't want to specify amount when he creating a deposit request, just a destination address

No, this is for the internal wallet but we can build on it later that use case :)

**Comment by woutersamaey** [comment]
Can this be done using command line?

**Comment by Kukks** [comment]
As long as we have the xpub, we can generate addresses on demand without the HW. Command line: no, we dont have an API for this

**Comment by NicolasDorier** [comment]
@Kukks I think a simple sollution is just to have a button "Generate a new address" which reserve an address and show it. That's it.

**Comment by Kukks** [comment]
https://github.com/btcpayserver/btcpayserver/pull/1065
