### ISSUE TITLE
Btcpayserver instance sends 2 emails after invoice is set as expired, paid or confirmed/complete

### ISSUE THREAD

**Issue by royserpa** [btcpayserver/btcpayserver#968]
I'm using btcpayserver on my site and I see that it currently sends 2 emails when an invoice is set as expired, paid or confirmed/complete.

When an invoice is set as new, it only sends 1 email.

I understand that maybe an email address won't receive an email at times, but sending 2 emails within the same second is kinda exaggerating imho.

Here are some pics:

https://i.imgur.com/7RffT1z.png
https://i.imgur.com/GYpdlf8.png

**Comment by pavlenex** [comment]
Possibliy related #785

**Comment by conscott** [comment]
Still an issue. Following here.

**Comment by royserpa** [comment]
Hey guys, any update on this? Also, are email notifications still a thing? Can't find how or where to enter my email to receive notifications.

**Comment by Kukks** [comment]
They are still there, we just don't expose it as an option with the apps built into BTCPay. You can still specify it when creating an invoice through the UI or API

**Comment by royserpa** [comment]
Is there any documentation on that, man? I've been reading the docs but can't find anything about it.
