### ISSUE TITLE
404 error in search a solution of a bug

### ISSUE THREAD

**Issue by didiandalucia** [btcpayserver/btcpayserver#969]
Troubleshooting an issue brings on a link for read about solutions a new bug:

404 thats not the page your are looking for!

Link on btcpay-Docs - Troubleshooting an issue - Finding a solution your self - BTCPayFAQ linked to 

https://github.com/btcpayserver/btcpayserver-doc/tree/2eb9c96806adec55dd32c61b54c01307dab1e05f/FAQ.md

So, please correct the link and send my the correct URL for the FAQs where I can find a solution about my problem!

An other questions is: Exists user they use BTCPAY in production? I found only problems!

**Comment by pavlenex** [comment]
Wrong repo. If your question is about docs, open it in [docs repository](https://github.com/btcpayserver/btcpayserver-doc).
The FAQ you're referring to can be found on the [docs page.](https://docs.btcpayserver.org/faq-and-common-issues/faq)
