### ISSUE TITLE
Allow getting a next unused address via API

### ISSUE THREAD

**Issue by alexk111** [btcpayserver/btcpayserver#974]
**Is your feature request related to a problem? Please describe.**
Accepting donations via the invoice screen is overcomplicated. There is no reason to show the amount with the expiration countdown timer. The timer is irrelevant for Bitcoin donations, and the amount can be entered in the wallet a user is going to send BTC from.

**Describe the solution you'd like**
Add API endpoint to get a next unused address by btcpay wallet id. This will enable showing BTC addresses and/or QR codes.

**Describe alternatives you've considered**
Could not find any alternatives in btcpay. Showing invoices on Donate button click was the only way I considered.

**Comment by alexk111** [comment]
Probably related #965. This API endpoint will also enable generating new addresses on the wallet ui.

**Comment by NicolasDorier** [comment]
I think a good idea would be to have a new app type which just give links to a reserved address, and rotate it when the address is actually used.

The links should be: svg/png for QR code, or plain text/QR via iframe to people can easily embed in their website.

**Comment by alexk111** [comment]
@NicolasDorier An app type giving links and QR codes would be awesome!

**Comment by alexk111** [comment]
The address should be rotated on each request, to not show the same address to different persons. If changing after its use, then attackers would be able to gather info the same way as when reusing one address. 

If it will be rotated on each request by IFrame on a page receiving tons of pageviews, then it may produce gap limit issues. Caching an address in LocalStorage and reusing it for the same user might reduce the address index growth.

**Comment by alexk111** [comment]
Click Donate button at the bottom of https://debitpay.directory/anti-bitcoin/ to see what I tried to achieve.
@pavlenex I made a standalone library for this: https://github.com/alexk111/One-Time-Address/ - hopefully this might somehow be useful for improving the API.

**Comment by NicolasDorier** [comment]
linking to https://github.com/btcpayserver/btcpayserver/issues/1320

**Comment by pavlenex** [comment]
Closing as this is now linked to 1320 and will be looked into there.
