### ISSUE TITLE
Xero Integration

### ISSUE THREAD

**Issue by bitcoinbrisbane** [btcpayserver/btcpayserver#983]
Allow BTC Pay server to push invoices into Xero.

- As a business owner,
When I create an invoice in BTC pay server, I want to see it added to Xero,
So that I don't have to double enter my information

- As a business owner,
When I create an invoice is paid by crypto via BTC pay server, I want to see it marked as paid in Xero,
So that I don't have to double enter my information

**Comment by Kukks** [comment]
I think this would make more sense as a separate plugin to BTCPay like the quickbooks plugin in the docker repo

**Comment by astupidmoose** [comment]
Does Xero have BTC in their accounting software? Last time I checked, which was recently it was not an option.

**Comment by bolatovumar** [comment]
@astupidmoose doesn't look like they do.

See here: https://community.xero.com/business/discussion/305641
But looks like people are using it with some other tools to make it work: https://medium.com/cryptfolio/tracking-cryptocurrency-payments-in-xero-5d0018056dca

**Comment by bitcoinbrisbane** [comment]
> Does Xero have BTC in their accounting software? Last time I checked, which was recently it was not an option.

Could be via FIAT?
