### ISSUE TITLE
Feature request - Add cryptocurrency prices together with fiat in Woocommerce

### ISSUE THREAD

**Issue by bitcoinshirt** [btcpayserver/btcpayserver#99]
I like the ability of some payment processors which are able to show the price in BTC/LTC or any other crypto merchant decides to accept.

It looks great and gives clarity that the seller accepts crypto.
![screenshot from 2018-04-02 18-55-32](https://user-images.githubusercontent.com/36959754/38205888-d6494308-3697-11e8-85b7-a8431c3f4e50.png)

**Comment by andres-pinilla** [comment]
+1

**Comment by bitcoinshirt** [comment]
@astupidmoose I remember you had some workaround or a separate plugin for this? Is this even something that can be done inside BTCPay plugin or should I close an issue? If you have a workaround maybe you can post it.

**Comment by bitcoinshirt** [comment]
Thank you @astupidmoose I'll close the issue now that there is a workaround.
