### ISSUE TITLE
Copy tab broken on checkout page

### ISSUE THREAD

**Issue by conscott** [btcpayserver/btcpayserver#994]
**Describe the problem/bug**
After #992 the "Copy" tab does not work on the checkout page. 

**Your environment**
Ubuntu 16.04
Chrome Chromium 76.0.3809.87
Manual Deployment on master 43ee22f965ecf50f0c080c96492ed9846b51fe05

**To Reproduce**
Create PoS invoice and try to click on the "Copy" tab to get address instead of QR code

**Expected behavior**
The Copy tab will be active and show this div containing the deposit address

**Actual behavior**
Nothing happens on click

**Additional context**
Copying the the old version of https://github.com/btcpayserver/btcpayserver/blob/dcaf0463a7da06b7cda836695f1cdc277d57b82a/BTCPayServer/wwwroot/checkout/js/core.js seems to fix the issue, so it seems to be a refactoring error.

**Comment by Kukks** [comment]
Thanks for reporting!, I'm in the middle of replacing all the legacy jquery with Vuejs to have a more consistent codebase
