### ISSUE TITLE
Payment request - modal (qrcode) window stays in non paid state after successful payment

### ISSUE THREAD

**Issue by rvrv** [btcpayserver/btcpayserver#998]
**Describe the problem/bug**
Payment request View - after successful LN invoice payment modal window with qrcode and countdown should changed to payed state, but it did not.

**Your environment**
BTCPayServer v1.0.3.127

**To Reproduce**
1. Create new payment request
2. Go to View payment request
3. Click 'Pay Now'
4. Pay LN invoice

**Expected behavior**
After successful payment modal window should change to 'Payed' state and close button should appear.

**Actual behavior**
Modal window stays in non paid state. JS console throws error:

Uncaught TypeError: this.fetchData is not a function
    at WebSocket.socket.onmessage

**Screenshots/Links**

<img width="1666" alt="error" src="https://user-images.githubusercontent.com/1556257/63807792-bdadda00-c91e-11e9-9ed9-9c475ca72061.png">

**Comment by NicolasDorier** [comment]
@Kukks maybe came from your refactoring?

**Comment by Kukks** [comment]
Yes fix is in #997
